---

pipeline:
  name: lt_99_SENIOR_TERRITORY_SALES_PKG_dag
  description: 99_SENIOR_TERRITORY_SALES_PKG package 
  schedule: "0 0 * * *" 
  tags:
    - lifetouch
    - 99_SENIOR_TERRITORY_SALES_PKG
  
  task_groups:
    - name: 99_SENIOR_TERRITORY_SALES_PKG_wait_for_data
      description: run ODI wait command
      schema_name: ODS_STAGE
      session_name: 99_SENIOR_TERRITORY_SALES_PKG
      table_name: DATA_EXPORT_TRIGGER


    - name: 99_SENIOR_TERRITORY_SALES_PKG_export
      description: drop and recreate table then extract data and load to s3
      export_file_name:
        v_data_export_run_date_trigger_table_refresh:  dags/sql/pre_sql/v_data_export_run_date_trigger_table_refresh.sql
      export_args:
        v_session_name: 99_SENIOR_TERRITORY_SALES_PKG  
      pre_sql:
        v_data_export_run_date_trigger_table_refresh: dags/sql/pre_sql/v_data_export_run_date_trigger_table_refresh.sql
        v_data_export_school_year_trigger_table_refresh: dags/sql/pre_sql/v_data_export_school_year_trigger_table_refresh.sql 


      tasks:
        - script_location: dags/sql/99_SENIOR_TERRITORY_SALES_PKG/SENIOR_TERRITORY_SALES_PKG_create_act_temp.sql
          args:
            v_session_name: 99_SENIOR_TERRITORY_SALES_PKG 
          export_files:
            - extract_query: 99_SENIOR_TERRITORY_SALES_PKG/SENIOR_TERRITORY_SALES_act_export.sql
              export_location: finance/senior_terr_sales/senior_terr_sales_act

        - script_location: dags/sql/99_SENIOR_TERRITORY_SALES_PKG/SENIOR_TERRITORY_SALES_PKG_create_terr_temp.sql
          args:
            v_session_name: 99_SENIOR_TERRITORY_SALES_PKG 
          export_files:
            - extract_query: 99_SENIOR_TERRITORY_SALES_PKG/SENIOR_TERRITORY_SALES_terr_export.sql
              export_location: finance/senior_terr_sales/senior_terr_sales_terr

        - script_location: dags/sql/99_SENIOR_TERRITORY_SALES_PKG/SENIOR_TERRITORY_SALES_PKG_create_comp_temp.sql
          args:
            v_session_name: 99_SENIOR_TERRITORY_SALES_PKG 
          export_files:
            - extract_query: 99_SENIOR_TERRITORY_SALES_PKG/SENIOR_TERRITORY_SALES_comp_export.sql
              export_location: finance/senior_terr_sales/senior_terr_sales_comp


    - name: 99_SENIOR_TERRITORY_SALES_PKG_ODI_Update
      description: ODI SQL Transformation Logic
      pre_sql:
        v_data_export_trigger_table_id: dags/sql/pre_sql/v_data_export_trigger_table_id.sql

      tasks: 
        - description: run_pkg
          type: oracle_sql
          script_location: dags/sql/99_SENIOR_TERRITORY_SALES_PKG/99_SENIOR_TERRITORY_SALES_PKG.sql
          args:
            v_session_name: 99_SENIOR_TERRITORY_SALES_PKG
