---

pipeline:
  name: lt_TEMP_FIX_EVENT_SHIPDATE_PRC_dag
  description: lifetouch lt_TEMP_FIX_EVENT_SHIPDATE_PRC package
  schedule: "@daily"
  tags:
    - lifetouch
    - TEMP_FIX_EVENT_SHIPDATE_PRC
  
  task_groups:
    - name: TEMP_FIX_EVENT_SHIPDATE_PRC_ODI_Transformation
      description: ODI SQL Transformation Logic
      # pre_sql:
      #   v_cdc_load_date: dags/sql/pre_sql.sql
      # default_args:
      #   v_cdc_overlap: 0.02083333333
      tasks: 
        - name: TEMP_FIX_EVENT_SHIPDATE_PRC
          description: load order tracking package
          type: oracle_sql
          script_location: dags/sql/TEMP_FIX_EVENT_SHIPDATE_PRC/TEMP_FIX_EVENT_SHIPDATE_PRC.sql
          # args:
          #   v_cdc_load_table_name: ORDER_TRACKING

