select 	
	UNSHIPPED_WOB.LAB	   LAB,
	UNSHIPPED_WOB.SCHOOL_YEAR	   SCHOOL_YEAR,
	UNSHIPPED_WOB.FISCAL_YEAR	   FISCAL_YEAR,
	UNSHIPPED_WOB.CALENDAR_WEEK	   CALENDAR_WEEK,
	UNSHIPPED_WOB.PRODUCTION_WEEK	   PRODUCTION_WEEK,
	UNSHIPPED_WOB.PROGRAM_NAME	   PROGRAM_NAME,
	UNSHIPPED_WOB.SUB_PROGRAM_NAME	   SUB_PROGRAM_NAME,
	UNSHIPPED_WOB.TERRITORY_CODE	   TERRITORY_CODE,
	UNSHIPPED_WOB.SELLING_METHOD	   SELLING_METHOD,
	UNSHIPPED_WOB.APO_ID	   APO_ID,
	REPLACE(UNSHIPPED_WOB.APO_DESC,',','-')	   APO_DESC,
	UNSHIPPED_WOB.SHIP_TO	   SHIP_TO,
	UNSHIPPED_WOB.EVENT_REF_ID	   EVENT_REF_ID,
	UNSHIPPED_WOB.PRODUCT_LINE	   PRODUCT_LINE,
	REPLACE(UNSHIPPED_WOB.MANUFACTURER_FAMILY,',','-')	   MANUFACTURER_FAMILY,
	UNSHIPPED_WOB.MANUFACTURER_ITEM	   MANUFACTURER_ITEM,
	REPLACE(UNSHIPPED_WOB.MANUFACTURER_ITEM_DESC,',','-')	   MANUFACTURER_ITEM_DESC,
	UNSHIPPED_WOB.BATCH_ID	   BATCH_ID,
	UNSHIPPED_WOB.ORDER_NO	   ORDER_NO,
	to_char(UNSHIPPED_WOB.PLANT_RECEIPT_DATE, 'MM/DD/YYYY HH24:MI:SS')	   PLANT_RECEIPT_DATE,
	to_char(UNSHIPPED_WOB.BATCH_CREATE_DATE, 'MM/DD/YYYY HH24:MI:SS')	   BATCH_CREATE_DATE,
	to_char(UNSHIPPED_WOB.READY_FULLFILLMENT_DATE, 'MM/DD/YYYY HH24:MI:SS')	   READY_FULLFILLMENT_DATE,
	to_char(UNSHIPPED_WOB.REQ_SHIP_DATE, 'MM/DD/YYYY HH24:MI:SS')	   REQ_SHIP_DATE,
	to_char(UNSHIPPED_WOB.SHIPPED_DATE, 'MM/DD/YYYY HH24:MI:SS')	   SHIPPED_DATE,
	UNSHIPPED_WOB.STATUS	   STATUS,
	UNSHIPPED_WOB.STATUS_DESC	   STATUS_DESC,
	to_char(UNSHIPPED_WOB.CURRENT_STATUS_DATE, 'MM/DD/YYYY HH24:MI:SS')	   CURRENT_STATUS_DATE,
	UNSHIPPED_WOB.TIME_FACTOR	   TIME_FACTOR,
	UNSHIPPED_WOB.MANUFACTURING_BATCH_ID	   MANUFACTURING_BATCH_ID,
	UNSHIPPED_WOB.TOTAL_WORK_ORDERS	   SHEETS,
	UNSHIPPED_WOB.TOTAL_PAGES	   TOTAL_PAGES,
	UNSHIPPED_WOB.TOTAL_ORDERS	   TOTAL_ORDERS,
	UNSHIPPED_WOB.BUYER_COUNT	   BUYER_COUNT,
	UNSHIPPED_WOB.MAKEOVER_REASON	   MAKEOVER_REASON,
	UNSHIPPED_WOB.REASON_DESC	   REASON_DESC
from	RAX_APP_USER.PPS_UNSHIPPED_WOB_STG   UNSHIPPED_WOB
where	
	(1=1)	
	

And ((UNSHIPPED_WOB.LAB = :v_data_export_Context || ' Lab' OR UNSHIPPED_WOB.LAB = :v_data_export_Context || ' SC'))
