/* TASK No. 1 */

/* NONE or SET VARIABLE STATEMENT FOUND, CHECK ODI TASK NO. 1 */




/*-----------------------------------------------*/
/* TASK No. 2 */

/* SELECT STATEMENT FOUND, CHECK ODI TASK NO. 2 */




/*-----------------------------------------------*/
/* TASK No. 3 */

/* SELECT STATEMENT FOUND, CHECK ODI TASK NO. 3 */




/*-----------------------------------------------*/
/* TASK No. 4 */
/* Drop work table */

-- drop table RAX_APP_USER.C$_0SAS_PAYMENT_STG purge

-- &


/*-----------------------------------------------*/
/* TASK No. 5 */
/* Create work table */

-- create table RAX_APP_USER.C$_0SAS_PAYMENT_STG
-- (
-- 	C1_PAYMENT_ID	NUMBER(10) NULL,
-- 	C2_AMOUNT	NUMBER(19,2) NULL,
-- 	C3_AUDIT_CREATE_DATE	TIMESTAMP(6) NULL,
-- 	C4_AUDIT_CREATED_BY	VARCHAR2(255) NULL,
-- 	C5_AUDIT_MODIFIED_BY	VARCHAR2(255) NULL,
-- 	C6_AUDIT_MODIFY_DATE	TIMESTAMP(6) NULL,
-- 	C7_BML_AUTH_CODE	VARCHAR2(50) NULL,
-- 	C8_BML_ORDER_ID	VARCHAR2(16) NULL,
-- 	C9_BML_STATUS	VARCHAR2(20) NULL,
-- 	C10_BML_ERROR_DESC	VARCHAR2(500) NULL,
-- 	C11_BML_ERROR_NO	VARCHAR2(50) NULL,
-- 	C12_BML_ERROR_STEP	VARCHAR2(20) NULL,
-- 	C13_CUSTOMER_EMAIL_ADDRESS	VARCHAR2(255) NULL,
-- 	C14_CUSTOMER_IP_ADDRESS	VARCHAR2(255) NULL,
-- 	C15_BML_PROMO_CODE	VARCHAR2(20) NULL,
-- 	C16_BML_REASON_CODE	VARCHAR2(50) NULL,
-- 	C17_BILLING_CITY	VARCHAR2(35) NULL,
-- 	C18_BILLING_COUNTRY	VARCHAR2(2) NULL,
-- 	C19_BILLING_FIRSTNAME	VARCHAR2(40) NULL,
-- 	C20_BILLING_LASTNAME	VARCHAR2(40) NULL,
-- 	C21_BILLING_LINE1	VARCHAR2(50) NULL,
-- 	C22_BILLING_LINE2	VARCHAR2(50) NULL,
-- 	C23_BILLING_PHONE_NUMBER	VARCHAR2(10) NULL,
-- 	C24_BILLING_POSTAL_CODE	VARCHAR2(35) NULL,
-- 	C25_BILLING_STATE_PROVINCE	VARCHAR2(35) NULL,
-- 	C26_AUTHORIZATION_CODE	VARCHAR2(10) NULL,
-- 	C27_CARD_EXPIRY_MONTH	NUMBER(10) NULL,
-- 	C28_CARD_EXPIRY_YEAR	NUMBER(10) NULL,
-- 	C29_FAILURE_CODE	VARCHAR2(9) NULL,
-- 	C30_FAILURE_REASON	VARCHAR2(100) NULL,
-- 	C31_CARD_USER_NAME	VARCHAR2(100) NULL,
-- 	C32_CARD_LAST_DIGITS	VARCHAR2(4) NULL,
-- 	C33_PAYMENT_SERVICE_ID	VARCHAR2(20) NULL,
-- 	C34_REFERENCE_TRANSACTION_ID	VARCHAR2(12) NULL,
-- 	C35_PAYMENT_METHOD	VARCHAR2(20) NULL,
-- 	C36_CREDIT_CARD_TYPE_ID	NUMBER(10) NULL,
-- 	C37_PAYMENT_OPTION_ID	NUMBER(10) NULL,
-- 	C38_CUSTOMER_ORDER_ID	NUMBER(10) NULL,
-- 	C39_EXTERNAL_PAYMENT_ID	VARCHAR2(19) NULL,
-- 	C40_PAYPAL_PAYER_ID	VARCHAR2(20) NULL,
-- 	C41_PAYPAL_PAYER_EMAIL	VARCHAR2(128) NULL
-- )
-- NOLOGGING

-- &


/*-----------------------------------------------*/
/* TASK No. 6 */
/* Load data */

/* SOURCE CODE */


-- select	
-- 	PAYMENT.PAYMENT_ID	   C1_PAYMENT_ID,
-- 	PAYMENT.AMOUNT	   C2_AMOUNT,
-- 	PAYMENT.AUDIT_CREATE_DATE	   C3_AUDIT_CREATE_DATE,
-- 	PAYMENT.AUDIT_CREATED_BY	   C4_AUDIT_CREATED_BY,
-- 	PAYMENT.AUDIT_MODIFIED_BY	   C5_AUDIT_MODIFIED_BY,
-- 	PAYMENT.AUDIT_MODIFY_DATE	   C6_AUDIT_MODIFY_DATE,
-- 	PAYMENT.BML_AUTH_CODE	   C7_BML_AUTH_CODE,
-- 	PAYMENT.BML_ORDER_ID	   C8_BML_ORDER_ID,
-- 	PAYMENT.BML_STATUS	   C9_BML_STATUS,
-- 	PAYMENT.BML_ERROR_DESC	   C10_BML_ERROR_DESC,
-- 	PAYMENT.BML_ERROR_NO	   C11_BML_ERROR_NO,
-- 	PAYMENT.BML_ERROR_STEP	   C12_BML_ERROR_STEP,
-- 	PAYMENT.CUSTOMER_EMAIL_ADDRESS	   C13_CUSTOMER_EMAIL_ADDRESS,
-- 	PAYMENT.CUSTOMER_IP_ADDRESS	   C14_CUSTOMER_IP_ADDRESS,
-- 	PAYMENT.BML_PROMO_CODE	   C15_BML_PROMO_CODE,
-- 	PAYMENT.BML_REASON_CODE	   C16_BML_REASON_CODE,
-- 	PAYMENT.BILLING_CITY	   C17_BILLING_CITY,
-- 	PAYMENT.BILLING_COUNTRY	   C18_BILLING_COUNTRY,
-- 	PAYMENT.BILLING_FIRSTNAME	   C19_BILLING_FIRSTNAME,
-- 	PAYMENT.BILLING_LASTNAME	   C20_BILLING_LASTNAME,
-- 	PAYMENT.BILLING_LINE1	   C21_BILLING_LINE1,
-- 	PAYMENT.BILLING_LINE2	   C22_BILLING_LINE2,
-- 	PAYMENT.BILLING_PHONE_NUMBER	   C23_BILLING_PHONE_NUMBER,
-- 	PAYMENT.BILLING_POSTAL_CODE	   C24_BILLING_POSTAL_CODE,
-- 	PAYMENT.BILLING_STATE_PROVINCE	   C25_BILLING_STATE_PROVINCE,
-- 	PAYMENT.AUTHORIZATION_CODE	   C26_AUTHORIZATION_CODE,
-- 	PAYMENT.CARD_EXPIRY_MONTH	   C27_CARD_EXPIRY_MONTH,
-- 	PAYMENT.CARD_EXPIRY_YEAR	   C28_CARD_EXPIRY_YEAR,
-- 	PAYMENT.FAILURE_CODE	   C29_FAILURE_CODE,
-- 	PAYMENT.FAILURE_REASON	   C30_FAILURE_REASON,
-- 	PAYMENT.CARD_USER_NAME	   C31_CARD_USER_NAME,
-- 	PAYMENT.CARD_LAST_DIGITS	   C32_CARD_LAST_DIGITS,
-- 	PAYMENT.PAYMENT_SERVICE_ID	   C33_PAYMENT_SERVICE_ID,
-- 	PAYMENT.REFERENCE_TRANSACTION_ID	   C34_REFERENCE_TRANSACTION_ID,
-- 	PAYMENT.PAYMENT_METHOD	   C35_PAYMENT_METHOD,
-- 	PAYMENT.CREDIT_CARD_TYPE_ID	   C36_CREDIT_CARD_TYPE_ID,
-- 	PAYMENT.PAYMENT_OPTION_ID	   C37_PAYMENT_OPTION_ID,
-- 	PAYMENT.CUSTOMER_ORDER_ID	   C38_CUSTOMER_ORDER_ID,
-- 	PAYMENT.EXTERNAL_PAYMENT_ID	   C39_EXTERNAL_PAYMENT_ID,
-- 	PAYMENT.PAYPAL_PAYER_ID	   C40_PAYPAL_PAYER_ID,
-- 	PAYMENT.PAYPAL_PAYER_EMAIL	   C41_PAYPAL_PAYER_EMAIL
-- from	SAS_SIT_OWN.PAYMENT   PAYMENT
-- where	(1=1)
-- And (PAYMENT.AUDIT_MODIFY_DATE >= TO_DATE(SUBSTR(:v_cdc_load_date, 1, 19), 'YYYY-MM-DD HH24:MI:SS')  -:v_cdc_overlap
-- )







-- &

/* TARGET CODE */
-- insert /*+ append */ into RAX_APP_USER.C$_0SAS_PAYMENT_STG
-- (
-- 	C1_PAYMENT_ID,
-- 	C2_AMOUNT,
-- 	C3_AUDIT_CREATE_DATE,
-- 	C4_AUDIT_CREATED_BY,
-- 	C5_AUDIT_MODIFIED_BY,
-- 	C6_AUDIT_MODIFY_DATE,
-- 	C7_BML_AUTH_CODE,
-- 	C8_BML_ORDER_ID,
-- 	C9_BML_STATUS,
-- 	C10_BML_ERROR_DESC,
-- 	C11_BML_ERROR_NO,
-- 	C12_BML_ERROR_STEP,
-- 	C13_CUSTOMER_EMAIL_ADDRESS,
-- 	C14_CUSTOMER_IP_ADDRESS,
-- 	C15_BML_PROMO_CODE,
-- 	C16_BML_REASON_CODE,
-- 	C17_BILLING_CITY,
-- 	C18_BILLING_COUNTRY,
-- 	C19_BILLING_FIRSTNAME,
-- 	C20_BILLING_LASTNAME,
-- 	C21_BILLING_LINE1,
-- 	C22_BILLING_LINE2,
-- 	C23_BILLING_PHONE_NUMBER,
-- 	C24_BILLING_POSTAL_CODE,
-- 	C25_BILLING_STATE_PROVINCE,
-- 	C26_AUTHORIZATION_CODE,
-- 	C27_CARD_EXPIRY_MONTH,
-- 	C28_CARD_EXPIRY_YEAR,
-- 	C29_FAILURE_CODE,
-- 	C30_FAILURE_REASON,
-- 	C31_CARD_USER_NAME,
-- 	C32_CARD_LAST_DIGITS,
-- 	C33_PAYMENT_SERVICE_ID,
-- 	C34_REFERENCE_TRANSACTION_ID,
-- 	C35_PAYMENT_METHOD,
-- 	C36_CREDIT_CARD_TYPE_ID,
-- 	C37_PAYMENT_OPTION_ID,
-- 	C38_CUSTOMER_ORDER_ID,
-- 	C39_EXTERNAL_PAYMENT_ID,
-- 	C40_PAYPAL_PAYER_ID,
-- 	C41_PAYPAL_PAYER_EMAIL
-- )
-- values
-- (
-- 	:C1_PAYMENT_ID,
-- 	:C2_AMOUNT,
-- 	:C3_AUDIT_CREATE_DATE,
-- 	:C4_AUDIT_CREATED_BY,
-- 	:C5_AUDIT_MODIFIED_BY,
-- 	:C6_AUDIT_MODIFY_DATE,
-- 	:C7_BML_AUTH_CODE,
-- 	:C8_BML_ORDER_ID,
-- 	:C9_BML_STATUS,
-- 	:C10_BML_ERROR_DESC,
-- 	:C11_BML_ERROR_NO,
-- 	:C12_BML_ERROR_STEP,
-- 	:C13_CUSTOMER_EMAIL_ADDRESS,
-- 	:C14_CUSTOMER_IP_ADDRESS,
-- 	:C15_BML_PROMO_CODE,
-- 	:C16_BML_REASON_CODE,
-- 	:C17_BILLING_CITY,
-- 	:C18_BILLING_COUNTRY,
-- 	:C19_BILLING_FIRSTNAME,
-- 	:C20_BILLING_LASTNAME,
-- 	:C21_BILLING_LINE1,
-- 	:C22_BILLING_LINE2,
-- 	:C23_BILLING_PHONE_NUMBER,
-- 	:C24_BILLING_POSTAL_CODE,
-- 	:C25_BILLING_STATE_PROVINCE,
-- 	:C26_AUTHORIZATION_CODE,
-- 	:C27_CARD_EXPIRY_MONTH,
-- 	:C28_CARD_EXPIRY_YEAR,
-- 	:C29_FAILURE_CODE,
-- 	:C30_FAILURE_REASON,
-- 	:C31_CARD_USER_NAME,
-- 	:C32_CARD_LAST_DIGITS,
-- 	:C33_PAYMENT_SERVICE_ID,
-- 	:C34_REFERENCE_TRANSACTION_ID,
-- 	:C35_PAYMENT_METHOD,
-- 	:C36_CREDIT_CARD_TYPE_ID,
-- 	:C37_PAYMENT_OPTION_ID,
-- 	:C38_CUSTOMER_ORDER_ID,
-- 	:C39_EXTERNAL_PAYMENT_ID,
-- 	:C40_PAYPAL_PAYER_ID,
-- 	:C41_PAYPAL_PAYER_EMAIL
-- )

-- &


/*-----------------------------------------------*/
/* TASK No. 7 */
/* Analyze work table */



BEGIN
DBMS_STATS.GATHER_TABLE_STATS (
    ownname =>	'RAX_APP_USER',
    tabname =>	'C$_0SAS_PAYMENT_STG',
    estimate_percent =>	DBMS_STATS.AUTO_SAMPLE_SIZE
);
END;




&


/*-----------------------------------------------*/
/* TASK No. 9 */
/* Set vID */

/* NONE or SET VARIABLE STATEMENT FOUND, CHECK ODI TASK NO. 9 */




/*-----------------------------------------------*/
/* TASK No. 10 */
/* Drop flow table */

-- drop table RAX_APP_USER.I$_SAS_PAYMENT_STG1393001

BEGIN
  EXECUTE IMMEDIATE 'drop table RAX_APP_USER.I$_SAS_PAYMENT_STG1393001';
EXCEPTION
  WHEN OTHERS THEN
   IF SQLCODE != -942 THEN
     RAISE;
   END IF;
END;


&


/*-----------------------------------------------*/
/* TASK No. 11 */
/* Create flow table I$ */

create table RAX_APP_USER.I$_SAS_PAYMENT_STG1393001
(
	PAYMENT_ID	NUMBER(10) NULL,
	AMOUNT	NUMBER(19,2) NULL,
	AUDIT_CREATE_DATE	TIMESTAMP(6) NULL,
	AUDIT_CREATED_BY	VARCHAR2(255) NULL,
	AUDIT_MODIFIED_BY	VARCHAR2(255) NULL,
	AUDIT_MODIFY_DATE	TIMESTAMP(6) NULL,
	BML_AUTH_CODE	VARCHAR2(50) NULL,
	BML_ORDER_ID	VARCHAR2(16) NULL,
	BML_STATUS	VARCHAR2(20) NULL,
	BML_ERROR_DESC	VARCHAR2(500) NULL,
	BML_ERROR_NO	VARCHAR2(50) NULL,
	BML_ERROR_STEP	VARCHAR2(20) NULL,
	CUSTOMER_EMAIL_ADDRESS	VARCHAR2(255) NULL,
	CUSTOMER_IP_ADDRESS	VARCHAR2(255) NULL,
	BML_PROMO_CODE	VARCHAR2(20) NULL,
	BML_REASON_CODE	VARCHAR2(50) NULL,
	BILLING_CITY	VARCHAR2(35) NULL,
	BILLING_COUNTRY	VARCHAR2(2) NULL,
	BILLING_FIRSTNAME	VARCHAR2(40) NULL,
	BILLING_LASTNAME	VARCHAR2(40) NULL,
	BILLING_LINE1	VARCHAR2(50) NULL,
	BILLING_LINE2	VARCHAR2(50) NULL,
	BILLING_PHONE_NUMBER	VARCHAR2(10) NULL,
	BILLING_POSTAL_CODE	VARCHAR2(35) NULL,
	BILLING_STATE_PROVINCE	VARCHAR2(35) NULL,
	AUTHORIZATION_CODE	VARCHAR2(10) NULL,
	CARD_EXPIRY_MONTH	NUMBER(10) NULL,
	CARD_EXPIRY_YEAR	NUMBER(10) NULL,
	FAILURE_CODE	VARCHAR2(9) NULL,
	FAILURE_REASON	VARCHAR2(100) NULL,
	CARD_USER_NAME	VARCHAR2(100) NULL,
	CARD_LAST_DIGITS	VARCHAR2(4) NULL,
	PAYMENT_SERVICE_ID	VARCHAR2(20) NULL,
	REFERENCE_TRANSACTION_ID	VARCHAR2(12) NULL,
	PAYMENT_METHOD	VARCHAR2(20) NULL,
	CREDIT_CARD_TYPE_ID	NUMBER(10) NULL,
	PAYMENT_OPTION_ID	NUMBER(10) NULL,
	CUSTOMER_ORDER_ID	NUMBER(10) NULL,
	EXTERNAL_PAYMENT_ID	VARCHAR2(19) NULL,
	PAYPAL_PAYER_ID	VARCHAR2(20) NULL,
	PAYPAL_PAYER_EMAIL	VARCHAR2(128) NULL,
	ODS_CREATE_DATE	DATE NULL,
	ODS_MODIFY_DATE	DATE NULL
	,IND_UPDATE		char(1)
)
NOLOGGING

&


/*-----------------------------------------------*/
/* TASK No. 12 */
/* Insert flow into I$ table */

/* DETECTION_STRATEGY = NOT_EXISTS */
 


  


insert into	RAX_APP_USER.I$_SAS_PAYMENT_STG1393001
(
	PAYMENT_ID,
	AMOUNT,
	AUDIT_CREATE_DATE,
	AUDIT_CREATED_BY,
	AUDIT_MODIFIED_BY,
	AUDIT_MODIFY_DATE,
	BML_AUTH_CODE,
	BML_ORDER_ID,
	BML_STATUS,
	BML_ERROR_DESC,
	BML_ERROR_NO,
	BML_ERROR_STEP,
	CUSTOMER_EMAIL_ADDRESS,
	CUSTOMER_IP_ADDRESS,
	BML_PROMO_CODE,
	BML_REASON_CODE,
	BILLING_CITY,
	BILLING_COUNTRY,
	BILLING_FIRSTNAME,
	BILLING_LASTNAME,
	BILLING_LINE1,
	BILLING_LINE2,
	BILLING_PHONE_NUMBER,
	BILLING_POSTAL_CODE,
	BILLING_STATE_PROVINCE,
	AUTHORIZATION_CODE,
	CARD_EXPIRY_MONTH,
	CARD_EXPIRY_YEAR,
	FAILURE_CODE,
	FAILURE_REASON,
	CARD_USER_NAME,
	CARD_LAST_DIGITS,
	PAYMENT_SERVICE_ID,
	REFERENCE_TRANSACTION_ID,
	PAYMENT_METHOD,
	CREDIT_CARD_TYPE_ID,
	PAYMENT_OPTION_ID,
	CUSTOMER_ORDER_ID,
	EXTERNAL_PAYMENT_ID,
	PAYPAL_PAYER_ID,
	PAYPAL_PAYER_EMAIL,
	IND_UPDATE
)
select 
PAYMENT_ID,
	AMOUNT,
	AUDIT_CREATE_DATE,
	AUDIT_CREATED_BY,
	AUDIT_MODIFIED_BY,
	AUDIT_MODIFY_DATE,
	BML_AUTH_CODE,
	BML_ORDER_ID,
	BML_STATUS,
	BML_ERROR_DESC,
	BML_ERROR_NO,
	BML_ERROR_STEP,
	CUSTOMER_EMAIL_ADDRESS,
	CUSTOMER_IP_ADDRESS,
	BML_PROMO_CODE,
	BML_REASON_CODE,
	BILLING_CITY,
	BILLING_COUNTRY,
	BILLING_FIRSTNAME,
	BILLING_LASTNAME,
	BILLING_LINE1,
	BILLING_LINE2,
	BILLING_PHONE_NUMBER,
	BILLING_POSTAL_CODE,
	BILLING_STATE_PROVINCE,
	AUTHORIZATION_CODE,
	CARD_EXPIRY_MONTH,
	CARD_EXPIRY_YEAR,
	FAILURE_CODE,
	FAILURE_REASON,
	CARD_USER_NAME,
	CARD_LAST_DIGITS,
	PAYMENT_SERVICE_ID,
	REFERENCE_TRANSACTION_ID,
	PAYMENT_METHOD,
	CREDIT_CARD_TYPE_ID,
	PAYMENT_OPTION_ID,
	CUSTOMER_ORDER_ID,
	EXTERNAL_PAYMENT_ID,
	PAYPAL_PAYER_ID,
	PAYPAL_PAYER_EMAIL,
	IND_UPDATE
 from (


select 	 
	
	C1_PAYMENT_ID PAYMENT_ID,
	C2_AMOUNT AMOUNT,
	C3_AUDIT_CREATE_DATE AUDIT_CREATE_DATE,
	C4_AUDIT_CREATED_BY AUDIT_CREATED_BY,
	C5_AUDIT_MODIFIED_BY AUDIT_MODIFIED_BY,
	C6_AUDIT_MODIFY_DATE AUDIT_MODIFY_DATE,
	C7_BML_AUTH_CODE BML_AUTH_CODE,
	C8_BML_ORDER_ID BML_ORDER_ID,
	C9_BML_STATUS BML_STATUS,
	C10_BML_ERROR_DESC BML_ERROR_DESC,
	C11_BML_ERROR_NO BML_ERROR_NO,
	C12_BML_ERROR_STEP BML_ERROR_STEP,
	C13_CUSTOMER_EMAIL_ADDRESS CUSTOMER_EMAIL_ADDRESS,
	C14_CUSTOMER_IP_ADDRESS CUSTOMER_IP_ADDRESS,
	C15_BML_PROMO_CODE BML_PROMO_CODE,
	C16_BML_REASON_CODE BML_REASON_CODE,
	C17_BILLING_CITY BILLING_CITY,
	C18_BILLING_COUNTRY BILLING_COUNTRY,
	C19_BILLING_FIRSTNAME BILLING_FIRSTNAME,
	C20_BILLING_LASTNAME BILLING_LASTNAME,
	C21_BILLING_LINE1 BILLING_LINE1,
	C22_BILLING_LINE2 BILLING_LINE2,
	C23_BILLING_PHONE_NUMBER BILLING_PHONE_NUMBER,
	C24_BILLING_POSTAL_CODE BILLING_POSTAL_CODE,
	C25_BILLING_STATE_PROVINCE BILLING_STATE_PROVINCE,
	C26_AUTHORIZATION_CODE AUTHORIZATION_CODE,
	C27_CARD_EXPIRY_MONTH CARD_EXPIRY_MONTH,
	C28_CARD_EXPIRY_YEAR CARD_EXPIRY_YEAR,
	C29_FAILURE_CODE FAILURE_CODE,
	C30_FAILURE_REASON FAILURE_REASON,
	C31_CARD_USER_NAME CARD_USER_NAME,
	C32_CARD_LAST_DIGITS CARD_LAST_DIGITS,
	C33_PAYMENT_SERVICE_ID PAYMENT_SERVICE_ID,
	C34_REFERENCE_TRANSACTION_ID REFERENCE_TRANSACTION_ID,
	C35_PAYMENT_METHOD PAYMENT_METHOD,
	C36_CREDIT_CARD_TYPE_ID CREDIT_CARD_TYPE_ID,
	C37_PAYMENT_OPTION_ID PAYMENT_OPTION_ID,
	C38_CUSTOMER_ORDER_ID CUSTOMER_ORDER_ID,
	C39_EXTERNAL_PAYMENT_ID EXTERNAL_PAYMENT_ID,
	C40_PAYPAL_PAYER_ID PAYPAL_PAYER_ID,
	C41_PAYPAL_PAYER_EMAIL PAYPAL_PAYER_EMAIL,

	'I' IND_UPDATE

from	RAX_APP_USER.C$_0SAS_PAYMENT_STG
where	(1=1)






) S
where NOT EXISTS 
	( select 1 from ODS_STAGE.SAS_PAYMENT_STG T
	where	T.PAYMENT_ID	= S.PAYMENT_ID 
		 and ((T.AMOUNT = S.AMOUNT) or (T.AMOUNT IS NULL and S.AMOUNT IS NULL)) and
		((T.AUDIT_CREATE_DATE = S.AUDIT_CREATE_DATE) or (T.AUDIT_CREATE_DATE IS NULL and S.AUDIT_CREATE_DATE IS NULL)) and
		((T.AUDIT_CREATED_BY = S.AUDIT_CREATED_BY) or (T.AUDIT_CREATED_BY IS NULL and S.AUDIT_CREATED_BY IS NULL)) and
		((T.AUDIT_MODIFIED_BY = S.AUDIT_MODIFIED_BY) or (T.AUDIT_MODIFIED_BY IS NULL and S.AUDIT_MODIFIED_BY IS NULL)) and
		((T.AUDIT_MODIFY_DATE = S.AUDIT_MODIFY_DATE) or (T.AUDIT_MODIFY_DATE IS NULL and S.AUDIT_MODIFY_DATE IS NULL)) and
		((T.BML_AUTH_CODE = S.BML_AUTH_CODE) or (T.BML_AUTH_CODE IS NULL and S.BML_AUTH_CODE IS NULL)) and
		((T.BML_ORDER_ID = S.BML_ORDER_ID) or (T.BML_ORDER_ID IS NULL and S.BML_ORDER_ID IS NULL)) and
		((T.BML_STATUS = S.BML_STATUS) or (T.BML_STATUS IS NULL and S.BML_STATUS IS NULL)) and
		((T.BML_ERROR_DESC = S.BML_ERROR_DESC) or (T.BML_ERROR_DESC IS NULL and S.BML_ERROR_DESC IS NULL)) and
		((T.BML_ERROR_NO = S.BML_ERROR_NO) or (T.BML_ERROR_NO IS NULL and S.BML_ERROR_NO IS NULL)) and
		((T.BML_ERROR_STEP = S.BML_ERROR_STEP) or (T.BML_ERROR_STEP IS NULL and S.BML_ERROR_STEP IS NULL)) and
		((T.CUSTOMER_EMAIL_ADDRESS = S.CUSTOMER_EMAIL_ADDRESS) or (T.CUSTOMER_EMAIL_ADDRESS IS NULL and S.CUSTOMER_EMAIL_ADDRESS IS NULL)) and
		((T.CUSTOMER_IP_ADDRESS = S.CUSTOMER_IP_ADDRESS) or (T.CUSTOMER_IP_ADDRESS IS NULL and S.CUSTOMER_IP_ADDRESS IS NULL)) and
		((T.BML_PROMO_CODE = S.BML_PROMO_CODE) or (T.BML_PROMO_CODE IS NULL and S.BML_PROMO_CODE IS NULL)) and
		((T.BML_REASON_CODE = S.BML_REASON_CODE) or (T.BML_REASON_CODE IS NULL and S.BML_REASON_CODE IS NULL)) and
		((T.BILLING_CITY = S.BILLING_CITY) or (T.BILLING_CITY IS NULL and S.BILLING_CITY IS NULL)) and
		((T.BILLING_COUNTRY = S.BILLING_COUNTRY) or (T.BILLING_COUNTRY IS NULL and S.BILLING_COUNTRY IS NULL)) and
		((T.BILLING_FIRSTNAME = S.BILLING_FIRSTNAME) or (T.BILLING_FIRSTNAME IS NULL and S.BILLING_FIRSTNAME IS NULL)) and
		((T.BILLING_LASTNAME = S.BILLING_LASTNAME) or (T.BILLING_LASTNAME IS NULL and S.BILLING_LASTNAME IS NULL)) and
		((T.BILLING_LINE1 = S.BILLING_LINE1) or (T.BILLING_LINE1 IS NULL and S.BILLING_LINE1 IS NULL)) and
		((T.BILLING_LINE2 = S.BILLING_LINE2) or (T.BILLING_LINE2 IS NULL and S.BILLING_LINE2 IS NULL)) and
		((T.BILLING_PHONE_NUMBER = S.BILLING_PHONE_NUMBER) or (T.BILLING_PHONE_NUMBER IS NULL and S.BILLING_PHONE_NUMBER IS NULL)) and
		((T.BILLING_POSTAL_CODE = S.BILLING_POSTAL_CODE) or (T.BILLING_POSTAL_CODE IS NULL and S.BILLING_POSTAL_CODE IS NULL)) and
		((T.BILLING_STATE_PROVINCE = S.BILLING_STATE_PROVINCE) or (T.BILLING_STATE_PROVINCE IS NULL and S.BILLING_STATE_PROVINCE IS NULL)) and
		((T.AUTHORIZATION_CODE = S.AUTHORIZATION_CODE) or (T.AUTHORIZATION_CODE IS NULL and S.AUTHORIZATION_CODE IS NULL)) and
		((T.CARD_EXPIRY_MONTH = S.CARD_EXPIRY_MONTH) or (T.CARD_EXPIRY_MONTH IS NULL and S.CARD_EXPIRY_MONTH IS NULL)) and
		((T.CARD_EXPIRY_YEAR = S.CARD_EXPIRY_YEAR) or (T.CARD_EXPIRY_YEAR IS NULL and S.CARD_EXPIRY_YEAR IS NULL)) and
		((T.FAILURE_CODE = S.FAILURE_CODE) or (T.FAILURE_CODE IS NULL and S.FAILURE_CODE IS NULL)) and
		((T.FAILURE_REASON = S.FAILURE_REASON) or (T.FAILURE_REASON IS NULL and S.FAILURE_REASON IS NULL)) and
		((T.CARD_USER_NAME = S.CARD_USER_NAME) or (T.CARD_USER_NAME IS NULL and S.CARD_USER_NAME IS NULL)) and
		((T.CARD_LAST_DIGITS = S.CARD_LAST_DIGITS) or (T.CARD_LAST_DIGITS IS NULL and S.CARD_LAST_DIGITS IS NULL)) and
		((T.PAYMENT_SERVICE_ID = S.PAYMENT_SERVICE_ID) or (T.PAYMENT_SERVICE_ID IS NULL and S.PAYMENT_SERVICE_ID IS NULL)) and
		((T.REFERENCE_TRANSACTION_ID = S.REFERENCE_TRANSACTION_ID) or (T.REFERENCE_TRANSACTION_ID IS NULL and S.REFERENCE_TRANSACTION_ID IS NULL)) and
		((T.PAYMENT_METHOD = S.PAYMENT_METHOD) or (T.PAYMENT_METHOD IS NULL and S.PAYMENT_METHOD IS NULL)) and
		((T.CREDIT_CARD_TYPE_ID = S.CREDIT_CARD_TYPE_ID) or (T.CREDIT_CARD_TYPE_ID IS NULL and S.CREDIT_CARD_TYPE_ID IS NULL)) and
		((T.PAYMENT_OPTION_ID = S.PAYMENT_OPTION_ID) or (T.PAYMENT_OPTION_ID IS NULL and S.PAYMENT_OPTION_ID IS NULL)) and
		((T.CUSTOMER_ORDER_ID = S.CUSTOMER_ORDER_ID) or (T.CUSTOMER_ORDER_ID IS NULL and S.CUSTOMER_ORDER_ID IS NULL)) and
		((T.EXTERNAL_PAYMENT_ID = S.EXTERNAL_PAYMENT_ID) or (T.EXTERNAL_PAYMENT_ID IS NULL and S.EXTERNAL_PAYMENT_ID IS NULL)) and
		((T.PAYPAL_PAYER_ID = S.PAYPAL_PAYER_ID) or (T.PAYPAL_PAYER_ID IS NULL and S.PAYPAL_PAYER_ID IS NULL)) and
		((T.PAYPAL_PAYER_EMAIL = S.PAYPAL_PAYER_EMAIL) or (T.PAYPAL_PAYER_EMAIL IS NULL and S.PAYPAL_PAYER_EMAIL IS NULL))
        )

  
  

  



&


/*-----------------------------------------------*/
/* TASK No. 13 */
/* Analyze integration table */



begin
    dbms_stats.gather_table_stats(
	ownname => 'RAX_APP_USER',
	tabname => 'I$_SAS_PAYMENT_STG1393001',
	estimate_percent => dbms_stats.auto_sample_size
    );
end;



&


/*-----------------------------------------------*/
/* TASK No. 14 */
/* Create Index on flow table */

-- create index	RAX_APP_USER.I$_SAS_PAYMENT_STG_IDX1393001
-- on		RAX_APP_USER.I$_SAS_PAYMENT_STG1393001 (PAYMENT_ID)
-- NOLOGGING

BEGIN
  EXECUTE IMMEDIATE 'create index RAX_APP_USER.I$_SAS_PAYMENT_STG_IDX1393001
on   RAX_APP_USER.I$_SAS_PAYMENT_STG1393001 (PAYMENT_ID)';
EXCEPTION
  WHEN OTHERS THEN
   -- Handle the case where the identifier is too long (ORA-00972)
   IF SQLCODE = -972 or  SQLCODE = -1408 or SQLCODE = -955  THEN
     DBMS_OUTPUT.PUT_LINE('Identifier is too long. Skipping creation of index.');
   ELSE
     RAISE;
   END IF;
END;

&


/*-----------------------------------------------*/
/* TASK No. 15 */
/* create check table */

BEGIN
  EXECUTE IMMEDIATE 'drop table RAX_APP_USER.SNP_CHECK_TAB';
EXCEPTION
  WHEN OTHERS THEN
   IF SQLCODE != -942 THEN
     RAISE;
   END IF;
END;


&


-- create table RAX_APP_USER.SNP_CHECK_TAB
-- (
-- 	CATALOG_NAME	VARCHAR2(100 CHAR) NULL ,
-- 	SCHEMA_NAME	VARCHAR2(100 CHAR) NULL ,
-- 	RESOURCE_NAME	VARCHAR2(100 CHAR) NULL,
-- 	FULL_RES_NAME	VARCHAR2(100 CHAR) NULL,
-- 	ERR_TYPE		VARCHAR2(1 CHAR) NULL,
-- 	ERR_MESS		VARCHAR2(250 CHAR) NULL ,
-- 	CHECK_DATE	DATE NULL,
-- 	ORIGIN		VARCHAR2(100 CHAR) NULL,
-- 	CONS_NAME	VARCHAR2(35 CHAR) NULL,
-- 	CONS_TYPE		VARCHAR2(2 CHAR) NULL,
-- 	ERR_COUNT		NUMBER(10) NULL
-- )
	
BEGIN
   EXECUTE IMMEDIATE '
      create table RAX_APP_USER.SNP_CHECK_TAB
		(
			CATALOG_NAME	VARCHAR2(100 CHAR) NULL ,
			SCHEMA_NAME	VARCHAR2(100 CHAR) NULL ,
			RESOURCE_NAME	VARCHAR2(100 CHAR) NULL,
			FULL_RES_NAME	VARCHAR2(100 CHAR) NULL,
			ERR_TYPE		VARCHAR2(1 CHAR) NULL,
			ERR_MESS		VARCHAR2(250 CHAR) NULL ,
			CHECK_DATE	DATE NULL,
			ORIGIN		VARCHAR2(100 CHAR) NULL,
			CONS_NAME	VARCHAR2(35 CHAR) NULL,
			CONS_TYPE		VARCHAR2(2 CHAR) NULL,
			ERR_COUNT		NUMBER(10) NULL
		)
   ';
END;

&


/*-----------------------------------------------*/
/* TASK No. 16 */
/* delete previous check sum */

delete from	RAX_APP_USER.SNP_CHECK_TAB
where	SCHEMA_NAME	= 'ODS_STAGE'
and	ORIGIN 		= '(1393001)ODS_Project.LOAD_SAS_PAYMENT_STG_INT'
and	ERR_TYPE 		= 'F'


&


/*-----------------------------------------------*/
/* TASK No. 17 */
/* create error table */

BEGIN
  EXECUTE IMMEDIATE 'drop table RAX_APP_USER.E$_SAS_PAYMENT_STG1393001';
EXCEPTION
  WHEN OTHERS THEN
   IF SQLCODE != -942 THEN
     RAISE;
   END IF;
END;


&


create table RAX_APP_USER.E$_SAS_PAYMENT_STG1393001
(
	ODI_ROW_ID 		UROWID,
	ODI_ERR_TYPE		VARCHAR2(1 CHAR) NULL, 
	ODI_ERR_MESS		VARCHAR2(250 CHAR) NULL,
	ODI_CHECK_DATE	DATE NULL, 
	PAYMENT_ID	NUMBER(10) NULL,
	AMOUNT	NUMBER(19,2) NULL,
	AUDIT_CREATE_DATE	TIMESTAMP(6) NULL,
	AUDIT_CREATED_BY	VARCHAR2(255) NULL,
	AUDIT_MODIFIED_BY	VARCHAR2(255) NULL,
	AUDIT_MODIFY_DATE	TIMESTAMP(6) NULL,
	BML_AUTH_CODE	VARCHAR2(50) NULL,
	BML_ORDER_ID	VARCHAR2(16) NULL,
	BML_STATUS	VARCHAR2(20) NULL,
	BML_ERROR_DESC	VARCHAR2(500) NULL,
	BML_ERROR_NO	VARCHAR2(50) NULL,
	BML_ERROR_STEP	VARCHAR2(20) NULL,
	CUSTOMER_EMAIL_ADDRESS	VARCHAR2(255) NULL,
	CUSTOMER_IP_ADDRESS	VARCHAR2(255) NULL,
	BML_PROMO_CODE	VARCHAR2(20) NULL,
	BML_REASON_CODE	VARCHAR2(50) NULL,
	BILLING_CITY	VARCHAR2(35) NULL,
	BILLING_COUNTRY	VARCHAR2(2) NULL,
	BILLING_FIRSTNAME	VARCHAR2(40) NULL,
	BILLING_LASTNAME	VARCHAR2(40) NULL,
	BILLING_LINE1	VARCHAR2(50) NULL,
	BILLING_LINE2	VARCHAR2(50) NULL,
	BILLING_PHONE_NUMBER	VARCHAR2(10) NULL,
	BILLING_POSTAL_CODE	VARCHAR2(35) NULL,
	BILLING_STATE_PROVINCE	VARCHAR2(35) NULL,
	AUTHORIZATION_CODE	VARCHAR2(10) NULL,
	CARD_EXPIRY_MONTH	NUMBER(10) NULL,
	CARD_EXPIRY_YEAR	NUMBER(10) NULL,
	FAILURE_CODE	VARCHAR2(9) NULL,
	FAILURE_REASON	VARCHAR2(100) NULL,
	CARD_USER_NAME	VARCHAR2(100) NULL,
	CARD_LAST_DIGITS	VARCHAR2(4) NULL,
	PAYMENT_SERVICE_ID	VARCHAR2(20) NULL,
	REFERENCE_TRANSACTION_ID	VARCHAR2(12) NULL,
	PAYMENT_METHOD	VARCHAR2(20) NULL,
	CREDIT_CARD_TYPE_ID	NUMBER(10) NULL,
	PAYMENT_OPTION_ID	NUMBER(10) NULL,
	CUSTOMER_ORDER_ID	NUMBER(10) NULL,
	EXTERNAL_PAYMENT_ID	VARCHAR2(19) NULL,
	PAYPAL_PAYER_ID	VARCHAR2(20) NULL,
	PAYPAL_PAYER_EMAIL	VARCHAR2(128) NULL,
	ODS_CREATE_DATE	DATE NULL,
	ODS_MODIFY_DATE	DATE NULL,
	ODI_ORIGIN		VARCHAR2(100 CHAR) NULL,
	ODI_CONS_NAME	VARCHAR2(35 CHAR) NULL,
	ODI_CONS_TYPE		VARCHAR2(2 CHAR) NULL,
	ODI_PK			VARCHAR2(32 CHAR) PRIMARY KEY,
	ODI_SESS_NO		VARCHAR2(19 CHAR)
)



&


/*-----------------------------------------------*/
/* TASK No. 18 */
/* delete previous errors */

delete from 	RAX_APP_USER.E$_SAS_PAYMENT_STG1393001
where	(ODI_ERR_TYPE = 'S'	and 'F' = 'S')
or	(ODI_ERR_TYPE = 'F'	and ODI_ORIGIN = '(1393001)ODS_Project.LOAD_SAS_PAYMENT_STG_INT')


&


/*-----------------------------------------------*/
/* TASK No. 19 */
/* Create index on PK */

 
/* FLOW CONTROL CREATE THE iNDEX ON THE I$TABLE */
-- create index 	RAX_APP_USER.I$_SAS_PAYMENT_STG1393001
-- on	RAX_APP_USER.I$_SAS_PAYMENT_STG1393001 (PAYMENT_ID)

BEGIN
  EXECUTE IMMEDIATE 'create index RAX_APP_USER.I$_SAS_PAYMENT_STG1393001
on   RAX_APP_USER.I$_SAS_PAYMENT_STG1393001 (PAYMENT_ID)';
EXCEPTION
  WHEN OTHERS THEN
   -- Handle the case where the identifier is too long (ORA-00972)
   IF SQLCODE = -972 or  SQLCODE = -1408 or SQLCODE = -955  THEN
     DBMS_OUTPUT.PUT_LINE('Identifier is too long. Skipping creation of index.');
   ELSE
     RAISE;
   END IF;
END;

&


/*-----------------------------------------------*/
/* TASK No. 20 */
/* insert PK errors */

DECLARE
               CheckTable                             VarChar2(60);
               TargetTable                            VarChar2(60);
               VariableCheckTable                     VarChar2(60);

BEGIN
               SELECT 'RAX_APP_USER.I$_SAS_PAYMENT_STG' INTO CheckTable FROM DUAL;
               SELECT 'ODS_STAGE.SAS_PAYMENT_STG' INTO TargetTable FROM DUAL;

IF CheckTable = TargetTable THEN
   VariableCheckTable := CheckTable; 
ELSE
   VariableCheckTable := CheckTable || '1393001';
END IF;

execute immediate '
insert into RAX_APP_USER.E$_SAS_PAYMENT_STG1393001
(
	ODI_PK,
	ODI_SESS_NO,
	ODI_ROW_ID,
	ODI_ERR_TYPE,
	ODI_ERR_MESS,
	ODI_ORIGIN,
	ODI_CHECK_DATE,
	ODI_CONS_NAME,
	ODI_CONS_TYPE,
	PAYMENT_ID,
	AMOUNT,
	AUDIT_CREATE_DATE,
	AUDIT_CREATED_BY,
	AUDIT_MODIFIED_BY,
	AUDIT_MODIFY_DATE,
	BML_AUTH_CODE,
	BML_ORDER_ID,
	BML_STATUS,
	BML_ERROR_DESC,
	BML_ERROR_NO,
	BML_ERROR_STEP,
	CUSTOMER_EMAIL_ADDRESS,
	CUSTOMER_IP_ADDRESS,
	BML_PROMO_CODE,
	BML_REASON_CODE,
	BILLING_CITY,
	BILLING_COUNTRY,
	BILLING_FIRSTNAME,
	BILLING_LASTNAME,
	BILLING_LINE1,
	BILLING_LINE2,
	BILLING_PHONE_NUMBER,
	BILLING_POSTAL_CODE,
	BILLING_STATE_PROVINCE,
	AUTHORIZATION_CODE,
	CARD_EXPIRY_MONTH,
	CARD_EXPIRY_YEAR,
	FAILURE_CODE,
	FAILURE_REASON,
	CARD_USER_NAME,
	CARD_LAST_DIGITS,
	PAYMENT_SERVICE_ID,
	REFERENCE_TRANSACTION_ID,
	PAYMENT_METHOD,
	CREDIT_CARD_TYPE_ID,
	PAYMENT_OPTION_ID,
	CUSTOMER_ORDER_ID,
	EXTERNAL_PAYMENT_ID,
	PAYPAL_PAYER_ID,
	PAYPAL_PAYER_EMAIL,
	ODS_CREATE_DATE,
	ODS_MODIFY_DATE
)
select	SYS_GUID(),
	:v_sess_no, 
	rowid,
	''F'', 
	''ODI-15064: The primary key PAYMENT_PK is not unique.'',
	''(1393001)ODS_Project.LOAD_SAS_PAYMENT_STG_INT'',
	sysdate,
	''PAYMENT_PK'',
	''PK'',	
	SAS_PAYMENT_STG.PAYMENT_ID,
	SAS_PAYMENT_STG.AMOUNT,
	SAS_PAYMENT_STG.AUDIT_CREATE_DATE,
	SAS_PAYMENT_STG.AUDIT_CREATED_BY,
	SAS_PAYMENT_STG.AUDIT_MODIFIED_BY,
	SAS_PAYMENT_STG.AUDIT_MODIFY_DATE,
	SAS_PAYMENT_STG.BML_AUTH_CODE,
	SAS_PAYMENT_STG.BML_ORDER_ID,
	SAS_PAYMENT_STG.BML_STATUS,
	SAS_PAYMENT_STG.BML_ERROR_DESC,
	SAS_PAYMENT_STG.BML_ERROR_NO,
	SAS_PAYMENT_STG.BML_ERROR_STEP,
	SAS_PAYMENT_STG.CUSTOMER_EMAIL_ADDRESS,
	SAS_PAYMENT_STG.CUSTOMER_IP_ADDRESS,
	SAS_PAYMENT_STG.BML_PROMO_CODE,
	SAS_PAYMENT_STG.BML_REASON_CODE,
	SAS_PAYMENT_STG.BILLING_CITY,
	SAS_PAYMENT_STG.BILLING_COUNTRY,
	SAS_PAYMENT_STG.BILLING_FIRSTNAME,
	SAS_PAYMENT_STG.BILLING_LASTNAME,
	SAS_PAYMENT_STG.BILLING_LINE1,
	SAS_PAYMENT_STG.BILLING_LINE2,
	SAS_PAYMENT_STG.BILLING_PHONE_NUMBER,
	SAS_PAYMENT_STG.BILLING_POSTAL_CODE,
	SAS_PAYMENT_STG.BILLING_STATE_PROVINCE,
	SAS_PAYMENT_STG.AUTHORIZATION_CODE,
	SAS_PAYMENT_STG.CARD_EXPIRY_MONTH,
	SAS_PAYMENT_STG.CARD_EXPIRY_YEAR,
	SAS_PAYMENT_STG.FAILURE_CODE,
	SAS_PAYMENT_STG.FAILURE_REASON,
	SAS_PAYMENT_STG.CARD_USER_NAME,
	SAS_PAYMENT_STG.CARD_LAST_DIGITS,
	SAS_PAYMENT_STG.PAYMENT_SERVICE_ID,
	SAS_PAYMENT_STG.REFERENCE_TRANSACTION_ID,
	SAS_PAYMENT_STG.PAYMENT_METHOD,
	SAS_PAYMENT_STG.CREDIT_CARD_TYPE_ID,
	SAS_PAYMENT_STG.PAYMENT_OPTION_ID,
	SAS_PAYMENT_STG.CUSTOMER_ORDER_ID,
	SAS_PAYMENT_STG.EXTERNAL_PAYMENT_ID,
	SAS_PAYMENT_STG.PAYPAL_PAYER_ID,
	SAS_PAYMENT_STG.PAYPAL_PAYER_EMAIL,
	SAS_PAYMENT_STG.ODS_CREATE_DATE,
	SAS_PAYMENT_STG.ODS_MODIFY_DATE
from	'
 || VariableCheckTable || 
' SAS_PAYMENT_STG 
where	exists  (
		select	SUB1.PAYMENT_ID
		from 	' 
|| VariableCheckTable ||
'  SUB1
		where 	SUB1.PAYMENT_ID=SAS_PAYMENT_STG.PAYMENT_ID
		group by 	SUB1.PAYMENT_ID
		having 	count(1) > 1
		)
';

END;


&


/*-----------------------------------------------*/
/* TASK No. 21 */
/* Create index on AK */

 
/* FLOW CONTROL CREATE THE iNDEX ON THE I$TABLE */
-- create index 	SAS_PAYMENT_PK_flow
-- on	RAX_APP_USER.I$_SAS_PAYMENT_STG1393001 
-- 	(PAYMENT_ID)

BEGIN
  EXECUTE IMMEDIATE 'create index SAS_PAYMENT_PK_flow
on   RAX_APP_USER.I$_SAS_PAYMENT_STG1393001 (PAYMENT_ID)';
EXCEPTION
  WHEN OTHERS THEN
   -- Handle the case where the identifier is too long (ORA-00972)
   IF SQLCODE = -972 or  SQLCODE = -1408 or SQLCODE = -955  THEN
     DBMS_OUTPUT.PUT_LINE('Identifier is too long. Skipping creation of index.');
   ELSE
     RAISE;
   END IF;
END;

&


/*-----------------------------------------------*/
/* TASK No. 22 */
/* insert AK errors */

DECLARE
               CheckTable                             VarChar2(60);
               TargetTable                            VarChar2(60);
               VariableCheckTable                VarChar2(60);

BEGIN
               SELECT 'RAX_APP_USER.I$_SAS_PAYMENT_STG' INTO CheckTable FROM DUAL;
               SELECT 'ODS_STAGE.SAS_PAYMENT_STG' INTO TargetTable FROM DUAL;

IF CheckTable = TargetTable THEN
   VariableCheckTable := CheckTable; 
ELSE
   VariableCheckTable := CheckTable || '1393001';
END IF;

execute immediate '
insert into RAX_APP_USER.E$_SAS_PAYMENT_STG1393001
(
	ODI_PK,
	ODI_SESS_NO,
	ODI_ROW_ID,
	ODI_ERR_TYPE,
	ODI_ERR_MESS,
	ODI_ORIGIN,
	ODI_CHECK_DATE,
	ODI_CONS_NAME,
	ODI_CONS_TYPE,
	PAYMENT_ID,
	AMOUNT,
	AUDIT_CREATE_DATE,
	AUDIT_CREATED_BY,
	AUDIT_MODIFIED_BY,
	AUDIT_MODIFY_DATE,
	BML_AUTH_CODE,
	BML_ORDER_ID,
	BML_STATUS,
	BML_ERROR_DESC,
	BML_ERROR_NO,
	BML_ERROR_STEP,
	CUSTOMER_EMAIL_ADDRESS,
	CUSTOMER_IP_ADDRESS,
	BML_PROMO_CODE,
	BML_REASON_CODE,
	BILLING_CITY,
	BILLING_COUNTRY,
	BILLING_FIRSTNAME,
	BILLING_LASTNAME,
	BILLING_LINE1,
	BILLING_LINE2,
	BILLING_PHONE_NUMBER,
	BILLING_POSTAL_CODE,
	BILLING_STATE_PROVINCE,
	AUTHORIZATION_CODE,
	CARD_EXPIRY_MONTH,
	CARD_EXPIRY_YEAR,
	FAILURE_CODE,
	FAILURE_REASON,
	CARD_USER_NAME,
	CARD_LAST_DIGITS,
	PAYMENT_SERVICE_ID,
	REFERENCE_TRANSACTION_ID,
	PAYMENT_METHOD,
	CREDIT_CARD_TYPE_ID,
	PAYMENT_OPTION_ID,
	CUSTOMER_ORDER_ID,
	EXTERNAL_PAYMENT_ID,
	PAYPAL_PAYER_ID,
	PAYPAL_PAYER_EMAIL,
	ODS_CREATE_DATE,
	ODS_MODIFY_DATE
)
select	SYS_GUID(),
	:v_sess_no, 
	rowid,
	''F'', 
	''ODI-15063: The alternate key SAS_PAYMENT_PK is not unique.'',
	''(1393001)ODS_Project.LOAD_SAS_PAYMENT_STG_INT'',
	sysdate,
	''SAS_PAYMENT_PK'',
	''AK'',	
	SAS_PAYMENT_STG.PAYMENT_ID,
	SAS_PAYMENT_STG.AMOUNT,
	SAS_PAYMENT_STG.AUDIT_CREATE_DATE,
	SAS_PAYMENT_STG.AUDIT_CREATED_BY,
	SAS_PAYMENT_STG.AUDIT_MODIFIED_BY,
	SAS_PAYMENT_STG.AUDIT_MODIFY_DATE,
	SAS_PAYMENT_STG.BML_AUTH_CODE,
	SAS_PAYMENT_STG.BML_ORDER_ID,
	SAS_PAYMENT_STG.BML_STATUS,
	SAS_PAYMENT_STG.BML_ERROR_DESC,
	SAS_PAYMENT_STG.BML_ERROR_NO,
	SAS_PAYMENT_STG.BML_ERROR_STEP,
	SAS_PAYMENT_STG.CUSTOMER_EMAIL_ADDRESS,
	SAS_PAYMENT_STG.CUSTOMER_IP_ADDRESS,
	SAS_PAYMENT_STG.BML_PROMO_CODE,
	SAS_PAYMENT_STG.BML_REASON_CODE,
	SAS_PAYMENT_STG.BILLING_CITY,
	SAS_PAYMENT_STG.BILLING_COUNTRY,
	SAS_PAYMENT_STG.BILLING_FIRSTNAME,
	SAS_PAYMENT_STG.BILLING_LASTNAME,
	SAS_PAYMENT_STG.BILLING_LINE1,
	SAS_PAYMENT_STG.BILLING_LINE2,
	SAS_PAYMENT_STG.BILLING_PHONE_NUMBER,
	SAS_PAYMENT_STG.BILLING_POSTAL_CODE,
	SAS_PAYMENT_STG.BILLING_STATE_PROVINCE,
	SAS_PAYMENT_STG.AUTHORIZATION_CODE,
	SAS_PAYMENT_STG.CARD_EXPIRY_MONTH,
	SAS_PAYMENT_STG.CARD_EXPIRY_YEAR,
	SAS_PAYMENT_STG.FAILURE_CODE,
	SAS_PAYMENT_STG.FAILURE_REASON,
	SAS_PAYMENT_STG.CARD_USER_NAME,
	SAS_PAYMENT_STG.CARD_LAST_DIGITS,
	SAS_PAYMENT_STG.PAYMENT_SERVICE_ID,
	SAS_PAYMENT_STG.REFERENCE_TRANSACTION_ID,
	SAS_PAYMENT_STG.PAYMENT_METHOD,
	SAS_PAYMENT_STG.CREDIT_CARD_TYPE_ID,
	SAS_PAYMENT_STG.PAYMENT_OPTION_ID,
	SAS_PAYMENT_STG.CUSTOMER_ORDER_ID,
	SAS_PAYMENT_STG.EXTERNAL_PAYMENT_ID,
	SAS_PAYMENT_STG.PAYPAL_PAYER_ID,
	SAS_PAYMENT_STG.PAYPAL_PAYER_EMAIL,
	SAS_PAYMENT_STG.ODS_CREATE_DATE,
	SAS_PAYMENT_STG.ODS_MODIFY_DATE
from              '	
 || VariableCheckTable || 
' SAS_PAYMENT_STG
where	exists  (
		select	SUB.PAYMENT_ID
		from 	'
 || VariableCheckTable || 
' SUB
		where 	SUB.PAYMENT_ID=SAS_PAYMENT_STG.PAYMENT_ID
		group by 	SUB.PAYMENT_ID
		having 	count(1) > 1
		)
 ';

END;

/*  Checked Datastore =RAX_APP_USER.I$_SAS_PAYMENT_STG  */
/*  Integration Datastore =RAX_APP_USER.I$_SAS_PAYMENT_STG   */
/*  Target Datastore =ODS_STAGE.SAS_PAYMENT_STG */



&


/*-----------------------------------------------*/
/* TASK No. 23 */
/* insert Not Null errors */

insert into RAX_APP_USER.E$_SAS_PAYMENT_STG1393001
(
	ODI_PK,
	ODI_SESS_NO,
	ODI_ROW_ID,
	ODI_ERR_TYPE,
	ODI_ERR_MESS,
	ODI_CHECK_DATE,
	ODI_ORIGIN,
	ODI_CONS_NAME,
	ODI_CONS_TYPE,
	PAYMENT_ID,
	AMOUNT,
	AUDIT_CREATE_DATE,
	AUDIT_CREATED_BY,
	AUDIT_MODIFIED_BY,
	AUDIT_MODIFY_DATE,
	BML_AUTH_CODE,
	BML_ORDER_ID,
	BML_STATUS,
	BML_ERROR_DESC,
	BML_ERROR_NO,
	BML_ERROR_STEP,
	CUSTOMER_EMAIL_ADDRESS,
	CUSTOMER_IP_ADDRESS,
	BML_PROMO_CODE,
	BML_REASON_CODE,
	BILLING_CITY,
	BILLING_COUNTRY,
	BILLING_FIRSTNAME,
	BILLING_LASTNAME,
	BILLING_LINE1,
	BILLING_LINE2,
	BILLING_PHONE_NUMBER,
	BILLING_POSTAL_CODE,
	BILLING_STATE_PROVINCE,
	AUTHORIZATION_CODE,
	CARD_EXPIRY_MONTH,
	CARD_EXPIRY_YEAR,
	FAILURE_CODE,
	FAILURE_REASON,
	CARD_USER_NAME,
	CARD_LAST_DIGITS,
	PAYMENT_SERVICE_ID,
	REFERENCE_TRANSACTION_ID,
	PAYMENT_METHOD,
	CREDIT_CARD_TYPE_ID,
	PAYMENT_OPTION_ID,
	CUSTOMER_ORDER_ID,
	EXTERNAL_PAYMENT_ID,
	PAYPAL_PAYER_ID,
	PAYPAL_PAYER_EMAIL,
	ODS_CREATE_DATE,
	ODS_MODIFY_DATE
)
select
	SYS_GUID(),
	:v_sess_no, 
	rowid,
	'F', 
	'ODI-15066: The column PAYMENT_ID cannot be null.',
	sysdate,
	'(1393001)ODS_Project.LOAD_SAS_PAYMENT_STG_INT',
	'PAYMENT_ID',
	'NN',	
	PAYMENT_ID,
	AMOUNT,
	AUDIT_CREATE_DATE,
	AUDIT_CREATED_BY,
	AUDIT_MODIFIED_BY,
	AUDIT_MODIFY_DATE,
	BML_AUTH_CODE,
	BML_ORDER_ID,
	BML_STATUS,
	BML_ERROR_DESC,
	BML_ERROR_NO,
	BML_ERROR_STEP,
	CUSTOMER_EMAIL_ADDRESS,
	CUSTOMER_IP_ADDRESS,
	BML_PROMO_CODE,
	BML_REASON_CODE,
	BILLING_CITY,
	BILLING_COUNTRY,
	BILLING_FIRSTNAME,
	BILLING_LASTNAME,
	BILLING_LINE1,
	BILLING_LINE2,
	BILLING_PHONE_NUMBER,
	BILLING_POSTAL_CODE,
	BILLING_STATE_PROVINCE,
	AUTHORIZATION_CODE,
	CARD_EXPIRY_MONTH,
	CARD_EXPIRY_YEAR,
	FAILURE_CODE,
	FAILURE_REASON,
	CARD_USER_NAME,
	CARD_LAST_DIGITS,
	PAYMENT_SERVICE_ID,
	REFERENCE_TRANSACTION_ID,
	PAYMENT_METHOD,
	CREDIT_CARD_TYPE_ID,
	PAYMENT_OPTION_ID,
	CUSTOMER_ORDER_ID,
	EXTERNAL_PAYMENT_ID,
	PAYPAL_PAYER_ID,
	PAYPAL_PAYER_EMAIL,
	ODS_CREATE_DATE,
	ODS_MODIFY_DATE
from	RAX_APP_USER.I$_SAS_PAYMENT_STG1393001
where	PAYMENT_ID is null



&


/*-----------------------------------------------*/
/* TASK No. 24 */
/* insert Not Null errors */

insert into RAX_APP_USER.E$_SAS_PAYMENT_STG1393001
(
	ODI_PK,
	ODI_SESS_NO,
	ODI_ROW_ID,
	ODI_ERR_TYPE,
	ODI_ERR_MESS,
	ODI_CHECK_DATE,
	ODI_ORIGIN,
	ODI_CONS_NAME,
	ODI_CONS_TYPE,
	PAYMENT_ID,
	AMOUNT,
	AUDIT_CREATE_DATE,
	AUDIT_CREATED_BY,
	AUDIT_MODIFIED_BY,
	AUDIT_MODIFY_DATE,
	BML_AUTH_CODE,
	BML_ORDER_ID,
	BML_STATUS,
	BML_ERROR_DESC,
	BML_ERROR_NO,
	BML_ERROR_STEP,
	CUSTOMER_EMAIL_ADDRESS,
	CUSTOMER_IP_ADDRESS,
	BML_PROMO_CODE,
	BML_REASON_CODE,
	BILLING_CITY,
	BILLING_COUNTRY,
	BILLING_FIRSTNAME,
	BILLING_LASTNAME,
	BILLING_LINE1,
	BILLING_LINE2,
	BILLING_PHONE_NUMBER,
	BILLING_POSTAL_CODE,
	BILLING_STATE_PROVINCE,
	AUTHORIZATION_CODE,
	CARD_EXPIRY_MONTH,
	CARD_EXPIRY_YEAR,
	FAILURE_CODE,
	FAILURE_REASON,
	CARD_USER_NAME,
	CARD_LAST_DIGITS,
	PAYMENT_SERVICE_ID,
	REFERENCE_TRANSACTION_ID,
	PAYMENT_METHOD,
	CREDIT_CARD_TYPE_ID,
	PAYMENT_OPTION_ID,
	CUSTOMER_ORDER_ID,
	EXTERNAL_PAYMENT_ID,
	PAYPAL_PAYER_ID,
	PAYPAL_PAYER_EMAIL,
	ODS_CREATE_DATE,
	ODS_MODIFY_DATE
)
select
	SYS_GUID(),
	:v_sess_no, 
	rowid,
	'F', 
	'ODI-15066: The column AUDIT_CREATE_DATE cannot be null.',
	sysdate,
	'(1393001)ODS_Project.LOAD_SAS_PAYMENT_STG_INT',
	'AUDIT_CREATE_DATE',
	'NN',	
	PAYMENT_ID,
	AMOUNT,
	AUDIT_CREATE_DATE,
	AUDIT_CREATED_BY,
	AUDIT_MODIFIED_BY,
	AUDIT_MODIFY_DATE,
	BML_AUTH_CODE,
	BML_ORDER_ID,
	BML_STATUS,
	BML_ERROR_DESC,
	BML_ERROR_NO,
	BML_ERROR_STEP,
	CUSTOMER_EMAIL_ADDRESS,
	CUSTOMER_IP_ADDRESS,
	BML_PROMO_CODE,
	BML_REASON_CODE,
	BILLING_CITY,
	BILLING_COUNTRY,
	BILLING_FIRSTNAME,
	BILLING_LASTNAME,
	BILLING_LINE1,
	BILLING_LINE2,
	BILLING_PHONE_NUMBER,
	BILLING_POSTAL_CODE,
	BILLING_STATE_PROVINCE,
	AUTHORIZATION_CODE,
	CARD_EXPIRY_MONTH,
	CARD_EXPIRY_YEAR,
	FAILURE_CODE,
	FAILURE_REASON,
	CARD_USER_NAME,
	CARD_LAST_DIGITS,
	PAYMENT_SERVICE_ID,
	REFERENCE_TRANSACTION_ID,
	PAYMENT_METHOD,
	CREDIT_CARD_TYPE_ID,
	PAYMENT_OPTION_ID,
	CUSTOMER_ORDER_ID,
	EXTERNAL_PAYMENT_ID,
	PAYPAL_PAYER_ID,
	PAYPAL_PAYER_EMAIL,
	ODS_CREATE_DATE,
	ODS_MODIFY_DATE
from	RAX_APP_USER.I$_SAS_PAYMENT_STG1393001
where	AUDIT_CREATE_DATE is null



&


/*-----------------------------------------------*/
/* TASK No. 25 */
/* insert Not Null errors */

insert into RAX_APP_USER.E$_SAS_PAYMENT_STG1393001
(
	ODI_PK,
	ODI_SESS_NO,
	ODI_ROW_ID,
	ODI_ERR_TYPE,
	ODI_ERR_MESS,
	ODI_CHECK_DATE,
	ODI_ORIGIN,
	ODI_CONS_NAME,
	ODI_CONS_TYPE,
	PAYMENT_ID,
	AMOUNT,
	AUDIT_CREATE_DATE,
	AUDIT_CREATED_BY,
	AUDIT_MODIFIED_BY,
	AUDIT_MODIFY_DATE,
	BML_AUTH_CODE,
	BML_ORDER_ID,
	BML_STATUS,
	BML_ERROR_DESC,
	BML_ERROR_NO,
	BML_ERROR_STEP,
	CUSTOMER_EMAIL_ADDRESS,
	CUSTOMER_IP_ADDRESS,
	BML_PROMO_CODE,
	BML_REASON_CODE,
	BILLING_CITY,
	BILLING_COUNTRY,
	BILLING_FIRSTNAME,
	BILLING_LASTNAME,
	BILLING_LINE1,
	BILLING_LINE2,
	BILLING_PHONE_NUMBER,
	BILLING_POSTAL_CODE,
	BILLING_STATE_PROVINCE,
	AUTHORIZATION_CODE,
	CARD_EXPIRY_MONTH,
	CARD_EXPIRY_YEAR,
	FAILURE_CODE,
	FAILURE_REASON,
	CARD_USER_NAME,
	CARD_LAST_DIGITS,
	PAYMENT_SERVICE_ID,
	REFERENCE_TRANSACTION_ID,
	PAYMENT_METHOD,
	CREDIT_CARD_TYPE_ID,
	PAYMENT_OPTION_ID,
	CUSTOMER_ORDER_ID,
	EXTERNAL_PAYMENT_ID,
	PAYPAL_PAYER_ID,
	PAYPAL_PAYER_EMAIL,
	ODS_CREATE_DATE,
	ODS_MODIFY_DATE
)
select
	SYS_GUID(),
	:v_sess_no, 
	rowid,
	'F', 
	'ODI-15066: The column AUDIT_CREATED_BY cannot be null.',
	sysdate,
	'(1393001)ODS_Project.LOAD_SAS_PAYMENT_STG_INT',
	'AUDIT_CREATED_BY',
	'NN',	
	PAYMENT_ID,
	AMOUNT,
	AUDIT_CREATE_DATE,
	AUDIT_CREATED_BY,
	AUDIT_MODIFIED_BY,
	AUDIT_MODIFY_DATE,
	BML_AUTH_CODE,
	BML_ORDER_ID,
	BML_STATUS,
	BML_ERROR_DESC,
	BML_ERROR_NO,
	BML_ERROR_STEP,
	CUSTOMER_EMAIL_ADDRESS,
	CUSTOMER_IP_ADDRESS,
	BML_PROMO_CODE,
	BML_REASON_CODE,
	BILLING_CITY,
	BILLING_COUNTRY,
	BILLING_FIRSTNAME,
	BILLING_LASTNAME,
	BILLING_LINE1,
	BILLING_LINE2,
	BILLING_PHONE_NUMBER,
	BILLING_POSTAL_CODE,
	BILLING_STATE_PROVINCE,
	AUTHORIZATION_CODE,
	CARD_EXPIRY_MONTH,
	CARD_EXPIRY_YEAR,
	FAILURE_CODE,
	FAILURE_REASON,
	CARD_USER_NAME,
	CARD_LAST_DIGITS,
	PAYMENT_SERVICE_ID,
	REFERENCE_TRANSACTION_ID,
	PAYMENT_METHOD,
	CREDIT_CARD_TYPE_ID,
	PAYMENT_OPTION_ID,
	CUSTOMER_ORDER_ID,
	EXTERNAL_PAYMENT_ID,
	PAYPAL_PAYER_ID,
	PAYPAL_PAYER_EMAIL,
	ODS_CREATE_DATE,
	ODS_MODIFY_DATE
from	RAX_APP_USER.I$_SAS_PAYMENT_STG1393001
where	AUDIT_CREATED_BY is null



&


/*-----------------------------------------------*/
/* TASK No. 26 */
/* insert Not Null errors */

insert into RAX_APP_USER.E$_SAS_PAYMENT_STG1393001
(
	ODI_PK,
	ODI_SESS_NO,
	ODI_ROW_ID,
	ODI_ERR_TYPE,
	ODI_ERR_MESS,
	ODI_CHECK_DATE,
	ODI_ORIGIN,
	ODI_CONS_NAME,
	ODI_CONS_TYPE,
	PAYMENT_ID,
	AMOUNT,
	AUDIT_CREATE_DATE,
	AUDIT_CREATED_BY,
	AUDIT_MODIFIED_BY,
	AUDIT_MODIFY_DATE,
	BML_AUTH_CODE,
	BML_ORDER_ID,
	BML_STATUS,
	BML_ERROR_DESC,
	BML_ERROR_NO,
	BML_ERROR_STEP,
	CUSTOMER_EMAIL_ADDRESS,
	CUSTOMER_IP_ADDRESS,
	BML_PROMO_CODE,
	BML_REASON_CODE,
	BILLING_CITY,
	BILLING_COUNTRY,
	BILLING_FIRSTNAME,
	BILLING_LASTNAME,
	BILLING_LINE1,
	BILLING_LINE2,
	BILLING_PHONE_NUMBER,
	BILLING_POSTAL_CODE,
	BILLING_STATE_PROVINCE,
	AUTHORIZATION_CODE,
	CARD_EXPIRY_MONTH,
	CARD_EXPIRY_YEAR,
	FAILURE_CODE,
	FAILURE_REASON,
	CARD_USER_NAME,
	CARD_LAST_DIGITS,
	PAYMENT_SERVICE_ID,
	REFERENCE_TRANSACTION_ID,
	PAYMENT_METHOD,
	CREDIT_CARD_TYPE_ID,
	PAYMENT_OPTION_ID,
	CUSTOMER_ORDER_ID,
	EXTERNAL_PAYMENT_ID,
	PAYPAL_PAYER_ID,
	PAYPAL_PAYER_EMAIL,
	ODS_CREATE_DATE,
	ODS_MODIFY_DATE
)
select
	SYS_GUID(),
	:v_sess_no, 
	rowid,
	'F', 
	'ODI-15066: The column AUDIT_MODIFIED_BY cannot be null.',
	sysdate,
	'(1393001)ODS_Project.LOAD_SAS_PAYMENT_STG_INT',
	'AUDIT_MODIFIED_BY',
	'NN',	
	PAYMENT_ID,
	AMOUNT,
	AUDIT_CREATE_DATE,
	AUDIT_CREATED_BY,
	AUDIT_MODIFIED_BY,
	AUDIT_MODIFY_DATE,
	BML_AUTH_CODE,
	BML_ORDER_ID,
	BML_STATUS,
	BML_ERROR_DESC,
	BML_ERROR_NO,
	BML_ERROR_STEP,
	CUSTOMER_EMAIL_ADDRESS,
	CUSTOMER_IP_ADDRESS,
	BML_PROMO_CODE,
	BML_REASON_CODE,
	BILLING_CITY,
	BILLING_COUNTRY,
	BILLING_FIRSTNAME,
	BILLING_LASTNAME,
	BILLING_LINE1,
	BILLING_LINE2,
	BILLING_PHONE_NUMBER,
	BILLING_POSTAL_CODE,
	BILLING_STATE_PROVINCE,
	AUTHORIZATION_CODE,
	CARD_EXPIRY_MONTH,
	CARD_EXPIRY_YEAR,
	FAILURE_CODE,
	FAILURE_REASON,
	CARD_USER_NAME,
	CARD_LAST_DIGITS,
	PAYMENT_SERVICE_ID,
	REFERENCE_TRANSACTION_ID,
	PAYMENT_METHOD,
	CREDIT_CARD_TYPE_ID,
	PAYMENT_OPTION_ID,
	CUSTOMER_ORDER_ID,
	EXTERNAL_PAYMENT_ID,
	PAYPAL_PAYER_ID,
	PAYPAL_PAYER_EMAIL,
	ODS_CREATE_DATE,
	ODS_MODIFY_DATE
from	RAX_APP_USER.I$_SAS_PAYMENT_STG1393001
where	AUDIT_MODIFIED_BY is null



&


/*-----------------------------------------------*/
/* TASK No. 27 */
/* insert Not Null errors */

insert into RAX_APP_USER.E$_SAS_PAYMENT_STG1393001
(
	ODI_PK,
	ODI_SESS_NO,
	ODI_ROW_ID,
	ODI_ERR_TYPE,
	ODI_ERR_MESS,
	ODI_CHECK_DATE,
	ODI_ORIGIN,
	ODI_CONS_NAME,
	ODI_CONS_TYPE,
	PAYMENT_ID,
	AMOUNT,
	AUDIT_CREATE_DATE,
	AUDIT_CREATED_BY,
	AUDIT_MODIFIED_BY,
	AUDIT_MODIFY_DATE,
	BML_AUTH_CODE,
	BML_ORDER_ID,
	BML_STATUS,
	BML_ERROR_DESC,
	BML_ERROR_NO,
	BML_ERROR_STEP,
	CUSTOMER_EMAIL_ADDRESS,
	CUSTOMER_IP_ADDRESS,
	BML_PROMO_CODE,
	BML_REASON_CODE,
	BILLING_CITY,
	BILLING_COUNTRY,
	BILLING_FIRSTNAME,
	BILLING_LASTNAME,
	BILLING_LINE1,
	BILLING_LINE2,
	BILLING_PHONE_NUMBER,
	BILLING_POSTAL_CODE,
	BILLING_STATE_PROVINCE,
	AUTHORIZATION_CODE,
	CARD_EXPIRY_MONTH,
	CARD_EXPIRY_YEAR,
	FAILURE_CODE,
	FAILURE_REASON,
	CARD_USER_NAME,
	CARD_LAST_DIGITS,
	PAYMENT_SERVICE_ID,
	REFERENCE_TRANSACTION_ID,
	PAYMENT_METHOD,
	CREDIT_CARD_TYPE_ID,
	PAYMENT_OPTION_ID,
	CUSTOMER_ORDER_ID,
	EXTERNAL_PAYMENT_ID,
	PAYPAL_PAYER_ID,
	PAYPAL_PAYER_EMAIL,
	ODS_CREATE_DATE,
	ODS_MODIFY_DATE
)
select
	SYS_GUID(),
	:v_sess_no, 
	rowid,
	'F', 
	'ODI-15066: The column AUDIT_MODIFY_DATE cannot be null.',
	sysdate,
	'(1393001)ODS_Project.LOAD_SAS_PAYMENT_STG_INT',
	'AUDIT_MODIFY_DATE',
	'NN',	
	PAYMENT_ID,
	AMOUNT,
	AUDIT_CREATE_DATE,
	AUDIT_CREATED_BY,
	AUDIT_MODIFIED_BY,
	AUDIT_MODIFY_DATE,
	BML_AUTH_CODE,
	BML_ORDER_ID,
	BML_STATUS,
	BML_ERROR_DESC,
	BML_ERROR_NO,
	BML_ERROR_STEP,
	CUSTOMER_EMAIL_ADDRESS,
	CUSTOMER_IP_ADDRESS,
	BML_PROMO_CODE,
	BML_REASON_CODE,
	BILLING_CITY,
	BILLING_COUNTRY,
	BILLING_FIRSTNAME,
	BILLING_LASTNAME,
	BILLING_LINE1,
	BILLING_LINE2,
	BILLING_PHONE_NUMBER,
	BILLING_POSTAL_CODE,
	BILLING_STATE_PROVINCE,
	AUTHORIZATION_CODE,
	CARD_EXPIRY_MONTH,
	CARD_EXPIRY_YEAR,
	FAILURE_CODE,
	FAILURE_REASON,
	CARD_USER_NAME,
	CARD_LAST_DIGITS,
	PAYMENT_SERVICE_ID,
	REFERENCE_TRANSACTION_ID,
	PAYMENT_METHOD,
	CREDIT_CARD_TYPE_ID,
	PAYMENT_OPTION_ID,
	CUSTOMER_ORDER_ID,
	EXTERNAL_PAYMENT_ID,
	PAYPAL_PAYER_ID,
	PAYPAL_PAYER_EMAIL,
	ODS_CREATE_DATE,
	ODS_MODIFY_DATE
from	RAX_APP_USER.I$_SAS_PAYMENT_STG1393001
where	AUDIT_MODIFY_DATE is null



&


/*-----------------------------------------------*/
/* TASK No. 28 */
/* insert Not Null errors */

insert into RAX_APP_USER.E$_SAS_PAYMENT_STG1393001
(
	ODI_PK,
	ODI_SESS_NO,
	ODI_ROW_ID,
	ODI_ERR_TYPE,
	ODI_ERR_MESS,
	ODI_CHECK_DATE,
	ODI_ORIGIN,
	ODI_CONS_NAME,
	ODI_CONS_TYPE,
	PAYMENT_ID,
	AMOUNT,
	AUDIT_CREATE_DATE,
	AUDIT_CREATED_BY,
	AUDIT_MODIFIED_BY,
	AUDIT_MODIFY_DATE,
	BML_AUTH_CODE,
	BML_ORDER_ID,
	BML_STATUS,
	BML_ERROR_DESC,
	BML_ERROR_NO,
	BML_ERROR_STEP,
	CUSTOMER_EMAIL_ADDRESS,
	CUSTOMER_IP_ADDRESS,
	BML_PROMO_CODE,
	BML_REASON_CODE,
	BILLING_CITY,
	BILLING_COUNTRY,
	BILLING_FIRSTNAME,
	BILLING_LASTNAME,
	BILLING_LINE1,
	BILLING_LINE2,
	BILLING_PHONE_NUMBER,
	BILLING_POSTAL_CODE,
	BILLING_STATE_PROVINCE,
	AUTHORIZATION_CODE,
	CARD_EXPIRY_MONTH,
	CARD_EXPIRY_YEAR,
	FAILURE_CODE,
	FAILURE_REASON,
	CARD_USER_NAME,
	CARD_LAST_DIGITS,
	PAYMENT_SERVICE_ID,
	REFERENCE_TRANSACTION_ID,
	PAYMENT_METHOD,
	CREDIT_CARD_TYPE_ID,
	PAYMENT_OPTION_ID,
	CUSTOMER_ORDER_ID,
	EXTERNAL_PAYMENT_ID,
	PAYPAL_PAYER_ID,
	PAYPAL_PAYER_EMAIL,
	ODS_CREATE_DATE,
	ODS_MODIFY_DATE
)
select
	SYS_GUID(),
	:v_sess_no, 
	rowid,
	'F', 
	'ODI-15066: The column CUSTOMER_ORDER_ID cannot be null.',
	sysdate,
	'(1393001)ODS_Project.LOAD_SAS_PAYMENT_STG_INT',
	'CUSTOMER_ORDER_ID',
	'NN',	
	PAYMENT_ID,
	AMOUNT,
	AUDIT_CREATE_DATE,
	AUDIT_CREATED_BY,
	AUDIT_MODIFIED_BY,
	AUDIT_MODIFY_DATE,
	BML_AUTH_CODE,
	BML_ORDER_ID,
	BML_STATUS,
	BML_ERROR_DESC,
	BML_ERROR_NO,
	BML_ERROR_STEP,
	CUSTOMER_EMAIL_ADDRESS,
	CUSTOMER_IP_ADDRESS,
	BML_PROMO_CODE,
	BML_REASON_CODE,
	BILLING_CITY,
	BILLING_COUNTRY,
	BILLING_FIRSTNAME,
	BILLING_LASTNAME,
	BILLING_LINE1,
	BILLING_LINE2,
	BILLING_PHONE_NUMBER,
	BILLING_POSTAL_CODE,
	BILLING_STATE_PROVINCE,
	AUTHORIZATION_CODE,
	CARD_EXPIRY_MONTH,
	CARD_EXPIRY_YEAR,
	FAILURE_CODE,
	FAILURE_REASON,
	CARD_USER_NAME,
	CARD_LAST_DIGITS,
	PAYMENT_SERVICE_ID,
	REFERENCE_TRANSACTION_ID,
	PAYMENT_METHOD,
	CREDIT_CARD_TYPE_ID,
	PAYMENT_OPTION_ID,
	CUSTOMER_ORDER_ID,
	EXTERNAL_PAYMENT_ID,
	PAYPAL_PAYER_ID,
	PAYPAL_PAYER_EMAIL,
	ODS_CREATE_DATE,
	ODS_MODIFY_DATE
from	RAX_APP_USER.I$_SAS_PAYMENT_STG1393001
where	CUSTOMER_ORDER_ID is null



&


/*-----------------------------------------------*/
/* TASK No. 29 */
/* create index on error table */

 
/* FLOW CONTROL CREATE INDEX ON THE E$TABLE */
-- create index 	RAX_APP_USER.E$_SAS_PAYMENT_STG1393001
-- on	RAX_APP_USER.E$_SAS_PAYMENT_STG1393001 (ODI_ROW_ID)

BEGIN
  EXECUTE IMMEDIATE 'create index RAX_APP_USER.E$_SAS_PAYMENT_STG1393001
on   RAX_APP_USER.E$_SAS_PAYMENT_STG1393001 (ODI_ROW_ID)';
EXCEPTION
  WHEN OTHERS THEN
   -- Handle the case where the identifier is too long (ORA-00972)
   IF SQLCODE = -972 or  SQLCODE = -1408 or SQLCODE = -955  THEN
     DBMS_OUTPUT.PUT_LINE('Identifier is too long. Skipping creation of index.');
   ELSE
     RAISE;
   END IF;
END;

&


/*-----------------------------------------------*/
/* TASK No. 30 */
/* delete errors from controlled table */

delete from	RAX_APP_USER.I$_SAS_PAYMENT_STG1393001  T
where	exists 	(
		select	1
		from	RAX_APP_USER.E$_SAS_PAYMENT_STG1393001 E
		where ODI_SESS_NO = :v_sess_no
		and T.rowid = E.ODI_ROW_ID
		)


&


/*-----------------------------------------------*/
/* TASK No. 31 */
/* insert check sum into check table */

insert into RAX_APP_USER.SNP_CHECK_TAB
(
	SCHEMA_NAME,
	RESOURCE_NAME,
	FULL_RES_NAME,
	ERR_TYPE,
	ERR_MESS,
	CHECK_DATE,
	ORIGIN,
	CONS_NAME,
	CONS_TYPE,
	ERR_COUNT
)
select	
	'ODS_STAGE',
	'SAS_PAYMENT_STG',
	'ODS_STAGE.SAS_PAYMENT_STG1393001',
	E.ODI_ERR_TYPE,
	E.ODI_ERR_MESS,
	E.ODI_CHECK_DATE,
	E.ODI_ORIGIN,
	E.ODI_CONS_NAME,
	E.ODI_CONS_TYPE,
	count(1) 
from	RAX_APP_USER.E$_SAS_PAYMENT_STG1393001 E
where	E.ODI_ERR_TYPE	= 'F'
and	E.ODI_ORIGIN 	= '(1393001)ODS_Project.LOAD_SAS_PAYMENT_STG_INT'
group by	E.ODI_ERR_TYPE,
	E.ODI_ERR_MESS,
	E.ODI_CHECK_DATE,
	E.ODI_ORIGIN,
	E.ODI_CONS_NAME,
	E.ODI_CONS_TYPE


&


/*-----------------------------------------------*/
/* TASK No. 32 */
/* Merge Rows */

merge into	ODS_STAGE.SAS_PAYMENT_STG T
using	RAX_APP_USER.I$_SAS_PAYMENT_STG1393001 S
on	(
		T.PAYMENT_ID=S.PAYMENT_ID
	)
when matched
then update set
	T.AMOUNT	= S.AMOUNT,
	T.AUDIT_CREATE_DATE	= S.AUDIT_CREATE_DATE,
	T.AUDIT_CREATED_BY	= S.AUDIT_CREATED_BY,
	T.AUDIT_MODIFIED_BY	= S.AUDIT_MODIFIED_BY,
	T.AUDIT_MODIFY_DATE	= S.AUDIT_MODIFY_DATE,
	T.BML_AUTH_CODE	= S.BML_AUTH_CODE,
	T.BML_ORDER_ID	= S.BML_ORDER_ID,
	T.BML_STATUS	= S.BML_STATUS,
	T.BML_ERROR_DESC	= S.BML_ERROR_DESC,
	T.BML_ERROR_NO	= S.BML_ERROR_NO,
	T.BML_ERROR_STEP	= S.BML_ERROR_STEP,
	T.CUSTOMER_EMAIL_ADDRESS	= S.CUSTOMER_EMAIL_ADDRESS,
	T.CUSTOMER_IP_ADDRESS	= S.CUSTOMER_IP_ADDRESS,
	T.BML_PROMO_CODE	= S.BML_PROMO_CODE,
	T.BML_REASON_CODE	= S.BML_REASON_CODE,
	T.BILLING_CITY	= S.BILLING_CITY,
	T.BILLING_COUNTRY	= S.BILLING_COUNTRY,
	T.BILLING_FIRSTNAME	= S.BILLING_FIRSTNAME,
	T.BILLING_LASTNAME	= S.BILLING_LASTNAME,
	T.BILLING_LINE1	= S.BILLING_LINE1,
	T.BILLING_LINE2	= S.BILLING_LINE2,
	T.BILLING_PHONE_NUMBER	= S.BILLING_PHONE_NUMBER,
	T.BILLING_POSTAL_CODE	= S.BILLING_POSTAL_CODE,
	T.BILLING_STATE_PROVINCE	= S.BILLING_STATE_PROVINCE,
	T.AUTHORIZATION_CODE	= S.AUTHORIZATION_CODE,
	T.CARD_EXPIRY_MONTH	= S.CARD_EXPIRY_MONTH,
	T.CARD_EXPIRY_YEAR	= S.CARD_EXPIRY_YEAR,
	T.FAILURE_CODE	= S.FAILURE_CODE,
	T.FAILURE_REASON	= S.FAILURE_REASON,
	T.CARD_USER_NAME	= S.CARD_USER_NAME,
	T.CARD_LAST_DIGITS	= S.CARD_LAST_DIGITS,
	T.PAYMENT_SERVICE_ID	= S.PAYMENT_SERVICE_ID,
	T.REFERENCE_TRANSACTION_ID	= S.REFERENCE_TRANSACTION_ID,
	T.PAYMENT_METHOD	= S.PAYMENT_METHOD,
	T.CREDIT_CARD_TYPE_ID	= S.CREDIT_CARD_TYPE_ID,
	T.PAYMENT_OPTION_ID	= S.PAYMENT_OPTION_ID,
	T.CUSTOMER_ORDER_ID	= S.CUSTOMER_ORDER_ID,
	T.EXTERNAL_PAYMENT_ID	= S.EXTERNAL_PAYMENT_ID,
	T.PAYPAL_PAYER_ID	= S.PAYPAL_PAYER_ID,
	T.PAYPAL_PAYER_EMAIL	= S.PAYPAL_PAYER_EMAIL
	,                                        T.ODS_MODIFY_DATE	= sysdate
when not matched
then insert
	(
	T.PAYMENT_ID,
	T.AMOUNT,
	T.AUDIT_CREATE_DATE,
	T.AUDIT_CREATED_BY,
	T.AUDIT_MODIFIED_BY,
	T.AUDIT_MODIFY_DATE,
	T.BML_AUTH_CODE,
	T.BML_ORDER_ID,
	T.BML_STATUS,
	T.BML_ERROR_DESC,
	T.BML_ERROR_NO,
	T.BML_ERROR_STEP,
	T.CUSTOMER_EMAIL_ADDRESS,
	T.CUSTOMER_IP_ADDRESS,
	T.BML_PROMO_CODE,
	T.BML_REASON_CODE,
	T.BILLING_CITY,
	T.BILLING_COUNTRY,
	T.BILLING_FIRSTNAME,
	T.BILLING_LASTNAME,
	T.BILLING_LINE1,
	T.BILLING_LINE2,
	T.BILLING_PHONE_NUMBER,
	T.BILLING_POSTAL_CODE,
	T.BILLING_STATE_PROVINCE,
	T.AUTHORIZATION_CODE,
	T.CARD_EXPIRY_MONTH,
	T.CARD_EXPIRY_YEAR,
	T.FAILURE_CODE,
	T.FAILURE_REASON,
	T.CARD_USER_NAME,
	T.CARD_LAST_DIGITS,
	T.PAYMENT_SERVICE_ID,
	T.REFERENCE_TRANSACTION_ID,
	T.PAYMENT_METHOD,
	T.CREDIT_CARD_TYPE_ID,
	T.PAYMENT_OPTION_ID,
	T.CUSTOMER_ORDER_ID,
	T.EXTERNAL_PAYMENT_ID,
	T.PAYPAL_PAYER_ID,
	T.PAYPAL_PAYER_EMAIL
	,                                         T.ODS_CREATE_DATE,
	T.ODS_MODIFY_DATE
	)
values
	(
	S.PAYMENT_ID,
	S.AMOUNT,
	S.AUDIT_CREATE_DATE,
	S.AUDIT_CREATED_BY,
	S.AUDIT_MODIFIED_BY,
	S.AUDIT_MODIFY_DATE,
	S.BML_AUTH_CODE,
	S.BML_ORDER_ID,
	S.BML_STATUS,
	S.BML_ERROR_DESC,
	S.BML_ERROR_NO,
	S.BML_ERROR_STEP,
	S.CUSTOMER_EMAIL_ADDRESS,
	S.CUSTOMER_IP_ADDRESS,
	S.BML_PROMO_CODE,
	S.BML_REASON_CODE,
	S.BILLING_CITY,
	S.BILLING_COUNTRY,
	S.BILLING_FIRSTNAME,
	S.BILLING_LASTNAME,
	S.BILLING_LINE1,
	S.BILLING_LINE2,
	S.BILLING_PHONE_NUMBER,
	S.BILLING_POSTAL_CODE,
	S.BILLING_STATE_PROVINCE,
	S.AUTHORIZATION_CODE,
	S.CARD_EXPIRY_MONTH,
	S.CARD_EXPIRY_YEAR,
	S.FAILURE_CODE,
	S.FAILURE_REASON,
	S.CARD_USER_NAME,
	S.CARD_LAST_DIGITS,
	S.PAYMENT_SERVICE_ID,
	S.REFERENCE_TRANSACTION_ID,
	S.PAYMENT_METHOD,
	S.CREDIT_CARD_TYPE_ID,
	S.PAYMENT_OPTION_ID,
	S.CUSTOMER_ORDER_ID,
	S.EXTERNAL_PAYMENT_ID,
	S.PAYPAL_PAYER_ID,
	S.PAYPAL_PAYER_EMAIL
	,                                         sysdate,
	sysdate
	)

&


/*-----------------------------------------------*/
/* TASK No. 33 */
/* Commit transaction */

/*commit*/


/*-----------------------------------------------*/
/* TASK No. 34 */
/* Drop flow table */

-- drop table RAX_APP_USER.I$_SAS_PAYMENT_STG1393001

BEGIN
  EXECUTE IMMEDIATE 'drop table RAX_APP_USER.I$_SAS_PAYMENT_STG1393001';
EXCEPTION
  WHEN OTHERS THEN
   IF SQLCODE != -942 THEN
     RAISE;
   END IF;
END;


&


/*-----------------------------------------------*/
/* TASK No. 1000008 */
/* Drop work table */

-- drop table RAX_APP_USER.C$_0SAS_PAYMENT_STG purge

BEGIN
  EXECUTE IMMEDIATE 'drop table RAX_APP_USER.C$_0SAS_PAYMENT_STG purge';
EXCEPTION
  WHEN OTHERS THEN
   IF SQLCODE != -942 THEN
     RAISE;
   END IF;
END;


&


/*-----------------------------------------------*/
/* TASK No. 35 */
/* MERGE INTO ODS_STAGE.SAS_PAYMENT_XR */

-- SAS_PAYMENT_XR
MERGE INTO ODS_STAGE.SAS_PAYMENT_XR d
USING (
select * from
    (  Select
        XR.PAYMENT_OID PAYMENT_OID,
        STG.PAYMENT_ID as SK_PAYMENT_ID,
        STG.EXTERNAL_PAYMENT_ID as SK_EXTERNAL_PAYMENT_ID,
        sysdate as ODS_CREATE_DATE,
        sysdate as ODS_MODIFY_DATE,
        STG.CUSTOMER_ORDER_ID  as SK_CUSTOMER_ORDER_ID	
    -- select *
    FROM 
        ODS_STAGE.SAS_PAYMENT_STG stg
        ,ODS_STAGE.SAS_PAYMENT_XR xr
    WHERE (1=1)
        and stg.ODS_MODIFY_DATE >= TO_DATE(SUBSTR(:v_cdc_load_date, 1, 19), 'YYYY-MM-DD HH24:MI:SS')  -:v_cdc_overlap
        and STG.PAYMENT_ID=XR.SK_PAYMENT_ID(+)
     ) s
where NOT EXISTS 
	( select 1 from ODS_STAGE.SAS_PAYMENT_XR T
	where	T.SK_PAYMENT_ID	= S.SK_PAYMENT_ID 
		 and
		((T.PAYMENT_OID = S.PAYMENT_OID) or (T.PAYMENT_OID IS NULL and S.PAYMENT_OID IS NULL)) and
		((T.SK_PAYMENT_ID = S.SK_PAYMENT_ID) or (T.SK_PAYMENT_ID IS NULL and S.SK_PAYMENT_ID IS NULL)) and
		((T.SK_EXTERNAL_PAYMENT_ID = S.SK_EXTERNAL_PAYMENT_ID) or (T.SK_EXTERNAL_PAYMENT_ID IS NULL and S.SK_EXTERNAL_PAYMENT_ID IS NULL))  and
		((T.SK_CUSTOMER_ORDER_ID = S.SK_CUSTOMER_ORDER_ID) or (T.SK_CUSTOMER_ORDER_ID IS NULL and S.SK_CUSTOMER_ORDER_ID IS NULL))
		        )
) s 
ON
  (s.SK_PAYMENT_ID=d.SK_PAYMENT_ID)
WHEN MATCHED
THEN
UPDATE SET
  d.PAYMENT_OID = s.PAYMENT_OID,
--  d.SK_PAYMENT_ID = s.SK_PAYMENT_ID,
  d.SK_EXTERNAL_PAYMENT_ID = s.SK_EXTERNAL_PAYMENT_ID,
  d.SK_CUSTOMER_ORDER_ID =s.SK_CUSTOMER_ORDER_ID,
  d.ODS_MODIFY_DATE = s.ODS_MODIFY_DATE
WHEN NOT MATCHED
THEN
INSERT (
  PAYMENT_OID, SK_PAYMENT_ID, SK_EXTERNAL_PAYMENT_ID,
   ODS_CREATE_DATE, ODS_MODIFY_DATE,SK_CUSTOMER_ORDER_ID)
VALUES (
  ODS_STAGE.PAYMENT_OID_SEQ.nextval, s.SK_PAYMENT_ID, s.SK_EXTERNAL_PAYMENT_ID,
   s.ODS_CREATE_DATE, s.ODS_MODIFY_DATE,s.SK_CUSTOMER_ORDER_ID
  )

&


/*-----------------------------------------------*/
/* TASK No. 36 */
/* MERGE INTO ODS_OWN.SAS_PAYMENT */

MERGE INTO ODS_OWN.SAS_PAYMENT d
USING (
select * from (
      Select
        XR.PAYMENT_OID as PAYMENT_OID,
        STG.EXTERNAL_PAYMENT_ID as EXTERNAL_PAYMENT_ID,
        STG.AMOUNT as AMOUNT,
        STG.AUDIT_CREATE_DATE as AUDIT_CREATE_DATE,
        STG.AUDIT_CREATED_BY as AUDIT_CREATED_BY,
        STG.AUDIT_MODIFY_DATE as AUDIT_MODIFY_DATE,
        STG.AUDIT_MODIFIED_BY as AUDIT_MODIFIED_BY,
        STG.BML_AUTH_CODE as BML_AUTH_CODE,
        STG.BML_ORDER_ID as BML_ORDER_ID,
        SS.SOURCE_SYSTEM_OID as SOURCE_SYSTEM_OID,
        sysdate as ODS_CREATE_DATE,
        sysdate as ODS_MODIFY_DATE,
        STG.BML_STATUS AS BML_STATUS,
    STG.BML_ERROR_DESC AS BML_ERROR_DESC,
    STG.BML_ERROR_NO AS BML_ERROR_NO,
    STG.BML_ERROR_STEP AS BML_ERROR_STEP,
    STG.CUSTOMER_EMAIL_ADDRESS as CUSTOMER_EMAIL_ADDRESS,
    STG.CUSTOMER_IP_ADDRESS AS CUSTOMER_IP_ADDRESS,
    STG.BML_PROMO_CODE AS BML_PROMO_CODE,
    STG.BML_REASON_CODE AS BML_REASON_CODE,
    STG.BILLING_CITY AS BILLING_CITY,
    STG.BILLING_COUNTRY as BILLING_COUNTRY,
    STG.BILLING_FIRSTNAME        ,
      STG.BILLING_LASTNAME           ,
    STG.BILLING_LINE1              ,
      STG.BILLING_LINE2              ,
      STG.BILLING_PHONE_NUMBER       ,
      STG.BILLING_POSTAL_CODE        ,
      STG.BILLING_STATE_PROVINCE   ,
      STG.AUTHORIZATION_CODE         ,
      STG.CARD_EXPIRY_MONTH         ,
      STG.CARD_EXPIRY_YEAR          ,
      STG.FAILURE_CODE               ,
      STG.FAILURE_REASON             ,
      STG.CARD_USER_NAME             ,
      STG.CARD_LAST_DIGITS           ,
      STG.PAYMENT_SERVICE_ID         ,
      STG.REFERENCE_TRANSACTION_ID   ,
      STG.PAYMENT_METHOD             ,
      STG.CREDIT_CARD_TYPE_ID       ,
      STG.PAYMENT_OPTION_ID         ,
      STG.CUSTOMER_ORDER_ID          ,
      STG.PAYPAL_PAYER_ID            ,
      STG.PAYPAL_PAYER_EMAIL    ,     
      cox.CUSTOMER_ORDER_OID
-- select *
    from
        ODS_STAGE.SAS_PAYMENT_STG stg
        ,ODS_STAGE.SAS_PAYMENT_XR xr
        ,ODS_OWN.SOURCE_SYSTEM SS
        ,ODS_STAGE.SAS_CUSTOMER_ORDER_XR cox
    where (1=1)
        and stg.ODS_MODIFY_DATE >= TO_DATE(SUBSTR(:v_cdc_load_date, 1, 19), 'YYYY-MM-DD HH24:MI:SS')  -:v_cdc_overlap
        and SS.SOURCE_SYSTEM_SHORT_NAME='SAS'
        and STG.PAYMENT_ID=XR.SK_PAYMENT_ID(+)
        and xr.SK_CUSTOMER_ORDER_ID = cox.SK_CUSTOMER_ORDER_ID(+)
        --and XR.SK_EXTERNAL_PAYMENT_ID=Stg.EXTERNAL_PAYMENT_ID(+)
     ) s
where NOT EXISTS 
    ( select 1 from ODS_OWN.SAS_PAYMENT T
    where    T.PAYMENT_OID    = S.PAYMENT_OID 
         and ((T.PAYMENT_OID = S.PAYMENT_OID) or (T.PAYMENT_OID IS NULL and S.PAYMENT_OID IS NULL)) and
        ((T.EXTERNAL_PAYMENT_ID = S.EXTERNAL_PAYMENT_ID) or (T.EXTERNAL_PAYMENT_ID IS NULL and S.EXTERNAL_PAYMENT_ID IS NULL)) and
        ((T.BML_AUTH_CODE = S.BML_AUTH_CODE) or (T.BML_AUTH_CODE IS NULL and S.BML_AUTH_CODE IS NULL)) and
    ((T.BML_ORDER_ID = S.BML_ORDER_ID) or (T.BML_ORDER_ID IS NULL and S.BML_ORDER_ID IS NULL)) and
    ((T.BML_STATUS = S.BML_STATUS) or (T.BML_STATUS IS NULL and S.BML_STATUS IS NULL)) and
    ((T.BML_ERROR_DESC = S.BML_ERROR_DESC) or (T.BML_ERROR_DESC IS NULL and S.BML_ERROR_DESC IS NULL)) and
    ((T.BML_ERROR_NO = S.BML_ERROR_NO) or (T.BML_ERROR_NO IS NULL and S.BML_ERROR_NO IS NULL)) and
    ((T.BML_ERROR_STEP = S.BML_ERROR_STEP) or (T.BML_ERROR_STEP IS NULL and S.BML_ERROR_STEP IS NULL)) and
    ((T.CUSTOMER_EMAIL_ADDRESS = S.CUSTOMER_EMAIL_ADDRESS) or (T.CUSTOMER_EMAIL_ADDRESS IS NULL and S.CUSTOMER_EMAIL_ADDRESS IS NULL)) and
    ((T.CUSTOMER_IP_ADDRESS = S.CUSTOMER_IP_ADDRESS) or (T.CUSTOMER_IP_ADDRESS IS NULL and S.CUSTOMER_IP_ADDRESS IS NULL)) and
    ((T.BML_PROMO_CODE = S.BML_PROMO_CODE) or (T.BML_PROMO_CODE IS NULL and S.BML_PROMO_CODE IS NULL)) and
    ((T.BML_REASON_CODE = S.BML_REASON_CODE) or (T.BML_REASON_CODE IS NULL and S.BML_REASON_CODE IS NULL)) and
    ((T.BILLING_CITY = S.BILLING_CITY) or (T.BILLING_CITY IS NULL and S.BILLING_CITY IS NULL)) and
    ((T.BILLING_COUNTRY = S.BILLING_COUNTRY) or (T.BILLING_COUNTRY IS NULL and S.BILLING_COUNTRY IS NULL)) and
    ((T.BILLING_FIRSTNAME = S.BILLING_FIRSTNAME) or (T.BILLING_FIRSTNAME IS NULL and S.BILLING_FIRSTNAME IS NULL)) and
    ((T.BILLING_LASTNAME = S.BILLING_LASTNAME) or (T.BILLING_LASTNAME IS NULL and S.BILLING_LASTNAME IS NULL)) and
    ((T.BILLING_LINE1 = S.BILLING_LINE1) or (T.BILLING_LINE1 IS NULL and S.BILLING_LINE1 IS NULL)) and
    ((T.BILLING_LINE2 = S.BILLING_LINE2) or (T.BILLING_LINE2 IS NULL and S.BILLING_LINE2 IS NULL)) and
    ((T.BILLING_PHONE_NUMBER = S.BILLING_PHONE_NUMBER) or (T.BILLING_PHONE_NUMBER IS NULL and S.BILLING_PHONE_NUMBER IS NULL)) and
    ((T.BILLING_POSTAL_CODE = S.BILLING_POSTAL_CODE) or (T.BILLING_POSTAL_CODE IS NULL and S.BILLING_POSTAL_CODE IS NULL)) and
    ((T.BILLING_STATE_PROVINCE = S.BILLING_STATE_PROVINCE) or (T.BILLING_STATE_PROVINCE IS NULL and S.BILLING_STATE_PROVINCE IS NULL)) and
    ((T.AUTHORIZATION_CODE = S.AUTHORIZATION_CODE) or (T.AUTHORIZATION_CODE IS NULL and S.AUTHORIZATION_CODE IS NULL)) and
    ((T.CARD_EXPIRY_MONTH = S.CARD_EXPIRY_MONTH) or (T.CARD_EXPIRY_MONTH IS NULL and S.CARD_EXPIRY_MONTH IS NULL)) and
    ((T.CARD_EXPIRY_YEAR = S.CARD_EXPIRY_YEAR) or (T.CARD_EXPIRY_YEAR IS NULL and S.CARD_EXPIRY_YEAR IS NULL)) and
    ((T.FAILURE_CODE = S.FAILURE_CODE) or (T.FAILURE_CODE IS NULL and S.FAILURE_CODE IS NULL)) and
    ((T.FAILURE_REASON = S.FAILURE_REASON) or (T.FAILURE_REASON IS NULL and S.FAILURE_REASON IS NULL)) and
    ((T.CARD_USER_NAME = S.CARD_USER_NAME) or (T.CARD_USER_NAME IS NULL and S.CARD_USER_NAME IS NULL)) and
    ((T.CARD_LAST_DIGITS = S.CARD_LAST_DIGITS) or (T.CARD_LAST_DIGITS IS NULL and S.CARD_LAST_DIGITS IS NULL)) and
    ((T.PAYMENT_SERVICE_ID = S.PAYMENT_SERVICE_ID) or (T.PAYMENT_SERVICE_ID IS NULL and S.PAYMENT_SERVICE_ID IS NULL)) and
    ((T.REFERENCE_TRANSACTION_ID = S.REFERENCE_TRANSACTION_ID) or (T.REFERENCE_TRANSACTION_ID IS NULL and S.REFERENCE_TRANSACTION_ID IS NULL)) and
    ((T.PAYMENT_METHOD = S.PAYMENT_METHOD) or (T.PAYMENT_METHOD IS NULL and S.PAYMENT_METHOD IS NULL)) and
    ((T.CREDIT_CARD_TYPE_ID = S.CREDIT_CARD_TYPE_ID) or (T.CREDIT_CARD_TYPE_ID IS NULL and S.CREDIT_CARD_TYPE_ID IS NULL)) and
    ((T.PAYMENT_OPTION_ID = S.PAYMENT_OPTION_ID) or (T.PAYMENT_OPTION_ID IS NULL and S.PAYMENT_OPTION_ID IS NULL)) and
    ((T.CUSTOMER_ORDER_ID = S.CUSTOMER_ORDER_ID) or (T.CUSTOMER_ORDER_ID IS NULL and S.CUSTOMER_ORDER_ID IS NULL)) and
    ((T.PAYPAL_PAYER_ID = S.PAYPAL_PAYER_ID) or (T.PAYPAL_PAYER_ID IS NULL and S.PAYPAL_PAYER_ID IS NULL)) and
    ((T.PAYPAL_PAYER_EMAIL = S.PAYPAL_PAYER_EMAIL) or (T.PAYPAL_PAYER_EMAIL IS NULL and S.PAYPAL_PAYER_EMAIL IS NULL)) and
        ((T.AUDIT_CREATE_DATE = S.AUDIT_CREATE_DATE) or (T.AUDIT_CREATE_DATE IS NULL and S.AUDIT_CREATE_DATE IS NULL)) and
        ((T.AUDIT_CREATED_BY = S.AUDIT_CREATED_BY) or (T.AUDIT_CREATED_BY IS NULL and S.AUDIT_CREATED_BY IS NULL)) and
        ((T.AUDIT_MODIFY_DATE = S.AUDIT_MODIFY_DATE) or (T.AUDIT_MODIFY_DATE IS NULL and S.AUDIT_MODIFY_DATE IS NULL)) and
        ((T.AUDIT_MODIFIED_BY = S.AUDIT_MODIFIED_BY) or (T.AUDIT_MODIFIED_BY IS NULL and S.AUDIT_MODIFIED_BY IS NULL)) and
((T.AMOUNT = S.AMOUNT) or (T.AMOUNT IS NULL and S.AMOUNT IS NULL))  and
        ((T.SOURCE_SYSTEM_OID = S.SOURCE_SYSTEM_OID) or (T.SOURCE_SYSTEM_OID IS NULL and S.SOURCE_SYSTEM_OID IS NULL)) 
        and
        ((T.CUSTOMER_ORDER_OID = S.CUSTOMER_ORDER_OID) or (T.CUSTOMER_ORDER_OID IS NULL and S.CUSTOMER_ORDER_OID IS NULL))
        ) 
) s 
ON
  (d.PAYMENT_OID = s.PAYMENT_OID)
WHEN MATCHED
THEN
UPDATE SET
d.BML_ORDER_ID = s.BML_ORDER_ID  ,
d.BML_STATUS   =s.BML_STATUS  ,
d.BML_ERROR_DESC =s.BML_ERROR_DESC ,
d.BML_ERROR_NO =s.BML_ERROR_NO  ,
d.BML_ERROR_STEP =s.BML_ERROR_STEP  ,
d.CUSTOMER_EMAIL_ADDRESS =s.CUSTOMER_EMAIL_ADDRESS    ,
d.CUSTOMER_IP_ADDRESS = s.CUSTOMER_IP_ADDRESS  ,
d.BML_PROMO_CODE =s.BML_PROMO_CODE            ,
d.BML_REASON_CODE  = s.BML_REASON_CODE          ,
d.BILLING_CITY =s.BILLING_CITY  ,
d.BILLING_COUNTRY = s.BILLING_COUNTRY  ,
d.BILLING_FIRSTNAME =s.BILLING_FIRSTNAME    ,
d.BILLING_LASTNAME  =s.BILLING_LASTNAME         ,
d.BILLING_LINE1 =s.BILLING_LINE1             ,
d.BILLING_LINE2 =s.BILLING_LINE2             ,
d.BILLING_PHONE_NUMBER =s.BILLING_PHONE_NUMBER       ,
d.BILLING_POSTAL_CODE  =s.BILLING_POSTAL_CODE      ,
d.BILLING_STATE_PROVINCE =s.BILLING_STATE_PROVINCE    ,
d.AUTHORIZATION_CODE =s.AUTHORIZATION_CODE        ,
d.CARD_EXPIRY_MONTH =s.CARD_EXPIRY_MONTH        ,
d.CARD_EXPIRY_YEAR =s.CARD_EXPIRY_YEAR         ,
d.FAILURE_CODE =s.FAILURE_CODE              ,
d.FAILURE_REASON =s.FAILURE_REASON            ,
d.CARD_USER_NAME =s.CARD_USER_NAME            ,
d.CARD_LAST_DIGITS =s.CARD_LAST_DIGITS          ,
d.PAYMENT_SERVICE_ID =s.PAYMENT_SERVICE_ID        ,
d.REFERENCE_TRANSACTION_ID =s.REFERENCE_TRANSACTION_ID ,
d.PAYMENT_METHOD =s.PAYMENT_METHOD            ,
d.CREDIT_CARD_TYPE_ID =s.CREDIT_CARD_TYPE_ID      ,
d.PAYMENT_OPTION_ID =s.PAYMENT_OPTION_ID        ,
d.CUSTOMER_ORDER_ID =s.CUSTOMER_ORDER_ID                  ,
d.EXTERNAL_PAYMENT_ID =s.EXTERNAL_PAYMENT_ID      ,
d.PAYPAL_PAYER_ID =s.PAYPAL_PAYER_ID           ,
d.PAYPAL_PAYER_EMAIL =s.PAYPAL_PAYER_EMAIL        ,
d.AUDIT_CREATE_DATE = s.AUDIT_CREATE_DATE,
d.AUDIT_CREATED_BY = s.AUDIT_CREATED_BY,
d.AUDIT_MODIFY_DATE = s.AUDIT_MODIFY_DATE,
d.AUDIT_MODIFIED_BY = s.AUDIT_MODIFIED_BY,
d.ODS_MODIFY_DATE = s.ODS_MODIFY_DATE,
d.SOURCE_SYSTEM_OID = s.SOURCE_SYSTEM_OID,
d.AMOUNT =s.AMOUNT,
d.CUSTOMER_ORDER_OID = s.CUSTOMER_ORDER_OID
WHEN NOT MATCHED
THEN
INSERT (
  PAYMENT_OID, EXTERNAL_PAYMENT_ID,AMOUNT,BML_AUTH_CODE,BML_ORDER_ID,BML_STATUS, BML_ERROR_DESC,BML_ERROR_NO,
   AUDIT_CREATE_DATE,BML_ERROR_STEP,CUSTOMER_EMAIL_ADDRESS,CUSTOMER_IP_ADDRESS,BML_PROMO_CODE,BML_REASON_CODE,BILLING_CITY,BILLING_COUNTRY,
  AUDIT_CREATED_BY, AUDIT_MODIFY_DATE, AUDIT_MODIFIED_BY,BILLING_FIRSTNAME,BILLING_LASTNAME,BILLING_LINE1,BILLING_LINE2,BILLING_PHONE_NUMBER,
  SOURCE_SYSTEM_OID, ODS_CREATE_DATE,BILLING_POSTAL_CODE,BILLING_STATE_PROVINCE,AUTHORIZATION_CODE,CARD_EXPIRY_MONTH,CARD_EXPIRY_YEAR,
  ODS_MODIFY_DATE,FAILURE_CODE,FAILURE_REASON,CARD_USER_NAME,CARD_LAST_DIGITS,PAYMENT_SERVICE_ID,REFERENCE_TRANSACTION_ID,PAYMENT_METHOD ,CREDIT_CARD_TYPE_ID  
,PAYMENT_OPTION_ID,CUSTOMER_ORDER_ID,PAYPAL_PAYER_ID,PAYPAL_PAYER_EMAIL,CUSTOMER_ORDER_OID)
VALUES (
  s.PAYMENT_OID, s.EXTERNAL_PAYMENT_ID,s.AMOUNT ,s.BML_AUTH_CODE,s.BML_ORDER_ID,s.BML_STATUS, s.BML_ERROR_DESC,s.BML_ERROR_NO,
  s.AUDIT_CREATE_DATE,s.BML_ERROR_STEP,s.CUSTOMER_EMAIL_ADDRESS,s.CUSTOMER_IP_ADDRESS,s.BML_PROMO_CODE,s.BML_REASON_CODE,s.BILLING_CITY,s.BILLING_COUNTRY,
  s.AUDIT_CREATED_BY, s.AUDIT_MODIFY_DATE, s.AUDIT_MODIFIED_BY,s.BILLING_FIRSTNAME,s.BILLING_LASTNAME,s.BILLING_LINE1,s.BILLING_LINE2,s.BILLING_PHONE_NUMBER,
  s.SOURCE_SYSTEM_OID, s.ODS_CREATE_DATE,s.BILLING_POSTAL_CODE,s.BILLING_STATE_PROVINCE,s.AUTHORIZATION_CODE,s.CARD_EXPIRY_MONTH,s.CARD_EXPIRY_YEAR,
  s.ODS_MODIFY_DATE,s.FAILURE_CODE,s.FAILURE_REASON ,s.CARD_USER_NAME,s.CARD_LAST_DIGITS,s.PAYMENT_SERVICE_ID,s.REFERENCE_TRANSACTION_ID,s.PAYMENT_METHOD,s.CREDIT_CARD_TYPE_ID,s.PAYMENT_OPTION_ID,s.CUSTOMER_ORDER_ID    
,s.PAYPAL_PAYER_ID,s.PAYPAL_PAYER_EMAIL,s.CUSTOMER_ORDER_OID
 )

&


/*-----------------------------------------------*/
/* TASK No. 37 */
/* Update CDC Load Status */

UPDATE ODS_OWN.ODS_CDC_LOAD_STATUS
SET LAST_CDC_COMPLETION_DATE=TO_DATE(
             SUBSTR(:v_sess_beg, 1, 19), 'RRRR-MM-DD HH24:MI:SS')
+ nvl((TIMEZONE_OFFSET/24), 0) 
WHERE ODS_TABLE_NAME=:v_cdc_load_table_name
AND CONTEXT_NAME = :v_env

/*
UPDATE ODS_OWN.ODS_CDC_LOAD_STATUS
SET LAST_CDC_COMPLETION_DATE=TO_DATE(
             SUBSTR(:v_sess_beg, 1, 19), 'RRRR-MM-DD HH24:MI:SS')
WHERE ODS_TABLE_NAME=:v_cdc_load_table_name
AND CONTEXT_NAME = :v_env
*/

&


/*-----------------------------------------------*/
/* TASK No. 38 */
/* Insert CDC Audit Record */

INSERT INTO RAX_APP_USER.ODS_CDC_LOAD_STATUS_AUDIT
(TABLE_NAME,
SESS_NO,                      
SESS_NAME,                    
SCEN_VERSION,                 
SESS_BEG,                     
ORIG_LAST_CDC_COMPLETION_DATE,
OVERLAP,
CREATE_DATE,
CONTEXT_NAME,
TIMEZONE_OFFSET              
)
select 
:v_cdc_load_table_name
,:v_sess_no
,'LOAD_SAS_PAYMENT_PKG'
,'007'
,TO_DATE(SUBSTR(:v_sess_beg, 1, 19), 'RRRR-MM-DD HH24:MI:SS')
,TO_DATE (SUBSTR(:v_cdc_load_date, 1, 19),'YYYY-MM-DD HH24:MI:SS')
,:v_cdc_overlap
,SYSDATE
,:v_env
,TIMEZONE_OFFSET
from 
ODS_OWN.ODS_CDC_LOAD_STATUS
WHERE ODS_TABLE_NAME=:v_cdc_load_table_name
AND CONTEXT_NAME = :v_env

/*
INSERT INTO RAX_APP_USER.ODS_CDC_LOAD_STATUS_AUDIT
(TABLE_NAME,
SESS_NO,                      
SESS_NAME,                    
SCEN_VERSION,                 
SESS_BEG,                     
ORIG_LAST_CDC_COMPLETION_DATE,
OVERLAP,
CREATE_DATE,
CONTEXT_NAME              
)
values (
:v_cdc_load_table_name,
:v_sess_no,
'LOAD_SAS_PAYMENT_PKG',
'007',
TO_DATE(
             SUBSTR(:v_sess_beg, 1, 19), 'RRRR-MM-DD HH24:MI:SS'),
TO_DATE (SUBSTR (:v_cdc_load_date, 1, 19),
                           'YYYY-MM-DD HH24:MI:SS'
                          )
,:v_cdc_overlap,
SYSDATE,
 :v_env)
*/


&


/*-----------------------------------------------*/
