/* TASK No. 1 */

/* NONE or SET VARIABLE STATEMENT FOUND, CHECK ODI TASK NO. 1 */




/*-----------------------------------------------*/
/* TASK No. 2 */

/* SELECT STATEMENT FOUND, CHECK ODI TASK NO. 2 */




/*-----------------------------------------------*/
/* TASK No. 3 */

/* SELECT STATEMENT FOUND, CHECK ODI TASK NO. 3 */




/*-----------------------------------------------*/
/* TASK No. 4 */
/* Drop work table */

-- drop table RAX_APP_USER.C$_0SAS_CUST_ORDER_STG purge

-- &


/*-----------------------------------------------*/
/* TASK No. 5 */
/* Create work table */

-- create table RAX_APP_USER.C$_0SAS_CUST_ORDER_STG
-- (
-- 	C1_CUSTOMER_ORDER_ID	NUMBER(10) NULL,
-- 	C2_ADDRESSES_SAME	NUMBER(1) NULL,
-- 	C3_AUDIT_CREATE_DATE	TIMESTAMP(6) NULL,
-- 	C4_AUDIT_CREATED_BY	VARCHAR2(255) NULL,
-- 	C5_AUDIT_MODIFIED_BY	VARCHAR2(255) NULL,
-- 	C6_AUDIT_MODIFY_DATE	TIMESTAMP(6) NULL,
-- 	C7_COD_LIST_AMOUNT	NUMBER(19,2) NULL,
-- 	C8_COD_TAX_RATE	NUMBER(10,10) NULL,
-- 	C9_COD_TAX	NUMBER(19,2) NULL,
-- 	C10_COD_TAX_DATE	VARCHAR2(255) NULL,
-- 	C11_CURRENCY_CODE	VARCHAR2(3) NULL,
-- 	C12_CURRENT_STATUS_CODE	VARCHAR2(1) NULL,
-- 	C13_ORDER_DATE	TIMESTAMP(6) NULL,
-- 	C14_LIFETOUCH_USER_PROFILE_ID	VARCHAR2(255) NULL,
-- 	C15_ORDER_NUMBER	VARCHAR2(255) NULL,
-- 	C16_PROOF_DEPOSIT_APPLIED	NUMBER(19,2) NULL,
-- 	C17_PROOF_DEPOSIT_TOTAL	NUMBER(19,2) NULL,
-- 	C18_SHIPPING_DISCOUNT	NUMBER(19,2) NULL,
-- 	C19_SHIPPING_LIST_AMOUNT	NUMBER(19,2) NULL,
-- 	C20_SHIPPING_TAX_RATE	NUMBER(10,10) NULL,
-- 	C21_SHIPPING_TAX	NUMBER(19,2) NULL,
-- 	C22_SHIPPING_TAX_DATE	VARCHAR2(255) NULL,
-- 	C23_SHIPPING_CITY	VARCHAR2(35) NULL,
-- 	C24_SHIPPING_COUNTRY	VARCHAR2(2) NULL,
-- 	C25_SHIPPING_FIRSTNAME	VARCHAR2(40) NULL,
-- 	C26_SHIPPING_LASTNAME	VARCHAR2(40) NULL,
-- 	C27_SHIPPING_LINE1	VARCHAR2(50) NULL,
-- 	C28_SHIPPING_LINE2	VARCHAR2(50) NULL,
-- 	C29_SHIPPING_PHONE_NUMBER	VARCHAR2(20) NULL,
-- 	C30_SHIPPING_POSTAL_CODE	VARCHAR2(35) NULL,
-- 	C31_SHIPPING_STATE_PROVINCE	VARCHAR2(35) NULL,
-- 	C32_SENT_TO_SPECTRUM_IND	NUMBER(1) NULL,
-- 	C33_SENT_TO_SPECTRUM_DATE	TIMESTAMP(6) NULL,
-- 	C34_TAX_AMOUNT	NUMBER(19,2) NULL,
-- 	C35_TAX_TOTAL_AS_OF_DATE	VARCHAR2(255) NULL,
-- 	C36_COD_PRODUCT_ID	NUMBER(10) NULL,
-- 	C37_PROMOTION_ID	NUMBER(19) NULL,
-- 	C38_SHIPPING_PRODUCT_ID	NUMBER(10) NULL,
-- 	C39_SUBJECT_ID	NUMBER(19) NULL,
-- 	C40_APO_ID	VARCHAR2(255) NULL,
-- 	C41_APPOINTMENT_ID	NUMBER NULL,
-- 	C42_DELETED_IND	VARCHAR2(1) NULL
-- )
-- NOLOGGING

-- &


/*-----------------------------------------------*/
/* TASK No. 6 */
/* Load data */

/* SOURCE CODE */


-- select	
-- 	CUSTOMER_ORDER.CUSTOMER_ORDER_ID	   C1_CUSTOMER_ORDER_ID,
-- 	CUSTOMER_ORDER.ADDRESSES_SAME	   C2_ADDRESSES_SAME,
-- 	CUSTOMER_ORDER.AUDIT_CREATE_DATE	   C3_AUDIT_CREATE_DATE,
-- 	CUSTOMER_ORDER.AUDIT_CREATED_BY	   C4_AUDIT_CREATED_BY,
-- 	CUSTOMER_ORDER.AUDIT_MODIFIED_BY	   C5_AUDIT_MODIFIED_BY,
-- 	CUSTOMER_ORDER.AUDIT_MODIFY_DATE	   C6_AUDIT_MODIFY_DATE,
-- 	CUSTOMER_ORDER.COD_LIST_AMOUNT	   C7_COD_LIST_AMOUNT,
-- 	CUSTOMER_ORDER.COD_TAX_RATE	   C8_COD_TAX_RATE,
-- 	CUSTOMER_ORDER.COD_TAX	   C9_COD_TAX,
-- 	CUSTOMER_ORDER.COD_TAX_DATE	   C10_COD_TAX_DATE,
-- 	CUSTOMER_ORDER.CURRENCY_CODE	   C11_CURRENCY_CODE,
-- 	CUSTOMER_ORDER.CURRENT_STATUS_CODE	   C12_CURRENT_STATUS_CODE,
-- 	CUSTOMER_ORDER.ORDER_DATE	   C13_ORDER_DATE,
-- 	CUSTOMER_ORDER.LIFETOUCH_USER_PROFILE_ID	   C14_LIFETOUCH_USER_PROFILE_ID,
-- 	CUSTOMER_ORDER.ORDER_NUMBER	   C15_ORDER_NUMBER,
-- 	CUSTOMER_ORDER.PROOF_DEPOSIT_APPLIED	   C16_PROOF_DEPOSIT_APPLIED,
-- 	CUSTOMER_ORDER.PROOF_DEPOSIT_TOTAL	   C17_PROOF_DEPOSIT_TOTAL,
-- 	CUSTOMER_ORDER.SHIPPING_DISCOUNT	   C18_SHIPPING_DISCOUNT,
-- 	CUSTOMER_ORDER.SHIPPING_LIST_AMOUNT	   C19_SHIPPING_LIST_AMOUNT,
-- 	CUSTOMER_ORDER.SHIPPING_TAX_RATE	   C20_SHIPPING_TAX_RATE,
-- 	CUSTOMER_ORDER.SHIPPING_TAX	   C21_SHIPPING_TAX,
-- 	CUSTOMER_ORDER.SHIPPING_TAX_DATE	   C22_SHIPPING_TAX_DATE,
-- 	CUSTOMER_ORDER.SHIPPING_CITY	   C23_SHIPPING_CITY,
-- 	CUSTOMER_ORDER.SHIPPING_COUNTRY	   C24_SHIPPING_COUNTRY,
-- 	CUSTOMER_ORDER.SHIPPING_FIRSTNAME	   C25_SHIPPING_FIRSTNAME,
-- 	CUSTOMER_ORDER.SHIPPING_LASTNAME	   C26_SHIPPING_LASTNAME,
-- 	CUSTOMER_ORDER.SHIPPING_LINE1	   C27_SHIPPING_LINE1,
-- 	CUSTOMER_ORDER.SHIPPING_LINE2	   C28_SHIPPING_LINE2,
-- 	CUSTOMER_ORDER.SHIPPING_PHONE_NUMBER	   C29_SHIPPING_PHONE_NUMBER,
-- 	CUSTOMER_ORDER.SHIPPING_POSTAL_CODE	   C30_SHIPPING_POSTAL_CODE,
-- 	CUSTOMER_ORDER.SHIPPING_STATE_PROVINCE	   C31_SHIPPING_STATE_PROVINCE,
-- 	CUSTOMER_ORDER.SENT_TO_SPECTRUM_IND	   C32_SENT_TO_SPECTRUM_IND,
-- 	CUSTOMER_ORDER.SENT_TO_SPECTRUM_DATE	   C33_SENT_TO_SPECTRUM_DATE,
-- 	CUSTOMER_ORDER.TAX_AMOUNT	   C34_TAX_AMOUNT,
-- 	CUSTOMER_ORDER.TAX_TOTAL_AS_OF_DATE	   C35_TAX_TOTAL_AS_OF_DATE,
-- 	CUSTOMER_ORDER.COD_PRODUCT_ID	   C36_COD_PRODUCT_ID,
-- 	CUSTOMER_ORDER.PROMOTION_ID	   C37_PROMOTION_ID,
-- 	CUSTOMER_ORDER.SHIPPING_PRODUCT_ID	   C38_SHIPPING_PRODUCT_ID,
-- 	CUSTOMER_ORDER.SUBJECT_ID	   C39_SUBJECT_ID,
-- 	CUSTOMER_ORDER.APO_ID	   C40_APO_ID,
-- 	CUSTOMER_ORDER.APPOINTMENT_ID	   C41_APPOINTMENT_ID,
-- 	CUSTOMER_ORDER.DELETED_IND	   C42_DELETED_IND
-- from	SAS_SIT_OWN.CUSTOMER_ORDER   CUSTOMER_ORDER
-- where	(1=1)
-- And ((1=1) 
-- and CUSTOMER_ORDER.AUDIT_MODIFY_DATE >= TO_DATE(SUBSTR(:v_cdc_load_date, 1, 19), 'YYYY-MM-DD HH24:MI:SS')  -:v_cdc_overlap)







-- &

/* TARGET CODE */
-- insert /*+ append */ into RAX_APP_USER.C$_0SAS_CUST_ORDER_STG
-- (
-- 	C1_CUSTOMER_ORDER_ID,
-- 	C2_ADDRESSES_SAME,
-- 	C3_AUDIT_CREATE_DATE,
-- 	C4_AUDIT_CREATED_BY,
-- 	C5_AUDIT_MODIFIED_BY,
-- 	C6_AUDIT_MODIFY_DATE,
-- 	C7_COD_LIST_AMOUNT,
-- 	C8_COD_TAX_RATE,
-- 	C9_COD_TAX,
-- 	C10_COD_TAX_DATE,
-- 	C11_CURRENCY_CODE,
-- 	C12_CURRENT_STATUS_CODE,
-- 	C13_ORDER_DATE,
-- 	C14_LIFETOUCH_USER_PROFILE_ID,
-- 	C15_ORDER_NUMBER,
-- 	C16_PROOF_DEPOSIT_APPLIED,
-- 	C17_PROOF_DEPOSIT_TOTAL,
-- 	C18_SHIPPING_DISCOUNT,
-- 	C19_SHIPPING_LIST_AMOUNT,
-- 	C20_SHIPPING_TAX_RATE,
-- 	C21_SHIPPING_TAX,
-- 	C22_SHIPPING_TAX_DATE,
-- 	C23_SHIPPING_CITY,
-- 	C24_SHIPPING_COUNTRY,
-- 	C25_SHIPPING_FIRSTNAME,
-- 	C26_SHIPPING_LASTNAME,
-- 	C27_SHIPPING_LINE1,
-- 	C28_SHIPPING_LINE2,
-- 	C29_SHIPPING_PHONE_NUMBER,
-- 	C30_SHIPPING_POSTAL_CODE,
-- 	C31_SHIPPING_STATE_PROVINCE,
-- 	C32_SENT_TO_SPECTRUM_IND,
-- 	C33_SENT_TO_SPECTRUM_DATE,
-- 	C34_TAX_AMOUNT,
-- 	C35_TAX_TOTAL_AS_OF_DATE,
-- 	C36_COD_PRODUCT_ID,
-- 	C37_PROMOTION_ID,
-- 	C38_SHIPPING_PRODUCT_ID,
-- 	C39_SUBJECT_ID,
-- 	C40_APO_ID,
-- 	C41_APPOINTMENT_ID,
-- 	C42_DELETED_IND
-- )
-- values
-- (
-- 	:C1_CUSTOMER_ORDER_ID,
-- 	:C2_ADDRESSES_SAME,
-- 	:C3_AUDIT_CREATE_DATE,
-- 	:C4_AUDIT_CREATED_BY,
-- 	:C5_AUDIT_MODIFIED_BY,
-- 	:C6_AUDIT_MODIFY_DATE,
-- 	:C7_COD_LIST_AMOUNT,
-- 	:C8_COD_TAX_RATE,
-- 	:C9_COD_TAX,
-- 	:C10_COD_TAX_DATE,
-- 	:C11_CURRENCY_CODE,
-- 	:C12_CURRENT_STATUS_CODE,
-- 	:C13_ORDER_DATE,
-- 	:C14_LIFETOUCH_USER_PROFILE_ID,
-- 	:C15_ORDER_NUMBER,
-- 	:C16_PROOF_DEPOSIT_APPLIED,
-- 	:C17_PROOF_DEPOSIT_TOTAL,
-- 	:C18_SHIPPING_DISCOUNT,
-- 	:C19_SHIPPING_LIST_AMOUNT,
-- 	:C20_SHIPPING_TAX_RATE,
-- 	:C21_SHIPPING_TAX,
-- 	:C22_SHIPPING_TAX_DATE,
-- 	:C23_SHIPPING_CITY,
-- 	:C24_SHIPPING_COUNTRY,
-- 	:C25_SHIPPING_FIRSTNAME,
-- 	:C26_SHIPPING_LASTNAME,
-- 	:C27_SHIPPING_LINE1,
-- 	:C28_SHIPPING_LINE2,
-- 	:C29_SHIPPING_PHONE_NUMBER,
-- 	:C30_SHIPPING_POSTAL_CODE,
-- 	:C31_SHIPPING_STATE_PROVINCE,
-- 	:C32_SENT_TO_SPECTRUM_IND,
-- 	:C33_SENT_TO_SPECTRUM_DATE,
-- 	:C34_TAX_AMOUNT,
-- 	:C35_TAX_TOTAL_AS_OF_DATE,
-- 	:C36_COD_PRODUCT_ID,
-- 	:C37_PROMOTION_ID,
-- 	:C38_SHIPPING_PRODUCT_ID,
-- 	:C39_SUBJECT_ID,
-- 	:C40_APO_ID,
-- 	:C41_APPOINTMENT_ID,
-- 	:C42_DELETED_IND
-- )

-- &


/*-----------------------------------------------*/
/* TASK No. 7 */
/* Analyze work table */



BEGIN
DBMS_STATS.GATHER_TABLE_STATS (
    ownname =>	'RAX_APP_USER',
    tabname =>	'C$_0SAS_CUST_ORDER_STG',
    estimate_percent =>	DBMS_STATS.AUTO_SAMPLE_SIZE
);
END;




&


/*-----------------------------------------------*/
/* TASK No. 9 */
/* Set vID */

/* NONE or SET VARIABLE STATEMENT FOUND, CHECK ODI TASK NO. 9 */




/*-----------------------------------------------*/
/* TASK No. 10 */
/* Drop flow table */

-- drop table RAX_APP_USER.I$_SAS_CUST_ORDER_STG1386001 

BEGIN
  EXECUTE IMMEDIATE 'drop table RAX_APP_USER.I$_SAS_CUST_ORDER_STG1386001';
EXCEPTION
  WHEN OTHERS THEN
   IF SQLCODE != -942 THEN
     RAISE;
   END IF;
END;


&


/*-----------------------------------------------*/
/* TASK No. 11 */
/* Create flow table I$ */


create table RAX_APP_USER.I$_SAS_CUST_ORDER_STG1386001
(
	CUSTOMER_ORDER_ID	NUMBER(10) NULL,
	ADDRESSES_SAME	NUMBER(1) NULL,
	AUDIT_CREATE_DATE	TIMESTAMP(6) NULL,
	AUDIT_CREATED_BY	VARCHAR2(255) NULL,
	AUDIT_MODIFIED_BY	VARCHAR2(255) NULL,
	AUDIT_MODIFY_DATE	TIMESTAMP(6) NULL,
	COD_LIST_AMOUNT	NUMBER(19,2) NULL,
	COD_TAX_RATE	NUMBER(10,10) NULL,
	COD_TAX	NUMBER(19,2) NULL,
	COD_TAX_DATE	VARCHAR2(255) NULL,
	CURRENCY_CODE	VARCHAR2(3) NULL,
	CURRENT_STATUS_CODE	VARCHAR2(1) NULL,
	ORDER_DATE	TIMESTAMP(6) NULL,
	LIFETOUCH_USER_PROFILE_ID	VARCHAR2(255) NULL,
	ORDER_NUMBER	VARCHAR2(255) NULL,
	PROOF_DEPOSIT_APPLIED	NUMBER(19,2) NULL,
	PROOF_DEPOSIT_TOTAL	NUMBER(19,2) NULL,
	SHIPPING_DISCOUNT	NUMBER(19,2) NULL,
	SHIPPING_LIST_AMOUNT	NUMBER(19,2) NULL,
	SHIPPING_TAX_RATE	NUMBER(10,10) NULL,
	SHIPPING_TAX	NUMBER(19,2) NULL,
	SHIPPING_TAX_DATE	VARCHAR2(255) NULL,
	SHIPPING_CITY	VARCHAR2(35) NULL,
	SHIPPING_COUNTRY	VARCHAR2(2) NULL,
	SHIPPING_FIRSTNAME	VARCHAR2(40) NULL,
	SHIPPING_LASTNAME	VARCHAR2(40) NULL,
	SHIPPING_LINE1	VARCHAR2(50) NULL,
	SHIPPING_LINE2	VARCHAR2(50) NULL,
	SHIPPING_PHONE_NUMBER	VARCHAR2(20) NULL,
	SHIPPING_POSTAL_CODE	VARCHAR2(35) NULL,
	SHIPPING_STATE_PROVINCE	VARCHAR2(35) NULL,
	SENT_TO_SPECTRUM_IND	NUMBER(1) NULL,
	SENT_TO_SPECTRUM_DATE	TIMESTAMP(6) NULL,
	TAX_AMOUNT	NUMBER(19,2) NULL,
	TAX_TOTAL_AS_OF_DATE	VARCHAR2(255) NULL,
	COD_PRODUCT_ID	NUMBER(10) NULL,
	PROMOTION_ID	NUMBER(19) NULL,
	SHIPPING_PRODUCT_ID	NUMBER(10) NULL,
	SUBJECT_ID	NUMBER(19) NULL,
	APO_ID	VARCHAR2(255) NULL,
	APPOINTMENT_ID	NUMBER NULL,
	ODS_CREATE_DATE	DATE NULL,
	ODS_MODIFY_DATE	DATE NULL,
	DELETED_IND	VARCHAR2(1) NULL
	,IND_UPDATE		char(1)
)
NOLOGGING

&


/*-----------------------------------------------*/
/* TASK No. 12 */
/* Insert flow into I$ table */

/* DETECTION_STRATEGY = NOT_EXISTS */
 


  


insert into	RAX_APP_USER.I$_SAS_CUST_ORDER_STG1386001
(
	CUSTOMER_ORDER_ID,
	ADDRESSES_SAME,
	AUDIT_CREATE_DATE,
	AUDIT_CREATED_BY,
	AUDIT_MODIFIED_BY,
	AUDIT_MODIFY_DATE,
	COD_LIST_AMOUNT,
	COD_TAX_RATE,
	COD_TAX,
	COD_TAX_DATE,
	CURRENCY_CODE,
	CURRENT_STATUS_CODE,
	ORDER_DATE,
	LIFETOUCH_USER_PROFILE_ID,
	ORDER_NUMBER,
	PROOF_DEPOSIT_APPLIED,
	PROOF_DEPOSIT_TOTAL,
	SHIPPING_DISCOUNT,
	SHIPPING_LIST_AMOUNT,
	SHIPPING_TAX_RATE,
	SHIPPING_TAX,
	SHIPPING_TAX_DATE,
	SHIPPING_CITY,
	SHIPPING_COUNTRY,
	SHIPPING_FIRSTNAME,
	SHIPPING_LASTNAME,
	SHIPPING_LINE1,
	SHIPPING_LINE2,
	SHIPPING_PHONE_NUMBER,
	SHIPPING_POSTAL_CODE,
	SHIPPING_STATE_PROVINCE,
	SENT_TO_SPECTRUM_IND,
	SENT_TO_SPECTRUM_DATE,
	TAX_AMOUNT,
	TAX_TOTAL_AS_OF_DATE,
	COD_PRODUCT_ID,
	PROMOTION_ID,
	SHIPPING_PRODUCT_ID,
	SUBJECT_ID,
	APO_ID,
	APPOINTMENT_ID,
	DELETED_IND,
	IND_UPDATE
)
select 
CUSTOMER_ORDER_ID,
	ADDRESSES_SAME,
	AUDIT_CREATE_DATE,
	AUDIT_CREATED_BY,
	AUDIT_MODIFIED_BY,
	AUDIT_MODIFY_DATE,
	COD_LIST_AMOUNT,
	COD_TAX_RATE,
	COD_TAX,
	COD_TAX_DATE,
	CURRENCY_CODE,
	CURRENT_STATUS_CODE,
	ORDER_DATE,
	LIFETOUCH_USER_PROFILE_ID,
	ORDER_NUMBER,
	PROOF_DEPOSIT_APPLIED,
	PROOF_DEPOSIT_TOTAL,
	SHIPPING_DISCOUNT,
	SHIPPING_LIST_AMOUNT,
	SHIPPING_TAX_RATE,
	SHIPPING_TAX,
	SHIPPING_TAX_DATE,
	SHIPPING_CITY,
	SHIPPING_COUNTRY,
	SHIPPING_FIRSTNAME,
	SHIPPING_LASTNAME,
	SHIPPING_LINE1,
	SHIPPING_LINE2,
	SHIPPING_PHONE_NUMBER,
	SHIPPING_POSTAL_CODE,
	SHIPPING_STATE_PROVINCE,
	SENT_TO_SPECTRUM_IND,
	SENT_TO_SPECTRUM_DATE,
	TAX_AMOUNT,
	TAX_TOTAL_AS_OF_DATE,
	COD_PRODUCT_ID,
	PROMOTION_ID,
	SHIPPING_PRODUCT_ID,
	SUBJECT_ID,
	APO_ID,
	APPOINTMENT_ID,
	DELETED_IND,
	IND_UPDATE
 from (


select 	 
	
	C1_CUSTOMER_ORDER_ID CUSTOMER_ORDER_ID,
	C2_ADDRESSES_SAME ADDRESSES_SAME,
	C3_AUDIT_CREATE_DATE AUDIT_CREATE_DATE,
	C4_AUDIT_CREATED_BY AUDIT_CREATED_BY,
	C5_AUDIT_MODIFIED_BY AUDIT_MODIFIED_BY,
	C6_AUDIT_MODIFY_DATE AUDIT_MODIFY_DATE,
	C7_COD_LIST_AMOUNT COD_LIST_AMOUNT,
	C8_COD_TAX_RATE COD_TAX_RATE,
	C9_COD_TAX COD_TAX,
	C10_COD_TAX_DATE COD_TAX_DATE,
	C11_CURRENCY_CODE CURRENCY_CODE,
	C12_CURRENT_STATUS_CODE CURRENT_STATUS_CODE,
	C13_ORDER_DATE ORDER_DATE,
	C14_LIFETOUCH_USER_PROFILE_ID LIFETOUCH_USER_PROFILE_ID,
	C15_ORDER_NUMBER ORDER_NUMBER,
	C16_PROOF_DEPOSIT_APPLIED PROOF_DEPOSIT_APPLIED,
	C17_PROOF_DEPOSIT_TOTAL PROOF_DEPOSIT_TOTAL,
	C18_SHIPPING_DISCOUNT SHIPPING_DISCOUNT,
	C19_SHIPPING_LIST_AMOUNT SHIPPING_LIST_AMOUNT,
	C20_SHIPPING_TAX_RATE SHIPPING_TAX_RATE,
	C21_SHIPPING_TAX SHIPPING_TAX,
	C22_SHIPPING_TAX_DATE SHIPPING_TAX_DATE,
	C23_SHIPPING_CITY SHIPPING_CITY,
	C24_SHIPPING_COUNTRY SHIPPING_COUNTRY,
	C25_SHIPPING_FIRSTNAME SHIPPING_FIRSTNAME,
	C26_SHIPPING_LASTNAME SHIPPING_LASTNAME,
	C27_SHIPPING_LINE1 SHIPPING_LINE1,
	C28_SHIPPING_LINE2 SHIPPING_LINE2,
	C29_SHIPPING_PHONE_NUMBER SHIPPING_PHONE_NUMBER,
	C30_SHIPPING_POSTAL_CODE SHIPPING_POSTAL_CODE,
	C31_SHIPPING_STATE_PROVINCE SHIPPING_STATE_PROVINCE,
	C32_SENT_TO_SPECTRUM_IND SENT_TO_SPECTRUM_IND,
	C33_SENT_TO_SPECTRUM_DATE SENT_TO_SPECTRUM_DATE,
	C34_TAX_AMOUNT TAX_AMOUNT,
	C35_TAX_TOTAL_AS_OF_DATE TAX_TOTAL_AS_OF_DATE,
	C36_COD_PRODUCT_ID COD_PRODUCT_ID,
	C37_PROMOTION_ID PROMOTION_ID,
	C38_SHIPPING_PRODUCT_ID SHIPPING_PRODUCT_ID,
	C39_SUBJECT_ID SUBJECT_ID,
	C40_APO_ID APO_ID,
	C41_APPOINTMENT_ID APPOINTMENT_ID,
	C42_DELETED_IND DELETED_IND,

	'I' IND_UPDATE

from	RAX_APP_USER.C$_0SAS_CUST_ORDER_STG
where	(1=1)






) S
where NOT EXISTS 
	( select 1 from ODS_STAGE.SAS_CUSTOMER_ORDER_STG T
	where	T.CUSTOMER_ORDER_ID	= S.CUSTOMER_ORDER_ID 
		 and ((T.ADDRESSES_SAME = S.ADDRESSES_SAME) or (T.ADDRESSES_SAME IS NULL and S.ADDRESSES_SAME IS NULL)) and
		((T.AUDIT_CREATE_DATE = S.AUDIT_CREATE_DATE) or (T.AUDIT_CREATE_DATE IS NULL and S.AUDIT_CREATE_DATE IS NULL)) and
		((T.AUDIT_CREATED_BY = S.AUDIT_CREATED_BY) or (T.AUDIT_CREATED_BY IS NULL and S.AUDIT_CREATED_BY IS NULL)) and
		((T.AUDIT_MODIFIED_BY = S.AUDIT_MODIFIED_BY) or (T.AUDIT_MODIFIED_BY IS NULL and S.AUDIT_MODIFIED_BY IS NULL)) and
		((T.AUDIT_MODIFY_DATE = S.AUDIT_MODIFY_DATE) or (T.AUDIT_MODIFY_DATE IS NULL and S.AUDIT_MODIFY_DATE IS NULL)) and
		((T.COD_LIST_AMOUNT = S.COD_LIST_AMOUNT) or (T.COD_LIST_AMOUNT IS NULL and S.COD_LIST_AMOUNT IS NULL)) and
		((T.COD_TAX_RATE = S.COD_TAX_RATE) or (T.COD_TAX_RATE IS NULL and S.COD_TAX_RATE IS NULL)) and
		((T.COD_TAX = S.COD_TAX) or (T.COD_TAX IS NULL and S.COD_TAX IS NULL)) and
		((T.COD_TAX_DATE = S.COD_TAX_DATE) or (T.COD_TAX_DATE IS NULL and S.COD_TAX_DATE IS NULL)) and
		((T.CURRENCY_CODE = S.CURRENCY_CODE) or (T.CURRENCY_CODE IS NULL and S.CURRENCY_CODE IS NULL)) and
		((T.CURRENT_STATUS_CODE = S.CURRENT_STATUS_CODE) or (T.CURRENT_STATUS_CODE IS NULL and S.CURRENT_STATUS_CODE IS NULL)) and
		((T.ORDER_DATE = S.ORDER_DATE) or (T.ORDER_DATE IS NULL and S.ORDER_DATE IS NULL)) and
		((T.LIFETOUCH_USER_PROFILE_ID = S.LIFETOUCH_USER_PROFILE_ID) or (T.LIFETOUCH_USER_PROFILE_ID IS NULL and S.LIFETOUCH_USER_PROFILE_ID IS NULL)) and
		((T.ORDER_NUMBER = S.ORDER_NUMBER) or (T.ORDER_NUMBER IS NULL and S.ORDER_NUMBER IS NULL)) and
		((T.PROOF_DEPOSIT_APPLIED = S.PROOF_DEPOSIT_APPLIED) or (T.PROOF_DEPOSIT_APPLIED IS NULL and S.PROOF_DEPOSIT_APPLIED IS NULL)) and
		((T.PROOF_DEPOSIT_TOTAL = S.PROOF_DEPOSIT_TOTAL) or (T.PROOF_DEPOSIT_TOTAL IS NULL and S.PROOF_DEPOSIT_TOTAL IS NULL)) and
		((T.SHIPPING_DISCOUNT = S.SHIPPING_DISCOUNT) or (T.SHIPPING_DISCOUNT IS NULL and S.SHIPPING_DISCOUNT IS NULL)) and
		((T.SHIPPING_LIST_AMOUNT = S.SHIPPING_LIST_AMOUNT) or (T.SHIPPING_LIST_AMOUNT IS NULL and S.SHIPPING_LIST_AMOUNT IS NULL)) and
		((T.SHIPPING_TAX_RATE = S.SHIPPING_TAX_RATE) or (T.SHIPPING_TAX_RATE IS NULL and S.SHIPPING_TAX_RATE IS NULL)) and
		((T.SHIPPING_TAX = S.SHIPPING_TAX) or (T.SHIPPING_TAX IS NULL and S.SHIPPING_TAX IS NULL)) and
		((T.SHIPPING_TAX_DATE = S.SHIPPING_TAX_DATE) or (T.SHIPPING_TAX_DATE IS NULL and S.SHIPPING_TAX_DATE IS NULL)) and
		((T.SHIPPING_CITY = S.SHIPPING_CITY) or (T.SHIPPING_CITY IS NULL and S.SHIPPING_CITY IS NULL)) and
		((T.SHIPPING_COUNTRY = S.SHIPPING_COUNTRY) or (T.SHIPPING_COUNTRY IS NULL and S.SHIPPING_COUNTRY IS NULL)) and
		((T.SHIPPING_FIRSTNAME = S.SHIPPING_FIRSTNAME) or (T.SHIPPING_FIRSTNAME IS NULL and S.SHIPPING_FIRSTNAME IS NULL)) and
		((T.SHIPPING_LASTNAME = S.SHIPPING_LASTNAME) or (T.SHIPPING_LASTNAME IS NULL and S.SHIPPING_LASTNAME IS NULL)) and
		((T.SHIPPING_LINE1 = S.SHIPPING_LINE1) or (T.SHIPPING_LINE1 IS NULL and S.SHIPPING_LINE1 IS NULL)) and
		((T.SHIPPING_LINE2 = S.SHIPPING_LINE2) or (T.SHIPPING_LINE2 IS NULL and S.SHIPPING_LINE2 IS NULL)) and
		((T.SHIPPING_PHONE_NUMBER = S.SHIPPING_PHONE_NUMBER) or (T.SHIPPING_PHONE_NUMBER IS NULL and S.SHIPPING_PHONE_NUMBER IS NULL)) and
		((T.SHIPPING_POSTAL_CODE = S.SHIPPING_POSTAL_CODE) or (T.SHIPPING_POSTAL_CODE IS NULL and S.SHIPPING_POSTAL_CODE IS NULL)) and
		((T.SHIPPING_STATE_PROVINCE = S.SHIPPING_STATE_PROVINCE) or (T.SHIPPING_STATE_PROVINCE IS NULL and S.SHIPPING_STATE_PROVINCE IS NULL)) and
		((T.SENT_TO_SPECTRUM_IND = S.SENT_TO_SPECTRUM_IND) or (T.SENT_TO_SPECTRUM_IND IS NULL and S.SENT_TO_SPECTRUM_IND IS NULL)) and
		((T.SENT_TO_SPECTRUM_DATE = S.SENT_TO_SPECTRUM_DATE) or (T.SENT_TO_SPECTRUM_DATE IS NULL and S.SENT_TO_SPECTRUM_DATE IS NULL)) and
		((T.TAX_AMOUNT = S.TAX_AMOUNT) or (T.TAX_AMOUNT IS NULL and S.TAX_AMOUNT IS NULL)) and
		((T.TAX_TOTAL_AS_OF_DATE = S.TAX_TOTAL_AS_OF_DATE) or (T.TAX_TOTAL_AS_OF_DATE IS NULL and S.TAX_TOTAL_AS_OF_DATE IS NULL)) and
		((T.COD_PRODUCT_ID = S.COD_PRODUCT_ID) or (T.COD_PRODUCT_ID IS NULL and S.COD_PRODUCT_ID IS NULL)) and
		((T.PROMOTION_ID = S.PROMOTION_ID) or (T.PROMOTION_ID IS NULL and S.PROMOTION_ID IS NULL)) and
		((T.SHIPPING_PRODUCT_ID = S.SHIPPING_PRODUCT_ID) or (T.SHIPPING_PRODUCT_ID IS NULL and S.SHIPPING_PRODUCT_ID IS NULL)) and
		((T.SUBJECT_ID = S.SUBJECT_ID) or (T.SUBJECT_ID IS NULL and S.SUBJECT_ID IS NULL)) and
		((T.APO_ID = S.APO_ID) or (T.APO_ID IS NULL and S.APO_ID IS NULL)) and
		((T.APPOINTMENT_ID = S.APPOINTMENT_ID) or (T.APPOINTMENT_ID IS NULL and S.APPOINTMENT_ID IS NULL)) and
		((T.DELETED_IND = S.DELETED_IND) or (T.DELETED_IND IS NULL and S.DELETED_IND IS NULL))
        )

  
  

  



&


/*-----------------------------------------------*/
/* TASK No. 13 */
/* Analyze integration table */



begin
    dbms_stats.gather_table_stats(
	ownname => 'RAX_APP_USER',
	tabname => 'I$_SAS_CUST_ORDER_STG1386001',
	estimate_percent => dbms_stats.auto_sample_size
    );
end;



&


/*-----------------------------------------------*/
/* TASK No. 14 */
/* Create Index on flow table */

-- create index	RAX_APP_USER.I$_SAS_CUST_ORDER_STG1386001
-- on		RAX_APP_USER.I$_SAS_CUST_ORDER_STG1386001 (CUSTOMER_ORDER_ID)
-- NOLOGGING

BEGIN
  EXECUTE IMMEDIATE 'create index RAX_APP_USER.I$_SAS_CUST_ORDER_STG1386001
on   RAX_APP_USER.I$_SAS_CUST_ORDER_STG1386001 (CUSTOMER_ORDER_ID)';
EXCEPTION
  WHEN OTHERS THEN
   -- Handle the case where the identifier is too long (ORA-00972)
   IF SQLCODE = -972 or  SQLCODE = -1408 or SQLCODE = -955  THEN
     DBMS_OUTPUT.PUT_LINE('Identifier is too long. Skipping creation of index.');
   ELSE
     RAISE;
   END IF;
END;

&


/*-----------------------------------------------*/
/* TASK No. 15 */
/* create check table */


BEGIN
  EXECUTE IMMEDIATE 'drop table RAX_APP_USER.SNP_CHECK_TAB';
EXCEPTION
  WHEN OTHERS THEN
   IF SQLCODE != -942 THEN
     RAISE;
   END IF;
END;


&

-- create table RAX_APP_USER.SNP_CHECK_TAB
-- (
-- 	CATALOG_NAME	VARCHAR2(100 CHAR) NULL ,
-- 	SCHEMA_NAME	VARCHAR2(100 CHAR) NULL ,
-- 	RESOURCE_NAME	VARCHAR2(100 CHAR) NULL,
-- 	FULL_RES_NAME	VARCHAR2(100 CHAR) NULL,
-- 	ERR_TYPE		VARCHAR2(1 CHAR) NULL,
-- 	ERR_MESS		VARCHAR2(250 CHAR) NULL ,
-- 	CHECK_DATE	DATE NULL,
-- 	ORIGIN		VARCHAR2(100 CHAR) NULL,
-- 	CONS_NAME	VARCHAR2(35 CHAR) NULL,
-- 	CONS_TYPE		VARCHAR2(2 CHAR) NULL,
-- 	ERR_COUNT		NUMBER(10) NULL
-- )
	

BEGIN
   EXECUTE IMMEDIATE '
      create table RAX_APP_USER.SNP_CHECK_TAB
		(
			CATALOG_NAME	VARCHAR2(100 CHAR) NULL ,
			SCHEMA_NAME	VARCHAR2(100 CHAR) NULL ,
			RESOURCE_NAME	VARCHAR2(100 CHAR) NULL,
			FULL_RES_NAME	VARCHAR2(100 CHAR) NULL,
			ERR_TYPE		VARCHAR2(1 CHAR) NULL,
			ERR_MESS		VARCHAR2(250 CHAR) NULL ,
			CHECK_DATE	DATE NULL,
			ORIGIN		VARCHAR2(100 CHAR) NULL,
			CONS_NAME	VARCHAR2(35 CHAR) NULL,
			CONS_TYPE		VARCHAR2(2 CHAR) NULL,
			ERR_COUNT		NUMBER(10) NULL
		)
   ';
END;

&


/*-----------------------------------------------*/
/* TASK No. 16 */
/* delete previous check sum */

delete from	RAX_APP_USER.SNP_CHECK_TAB
where	SCHEMA_NAME	= 'ODS_STAGE'
and	ORIGIN 		= '(1386001)ODS_Project.LOAD_SAS_CUSTOMER_ORDER_STG_INT'
and	ERR_TYPE 		= 'F'


&


/*-----------------------------------------------*/
/* TASK No. 17 */
/* create error table */


BEGIN
  EXECUTE IMMEDIATE 'drop table RAX_APP_USER.E$_SAS_CUST_ORDER_STG1386001';
EXCEPTION
  WHEN OTHERS THEN
   IF SQLCODE != -942 THEN
     RAISE;
   END IF;
END;


&

create table RAX_APP_USER.E$_SAS_CUST_ORDER_STG1386001
(
	ODI_ROW_ID 		UROWID,
	ODI_ERR_TYPE		VARCHAR2(1 CHAR) NULL, 
	ODI_ERR_MESS		VARCHAR2(250 CHAR) NULL,
	ODI_CHECK_DATE	DATE NULL, 
	CUSTOMER_ORDER_ID	NUMBER(10) NULL,
	ADDRESSES_SAME	NUMBER(1) NULL,
	AUDIT_CREATE_DATE	TIMESTAMP(6) NULL,
	AUDIT_CREATED_BY	VARCHAR2(255) NULL,
	AUDIT_MODIFIED_BY	VARCHAR2(255) NULL,
	AUDIT_MODIFY_DATE	TIMESTAMP(6) NULL,
	COD_LIST_AMOUNT	NUMBER(19,2) NULL,
	COD_TAX_RATE	NUMBER(10,10) NULL,
	COD_TAX	NUMBER(19,2) NULL,
	COD_TAX_DATE	VARCHAR2(255) NULL,
	CURRENCY_CODE	VARCHAR2(3) NULL,
	CURRENT_STATUS_CODE	VARCHAR2(1) NULL,
	ORDER_DATE	TIMESTAMP(6) NULL,
	LIFETOUCH_USER_PROFILE_ID	VARCHAR2(255) NULL,
	ORDER_NUMBER	VARCHAR2(255) NULL,
	PROOF_DEPOSIT_APPLIED	NUMBER(19,2) NULL,
	PROOF_DEPOSIT_TOTAL	NUMBER(19,2) NULL,
	SHIPPING_DISCOUNT	NUMBER(19,2) NULL,
	SHIPPING_LIST_AMOUNT	NUMBER(19,2) NULL,
	SHIPPING_TAX_RATE	NUMBER(10,10) NULL,
	SHIPPING_TAX	NUMBER(19,2) NULL,
	SHIPPING_TAX_DATE	VARCHAR2(255) NULL,
	SHIPPING_CITY	VARCHAR2(35) NULL,
	SHIPPING_COUNTRY	VARCHAR2(2) NULL,
	SHIPPING_FIRSTNAME	VARCHAR2(40) NULL,
	SHIPPING_LASTNAME	VARCHAR2(40) NULL,
	SHIPPING_LINE1	VARCHAR2(50) NULL,
	SHIPPING_LINE2	VARCHAR2(50) NULL,
	SHIPPING_PHONE_NUMBER	VARCHAR2(20) NULL,
	SHIPPING_POSTAL_CODE	VARCHAR2(35) NULL,
	SHIPPING_STATE_PROVINCE	VARCHAR2(35) NULL,
	SENT_TO_SPECTRUM_IND	NUMBER(1) NULL,
	SENT_TO_SPECTRUM_DATE	TIMESTAMP(6) NULL,
	TAX_AMOUNT	NUMBER(19,2) NULL,
	TAX_TOTAL_AS_OF_DATE	VARCHAR2(255) NULL,
	COD_PRODUCT_ID	NUMBER(10) NULL,
	PROMOTION_ID	NUMBER(19) NULL,
	SHIPPING_PRODUCT_ID	NUMBER(10) NULL,
	SUBJECT_ID	NUMBER(19) NULL,
	APO_ID	VARCHAR2(255) NULL,
	APPOINTMENT_ID	NUMBER NULL,
	ODS_CREATE_DATE	DATE NULL,
	ODS_MODIFY_DATE	DATE NULL,
	DELETED_IND	VARCHAR2(1) NULL,
	ODI_ORIGIN		VARCHAR2(100 CHAR) NULL,
	ODI_CONS_NAME	VARCHAR2(35 CHAR) NULL,
	ODI_CONS_TYPE		VARCHAR2(2 CHAR) NULL,
	ODI_PK			VARCHAR2(32 CHAR) PRIMARY KEY,
	ODI_SESS_NO		VARCHAR2(19 CHAR)
)



&


/*-----------------------------------------------*/
/* TASK No. 18 */
/* delete previous errors */

delete from 	RAX_APP_USER.E$_SAS_CUST_ORDER_STG1386001
where	(ODI_ERR_TYPE = 'S'	and 'F' = 'S')
or	(ODI_ERR_TYPE = 'F'	and ODI_ORIGIN = '(1386001)ODS_Project.LOAD_SAS_CUSTOMER_ORDER_STG_INT')


&


/*-----------------------------------------------*/
/* TASK No. 19 */
/* Create index on PK */

 
/* FLOW CONTROL CREATE THE iNDEX ON THE I$TABLE */
-- create index 	RAX_APP_USER.I$_SAS_CUST_ORDER_STG1386001
-- on	RAX_APP_USER.I$_SAS_CUST_ORDER_STG1386001 (CUSTOMER_ORDER_ID)


BEGIN
  EXECUTE IMMEDIATE 'create index RAX_APP_USER.I$_SAS_CUST_ORDER_STG1386001
on   RAX_APP_USER.I$_SAS_CUST_ORDER_STG1386001 (CUSTOMER_ORDER_ID)';
EXCEPTION
  WHEN OTHERS THEN
   -- Handle the case where the identifier is too long (ORA-00972)
   IF SQLCODE = -972 or  SQLCODE = -1408 or SQLCODE = -955  THEN
     DBMS_OUTPUT.PUT_LINE('Identifier is too long. Skipping creation of index.');
   ELSE
     RAISE;
   END IF;
END;

&


/*-----------------------------------------------*/
/* TASK No. 20 */
/* insert PK errors */

DECLARE
               CheckTable                             VarChar2(60);
               TargetTable                            VarChar2(60);
               VariableCheckTable                     VarChar2(60);

BEGIN
               SELECT 'RAX_APP_USER.I$_SAS_CUST_ORDER_STG' INTO CheckTable FROM DUAL;
               SELECT 'ODS_STAGE.SAS_CUSTOMER_ORDER_STG' INTO TargetTable FROM DUAL;

IF CheckTable = TargetTable THEN
   VariableCheckTable := CheckTable; 
ELSE
   VariableCheckTable := CheckTable || '1386001';
END IF;

execute immediate '
insert into RAX_APP_USER.E$_SAS_CUST_ORDER_STG1386001
(
	ODI_PK,
	ODI_SESS_NO,
	ODI_ROW_ID,
	ODI_ERR_TYPE,
	ODI_ERR_MESS,
	ODI_ORIGIN,
	ODI_CHECK_DATE,
	ODI_CONS_NAME,
	ODI_CONS_TYPE,
	CUSTOMER_ORDER_ID,
	ADDRESSES_SAME,
	AUDIT_CREATE_DATE,
	AUDIT_CREATED_BY,
	AUDIT_MODIFIED_BY,
	AUDIT_MODIFY_DATE,
	COD_LIST_AMOUNT,
	COD_TAX_RATE,
	COD_TAX,
	COD_TAX_DATE,
	CURRENCY_CODE,
	CURRENT_STATUS_CODE,
	ORDER_DATE,
	LIFETOUCH_USER_PROFILE_ID,
	ORDER_NUMBER,
	PROOF_DEPOSIT_APPLIED,
	PROOF_DEPOSIT_TOTAL,
	SHIPPING_DISCOUNT,
	SHIPPING_LIST_AMOUNT,
	SHIPPING_TAX_RATE,
	SHIPPING_TAX,
	SHIPPING_TAX_DATE,
	SHIPPING_CITY,
	SHIPPING_COUNTRY,
	SHIPPING_FIRSTNAME,
	SHIPPING_LASTNAME,
	SHIPPING_LINE1,
	SHIPPING_LINE2,
	SHIPPING_PHONE_NUMBER,
	SHIPPING_POSTAL_CODE,
	SHIPPING_STATE_PROVINCE,
	SENT_TO_SPECTRUM_IND,
	SENT_TO_SPECTRUM_DATE,
	TAX_AMOUNT,
	TAX_TOTAL_AS_OF_DATE,
	COD_PRODUCT_ID,
	PROMOTION_ID,
	SHIPPING_PRODUCT_ID,
	SUBJECT_ID,
	APO_ID,
	APPOINTMENT_ID,
	ODS_CREATE_DATE,
	ODS_MODIFY_DATE,
	DELETED_IND
)
select	SYS_GUID(),
	:v_sess_no, 
	rowid,
	''F'', 
	''ODI-15064: The primary key CUSTOMER_ORDER_PK is not unique.'',
	''(1386001)ODS_Project.LOAD_SAS_CUSTOMER_ORDER_STG_INT'',
	sysdate,
	''CUSTOMER_ORDER_PK'',
	''PK'',	
	SAS_CUST_ORDER_STG.CUSTOMER_ORDER_ID,
	SAS_CUST_ORDER_STG.ADDRESSES_SAME,
	SAS_CUST_ORDER_STG.AUDIT_CREATE_DATE,
	SAS_CUST_ORDER_STG.AUDIT_CREATED_BY,
	SAS_CUST_ORDER_STG.AUDIT_MODIFIED_BY,
	SAS_CUST_ORDER_STG.AUDIT_MODIFY_DATE,
	SAS_CUST_ORDER_STG.COD_LIST_AMOUNT,
	SAS_CUST_ORDER_STG.COD_TAX_RATE,
	SAS_CUST_ORDER_STG.COD_TAX,
	SAS_CUST_ORDER_STG.COD_TAX_DATE,
	SAS_CUST_ORDER_STG.CURRENCY_CODE,
	SAS_CUST_ORDER_STG.CURRENT_STATUS_CODE,
	SAS_CUST_ORDER_STG.ORDER_DATE,
	SAS_CUST_ORDER_STG.LIFETOUCH_USER_PROFILE_ID,
	SAS_CUST_ORDER_STG.ORDER_NUMBER,
	SAS_CUST_ORDER_STG.PROOF_DEPOSIT_APPLIED,
	SAS_CUST_ORDER_STG.PROOF_DEPOSIT_TOTAL,
	SAS_CUST_ORDER_STG.SHIPPING_DISCOUNT,
	SAS_CUST_ORDER_STG.SHIPPING_LIST_AMOUNT,
	SAS_CUST_ORDER_STG.SHIPPING_TAX_RATE,
	SAS_CUST_ORDER_STG.SHIPPING_TAX,
	SAS_CUST_ORDER_STG.SHIPPING_TAX_DATE,
	SAS_CUST_ORDER_STG.SHIPPING_CITY,
	SAS_CUST_ORDER_STG.SHIPPING_COUNTRY,
	SAS_CUST_ORDER_STG.SHIPPING_FIRSTNAME,
	SAS_CUST_ORDER_STG.SHIPPING_LASTNAME,
	SAS_CUST_ORDER_STG.SHIPPING_LINE1,
	SAS_CUST_ORDER_STG.SHIPPING_LINE2,
	SAS_CUST_ORDER_STG.SHIPPING_PHONE_NUMBER,
	SAS_CUST_ORDER_STG.SHIPPING_POSTAL_CODE,
	SAS_CUST_ORDER_STG.SHIPPING_STATE_PROVINCE,
	SAS_CUST_ORDER_STG.SENT_TO_SPECTRUM_IND,
	SAS_CUST_ORDER_STG.SENT_TO_SPECTRUM_DATE,
	SAS_CUST_ORDER_STG.TAX_AMOUNT,
	SAS_CUST_ORDER_STG.TAX_TOTAL_AS_OF_DATE,
	SAS_CUST_ORDER_STG.COD_PRODUCT_ID,
	SAS_CUST_ORDER_STG.PROMOTION_ID,
	SAS_CUST_ORDER_STG.SHIPPING_PRODUCT_ID,
	SAS_CUST_ORDER_STG.SUBJECT_ID,
	SAS_CUST_ORDER_STG.APO_ID,
	SAS_CUST_ORDER_STG.APPOINTMENT_ID,
	SAS_CUST_ORDER_STG.ODS_CREATE_DATE,
	SAS_CUST_ORDER_STG.ODS_MODIFY_DATE,
	SAS_CUST_ORDER_STG.DELETED_IND
from	'
 || VariableCheckTable || 
' SAS_CUST_ORDER_STG 
where	exists  (
		select	SUB1.CUSTOMER_ORDER_ID
		from 	' 
|| VariableCheckTable ||
'  SUB1
		where 	SUB1.CUSTOMER_ORDER_ID=SAS_CUST_ORDER_STG.CUSTOMER_ORDER_ID
		group by 	SUB1.CUSTOMER_ORDER_ID
		having 	count(1) > 1
		)
';

END;


&


/*-----------------------------------------------*/
/* TASK No. 21 */
/* Create index on AK */

 
/* FLOW CONTROL CREATE THE iNDEX ON THE I$TABLE */
-- create index 	SAS_CUSTOMER_ORDER_AK_flow
-- on	RAX_APP_USER.I$_SAS_CUST_ORDER_STG1386001 
-- 	(APPOINTMENT_ID)

BEGIN
  EXECUTE IMMEDIATE 'create index SAS_CUSTOMER_ORDER_AK_flow
on   RAX_APP_USER.I$_SAS_CUST_ORDER_STG1386001  (APPOINTMENT_ID)';
EXCEPTION
  WHEN OTHERS THEN
   -- Handle the case where the identifier is too long (ORA-00972)
   IF SQLCODE = -972 or  SQLCODE = -1408 or SQLCODE = -955  THEN
     DBMS_OUTPUT.PUT_LINE('Identifier is too long. Skipping creation of index.');
   ELSE
     RAISE;
   END IF;
END;

&


/*-----------------------------------------------*/
/* TASK No. 22 */
/* insert AK errors */

DECLARE
               CheckTable                             VarChar2(60);
               TargetTable                            VarChar2(60);
               VariableCheckTable                VarChar2(60);

BEGIN
               SELECT 'RAX_APP_USER.I$_SAS_CUST_ORDER_STG' INTO CheckTable FROM DUAL;
               SELECT 'ODS_STAGE.SAS_CUSTOMER_ORDER_STG' INTO TargetTable FROM DUAL;

IF CheckTable = TargetTable THEN
   VariableCheckTable := CheckTable; 
ELSE
   VariableCheckTable := CheckTable || '1386001';
END IF;

execute immediate '
insert into RAX_APP_USER.E$_SAS_CUST_ORDER_STG1386001
(
	ODI_PK,
	ODI_SESS_NO,
	ODI_ROW_ID,
	ODI_ERR_TYPE,
	ODI_ERR_MESS,
	ODI_ORIGIN,
	ODI_CHECK_DATE,
	ODI_CONS_NAME,
	ODI_CONS_TYPE,
	CUSTOMER_ORDER_ID,
	ADDRESSES_SAME,
	AUDIT_CREATE_DATE,
	AUDIT_CREATED_BY,
	AUDIT_MODIFIED_BY,
	AUDIT_MODIFY_DATE,
	COD_LIST_AMOUNT,
	COD_TAX_RATE,
	COD_TAX,
	COD_TAX_DATE,
	CURRENCY_CODE,
	CURRENT_STATUS_CODE,
	ORDER_DATE,
	LIFETOUCH_USER_PROFILE_ID,
	ORDER_NUMBER,
	PROOF_DEPOSIT_APPLIED,
	PROOF_DEPOSIT_TOTAL,
	SHIPPING_DISCOUNT,
	SHIPPING_LIST_AMOUNT,
	SHIPPING_TAX_RATE,
	SHIPPING_TAX,
	SHIPPING_TAX_DATE,
	SHIPPING_CITY,
	SHIPPING_COUNTRY,
	SHIPPING_FIRSTNAME,
	SHIPPING_LASTNAME,
	SHIPPING_LINE1,
	SHIPPING_LINE2,
	SHIPPING_PHONE_NUMBER,
	SHIPPING_POSTAL_CODE,
	SHIPPING_STATE_PROVINCE,
	SENT_TO_SPECTRUM_IND,
	SENT_TO_SPECTRUM_DATE,
	TAX_AMOUNT,
	TAX_TOTAL_AS_OF_DATE,
	COD_PRODUCT_ID,
	PROMOTION_ID,
	SHIPPING_PRODUCT_ID,
	SUBJECT_ID,
	APO_ID,
	APPOINTMENT_ID,
	ODS_CREATE_DATE,
	ODS_MODIFY_DATE,
	DELETED_IND
)
select	SYS_GUID(),
	:v_sess_no, 
	rowid,
	''F'', 
	''ODI-15063: The alternate key SAS_CUSTOMER_ORDER_AK is not unique.'',
	''(1386001)ODS_Project.LOAD_SAS_CUSTOMER_ORDER_STG_INT'',
	sysdate,
	''SAS_CUSTOMER_ORDER_AK'',
	''AK'',	
	SAS_CUST_ORDER_STG.CUSTOMER_ORDER_ID,
	SAS_CUST_ORDER_STG.ADDRESSES_SAME,
	SAS_CUST_ORDER_STG.AUDIT_CREATE_DATE,
	SAS_CUST_ORDER_STG.AUDIT_CREATED_BY,
	SAS_CUST_ORDER_STG.AUDIT_MODIFIED_BY,
	SAS_CUST_ORDER_STG.AUDIT_MODIFY_DATE,
	SAS_CUST_ORDER_STG.COD_LIST_AMOUNT,
	SAS_CUST_ORDER_STG.COD_TAX_RATE,
	SAS_CUST_ORDER_STG.COD_TAX,
	SAS_CUST_ORDER_STG.COD_TAX_DATE,
	SAS_CUST_ORDER_STG.CURRENCY_CODE,
	SAS_CUST_ORDER_STG.CURRENT_STATUS_CODE,
	SAS_CUST_ORDER_STG.ORDER_DATE,
	SAS_CUST_ORDER_STG.LIFETOUCH_USER_PROFILE_ID,
	SAS_CUST_ORDER_STG.ORDER_NUMBER,
	SAS_CUST_ORDER_STG.PROOF_DEPOSIT_APPLIED,
	SAS_CUST_ORDER_STG.PROOF_DEPOSIT_TOTAL,
	SAS_CUST_ORDER_STG.SHIPPING_DISCOUNT,
	SAS_CUST_ORDER_STG.SHIPPING_LIST_AMOUNT,
	SAS_CUST_ORDER_STG.SHIPPING_TAX_RATE,
	SAS_CUST_ORDER_STG.SHIPPING_TAX,
	SAS_CUST_ORDER_STG.SHIPPING_TAX_DATE,
	SAS_CUST_ORDER_STG.SHIPPING_CITY,
	SAS_CUST_ORDER_STG.SHIPPING_COUNTRY,
	SAS_CUST_ORDER_STG.SHIPPING_FIRSTNAME,
	SAS_CUST_ORDER_STG.SHIPPING_LASTNAME,
	SAS_CUST_ORDER_STG.SHIPPING_LINE1,
	SAS_CUST_ORDER_STG.SHIPPING_LINE2,
	SAS_CUST_ORDER_STG.SHIPPING_PHONE_NUMBER,
	SAS_CUST_ORDER_STG.SHIPPING_POSTAL_CODE,
	SAS_CUST_ORDER_STG.SHIPPING_STATE_PROVINCE,
	SAS_CUST_ORDER_STG.SENT_TO_SPECTRUM_IND,
	SAS_CUST_ORDER_STG.SENT_TO_SPECTRUM_DATE,
	SAS_CUST_ORDER_STG.TAX_AMOUNT,
	SAS_CUST_ORDER_STG.TAX_TOTAL_AS_OF_DATE,
	SAS_CUST_ORDER_STG.COD_PRODUCT_ID,
	SAS_CUST_ORDER_STG.PROMOTION_ID,
	SAS_CUST_ORDER_STG.SHIPPING_PRODUCT_ID,
	SAS_CUST_ORDER_STG.SUBJECT_ID,
	SAS_CUST_ORDER_STG.APO_ID,
	SAS_CUST_ORDER_STG.APPOINTMENT_ID,
	SAS_CUST_ORDER_STG.ODS_CREATE_DATE,
	SAS_CUST_ORDER_STG.ODS_MODIFY_DATE,
	SAS_CUST_ORDER_STG.DELETED_IND
from              '	
 || VariableCheckTable || 
' SAS_CUST_ORDER_STG
where	exists  (
		select	SUB.APPOINTMENT_ID
		from 	'
 || VariableCheckTable || 
' SUB
		where 	SUB.APPOINTMENT_ID=SAS_CUST_ORDER_STG.APPOINTMENT_ID
		group by 	SUB.APPOINTMENT_ID
		having 	count(1) > 1
		)
 ';

END;

/*  Checked Datastore =RAX_APP_USER.I$_SAS_CUST_ORDER_STG  */
/*  Integration Datastore =RAX_APP_USER.I$_SAS_CUST_ORDER_STG   */
/*  Target Datastore =ODS_STAGE.SAS_CUSTOMER_ORDER_STG */



&


/*-----------------------------------------------*/
/* TASK No. 23 */
/* Create index on AK */

 
/* FLOW CONTROL CREATE THE iNDEX ON THE I$TABLE */
-- create index 	SAS_CUSTOMER_ORDER_PK_flow
-- on	RAX_APP_USER.I$_SAS_CUST_ORDER_STG1386001 
-- 	(CUSTOMER_ORDER_ID)


BEGIN
  EXECUTE IMMEDIATE 'create index SAS_CUSTOMER_ORDER_PK_flow
on   RAX_APP_USER.I$_SAS_CUST_ORDER_STG1386001  (CUSTOMER_ORDER_ID)';
EXCEPTION
  WHEN OTHERS THEN
   -- Handle the case where the identifier is too long (ORA-00972)
   IF SQLCODE = -972 or  SQLCODE = -1408 or SQLCODE = -955  THEN
     DBMS_OUTPUT.PUT_LINE('Identifier is too long. Skipping creation of index.');
   ELSE
     RAISE;
   END IF;
END;

&


/*-----------------------------------------------*/
/* TASK No. 24 */
/* insert AK errors */

DECLARE
               CheckTable                             VarChar2(60);
               TargetTable                            VarChar2(60);
               VariableCheckTable                VarChar2(60);

BEGIN
               SELECT 'RAX_APP_USER.I$_SAS_CUST_ORDER_STG' INTO CheckTable FROM DUAL;
               SELECT 'ODS_STAGE.SAS_CUSTOMER_ORDER_STG' INTO TargetTable FROM DUAL;

IF CheckTable = TargetTable THEN
   VariableCheckTable := CheckTable; 
ELSE
   VariableCheckTable := CheckTable || '1386001';
END IF;

execute immediate '
insert into RAX_APP_USER.E$_SAS_CUST_ORDER_STG1386001
(
	ODI_PK,
	ODI_SESS_NO,
	ODI_ROW_ID,
	ODI_ERR_TYPE,
	ODI_ERR_MESS,
	ODI_ORIGIN,
	ODI_CHECK_DATE,
	ODI_CONS_NAME,
	ODI_CONS_TYPE,
	CUSTOMER_ORDER_ID,
	ADDRESSES_SAME,
	AUDIT_CREATE_DATE,
	AUDIT_CREATED_BY,
	AUDIT_MODIFIED_BY,
	AUDIT_MODIFY_DATE,
	COD_LIST_AMOUNT,
	COD_TAX_RATE,
	COD_TAX,
	COD_TAX_DATE,
	CURRENCY_CODE,
	CURRENT_STATUS_CODE,
	ORDER_DATE,
	LIFETOUCH_USER_PROFILE_ID,
	ORDER_NUMBER,
	PROOF_DEPOSIT_APPLIED,
	PROOF_DEPOSIT_TOTAL,
	SHIPPING_DISCOUNT,
	SHIPPING_LIST_AMOUNT,
	SHIPPING_TAX_RATE,
	SHIPPING_TAX,
	SHIPPING_TAX_DATE,
	SHIPPING_CITY,
	SHIPPING_COUNTRY,
	SHIPPING_FIRSTNAME,
	SHIPPING_LASTNAME,
	SHIPPING_LINE1,
	SHIPPING_LINE2,
	SHIPPING_PHONE_NUMBER,
	SHIPPING_POSTAL_CODE,
	SHIPPING_STATE_PROVINCE,
	SENT_TO_SPECTRUM_IND,
	SENT_TO_SPECTRUM_DATE,
	TAX_AMOUNT,
	TAX_TOTAL_AS_OF_DATE,
	COD_PRODUCT_ID,
	PROMOTION_ID,
	SHIPPING_PRODUCT_ID,
	SUBJECT_ID,
	APO_ID,
	APPOINTMENT_ID,
	ODS_CREATE_DATE,
	ODS_MODIFY_DATE,
	DELETED_IND
)
select	SYS_GUID(),
	:v_sess_no, 
	rowid,
	''F'', 
	''ODI-15063: The alternate key SAS_CUSTOMER_ORDER_PK is not unique.'',
	''(1386001)ODS_Project.LOAD_SAS_CUSTOMER_ORDER_STG_INT'',
	sysdate,
	''SAS_CUSTOMER_ORDER_PK'',
	''AK'',	
	SAS_CUST_ORDER_STG.CUSTOMER_ORDER_ID,
	SAS_CUST_ORDER_STG.ADDRESSES_SAME,
	SAS_CUST_ORDER_STG.AUDIT_CREATE_DATE,
	SAS_CUST_ORDER_STG.AUDIT_CREATED_BY,
	SAS_CUST_ORDER_STG.AUDIT_MODIFIED_BY,
	SAS_CUST_ORDER_STG.AUDIT_MODIFY_DATE,
	SAS_CUST_ORDER_STG.COD_LIST_AMOUNT,
	SAS_CUST_ORDER_STG.COD_TAX_RATE,
	SAS_CUST_ORDER_STG.COD_TAX,
	SAS_CUST_ORDER_STG.COD_TAX_DATE,
	SAS_CUST_ORDER_STG.CURRENCY_CODE,
	SAS_CUST_ORDER_STG.CURRENT_STATUS_CODE,
	SAS_CUST_ORDER_STG.ORDER_DATE,
	SAS_CUST_ORDER_STG.LIFETOUCH_USER_PROFILE_ID,
	SAS_CUST_ORDER_STG.ORDER_NUMBER,
	SAS_CUST_ORDER_STG.PROOF_DEPOSIT_APPLIED,
	SAS_CUST_ORDER_STG.PROOF_DEPOSIT_TOTAL,
	SAS_CUST_ORDER_STG.SHIPPING_DISCOUNT,
	SAS_CUST_ORDER_STG.SHIPPING_LIST_AMOUNT,
	SAS_CUST_ORDER_STG.SHIPPING_TAX_RATE,
	SAS_CUST_ORDER_STG.SHIPPING_TAX,
	SAS_CUST_ORDER_STG.SHIPPING_TAX_DATE,
	SAS_CUST_ORDER_STG.SHIPPING_CITY,
	SAS_CUST_ORDER_STG.SHIPPING_COUNTRY,
	SAS_CUST_ORDER_STG.SHIPPING_FIRSTNAME,
	SAS_CUST_ORDER_STG.SHIPPING_LASTNAME,
	SAS_CUST_ORDER_STG.SHIPPING_LINE1,
	SAS_CUST_ORDER_STG.SHIPPING_LINE2,
	SAS_CUST_ORDER_STG.SHIPPING_PHONE_NUMBER,
	SAS_CUST_ORDER_STG.SHIPPING_POSTAL_CODE,
	SAS_CUST_ORDER_STG.SHIPPING_STATE_PROVINCE,
	SAS_CUST_ORDER_STG.SENT_TO_SPECTRUM_IND,
	SAS_CUST_ORDER_STG.SENT_TO_SPECTRUM_DATE,
	SAS_CUST_ORDER_STG.TAX_AMOUNT,
	SAS_CUST_ORDER_STG.TAX_TOTAL_AS_OF_DATE,
	SAS_CUST_ORDER_STG.COD_PRODUCT_ID,
	SAS_CUST_ORDER_STG.PROMOTION_ID,
	SAS_CUST_ORDER_STG.SHIPPING_PRODUCT_ID,
	SAS_CUST_ORDER_STG.SUBJECT_ID,
	SAS_CUST_ORDER_STG.APO_ID,
	SAS_CUST_ORDER_STG.APPOINTMENT_ID,
	SAS_CUST_ORDER_STG.ODS_CREATE_DATE,
	SAS_CUST_ORDER_STG.ODS_MODIFY_DATE,
	SAS_CUST_ORDER_STG.DELETED_IND
from              '	
 || VariableCheckTable || 
' SAS_CUST_ORDER_STG
where	exists  (
		select	SUB.CUSTOMER_ORDER_ID
		from 	'
 || VariableCheckTable || 
' SUB
		where 	SUB.CUSTOMER_ORDER_ID=SAS_CUST_ORDER_STG.CUSTOMER_ORDER_ID
		group by 	SUB.CUSTOMER_ORDER_ID
		having 	count(1) > 1
		)
 ';

END;

/*  Checked Datastore =RAX_APP_USER.I$_SAS_CUST_ORDER_STG  */
/*  Integration Datastore =RAX_APP_USER.I$_SAS_CUST_ORDER_STG   */
/*  Target Datastore =ODS_STAGE.SAS_CUSTOMER_ORDER_STG */



&


/*-----------------------------------------------*/
/* TASK No. 25 */
/* insert Not Null errors */

insert into RAX_APP_USER.E$_SAS_CUST_ORDER_STG1386001
(
	ODI_PK,
	ODI_SESS_NO,
	ODI_ROW_ID,
	ODI_ERR_TYPE,
	ODI_ERR_MESS,
	ODI_CHECK_DATE,
	ODI_ORIGIN,
	ODI_CONS_NAME,
	ODI_CONS_TYPE,
	CUSTOMER_ORDER_ID,
	ADDRESSES_SAME,
	AUDIT_CREATE_DATE,
	AUDIT_CREATED_BY,
	AUDIT_MODIFIED_BY,
	AUDIT_MODIFY_DATE,
	COD_LIST_AMOUNT,
	COD_TAX_RATE,
	COD_TAX,
	COD_TAX_DATE,
	CURRENCY_CODE,
	CURRENT_STATUS_CODE,
	ORDER_DATE,
	LIFETOUCH_USER_PROFILE_ID,
	ORDER_NUMBER,
	PROOF_DEPOSIT_APPLIED,
	PROOF_DEPOSIT_TOTAL,
	SHIPPING_DISCOUNT,
	SHIPPING_LIST_AMOUNT,
	SHIPPING_TAX_RATE,
	SHIPPING_TAX,
	SHIPPING_TAX_DATE,
	SHIPPING_CITY,
	SHIPPING_COUNTRY,
	SHIPPING_FIRSTNAME,
	SHIPPING_LASTNAME,
	SHIPPING_LINE1,
	SHIPPING_LINE2,
	SHIPPING_PHONE_NUMBER,
	SHIPPING_POSTAL_CODE,
	SHIPPING_STATE_PROVINCE,
	SENT_TO_SPECTRUM_IND,
	SENT_TO_SPECTRUM_DATE,
	TAX_AMOUNT,
	TAX_TOTAL_AS_OF_DATE,
	COD_PRODUCT_ID,
	PROMOTION_ID,
	SHIPPING_PRODUCT_ID,
	SUBJECT_ID,
	APO_ID,
	APPOINTMENT_ID,
	ODS_CREATE_DATE,
	ODS_MODIFY_DATE,
	DELETED_IND
)
select
	SYS_GUID(),
	:v_sess_no, 
	rowid,
	'F', 
	'ODI-15066: The column CUSTOMER_ORDER_ID cannot be null.',
	sysdate,
	'(1386001)ODS_Project.LOAD_SAS_CUSTOMER_ORDER_STG_INT',
	'CUSTOMER_ORDER_ID',
	'NN',	
	CUSTOMER_ORDER_ID,
	ADDRESSES_SAME,
	AUDIT_CREATE_DATE,
	AUDIT_CREATED_BY,
	AUDIT_MODIFIED_BY,
	AUDIT_MODIFY_DATE,
	COD_LIST_AMOUNT,
	COD_TAX_RATE,
	COD_TAX,
	COD_TAX_DATE,
	CURRENCY_CODE,
	CURRENT_STATUS_CODE,
	ORDER_DATE,
	LIFETOUCH_USER_PROFILE_ID,
	ORDER_NUMBER,
	PROOF_DEPOSIT_APPLIED,
	PROOF_DEPOSIT_TOTAL,
	SHIPPING_DISCOUNT,
	SHIPPING_LIST_AMOUNT,
	SHIPPING_TAX_RATE,
	SHIPPING_TAX,
	SHIPPING_TAX_DATE,
	SHIPPING_CITY,
	SHIPPING_COUNTRY,
	SHIPPING_FIRSTNAME,
	SHIPPING_LASTNAME,
	SHIPPING_LINE1,
	SHIPPING_LINE2,
	SHIPPING_PHONE_NUMBER,
	SHIPPING_POSTAL_CODE,
	SHIPPING_STATE_PROVINCE,
	SENT_TO_SPECTRUM_IND,
	SENT_TO_SPECTRUM_DATE,
	TAX_AMOUNT,
	TAX_TOTAL_AS_OF_DATE,
	COD_PRODUCT_ID,
	PROMOTION_ID,
	SHIPPING_PRODUCT_ID,
	SUBJECT_ID,
	APO_ID,
	APPOINTMENT_ID,
	ODS_CREATE_DATE,
	ODS_MODIFY_DATE,
	DELETED_IND
from	RAX_APP_USER.I$_SAS_CUST_ORDER_STG1386001
where	CUSTOMER_ORDER_ID is null



&


/*-----------------------------------------------*/
/* TASK No. 26 */
/* insert Not Null errors */

insert into RAX_APP_USER.E$_SAS_CUST_ORDER_STG1386001
(
	ODI_PK,
	ODI_SESS_NO,
	ODI_ROW_ID,
	ODI_ERR_TYPE,
	ODI_ERR_MESS,
	ODI_CHECK_DATE,
	ODI_ORIGIN,
	ODI_CONS_NAME,
	ODI_CONS_TYPE,
	CUSTOMER_ORDER_ID,
	ADDRESSES_SAME,
	AUDIT_CREATE_DATE,
	AUDIT_CREATED_BY,
	AUDIT_MODIFIED_BY,
	AUDIT_MODIFY_DATE,
	COD_LIST_AMOUNT,
	COD_TAX_RATE,
	COD_TAX,
	COD_TAX_DATE,
	CURRENCY_CODE,
	CURRENT_STATUS_CODE,
	ORDER_DATE,
	LIFETOUCH_USER_PROFILE_ID,
	ORDER_NUMBER,
	PROOF_DEPOSIT_APPLIED,
	PROOF_DEPOSIT_TOTAL,
	SHIPPING_DISCOUNT,
	SHIPPING_LIST_AMOUNT,
	SHIPPING_TAX_RATE,
	SHIPPING_TAX,
	SHIPPING_TAX_DATE,
	SHIPPING_CITY,
	SHIPPING_COUNTRY,
	SHIPPING_FIRSTNAME,
	SHIPPING_LASTNAME,
	SHIPPING_LINE1,
	SHIPPING_LINE2,
	SHIPPING_PHONE_NUMBER,
	SHIPPING_POSTAL_CODE,
	SHIPPING_STATE_PROVINCE,
	SENT_TO_SPECTRUM_IND,
	SENT_TO_SPECTRUM_DATE,
	TAX_AMOUNT,
	TAX_TOTAL_AS_OF_DATE,
	COD_PRODUCT_ID,
	PROMOTION_ID,
	SHIPPING_PRODUCT_ID,
	SUBJECT_ID,
	APO_ID,
	APPOINTMENT_ID,
	ODS_CREATE_DATE,
	ODS_MODIFY_DATE,
	DELETED_IND
)
select
	SYS_GUID(),
	:v_sess_no, 
	rowid,
	'F', 
	'ODI-15066: The column AUDIT_CREATE_DATE cannot be null.',
	sysdate,
	'(1386001)ODS_Project.LOAD_SAS_CUSTOMER_ORDER_STG_INT',
	'AUDIT_CREATE_DATE',
	'NN',	
	CUSTOMER_ORDER_ID,
	ADDRESSES_SAME,
	AUDIT_CREATE_DATE,
	AUDIT_CREATED_BY,
	AUDIT_MODIFIED_BY,
	AUDIT_MODIFY_DATE,
	COD_LIST_AMOUNT,
	COD_TAX_RATE,
	COD_TAX,
	COD_TAX_DATE,
	CURRENCY_CODE,
	CURRENT_STATUS_CODE,
	ORDER_DATE,
	LIFETOUCH_USER_PROFILE_ID,
	ORDER_NUMBER,
	PROOF_DEPOSIT_APPLIED,
	PROOF_DEPOSIT_TOTAL,
	SHIPPING_DISCOUNT,
	SHIPPING_LIST_AMOUNT,
	SHIPPING_TAX_RATE,
	SHIPPING_TAX,
	SHIPPING_TAX_DATE,
	SHIPPING_CITY,
	SHIPPING_COUNTRY,
	SHIPPING_FIRSTNAME,
	SHIPPING_LASTNAME,
	SHIPPING_LINE1,
	SHIPPING_LINE2,
	SHIPPING_PHONE_NUMBER,
	SHIPPING_POSTAL_CODE,
	SHIPPING_STATE_PROVINCE,
	SENT_TO_SPECTRUM_IND,
	SENT_TO_SPECTRUM_DATE,
	TAX_AMOUNT,
	TAX_TOTAL_AS_OF_DATE,
	COD_PRODUCT_ID,
	PROMOTION_ID,
	SHIPPING_PRODUCT_ID,
	SUBJECT_ID,
	APO_ID,
	APPOINTMENT_ID,
	ODS_CREATE_DATE,
	ODS_MODIFY_DATE,
	DELETED_IND
from	RAX_APP_USER.I$_SAS_CUST_ORDER_STG1386001
where	AUDIT_CREATE_DATE is null



&


/*-----------------------------------------------*/
/* TASK No. 27 */
/* insert Not Null errors */

insert into RAX_APP_USER.E$_SAS_CUST_ORDER_STG1386001
(
	ODI_PK,
	ODI_SESS_NO,
	ODI_ROW_ID,
	ODI_ERR_TYPE,
	ODI_ERR_MESS,
	ODI_CHECK_DATE,
	ODI_ORIGIN,
	ODI_CONS_NAME,
	ODI_CONS_TYPE,
	CUSTOMER_ORDER_ID,
	ADDRESSES_SAME,
	AUDIT_CREATE_DATE,
	AUDIT_CREATED_BY,
	AUDIT_MODIFIED_BY,
	AUDIT_MODIFY_DATE,
	COD_LIST_AMOUNT,
	COD_TAX_RATE,
	COD_TAX,
	COD_TAX_DATE,
	CURRENCY_CODE,
	CURRENT_STATUS_CODE,
	ORDER_DATE,
	LIFETOUCH_USER_PROFILE_ID,
	ORDER_NUMBER,
	PROOF_DEPOSIT_APPLIED,
	PROOF_DEPOSIT_TOTAL,
	SHIPPING_DISCOUNT,
	SHIPPING_LIST_AMOUNT,
	SHIPPING_TAX_RATE,
	SHIPPING_TAX,
	SHIPPING_TAX_DATE,
	SHIPPING_CITY,
	SHIPPING_COUNTRY,
	SHIPPING_FIRSTNAME,
	SHIPPING_LASTNAME,
	SHIPPING_LINE1,
	SHIPPING_LINE2,
	SHIPPING_PHONE_NUMBER,
	SHIPPING_POSTAL_CODE,
	SHIPPING_STATE_PROVINCE,
	SENT_TO_SPECTRUM_IND,
	SENT_TO_SPECTRUM_DATE,
	TAX_AMOUNT,
	TAX_TOTAL_AS_OF_DATE,
	COD_PRODUCT_ID,
	PROMOTION_ID,
	SHIPPING_PRODUCT_ID,
	SUBJECT_ID,
	APO_ID,
	APPOINTMENT_ID,
	ODS_CREATE_DATE,
	ODS_MODIFY_DATE,
	DELETED_IND
)
select
	SYS_GUID(),
	:v_sess_no, 
	rowid,
	'F', 
	'ODI-15066: The column AUDIT_CREATED_BY cannot be null.',
	sysdate,
	'(1386001)ODS_Project.LOAD_SAS_CUSTOMER_ORDER_STG_INT',
	'AUDIT_CREATED_BY',
	'NN',	
	CUSTOMER_ORDER_ID,
	ADDRESSES_SAME,
	AUDIT_CREATE_DATE,
	AUDIT_CREATED_BY,
	AUDIT_MODIFIED_BY,
	AUDIT_MODIFY_DATE,
	COD_LIST_AMOUNT,
	COD_TAX_RATE,
	COD_TAX,
	COD_TAX_DATE,
	CURRENCY_CODE,
	CURRENT_STATUS_CODE,
	ORDER_DATE,
	LIFETOUCH_USER_PROFILE_ID,
	ORDER_NUMBER,
	PROOF_DEPOSIT_APPLIED,
	PROOF_DEPOSIT_TOTAL,
	SHIPPING_DISCOUNT,
	SHIPPING_LIST_AMOUNT,
	SHIPPING_TAX_RATE,
	SHIPPING_TAX,
	SHIPPING_TAX_DATE,
	SHIPPING_CITY,
	SHIPPING_COUNTRY,
	SHIPPING_FIRSTNAME,
	SHIPPING_LASTNAME,
	SHIPPING_LINE1,
	SHIPPING_LINE2,
	SHIPPING_PHONE_NUMBER,
	SHIPPING_POSTAL_CODE,
	SHIPPING_STATE_PROVINCE,
	SENT_TO_SPECTRUM_IND,
	SENT_TO_SPECTRUM_DATE,
	TAX_AMOUNT,
	TAX_TOTAL_AS_OF_DATE,
	COD_PRODUCT_ID,
	PROMOTION_ID,
	SHIPPING_PRODUCT_ID,
	SUBJECT_ID,
	APO_ID,
	APPOINTMENT_ID,
	ODS_CREATE_DATE,
	ODS_MODIFY_DATE,
	DELETED_IND
from	RAX_APP_USER.I$_SAS_CUST_ORDER_STG1386001
where	AUDIT_CREATED_BY is null



&


/*-----------------------------------------------*/
/* TASK No. 28 */
/* insert Not Null errors */

insert into RAX_APP_USER.E$_SAS_CUST_ORDER_STG1386001
(
	ODI_PK,
	ODI_SESS_NO,
	ODI_ROW_ID,
	ODI_ERR_TYPE,
	ODI_ERR_MESS,
	ODI_CHECK_DATE,
	ODI_ORIGIN,
	ODI_CONS_NAME,
	ODI_CONS_TYPE,
	CUSTOMER_ORDER_ID,
	ADDRESSES_SAME,
	AUDIT_CREATE_DATE,
	AUDIT_CREATED_BY,
	AUDIT_MODIFIED_BY,
	AUDIT_MODIFY_DATE,
	COD_LIST_AMOUNT,
	COD_TAX_RATE,
	COD_TAX,
	COD_TAX_DATE,
	CURRENCY_CODE,
	CURRENT_STATUS_CODE,
	ORDER_DATE,
	LIFETOUCH_USER_PROFILE_ID,
	ORDER_NUMBER,
	PROOF_DEPOSIT_APPLIED,
	PROOF_DEPOSIT_TOTAL,
	SHIPPING_DISCOUNT,
	SHIPPING_LIST_AMOUNT,
	SHIPPING_TAX_RATE,
	SHIPPING_TAX,
	SHIPPING_TAX_DATE,
	SHIPPING_CITY,
	SHIPPING_COUNTRY,
	SHIPPING_FIRSTNAME,
	SHIPPING_LASTNAME,
	SHIPPING_LINE1,
	SHIPPING_LINE2,
	SHIPPING_PHONE_NUMBER,
	SHIPPING_POSTAL_CODE,
	SHIPPING_STATE_PROVINCE,
	SENT_TO_SPECTRUM_IND,
	SENT_TO_SPECTRUM_DATE,
	TAX_AMOUNT,
	TAX_TOTAL_AS_OF_DATE,
	COD_PRODUCT_ID,
	PROMOTION_ID,
	SHIPPING_PRODUCT_ID,
	SUBJECT_ID,
	APO_ID,
	APPOINTMENT_ID,
	ODS_CREATE_DATE,
	ODS_MODIFY_DATE,
	DELETED_IND
)
select
	SYS_GUID(),
	:v_sess_no, 
	rowid,
	'F', 
	'ODI-15066: The column AUDIT_MODIFIED_BY cannot be null.',
	sysdate,
	'(1386001)ODS_Project.LOAD_SAS_CUSTOMER_ORDER_STG_INT',
	'AUDIT_MODIFIED_BY',
	'NN',	
	CUSTOMER_ORDER_ID,
	ADDRESSES_SAME,
	AUDIT_CREATE_DATE,
	AUDIT_CREATED_BY,
	AUDIT_MODIFIED_BY,
	AUDIT_MODIFY_DATE,
	COD_LIST_AMOUNT,
	COD_TAX_RATE,
	COD_TAX,
	COD_TAX_DATE,
	CURRENCY_CODE,
	CURRENT_STATUS_CODE,
	ORDER_DATE,
	LIFETOUCH_USER_PROFILE_ID,
	ORDER_NUMBER,
	PROOF_DEPOSIT_APPLIED,
	PROOF_DEPOSIT_TOTAL,
	SHIPPING_DISCOUNT,
	SHIPPING_LIST_AMOUNT,
	SHIPPING_TAX_RATE,
	SHIPPING_TAX,
	SHIPPING_TAX_DATE,
	SHIPPING_CITY,
	SHIPPING_COUNTRY,
	SHIPPING_FIRSTNAME,
	SHIPPING_LASTNAME,
	SHIPPING_LINE1,
	SHIPPING_LINE2,
	SHIPPING_PHONE_NUMBER,
	SHIPPING_POSTAL_CODE,
	SHIPPING_STATE_PROVINCE,
	SENT_TO_SPECTRUM_IND,
	SENT_TO_SPECTRUM_DATE,
	TAX_AMOUNT,
	TAX_TOTAL_AS_OF_DATE,
	COD_PRODUCT_ID,
	PROMOTION_ID,
	SHIPPING_PRODUCT_ID,
	SUBJECT_ID,
	APO_ID,
	APPOINTMENT_ID,
	ODS_CREATE_DATE,
	ODS_MODIFY_DATE,
	DELETED_IND
from	RAX_APP_USER.I$_SAS_CUST_ORDER_STG1386001
where	AUDIT_MODIFIED_BY is null



&


/*-----------------------------------------------*/
/* TASK No. 29 */
/* insert Not Null errors */

insert into RAX_APP_USER.E$_SAS_CUST_ORDER_STG1386001
(
	ODI_PK,
	ODI_SESS_NO,
	ODI_ROW_ID,
	ODI_ERR_TYPE,
	ODI_ERR_MESS,
	ODI_CHECK_DATE,
	ODI_ORIGIN,
	ODI_CONS_NAME,
	ODI_CONS_TYPE,
	CUSTOMER_ORDER_ID,
	ADDRESSES_SAME,
	AUDIT_CREATE_DATE,
	AUDIT_CREATED_BY,
	AUDIT_MODIFIED_BY,
	AUDIT_MODIFY_DATE,
	COD_LIST_AMOUNT,
	COD_TAX_RATE,
	COD_TAX,
	COD_TAX_DATE,
	CURRENCY_CODE,
	CURRENT_STATUS_CODE,
	ORDER_DATE,
	LIFETOUCH_USER_PROFILE_ID,
	ORDER_NUMBER,
	PROOF_DEPOSIT_APPLIED,
	PROOF_DEPOSIT_TOTAL,
	SHIPPING_DISCOUNT,
	SHIPPING_LIST_AMOUNT,
	SHIPPING_TAX_RATE,
	SHIPPING_TAX,
	SHIPPING_TAX_DATE,
	SHIPPING_CITY,
	SHIPPING_COUNTRY,
	SHIPPING_FIRSTNAME,
	SHIPPING_LASTNAME,
	SHIPPING_LINE1,
	SHIPPING_LINE2,
	SHIPPING_PHONE_NUMBER,
	SHIPPING_POSTAL_CODE,
	SHIPPING_STATE_PROVINCE,
	SENT_TO_SPECTRUM_IND,
	SENT_TO_SPECTRUM_DATE,
	TAX_AMOUNT,
	TAX_TOTAL_AS_OF_DATE,
	COD_PRODUCT_ID,
	PROMOTION_ID,
	SHIPPING_PRODUCT_ID,
	SUBJECT_ID,
	APO_ID,
	APPOINTMENT_ID,
	ODS_CREATE_DATE,
	ODS_MODIFY_DATE,
	DELETED_IND
)
select
	SYS_GUID(),
	:v_sess_no, 
	rowid,
	'F', 
	'ODI-15066: The column AUDIT_MODIFY_DATE cannot be null.',
	sysdate,
	'(1386001)ODS_Project.LOAD_SAS_CUSTOMER_ORDER_STG_INT',
	'AUDIT_MODIFY_DATE',
	'NN',	
	CUSTOMER_ORDER_ID,
	ADDRESSES_SAME,
	AUDIT_CREATE_DATE,
	AUDIT_CREATED_BY,
	AUDIT_MODIFIED_BY,
	AUDIT_MODIFY_DATE,
	COD_LIST_AMOUNT,
	COD_TAX_RATE,
	COD_TAX,
	COD_TAX_DATE,
	CURRENCY_CODE,
	CURRENT_STATUS_CODE,
	ORDER_DATE,
	LIFETOUCH_USER_PROFILE_ID,
	ORDER_NUMBER,
	PROOF_DEPOSIT_APPLIED,
	PROOF_DEPOSIT_TOTAL,
	SHIPPING_DISCOUNT,
	SHIPPING_LIST_AMOUNT,
	SHIPPING_TAX_RATE,
	SHIPPING_TAX,
	SHIPPING_TAX_DATE,
	SHIPPING_CITY,
	SHIPPING_COUNTRY,
	SHIPPING_FIRSTNAME,
	SHIPPING_LASTNAME,
	SHIPPING_LINE1,
	SHIPPING_LINE2,
	SHIPPING_PHONE_NUMBER,
	SHIPPING_POSTAL_CODE,
	SHIPPING_STATE_PROVINCE,
	SENT_TO_SPECTRUM_IND,
	SENT_TO_SPECTRUM_DATE,
	TAX_AMOUNT,
	TAX_TOTAL_AS_OF_DATE,
	COD_PRODUCT_ID,
	PROMOTION_ID,
	SHIPPING_PRODUCT_ID,
	SUBJECT_ID,
	APO_ID,
	APPOINTMENT_ID,
	ODS_CREATE_DATE,
	ODS_MODIFY_DATE,
	DELETED_IND
from	RAX_APP_USER.I$_SAS_CUST_ORDER_STG1386001
where	AUDIT_MODIFY_DATE is null



&


/*-----------------------------------------------*/
/* TASK No. 30 */
/* insert Not Null errors */

insert into RAX_APP_USER.E$_SAS_CUST_ORDER_STG1386001
(
	ODI_PK,
	ODI_SESS_NO,
	ODI_ROW_ID,
	ODI_ERR_TYPE,
	ODI_ERR_MESS,
	ODI_CHECK_DATE,
	ODI_ORIGIN,
	ODI_CONS_NAME,
	ODI_CONS_TYPE,
	CUSTOMER_ORDER_ID,
	ADDRESSES_SAME,
	AUDIT_CREATE_DATE,
	AUDIT_CREATED_BY,
	AUDIT_MODIFIED_BY,
	AUDIT_MODIFY_DATE,
	COD_LIST_AMOUNT,
	COD_TAX_RATE,
	COD_TAX,
	COD_TAX_DATE,
	CURRENCY_CODE,
	CURRENT_STATUS_CODE,
	ORDER_DATE,
	LIFETOUCH_USER_PROFILE_ID,
	ORDER_NUMBER,
	PROOF_DEPOSIT_APPLIED,
	PROOF_DEPOSIT_TOTAL,
	SHIPPING_DISCOUNT,
	SHIPPING_LIST_AMOUNT,
	SHIPPING_TAX_RATE,
	SHIPPING_TAX,
	SHIPPING_TAX_DATE,
	SHIPPING_CITY,
	SHIPPING_COUNTRY,
	SHIPPING_FIRSTNAME,
	SHIPPING_LASTNAME,
	SHIPPING_LINE1,
	SHIPPING_LINE2,
	SHIPPING_PHONE_NUMBER,
	SHIPPING_POSTAL_CODE,
	SHIPPING_STATE_PROVINCE,
	SENT_TO_SPECTRUM_IND,
	SENT_TO_SPECTRUM_DATE,
	TAX_AMOUNT,
	TAX_TOTAL_AS_OF_DATE,
	COD_PRODUCT_ID,
	PROMOTION_ID,
	SHIPPING_PRODUCT_ID,
	SUBJECT_ID,
	APO_ID,
	APPOINTMENT_ID,
	ODS_CREATE_DATE,
	ODS_MODIFY_DATE,
	DELETED_IND
)
select
	SYS_GUID(),
	:v_sess_no, 
	rowid,
	'F', 
	'ODI-15066: The column CURRENCY_CODE cannot be null.',
	sysdate,
	'(1386001)ODS_Project.LOAD_SAS_CUSTOMER_ORDER_STG_INT',
	'CURRENCY_CODE',
	'NN',	
	CUSTOMER_ORDER_ID,
	ADDRESSES_SAME,
	AUDIT_CREATE_DATE,
	AUDIT_CREATED_BY,
	AUDIT_MODIFIED_BY,
	AUDIT_MODIFY_DATE,
	COD_LIST_AMOUNT,
	COD_TAX_RATE,
	COD_TAX,
	COD_TAX_DATE,
	CURRENCY_CODE,
	CURRENT_STATUS_CODE,
	ORDER_DATE,
	LIFETOUCH_USER_PROFILE_ID,
	ORDER_NUMBER,
	PROOF_DEPOSIT_APPLIED,
	PROOF_DEPOSIT_TOTAL,
	SHIPPING_DISCOUNT,
	SHIPPING_LIST_AMOUNT,
	SHIPPING_TAX_RATE,
	SHIPPING_TAX,
	SHIPPING_TAX_DATE,
	SHIPPING_CITY,
	SHIPPING_COUNTRY,
	SHIPPING_FIRSTNAME,
	SHIPPING_LASTNAME,
	SHIPPING_LINE1,
	SHIPPING_LINE2,
	SHIPPING_PHONE_NUMBER,
	SHIPPING_POSTAL_CODE,
	SHIPPING_STATE_PROVINCE,
	SENT_TO_SPECTRUM_IND,
	SENT_TO_SPECTRUM_DATE,
	TAX_AMOUNT,
	TAX_TOTAL_AS_OF_DATE,
	COD_PRODUCT_ID,
	PROMOTION_ID,
	SHIPPING_PRODUCT_ID,
	SUBJECT_ID,
	APO_ID,
	APPOINTMENT_ID,
	ODS_CREATE_DATE,
	ODS_MODIFY_DATE,
	DELETED_IND
from	RAX_APP_USER.I$_SAS_CUST_ORDER_STG1386001
where	CURRENCY_CODE is null



&


/*-----------------------------------------------*/
/* TASK No. 31 */
/* insert Not Null errors */

insert into RAX_APP_USER.E$_SAS_CUST_ORDER_STG1386001
(
	ODI_PK,
	ODI_SESS_NO,
	ODI_ROW_ID,
	ODI_ERR_TYPE,
	ODI_ERR_MESS,
	ODI_CHECK_DATE,
	ODI_ORIGIN,
	ODI_CONS_NAME,
	ODI_CONS_TYPE,
	CUSTOMER_ORDER_ID,
	ADDRESSES_SAME,
	AUDIT_CREATE_DATE,
	AUDIT_CREATED_BY,
	AUDIT_MODIFIED_BY,
	AUDIT_MODIFY_DATE,
	COD_LIST_AMOUNT,
	COD_TAX_RATE,
	COD_TAX,
	COD_TAX_DATE,
	CURRENCY_CODE,
	CURRENT_STATUS_CODE,
	ORDER_DATE,
	LIFETOUCH_USER_PROFILE_ID,
	ORDER_NUMBER,
	PROOF_DEPOSIT_APPLIED,
	PROOF_DEPOSIT_TOTAL,
	SHIPPING_DISCOUNT,
	SHIPPING_LIST_AMOUNT,
	SHIPPING_TAX_RATE,
	SHIPPING_TAX,
	SHIPPING_TAX_DATE,
	SHIPPING_CITY,
	SHIPPING_COUNTRY,
	SHIPPING_FIRSTNAME,
	SHIPPING_LASTNAME,
	SHIPPING_LINE1,
	SHIPPING_LINE2,
	SHIPPING_PHONE_NUMBER,
	SHIPPING_POSTAL_CODE,
	SHIPPING_STATE_PROVINCE,
	SENT_TO_SPECTRUM_IND,
	SENT_TO_SPECTRUM_DATE,
	TAX_AMOUNT,
	TAX_TOTAL_AS_OF_DATE,
	COD_PRODUCT_ID,
	PROMOTION_ID,
	SHIPPING_PRODUCT_ID,
	SUBJECT_ID,
	APO_ID,
	APPOINTMENT_ID,
	ODS_CREATE_DATE,
	ODS_MODIFY_DATE,
	DELETED_IND
)
select
	SYS_GUID(),
	:v_sess_no, 
	rowid,
	'F', 
	'ODI-15066: The column ORDER_DATE cannot be null.',
	sysdate,
	'(1386001)ODS_Project.LOAD_SAS_CUSTOMER_ORDER_STG_INT',
	'ORDER_DATE',
	'NN',	
	CUSTOMER_ORDER_ID,
	ADDRESSES_SAME,
	AUDIT_CREATE_DATE,
	AUDIT_CREATED_BY,
	AUDIT_MODIFIED_BY,
	AUDIT_MODIFY_DATE,
	COD_LIST_AMOUNT,
	COD_TAX_RATE,
	COD_TAX,
	COD_TAX_DATE,
	CURRENCY_CODE,
	CURRENT_STATUS_CODE,
	ORDER_DATE,
	LIFETOUCH_USER_PROFILE_ID,
	ORDER_NUMBER,
	PROOF_DEPOSIT_APPLIED,
	PROOF_DEPOSIT_TOTAL,
	SHIPPING_DISCOUNT,
	SHIPPING_LIST_AMOUNT,
	SHIPPING_TAX_RATE,
	SHIPPING_TAX,
	SHIPPING_TAX_DATE,
	SHIPPING_CITY,
	SHIPPING_COUNTRY,
	SHIPPING_FIRSTNAME,
	SHIPPING_LASTNAME,
	SHIPPING_LINE1,
	SHIPPING_LINE2,
	SHIPPING_PHONE_NUMBER,
	SHIPPING_POSTAL_CODE,
	SHIPPING_STATE_PROVINCE,
	SENT_TO_SPECTRUM_IND,
	SENT_TO_SPECTRUM_DATE,
	TAX_AMOUNT,
	TAX_TOTAL_AS_OF_DATE,
	COD_PRODUCT_ID,
	PROMOTION_ID,
	SHIPPING_PRODUCT_ID,
	SUBJECT_ID,
	APO_ID,
	APPOINTMENT_ID,
	ODS_CREATE_DATE,
	ODS_MODIFY_DATE,
	DELETED_IND
from	RAX_APP_USER.I$_SAS_CUST_ORDER_STG1386001
where	ORDER_DATE is null



&


/*-----------------------------------------------*/
/* TASK No. 32 */
/* insert Not Null errors */

insert into RAX_APP_USER.E$_SAS_CUST_ORDER_STG1386001
(
	ODI_PK,
	ODI_SESS_NO,
	ODI_ROW_ID,
	ODI_ERR_TYPE,
	ODI_ERR_MESS,
	ODI_CHECK_DATE,
	ODI_ORIGIN,
	ODI_CONS_NAME,
	ODI_CONS_TYPE,
	CUSTOMER_ORDER_ID,
	ADDRESSES_SAME,
	AUDIT_CREATE_DATE,
	AUDIT_CREATED_BY,
	AUDIT_MODIFIED_BY,
	AUDIT_MODIFY_DATE,
	COD_LIST_AMOUNT,
	COD_TAX_RATE,
	COD_TAX,
	COD_TAX_DATE,
	CURRENCY_CODE,
	CURRENT_STATUS_CODE,
	ORDER_DATE,
	LIFETOUCH_USER_PROFILE_ID,
	ORDER_NUMBER,
	PROOF_DEPOSIT_APPLIED,
	PROOF_DEPOSIT_TOTAL,
	SHIPPING_DISCOUNT,
	SHIPPING_LIST_AMOUNT,
	SHIPPING_TAX_RATE,
	SHIPPING_TAX,
	SHIPPING_TAX_DATE,
	SHIPPING_CITY,
	SHIPPING_COUNTRY,
	SHIPPING_FIRSTNAME,
	SHIPPING_LASTNAME,
	SHIPPING_LINE1,
	SHIPPING_LINE2,
	SHIPPING_PHONE_NUMBER,
	SHIPPING_POSTAL_CODE,
	SHIPPING_STATE_PROVINCE,
	SENT_TO_SPECTRUM_IND,
	SENT_TO_SPECTRUM_DATE,
	TAX_AMOUNT,
	TAX_TOTAL_AS_OF_DATE,
	COD_PRODUCT_ID,
	PROMOTION_ID,
	SHIPPING_PRODUCT_ID,
	SUBJECT_ID,
	APO_ID,
	APPOINTMENT_ID,
	ODS_CREATE_DATE,
	ODS_MODIFY_DATE,
	DELETED_IND
)
select
	SYS_GUID(),
	:v_sess_no, 
	rowid,
	'F', 
	'ODI-15066: The column SENT_TO_SPECTRUM_IND cannot be null.',
	sysdate,
	'(1386001)ODS_Project.LOAD_SAS_CUSTOMER_ORDER_STG_INT',
	'SENT_TO_SPECTRUM_IND',
	'NN',	
	CUSTOMER_ORDER_ID,
	ADDRESSES_SAME,
	AUDIT_CREATE_DATE,
	AUDIT_CREATED_BY,
	AUDIT_MODIFIED_BY,
	AUDIT_MODIFY_DATE,
	COD_LIST_AMOUNT,
	COD_TAX_RATE,
	COD_TAX,
	COD_TAX_DATE,
	CURRENCY_CODE,
	CURRENT_STATUS_CODE,
	ORDER_DATE,
	LIFETOUCH_USER_PROFILE_ID,
	ORDER_NUMBER,
	PROOF_DEPOSIT_APPLIED,
	PROOF_DEPOSIT_TOTAL,
	SHIPPING_DISCOUNT,
	SHIPPING_LIST_AMOUNT,
	SHIPPING_TAX_RATE,
	SHIPPING_TAX,
	SHIPPING_TAX_DATE,
	SHIPPING_CITY,
	SHIPPING_COUNTRY,
	SHIPPING_FIRSTNAME,
	SHIPPING_LASTNAME,
	SHIPPING_LINE1,
	SHIPPING_LINE2,
	SHIPPING_PHONE_NUMBER,
	SHIPPING_POSTAL_CODE,
	SHIPPING_STATE_PROVINCE,
	SENT_TO_SPECTRUM_IND,
	SENT_TO_SPECTRUM_DATE,
	TAX_AMOUNT,
	TAX_TOTAL_AS_OF_DATE,
	COD_PRODUCT_ID,
	PROMOTION_ID,
	SHIPPING_PRODUCT_ID,
	SUBJECT_ID,
	APO_ID,
	APPOINTMENT_ID,
	ODS_CREATE_DATE,
	ODS_MODIFY_DATE,
	DELETED_IND
from	RAX_APP_USER.I$_SAS_CUST_ORDER_STG1386001
where	SENT_TO_SPECTRUM_IND is null



&


/*-----------------------------------------------*/
/* TASK No. 33 */
/* insert Not Null errors */

insert into RAX_APP_USER.E$_SAS_CUST_ORDER_STG1386001
(
	ODI_PK,
	ODI_SESS_NO,
	ODI_ROW_ID,
	ODI_ERR_TYPE,
	ODI_ERR_MESS,
	ODI_CHECK_DATE,
	ODI_ORIGIN,
	ODI_CONS_NAME,
	ODI_CONS_TYPE,
	CUSTOMER_ORDER_ID,
	ADDRESSES_SAME,
	AUDIT_CREATE_DATE,
	AUDIT_CREATED_BY,
	AUDIT_MODIFIED_BY,
	AUDIT_MODIFY_DATE,
	COD_LIST_AMOUNT,
	COD_TAX_RATE,
	COD_TAX,
	COD_TAX_DATE,
	CURRENCY_CODE,
	CURRENT_STATUS_CODE,
	ORDER_DATE,
	LIFETOUCH_USER_PROFILE_ID,
	ORDER_NUMBER,
	PROOF_DEPOSIT_APPLIED,
	PROOF_DEPOSIT_TOTAL,
	SHIPPING_DISCOUNT,
	SHIPPING_LIST_AMOUNT,
	SHIPPING_TAX_RATE,
	SHIPPING_TAX,
	SHIPPING_TAX_DATE,
	SHIPPING_CITY,
	SHIPPING_COUNTRY,
	SHIPPING_FIRSTNAME,
	SHIPPING_LASTNAME,
	SHIPPING_LINE1,
	SHIPPING_LINE2,
	SHIPPING_PHONE_NUMBER,
	SHIPPING_POSTAL_CODE,
	SHIPPING_STATE_PROVINCE,
	SENT_TO_SPECTRUM_IND,
	SENT_TO_SPECTRUM_DATE,
	TAX_AMOUNT,
	TAX_TOTAL_AS_OF_DATE,
	COD_PRODUCT_ID,
	PROMOTION_ID,
	SHIPPING_PRODUCT_ID,
	SUBJECT_ID,
	APO_ID,
	APPOINTMENT_ID,
	ODS_CREATE_DATE,
	ODS_MODIFY_DATE,
	DELETED_IND
)
select
	SYS_GUID(),
	:v_sess_no, 
	rowid,
	'F', 
	'ODI-15066: The column SUBJECT_ID cannot be null.',
	sysdate,
	'(1386001)ODS_Project.LOAD_SAS_CUSTOMER_ORDER_STG_INT',
	'SUBJECT_ID',
	'NN',	
	CUSTOMER_ORDER_ID,
	ADDRESSES_SAME,
	AUDIT_CREATE_DATE,
	AUDIT_CREATED_BY,
	AUDIT_MODIFIED_BY,
	AUDIT_MODIFY_DATE,
	COD_LIST_AMOUNT,
	COD_TAX_RATE,
	COD_TAX,
	COD_TAX_DATE,
	CURRENCY_CODE,
	CURRENT_STATUS_CODE,
	ORDER_DATE,
	LIFETOUCH_USER_PROFILE_ID,
	ORDER_NUMBER,
	PROOF_DEPOSIT_APPLIED,
	PROOF_DEPOSIT_TOTAL,
	SHIPPING_DISCOUNT,
	SHIPPING_LIST_AMOUNT,
	SHIPPING_TAX_RATE,
	SHIPPING_TAX,
	SHIPPING_TAX_DATE,
	SHIPPING_CITY,
	SHIPPING_COUNTRY,
	SHIPPING_FIRSTNAME,
	SHIPPING_LASTNAME,
	SHIPPING_LINE1,
	SHIPPING_LINE2,
	SHIPPING_PHONE_NUMBER,
	SHIPPING_POSTAL_CODE,
	SHIPPING_STATE_PROVINCE,
	SENT_TO_SPECTRUM_IND,
	SENT_TO_SPECTRUM_DATE,
	TAX_AMOUNT,
	TAX_TOTAL_AS_OF_DATE,
	COD_PRODUCT_ID,
	PROMOTION_ID,
	SHIPPING_PRODUCT_ID,
	SUBJECT_ID,
	APO_ID,
	APPOINTMENT_ID,
	ODS_CREATE_DATE,
	ODS_MODIFY_DATE,
	DELETED_IND
from	RAX_APP_USER.I$_SAS_CUST_ORDER_STG1386001
where	SUBJECT_ID is null



&


/*-----------------------------------------------*/
/* TASK No. 34 */
/* create index on error table */

 
/* FLOW CONTROL CREATE INDEX ON THE E$TABLE */
-- create index 	RAX_APP_USER.E$_SAS_CUST_ORDER_STG1386001
-- on	RAX_APP_USER.E$_SAS_CUST_ORDER_STG1386001 (ODI_ROW_ID)

BEGIN
  EXECUTE IMMEDIATE 'create index RAX_APP_USER.E$_SAS_CUST_ORDER_STG1386001
on   RAX_APP_USER.E$_SAS_CUST_ORDER_STG1386001 (ODI_ROW_ID)';
EXCEPTION
  WHEN OTHERS THEN
   -- Handle the case where the identifier is too long (ORA-00972)
   IF SQLCODE = -972 or  SQLCODE = -1408 or SQLCODE = -955  THEN
     DBMS_OUTPUT.PUT_LINE('Identifier is too long. Skipping creation of index.');
   ELSE
     RAISE;
   END IF;
END;

&


/*-----------------------------------------------*/
/* TASK No. 35 */
/* delete errors from controlled table */

delete from	RAX_APP_USER.I$_SAS_CUST_ORDER_STG1386001  T
where	exists 	(
		select	1
		from	RAX_APP_USER.E$_SAS_CUST_ORDER_STG1386001 E
		where ODI_SESS_NO = :v_sess_no
		and T.rowid = E.ODI_ROW_ID
		)


&


/*-----------------------------------------------*/
/* TASK No. 36 */
/* insert check sum into check table */

insert into RAX_APP_USER.SNP_CHECK_TAB
(
	SCHEMA_NAME,
	RESOURCE_NAME,
	FULL_RES_NAME,
	ERR_TYPE,
	ERR_MESS,
	CHECK_DATE,
	ORIGIN,
	CONS_NAME,
	CONS_TYPE,
	ERR_COUNT
)
select	
	'ODS_STAGE',
	'SAS_CUST_ORDER_STG',
	'ODS_STAGE.SAS_CUSTOMER_ORDER_STG1386001',
	E.ODI_ERR_TYPE,
	E.ODI_ERR_MESS,
	E.ODI_CHECK_DATE,
	E.ODI_ORIGIN,
	E.ODI_CONS_NAME,
	E.ODI_CONS_TYPE,
	count(1) 
from	RAX_APP_USER.E$_SAS_CUST_ORDER_STG1386001 E
where	E.ODI_ERR_TYPE	= 'F'
and	E.ODI_ORIGIN 	= '(1386001)ODS_Project.LOAD_SAS_CUSTOMER_ORDER_STG_INT'
group by	E.ODI_ERR_TYPE,
	E.ODI_ERR_MESS,
	E.ODI_CHECK_DATE,
	E.ODI_ORIGIN,
	E.ODI_CONS_NAME,
	E.ODI_CONS_TYPE


&


/*-----------------------------------------------*/
/* TASK No. 37 */
/* Merge Rows */

merge into	ODS_STAGE.SAS_CUSTOMER_ORDER_STG T
using	RAX_APP_USER.I$_SAS_CUST_ORDER_STG1386001 S
on	(
		T.CUSTOMER_ORDER_ID=S.CUSTOMER_ORDER_ID
	)
when matched
then update set
	T.ADDRESSES_SAME	= S.ADDRESSES_SAME,
	T.AUDIT_CREATE_DATE	= S.AUDIT_CREATE_DATE,
	T.AUDIT_CREATED_BY	= S.AUDIT_CREATED_BY,
	T.AUDIT_MODIFIED_BY	= S.AUDIT_MODIFIED_BY,
	T.AUDIT_MODIFY_DATE	= S.AUDIT_MODIFY_DATE,
	T.COD_LIST_AMOUNT	= S.COD_LIST_AMOUNT,
	T.COD_TAX_RATE	= S.COD_TAX_RATE,
	T.COD_TAX	= S.COD_TAX,
	T.COD_TAX_DATE	= S.COD_TAX_DATE,
	T.CURRENCY_CODE	= S.CURRENCY_CODE,
	T.CURRENT_STATUS_CODE	= S.CURRENT_STATUS_CODE,
	T.ORDER_DATE	= S.ORDER_DATE,
	T.LIFETOUCH_USER_PROFILE_ID	= S.LIFETOUCH_USER_PROFILE_ID,
	T.ORDER_NUMBER	= S.ORDER_NUMBER,
	T.PROOF_DEPOSIT_APPLIED	= S.PROOF_DEPOSIT_APPLIED,
	T.PROOF_DEPOSIT_TOTAL	= S.PROOF_DEPOSIT_TOTAL,
	T.SHIPPING_DISCOUNT	= S.SHIPPING_DISCOUNT,
	T.SHIPPING_LIST_AMOUNT	= S.SHIPPING_LIST_AMOUNT,
	T.SHIPPING_TAX_RATE	= S.SHIPPING_TAX_RATE,
	T.SHIPPING_TAX	= S.SHIPPING_TAX,
	T.SHIPPING_TAX_DATE	= S.SHIPPING_TAX_DATE,
	T.SHIPPING_CITY	= S.SHIPPING_CITY,
	T.SHIPPING_COUNTRY	= S.SHIPPING_COUNTRY,
	T.SHIPPING_FIRSTNAME	= S.SHIPPING_FIRSTNAME,
	T.SHIPPING_LASTNAME	= S.SHIPPING_LASTNAME,
	T.SHIPPING_LINE1	= S.SHIPPING_LINE1,
	T.SHIPPING_LINE2	= S.SHIPPING_LINE2,
	T.SHIPPING_PHONE_NUMBER	= S.SHIPPING_PHONE_NUMBER,
	T.SHIPPING_POSTAL_CODE	= S.SHIPPING_POSTAL_CODE,
	T.SHIPPING_STATE_PROVINCE	= S.SHIPPING_STATE_PROVINCE,
	T.SENT_TO_SPECTRUM_IND	= S.SENT_TO_SPECTRUM_IND,
	T.SENT_TO_SPECTRUM_DATE	= S.SENT_TO_SPECTRUM_DATE,
	T.TAX_AMOUNT	= S.TAX_AMOUNT,
	T.TAX_TOTAL_AS_OF_DATE	= S.TAX_TOTAL_AS_OF_DATE,
	T.COD_PRODUCT_ID	= S.COD_PRODUCT_ID,
	T.PROMOTION_ID	= S.PROMOTION_ID,
	T.SHIPPING_PRODUCT_ID	= S.SHIPPING_PRODUCT_ID,
	T.SUBJECT_ID	= S.SUBJECT_ID,
	T.APO_ID	= S.APO_ID,
	T.APPOINTMENT_ID	= S.APPOINTMENT_ID,
	T.DELETED_IND	= S.DELETED_IND
	,                                         T.ODS_MODIFY_DATE	= sysdate
when not matched
then insert
	(
	T.CUSTOMER_ORDER_ID,
	T.ADDRESSES_SAME,
	T.AUDIT_CREATE_DATE,
	T.AUDIT_CREATED_BY,
	T.AUDIT_MODIFIED_BY,
	T.AUDIT_MODIFY_DATE,
	T.COD_LIST_AMOUNT,
	T.COD_TAX_RATE,
	T.COD_TAX,
	T.COD_TAX_DATE,
	T.CURRENCY_CODE,
	T.CURRENT_STATUS_CODE,
	T.ORDER_DATE,
	T.LIFETOUCH_USER_PROFILE_ID,
	T.ORDER_NUMBER,
	T.PROOF_DEPOSIT_APPLIED,
	T.PROOF_DEPOSIT_TOTAL,
	T.SHIPPING_DISCOUNT,
	T.SHIPPING_LIST_AMOUNT,
	T.SHIPPING_TAX_RATE,
	T.SHIPPING_TAX,
	T.SHIPPING_TAX_DATE,
	T.SHIPPING_CITY,
	T.SHIPPING_COUNTRY,
	T.SHIPPING_FIRSTNAME,
	T.SHIPPING_LASTNAME,
	T.SHIPPING_LINE1,
	T.SHIPPING_LINE2,
	T.SHIPPING_PHONE_NUMBER,
	T.SHIPPING_POSTAL_CODE,
	T.SHIPPING_STATE_PROVINCE,
	T.SENT_TO_SPECTRUM_IND,
	T.SENT_TO_SPECTRUM_DATE,
	T.TAX_AMOUNT,
	T.TAX_TOTAL_AS_OF_DATE,
	T.COD_PRODUCT_ID,
	T.PROMOTION_ID,
	T.SHIPPING_PRODUCT_ID,
	T.SUBJECT_ID,
	T.APO_ID,
	T.APPOINTMENT_ID,
	T.DELETED_IND
	,                                          T.ODS_CREATE_DATE,
	T.ODS_MODIFY_DATE
	)
values
	(
	S.CUSTOMER_ORDER_ID,
	S.ADDRESSES_SAME,
	S.AUDIT_CREATE_DATE,
	S.AUDIT_CREATED_BY,
	S.AUDIT_MODIFIED_BY,
	S.AUDIT_MODIFY_DATE,
	S.COD_LIST_AMOUNT,
	S.COD_TAX_RATE,
	S.COD_TAX,
	S.COD_TAX_DATE,
	S.CURRENCY_CODE,
	S.CURRENT_STATUS_CODE,
	S.ORDER_DATE,
	S.LIFETOUCH_USER_PROFILE_ID,
	S.ORDER_NUMBER,
	S.PROOF_DEPOSIT_APPLIED,
	S.PROOF_DEPOSIT_TOTAL,
	S.SHIPPING_DISCOUNT,
	S.SHIPPING_LIST_AMOUNT,
	S.SHIPPING_TAX_RATE,
	S.SHIPPING_TAX,
	S.SHIPPING_TAX_DATE,
	S.SHIPPING_CITY,
	S.SHIPPING_COUNTRY,
	S.SHIPPING_FIRSTNAME,
	S.SHIPPING_LASTNAME,
	S.SHIPPING_LINE1,
	S.SHIPPING_LINE2,
	S.SHIPPING_PHONE_NUMBER,
	S.SHIPPING_POSTAL_CODE,
	S.SHIPPING_STATE_PROVINCE,
	S.SENT_TO_SPECTRUM_IND,
	S.SENT_TO_SPECTRUM_DATE,
	S.TAX_AMOUNT,
	S.TAX_TOTAL_AS_OF_DATE,
	S.COD_PRODUCT_ID,
	S.PROMOTION_ID,
	S.SHIPPING_PRODUCT_ID,
	S.SUBJECT_ID,
	S.APO_ID,
	S.APPOINTMENT_ID,
	S.DELETED_IND
	,                                          sysdate,
	sysdate
	)

&


/*-----------------------------------------------*/
/* TASK No. 38 */
/* Commit transaction */

/*commit*/


/*-----------------------------------------------*/
/* TASK No. 39 */
/* Drop flow table */

-- drop table RAX_APP_USER.I$_SAS_CUST_ORDER_STG1386001

BEGIN
  EXECUTE IMMEDIATE 'drop table RAX_APP_USER.I$_SAS_CUST_ORDER_STG1386001';
EXCEPTION
  WHEN OTHERS THEN
   IF SQLCODE != -942 THEN
     RAISE;
   END IF;
END;


&


/*-----------------------------------------------*/
/* TASK No. 1000008 */
/* Drop work table */

-- drop table RAX_APP_USER.C$_0SAS_CUST_ORDER_STG purge

BEGIN
  EXECUTE IMMEDIATE 'drop table RAX_APP_USER.C$_0SAS_CUST_ORDER_STG purge';
EXCEPTION
  WHEN OTHERS THEN
   IF SQLCODE != -942 THEN
     RAISE;
   END IF;
END;


&


/*-----------------------------------------------*/
/* TASK No. 40 */
/* MERGE INTO ODS_STAGE.SAS_CUSTOMER_ORDER_XR */

-- SAS_CUSTOMER_ORDER_XR
MERGE INTO ODS_STAGE.SAS_CUSTOMER_ORDER_XR d
USING (
select * from
    (  Select
        XR.CUSTOMER_ORDER_OID as CUSTOMER_ORDER_OID,
        STG.CUSTOMER_ORDER_ID as SK_CUSTOMER_ORDER_ID,
        STG.APPOINTMENT_ID as SK_APPOINTMENT_ID,
        STG.SUBJECT_ID as SK_SUBJECT_ID,
        sysdate as ODS_CREATE_DATE,
        sysdate as ODS_MODIFY_DATE
    -- select *
    FROM 
        ODS_STAGE.SAS_CUSTOMER_ORDER_STG stg
        ,ODS_STAGE.SAS_CUSTOMER_ORDER_XR xr
    WHERE (1=1)
        and stg.ODS_MODIFY_DATE >= TO_DATE(SUBSTR(:v_cdc_load_date, 1, 19), 'YYYY-MM-DD HH24:MI:SS')  -:v_cdc_overlap
        and STG.CUSTOMER_ORDER_ID=XR.SK_CUSTOMER_ORDER_ID(+)
     ) s
where NOT EXISTS 
	( select 1 from ODS_STAGE.SAS_CUSTOMER_ORDER_XR T
	where	T.SK_CUSTOMER_ORDER_ID	= S.SK_CUSTOMER_ORDER_ID 
		 and
		((T.CUSTOMER_ORDER_OID = S.CUSTOMER_ORDER_OID) or (T.CUSTOMER_ORDER_OID IS NULL and S.CUSTOMER_ORDER_OID IS NULL)) and
		((T.SK_CUSTOMER_ORDER_ID = S.SK_CUSTOMER_ORDER_ID) or (T.SK_CUSTOMER_ORDER_ID IS NULL and S.SK_CUSTOMER_ORDER_ID IS NULL)) and
		((T.SK_APPOINTMENT_ID = S.SK_APPOINTMENT_ID) or (T.SK_APPOINTMENT_ID IS NULL and S.SK_APPOINTMENT_ID IS NULL)) and
		((T.SK_SUBJECT_ID = S.SK_SUBJECT_ID) or (T.SK_SUBJECT_ID IS NULL and S.SK_SUBJECT_ID IS NULL)) 
		        )
) s 
ON
  (s.SK_CUSTOMER_ORDER_ID=d.SK_CUSTOMER_ORDER_ID)
WHEN MATCHED
THEN
UPDATE SET
  d.CUSTOMER_ORDER_OID = s.CUSTOMER_ORDER_OID,
  d.SK_APPOINTMENT_ID = s.SK_APPOINTMENT_ID,
  d.SK_SUBJECT_ID = s.SK_SUBJECT_ID,
  d.ODS_MODIFY_DATE = s.ODS_MODIFY_DATE
WHEN NOT MATCHED
THEN
INSERT (
  CUSTOMER_ORDER_OID, SK_CUSTOMER_ORDER_ID, SK_APPOINTMENT_ID,
  SK_SUBJECT_ID, ODS_CREATE_DATE, ODS_MODIFY_DATE)
VALUES (
  ODS_STAGE.CUSTOMER_ORDER_OID_SEQ.nextval, s.SK_CUSTOMER_ORDER_ID, s.SK_APPOINTMENT_ID,
  s.SK_SUBJECT_ID, s.ODS_CREATE_DATE, s.ODS_MODIFY_DATE
  )

&


/*-----------------------------------------------*/
/* TASK No. 41 */
/* MERGE INTO ODS_OWN.SAS_CUSTOMER_ORDER */

MERGE INTO ODS_OWN.SAS_CUSTOMER_ORDER d
USING (
select * from (
      Select
        xr.CUSTOMER_ORDER_OID as CUSTOMER_ORDER_OID,
        axr.APPOINTMENT_OID as APPOINTMENT_OID,
        SUB_XR.SUBJECT_OID as SUBJECT_OID,
        u.USER_PROFILE_OID as USER_PROFILE_OID,
        stg.ADDRESSES_SAME as ADDRESSES_SAME,
        stg.AUDIT_CREATE_DATE as AUDIT_CREATE_DATE,
        stg.AUDIT_CREATED_BY as AUDIT_CREATED_BY,
        stg.AUDIT_MODIFIED_BY as AUDIT_MODIFIED_BY,
        stg.AUDIT_MODIFY_DATE as  AUDIT_MODIFY_DATE,         
        stg.COD_LIST_AMOUNT  as COD_LIST_AMOUNT,          
        stg.COD_TAX_RATE as COD_TAX_RATE       ,      
        stg.COD_TAX  ,                  
        stg.COD_TAX_DATE               ,
        stg.CURRENCY_CODE             , 
        stg.CURRENT_STATUS_CODE  ,     
        stg.ORDER_DATE                       ,
        stg.ORDER_NUMBER               ,
        stg.PROOF_DEPOSIT_APPLIED,      
        stg.PROOF_DEPOSIT_TOTAL    ,    
        stg.SHIPPING_DISCOUNT          ,
        stg.SHIPPING_LIST_AMOUNT     ,  
        stg.SHIPPING_TAX_RATE          ,
        stg.SHIPPING_TAX               ,
        stg.SHIPPING_TAX_DATE      ,    
        stg.SHIPPING_CITY              ,
        stg.SHIPPING_COUNTRY       ,   
        stg.SHIPPING_FIRSTNAME     ,    
        stg.SHIPPING_LASTNAME        ,  
        stg.SHIPPING_LINE1             ,
        stg.SHIPPING_LINE2             ,
        stg.SHIPPING_PHONE_NUMBER      ,
        stg.SHIPPING_POSTAL_CODE,       
        stg.SHIPPING_STATE_PROVINCE    ,
        stg.SENT_TO_SPECTRUM_IND       ,
        stg.SENT_TO_SPECTRUM_DATE      ,
        stg.TAX_AMOUNT                 ,
        stg.LIFETOUCH_USER_PROFILE_ID,
        stg.TAX_TOTAL_AS_OF_DATE       ,
        stg.COD_PRODUCT_ID            ,
        stg.PROMOTION_ID               ,
        stg.SHIPPING_PRODUCT_ID   ,     
        stg.APO_ID                              ,
        stg.DELETED_IND                ,
        sysdate as ODS_CREATE_DATE,
        sysdate as ODS_MODIFY_DATE,
       SS.SOURCE_SYSTEM_OID as SOURCE_SYSTEM_OID
 
    FROM 
        ODS_STAGE.SAS_CUSTOMER_ORDER_STG stg
        ,ODS_STAGE.SAS_CUSTOMER_ORDER_XR xr
        ,ODS_STAGE.SAS_APPOINTMENT_XR axr
       ,ODS_OWN.USER_PROFILE u 
        ,ODS_STAGE.SAS_SUBJECT_XR SUB_XR
       ,ODS_OWN.SOURCE_SYSTEM SS
    WHERE (1=1)
        and stg.ODS_MODIFY_DATE >= TO_DATE(SUBSTR(:v_cdc_load_date, 1, 19), 'YYYY-MM-DD HH24:MI:SS')  -:v_cdc_overlap
  and SS.SOURCE_SYSTEM_SHORT_NAME='SAS'
        and stg.CUSTOMER_ORDER_ID =xr.SK_CUSTOMER_ORDER_ID(+)
        and xr.SK_APPOINTMENT_ID=AXR.SK_APPOINTMENT_ID(+)
        and XR.SK_SUBJECT_ID=SUB_XR.SK_SUBJECT_ID(+)
        and stg.LIFETOUCH_USER_PROFILE_ID = u.LIFETOUCH_USER_PROFILE_ID(+)
   ) s
where NOT EXISTS 
	( select 1 from ODS_OWN.SAS_CUSTOMER_ORDER T
	where	T.CUSTOMER_ORDER_OID	= S.CUSTOMER_ORDER_OID 
 	and ((T.CUSTOMER_ORDER_OID = S.CUSTOMER_ORDER_OID) or (T.CUSTOMER_ORDER_OID IS NULL and S.CUSTOMER_ORDER_OID IS NULL)) and
 ((T.APPOINTMENT_OID = S.APPOINTMENT_OID) or (T.APPOINTMENT_OID IS NULL and S.APPOINTMENT_OID IS NULL)) AND
 ((T.SUBJECT_OID = S.SUBJECT_OID) or (T.SUBJECT_OID IS NULL and S.SUBJECT_OID IS NULL)) and
 ((T.AUDIT_CREATE_DATE = S.AUDIT_CREATE_DATE) or (T.AUDIT_CREATE_DATE IS NULL and S.AUDIT_CREATE_DATE IS NULL)) and
((T.AUDIT_CREATED_BY = S.AUDIT_CREATED_BY) or (T.AUDIT_CREATED_BY IS NULL and S.AUDIT_CREATED_BY IS NULL)) and
        ((T.AUDIT_MODIFY_DATE = S.AUDIT_MODIFY_DATE) or (T.AUDIT_MODIFY_DATE IS NULL and S.AUDIT_MODIFY_DATE IS NULL)) and
        ((T.AUDIT_MODIFIED_BY = S.AUDIT_MODIFIED_BY) or (T.AUDIT_MODIFIED_BY IS NULL and S.AUDIT_MODIFIED_BY IS NULL)) and
 ((T.SOURCE_SYSTEM_OID = S.SOURCE_SYSTEM_OID) or (T.SOURCE_SYSTEM_OID IS NULL and S.SOURCE_SYSTEM_OID IS NULL)) AND
((T.ADDRESSES_SAME=S.ADDRESSES_SAME)or(T.ADDRESSES_SAME IS NULL and S.ADDRESSES_SAME IS NULL)) AND
((T.COD_LIST_AMOUNT=S.COD_LIST_AMOUNT) or(T.COD_LIST_AMOUNT IS NULL and S.COD_LIST_AMOUNT IS NULL)) AND
((T.COD_TAX_RATE=S.COD_TAX_RATE ) or(T.COD_TAX_RATE  IS NULL and S.COD_TAX_RATE  IS NULL)) AND          
((T.COD_TAX=S.COD_TAX) or(T.COD_TAX  IS NULL and S.COD_TAX IS NULL)) AND               
((T.COD_TAX_DATE=S.COD_TAX_DATE ) or(T.COD_TAX_DATE  IS NULL and S.COD_TAX_DATE  IS NULL)) AND 
((T.CURRENCY_CODE=S.CURRENCY_CODE ) or(T.CURRENCY_CODE  IS NULL and S.CURRENCY_CODE  IS NULL)) AND 
((T.CURRENT_STATUS_CODE=S.CURRENT_STATUS_CODE) or(T.CURRENT_STATUS_CODE IS NULL and S.CURRENT_STATUS_CODE IS NULL)) AND  
((T.ORDER_DATE =S.ORDER_DATE) or(T.ORDER_DATE  IS NULL and S.ORDER_DATE IS NULL)) AND  
((T.LIFETOUCH_USER_PROFILE_ID  =S.LIFETOUCH_USER_PROFILE_ID  ) or(T.LIFETOUCH_USER_PROFILE_ID  IS NULL and S.  LIFETOUCH_USER_PROFILE_ID  IS NULL)) AND  
((T.ORDER_NUMBER=S.ORDER_NUMBER) or(T.ORDER_NUMBER IS NULL and S.ORDER_NUMBER  IS NULL)) AND  
((T.PROOF_DEPOSIT_APPLIED=S.PROOF_DEPOSIT_APPLIED ) or(T.PROOF_DEPOSIT_APPLIED  IS NULL and S.PROOF_DEPOSIT_APPLIED  IS NULL)) AND  
((T.PROOF_DEPOSIT_TOTAL =S.PROOF_DEPOSIT_TOTAL ) or(T.PROOF_DEPOSIT_TOTAL IS NULL and S.PROOF_DEPOSIT_TOTAL  IS NULL)) AND  
((T.SHIPPING_DISCOUNT =S.SHIPPING_DISCOUNT) or(T.SHIPPING_DISCOUNT IS NULL and S.SHIPPING_DISCOUNT  IS NULL)) AND  
((T.SHIPPING_LIST_AMOUNT =S.SHIPPING_LIST_AMOUNT) or(T.SHIPPING_LIST_AMOUNT IS NULL and S.SHIPPING_LIST_AMOUNT  IS NULL)) AND  
((T.SHIPPING_TAX_RATE =S.SHIPPING_TAX_RATE ) or(T.SHIPPING_TAX_RATE  IS NULL and S.SHIPPING_TAX_RATE   IS NULL)) AND  
((T.SHIPPING_TAX=S.SHIPPING_TAX) or(T.SHIPPING_TAX  IS NULL and S.  SHIPPING_TAX  IS NULL)) AND  
((T.SHIPPING_TAX_DATE=S.SHIPPING_TAX_DATE ) or(T.SHIPPING_TAX_DATE  IS NULL and S.SHIPPING_TAX_DATE   IS NULL)) AND  
((T.SHIPPING_CITY=S.SHIPPING_CITY ) or(T.SHIPPING_CITY  IS NULL and S.SHIPPING_CITY  IS NULL)) AND  
((T.SHIPPING_COUNTRY=S.SHIPPING_COUNTRY) or(T.SHIPPING_COUNTRY  IS NULL and S.SHIPPING_COUNTRY   IS NULL)) AND  
((T.SHIPPING_FIRSTNAME =S.SHIPPING_FIRSTNAME) or(T.SHIPPING_FIRSTNAME  IS NULL and S.SHIPPING_FIRSTNAME    IS NULL)) AND  
((T.SHIPPING_LASTNAME =S.SHIPPING_LASTNAME) or(T.SHIPPING_LASTNAME   IS NULL and S.SHIPPING_LASTNAME  IS NULL)) AND  
((T.SHIPPING_LINE1 =S.SHIPPING_LINE1) or(T.SHIPPING_LINE1             IS NULL and S.  SHIPPING_LINE1             IS NULL)) AND  
((T.SHIPPING_LINE2 =S.  SHIPPING_LINE2 ) or(T.SHIPPING_LINE2             IS NULL and S.  SHIPPING_LINE2             IS NULL)) AND  
((T.SHIPPING_PHONE_NUMBER =S.SHIPPING_PHONE_NUMBER) or(T.SHIPPING_PHONE_NUMBER  IS NULL and S.  SHIPPING_PHONE_NUMBER  IS NULL)) AND  
((T.  SHIPPING_POSTAL_CODE=S.  SHIPPING_POSTAL_CODE       ) or(T.  SHIPPING_POSTAL_CODE       IS NULL and S.  SHIPPING_POSTAL_CODE       IS NULL)) AND  
((T.  SHIPPING_STATE_PROVINCE    =S.  SHIPPING_STATE_PROVINCE  ) or(T.  SHIPPING_STATE_PROVINCE    IS NULL and S.  SHIPPING_STATE_PROVINCE    IS NULL)) AND  
((T.  SENT_TO_SPECTRUM_IND       =S.  SENT_TO_SPECTRUM_IND ) or(T.  SENT_TO_SPECTRUM_IND  IS NULL and S.  SENT_TO_SPECTRUM_IND       IS NULL)) AND  
((T.SENT_TO_SPECTRUM_DATE =S.  SENT_TO_SPECTRUM_DATE ) or(T.  SENT_TO_SPECTRUM_DATE IS NULL and S.  SENT_TO_SPECTRUM_DATE      IS NULL)) AND  
((T.TAX_AMOUNT  =S.  TAX_AMOUNT  ) or(T.  TAX_AMOUNT  IS NULL and S.  TAX_AMOUNT   IS NULL)) AND  
((T.TAX_TOTAL_AS_OF_DATE=S.  TAX_TOTAL_AS_OF_DATE) or(T.TAX_TOTAL_AS_OF_DATE IS NULL and S.  TAX_TOTAL_AS_OF_DATE       IS NULL)) AND  
((T.COD_PRODUCT_ID  =S.  COD_PRODUCT_ID ) or(T.  COD_PRODUCT_ID    IS NULL and S.  COD_PRODUCT_ID IS NULL)) AND  
((T.PROMOTION_ID    =S.  PROMOTION_ID  ) or(T.  PROMOTION_ID    IS NULL and S.  PROMOTION_ID      IS NULL)) AND  
((T.SHIPPING_PRODUCT_ID =S.SHIPPING_PRODUCT_ID ) or(T.SHIPPING_PRODUCT_ID  IS NULL and S.SHIPPING_PRODUCT_ID  IS NULL)) AND  
((T.APO_ID  =S.  APO_ID ) or(T.  APO_ID     IS NULL and S.  APO_ID  IS NULL)) AND  
((T. DELETED_IND  =S.  DELETED_IND  ) or(T.  DELETED_IND  IS NULL and S.  DELETED_IND  IS NULL))   
        ) 
) s 
ON
  (d.CUSTOMER_ORDER_OID = s.CUSTOMER_ORDER_OID)
WHEN MATCHED
THEN
UPDATE SET
  d.SUBJECT_OID = s.SUBJECT_OID,
  d.APPOINTMENT_OID= s.APPOINTMENT_OID,
d.USER_PROFILE_OID =s.USER_PROFILE_OID,
  d.AUDIT_CREATE_DATE = s.AUDIT_CREATE_DATE,
  d.AUDIT_CREATED_BY = s.AUDIT_CREATED_BY,
  d.AUDIT_MODIFY_DATE = s.AUDIT_MODIFY_DATE,
  d.AUDIT_MODIFIED_BY = s.AUDIT_MODIFIED_BY,
  d.SOURCE_SYSTEM_OID = s.SOURCE_SYSTEM_OID,
  d.ADDRESSES_SAME=s.ADDRESSES_SAME,
  d.COD_LIST_AMOUNT=s.COD_LIST_AMOUNT,
 d.LIFETOUCH_USER_PROFILE_ID=s.LIFETOUCH_USER_PROFILE_ID,
  d.COD_TAX_RATE=s.COD_TAX_RATE,
  d.COD_TAX=s.COD_TAX,
  d.COD_TAX_DATE=s.COD_TAX_DATE,
  d.CURRENCY_CODE=s.CURRENCY_CODE,
  d.CURRENT_STATUS_CODE=s.CURRENT_STATUS_CODE,
  d.ORDER_DATE=s.ORDER_DATE,
  d.ORDER_NUMBER=s.ORDER_NUMBER,
 d.PROOF_DEPOSIT_APPLIED=s.PROOF_DEPOSIT_APPLIED,
d.PROOF_DEPOSIT_TOTAL=s.PROOF_DEPOSIT_TOTAL,
d.SHIPPING_DISCOUNT=s.SHIPPING_DISCOUNT,
d.SHIPPING_LIST_AMOUNT=s.SHIPPING_LIST_AMOUNT,
d.SHIPPING_TAX_RATE=s.SHIPPING_TAX_RATE,
d.SHIPPING_TAX=s.SHIPPING_TAX,
d.SHIPPING_TAX_DATE=s.SHIPPING_TAX_DATE,
d.SHIPPING_COUNTRY=s.SHIPPING_COUNTRY,
d.SHIPPING_FIRSTNAME=s.SHIPPING_FIRSTNAME,
d.SHIPPING_LASTNAME=s.SHIPPING_LASTNAME,
d.SHIPPING_LINE1=s.SHIPPING_LINE1,
d.SHIPPING_LINE2=s.SHIPPING_LINE2,
d.SHIPPING_PHONE_NUMBER=s.SHIPPING_PHONE_NUMBER,
d.SHIPPING_POSTAL_CODE=s.SHIPPING_POSTAL_CODE,
d.SHIPPING_STATE_PROVINCE=s.SHIPPING_STATE_PROVINCE,
d.SENT_TO_SPECTRUM_IND=s.SENT_TO_SPECTRUM_IND,
d.SENT_TO_SPECTRUM_DATE=s.SENT_TO_SPECTRUM_DATE,
d.TAX_AMOUNT=s.TAX_AMOUNT,
d.TAX_TOTAL_AS_OF_DATE=s.TAX_TOTAL_AS_OF_DATE,
d.COD_PRODUCT_ID=s.COD_PRODUCT_ID,
d.PROMOTION_ID=s.PROMOTION_ID,
d.SHIPPING_PRODUCT_ID=s.SHIPPING_PRODUCT_ID,
d.APO_ID=s.APO_ID,
d.ODS_MODIFY_DATE=s.ODS_MODIFY_DATE,
d.DELETED_IND=s.DELETED_IND
WHEN NOT MATCHED
THEN
INSERT (CUSTOMER_ORDER_OID,APPOINTMENT_OID, SUBJECT_OID,USER_PROFILE_OID,
  AUDIT_CREATE_DATE,
  AUDIT_CREATED_BY, AUDIT_MODIFY_DATE, AUDIT_MODIFIED_BY,LIFETOUCH_USER_PROFILE_ID, ODS_MODIFY_DATE,ODS_CREATE_DATE,ADDRESSES_SAME,COD_LIST_AMOUNT,COD_TAX_RATE,COD_TAX,COD_TAX_DATE,CURRENCY_CODE,CURRENT_STATUS_CODE,ORDER_DATE,ORDER_NUMBER,PROOF_DEPOSIT_APPLIED,PROOF_DEPOSIT_TOTAL,SHIPPING_DISCOUNT,SHIPPING_LIST_AMOUNT,SHIPPING_TAX_RATE,SHIPPING_TAX,SHIPPING_TAX_DATE,SHIPPING_CITY,SHIPPING_COUNTRY,SHIPPING_FIRSTNAME,SHIPPING_LASTNAME,SHIPPING_LINE1,SHIPPING_LINE2,SHIPPING_PHONE_NUMBER,SHIPPING_POSTAL_CODE,SHIPPING_STATE_PROVINCE,SENT_TO_SPECTRUM_IND,SENT_TO_SPECTRUM_DATE,TAX_AMOUNT,TAX_TOTAL_AS_OF_DATE,COD_PRODUCT_ID,PROMOTION_ID,SHIPPING_PRODUCT_ID,APO_ID,DELETED_IND

)VALUES(s.CUSTOMER_ORDER_OID,s.APPOINTMENT_OID, s.SUBJECT_OID,s.USER_PROFILE_OID,
  s.AUDIT_CREATE_DATE,
  s.AUDIT_CREATED_BY, s.AUDIT_MODIFY_DATE,s.AUDIT_MODIFIED_BY,s.LIFETOUCH_USER_PROFILE_ID, s.ODS_MODIFY_DATE,s.ODS_CREATE_DATE,s.ADDRESSES_SAME,s.COD_LIST_AMOUNT,s.COD_TAX_RATE,s.COD_TAX,s.COD_TAX_DATE,s.CURRENCY_CODE,s.CURRENT_STATUS_CODE,s.ORDER_DATE,s.ORDER_NUMBER,s.PROOF_DEPOSIT_APPLIED,s.PROOF_DEPOSIT_TOTAL,s.SHIPPING_DISCOUNT,s.SHIPPING_LIST_AMOUNT,s.SHIPPING_TAX_RATE,s.SHIPPING_TAX,s.SHIPPING_TAX_DATE,s.SHIPPING_CITY,s.SHIPPING_COUNTRY,s.SHIPPING_FIRSTNAME,s.SHIPPING_LASTNAME,s.SHIPPING_LINE1,s.SHIPPING_LINE2,s.SHIPPING_PHONE_NUMBER,s.SHIPPING_POSTAL_CODE,s.SHIPPING_STATE_PROVINCE,s.SENT_TO_SPECTRUM_IND,s.SENT_TO_SPECTRUM_DATE,s.TAX_AMOUNT,s.TAX_TOTAL_AS_OF_DATE,s.COD_PRODUCT_ID,s.PROMOTION_ID,s.SHIPPING_PRODUCT_ID,s.APO_ID,s.DELETED_IND

)



&


/*-----------------------------------------------*/
/* TASK No. 42 */
/* Update CDC Load Status */

UPDATE ODS_OWN.ODS_CDC_LOAD_STATUS
SET LAST_CDC_COMPLETION_DATE=TO_DATE(
             SUBSTR(:v_sess_beg, 1, 19), 'RRRR-MM-DD HH24:MI:SS')
+ nvl((TIMEZONE_OFFSET/24), 0) 
WHERE ODS_TABLE_NAME=:v_cdc_load_table_name
AND CONTEXT_NAME = :v_env

/*
UPDATE ODS_OWN.ODS_CDC_LOAD_STATUS
SET LAST_CDC_COMPLETION_DATE=TO_DATE(
             SUBSTR(:v_sess_beg, 1, 19), 'RRRR-MM-DD HH24:MI:SS')
WHERE ODS_TABLE_NAME=:v_cdc_load_table_name
AND CONTEXT_NAME = :v_env
*/

&


/*-----------------------------------------------*/
/* TASK No. 43 */
/* Insert CDC Audit Record */

INSERT INTO RAX_APP_USER.ODS_CDC_LOAD_STATUS_AUDIT
(TABLE_NAME,
SESS_NO,                      
SESS_NAME,                    
SCEN_VERSION,                 
SESS_BEG,                     
ORIG_LAST_CDC_COMPLETION_DATE,
OVERLAP,
CREATE_DATE,
CONTEXT_NAME,
TIMEZONE_OFFSET              
)
select 
:v_cdc_load_table_name
,:v_sess_no
,'LOAD_SAS_CUSTOMER_ORDER_PKG'
,'005'
,TO_DATE(SUBSTR(:v_sess_beg, 1, 19), 'RRRR-MM-DD HH24:MI:SS')
,TO_DATE (SUBSTR(:v_cdc_load_date, 1, 19),'YYYY-MM-DD HH24:MI:SS')
,:v_cdc_overlap
,SYSDATE
,:v_env
,TIMEZONE_OFFSET
from 
ODS_OWN.ODS_CDC_LOAD_STATUS
WHERE ODS_TABLE_NAME=:v_cdc_load_table_name
AND CONTEXT_NAME = :v_env

/*
INSERT INTO RAX_APP_USER.ODS_CDC_LOAD_STATUS_AUDIT
(TABLE_NAME,
SESS_NO,                      
SESS_NAME,                    
SCEN_VERSION,                 
SESS_BEG,                     
ORIG_LAST_CDC_COMPLETION_DATE,
OVERLAP,
CREATE_DATE,
CONTEXT_NAME              
)
values (
:v_cdc_load_table_name,
:v_sess_no,
'LOAD_SAS_CUSTOMER_ORDER_PKG',
'005',
TO_DATE(
             SUBSTR(:v_sess_beg, 1, 19), 'RRRR-MM-DD HH24:MI:SS'),
TO_DATE (SUBSTR (:v_cdc_load_date, 1, 19),
                           'YYYY-MM-DD HH24:MI:SS'
                          )
,:v_cdc_overlap,
SYSDATE,
 :v_env)
*/


&


/*-----------------------------------------------*/
