/* TASK No. 1 */

/* NONE or SET VARIABLE STATEMENT FOUND, CHECK ODI TASK NO. 1 */




/*-----------------------------------------------*/
/* TASK No. 2 */

/* SELECT STATEMENT FOUND, CHECK ODI TASK NO. 2 */




/*-----------------------------------------------*/
/* TASK No. 3 */

/* SELECT STATEMENT FOUND, CHECK ODI TASK NO. 3 */




/*-----------------------------------------------*/
/* TASK No. 4 */
/* Drop work table */

-- drop table RAX_APP_USER.C$_0SAS_CU_OL_DTL_STG purge

-- &


/*-----------------------------------------------*/
/* TASK No. 5 */
/* Create work table */

-- create table RAX_APP_USER.C$_0SAS_CU_OL_DTL_STG
-- (
-- 	C1_TYPE	VARCHAR2(1) NULL,
-- 	C2_CUSTOMER_ORDER_LINE_DETAIL_	NUMBER(10) NULL,
-- 	C3_AUDIT_CREATE_DATE	TIMESTAMP(6) NULL,
-- 	C4_AUDIT_CREATED_BY	VARCHAR2(255) NULL,
-- 	C5_AUDIT_MODIFIED_BY	VARCHAR2(255) NULL,
-- 	C6_AUDIT_MODIFY_DATE	TIMESTAMP(6) NULL,
-- 	C7_QUANTITY	NUMBER(10) NULL,
-- 	C8_CUSTOMER_ORDER_LINE_ID	NUMBER(10) NULL,
-- 	C9_ITEM_NUMBER	VARCHAR2(16) NULL,
-- 	C10_DELETED_IND	VARCHAR2(1) NULL
-- )
-- NOLOGGING

-- &


/*-----------------------------------------------*/
/* TASK No. 6 */
/* Load data */

/* SOURCE CODE */


-- select	
-- 	CUSTOMER_ORDER_LINE_DETAIL.TYPE	   C1_TYPE,
-- 	CUSTOMER_ORDER_LINE_DETAIL.CUSTOMER_ORDER_LINE_DETAIL_ID	   C2_CUSTOMER_ORDER_LINE_DETAIL_,
-- 	CUSTOMER_ORDER_LINE_DETAIL.AUDIT_CREATE_DATE	   C3_AUDIT_CREATE_DATE,
-- 	CUSTOMER_ORDER_LINE_DETAIL.AUDIT_CREATED_BY	   C4_AUDIT_CREATED_BY,
-- 	CUSTOMER_ORDER_LINE_DETAIL.AUDIT_MODIFIED_BY	   C5_AUDIT_MODIFIED_BY,
-- 	CUSTOMER_ORDER_LINE_DETAIL.AUDIT_MODIFY_DATE	   C6_AUDIT_MODIFY_DATE,
-- 	CUSTOMER_ORDER_LINE_DETAIL.QUANTITY	   C7_QUANTITY,
-- 	CUSTOMER_ORDER_LINE_DETAIL.CUSTOMER_ORDER_LINE_ID	   C8_CUSTOMER_ORDER_LINE_ID,
-- 	CUSTOMER_ORDER_LINE_DETAIL.ITEM_NUMBER	   C9_ITEM_NUMBER,
-- 	CUSTOMER_ORDER_LINE_DETAIL.DELETED_IND	   C10_DELETED_IND
-- from	SAS_SIT_OWN.CUSTOMER_ORDER_LINE_DETAIL   CUSTOMER_ORDER_LINE_DETAIL
-- where	(1=1)
-- And (CUSTOMER_ORDER_LINE_DETAIL.AUDIT_MODIFY_DATE >= TO_DATE(SUBSTR(:v_cdc_load_date, 1, 19), 'YYYY-MM-DD HH24:MI:SS')  -:v_cdc_overlap)







-- &

/* TARGET CODE */
-- insert /*+ append */ into RAX_APP_USER.C$_0SAS_CU_OL_DTL_STG
-- (
-- 	C1_TYPE,
-- 	C2_CUSTOMER_ORDER_LINE_DETAIL_,
-- 	C3_AUDIT_CREATE_DATE,
-- 	C4_AUDIT_CREATED_BY,
-- 	C5_AUDIT_MODIFIED_BY,
-- 	C6_AUDIT_MODIFY_DATE,
-- 	C7_QUANTITY,
-- 	C8_CUSTOMER_ORDER_LINE_ID,
-- 	C9_ITEM_NUMBER,
-- 	C10_DELETED_IND
-- )
-- values
-- (
-- 	:C1_TYPE,
-- 	:C2_CUSTOMER_ORDER_LINE_DETAIL_,
-- 	:C3_AUDIT_CREATE_DATE,
-- 	:C4_AUDIT_CREATED_BY,
-- 	:C5_AUDIT_MODIFIED_BY,
-- 	:C6_AUDIT_MODIFY_DATE,
-- 	:C7_QUANTITY,
-- 	:C8_CUSTOMER_ORDER_LINE_ID,
-- 	:C9_ITEM_NUMBER,
-- 	:C10_DELETED_IND
-- )

-- &


/*-----------------------------------------------*/
/* TASK No. 7 */
/* Analyze work table */



BEGIN
DBMS_STATS.GATHER_TABLE_STATS (
    ownname =>	'RAX_APP_USER',
    tabname =>	'C$_0SAS_CU_OL_DTL_STG',
    estimate_percent =>	DBMS_STATS.AUTO_SAMPLE_SIZE
);
END;




&


/*-----------------------------------------------*/
/* TASK No. 9 */
/* Set vID */

/* NONE or SET VARIABLE STATEMENT FOUND, CHECK ODI TASK NO. 9 */




/*-----------------------------------------------*/
/* TASK No. 10 */
/* Drop flow table */

-- drop table RAX_APP_USER.I$_SAS_CU_OL_DTL_STG1387001

BEGIN
  EXECUTE IMMEDIATE 'drop table RAX_APP_USER.I$_SAS_CU_OL_DTL_STG1387001';
EXCEPTION
  WHEN OTHERS THEN
   IF SQLCODE != -942 THEN
     RAISE;
   END IF;
END;


&


/*-----------------------------------------------*/
/* TASK No. 11 */
/* Create flow table I$ */

create table RAX_APP_USER.I$_SAS_CU_OL_DTL_STG1387001
(
	TYPE	VARCHAR2(1) NULL,
	CUSTOMER_ORDER_LINE_DETAIL_ID	NUMBER(10) NULL,
	AUDIT_CREATE_DATE	TIMESTAMP(6) NULL,
	AUDIT_CREATED_BY	VARCHAR2(255) NULL,
	AUDIT_MODIFIED_BY	VARCHAR2(255) NULL,
	AUDIT_MODIFY_DATE	TIMESTAMP(6) NULL,
	QUANTITY	NUMBER(10) NULL,
	CUSTOMER_ORDER_LINE_ID	NUMBER(10) NULL,
	ITEM_NUMBER	VARCHAR2(16) NULL,
	ODS_CREATE_DATE	DATE NULL,
	ODS_MODIFY_DATE	DATE NULL,
	DELETED_IND	VARCHAR2(1) NULL
	,IND_UPDATE		char(1)
)
NOLOGGING

&


/*-----------------------------------------------*/
/* TASK No. 12 */
/* Insert flow into I$ table */

/* DETECTION_STRATEGY = NOT_EXISTS */
 


  


insert into	RAX_APP_USER.I$_SAS_CU_OL_DTL_STG1387001
(
	TYPE,
	CUSTOMER_ORDER_LINE_DETAIL_ID,
	AUDIT_CREATE_DATE,
	AUDIT_CREATED_BY,
	AUDIT_MODIFIED_BY,
	AUDIT_MODIFY_DATE,
	QUANTITY,
	CUSTOMER_ORDER_LINE_ID,
	ITEM_NUMBER,
	DELETED_IND,
	IND_UPDATE
)
select 
TYPE,
	CUSTOMER_ORDER_LINE_DETAIL_ID,
	AUDIT_CREATE_DATE,
	AUDIT_CREATED_BY,
	AUDIT_MODIFIED_BY,
	AUDIT_MODIFY_DATE,
	QUANTITY,
	CUSTOMER_ORDER_LINE_ID,
	ITEM_NUMBER,
	DELETED_IND,
	IND_UPDATE
 from (


select 	 
	
	C1_TYPE TYPE,
	C2_CUSTOMER_ORDER_LINE_DETAIL_ CUSTOMER_ORDER_LINE_DETAIL_ID,
	C3_AUDIT_CREATE_DATE AUDIT_CREATE_DATE,
	C4_AUDIT_CREATED_BY AUDIT_CREATED_BY,
	C5_AUDIT_MODIFIED_BY AUDIT_MODIFIED_BY,
	C6_AUDIT_MODIFY_DATE AUDIT_MODIFY_DATE,
	C7_QUANTITY QUANTITY,
	C8_CUSTOMER_ORDER_LINE_ID CUSTOMER_ORDER_LINE_ID,
	C9_ITEM_NUMBER ITEM_NUMBER,
	C10_DELETED_IND DELETED_IND,

	'I' IND_UPDATE

from	RAX_APP_USER.C$_0SAS_CU_OL_DTL_STG
where	(1=1)






) S
where NOT EXISTS 
	( select 1 from ODS_STAGE.SAS_CUST_ORD_LINE_DTL_STG T
	where	T.CUSTOMER_ORDER_LINE_DETAIL_ID	= S.CUSTOMER_ORDER_LINE_DETAIL_ID 
		 and ((T.TYPE = S.TYPE) or (T.TYPE IS NULL and S.TYPE IS NULL)) and
		((T.AUDIT_CREATE_DATE = S.AUDIT_CREATE_DATE) or (T.AUDIT_CREATE_DATE IS NULL and S.AUDIT_CREATE_DATE IS NULL)) and
		((T.AUDIT_CREATED_BY = S.AUDIT_CREATED_BY) or (T.AUDIT_CREATED_BY IS NULL and S.AUDIT_CREATED_BY IS NULL)) and
		((T.AUDIT_MODIFIED_BY = S.AUDIT_MODIFIED_BY) or (T.AUDIT_MODIFIED_BY IS NULL and S.AUDIT_MODIFIED_BY IS NULL)) and
		((T.AUDIT_MODIFY_DATE = S.AUDIT_MODIFY_DATE) or (T.AUDIT_MODIFY_DATE IS NULL and S.AUDIT_MODIFY_DATE IS NULL)) and
		((T.QUANTITY = S.QUANTITY) or (T.QUANTITY IS NULL and S.QUANTITY IS NULL)) and
		((T.CUSTOMER_ORDER_LINE_ID = S.CUSTOMER_ORDER_LINE_ID) or (T.CUSTOMER_ORDER_LINE_ID IS NULL and S.CUSTOMER_ORDER_LINE_ID IS NULL)) and
		((T.ITEM_NUMBER = S.ITEM_NUMBER) or (T.ITEM_NUMBER IS NULL and S.ITEM_NUMBER IS NULL)) and
		((T.DELETED_IND = S.DELETED_IND) or (T.DELETED_IND IS NULL and S.DELETED_IND IS NULL))
        )

  
  

  



&


/*-----------------------------------------------*/
/* TASK No. 13 */
/* Analyze integration table */



begin
    dbms_stats.gather_table_stats(
	ownname => 'RAX_APP_USER',
	tabname => 'I$_SAS_CU_OL_DTL_STG1387001',
	estimate_percent => dbms_stats.auto_sample_size
    );
end;



&


/*-----------------------------------------------*/
/* TASK No. 14 */
/* Create Index on flow table */

-- create index	RAX_APP_USER.I$_SAS_CU_OL_DTL_STG_IDX1387001
-- on		RAX_APP_USER.I$_SAS_CU_OL_DTL_STG1387001 (CUSTOMER_ORDER_LINE_DETAIL_ID)
-- NOLOGGING

BEGIN
  EXECUTE IMMEDIATE 'create index RAX_APP_USER.I$_SAS_CU_OL_DTL_STG_IDX1387001
on   RAX_APP_USER.I$_SAS_CU_OL_DTL_STG1387001 (CUSTOMER_ORDER_LINE_DETAIL_ID)';
EXCEPTION
  WHEN OTHERS THEN
   -- Handle the case where the identifier is too long (ORA-00972)
   IF SQLCODE = -972 or  SQLCODE = -1408 or SQLCODE = -955  THEN
     DBMS_OUTPUT.PUT_LINE('Identifier is too long. Skipping creation of index.');
   ELSE
     RAISE;
   END IF;
END;

&


/*-----------------------------------------------*/
/* TASK No. 15 */
/* create check table */

BEGIN
  EXECUTE IMMEDIATE 'drop table RAX_APP_USER.SNP_CHECK_TAB';
EXCEPTION
  WHEN OTHERS THEN
   IF SQLCODE != -942 THEN
     RAISE;
   END IF;
END;

&

-- create table RAX_APP_USER.SNP_CHECK_TAB
-- (
-- 	CATALOG_NAME	VARCHAR2(100 CHAR) NULL ,
-- 	SCHEMA_NAME	VARCHAR2(100 CHAR) NULL ,
-- 	RESOURCE_NAME	VARCHAR2(100 CHAR) NULL,
-- 	FULL_RES_NAME	VARCHAR2(100 CHAR) NULL,
-- 	ERR_TYPE		VARCHAR2(1 CHAR) NULL,
-- 	ERR_MESS		VARCHAR2(250 CHAR) NULL ,
-- 	CHECK_DATE	DATE NULL,
-- 	ORIGIN		VARCHAR2(100 CHAR) NULL,
-- 	CONS_NAME	VARCHAR2(35 CHAR) NULL,
-- 	CONS_TYPE		VARCHAR2(2 CHAR) NULL,
-- 	ERR_COUNT		NUMBER(10) NULL
-- )

BEGIN
   EXECUTE IMMEDIATE '
      create table RAX_APP_USER.SNP_CHECK_TAB
		(
			CATALOG_NAME	VARCHAR2(100 CHAR) NULL ,
			SCHEMA_NAME	VARCHAR2(100 CHAR) NULL ,
			RESOURCE_NAME	VARCHAR2(100 CHAR) NULL,
			FULL_RES_NAME	VARCHAR2(100 CHAR) NULL,
			ERR_TYPE		VARCHAR2(1 CHAR) NULL,
			ERR_MESS		VARCHAR2(250 CHAR) NULL ,
			CHECK_DATE	DATE NULL,
			ORIGIN		VARCHAR2(100 CHAR) NULL,
			CONS_NAME	VARCHAR2(35 CHAR) NULL,
			CONS_TYPE		VARCHAR2(2 CHAR) NULL,
			ERR_COUNT		NUMBER(10) NULL
		)
   ';
END;


&


/*-----------------------------------------------*/
/* TASK No. 16 */
/* delete previous check sum */

delete from	RAX_APP_USER.SNP_CHECK_TAB
where	SCHEMA_NAME	= 'ODS_STAGE'
and	ORIGIN 		= '(1387001)ODS_Project.LOAD_SAS_CUST_ORD_LINE_DTL_STG_INT'
and	ERR_TYPE 		= 'F'


&


/*-----------------------------------------------*/
/* TASK No. 17 */
/* create error table */

BEGIN
  EXECUTE IMMEDIATE 'drop table RAX_APP_USER.E$_SAS_CU_OL_DTL_STG1387001';
EXCEPTION
  WHEN OTHERS THEN
   IF SQLCODE != -942 THEN
     RAISE;
   END IF;
END;

&

create table RAX_APP_USER.E$_SAS_CU_OL_DTL_STG1387001
(
	ODI_ROW_ID 		UROWID,
	ODI_ERR_TYPE		VARCHAR2(1 CHAR) NULL, 
	ODI_ERR_MESS		VARCHAR2(250 CHAR) NULL,
	ODI_CHECK_DATE	DATE NULL, 
	TYPE	VARCHAR2(1) NULL,
	CUSTOMER_ORDER_LINE_DETAIL_ID	NUMBER(10) NULL,
	AUDIT_CREATE_DATE	TIMESTAMP(6) NULL,
	AUDIT_CREATED_BY	VARCHAR2(255) NULL,
	AUDIT_MODIFIED_BY	VARCHAR2(255) NULL,
	AUDIT_MODIFY_DATE	TIMESTAMP(6) NULL,
	QUANTITY	NUMBER(10) NULL,
	CUSTOMER_ORDER_LINE_ID	NUMBER(10) NULL,
	ITEM_NUMBER	VARCHAR2(16) NULL,
	ODS_CREATE_DATE	DATE NULL,
	ODS_MODIFY_DATE	DATE NULL,
	DELETED_IND	VARCHAR2(1) NULL,
	ODI_ORIGIN		VARCHAR2(100 CHAR) NULL,
	ODI_CONS_NAME	VARCHAR2(35 CHAR) NULL,
	ODI_CONS_TYPE		VARCHAR2(2 CHAR) NULL,
	ODI_PK			VARCHAR2(32 CHAR) PRIMARY KEY,
	ODI_SESS_NO		VARCHAR2(19 CHAR)
)



&


/*-----------------------------------------------*/
/* TASK No. 18 */
/* delete previous errors */

delete from 	RAX_APP_USER.E$_SAS_CU_OL_DTL_STG1387001
where	(ODI_ERR_TYPE = 'S'	and 'F' = 'S')
or	(ODI_ERR_TYPE = 'F'	and ODI_ORIGIN = '(1387001)ODS_Project.LOAD_SAS_CUST_ORD_LINE_DTL_STG_INT')


&


/*-----------------------------------------------*/
/* TASK No. 19 */
/* Create index on PK */

 
/* FLOW CONTROL CREATE THE iNDEX ON THE I$TABLE */
-- create index 	RAX_APP_USER.I$_SAS_CU_OL_DTL_STG1387001
-- on	RAX_APP_USER.I$_SAS_CU_OL_DTL_STG1387001 (CUSTOMER_ORDER_LINE_DETAIL_ID)

BEGIN
  EXECUTE IMMEDIATE 'create index RAX_APP_USER.I$_SAS_CU_OL_DTL_STG1387001
on   RAX_APP_USER.I$_SAS_CU_OL_DTL_STG1387001 (CUSTOMER_ORDER_LINE_DETAIL_ID)';
EXCEPTION
  WHEN OTHERS THEN
   -- Handle the case where the identifier is too long (ORA-00972)
   IF SQLCODE = -972 or  SQLCODE = -1408 or SQLCODE = -955  THEN
     DBMS_OUTPUT.PUT_LINE('Identifier is too long. Skipping creation of index.');
   ELSE
     RAISE;
   END IF;
END;

&


/*-----------------------------------------------*/
/* TASK No. 20 */
/* insert PK errors */

DECLARE
               CheckTable                             VarChar2(60);
               TargetTable                            VarChar2(60);
               VariableCheckTable                     VarChar2(60);

BEGIN
               SELECT 'RAX_APP_USER.I$_SAS_CU_OL_DTL_STG' INTO CheckTable FROM DUAL;
               SELECT 'ODS_STAGE.SAS_CUST_ORD_LINE_DTL_STG' INTO TargetTable FROM DUAL;

IF CheckTable = TargetTable THEN
   VariableCheckTable := CheckTable; 
ELSE
   VariableCheckTable := CheckTable || '1387001';
END IF;

execute immediate '
insert into RAX_APP_USER.E$_SAS_CU_OL_DTL_STG1387001
(
	ODI_PK,
	ODI_SESS_NO,
	ODI_ROW_ID,
	ODI_ERR_TYPE,
	ODI_ERR_MESS,
	ODI_ORIGIN,
	ODI_CHECK_DATE,
	ODI_CONS_NAME,
	ODI_CONS_TYPE,
	TYPE,
	CUSTOMER_ORDER_LINE_DETAIL_ID,
	AUDIT_CREATE_DATE,
	AUDIT_CREATED_BY,
	AUDIT_MODIFIED_BY,
	AUDIT_MODIFY_DATE,
	QUANTITY,
	CUSTOMER_ORDER_LINE_ID,
	ITEM_NUMBER,
	ODS_CREATE_DATE,
	ODS_MODIFY_DATE,
	DELETED_IND
)
select	SYS_GUID(),
	:v_sess_no, 
	rowid,
	''F'', 
	''ODI-15064: The primary key CUST_ORD_LINE_DETAIL_PK is not unique.'',
	''(1387001)ODS_Project.LOAD_SAS_CUST_ORD_LINE_DTL_STG_INT'',
	sysdate,
	''CUST_ORD_LINE_DETAIL_PK'',
	''PK'',	
	SAS_CU_OL_DTL_STG.TYPE,
	SAS_CU_OL_DTL_STG.CUSTOMER_ORDER_LINE_DETAIL_ID,
	SAS_CU_OL_DTL_STG.AUDIT_CREATE_DATE,
	SAS_CU_OL_DTL_STG.AUDIT_CREATED_BY,
	SAS_CU_OL_DTL_STG.AUDIT_MODIFIED_BY,
	SAS_CU_OL_DTL_STG.AUDIT_MODIFY_DATE,
	SAS_CU_OL_DTL_STG.QUANTITY,
	SAS_CU_OL_DTL_STG.CUSTOMER_ORDER_LINE_ID,
	SAS_CU_OL_DTL_STG.ITEM_NUMBER,
	SAS_CU_OL_DTL_STG.ODS_CREATE_DATE,
	SAS_CU_OL_DTL_STG.ODS_MODIFY_DATE,
	SAS_CU_OL_DTL_STG.DELETED_IND
from	'
 || VariableCheckTable || 
' SAS_CU_OL_DTL_STG 
where	exists  (
		select	SUB1.CUSTOMER_ORDER_LINE_DETAIL_ID
		from 	' 
|| VariableCheckTable ||
'  SUB1
		where 	SUB1.CUSTOMER_ORDER_LINE_DETAIL_ID=SAS_CU_OL_DTL_STG.CUSTOMER_ORDER_LINE_DETAIL_ID
		group by 	SUB1.CUSTOMER_ORDER_LINE_DETAIL_ID
		having 	count(1) > 1
		)
';

END;


&


/*-----------------------------------------------*/
/* TASK No. 21 */
/* Create index on AK */

 
/* FLOW CONTROL CREATE THE iNDEX ON THE I$TABLE */
-- create index 	SAS_CUST_ORD_LINE_DETAIL_PK_flow
-- on	RAX_APP_USER.I$_SAS_CU_OL_DTL_STG1387001 
-- 	(CUSTOMER_ORDER_LINE_DETAIL_ID)

BEGIN
  EXECUTE IMMEDIATE 'create index SAS_CUST_ORD_LINE_DETAIL_PK_flow
on   RAX_APP_USER.I$_SAS_CU_OL_DTL_STG1387001 (CUSTOMER_ORDER_LINE_DETAIL_ID)';
EXCEPTION
  WHEN OTHERS THEN
   -- Handle the case where the identifier is too long (ORA-00972)
   IF SQLCODE = -972 or  SQLCODE = -1408 or SQLCODE = -955  THEN
     DBMS_OUTPUT.PUT_LINE('Identifier is too long. Skipping creation of index.');
   ELSE
     RAISE;
   END IF;
END;

&


/*-----------------------------------------------*/
/* TASK No. 22 */
/* insert AK errors */

DECLARE
               CheckTable                             VarChar2(60);
               TargetTable                            VarChar2(60);
               VariableCheckTable                VarChar2(60);

BEGIN
               SELECT 'RAX_APP_USER.I$_SAS_CU_OL_DTL_STG' INTO CheckTable FROM DUAL;
               SELECT 'ODS_STAGE.SAS_CUST_ORD_LINE_DTL_STG' INTO TargetTable FROM DUAL;

IF CheckTable = TargetTable THEN
   VariableCheckTable := CheckTable; 
ELSE
   VariableCheckTable := CheckTable || '1387001';
END IF;

execute immediate '
insert into RAX_APP_USER.E$_SAS_CU_OL_DTL_STG1387001
(
	ODI_PK,
	ODI_SESS_NO,
	ODI_ROW_ID,
	ODI_ERR_TYPE,
	ODI_ERR_MESS,
	ODI_ORIGIN,
	ODI_CHECK_DATE,
	ODI_CONS_NAME,
	ODI_CONS_TYPE,
	TYPE,
	CUSTOMER_ORDER_LINE_DETAIL_ID,
	AUDIT_CREATE_DATE,
	AUDIT_CREATED_BY,
	AUDIT_MODIFIED_BY,
	AUDIT_MODIFY_DATE,
	QUANTITY,
	CUSTOMER_ORDER_LINE_ID,
	ITEM_NUMBER,
	ODS_CREATE_DATE,
	ODS_MODIFY_DATE,
	DELETED_IND
)
select	SYS_GUID(),
	:v_sess_no, 
	rowid,
	''F'', 
	''ODI-15063: The alternate key SAS_CUST_ORD_LINE_DETAIL_PK is not unique.'',
	''(1387001)ODS_Project.LOAD_SAS_CUST_ORD_LINE_DTL_STG_INT'',
	sysdate,
	''SAS_CUST_ORD_LINE_DETAIL_PK'',
	''AK'',	
	SAS_CU_OL_DTL_STG.TYPE,
	SAS_CU_OL_DTL_STG.CUSTOMER_ORDER_LINE_DETAIL_ID,
	SAS_CU_OL_DTL_STG.AUDIT_CREATE_DATE,
	SAS_CU_OL_DTL_STG.AUDIT_CREATED_BY,
	SAS_CU_OL_DTL_STG.AUDIT_MODIFIED_BY,
	SAS_CU_OL_DTL_STG.AUDIT_MODIFY_DATE,
	SAS_CU_OL_DTL_STG.QUANTITY,
	SAS_CU_OL_DTL_STG.CUSTOMER_ORDER_LINE_ID,
	SAS_CU_OL_DTL_STG.ITEM_NUMBER,
	SAS_CU_OL_DTL_STG.ODS_CREATE_DATE,
	SAS_CU_OL_DTL_STG.ODS_MODIFY_DATE,
	SAS_CU_OL_DTL_STG.DELETED_IND
from              '	
 || VariableCheckTable || 
' SAS_CU_OL_DTL_STG
where	exists  (
		select	SUB.CUSTOMER_ORDER_LINE_DETAIL_ID
		from 	'
 || VariableCheckTable || 
' SUB
		where 	SUB.CUSTOMER_ORDER_LINE_DETAIL_ID=SAS_CU_OL_DTL_STG.CUSTOMER_ORDER_LINE_DETAIL_ID
		group by 	SUB.CUSTOMER_ORDER_LINE_DETAIL_ID
		having 	count(1) > 1
		)
 ';

END;

/*  Checked Datastore =RAX_APP_USER.I$_SAS_CU_OL_DTL_STG  */
/*  Integration Datastore =RAX_APP_USER.I$_SAS_CU_OL_DTL_STG   */
/*  Target Datastore =ODS_STAGE.SAS_CUST_ORD_LINE_DTL_STG */



&


/*-----------------------------------------------*/
/* TASK No. 23 */
/* insert Not Null errors */

insert into RAX_APP_USER.E$_SAS_CU_OL_DTL_STG1387001
(
	ODI_PK,
	ODI_SESS_NO,
	ODI_ROW_ID,
	ODI_ERR_TYPE,
	ODI_ERR_MESS,
	ODI_CHECK_DATE,
	ODI_ORIGIN,
	ODI_CONS_NAME,
	ODI_CONS_TYPE,
	TYPE,
	CUSTOMER_ORDER_LINE_DETAIL_ID,
	AUDIT_CREATE_DATE,
	AUDIT_CREATED_BY,
	AUDIT_MODIFIED_BY,
	AUDIT_MODIFY_DATE,
	QUANTITY,
	CUSTOMER_ORDER_LINE_ID,
	ITEM_NUMBER,
	ODS_CREATE_DATE,
	ODS_MODIFY_DATE,
	DELETED_IND
)
select
	SYS_GUID(),
	:v_sess_no, 
	rowid,
	'F', 
	'ODI-15066: The column TYPE cannot be null.',
	sysdate,
	'(1387001)ODS_Project.LOAD_SAS_CUST_ORD_LINE_DTL_STG_INT',
	'TYPE',
	'NN',	
	TYPE,
	CUSTOMER_ORDER_LINE_DETAIL_ID,
	AUDIT_CREATE_DATE,
	AUDIT_CREATED_BY,
	AUDIT_MODIFIED_BY,
	AUDIT_MODIFY_DATE,
	QUANTITY,
	CUSTOMER_ORDER_LINE_ID,
	ITEM_NUMBER,
	ODS_CREATE_DATE,
	ODS_MODIFY_DATE,
	DELETED_IND
from	RAX_APP_USER.I$_SAS_CU_OL_DTL_STG1387001
where	TYPE is null



&


/*-----------------------------------------------*/
/* TASK No. 24 */
/* insert Not Null errors */

insert into RAX_APP_USER.E$_SAS_CU_OL_DTL_STG1387001
(
	ODI_PK,
	ODI_SESS_NO,
	ODI_ROW_ID,
	ODI_ERR_TYPE,
	ODI_ERR_MESS,
	ODI_CHECK_DATE,
	ODI_ORIGIN,
	ODI_CONS_NAME,
	ODI_CONS_TYPE,
	TYPE,
	CUSTOMER_ORDER_LINE_DETAIL_ID,
	AUDIT_CREATE_DATE,
	AUDIT_CREATED_BY,
	AUDIT_MODIFIED_BY,
	AUDIT_MODIFY_DATE,
	QUANTITY,
	CUSTOMER_ORDER_LINE_ID,
	ITEM_NUMBER,
	ODS_CREATE_DATE,
	ODS_MODIFY_DATE,
	DELETED_IND
)
select
	SYS_GUID(),
	:v_sess_no, 
	rowid,
	'F', 
	'ODI-15066: The column CUSTOMER_ORDER_LINE_DETAIL_ID cannot be null.',
	sysdate,
	'(1387001)ODS_Project.LOAD_SAS_CUST_ORD_LINE_DTL_STG_INT',
	'CUSTOMER_ORDER_LINE_DETAIL_ID',
	'NN',	
	TYPE,
	CUSTOMER_ORDER_LINE_DETAIL_ID,
	AUDIT_CREATE_DATE,
	AUDIT_CREATED_BY,
	AUDIT_MODIFIED_BY,
	AUDIT_MODIFY_DATE,
	QUANTITY,
	CUSTOMER_ORDER_LINE_ID,
	ITEM_NUMBER,
	ODS_CREATE_DATE,
	ODS_MODIFY_DATE,
	DELETED_IND
from	RAX_APP_USER.I$_SAS_CU_OL_DTL_STG1387001
where	CUSTOMER_ORDER_LINE_DETAIL_ID is null



&


/*-----------------------------------------------*/
/* TASK No. 25 */
/* insert Not Null errors */

insert into RAX_APP_USER.E$_SAS_CU_OL_DTL_STG1387001
(
	ODI_PK,
	ODI_SESS_NO,
	ODI_ROW_ID,
	ODI_ERR_TYPE,
	ODI_ERR_MESS,
	ODI_CHECK_DATE,
	ODI_ORIGIN,
	ODI_CONS_NAME,
	ODI_CONS_TYPE,
	TYPE,
	CUSTOMER_ORDER_LINE_DETAIL_ID,
	AUDIT_CREATE_DATE,
	AUDIT_CREATED_BY,
	AUDIT_MODIFIED_BY,
	AUDIT_MODIFY_DATE,
	QUANTITY,
	CUSTOMER_ORDER_LINE_ID,
	ITEM_NUMBER,
	ODS_CREATE_DATE,
	ODS_MODIFY_DATE,
	DELETED_IND
)
select
	SYS_GUID(),
	:v_sess_no, 
	rowid,
	'F', 
	'ODI-15066: The column AUDIT_CREATE_DATE cannot be null.',
	sysdate,
	'(1387001)ODS_Project.LOAD_SAS_CUST_ORD_LINE_DTL_STG_INT',
	'AUDIT_CREATE_DATE',
	'NN',	
	TYPE,
	CUSTOMER_ORDER_LINE_DETAIL_ID,
	AUDIT_CREATE_DATE,
	AUDIT_CREATED_BY,
	AUDIT_MODIFIED_BY,
	AUDIT_MODIFY_DATE,
	QUANTITY,
	CUSTOMER_ORDER_LINE_ID,
	ITEM_NUMBER,
	ODS_CREATE_DATE,
	ODS_MODIFY_DATE,
	DELETED_IND
from	RAX_APP_USER.I$_SAS_CU_OL_DTL_STG1387001
where	AUDIT_CREATE_DATE is null



&


/*-----------------------------------------------*/
/* TASK No. 26 */
/* insert Not Null errors */

insert into RAX_APP_USER.E$_SAS_CU_OL_DTL_STG1387001
(
	ODI_PK,
	ODI_SESS_NO,
	ODI_ROW_ID,
	ODI_ERR_TYPE,
	ODI_ERR_MESS,
	ODI_CHECK_DATE,
	ODI_ORIGIN,
	ODI_CONS_NAME,
	ODI_CONS_TYPE,
	TYPE,
	CUSTOMER_ORDER_LINE_DETAIL_ID,
	AUDIT_CREATE_DATE,
	AUDIT_CREATED_BY,
	AUDIT_MODIFIED_BY,
	AUDIT_MODIFY_DATE,
	QUANTITY,
	CUSTOMER_ORDER_LINE_ID,
	ITEM_NUMBER,
	ODS_CREATE_DATE,
	ODS_MODIFY_DATE,
	DELETED_IND
)
select
	SYS_GUID(),
	:v_sess_no, 
	rowid,
	'F', 
	'ODI-15066: The column AUDIT_CREATED_BY cannot be null.',
	sysdate,
	'(1387001)ODS_Project.LOAD_SAS_CUST_ORD_LINE_DTL_STG_INT',
	'AUDIT_CREATED_BY',
	'NN',	
	TYPE,
	CUSTOMER_ORDER_LINE_DETAIL_ID,
	AUDIT_CREATE_DATE,
	AUDIT_CREATED_BY,
	AUDIT_MODIFIED_BY,
	AUDIT_MODIFY_DATE,
	QUANTITY,
	CUSTOMER_ORDER_LINE_ID,
	ITEM_NUMBER,
	ODS_CREATE_DATE,
	ODS_MODIFY_DATE,
	DELETED_IND
from	RAX_APP_USER.I$_SAS_CU_OL_DTL_STG1387001
where	AUDIT_CREATED_BY is null



&


/*-----------------------------------------------*/
/* TASK No. 27 */
/* insert Not Null errors */

insert into RAX_APP_USER.E$_SAS_CU_OL_DTL_STG1387001
(
	ODI_PK,
	ODI_SESS_NO,
	ODI_ROW_ID,
	ODI_ERR_TYPE,
	ODI_ERR_MESS,
	ODI_CHECK_DATE,
	ODI_ORIGIN,
	ODI_CONS_NAME,
	ODI_CONS_TYPE,
	TYPE,
	CUSTOMER_ORDER_LINE_DETAIL_ID,
	AUDIT_CREATE_DATE,
	AUDIT_CREATED_BY,
	AUDIT_MODIFIED_BY,
	AUDIT_MODIFY_DATE,
	QUANTITY,
	CUSTOMER_ORDER_LINE_ID,
	ITEM_NUMBER,
	ODS_CREATE_DATE,
	ODS_MODIFY_DATE,
	DELETED_IND
)
select
	SYS_GUID(),
	:v_sess_no, 
	rowid,
	'F', 
	'ODI-15066: The column AUDIT_MODIFIED_BY cannot be null.',
	sysdate,
	'(1387001)ODS_Project.LOAD_SAS_CUST_ORD_LINE_DTL_STG_INT',
	'AUDIT_MODIFIED_BY',
	'NN',	
	TYPE,
	CUSTOMER_ORDER_LINE_DETAIL_ID,
	AUDIT_CREATE_DATE,
	AUDIT_CREATED_BY,
	AUDIT_MODIFIED_BY,
	AUDIT_MODIFY_DATE,
	QUANTITY,
	CUSTOMER_ORDER_LINE_ID,
	ITEM_NUMBER,
	ODS_CREATE_DATE,
	ODS_MODIFY_DATE,
	DELETED_IND
from	RAX_APP_USER.I$_SAS_CU_OL_DTL_STG1387001
where	AUDIT_MODIFIED_BY is null



&


/*-----------------------------------------------*/
/* TASK No. 28 */
/* insert Not Null errors */

insert into RAX_APP_USER.E$_SAS_CU_OL_DTL_STG1387001
(
	ODI_PK,
	ODI_SESS_NO,
	ODI_ROW_ID,
	ODI_ERR_TYPE,
	ODI_ERR_MESS,
	ODI_CHECK_DATE,
	ODI_ORIGIN,
	ODI_CONS_NAME,
	ODI_CONS_TYPE,
	TYPE,
	CUSTOMER_ORDER_LINE_DETAIL_ID,
	AUDIT_CREATE_DATE,
	AUDIT_CREATED_BY,
	AUDIT_MODIFIED_BY,
	AUDIT_MODIFY_DATE,
	QUANTITY,
	CUSTOMER_ORDER_LINE_ID,
	ITEM_NUMBER,
	ODS_CREATE_DATE,
	ODS_MODIFY_DATE,
	DELETED_IND
)
select
	SYS_GUID(),
	:v_sess_no, 
	rowid,
	'F', 
	'ODI-15066: The column AUDIT_MODIFY_DATE cannot be null.',
	sysdate,
	'(1387001)ODS_Project.LOAD_SAS_CUST_ORD_LINE_DTL_STG_INT',
	'AUDIT_MODIFY_DATE',
	'NN',	
	TYPE,
	CUSTOMER_ORDER_LINE_DETAIL_ID,
	AUDIT_CREATE_DATE,
	AUDIT_CREATED_BY,
	AUDIT_MODIFIED_BY,
	AUDIT_MODIFY_DATE,
	QUANTITY,
	CUSTOMER_ORDER_LINE_ID,
	ITEM_NUMBER,
	ODS_CREATE_DATE,
	ODS_MODIFY_DATE,
	DELETED_IND
from	RAX_APP_USER.I$_SAS_CU_OL_DTL_STG1387001
where	AUDIT_MODIFY_DATE is null



&


/*-----------------------------------------------*/
/* TASK No. 29 */
/* insert Not Null errors */

insert into RAX_APP_USER.E$_SAS_CU_OL_DTL_STG1387001
(
	ODI_PK,
	ODI_SESS_NO,
	ODI_ROW_ID,
	ODI_ERR_TYPE,
	ODI_ERR_MESS,
	ODI_CHECK_DATE,
	ODI_ORIGIN,
	ODI_CONS_NAME,
	ODI_CONS_TYPE,
	TYPE,
	CUSTOMER_ORDER_LINE_DETAIL_ID,
	AUDIT_CREATE_DATE,
	AUDIT_CREATED_BY,
	AUDIT_MODIFIED_BY,
	AUDIT_MODIFY_DATE,
	QUANTITY,
	CUSTOMER_ORDER_LINE_ID,
	ITEM_NUMBER,
	ODS_CREATE_DATE,
	ODS_MODIFY_DATE,
	DELETED_IND
)
select
	SYS_GUID(),
	:v_sess_no, 
	rowid,
	'F', 
	'ODI-15066: The column QUANTITY cannot be null.',
	sysdate,
	'(1387001)ODS_Project.LOAD_SAS_CUST_ORD_LINE_DTL_STG_INT',
	'QUANTITY',
	'NN',	
	TYPE,
	CUSTOMER_ORDER_LINE_DETAIL_ID,
	AUDIT_CREATE_DATE,
	AUDIT_CREATED_BY,
	AUDIT_MODIFIED_BY,
	AUDIT_MODIFY_DATE,
	QUANTITY,
	CUSTOMER_ORDER_LINE_ID,
	ITEM_NUMBER,
	ODS_CREATE_DATE,
	ODS_MODIFY_DATE,
	DELETED_IND
from	RAX_APP_USER.I$_SAS_CU_OL_DTL_STG1387001
where	QUANTITY is null



&


/*-----------------------------------------------*/
/* TASK No. 30 */
/* create index on error table */

 
/* FLOW CONTROL CREATE INDEX ON THE E$TABLE */
-- create index 	RAX_APP_USER.E$_SAS_CU_OL_DTL_STG1387001
-- on	RAX_APP_USER.E$_SAS_CU_OL_DTL_STG1387001 (ODI_ROW_ID)

BEGIN
  EXECUTE IMMEDIATE 'create index RAX_APP_USER.E$_SAS_CU_OL_DTL_STG1387001
on   RAX_APP_USER.E$_SAS_CU_OL_DTL_STG1387001 (ODI_ROW_ID)';
EXCEPTION
  WHEN OTHERS THEN
   -- Handle the case where the identifier is too long (ORA-00972)
   IF SQLCODE = -972 or  SQLCODE = -1408 or SQLCODE = -955  THEN
     DBMS_OUTPUT.PUT_LINE('Identifier is too long. Skipping creation of index.');
   ELSE
     RAISE;
   END IF;
END;

&


/*-----------------------------------------------*/
/* TASK No. 31 */
/* delete errors from controlled table */

delete from	RAX_APP_USER.I$_SAS_CU_OL_DTL_STG1387001  T
where	exists 	(
		select	1
		from	RAX_APP_USER.E$_SAS_CU_OL_DTL_STG1387001 E
		where ODI_SESS_NO = :v_sess_no
		and T.rowid = E.ODI_ROW_ID
		)


&


/*-----------------------------------------------*/
/* TASK No. 32 */
/* insert check sum into check table */

insert into RAX_APP_USER.SNP_CHECK_TAB
(
	SCHEMA_NAME,
	RESOURCE_NAME,
	FULL_RES_NAME,
	ERR_TYPE,
	ERR_MESS,
	CHECK_DATE,
	ORIGIN,
	CONS_NAME,
	CONS_TYPE,
	ERR_COUNT
)
select	
	'ODS_STAGE',
	'SAS_CU_OL_DTL_STG',
	'ODS_STAGE.SAS_CUST_ORD_LINE_DTL_STG1387001',
	E.ODI_ERR_TYPE,
	E.ODI_ERR_MESS,
	E.ODI_CHECK_DATE,
	E.ODI_ORIGIN,
	E.ODI_CONS_NAME,
	E.ODI_CONS_TYPE,
	count(1) 
from	RAX_APP_USER.E$_SAS_CU_OL_DTL_STG1387001 E
where	E.ODI_ERR_TYPE	= 'F'
and	E.ODI_ORIGIN 	= '(1387001)ODS_Project.LOAD_SAS_CUST_ORD_LINE_DTL_STG_INT'
group by	E.ODI_ERR_TYPE,
	E.ODI_ERR_MESS,
	E.ODI_CHECK_DATE,
	E.ODI_ORIGIN,
	E.ODI_CONS_NAME,
	E.ODI_CONS_TYPE


&


/*-----------------------------------------------*/
/* TASK No. 33 */
/* Merge Rows */

merge into	ODS_STAGE.SAS_CUST_ORD_LINE_DTL_STG T
using	RAX_APP_USER.I$_SAS_CU_OL_DTL_STG1387001 S
on	(
		T.CUSTOMER_ORDER_LINE_DETAIL_ID=S.CUSTOMER_ORDER_LINE_DETAIL_ID
	)
when matched
then update set
	T.TYPE	= S.TYPE,
	T.AUDIT_CREATE_DATE	= S.AUDIT_CREATE_DATE,
	T.AUDIT_CREATED_BY	= S.AUDIT_CREATED_BY,
	T.AUDIT_MODIFIED_BY	= S.AUDIT_MODIFIED_BY,
	T.AUDIT_MODIFY_DATE	= S.AUDIT_MODIFY_DATE,
	T.QUANTITY	= S.QUANTITY,
	T.CUSTOMER_ORDER_LINE_ID	= S.CUSTOMER_ORDER_LINE_ID,
	T.ITEM_NUMBER	= S.ITEM_NUMBER,
	T.DELETED_IND	= S.DELETED_IND
	,         T.ODS_MODIFY_DATE	= sysdate
when not matched
then insert
	(
	T.TYPE,
	T.CUSTOMER_ORDER_LINE_DETAIL_ID,
	T.AUDIT_CREATE_DATE,
	T.AUDIT_CREATED_BY,
	T.AUDIT_MODIFIED_BY,
	T.AUDIT_MODIFY_DATE,
	T.QUANTITY,
	T.CUSTOMER_ORDER_LINE_ID,
	T.ITEM_NUMBER,
	T.DELETED_IND
	,          T.ODS_CREATE_DATE,
	T.ODS_MODIFY_DATE
	)
values
	(
	S.TYPE,
	S.CUSTOMER_ORDER_LINE_DETAIL_ID,
	S.AUDIT_CREATE_DATE,
	S.AUDIT_CREATED_BY,
	S.AUDIT_MODIFIED_BY,
	S.AUDIT_MODIFY_DATE,
	S.QUANTITY,
	S.CUSTOMER_ORDER_LINE_ID,
	S.ITEM_NUMBER,
	S.DELETED_IND
	,          sysdate,
	sysdate
	)

&


/*-----------------------------------------------*/
/* TASK No. 34 */
/* Commit transaction */

/*commit*/


/*-----------------------------------------------*/
/* TASK No. 35 */
/* Drop flow table */

-- drop table RAX_APP_USER.I$_SAS_CU_OL_DTL_STG1387001

BEGIN
  EXECUTE IMMEDIATE 'drop table RAX_APP_USER.I$_SAS_CU_OL_DTL_STG1387001';
EXCEPTION
  WHEN OTHERS THEN
   IF SQLCODE != -942 THEN
     RAISE;
   END IF;
END;


&


/*-----------------------------------------------*/
/* TASK No. 1000008 */
/* Drop work table */

-- drop table RAX_APP_USER.C$_0SAS_CU_OL_DTL_STG purge

BEGIN
  EXECUTE IMMEDIATE 'drop table RAX_APP_USER.C$_0SAS_CU_OL_DTL_STG purge';
EXCEPTION
  WHEN OTHERS THEN
   IF SQLCODE != -942 THEN
     RAISE;
   END IF;
END;



&


/*-----------------------------------------------*/
/* TASK No. 36 */
/* Command MERGE INTO SAS_CUST_ORD_LINE_DTL_XR */

-- SAS_CUSTOMER_ORDER_LINE_XR
MERGE INTO ODS_STAGE.SAS_CUST_ORD_LINE_DTL_XR d
USING (
select * from
    (  Select
        XR.CUSTOMER_ORDER_LINE_DETAIL_OID as CUSTOMER_ORDER_LINE_DETAIL_OID,
        STG.CUSTOMER_ORDER_LINE_DETAIL_ID as SK_CUSTOMER_ORD_LINE_DETAIL_ID      ,
        STG.CUSTOMER_ORDER_LINE_ID as SK_CUSTOMER_ORDER_LINE_ID,
        sysdate as ODS_CREATE_DATE,
        sysdate as ODS_MODIFY_DATE
    FROM 
        ODS_STAGE.SAS_CUST_ORD_LINE_DTL_STG stg
        ,ODS_STAGE.SAS_CUST_ORD_LINE_DTL_XR xr
    WHERE (1=1)
        and stg.ODS_MODIFY_DATE >= TO_DATE(SUBSTR(:v_cdc_load_date, 1, 19), 'YYYY-MM-DD HH24:MI:SS')  -:v_cdc_overlap
        and STG.CUSTOMER_ORDER_LINE_DETAIL_ID=XR.SK_CUSTOMER_ORD_LINE_DETAIL_ID(+)
     ) s
where NOT EXISTS 
	( select 1 from ODS_STAGE.SAS_CUST_ORD_LINE_DTL_XR T
	where	T.SK_CUSTOMER_ORD_LINE_DETAIL_ID = S.SK_CUSTOMER_ORD_LINE_DETAIL_ID 
		 and
		((T.CUSTOMER_ORDER_LINE_DETAIL_OID = S.CUSTOMER_ORDER_LINE_DETAIL_OID) or (T.CUSTOMER_ORDER_LINE_DETAIL_OID  IS NULL and S.CUSTOMER_ORDER_LINE_DETAIL_OID   IS NULL)) and
		((T.SK_CUSTOMER_ORDER_LINE_ID = S.SK_CUSTOMER_ORDER_LINE_ID) or (T.SK_CUSTOMER_ORDER_LINE_ID IS NULL and S.SK_CUSTOMER_ORDER_LINE_ID IS NULL)) 
	)	
) s 
ON
  (s.SK_CUSTOMER_ORD_LINE_DETAIL_ID =d.SK_CUSTOMER_ORD_LINE_DETAIL_ID)
WHEN MATCHED
THEN
UPDATE SET
  d.CUSTOMER_ORDER_LINE_DETAIL_OID = s.CUSTOMER_ORDER_LINE_DETAIL_OID,
  d.SK_CUSTOMER_ORDER_LINE_ID = s.SK_CUSTOMER_ORDER_LINE_ID,
  d.ODS_MODIFY_DATE = s.ODS_MODIFY_DATE
WHEN NOT MATCHED
THEN
INSERT (
  CUSTOMER_ORDER_LINE_DETAIL_OID, SK_CUSTOMER_ORDER_LINE_ID, SK_CUSTOMER_ORD_LINE_DETAIL_ID,
   ODS_CREATE_DATE, ODS_MODIFY_DATE)
VALUES (
  ODS_STAGE.CUST_ORD_LINE_DTL_OID_SEQ.nextval, s.SK_CUSTOMER_ORDER_LINE_ID, s.SK_CUSTOMER_ORD_LINE_DETAIL_ID,
   s.ODS_CREATE_DATE, s.ODS_MODIFY_DATE
  )

&


/*-----------------------------------------------*/
/* TASK No. 37 */
/* Command MERGE INTO ODS_OWN.SAS_CUST_ORD_LINE_DTL */

MERGE INTO ODS_OWN.SAS_CUSTOMER_ORDER_LINE_DETAIL d
USING (
select * from (
      Select
        xr.CUSTOMER_ORDER_LINE_DETAIL_OID  as CUSTOMER_ORDER_LINE_DETAIL_OID ,
        axr.CUSTOMER_ORDER_LINE_OID as  CUSTOMER_ORDER_LINE_OID,
        stg.AUDIT_CREATE_DATE as AUDIT_CREATE_DATE,
        stg.AUDIT_CREATED_BY as AUDIT_CREATED_BY,
        stg.AUDIT_MODIFIED_BY as AUDIT_MODIFIED_BY,
        stg.AUDIT_MODIFY_DATE as  AUDIT_MODIFY_DATE,             
        stg.TYPE,           
        stg.QUANTITY,      
        stg.ITEM_NUMBER,
        stg.DELETED_IND                ,
        sysdate as ODS_CREATE_DATE,
        sysdate as ODS_MODIFY_DATE,
       SS.SOURCE_SYSTEM_OID as SOURCE_SYSTEM_OID
 
    FROM 
        ODS_STAGE.SAS_CUST_ORD_LINE_DTL_STG stg
        ,ODS_STAGE.SAS_CUST_ORD_LINE_DTL_XR xr
        ,ODS_STAGE.SAS_CUSTOMER_ORDER_LINE_XR axr
       ,ODS_OWN.SOURCE_SYSTEM SS
    WHERE (1=1)
        and stg.ODS_MODIFY_DATE >= TO_DATE(SUBSTR(:v_cdc_load_date, 1, 19), 'YYYY-MM-DD HH24:MI:SS')  -:v_cdc_overlap
  and SS.SOURCE_SYSTEM_SHORT_NAME='SAS'
        and stg.CUSTOMER_ORDER_LINE_DETAIL_ID =xr.SK_CUSTOMER_ORD_LINE_DETAIL_ID(+)
        and xr.SK_CUSTOMER_ORDER_LINE_ID =AXR.SK_CUSTOMER_ORDER_LINE_ID (+)
   ) s
where NOT EXISTS 
	( select 1 from ODS_OWN.SAS_CUSTOMER_ORDER_LINE_DETAIL T
	where	T.CUSTOMER_ORDER_LINE_DETAIL_OID	= S.CUSTOMER_ORDER_LINE_DETAIL_OID 
 	and ((T.CUSTOMER_ORDER_LINE_DETAIL_OID = S.CUSTOMER_ORDER_LINE_DETAIL_OID) or (T.CUSTOMER_ORDER_LINE_DETAIL_OID IS NULL and S.CUSTOMER_ORDER_LINE_DETAIL_OID IS NULL)) and
 ((T.CUSTOMER_ORDER_LINE_OID = S.CUSTOMER_ORDER_LINE_OID) or (T.CUSTOMER_ORDER_LINE_OID IS NULL and S.CUSTOMER_ORDER_LINE_OID IS NULL)) and
 ((T.AUDIT_CREATE_DATE = S.AUDIT_CREATE_DATE) or (T.AUDIT_CREATE_DATE IS NULL and S.AUDIT_CREATE_DATE IS NULL)) and
((T.AUDIT_CREATED_BY = S.AUDIT_CREATED_BY) or (T.AUDIT_CREATED_BY IS NULL and S.AUDIT_CREATED_BY IS NULL)) and
        ((T.AUDIT_MODIFY_DATE = S.AUDIT_MODIFY_DATE) or (T.AUDIT_MODIFY_DATE IS NULL and S.AUDIT_MODIFY_DATE IS NULL)) and
        ((T.AUDIT_MODIFIED_BY = S.AUDIT_MODIFIED_BY) or (T.AUDIT_MODIFIED_BY IS NULL and S.AUDIT_MODIFIED_BY IS NULL)) and
 ((T.SOURCE_SYSTEM_OID = S.SOURCE_SYSTEM_OID) or (T.SOURCE_SYSTEM_OID IS NULL and S.SOURCE_SYSTEM_OID IS NULL)) AND
 ((T.TYPE=S.TYPE) or(T.TYPE  IS NULL and S.TYPE IS NULL)) AND    
 ((T.QUANTITY=S.QUANTITY) or(T.QUANTITY  IS NULL and S.QUANTITY IS NULL)) AND  
((T.ITEM_NUMBER =S.ITEM_NUMBER) or(T.ITEM_NUMBER  IS NULL and S.ITEM_NUMBER IS NULL)) AND  
((T.DELETED_IND  =S.DELETED_IND  ) or(T.DELETED_IND  IS NULL and S.DELETED_IND  IS NULL))   
        ) 
) s 
ON
  (d.CUSTOMER_ORDER_LINE_DETAIL_OID = s.CUSTOMER_ORDER_LINE_DETAIL_OID)
WHEN MATCHED
THEN
UPDATE SET
  d.CUSTOMER_ORDER_LINE_OID = s.CUSTOMER_ORDER_LINE_OID,
  d.AUDIT_CREATE_DATE = s.AUDIT_CREATE_DATE,
  d.AUDIT_CREATED_BY = s.AUDIT_CREATED_BY,
  d.AUDIT_MODIFY_DATE = s.AUDIT_MODIFY_DATE,
  d.AUDIT_MODIFIED_BY = s.AUDIT_MODIFIED_BY,
  d.SOURCE_SYSTEM_OID = s.SOURCE_SYSTEM_OID,
  d.TYPE=s.TYPE,
  d.QUANTITY=s.QUANTITY,
  d.ITEM_NUMBER=s.ITEM_NUMBER,
  d.ODS_MODIFY_DATE=s.ODS_MODIFY_DATE,
  d.DELETED_IND=s.DELETED_IND
WHEN NOT MATCHED
THEN
INSERT (CUSTOMER_ORDER_LINE_DETAIL_OID,CUSTOMER_ORDER_LINE_OID, 
  AUDIT_CREATE_DATE,
  AUDIT_CREATED_BY, AUDIT_MODIFY_DATE, AUDIT_MODIFIED_BY,TYPE ,ODS_MODIFY_DATE,ODS_CREATE_DATE,DELETED_IND,
QUANTITY,ITEM_NUMBER

)VALUES(s.CUSTOMER_ORDER_LINE_DETAIL_OID,s.CUSTOMER_ORDER_LINE_OID,
  s.AUDIT_CREATE_DATE,
  s.AUDIT_CREATED_BY, s.AUDIT_MODIFY_DATE,s. AUDIT_MODIFIED_BY,s.TYPE, s.ODS_MODIFY_DATE,s.ODS_CREATE_DATE,s.DELETED_IND,s.QUANTITY,
s.ITEM_NUMBER

)



&


/*-----------------------------------------------*/
/* TASK No. 38 */
/* Update CDC Load Status */

UPDATE ODS_OWN.ODS_CDC_LOAD_STATUS
SET LAST_CDC_COMPLETION_DATE=TO_DATE(
             SUBSTR(:v_sess_beg, 1, 19), 'RRRR-MM-DD HH24:MI:SS')
+ nvl((TIMEZONE_OFFSET/24), 0) 
WHERE ODS_TABLE_NAME=:v_cdc_load_table_name
AND CONTEXT_NAME = :v_env

/*
UPDATE ODS_OWN.ODS_CDC_LOAD_STATUS
SET LAST_CDC_COMPLETION_DATE=TO_DATE(
             SUBSTR(:v_sess_beg, 1, 19), 'RRRR-MM-DD HH24:MI:SS')
WHERE ODS_TABLE_NAME=:v_cdc_load_table_name
AND CONTEXT_NAME = :v_env
*/

&


/*-----------------------------------------------*/
/* TASK No. 39 */
/* Insert CDC Audit Record */

INSERT INTO RAX_APP_USER.ODS_CDC_LOAD_STATUS_AUDIT
(TABLE_NAME,
SESS_NO,                      
SESS_NAME,                    
SCEN_VERSION,                 
SESS_BEG,                     
ORIG_LAST_CDC_COMPLETION_DATE,
OVERLAP,
CREATE_DATE,
CONTEXT_NAME,
TIMEZONE_OFFSET              
)
select 
:v_cdc_load_table_name
,:v_sess_no
,'LOAD_SAS_CUST_ORD_LINE_DTL_PKG'
,'004'
,TO_DATE(SUBSTR(:v_sess_beg, 1, 19), 'RRRR-MM-DD HH24:MI:SS')
,TO_DATE (SUBSTR(:v_cdc_load_date, 1, 19),'YYYY-MM-DD HH24:MI:SS')
,:v_cdc_overlap
,SYSDATE
,:v_env
,TIMEZONE_OFFSET
from 
ODS_OWN.ODS_CDC_LOAD_STATUS
WHERE ODS_TABLE_NAME=:v_cdc_load_table_name
AND CONTEXT_NAME = :v_env

/*
INSERT INTO RAX_APP_USER.ODS_CDC_LOAD_STATUS_AUDIT
(TABLE_NAME,
SESS_NO,                      
SESS_NAME,                    
SCEN_VERSION,                 
SESS_BEG,                     
ORIG_LAST_CDC_COMPLETION_DATE,
OVERLAP,
CREATE_DATE,
CONTEXT_NAME              
)
values (
:v_cdc_load_table_name,
:v_sess_no,
'LOAD_SAS_CUST_ORD_LINE_DTL_PKG',
'004',
TO_DATE(
             SUBSTR(:v_sess_beg, 1, 19), 'RRRR-MM-DD HH24:MI:SS'),
TO_DATE (SUBSTR (:v_cdc_load_date, 1, 19),
                           'YYYY-MM-DD HH24:MI:SS'
                          )
,:v_cdc_overlap,
SYSDATE,
 :v_env)
*/


&


/*-----------------------------------------------*/
