/* TASK No. 1 */

/* NONE or SET VARIABLE STATEMENT FOUND, CHECK ODI TASK NO. 1 */




/*-----------------------------------------------*/
/* TASK No. 2 */

/* SELECT STATEMENT FOUND, CHECK ODI TASK NO. 2 */




/*-----------------------------------------------*/
/* TASK No. 3 */

/* SELECT STATEMENT FOUND, CHECK ODI TASK NO. 3 */




/*-----------------------------------------------*/
/* TASK No. 4 */
/* Drop work table */

-- drop table RAX_APP_USER.C$_0SAS_CUST_ORD_LN_STG purge

-- &


/*-----------------------------------------------*/
/* TASK No. 5 */
/* Create work table */

-- create table RAX_APP_USER.C$_0SAS_CUST_ORD_LN_STG
-- (
-- 	C1_LINE_TYPE	VARCHAR2(1) NULL,
-- 	C2_CUSTOMER_ORDER_LINE_ID	NUMBER(10) NULL,
-- 	C3_AUDIT_CREATE_DATE	TIMESTAMP(6) NULL,
-- 	C4_AUDIT_CREATED_BY	VARCHAR2(255) NULL,
-- 	C5_AUDIT_MODIFIED_BY	VARCHAR2(255) NULL,
-- 	C6_AUDIT_MODIFY_DATE	TIMESTAMP(6) NULL,
-- 	C7_DISCOUNT_AMOUNT	NUMBER(19,2) NULL,
-- 	C8_DISCOUNTED_ITEM_IND	NUMBER(1) NULL,
-- 	C9_PRICE	NUMBER(19,2) NULL,
-- 	C10_QUANTITY	NUMBER(10) NULL,
-- 	C11_SEQUENCE	NUMBER(10) NULL,
-- 	C12_TAX_TOTAL_EFFECTIVE_RATE	NUMBER(10,10) NULL,
-- 	C13_TAX_AMOUNT	NUMBER(19,2) NULL,
-- 	C14_TAX_AS_OF_DATE	VARCHAR2(255) NULL,
-- 	C15_CUSTOMER_ORDER_ID	NUMBER(10) NULL,
-- 	C16_ITEM_NUMBER	VARCHAR2(16) NULL,
-- 	C17_NAME	VARCHAR2(255) NULL,
-- 	C18_DELETED_IND	VARCHAR2(1) NULL
-- )
-- NOLOGGING

-- &


/*-----------------------------------------------*/
/* TASK No. 6 */
/* Load data */

/* SOURCE CODE */


-- select	
-- 	CUSTOMER_ORDER_LINE.LINE_TYPE	   C1_LINE_TYPE,
-- 	CUSTOMER_ORDER_LINE.CUSTOMER_ORDER_LINE_ID	   C2_CUSTOMER_ORDER_LINE_ID,
-- 	CUSTOMER_ORDER_LINE.AUDIT_CREATE_DATE	   C3_AUDIT_CREATE_DATE,
-- 	CUSTOMER_ORDER_LINE.AUDIT_CREATED_BY	   C4_AUDIT_CREATED_BY,
-- 	CUSTOMER_ORDER_LINE.AUDIT_MODIFIED_BY	   C5_AUDIT_MODIFIED_BY,
-- 	CUSTOMER_ORDER_LINE.AUDIT_MODIFY_DATE	   C6_AUDIT_MODIFY_DATE,
-- 	CUSTOMER_ORDER_LINE.DISCOUNT_AMOUNT	   C7_DISCOUNT_AMOUNT,
-- 	CUSTOMER_ORDER_LINE.DISCOUNTED_ITEM_IND	   C8_DISCOUNTED_ITEM_IND,
-- 	CUSTOMER_ORDER_LINE.PRICE	   C9_PRICE,
-- 	CUSTOMER_ORDER_LINE.QUANTITY	   C10_QUANTITY,
-- 	CUSTOMER_ORDER_LINE.SEQUENCE	   C11_SEQUENCE,
-- 	CUSTOMER_ORDER_LINE.TAX_TOTAL_EFFECTIVE_RATE	   C12_TAX_TOTAL_EFFECTIVE_RATE,
-- 	CUSTOMER_ORDER_LINE.TAX_AMOUNT	   C13_TAX_AMOUNT,
-- 	CUSTOMER_ORDER_LINE.TAX_AS_OF_DATE	   C14_TAX_AS_OF_DATE,
-- 	CUSTOMER_ORDER_LINE.CUSTOMER_ORDER_ID	   C15_CUSTOMER_ORDER_ID,
-- 	CUSTOMER_ORDER_LINE.ITEM_NUMBER	   C16_ITEM_NUMBER,
-- 	CUSTOMER_ORDER_LINE.NAME	   C17_NAME,
-- 	CUSTOMER_ORDER_LINE.DELETED_IND	   C18_DELETED_IND
-- from	SAS_SIT_OWN.CUSTOMER_ORDER_LINE   CUSTOMER_ORDER_LINE
-- where	(1=1)
-- And (CUSTOMER_ORDER_LINE.AUDIT_MODIFY_DATE >= TO_DATE(SUBSTR(:v_cdc_load_date, 1, 19), 'YYYY-MM-DD HH24:MI:SS')  -:v_cdc_overlap)


-- &

/* TARGET CODE */
-- insert /*+ append */ into RAX_APP_USER.C$_0SAS_CUST_ORD_LN_STG
-- (
-- 	C1_LINE_TYPE,
-- 	C2_CUSTOMER_ORDER_LINE_ID,
-- 	C3_AUDIT_CREATE_DATE,
-- 	C4_AUDIT_CREATED_BY,
-- 	C5_AUDIT_MODIFIED_BY,
-- 	C6_AUDIT_MODIFY_DATE,
-- 	C7_DISCOUNT_AMOUNT,
-- 	C8_DISCOUNTED_ITEM_IND,
-- 	C9_PRICE,
-- 	C10_QUANTITY,
-- 	C11_SEQUENCE,
-- 	C12_TAX_TOTAL_EFFECTIVE_RATE,
-- 	C13_TAX_AMOUNT,
-- 	C14_TAX_AS_OF_DATE,
-- 	C15_CUSTOMER_ORDER_ID,
-- 	C16_ITEM_NUMBER,
-- 	C17_NAME,
-- 	C18_DELETED_IND
-- )
-- values
-- (
-- 	:C1_LINE_TYPE,
-- 	:C2_CUSTOMER_ORDER_LINE_ID,
-- 	:C3_AUDIT_CREATE_DATE,
-- 	:C4_AUDIT_CREATED_BY,
-- 	:C5_AUDIT_MODIFIED_BY,
-- 	:C6_AUDIT_MODIFY_DATE,
-- 	:C7_DISCOUNT_AMOUNT,
-- 	:C8_DISCOUNTED_ITEM_IND,
-- 	:C9_PRICE,
-- 	:C10_QUANTITY,
-- 	:C11_SEQUENCE,
-- 	:C12_TAX_TOTAL_EFFECTIVE_RATE,
-- 	:C13_TAX_AMOUNT,
-- 	:C14_TAX_AS_OF_DATE,
-- 	:C15_CUSTOMER_ORDER_ID,
-- 	:C16_ITEM_NUMBER,
-- 	:C17_NAME,
-- 	:C18_DELETED_IND
-- )

-- &


/*-----------------------------------------------*/
/* TASK No. 7 */
/* Analyze work table */



BEGIN
DBMS_STATS.GATHER_TABLE_STATS (
    ownname =>	'RAX_APP_USER',
    tabname =>	'C$_0SAS_CUST_ORD_LN_STG',
    estimate_percent =>	DBMS_STATS.AUTO_SAMPLE_SIZE
);
END;




&


/*-----------------------------------------------*/
/* TASK No. 9 */
/* Set vID */

/* NONE or SET VARIABLE STATEMENT FOUND, CHECK ODI TASK NO. 9 */




/*-----------------------------------------------*/
/* TASK No. 10 */
/* Drop flow table */

-- drop table RAX_APP_USER.I$_SAS_CUST_ORD_LN_STG1385001

BEGIN
  EXECUTE IMMEDIATE 'drop table RAX_APP_USER.I$_SAS_CUST_ORD_LN_STG1385001';
EXCEPTION
  WHEN OTHERS THEN
   IF SQLCODE != -942 THEN
     RAISE;
   END IF;
END;


&


/*-----------------------------------------------*/
/* TASK No. 11 */
/* Create flow table I$ */

create table RAX_APP_USER.I$_SAS_CUST_ORD_LN_STG1385001
(
	LINE_TYPE	VARCHAR2(1) NULL,
	CUSTOMER_ORDER_LINE_ID	NUMBER(10) NULL,
	AUDIT_CREATE_DATE	TIMESTAMP(6) NULL,
	AUDIT_CREATED_BY	VARCHAR2(255) NULL,
	AUDIT_MODIFIED_BY	VARCHAR2(255) NULL,
	AUDIT_MODIFY_DATE	TIMESTAMP(6) NULL,
	DISCOUNT_AMOUNT	NUMBER(19,2) NULL,
	DISCOUNTED_ITEM_IND	NUMBER(1) NULL,
	PRICE	NUMBER(19,2) NULL,
	QUANTITY	NUMBER(10) NULL,
	SEQUENCE	NUMBER(10) NULL,
	TAX_TOTAL_EFFECTIVE_RATE	NUMBER(10,10) NULL,
	TAX_AMOUNT	NUMBER(19,2) NULL,
	TAX_AS_OF_DATE	VARCHAR2(255) NULL,
	CUSTOMER_ORDER_ID	NUMBER(10) NULL,
	ITEM_NUMBER	VARCHAR2(16) NULL,
	NAME	VARCHAR2(255) NULL,
	ODS_CREATE_DATE	DATE NULL,
	ODS_MODIFY_DATE	DATE NULL,
	DELETED_IND	VARCHAR2(1) NULL
	,IND_UPDATE		char(1)
)
NOLOGGING

&


/*-----------------------------------------------*/
/* TASK No. 12 */
/* Insert flow into I$ table */

/* DETECTION_STRATEGY = NOT_EXISTS */
 


  


insert into	RAX_APP_USER.I$_SAS_CUST_ORD_LN_STG1385001
(
	LINE_TYPE,
	CUSTOMER_ORDER_LINE_ID,
	AUDIT_CREATE_DATE,
	AUDIT_CREATED_BY,
	AUDIT_MODIFIED_BY,
	AUDIT_MODIFY_DATE,
	DISCOUNT_AMOUNT,
	DISCOUNTED_ITEM_IND,
	PRICE,
	QUANTITY,
	SEQUENCE,
	TAX_TOTAL_EFFECTIVE_RATE,
	TAX_AMOUNT,
	TAX_AS_OF_DATE,
	CUSTOMER_ORDER_ID,
	ITEM_NUMBER,
	NAME,
	DELETED_IND,
	IND_UPDATE
)
select 
LINE_TYPE,
	CUSTOMER_ORDER_LINE_ID,
	AUDIT_CREATE_DATE,
	AUDIT_CREATED_BY,
	AUDIT_MODIFIED_BY,
	AUDIT_MODIFY_DATE,
	DISCOUNT_AMOUNT,
	DISCOUNTED_ITEM_IND,
	PRICE,
	QUANTITY,
	SEQUENCE,
	TAX_TOTAL_EFFECTIVE_RATE,
	TAX_AMOUNT,
	TAX_AS_OF_DATE,
	CUSTOMER_ORDER_ID,
	ITEM_NUMBER,
	NAME,
	DELETED_IND,
	IND_UPDATE
 from (


select 	 
	
	C1_LINE_TYPE LINE_TYPE,
	C2_CUSTOMER_ORDER_LINE_ID CUSTOMER_ORDER_LINE_ID,
	C3_AUDIT_CREATE_DATE AUDIT_CREATE_DATE,
	C4_AUDIT_CREATED_BY AUDIT_CREATED_BY,
	C5_AUDIT_MODIFIED_BY AUDIT_MODIFIED_BY,
	C6_AUDIT_MODIFY_DATE AUDIT_MODIFY_DATE,
	C7_DISCOUNT_AMOUNT DISCOUNT_AMOUNT,
	C8_DISCOUNTED_ITEM_IND DISCOUNTED_ITEM_IND,
	C9_PRICE PRICE,
	C10_QUANTITY QUANTITY,
	C11_SEQUENCE SEQUENCE,
	C12_TAX_TOTAL_EFFECTIVE_RATE TAX_TOTAL_EFFECTIVE_RATE,
	C13_TAX_AMOUNT TAX_AMOUNT,
	C14_TAX_AS_OF_DATE TAX_AS_OF_DATE,
	C15_CUSTOMER_ORDER_ID CUSTOMER_ORDER_ID,
	C16_ITEM_NUMBER ITEM_NUMBER,
	C17_NAME NAME,
	C18_DELETED_IND DELETED_IND,

	'I' IND_UPDATE

from	RAX_APP_USER.C$_0SAS_CUST_ORD_LN_STG
where	(1=1)






) S
where NOT EXISTS 
	( select 1 from ODS_STAGE.SAS_CUSTOMER_ORDER_LINE_STG T
	where	T.CUSTOMER_ORDER_LINE_ID	= S.CUSTOMER_ORDER_LINE_ID 
		 and ((T.LINE_TYPE = S.LINE_TYPE) or (T.LINE_TYPE IS NULL and S.LINE_TYPE IS NULL)) and
		((T.AUDIT_CREATE_DATE = S.AUDIT_CREATE_DATE) or (T.AUDIT_CREATE_DATE IS NULL and S.AUDIT_CREATE_DATE IS NULL)) and
		((T.AUDIT_CREATED_BY = S.AUDIT_CREATED_BY) or (T.AUDIT_CREATED_BY IS NULL and S.AUDIT_CREATED_BY IS NULL)) and
		((T.AUDIT_MODIFIED_BY = S.AUDIT_MODIFIED_BY) or (T.AUDIT_MODIFIED_BY IS NULL and S.AUDIT_MODIFIED_BY IS NULL)) and
		((T.AUDIT_MODIFY_DATE = S.AUDIT_MODIFY_DATE) or (T.AUDIT_MODIFY_DATE IS NULL and S.AUDIT_MODIFY_DATE IS NULL)) and
		((T.DISCOUNT_AMOUNT = S.DISCOUNT_AMOUNT) or (T.DISCOUNT_AMOUNT IS NULL and S.DISCOUNT_AMOUNT IS NULL)) and
		((T.DISCOUNTED_ITEM_IND = S.DISCOUNTED_ITEM_IND) or (T.DISCOUNTED_ITEM_IND IS NULL and S.DISCOUNTED_ITEM_IND IS NULL)) and
		((T.PRICE = S.PRICE) or (T.PRICE IS NULL and S.PRICE IS NULL)) and
		((T.QUANTITY = S.QUANTITY) or (T.QUANTITY IS NULL and S.QUANTITY IS NULL)) and
		((T.SEQUENCE = S.SEQUENCE) or (T.SEQUENCE IS NULL and S.SEQUENCE IS NULL)) and
		((T.TAX_TOTAL_EFFECTIVE_RATE = S.TAX_TOTAL_EFFECTIVE_RATE) or (T.TAX_TOTAL_EFFECTIVE_RATE IS NULL and S.TAX_TOTAL_EFFECTIVE_RATE IS NULL)) and
		((T.TAX_AMOUNT = S.TAX_AMOUNT) or (T.TAX_AMOUNT IS NULL and S.TAX_AMOUNT IS NULL)) and
		((T.TAX_AS_OF_DATE = S.TAX_AS_OF_DATE) or (T.TAX_AS_OF_DATE IS NULL and S.TAX_AS_OF_DATE IS NULL)) and
		((T.CUSTOMER_ORDER_ID = S.CUSTOMER_ORDER_ID) or (T.CUSTOMER_ORDER_ID IS NULL and S.CUSTOMER_ORDER_ID IS NULL)) and
		((T.ITEM_NUMBER = S.ITEM_NUMBER) or (T.ITEM_NUMBER IS NULL and S.ITEM_NUMBER IS NULL)) and
		((T.NAME = S.NAME) or (T.NAME IS NULL and S.NAME IS NULL)) and
		((T.DELETED_IND = S.DELETED_IND) or (T.DELETED_IND IS NULL and S.DELETED_IND IS NULL))
        )

  
  

  



&


/*-----------------------------------------------*/
/* TASK No. 13 */
/* Analyze integration table */



begin
    dbms_stats.gather_table_stats(
	ownname => 'RAX_APP_USER',
	tabname => 'I$_SAS_CUST_ORD_LN_STG1385001',
	estimate_percent => dbms_stats.auto_sample_size
    );
end;



&


/*-----------------------------------------------*/
/* TASK No. 14 */
/* Create Index on flow table */

-- create index	RAX_APP_USER.I$_SAS_CUST_ORD_LN_STG_IDX1385001
-- on		RAX_APP_USER.I$_SAS_CUST_ORD_LN_STG1385001 (CUSTOMER_ORDER_LINE_ID)
-- NOLOGGING

BEGIN
  EXECUTE IMMEDIATE 'create index RAX_APP_USER.I$_SAS_CUST_ORD_LN_STG_IDX1385001
on   RAX_APP_USER.I$_SAS_CUST_ORD_LN_STG1385001 (CUSTOMER_ORDER_LINE_ID)';
EXCEPTION
  WHEN OTHERS THEN
   -- Handle the case where the identifier is too long (ORA-00972)
   IF SQLCODE = -972 or  SQLCODE = -1408 or SQLCODE = -955  THEN
     DBMS_OUTPUT.PUT_LINE('Identifier is too long. Skipping creation of index.');
   ELSE
     RAISE;
   END IF;
END;


&


/*-----------------------------------------------*/
/* TASK No. 15 */
/* create check table */

BEGIN
  EXECUTE IMMEDIATE 'drop table RAX_APP_USER.SNP_CHECK_TAB';
EXCEPTION
  WHEN OTHERS THEN
   IF SQLCODE != -942 THEN
     RAISE;
   END IF;
END;


&

-- create table RAX_APP_USER.SNP_CHECK_TAB
-- (
-- 	CATALOG_NAME	VARCHAR2(100 CHAR) NULL ,
-- 	SCHEMA_NAME	VARCHAR2(100 CHAR) NULL ,
-- 	RESOURCE_NAME	VARCHAR2(100 CHAR) NULL,
-- 	FULL_RES_NAME	VARCHAR2(100 CHAR) NULL,
-- 	ERR_TYPE		VARCHAR2(1 CHAR) NULL,
-- 	ERR_MESS		VARCHAR2(250 CHAR) NULL ,
-- 	CHECK_DATE	DATE NULL,
-- 	ORIGIN		VARCHAR2(100 CHAR) NULL,
-- 	CONS_NAME	VARCHAR2(35 CHAR) NULL,
-- 	CONS_TYPE		VARCHAR2(2 CHAR) NULL,
-- 	ERR_COUNT		NUMBER(10) NULL
-- )


BEGIN
   EXECUTE IMMEDIATE '
      create table RAX_APP_USER.SNP_CHECK_TAB
		(
			CATALOG_NAME	VARCHAR2(100 CHAR) NULL ,
			SCHEMA_NAME	VARCHAR2(100 CHAR) NULL ,
			RESOURCE_NAME	VARCHAR2(100 CHAR) NULL,
			FULL_RES_NAME	VARCHAR2(100 CHAR) NULL,
			ERR_TYPE		VARCHAR2(1 CHAR) NULL,
			ERR_MESS		VARCHAR2(250 CHAR) NULL ,
			CHECK_DATE	DATE NULL,
			ORIGIN		VARCHAR2(100 CHAR) NULL,
			CONS_NAME	VARCHAR2(35 CHAR) NULL,
			CONS_TYPE		VARCHAR2(2 CHAR) NULL,
			ERR_COUNT		NUMBER(10) NULL
		)
   ';
END;


&


/*-----------------------------------------------*/
/* TASK No. 16 */
/* delete previous check sum */

delete from	RAX_APP_USER.SNP_CHECK_TAB
where	SCHEMA_NAME	= 'ODS_STAGE'
and	ORIGIN 		= '(1385001)ODS_Project.LOAD_SAS_CUSTOMER_ORDER_LINE_STG_INT'
and	ERR_TYPE 		= 'F'


&


/*-----------------------------------------------*/
/* TASK No. 17 */
/* create error table */

BEGIN
  EXECUTE IMMEDIATE 'drop table RAX_APP_USER.E$_SAS_CUST_ORD_LN_STG1385001';
EXCEPTION
  WHEN OTHERS THEN
   IF SQLCODE != -942 THEN
     RAISE;
   END IF;
END;


&

create table RAX_APP_USER.E$_SAS_CUST_ORD_LN_STG1385001
(
	ODI_ROW_ID 		UROWID,
	ODI_ERR_TYPE		VARCHAR2(1 CHAR) NULL, 
	ODI_ERR_MESS		VARCHAR2(250 CHAR) NULL,
	ODI_CHECK_DATE	DATE NULL, 
	LINE_TYPE	VARCHAR2(1) NULL,
	CUSTOMER_ORDER_LINE_ID	NUMBER(10) NULL,
	AUDIT_CREATE_DATE	TIMESTAMP(6) NULL,
	AUDIT_CREATED_BY	VARCHAR2(255) NULL,
	AUDIT_MODIFIED_BY	VARCHAR2(255) NULL,
	AUDIT_MODIFY_DATE	TIMESTAMP(6) NULL,
	DISCOUNT_AMOUNT	NUMBER(19,2) NULL,
	DISCOUNTED_ITEM_IND	NUMBER(1) NULL,
	PRICE	NUMBER(19,2) NULL,
	QUANTITY	NUMBER(10) NULL,
	SEQUENCE	NUMBER(10) NULL,
	TAX_TOTAL_EFFECTIVE_RATE	NUMBER(10,10) NULL,
	TAX_AMOUNT	NUMBER(19,2) NULL,
	TAX_AS_OF_DATE	VARCHAR2(255) NULL,
	CUSTOMER_ORDER_ID	NUMBER(10) NULL,
	ITEM_NUMBER	VARCHAR2(16) NULL,
	NAME	VARCHAR2(255) NULL,
	ODS_CREATE_DATE	DATE NULL,
	ODS_MODIFY_DATE	DATE NULL,
	DELETED_IND	VARCHAR2(1) NULL,
	ODI_ORIGIN		VARCHAR2(100 CHAR) NULL,
	ODI_CONS_NAME	VARCHAR2(35 CHAR) NULL,
	ODI_CONS_TYPE		VARCHAR2(2 CHAR) NULL,
	ODI_PK			VARCHAR2(32 CHAR) PRIMARY KEY,
	ODI_SESS_NO		VARCHAR2(19 CHAR)
)



&


/*-----------------------------------------------*/
/* TASK No. 18 */
/* delete previous errors */

delete from 	RAX_APP_USER.E$_SAS_CUST_ORD_LN_STG1385001
where	(ODI_ERR_TYPE = 'S'	and 'F' = 'S')
or	(ODI_ERR_TYPE = 'F'	and ODI_ORIGIN = '(1385001)ODS_Project.LOAD_SAS_CUSTOMER_ORDER_LINE_STG_INT')


&


/*-----------------------------------------------*/
/* TASK No. 19 */
/* Create index on PK */

 
/* FLOW CONTROL CREATE THE iNDEX ON THE I$TABLE */
-- create index 	RAX_APP_USER.I$_SAS_CUST_ORD_LN_STG1385001
-- on	RAX_APP_USER.I$_SAS_CUST_ORD_LN_STG1385001 (CUSTOMER_ORDER_LINE_ID)

BEGIN
  EXECUTE IMMEDIATE 'create index RAX_APP_USER.I$_SAS_CUST_ORD_LN_STG1385001
on   RAX_APP_USER.I$_SAS_CUST_ORD_LN_STG1385001 (CUSTOMER_ORDER_LINE_ID)';
EXCEPTION
  WHEN OTHERS THEN
   -- Handle the case where the identifier is too long (ORA-00972)
   IF SQLCODE = -972 or  SQLCODE = -1408 or SQLCODE = -955  THEN
     DBMS_OUTPUT.PUT_LINE('Identifier is too long. Skipping creation of index.');
   ELSE
     RAISE;
   END IF;
END;


&


/*-----------------------------------------------*/
/* TASK No. 20 */
/* insert PK errors */

DECLARE
               CheckTable                             VarChar2(60);
               TargetTable                            VarChar2(60);
               VariableCheckTable                     VarChar2(60);

BEGIN
               SELECT 'RAX_APP_USER.I$_SAS_CUST_ORD_LN_STG' INTO CheckTable FROM DUAL;
               SELECT 'ODS_STAGE.SAS_CUSTOMER_ORDER_LINE_STG' INTO TargetTable FROM DUAL;

IF CheckTable = TargetTable THEN
   VariableCheckTable := CheckTable; 
ELSE
   VariableCheckTable := CheckTable || '1385001';
END IF;

execute immediate '
insert into RAX_APP_USER.E$_SAS_CUST_ORD_LN_STG1385001
(
	ODI_PK,
	ODI_SESS_NO,
	ODI_ROW_ID,
	ODI_ERR_TYPE,
	ODI_ERR_MESS,
	ODI_ORIGIN,
	ODI_CHECK_DATE,
	ODI_CONS_NAME,
	ODI_CONS_TYPE,
	LINE_TYPE,
	CUSTOMER_ORDER_LINE_ID,
	AUDIT_CREATE_DATE,
	AUDIT_CREATED_BY,
	AUDIT_MODIFIED_BY,
	AUDIT_MODIFY_DATE,
	DISCOUNT_AMOUNT,
	DISCOUNTED_ITEM_IND,
	PRICE,
	QUANTITY,
	SEQUENCE,
	TAX_TOTAL_EFFECTIVE_RATE,
	TAX_AMOUNT,
	TAX_AS_OF_DATE,
	CUSTOMER_ORDER_ID,
	ITEM_NUMBER,
	NAME,
	ODS_CREATE_DATE,
	ODS_MODIFY_DATE,
	DELETED_IND
)
select	SYS_GUID(),
	:v_sess_no, 
	rowid,
	''F'', 
	''ODI-15064: The primary key CUSTOMER_ORDER_LINE_PK is not unique.'',
	''(1385001)ODS_Project.LOAD_SAS_CUSTOMER_ORDER_LINE_STG_INT'',
	sysdate,
	''CUSTOMER_ORDER_LINE_PK'',
	''PK'',	
	SAS_CUST_ORD_LN_STG.LINE_TYPE,
	SAS_CUST_ORD_LN_STG.CUSTOMER_ORDER_LINE_ID,
	SAS_CUST_ORD_LN_STG.AUDIT_CREATE_DATE,
	SAS_CUST_ORD_LN_STG.AUDIT_CREATED_BY,
	SAS_CUST_ORD_LN_STG.AUDIT_MODIFIED_BY,
	SAS_CUST_ORD_LN_STG.AUDIT_MODIFY_DATE,
	SAS_CUST_ORD_LN_STG.DISCOUNT_AMOUNT,
	SAS_CUST_ORD_LN_STG.DISCOUNTED_ITEM_IND,
	SAS_CUST_ORD_LN_STG.PRICE,
	SAS_CUST_ORD_LN_STG.QUANTITY,
	SAS_CUST_ORD_LN_STG.SEQUENCE,
	SAS_CUST_ORD_LN_STG.TAX_TOTAL_EFFECTIVE_RATE,
	SAS_CUST_ORD_LN_STG.TAX_AMOUNT,
	SAS_CUST_ORD_LN_STG.TAX_AS_OF_DATE,
	SAS_CUST_ORD_LN_STG.CUSTOMER_ORDER_ID,
	SAS_CUST_ORD_LN_STG.ITEM_NUMBER,
	SAS_CUST_ORD_LN_STG.NAME,
	SAS_CUST_ORD_LN_STG.ODS_CREATE_DATE,
	SAS_CUST_ORD_LN_STG.ODS_MODIFY_DATE,
	SAS_CUST_ORD_LN_STG.DELETED_IND
from	'
 || VariableCheckTable || 
' SAS_CUST_ORD_LN_STG 
where	exists  (
		select	SUB1.CUSTOMER_ORDER_LINE_ID
		from 	' 
|| VariableCheckTable ||
'  SUB1
		where 	SUB1.CUSTOMER_ORDER_LINE_ID=SAS_CUST_ORD_LN_STG.CUSTOMER_ORDER_LINE_ID
		group by 	SUB1.CUSTOMER_ORDER_LINE_ID
		having 	count(1) > 1
		)
';

END;


&


/*-----------------------------------------------*/
/* TASK No. 21 */
/* Create index on AK */

 
/* FLOW CONTROL CREATE THE iNDEX ON THE I$TABLE */
-- create index 	SAS_CUSTOMER_ORDER_LINE_PK_flow
-- on	RAX_APP_USER.I$_SAS_CUST_ORD_LN_STG1385001 
-- 	(CUSTOMER_ORDER_LINE_ID)

BEGIN
  EXECUTE IMMEDIATE 'create index SAS_CUSTOMER_ORDER_LINE_PK_flow
on   RAX_APP_USER.I$_SAS_CUST_ORD_LN_STG1385001 (CUSTOMER_ORDER_LINE_ID)';
EXCEPTION
  WHEN OTHERS THEN
   -- Handle the case where the identifier is too long (ORA-00972)
   IF SQLCODE = -972 or  SQLCODE = -1408 or SQLCODE = -955  THEN
     DBMS_OUTPUT.PUT_LINE('Identifier is too long. Skipping creation of index.');
   ELSE
     RAISE;
   END IF;
END;


&


/*-----------------------------------------------*/
/* TASK No. 22 */
/* insert AK errors */

DECLARE
               CheckTable                             VarChar2(60);
               TargetTable                            VarChar2(60);
               VariableCheckTable                VarChar2(60);

BEGIN
               SELECT 'RAX_APP_USER.I$_SAS_CUST_ORD_LN_STG' INTO CheckTable FROM DUAL;
               SELECT 'ODS_STAGE.SAS_CUSTOMER_ORDER_LINE_STG' INTO TargetTable FROM DUAL;

IF CheckTable = TargetTable THEN
   VariableCheckTable := CheckTable; 
ELSE
   VariableCheckTable := CheckTable || '1385001';
END IF;

execute immediate '
insert into RAX_APP_USER.E$_SAS_CUST_ORD_LN_STG1385001
(
	ODI_PK,
	ODI_SESS_NO,
	ODI_ROW_ID,
	ODI_ERR_TYPE,
	ODI_ERR_MESS,
	ODI_ORIGIN,
	ODI_CHECK_DATE,
	ODI_CONS_NAME,
	ODI_CONS_TYPE,
	LINE_TYPE,
	CUSTOMER_ORDER_LINE_ID,
	AUDIT_CREATE_DATE,
	AUDIT_CREATED_BY,
	AUDIT_MODIFIED_BY,
	AUDIT_MODIFY_DATE,
	DISCOUNT_AMOUNT,
	DISCOUNTED_ITEM_IND,
	PRICE,
	QUANTITY,
	SEQUENCE,
	TAX_TOTAL_EFFECTIVE_RATE,
	TAX_AMOUNT,
	TAX_AS_OF_DATE,
	CUSTOMER_ORDER_ID,
	ITEM_NUMBER,
	NAME,
	ODS_CREATE_DATE,
	ODS_MODIFY_DATE,
	DELETED_IND
)
select	SYS_GUID(),
	:v_sess_no, 
	rowid,
	''F'', 
	''ODI-15063: The alternate key SAS_CUSTOMER_ORDER_LINE_PK is not unique.'',
	''(1385001)ODS_Project.LOAD_SAS_CUSTOMER_ORDER_LINE_STG_INT'',
	sysdate,
	''SAS_CUSTOMER_ORDER_LINE_PK'',
	''AK'',	
	SAS_CUST_ORD_LN_STG.LINE_TYPE,
	SAS_CUST_ORD_LN_STG.CUSTOMER_ORDER_LINE_ID,
	SAS_CUST_ORD_LN_STG.AUDIT_CREATE_DATE,
	SAS_CUST_ORD_LN_STG.AUDIT_CREATED_BY,
	SAS_CUST_ORD_LN_STG.AUDIT_MODIFIED_BY,
	SAS_CUST_ORD_LN_STG.AUDIT_MODIFY_DATE,
	SAS_CUST_ORD_LN_STG.DISCOUNT_AMOUNT,
	SAS_CUST_ORD_LN_STG.DISCOUNTED_ITEM_IND,
	SAS_CUST_ORD_LN_STG.PRICE,
	SAS_CUST_ORD_LN_STG.QUANTITY,
	SAS_CUST_ORD_LN_STG.SEQUENCE,
	SAS_CUST_ORD_LN_STG.TAX_TOTAL_EFFECTIVE_RATE,
	SAS_CUST_ORD_LN_STG.TAX_AMOUNT,
	SAS_CUST_ORD_LN_STG.TAX_AS_OF_DATE,
	SAS_CUST_ORD_LN_STG.CUSTOMER_ORDER_ID,
	SAS_CUST_ORD_LN_STG.ITEM_NUMBER,
	SAS_CUST_ORD_LN_STG.NAME,
	SAS_CUST_ORD_LN_STG.ODS_CREATE_DATE,
	SAS_CUST_ORD_LN_STG.ODS_MODIFY_DATE,
	SAS_CUST_ORD_LN_STG.DELETED_IND
from              '	
 || VariableCheckTable || 
' SAS_CUST_ORD_LN_STG
where	exists  (
		select	SUB.CUSTOMER_ORDER_LINE_ID
		from 	'
 || VariableCheckTable || 
' SUB
		where 	SUB.CUSTOMER_ORDER_LINE_ID=SAS_CUST_ORD_LN_STG.CUSTOMER_ORDER_LINE_ID
		group by 	SUB.CUSTOMER_ORDER_LINE_ID
		having 	count(1) > 1
		)
 ';

END;

/*  Checked Datastore =RAX_APP_USER.I$_SAS_CUST_ORD_LN_STG  */
/*  Integration Datastore =RAX_APP_USER.I$_SAS_CUST_ORD_LN_STG   */
/*  Target Datastore =ODS_STAGE.SAS_CUSTOMER_ORDER_LINE_STG */



&


/*-----------------------------------------------*/
/* TASK No. 23 */
/* insert Not Null errors */

insert into RAX_APP_USER.E$_SAS_CUST_ORD_LN_STG1385001
(
	ODI_PK,
	ODI_SESS_NO,
	ODI_ROW_ID,
	ODI_ERR_TYPE,
	ODI_ERR_MESS,
	ODI_CHECK_DATE,
	ODI_ORIGIN,
	ODI_CONS_NAME,
	ODI_CONS_TYPE,
	LINE_TYPE,
	CUSTOMER_ORDER_LINE_ID,
	AUDIT_CREATE_DATE,
	AUDIT_CREATED_BY,
	AUDIT_MODIFIED_BY,
	AUDIT_MODIFY_DATE,
	DISCOUNT_AMOUNT,
	DISCOUNTED_ITEM_IND,
	PRICE,
	QUANTITY,
	SEQUENCE,
	TAX_TOTAL_EFFECTIVE_RATE,
	TAX_AMOUNT,
	TAX_AS_OF_DATE,
	CUSTOMER_ORDER_ID,
	ITEM_NUMBER,
	NAME,
	ODS_CREATE_DATE,
	ODS_MODIFY_DATE,
	DELETED_IND
)
select
	SYS_GUID(),
	:v_sess_no, 
	rowid,
	'F', 
	'ODI-15066: The column LINE_TYPE cannot be null.',
	sysdate,
	'(1385001)ODS_Project.LOAD_SAS_CUSTOMER_ORDER_LINE_STG_INT',
	'LINE_TYPE',
	'NN',	
	LINE_TYPE,
	CUSTOMER_ORDER_LINE_ID,
	AUDIT_CREATE_DATE,
	AUDIT_CREATED_BY,
	AUDIT_MODIFIED_BY,
	AUDIT_MODIFY_DATE,
	DISCOUNT_AMOUNT,
	DISCOUNTED_ITEM_IND,
	PRICE,
	QUANTITY,
	SEQUENCE,
	TAX_TOTAL_EFFECTIVE_RATE,
	TAX_AMOUNT,
	TAX_AS_OF_DATE,
	CUSTOMER_ORDER_ID,
	ITEM_NUMBER,
	NAME,
	ODS_CREATE_DATE,
	ODS_MODIFY_DATE,
	DELETED_IND
from	RAX_APP_USER.I$_SAS_CUST_ORD_LN_STG1385001
where	LINE_TYPE is null



&


/*-----------------------------------------------*/
/* TASK No. 24 */
/* insert Not Null errors */

insert into RAX_APP_USER.E$_SAS_CUST_ORD_LN_STG1385001
(
	ODI_PK,
	ODI_SESS_NO,
	ODI_ROW_ID,
	ODI_ERR_TYPE,
	ODI_ERR_MESS,
	ODI_CHECK_DATE,
	ODI_ORIGIN,
	ODI_CONS_NAME,
	ODI_CONS_TYPE,
	LINE_TYPE,
	CUSTOMER_ORDER_LINE_ID,
	AUDIT_CREATE_DATE,
	AUDIT_CREATED_BY,
	AUDIT_MODIFIED_BY,
	AUDIT_MODIFY_DATE,
	DISCOUNT_AMOUNT,
	DISCOUNTED_ITEM_IND,
	PRICE,
	QUANTITY,
	SEQUENCE,
	TAX_TOTAL_EFFECTIVE_RATE,
	TAX_AMOUNT,
	TAX_AS_OF_DATE,
	CUSTOMER_ORDER_ID,
	ITEM_NUMBER,
	NAME,
	ODS_CREATE_DATE,
	ODS_MODIFY_DATE,
	DELETED_IND
)
select
	SYS_GUID(),
	:v_sess_no, 
	rowid,
	'F', 
	'ODI-15066: The column CUSTOMER_ORDER_LINE_ID cannot be null.',
	sysdate,
	'(1385001)ODS_Project.LOAD_SAS_CUSTOMER_ORDER_LINE_STG_INT',
	'CUSTOMER_ORDER_LINE_ID',
	'NN',	
	LINE_TYPE,
	CUSTOMER_ORDER_LINE_ID,
	AUDIT_CREATE_DATE,
	AUDIT_CREATED_BY,
	AUDIT_MODIFIED_BY,
	AUDIT_MODIFY_DATE,
	DISCOUNT_AMOUNT,
	DISCOUNTED_ITEM_IND,
	PRICE,
	QUANTITY,
	SEQUENCE,
	TAX_TOTAL_EFFECTIVE_RATE,
	TAX_AMOUNT,
	TAX_AS_OF_DATE,
	CUSTOMER_ORDER_ID,
	ITEM_NUMBER,
	NAME,
	ODS_CREATE_DATE,
	ODS_MODIFY_DATE,
	DELETED_IND
from	RAX_APP_USER.I$_SAS_CUST_ORD_LN_STG1385001
where	CUSTOMER_ORDER_LINE_ID is null



&


/*-----------------------------------------------*/
/* TASK No. 25 */
/* insert Not Null errors */

insert into RAX_APP_USER.E$_SAS_CUST_ORD_LN_STG1385001
(
	ODI_PK,
	ODI_SESS_NO,
	ODI_ROW_ID,
	ODI_ERR_TYPE,
	ODI_ERR_MESS,
	ODI_CHECK_DATE,
	ODI_ORIGIN,
	ODI_CONS_NAME,
	ODI_CONS_TYPE,
	LINE_TYPE,
	CUSTOMER_ORDER_LINE_ID,
	AUDIT_CREATE_DATE,
	AUDIT_CREATED_BY,
	AUDIT_MODIFIED_BY,
	AUDIT_MODIFY_DATE,
	DISCOUNT_AMOUNT,
	DISCOUNTED_ITEM_IND,
	PRICE,
	QUANTITY,
	SEQUENCE,
	TAX_TOTAL_EFFECTIVE_RATE,
	TAX_AMOUNT,
	TAX_AS_OF_DATE,
	CUSTOMER_ORDER_ID,
	ITEM_NUMBER,
	NAME,
	ODS_CREATE_DATE,
	ODS_MODIFY_DATE,
	DELETED_IND
)
select
	SYS_GUID(),
	:v_sess_no, 
	rowid,
	'F', 
	'ODI-15066: The column AUDIT_CREATE_DATE cannot be null.',
	sysdate,
	'(1385001)ODS_Project.LOAD_SAS_CUSTOMER_ORDER_LINE_STG_INT',
	'AUDIT_CREATE_DATE',
	'NN',	
	LINE_TYPE,
	CUSTOMER_ORDER_LINE_ID,
	AUDIT_CREATE_DATE,
	AUDIT_CREATED_BY,
	AUDIT_MODIFIED_BY,
	AUDIT_MODIFY_DATE,
	DISCOUNT_AMOUNT,
	DISCOUNTED_ITEM_IND,
	PRICE,
	QUANTITY,
	SEQUENCE,
	TAX_TOTAL_EFFECTIVE_RATE,
	TAX_AMOUNT,
	TAX_AS_OF_DATE,
	CUSTOMER_ORDER_ID,
	ITEM_NUMBER,
	NAME,
	ODS_CREATE_DATE,
	ODS_MODIFY_DATE,
	DELETED_IND
from	RAX_APP_USER.I$_SAS_CUST_ORD_LN_STG1385001
where	AUDIT_CREATE_DATE is null



&


/*-----------------------------------------------*/
/* TASK No. 26 */
/* insert Not Null errors */

insert into RAX_APP_USER.E$_SAS_CUST_ORD_LN_STG1385001
(
	ODI_PK,
	ODI_SESS_NO,
	ODI_ROW_ID,
	ODI_ERR_TYPE,
	ODI_ERR_MESS,
	ODI_CHECK_DATE,
	ODI_ORIGIN,
	ODI_CONS_NAME,
	ODI_CONS_TYPE,
	LINE_TYPE,
	CUSTOMER_ORDER_LINE_ID,
	AUDIT_CREATE_DATE,
	AUDIT_CREATED_BY,
	AUDIT_MODIFIED_BY,
	AUDIT_MODIFY_DATE,
	DISCOUNT_AMOUNT,
	DISCOUNTED_ITEM_IND,
	PRICE,
	QUANTITY,
	SEQUENCE,
	TAX_TOTAL_EFFECTIVE_RATE,
	TAX_AMOUNT,
	TAX_AS_OF_DATE,
	CUSTOMER_ORDER_ID,
	ITEM_NUMBER,
	NAME,
	ODS_CREATE_DATE,
	ODS_MODIFY_DATE,
	DELETED_IND
)
select
	SYS_GUID(),
	:v_sess_no, 
	rowid,
	'F', 
	'ODI-15066: The column AUDIT_CREATED_BY cannot be null.',
	sysdate,
	'(1385001)ODS_Project.LOAD_SAS_CUSTOMER_ORDER_LINE_STG_INT',
	'AUDIT_CREATED_BY',
	'NN',	
	LINE_TYPE,
	CUSTOMER_ORDER_LINE_ID,
	AUDIT_CREATE_DATE,
	AUDIT_CREATED_BY,
	AUDIT_MODIFIED_BY,
	AUDIT_MODIFY_DATE,
	DISCOUNT_AMOUNT,
	DISCOUNTED_ITEM_IND,
	PRICE,
	QUANTITY,
	SEQUENCE,
	TAX_TOTAL_EFFECTIVE_RATE,
	TAX_AMOUNT,
	TAX_AS_OF_DATE,
	CUSTOMER_ORDER_ID,
	ITEM_NUMBER,
	NAME,
	ODS_CREATE_DATE,
	ODS_MODIFY_DATE,
	DELETED_IND
from	RAX_APP_USER.I$_SAS_CUST_ORD_LN_STG1385001
where	AUDIT_CREATED_BY is null



&


/*-----------------------------------------------*/
/* TASK No. 27 */
/* insert Not Null errors */

insert into RAX_APP_USER.E$_SAS_CUST_ORD_LN_STG1385001
(
	ODI_PK,
	ODI_SESS_NO,
	ODI_ROW_ID,
	ODI_ERR_TYPE,
	ODI_ERR_MESS,
	ODI_CHECK_DATE,
	ODI_ORIGIN,
	ODI_CONS_NAME,
	ODI_CONS_TYPE,
	LINE_TYPE,
	CUSTOMER_ORDER_LINE_ID,
	AUDIT_CREATE_DATE,
	AUDIT_CREATED_BY,
	AUDIT_MODIFIED_BY,
	AUDIT_MODIFY_DATE,
	DISCOUNT_AMOUNT,
	DISCOUNTED_ITEM_IND,
	PRICE,
	QUANTITY,
	SEQUENCE,
	TAX_TOTAL_EFFECTIVE_RATE,
	TAX_AMOUNT,
	TAX_AS_OF_DATE,
	CUSTOMER_ORDER_ID,
	ITEM_NUMBER,
	NAME,
	ODS_CREATE_DATE,
	ODS_MODIFY_DATE,
	DELETED_IND
)
select
	SYS_GUID(),
	:v_sess_no, 
	rowid,
	'F', 
	'ODI-15066: The column AUDIT_MODIFIED_BY cannot be null.',
	sysdate,
	'(1385001)ODS_Project.LOAD_SAS_CUSTOMER_ORDER_LINE_STG_INT',
	'AUDIT_MODIFIED_BY',
	'NN',	
	LINE_TYPE,
	CUSTOMER_ORDER_LINE_ID,
	AUDIT_CREATE_DATE,
	AUDIT_CREATED_BY,
	AUDIT_MODIFIED_BY,
	AUDIT_MODIFY_DATE,
	DISCOUNT_AMOUNT,
	DISCOUNTED_ITEM_IND,
	PRICE,
	QUANTITY,
	SEQUENCE,
	TAX_TOTAL_EFFECTIVE_RATE,
	TAX_AMOUNT,
	TAX_AS_OF_DATE,
	CUSTOMER_ORDER_ID,
	ITEM_NUMBER,
	NAME,
	ODS_CREATE_DATE,
	ODS_MODIFY_DATE,
	DELETED_IND
from	RAX_APP_USER.I$_SAS_CUST_ORD_LN_STG1385001
where	AUDIT_MODIFIED_BY is null



&


/*-----------------------------------------------*/
/* TASK No. 28 */
/* insert Not Null errors */

insert into RAX_APP_USER.E$_SAS_CUST_ORD_LN_STG1385001
(
	ODI_PK,
	ODI_SESS_NO,
	ODI_ROW_ID,
	ODI_ERR_TYPE,
	ODI_ERR_MESS,
	ODI_CHECK_DATE,
	ODI_ORIGIN,
	ODI_CONS_NAME,
	ODI_CONS_TYPE,
	LINE_TYPE,
	CUSTOMER_ORDER_LINE_ID,
	AUDIT_CREATE_DATE,
	AUDIT_CREATED_BY,
	AUDIT_MODIFIED_BY,
	AUDIT_MODIFY_DATE,
	DISCOUNT_AMOUNT,
	DISCOUNTED_ITEM_IND,
	PRICE,
	QUANTITY,
	SEQUENCE,
	TAX_TOTAL_EFFECTIVE_RATE,
	TAX_AMOUNT,
	TAX_AS_OF_DATE,
	CUSTOMER_ORDER_ID,
	ITEM_NUMBER,
	NAME,
	ODS_CREATE_DATE,
	ODS_MODIFY_DATE,
	DELETED_IND
)
select
	SYS_GUID(),
	:v_sess_no, 
	rowid,
	'F', 
	'ODI-15066: The column AUDIT_MODIFY_DATE cannot be null.',
	sysdate,
	'(1385001)ODS_Project.LOAD_SAS_CUSTOMER_ORDER_LINE_STG_INT',
	'AUDIT_MODIFY_DATE',
	'NN',	
	LINE_TYPE,
	CUSTOMER_ORDER_LINE_ID,
	AUDIT_CREATE_DATE,
	AUDIT_CREATED_BY,
	AUDIT_MODIFIED_BY,
	AUDIT_MODIFY_DATE,
	DISCOUNT_AMOUNT,
	DISCOUNTED_ITEM_IND,
	PRICE,
	QUANTITY,
	SEQUENCE,
	TAX_TOTAL_EFFECTIVE_RATE,
	TAX_AMOUNT,
	TAX_AS_OF_DATE,
	CUSTOMER_ORDER_ID,
	ITEM_NUMBER,
	NAME,
	ODS_CREATE_DATE,
	ODS_MODIFY_DATE,
	DELETED_IND
from	RAX_APP_USER.I$_SAS_CUST_ORD_LN_STG1385001
where	AUDIT_MODIFY_DATE is null



&


/*-----------------------------------------------*/
/* TASK No. 29 */
/* insert Not Null errors */

insert into RAX_APP_USER.E$_SAS_CUST_ORD_LN_STG1385001
(
	ODI_PK,
	ODI_SESS_NO,
	ODI_ROW_ID,
	ODI_ERR_TYPE,
	ODI_ERR_MESS,
	ODI_CHECK_DATE,
	ODI_ORIGIN,
	ODI_CONS_NAME,
	ODI_CONS_TYPE,
	LINE_TYPE,
	CUSTOMER_ORDER_LINE_ID,
	AUDIT_CREATE_DATE,
	AUDIT_CREATED_BY,
	AUDIT_MODIFIED_BY,
	AUDIT_MODIFY_DATE,
	DISCOUNT_AMOUNT,
	DISCOUNTED_ITEM_IND,
	PRICE,
	QUANTITY,
	SEQUENCE,
	TAX_TOTAL_EFFECTIVE_RATE,
	TAX_AMOUNT,
	TAX_AS_OF_DATE,
	CUSTOMER_ORDER_ID,
	ITEM_NUMBER,
	NAME,
	ODS_CREATE_DATE,
	ODS_MODIFY_DATE,
	DELETED_IND
)
select
	SYS_GUID(),
	:v_sess_no, 
	rowid,
	'F', 
	'ODI-15066: The column PRICE cannot be null.',
	sysdate,
	'(1385001)ODS_Project.LOAD_SAS_CUSTOMER_ORDER_LINE_STG_INT',
	'PRICE',
	'NN',	
	LINE_TYPE,
	CUSTOMER_ORDER_LINE_ID,
	AUDIT_CREATE_DATE,
	AUDIT_CREATED_BY,
	AUDIT_MODIFIED_BY,
	AUDIT_MODIFY_DATE,
	DISCOUNT_AMOUNT,
	DISCOUNTED_ITEM_IND,
	PRICE,
	QUANTITY,
	SEQUENCE,
	TAX_TOTAL_EFFECTIVE_RATE,
	TAX_AMOUNT,
	TAX_AS_OF_DATE,
	CUSTOMER_ORDER_ID,
	ITEM_NUMBER,
	NAME,
	ODS_CREATE_DATE,
	ODS_MODIFY_DATE,
	DELETED_IND
from	RAX_APP_USER.I$_SAS_CUST_ORD_LN_STG1385001
where	PRICE is null



&


/*-----------------------------------------------*/
/* TASK No. 30 */
/* insert Not Null errors */

insert into RAX_APP_USER.E$_SAS_CUST_ORD_LN_STG1385001
(
	ODI_PK,
	ODI_SESS_NO,
	ODI_ROW_ID,
	ODI_ERR_TYPE,
	ODI_ERR_MESS,
	ODI_CHECK_DATE,
	ODI_ORIGIN,
	ODI_CONS_NAME,
	ODI_CONS_TYPE,
	LINE_TYPE,
	CUSTOMER_ORDER_LINE_ID,
	AUDIT_CREATE_DATE,
	AUDIT_CREATED_BY,
	AUDIT_MODIFIED_BY,
	AUDIT_MODIFY_DATE,
	DISCOUNT_AMOUNT,
	DISCOUNTED_ITEM_IND,
	PRICE,
	QUANTITY,
	SEQUENCE,
	TAX_TOTAL_EFFECTIVE_RATE,
	TAX_AMOUNT,
	TAX_AS_OF_DATE,
	CUSTOMER_ORDER_ID,
	ITEM_NUMBER,
	NAME,
	ODS_CREATE_DATE,
	ODS_MODIFY_DATE,
	DELETED_IND
)
select
	SYS_GUID(),
	:v_sess_no, 
	rowid,
	'F', 
	'ODI-15066: The column QUANTITY cannot be null.',
	sysdate,
	'(1385001)ODS_Project.LOAD_SAS_CUSTOMER_ORDER_LINE_STG_INT',
	'QUANTITY',
	'NN',	
	LINE_TYPE,
	CUSTOMER_ORDER_LINE_ID,
	AUDIT_CREATE_DATE,
	AUDIT_CREATED_BY,
	AUDIT_MODIFIED_BY,
	AUDIT_MODIFY_DATE,
	DISCOUNT_AMOUNT,
	DISCOUNTED_ITEM_IND,
	PRICE,
	QUANTITY,
	SEQUENCE,
	TAX_TOTAL_EFFECTIVE_RATE,
	TAX_AMOUNT,
	TAX_AS_OF_DATE,
	CUSTOMER_ORDER_ID,
	ITEM_NUMBER,
	NAME,
	ODS_CREATE_DATE,
	ODS_MODIFY_DATE,
	DELETED_IND
from	RAX_APP_USER.I$_SAS_CUST_ORD_LN_STG1385001
where	QUANTITY is null



&


/*-----------------------------------------------*/
/* TASK No. 31 */
/* insert Not Null errors */

insert into RAX_APP_USER.E$_SAS_CUST_ORD_LN_STG1385001
(
	ODI_PK,
	ODI_SESS_NO,
	ODI_ROW_ID,
	ODI_ERR_TYPE,
	ODI_ERR_MESS,
	ODI_CHECK_DATE,
	ODI_ORIGIN,
	ODI_CONS_NAME,
	ODI_CONS_TYPE,
	LINE_TYPE,
	CUSTOMER_ORDER_LINE_ID,
	AUDIT_CREATE_DATE,
	AUDIT_CREATED_BY,
	AUDIT_MODIFIED_BY,
	AUDIT_MODIFY_DATE,
	DISCOUNT_AMOUNT,
	DISCOUNTED_ITEM_IND,
	PRICE,
	QUANTITY,
	SEQUENCE,
	TAX_TOTAL_EFFECTIVE_RATE,
	TAX_AMOUNT,
	TAX_AS_OF_DATE,
	CUSTOMER_ORDER_ID,
	ITEM_NUMBER,
	NAME,
	ODS_CREATE_DATE,
	ODS_MODIFY_DATE,
	DELETED_IND
)
select
	SYS_GUID(),
	:v_sess_no, 
	rowid,
	'F', 
	'ODI-15066: The column SEQUENCE cannot be null.',
	sysdate,
	'(1385001)ODS_Project.LOAD_SAS_CUSTOMER_ORDER_LINE_STG_INT',
	'SEQUENCE',
	'NN',	
	LINE_TYPE,
	CUSTOMER_ORDER_LINE_ID,
	AUDIT_CREATE_DATE,
	AUDIT_CREATED_BY,
	AUDIT_MODIFIED_BY,
	AUDIT_MODIFY_DATE,
	DISCOUNT_AMOUNT,
	DISCOUNTED_ITEM_IND,
	PRICE,
	QUANTITY,
	SEQUENCE,
	TAX_TOTAL_EFFECTIVE_RATE,
	TAX_AMOUNT,
	TAX_AS_OF_DATE,
	CUSTOMER_ORDER_ID,
	ITEM_NUMBER,
	NAME,
	ODS_CREATE_DATE,
	ODS_MODIFY_DATE,
	DELETED_IND
from	RAX_APP_USER.I$_SAS_CUST_ORD_LN_STG1385001
where	SEQUENCE is null



&


/*-----------------------------------------------*/
/* TASK No. 32 */
/* create index on error table */

 
/* FLOW CONTROL CREATE INDEX ON THE E$TABLE */
-- create index 	RAX_APP_USER.E$_SAS_CUST_ORD_LN_STG1385001
-- on	RAX_APP_USER.E$_SAS_CUST_ORD_LN_STG1385001 (ODI_ROW_ID)

BEGIN
  EXECUTE IMMEDIATE 'create index RAX_APP_USER.E$_SAS_CUST_ORD_LN_STG1385001
on   RAX_APP_USER.E$_SAS_CUST_ORD_LN_STG1385001 (ODI_ROW_ID)';
EXCEPTION
  WHEN OTHERS THEN
   -- Handle the case where the identifier is too long (ORA-00972)
   IF SQLCODE = -972 or  SQLCODE = -1408 or SQLCODE = -955  THEN
     DBMS_OUTPUT.PUT_LINE('Identifier is too long. Skipping creation of index.');
   ELSE
     RAISE;
   END IF;
END;

&


/*-----------------------------------------------*/
/* TASK No. 33 */
/* delete errors from controlled table */

delete from	RAX_APP_USER.I$_SAS_CUST_ORD_LN_STG1385001  T
where	exists 	(
		select	1
		from	RAX_APP_USER.E$_SAS_CUST_ORD_LN_STG1385001 E
		where ODI_SESS_NO = :v_sess_no
		and T.rowid = E.ODI_ROW_ID
		)


&


/*-----------------------------------------------*/
/* TASK No. 34 */
/* insert check sum into check table */

insert into RAX_APP_USER.SNP_CHECK_TAB
(
	SCHEMA_NAME,
	RESOURCE_NAME,
	FULL_RES_NAME,
	ERR_TYPE,
	ERR_MESS,
	CHECK_DATE,
	ORIGIN,
	CONS_NAME,
	CONS_TYPE,
	ERR_COUNT
)
select	
	'ODS_STAGE',
	'SAS_CUST_ORD_LN_STG',
	'ODS_STAGE.SAS_CUSTOMER_ORDER_LINE_STG1385001',
	E.ODI_ERR_TYPE,
	E.ODI_ERR_MESS,
	E.ODI_CHECK_DATE,
	E.ODI_ORIGIN,
	E.ODI_CONS_NAME,
	E.ODI_CONS_TYPE,
	count(1) 
from	RAX_APP_USER.E$_SAS_CUST_ORD_LN_STG1385001 E
where	E.ODI_ERR_TYPE	= 'F'
and	E.ODI_ORIGIN 	= '(1385001)ODS_Project.LOAD_SAS_CUSTOMER_ORDER_LINE_STG_INT'
group by	E.ODI_ERR_TYPE,
	E.ODI_ERR_MESS,
	E.ODI_CHECK_DATE,
	E.ODI_ORIGIN,
	E.ODI_CONS_NAME,
	E.ODI_CONS_TYPE


&


/*-----------------------------------------------*/
/* TASK No. 35 */
/* Merge Rows */

merge into	ODS_STAGE.SAS_CUSTOMER_ORDER_LINE_STG T
using	RAX_APP_USER.I$_SAS_CUST_ORD_LN_STG1385001 S
on	(
		T.CUSTOMER_ORDER_LINE_ID=S.CUSTOMER_ORDER_LINE_ID
	)
when matched
then update set
	T.LINE_TYPE	= S.LINE_TYPE,
	T.AUDIT_CREATE_DATE	= S.AUDIT_CREATE_DATE,
	T.AUDIT_CREATED_BY	= S.AUDIT_CREATED_BY,
	T.AUDIT_MODIFIED_BY	= S.AUDIT_MODIFIED_BY,
	T.AUDIT_MODIFY_DATE	= S.AUDIT_MODIFY_DATE,
	T.DISCOUNT_AMOUNT	= S.DISCOUNT_AMOUNT,
	T.DISCOUNTED_ITEM_IND	= S.DISCOUNTED_ITEM_IND,
	T.PRICE	= S.PRICE,
	T.QUANTITY	= S.QUANTITY,
	T.SEQUENCE	= S.SEQUENCE,
	T.TAX_TOTAL_EFFECTIVE_RATE	= S.TAX_TOTAL_EFFECTIVE_RATE,
	T.TAX_AMOUNT	= S.TAX_AMOUNT,
	T.TAX_AS_OF_DATE	= S.TAX_AS_OF_DATE,
	T.CUSTOMER_ORDER_ID	= S.CUSTOMER_ORDER_ID,
	T.ITEM_NUMBER	= S.ITEM_NUMBER,
	T.NAME	= S.NAME,
	T.DELETED_IND	= S.DELETED_IND
	,                 T.ODS_MODIFY_DATE	= sysdate
when not matched
then insert
	(
	T.LINE_TYPE,
	T.CUSTOMER_ORDER_LINE_ID,
	T.AUDIT_CREATE_DATE,
	T.AUDIT_CREATED_BY,
	T.AUDIT_MODIFIED_BY,
	T.AUDIT_MODIFY_DATE,
	T.DISCOUNT_AMOUNT,
	T.DISCOUNTED_ITEM_IND,
	T.PRICE,
	T.QUANTITY,
	T.SEQUENCE,
	T.TAX_TOTAL_EFFECTIVE_RATE,
	T.TAX_AMOUNT,
	T.TAX_AS_OF_DATE,
	T.CUSTOMER_ORDER_ID,
	T.ITEM_NUMBER,
	T.NAME,
	T.DELETED_IND
	,                  T.ODS_CREATE_DATE,
	T.ODS_MODIFY_DATE
	)
values
	(
	S.LINE_TYPE,
	S.CUSTOMER_ORDER_LINE_ID,
	S.AUDIT_CREATE_DATE,
	S.AUDIT_CREATED_BY,
	S.AUDIT_MODIFIED_BY,
	S.AUDIT_MODIFY_DATE,
	S.DISCOUNT_AMOUNT,
	S.DISCOUNTED_ITEM_IND,
	S.PRICE,
	S.QUANTITY,
	S.SEQUENCE,
	S.TAX_TOTAL_EFFECTIVE_RATE,
	S.TAX_AMOUNT,
	S.TAX_AS_OF_DATE,
	S.CUSTOMER_ORDER_ID,
	S.ITEM_NUMBER,
	S.NAME,
	S.DELETED_IND
	,                  sysdate,
	sysdate
	)

&


/*-----------------------------------------------*/
/* TASK No. 36 */
/* Commit transaction */

/*commit*/


/*-----------------------------------------------*/
/* TASK No. 37 */
/* Drop flow table */

-- drop table RAX_APP_USER.I$_SAS_CUST_ORD_LN_STG1385001

BEGIN
  EXECUTE IMMEDIATE 'drop table RAX_APP_USER.I$_SAS_CUST_ORD_LN_STG1385001';
EXCEPTION
  WHEN OTHERS THEN
   IF SQLCODE != -942 THEN
     RAISE;
   END IF;
END;

&


/*-----------------------------------------------*/
/* TASK No. 1000008 */
/* Drop work table */

-- drop table RAX_APP_USER.C$_0SAS_CUST_ORD_LN_STG purge

BEGIN
  EXECUTE IMMEDIATE 'drop table RAX_APP_USER.C$_0SAS_CUST_ORD_LN_STG purge';
EXCEPTION
  WHEN OTHERS THEN
   IF SQLCODE != -942 THEN
     RAISE;
   END IF;
END;


&


/*-----------------------------------------------*/
/* TASK No. 38 */
/* MERGE INTO ODS_STAGE.SAS_CUSTOMER_ORDER_LINE_XR */

-- SAS_CUSTOMER_ORDER_LINE_XR
MERGE INTO ODS_STAGE.SAS_CUSTOMER_ORDER_LINE_XR d
USING (
select * from
    (  Select
        XR.CUSTOMER_ORDER_LINE_OID as CUSTOMER_ORDER_LINE_OID,
        STG.CUSTOMER_ORDER_ID as SK_CUSTOMER_ORDER_ID,
        STG.CUSTOMER_ORDER_LINE_ID as SK_CUSTOMER_ORDER_LINE_ID,
        sysdate as ODS_CREATE_DATE,
        sysdate as ODS_MODIFY_DATE
    FROM 
        ODS_STAGE.SAS_CUSTOMER_ORDER_LINE_STG stg
        ,ODS_STAGE.SAS_CUSTOMER_ORDER_LINE_XR xr
    WHERE (1=1)
        and stg.ODS_MODIFY_DATE >= TO_DATE(SUBSTR(:v_cdc_load_date, 1, 19), 'YYYY-MM-DD HH24:MI:SS')  -:v_cdc_overlap
        and STG.CUSTOMER_ORDER_LINE_ID=XR.SK_CUSTOMER_ORDER_LINE_ID(+)
     ) s
where NOT EXISTS 
	( select 1 from ODS_STAGE.SAS_CUSTOMER_ORDER_LINE_XR T
	where	T.SK_CUSTOMER_ORDER_ID	= S.SK_CUSTOMER_ORDER_ID 
		 and
		((T.CUSTOMER_ORDER_LINE_OID = S.CUSTOMER_ORDER_LINE_OID) or (T.CUSTOMER_ORDER_LINE_OID IS NULL and S.CUSTOMER_ORDER_LINE_OID IS NULL)) and
		((T.SK_CUSTOMER_ORDER_LINE_ID = S.SK_CUSTOMER_ORDER_LINE_ID) or (T.SK_CUSTOMER_ORDER_LINE_ID IS NULL and S.SK_CUSTOMER_ORDER_LINE_ID IS NULL)) 
	)	
) s 
ON
  (s.SK_CUSTOMER_ORDER_LINE_ID=d.SK_CUSTOMER_ORDER_LINE_ID)
WHEN MATCHED
THEN
UPDATE SET
  d.CUSTOMER_ORDER_LINE_OID = s.CUSTOMER_ORDER_LINE_OID,
  d.SK_CUSTOMER_ORDER_ID = s.SK_CUSTOMER_ORDER_ID,
  d.ODS_MODIFY_DATE = s.ODS_MODIFY_DATE
WHEN NOT MATCHED
THEN
INSERT (
  CUSTOMER_ORDER_LINE_OID, SK_CUSTOMER_ORDER_ID, SK_CUSTOMER_ORDER_LINE_ID,
   ODS_CREATE_DATE, ODS_MODIFY_DATE)
VALUES (
  ODS_STAGE.CUSTOMER_ORDER_LINE_OID_SEQ.nextval, s.SK_CUSTOMER_ORDER_ID, s.SK_CUSTOMER_ORDER_LINE_ID,
   s.ODS_CREATE_DATE, s.ODS_MODIFY_DATE
  )

&


/*-----------------------------------------------*/
/* TASK No. 39 */
/* MERGE INTO ODS_OWN.SAS_CUSTOMER_ORDER_LINE */

MERGE INTO ODS_OWN.SAS_CUSTOMER_ORDER_LINE d
USING (
select * from (
      Select
        xr.CUSTOMER_ORDER_LINE_OID as CUSTOMER_ORDER_LINE_OID,
        axr.CUSTOMER_ORDER_OID as CUSTOMER_ORDER_OID,
        stg.AUDIT_CREATE_DATE as AUDIT_CREATE_DATE,
        stg.AUDIT_CREATED_BY as AUDIT_CREATED_BY,
        stg.AUDIT_MODIFIED_BY as AUDIT_MODIFIED_BY,
        stg.AUDIT_MODIFY_DATE as  AUDIT_MODIFY_DATE,         
        stg.DISCOUNT_AMOUNT  as DISCOUNT_AMOUNT,          
        stg.DISCOUNTED_ITEM_IND as DISCOUNTED_ITEM_IND       ,      
        stg.PRICE  ,       
       stg.LINE_TYPE,           
        stg.QUANTITY,      
        stg.SEQUENCE    ,    
        stg.TAX_TOTAL_EFFECTIVE_RATE       ,
        stg.TAX_AMOUNT     ,  
        stg.TAX_AS_OF_DATE       ,
        stg.ITEM_NUMBER           ,
        stg.NAME           ,
        stg.DELETED_IND                ,
        sysdate as ODS_CREATE_DATE,
        sysdate as ODS_MODIFY_DATE,
       SS.SOURCE_SYSTEM_OID as SOURCE_SYSTEM_OID
 
    FROM 
        ODS_STAGE.SAS_CUSTOMER_ORDER_LINE_STG stg
        ,ODS_STAGE.SAS_CUSTOMER_ORDER_LINE_XR xr
        ,ODS_STAGE.SAS_CUSTOMER_ORDER_XR axr
       ,ODS_OWN.SOURCE_SYSTEM SS
    WHERE (1=1)
        and stg.ODS_MODIFY_DATE >= TO_DATE(SUBSTR(:v_cdc_load_date, 1, 19), 'YYYY-MM-DD HH24:MI:SS')  -:v_cdc_overlap
  and SS.SOURCE_SYSTEM_SHORT_NAME='SAS'
        and stg.CUSTOMER_ORDER_LINE_ID =xr.SK_CUSTOMER_ORDER_LINE_ID(+)
        and xr.SK_CUSTOMER_ORDER_ID=AXR.SK_CUSTOMER_ORDER_ID(+)
   ) s
where NOT EXISTS 
	( select 1 from ODS_OWN.SAS_CUSTOMER_ORDER_LINE T
	where	T.CUSTOMER_ORDER_LINE_OID	= S.CUSTOMER_ORDER_LINE_OID 
 	and ((T.CUSTOMER_ORDER_LINE_OID = S.CUSTOMER_ORDER_LINE_OID) or (T.CUSTOMER_ORDER_LINE_OID IS NULL and S.CUSTOMER_ORDER_LINE_OID IS NULL)) and
 ((T.CUSTOMER_ORDER_OID = S.CUSTOMER_ORDER_OID) or (T.CUSTOMER_ORDER_OID IS NULL and S.CUSTOMER_ORDER_OID IS NULL)) and
 ((T.AUDIT_CREATE_DATE = S.AUDIT_CREATE_DATE) or (T.AUDIT_CREATE_DATE IS NULL and S.AUDIT_CREATE_DATE IS NULL)) and
((T.AUDIT_CREATED_BY = S.AUDIT_CREATED_BY) or (T.AUDIT_CREATED_BY IS NULL and S.AUDIT_CREATED_BY IS NULL)) and
        ((T.AUDIT_MODIFY_DATE = S.AUDIT_MODIFY_DATE) or (T.AUDIT_MODIFY_DATE IS NULL and S.AUDIT_MODIFY_DATE IS NULL)) and
        ((T.AUDIT_MODIFIED_BY = S.AUDIT_MODIFIED_BY) or (T.AUDIT_MODIFIED_BY IS NULL and S.AUDIT_MODIFIED_BY IS NULL)) and
 ((T.SOURCE_SYSTEM_OID = S.SOURCE_SYSTEM_OID) or (T.SOURCE_SYSTEM_OID IS NULL and S.SOURCE_SYSTEM_OID IS NULL)) AND

((T.DISCOUNT_AMOUNT=S.DISCOUNT_AMOUNT) or(T.DISCOUNT_AMOUNT IS NULL and S.DISCOUNT_AMOUNT IS NULL)) AND
((T.DISCOUNTED_ITEM_IND=S.DISCOUNTED_ITEM_IND ) or(T.DISCOUNTED_ITEM_IND  IS NULL and S.DISCOUNTED_ITEM_IND  IS NULL)) AND          
((T.LINE_TYPE=S.LINE_TYPE) or(T.LINE_TYPE  IS NULL and S.LINE_TYPE IS NULL)) AND    
((T.PRICE=S.PRICE) or(T.PRICE  IS NULL and S.PRICE IS NULL)) AND           
((T.QUANTITY=S.QUANTITY) or(T.QUANTITY  IS NULL and S.QUANTITY IS NULL)) AND  
((T.SEQUENCE=S.SEQUENCE) or(T.SEQUENCE  IS NULL and S.SEQUENCE IS NULL)) AND    
((T.TAX_TOTAL_EFFECTIVE_RATE=S.TAX_TOTAL_EFFECTIVE_RATE) or(T.TAX_TOTAL_EFFECTIVE_RATE  IS NULL and S.TAX_TOTAL_EFFECTIVE_RATE IS NULL)) AND  
((T.TAX_AMOUNT =S.TAX_AMOUNT) or(T.TAX_AMOUNT  IS NULL and S.TAX_AMOUNT IS NULL)) AND  
((T.TAX_AS_OF_DATE =S.TAX_AS_OF_DATE) or(T.TAX_AS_OF_DATE  IS NULL and S.TAX_AS_OF_DATE IS NULL)) AND 
((T.ITEM_NUMBER =S.ITEM_NUMBER) or(T.ITEM_NUMBER  IS NULL and S.ITEM_NUMBER IS NULL)) AND  
((T.NAME=S.NAME ) or(T.NAME  IS NULL and S.NAME  IS NULL)) AND  
((T.DELETED_IND  =S.DELETED_IND  ) or(T.DELETED_IND  IS NULL and S.DELETED_IND  IS NULL))   
        ) 
) s 
ON
  (d.CUSTOMER_ORDER_LINE_OID = s.CUSTOMER_ORDER_LINE_OID)
WHEN MATCHED
THEN
UPDATE SET
  d.CUSTOMER_ORDER_OID = s.CUSTOMER_ORDER_OID,
  d.AUDIT_CREATE_DATE = s.AUDIT_CREATE_DATE,
  d.AUDIT_CREATED_BY = s.AUDIT_CREATED_BY,
  d.AUDIT_MODIFY_DATE = s.AUDIT_MODIFY_DATE,
  d.AUDIT_MODIFIED_BY = s.AUDIT_MODIFIED_BY,
  d.SOURCE_SYSTEM_OID = s.SOURCE_SYSTEM_OID,
  d.LINE_TYPE=s.LINE_TYPE,
  d.DISCOUNT_AMOUNT=s.DISCOUNT_AMOUNT,
 d.DISCOUNTED_ITEM_IND=s.DISCOUNTED_ITEM_IND,
  d.PRICE=s.PRICE,
  d.QUANTITY=s.QUANTITY,
  d.SEQUENCE=s.SEQUENCE,
  d.TAX_TOTAL_EFFECTIVE_RATE=s.TAX_TOTAL_EFFECTIVE_RATE,
  d.TAX_AMOUNT=s.TAX_AMOUNT,
  d.TAX_AS_OF_DATE=s.TAX_AS_OF_DATE,
  d.ITEM_NUMBER=s.ITEM_NUMBER,
  d.NAME=s.NAME,
  d.ODS_MODIFY_DATE=s.ODS_MODIFY_DATE,
  d.DELETED_IND=s.DELETED_IND
WHEN NOT MATCHED
THEN
INSERT (CUSTOMER_ORDER_LINE_OID,CUSTOMER_ORDER_OID, 
  AUDIT_CREATE_DATE,
  AUDIT_CREATED_BY, AUDIT_MODIFY_DATE, AUDIT_MODIFIED_BY,LINE_TYPE ,ODS_MODIFY_DATE,ODS_CREATE_DATE,DELETED_IND,
DISCOUNT_AMOUNT,DISCOUNTED_ITEM_IND,PRICE,QUANTITY,SEQUENCE,TAX_TOTAL_EFFECTIVE_RATE,TAX_AMOUNT,TAX_AS_OF_DATE,ITEM_NUMBER,NAME

)VALUES(s.CUSTOMER_ORDER_LINE_OID,s.CUSTOMER_ORDER_OID,
  s.AUDIT_CREATE_DATE,
  s.AUDIT_CREATED_BY, s.AUDIT_MODIFY_DATE,s. AUDIT_MODIFIED_BY,s.LINE_TYPE, s.ODS_MODIFY_DATE,s.ODS_CREATE_DATE,s.DELETED_IND,s.DISCOUNT_AMOUNT,s.DISCOUNTED_ITEM_IND,s.PRICE,s.QUANTITY,
s.SEQUENCE,s.TAX_TOTAL_EFFECTIVE_RATE,s.TAX_AMOUNT,s.TAX_AS_OF_DATE,s.ITEM_NUMBER,s.NAME

)



&


/*-----------------------------------------------*/
/* TASK No. 40 */
/* Update CDC Load Status */

UPDATE ODS_OWN.ODS_CDC_LOAD_STATUS
SET LAST_CDC_COMPLETION_DATE=TO_DATE(
             SUBSTR(:v_sess_beg, 1, 19), 'RRRR-MM-DD HH24:MI:SS')
+ nvl((TIMEZONE_OFFSET/24), 0) 
WHERE ODS_TABLE_NAME=:v_cdc_load_table_name
AND CONTEXT_NAME = :v_env

/*
UPDATE ODS_OWN.ODS_CDC_LOAD_STATUS
SET LAST_CDC_COMPLETION_DATE=TO_DATE(
             SUBSTR(:v_sess_beg, 1, 19), 'RRRR-MM-DD HH24:MI:SS')
WHERE ODS_TABLE_NAME=:v_cdc_load_table_name
AND CONTEXT_NAME = :v_env
*/

&


/*-----------------------------------------------*/
/* TASK No. 41 */
/* Insert CDC Audit Record */

INSERT INTO RAX_APP_USER.ODS_CDC_LOAD_STATUS_AUDIT
(TABLE_NAME,
SESS_NO,                      
SESS_NAME,                    
SCEN_VERSION,                 
SESS_BEG,                     
ORIG_LAST_CDC_COMPLETION_DATE,
OVERLAP,
CREATE_DATE,
CONTEXT_NAME,
TIMEZONE_OFFSET              
)
select 
:v_cdc_load_table_name
,:v_sess_no
,'LOAD_SAS_CUSTOMER_ORDER_LINE_PKG'
,'004'
,TO_DATE(SUBSTR(:v_sess_beg, 1, 19), 'RRRR-MM-DD HH24:MI:SS')
,TO_DATE (SUBSTR(:v_cdc_load_date, 1, 19),'YYYY-MM-DD HH24:MI:SS')
,:v_cdc_overlap
,SYSDATE
,:v_env
,TIMEZONE_OFFSET
from 
ODS_OWN.ODS_CDC_LOAD_STATUS
WHERE ODS_TABLE_NAME=:v_cdc_load_table_name
AND CONTEXT_NAME = :v_env

/*
INSERT INTO RAX_APP_USER.ODS_CDC_LOAD_STATUS_AUDIT
(TABLE_NAME,
SESS_NO,                      
SESS_NAME,                    
SCEN_VERSION,                 
SESS_BEG,                     
ORIG_LAST_CDC_COMPLETION_DATE,
OVERLAP,
CREATE_DATE,
CONTEXT_NAME              
)
values (
:v_cdc_load_table_name,
:v_sess_no,
'LOAD_SAS_CUSTOMER_ORDER_LINE_PKG',
'004',
TO_DATE(
             SUBSTR(:v_sess_beg, 1, 19), 'RRRR-MM-DD HH24:MI:SS'),
TO_DATE (SUBSTR (:v_cdc_load_date, 1, 19),
                           'YYYY-MM-DD HH24:MI:SS'
                          )
,:v_cdc_overlap,
SYSDATE,
 :v_env)
*/


&


/*-----------------------------------------------*/
