/* TASK No. 1 */

/* NONE or SET VARIABLE STATEMENT FOUND, CHECK ODI TASK NO. 1 */




/*-----------------------------------------------*/
/* TASK No. 2 */

/* SELECT STATEMENT FOUND, CHECK ODI TASK NO. 2 */




/*-----------------------------------------------*/
/* TASK No. 3 */

/* SELECT STATEMENT FOUND, CHECK ODI TASK NO. 3 */




/*-----------------------------------------------*/
/* TASK No. 4 */
/* Drop work table */

-- drop table RAX_APP_USER.C$_0SAS_ORD_STATUS_STG purge

-- &


/*-----------------------------------------------*/
/* TASK No. 5 */
/* Create work table */

-- create table RAX_APP_USER.C$_0SAS_ORD_STATUS_STG
-- (
-- 	C1_ORDER_STATUS_ID	NUMBER(10) NULL,
-- 	C2_AUDIT_CREATE_DATE	TIMESTAMP(6) NULL,
-- 	C3_AUDIT_CREATED_BY	VARCHAR2(255) NULL,
-- 	C4_AUDIT_MODIFIED_BY	VARCHAR2(255) NULL,
-- 	C5_AUDIT_MODIFY_DATE	TIMESTAMP(6) NULL,
-- 	C6_CODE	VARCHAR2(255) NULL,
-- 	C7_CREATE_DT	TIMESTAMP(6) NULL,
-- 	C8_MODIFYING_USER	VARCHAR2(255) NULL,
-- 	C9_STATUS_SEQUENCE	NUMBER(10) NULL,
-- 	C10_CUSTOMER_ORDER_ID	NUMBER(10) NULL,
-- 	C11_DELETED_IND	VARCHAR2(1) NULL
-- )
-- NOLOGGING

-- &


/*-----------------------------------------------*/
/* TASK No. 6 */
/* Load data */

/* SOURCE CODE */


-- select	
-- 	ORDER_STATUS.ORDER_STATUS_ID	   C1_ORDER_STATUS_ID,
-- 	ORDER_STATUS.AUDIT_CREATE_DATE	   C2_AUDIT_CREATE_DATE,
-- 	ORDER_STATUS.AUDIT_CREATED_BY	   C3_AUDIT_CREATED_BY,
-- 	ORDER_STATUS.AUDIT_MODIFIED_BY	   C4_AUDIT_MODIFIED_BY,
-- 	ORDER_STATUS.AUDIT_MODIFY_DATE	   C5_AUDIT_MODIFY_DATE,
-- 	ORDER_STATUS.CODE	   C6_CODE,
-- 	ORDER_STATUS.CREATE_DT	   C7_CREATE_DT,
-- 	ORDER_STATUS.MODIFYING_USER	   C8_MODIFYING_USER,
-- 	ORDER_STATUS.STATUS_SEQUENCE	   C9_STATUS_SEQUENCE,
-- 	ORDER_STATUS.CUSTOMER_ORDER_ID	   C10_CUSTOMER_ORDER_ID,
-- 	ORDER_STATUS.DELETED_IND	   C11_DELETED_IND
-- from	SAS_SIT_OWN.ORDER_STATUS   ORDER_STATUS
-- where	(1=1)
-- And (ORDER_STATUS.AUDIT_MODIFY_DATE >= TO_DATE(SUBSTR(:v_cdc_load_date, 1, 19), 'YYYY-MM-DD HH24:MI:SS')  -:v_cdc_overlap
-- )







-- &

/* TARGET CODE */
-- insert /*+ append */ into RAX_APP_USER.C$_0SAS_ORD_STATUS_STG
-- (
-- 	C1_ORDER_STATUS_ID,
-- 	C2_AUDIT_CREATE_DATE,
-- 	C3_AUDIT_CREATED_BY,
-- 	C4_AUDIT_MODIFIED_BY,
-- 	C5_AUDIT_MODIFY_DATE,
-- 	C6_CODE,
-- 	C7_CREATE_DT,
-- 	C8_MODIFYING_USER,
-- 	C9_STATUS_SEQUENCE,
-- 	C10_CUSTOMER_ORDER_ID,
-- 	C11_DELETED_IND
-- )
-- values
-- (
-- 	:C1_ORDER_STATUS_ID,
-- 	:C2_AUDIT_CREATE_DATE,
-- 	:C3_AUDIT_CREATED_BY,
-- 	:C4_AUDIT_MODIFIED_BY,
-- 	:C5_AUDIT_MODIFY_DATE,
-- 	:C6_CODE,
-- 	:C7_CREATE_DT,
-- 	:C8_MODIFYING_USER,
-- 	:C9_STATUS_SEQUENCE,
-- 	:C10_CUSTOMER_ORDER_ID,
-- 	:C11_DELETED_IND
-- )

-- &


/*-----------------------------------------------*/
/* TASK No. 7 */
/* Analyze work table */



BEGIN
DBMS_STATS.GATHER_TABLE_STATS (
    ownname =>	'RAX_APP_USER',
    tabname =>	'C$_0SAS_ORD_STATUS_STG',
    estimate_percent =>	DBMS_STATS.AUTO_SAMPLE_SIZE
);
END;




&


/*-----------------------------------------------*/
/* TASK No. 9 */
/* Set vID */

/* NONE or SET VARIABLE STATEMENT FOUND, CHECK ODI TASK NO. 9 */




/*-----------------------------------------------*/
/* TASK No. 10 */
/* Drop flow table */

-- drop table RAX_APP_USER.I$_SAS_ORD_STATUS_STG1391001

BEGIN
  EXECUTE IMMEDIATE 'drop table RAX_APP_USER.I$_SAS_ORD_STATUS_STG1391001';
EXCEPTION
  WHEN OTHERS THEN
   IF SQLCODE != -942 THEN
     RAISE;
   END IF;
END;


&


/*-----------------------------------------------*/
/* TASK No. 11 */
/* Create flow table I$ */

create table RAX_APP_USER.I$_SAS_ORD_STATUS_STG1391001
(
	ORDER_STATUS_ID	NUMBER(10) NULL,
	AUDIT_CREATE_DATE	TIMESTAMP(6) NULL,
	AUDIT_CREATED_BY	VARCHAR2(255) NULL,
	AUDIT_MODIFIED_BY	VARCHAR2(255) NULL,
	AUDIT_MODIFY_DATE	TIMESTAMP(6) NULL,
	CODE	VARCHAR2(255) NULL,
	CREATE_DT	TIMESTAMP(6) NULL,
	MODIFYING_USER	VARCHAR2(255) NULL,
	STATUS_SEQUENCE	NUMBER(10) NULL,
	CUSTOMER_ORDER_ID	NUMBER(10) NULL,
	ODS_CREATE_DATE	DATE NULL,
	ODS_MODIFY_DATE	DATE NULL,
	DELETED_IND	VARCHAR2(1) NULL
	,IND_UPDATE		char(1)
)
NOLOGGING

&


/*-----------------------------------------------*/
/* TASK No. 12 */
/* Insert flow into I$ table */

/* DETECTION_STRATEGY = NOT_EXISTS */
 


  


insert into	RAX_APP_USER.I$_SAS_ORD_STATUS_STG1391001
(
	ORDER_STATUS_ID,
	AUDIT_CREATE_DATE,
	AUDIT_CREATED_BY,
	AUDIT_MODIFIED_BY,
	AUDIT_MODIFY_DATE,
	CODE,
	CREATE_DT,
	MODIFYING_USER,
	STATUS_SEQUENCE,
	CUSTOMER_ORDER_ID,
	DELETED_IND,
	IND_UPDATE
)
select 
ORDER_STATUS_ID,
	AUDIT_CREATE_DATE,
	AUDIT_CREATED_BY,
	AUDIT_MODIFIED_BY,
	AUDIT_MODIFY_DATE,
	CODE,
	CREATE_DT,
	MODIFYING_USER,
	STATUS_SEQUENCE,
	CUSTOMER_ORDER_ID,
	DELETED_IND,
	IND_UPDATE
 from (


select 	 
	
	C1_ORDER_STATUS_ID ORDER_STATUS_ID,
	C2_AUDIT_CREATE_DATE AUDIT_CREATE_DATE,
	C3_AUDIT_CREATED_BY AUDIT_CREATED_BY,
	C4_AUDIT_MODIFIED_BY AUDIT_MODIFIED_BY,
	C5_AUDIT_MODIFY_DATE AUDIT_MODIFY_DATE,
	C6_CODE CODE,
	C7_CREATE_DT CREATE_DT,
	C8_MODIFYING_USER MODIFYING_USER,
	C9_STATUS_SEQUENCE STATUS_SEQUENCE,
	C10_CUSTOMER_ORDER_ID CUSTOMER_ORDER_ID,
	C11_DELETED_IND DELETED_IND,

	'I' IND_UPDATE

from	RAX_APP_USER.C$_0SAS_ORD_STATUS_STG
where	(1=1)






) S
where NOT EXISTS 
	( select 1 from ODS_STAGE.SAS_ORDER_STATUS_STG T
	where	T.ORDER_STATUS_ID	= S.ORDER_STATUS_ID 
		 and ((T.AUDIT_CREATE_DATE = S.AUDIT_CREATE_DATE) or (T.AUDIT_CREATE_DATE IS NULL and S.AUDIT_CREATE_DATE IS NULL)) and
		((T.AUDIT_CREATED_BY = S.AUDIT_CREATED_BY) or (T.AUDIT_CREATED_BY IS NULL and S.AUDIT_CREATED_BY IS NULL)) and
		((T.AUDIT_MODIFIED_BY = S.AUDIT_MODIFIED_BY) or (T.AUDIT_MODIFIED_BY IS NULL and S.AUDIT_MODIFIED_BY IS NULL)) and
		((T.AUDIT_MODIFY_DATE = S.AUDIT_MODIFY_DATE) or (T.AUDIT_MODIFY_DATE IS NULL and S.AUDIT_MODIFY_DATE IS NULL)) and
		((T.CODE = S.CODE) or (T.CODE IS NULL and S.CODE IS NULL)) and
		((T.CREATE_DT = S.CREATE_DT) or (T.CREATE_DT IS NULL and S.CREATE_DT IS NULL)) and
		((T.MODIFYING_USER = S.MODIFYING_USER) or (T.MODIFYING_USER IS NULL and S.MODIFYING_USER IS NULL)) and
		((T.STATUS_SEQUENCE = S.STATUS_SEQUENCE) or (T.STATUS_SEQUENCE IS NULL and S.STATUS_SEQUENCE IS NULL)) and
		((T.CUSTOMER_ORDER_ID = S.CUSTOMER_ORDER_ID) or (T.CUSTOMER_ORDER_ID IS NULL and S.CUSTOMER_ORDER_ID IS NULL)) and
		((T.DELETED_IND = S.DELETED_IND) or (T.DELETED_IND IS NULL and S.DELETED_IND IS NULL))
        )

  
  

  



&


/*-----------------------------------------------*/
/* TASK No. 13 */
/* Analyze integration table */



begin
    dbms_stats.gather_table_stats(
	ownname => 'RAX_APP_USER',
	tabname => 'I$_SAS_ORD_STATUS_STG1391001',
	estimate_percent => dbms_stats.auto_sample_size
    );
end;



&


/*-----------------------------------------------*/
/* TASK No. 14 */
/* Create Index on flow table */

-- create index	RAX_APP_USER.I$_SAS_ORD_STATUS_STG1391001
-- on		RAX_APP_USER.I$_SAS_ORD_STATUS_STG1391001 (ORDER_STATUS_ID)
-- NOLOGGING

BEGIN
  EXECUTE IMMEDIATE 'create index RAX_APP_USER.I$_SAS_ORD_STATUS_STG1391001
on   RAX_APP_USER.I$_SAS_ORD_STATUS_STG1391001 (ORDER_STATUS_ID)';
EXCEPTION
  WHEN OTHERS THEN
   -- Handle the case where the identifier is too long (ORA-00972)
   IF SQLCODE = -972 or  SQLCODE = -1408 or SQLCODE = -955  THEN
     DBMS_OUTPUT.PUT_LINE('Identifier is too long. Skipping creation of index.');
   ELSE
     RAISE;
   END IF;
END;

&


/*-----------------------------------------------*/
/* TASK No. 15 */
/* create check table */


BEGIN
  EXECUTE IMMEDIATE 'drop table RAX_APP_USER.SNP_CHECK_TAB';
EXCEPTION
  WHEN OTHERS THEN
   IF SQLCODE != -942 THEN
     RAISE;
   END IF;
END;

&

-- create table RAX_APP_USER.SNP_CHECK_TAB
-- (
-- 	CATALOG_NAME	VARCHAR2(100 CHAR) NULL ,
-- 	SCHEMA_NAME	VARCHAR2(100 CHAR) NULL ,
-- 	RESOURCE_NAME	VARCHAR2(100 CHAR) NULL,
-- 	FULL_RES_NAME	VARCHAR2(100 CHAR) NULL,
-- 	ERR_TYPE		VARCHAR2(1 CHAR) NULL,
-- 	ERR_MESS		VARCHAR2(250 CHAR) NULL ,
-- 	CHECK_DATE	DATE NULL,
-- 	ORIGIN		VARCHAR2(100 CHAR) NULL,
-- 	CONS_NAME	VARCHAR2(35 CHAR) NULL,
-- 	CONS_TYPE		VARCHAR2(2 CHAR) NULL,
-- 	ERR_COUNT		NUMBER(10) NULL
-- )


BEGIN
   EXECUTE IMMEDIATE '
      create table RAX_APP_USER.SNP_CHECK_TAB
		(
			CATALOG_NAME	VARCHAR2(100 CHAR) NULL ,
			SCHEMA_NAME	VARCHAR2(100 CHAR) NULL ,
			RESOURCE_NAME	VARCHAR2(100 CHAR) NULL,
			FULL_RES_NAME	VARCHAR2(100 CHAR) NULL,
			ERR_TYPE		VARCHAR2(1 CHAR) NULL,
			ERR_MESS		VARCHAR2(250 CHAR) NULL ,
			CHECK_DATE	DATE NULL,
			ORIGIN		VARCHAR2(100 CHAR) NULL,
			CONS_NAME	VARCHAR2(35 CHAR) NULL,
			CONS_TYPE		VARCHAR2(2 CHAR) NULL,
			ERR_COUNT		NUMBER(10) NULL
		)
   ';
END;


&


/*-----------------------------------------------*/
/* TASK No. 16 */
/* delete previous check sum */

delete from	RAX_APP_USER.SNP_CHECK_TAB
where	SCHEMA_NAME	= 'ODS_STAGE'
and	ORIGIN 		= '(1391001)ODS_Project.LOAD_SAS_ORDER_STATUS_STG_INT'
and	ERR_TYPE 		= 'F'


&


/*-----------------------------------------------*/
/* TASK No. 17 */
/* create error table */

BEGIN
  EXECUTE IMMEDIATE 'drop table RAX_APP_USER.E$_SAS_ORD_STATUS_STG1391001';
EXCEPTION
  WHEN OTHERS THEN
   IF SQLCODE != -942 THEN
     RAISE;
   END IF;
END;

&

create table RAX_APP_USER.E$_SAS_ORD_STATUS_STG1391001
(
	ODI_ROW_ID 		UROWID,
	ODI_ERR_TYPE		VARCHAR2(1 CHAR) NULL, 
	ODI_ERR_MESS		VARCHAR2(250 CHAR) NULL,
	ODI_CHECK_DATE	DATE NULL, 
	ORDER_STATUS_ID	NUMBER(10) NULL,
	AUDIT_CREATE_DATE	TIMESTAMP(6) NULL,
	AUDIT_CREATED_BY	VARCHAR2(255) NULL,
	AUDIT_MODIFIED_BY	VARCHAR2(255) NULL,
	AUDIT_MODIFY_DATE	TIMESTAMP(6) NULL,
	CODE	VARCHAR2(255) NULL,
	CREATE_DT	TIMESTAMP(6) NULL,
	MODIFYING_USER	VARCHAR2(255) NULL,
	STATUS_SEQUENCE	NUMBER(10) NULL,
	CUSTOMER_ORDER_ID	NUMBER(10) NULL,
	ODS_CREATE_DATE	DATE NULL,
	ODS_MODIFY_DATE	DATE NULL,
	DELETED_IND	VARCHAR2(1) NULL,
	ODI_ORIGIN		VARCHAR2(100 CHAR) NULL,
	ODI_CONS_NAME	VARCHAR2(35 CHAR) NULL,
	ODI_CONS_TYPE		VARCHAR2(2 CHAR) NULL,
	ODI_PK			VARCHAR2(32 CHAR) PRIMARY KEY,
	ODI_SESS_NO		VARCHAR2(19 CHAR)
)



&


/*-----------------------------------------------*/
/* TASK No. 18 */
/* delete previous errors */

delete from 	RAX_APP_USER.E$_SAS_ORD_STATUS_STG1391001
where	(ODI_ERR_TYPE = 'S'	and 'F' = 'S')
or	(ODI_ERR_TYPE = 'F'	and ODI_ORIGIN = '(1391001)ODS_Project.LOAD_SAS_ORDER_STATUS_STG_INT')


&


/*-----------------------------------------------*/
/* TASK No. 19 */
/* Create index on PK */

 
/* FLOW CONTROL CREATE THE iNDEX ON THE I$TABLE */
-- create index 	RAX_APP_USER.I$_SAS_ORD_STATUS_STG1391001
-- on	RAX_APP_USER.I$_SAS_ORD_STATUS_STG1391001 (ORDER_STATUS_ID)

BEGIN
  EXECUTE IMMEDIATE 'create index RAX_APP_USER.I$_SAS_ORD_STATUS_STG1391001
on   RAX_APP_USER.I$_SAS_ORD_STATUS_STG1391001 (ORDER_STATUS_ID)';
EXCEPTION
  WHEN OTHERS THEN
   -- Handle the case where the identifier is too long (ORA-00972)
   IF SQLCODE = -972 or  SQLCODE = -1408 or SQLCODE = -955  THEN
     DBMS_OUTPUT.PUT_LINE('Identifier is too long. Skipping creation of index.');
   ELSE
     RAISE;
   END IF;
END;

&


/*-----------------------------------------------*/
/* TASK No. 20 */
/* insert PK errors */

DECLARE
               CheckTable                             VarChar2(60);
               TargetTable                            VarChar2(60);
               VariableCheckTable                     VarChar2(60);

BEGIN
               SELECT 'RAX_APP_USER.I$_SAS_ORD_STATUS_STG' INTO CheckTable FROM DUAL;
               SELECT 'ODS_STAGE.SAS_ORDER_STATUS_STG' INTO TargetTable FROM DUAL;

IF CheckTable = TargetTable THEN
   VariableCheckTable := CheckTable; 
ELSE
   VariableCheckTable := CheckTable || '1391001';
END IF;

execute immediate '
insert into RAX_APP_USER.E$_SAS_ORD_STATUS_STG1391001
(
	ODI_PK,
	ODI_SESS_NO,
	ODI_ROW_ID,
	ODI_ERR_TYPE,
	ODI_ERR_MESS,
	ODI_ORIGIN,
	ODI_CHECK_DATE,
	ODI_CONS_NAME,
	ODI_CONS_TYPE,
	ORDER_STATUS_ID,
	AUDIT_CREATE_DATE,
	AUDIT_CREATED_BY,
	AUDIT_MODIFIED_BY,
	AUDIT_MODIFY_DATE,
	CODE,
	CREATE_DT,
	MODIFYING_USER,
	STATUS_SEQUENCE,
	CUSTOMER_ORDER_ID,
	ODS_CREATE_DATE,
	ODS_MODIFY_DATE,
	DELETED_IND
)
select	SYS_GUID(),
	:v_sess_no, 
	rowid,
	''F'', 
	''ODI-15064: The primary key ORDER_STATUS_PK is not unique.'',
	''(1391001)ODS_Project.LOAD_SAS_ORDER_STATUS_STG_INT'',
	sysdate,
	''ORDER_STATUS_PK'',
	''PK'',	
	SAS_ORD_STATUS_STG.ORDER_STATUS_ID,
	SAS_ORD_STATUS_STG.AUDIT_CREATE_DATE,
	SAS_ORD_STATUS_STG.AUDIT_CREATED_BY,
	SAS_ORD_STATUS_STG.AUDIT_MODIFIED_BY,
	SAS_ORD_STATUS_STG.AUDIT_MODIFY_DATE,
	SAS_ORD_STATUS_STG.CODE,
	SAS_ORD_STATUS_STG.CREATE_DT,
	SAS_ORD_STATUS_STG.MODIFYING_USER,
	SAS_ORD_STATUS_STG.STATUS_SEQUENCE,
	SAS_ORD_STATUS_STG.CUSTOMER_ORDER_ID,
	SAS_ORD_STATUS_STG.ODS_CREATE_DATE,
	SAS_ORD_STATUS_STG.ODS_MODIFY_DATE,
	SAS_ORD_STATUS_STG.DELETED_IND
from	'
 || VariableCheckTable || 
' SAS_ORD_STATUS_STG 
where	exists  (
		select	SUB1.ORDER_STATUS_ID
		from 	' 
|| VariableCheckTable ||
'  SUB1
		where 	SUB1.ORDER_STATUS_ID=SAS_ORD_STATUS_STG.ORDER_STATUS_ID
		group by 	SUB1.ORDER_STATUS_ID
		having 	count(1) > 1
		)
';

END;


&


/*-----------------------------------------------*/
/* TASK No. 21 */
/* Create index on AK */

 
/* FLOW CONTROL CREATE THE iNDEX ON THE I$TABLE */
-- create index 	SAS_ORDER_STATUS_PK_flow
-- on	RAX_APP_USER.I$_SAS_ORD_STATUS_STG1391001 
-- 	(ORDER_STATUS_ID)

BEGIN
  EXECUTE IMMEDIATE 'create index SAS_ORDER_STATUS_PK_flow
on   RAX_APP_USER.I$_SAS_ORD_STATUS_STG1391001 (ORDER_STATUS_ID)';
EXCEPTION
  WHEN OTHERS THEN
   -- Handle the case where the identifier is too long (ORA-00972)
   IF SQLCODE = -972 or  SQLCODE = -1408 or SQLCODE = -955  THEN
     DBMS_OUTPUT.PUT_LINE('Identifier is too long. Skipping creation of index.');
   ELSE
     RAISE;
   END IF;
END;

&


/*-----------------------------------------------*/
/* TASK No. 22 */
/* insert AK errors */

DECLARE
               CheckTable                             VarChar2(60);
               TargetTable                            VarChar2(60);
               VariableCheckTable                VarChar2(60);

BEGIN
               SELECT 'RAX_APP_USER.I$_SAS_ORD_STATUS_STG' INTO CheckTable FROM DUAL;
               SELECT 'ODS_STAGE.SAS_ORDER_STATUS_STG' INTO TargetTable FROM DUAL;

IF CheckTable = TargetTable THEN
   VariableCheckTable := CheckTable; 
ELSE
   VariableCheckTable := CheckTable || '1391001';
END IF;

execute immediate '
insert into RAX_APP_USER.E$_SAS_ORD_STATUS_STG1391001
(
	ODI_PK,
	ODI_SESS_NO,
	ODI_ROW_ID,
	ODI_ERR_TYPE,
	ODI_ERR_MESS,
	ODI_ORIGIN,
	ODI_CHECK_DATE,
	ODI_CONS_NAME,
	ODI_CONS_TYPE,
	ORDER_STATUS_ID,
	AUDIT_CREATE_DATE,
	AUDIT_CREATED_BY,
	AUDIT_MODIFIED_BY,
	AUDIT_MODIFY_DATE,
	CODE,
	CREATE_DT,
	MODIFYING_USER,
	STATUS_SEQUENCE,
	CUSTOMER_ORDER_ID,
	ODS_CREATE_DATE,
	ODS_MODIFY_DATE,
	DELETED_IND
)
select	SYS_GUID(),
	:v_sess_no, 
	rowid,
	''F'', 
	''ODI-15063: The alternate key SAS_ORDER_STATUS_PK is not unique.'',
	''(1391001)ODS_Project.LOAD_SAS_ORDER_STATUS_STG_INT'',
	sysdate,
	''SAS_ORDER_STATUS_PK'',
	''AK'',	
	SAS_ORD_STATUS_STG.ORDER_STATUS_ID,
	SAS_ORD_STATUS_STG.AUDIT_CREATE_DATE,
	SAS_ORD_STATUS_STG.AUDIT_CREATED_BY,
	SAS_ORD_STATUS_STG.AUDIT_MODIFIED_BY,
	SAS_ORD_STATUS_STG.AUDIT_MODIFY_DATE,
	SAS_ORD_STATUS_STG.CODE,
	SAS_ORD_STATUS_STG.CREATE_DT,
	SAS_ORD_STATUS_STG.MODIFYING_USER,
	SAS_ORD_STATUS_STG.STATUS_SEQUENCE,
	SAS_ORD_STATUS_STG.CUSTOMER_ORDER_ID,
	SAS_ORD_STATUS_STG.ODS_CREATE_DATE,
	SAS_ORD_STATUS_STG.ODS_MODIFY_DATE,
	SAS_ORD_STATUS_STG.DELETED_IND
from              '	
 || VariableCheckTable || 
' SAS_ORD_STATUS_STG
where	exists  (
		select	SUB.ORDER_STATUS_ID
		from 	'
 || VariableCheckTable || 
' SUB
		where 	SUB.ORDER_STATUS_ID=SAS_ORD_STATUS_STG.ORDER_STATUS_ID
		group by 	SUB.ORDER_STATUS_ID
		having 	count(1) > 1
		)
 ';

END;

/*  Checked Datastore =RAX_APP_USER.I$_SAS_ORD_STATUS_STG  */
/*  Integration Datastore =RAX_APP_USER.I$_SAS_ORD_STATUS_STG   */
/*  Target Datastore =ODS_STAGE.SAS_ORDER_STATUS_STG */



&


/*-----------------------------------------------*/
/* TASK No. 23 */
/* insert Not Null errors */

insert into RAX_APP_USER.E$_SAS_ORD_STATUS_STG1391001
(
	ODI_PK,
	ODI_SESS_NO,
	ODI_ROW_ID,
	ODI_ERR_TYPE,
	ODI_ERR_MESS,
	ODI_CHECK_DATE,
	ODI_ORIGIN,
	ODI_CONS_NAME,
	ODI_CONS_TYPE,
	ORDER_STATUS_ID,
	AUDIT_CREATE_DATE,
	AUDIT_CREATED_BY,
	AUDIT_MODIFIED_BY,
	AUDIT_MODIFY_DATE,
	CODE,
	CREATE_DT,
	MODIFYING_USER,
	STATUS_SEQUENCE,
	CUSTOMER_ORDER_ID,
	ODS_CREATE_DATE,
	ODS_MODIFY_DATE,
	DELETED_IND
)
select
	SYS_GUID(),
	:v_sess_no, 
	rowid,
	'F', 
	'ODI-15066: The column ORDER_STATUS_ID cannot be null.',
	sysdate,
	'(1391001)ODS_Project.LOAD_SAS_ORDER_STATUS_STG_INT',
	'ORDER_STATUS_ID',
	'NN',	
	ORDER_STATUS_ID,
	AUDIT_CREATE_DATE,
	AUDIT_CREATED_BY,
	AUDIT_MODIFIED_BY,
	AUDIT_MODIFY_DATE,
	CODE,
	CREATE_DT,
	MODIFYING_USER,
	STATUS_SEQUENCE,
	CUSTOMER_ORDER_ID,
	ODS_CREATE_DATE,
	ODS_MODIFY_DATE,
	DELETED_IND
from	RAX_APP_USER.I$_SAS_ORD_STATUS_STG1391001
where	ORDER_STATUS_ID is null



&


/*-----------------------------------------------*/
/* TASK No. 24 */
/* insert Not Null errors */

insert into RAX_APP_USER.E$_SAS_ORD_STATUS_STG1391001
(
	ODI_PK,
	ODI_SESS_NO,
	ODI_ROW_ID,
	ODI_ERR_TYPE,
	ODI_ERR_MESS,
	ODI_CHECK_DATE,
	ODI_ORIGIN,
	ODI_CONS_NAME,
	ODI_CONS_TYPE,
	ORDER_STATUS_ID,
	AUDIT_CREATE_DATE,
	AUDIT_CREATED_BY,
	AUDIT_MODIFIED_BY,
	AUDIT_MODIFY_DATE,
	CODE,
	CREATE_DT,
	MODIFYING_USER,
	STATUS_SEQUENCE,
	CUSTOMER_ORDER_ID,
	ODS_CREATE_DATE,
	ODS_MODIFY_DATE,
	DELETED_IND
)
select
	SYS_GUID(),
	:v_sess_no, 
	rowid,
	'F', 
	'ODI-15066: The column AUDIT_CREATE_DATE cannot be null.',
	sysdate,
	'(1391001)ODS_Project.LOAD_SAS_ORDER_STATUS_STG_INT',
	'AUDIT_CREATE_DATE',
	'NN',	
	ORDER_STATUS_ID,
	AUDIT_CREATE_DATE,
	AUDIT_CREATED_BY,
	AUDIT_MODIFIED_BY,
	AUDIT_MODIFY_DATE,
	CODE,
	CREATE_DT,
	MODIFYING_USER,
	STATUS_SEQUENCE,
	CUSTOMER_ORDER_ID,
	ODS_CREATE_DATE,
	ODS_MODIFY_DATE,
	DELETED_IND
from	RAX_APP_USER.I$_SAS_ORD_STATUS_STG1391001
where	AUDIT_CREATE_DATE is null



&


/*-----------------------------------------------*/
/* TASK No. 25 */
/* insert Not Null errors */

insert into RAX_APP_USER.E$_SAS_ORD_STATUS_STG1391001
(
	ODI_PK,
	ODI_SESS_NO,
	ODI_ROW_ID,
	ODI_ERR_TYPE,
	ODI_ERR_MESS,
	ODI_CHECK_DATE,
	ODI_ORIGIN,
	ODI_CONS_NAME,
	ODI_CONS_TYPE,
	ORDER_STATUS_ID,
	AUDIT_CREATE_DATE,
	AUDIT_CREATED_BY,
	AUDIT_MODIFIED_BY,
	AUDIT_MODIFY_DATE,
	CODE,
	CREATE_DT,
	MODIFYING_USER,
	STATUS_SEQUENCE,
	CUSTOMER_ORDER_ID,
	ODS_CREATE_DATE,
	ODS_MODIFY_DATE,
	DELETED_IND
)
select
	SYS_GUID(),
	:v_sess_no, 
	rowid,
	'F', 
	'ODI-15066: The column AUDIT_CREATED_BY cannot be null.',
	sysdate,
	'(1391001)ODS_Project.LOAD_SAS_ORDER_STATUS_STG_INT',
	'AUDIT_CREATED_BY',
	'NN',	
	ORDER_STATUS_ID,
	AUDIT_CREATE_DATE,
	AUDIT_CREATED_BY,
	AUDIT_MODIFIED_BY,
	AUDIT_MODIFY_DATE,
	CODE,
	CREATE_DT,
	MODIFYING_USER,
	STATUS_SEQUENCE,
	CUSTOMER_ORDER_ID,
	ODS_CREATE_DATE,
	ODS_MODIFY_DATE,
	DELETED_IND
from	RAX_APP_USER.I$_SAS_ORD_STATUS_STG1391001
where	AUDIT_CREATED_BY is null



&


/*-----------------------------------------------*/
/* TASK No. 26 */
/* insert Not Null errors */

insert into RAX_APP_USER.E$_SAS_ORD_STATUS_STG1391001
(
	ODI_PK,
	ODI_SESS_NO,
	ODI_ROW_ID,
	ODI_ERR_TYPE,
	ODI_ERR_MESS,
	ODI_CHECK_DATE,
	ODI_ORIGIN,
	ODI_CONS_NAME,
	ODI_CONS_TYPE,
	ORDER_STATUS_ID,
	AUDIT_CREATE_DATE,
	AUDIT_CREATED_BY,
	AUDIT_MODIFIED_BY,
	AUDIT_MODIFY_DATE,
	CODE,
	CREATE_DT,
	MODIFYING_USER,
	STATUS_SEQUENCE,
	CUSTOMER_ORDER_ID,
	ODS_CREATE_DATE,
	ODS_MODIFY_DATE,
	DELETED_IND
)
select
	SYS_GUID(),
	:v_sess_no, 
	rowid,
	'F', 
	'ODI-15066: The column AUDIT_MODIFIED_BY cannot be null.',
	sysdate,
	'(1391001)ODS_Project.LOAD_SAS_ORDER_STATUS_STG_INT',
	'AUDIT_MODIFIED_BY',
	'NN',	
	ORDER_STATUS_ID,
	AUDIT_CREATE_DATE,
	AUDIT_CREATED_BY,
	AUDIT_MODIFIED_BY,
	AUDIT_MODIFY_DATE,
	CODE,
	CREATE_DT,
	MODIFYING_USER,
	STATUS_SEQUENCE,
	CUSTOMER_ORDER_ID,
	ODS_CREATE_DATE,
	ODS_MODIFY_DATE,
	DELETED_IND
from	RAX_APP_USER.I$_SAS_ORD_STATUS_STG1391001
where	AUDIT_MODIFIED_BY is null



&


/*-----------------------------------------------*/
/* TASK No. 27 */
/* insert Not Null errors */

insert into RAX_APP_USER.E$_SAS_ORD_STATUS_STG1391001
(
	ODI_PK,
	ODI_SESS_NO,
	ODI_ROW_ID,
	ODI_ERR_TYPE,
	ODI_ERR_MESS,
	ODI_CHECK_DATE,
	ODI_ORIGIN,
	ODI_CONS_NAME,
	ODI_CONS_TYPE,
	ORDER_STATUS_ID,
	AUDIT_CREATE_DATE,
	AUDIT_CREATED_BY,
	AUDIT_MODIFIED_BY,
	AUDIT_MODIFY_DATE,
	CODE,
	CREATE_DT,
	MODIFYING_USER,
	STATUS_SEQUENCE,
	CUSTOMER_ORDER_ID,
	ODS_CREATE_DATE,
	ODS_MODIFY_DATE,
	DELETED_IND
)
select
	SYS_GUID(),
	:v_sess_no, 
	rowid,
	'F', 
	'ODI-15066: The column AUDIT_MODIFY_DATE cannot be null.',
	sysdate,
	'(1391001)ODS_Project.LOAD_SAS_ORDER_STATUS_STG_INT',
	'AUDIT_MODIFY_DATE',
	'NN',	
	ORDER_STATUS_ID,
	AUDIT_CREATE_DATE,
	AUDIT_CREATED_BY,
	AUDIT_MODIFIED_BY,
	AUDIT_MODIFY_DATE,
	CODE,
	CREATE_DT,
	MODIFYING_USER,
	STATUS_SEQUENCE,
	CUSTOMER_ORDER_ID,
	ODS_CREATE_DATE,
	ODS_MODIFY_DATE,
	DELETED_IND
from	RAX_APP_USER.I$_SAS_ORD_STATUS_STG1391001
where	AUDIT_MODIFY_DATE is null



&


/*-----------------------------------------------*/
/* TASK No. 28 */
/* insert Not Null errors */

insert into RAX_APP_USER.E$_SAS_ORD_STATUS_STG1391001
(
	ODI_PK,
	ODI_SESS_NO,
	ODI_ROW_ID,
	ODI_ERR_TYPE,
	ODI_ERR_MESS,
	ODI_CHECK_DATE,
	ODI_ORIGIN,
	ODI_CONS_NAME,
	ODI_CONS_TYPE,
	ORDER_STATUS_ID,
	AUDIT_CREATE_DATE,
	AUDIT_CREATED_BY,
	AUDIT_MODIFIED_BY,
	AUDIT_MODIFY_DATE,
	CODE,
	CREATE_DT,
	MODIFYING_USER,
	STATUS_SEQUENCE,
	CUSTOMER_ORDER_ID,
	ODS_CREATE_DATE,
	ODS_MODIFY_DATE,
	DELETED_IND
)
select
	SYS_GUID(),
	:v_sess_no, 
	rowid,
	'F', 
	'ODI-15066: The column CODE cannot be null.',
	sysdate,
	'(1391001)ODS_Project.LOAD_SAS_ORDER_STATUS_STG_INT',
	'CODE',
	'NN',	
	ORDER_STATUS_ID,
	AUDIT_CREATE_DATE,
	AUDIT_CREATED_BY,
	AUDIT_MODIFIED_BY,
	AUDIT_MODIFY_DATE,
	CODE,
	CREATE_DT,
	MODIFYING_USER,
	STATUS_SEQUENCE,
	CUSTOMER_ORDER_ID,
	ODS_CREATE_DATE,
	ODS_MODIFY_DATE,
	DELETED_IND
from	RAX_APP_USER.I$_SAS_ORD_STATUS_STG1391001
where	CODE is null



&


/*-----------------------------------------------*/
/* TASK No. 29 */
/* insert Not Null errors */

insert into RAX_APP_USER.E$_SAS_ORD_STATUS_STG1391001
(
	ODI_PK,
	ODI_SESS_NO,
	ODI_ROW_ID,
	ODI_ERR_TYPE,
	ODI_ERR_MESS,
	ODI_CHECK_DATE,
	ODI_ORIGIN,
	ODI_CONS_NAME,
	ODI_CONS_TYPE,
	ORDER_STATUS_ID,
	AUDIT_CREATE_DATE,
	AUDIT_CREATED_BY,
	AUDIT_MODIFIED_BY,
	AUDIT_MODIFY_DATE,
	CODE,
	CREATE_DT,
	MODIFYING_USER,
	STATUS_SEQUENCE,
	CUSTOMER_ORDER_ID,
	ODS_CREATE_DATE,
	ODS_MODIFY_DATE,
	DELETED_IND
)
select
	SYS_GUID(),
	:v_sess_no, 
	rowid,
	'F', 
	'ODI-15066: The column CREATE_DT cannot be null.',
	sysdate,
	'(1391001)ODS_Project.LOAD_SAS_ORDER_STATUS_STG_INT',
	'CREATE_DT',
	'NN',	
	ORDER_STATUS_ID,
	AUDIT_CREATE_DATE,
	AUDIT_CREATED_BY,
	AUDIT_MODIFIED_BY,
	AUDIT_MODIFY_DATE,
	CODE,
	CREATE_DT,
	MODIFYING_USER,
	STATUS_SEQUENCE,
	CUSTOMER_ORDER_ID,
	ODS_CREATE_DATE,
	ODS_MODIFY_DATE,
	DELETED_IND
from	RAX_APP_USER.I$_SAS_ORD_STATUS_STG1391001
where	CREATE_DT is null



&


/*-----------------------------------------------*/
/* TASK No. 30 */
/* insert Not Null errors */

insert into RAX_APP_USER.E$_SAS_ORD_STATUS_STG1391001
(
	ODI_PK,
	ODI_SESS_NO,
	ODI_ROW_ID,
	ODI_ERR_TYPE,
	ODI_ERR_MESS,
	ODI_CHECK_DATE,
	ODI_ORIGIN,
	ODI_CONS_NAME,
	ODI_CONS_TYPE,
	ORDER_STATUS_ID,
	AUDIT_CREATE_DATE,
	AUDIT_CREATED_BY,
	AUDIT_MODIFIED_BY,
	AUDIT_MODIFY_DATE,
	CODE,
	CREATE_DT,
	MODIFYING_USER,
	STATUS_SEQUENCE,
	CUSTOMER_ORDER_ID,
	ODS_CREATE_DATE,
	ODS_MODIFY_DATE,
	DELETED_IND
)
select
	SYS_GUID(),
	:v_sess_no, 
	rowid,
	'F', 
	'ODI-15066: The column STATUS_SEQUENCE cannot be null.',
	sysdate,
	'(1391001)ODS_Project.LOAD_SAS_ORDER_STATUS_STG_INT',
	'STATUS_SEQUENCE',
	'NN',	
	ORDER_STATUS_ID,
	AUDIT_CREATE_DATE,
	AUDIT_CREATED_BY,
	AUDIT_MODIFIED_BY,
	AUDIT_MODIFY_DATE,
	CODE,
	CREATE_DT,
	MODIFYING_USER,
	STATUS_SEQUENCE,
	CUSTOMER_ORDER_ID,
	ODS_CREATE_DATE,
	ODS_MODIFY_DATE,
	DELETED_IND
from	RAX_APP_USER.I$_SAS_ORD_STATUS_STG1391001
where	STATUS_SEQUENCE is null



&


/*-----------------------------------------------*/
/* TASK No. 31 */
/* insert Not Null errors */

insert into RAX_APP_USER.E$_SAS_ORD_STATUS_STG1391001
(
	ODI_PK,
	ODI_SESS_NO,
	ODI_ROW_ID,
	ODI_ERR_TYPE,
	ODI_ERR_MESS,
	ODI_CHECK_DATE,
	ODI_ORIGIN,
	ODI_CONS_NAME,
	ODI_CONS_TYPE,
	ORDER_STATUS_ID,
	AUDIT_CREATE_DATE,
	AUDIT_CREATED_BY,
	AUDIT_MODIFIED_BY,
	AUDIT_MODIFY_DATE,
	CODE,
	CREATE_DT,
	MODIFYING_USER,
	STATUS_SEQUENCE,
	CUSTOMER_ORDER_ID,
	ODS_CREATE_DATE,
	ODS_MODIFY_DATE,
	DELETED_IND
)
select
	SYS_GUID(),
	:v_sess_no, 
	rowid,
	'F', 
	'ODI-15066: The column CUSTOMER_ORDER_ID cannot be null.',
	sysdate,
	'(1391001)ODS_Project.LOAD_SAS_ORDER_STATUS_STG_INT',
	'CUSTOMER_ORDER_ID',
	'NN',	
	ORDER_STATUS_ID,
	AUDIT_CREATE_DATE,
	AUDIT_CREATED_BY,
	AUDIT_MODIFIED_BY,
	AUDIT_MODIFY_DATE,
	CODE,
	CREATE_DT,
	MODIFYING_USER,
	STATUS_SEQUENCE,
	CUSTOMER_ORDER_ID,
	ODS_CREATE_DATE,
	ODS_MODIFY_DATE,
	DELETED_IND
from	RAX_APP_USER.I$_SAS_ORD_STATUS_STG1391001
where	CUSTOMER_ORDER_ID is null



&


/*-----------------------------------------------*/
/* TASK No. 32 */
/* create index on error table */

 
/* FLOW CONTROL CREATE INDEX ON THE E$TABLE */
-- create index 	RAX_APP_USER.E$_SAS_ORD_STATUS_STG1391001
-- on	RAX_APP_USER.E$_SAS_ORD_STATUS_STG1391001 (ODI_ROW_ID)

BEGIN
  EXECUTE IMMEDIATE 'create index RAX_APP_USER.E$_SAS_ORD_STATUS_STG1391001
on   RAX_APP_USER.E$_SAS_ORD_STATUS_STG1391001 (ODI_ROW_ID)';
EXCEPTION
  WHEN OTHERS THEN
   -- Handle the case where the identifier is too long (ORA-00972)
   IF SQLCODE = -972 or  SQLCODE = -1408 or SQLCODE = -955  THEN
     DBMS_OUTPUT.PUT_LINE('Identifier is too long. Skipping creation of index.');
   ELSE
     RAISE;
   END IF;
END;

&


/*-----------------------------------------------*/
/* TASK No. 33 */
/* delete errors from controlled table */

delete from	RAX_APP_USER.I$_SAS_ORD_STATUS_STG1391001  T
where	exists 	(
		select	1
		from	RAX_APP_USER.E$_SAS_ORD_STATUS_STG1391001 E
		where ODI_SESS_NO = :v_sess_no
		and T.rowid = E.ODI_ROW_ID
		)


&


/*-----------------------------------------------*/
/* TASK No. 34 */
/* insert check sum into check table */

insert into RAX_APP_USER.SNP_CHECK_TAB
(
	SCHEMA_NAME,
	RESOURCE_NAME,
	FULL_RES_NAME,
	ERR_TYPE,
	ERR_MESS,
	CHECK_DATE,
	ORIGIN,
	CONS_NAME,
	CONS_TYPE,
	ERR_COUNT
)
select	
	'ODS_STAGE',
	'SAS_ORD_STATUS_STG',
	'ODS_STAGE.SAS_ORDER_STATUS_STG1391001',
	E.ODI_ERR_TYPE,
	E.ODI_ERR_MESS,
	E.ODI_CHECK_DATE,
	E.ODI_ORIGIN,
	E.ODI_CONS_NAME,
	E.ODI_CONS_TYPE,
	count(1) 
from	RAX_APP_USER.E$_SAS_ORD_STATUS_STG1391001 E
where	E.ODI_ERR_TYPE	= 'F'
and	E.ODI_ORIGIN 	= '(1391001)ODS_Project.LOAD_SAS_ORDER_STATUS_STG_INT'
group by	E.ODI_ERR_TYPE,
	E.ODI_ERR_MESS,
	E.ODI_CHECK_DATE,
	E.ODI_ORIGIN,
	E.ODI_CONS_NAME,
	E.ODI_CONS_TYPE


&


/*-----------------------------------------------*/
/* TASK No. 35 */
/* Merge Rows */

merge into	ODS_STAGE.SAS_ORDER_STATUS_STG T
using	RAX_APP_USER.I$_SAS_ORD_STATUS_STG1391001 S
on	(
		T.ORDER_STATUS_ID=S.ORDER_STATUS_ID
	)
when matched
then update set
	T.AUDIT_CREATE_DATE	= S.AUDIT_CREATE_DATE,
	T.AUDIT_CREATED_BY	= S.AUDIT_CREATED_BY,
	T.AUDIT_MODIFIED_BY	= S.AUDIT_MODIFIED_BY,
	T.AUDIT_MODIFY_DATE	= S.AUDIT_MODIFY_DATE,
	T.CODE	= S.CODE,
	T.CREATE_DT	= S.CREATE_DT,
	T.MODIFYING_USER	= S.MODIFYING_USER,
	T.STATUS_SEQUENCE	= S.STATUS_SEQUENCE,
	T.CUSTOMER_ORDER_ID	= S.CUSTOMER_ORDER_ID,
	T.DELETED_IND	= S.DELETED_IND
	,          T.ODS_MODIFY_DATE	= sysdate
when not matched
then insert
	(
	T.ORDER_STATUS_ID,
	T.AUDIT_CREATE_DATE,
	T.AUDIT_CREATED_BY,
	T.AUDIT_MODIFIED_BY,
	T.AUDIT_MODIFY_DATE,
	T.CODE,
	T.CREATE_DT,
	T.MODIFYING_USER,
	T.STATUS_SEQUENCE,
	T.CUSTOMER_ORDER_ID,
	T.DELETED_IND
	,           T.ODS_CREATE_DATE,
	T.ODS_MODIFY_DATE
	)
values
	(
	S.ORDER_STATUS_ID,
	S.AUDIT_CREATE_DATE,
	S.AUDIT_CREATED_BY,
	S.AUDIT_MODIFIED_BY,
	S.AUDIT_MODIFY_DATE,
	S.CODE,
	S.CREATE_DT,
	S.MODIFYING_USER,
	S.STATUS_SEQUENCE,
	S.CUSTOMER_ORDER_ID,
	S.DELETED_IND
	,           sysdate,
	sysdate
	)

&


/*-----------------------------------------------*/
/* TASK No. 36 */
/* Commit transaction */

/*commit*/


/*-----------------------------------------------*/
/* TASK No. 37 */
/* Drop flow table */

-- drop table RAX_APP_USER.I$_SAS_ORD_STATUS_STG1391001

BEGIN
  EXECUTE IMMEDIATE 'drop table RAX_APP_USER.I$_SAS_ORD_STATUS_STG1391001';
EXCEPTION
  WHEN OTHERS THEN
   IF SQLCODE != -942 THEN
     RAISE;
   END IF;
END;

&


/*-----------------------------------------------*/
/* TASK No. 1000008 */
/* Drop work table */

-- drop table RAX_APP_USER.C$_0SAS_ORD_STATUS_STG purge


BEGIN
  EXECUTE IMMEDIATE 'drop table RAX_APP_USER.C$_0SAS_ORD_STATUS_STG purge';
EXCEPTION
  WHEN OTHERS THEN
   IF SQLCODE != -942 THEN
     RAISE;
   END IF;
END;

&


/*-----------------------------------------------*/
/* TASK No. 38 */
/* Update CDC Load Status */

UPDATE ODS_OWN.ODS_CDC_LOAD_STATUS
SET LAST_CDC_COMPLETION_DATE=TO_DATE(
             SUBSTR(:v_sess_beg, 1, 19), 'RRRR-MM-DD HH24:MI:SS')
+ nvl((TIMEZONE_OFFSET/24), 0) 
WHERE ODS_TABLE_NAME=:v_cdc_load_table_name
AND CONTEXT_NAME = :v_env

/*
UPDATE ODS_OWN.ODS_CDC_LOAD_STATUS
SET LAST_CDC_COMPLETION_DATE=TO_DATE(
             SUBSTR(:v_sess_beg, 1, 19), 'RRRR-MM-DD HH24:MI:SS')
WHERE ODS_TABLE_NAME=:v_cdc_load_table_name
AND CONTEXT_NAME = :v_env
*/

&


/*-----------------------------------------------*/
/* TASK No. 39 */
/* Insert CDC Audit Record */

INSERT INTO RAX_APP_USER.ODS_CDC_LOAD_STATUS_AUDIT
(TABLE_NAME,
SESS_NO,                      
SESS_NAME,                    
SCEN_VERSION,                 
SESS_BEG,                     
ORIG_LAST_CDC_COMPLETION_DATE,
OVERLAP,
CREATE_DATE,
CONTEXT_NAME,
TIMEZONE_OFFSET              
)
select 
:v_cdc_load_table_name
,:v_sess_no
,'LOAD_SAS_ORDER_STATUS_PKG'
,'003'
,TO_DATE(SUBSTR(:v_sess_beg, 1, 19), 'RRRR-MM-DD HH24:MI:SS')
,TO_DATE (SUBSTR(:v_cdc_load_date, 1, 19),'YYYY-MM-DD HH24:MI:SS')
,:v_cdc_overlap
,SYSDATE
,:v_env
,TIMEZONE_OFFSET
from 
ODS_OWN.ODS_CDC_LOAD_STATUS
WHERE ODS_TABLE_NAME=:v_cdc_load_table_name
AND CONTEXT_NAME = :v_env

/*
INSERT INTO RAX_APP_USER.ODS_CDC_LOAD_STATUS_AUDIT
(TABLE_NAME,
SESS_NO,                      
SESS_NAME,                    
SCEN_VERSION,                 
SESS_BEG,                     
ORIG_LAST_CDC_COMPLETION_DATE,
OVERLAP,
CREATE_DATE,
CONTEXT_NAME              
)
values (
:v_cdc_load_table_name,
:v_sess_no,
'LOAD_SAS_ORDER_STATUS_PKG',
'003',
TO_DATE(
             SUBSTR(:v_sess_beg, 1, 19), 'RRRR-MM-DD HH24:MI:SS'),
TO_DATE (SUBSTR (:v_cdc_load_date, 1, 19),
                           'YYYY-MM-DD HH24:MI:SS'
                          )
,:v_cdc_overlap,
SYSDATE,
 :v_env)
*/


&


/*-----------------------------------------------*/
