/* TASK No. 1 */

/* NONE or SET VARIABLE STATEMENT FOUND, CHECK ODI TASK NO. 1 */




/*-----------------------------------------------*/
/* TASK No. 2 */

/* SELECT STATEMENT FOUND, CHECK ODI TASK NO. 2 */




/*-----------------------------------------------*/
/* TASK No. 3 */

/* SELECT STATEMENT FOUND, CHECK ODI TASK NO. 3 */




/*-----------------------------------------------*/
/* TASK No. 4 */
/* Drop work table */

-- drop table RAX_APP_USER.C$_0SAS_PAR_GUAR_STG purge

-- &


/*-----------------------------------------------*/
/* TASK No. 5 */
/* Create work table */

-- create table RAX_APP_USER.C$_0SAS_PAR_GUAR_STG
-- (
-- 	C1_PARENT_GUARDIAN_ID	NUMBER(19) NULL,
-- 	C2_ADDRESS_LINE_1	VARCHAR2(50) NULL,
-- 	C3_ADDRESS_LINE_2	VARCHAR2(50) NULL,
-- 	C4_AUDIT_CREATE_DATE	TIMESTAMP(6) NULL,
-- 	C5_AUDIT_CREATED_BY	VARCHAR2(255) NULL,
-- 	C6_AUDIT_MODIFIED_BY	VARCHAR2(255) NULL,
-- 	C7_AUDIT_MODIFY_DATE	TIMESTAMP(6) NULL,
-- 	C8_CITY	VARCHAR2(30) NULL,
-- 	C9_COUNTRY	VARCHAR2(2) NULL,
-- 	C10_COURTESY_TITLE	VARCHAR2(50) NULL,
-- 	C11_DAYTIME_PHONE	VARCHAR2(20) NULL,
-- 	C12_EMAIL_ADDRESS	VARCHAR2(320) NULL,
-- 	C13_EMERGENCY_CONTACT	NUMBER(1) NULL,
-- 	C14_FIRST_NAME	VARCHAR2(50) NULL,
-- 	C15_LAST_NAME	VARCHAR2(50) NULL,
-- 	C16_MIDDLE_NAME	VARCHAR2(50) NULL,
-- 	C17_EVENING_PHONE	VARCHAR2(20) NULL,
-- 	C18_POSTAL_CODE	VARCHAR2(10) NULL,
-- 	C19_RELATIONSHIP	VARCHAR2(50) NULL,
-- 	C20_STATE	VARCHAR2(10) NULL,
-- 	C21_SUBJECT_ID	NUMBER(19) NULL
-- )
-- NOLOGGING

-- &


/*-----------------------------------------------*/
/* TASK No. 6 */
/* Load data */

/* SOURCE CODE */


-- select	
-- 	PARENT_GUARDIAN.PARENT_GUARDIAN_ID	   C1_PARENT_GUARDIAN_ID,
-- 	PARENT_GUARDIAN.ADDRESS_LINE_1	   C2_ADDRESS_LINE_1,
-- 	PARENT_GUARDIAN.ADDRESS_LINE_2	   C3_ADDRESS_LINE_2,
-- 	PARENT_GUARDIAN.AUDIT_CREATE_DATE	   C4_AUDIT_CREATE_DATE,
-- 	PARENT_GUARDIAN.AUDIT_CREATED_BY	   C5_AUDIT_CREATED_BY,
-- 	PARENT_GUARDIAN.AUDIT_MODIFIED_BY	   C6_AUDIT_MODIFIED_BY,
-- 	PARENT_GUARDIAN.AUDIT_MODIFY_DATE	   C7_AUDIT_MODIFY_DATE,
-- 	PARENT_GUARDIAN.CITY	   C8_CITY,
-- 	PARENT_GUARDIAN.COUNTRY	   C9_COUNTRY,
-- 	PARENT_GUARDIAN.COURTESY_TITLE	   C10_COURTESY_TITLE,
-- 	PARENT_GUARDIAN.DAYTIME_PHONE	   C11_DAYTIME_PHONE,
-- 	PARENT_GUARDIAN.EMAIL_ADDRESS	   C12_EMAIL_ADDRESS,
-- 	PARENT_GUARDIAN.EMERGENCY_CONTACT	   C13_EMERGENCY_CONTACT,
-- 	PARENT_GUARDIAN.FIRST_NAME	   C14_FIRST_NAME,
-- 	PARENT_GUARDIAN.LAST_NAME	   C15_LAST_NAME,
-- 	PARENT_GUARDIAN.MIDDLE_NAME	   C16_MIDDLE_NAME,
-- 	PARENT_GUARDIAN.EVENING_PHONE	   C17_EVENING_PHONE,
-- 	PARENT_GUARDIAN.POSTAL_CODE	   C18_POSTAL_CODE,
-- 	PARENT_GUARDIAN.RELATIONSHIP	   C19_RELATIONSHIP,
-- 	PARENT_GUARDIAN.STATE	   C20_STATE,
-- 	PARENT_GUARDIAN.SUBJECT_ID	   C21_SUBJECT_ID
-- from	SAS_SIT_OWN.PARENT_GUARDIAN   PARENT_GUARDIAN
-- where	(1=1)
-- And (nvl(PARENT_GUARDIAN.AUDIT_MODIFY_DATE,PARENT_GUARDIAN.AUDIT_CREATE_DATE) >= TO_DATE(SUBSTR(:v_cdc_load_date, 1, 19), 'YYYY-MM-DD HH24:MI:SS')  -:v_cdc_overlap
-- )







-- &

/* TARGET CODE */
-- insert /*+ append */ into RAX_APP_USER.C$_0SAS_PAR_GUAR_STG
-- (
-- 	C1_PARENT_GUARDIAN_ID,
-- 	C2_ADDRESS_LINE_1,
-- 	C3_ADDRESS_LINE_2,
-- 	C4_AUDIT_CREATE_DATE,
-- 	C5_AUDIT_CREATED_BY,
-- 	C6_AUDIT_MODIFIED_BY,
-- 	C7_AUDIT_MODIFY_DATE,
-- 	C8_CITY,
-- 	C9_COUNTRY,
-- 	C10_COURTESY_TITLE,
-- 	C11_DAYTIME_PHONE,
-- 	C12_EMAIL_ADDRESS,
-- 	C13_EMERGENCY_CONTACT,
-- 	C14_FIRST_NAME,
-- 	C15_LAST_NAME,
-- 	C16_MIDDLE_NAME,
-- 	C17_EVENING_PHONE,
-- 	C18_POSTAL_CODE,
-- 	C19_RELATIONSHIP,
-- 	C20_STATE,
-- 	C21_SUBJECT_ID
-- )
-- values
-- (
-- 	:C1_PARENT_GUARDIAN_ID,
-- 	:C2_ADDRESS_LINE_1,
-- 	:C3_ADDRESS_LINE_2,
-- 	:C4_AUDIT_CREATE_DATE,
-- 	:C5_AUDIT_CREATED_BY,
-- 	:C6_AUDIT_MODIFIED_BY,
-- 	:C7_AUDIT_MODIFY_DATE,
-- 	:C8_CITY,
-- 	:C9_COUNTRY,
-- 	:C10_COURTESY_TITLE,
-- 	:C11_DAYTIME_PHONE,
-- 	:C12_EMAIL_ADDRESS,
-- 	:C13_EMERGENCY_CONTACT,
-- 	:C14_FIRST_NAME,
-- 	:C15_LAST_NAME,
-- 	:C16_MIDDLE_NAME,
-- 	:C17_EVENING_PHONE,
-- 	:C18_POSTAL_CODE,
-- 	:C19_RELATIONSHIP,
-- 	:C20_STATE,
-- 	:C21_SUBJECT_ID
-- )

-- &


/*-----------------------------------------------*/
/* TASK No. 7 */
/* Analyze work table */



BEGIN
DBMS_STATS.GATHER_TABLE_STATS (
    ownname =>	'RAX_APP_USER',
    tabname =>	'C$_0SAS_PAR_GUAR_STG',
    estimate_percent =>	DBMS_STATS.AUTO_SAMPLE_SIZE
);
END;




&


/*-----------------------------------------------*/
/* TASK No. 9 */
/* Set vID */

/* NONE or SET VARIABLE STATEMENT FOUND, CHECK ODI TASK NO. 9 */




/*-----------------------------------------------*/
/* TASK No. 10 */
/* Drop flow table */

-- drop table RAX_APP_USER.I$_SAS_PAR_GUAR_STG1392001

BEGIN
  EXECUTE IMMEDIATE 'drop table RAX_APP_USER.I$_SAS_PAR_GUAR_STG1392001';
EXCEPTION
  WHEN OTHERS THEN
   IF SQLCODE != -942 THEN
     RAISE;
   END IF;
END;


&


/*-----------------------------------------------*/
/* TASK No. 11 */
/* Create flow table I$ */

create table RAX_APP_USER.I$_SAS_PAR_GUAR_STG1392001
(
	PARENT_GUARDIAN_ID	NUMBER(19) NULL,
	ADDRESS_LINE_1	VARCHAR2(50) NULL,
	ADDRESS_LINE_2	VARCHAR2(50) NULL,
	AUDIT_CREATE_DATE	TIMESTAMP(6) NULL,
	AUDIT_CREATED_BY	VARCHAR2(255) NULL,
	AUDIT_MODIFIED_BY	VARCHAR2(255) NULL,
	AUDIT_MODIFY_DATE	TIMESTAMP(6) NULL,
	CITY	VARCHAR2(30) NULL,
	COUNTRY	VARCHAR2(2) NULL,
	COURTESY_TITLE	VARCHAR2(50) NULL,
	DAYTIME_PHONE	VARCHAR2(20) NULL,
	EMAIL_ADDRESS	VARCHAR2(320) NULL,
	EMERGENCY_CONTACT	NUMBER(1) NULL,
	FIRST_NAME	VARCHAR2(50) NULL,
	LAST_NAME	VARCHAR2(50) NULL,
	MIDDLE_NAME	VARCHAR2(50) NULL,
	EVENING_PHONE	VARCHAR2(20) NULL,
	POSTAL_CODE	VARCHAR2(10) NULL,
	RELATIONSHIP	VARCHAR2(50) NULL,
	STATE	VARCHAR2(10) NULL,
	SUBJECT_ID	NUMBER(19) NULL,
	ODS_CREATE_DATE	DATE NULL,
	ODS_MODIFY_DATE	DATE NULL
	,IND_UPDATE		char(1)
)
NOLOGGING

&


/*-----------------------------------------------*/
/* TASK No. 12 */
/* Insert flow into I$ table */

/* DETECTION_STRATEGY = NOT_EXISTS */
 


  


insert into	RAX_APP_USER.I$_SAS_PAR_GUAR_STG1392001
(
	PARENT_GUARDIAN_ID,
	ADDRESS_LINE_1,
	ADDRESS_LINE_2,
	AUDIT_CREATE_DATE,
	AUDIT_CREATED_BY,
	AUDIT_MODIFIED_BY,
	AUDIT_MODIFY_DATE,
	CITY,
	COUNTRY,
	COURTESY_TITLE,
	DAYTIME_PHONE,
	EMAIL_ADDRESS,
	EMERGENCY_CONTACT,
	FIRST_NAME,
	LAST_NAME,
	MIDDLE_NAME,
	EVENING_PHONE,
	POSTAL_CODE,
	RELATIONSHIP,
	STATE,
	SUBJECT_ID,
	IND_UPDATE
)
select 
PARENT_GUARDIAN_ID,
	ADDRESS_LINE_1,
	ADDRESS_LINE_2,
	AUDIT_CREATE_DATE,
	AUDIT_CREATED_BY,
	AUDIT_MODIFIED_BY,
	AUDIT_MODIFY_DATE,
	CITY,
	COUNTRY,
	COURTESY_TITLE,
	DAYTIME_PHONE,
	EMAIL_ADDRESS,
	EMERGENCY_CONTACT,
	FIRST_NAME,
	LAST_NAME,
	MIDDLE_NAME,
	EVENING_PHONE,
	POSTAL_CODE,
	RELATIONSHIP,
	STATE,
	SUBJECT_ID,
	IND_UPDATE
 from (


select 	 
	
	C1_PARENT_GUARDIAN_ID PARENT_GUARDIAN_ID,
	C2_ADDRESS_LINE_1 ADDRESS_LINE_1,
	C3_ADDRESS_LINE_2 ADDRESS_LINE_2,
	C4_AUDIT_CREATE_DATE AUDIT_CREATE_DATE,
	C5_AUDIT_CREATED_BY AUDIT_CREATED_BY,
	C6_AUDIT_MODIFIED_BY AUDIT_MODIFIED_BY,
	C7_AUDIT_MODIFY_DATE AUDIT_MODIFY_DATE,
	C8_CITY CITY,
	C9_COUNTRY COUNTRY,
	C10_COURTESY_TITLE COURTESY_TITLE,
	C11_DAYTIME_PHONE DAYTIME_PHONE,
	C12_EMAIL_ADDRESS EMAIL_ADDRESS,
	C13_EMERGENCY_CONTACT EMERGENCY_CONTACT,
	C14_FIRST_NAME FIRST_NAME,
	C15_LAST_NAME LAST_NAME,
	C16_MIDDLE_NAME MIDDLE_NAME,
	C17_EVENING_PHONE EVENING_PHONE,
	C18_POSTAL_CODE POSTAL_CODE,
	C19_RELATIONSHIP RELATIONSHIP,
	C20_STATE STATE,
	C21_SUBJECT_ID SUBJECT_ID,

	'I' IND_UPDATE

from	RAX_APP_USER.C$_0SAS_PAR_GUAR_STG
where	(1=1)






) S
where NOT EXISTS 
	( select 1 from ODS_STAGE.SAS_PARENT_GUARDIAN_STG T
	where	T.PARENT_GUARDIAN_ID	= S.PARENT_GUARDIAN_ID 
		 and ((T.ADDRESS_LINE_1 = S.ADDRESS_LINE_1) or (T.ADDRESS_LINE_1 IS NULL and S.ADDRESS_LINE_1 IS NULL)) and
		((T.ADDRESS_LINE_2 = S.ADDRESS_LINE_2) or (T.ADDRESS_LINE_2 IS NULL and S.ADDRESS_LINE_2 IS NULL)) and
		((T.AUDIT_CREATE_DATE = S.AUDIT_CREATE_DATE) or (T.AUDIT_CREATE_DATE IS NULL and S.AUDIT_CREATE_DATE IS NULL)) and
		((T.AUDIT_CREATED_BY = S.AUDIT_CREATED_BY) or (T.AUDIT_CREATED_BY IS NULL and S.AUDIT_CREATED_BY IS NULL)) and
		((T.AUDIT_MODIFIED_BY = S.AUDIT_MODIFIED_BY) or (T.AUDIT_MODIFIED_BY IS NULL and S.AUDIT_MODIFIED_BY IS NULL)) and
		((T.AUDIT_MODIFY_DATE = S.AUDIT_MODIFY_DATE) or (T.AUDIT_MODIFY_DATE IS NULL and S.AUDIT_MODIFY_DATE IS NULL)) and
		((T.CITY = S.CITY) or (T.CITY IS NULL and S.CITY IS NULL)) and
		((T.COUNTRY = S.COUNTRY) or (T.COUNTRY IS NULL and S.COUNTRY IS NULL)) and
		((T.COURTESY_TITLE = S.COURTESY_TITLE) or (T.COURTESY_TITLE IS NULL and S.COURTESY_TITLE IS NULL)) and
		((T.DAYTIME_PHONE = S.DAYTIME_PHONE) or (T.DAYTIME_PHONE IS NULL and S.DAYTIME_PHONE IS NULL)) and
		((T.EMAIL_ADDRESS = S.EMAIL_ADDRESS) or (T.EMAIL_ADDRESS IS NULL and S.EMAIL_ADDRESS IS NULL)) and
		((T.EMERGENCY_CONTACT = S.EMERGENCY_CONTACT) or (T.EMERGENCY_CONTACT IS NULL and S.EMERGENCY_CONTACT IS NULL)) and
		((T.FIRST_NAME = S.FIRST_NAME) or (T.FIRST_NAME IS NULL and S.FIRST_NAME IS NULL)) and
		((T.LAST_NAME = S.LAST_NAME) or (T.LAST_NAME IS NULL and S.LAST_NAME IS NULL)) and
		((T.MIDDLE_NAME = S.MIDDLE_NAME) or (T.MIDDLE_NAME IS NULL and S.MIDDLE_NAME IS NULL)) and
		((T.EVENING_PHONE = S.EVENING_PHONE) or (T.EVENING_PHONE IS NULL and S.EVENING_PHONE IS NULL)) and
		((T.POSTAL_CODE = S.POSTAL_CODE) or (T.POSTAL_CODE IS NULL and S.POSTAL_CODE IS NULL)) and
		((T.RELATIONSHIP = S.RELATIONSHIP) or (T.RELATIONSHIP IS NULL and S.RELATIONSHIP IS NULL)) and
		((T.STATE = S.STATE) or (T.STATE IS NULL and S.STATE IS NULL)) and
		((T.SUBJECT_ID = S.SUBJECT_ID) or (T.SUBJECT_ID IS NULL and S.SUBJECT_ID IS NULL))
        )

  
  

  



&


/*-----------------------------------------------*/
/* TASK No. 13 */
/* Analyze integration table */



begin
    dbms_stats.gather_table_stats(
	ownname => 'RAX_APP_USER',
	tabname => 'I$_SAS_PAR_GUAR_STG1392001',
	estimate_percent => dbms_stats.auto_sample_size
    );
end;



&


/*-----------------------------------------------*/
/* TASK No. 14 */
/* Create Index on flow table */

-- create index	RAX_APP_USER.I$_SAS_PAR_GUAR_STG1392001
-- on		RAX_APP_USER.I$_SAS_PAR_GUAR_STG1392001 (PARENT_GUARDIAN_ID)
-- NOLOGGING

BEGIN
  EXECUTE IMMEDIATE 'create index RAX_APP_USER.I$_SAS_PAR_GUAR_STG1392001
on   RAX_APP_USER.I$_SAS_PAR_GUAR_STG1392001 (PARENT_GUARDIAN_ID)';
EXCEPTION
  WHEN OTHERS THEN
   -- Handle the case where the identifier is too long (ORA-00972)
   IF SQLCODE = -972 or  SQLCODE = -1408 or SQLCODE = -955  THEN
     DBMS_OUTPUT.PUT_LINE('Identifier is too long. Skipping creation of index.');
   ELSE
     RAISE;
   END IF;
END;

&


/*-----------------------------------------------*/
/* TASK No. 15 */
/* create check table */


BEGIN
  EXECUTE IMMEDIATE 'drop table RAX_APP_USER.SNP_CHECK_TAB';
EXCEPTION
  WHEN OTHERS THEN
   IF SQLCODE != -942 THEN
     RAISE;
   END IF;
END;


&


-- create table RAX_APP_USER.SNP_CHECK_TAB
-- (
-- 	CATALOG_NAME	VARCHAR2(100 CHAR) NULL ,
-- 	SCHEMA_NAME	VARCHAR2(100 CHAR) NULL ,
-- 	RESOURCE_NAME	VARCHAR2(100 CHAR) NULL,
-- 	FULL_RES_NAME	VARCHAR2(100 CHAR) NULL,
-- 	ERR_TYPE		VARCHAR2(1 CHAR) NULL,
-- 	ERR_MESS		VARCHAR2(250 CHAR) NULL ,
-- 	CHECK_DATE	DATE NULL,
-- 	ORIGIN		VARCHAR2(100 CHAR) NULL,
-- 	CONS_NAME	VARCHAR2(35 CHAR) NULL,
-- 	CONS_TYPE		VARCHAR2(2 CHAR) NULL,
-- 	ERR_COUNT		NUMBER(10) NULL
-- )
	
BEGIN
   EXECUTE IMMEDIATE '
      create table RAX_APP_USER.SNP_CHECK_TAB
		(
			CATALOG_NAME	VARCHAR2(100 CHAR) NULL ,
			SCHEMA_NAME	VARCHAR2(100 CHAR) NULL ,
			RESOURCE_NAME	VARCHAR2(100 CHAR) NULL,
			FULL_RES_NAME	VARCHAR2(100 CHAR) NULL,
			ERR_TYPE		VARCHAR2(1 CHAR) NULL,
			ERR_MESS		VARCHAR2(250 CHAR) NULL ,
			CHECK_DATE	DATE NULL,
			ORIGIN		VARCHAR2(100 CHAR) NULL,
			CONS_NAME	VARCHAR2(35 CHAR) NULL,
			CONS_TYPE		VARCHAR2(2 CHAR) NULL,
			ERR_COUNT		NUMBER(10) NULL
		)
   ';
END;

&


/*-----------------------------------------------*/
/* TASK No. 16 */
/* delete previous check sum */

delete from	RAX_APP_USER.SNP_CHECK_TAB
where	SCHEMA_NAME	= 'ODS_STAGE'
and	ORIGIN 		= '(1392001)ODS_Project.LOAD_SAS_PARENT_GUARDIAN_STG_INT'
and	ERR_TYPE 		= 'F'


&


/*-----------------------------------------------*/
/* TASK No. 17 */
/* create error table */


BEGIN
  EXECUTE IMMEDIATE 'drop table RAX_APP_USER.E$_SAS_PAR_GUAR_STG1392001';
EXCEPTION
  WHEN OTHERS THEN
   IF SQLCODE != -942 THEN
     RAISE;
   END IF;
END;


&

create table RAX_APP_USER.E$_SAS_PAR_GUAR_STG1392001
(
	ODI_ROW_ID 		UROWID,
	ODI_ERR_TYPE		VARCHAR2(1 CHAR) NULL, 
	ODI_ERR_MESS		VARCHAR2(250 CHAR) NULL,
	ODI_CHECK_DATE	DATE NULL, 
	PARENT_GUARDIAN_ID	NUMBER(19) NULL,
	ADDRESS_LINE_1	VARCHAR2(50) NULL,
	ADDRESS_LINE_2	VARCHAR2(50) NULL,
	AUDIT_CREATE_DATE	TIMESTAMP(6) NULL,
	AUDIT_CREATED_BY	VARCHAR2(255) NULL,
	AUDIT_MODIFIED_BY	VARCHAR2(255) NULL,
	AUDIT_MODIFY_DATE	TIMESTAMP(6) NULL,
	CITY	VARCHAR2(30) NULL,
	COUNTRY	VARCHAR2(2) NULL,
	COURTESY_TITLE	VARCHAR2(50) NULL,
	DAYTIME_PHONE	VARCHAR2(20) NULL,
	EMAIL_ADDRESS	VARCHAR2(320) NULL,
	EMERGENCY_CONTACT	NUMBER(1) NULL,
	FIRST_NAME	VARCHAR2(50) NULL,
	LAST_NAME	VARCHAR2(50) NULL,
	MIDDLE_NAME	VARCHAR2(50) NULL,
	EVENING_PHONE	VARCHAR2(20) NULL,
	POSTAL_CODE	VARCHAR2(10) NULL,
	RELATIONSHIP	VARCHAR2(50) NULL,
	STATE	VARCHAR2(10) NULL,
	SUBJECT_ID	NUMBER(19) NULL,
	ODS_CREATE_DATE	DATE NULL,
	ODS_MODIFY_DATE	DATE NULL,
	ODI_ORIGIN		VARCHAR2(100 CHAR) NULL,
	ODI_CONS_NAME	VARCHAR2(35 CHAR) NULL,
	ODI_CONS_TYPE		VARCHAR2(2 CHAR) NULL,
	ODI_PK			VARCHAR2(32 CHAR) PRIMARY KEY,
	ODI_SESS_NO		VARCHAR2(19 CHAR)
)



&


/*-----------------------------------------------*/
/* TASK No. 18 */
/* delete previous errors */

delete from 	RAX_APP_USER.E$_SAS_PAR_GUAR_STG1392001
where	(ODI_ERR_TYPE = 'S'	and 'F' = 'S')
or	(ODI_ERR_TYPE = 'F'	and ODI_ORIGIN = '(1392001)ODS_Project.LOAD_SAS_PARENT_GUARDIAN_STG_INT')


&


/*-----------------------------------------------*/
/* TASK No. 19 */
/* Create index on PK */

 
/* FLOW CONTROL CREATE THE iNDEX ON THE I$TABLE */
-- create index 	RAX_APP_USER.I$_SAS_PAR_GUAR_STG1392001
-- on	RAX_APP_USER.I$_SAS_PAR_GUAR_STG1392001 (PARENT_GUARDIAN_ID)

BEGIN
  EXECUTE IMMEDIATE 'create index RAX_APP_USER.I$_SAS_PAR_GUAR_STG1392001
on   RAX_APP_USER.I$_SAS_PAR_GUAR_STG1392001 (PARENT_GUARDIAN_ID)';
EXCEPTION
  WHEN OTHERS THEN
   -- Handle the case where the identifier is too long (ORA-00972)
   IF SQLCODE = -972 or  SQLCODE = -1408 or SQLCODE = -955  THEN
     DBMS_OUTPUT.PUT_LINE('Identifier is too long. Skipping creation of index.');
   ELSE
     RAISE;
   END IF;
END;

&


/*-----------------------------------------------*/
/* TASK No. 20 */
/* insert PK errors */

DECLARE
               CheckTable                             VarChar2(60);
               TargetTable                            VarChar2(60);
               VariableCheckTable                     VarChar2(60);

BEGIN
               SELECT 'RAX_APP_USER.I$_SAS_PAR_GUAR_STG' INTO CheckTable FROM DUAL;
               SELECT 'ODS_STAGE.SAS_PARENT_GUARDIAN_STG' INTO TargetTable FROM DUAL;

IF CheckTable = TargetTable THEN
   VariableCheckTable := CheckTable; 
ELSE
   VariableCheckTable := CheckTable || '1392001';
END IF;

execute immediate '
insert into RAX_APP_USER.E$_SAS_PAR_GUAR_STG1392001
(
	ODI_PK,
	ODI_SESS_NO,
	ODI_ROW_ID,
	ODI_ERR_TYPE,
	ODI_ERR_MESS,
	ODI_ORIGIN,
	ODI_CHECK_DATE,
	ODI_CONS_NAME,
	ODI_CONS_TYPE,
	PARENT_GUARDIAN_ID,
	ADDRESS_LINE_1,
	ADDRESS_LINE_2,
	AUDIT_CREATE_DATE,
	AUDIT_CREATED_BY,
	AUDIT_MODIFIED_BY,
	AUDIT_MODIFY_DATE,
	CITY,
	COUNTRY,
	COURTESY_TITLE,
	DAYTIME_PHONE,
	EMAIL_ADDRESS,
	EMERGENCY_CONTACT,
	FIRST_NAME,
	LAST_NAME,
	MIDDLE_NAME,
	EVENING_PHONE,
	POSTAL_CODE,
	RELATIONSHIP,
	STATE,
	SUBJECT_ID,
	ODS_CREATE_DATE,
	ODS_MODIFY_DATE
)
select	SYS_GUID(),
	:v_sess_no, 
	rowid,
	''F'', 
	''ODI-15064: The primary key PARENT_GUARDIAN_PK is not unique.'',
	''(1392001)ODS_Project.LOAD_SAS_PARENT_GUARDIAN_STG_INT'',
	sysdate,
	''PARENT_GUARDIAN_PK'',
	''PK'',	
	SAS_PAR_GUAR_STG.PARENT_GUARDIAN_ID,
	SAS_PAR_GUAR_STG.ADDRESS_LINE_1,
	SAS_PAR_GUAR_STG.ADDRESS_LINE_2,
	SAS_PAR_GUAR_STG.AUDIT_CREATE_DATE,
	SAS_PAR_GUAR_STG.AUDIT_CREATED_BY,
	SAS_PAR_GUAR_STG.AUDIT_MODIFIED_BY,
	SAS_PAR_GUAR_STG.AUDIT_MODIFY_DATE,
	SAS_PAR_GUAR_STG.CITY,
	SAS_PAR_GUAR_STG.COUNTRY,
	SAS_PAR_GUAR_STG.COURTESY_TITLE,
	SAS_PAR_GUAR_STG.DAYTIME_PHONE,
	SAS_PAR_GUAR_STG.EMAIL_ADDRESS,
	SAS_PAR_GUAR_STG.EMERGENCY_CONTACT,
	SAS_PAR_GUAR_STG.FIRST_NAME,
	SAS_PAR_GUAR_STG.LAST_NAME,
	SAS_PAR_GUAR_STG.MIDDLE_NAME,
	SAS_PAR_GUAR_STG.EVENING_PHONE,
	SAS_PAR_GUAR_STG.POSTAL_CODE,
	SAS_PAR_GUAR_STG.RELATIONSHIP,
	SAS_PAR_GUAR_STG.STATE,
	SAS_PAR_GUAR_STG.SUBJECT_ID,
	SAS_PAR_GUAR_STG.ODS_CREATE_DATE,
	SAS_PAR_GUAR_STG.ODS_MODIFY_DATE
from	'
 || VariableCheckTable || 
' SAS_PAR_GUAR_STG 
where	exists  (
		select	SUB1.PARENT_GUARDIAN_ID
		from 	' 
|| VariableCheckTable ||
'  SUB1
		where 	SUB1.PARENT_GUARDIAN_ID=SAS_PAR_GUAR_STG.PARENT_GUARDIAN_ID
		group by 	SUB1.PARENT_GUARDIAN_ID
		having 	count(1) > 1
		)
';

END;


&


/*-----------------------------------------------*/
/* TASK No. 21 */
/* Create index on AK */

 
/* FLOW CONTROL CREATE THE iNDEX ON THE I$TABLE */
-- create index 	SAS_PARENT_GUARDIAN_PK_flow
-- on	RAX_APP_USER.I$_SAS_PAR_GUAR_STG1392001 
-- 	(PARENT_GUARDIAN_ID)

BEGIN
  EXECUTE IMMEDIATE 'create index SAS_PARENT_GUARDIAN_PK_flow
on   RAX_APP_USER.I$_SAS_PAR_GUAR_STG1392001 (PARENT_GUARDIAN_ID)';
EXCEPTION
  WHEN OTHERS THEN
   -- Handle the case where the identifier is too long (ORA-00972)
   IF SQLCODE = -972 or  SQLCODE = -1408 or SQLCODE = -955  THEN
     DBMS_OUTPUT.PUT_LINE('Identifier is too long. Skipping creation of index.');
   ELSE
     RAISE;
   END IF;
END;

&


/*-----------------------------------------------*/
/* TASK No. 22 */
/* insert AK errors */

DECLARE
               CheckTable                             VarChar2(60);
               TargetTable                            VarChar2(60);
               VariableCheckTable                VarChar2(60);

BEGIN
               SELECT 'RAX_APP_USER.I$_SAS_PAR_GUAR_STG' INTO CheckTable FROM DUAL;
               SELECT 'ODS_STAGE.SAS_PARENT_GUARDIAN_STG' INTO TargetTable FROM DUAL;

IF CheckTable = TargetTable THEN
   VariableCheckTable := CheckTable; 
ELSE
   VariableCheckTable := CheckTable || '1392001';
END IF;

execute immediate '
insert into RAX_APP_USER.E$_SAS_PAR_GUAR_STG1392001
(
	ODI_PK,
	ODI_SESS_NO,
	ODI_ROW_ID,
	ODI_ERR_TYPE,
	ODI_ERR_MESS,
	ODI_ORIGIN,
	ODI_CHECK_DATE,
	ODI_CONS_NAME,
	ODI_CONS_TYPE,
	PARENT_GUARDIAN_ID,
	ADDRESS_LINE_1,
	ADDRESS_LINE_2,
	AUDIT_CREATE_DATE,
	AUDIT_CREATED_BY,
	AUDIT_MODIFIED_BY,
	AUDIT_MODIFY_DATE,
	CITY,
	COUNTRY,
	COURTESY_TITLE,
	DAYTIME_PHONE,
	EMAIL_ADDRESS,
	EMERGENCY_CONTACT,
	FIRST_NAME,
	LAST_NAME,
	MIDDLE_NAME,
	EVENING_PHONE,
	POSTAL_CODE,
	RELATIONSHIP,
	STATE,
	SUBJECT_ID,
	ODS_CREATE_DATE,
	ODS_MODIFY_DATE
)
select	SYS_GUID(),
	:v_sess_no, 
	rowid,
	''F'', 
	''ODI-15063: The alternate key SAS_PARENT_GUARDIAN_PK is not unique.'',
	''(1392001)ODS_Project.LOAD_SAS_PARENT_GUARDIAN_STG_INT'',
	sysdate,
	''SAS_PARENT_GUARDIAN_PK'',
	''AK'',	
	SAS_PAR_GUAR_STG.PARENT_GUARDIAN_ID,
	SAS_PAR_GUAR_STG.ADDRESS_LINE_1,
	SAS_PAR_GUAR_STG.ADDRESS_LINE_2,
	SAS_PAR_GUAR_STG.AUDIT_CREATE_DATE,
	SAS_PAR_GUAR_STG.AUDIT_CREATED_BY,
	SAS_PAR_GUAR_STG.AUDIT_MODIFIED_BY,
	SAS_PAR_GUAR_STG.AUDIT_MODIFY_DATE,
	SAS_PAR_GUAR_STG.CITY,
	SAS_PAR_GUAR_STG.COUNTRY,
	SAS_PAR_GUAR_STG.COURTESY_TITLE,
	SAS_PAR_GUAR_STG.DAYTIME_PHONE,
	SAS_PAR_GUAR_STG.EMAIL_ADDRESS,
	SAS_PAR_GUAR_STG.EMERGENCY_CONTACT,
	SAS_PAR_GUAR_STG.FIRST_NAME,
	SAS_PAR_GUAR_STG.LAST_NAME,
	SAS_PAR_GUAR_STG.MIDDLE_NAME,
	SAS_PAR_GUAR_STG.EVENING_PHONE,
	SAS_PAR_GUAR_STG.POSTAL_CODE,
	SAS_PAR_GUAR_STG.RELATIONSHIP,
	SAS_PAR_GUAR_STG.STATE,
	SAS_PAR_GUAR_STG.SUBJECT_ID,
	SAS_PAR_GUAR_STG.ODS_CREATE_DATE,
	SAS_PAR_GUAR_STG.ODS_MODIFY_DATE
from              '	
 || VariableCheckTable || 
' SAS_PAR_GUAR_STG
where	exists  (
		select	SUB.PARENT_GUARDIAN_ID
		from 	'
 || VariableCheckTable || 
' SUB
		where 	SUB.PARENT_GUARDIAN_ID=SAS_PAR_GUAR_STG.PARENT_GUARDIAN_ID
		group by 	SUB.PARENT_GUARDIAN_ID
		having 	count(1) > 1
		)
 ';

END;

/*  Checked Datastore =RAX_APP_USER.I$_SAS_PAR_GUAR_STG  */
/*  Integration Datastore =RAX_APP_USER.I$_SAS_PAR_GUAR_STG   */
/*  Target Datastore =ODS_STAGE.SAS_PARENT_GUARDIAN_STG */



&


/*-----------------------------------------------*/
/* TASK No. 23 */
/* insert Not Null errors */

insert into RAX_APP_USER.E$_SAS_PAR_GUAR_STG1392001
(
	ODI_PK,
	ODI_SESS_NO,
	ODI_ROW_ID,
	ODI_ERR_TYPE,
	ODI_ERR_MESS,
	ODI_CHECK_DATE,
	ODI_ORIGIN,
	ODI_CONS_NAME,
	ODI_CONS_TYPE,
	PARENT_GUARDIAN_ID,
	ADDRESS_LINE_1,
	ADDRESS_LINE_2,
	AUDIT_CREATE_DATE,
	AUDIT_CREATED_BY,
	AUDIT_MODIFIED_BY,
	AUDIT_MODIFY_DATE,
	CITY,
	COUNTRY,
	COURTESY_TITLE,
	DAYTIME_PHONE,
	EMAIL_ADDRESS,
	EMERGENCY_CONTACT,
	FIRST_NAME,
	LAST_NAME,
	MIDDLE_NAME,
	EVENING_PHONE,
	POSTAL_CODE,
	RELATIONSHIP,
	STATE,
	SUBJECT_ID,
	ODS_CREATE_DATE,
	ODS_MODIFY_DATE
)
select
	SYS_GUID(),
	:v_sess_no, 
	rowid,
	'F', 
	'ODI-15066: The column PARENT_GUARDIAN_ID cannot be null.',
	sysdate,
	'(1392001)ODS_Project.LOAD_SAS_PARENT_GUARDIAN_STG_INT',
	'PARENT_GUARDIAN_ID',
	'NN',	
	PARENT_GUARDIAN_ID,
	ADDRESS_LINE_1,
	ADDRESS_LINE_2,
	AUDIT_CREATE_DATE,
	AUDIT_CREATED_BY,
	AUDIT_MODIFIED_BY,
	AUDIT_MODIFY_DATE,
	CITY,
	COUNTRY,
	COURTESY_TITLE,
	DAYTIME_PHONE,
	EMAIL_ADDRESS,
	EMERGENCY_CONTACT,
	FIRST_NAME,
	LAST_NAME,
	MIDDLE_NAME,
	EVENING_PHONE,
	POSTAL_CODE,
	RELATIONSHIP,
	STATE,
	SUBJECT_ID,
	ODS_CREATE_DATE,
	ODS_MODIFY_DATE
from	RAX_APP_USER.I$_SAS_PAR_GUAR_STG1392001
where	PARENT_GUARDIAN_ID is null



&


/*-----------------------------------------------*/
/* TASK No. 24 */
/* create index on error table */

 
/* FLOW CONTROL CREATE INDEX ON THE E$TABLE */
-- create index 	RAX_APP_USER.E$_SAS_PAR_GUAR_STG1392001
-- on	RAX_APP_USER.E$_SAS_PAR_GUAR_STG1392001 (ODI_ROW_ID)

BEGIN
  EXECUTE IMMEDIATE 'create index RAX_APP_USER.E$_SAS_PAR_GUAR_STG1392001
on   RAX_APP_USER.E$_SAS_PAR_GUAR_STG1392001 (ODI_ROW_ID)';
EXCEPTION
  WHEN OTHERS THEN
   -- Handle the case where the identifier is too long (ORA-00972)
   IF SQLCODE = -972 or  SQLCODE = -1408 or SQLCODE = -955  THEN
     DBMS_OUTPUT.PUT_LINE('Identifier is too long. Skipping creation of index.');
   ELSE
     RAISE;
   END IF;
END;

&


/*-----------------------------------------------*/
/* TASK No. 25 */
/* delete errors from controlled table */

delete from	RAX_APP_USER.I$_SAS_PAR_GUAR_STG1392001  T
where	exists 	(
		select	1
		from	RAX_APP_USER.E$_SAS_PAR_GUAR_STG1392001 E
		where ODI_SESS_NO = :v_sess_no
		and T.rowid = E.ODI_ROW_ID
		)


&


/*-----------------------------------------------*/
/* TASK No. 26 */
/* insert check sum into check table */

insert into RAX_APP_USER.SNP_CHECK_TAB
(
	SCHEMA_NAME,
	RESOURCE_NAME,
	FULL_RES_NAME,
	ERR_TYPE,
	ERR_MESS,
	CHECK_DATE,
	ORIGIN,
	CONS_NAME,
	CONS_TYPE,
	ERR_COUNT
)
select	
	'ODS_STAGE',
	'SAS_PAR_GUAR_STG',
	'ODS_STAGE.SAS_PARENT_GUARDIAN_STG1392001',
	E.ODI_ERR_TYPE,
	E.ODI_ERR_MESS,
	E.ODI_CHECK_DATE,
	E.ODI_ORIGIN,
	E.ODI_CONS_NAME,
	E.ODI_CONS_TYPE,
	count(1) 
from	RAX_APP_USER.E$_SAS_PAR_GUAR_STG1392001 E
where	E.ODI_ERR_TYPE	= 'F'
and	E.ODI_ORIGIN 	= '(1392001)ODS_Project.LOAD_SAS_PARENT_GUARDIAN_STG_INT'
group by	E.ODI_ERR_TYPE,
	E.ODI_ERR_MESS,
	E.ODI_CHECK_DATE,
	E.ODI_ORIGIN,
	E.ODI_CONS_NAME,
	E.ODI_CONS_TYPE


&


/*-----------------------------------------------*/
/* TASK No. 27 */
/* Merge Rows */

merge into	ODS_STAGE.SAS_PARENT_GUARDIAN_STG T
using	RAX_APP_USER.I$_SAS_PAR_GUAR_STG1392001 S
on	(
		T.PARENT_GUARDIAN_ID=S.PARENT_GUARDIAN_ID
	)
when matched
then update set
	T.ADDRESS_LINE_1	= S.ADDRESS_LINE_1,
	T.ADDRESS_LINE_2	= S.ADDRESS_LINE_2,
	T.AUDIT_CREATE_DATE	= S.AUDIT_CREATE_DATE,
	T.AUDIT_CREATED_BY	= S.AUDIT_CREATED_BY,
	T.AUDIT_MODIFIED_BY	= S.AUDIT_MODIFIED_BY,
	T.AUDIT_MODIFY_DATE	= S.AUDIT_MODIFY_DATE,
	T.CITY	= S.CITY,
	T.COUNTRY	= S.COUNTRY,
	T.COURTESY_TITLE	= S.COURTESY_TITLE,
	T.DAYTIME_PHONE	= S.DAYTIME_PHONE,
	T.EMAIL_ADDRESS	= S.EMAIL_ADDRESS,
	T.EMERGENCY_CONTACT	= S.EMERGENCY_CONTACT,
	T.FIRST_NAME	= S.FIRST_NAME,
	T.LAST_NAME	= S.LAST_NAME,
	T.MIDDLE_NAME	= S.MIDDLE_NAME,
	T.EVENING_PHONE	= S.EVENING_PHONE,
	T.POSTAL_CODE	= S.POSTAL_CODE,
	T.RELATIONSHIP	= S.RELATIONSHIP,
	T.STATE	= S.STATE,
	T.SUBJECT_ID	= S.SUBJECT_ID
	,                    T.ODS_MODIFY_DATE	= sysdate
when not matched
then insert
	(
	T.PARENT_GUARDIAN_ID,
	T.ADDRESS_LINE_1,
	T.ADDRESS_LINE_2,
	T.AUDIT_CREATE_DATE,
	T.AUDIT_CREATED_BY,
	T.AUDIT_MODIFIED_BY,
	T.AUDIT_MODIFY_DATE,
	T.CITY,
	T.COUNTRY,
	T.COURTESY_TITLE,
	T.DAYTIME_PHONE,
	T.EMAIL_ADDRESS,
	T.EMERGENCY_CONTACT,
	T.FIRST_NAME,
	T.LAST_NAME,
	T.MIDDLE_NAME,
	T.EVENING_PHONE,
	T.POSTAL_CODE,
	T.RELATIONSHIP,
	T.STATE,
	T.SUBJECT_ID
	,                     T.ODS_CREATE_DATE,
	T.ODS_MODIFY_DATE
	)
values
	(
	S.PARENT_GUARDIAN_ID,
	S.ADDRESS_LINE_1,
	S.ADDRESS_LINE_2,
	S.AUDIT_CREATE_DATE,
	S.AUDIT_CREATED_BY,
	S.AUDIT_MODIFIED_BY,
	S.AUDIT_MODIFY_DATE,
	S.CITY,
	S.COUNTRY,
	S.COURTESY_TITLE,
	S.DAYTIME_PHONE,
	S.EMAIL_ADDRESS,
	S.EMERGENCY_CONTACT,
	S.FIRST_NAME,
	S.LAST_NAME,
	S.MIDDLE_NAME,
	S.EVENING_PHONE,
	S.POSTAL_CODE,
	S.RELATIONSHIP,
	S.STATE,
	S.SUBJECT_ID
	,                     sysdate,
	sysdate
	)

&


/*-----------------------------------------------*/
/* TASK No. 28 */
/* Commit transaction */

/*commit*/


/*-----------------------------------------------*/
/* TASK No. 29 */
/* Drop flow table */

-- drop table RAX_APP_USER.I$_SAS_PAR_GUAR_STG1392001 

BEGIN
  EXECUTE IMMEDIATE 'drop table RAX_APP_USER.I$_SAS_PAR_GUAR_STG1392001';
EXCEPTION
  WHEN OTHERS THEN
   IF SQLCODE != -942 THEN
     RAISE;
   END IF;
END;

&


/*-----------------------------------------------*/
/* TASK No. 1000008 */
/* Drop work table */

-- drop table RAX_APP_USER.C$_0SAS_PAR_GUAR_STG purge

BEGIN
  EXECUTE IMMEDIATE 'drop table RAX_APP_USER.C$_0SAS_PAR_GUAR_STG purge';
EXCEPTION
  WHEN OTHERS THEN
   IF SQLCODE != -942 THEN
     RAISE;
   END IF;
END;


&


/*-----------------------------------------------*/
/* TASK No. 30 */
/* Update CDC Load Status */

UPDATE ODS_OWN.ODS_CDC_LOAD_STATUS
SET LAST_CDC_COMPLETION_DATE=TO_DATE(
             SUBSTR(:v_sess_beg, 1, 19), 'RRRR-MM-DD HH24:MI:SS')
+ nvl((TIMEZONE_OFFSET/24), 0) 
WHERE ODS_TABLE_NAME=:v_cdc_load_table_name
AND CONTEXT_NAME = :v_env

/*
UPDATE ODS_OWN.ODS_CDC_LOAD_STATUS
SET LAST_CDC_COMPLETION_DATE=TO_DATE(
             SUBSTR(:v_sess_beg, 1, 19), 'RRRR-MM-DD HH24:MI:SS')
WHERE ODS_TABLE_NAME=:v_cdc_load_table_name
AND CONTEXT_NAME = :v_env
*/

&


/*-----------------------------------------------*/
/* TASK No. 31 */
/* Insert CDC Audit Record */

INSERT INTO RAX_APP_USER.ODS_CDC_LOAD_STATUS_AUDIT
(TABLE_NAME,
SESS_NO,                      
SESS_NAME,                    
SCEN_VERSION,                 
SESS_BEG,                     
ORIG_LAST_CDC_COMPLETION_DATE,
OVERLAP,
CREATE_DATE,
CONTEXT_NAME,
TIMEZONE_OFFSET              
)
select 
:v_cdc_load_table_name
,:v_sess_no
,'LOAD_SAS_PARENT_GUARDIAN_PKG'
,'003'
,TO_DATE(SUBSTR(:v_sess_beg, 1, 19), 'RRRR-MM-DD HH24:MI:SS')
,TO_DATE (SUBSTR(:v_cdc_load_date, 1, 19),'YYYY-MM-DD HH24:MI:SS')
,:v_cdc_overlap
,SYSDATE
,:v_env
,TIMEZONE_OFFSET
from 
ODS_OWN.ODS_CDC_LOAD_STATUS
WHERE ODS_TABLE_NAME=:v_cdc_load_table_name
AND CONTEXT_NAME = :v_env

/*
INSERT INTO RAX_APP_USER.ODS_CDC_LOAD_STATUS_AUDIT
(TABLE_NAME,
SESS_NO,                      
SESS_NAME,                    
SCEN_VERSION,                 
SESS_BEG,                     
ORIG_LAST_CDC_COMPLETION_DATE,
OVERLAP,
CREATE_DATE,
CONTEXT_NAME              
)
values (
:v_cdc_load_table_name,
:v_sess_no,
'LOAD_SAS_PARENT_GUARDIAN_PKG',
'003',
TO_DATE(
             SUBSTR(:v_sess_beg, 1, 19), 'RRRR-MM-DD HH24:MI:SS'),
TO_DATE (SUBSTR (:v_cdc_load_date, 1, 19),
                           'YYYY-MM-DD HH24:MI:SS'
                          )
,:v_cdc_overlap,
SYSDATE,
 :v_env)
*/


&


/*-----------------------------------------------*/
