select 	
	ACT_SNG_BOOK.PROGRAM_ID	   PROGRAM_ID,
	ACT_SNG_BOOK.SALES_LINE_ID	   SALES_LINE_ID,
	ACT_SNG_BOOK.SUB_PROGRAM_ID	   SUB_PROGRAM_ID,
	ACT_SNG_BOOK.SUB_PROGRAM_NAME	   SUB_PROGRAM_NAME,
	ACT_SNG_BOOK.TERRITORY_CODE	   TERRITORY_CODE,
	ACT_SNG_BOOK.REGION_NAME	   REGION_NAME,
	ACT_SNG_BOOK.AREA_NAME	   AREA_NAME,
	ACT_SNG_BOOK.COUNTRY_NAME	   COUNTRY_NAME,
	ACT_SNG_BOOK.COMPANY_NAME	   COMPANY_NAME,
	ACT_SNG_BOOK.FISCAL_YEAR	   FISCAL_YEAR,
	ACT_SNG_BOOK.SCHOOL_YEAR	   SCHOOL_YEAR,
	ACT_SNG_BOOK.RUN_DATE	   RUN_DATE,
	SUM(ACT_SNG_BOOK.PRIOR_YEAR_ACCOUNTS)	   PRIOR_YEAR_ACCOUNTS,
	SUM(ACT_SNG_BOOK.REBOOKED_ACCOUNTS)	   REBOOKED_ACCOUNTS,
	SUM(ACT_SNG_BOOK.NOT_REBOOKED_ACCOUNTS)	   NOT_REBOOKED_ACCOUNTS,
	SUM(ACT_SNG_BOOK.NEW_ACCOUNTS)	   NEW_ACCOUNTS,
	SUM(ACT_SNG_BOOK.LOST_ACCOUNTS)	   LOST_ACCOUNTS,
	SUM(ACT_SNG_BOOK.BOOKED_ACCOUNTS)	   BOOKED_ACCOUNTS,
	SUM(ACT_SNG_BOOK.BOOKED_ACCOUNTS_PRIOR_WEEK)	   BOOKED_ACCOUNTS_PRIOR_WEEK,
	SUM(ACT_SNG_BOOK.LY_PRIOR_YEAR_ACCOUNTS)	   LY_PRIOR_YEAR_ACCOUNTS,
	SUM(ACT_SNG_BOOK.LY_REBOOKED_ACCOUNTS)	   LY_REBOOKED_ACCOUNTS,
	SUM(ACT_SNG_BOOK.BID_ACCTS)	   BID_ACCTS,
	SUM(ACT_SNG_BOOK.NOT_REBK_RISK_ACCTS)	   NOT_REBK_RISK_ACCTS,
	SUM(ACT_SNG_BOOK.BOOKED_RISK_ACCTS)	   BOOKED_RISK_ACCTS
from	RAX_APP_USER.ACTUATE_BOOKSTATSUMM_STAGE   ACT_SNG_BOOK
where	
	(1=1)	
	

And (ACT_SNG_BOOK.ALL_FLAG = 0)

Group By ACT_SNG_BOOK.PROGRAM_ID,
 ACT_SNG_BOOK.SALES_LINE_ID,
 ACT_SNG_BOOK.SUB_PROGRAM_ID,
 ACT_SNG_BOOK.SUB_PROGRAM_NAME,
 ACT_SNG_BOOK.TERRITORY_CODE,
 ACT_SNG_BOOK.REGION_NAME,
 ACT_SNG_BOOK.AREA_NAME,
 ACT_SNG_BOOK.COUNTRY_NAME,
 ACT_SNG_BOOK.COMPANY_NAME,
 ACT_SNG_BOOK.FISCAL_YEAR,
 ACT_SNG_BOOK.SCHOOL_YEAR,
 ACT_SNG_BOOK.RUN_DATE
