select	
	ORDER_LINE_ITEM.PARENT_ORDER_LINE_ID	   C1_PARENT_ORDER_LINE_ID,
	ORDER_LINE_ITEM.CHILD_ORDER_LINE_ID	   C2_CHILD_ORDER_LINE_ID
from	<schema_name>.ORDER_LINE_ITEM   ORDER_LINE_ITEM, <schema_name>.ORDER_LINE   ORDER_LINE
where	(1=1)
And (ORDER_LINE.AUDIT_MODIFY_DATE >= ( TO_DATE(SUBSTR(:v_cdc_load_date, 1, 19), 'YYYY-MM-DD HH24:MI:SS')  - :v_cdc_oms_overlap))
 And (ORDER_LINE_ITEM.PARENT_ORDER_LINE_ID=ORDER_LINE.ORDER_LINE_ID)