DECLARE create_query CLOB;  
   BEGIN  
      BEGIN  
         EXECUTE IMMEDIATE 'DROP TABLE RAX_APP_USER.C$_0MLT_ORDER_LINE_ITEM';  
      EXCEPTION  
         WHEN OTHERS THEN NULL;  
      END;  
      create_query := 'CREATE TABLE RAX_APP_USER.C$_0MLT_ORDER_LINE_ITEM (C1_PARENT_ORDER_LINE_ID	NUMBER NULL,	C2_CHILD_ORDER_LINE_ID	NUMBER NULL) NOLOGGING';  
      EXECUTE IMMEDIATE create_query;  
   END;  