pipeline:
  name: lt_LOAD_ITEM_DIM_dag
  description: Laod ITEM DIM Package
  schedule: "0 */6 * * *"
  tags:
    - lifetouch
    - load_item_dim
  task_groups:

    - name: LOAD_ITEM_DIM_ODI_Transformation
      description: ODI SQL Transformation Logic for EVENT PAYMENT FACT
      pre_sql:
        v_cdc_load_date: dags/sql/pre_sql/v_cdc_load_date_ODS_DM.sql
      default_args:
        v_cdc_ods_overlap: 0.02083333333
      tasks: 
        - description: load LOAD_ITEM_DIM subpackage
          type: oracle_sql
          script_location: dags/sql/LOAD_ITEM_DIM/LOAD_ITEM_DIM.sql
          args:
            v_cdc_load_table_name: ODS_ITEM
