---

pipeline:
  name: lt_LOAD_MART_MARKETING_PKG_dag
  description: LOAD_MART_MARKETING_PKG package
  schedule: "0 */4 * * *"
  tags:
    - lifetouch
    - lt_LOAD_MART_MARKETING_PKG
  task_groups:
    - name: LOAD_MART_MARKETING_PKG_ODI_Transformation
      description: ODI SQL Transformation Logic
      tasks: 
        - description: load yearbook fact subpackage
          type: oracle_sql
          script_location: dags/sql/LOAD_MART_MARKETING_PKG/LOAD_MART_MARKETING_PKG.sql