
select 	
	SPE.APO_ID	   APO_ID,
	SPE.ORDER_NO	   ORDER_NO,
	SPE.FIRST_NAME	   FIRST_NAME,
	SPE.LAST_NAME	   LAST_NAME,
	SPE.PAYMENT_AMOUNT	   PAYMENT_AMOUNT,
	SPE.PAYMENT_TYPE	   PAYMENT_TYPE,
	SPE.DATE_PAYMENT_POSTED	   DATE_PAYMENT_POSTED
from	RAX_APP_USER.SPECTRUM_SENIOR_PAYMENT_STG   SPE
where	
	(1=1)	
	
