
select 	
	UC_LAWSON_REFUNDS.SCHOOL_YEAR	   SCHOOL_YEAR,
	UC_LAWSON_REFUNDS.APO_ID	   APO_ID,
	UC_LAWSON_REFUNDS.TERRITORY_CODE	   TERRITORY_CODE,
	UC_LAWSON_REFUNDS.SUB_PROGRAM_NAME	   SUB_PROGRAM_NAME,
	UC_LAWSON_REFUNDS.EVENT_REF_ID	   EVENT_REF_ID,
	UC_LAWSON_REFUNDS.REFUND_AMOUNT	   REFUND_AMOUNT,
	UC_LAWSON_REFUNDS.CARDHOLDER_NAME	   CARDHOLDER_NAME,
	UC_LAWSON_REFUNDS.CHECK_NUMBER	   CHECK_NUMBER,
	UC_LAWSON_REFUNDS.RECORD_STATUS	   RECORD_STATUS,
	UC_LAWSON_REFUNDS.PAYMENT_DATE	   PAYMENT_DATE
from	RAX_APP_USER.UC_LAWSON_REFUNDS   UC_LAWSON_REFUNDS
where	
	(1=1)	
	