select 	
	ACT_EZ.FISCAL_YEAR	   FISCAL_YEAR,
	ACT_EZ.MONTH_NAME	   MONTH_NAME,
	ACT_EZ.FISCAL_MONTH_NUMBER	   FISCAL_MONTH_NUMBER,
	ACT_EZ.COUNTRY_NAME	   COUNTRY_NAME,
	ACT_EZ.AMS_BUSINESS_UNIT_NAME	   AMS_BUSINESS_UNIT_NAME,
	ACT_EZ.COMPANY_NAME	   COMPANY_NAME,
	ACT_EZ.TYPE	   TYPE,
	ACT_EZ.REVENUE	   REVENUE,
	ACT_EZ.EXPENSE	   EXPENSE
from	RAX_APP_USER.ACTUATE_EZPRINTS_DETAIL_STAGE   ACT_EZ
where	
	(1=1)