

/*-----------------------------------------------*/
/* TASK No. 14 */
/* Insert new rows */

/* SOURCE CODE */


select 	
	ACT_TERR.COUNTRY_NAME	   COUNTRY_NAME,
	ACT_TERR.COMPANY_NAME	   COMPANY_NAME,
	ACT_TERR.AREA_NAME	   AREA_NAME,
	ACT_TERR.REGION_NAME	   REGION_NAME,
	ACT_TERR.TERRITORY_CODE	   TERRITORY_CODE,
	ACT_TERR.TERRITORY_MANAGER	   TERRITORY_MANAGER,
	ACT_TERR.FISCAL_YEAR	   FISCAL_YEAR,
	ACT_TERR.PROGRAM_NAME	   PROGRAM_NAME,
	ACT_TERR.GROUP_LEVEL_3_SORT	   GROUP_LEVEL_3_SORT,
	ACT_TERR.GROUP_LEVEL_3	   GROUP_LEVEL_3,
	ACT_TERR.ITEM_GROUP	   ITEM_GROUP,
	ACT_TERR.RUN_DATE	   RUN_DATE,
	ACT_TERR.TAX_AMT	   TAX_AMT,
	ACT_TERR.SHIPPED_SALES_AMT	   SHIPPED_SALES_AMT,
	ACT_TERR.GROSS_SHIP_SALES_AMT	   GROSS_SHIP_SALES_AMT,
	ACT_TERR.GROSS_SHIP_PAID_AMT	   GROSS_SHIP_PAID_AMT,
	ACT_TERR.TERR_EARNINGS_AMT	   TERR_EARNINGS_AMT
from	RAX_APP_USER.ACTUATE_SENITERRSAL_TERR_STAGE   ACT_TERR
where	
	(1=1)	
	





/* Order the output by the UD1, UD2, UD3, UD4, UD5, UD6 Fields. */

