

/*-----------------------------------------------*/
/* TASK No. 20 */
/* Insert new rows */

/* SOURCE CODE */


select 	
	ACT_COMP.COUNTRY_NAME	   COUNTRY_NAME,
	ACT_COMP.COMPANY_NAME	   COMPANY_NAME,
	ACT_COMP.FISCAL_YEAR	   FISCAL_YEAR,
	ACT_COMP.PROGRAM_NAME	   PROGRAM_NAME,
	ACT_COMP.GROUP_LEVEL_3_SORT	   GROUP_LEVEL_3_SORT,
	ACT_COMP.GROUP_LEVEL_3	   GROUP_LEVEL_3,
	ACT_COMP.ITEM_GROUP	   ITEM_GROUP,
	ACT_COMP.RUN_DATE	   RUN_DATE,
	ACT_COMP.TAX_AMT	   TAX_AMT,
	ACT_COMP.SHIPPED_SALES_AMT	   SHIPPED_SALES_AMT,
	ACT_COMP.GROSS_SHIP_SALES_AMT	   GROSS_SHIP_SALES_AMT,
	ACT_COMP.GROSS_SHIP_PAID_AMT	   GROSS_SHIP_PAID_AMT,
	ACT_COMP.TERR_EARNINGS_AMT	   TERR_EARNINGS_AMT
from	RAX_APP_USER.ACTUATE_SENITERRSAL_COMP_STAGE   ACT_COMP
where	
	(1=1)	
	





/* Order the output by the UD1, UD2, UD3, UD4, UD5, UD6 Fields. */

