

/*-----------------------------------------------*/
/* TASK No. 8 */
/* Insert new rows */

/* SOURCE CODE */


select 	
	ACT.COUNTRY_NAME	   COUNTRY_NAME,
	ACT.COMPANY_NAME	   COMPANY_NAME,
	ACT.AREA_NAME	   AREA_NAME,
	ACT.REGION_NAME	   REGION_NAME,
	ACT.TERRITORY_CODE	   TERRITORY_CODE,
	ACT.LOCATION_CODE	   LOCATION_CODE,
	ACT.TERRITORY_MANAGER	   TERRITORY_MANAGER,
	ACT.ACCOUNT_NAME	   ACCOUNT_NAME,
	ACT.ACCT_SORT_ORDER	   ACCT_SORT_ORDER,
	ACT.LIFETOUCH_ID	   LIFETOUCH_ID,
	ACT.ACCOUNT_ID	   ACCOUNT_ID,
	ACT.ADDRESS_LINE_1	   ADDRESS_LINE_1,
	ACT.CITY	   CITY,
	ACT.STATE	   STATE,
	ACT.POSTAL_CODE	   POSTAL_CODE,
	ACT.FISCAL_YEAR	   FISCAL_YEAR,
	ACT.RUN_DATE	   RUN_DATE,
	ACT.ITEM_GROUP	   ITEM_GROUP,
	ACT.GROUP_LEVEL_3_SORT	   GROUP_LEVEL_3_SORT,
	ACT.GROUP_LEVEL_3	   GROUP_LEVEL_3,
	ACT.SUB_PROGRAM_NAME	   SUB_PROGRAM_NAME,
	ACT.PROGRAM_NAME	   PROGRAM_NAME,
	ACT.SHIPPED_SALES_AMT	   SHIPPED_SALES_AMT,
	ACT.TAX_AMT	   TAX_AMT,
	ACT.ORDERED_QTY	   ORDERED_QTY,
	ACT.GROSS_SHIP_SALES_AMT	   GROSS_SHIP_SALES_AMT,
	ACT.GROSS_SHIP_PAID_AMT	   GROSS_SHIP_PAID_AMT,
	ACT.TERR_EARNINGS_AMT	   TERR_EARNINGS_AMT
from	RAX_APP_USER.ACTUATE_SENITERRSAL_ACT_STAGE   ACT
where	
	(1=1)	
	





/* Order the output by the UD1, UD2, UD3, UD4, UD5, UD6 Fields. */



