select	
	SUBSCRIPTION_TYPE.SUBSCRIPTION_TYPE_ID	   C1_SUBSCRIPTION_TYPE_ID,
	SUBSCRIPTION_TYPE.SUBSCRIPTION_TYPE	   C2_SUBSCRIPTION_TYPE
from	<schema_name>.SUBSCRIPTION_TYPE   SUBSCRIPTION_TYPE
where	(1=1)

