select	
	CUSTOMER_ORDER_LINE.LINE_TYPE	   C1_LINE_TYPE,
	CUSTOMER_ORDER_LINE.CUSTOMER_ORDER_LINE_ID	   C2_CUSTOMER_ORDER_LINE_ID,
	CUSTOMER_ORDER_LINE.AUDIT_CREATE_DATE	   C3_AUDIT_CREATE_DATE,
	CUSTOMER_ORDER_LINE.AUDIT_CREATED_BY	   C4_AUDIT_CREATED_BY,
	CUSTOMER_ORDER_LINE.AUDIT_MODIFIED_BY	   C5_AUDIT_MODIFIED_BY,
	CUSTOMER_ORDER_LINE.AUDIT_MODIFY_DATE	   C6_AUDIT_MODIFY_DATE,
	CUSTOMER_ORDER_LINE.DISCOUNT_AMOUNT	   C7_DISCOUNT_AMOUNT,
	CUSTOMER_ORDER_LINE.DISCOUNTED_ITEM_IND	   C8_DISCOUNTED_ITEM_IND,
	CUSTOMER_ORDER_LINE.PRICE	   C9_PRICE,
	CUSTOMER_ORDER_LINE.QUANTITY	   C10_QUANTITY,
	CUSTOMER_ORDER_LINE.SEQUENCE	   C11_SEQUENCE,
	CUSTOMER_ORDER_LINE.TAX_TOTAL_EFFECTIVE_RATE	   C12_TAX_TOTAL_EFFECTIVE_RATE,
	CUSTOMER_ORDER_LINE.TAX_AMOUNT	   C13_TAX_AMOUNT,
	CUSTOMER_ORDER_LINE.TAX_AS_OF_DATE	   C14_TAX_AS_OF_DATE,
	CUSTOMER_ORDER_LINE.CUSTOMER_ORDER_ID	   C15_CUSTOMER_ORDER_ID,
	CUSTOMER_ORDER_LINE.ITEM_NUMBER	   C16_ITEM_NUMBER,
	CUSTOMER_ORDER_LINE.NAME	   C17_NAME,
	CUSTOMER_ORDER_LINE.DELETED_IND	   C18_DELETED_IND
from	<schema_name>.CUSTOMER_ORDER_LINE   CUSTOMER_ORDER_LINE
where	(1=1)
And (CUSTOMER_ORDER_LINE.AUDIT_MODIFY_DATE >= TO_DATE(SUBSTR(:v_cdc_load_date, 1, 19), 'YYYY-MM-DD HH24:MI:SS')  -:v_cdc_overlap)

