select	
	APPOINTMENT.APPOINTMENT_ID	   C1_APPOINTMENT_ID,
	APPOINTMENT.APPOINTMENT_CODE	   C2_APPOINTMENT_CODE,
	APPOINTMENT.STATUS	   C3_STATUS,
	APPOINTMENT.SUBJECT_ID	   C4_SUBJECT_ID,
	APPOINTMENT.APPOINTMENT_SLOT_ID	   C5_APPOINTMENT_SLOT_ID,
	APPOINTMENT.AUDIT_CREATE_DATE	   C6_AUDIT_CREATE_DATE,
	APPOINTMENT.AUDIT_CREATED_BY	   C7_AUDIT_CREATED_BY,
	APPOINTMENT.AUDIT_MODIFY_DATE	   C8_AUDIT_MODIFY_DATE,
	APPOINTMENT.AUDIT_MODIFIED_BY	   C9_AUDIT_MODIFIED_BY,
	APPOINTMENT.LANGUAGE	   C10_LANGUAGE,
	APPOINTMENT.TIME_ZONE	   C11_TIME_ZONE,
	APPOINTMENT.EVENT_REF_ID	   C12_EVENT_REF_ID,
	APPOINTMENT.APPOINTMENT_COMMENTS	   C13_APPOINTMENT_COMMENTS,
	APPOINTMENT.APO_ID	   C14_APO_ID
from	<schema_name>.APPOINTMENT   APPOINTMENT
where	(1=1)
And (APPOINTMENT.AUDIT_MODIFY_DATE >= TO_DATE(SUBSTR(:v_cdc_load_date, 1, 19), 'YYYY-MM-DD HH24:MI:SS')  -:v_cdc_overlap)
