select	
	APPOINTMENT_SLOT.APPOINTMENT_SLOT_ID	   C1_APPOINTMENT_SLOT_ID,
	APPOINTMENT_SLOT.PICTURE_DAY_ID	   C2_PICTURE_DAY_ID,
	APPOINTMENT_SLOT.APPOINTMENT_TIME	   C3_APPOINTMENT_TIME,
	APPOINTMENT_SLOT.SLOT_TYPE	   C4_SLOT_TYPE,
	APPOINTMENT_SLOT.AUDIT_CREATE_DATE	   C5_AUDIT_CREATE_DATE,
	APPOINTMENT_SLOT.AUDIT_CREATED_BY	   C6_AUDIT_CREATED_BY,
	APPOINTMENT_SLOT.AUDIT_MODIFY_DATE	   C7_AUDIT_MODIFY_DATE,
	APPOINTMENT_SLOT.AUDIT_MODIFIED_BY	   C8_AUDIT_MODIFIED_BY
from	<schema_name>.APPOINTMENT_SLOT   APPOINTMENT_SLOT
where	(1=1)
And ((1=1) 
and APPOINTMENT_SLOT.AUDIT_MODIFY_DATE >= TO_DATE(SUBSTR(:v_cdc_load_date, 1, 19), 'YYYY-MM-DD HH24:MI:SS')  -:v_cdc_overlap )
