select	
	ORDER_STATUS.ORDER_STATUS_ID	   C1_ORDER_STATUS_ID,
	ORDER_STATUS.AUDIT_CREATE_DATE	   C2_AUDIT_CREATE_DATE,
	ORDER_STATUS.AUDIT_CREATED_BY	   C3_AUDIT_CREATED_BY,
	ORDER_STATUS.AUDIT_MODIFIED_BY	   C4_AUDIT_MODIFIED_BY,
	ORDER_STATUS.AUDIT_MODIFY_DATE	   C5_AUDIT_MODIFY_DATE,
	ORDER_STATUS.CODE	   C6_CODE,
	ORDER_STATUS.CREATE_DT	   C7_CREATE_DT,
	ORDER_STATUS.MODIFYING_USER	   C8_MODIFYING_USER,
	ORDER_STATUS.STATUS_SEQUENCE	   C9_STATUS_SEQUENCE,
	ORDER_STATUS.CUSTOMER_ORDER_ID	   C10_CUSTOMER_ORDER_ID,
	ORDER_STATUS.DELETED_IND	   C11_DELETED_IND
from	<schema_name>.ORDER_STATUS   ORDER_STATUS
where	(1=1)
And (ORDER_STATUS.AUDIT_MODIFY_DATE >= TO_DATE(SUBSTR(:v_cdc_load_date, 1, 19), 'YYYY-MM-DD HH24:MI:SS')  -:v_cdc_overlap
)
