select	
	SUBSCRIPTION_RELATIONSHIP.RELATIONSHIP_ID	   C1_RELATIONSHIP_ID,
	SUBSCRIPTION_RELATIONSHIP.RELATIONSHIP	   C2_RELATIONSHIP
from	<schema_name>.SUBSCRIPTION_RELATIONSHIP   SUBSCRIPTION_RELATIONSHIP
where	(1=1)
