select	
	CUSTOMER_ORDER_LINE_PROMOTION.CUSTOMER_ORDER_LINE_ID	   C1_CUSTOMER_ORDER_LINE_ID,
	CUSTOMER_ORDER_LINE_PROMOTION.PROMOTION_CODE	   C2_PROMOTION_CODE,
	CUSTOMER_ORDER_LINE_PROMOTION.DISCOUNT_AMOUNT	   C3_DISCOUNT_AMOUNT,
	CUSTOMER_ORDER_LINE_PROMOTION.CUSTOMER_ORDER_LINE_PROMO_ID	   C4_CUSTOMER_ORDER_LINE_PROMO_I,
	CUSTOMER_ORDER_LINE_PROMOTION.ITEM_NUMBER	   C5_ITEM_NUMBER,
	CUSTOMER_ORDER_LINE_PROMOTION.DELETED_IND	   C6_DELETED_IND,
	CUSTOMER_ORDER_LINE_PROMOTION.AUDIT_CREATE_DATE	   C7_AUDIT_CREATE_DATE,
	CUSTOMER_ORDER_LINE_PROMOTION.AUDIT_MODIFY_DATE	   C8_AUDIT_MODIFY_DATE
from	<schema_name>.CUSTOMER_ORDER_LINE_PROMOTION   CUSTOMER_ORDER_LINE_PROMOTION
where	(1=1)
And (CUSTOMER_ORDER_LINE_PROMOTION.AUDIT_MODIFY_DATE >= TO_DATE(SUBSTR(:v_cdc_load_date, 1, 19), 'YYYY-MM-DD HH24:MI:SS')  -:v_cdc_overlap)
