DECLARE create_query CLOB;  
   BEGIN  
      BEGIN  
         EXECUTE IMMEDIATE 'drop table RAX_APP_USER.C$_0SAS_CUST_ORDER_STG purge';  
      EXCEPTION  
         WHEN OTHERS THEN NULL;  
      END;  
      create_query := 'create table RAX_APP_USER.C$_0SAS_CUST_ORDER_STG
         (
            C1_CUSTOMER_ORDER_ID	NUMBER(10) NULL,
            C2_ADDRESSES_SAME	NUMBER(1) NULL,
            C3_AUDIT_CREATE_DATE	TIMESTAMP(6) NULL,
            C4_AUDIT_CREATED_BY	VARCHAR2(255) NULL,
            C5_AUDIT_MODIFIED_BY	VARCHAR2(255) NULL,
            C6_AUDIT_MODIFY_DATE	TIMESTAMP(6) NULL,
            C7_COD_LIST_AMOUNT	NUMBER(19,2) NULL,
            C8_COD_TAX_RATE	NUMBER(10,10) NULL,
            C9_COD_TAX	NUMBER(19,2) NULL,
            C10_COD_TAX_DATE	VARCHAR2(255) NULL,
            C11_CURRENCY_CODE	VARCHAR2(3) NULL,
            C12_CURRENT_STATUS_CODE	VARCHAR2(1) NULL,
            C13_ORDER_DATE	TIMESTAMP(6) NULL,
            C14_LIFETOUCH_USER_PROFILE_ID	VARCHAR2(255) NULL,
            C15_ORDER_NUMBER	VARCHAR2(255) NULL,
            C16_PROOF_DEPOSIT_APPLIED	NUMBER(19,2) NULL,
            C17_PROOF_DEPOSIT_TOTAL	NUMBER(19,2) NULL,
            C18_SHIPPING_DISCOUNT	NUMBER(19,2) NULL,
            C19_SHIPPING_LIST_AMOUNT	NUMBER(19,2) NULL,
            C20_SHIPPING_TAX_RATE	NUMBER(10,10) NULL,
            C21_SHIPPING_TAX	NUMBER(19,2) NULL,
            C22_SHIPPING_TAX_DATE	VARCHAR2(255) NULL,
            C23_SHIPPING_CITY	VARCHAR2(35) NULL,
            C24_SHIPPING_COUNTRY	VARCHAR2(2) NULL,
            C25_SHIPPING_FIRSTNAME	VARCHAR2(40) NULL,
            C26_SHIPPING_LASTNAME	VARCHAR2(40) NULL,
            C27_SHIPPING_LINE1	VARCHAR2(50) NULL,
            C28_SHIPPING_LINE2	VARCHAR2(50) NULL,
            C29_SHIPPING_PHONE_NUMBER	VARCHAR2(20) NULL,
            C30_SHIPPING_POSTAL_CODE	VARCHAR2(35) NULL,
            C31_SHIPPING_STATE_PROVINCE	VARCHAR2(35) NULL,
            C32_SENT_TO_SPECTRUM_IND	NUMBER(1) NULL,
            C33_SENT_TO_SPECTRUM_DATE	TIMESTAMP(6) NULL,
            C34_TAX_AMOUNT	NUMBER(19,2) NULL,
            C35_TAX_TOTAL_AS_OF_DATE	VARCHAR2(255) NULL,
            C36_COD_PRODUCT_ID	NUMBER(10) NULL,
            C37_PROMOTION_ID	NUMBER(19) NULL,
            C38_SHIPPING_PRODUCT_ID	NUMBER(10) NULL,
            C39_SUBJECT_ID	NUMBER(19) NULL,
            C40_APO_ID	VARCHAR2(255) NULL,
            C41_APPOINTMENT_ID	NUMBER NULL,
            C42_DELETED_IND	VARCHAR2(1) NULL
         )
	   ';
      EXECUTE IMMEDIATE create_query;  
   END;
