DECLARE create_query CLOB;  
   BEGIN  
      BEGIN  
         EXECUTE IMMEDIATE 'drop table RAX_APP_USER.C$_0SAS_CUST_ORD_LN_STG purge';  
      EXCEPTION  
         WHEN OTHERS THEN NULL;  
      END;  
      create_query := 'create table RAX_APP_USER.C$_0SAS_CUST_ORD_LN_STG
         (
            C1_LINE_TYPE	VARCHAR2(1) NULL,
            C2_CUSTOMER_ORDER_LINE_ID	NUMBER(10) NULL,
            C3_AUDIT_CREATE_DATE	TIMESTAMP(6) NULL,
            C4_AUDIT_CREATED_BY	VARCHAR2(255) NULL,
            C5_AUDIT_MODIFIED_BY	VARCHAR2(255) NULL,
            C6_AUDIT_MODIFY_DATE	TIMESTAMP(6) NULL,
            C7_DISCOUNT_AMOUNT	NUMBER(19,2) NULL,
            C8_DISCOUNTED_ITEM_IND	NUMBER(1) NULL,
            C9_PRICE	NUMBER(19,2) NULL,
            C10_QUANTITY	NUMBER(10) NULL,
            C11_SEQUENCE	NUMBER(10) NULL,
            C12_TAX_TOTAL_EFFECTIVE_RATE	NUMBER(10,10) NULL,
            C13_TAX_AMOUNT	NUMBER(19,2) NULL,
            C14_TAX_AS_OF_DATE	VARCHAR2(255) NULL,
            C15_CUSTOMER_ORDER_ID	NUMBER(10) NULL,
            C16_ITEM_NUMBER	VARCHAR2(16) NULL,
            C17_NAME	VARCHAR2(255) NULL,
            C18_DELETED_IND	VARCHAR2(1) NULL
         )
	   ';
      EXECUTE IMMEDIATE create_query;  
   END;

