
DECLARE create_query CLOB;  
   BEGIN  
      BEGIN  
         EXECUTE IMMEDIATE 'drop table RAX_APP_USER.C$_0SAS_SUBJECT_STG purge';  
      EXCEPTION  
         WHEN OTHERS THEN NULL;  
      END;  
      create_query := 'create table RAX_APP_USER.C$_0SAS_SUBJECT_STG
         (
            C1_SUBJECT_ID	NUMBER(19) NULL,
            C2_AUDIT_CREATE_DATE	TIMESTAMP(6) NULL,
            C3_AUDIT_CREATED_BY	VARCHAR2(255) NULL,
            C4_AUDIT_MODIFIED_BY	VARCHAR2(255) NULL,
            C5_AUDIT_MODIFY_DATE	TIMESTAMP(6) NULL,
            C6_SUBJECT_KEY	VARCHAR2(36) NULL,
            C7_ADDRESS_LINE_1	VARCHAR2(50) NULL,
            C8_ADDRESS_LINE_2	VARCHAR2(50) NULL,
            C9_AS_OF_DATE	TIMESTAMP(6) NULL,
            C10_BUS_NBR	VARCHAR2(50) NULL,
            C11_CITY	VARCHAR2(30) NULL,
            C12_COUNTRY	VARCHAR2(2) NULL,
            C13_COURTESY_TITLE	VARCHAR2(50) NULL,
            C14_DAYTIME_PHONE	VARCHAR2(20) NULL,
            C15_EMAIL_ADDRESS	VARCHAR2(320) NULL,
            C16_EMERGENCY_FIRST_NAME	VARCHAR2(50) NULL,
            C17_EMERGENCY_LAST_NAME	VARCHAR2(50) NULL,
            C18_EMERGENCY_PHONE	VARCHAR2(50) NULL,
            C19_FIRST_NAME	VARCHAR2(50) NULL,
            C20_GENDER	VARCHAR2(1) NULL,
            C21_GRADE	VARCHAR2(10) NULL,
            C22_GRADUATION_YEAR	VARCHAR2(10) NULL,
            C23_HOMEROOM	VARCHAR2(10) NULL,
            C24_LAST_NAME	VARCHAR2(50) NULL,
            C25_LOCKER	VARCHAR2(50) NULL,
            C26_MAJOR	VARCHAR2(50) NULL,
            C27_MIDDLE_NAME	VARCHAR2(50) NULL,
            C28_MINOR	VARCHAR2(50) NULL,
            C29_EVENING_PHONE	VARCHAR2(20) NULL,
            C30_PERIOD	VARCHAR2(10) NULL,
            C31_POSTAL_CODE	VARCHAR2(10) NULL,
            C32_SQUADRON	VARCHAR2(50) NULL,
            C33_STATE	VARCHAR2(10) NULL,
            C34_SUBJECT_EXTRA_DATA	VARCHAR2(255) NULL,
            C35_TEACHER_FIRST_NAME	VARCHAR2(50) NULL,
            C36_TEACHER_LAST_NAME	VARCHAR2(50) NULL,
            C37_TEACHER_MIDDLE_NAME	VARCHAR2(50) NULL,
            C38_TEACHER_NAME	VARCHAR2(40) NULL,
            C39_TEACHER_NBR	VARCHAR2(10) NULL,
            C40_TEACHER_TITLE	VARCHAR2(50) NULL,
            C41_TRACK	VARCHAR2(50) NULL,
            C42_STAFF_CODE	VARCHAR2(10) NULL,
            C43_STAFF_FLAG	VARCHAR2(1) NULL,
            C44_EXTERNAL_SUBJECT_ID	VARCHAR2(255) NULL,
            C45_REVISION_NO	NUMBER(10) NULL,
            C46_ACTIVE	NUMBER(1) NULL,
            C47_VALID	NUMBER(1) NULL,
            C48_BIRTH_DATE	VARCHAR2(25) NULL,
            C49_STAFF_INDICATOR	VARCHAR2(255) NULL,
            C50_AREA_CODE	VARCHAR2(3) NULL,
            C51_EXCHANGE	VARCHAR2(3) NULL,
            C52_PHONE	VARCHAR2(4) NULL,
            C53_EMAIL2	VARCHAR2(50) NULL,
            C54_EMAIL_MISC	VARCHAR2(50) NULL,
            C55_POSITION	VARCHAR2(64) NULL,
            C56_COLLEGE_ORG	VARCHAR2(50) NULL,
            C57_FLIGHT	VARCHAR2(50) NULL,
            C58_MIDDLE_INIT	VARCHAR2(50) NULL,
            C59_ACCESS_CODE	VARCHAR2(6) NULL,
            C60_AGE	NUMBER(3) NULL,
            C61_MISCELLANEOUS	VARCHAR2(50) NULL,
            C62_COURTESY	VARCHAR2(50) NULL,
            C63_MISC_INFO	VARCHAR2(50) NULL,
            C64_BIRTHDATE	VARCHAR2(25) NULL,
            C65_APO_ID	VARCHAR2(255) NULL,
            C66_OMS_SUBJECT_ID	VARCHAR2(15) NULL
         )
	   ';
      EXECUTE IMMEDIATE create_query;  
   END;

