DECLARE create_query CLOB;  
   BEGIN  
      BEGIN  
         EXECUTE IMMEDIATE 'drop table RAX_APP_USER.C$_0SAS_APPOINTMENT_STG purge';  
      EXCEPTION  
         WHEN OTHERS THEN NULL;  
      END;  
      create_query := 'create table RAX_APP_USER.C$_0SAS_APPOINTMENT_STG
         (
            C1_APPOINTMENT_ID	NUMBER NULL,
            C2_APPOINTMENT_CODE	VARCHAR2(8) NULL,
            C3_STATUS	VARCHAR2(1) NULL,
            C4_SUBJECT_ID	NUMBER NULL,
            C5_APPOINTMENT_SLOT_ID	NUMBER NULL,
            C6_AUDIT_CREATE_DATE	TIMESTAMP(6) NULL,
            C7_AUDIT_CREATED_BY	VARCHAR2(255) NULL,
            C8_AUDIT_MODIFY_DATE	TIMESTAMP(6) NULL,
            C9_AUDIT_MODIFIED_BY	VARCHAR2(255) NULL,
            C10_LANGUAGE	VARCHAR2(255) NULL,
            C11_TIME_ZONE	NUMBER NULL,
            C12_EVENT_REF_ID	VARCHAR2(10) NULL,
            C13_APPOINTMENT_COMMENTS	VARCHAR2(500) NULL,
            C14_APO_ID	VARCHAR2(255) NULL
         )
	   ';
      EXECUTE IMMEDIATE create_query;  
   END;

