
DECLARE create_query CLOB;  
   BEGIN  
      BEGIN  
         EXECUTE IMMEDIATE 'drop table RAX_APP_USER.C$_0SAS_SUB_SUBSCR_STG purge';  
      EXCEPTION  
         WHEN OTHERS THEN NULL;  
      END;  
      create_query := 'create table RAX_APP_USER.C$_0SAS_SUB_SUBSCR_STG
         (
            C1_SUBJECT_SUBSCRIPTION_ID	NUMBER NULL,
            C2_SUBJECT_ID	NUMBER NULL,
            C3_SUBSCRIPTION	VARCHAR2(255) NULL,
            C4_SUBSCRIPTION_TYPE_ID	NUMBER NULL,
            C5_SUBSCRIPTION_OPT_IN	VARCHAR2(1) NULL,
            C6_SUBSCRIPTION_OPT_IN_TEXT	VARCHAR2(255) NULL,
            C7_SUBSCRIPTION_RELATIONSHIP_I	NUMBER NULL,
            C8_SUBSCRIPTION_ORDER	NUMBER NULL,
            C9_SOURCE_IP_ADDRESS	VARCHAR2(15) NULL,
            C10_AUDIT_CREATE_DATE	TIMESTAMP(6) NULL,
            C11_AUDIT_CREATED_BY	VARCHAR2(255) NULL,
            C12_AUDIT_MODIFIED_BY	VARCHAR2(255) NULL,
            C13_AUDIT_MODIFY_DATE	TIMESTAMP(6) NULL
         )
	   ';
      EXECUTE IMMEDIATE create_query;  
   END;

