select 	
	ACM_CHECKS.TERRITORY_CODE	   TERRITORY_CODE,
	ACM_CHECKS.PROGRAM_NAME	   PROGRAM_NAME,
	ACM_CHECKS.SELLING_METHOD	   SELLING_METHOD,
	ACM_CHECKS.LIFETOUCH_ID	   LIFETOUCH_IDS,
	ACM_CHECKS.APO_ID	   APO_ID,
	ACM_CHECKS.FINALIZED_DATE	   FINALIZED_DATE,
	ACM_CHECKS.REQUEST_DATE	   REQUEST_DATE,
	ACM_CHECKS.PAYMENT_AMOUNT	   PAYMENT_AMOUNT
from	RAX_APP_USER.PENDING_ACM_CHECKS_STAGE   ACM_CHECKS
where	
	(1=1)	
	