
select 	
	SER_AC.LIFETOUCH_ID	   LIFETOUCH_ID,
	SER_AC.ACCOUNT_NAME	   ACCOUNT_NAME,
	SER_AC.PHYSICAL_ADDRESS_LINE1	   PHYSICAL_ADDRESS_LINE1,
	SER_AC.CITY	   CITY,
	SER_AC.STATE	   STATE,
	SER_AC.CATEGORY_NAME	   CATEGORY_NAME,
	SER_AC.SUBCATEGORY_NAME	   SUBCATEGORY_NAME,
	SER_AC.ENROLLMENT	   ENROLLMENT,
	SER_AC.BUSINESS_PHONE	   BUSINESS_PHONE,
	SER_AC.PARENT_LIFETOUCH_ID	   PARENT_LIFETOUCH_ID
from	RAX_APP_USER.SERVICENOW_ACCOUNT_STAGE   SER_AC
where	
	(1=1)