select 	
	SER_CN.CONTACT_OID	   CONTACT_OID,
	SER_CN.FIRST_NAME	   FIRST_NAME,
	SER_CN.LAST_NAME	   LAST_NAME,
	SER_CN.TITLE_NAME	   TITLE_NAME,
	SER_CN.WORK_PHONE	   WORK_PHONE,
	SER_CN.EMAIL_ADDRESS	   EMAIL_ADDRESS
from	RAX_APP_USER.SERVICENOW_CONTACT_STAGE   SER_CN
where	
	(1=1)	
	

And (SER_CN.FIRST_NAME NOT  IN ('-','.','..','...','?','_'))