/* TASK No. 1 */

/* SELECT STATEMENT FOUND, CHECK ODI TASK NO. 1 */




/*-----------------------------------------------*/
/* TASK No. 2 */
/* drop table */

drop table RAX_APP_USER.SERVICENOW_ACCOUNT_STAGE

&


/*-----------------------------------------------*/
/* TASK No. 3 */
/* create table */

create table RAX_APP_USER.SERVICENOW_ACCOUNT_STAGE as
SELECT a.lifetouch_id,
       a.account_name,
       a.physical_address_line1,
       a.city,
       a.state,
       a.category_name,
       a.subcategory_name,
       a.enrollment,
       a.business_phone,
       pa.lifetouch_id     AS parent_lifetouch_id
  FROM ods_own.account a, ods_own.account pa, ods_own.source_system ss
 WHERE     1 = 1
       AND a.parent_account_oid = pa.account_oid(+)
       AND a.source_system_oid = ss.source_system_oid
       AND a.active_account_ind = 'A'
       AND (a.category_name<>'Test' OR a.subcategory_name<>'Test'  )
       AND a.account_name not like '%Test Account%'
       AND EXISTS
               (SELECT 1
                  FROM ods_own.booking_opportunity  bo,
                       (SELECT TO_NUMBER (TO_CHAR (SYSDATE, 'YYYY'))    AS school_year
                          FROM DUAL) curr
                 WHERE     bo.account_oid = a.account_oid
                       AND bo.school_year IN
                               (curr.school_year, curr.school_year - 1)
                       AND bo.booking_status IN ('Agreement Filed'))


&


/*-----------------------------------------------*/
/* TASK No. 4 */
/* Generate header */

create header	(LIFETOUCH_ID,
	ACCOUNT_NAME,
	PHYSICAL_ADDRESS_LINE1,
	CITY,
	STATE,
	CATEGORY_NAME,
	SUBCATEGORY_NAME,
	ENROLLMENT,
	BUSINESS_PHONE,
	PARENT_LIFETOUCH_ID)

/*$$SNPS_START_KEYSNP$CRDWG_TABLESNP$CRTABLE_NAME=account.csvSNP$CRLOAD_FILE=/dw_export/PROD/account.csvSNP$CRFILE_FORMAT=DSNP$CRFILE_SEP_FIELD=0x002cSNP$CRFILE_SEP_LINE=0x000D0x000ASNP$CRFILE_FIRST_ROW=0SNP$CRFILE_ENC_FIELD="SNP$CRFILE_DEC_SEP=SNP$CRSNP$CRDWG_COLSNP$CRCOL_NAME=LIFETOUCH_IDSNP$CRTYPE_NAME=STRINGSNP$CRORDER=1SNP$CRLENGTH=50SNP$CRPRECISION=50SNP$CRSNP$CRDWG_COLSNP$CRCOL_NAME=ACCOUNT_NAMESNP$CRTYPE_NAME=STRINGSNP$CRORDER=2SNP$CRLENGTH=90SNP$CRPRECISION=90SNP$CRSNP$CRDWG_COLSNP$CRCOL_NAME=PHYSICAL_ADDRESS_LINE1SNP$CRTYPE_NAME=STRINGSNP$CRORDER=3SNP$CRLENGTH=120SNP$CRPRECISION=120SNP$CRSNP$CRDWG_COLSNP$CRCOL_NAME=CITYSNP$CRTYPE_NAME=STRINGSNP$CRORDER=4SNP$CRLENGTH=60SNP$CRPRECISION=60SNP$CRSNP$CRDWG_COLSNP$CRCOL_NAME=STATESNP$CRTYPE_NAME=STRINGSNP$CRORDER=5SNP$CRLENGTH=60SNP$CRPRECISION=60SNP$CRSNP$CRDWG_COLSNP$CRCOL_NAME=CATEGORY_NAMESNP$CRTYPE_NAME=STRINGSNP$CRORDER=6SNP$CRLENGTH=50SNP$CRPRECISION=50SNP$CRSNP$CRDWG_COLSNP$CRCOL_NAME=SUBCATEGORY_NAMESNP$CRTYPE_NAME=STRINGSNP$CRORDER=7SNP$CRLENGTH=50SNP$CRPRECISION=50SNP$CRSNP$CRDWG_COLSNP$CRCOL_NAME=ENROLLMENTSNP$CRTYPE_NAME=STRINGSNP$CRORDER=8SNP$CRLENGTH=50SNP$CRPRECISION=50SNP$CRSNP$CRDWG_COLSNP$CRCOL_NAME=BUSINESS_PHONESNP$CRTYPE_NAME=STRINGSNP$CRORDER=9SNP$CRLENGTH=50SNP$CRPRECISION=50SNP$CRSNP$CRDWG_COLSNP$CRCOL_NAME=PARENT_LIFETOUCH_IDSNP$CRTYPE_NAME=STRINGSNP$CRORDER=10SNP$CRLENGTH=50SNP$CRPRECISION=50SNP$CR$$SNPS_END_KEY*/


&


/*-----------------------------------------------*/
/* TASK No. 5 */
/* Insert new rows */

/* SOURCE CODE */


select 	
	SER_AC.LIFETOUCH_ID	   LIFETOUCH_ID,
	SER_AC.ACCOUNT_NAME	   ACCOUNT_NAME,
	SER_AC.PHYSICAL_ADDRESS_LINE1	   PHYSICAL_ADDRESS_LINE1,
	SER_AC.CITY	   CITY,
	SER_AC.STATE	   STATE,
	SER_AC.CATEGORY_NAME	   CATEGORY_NAME,
	SER_AC.SUBCATEGORY_NAME	   SUBCATEGORY_NAME,
	SER_AC.ENROLLMENT	   ENROLLMENT,
	SER_AC.BUSINESS_PHONE	   BUSINESS_PHONE,
	SER_AC.PARENT_LIFETOUCH_ID	   PARENT_LIFETOUCH_ID
from	RAX_APP_USER.SERVICENOW_ACCOUNT_STAGE   SER_AC
where	
	(1=1)	
	





/* Order the output by the UD1, UD2, UD3, UD4, UD5, UD6 Fields. */



&

/* TARGET CODE */
insert into "/dw_export/PROD/account.csv"
(
	LIFETOUCH_ID,
	ACCOUNT_NAME,
	PHYSICAL_ADDRESS_LINE1,
	CITY,
	STATE,
	CATEGORY_NAME,
	SUBCATEGORY_NAME,
	ENROLLMENT,
	BUSINESS_PHONE,
	PARENT_LIFETOUCH_ID
                     
)
values 
(
	:LIFETOUCH_ID,
	:ACCOUNT_NAME,
	:PHYSICAL_ADDRESS_LINE1,
	:CITY,
	:STATE,
	:CATEGORY_NAME,
	:SUBCATEGORY_NAME,
	:ENROLLMENT,
	:BUSINESS_PHONE,
	:PARENT_LIFETOUCH_ID
                     
)
/*$$SNPS_START_KEYSNP$CRDWG_TABLESNP$CRTABLE_NAME=account.csvSNP$CRLOAD_FILE=/dw_export/PROD/account.csvSNP$CRFILE_FORMAT=DSNP$CRFILE_SEP_FIELD=0x002cSNP$CRFILE_SEP_LINE=0x000D0x000ASNP$CRFILE_FIRST_ROW=0SNP$CRFILE_ENC_FIELD="SNP$CRFILE_DEC_SEP=SNP$CRSNP$CRDWG_COLSNP$CRCOL_NAME=LIFETOUCH_IDSNP$CRTYPE_NAME=STRINGSNP$CRORDER=1SNP$CRLENGTH=50SNP$CRPRECISION=50SNP$CRSNP$CRDWG_COLSNP$CRCOL_NAME=ACCOUNT_NAMESNP$CRTYPE_NAME=STRINGSNP$CRORDER=2SNP$CRLENGTH=90SNP$CRPRECISION=90SNP$CRSNP$CRDWG_COLSNP$CRCOL_NAME=PHYSICAL_ADDRESS_LINE1SNP$CRTYPE_NAME=STRINGSNP$CRORDER=3SNP$CRLENGTH=120SNP$CRPRECISION=120SNP$CRSNP$CRDWG_COLSNP$CRCOL_NAME=CITYSNP$CRTYPE_NAME=STRINGSNP$CRORDER=4SNP$CRLENGTH=60SNP$CRPRECISION=60SNP$CRSNP$CRDWG_COLSNP$CRCOL_NAME=STATESNP$CRTYPE_NAME=STRINGSNP$CRORDER=5SNP$CRLENGTH=60SNP$CRPRECISION=60SNP$CRSNP$CRDWG_COLSNP$CRCOL_NAME=CATEGORY_NAMESNP$CRTYPE_NAME=STRINGSNP$CRORDER=6SNP$CRLENGTH=50SNP$CRPRECISION=50SNP$CRSNP$CRDWG_COLSNP$CRCOL_NAME=SUBCATEGORY_NAMESNP$CRTYPE_NAME=STRINGSNP$CRORDER=7SNP$CRLENGTH=50SNP$CRPRECISION=50SNP$CRSNP$CRDWG_COLSNP$CRCOL_NAME=ENROLLMENTSNP$CRTYPE_NAME=STRINGSNP$CRORDER=8SNP$CRLENGTH=50SNP$CRPRECISION=50SNP$CRSNP$CRDWG_COLSNP$CRCOL_NAME=BUSINESS_PHONESNP$CRTYPE_NAME=STRINGSNP$CRORDER=9SNP$CRLENGTH=50SNP$CRPRECISION=50SNP$CRSNP$CRDWG_COLSNP$CRCOL_NAME=PARENT_LIFETOUCH_IDSNP$CRTYPE_NAME=STRINGSNP$CRORDER=10SNP$CRLENGTH=50SNP$CRPRECISION=50SNP$CR$$SNPS_END_KEY*/



/*-----------------------------------------------*/
/* TASK No. 6 */

chmod 644 /dw_export/PROD/account.csv

&


/*-----------------------------------------------*/
/* TASK No. 7 */

mv /dw_export/PROD/account.csv /dw_export/PROD/finance/ServiceNow/account.csv

&


/*-----------------------------------------------*/
/* TASK No. 8 */
/* drop table */

drop table RAX_APP_USER.SERVICENOW_CONTACT_STAGE

&


/*-----------------------------------------------*/
/* TASK No. 9 */
/* create table */

create table RAX_APP_USER.SERVICENOW_CONTACT_STAGE as
SELECT a.lifetouch_id,
       c.contact_oid,
       c.first_name,
       c.last_name,
       c.title_name,
       c.work_phone,
       c.email_address
  FROM ods_own.account        a,
       ods_own.account        pa,
       ods_own.contact        c,
       ods_own.source_system  ss
 WHERE     1 = 1
       AND a.account_oid = c.account_oid
       AND a.parent_account_oid = pa.account_oid(+)
       AND c.source_system_oid = ss.source_system_oid
       AND ss.source_system_short_name NOT IN ('MDR')
       AND a.active_account_ind = 'A'
       AND (a.category_name<>'Test' OR a.subcategory_name<>'Test')
       AND UPPER(c.email_address) NOT LIKE '%@LIFETOUCH.COM'
       AND UPPER(c.email_address) NOT LIKE '%@LIFETOUCH.CA'
       AND a.account_name not like '%Test Account%' 
     AND EXISTS
               (SELECT 1
                  FROM ods_own.booking_opportunity  bo,
                       (SELECT TO_NUMBER (TO_CHAR (SYSDATE, 'YYYY'))    AS school_year
                          FROM DUAL) curr
                 WHERE     bo.account_oid = a.account_oid
                       AND bo.school_year IN
                               (curr.school_year, curr.school_year - 1)
                       AND bo.booking_status IN ('Agreement Filed'))

&


/*-----------------------------------------------*/
/* TASK No. 10 */
/* Generate header */

create header	(CONTACT_OID,
	FIRST_NAME,
	LAST_NAME,
	TITLE_NAME,
	WORK_PHONE,
	EMAIL_ADDRESS)

/*$$SNPS_START_KEYSNP$CRDWG_TABLESNP$CRTABLE_NAME=contact.csvSNP$CRLOAD_FILE=/dw_export/PROD/contact.csvSNP$CRFILE_FORMAT=DSNP$CRFILE_SEP_FIELD=0x002cSNP$CRFILE_SEP_LINE=0x000D0x000ASNP$CRFILE_FIRST_ROW=0SNP$CRFILE_ENC_FIELD="SNP$CRFILE_DEC_SEP=SNP$CRSNP$CRDWG_COLSNP$CRCOL_NAME=CONTACT_OIDSNP$CRTYPE_NAME=STRINGSNP$CRORDER=1SNP$CRLENGTH=50SNP$CRPRECISION=50SNP$CRSNP$CRDWG_COLSNP$CRCOL_NAME=FIRST_NAMESNP$CRTYPE_NAME=STRINGSNP$CRORDER=2SNP$CRLENGTH=50SNP$CRPRECISION=50SNP$CRSNP$CRDWG_COLSNP$CRCOL_NAME=LAST_NAMESNP$CRTYPE_NAME=STRINGSNP$CRORDER=3SNP$CRLENGTH=50SNP$CRPRECISION=50SNP$CRSNP$CRDWG_COLSNP$CRCOL_NAME=TITLE_NAMESNP$CRTYPE_NAME=STRINGSNP$CRORDER=4SNP$CRLENGTH=255SNP$CRPRECISION=255SNP$CRSNP$CRDWG_COLSNP$CRCOL_NAME=WORK_PHONESNP$CRTYPE_NAME=STRINGSNP$CRORDER=5SNP$CRLENGTH=50SNP$CRPRECISION=50SNP$CRSNP$CRDWG_COLSNP$CRCOL_NAME=EMAIL_ADDRESSSNP$CRTYPE_NAME=STRINGSNP$CRORDER=6SNP$CRLENGTH=120SNP$CRPRECISION=120SNP$CR$$SNPS_END_KEY*/


&


/*-----------------------------------------------*/
/* TASK No. 11 */
/* Insert new rows */

/* SOURCE CODE */


select 	
	SER_CN.CONTACT_OID	   CONTACT_OID,
	SER_CN.FIRST_NAME	   FIRST_NAME,
	SER_CN.LAST_NAME	   LAST_NAME,
	SER_CN.TITLE_NAME	   TITLE_NAME,
	SER_CN.WORK_PHONE	   WORK_PHONE,
	SER_CN.EMAIL_ADDRESS	   EMAIL_ADDRESS
from	RAX_APP_USER.SERVICENOW_CONTACT_STAGE   SER_CN
where	
	(1=1)	
	

And (SER_CN.FIRST_NAME NOT  IN ('-','.','..','...','?','_'))



/* Order the output by the UD1, UD2, UD3, UD4, UD5, UD6 Fields. */



&

/* TARGET CODE */
insert into "/dw_export/PROD/contact.csv"
(
	CONTACT_OID,
	FIRST_NAME,
	LAST_NAME,
	TITLE_NAME,
	WORK_PHONE,
	EMAIL_ADDRESS
                     
)
values 
(
	:CONTACT_OID,
	:FIRST_NAME,
	:LAST_NAME,
	:TITLE_NAME,
	:WORK_PHONE,
	:EMAIL_ADDRESS
                     
)
/*$$SNPS_START_KEYSNP$CRDWG_TABLESNP$CRTABLE_NAME=contact.csvSNP$CRLOAD_FILE=/dw_export/PROD/contact.csvSNP$CRFILE_FORMAT=DSNP$CRFILE_SEP_FIELD=0x002cSNP$CRFILE_SEP_LINE=0x000D0x000ASNP$CRFILE_FIRST_ROW=0SNP$CRFILE_ENC_FIELD="SNP$CRFILE_DEC_SEP=SNP$CRSNP$CRDWG_COLSNP$CRCOL_NAME=CONTACT_OIDSNP$CRTYPE_NAME=STRINGSNP$CRORDER=1SNP$CRLENGTH=50SNP$CRPRECISION=50SNP$CRSNP$CRDWG_COLSNP$CRCOL_NAME=FIRST_NAMESNP$CRTYPE_NAME=STRINGSNP$CRORDER=2SNP$CRLENGTH=50SNP$CRPRECISION=50SNP$CRSNP$CRDWG_COLSNP$CRCOL_NAME=LAST_NAMESNP$CRTYPE_NAME=STRINGSNP$CRORDER=3SNP$CRLENGTH=50SNP$CRPRECISION=50SNP$CRSNP$CRDWG_COLSNP$CRCOL_NAME=TITLE_NAMESNP$CRTYPE_NAME=STRINGSNP$CRORDER=4SNP$CRLENGTH=255SNP$CRPRECISION=255SNP$CRSNP$CRDWG_COLSNP$CRCOL_NAME=WORK_PHONESNP$CRTYPE_NAME=STRINGSNP$CRORDER=5SNP$CRLENGTH=50SNP$CRPRECISION=50SNP$CRSNP$CRDWG_COLSNP$CRCOL_NAME=EMAIL_ADDRESSSNP$CRTYPE_NAME=STRINGSNP$CRORDER=6SNP$CRLENGTH=120SNP$CRPRECISION=120SNP$CR$$SNPS_END_KEY*/



/*-----------------------------------------------*/
/* TASK No. 12 */

chmod 644 /dw_export/PROD/contact.csv

&


/*-----------------------------------------------*/
/* TASK No. 13 */

mv /dw_export/PROD/contact.csv /dw_export/PROD/finance/ServiceNow/contact.csv

&


/*-----------------------------------------------*/
