
select 	
	SNG_RECCUST.COUNTRY_NAME	   COUNTRY_NAME,
	SNG_RECCUST.COMPANY_NAME	   COMPANY_NAME,
	SNG_RECCUST.AREA_NAME	   AREA_NAME,
	SNG_RECCUST.REGION_NAME	   REGION_NAME,
	SNG_RECCUST.TERRITORY_CODE	   TERRITORY_CODE,
	SNG_RECCUST.TM_NAME	   TM_NAME,
	SNG_RECCUST.SUB_PROGRAM_NAME	   SUB_PROGRAM_NAME,
	SNG_RECCUST.ORDER_NO	   ORDER_NO,
	SNG_RECCUST.PHOTOGRAPHY_LOCATION	   PHOTOGRAPHY_LOCATION,
	SNG_RECCUST.STUDIO_CODE	   STUDIO_CODE,
	SNG_RECCUST.ORDER_SALES_CHANNEL	   ORDER_SALES_CHANNEL,
	SNG_RECCUST.SCHOOL_YEAR	   SCHOOL_YEAR,
	SNG_RECCUST.ACCOUNT_NAME	   ACCOUNT_NAME,
	SNG_RECCUST.LIFETOUCH_ID	   LIFETOUCH_ID,
	SNG_RECCUST.ACCT_ADDRESS	   ACCT_ADDRESS,
	SNG_RECCUST.AMOUNT_PAID	   AMOUNT_PAID,
	SNG_RECCUST.SERVICE_SALES	   SERVICE_SALES,
	SNG_RECCUST.PRODUCT_SALES	   PRODUCT_SALES,
	SNG_RECCUST.TOTAL_SALES	   TOTAL_SALES,
	SNG_RECCUST.AMOUNT_DUE	   AMOUNT_DUE,
	SNG_RECCUST.DEPOSIT_AMT	   DEPOSIT_AMT,
	SNG_RECCUST.AR_WRITEOFF_AMT	   AR_WRITEOFF_AMT,
	SNG_RECCUST.OUT_OF_BALANCE_IND	   OUT_OF_BALANCE_IND
from	RAX_APP_USER.ACTUATE_RECCUST_DEPO_STG   SNG_RECCUST
where	
	(1=1)	
	
