

select	
	trim(YFS_STATUS.STATUS_KEY)	   C1_STATUS_KEY,
	trim(YFS_STATUS.STATUS)	   C2_STATUS,
	YFS_STATUS.DESCRIPTION	   C3_DESCRIPTION,
	trim(YFS_STATUS.PROCESS_TYPE_KEY)	   C4_PROCESS_TYPE_KEY,
	YFS_STATUS.STATUS_NAME	   C5_STATUS_NAME,
	YFS_STATUS.STATUS_TYPE	   C6_STATUS_TYPE,
	trim(YFS_STATUS.OWNER_KEY)	   C7_OWNER_KEY,
	YFS_STATUS.REQUIRES_COLLABORATION	   C8_REQUIRES_COLLABORATION,
	YFS_STATUS.LOCKID	   C9_LOCKID,
	YFS_STATUS.CREATETS	   C10_CREATETS,
	YFS_STATUS.MODIFYTS	   C11_MODIFYTS,
	YFS_STATUS.CREATEUSERID	   C12_CREATEUSERID,
	YFS_STATUS.MODIFYUSERID	   C13_MODIFYUSERID,
	YFS_STATUS.CREATEPROGID	   C14_CREATEPROGID,
	YFS_STATUS.MODIFYPROGID	   C15_MODIFYPROGID
from	<schema_name>.YFS_STATUS   YFS_STATUS
where	(1=1)
And (YFS_STATUS.MODIFYTS >= TO_DATE(SUBSTR(:v_cdc_load_date, 1, 19), 'YYYY-MM-DD HH24:MI:SS')  -:v_cdc_overlap
)





