select	
	trim(LT_IMAGE.IMAGE_KEY)	   C1_IMAGE_KEY,
	LT_IMAGE.IMAGE_ID	   C2_IMAGE_ID,
	trim(LT_IMAGE.SESSION_KEY)	   C3_SESSION_KEY,
	trim(LT_IMAGE.PHOTOGRAPHER_ID)	   C4_PHOTOGRAPHER_ID,
	LT_IMAGE.SELLABLE	   C5_SELLABLE,
	LT_IMAGE.PRINTABLE	   C6_PRINTABLE,
	LT_IMAGE.RETOUCH_REQUIRED	   C7_RETOUCH_REQUIRED,
	LT_IMAGE.YEARBOOK_ACCEPTABLE	   C8_YEARBOOK_ACCEPTABLE,
	trim(LT_IMAGE.IMAGE_TYPE)	   C9_IMAGE_TYPE,
	trim(LT_IMAGE.PRIMARY_LAB)	   C10_PRIMARY_LAB,
	trim(LT_IMAGE.PRIMARY_IMAGE_IMPORT_GROUP_ID)	   C11_PRIMARY_IMAGE_IMPORT_GROUP,
	LT_IMAGE.IMAGE_STATUS	   C12_IMAGE_STATUS,
	LT_IMAGE.CREATETS	   C13_CREATETS,
	LT_IMAGE.MODIFYTS	   C14_MODIFYTS,
	LT_IMAGE.CREATEUSERID	   C15_CREATEUSERID,
	LT_IMAGE.MODIFYUSERID	   C16_MODIFYUSERID,
	LT_IMAGE.CREATEPROGID	   C17_CREATEPROGID,
	LT_IMAGE.MODIFYPROGID	   C18_MODIFYPROGID,
	LT_IMAGE.LOCKID	   C19_LOCKID,
	LT_IMAGE.LAB_REVISION_NO	   C20_LAB_REVISION_NO
from	<schema_name>.LT_IMAGE   LT_IMAGE
where	(1=1)
And (LT_IMAGE.MODIFYTS >= TO_DATE(SUBSTR(:v_cdc_load_date, 1, 19), 'YYYY-MM-DD HH24:MI:SS')  -:v_cdc_overlap
)
 And (LT_IMAGE.IMAGE_ID is not null)