DECLARE create_query CLOB;  
   BEGIN  
      BEGIN  
         EXECUTE IMMEDIATE 'drop table RAX_APP_USER.C$_0OMS2_YFS_STATUS_STG purge';  
      EXCEPTION  
         WHEN OTHERS THEN NULL;  
      END;  
      create_query := 'create table RAX_APP_USER.C$_0OMS2_YFS_STATUS_STG
(
	C1_STATUS_KEY	VARCHAR2(24) NULL,
	C2_STATUS	VARCHAR2(15) NULL,
	C3_DESCRIPTION	VARCHAR2(100) NULL,
	C4_PROCESS_TYPE_KEY	VARCHAR2(24) NULL,
	C5_STATUS_NAME	VARCHAR2(50) NULL,
	C6_STATUS_TYPE	VARCHAR2(15) NULL,
	C7_OWNER_KEY	VARCHAR2(24) NULL,
	C8_REQUIRES_COLLABORATION	VARCHAR2(1) NULL,
	C9_LOCKID	NUMBER NULL,
	C10_CREATETS	DATE NULL,
	C11_MODIFYTS	DATE NULL,
	C12_CREATEUSERID	VARCHAR2(40) NULL,
	C13_MODIFYUSERID	VARCHAR2(40) NULL,
	C14_CREATEPROGID	VARCHAR2(40) NULL,
	C15_MODIFYPROGID	VARCHAR2(40) NULL
)
NOLOGGING';  
      EXECUTE IMMEDIATE create_query;  
   END;  