DECLARE create_query CLOB;  
   BEGIN  
      BEGIN  
         EXECUTE IMMEDIATE 'drop table RAX_APP_USER.C$_0OMS2_LT_IMAGE_STG purge';  
      EXCEPTION  
         WHEN OTHERS THEN NULL;  
      END;  
      create_query := 'create table RAX_APP_USER.C$_0OMS2_LT_IMAGE_STG
(
	C1_IMAGE_KEY	VARCHAR2(24) NULL,
	C2_IMAGE_ID	VARCHAR2(40) NULL,
	C3_SESSION_KEY	VARCHAR2(24) NULL,
	C4_PHOTOGRAPHER_ID	VARCHAR2(24) NULL,
	C5_SELLABLE	VARCHAR2(1) NULL,
	C6_PRINTABLE	VARCHAR2(1) NULL,
	C7_RETOUCH_REQUIRED	VARCHAR2(1) NULL,
	C8_YEARBOOK_ACCEPTABLE	VARCHAR2(1) NULL,
	C9_IMAGE_TYPE	VARCHAR2(24) NULL,
	C10_PRIMARY_LAB	VARCHAR2(24) NULL,
	C11_PRIMARY_IMAGE_IMPORT_GROUP	VARCHAR2(24) NULL,
	C12_IMAGE_STATUS	VARCHAR2(15) NULL,
	C13_CREATETS	DATE NULL,
	C14_MODIFYTS	DATE NULL,
	C15_CREATEUSERID	VARCHAR2(40) NULL,
	C16_MODIFYUSERID	VARCHAR2(40) NULL,
	C17_CREATEPROGID	VARCHAR2(40) NULL,
	C18_MODIFYPROGID	VARCHAR2(40) NULL,
	C19_LOCKID	NUMBER NULL,
	C20_LAB_REVISION_NO	NUMBER NULL
)
NOLOGGING';  
      EXECUTE IMMEDIATE create_query;  
   END;  