DECLARE create_query CLOB;  
   BEGIN  
      BEGIN  
         EXECUTE IMMEDIATE 'drop table RAX_APP_USER.C$_0OMS2_LT_SB_A_SES_STG purge';  
      EXCEPTION  
         WHEN OTHERS THEN NULL;  
      END;  
      create_query := 'create table RAX_APP_USER.C$_0OMS2_LT_SB_A_SES_STG
(
	C1_SESSION_KEY	VARCHAR2(24) NULL,
	C2_SUBJECT_KEY	VARCHAR2(24) NULL,
	C3_APO_KEY	VARCHAR2(24) NULL,
	C4_SIT_TYPE	VARCHAR2(15) NULL,
	C5_LOCATION	VARCHAR2(15) NULL,
	C6_EXECUTION_DATE	DATE NULL,
	C7_CREATETS	DATE NULL,
	C8_MODIFYTS	DATE NULL,
	C9_CREATEUSERID	VARCHAR2(40) NULL,
	C10_MODIFYUSERID	VARCHAR2(40) NULL,
	C11_CREATEPROGID	VARCHAR2(40) NULL,
	C12_MODIFYPROGID	VARCHAR2(40) NULL,
	C13_LOCKID	NUMBER NULL
)
NOLOGGING';  
      EXECUTE IMMEDIATE create_query;  
   END;  