SELECT count(*),MAX(BATCH_CREATE_DATE)
FROM  ODS_OWN.WORK_ORDER_BATCH WOB,
      ODS_OWN.APO,
      ODS_OWN.EVENT E,
      ODS_OWN.SUB_PROGRAM SP,
      ODS_OWN.PROGRAM P,
      MART.TIME T
      WHERE 1 = 1
      AND WOB.EVENT_OID = E.EVENT_OID(+)
      AND WOB.APO_OID = APO.APO_OID(+)
      AND APO.SUB_PROGRAM_OID = SP.SUB_PROGRAM_OID(+)
      AND SP.PROGRAM_OID = P.PROGRAM_OID
      AND TRUNC(WOB.BATCH_CREATE_DATE) = T.DATE_KEY
      AND WOB.STATUS_DESC NOT IN ('Cancelled')
      AND WOB.SHIPPED_DATE IS NULL
      AND APO.TERRITORY_CODE NOT IN ('LN')
      AND APO.SCHOOL_YEAR >= (SELECT FISCAL_YEAR - 1 FROM MART.TIME WHERE DATE_KEY = trunc(sysdate))
ORDER BY WOB.LAB,WOB.BATCH_CREATE_DATE
--COUNT(*)|MAX(BATCH_CREATE_DATE)|
----------+----------------------+
--     176|   2024-08-13 08:16:27|

SELECT count(*),max(BATCH_CREATE_DATE) FROM RAX_APP_USER.PPS_UNSHIPPED_WOB_STG
ORDER BY BATCH_CREATE_DATE DESC

--COUNT(*)|MAX(BATCH_CREATE_DATE)|
----------+----------------------+
--     176|   2024-08-13 08:16:27|

drop table RAX_APP_USER.PPS_UNSHIPPED_WOB_STG

-- Run The DAG

SELECT count(*),max(BATCH_CREATE_DATE) FROM RAX_APP_USER.PPS_UNSHIPPED_WOB_STG
ORDER BY BATCH_CREATE_DATE DESC
--COUNT(*)|MAX(BATCH_CREATE_DATE)|
----------+----------------------+
--     176|   2024-08-13 08:16:27|