SELECT * FROM ODS_OWN.ODS_CDC_LOAD_STATUS
WHERE ODS_TABLE_NAME = 'UC_LAWSON_REFUNDS'


SELECT * FROM
RAX_APP_USER.ODS_CDC_LOAD_STATUS_AUDIT
WHERE SESS_NAME  = '99_UC_LAWSON_REFUNDS_PKG'
ORDER BY CREATE_DATE desc



SELECT APO.SCHOOL_YEAR,
       APO.APO_ID,
       EVENT.TERRITORY_CODE,
       SUB_PROGRAM.SUB_PROGRAM_NAME,
       EVENT.EVENT_REF_ID,
       EVENT_PAYMENT.PAYMENT_AMOUNT     AS REFUND_AMOUNT,
       EVENT_PAYMENT.CARDHOLDER_NAME,
       EVENT_PAYMENT.CHECK_NUMBER,
       EVENT_PAYMENT.RECORD_STATUS,
       EVENT_PAYMENT.PAYMENT_DATE
  FROM ODS_OWN.EVENT          EVENT,
       ODS_OWN.EVENT_PAYMENT  EVENT_PAYMENT,
       ODS_OWN.PAYMENT_TYPE   PAYMENT_TYPE,
       ODS_OWN.SUB_PROGRAM    SUB_PROGRAM,
       ODS_OWN.APO            APO
 WHERE     (SUB_PROGRAM.SUB_PROGRAM_NAME != 'Yearbook')
       AND (EVENT_PAYMENT.ODS_CREATE_DATE BETWEEN TRUNC (
                                                        TRUNC (SYSDATE, 'MM')
                                                      - 1,
                                                      'MM')
                                              AND TRUNC (SYSDATE, 'MM') - 1)
       AND (EVENT_PAYMENT.PAYMENT_AMOUNT != 0)
       AND (PAYMENT_TYPE.PAYMENT_TYPE = 'RefundCheck')
       AND (EVENT_PAYMENT.EVENT_OID = EVENT.EVENT_OID)
       AND (EVENT_PAYMENT.PAYMENT_TYPE_OID = PAYMENT_TYPE.PAYMENT_TYPE_OID)
       AND (EVENT.APO_OID = APO.APO_OID)
       AND (APO.SUB_PROGRAM_OID = SUB_PROGRAM.SUB_PROGRAM_OID)
       union all
       SELECT APO.SCHOOL_YEAR,
       APO.APO_ID,
       EVENT.TERRITORY_CODE,
       SUB_PROGRAM.SUB_PROGRAM_NAME,
       EVENT.EVENT_REF_ID,
       pr.PAYMENT_AMOUNT     AS REFUND_AMOUNT,
       EVENT_PAYMENT.CARDHOLDER_NAME,
       EVENT_PAYMENT.CHECK_NUMBER,
       EVENT_PAYMENT.RECORD_STATUS,
       trunc(EVENT_PAYMENT.ODS_MODIFY_DATE)
  FROM ODS_OWN.EVENT          EVENT,
       ODS_OWN.EVENT_PAYMENT  EVENT_PAYMENT,
       ODS_OWN.PAYMENT_TYPE   PAYMENT_TYPE,
       ODS_OWN.SUB_PROGRAM    SUB_PROGRAM,
       ODS_OWN.APO            APO,
       ODS_OWN.ACCT_COMM_PMT_REQ pr
 WHERE     (SUB_PROGRAM.SUB_PROGRAM_NAME != 'Yearbook')
       AND (EVENT_PAYMENT.ODS_MODIFY_DATE BETWEEN TRUNC (
                                                        TRUNC (SYSDATE, 'MM')
                                                      - 1,
                                                      'MM')
                                              AND TRUNC (SYSDATE, 'MM') - 1)
       AND (EVENT_PAYMENT.PAYMENT_AMOUNT = 0)
       AND (PAYMENT_TYPE.PAYMENT_TYPE = 'RefundCheck')
       AND (EVENT_PAYMENT.EVENT_OID = EVENT.EVENT_OID)
       AND (EVENT_PAYMENT.PAYMENT_TYPE_OID = PAYMENT_TYPE.PAYMENT_TYPE_OID)
       AND (EVENT.APO_OID = APO.APO_OID)
       AND (APO.SUB_PROGRAM_OID = SUB_PROGRAM.SUB_PROGRAM_OID)
       and pr.ACCT_COMM_PMT_REQ_ID = EVENT_PAYMENT.ACCT_COMM_PMT_REQ_ID


select count(*)
from	RAX_APP_USER.UC_LAWSON_REFUNDS   UC_LAWSON_REFUNDS