SELECT * FROM ODS.DW_CDC_LOAD_STATUS
WHERE DW_TABLE_NAME = 'STG_SODS_CSF'

--DW_TABLE_NAME|LAST_CDC_COMPLETION_DATE|CONTEXT_NAME|TIMEZONE_OFFSET|
---------------+------------------------+------------+---------------+
--STG_SODS_CSF |     2024-09-08 03:00:16|QA          |               |



--select	APO_CODE
--		from	RAX_APP_USER.I$_ODS_CSF_SUMMARY
--		where	IND_UPDATE = 'U'

--		select 	APO_CODE,
--	CAPTURE_SESSION_QTY,
--	STAFF_CAPTURE_SESSION_QTY,
--	CLICK_QTY,
--	ODS_CREATE_DATE,
--	ODS_MODIFY_DATE
--	,      ODS.ODS_CSF_SUMMARY_ID_SEQ.nextval,
--	SYSDATE
--from	RAX_APP_USER.I$_ODS_CSF_SUMMARY S


select	*
from	ODS_OWN.APO   APO, ODS_OWN.SOURCE_SYSTEM   SOURCE_SYSTEM
where	(1=1)
--And (APO.ODS_MODIFY_DATE >= TO_DATE(SUBSTR(':v_cdc_load_date', 1, 19), 'YYYY-MM-DD HH24:MI:SS') - :v_cdc_sales_ods_overlap)
 And (SOURCE_SYSTEM.SOURCE_SYSTEM_SHORT_NAME = 'OMS2')
 And (APO.SOURCE_SYSTEM_OID=SOURCE_SYSTEM.SOURCE_SYSTEM_OID)
 AND APO.APO_ID = '9KKZ'

 select 1 from ODS.ODS_CSF_SUMMARY T
	where	T.APO_CODE	= S.APO_CODE
		 and ((T.CAPTURE_SESSION_QTY = S.CAPTURE_SESSION_QTY) or (T.CAPTURE_SESSION_QTY IS NULL and S.CAPTURE_SESSION_QTY IS NULL)) and
		((T.STAFF_CAPTURE_SESSION_QTY = S.STAFF_CAPTURE_SESSION_QTY) or (T.STAFF_CAPTURE_SESSION_QTY IS NULL and S.STAFF_CAPTURE_SESSION_QTY IS NULL)) and
		((T.CLICK_QTY = S.CLICK_QTY) or (T.CLICK_QTY IS NULL and S.CLICK_QTY IS NULL)) and
		((T.ODS_MODIFY_DATE = S.ODS_MODIFY_DATE) or (T.ODS_MODIFY_DATE IS NULL and S.ODS_MODIFY_DATE IS NULL))

SELECT * FROM ODS.ODS_CSF_SUMMARY ORDER BY EFFECTIVE_DATE DESC FETCH FIRST 10 ROWS ONLY
--ODS_CSF_SUMMARY_ID|EFFECTIVE_DATE     |APO_CODE|CAPTURE_SESSION_QTY|STAFF_CAPTURE_SESSION_QTY|CLICK_QTY|ODS_CREATE_DATE    |ODS_MODIFY_DATE    |
--------------------+-------------------+--------+-------------------+-------------------------+---------+-------------------+-------------------+
--             11422|2024-09-03 05:53:32|9G4X    |                  1|                         |       19|2024-09-03 05:53:32|2024-09-03 05:53:32|
--             10904|2024-09-03 05:01:16|98Y3    |                  1|                         |       19|2023-11-21 10:44:31|2024-09-03 05:01:15|
--              9764|2024-09-01 04:04:19|8MBZ    |                  1|                         |        9|2023-04-19 08:33:32|2024-09-01 04:04:18|
--              9503|2024-09-01 04:04:19|8JC6    |                  1|                         |       19|2023-04-08 04:31:02|2024-09-01 04:04:18|
--              7378|2024-09-01 04:04:19|8367    |                  1|                         |       19|2022-05-30 09:35:25|2024-09-01 04:04:18|
--              6191|2024-09-01 04:04:19|7WG6    |                  1|                         |       19|2021-01-25 13:40:37|2024-09-01 04:04:18|
--              6009|2024-09-01 04:04:19|7K32    |                  1|                         |       19|2020-01-17 12:59:09|2024-09-01 04:04:18|
--             12163|2024-08-30 16:04:09|9KJ7    |                   |                         |         |2024-08-30 12:04:07|2024-08-30 16:04:08|
--             12131|2024-08-29 08:04:01|9JV2    |                  2|                         |       19|2024-08-27 08:03:46|2024-08-29 08:04:00|
--              7978|2024-08-29 08:04:01|86ZZ    |                  1|                         |       19|2022-12-13 09:25:09|2024-08-29 08:04:00|




 SELECT * FROM ODS.ODS_CSF_SUMMARY WHERE ODS_CSF_SUMMARY_ID = '12403'
--ODS_CSF_SUMMARY_ID|EFFECTIVE_DATE     |APO_CODE|CAPTURE_SESSION_QTY|STAFF_CAPTURE_SESSION_QTY|CLICK_QTY|ODS_CREATE_DATE    |ODS_MODIFY_DATE    |
--------------------+-------------------+--------+-------------------+-------------------------+---------+-------------------+-------------------+
--             12403|2024-09-06 07:00:20|9KKZ    |                   |                         |         |2024-09-06 03:00:27|2024-09-06 07:00:19|


insert into RAX_APP_USER.C$_0ODS_CSF_SUMMARY
(
	C1_APO_CODE,
	C2_CAPTURE_SESSION_QTY,
	C3_STAFF_CAPTURE_SESSION_QTY,
	C4_CLICK_QTY,
	C5_ODS_CREATE_DATE,
	C6_ODS_MODIFY_DATE
)
select
	APO.APO_ID	   C1_APO_CODE,
	APO.CAPTURE_SESSION_QTY	   C2_CAPTURE_SESSION_QTY,
	APO.STAFF_CAPTURE_SESSION_QTY	   C3_STAFF_CAPTURE_SESSION_QTY,
	APO.CLICK_QTY	   C4_CLICK_QTY,
	SYSDATE	   C5_ODS_CREATE_DATE,
	SYSDATE	   C6_ODS_MODIFY_DATE
from	ODS_OWN.APO   APO, ODS_OWN.SOURCE_SYSTEM   SOURCE_SYSTEM
where	(1=1)
And (APO.ODS_MODIFY_DATE >=  TO_DATE(SUBSTR('2017-07-01 00:00:00', 1, 19), 'YYYY-MM-DD HH24:MI:SS'))
 And (SOURCE_SYSTEM.SOURCE_SYSTEM_SHORT_NAME = 'OMS2')
 And (APO.SOURCE_SYSTEM_OID=SOURCE_SYSTEM.SOURCE_SYSTEM_OID)

 create table RAX_APP_USER.I$_ODS_CSF_SUMMARY
(
	ODS_CSF_SUMMARY_ID		NUMBER NULL,
	EFFECTIVE_DATE		DATE NULL,
	APO_CODE		VARCHAR2(20) NULL,
	CAPTURE_SESSION_QTY		NUMBER NULL,
	STAFF_CAPTURE_SESSION_QTY		NUMBER NULL,
	CLICK_QTY		NUMBER NULL,
	ODS_CREATE_DATE		DATE NULL,
	ODS_MODIFY_DATE		DATE NULL,
	IND_UPDATE		CHAR(1)
)

 insert into	RAX_APP_USER.I$_ODS_CSF_SUMMARY
(
	APO_CODE,
	CAPTURE_SESSION_QTY,
	STAFF_CAPTURE_SESSION_QTY,
	CLICK_QTY,
	ODS_CREATE_DATE,
	ODS_MODIFY_DATE,
	IND_UPDATE
)
select
APO_CODE,
	CAPTURE_SESSION_QTY,
	STAFF_CAPTURE_SESSION_QTY,
	CLICK_QTY,
	ODS_CREATE_DATE,
	ODS_MODIFY_DATE,
	IND_UPDATE
 from (


select

	C1_APO_CODE APO_CODE,
	C2_CAPTURE_SESSION_QTY CAPTURE_SESSION_QTY,
	C3_STAFF_CAPTURE_SESSION_QTY STAFF_CAPTURE_SESSION_QTY,
	C4_CLICK_QTY CLICK_QTY,
	C5_ODS_CREATE_DATE ODS_CREATE_DATE,
	C6_ODS_MODIFY_DATE ODS_MODIFY_DATE,

	'I' IND_UPDATE

from	RAX_APP_USER.C$_0ODS_CSF_SUMMARY
where	(1=1)






) S
where NOT EXISTS
	( select 1 from ODS.ODS_CSF_SUMMARY T
	where	T.APO_CODE	= S.APO_CODE
		 and ((T.CAPTURE_SESSION_QTY = S.CAPTURE_SESSION_QTY) or (T.CAPTURE_SESSION_QTY IS NULL and S.CAPTURE_SESSION_QTY IS NULL)) and
		((T.STAFF_CAPTURE_SESSION_QTY = S.STAFF_CAPTURE_SESSION_QTY) or (T.STAFF_CAPTURE_SESSION_QTY IS NULL and S.STAFF_CAPTURE_SESSION_QTY IS NULL)) and
		((T.CLICK_QTY = S.CLICK_QTY) or (T.CLICK_QTY IS NULL and S.CLICK_QTY IS NULL)) and
		((T.ODS_MODIFY_DATE = S.ODS_MODIFY_DATE) or (T.ODS_MODIFY_DATE IS NULL and S.ODS_MODIFY_DATE IS NULL))
        )


        update	RAX_APP_USER.I$_ODS_CSF_SUMMARY
set	IND_UPDATE = 'U'
where	(APO_CODE)
	in	(
		select	APO_CODE
		from	ODS.ODS_CSF_SUMMARY
		)

		SELECT * FROM RAX_APP_USER.I$_ODS_CSF_SUMMARY

		update	ODS.ODS_CSF_SUMMARY T
set
	(
	T.CAPTURE_SESSION_QTY,
	T.STAFF_CAPTURE_SESSION_QTY,
	T.CLICK_QTY,
	T.ODS_MODIFY_DATE
	) =
		(
		select	S.CAPTURE_SESSION_QTY,
			S.STAFF_CAPTURE_SESSION_QTY,
			S.CLICK_QTY,
			S.ODS_MODIFY_DATE
		from	RAX_APP_USER.I$_ODS_CSF_SUMMARY S
		where	T.APO_CODE	=S.APO_CODE
	    	 )
	,    T.EFFECTIVE_DATE = SYSDATE

where	(APO_CODE)
	in	(
		select	APO_CODE
		from	RAX_APP_USER.I$_ODS_CSF_SUMMARY
		where	IND_UPDATE = 'U'
		)


       insert into RAX_APP_USER.SNP_CHECK_TAB
(
	SCHEMA_NAME,
	RESOURCE_NAME,
	FULL_RES_NAME,
	ERR_TYPE,
	ERR_MESS,
	CHECK_DATE,
	ORIGIN,
	CONS_NAME,
	CONS_TYPE,
	ERR_COUNT
)
select
	'ODS',
	'ODS_CSF_SUMMARY',
	'ODS.ODS_CSF_SUMMARY',
	E.ODI_ERR_TYPE,
	E.ODI_ERR_MESS,
	E.ODI_CHECK_DATE,
	E.ODI_ORIGIN,
	E.ODI_CONS_NAME,
	E.ODI_CONS_TYPE,
	count(1)
from	RAX_APP_USER.E$_ODS_CSF_SUMMARY E
where	E.ODI_ERR_TYPE	= 'F'
and	E.ODI_ORIGIN 	= '(235003)Warehouse_Project.LOAD_ODS_CSF_SUMMARY'
group by	E.ODI_ERR_TYPE,
	E.ODI_ERR_MESS,
	E.ODI_CHECK_DATE,
	E.ODI_ORIGIN,
	E.ODI_CONS_NAME,
	E.ODI_CONS_TYPE


SELECT * FROM RAX_APP_USER.I$_ODS_CSF_SUMMARY WHERE APO_CODE = '9G4X'

select 	APO_CODE,
	CAPTURE_SESSION_QTY,
	STAFF_CAPTURE_SESSION_QTY,
	CLICK_QTY,
	ODS_CREATE_DATE,
	ODS_MODIFY_DATE
	,      ODS.ODS_CSF_SUMMARY_ID_SEQ.nextval,
	SYSDATE
from	RAX_APP_USER.I$_ODS_CSF_SUMMARY S



where	IND_UPDATE = 'I' AND APO_CODE = '9G4X'



UPDATE ODS.ODS_CSF_SUMMARY
SET CAPTURE_SESSION_QTY = 0
WHERE ODS_CSF_SUMMARY_ID = '11422'

SELECT * FROM ODS.ODS_CSF_SUMMARY WHERE ODS_CSF_SUMMARY_ID = '11422'

-- ODS_CSF_SUMMARY_ID|EFFECTIVE_DATE     |APO_CODE|CAPTURE_SESSION_QTY|STAFF_CAPTURE_SESSION_QTY|CLICK_QTY|ODS_CREATE_DATE    |ODS_MODIFY_DATE    |
--------------------+-------------------+--------+-------------------+-------------------------+---------+-------------------+-------------------+
--             11422|2024-09-03 06:14:49|9G4X    |                  0|                         |       19|2024-09-03 06:14:49|2024-09-03 06:14:49|


UPDATE ODS.DW_CDC_LOAD_STATUS
SET last_cdc_completion_date = TO_DATE(SUBSTR('2017-07-01 00:00:00', 1, 19), 'YYYY-MM-DD HH24:MI:SS')
WHERE DW_TABLE_NAME= 'STG_SODS_CSF'

-- run the dag

SELECT * FROM ODS.ODS_CSF_SUMMARY WHERE ODS_CSF_SUMMARY_ID = '11422'
--ODS_CSF_SUMMARY_ID|EFFECTIVE_DATE     |APO_CODE|CAPTURE_SESSION_QTY|STAFF_CAPTURE_SESSION_QTY|CLICK_QTY|ODS_CREATE_DATE    |ODS_MODIFY_DATE    |
--------------------+-------------------+--------+-------------------+-------------------------+---------+-------------------+-------------------+
--             11422|2024-09-03 07:01:21|9G4X    |                  1|                         |       19|2024-09-03 06:14:49|2024-09-03 07:01:20|



SELECT count(*) FROM ODS.ODS_CSF_SUMMARY
--COUNT(*)|
----------+
--    6139|

SELECT * FROM ODS.ODS_CSF_SUMMARY WHERE APO_CODE = '9G4X'
--ODS_CSF_SUMMARY_ID|EFFECTIVE_DATE     |APO_CODE|CAPTURE_SESSION_QTY|STAFF_CAPTURE_SESSION_QTY|CLICK_QTY|ODS_CREATE_DATE    |ODS_MODIFY_DATE    |
--------------------+-------------------+--------+-------------------+-------------------------+---------+-------------------+-------------------+
--             11422|2024-09-03 05:53:32|9G4X    |                  1|                         |       19|2024-09-03 05:53:32|2024-09-03 05:53:32|

-- run the dag

 SELECT count(*) FROM ODS.ODS_CSF_SUMMARY
--COUNT(*)|
----------+
--    6139|

-- run the dag

SELECT * FROM ODS.ODS_CSF_SUMMARY WHERE APO_CODE = '9G4X'
--ODS_CSF_SUMMARY_ID|EFFECTIVE_DATE     |APO_CODE|CAPTURE_SESSION_QTY|STAFF_CAPTURE_SESSION_QTY|CLICK_QTY|ODS_CREATE_DATE    |ODS_MODIFY_DATE    |
--------------------+-------------------+--------+-------------------+-------------------------+---------+-------------------+-------------------+
--             11422|2024-09-03 05:53:32|9G4X    |                  1|                         |       19|2024-09-03 05:53:32|2024-09-03 05:53:32|


 -----------------------------------------------
select
APO_CODE,
	CAPTURE_SESSION_QTY,
	STAFF_CAPTURE_SESSION_QTY,
	CLICK_QTY,
	ODS_CREATE_DATE,
	ODS_MODIFY_DATE,
	IND_UPDATE
 from (
select
	C1_APO_CODE APO_CODE,
	C2_CAPTURE_SESSION_QTY CAPTURE_SESSION_QTY,
	C3_STAFF_CAPTURE_SESSION_QTY STAFF_CAPTURE_SESSION_QTY,
	C4_CLICK_QTY CLICK_QTY,
	C5_ODS_CREATE_DATE ODS_CREATE_DATE,
	C6_ODS_MODIFY_DATE ODS_MODIFY_DATE,
	'I' IND_UPDATE
from	RAX_APP_USER.C$_0ODS_CSF_SUMMARY
where	(1=1)
) S
where NOT EXISTS
	( select 1 from ODS.ODS_CSF_SUMMARY T
	where	T.APO_CODE	= S.APO_CODE
		 and ((T.CAPTURE_SESSION_QTY = S.CAPTURE_SESSION_QTY) or (T.CAPTURE_SESSION_QTY IS NULL and S.CAPTURE_SESSION_QTY IS NULL)) and
		((T.STAFF_CAPTURE_SESSION_QTY = S.STAFF_CAPTURE_SESSION_QTY) or (T.STAFF_CAPTURE_SESSION_QTY IS NULL and S.STAFF_CAPTURE_SESSION_QTY IS NULL)) and
		((T.CLICK_QTY = S.CLICK_QTY) or (T.CLICK_QTY IS NULL and S.CLICK_QTY IS NULL)) and
		((T.ODS_MODIFY_DATE = S.ODS_MODIFY_DATE) or (T.ODS_MODIFY_DATE IS NULL and S.ODS_MODIFY_DATE IS NULL))
        )

