select * FROM MART.WORK_ORDER_BATCH_FACT
ORDER BY MART_MODIFY_DATE DESC FETCH FIRST 10 ROWS ONLY

--WORK_ORDER_BATCH_OID|MARKETING_ID|ACCOUNT_ID|ITEM_ID|APO_ID  |EVENT_ID|JOB_TICKET_ORG_ID|WORK_ORDER_BATCH_JUNK_ID|SHIPMENT_OID|PARENT_ORDER_HEADER_OID|BATCH_ID           |BATCH_CREATE_DATE_KEY|READY_FULLFILLMENT_DATE_KEY|PRINT_DATE_KEY|COMPLETE_DATE_KEY|BINNED_DATE_KEY|PACKED_DATE_KEY|SHIPPED_DATE_KEY|AVAILABLE_DATE_KEY |STATUS_DESC     |TOTAL_TASKS|TOTAL_COMPLTD_TASKS|TOTAL_PAGES|TOTAL_WORK_ORDERS|DEVICE_GROUP       |FULFILLMENT_TYPE|START_PAGE|END_PAGE|MAKEOVER_REASON|REASON_DESC|CANCEL_COMMENT|BIN_LOCATION|ORDER_NO|MART_CREATE_DATE   |MART_MODIFY_DATE   |CALC_READY_FULLFILL_DATE_KEY|CALC_COMPLETE_DATE_KEY|READY_FULLFILL_COMP_DAYS|MANUFACTURER_ITEM|BOC_BATCH_ID  |TOTAL_ORDERS|BUYER_COUNT|MAGNET|BUTTONS|PLAQUES|TRADER_CARDS|STANDARD_PRINTS|TP16X20|TP11X14|
----------------------+------------+----------+-------+--------+--------+-----------------+------------------------+------------+-----------------------+-------------------+---------------------+---------------------------+--------------+-----------------+---------------+---------------+----------------+-------------------+----------------+-----------+-------------------+-----------+-----------------+-------------------+----------------+----------+--------+---------------+-----------+--------------+------------+--------+-------------------+-------------------+----------------------------+----------------------+------------------------+-----------------+--------------+------------+-----------+------+-------+-------+------------+---------------+-------+-------+
--               55510|         275|     97466|6048484|10135530|11046121|              120|                       3|            |                       |Consumer_Test1_CD  |                     |                           |              |                 |               |               |                |2024-09-26 02:18:33|Partially Binned|          3|                  0|          0|               16|Indigo Printing    |                |0         |0       |               |           |              |FOWRCP7     |        |2019-06-07 16:05:37|2024-09-26 02:00:25|                            |                      |                        |69969            |Consumer_Test1|            |           |      |       |       |            |               |       |       |
--              269315|      900314|     41941|6035674|10135769|39861221|           340006|                       3|            |                       |OMSTEST-12-Pkg     |                     |                           |              |                 |               |               |                |2024-09-26 02:18:33|Partially Binned|          3|                  0|          0|                3|NoritsuR2P Printing|                |0         |0       |               |           |              |FOWF887     |        |2019-06-07 16:05:37|2024-09-26 02:00:25|                            |                      |                        |                 |OMSTEST_12    |           3|           |      |       |       |            |               |       |       |
--              269171|      900314|     41941|6035674|10135769|39861221|           340006|                       3|            |                       |OMSTEST-5-Pkg      |                     |                           |              |                 |               |               |                |2024-09-26 02:18:33|Partially Binned|          3|                  0|          0|                3|NoritsuR2P Printing|                |0         |0       |               |           |              |FOWF887     |        |2019-06-07 16:05:37|2024-09-26 02:00:25|                            |                      |                        |                 |OMSTEST_5     |           3|           |      |       |       |            |               |       |       |
--              269176|      900314|     41941|6048475|10135769|39861221|           340006|                       3|            |                       |OMSTEST-2-CD       |                     |                           |              |                 |               |               |                |2024-09-26 02:18:33|Partially Binned|          3|                  0|          0|                3|NoritsuR2P Printing|                |0         |0       |               |           |              |FOWF887     |        |2019-06-07 16:05:37|2024-09-26 02:00:25|                            |                      |                        |                 |OMSTEST_2     |           3|           |      |       |       |            |               |       |       |
--              465635|      900314|     41941|6035690|10135769|39861221|           340006|                       3|            |                       |UPDATEBINPT-2-PKG  |                     |                           |              |                 |               |               |                |2024-09-26 02:18:31|Partially Binned|          3|                  0|          0|              140|NoritsuR2P Printing|                |0         |0       |               |           |              |FOWF887     |        |2019-06-07 16:05:37|2024-09-26 02:00:25|                            |                      |                        |MIP00232         |UPDATEBINPT_2 |          10|           |      |       |       |            |               |       |       |
--              272407|         275|     97466|6048474|10135530|39140884|              120|                       3|            |                       |TEST-CONS1-Pick    |                     |                           |              |                 |               |               |                |2024-09-26 02:18:33|Partially Binned|          3|                  0|          0|                5|NoritsuR2P Printing|                |0         |0       |               |           |              |FOWRCP7     |        |2019-06-07 16:05:37|2024-09-26 02:00:25|                            |                      |                        |90515            |TEST_CONS1    |           5|           |      |       |       |            |               |       |       |
--              355836|      900314|     41941|6048482|10135769|39801409|           340006|                       3|            |                       |LN806244X0-23-Pkg  |                     |                           |              |                 |               |               |                |2024-09-26 02:18:31|Partially Binned|          3|                  0|          0|                4|NoritsuR2P Printing|                |0         |0       |               |           |              |FOWF887     |        |2019-06-07 16:05:37|2024-09-26 02:00:25|                            |                      |                        |                 |LN806244X0_23 |           2|           |      |       |       |            |               |       |       |
--               55515|         275|     97466|6048483|10135530|11046121|              120|                       3|            |                       |Consumer_Test3_Pick|                     |                           |              |                 |               |               |                |2024-09-26 02:18:33|Partially Binned|          3|                  0|          0|                2|Indigo Printing    |                |0         |0       |               |           |              |FOWRCP7     |        |2019-06-07 16:05:37|2024-09-26 02:00:25|                            |                      |                        |                 |Consumer_Test3|            |           |      |       |       |            |               |       |       |
--               55512|         275|     97466|6048484|10135530|11046121|              120|                       3|            |                       |Consumer_Test3_CD  |                     |                           |              |                 |               |               |                |2024-09-26 02:18:33|Partially Binned|          3|                  0|          0|                4|Indigo Printing    |                |0         |0       |               |           |              |FOWRCP7     |        |2019-06-07 16:05:37|2024-09-26 02:00:25|                            |                      |                        |69969            |Consumer_Test3|            |           |      |       |       |            |               |       |       |
--               55511|         275|     97466|6048484|10135530|11046121|              120|                       3|            |                       |Consumer_Test2_CD  |                     |                           |              |                 |               |               |                |2024-09-26 02:18:33|Partially Binned|          3|                  0|          0|               20|Indigo Printing    |                |0         |0       |               |           |              |FOWRCP7     |        |2019-06-07 16:05:37|2024-09-26 02:00:25|                            |                      |                        |69969            |Consumer_Test2|            |           |      |       |       |            |               |       |       |

select * FROM MART.WORK_ORDER_BATCH_FACT WHERE WORK_ORDER_BATCH_OID = '55510'

--WORK_ORDER_BATCH_OID|MARKETING_ID|ACCOUNT_ID|ITEM_ID|APO_ID  |EVENT_ID|JOB_TICKET_ORG_ID|WORK_ORDER_BATCH_JUNK_ID|SHIPMENT_OID|PARENT_ORDER_HEADER_OID|BATCH_ID         |BATCH_CREATE_DATE_KEY|READY_FULLFILLMENT_DATE_KEY|PRINT_DATE_KEY|COMPLETE_DATE_KEY|BINNED_DATE_KEY|PACKED_DATE_KEY|SHIPPED_DATE_KEY|AVAILABLE_DATE_KEY |STATUS_DESC     |TOTAL_TASKS|TOTAL_COMPLTD_TASKS|TOTAL_PAGES|TOTAL_WORK_ORDERS|DEVICE_GROUP   |FULFILLMENT_TYPE|START_PAGE|END_PAGE|MAKEOVER_REASON|REASON_DESC|CANCEL_COMMENT|BIN_LOCATION|ORDER_NO|MART_CREATE_DATE   |MART_MODIFY_DATE   |CALC_READY_FULLFILL_DATE_KEY|CALC_COMPLETE_DATE_KEY|READY_FULLFILL_COMP_DAYS|MANUFACTURER_ITEM|BOC_BATCH_ID  |TOTAL_ORDERS|BUYER_COUNT|MAGNET|BUTTONS|PLAQUES|TRADER_CARDS|STANDARD_PRINTS|TP16X20|TP11X14|
----------------------+------------+----------+-------+--------+--------+-----------------+------------------------+------------+-----------------------+-----------------+---------------------+---------------------------+--------------+-----------------+---------------+---------------+----------------+-------------------+----------------+-----------+-------------------+-----------+-----------------+---------------+----------------+----------+--------+---------------+-----------+--------------+------------+--------+-------------------+-------------------+----------------------------+----------------------+------------------------+-----------------+--------------+------------+-----------+------+-------+-------+------------+---------------+-------+-------+
--               55510|         275|     97466|6048484|10135530|11046121|              120|                       3|            |                       |Consumer_Test1_CD|                     |                           |              |                 |               |               |                |2024-09-26 02:18:33|Partially Binned|          3|                  0|          0|               16|Indigo Printing|                |0         |0       |               |           |              |FOWRCP7     |        |2019-06-07 16:05:37|2024-09-26 02:00:25|                            |                      |                        |69969            |Consumer_Test1|            |           |      |       |       |            |               |       |       |


DELETE  FROM MART.WORK_ORDER_BATCH_FACT WHERE WORK_ORDER_BATCH_OID = '55510'

UPDATE ODS.DW_CDC_LOAD_STATUS
SET last_cdc_completion_date = TO_DATE(SUBSTR('2024-09-26 00:00:00', 1, 19), 'YYYY-MM-DD HH24:MI:SS')
WHERE dw_table_name= 'WORK_ORDER_BATCH_FACT'


-- run the dag


select * FROM MART.WORK_ORDER_BATCH_FACT WHERE WORK_ORDER_BATCH_OID = '55510'
--WORK_ORDER_BATCH_OID|MARKETING_ID|ACCOUNT_ID|ITEM_ID|APO_ID  |EVENT_ID|JOB_TICKET_ORG_ID|WORK_ORDER_BATCH_JUNK_ID|SHIPMENT_OID|PARENT_ORDER_HEADER_OID|BATCH_ID         |BATCH_CREATE_DATE_KEY|READY_FULLFILLMENT_DATE_KEY|PRINT_DATE_KEY|COMPLETE_DATE_KEY|BINNED_DATE_KEY|PACKED_DATE_KEY|SHIPPED_DATE_KEY|AVAILABLE_DATE_KEY |STATUS_DESC     |TOTAL_TASKS|TOTAL_COMPLTD_TASKS|TOTAL_PAGES|TOTAL_WORK_ORDERS|DEVICE_GROUP   |FULFILLMENT_TYPE|START_PAGE|END_PAGE|MAKEOVER_REASON|REASON_DESC|CANCEL_COMMENT|BIN_LOCATION|ORDER_NO|MART_CREATE_DATE   |MART_MODIFY_DATE   |CALC_READY_FULLFILL_DATE_KEY|CALC_COMPLETE_DATE_KEY|READY_FULLFILL_COMP_DAYS|MANUFACTURER_ITEM|BOC_BATCH_ID  |TOTAL_ORDERS|BUYER_COUNT|MAGNET|BUTTONS|PLAQUES|TRADER_CARDS|STANDARD_PRINTS|TP16X20|TP11X14|
----------------------+------------+----------+-------+--------+--------+-----------------+------------------------+------------+-----------------------+-----------------+---------------------+---------------------------+--------------+-----------------+---------------+---------------+----------------+-------------------+----------------+-----------+-------------------+-----------+-----------------+---------------+----------------+----------+--------+---------------+-----------+--------------+------------+--------+-------------------+-------------------+----------------------------+----------------------+------------------------+-----------------+--------------+------------+-----------+------+-------+-------+------------+---------------+-------+-------+
--               55510|         275|     97466|6048484|10135530|11046121|              120|                       3|            |                       |Consumer_Test1_CD|                     |                           |              |                 |               |               |                |2024-09-26 05:18:33|Partially Binned|          3|                  0|          0|               16|Indigo Printing|                |0         |0       |               |           |              |FOWRCP7     |        |2024-09-26 05:09:33|2024-09-26 05:09:33|                            |                      |                        |69969            |Consumer_Test1|            |           |      |       |       |            |               |       |       |