SELECT * FROM ODS_STAGE.X1_WO_SHIPPED_HIST

SELECT SHIPMENT_PROPOSAL_ID FROM ODS_STAGE.WOMS_WORK_ORDER_STG WHERE APO_ID = '1599978'


DELETE FROM ODS_STAGE.WOMS_WORK_ORDER_STG WHERE WORK_ORDER_ID = 0


INSERT INTO ODS_STAGE.WOMS_WORK_ORDER_STG (WORK_ORDER_ID,ODS_MODIFY_DATE,ODS_create_DATE,WOMS_NODE,APO_ID,SHIPMENT_PROPOSAL_ID,STATUS) VALUES (0, sysdate,sysdate,'Winnipeg',1599978,'32b45ceb-853b-4241-a0d2-14f438896a7f','Shipped Acknowledged')


--DELETE FROM ODS_STAGE.X1_WO_SHIPPED_HIST WHERE WORK_ORDER_ID = 0

INSERT INTO ODS_STAGE.X1_WO_SHIPPED_HIST (WORK_ORDER_ID,WORK_ORDER_STATUS,ODS_MODIFY_DATE,ODS_create_DATE,status,WOMS_NODE) VALUES (0,'new', sysdate,sysdate,Null,'Winnipeg')


SELECT STATUS,STATUS_DATE FROM  ODS_STAGE.X1_WO_SHIPPED_HIST WHERE WORK_ORDER_ID = 0
--STATUS|STATUS_DATE|
--------+-----------+
--      |           |

-- run the MANUAL_DEACTIVATED_FLAG
SELECT STATUS,STATUS_DATE FROM  ODS_STAGE.X1_WO_SHIPPED_HIST WHERE WORK_ORDER_ID = 0

--STATUS              |STATUS_DATE        |
----------------------+-------------------+
--Shipped Acknowledged|2024-09-02 07:53:27|

------------------------
SELECT
    SHPD.WORK_ORDER_ID,
    SHPD.WOMS_NODE,
    WO.STATUS,
    MAX(WO.AUDIT_MODIFY_DATE) STATUS_CHANGE_TS
    FROM
    ODS_STAGE.X1_WO_SHIPPED_HIST SHPD,
    ODS_STAGE.WOMS_WORK_ORDER_STG WO
    WHERE 1 = 1
    AND SHPD.WORK_ORDER_ID = WO.WORK_ORDER_ID
    AND SHPD.WOMS_NODE = WO.WOMS_NODE
    AND SHPD.WORK_ORDER_STATUS NOT IN ('Error')
    AND WO.STATUS IN ('Shipped Acknowledged')
    AND SHPD.STATUS IS NULL
--    AND SHPD.ODS_MODIFY_DATE >=  TO_DATE(SUBSTR('2000-08-03 00:00:00', 1, 19), 'YYYY-MM-DD HH24:MI:SS')
    GROUP BY
    SHPD.WORK_ORDER_ID,
    SHPD.WOMS_NODE,
    WO.STATUS


SELECT * FROM RAX_APP_USER.X1_WO_UNSHIPPED_TEMP2

SELECT
     WORK_ORDER_ID,
     LID,
     UNDERCLASS_PRODUCT_CODE,
     PRODUCE_PRODUCED_DT,
     WOMS_NODE
           FROM
      X1_WO_PRODUCE_DT_TEMP
      WHERE UNDERCLASS_PRODUCT_CODE IN ('PKG','SBP')
      AND STATUS_ID = 2

SELECT
     WORK_ORDER_ID,
     LID,
     UNDERCLASS_PRODUCT_CODE,
     PRODUCE_PRODUCED_DT,
     WOMS_NODE
           FROM
        X1_WO_PRODUCE_DT_TEMP
    WHERE UNDERCLASS_PRODUCT_CODE = 'RET'
    AND STATUS_ID = 2

SELECT
TEMP.WOMS_NODE,
TEMP.WORK_ORDER_ID,
TEMP.LID AS LID,
X.UNDERCLASS_PRODUCT_CODE AS UNDERCLASS_PRODUCT_CODE,
MAX(SH.STATUS_CHANGE_TS) AS PRODUCE_PRODUCED_DT,
MAX(sh.STATUS_CHANGE_TS) AS  PRODUCT_SHIPPED_DT,
SH.STATUS_ID
FROM
RAX_APP_USER.X1_WO_UNSHIPPED_TEMP1 TEMP,
ODS_STAGE.WOMS_STATUS_HISTORY_STG SH,
ODS_STAGE.WOMS_WORK_ORDER_DETAIL_STG WOD,
ODS_STAGE.WOMS_ITEM_ID_REFERENCE_STG I,
ODS_STAGE.WOMS_XREF_OMS_PROD_STG X
WHERE
    1 = 1
AND TEMP.WORK_ORDER_ID = WOD.WORK_ORDER_ID
AND SH.WORK_ORDER_DETAIL_ID = WOD.WORK_ORDER_DETAIL_ID
AND I.ITEM_ID_REFERENCE_ID = WOD.ITEM_ID_REFERENCE_ID
AND X.XREF_OMS_PROD_ID = I.XREF_OMS_PROD_ID
AND SH.WOMS_NODE = WOD.WOMS_NODE
AND WOD.WOMS_NODE = TEMP.WOMS_NODE
AND SH.WORK_ORDER_ID IS NULL
AND I.PRODUCIBLE_FLAG = 1
AND SH.STATUS_ID IN (2)
AND WOD.DEACTIVATED_DATE IS NULL
AND WOD.ODS_CREATE_DATE >= (SELECT MIN(DATE_KEY) FROM MART.TIME
                                           WHERE FISCAL_YEAR = (SELECT FISCAL_YEAR FROM MART.TIME
                                                               WHERE DATE_KEY = TRUNC(SYSDATE))-1)
AND SH.ODS_CREATE_DATE >= (SELECT MIN(DATE_KEY) FROM MART.TIME
                                           WHERE FISCAL_YEAR = (SELECT FISCAL_YEAR FROM MART.TIME
                                                               WHERE DATE_KEY = TRUNC(SYSDATE))-1)
GROUP BY
         TEMP.WOMS_NODE,
         TEMP.WORK_ORDER_ID,
         TEMP.LID,
         X.UNDERCLASS_PRODUCT_CODE,
         SH.STATUS_ID


SELECT * FROM RAX_APP_USER.TEMP_POS

SELECT
    VW.PLATFORM_DETAIL AS PLATFORM_DETAIL,
    WO.WORK_ORDER_ID,
    EVENT.EVENT_REF_ID AS EVENT_REF_ID,
    EVENT.SELLING_METHOD AS JOB_TYPE,
    APO.LIFETOUCH_ID AS LID,
    ACCOUNT.ACCOUNT_NAME AS ACCT_NAME,
    WO.RECEIVED_DATE AS SHIP_PROPSL_RECEIVED,
    NULL AS MAIL_RECEIVED,
    BATCH.SHIP_PROPSL_BATCH_ID AS SHIP_PROPSL_BATCH_ID,
    WO.WORK_ORDER_ALIAS_ID AS WORK_ORDER_ALIAS_ID,
    NULL AS SUBJECT_COUNT,
    NULL AS WORK_ORDER_FORM_PRT,
    NULL AS SESSION_ID,
    WO.DEACTIVATED_DATE,
    NULL AS RET,
    NULL AS RET_QTY,
    NULL AS RET_PRT,
    NULL AS PKG,
    NULL AS PKG_QTY,
    NULL AS PKG_PRT,
    'POS' AS POS,
    NULL AS POS_QTY,
    NULL AS POS_PRT,
    NULL AS DIGITAL_MEDIA1,
    NULL AS DIGITAL_MEDIA1_QTY,
    NULL AS DIGITAL_MEDIA1_PRT,
    NULL AS DIGITAL_MEDIA2,
    NULL AS DIGITAL_MEDIA2_QTY,
    NULL AS DIGITAL_MEDIA2_PRT,
    NULL AS LAMINATE,
    NULL AS LAMINATE_QTY,
    NULL AS LAMINATE_PRT,
    NULL AS MAGNET,
    NULL AS MAGNET_QTY,
    NULL AS MAGNET_PRT,
    NULL AS METALLIC,
    NULL AS METALLIC_QTY,
    NULL AS METALLIC_PRT,
    NULL AS SPECIALITY,
    NULL AS SPECIALITY_QTY,
    NULL AS SPECIALITY_PRODUCED,
    NULL AS  INDIGO_PRODUCT1               ,
    NULL AS  INDIGO_PRODUCT1_QTY           ,
    NULL AS  INDIGO_PRODUCT1_PRODUCED      ,
    NULL AS  INDIGO_PRODUCT2               ,
    NULL AS  INDIGO_PRODUCT2_QTY           ,
    NULL AS  INDIGO_PRODUCT2_PRODUCED      ,
    NULL AS PROOF,
    NULL AS PROOF_QTY,
    NULL AS PROOF_PRODUCED,
    NULL AS CLASS_DELIVER_TYPE,
    NULL AS CLASS,
    NULL AS CLASS_QTY,
    NULL AS CLASS_PRT,
    NULL AS DID,
    NULL AS DID_QTY,
    NULL AS DID_PRT,
    NULL AS DSSK,
    NULL AS DSSK_QTY,
    NULL AS DSSK_PRT,
    NULL AS EZP,
    NULL AS EZP_QTY,
    NULL AS EZP_PRT,
    NULL AS POS618,
    NULL AS POS618_QTY,
    NULL AS POS618_PRT,
    WO.STATUS,
    WO.PROCESSING_COMMENT,
    WO.SHIP_GOAL_DATE,
    WO.WOMS_NODE,
    NULL AS DEACTIVATED_FLAG
    FROM

                  ODS_STAGE.WOMS_WORK_ORDER_STG WO,
                  ODS_STAGE.WOMS_ORDER_BATCH_STG BATCH,
                  ODS_STAGE.WOMS_WORK_ORDER_DETAIL_STG WOD,
                  ODS_OWN.APO,
                  ODS_OWN.APO_TAG_VW VW ,
                  ODS_OWN.ACCOUNT,
                  ODS_OWN.EVENT

    WHERE
                1 = 1
                AND WO.WORK_ORDER_ID = BATCH.WORK_ORDER_ID(+)
                AND WO.WOMS_NODE = BATCH.WOMS_NODE(+)
                AND WO.WOMS_NODE = WOD.WOMS_NODE
                AND WO.WORK_ORDER_ID = WOD.WORK_ORDER_ID
                AND WOD.APO_ID = APO.APO_ID
                AND APO.APO_ID = VW.APO_ID
                AND APO.ACCOUNT_OID = ACCOUNT.ACCOUNT_OID
                AND APO.VISION_JOB_NO = EVENT.EVENT_REF_ID(+)
                AND WO.ODS_MODIFY_DATE >  ( SELECT LAST_CDC_COMPLETION_DATE - .010
			        FROM ODS.DW_CDC_LOAD_STATUS
                                                                        WHERE DW_TABLE_NAME = 'X1_WO_UNSHIPPED')
                AND WOD.ODS_CREATE_DATE >= (SELECT MIN(DATE_KEY) FROM MART.TIME
                			WHERE FISCAL_YEAR = (SELECT FISCAL_YEAR FROM MART.TIME
                                                                WHERE DATE_KEY = TRUNC(SYSDATE))-1)
-- AND WO.STATUS NOT IN ('Canceled Acknowledged','Lab Canceled')
    AND WO.WOMS_NODE IN (
                                                select distinct plant_group from MART.PLANT_NAME_XREF
		     where plant_group in (select  case when 'United States' <> :v_data_center
                                                                                then 'Winnipeg'
                                                                                else plant_group
                                                                                end from MART.PLANT_NAME_XREF)
                                               )
	AND WO.WORK_ORDER_ID not in (6691166)
)
 GROUP BY
    PLATFORM_DETAIL,
    WORK_ORDER_ID,
    EVENT_REF_ID,
    JOB_TYPE,
    LID,
    ACCT_NAME,
    SHIP_PROPSL_RECEIVED,
    SHIP_PROPSL_BATCH_ID,
    WORK_ORDER_ALIAS_ID,
    NULL,
    WORK_ORDER_FORM_PRT,
    RET,
    RET_PRT,
    PKG,
    PKG_PRT,
    POS,
    POS_PRT,
    DIGITAL_MEDIA1,
    DIGITAL_MEDIA1_PRT,
    DIGITAL_MEDIA2,
    DIGITAL_MEDIA2_PRT,
    LAMINATE,
    LAMINATE_PRT,
    MAGNET,
    MAGNET_PRT,
    METALLIC,
    METALLIC_PRT,
    SPECIALITY,
    SPECIALITY_PRODUCED,
    INDIGO_PRODUCT1  ,
    INDIGO_PRODUCT1_PRODUCED      ,
    INDIGO_PRODUCT2  ,
    INDIGO_PRODUCT2_PRODUCED      ,
    PROOF,
    PROOF_PRODUCED,
    CLASS_DELIVER_TYPE,
    CLASS,
    CLASS_PRT,
    DID,
    DSSK,
    EZP,
    STATUS,
    PROCESSING_COMMENT,
    SHIP_GOAL_DATE,
    WOMS_NODE,
    DEACTIVATED_FLAG

SELECT
    J.JOB_NUMBER,J.SORT_ORDER,J.WORK_ORDER_ID,
    J.WOMS_NODE,X1.EVENT_REF_ID
    FROM ODS_STAGE.X1_WO_UNSHIPPED_HIST  X1,
               ODS_STAGE.WOMS_JOB_NUMBER_STG J
    WHERE 1 = 1
    AND X1.WORK_ORDER_ID = J.WORK_ORDER_ID
    AND X1.WOMS_NODE = J.WOMS_NODE
--    AND J.SORT_ORDER = 1
--    AND X1.WORK_ORDER_STATUS NOT IN ('Error')
--    AND X1.WORK_ORDER_ID not in (8910237,
--6691164,
--6691168,
--6691169,
--6691170,
--6691165,
--8910341,
--6691167)

SELECT
    X1.WORK_ORDER_ID,X1.EVENT_REF_ID,X1.WOMS_NODE
    FROM
    ODS_STAGE.X1_WO_UNSHIPPED_HIST  X1
    WHERE X1.WORK_ORDER_STATUS NOT IN ('Error')
    AND X1.WORK_ORDER_ID NOT IN (8910237,
6691164,
6691168,
6691169,
6691170,
6691165,
8910341,
6691167)

SELECT
    VW.PLATFORM_DETAIL AS PLATFORM_DETAIL,
    WO.WORK_ORDER_ID,
    EVENT.EVENT_REF_ID AS EVENT_REF_ID,
    EVENT.SELLING_METHOD AS JOB_TYPE,
    APO.LIFETOUCH_ID AS LID,
    ACCOUNT.ACCOUNT_NAME AS ACCT_NAME,
    WO.RECEIVED_DATE AS SHIP_PROPSL_RECEIVED,
    NULL AS MAIL_RECEIVED,
    BATCH.SHIP_PROPSL_BATCH_ID AS SHIP_PROPSL_BATCH_ID,
    WO.WORK_ORDER_ALIAS_ID AS WORK_ORDER_ALIAS_ID,
    NULL AS SUBJECT_COUNT,
    NULL AS WORK_ORDER_FORM_PRT,
    NULL AS SESSION_ID,
    WO.DEACTIVATED_DATE,
    NULL AS RET,
    NULL AS RET_QTY,
    NULL AS RET_PRT,
    NULL AS PKG,
    NULL AS PKG_QTY,
    NULL AS PKG_PRT,
    'POS' AS POS,
    NULL AS POS_QTY,
    NULL AS POS_PRT,
    NULL AS DIGITAL_MEDIA1,
    NULL AS DIGITAL_MEDIA1_QTY,
    NULL AS DIGITAL_MEDIA1_PRT,
    NULL AS DIGITAL_MEDIA2,
    NULL AS DIGITAL_MEDIA2_QTY,
    NULL AS DIGITAL_MEDIA2_PRT,
    NULL AS LAMINATE,
    NULL AS LAMINATE_QTY,
    NULL AS LAMINATE_PRT,
    NULL AS MAGNET,
    NULL AS MAGNET_QTY,
    NULL AS MAGNET_PRT,
    NULL AS METALLIC,
    NULL AS METALLIC_QTY,
    NULL AS METALLIC_PRT,
    NULL AS SPECIALITY,
    NULL AS SPECIALITY_QTY,
    NULL AS SPECIALITY_PRODUCED,
    NULL AS  INDIGO_PRODUCT1               ,
    NULL AS  INDIGO_PRODUCT1_QTY           ,
    NULL AS  INDIGO_PRODUCT1_PRODUCED      ,
    NULL AS  INDIGO_PRODUCT2               ,
    NULL AS  INDIGO_PRODUCT2_QTY           ,
    NULL AS  INDIGO_PRODUCT2_PRODUCED      ,
    NULL AS PROOF,
    NULL AS PROOF_QTY,
    NULL AS PROOF_PRODUCED,
    NULL AS CLASS_DELIVER_TYPE,
    NULL AS CLASS,
    NULL AS CLASS_QTY,
    NULL AS CLASS_PRT,
    NULL AS DID,
    NULL AS DID_QTY,
    NULL AS DID_PRT,
    NULL AS DSSK,
    NULL AS DSSK_QTY,
    NULL AS DSSK_PRT,
    NULL AS EZP,
    NULL AS EZP_QTY,
    NULL AS EZP_PRT,
    NULL AS POS618,
    NULL AS POS618_QTY,
    NULL AS POS618_PRT,
    WO.STATUS,
    WO.PROCESSING_COMMENT,
    WO.SHIP_GOAL_DATE,
    WO.WOMS_NODE,
    NULL AS DEACTIVATED_FLAG
    FROM

                  ODS_STAGE.WOMS_WORK_ORDER_STG WO,
                  ODS_STAGE.WOMS_ORDER_BATCH_STG BATCH,
                  ODS_STAGE.WOMS_WORK_ORDER_DETAIL_STG WOD,
                  ODS_OWN.APO,
                  ODS_OWN.APO_TAG_VW VW ,
                  ODS_OWN.ACCOUNT,
                  ODS_OWN.EVENT

    WHERE
                1 = 1
                AND WO.WORK_ORDER_ID = BATCH.WORK_ORDER_ID(+)
                AND WO.WOMS_NODE = BATCH.WOMS_NODE(+)
                AND WO.WOMS_NODE = WOD.WOMS_NODE
                AND WO.WORK_ORDER_ID = WOD.WORK_ORDER_ID
                AND WOD.APO_ID = APO.APO_ID
                AND APO.APO_ID = VW.APO_ID
                AND APO.ACCOUNT_OID = ACCOUNT.ACCOUNT_OID
                AND APO.VISION_JOB_NO = EVENT.EVENT_REF_ID(+)
--                AND WO.ODS_MODIFY_DATE >  ( SELECT LAST_CDC_COMPLETION_DATE - .010
--			        FROM ODS.DW_CDC_LOAD_STATUS
--                                                                        WHERE DW_TABLE_NAME = 'X1_WO_UNSHIPPED')
                AND WOD.ODS_CREATE_DATE >= (SELECT MIN(DATE_KEY) FROM MART.TIME
                			WHERE FISCAL_YEAR = (SELECT FISCAL_YEAR FROM MART.TIME
                                                                WHERE DATE_KEY = TRUNC(SYSDATE))-1)
-- AND WO.STATUS NOT IN ('Canceled Acknowledged','Lab Canceled')
--    AND WO.WOMS_NODE IN (
--                                                select distinct plant_group from MART.PLANT_NAME_XREF
--		     where plant_group in (select  case when 'United States' <> 'United States'
--                                                                                then 'Winnipeg'
--                                                                                else plant_group
--                                                                                end from MART.PLANT_NAME_XREF)
--                                               )
--	AND WO.WORK_ORDER_ID not in (6691166)


	select trim(dc.data_center_name) from ODS_OWN.DATA_CENTER dc


SELECT * FROM ODS_STAGE.X1_WO_UNSHIPPED_HIST


	SELECT
	PLATFORM_DETAIL	,
	WORK_ORDER_ID	,
	EVENT_REF_ID	,
	JOB_TYPE		,
	LID		,
	ACCT_NAME		,
	SHIP_PROPSL_RECEIVED	,
	MAIL_RECEIVED                ,
	BATCH_ID		,
	WORK_ORDER_ALIAS_ID	,
	SUBJECT_COUNT	,
	WORK_ORDER_FORM_PRT,
	RET		,
	RET_QTY		,
	RET_PRT		,
	PKG		,
	PKG_QTY		,
	PKG_PRT		,
	POS		,
	POS_QTY		,
	POS_PRT		,
	DIGITAL_MEDIA1                  ,
	DIGITAL_MEDIA1_QTY          ,
	DIGITAL_MEDIA1_PRT          ,
	DIGITAL_MEDIA2                  ,
	DIGITAL_MEDIA2_QTY          ,
	DIGITAL_MEDIA2_PRT          ,
	LAMINATE		,
	LAMINATE_QTY	,
	LAMINATE_PRT	,
	MAGNET		,
	MAGNET_QTY	,
	MAGNET_PRT	,
	METALLIC		,
	METALLIC_QTY	,
	METALLIC_PRT	,
	SPECIALITY		,
	SPECIALITY_QTY	,
	SPECIALITY_PRODUCED	,
	INDIGO_PRODUCT1                          ,
	INDIGO_PRODUCT1_QTY                 ,
	INDIGO_PRODUCT1_PRODUCED      ,
	INDIGO_PRODUCT2                          ,
	INDIGO_PRODUCT2_QTY                 ,
	INDIGO_PRODUCT2_PRODUCED      ,
	PROOF_PRODUCT	,
	PROOF_QTY		,
	PROOF_PRODUCED	,
	CLASS_DELIVERY	,
	CLASS		,
	CLASS_QTY	,
	CLASS_PRT	,
	DID	,
	DID_QTY	,
	DID_PRT	,
	DSSK	,
	DSSK_QTY	,
	DSSK_PRT	,
	EZP	,
	EZP_QTY	,
	EZP_PRT	,
	SPECIAL_REQUEST	,
	WORK_ORDER_STATUS	,
	PROCESSING_COMMENT	,
	SHIP_GOAL_DATE	,
	WOMS_NODE                    ,
	MANUAL_DEACTIVATED_FLAG    ,
	PENDING_CLASS_PRODUCT        ,
	MANUALLY_SHIPPED
                     FROM ODS_STAGE.X1_WO_UNSHIPPED_HIST
--                     WHERE MANUALLY_SHIPPED = 'Y'

SELECT
    SHPD.WORK_ORDER_ID,
    SHPD.WOMS_NODE,
    ST.DESCRIPTION,
    ST.CODE,
    MAX(SH.STATUS_CHANGE_TS) STATUS_CHANGE_TS
    FROM
    ODS_STAGE.X1_WO_SHIPPED_HIST SHPD,
    ODS_STAGE.WOMS_WORK_ORDER_DETAIL_STG WOD,
    ODS_STAGE.WOMS_STATUS_HISTORY_STG SH,
    ODS_STAGE.WOMS_STATUS_STAGE ST
    WHERE 1 = 1
    AND SHPD.WORK_ORDER_ID = WOD.WORK_ORDER_ID
    AND SHPD.WOMS_NODE = WOD.WOMS_NODE
    AND WOD.WORK_ORDER_DETAIL_ID = SH.WORK_ORDER_DETAIL_ID
    AND WOD.WOMS_NODE = SH.WOMS_NODE
    AND SH.STATUS_ID = ST.STATUS_ID
    AND SH.WOMS_NODE = ST.SOURCE_NODE
    AND ST.CODE = 'SA'
    AND SHPD.CHANGE_FLAG NOT IN ('C')
    AND SHPD.WORK_ORDER_STATUS NOT IN ('Error')
    AND SHPD.ODS_MODIFY_DATE >=  ( SELECT LAST_CDC_COMPLETION_DATE
                                   FROM ODS.DW_CDC_LOAD_STATUS
                                   WHERE DW_TABLE_NAME = 'UPDATE_X1_WO_SHIPPED_HIST') - .010
    AND SH.ODS_MODIFY_DATE >= (SELECT MIN(DATE_KEY) FROM MART.TIME
                               WHERE FISCAL_YEAR = (SELECT FISCAL_YEAR FROM MART.TIME
                                                    WHERE DATE_KEY = TRUNC(SYSDATE))-1)
    AND WOD.ODS_MODIFY_DATE >= (SELECT MIN(DATE_KEY) FROM MART.TIME
                               WHERE FISCAL_YEAR = (SELECT FISCAL_YEAR FROM MART.TIME
                                                    WHERE DATE_KEY = TRUNC(SYSDATE))-1)
    GROUP BY
    SHPD.WORK_ORDER_ID,
    SHPD.WOMS_NODE,
    ST.DESCRIPTION,
    ST.CODE


SELECT
    SHPD.WORK_ORDER_ID,
    SHPD.WOMS_NODE,
    MAX(SH.STATUS_CHANGE_TS) STATUS_CHANGE_TS
    FROM
    ODS_STAGE.X1_WO_SHIPPED_HIST SHPD,
    ODS_STAGE.WOMS_WORK_ORDER_DETAIL_STG WOD,
    ODS_STAGE.WOMS_STATUS_HISTORY_STG SH,
    ODS_STAGE.WOMS_STATUS_STAGE ST
    WHERE 1 = 1
    AND SHPD.WORK_ORDER_ID = WOD.WORK_ORDER_ID
    AND SHPD.WOMS_NODE = WOD.WOMS_NODE
    AND WOD.WORK_ORDER_DETAIL_ID = SH.WORK_ORDER_DETAIL_ID
    AND WOD.WOMS_NODE = SH.WOMS_NODE
    AND SH.STATUS_ID = ST.STATUS_ID
    AND SH.WOMS_NODE = ST.SOURCE_NODE
    AND SHPD.CHANGE_FLAG = 'C'
    AND SHPD.STATUS IS NULL
    AND SHPD.ODS_MODIFY_DATE >=  ( SELECT LAST_CDC_COMPLETION_DATE
                                    FROM ODS.DW_CDC_LOAD_STATUS
                                    WHERE DW_TABLE_NAME = 'UPDATE_X1_WO_SHIPPED_HIST') - .010
    AND SH.ODS_MODIFY_DATE >= (SELECT MIN(DATE_KEY) FROM MART.TIME
                               WHERE FISCAL_YEAR = (SELECT FISCAL_YEAR FROM MART.TIME
                                                    WHERE DATE_KEY = TRUNC(SYSDATE))-1)
    AND WOD.ODS_MODIFY_DATE >= (SELECT MIN(DATE_KEY) FROM MART.TIME
                               WHERE FISCAL_YEAR = (SELECT FISCAL_YEAR FROM MART.TIME
                                                    WHERE DATE_KEY = TRUNC(SYSDATE))-1)
    GROUP BY
    SHPD.WORK_ORDER_ID,
    SHPD.WOMS_NODE


SELECT
    SHPD.WORK_ORDER_ID,
    SHPD.WOMS_NODE,
    WO.STATUS,
    MAX(WO.AUDIT_MODIFY_DATE) STATUS_CHANGE_TS
    FROM
    ODS_STAGE.X1_WO_SHIPPED_HIST SHPD,
    ODS_STAGE.WOMS_WORK_ORDER_STG WO
    WHERE 1 = 1
    AND SHPD.WORK_ORDER_ID = WO.WORK_ORDER_ID
    AND SHPD.WOMS_NODE = WO.WOMS_NODE
    AND SHPD.WORK_ORDER_STATUS NOT IN ('Error')
    AND WO.STATUS IN ('Shipped Acknowledged')
    AND SHPD.STATUS IS NULL
    AND SHPD.ODS_MODIFY_DATE >=  (SELECT LAST_CDC_COMPLETION_DATE
                                   FROM ODS.DW_CDC_LOAD_STATUS
                                   WHERE DW_TABLE_NAME = 'UPDATE_X1_WO_SHIPPED_HIST') - 15
    GROUP BY
    SHPD.WORK_ORDER_ID,
    SHPD.WOMS_NODE,
    WO.STATUS


SELECT
    WORK_ORDER_ID,
    WOMS_NODE,
    LID,
    MANUALLY_SHIPPED
    FROM
    ODS_STAGE.X1_WO_UNSHIPPED_HIST
--    WHERE MANUALLY_SHIPPED IS NOT NULL