select	
	OFFERING_MODEL_SUM_COMM.ID	   C1_ID,
	OFFERING_MODEL_SUM_COMM.BASIS	   C2_BASIS,
	OFFERING_MODEL_SUM_COMM.VALUATION_TYPE	   C3_VALUATION_TYPE,
	OFFERING_MODEL_SUM_COMM.VALUE	   C4_VALUE
from	<schema_name>.OFFERING_MODEL_SUM_COMM   OFFERING_MODEL_SUM_COMM, <schema_name>.OFFERING_MODEL_COMMISSION   OFFERING_MODEL_COMMISSION, <schema_name>.OFFERING_MODEL   OFFERING_MODEL
where	(1=1)
And (OFFERING_MODEL.LAST_UPDATED >=   ( TO_DATE(SUBSTR(:v_cdc_load_date, 1, 19), 'YYYY-MM-DD HH24:MI:SS')  - :v_cdc_oms_overlap))
 And (OFFERING_MODEL_SUM_COMM.ID=OFFERING_MODEL_COMMISSION.ID)
AND (OFFERING_MODEL.COMMISSION_MODEL_ID=OFFERING_MODEL_COMMISSION.ID)