select	
	OFFERING_MODEL.ID	   C1_ID,
	OFFERING_MODEL.VERSION	   C2_VERSION,
	OFFERING_MODEL_COMMISSION.BAD_CHECK_ALLOWANCE	   C3_BAD_CHECK_ALLOWANCE,
	OFFERING_MODEL_COMMISSION.GUARANTEED_MINIMUM	   C4_GUARANTEED_MINIMUM,
	OFFERING_MODEL_COMMISSION.PAY_ON_SHIP_TO_HOME	   C5_PAY_ON_SHIP_TO_HOME
from	<schema_name>.OFFERING_MODEL   OFFERING_MODEL, <schema_name>.OFFERING_MODEL_COMMISSION   OFFERING_MODEL_COMMISSION
where	(1=1)
And (OFFERING_MODEL.LAST_UPDATED >=   ( TO_DATE(SUBSTR(:v_cdc_load_date, 1, 19), 'YYYY-MM-DD HH24:MI:SS')  - :v_cdc_oms_overlap))
 And (OFFERING_MODEL.COMMISSION_MODEL_ID=OFFERING_MODEL_COMMISSION.ID)