select	
	OFFERING_MODEL_TAGS.OFFERING_MODEL_ID	   C1_OFFERING_MODEL_ID,
	OFFERING_MODEL_TAGS.TAGS_INTEGER	   C2_TAGS_INTEGER
from	<schema_name>.OFFERING_MODEL_TAGS   OFFERING_MODEL_TAGS, <schema_name>.OFFERING_MODEL   OFFERING_MODEL
where	(1=1)
And (OFFERING_MODEL.LAST_UPDATED >=   ( TO_DATE(SUBSTR(:v_cdc_load_date, 1, 19), 'YYYY-MM-DD HH24:MI:SS')  - :v_cdc_oms_overlap))
 And (OFFERING_MODEL.ID=OFFERING_MODEL_TAGS.OFFERING_MODEL_ID)