select	DISTINCT
	OFFERING_MODEL_PACKAGE_COMM.ID	   C1_ID
from	<schema_name>.OFFERING_MODEL_PACKAGE_COMM   OFFERING_MODEL_PACKAGE_COMM, <schema_name>.OFFERING_MODEL_COMMISSION   OFFERING_MODEL_COMMISSION, <schema_name>.OFFERING_MODEL   OFFERING_MODEL
where	(1=1)
And (OFFERING_MODEL.LAST_UPDATED >=  ( TO_DATE(SUBSTR(:v_cdc_load_date, 1, 19), 'YYYY-MM-DD HH24:MI:SS')  - :v_cdc_oms_overlap))
 And (OFFERING_MODEL_COMMISSION.ID=OFFERING_MODEL_PACKAGE_COMM.ID)
AND (OFFERING_MODEL.COMMISSION_MODEL_ID=OFFERING_MODEL_COMMISSION.ID)