select	
	ITEM_COMMISSION_VALUE.ID	   C1_ID,
	ITEM_COMMISSION_VALUE.VERSION	   C2_VERSION,
	ITEM_COMMISSION_VALUE.PACKAGE_COMMISSION_MODEL_ID	   C3_PACKAGE_COMMISSION_MODEL_ID,
	ITEM_COMMISSION_VALUE.SKU_CODE	   C4_SKU_CODE,
	ITEM_COMMISSION_VALUE.VALUATION_TYPE	   C5_VALUATION_TYPE,
	ITEM_COMMISSION_VALUE.VALUE	   C6_VALUE
from	<schema_name>.ITEM_COMMISSION_VALUE   ITEM_COMMISSION_VALUE, <schema_name>.OFFERING_MODEL_PACKAGE_COMM   OFFERING_MODEL_PACKAGE_COMM, <schema_name>.OFFERING_MODEL_COMMISSION   OFFERING_MODEL_COMMISSION, <schema_name>.OFFERING_MODEL   OFFERING_MODEL
where	(1=1)
And (OFFERING_MODEL.LAST_UPDATED >=   ( TO_DATE(SUBSTR(:v_cdc_load_date, 1, 19), 'YYYY-MM-DD HH24:MI:SS')  - :v_cdc_oms_overlap))
 And (OFFERING_MODEL_PACKAGE_COMM.ID=OFFERING_MODEL_COMMISSION.ID)
AND (OFFERING_MODEL_COMMISSION.ID=OFFERING_MODEL.COMMISSION_MODEL_ID)
AND (ITEM_COMMISSION_VALUE.PACKAGE_COMMISSION_MODEL_ID=OFFERING_MODEL_PACKAGE_COMM.ID)