/* TASK No. 1 */

/* NONE or SET VARIABLE STATEMENT FOUND, CHECK ODI TASK NO. 1 */




/*-----------------------------------------------*/
/* TASK No. 2 */

/* SELECT STATEMENT FOUND, CHECK ODI TASK NO. 2 */




/*-----------------------------------------------*/
/* TASK No. 3 */

/* SELECT STATEMENT FOUND, CHECK ODI TASK NO. 3 */




/*-----------------------------------------------*/
/* TASK No. 4 */
/* Drop work table */

-- drop table RAX_APP_USER.C$_0MDP_ITEM_ELIGIBILITY_STG purge

-- &


/*-----------------------------------------------*/
/* TASK No. 5 */
/* Create work table */

-- create table RAX_APP_USER.C$_0MDP_ITEM_ELIGIBILITY_STG
-- (
-- 	C1_ITEM_ID	VARCHAR2(64) NULL,
-- 	C2_SHUTTERFLY_ELIGIBLE	NUMBER(1) NULL,
-- 	C3_AUDIT_CREATE_DATE	DATE NULL,
-- 	C4_AUDIT_MODIFIED_DATE	DATE NULL,
-- 	C5_AUDIT_CREATE_BY	VARCHAR2(64) NULL,
-- 	C6_AUDIT_MODIFIED_BY	VARCHAR2(64) NULL,
-- 	C7_ADMINISTRATIVE_TYPE	VARCHAR2(255) NULL,
-- 	C8_EXCLUDE_FROM_SHIPMENT_TRIGG	NUMBER(1) NULL,
-- 	C9_ALL_LOOKS_SHUTTERFLY_ELIGIB	NUMBER(1) NULL
-- )
-- NOLOGGING

-- &


/*-----------------------------------------------*/
/* TASK No. 6 */
/* Load data */

/* SOURCE CODE */


-- select	
-- 	ITEM_ELIGIBILITY.ITEM_ID	   C1_ITEM_ID,
-- 	ITEM_ELIGIBILITY.SHUTTERFLY_ELIGIBLE	   C2_SHUTTERFLY_ELIGIBLE,
-- 	ITEM_ELIGIBILITY.AUDIT_CREATE_DATE	   C3_AUDIT_CREATE_DATE,
-- 	ITEM_ELIGIBILITY.AUDIT_MODIFIED_DATE	   C4_AUDIT_MODIFIED_DATE,
-- 	ITEM_ELIGIBILITY.AUDIT_CREATE_BY	   C5_AUDIT_CREATE_BY,
-- 	ITEM_ELIGIBILITY.AUDIT_MODIFIED_BY	   C6_AUDIT_MODIFIED_BY,
-- 	ITEM_ELIGIBILITY.ADMINISTRATIVE_TYPE	   C7_ADMINISTRATIVE_TYPE,
-- 	ITEM_ELIGIBILITY.EXCLUDE_FROM_SHIPMENT_TRIGGER	   C8_EXCLUDE_FROM_SHIPMENT_TRIGG,
-- 	ITEM_ELIGIBILITY.ALL_LOOKS_SHUTTERFLY_ELIGIBLE	   C9_ALL_LOOKS_SHUTTERFLY_ELIGIB
-- from	MDP_OWN.ITEM_ELIGIBILITY   ITEM_ELIGIBILITY
-- where	(1=1)
-- And (ITEM_ELIGIBILITY.AUDIT_MODIFIED_DATE >= TO_DATE(SUBSTR(:v_cdc_load_date, 1, 19), 'YYYY-MM-DD HH24:MI:SS')  -:v_cdc_oms_overlap)







-- &

-- /* TARGET CODE */
-- insert /*+ append */ into RAX_APP_USER.C$_0MDP_ITEM_ELIGIBILITY_STG
-- (
-- 	C1_ITEM_ID,
-- 	C2_SHUTTERFLY_ELIGIBLE,
-- 	C3_AUDIT_CREATE_DATE,
-- 	C4_AUDIT_MODIFIED_DATE,
-- 	C5_AUDIT_CREATE_BY,
-- 	C6_AUDIT_MODIFIED_BY,
-- 	C7_ADMINISTRATIVE_TYPE,
-- 	C8_EXCLUDE_FROM_SHIPMENT_TRIGG,
-- 	C9_ALL_LOOKS_SHUTTERFLY_ELIGIB
-- )
-- values
-- (
-- 	:C1_ITEM_ID,
-- 	:C2_SHUTTERFLY_ELIGIBLE,
-- 	:C3_AUDIT_CREATE_DATE,
-- 	:C4_AUDIT_MODIFIED_DATE,
-- 	:C5_AUDIT_CREATE_BY,
-- 	:C6_AUDIT_MODIFIED_BY,
-- 	:C7_ADMINISTRATIVE_TYPE,
-- 	:C8_EXCLUDE_FROM_SHIPMENT_TRIGG,
-- 	:C9_ALL_LOOKS_SHUTTERFLY_ELIGIB
-- )

-- &


/*-----------------------------------------------*/
/* TASK No. 7 */
/* Analyze work table */



BEGIN
DBMS_STATS.GATHER_TABLE_STATS (
    ownname =>	'RAX_APP_USER',
    tabname =>	'C$_0MDP_ITEM_ELIGIBILITY_STG',
    estimate_percent =>	DBMS_STATS.AUTO_SAMPLE_SIZE
);
END;




&


/*-----------------------------------------------*/
/* TASK No. 9 */
/* Drop flow table */
BEGIN  
   EXECUTE IMMEDIATE 'drop table RAX_APP_USER.I$_MDP_ITEM_ELIGIBILITY_STG';  
EXCEPTION  
   WHEN OTHERS THEN  
      IF SQLCODE != -942 THEN  
         RAISE;  
      END IF;  
END;


&




/*-----------------------------------------------*/
/* TASK No. 10 */
/* Create flow table I$ */

create table RAX_APP_USER.I$_MDP_ITEM_ELIGIBILITY_STG
(
	ITEM_ID		VARCHAR2(64) NULL,
	SHUTTERFLY_ELIGIBLE		NUMBER(1) NULL,
	AUDIT_CREATE_DATE		DATE NULL,
	AUDIT_MODIFIED_DATE		DATE NULL,
	AUDIT_CREATE_BY		VARCHAR2(64) NULL,
	AUDIT_MODIFIED_BY		VARCHAR2(64) NULL,
	ADMINISTRATIVE_TYPE		VARCHAR2(255) NULL,
	EXCLUDE_FROM_SHIPMENT_TRIGGER		NUMBER(1) NULL,
	ODS_MODIFY_DATE		DATE NULL,
	ALL_LOOKS_SHUTTERFLY_ELIGIBLE		NUMBER(1) NULL,
	IND_UPDATE		CHAR(1)
)
NOLOGGING

&


/*-----------------------------------------------*/
/* TASK No. 11 */
/* Insert flow into I$ table */

/* DETECTION_STRATEGY = NOT_EXISTS */
 


  


insert into	RAX_APP_USER.I$_MDP_ITEM_ELIGIBILITY_STG
(
	ITEM_ID,
	SHUTTERFLY_ELIGIBLE,
	AUDIT_CREATE_DATE,
	AUDIT_MODIFIED_DATE,
	AUDIT_CREATE_BY,
	AUDIT_MODIFIED_BY,
	ADMINISTRATIVE_TYPE,
	EXCLUDE_FROM_SHIPMENT_TRIGGER,
	ALL_LOOKS_SHUTTERFLY_ELIGIBLE,
	IND_UPDATE
)
select 
ITEM_ID,
	SHUTTERFLY_ELIGIBLE,
	AUDIT_CREATE_DATE,
	AUDIT_MODIFIED_DATE,
	AUDIT_CREATE_BY,
	AUDIT_MODIFIED_BY,
	ADMINISTRATIVE_TYPE,
	EXCLUDE_FROM_SHIPMENT_TRIGGER,
	ALL_LOOKS_SHUTTERFLY_ELIGIBLE,
	IND_UPDATE
 from (


select 	 
	
	C1_ITEM_ID ITEM_ID,
	C2_SHUTTERFLY_ELIGIBLE SHUTTERFLY_ELIGIBLE,
	C3_AUDIT_CREATE_DATE AUDIT_CREATE_DATE,
	C4_AUDIT_MODIFIED_DATE AUDIT_MODIFIED_DATE,
	C5_AUDIT_CREATE_BY AUDIT_CREATE_BY,
	C6_AUDIT_MODIFIED_BY AUDIT_MODIFIED_BY,
	C7_ADMINISTRATIVE_TYPE ADMINISTRATIVE_TYPE,
	C8_EXCLUDE_FROM_SHIPMENT_TRIGG EXCLUDE_FROM_SHIPMENT_TRIGGER,
	C9_ALL_LOOKS_SHUTTERFLY_ELIGIB ALL_LOOKS_SHUTTERFLY_ELIGIBLE,

	'I' IND_UPDATE

from	RAX_APP_USER.C$_0MDP_ITEM_ELIGIBILITY_STG
where	(1=1)






) S
where NOT EXISTS 
	( select 1 from ODS_STAGE.MDP_ITEM_ELIGIBILITY_STG T
	where	T.ITEM_ID	= S.ITEM_ID 
		 and ((T.SHUTTERFLY_ELIGIBLE = S.SHUTTERFLY_ELIGIBLE) or (T.SHUTTERFLY_ELIGIBLE IS NULL and S.SHUTTERFLY_ELIGIBLE IS NULL)) and
		((T.AUDIT_CREATE_DATE = S.AUDIT_CREATE_DATE) or (T.AUDIT_CREATE_DATE IS NULL and S.AUDIT_CREATE_DATE IS NULL)) and
		((T.AUDIT_MODIFIED_DATE = S.AUDIT_MODIFIED_DATE) or (T.AUDIT_MODIFIED_DATE IS NULL and S.AUDIT_MODIFIED_DATE IS NULL)) and
		((T.AUDIT_CREATE_BY = S.AUDIT_CREATE_BY) or (T.AUDIT_CREATE_BY IS NULL and S.AUDIT_CREATE_BY IS NULL)) and
		((T.AUDIT_MODIFIED_BY = S.AUDIT_MODIFIED_BY) or (T.AUDIT_MODIFIED_BY IS NULL and S.AUDIT_MODIFIED_BY IS NULL)) and
		((T.ADMINISTRATIVE_TYPE = S.ADMINISTRATIVE_TYPE) or (T.ADMINISTRATIVE_TYPE IS NULL and S.ADMINISTRATIVE_TYPE IS NULL)) and
		((T.EXCLUDE_FROM_SHIPMENT_TRIGGER = S.EXCLUDE_FROM_SHIPMENT_TRIGGER) or (T.EXCLUDE_FROM_SHIPMENT_TRIGGER IS NULL and S.EXCLUDE_FROM_SHIPMENT_TRIGGER IS NULL)) and
		((T.ALL_LOOKS_SHUTTERFLY_ELIGIBLE = S.ALL_LOOKS_SHUTTERFLY_ELIGIBLE) or (T.ALL_LOOKS_SHUTTERFLY_ELIGIBLE IS NULL and S.ALL_LOOKS_SHUTTERFLY_ELIGIBLE IS NULL))
        )

  
  

  

 


&


/*-----------------------------------------------*/
/* TASK No. 12 */
/* Create Index on flow table */

BEGIN  
   EXECUTE IMMEDIATE 'create index	RAX_APP_USER.I$_MDP_ITEM_ELIGIBILITY_STG_ID
on		RAX_APP_USER.I$_MDP_ITEM_ELIGIBILITY_STG (ITEM_ID)';  
 EXCEPTION  
    WHEN OTHERS THEN NULL;  
END;


&


/*-----------------------------------------------*/
/* TASK No. 13 */
/* Analyze integration table */



begin
    dbms_stats.gather_table_stats(
	ownname => 'RAX_APP_USER',
	tabname => 'I$_MDP_ITEM_ELIGIBILITY_STG',
	estimate_percent => dbms_stats.auto_sample_size
    );
end;



&


/*-----------------------------------------------*/
/* TASK No. 14 */
/* create check table */


-- create table RAX_APP_USER.SNP_CHECK_TAB
-- (
-- 	CATALOG_NAME	VARCHAR2(100 CHAR) NULL ,
-- 	SCHEMA_NAME	VARCHAR2(100 CHAR) NULL ,
-- 	RESOURCE_NAME	VARCHAR2(100 CHAR) NULL,
-- 	FULL_RES_NAME	VARCHAR2(100 CHAR) NULL,
-- 	ERR_TYPE		VARCHAR2(1 CHAR) NULL,
-- 	ERR_MESS		VARCHAR2(250 CHAR) NULL ,
-- 	CHECK_DATE	DATE NULL,
-- 	ORIGIN		VARCHAR2(100 CHAR) NULL,
-- 	CONS_NAME	VARCHAR2(35 CHAR) NULL,
-- 	CONS_TYPE		VARCHAR2(2 CHAR) NULL,
-- 	ERR_COUNT		NUMBER(10) NULL
-- )
	

-- &


/*-----------------------------------------------*/
/* TASK No. 15 */
/* delete previous check sum */

delete from	RAX_APP_USER.SNP_CHECK_TAB
where	SCHEMA_NAME	= 'ODS_STAGE'
and	ORIGIN 		= '(2317001)ODS_Project.LOAD_MDP_ITEM_ELIGIBILITY_INT'
and	ERR_TYPE 		= 'F'


&


/*-----------------------------------------------*/
/* TASK No. 16 */
/* create error table */
BEGIN
   EXECUTE IMMEDIATE 
   'create table RAX_APP_USER.E$_MDP_ITEM_ELIGIBILITY_STG
(
	ODI_ROW_ID 		UROWID,
	ODI_ERR_TYPE		VARCHAR2(1 CHAR) NULL, 
	ODI_ERR_MESS		VARCHAR2(250 CHAR) NULL,
	ODI_CHECK_DATE	DATE NULL, 
	ITEM_ID	VARCHAR2(64) NULL,
	SHUTTERFLY_ELIGIBLE	NUMBER(1) NULL,
	AUDIT_CREATE_DATE	DATE NULL,
	AUDIT_MODIFIED_DATE	DATE NULL,
	AUDIT_CREATE_BY	VARCHAR2(64) NULL,
	AUDIT_MODIFIED_BY	VARCHAR2(64) NULL,
	ADMINISTRATIVE_TYPE	VARCHAR2(255) NULL,
	EXCLUDE_FROM_SHIPMENT_TRIGGER	NUMBER(1) NULL,
	ODS_MODIFY_DATE	DATE NULL,
	ALL_LOOKS_SHUTTERFLY_ELIGIBLE	NUMBER(1) NULL,
	ODI_ORIGIN		VARCHAR2(100 CHAR) NULL,
	ODI_CONS_NAME	VARCHAR2(35 CHAR) NULL,
	ODI_CONS_TYPE		VARCHAR2(2 CHAR) NULL,
	ODI_PK			VARCHAR2(32 CHAR) PRIMARY KEY,
	ODI_SESS_NO		VARCHAR2(19 CHAR)
)';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -955 THEN  -- ORA-00955: name is already used by an existing object
         RAISE;
      ELSE
         DBMS_OUTPUT.PUT_LINE('Table RAX_APP_USER.E$_MDP_ITEM_ELIGIBILITY_STG already exists.');
      END IF;
END;


&


/*-----------------------------------------------*/
/* TASK No. 17 */
/* delete previous errors */

delete from 	RAX_APP_USER.E$_MDP_ITEM_ELIGIBILITY_STG
where	(ODI_ERR_TYPE = 'S'	and 'F' = 'S')
or	(ODI_ERR_TYPE = 'F'	and ODI_ORIGIN = '(2317001)ODS_Project.LOAD_MDP_ITEM_ELIGIBILITY_INT')


&


/*-----------------------------------------------*/
/* TASK No. 18 */
/* Create index on PK */

 
/* FLOW CONTROL CREATE THE iNDEX ON THE I$TABLE */
-- create index 	RAX_APP_USER.I$_MDP_ITEM_ELIGIBILITY_STG_ID
-- on	RAX_APP_USER.I$_MDP_ITEM_ELIGIBILITY_STG (ITEM_ID)


-- &


/*-----------------------------------------------*/
/* TASK No. 19 */
/* insert PK errors */

insert into RAX_APP_USER.E$_MDP_ITEM_ELIGIBILITY_STG
(
	ODI_PK,
	ODI_SESS_NO,
	ODI_ROW_ID,
	ODI_ERR_TYPE,
	ODI_ERR_MESS,
	ODI_ORIGIN,
	ODI_CHECK_DATE,
	ODI_CONS_NAME,
	ODI_CONS_TYPE,
	ITEM_ID,
	SHUTTERFLY_ELIGIBLE,
	AUDIT_CREATE_DATE,
	AUDIT_MODIFIED_DATE,
	AUDIT_CREATE_BY,
	AUDIT_MODIFIED_BY,
	ADMINISTRATIVE_TYPE,
	EXCLUDE_FROM_SHIPMENT_TRIGGER,
	ODS_MODIFY_DATE,
	ALL_LOOKS_SHUTTERFLY_ELIGIBLE
)
select	SYS_GUID(),
	:v_sess_no, 
	rowid,
	'F', 
	'ODI-15064: The primary key MDP_ITEM_ELIGIBILITY_STG_PK is not unique.',
	'(2317001)ODS_Project.LOAD_MDP_ITEM_ELIGIBILITY_INT',
	sysdate,
	'MDP_ITEM_ELIGIBILITY_STG_PK',
	'PK',	
	MDP_ITEM_ELIGIBILITY_STG.ITEM_ID,
	MDP_ITEM_ELIGIBILITY_STG.SHUTTERFLY_ELIGIBLE,
	MDP_ITEM_ELIGIBILITY_STG.AUDIT_CREATE_DATE,
	MDP_ITEM_ELIGIBILITY_STG.AUDIT_MODIFIED_DATE,
	MDP_ITEM_ELIGIBILITY_STG.AUDIT_CREATE_BY,
	MDP_ITEM_ELIGIBILITY_STG.AUDIT_MODIFIED_BY,
	MDP_ITEM_ELIGIBILITY_STG.ADMINISTRATIVE_TYPE,
	MDP_ITEM_ELIGIBILITY_STG.EXCLUDE_FROM_SHIPMENT_TRIGGER,
	MDP_ITEM_ELIGIBILITY_STG.ODS_MODIFY_DATE,
	MDP_ITEM_ELIGIBILITY_STG.ALL_LOOKS_SHUTTERFLY_ELIGIBLE
from	RAX_APP_USER.I$_MDP_ITEM_ELIGIBILITY_STG   MDP_ITEM_ELIGIBILITY_STG
where	exists  (
		select	SUB.ITEM_ID
		from 	RAX_APP_USER.I$_MDP_ITEM_ELIGIBILITY_STG SUB
		where 	SUB.ITEM_ID=MDP_ITEM_ELIGIBILITY_STG.ITEM_ID
		group by 	SUB.ITEM_ID
		having 	count(1) > 1
		)



&


/*-----------------------------------------------*/
/* TASK No. 20 */
/* insert Not Null errors */

insert into RAX_APP_USER.E$_MDP_ITEM_ELIGIBILITY_STG
(
	ODI_PK,
	ODI_SESS_NO,
	ODI_ROW_ID,
	ODI_ERR_TYPE,
	ODI_ERR_MESS,
	ODI_CHECK_DATE,
	ODI_ORIGIN,
	ODI_CONS_NAME,
	ODI_CONS_TYPE,
	ITEM_ID,
	SHUTTERFLY_ELIGIBLE,
	AUDIT_CREATE_DATE,
	AUDIT_MODIFIED_DATE,
	AUDIT_CREATE_BY,
	AUDIT_MODIFIED_BY,
	ADMINISTRATIVE_TYPE,
	EXCLUDE_FROM_SHIPMENT_TRIGGER,
	ODS_MODIFY_DATE,
	ALL_LOOKS_SHUTTERFLY_ELIGIBLE
)
select
	SYS_GUID(),
	:v_sess_no, 
	rowid,
	'F', 
	'ODI-15066: The column ITEM_ID cannot be null.',
	sysdate,
	'(2317001)ODS_Project.LOAD_MDP_ITEM_ELIGIBILITY_INT',
	'ITEM_ID',
	'NN',	
	ITEM_ID,
	SHUTTERFLY_ELIGIBLE,
	AUDIT_CREATE_DATE,
	AUDIT_MODIFIED_DATE,
	AUDIT_CREATE_BY,
	AUDIT_MODIFIED_BY,
	ADMINISTRATIVE_TYPE,
	EXCLUDE_FROM_SHIPMENT_TRIGGER,
	ODS_MODIFY_DATE,
	ALL_LOOKS_SHUTTERFLY_ELIGIBLE
from	RAX_APP_USER.I$_MDP_ITEM_ELIGIBILITY_STG
where	ITEM_ID is null



&


/*-----------------------------------------------*/
/* TASK No. 21 */
/* create index on error table */

 
/* FLOW CONTROL CREATE INDEX ON THE E$TABLE */

BEGIN  
   EXECUTE IMMEDIATE 'create index 	RAX_APP_USER.E$_MDP_ITEM_ELIGIBILITY_STG_ID
on	RAX_APP_USER.E$_MDP_ITEM_ELIGIBILITY_STG (ODI_ROW_ID)';  
 EXCEPTION  
    WHEN OTHERS THEN NULL;  
END;


&


/*-----------------------------------------------*/
/* TASK No. 22 */
/* delete errors from controlled table */

delete from	RAX_APP_USER.I$_MDP_ITEM_ELIGIBILITY_STG  T
where	exists 	(
		select	1
		from	RAX_APP_USER.E$_MDP_ITEM_ELIGIBILITY_STG E
		where ODI_SESS_NO = :v_sess_no
		and T.rowid = E.ODI_ROW_ID
		)


&


/*-----------------------------------------------*/
/* TASK No. 23 */
/* insert check sum into check table */

insert into RAX_APP_USER.SNP_CHECK_TAB
(
	SCHEMA_NAME,
	RESOURCE_NAME,
	FULL_RES_NAME,
	ERR_TYPE,
	ERR_MESS,
	CHECK_DATE,
	ORIGIN,
	CONS_NAME,
	CONS_TYPE,
	ERR_COUNT
)
select	
	'ODS_STAGE',
	'MDP_ITEM_ELIGIBILITY_STG',
	'ODS_STAGE.MDP_ITEM_ELIGIBILITY_STG',
	E.ODI_ERR_TYPE,
	E.ODI_ERR_MESS,
	E.ODI_CHECK_DATE,
	E.ODI_ORIGIN,
	E.ODI_CONS_NAME,
	E.ODI_CONS_TYPE,
	count(1) 
from	RAX_APP_USER.E$_MDP_ITEM_ELIGIBILITY_STG E
where	E.ODI_ERR_TYPE	= 'F'
and	E.ODI_ORIGIN 	= '(2317001)ODS_Project.LOAD_MDP_ITEM_ELIGIBILITY_INT'
group by	E.ODI_ERR_TYPE,
	E.ODI_ERR_MESS,
	E.ODI_CHECK_DATE,
	E.ODI_ORIGIN,
	E.ODI_CONS_NAME,
	E.ODI_CONS_TYPE


&


/*-----------------------------------------------*/
/* TASK No. 24 */
/* Flag rows for update */

/* DETECTION_STRATEGY = NOT_EXISTS */


update	RAX_APP_USER.I$_MDP_ITEM_ELIGIBILITY_STG
set	IND_UPDATE = 'U'
where	(ITEM_ID)
	in	(
		select	ITEM_ID
		from	ODS_STAGE.MDP_ITEM_ELIGIBILITY_STG
		)



&


/*-----------------------------------------------*/
/* TASK No. 25 */
/* Flag useless rows */

/* DETECTION_STRATEGY = NOT_EXISTS */

/* Command skipped due to chosen DETECTION_STRATEGY */



/*-----------------------------------------------*/
/* TASK No. 26 */
/* Update existing rows */

/* DETECTION_STRATEGY = NOT_EXISTS */
update	ODS_STAGE.MDP_ITEM_ELIGIBILITY_STG T
set 	
	(
	T.SHUTTERFLY_ELIGIBLE,
	T.AUDIT_CREATE_DATE,
	T.AUDIT_MODIFIED_DATE,
	T.AUDIT_CREATE_BY,
	T.AUDIT_MODIFIED_BY,
	T.ADMINISTRATIVE_TYPE,
	T.EXCLUDE_FROM_SHIPMENT_TRIGGER,
	T.ALL_LOOKS_SHUTTERFLY_ELIGIBLE
	) =
		(
		select	S.SHUTTERFLY_ELIGIBLE,
			S.AUDIT_CREATE_DATE,
			S.AUDIT_MODIFIED_DATE,
			S.AUDIT_CREATE_BY,
			S.AUDIT_MODIFIED_BY,
			S.ADMINISTRATIVE_TYPE,
			S.EXCLUDE_FROM_SHIPMENT_TRIGGER,
			S.ALL_LOOKS_SHUTTERFLY_ELIGIBLE
		from	RAX_APP_USER.I$_MDP_ITEM_ELIGIBILITY_STG S
		where	T.ITEM_ID	=S.ITEM_ID
	    	 )
	,        T.ODS_MODIFY_DATE = SYSDATE

where	(ITEM_ID)
	in	(
		select	ITEM_ID
		from	RAX_APP_USER.I$_MDP_ITEM_ELIGIBILITY_STG
		where	IND_UPDATE = 'U'
		)




&


/*-----------------------------------------------*/
/* TASK No. 27 */
/* Insert new rows */

/* DETECTION_STRATEGY = NOT_EXISTS */
insert into 	ODS_STAGE.MDP_ITEM_ELIGIBILITY_STG T
	(
	ITEM_ID,
	SHUTTERFLY_ELIGIBLE,
	AUDIT_CREATE_DATE,
	AUDIT_MODIFIED_DATE,
	AUDIT_CREATE_BY,
	AUDIT_MODIFIED_BY,
	ADMINISTRATIVE_TYPE,
	EXCLUDE_FROM_SHIPMENT_TRIGGER,
	ALL_LOOKS_SHUTTERFLY_ELIGIBLE
	,         ODS_MODIFY_DATE
	)
select 	ITEM_ID,
	SHUTTERFLY_ELIGIBLE,
	AUDIT_CREATE_DATE,
	AUDIT_MODIFIED_DATE,
	AUDIT_CREATE_BY,
	AUDIT_MODIFIED_BY,
	ADMINISTRATIVE_TYPE,
	EXCLUDE_FROM_SHIPMENT_TRIGGER,
	ALL_LOOKS_SHUTTERFLY_ELIGIBLE
	,         SYSDATE
from	RAX_APP_USER.I$_MDP_ITEM_ELIGIBILITY_STG S



where	IND_UPDATE = 'I'



&


/*-----------------------------------------------*/
/* TASK No. 28 */
/* Commit transaction */

/*commit*/


/*-----------------------------------------------*/
/* TASK No. 29 */
/* Drop flow table */

drop table RAX_APP_USER.I$_MDP_ITEM_ELIGIBILITY_STG 

&


/*-----------------------------------------------*/
/* TASK No. 1000008 */
/* Drop work table */

drop table RAX_APP_USER.C$_0MDP_ITEM_ELIGIBILITY_STG purge

&


/*-----------------------------------------------*/
/* TASK No. 30 */
/* Update CDC Load Status */

UPDATE ODS_OWN.ODS_CDC_LOAD_STATUS
SET LAST_CDC_COMPLETION_DATE=TO_DATE(
             SUBSTR(:v_sess_beg, 1, 19), 'RRRR-MM-DD HH24:MI:SS')
+ nvl((TIMEZONE_OFFSET/24), 0) 
WHERE ODS_TABLE_NAME=:v_cdc_load_table_name
AND CONTEXT_NAME = :v_env

/*
UPDATE ODS_OWN.ODS_CDC_LOAD_STATUS
SET LAST_CDC_COMPLETION_DATE=TO_DATE(
             SUBSTR('2024-06-17 13:09:29.0', 1, 19), 'RRRR-MM-DD HH24:MI:SS')
WHERE ODS_TABLE_NAME=:v_cdc_load_table_name
AND CONTEXT_NAME = :v_env
*/

&


/*-----------------------------------------------*/
/* TASK No. 31 */
/* Insert CDC Audit Record */

INSERT INTO RAX_APP_USER.ODS_CDC_LOAD_STATUS_AUDIT
(TABLE_NAME,
SESS_NO,                      
SESS_NAME,                    
SCEN_VERSION,                 
SESS_BEG,                     
ORIG_LAST_CDC_COMPLETION_DATE,
OVERLAP,
CREATE_DATE,
CONTEXT_NAME,
TIMEZONE_OFFSET              
)
select 
:v_cdc_load_table_name
,:v_sess_no
,'LOAD_MDP_ITEM_ELIGIBILITY_PKG'
,'004'
,TO_DATE(SUBSTR(:v_sess_beg, 1, 19), 'RRRR-MM-DD HH24:MI:SS')
,TO_DATE (SUBSTR(:v_cdc_load_date, 1, 19),'YYYY-MM-DD HH24:MI:SS')
,:v_cdc_overlap
,SYSDATE
,:v_env
,TIMEZONE_OFFSET
from 
ODS_OWN.ODS_CDC_LOAD_STATUS
WHERE ODS_TABLE_NAME=:v_cdc_load_table_name
AND CONTEXT_NAME = :v_env

/*
INSERT INTO RAX_APP_USER.ODS_CDC_LOAD_STATUS_AUDIT
(TABLE_NAME,
SESS_NO,                      
SESS_NAME,                    
SCEN_VERSION,                 
SESS_BEG,                     
ORIG_LAST_CDC_COMPLETION_DATE,
OVERLAP,
CREATE_DATE,
CONTEXT_NAME              
)
values (
:v_cdc_load_table_name,
:v_sess_no,
'LOAD_MDP_ITEM_ELIGIBILITY_PKG',
'004',
TO_DATE(
             SUBSTR('2024-06-17 13:09:29.0', 1, 19), 'RRRR-MM-DD HH24:MI:SS'),
TO_DATE (SUBSTR (:v_cdc_load_date, 1, 19),
                           'YYYY-MM-DD HH24:MI:SS'
                          )
,:v_cdc_overlap,
SYSDATE,
 :v_env)
*/


&


/*-----------------------------------------------*/
