---

pipeline:
  name: lt_99_YEARBOOK_IN_THE_PACK_PKG_dag
  description: 99_YEARBOOK_IN_THE_PACK_PKG
  schedule: "@monthly"
  tags:
    - lifetouch
    - 99_YEARBOOK_IN_THE_PACK_PKG
  
  task_groups:

    - name: 99_YEARBOOK_IN_THE_PACK_PKG_export
      description: drop and recreate table then extract data and load to s3
      export_file_name:
        v_data_export_run_date: dags/sql/pre_sql/v_data_export_run_date.sql
      pre_sql:
        v_data_export_last_month_begin_date: dags/sql/pre_sql/v_data_export_last_month_begin_date.sql
        v_data_export_last_month_end_date: dags/sql/pre_sql/v_data_export_last_month_end_date.sql
      tasks:
        - script_location: dags/sql/99_YEARBOOK_IN_THE_PACK_PKG/yearbook_sales_create_tmp.sql
          export_files:
            - extract_query: 99_YEARBOOK_IN_THE_PACK_PKG/yearbook_sales_export.sql
              export_location: finance/yearbook_sales/InThePack


   