select 	
	ACT_SNG_SUP.FISCAL_YEAR	   FISCAL_YEAR,
	ACT_SNG_SUP.MONTH	   MONTH,
	ACT_SNG_SUP.RUN_DATE	   RUN_DATE,
	ACT_SNG_SUP.COMPANY_NAME	   COMPANY_NAME,
	ACT_SNG_SUP.COUNTRY_NAME	   COUNTRY_NAME,
	ACT_SNG_SUP.SUB_PROGRAM_NAME	   SUB_PROGRAM_NAME,
	ACT_SNG_SUP.MERCHANDISE_CATEGORY	   MERCHANDISE_CATEGORY,
	ACT_SNG_SUP.ITEM_GROUP	   ITEM_GROUP,
	ACT_SNG_SUP.NET_SHIPPED_SALES_AMT	   NET_SHIPPED_SALES_AMT
from	RAX_APP_USER.ACTUATE_SENIORSAL_SUPPLE_STAGE   ACT_SNG_SUP
where	
	(1=1)	