select 	
	ACT_SEN_DET.COUNTRY_NAME	   COUNTRY_NAME,
	ACT_SEN_DET.COMPANY_NAME	   COMPANY_NAME,
	ACT_SEN_DET.FISCAL_YEAR	   FISCAL_YEAR,
	ACT_SEN_DET.MONTH	   MONTH,
	ACT_SEN_DET.RUN_DATE	   RUN_DATE,
	ACT_SEN_DET.SUB_PROGRAM_NAME	   SUB_PROGRAM_NAME,
	ACT_SEN_DET.PROGRAM_NAME	   PROGRAM_NAME,
	ACT_SEN_DET.PHOTO_SUBJ	   PHOTO_SUBJ,
	ACT_SEN_DET.ORDER_SUBJ	   ORDER_SUBJ,
	ACT_SEN_DET.SERV_NET_SALES	   SERV_NET_SALES,
	ACT_SEN_DET.SIT_AVG	   SIT_AVG,
	ACT_SEN_DET.SERV_TAX	   SERV_TAX,
	ACT_SEN_DET.PROD_NET_SALES	   PROD_NET_SALES,
	ACT_SEN_DET.ORDER_AVG	   ORDER_AVG,
	ACT_SEN_DET.PROD_TAX	   PROD_TAX,
	ACT_SEN_DET.OTHER_NET_SALES	   OTHER_NET_SALES,
	ACT_SEN_DET.OTHER_TAX	   OTHER_TAX,
	ACT_SEN_DET.NET_PAID_SALES	   NET_PAID_SALES,
	ACT_SEN_DET.TERRITORY_EARNINGS	   TERRITORY_EARNINGS,
	ACT_SEN_DET.SERV_NET_SALES  +  ACT_SEN_DET.PROD_NET_SALES	   NET_SHIPPED_SALES,
	DECODE( ACT_SEN_DET.PHOTO_SUBJ   ,0,0, (ACT_SEN_DET.SERV_NET_SALES  +  ACT_SEN_DET.PROD_NET_SALES) / ACT_SEN_DET.PHOTO_SUBJ )	   SALES_AVG,
	ACT_SEN_DET.SERV_TAX + ACT_SEN_DET.PROD_TAX	   TAX
from	RAX_APP_USER.ACTUATE_SENIORSAL_DETAIL_STAGE   ACT_SEN_DET
where	
	(1=1)	