---

pipeline:
  name: PKG_NAME_PKG_dag
  description: PKG_NAMEpackage
  schedule: add your schedule
  tags:
    - lifetouch
    - PKG_NAME
  
  task_groups:
    - name: PKG_NAME_wait_for_data
      description: run ODI wait command
      schema_name: 
      session_name: 
      table_name: 
    

    - name: PKG_NAME_export
      description: drop and recreate table then extract data and load to s3
      export_file_name:
        v_data_export_trigger_table_id: dags/sql/pre_sql/data_export_trigger_table_id.sql
        v_data_export_run_date_trigger_table_refresh:  dags/sql/pre_sql/data_export_run_date_trigger_table_refresh.sql

      tasks:
        - script_location: dags/sql/PKG_NAME/your_sub_pkg_filename.sql
          export_files:
            - extract_query: PKG_NAME/export_filename.sql
              export_location: 


    - name: PKG_NAME_ODI_Update
      description: ODI SQL Transformation Logic
      pre_sql:
        v_data_export_trigger_table_id: dags/sql/pre_sql/v_data_export_trigger_table_id.sql
      default_args:
        v_cdc_overlap: 0.02083333333
      tasks: 
        - description: run_pkg
          type: oracle_sql
          script_location: dags/sql/PKG_NAME/your_sub_pkg_filename.sql
          args:
            v_session_name: PKG_NAME

        
        
