---

pipeline:
  name: lt_99_uc_lawson_refunds_pkg_dag
  description: 99_uc_lawson_refunds_pkgpackage
  schedule: 0 5 1 * *         # Runs first day of each month at 5 AM.
  tags:
    - lifetouch
    - 99_uc_lawson_refunds_pkg
  
  task_groups:

    - name: 99_uc_lawson_refunds_pkg_export
      description: drop and recreate table then extract data and load to s3

      export_file_name:
        v_actuate_sysdate: dags/sql/pre_sql/v_actuate_sysdate.sql
      tasks:
        - script_location: dags/sql/99_uc_lawson_refunds_pkg/uc_lawson_refunds_create.sql
          export_files:
            - extract_query: 99_uc_lawson_refunds_pkg/uc_lawson_refunds_export.sql
              export_location: finance/Audit/UC_Lawson_Refunds/UC_LAWSON_REFUNDS-


    - name: 99_uc_lawson_refunds_pkg_ODI_Update
      description: ODI SQL Transformation Logic
      pre_sql:
        v_cdc_ld_date: dags/sql/pre_sql/pre_v_cdc_ld_date.sql
        v_actuate_sysdate: dags/sql/pre_sql/v_actuate_sysdate.sql
        v_US_data_center_replace_space: dags/sql/pre_sql/v_US_data_center_replace_space.sql
        v_cdc_load_date: dags/sql/pre_sql/pre_v_cdc_ld_date.sql
      default_args:
        v_cdc_overlap: 0.02083333333
      tasks: 
        - description: run_pkg
          type: oracle_sql
          script_location: dags/sql/99_uc_lawson_refunds_pkg/99_UC_LAWSON_REFUNDS_PKG.sql
          args:
            v_session_name: 99_uc_lawson_refunds_pkg
            v_cdc_load_table_name: UC_LAWSON_REFUNDS

    - name: SEND_EMAIL
      email_configurations:
        subject: Monthly Underclass Lawson Refunds Files Created
        message: dags/sql/messages/99_uc_lawson_refunds_pkg/email.txt
        message_args: 
              v_US_data_center:
                path: dags/sql/pre_sql/v_US_data_center.sql
        email_recipient_query: pre_sql/v_error_email_to.sql
        email_recipient_query_args:
          v_package_name: '99_uc_lawson_refunds_pkg'
        
        
