/* TASK No. 1 */

/* SELECT STATEMENT FOUND, CHECK ODI TASK NO. 1 */




/*-----------------------------------------------*/
/* TASK No. 2 */
/* drop  report tabe */

drop table RAX_APP_USER.actuate_imgstrm_chrgebk_stage


&


/*-----------------------------------------------*/
/* TASK No. 3 */
/* Create  report  table */

create table RAX_APP_USER.actuate_imgstrm_chrgebk_stage as
select territory_code
, ams_business_unit_name
, lifetouch_id
, account_name
, city
, state
, chargeback_amount
, item770
from imagestream_chargeback_true_up
order by territory_code
, lifetouch_id

&


/*-----------------------------------------------*/
/* TASK No. 4 */
/* Generate header */

create header	(TERRITORY_CODE,
	AMS_BUSINESS_UNIT_NAME,
	LIFETOUCH_ID,
	ACCOUNT_NAME,
	CITY,
	STATE,
	CHARGEBACK_AMOUNT,
	ITEM770)

/*$$SNPS_START_KEYSNP$CRDWG_TABLESNP$CRTABLE_NAME=imgstream_chrgeback_trueup.csvSNP$CRLOAD_FILE=/dw_export/PROD/imgstream_chrgeback_trueup.csvSNP$CRFILE_FORMAT=DSNP$CRFILE_SEP_FIELD=0x002cSNP$CRFILE_SEP_LINE=0x000D0x000ASNP$CRFILE_FIRST_ROW=0SNP$CRFILE_ENC_FIELD="SNP$CRFILE_DEC_SEP=SNP$CRSNP$CRDWG_COLSNP$CRCOL_NAME=TERRITORY_CODESNP$CRTYPE_NAME=STRINGSNP$CRORDER=1SNP$CRLENGTH=50SNP$CRPRECISION=50SNP$CRSNP$CRDWG_COLSNP$CRCOL_NAME=AMS_BUSINESS_UNIT_NAMESNP$CRTYPE_NAME=STRINGSNP$CRORDER=2SNP$CRLENGTH=100SNP$CRPRECISION=100SNP$CRSNP$CRDWG_COLSNP$CRCOL_NAME=LIFETOUCH_IDSNP$CRTYPE_NAME=STRINGSNP$CRORDER=3SNP$CRLENGTH=50SNP$CRPRECISION=50SNP$CRSNP$CRDWG_COLSNP$CRCOL_NAME=ACCOUNT_NAMESNP$CRTYPE_NAME=STRINGSNP$CRORDER=4SNP$CRLENGTH=50SNP$CRPRECISION=50SNP$CRSNP$CRDWG_COLSNP$CRCOL_NAME=CITYSNP$CRTYPE_NAME=STRINGSNP$CRORDER=5SNP$CRLENGTH=50SNP$CRPRECISION=50SNP$CRSNP$CRDWG_COLSNP$CRCOL_NAME=STATESNP$CRTYPE_NAME=STRINGSNP$CRORDER=6SNP$CRLENGTH=50SNP$CRPRECISION=50SNP$CRSNP$CRDWG_COLSNP$CRCOL_NAME=CHARGEBACK_AMOUNTSNP$CRTYPE_NAME=STRINGSNP$CRORDER=7SNP$CRLENGTH=50SNP$CRPRECISION=50SNP$CRSNP$CRDWG_COLSNP$CRCOL_NAME=ITEM770SNP$CRTYPE_NAME=STRINGSNP$CRORDER=8SNP$CRLENGTH=50SNP$CRPRECISION=50SNP$CR$$SNPS_END_KEY*/


&


/*-----------------------------------------------*/
/* TASK No. 5 */
/* Insert new rows */

/* SOURCE CODE */


select 	
	ACT.TERRITORY_CODE	   TERRITORY_CODE,
	ACT.AMS_BUSINESS_UNIT_NAME	   AMS_BUSINESS_UNIT_NAME,
	ACT.LIFETOUCH_ID	   LIFETOUCH_ID,
	ACT.ACCOUNT_NAME	   ACCOUNT_NAME,
	ACT.CITY	   CITY,
	ACT.STATE	   STATE,
	ACT.CHARGEBACK_AMOUNT	   CHARGEBACK_AMOUNT,
	ACT.ITEM770	   ITEM770
from	RAX_APP_USER.ACTUATE_IMGSTRM_CHRGEBK_STAGE   ACT
where	
	(1=1)	
	





/* Order the output by the UD1, UD2, UD3, UD4, UD5, UD6 Fields. */



&

/* TARGET CODE */
insert into "/dw_export/PROD/imgstream_chrgeback_trueup.csv"
(
	TERRITORY_CODE,
	AMS_BUSINESS_UNIT_NAME,
	LIFETOUCH_ID,
	ACCOUNT_NAME,
	CITY,
	STATE,
	CHARGEBACK_AMOUNT,
	ITEM770
                     
)
values 
(
	:TERRITORY_CODE,
	:AMS_BUSINESS_UNIT_NAME,
	:LIFETOUCH_ID,
	:ACCOUNT_NAME,
	:CITY,
	:STATE,
	:CHARGEBACK_AMOUNT,
	:ITEM770
                     
)
/*$$SNPS_START_KEYSNP$CRDWG_TABLESNP$CRTABLE_NAME=imgstream_chrgeback_trueup.csvSNP$CRLOAD_FILE=/dw_export/PROD/imgstream_chrgeback_trueup.csvSNP$CRFILE_FORMAT=DSNP$CRFILE_SEP_FIELD=0x002cSNP$CRFILE_SEP_LINE=0x000D0x000ASNP$CRFILE_FIRST_ROW=0SNP$CRFILE_ENC_FIELD="SNP$CRFILE_DEC_SEP=SNP$CRSNP$CRDWG_COLSNP$CRCOL_NAME=TERRITORY_CODESNP$CRTYPE_NAME=STRINGSNP$CRORDER=1SNP$CRLENGTH=50SNP$CRPRECISION=50SNP$CRSNP$CRDWG_COLSNP$CRCOL_NAME=AMS_BUSINESS_UNIT_NAMESNP$CRTYPE_NAME=STRINGSNP$CRORDER=2SNP$CRLENGTH=100SNP$CRPRECISION=100SNP$CRSNP$CRDWG_COLSNP$CRCOL_NAME=LIFETOUCH_IDSNP$CRTYPE_NAME=STRINGSNP$CRORDER=3SNP$CRLENGTH=50SNP$CRPRECISION=50SNP$CRSNP$CRDWG_COLSNP$CRCOL_NAME=ACCOUNT_NAMESNP$CRTYPE_NAME=STRINGSNP$CRORDER=4SNP$CRLENGTH=50SNP$CRPRECISION=50SNP$CRSNP$CRDWG_COLSNP$CRCOL_NAME=CITYSNP$CRTYPE_NAME=STRINGSNP$CRORDER=5SNP$CRLENGTH=50SNP$CRPRECISION=50SNP$CRSNP$CRDWG_COLSNP$CRCOL_NAME=STATESNP$CRTYPE_NAME=STRINGSNP$CRORDER=6SNP$CRLENGTH=50SNP$CRPRECISION=50SNP$CRSNP$CRDWG_COLSNP$CRCOL_NAME=CHARGEBACK_AMOUNTSNP$CRTYPE_NAME=STRINGSNP$CRORDER=7SNP$CRLENGTH=50SNP$CRPRECISION=50SNP$CRSNP$CRDWG_COLSNP$CRCOL_NAME=ITEM770SNP$CRTYPE_NAME=STRINGSNP$CRORDER=8SNP$CRLENGTH=50SNP$CRPRECISION=50SNP$CR$$SNPS_END_KEY*/



/*-----------------------------------------------*/
/* TASK No. 6 */

chmod 644 /dw_export/PROD/imgstream_chrgeback_trueup.csv

&


/*-----------------------------------------------*/
/* TASK No. 7 */

mv /dw_export/PROD/imgstream_chrgeback_trueup.csv /dw_export/PROD/finance/imgstream_chrgeback_trueup/imgstream_chrgeback_trueup:v_actuate_sysdate.csv

&


/*-----------------------------------------------*/
