select 	
	ACT.TERRITORY_CODE	   TERRITORY_CODE,
	ACT.AMS_BUSINESS_UNIT_NAME	   AMS_BUSINESS_UNIT_NAME,
	ACT.LIFETOUCH_ID	   LIFETOUCH_ID,
	ACT.ACCOUNT_NAME	   ACCOUNT_NAME,
	ACT.CITY	   CITY,
	ACT.STATE	   STATE,
	ACT.CHARGEBACK_AMOUNT	   CHARGEBACK_AMOUNT,
	ACT.ITEM770	   ITEM770
from	RAX_APP_USER.ACTUATE_IMGSTRM_CHRGEBK_STAGE   ACT
where	
	(1=1)	