

select 	
	SHIPMENTS_BY_EVENT_STG.PLANT_NAME	   PLANT_NAME,
	SHIPMENTS_BY_EVENT_STG.CALENDAR_YEAR	   CALENDAR_YEAR,
	SHIPMENTS_BY_EVENT_STG.CALENDAR_WEEK_NUMBER	   CALENDAR_WEEK,
	SHIPMENTS_BY_EVENT_STG.JOB_NBR	   JOB_NUMBER,
	SHIPMENTS_BY_EVENT_STG.SALES_LINE_NAME	   SALES_LINE_NAME,
	SHIPMENTS_BY_EVENT_STG.PROGRAM_NAME	   PROGRAM_NAME,
	SHIPMENTS_BY_EVENT_STG.SUB_PROGRAM_NAME	   SUB_PROGRAM_NAME,
	SHIPMENTS_BY_EVENT_STG.ACCOUNT_NAME	   ACCOUNT_NAME,
	SHIPMENTS_BY_EVENT_STG.TRANS_DATE	   TRANS_DATE,
	SHIPMENTS_BY_EVENT_STG.SHIPPED_ORDER_QTY	   SHIPPED_QTY
from	RAX_APP_USER.SHIPMENTS_BY_EVENT_STG   SHIPMENTS_BY_EVENT_STG
where	
	(1=1)	
	






