select	
	LT_FULFILLMENT_BATCH.FULFILLMENT_BATCH_KEY	   C1_FULFILLMENT_BATCH_KEY,
	LT_FULFILLMENT_BATCH.BATCH_ID	   C2_BATCH_ID,
	LT_FULFILLMENT_BATCH.AVAILABLE_DATE	   C3_AVAILABLE_DATE,
	LT_FULFILLMENT_BATCH.STATUS	   C4_STATUS,
	LT_FULFILLMENT_BATCH.PACK_LIST_TYPE	   C5_PACK_LIST_TYPE,
	LT_FULFILLMENT_BATCH.RETOUCHING_FLAG	   C6_RETOUCHING_FLAG,
	LT_FULFILLMENT_BATCH.CREATETS	   C7_CREATETS,
	LT_FULFILLMENT_BATCH.MODIFYTS	   C8_MODIFYTS,
	LT_FULFILLMENT_BATCH.CREATEUSERID	   C9_CREATEUSERID,
	LT_FULFILLMENT_BATCH.MODIFYUSERID	   C10_MODIFYUSERID,
	LT_FULFILLMENT_BATCH.CREATEPROGID	   C11_CREATEPROGID,
	LT_FULFILLMENT_BATCH.MODIFYPROGID	   C12_MODIFYPROGID,
	LT_FULFILLMENT_BATCH.LOCKID	   C13_LOCKID,
	LT_FULFILLMENT_BATCH.ORDER_COUNT_BOC	   C14_ORDER_COUNT_BOC,
	LT_FULFILLMENT_BATCH.SHIP_NODE	   C15_SHIP_NODE,
	LT_FULFILLMENT_BATCH.BOC_BATCH_CREATETS	   C16_BOC_BATCH_CREATETS,
	LT_FULFILLMENT_BATCH.SERVICE_RECOVERY	   C17_SERVICE_RECOVERY,
	LT_FULFILLMENT_BATCH.BATCH_TYPE	   C18_BATCH_TYPE
from	OMS3_SIT94.LT_FULFILLMENT_BATCH   LT_FULFILLMENT_BATCH
where	(1=1)
And (LT_FULFILLMENT_BATCH.MODIFYTS >= TO_DATE(SUBSTR(:v_cdc_load_date, 1, 19), 'YYYY-MM-DD HH24:MI:SS')  - :v_cdc_oms_overlap)