DECLARE create_query CLOB;  
   BEGIN  
      BEGIN  
         EXECUTE IMMEDIATE 'drop table RAX_APP_USER.C$_0LT_FULFILL_BATCH_STG purge';  
      EXCEPTION  
         WHEN OTHERS THEN NULL;  
      END;  
      create_query := 'create table RAX_APP_USER.C$_0LT_FULFILL_BATCH_STG
(
	C1_FULFILLMENT_BATCH_KEY	VARCHAR2(24) NULL,
	C2_BATCH_ID	VARCHAR2(40) NULL,
	C3_AVAILABLE_DATE	DATE NULL,
	C4_STATUS	VARCHAR2(40) NULL,
	C5_PACK_LIST_TYPE	VARCHAR2(20) NULL,
	C6_RETOUCHING_FLAG	VARCHAR2(5) NULL,
	C7_CREATETS	DATE NULL,
	C8_MODIFYTS	DATE NULL,
	C9_CREATEUSERID	VARCHAR2(40) NULL,
	C10_MODIFYUSERID	VARCHAR2(40) NULL,
	C11_CREATEPROGID	VARCHAR2(40) NULL,
	C12_MODIFYPROGID	VARCHAR2(40) NULL,
	C13_LOCKID	NUMBER(5) NULL,
	C14_ORDER_COUNT_BOC	NUMBER(5) NULL,
	C15_SHIP_NODE	CHAR(24) NULL,
	C16_BOC_BATCH_CREATETS	DATE NULL,
	C17_SERVICE_RECOVERY	VARCHAR2(40) NULL,
	C18_BATCH_TYPE	VARCHAR2(20) NULL
)
NOLOGGING';  
      EXECUTE IMMEDIATE create_query;  
   END;  