---

pipeline:
  name: lt_99_SENIOR_SALES_ANALYSIS_PKG
  description: 99_SENIOR_SALES_ANALYSIS_PKG 
  schedule: '@daily'
  tags:
    - lifetouch
    - 99_SENIOR_SALES_ANALYSIS_PKG
  
  task_groups:
    - name: 99_SENIOR_SALES_ANALYSIS_PKG_wait_for_data
      description: run ODI wait command
      schema_name: ODS_STAGE
      session_name: 99_SENIOR_SALES_ANALYSIS_PKG
      table_name: DATA_EXPORT_TRIGGER
    

    - name: 99_SENIOR_SALES_ANALYSIS_PKG_export
      description: drop and recreate table then extract data and load to s3
      export_file_name:
        v_data_export_trigger_table_id: dags/sql/pre_sql/v_data_export_trigger_table_id.sql
        v_data_export_run_date_trigger_table_refresh:  dags/sql/pre_sql/data_export_run_date_trigger_table_refresh.sql
      export_args:
          v_session_name: 99_SENIOR_SALES_ANALYSIS_PKG
      
      pre_sql:
        v_data_export_run_date_trigger_table_refresh: dags/sql/pre_sql/v_data_export_run_date_trigger_table_refresh.sql
      
      tasks:
        - script_location: dags/sql/99_SENIOR_SALES_ANALYSIS_PKG/senior_sales_analysis_detail_create_tmp.sql
          args: 
            v_session_name: 99_SENIOR_SALES_ANALYSIS_PKG
          export_files:
            - extract_query: 99_SENIOR_SALES_ANALYSIS_PKG/senior_sales_analysis_detail_export.sql
              export_location: finance/senior_sales_analysis/senior_sales_analysis_detail
        
        - script_location: dags/sql/99_SENIOR_SALES_ANALYSIS_PKG/senior_sales_analysis_supple_create_tmp.sql
          args: 
            v_session_name: 99_SENIOR_SALES_ANALYSIS_PKG
          
          export_files:
            - extract_query: 99_SENIOR_SALES_ANALYSIS_PKG/senior_sales_analysis_supple_export.sql
              export_location: finance/senior_sales_analysis/senior_sales_analysis_supple


    - name: 99_SENIOR_SALES_ANALYSIS_PKG_ODI_Update
      description: ODI SQL Transformation Logic
      pre_sql:
        v_data_export_trigger_table_id: dags/sql/pre_sql/v_data_export_trigger_table_id.sql
      default_args:
        v_session_name: 99_SENIOR_SALES_ANALYSIS_PKG
      tasks: 
        - description: run_pkg
          type: oracle_sql
          script_location: dags/sql/99_SENIOR_SALES_ANALYSIS_PKG/99_SENIOR_SALES_ANALYSIS_PKG.sql
          args:
            v_session_name: 99_SENIOR_SALES_ANALYSIS_PKG

        
        
