/* TASK No. 1 */

/* NONE or SET VARIABLE STATEMENT FOUND, CHECK ODI TASK NO. 1 */




/*-----------------------------------------------*/
/* TASK No. 2 */

/* SELECT STATEMENT FOUND, CHECK ODI TASK NO. 2 */




/*-----------------------------------------------*/
/* TASK No. 3 */

/* SELECT STATEMENT FOUND, CHECK ODI TASK NO. 3 */




/*-----------------------------------------------*/
/* TASK No. 4 */
/* Delete from ODS_OWN.Invitation */

DELETE FROM ODS_OWN.USER_INVITATION T
      WHERE EXISTS
               (SELECT 1
                  FROM ODS_STAGE.AAR_USER_INVITATION_XR            XR,
                       ODS_STAGE.AAR_RECORD_CHANGE_AUDIT_STG D
                 WHERE     XR.USER_INVITATION_OID = T.USER_INVITATION_OID
                       AND XR.IDENTIFIER_KEY = D.KEY_VALUE
                       AND D.EVENT_TYPE = 'DELETE'
                       AND D.TABLE_NAME = 'INVITATION'
                       AND d.ods_create_date >= TO_DATE(SUBSTR(:v_cdc_load_date, 1, 19), 'YYYY-MM-DD HH24:MI:SS')  -:v_cdc_overlap )

&


/*-----------------------------------------------*/
/* TASK No. 5 */
/* Delete from Stage */

DELETE FROM ODS_STAGE.AAR_INVITATION_STG T
      WHERE EXISTS
               (SELECT 1
                  FROM ODS_STAGE.AAR_RECORD_CHANGE_AUDIT_STG D
                 WHERE     T.IDENTIFIER = D.KEY_VALUE
                       AND D.EVENT_TYPE = 'DELETE'
                       AND D.TABLE_NAME = 'INVITATION'
                       AND d.ods_create_date >= TO_DATE(SUBSTR(:v_cdc_load_date, 1, 19), 'YYYY-MM-DD HH24:MI:SS')  -:v_cdc_overlap)

&


/*-----------------------------------------------*/
/* TASK No. 6 */
/* Insert new rows */

 
insert into	ODS_STAGE.AAR_USER_INVITATION_XR 
( 
	IDENTIFIER_KEY 
	,USER_INVITATION_OID,
	ODS_CREATE_DATE 
) 

select
    IDENTIFIER_KEY   
  ,ODS_STAGE.USER_INVITATION_OID_SEQ.nextval,
	sysdate 
FROM (	


select 	DISTINCT
	AAR_INVITATION_STG.IDENTIFIER IDENTIFIER_KEY 
from	ODS_STAGE.AAR_USER_INVITATION_XR   AAR_USER_INVITATION_XR, ODS_STAGE.AAR_INVITATION_STG   AAR_INVITATION_STG
where		(1=1)	
 And (AAR_INVITATION_STG.IDENTIFIER=AAR_USER_INVITATION_XR.IDENTIFIER_KEY(+) and AAR_USER_INVITATION_XR.IDENTIFIER_KEY is null)





)    ODI_GET_FROM




&


/*-----------------------------------------------*/
/* TASK No. 7 */
/* Commit transaction */

/* commit */


/*-----------------------------------------------*/
/* TASK No. 8 */
/* Drop flow table */

BEGIN
    EXECUTE IMMEDIATE 'drop table RAX_APP_USER.I$_USER_INVITATION';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE = -942 THEN
            DBMS_OUTPUT.PUT_LINE('Table does not exist.');
        ELSE
            RAISE;
        END IF;
END;

&


/*-----------------------------------------------*/
/* TASK No. 9 */
/* Create flow table I$ */

create table RAX_APP_USER.I$_USER_INVITATION
(
	USER_INVITATION_OID	NUMBER NULL,
	USER_ACCOUNT_PRINCIPAL_OID	NUMBER NULL,
	EXPIRATION_DATE	DATE NULL,
	PROFILE_EMAIL_ADDRESS	VARCHAR2(255) NULL,
	AUDIT_CREATE_DATE	TIMESTAMP(6) NULL,
	AUDIT_CREATED_BY	VARCHAR2(255) NULL,
	AUDIT_MODIFY_DATE	TIMESTAMP(6) NULL,
	AUDIT_MODIFIED_BY	VARCHAR2(255) NULL,
	ODS_CREATE_DATE	DATE NULL,
	ODS_MODIFY_DATE	DATE NULL,
	INVITATION_IDENTIFIER	VARCHAR2(255) NULL
	,IND_UPDATE		char(1)
)
NOLOGGING

&


/*-----------------------------------------------*/
/* TASK No. 10 */
/* Insert flow into I$ table */

insert /*+ APPEND */  into RAX_APP_USER.I$_USER_INVITATION
	(
	USER_INVITATION_OID,
	USER_ACCOUNT_PRINCIPAL_OID,
	EXPIRATION_DATE,
	PROFILE_EMAIL_ADDRESS,
	AUDIT_CREATE_DATE,
	AUDIT_CREATED_BY,
	AUDIT_MODIFY_DATE,
	AUDIT_MODIFIED_BY,
	INVITATION_IDENTIFIER
	,IND_UPDATE
	)


select 	 
	
	AAR_USER_INVITATION_XR.USER_INVITATION_OID,
	USER_ACCT_PRNCPL.USER_ACCOUNT_PRINCIPAL_OID,
	AAR_INVITATION_STG.EXPIRATION_DATE,
	AAR_INVITATION_STG.PROFILE_EMAIL_ADDRESS,
	AAR_INVITATION_STG.AUDIT_CREATE_DATE,
	AAR_INVITATION_STG.AUDIT_CREATED_BY,
	AAR_INVITATION_STG.AUDIT_MODIFY_DATE,
	AAR_INVITATION_STG.AUDIT_MODIFIED_BY,
	AAR_INVITATION_STG.IDENTIFIER,

	'I' IND_UPDATE

from	ODS_STAGE.AAR_USER_INVITATION_XR   AAR_USER_INVITATION_XR, ODS_STAGE.AAR_INVITATION_STG   AAR_INVITATION_STG, ODS_OWN.USER_ACCOUNT_PRINCIPAL   USER_ACCT_PRNCPL
where	(1=1)
 And (AAR_USER_INVITATION_XR.IDENTIFIER_KEY=AAR_INVITATION_STG.IDENTIFIER)
AND (AAR_INVITATION_STG.ACCOUNT_PRINCIPAL_ID=USER_ACCT_PRNCPL.ACCOUNT_PRINCIPAL_ID)





minus
select
	USER_INVITATION_OID,
	USER_ACCOUNT_PRINCIPAL_OID,
	EXPIRATION_DATE,
	PROFILE_EMAIL_ADDRESS,
	AUDIT_CREATE_DATE,
	AUDIT_CREATED_BY,
	AUDIT_MODIFY_DATE,
	AUDIT_MODIFIED_BY,
	INVITATION_IDENTIFIER
	,'I'	IND_UPDATE
from	ODS_OWN.USER_INVITATION

&


/*-----------------------------------------------*/
/* TASK No. 11 */
/* Analyze integration table */



begin
    dbms_stats.gather_table_stats(
	ownname => 'RAX_APP_USER',
	tabname => 'I$_USER_INVITATION',
	estimate_percent => dbms_stats.auto_sample_size
    );
end;



&


/*-----------------------------------------------*/
/* TASK No. 12 */
/* Create Index on flow table */

create index	RAX_APP_USER.I$_USER_INVITATION_IDX
on		RAX_APP_USER.I$_USER_INVITATION (USER_INVITATION_OID)
NOLOGGING

&


/*-----------------------------------------------*/
/* TASK No. 13 */
/* drop table SNP_CHECK_TAB */

drop table RAX_APP_USER.SNP_CHECK_TAB

&


/*-----------------------------------------------*/
/* TASK No. 14 */
/* create check table */


create table RAX_APP_USER.SNP_CHECK_TAB
(
	CATALOG_NAME	VARCHAR2(100 CHAR) NULL ,
	SCHEMA_NAME	VARCHAR2(100 CHAR) NULL ,
	RESOURCE_NAME	VARCHAR2(100 CHAR) NULL,
	FULL_RES_NAME	VARCHAR2(100 CHAR) NULL,
	ERR_TYPE		VARCHAR2(1 CHAR) NULL,
	ERR_MESS		VARCHAR2(250 CHAR) NULL ,
	CHECK_DATE	DATE NULL,
	ORIGIN		VARCHAR2(100 CHAR) NULL,
	CONS_NAME	VARCHAR2(35 CHAR) NULL,
	CONS_TYPE		VARCHAR2(2 CHAR) NULL,
	ERR_COUNT		NUMBER(10) NULL
)
	

&


/*-----------------------------------------------*/
/* TASK No. 15 */
/* delete previous check sum */

delete from	RAX_APP_USER.SNP_CHECK_TAB
where	SCHEMA_NAME	= 'ODS_OWN'
and	ORIGIN 		= '(1638001)ODS_Project.LOAD_USER_INVITATION_INT'
and	ERR_TYPE 		= 'F'


&

/*-----------------------------------------------*/
/* TASK No. 16 */
/* drop error table */

drop table RAX_APP_USER.E$_USER_INVITATION


&


/*-----------------------------------------------*/
/* TASK No. 16 */
/* create error table */

BEGIN  
   EXECUTE IMMEDIATE 'create table RAX_APP_USER.E$_USER_INVITATION
(
	ODI_ROW_ID 		UROWID,
	ODI_ERR_TYPE		VARCHAR2(1 CHAR) NULL, 
	ODI_ERR_MESS		VARCHAR2(250 CHAR) NULL,
	ODI_CHECK_DATE	DATE NULL, 
	USER_INVITATION_OID	NUMBER NULL,
	USER_ACCOUNT_PRINCIPAL_OID	NUMBER NULL,
	EXPIRATION_DATE	DATE NULL,
	PROFILE_EMAIL_ADDRESS	VARCHAR2(255) NULL,
	AUDIT_CREATE_DATE	TIMESTAMP(6) NULL,
	AUDIT_CREATED_BY	VARCHAR2(255) NULL,
	AUDIT_MODIFY_DATE	TIMESTAMP(6) NULL,
	AUDIT_MODIFIED_BY	VARCHAR2(255) NULL,
	ODS_CREATE_DATE	DATE NULL,
	ODS_MODIFY_DATE	DATE NULL,
	INVITATION_IDENTIFIER	VARCHAR2(255) NULL,
	ODI_ORIGIN		VARCHAR2(100 CHAR) NULL,
	ODI_CONS_NAME	VARCHAR2(35 CHAR) NULL,
	ODI_CONS_TYPE		VARCHAR2(2 CHAR) NULL,
	ODI_PK			VARCHAR2(32 CHAR) PRIMARY KEY,
	ODI_SESS_NO		VARCHAR2(19 CHAR)
)';  
EXCEPTION  
   WHEN OTHERS THEN  
      NULL;
END;




&


/*-----------------------------------------------*/
/* TASK No. 17 */
/* delete previous errors */

delete from 	RAX_APP_USER.E$_USER_INVITATION
where	(ODI_ERR_TYPE = 'S'	and 'F' = 'S')
or	(ODI_ERR_TYPE = 'F'	and ODI_ORIGIN = '(1638001)ODS_Project.LOAD_USER_INVITATION_INT')


&


/*-----------------------------------------------*/
/* TASK No. 18 */
/* Create index on PK */

 
/* FLOW CONTROL CREATE THE iNDEX ON THE I$TABLE */

BEGIN
    EXECUTE IMMEDIATE 'CREATE INDEX RAX_APP_USER.I$_USER_INVITATION_IDX ON RAX_APP_USER.I$_USER_INVITATION (USER_INVITATION_OID)';
    DBMS_OUTPUT.PUT_LINE('Index created successfully.');
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE = -955 THEN
            DBMS_OUTPUT.PUT_LINE('Index already exists.');
        ELSE
            RAISE;
        END IF;
END;



&


/*-----------------------------------------------*/
/* TASK No. 19 */
/* insert PK errors */

insert into RAX_APP_USER.E$_USER_INVITATION
(
	ODI_PK,
	ODI_SESS_NO,
	ODI_ROW_ID,
	ODI_ERR_TYPE,
	ODI_ERR_MESS,
	ODI_ORIGIN,
	ODI_CHECK_DATE,
	ODI_CONS_NAME,
	ODI_CONS_TYPE,
	USER_INVITATION_OID,
	USER_ACCOUNT_PRINCIPAL_OID,
	EXPIRATION_DATE,
	PROFILE_EMAIL_ADDRESS,
	AUDIT_CREATE_DATE,
	AUDIT_CREATED_BY,
	AUDIT_MODIFY_DATE,
	AUDIT_MODIFIED_BY,
	ODS_CREATE_DATE,
	ODS_MODIFY_DATE,
	INVITATION_IDENTIFIER
)
select	SYS_GUID(),
	:v_sess_no, 
	rowid,
	'F', 
	'ODI-15064: The primary key USER_INVITATION_PK is not unique.',
	'(1638001)ODS_Project.LOAD_USER_INVITATION_INT',
	sysdate,
	'USER_INVITATION_PK',
	'PK',	
	USER_INVITATION.USER_INVITATION_OID,
	USER_INVITATION.USER_ACCOUNT_PRINCIPAL_OID,
	USER_INVITATION.EXPIRATION_DATE,
	USER_INVITATION.PROFILE_EMAIL_ADDRESS,
	USER_INVITATION.AUDIT_CREATE_DATE,
	USER_INVITATION.AUDIT_CREATED_BY,
	USER_INVITATION.AUDIT_MODIFY_DATE,
	USER_INVITATION.AUDIT_MODIFIED_BY,
	USER_INVITATION.ODS_CREATE_DATE,
	USER_INVITATION.ODS_MODIFY_DATE,
	USER_INVITATION.INVITATION_IDENTIFIER
from	RAX_APP_USER.I$_USER_INVITATION   USER_INVITATION
where	exists  (
		select	SUB.USER_INVITATION_OID
		from 	RAX_APP_USER.I$_USER_INVITATION SUB
		where 	SUB.USER_INVITATION_OID=USER_INVITATION.USER_INVITATION_OID
		group by 	SUB.USER_INVITATION_OID
		having 	count(1) > 1
		)



&


/*-----------------------------------------------*/
/* TASK No. 20 */
/* insert Not Null errors */

insert into RAX_APP_USER.E$_USER_INVITATION
(
	ODI_PK,
	ODI_SESS_NO,
	ODI_ROW_ID,
	ODI_ERR_TYPE,
	ODI_ERR_MESS,
	ODI_CHECK_DATE,
	ODI_ORIGIN,
	ODI_CONS_NAME,
	ODI_CONS_TYPE,
	USER_INVITATION_OID,
	USER_ACCOUNT_PRINCIPAL_OID,
	EXPIRATION_DATE,
	PROFILE_EMAIL_ADDRESS,
	AUDIT_CREATE_DATE,
	AUDIT_CREATED_BY,
	AUDIT_MODIFY_DATE,
	AUDIT_MODIFIED_BY,
	ODS_CREATE_DATE,
	ODS_MODIFY_DATE,
	INVITATION_IDENTIFIER
)
select
	SYS_GUID(),
	:v_sess_no, 
	rowid,
	'F', 
	'ODI-15066: The column USER_INVITATION_OID cannot be null.',
	sysdate,
	'(1638001)ODS_Project.LOAD_USER_INVITATION_INT',
	'USER_INVITATION_OID',
	'NN',	
	USER_INVITATION_OID,
	USER_ACCOUNT_PRINCIPAL_OID,
	EXPIRATION_DATE,
	PROFILE_EMAIL_ADDRESS,
	AUDIT_CREATE_DATE,
	AUDIT_CREATED_BY,
	AUDIT_MODIFY_DATE,
	AUDIT_MODIFIED_BY,
	ODS_CREATE_DATE,
	ODS_MODIFY_DATE,
	INVITATION_IDENTIFIER
from	RAX_APP_USER.I$_USER_INVITATION
where	USER_INVITATION_OID is null



&


/*-----------------------------------------------*/
/* TASK No. 21 */
/* create index on error table */

 
/* FLOW CONTROL CREATE INDEX ON THE E$TABLE */
BEGIN
    EXECUTE IMMEDIATE 'CREATE INDEX RAX_APP_USER.E$_USER_INVITATION_IDX ON RAX_APP_USER.E$_USER_INVITATION (ODI_ROW_ID)';
    DBMS_OUTPUT.PUT_LINE('Index created successfully.');
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE = -955 THEN
            DBMS_OUTPUT.PUT_LINE('Index already exists.');
        ELSE
            RAISE;
        END IF;
END; 

&


/*-----------------------------------------------*/
/* TASK No. 22 */
/* delete errors from controlled table */

delete from	RAX_APP_USER.I$_USER_INVITATION  T
where	exists 	(
		select	1
		from	RAX_APP_USER.E$_USER_INVITATION E
		where ODI_SESS_NO = :v_sess_no
		and T.rowid = E.ODI_ROW_ID
		)


&


/*-----------------------------------------------*/
/* TASK No. 23 */
/* insert check sum into check table */

insert into RAX_APP_USER.SNP_CHECK_TAB
(
	SCHEMA_NAME,
	RESOURCE_NAME,
	FULL_RES_NAME,
	ERR_TYPE,
	ERR_MESS,
	CHECK_DATE,
	ORIGIN,
	CONS_NAME,
	CONS_TYPE,
	ERR_COUNT
)
select	
	'ODS_OWN',
	'USER_INVITATION',
	'ODS_OWN.USER_INVITATION',
	E.ODI_ERR_TYPE,
	E.ODI_ERR_MESS,
	E.ODI_CHECK_DATE,
	E.ODI_ORIGIN,
	E.ODI_CONS_NAME,
	E.ODI_CONS_TYPE,
	count(1) 
from	RAX_APP_USER.E$_USER_INVITATION E
where	E.ODI_ERR_TYPE	= 'F'
and	E.ODI_ORIGIN 	= '(1638001)ODS_Project.LOAD_USER_INVITATION_INT'
group by	E.ODI_ERR_TYPE,
	E.ODI_ERR_MESS,
	E.ODI_CHECK_DATE,
	E.ODI_ORIGIN,
	E.ODI_CONS_NAME,
	E.ODI_CONS_TYPE


&


/*-----------------------------------------------*/
/* TASK No. 24 */
/* Merge Rows */

merge into	ODS_OWN.USER_INVITATION T
using	RAX_APP_USER.I$_USER_INVITATION S
on	(
		T.USER_INVITATION_OID=S.USER_INVITATION_OID
	)
when matched
then update set
	T.USER_ACCOUNT_PRINCIPAL_OID	= S.USER_ACCOUNT_PRINCIPAL_OID,
	T.EXPIRATION_DATE	= S.EXPIRATION_DATE,
	T.PROFILE_EMAIL_ADDRESS	= S.PROFILE_EMAIL_ADDRESS,
	T.AUDIT_CREATE_DATE	= S.AUDIT_CREATE_DATE,
	T.AUDIT_CREATED_BY	= S.AUDIT_CREATED_BY,
	T.AUDIT_MODIFY_DATE	= S.AUDIT_MODIFY_DATE,
	T.AUDIT_MODIFIED_BY	= S.AUDIT_MODIFIED_BY,
	T.INVITATION_IDENTIFIER	= S.INVITATION_IDENTIFIER
	,        T.ODS_MODIFY_DATE	= sysdate
when not matched
then insert
	(
	T.USER_INVITATION_OID,
	T.USER_ACCOUNT_PRINCIPAL_OID,
	T.EXPIRATION_DATE,
	T.PROFILE_EMAIL_ADDRESS,
	T.AUDIT_CREATE_DATE,
	T.AUDIT_CREATED_BY,
	T.AUDIT_MODIFY_DATE,
	T.AUDIT_MODIFIED_BY,
	T.INVITATION_IDENTIFIER
	,         T.ODS_CREATE_DATE,
	T.ODS_MODIFY_DATE
	)
values
	(
	S.USER_INVITATION_OID,
	S.USER_ACCOUNT_PRINCIPAL_OID,
	S.EXPIRATION_DATE,
	S.PROFILE_EMAIL_ADDRESS,
	S.AUDIT_CREATE_DATE,
	S.AUDIT_CREATED_BY,
	S.AUDIT_MODIFY_DATE,
	S.AUDIT_MODIFIED_BY,
	S.INVITATION_IDENTIFIER
	,         sysdate,
	sysdate
	)

&


/*-----------------------------------------------*/
/* TASK No. 25 */
/* Commit transaction */

/*commit*/


/*-----------------------------------------------*/
/* TASK No. 26 */
/* Drop flow table */

drop table RAX_APP_USER.I$_USER_INVITATION 

&


/*-----------------------------------------------*/
/* TASK No. 27 */
/* Update CDC Load Status */

UPDATE ODS_OWN.ODS_CDC_LOAD_STATUS
SET LAST_CDC_COMPLETION_DATE=TO_DATE(
             SUBSTR(:v_sess_beg, 1, 19), 'RRRR-MM-DD HH24:MI:SS')
+ nvl((TIMEZONE_OFFSET/24), 0) 
WHERE ODS_TABLE_NAME=:v_cdc_load_table_name
AND CONTEXT_NAME = :v_env

/*
UPDATE ODS_OWN.ODS_CDC_LOAD_STATUS
SET LAST_CDC_COMPLETION_DATE=TO_DATE(
             SUBSTR(:v_sess_beg, 1, 19), 'RRRR-MM-DD HH24:MI:SS')
WHERE ODS_TABLE_NAME=:v_cdc_load_table_name
AND CONTEXT_NAME = :v_env
*/

&


/*-----------------------------------------------*/
/* TASK No. 28 */
/* Insert CDC Audit Record */

INSERT INTO RAX_APP_USER.ODS_CDC_LOAD_STATUS_AUDIT
(TABLE_NAME,
SESS_NO,                      
SESS_NAME,                    
SCEN_VERSION,                 
SESS_BEG,                     
ORIG_LAST_CDC_COMPLETION_DATE,
OVERLAP,
CREATE_DATE,
CONTEXT_NAME,
TIMEZONE_OFFSET              
)
select 
:v_cdc_load_table_name
,:v_sess_no
,'LOAD_INVITATION_PKG'
,'005'
,TO_DATE(SUBSTR(:v_sess_beg, 1, 19), 'RRRR-MM-DD HH24:MI:SS')
,TO_DATE (SUBSTR(:v_cdc_load_date, 1, 19),'YYYY-MM-DD HH24:MI:SS')
,:v_cdc_overlap
,SYSDATE
,:v_env
,TIMEZONE_OFFSET
from 
ODS_OWN.ODS_CDC_LOAD_STATUS
WHERE ODS_TABLE_NAME=:v_cdc_load_table_name
AND CONTEXT_NAME = :v_env

/*
INSERT INTO RAX_APP_USER.ODS_CDC_LOAD_STATUS_AUDIT
(TABLE_NAME,
SESS_NO,                      
SESS_NAME,                    
SCEN_VERSION,                 
SESS_BEG,                     
ORIG_LAST_CDC_COMPLETION_DATE,
OVERLAP,
CREATE_DATE,
CONTEXT_NAME              
)
values (
:v_cdc_load_table_name,
:v_sess_no,
'LOAD_INVITATION_PKG',
'005',
TO_DATE(
             SUBSTR(:v_sess_beg, 1, 19), 'RRRR-MM-DD HH24:MI:SS'),
TO_DATE (SUBSTR (:v_cdc_load_date, 1, 19),
                           'YYYY-MM-DD HH24:MI:SS'
                          )
,:v_cdc_overlap,
SYSDATE,
 :v_env)
*/


&


/*-----------------------------------------------*/
