select 	
	NON_NSS_CODE.BEGIN_DATE	   BEGIN_DATE,
	NON_NSS_CODE.END_DATE	   END_DATE,
	NON_NSS_CODE.EVENT_PAYMENT_OID	   EVENT_PAYMENT_OID,
	NON_NSS_CODE.SRMENABLED	   SRMENABLED,
	NON_NSS_CODE.COUNTRY	   COUNTRY,
	NON_NSS_CODE.BANKCODE	   BANKCODE,
	NON_NSS_CODE.SCHOOLNAME	   SCHOOLNAME,
	NON_NSS_CODE.YBJOBNUMBER	   YBJOBNUMBER,
	NON_NSS_CODE.AMOUNT	   AMOUNT,
	NON_NSS_CODE.USERID	   USERID,
	NON_NSS_CODE.DEPOSITDATE	   DEPOSITDATE,
	NON_NSS_CODE.POSTEDDATE	   POSTEDDATE,
	NON_NSS_CODE.LID	   LID
from	RAX_APP_USER.NON_NSS_CODE   NON_NSS_CODE
where	
	(1=1)	
	





/* Order the output by the UD1, UD2, UD3, UD4, UD5, UD6 Fields. */
 
ORDER BY  DEPOSITDATE
, BANKCODE