select 	
	NSS_CODE.BEGIN_DATE	   BEGIN_DATE,
	NSS_CODE.END_DATE	   END_DATE,
	NSS_CODE.EVENT_PAYMENT_OID	   EVENT_PAYMENT_OID,
	NSS_CODE.SRMENABLED	   SRMENABLED,
	NSS_CODE.COUNTRY	   COUNTRY,
	NSS_CODE.BANKCODE	   BANKCODE,
	NSS_CODE.SCHOOLNAME	   SCHOOLNAME,
	NSS_CODE.YBJOBNUMBER	   YBJOBNUMBER,
	NSS_CODE.AMOUNT	   AMOUNT,
	NSS_CODE.USERID	   USERID,
	NSS_CODE.DEPOSITDATE	   DEPOSITDATE,
	NSS_CODE.POSTEDDATE	   POSTEDDATE,
	NSS_CODE.LID	   LID
from	RAX_APP_USER.NSS_CODE   NSS_CODE
where	
	(1=1)	
	





/* Order the output by the UD1, UD2, UD3, UD4, UD5, UD6 Fields. */
 
ORDER BY  DEPOSITDATE
, BANKCODE