select	
	JOB_BAG.ID	   C1_ID,
	JOB_BAG.VERSION	   C2_VERSION,
	JOB_BAG.JOB_NUMBER	   C3_JOB_NUMBER,
	JOB_BAG.CREATED_BY	   C4_CREATED_BY,
	JOB_BAG.UPDATED_BY	   C5_UPDATED_BY,
	JOB_BAG.DATE_CREATED	   C6_DATE_CREATED,
	JOB_BAG.LAST_UPDATED	   C7_LAST_UPDATED,
	JOB_BAG.EVENT_NAME	   C8_EVENT_NAME,
	JOB_BAG.PROCESSED_AT	   C9_PROCESSED_AT,
	JOB_BAG.RECEIVE_PROCESSED_AT	   C10_RECEIVE_PROCESSED_AT,
	JOB_BAG.TRACKING_NUMBER	   C11_TRACKING_NUMBER,
	JOB_BAG.JOB_BAG_STATUS	   C12_JOB_BAG_STATUS,
	JOB_BAG.CHECKED_IN_COMMENT	   C13_CHECKED_IN_COMMENT,
	JOB_BAG.CHECKED_OUT_COMMENT	   C14_CHECKED_OUT_COMMENT,
	JOB_BAG.CHECKED_IN	   C15_CHECKED_IN,
	JOB_BAG.CHECKED_OUT	   C16_CHECKED_OUT,
	JOB_BAG.TRACKING_COMMENTS	   C17_TRACKING_COMMENTS,
	JOB_BAG.CHECKED_IN_PHOTOGRAPHER	   C18_CHECKED_IN_PHOTOGRAPHER,
	JOB_BAG.CHECKED_OUT_PHOTOGRAPHER	   C19_CHECKED_OUT_PHOTOGRAPHER
from	<schema_name>.JOB_BAG   JOB_BAG
where	(1=1)
And (JOB_BAG.LAST_UPDATED >= TO_DATE(SUBSTR(:v_cdc_load_date, 1, 19), 'YYYY-MM-DD HH24:MI:SS')  -:v_cdc_oms_overlap)
