select	
	TAMPER_EVIDENT_DETAILS.ID	   C1_ID,
	TAMPER_EVIDENT_DETAILS.VERSION	   C2_VERSION,
	TAMPER_EVIDENT_DETAILS.COMMENTS	   C3_COMMENTS,
	TAMPER_EVIDENT_DETAILS.JOB_NUMBER	   C4_JOB_NUMBER,
	TAMPER_EVIDENT_DETAILS.PHOTOGRAPHY_ID	   C5_PHOTOGRAPHY_ID,
	TAMPER_EVIDENT_DETAILS.TE_BAGS	   C6_TE_BAGS,
	TAMPER_EVIDENT_DETAILS.STATUS	   C7_STATUS,
	TAMPER_EVIDENT_DETAILS.CREATED_BY	   C8_CREATED_BY,
	TAMPER_EVIDENT_DETAILS.UPDATED_BY	   C9_UPDATED_BY,
	TAMPER_EVIDENT_DETAILS.DATE_CREATED	   C10_DATE_CREATED,
	TAMPER_EVIDENT_DETAILS.LAST_UPDATED	   C11_LAST_UPDATED,
	TAMPER_EVIDENT_DETAILS.EVENT_NAME	   C12_EVENT_NAME,
	TAMPER_EVIDENT_DETAILS.TRACKING_NUMBER	   C13_TRACKING_NUMBER
from	<schema_name>.TAMPER_EVIDENT_DETAILS   TAMPER_EVIDENT_DETAILS
where	(1=1)
And (TAMPER_EVIDENT_DETAILS.LAST_UPDATED >= TO_DATE(SUBSTR(:v_cdc_load_date, 1, 19), 'YYYY-MM-DD HH24:MI:SS')  -:v_cdc_oms_overlap)


