DECLARE create_query CLOB;  
   BEGIN  
      BEGIN  
         EXECUTE IMMEDIATE 'drop table RAX_APP_USER.C$_0BTA_JOB_BAG_STG purge';  
      EXCEPTION  
         WHEN OTHERS THEN NULL;  
      END;  
      create_query := 'create table RAX_APP_USER.C$_0BTA_JOB_BAG_STG(C1_ID	NUMBER(19) NULL, C2_VERSION	NUMBER(19) NULL, C3_JOB_NUMBER	VARCHAR2(255) NULL, C4_CREATED_BY	VARCHAR2(255) NULL, C5_UPDATED_BY	VARCHAR2(255) NULL, C6_DATE_CREATED	DATE NULL, C7_LAST_UPDATED	DATE NULL, C8_EVENT_NAME	VARCHAR2(255) NULL, C9_PROCESSED_AT	VARCHAR2(255) NULL, C10_RECEIVE_PROCESSED_AT	VARCHAR2(255) NULL, C11_TRACKING_NUMBER	VARCHAR2(255) NULL, C12_JOB_BAG_STATUS	VARCHAR2(255) NULL, C13_CHECKED_IN_COMMENT	VARCHAR2(255) NULL, C14_CHECKED_OUT_COMMENT	VARCHAR2(255) NULL, C15_CHECKED_IN	DATE NULL, C16_CHECKED_OUT	DATE NULL, C17_TRACKING_COMMENTS	VARCHAR2(255) NULL, C18_CHECKED_IN_PHOTOGRAPHER	VARCHAR2(255) NULL, C19_CHECKED_OUT_PHOTOGRAPHER	VARCHAR2(255) NULL)';
      EXECUTE IMMEDIATE create_query;  
   END;  

