DECLARE create_query CLOB;  
   BEGIN  
      BEGIN  
         EXECUTE IMMEDIATE 'drop table RAX_APP_USER.C$_0BTA_TMPR_EVID_DETS_STG purge';  
      EXCEPTION  
         WHEN OTHERS THEN NULL;  
      END;  
      create_query := 'create table RAX_APP_USER.C$_0BTA_TMPR_EVID_DETS_STG(C1_ID	NUMBER(19) NULL, C2_VERSION	NUMBER(19) NULL,	C3_COMMENTS	VARCHAR2(255) NULL, C4_JOB_NUMBER	VARCHAR2(255) NULL, C5_PHOTOGRAPHY_ID	VARCHAR2(255) NULL, C6_TE_BAGS	VARCHAR2(255) NULL, C7_STATUS	VARCHAR2(50) NULL, C8_CREATED_BY	VARCHAR2(255) NULL, C9_UPDATED_BY	VARCHAR2(255) NULL, C10_DATE_CREATED	DATE NULL, C11_LAST_UPDATED	DATE NULL, C12_EVENT_NAME	VARCHAR2(255) NULL, C13_TRACKING_NUMBER	VARCHAR2(255) NULL)';
      EXECUTE IMMEDIATE create_query;  
   END;  

