select	
	ITEM_ELIGIBILITY.ITEM_ID	   C1_ITEM_ID,
	ITEM_ELIGIBILITY.SHUTTERFLY_ELIGIBLE	   C2_SHUTTERFLY_ELIGIBLE,
	ITEM_ELIGIBILITY.AUDIT_CREATE_DATE	   C3_AUDIT_CREATE_DATE,
	ITEM_ELIGIBILITY.AUDIT_MODIFIED_DATE	   C4_AUDIT_MODIFIED_DATE,
	ITEM_ELIGIBILITY.AUDIT_CREATE_BY	   C5_AUDIT_CREATE_BY,
	ITEM_ELIGIBILITY.AUDIT_MODIFIED_BY	   C6_AUDIT_MODIFIED_BY,
	ITEM_ELIGIBILITY.ADMINISTRATIVE_TYPE	   C7_ADMINISTRATIVE_TYPE,
	ITEM_ELIGIBILITY.EXCLUDE_FROM_SHIPMENT_TRIGGER	   C8_EXCLUDE_FROM_SHIPMENT_TRIGG,
	ITEM_ELIGIBILITY.ALL_LOOKS_SHUTTERFLY_ELIGIBLE	   C9_ALL_LOOKS_SHUTTERFLY_ELIGIB
from	<schema_name>.ITEM_ELIGIBILITY   ITEM_ELIGIBILITY
where	(1=1)
And (ITEM_ELIGIBILITY.AUDIT_MODIFIED_DATE >= TO_DATE(SUBSTR(:v_cdc_load_date, 1, 19), 'YYYY-MM-DD HH24:MI:SS')  -:v_cdc_oms_overlap)
