select	
	ITEM_ELIGIBILITY_HISTORY.ITEM_ID	   C1_ITEM_ID,
	ITEM_ELIGIBILITY_HISTORY.SHUTTERFLY_ELIGIBLE	   C2_SHUTTERFLY_ELIGIBLE,
	ITEM_ELIGIBILITY_HISTORY.AUDIT_MODIFIED_BY	   C3_AUDIT_MODIFIED_BY,
	ITEM_ELIGIBILITY_HISTORY.AUDIT_MODIFIED_DATE	   C4_AUDIT_MODIFIED_DATE,
	ITEM_ELIGIBILITY_HISTORY.ADMINISTRATIVE_TYPE	   C5_ADMINISTRATIVE_TYPE,
	ITEM_ELIGIBILITY_HISTORY.EXCLUDE_FROM_SHIPMENT_TRIGGER	   C6_EXCLUDE_FROM_SHIPMENT_TRIGG,
	ITEM_ELIGIBILITY_HISTORY.ALL_LOOKS_SHUTTERFLY_ELIGIBLE	   C7_ALL_LOOKS_SHUTTERFLY_ELIGIB
from	<schema_name>.ITEM_ELIGIBILITY_HISTORY   ITEM_ELIGIBILITY_HISTORY
where	(1=1)
And (ITEM_ELIGIBILITY_HISTORY.AUDIT_MODIFIED_DATE >= TO_DATE(SUBSTR(:v_cdc_load_date, 1, 19), 'YYYY-MM-DD HH24:MI:SS')  -:v_cdc_oms_overlap)


