select	
	MDP_ORDER.ORDER_ID	   C1_ORDER_ID,
	MDP_ORDER.SHIPMENT_ID	   C2_SHIPMENT_ID,
	MDP_ORDER.SOURCE	   C3_SOURCE,
	MDP_ORDER.ORDER_NO	   C4_ORDER_NO,
	MDP_ORDER.PROCESSING_START_TIME	   C5_PROCESSING_START_TIME,
	MDP_ORDER.PROCESSING_END_TIME	   C6_PROCESSING_END_TIME,
	MDP_ORDER.OUTCOME	   C7_OUTCOME,
	MDP_ORDER.AUDIT_CREATE_DATE	   C8_AUDIT_CREATE_DATE,
	MDP_ORDER.AUDIT_MODIFIED_DATE	   C9_AUDIT_MODIFIED_DATE,
	MDP_ORDER.VERSION	   C10_VERSION,
	MDP_ORDER.CUSTOMER_ORDER_MESSAGE_KEY	   C11_CUSTOMER_ORDER_MESSAGE_KEY,
	SHIPMENT.SHIPMENT_KEY	   C12_SHIPMENT_KEY
from	<schema_name>.MDP_ORDER   MDP_ORDER, <schema_name>.SHIPMENT   SHIPMENT
where	(1=1)
And (MDP_ORDER.AUDIT_MODIFIED_DATE >= TO_DATE(SUBSTR(:v_cdc_load_date, 1, 19), 'YYYY-MM-DD HH24:MI:SS')  -:v_cdc_oms_overlap)

 And (MDP_ORDER.SHIPMENT_ID=SHIPMENT.SHIPMENT_ID (+))