DECLARE create_query CLOB;  
   BEGIN  
      BEGIN  
         EXECUTE IMMEDIATE 'DROP TABLE RAX_APP_USER.C$_0MDP_ORDER_STG';  
      EXCEPTION  
         WHEN OTHERS THEN NULL;  
      END;  
      create_query := 'create table RAX_APP_USER.C$_0MDP_ORDER_STG
(
	C1_ORDER_ID	NUMBER NULL,
	C2_SHIPMENT_ID	NUMBER NULL,
	C3_SOURCE	VARCHAR2(255) NULL,
	C4_ORDER_NO	VARCHAR2(255) NULL,
	C5_PROCESSING_START_TIME	TIMESTAMP(6) NULL,
	C6_PROCESSING_END_TIME	TIMESTAMP(6) NULL,
	C7_OUTCOME	VARCHAR2(255) NULL,
	C8_AUDIT_CREATE_DATE	TIMESTAMP(6) NULL,
	C9_AUDIT_MODIFIED_DATE	TIMESTAMP(6) NULL,
	C10_VERSION	NUMBER NULL,
	C11_CUSTOMER_ORDER_MESSAGE_KEY	VARCHAR2(255) NULL,
	C12_SHIPMENT_KEY	VARCHAR2(255) NULL
)';  
      EXECUTE IMMEDIATE create_query;  
   END;  