DECLARE create_query CLOB;  
   BEGIN  
      BEGIN  
         EXECUTE IMMEDIATE 'DROP TABLE RAX_APP_USER.C$_0MDP_ITEM_ELIGIBILITY_STG';  
      EXCEPTION  
         WHEN OTHERS THEN NULL;  
      END;  
      create_query := 'create table RAX_APP_USER.C$_0MDP_ITEM_ELIGIBILITY_STG
(
	C1_ITEM_ID	VARCHAR2(64) NULL,
	C2_SHUTTERFLY_ELIGIBLE	NUMBER(1) NULL,
	C3_AUDIT_CREATE_DATE	DATE NULL,
	C4_AUDIT_MODIFIED_DATE	DATE NULL,
	C5_AUDIT_CREATE_BY	VARCHAR2(64) NULL,
	C6_AUDIT_MODIFIED_BY	VARCHAR2(64) NULL,
	C7_ADMINISTRATIVE_TYPE	VARCHAR2(255) NULL,
	C8_EXCLUDE_FROM_SHIPMENT_TRIGG	NUMBER(1) NULL,
	C9_ALL_LOOKS_SHUTTERFLY_ELIGIB	NUMBER(1) NULL
)';  
      EXECUTE IMMEDIATE create_query;  
   END;  