/* TASK No. 1 */

/* NONE or SET VARIABLE STATEMENT FOUND, CHECK ODI TASK NO. 1 */




/*-----------------------------------------------*/
/* TASK No. 2 */

/* SELECT STATEMENT FOUND, CHECK ODI TASK NO. 2 */




/*-----------------------------------------------*/
/* TASK No. 3 */

/* SELECT STATEMENT FOUND, CHECK ODI TASK NO. 3 */




/*-----------------------------------------------*/
/* TASK No. 4 */

/* SELECT STATEMENT FOUND, CHECK ODI TASK NO. 4 */




/*-----------------------------------------------*/
/* TASK No. 5 */

/* SELECT STATEMENT FOUND, CHECK ODI TASK NO. 5 */




/*-----------------------------------------------*/
/* TASK No. 6 */

/* SELECT STATEMENT FOUND, CHECK ODI TASK NO. 6 */




/*-----------------------------------------------*/
/* TASK No. 7 */

/* SELECT STATEMENT FOUND, CHECK ODI TASK NO. 7 */




/*-----------------------------------------------*/
/* TASK No. 8 */
/* Drop Temp Table */

drop table rax_app_user.monthly_ep_audit

&


/*-----------------------------------------------*/
/* TASK No. 9 */
/* Create and load temp table */

CREATE TABLE rax_app_user.monthly_ep_audit AS
SELECT EVENT_PAYMENT.EVENT_PAYMENT_OID,
       EVENT_PAYMENT.PAYMENT_DATE,
       EVENT.LIFETOUCH_ID,
       EVENT.EVENT_REF_ID,
       SUB_PROGRAM.SUB_PROGRAM_NAME,
       EVENT_PAYMENT.SUBJECT_FIRST_NAME,
       EVENT_PAYMENT.SUBJECT_LAST_NAME,
       PAYMENT_TYPE.PAYMENT_CATEGORY,
       EVENT_PAYMENT.PAYMENT_AMOUNT,
       ORDER_HEADER.TAX     AS SRM_TAX,
       ORDER_HEADER.OMS_TAX,
       ORDER_HEADER.TAX_EXEMPT_FLAG
  FROM ODS_OWN.EVENT_PAYMENT  EVENT_PAYMENT,
       ODS_OWN.EVENT          EVENT,
       ODS_OWN.APO            APO,
       ODS_OWN.SUB_PROGRAM    SUB_PROGRAM,
       ODS_OWN.PAYMENT_TYPE   PAYMENT_TYPE,
       ODS_OWN.ORDER_HEADER   ORDER_HEADER
 WHERE     (EVENT_PAYMENT.PAYMENT_DATE  BETWEEN TRUNC (TRUNC (SYSDATE, 'MM') - 1, 'MM')
                                 AND TRUNC (SYSDATE, 'MM') - 1)
       AND (PAYMENT_TYPE.PAYMENT_CATEGORY not IN ('CreditCard', 'Paypal','Venmo'))
       AND (EVENT_PAYMENT.PAYMENT_AMOUNT != 0)
       AND (EVENT_PAYMENT.EVENT_OID = EVENT.EVENT_OID)
       AND (EVENT.APO_OID = APO.APO_OID)
       AND (APO.SUB_PROGRAM_OID = SUB_PROGRAM.SUB_PROGRAM_OID)
       AND (EVENT_PAYMENT.PAYMENT_TYPE_OID =
            PAYMENT_TYPE.PAYMENT_TYPE_OID(+))
       AND (EVENT_PAYMENT.ORDER_HEADER_OID =
            ORDER_HEADER.ORDER_HEADER_OID(+))

&


/*-----------------------------------------------*/
/* TASK No. 10 */

/* SELECT STATEMENT FOUND, CHECK ODI TASK NO. 10 */




/*-----------------------------------------------*/
/* TASK No. 11 */

/* NONE or SET VARIABLE STATEMENT FOUND, CHECK ODI TASK NO. 11 */




/*-----------------------------------------------*/
/* TASK No. 12 */

/* NONE or SET VARIABLE STATEMENT FOUND, CHECK ODI TASK NO. 12 */




/*-----------------------------------------------*/
/* TASK No. 13 */

/* NONE or SET VARIABLE STATEMENT FOUND, CHECK ODI TASK NO. 13 */




/*-----------------------------------------------*/
/* TASK No. 14 */

/* NONE or SET VARIABLE STATEMENT FOUND, CHECK ODI TASK NO. 14 */




/*-----------------------------------------------*/
/* TASK No. 15 */
/* Drop Temp Table */

drop table rax_app_user.monthly_ep_audit_num


&


/*-----------------------------------------------*/
/* TASK No. 16 */
/* Create and load temp table */

CREATE TABLE RAX_APP_USER.MONTHLY_EP_AUDIT_NUM
AS
SELECT EVENT_PAYMENT_OID,
       PAYMENT_DATE,
       LIFETOUCH_ID,
       EVENT_REF_ID,
       SUB_PROGRAM_NAME,
       SUBJECT_FIRST_NAME,
       SUBJECT_LAST_NAME,
       PAYMENT_CATEGORY,
       PAYMENT_AMOUNT,
       SRM_TAX,
       OMS_TAX,
       TAX_EXEMPT_FLAG
  FROM (SELECT EVENT_PAYMENT_OID,
               PAYMENT_DATE,
               LIFETOUCH_ID,
               EVENT_REF_ID,
               SUB_PROGRAM_NAME,
               SUBJECT_FIRST_NAME,
               SUBJECT_LAST_NAME,
               PAYMENT_CATEGORY,
               PAYMENT_AMOUNT,
               SRM_TAX,
               OMS_TAX,
               TAX_EXEMPT_FLAG,
               ROW_NUMBER () OVER (ORDER BY event_payment_oid)     r
          FROM RAX_APP_USER.MONTHLY_EP_AUDIT)
 WHERE r BETWEEN :v_ep_auditors_ctr AND :v_ep_auditors_ctr + :v_ep_dump_file_max - 1

&


/*-----------------------------------------------*/
/* TASK No. 17 */

OdiFileDelete "-DIR=//dw_export/PROD" "-FILE=MONTHLY_EP_AUDIT_NUM.csv" "-RECURSE=NO" "-CASESENS=YES" "-NOFILE_ERROR=NO"

&


/*-----------------------------------------------*/
/* TASK No. 18 */
/* Generate header */

create header	(EVENT_PAYMENT_OID,
	PAYMENT_DATE,
	LIFETOUCH_ID,
	EVENT_REF_ID,
	SUB_PROGRAM_NAME,
	SUBJECT_FIRST_NAME,
	SUBJECT_LAST_NAME,
	PAYMENT_CATEGORY,
	PAYMENT_AMOUNT,
	SRM_TAX,
	OMS_TAX,
	TAX_EXEMPT_FLAG)

/*$$SNPS_START_KEYSNP$CRDWG_TABLESNP$CRTABLE_NAME=EP_DUMP_FOR_AUDITORS.csvSNP$CRLOAD_FILE=/dw_export/PROD/EP_DUMP_FOR_AUDITORS.csvSNP$CRFILE_FORMAT=DSNP$CRFILE_SEP_FIELD=0x002cSNP$CRFILE_SEP_LINE=0x000D0x000ASNP$CRFILE_FIRST_ROW=0SNP$CRFILE_ENC_FIELD="SNP$CRFILE_DEC_SEP=SNP$CRSNP$CRDWG_COLSNP$CRCOL_NAME=EVENT_PAYMENT_OIDSNP$CRTYPE_NAME=STRINGSNP$CRORDER=1SNP$CRLENGTH=50SNP$CRPRECISION=50SNP$CRSNP$CRDWG_COLSNP$CRCOL_NAME=PAYMENT_DATESNP$CRTYPE_NAME=STRINGSNP$CRORDER=2SNP$CRLENGTH=50SNP$CRPRECISION=50SNP$CRSNP$CRDWG_COLSNP$CRCOL_NAME=LIFETOUCH_IDSNP$CRTYPE_NAME=STRINGSNP$CRORDER=3SNP$CRLENGTH=50SNP$CRPRECISION=50SNP$CRSNP$CRDWG_COLSNP$CRCOL_NAME=EVENT_REF_IDSNP$CRTYPE_NAME=STRINGSNP$CRORDER=4SNP$CRLENGTH=50SNP$CRPRECISION=50SNP$CRSNP$CRDWG_COLSNP$CRCOL_NAME=SUB_PROGRAM_NAMESNP$CRTYPE_NAME=STRINGSNP$CRORDER=5SNP$CRLENGTH=100SNP$CRPRECISION=50SNP$CRSNP$CRDWG_COLSNP$CRCOL_NAME=SUBJECT_FIRST_NAMESNP$CRTYPE_NAME=STRINGSNP$CRORDER=6SNP$CRLENGTH=100SNP$CRPRECISION=50SNP$CRSNP$CRDWG_COLSNP$CRCOL_NAME=SUBJECT_LAST_NAMESNP$CRTYPE_NAME=STRINGSNP$CRORDER=7SNP$CRLENGTH=100SNP$CRPRECISION=50SNP$CRSNP$CRDWG_COLSNP$CRCOL_NAME=PAYMENT_CATEGORYSNP$CRTYPE_NAME=STRINGSNP$CRORDER=8SNP$CRLENGTH=50SNP$CRPRECISION=50SNP$CRSNP$CRDWG_COLSNP$CRCOL_NAME=PAYMENT_AMOUNTSNP$CRTYPE_NAME=STRINGSNP$CRORDER=9SNP$CRLENGTH=50SNP$CRPRECISION=50SNP$CRSNP$CRDWG_COLSNP$CRCOL_NAME=SRM_TAXSNP$CRTYPE_NAME=STRINGSNP$CRORDER=10SNP$CRLENGTH=50SNP$CRPRECISION=50SNP$CRSNP$CRDWG_COLSNP$CRCOL_NAME=OMS_TAXSNP$CRTYPE_NAME=STRINGSNP$CRORDER=11SNP$CRLENGTH=50SNP$CRPRECISION=50SNP$CRSNP$CRDWG_COLSNP$CRCOL_NAME=TAX_EXEMPT_FLAGSNP$CRTYPE_NAME=STRINGSNP$CRORDER=12SNP$CRLENGTH=50SNP$CRPRECISION=50SNP$CR$$SNPS_END_KEY*/


&


/*-----------------------------------------------*/
/* TASK No. 19 */
/* Insert new rows */

/* SOURCE CODE */


select 	
	MONTHLY_EP_AUDIT_NUM.EVENT_PAYMENT_OID	   EVENT_PAYMENT_OID,
	MONTHLY_EP_AUDIT_NUM.PAYMENT_DATE	   PAYMENT_DATE,
	MONTHLY_EP_AUDIT_NUM.LIFETOUCH_ID	   LIFETOUCH_ID,
	MONTHLY_EP_AUDIT_NUM.EVENT_REF_ID	   EVENT_REF_ID,
	MONTHLY_EP_AUDIT_NUM.SUB_PROGRAM_NAME	   SUB_PROGRAM_NAME,
	MONTHLY_EP_AUDIT_NUM.SUBJECT_FIRST_NAME	   SUBJECT_FIRST_NAME,
	MONTHLY_EP_AUDIT_NUM.SUBJECT_LAST_NAME	   SUBJECT_LAST_NAME,
	MONTHLY_EP_AUDIT_NUM.PAYMENT_CATEGORY	   PAYMENT_CATEGORY,
	MONTHLY_EP_AUDIT_NUM.PAYMENT_AMOUNT	   PAYMENT_AMOUNT,
	MONTHLY_EP_AUDIT_NUM.SRM_TAX	   SRM_TAX,
	MONTHLY_EP_AUDIT_NUM.OMS_TAX	   OMS_TAX,
	MONTHLY_EP_AUDIT_NUM.TAX_EXEMPT_FLAG	   TAX_EXEMPT_FLAG
from	RAX_APP_USER.MONTHLY_EP_AUDIT_NUM   MONTHLY_EP_AUDIT_NUM
where	
	(1=1)	
	





/* Order the output by the UD1, UD2, UD3, UD4, UD5, UD6 Fields. */



&

/* TARGET CODE */
insert into "/dw_export/PROD/EP_DUMP_FOR_AUDITORS.csv"
(
	EVENT_PAYMENT_OID,
	PAYMENT_DATE,
	LIFETOUCH_ID,
	EVENT_REF_ID,
	SUB_PROGRAM_NAME,
	SUBJECT_FIRST_NAME,
	SUBJECT_LAST_NAME,
	PAYMENT_CATEGORY,
	PAYMENT_AMOUNT,
	SRM_TAX,
	OMS_TAX,
	TAX_EXEMPT_FLAG
                     
)
values 
(
	:EVENT_PAYMENT_OID,
	:PAYMENT_DATE,
	:LIFETOUCH_ID,
	:EVENT_REF_ID,
	:SUB_PROGRAM_NAME,
	:SUBJECT_FIRST_NAME,
	:SUBJECT_LAST_NAME,
	:PAYMENT_CATEGORY,
	:PAYMENT_AMOUNT,
	:SRM_TAX,
	:OMS_TAX,
	:TAX_EXEMPT_FLAG
                     
)
/*$$SNPS_START_KEYSNP$CRDWG_TABLESNP$CRTABLE_NAME=EP_DUMP_FOR_AUDITORS.csvSNP$CRLOAD_FILE=/dw_export/PROD/EP_DUMP_FOR_AUDITORS.csvSNP$CRFILE_FORMAT=DSNP$CRFILE_SEP_FIELD=0x002cSNP$CRFILE_SEP_LINE=0x000D0x000ASNP$CRFILE_FIRST_ROW=0SNP$CRFILE_ENC_FIELD="SNP$CRFILE_DEC_SEP=SNP$CRSNP$CRDWG_COLSNP$CRCOL_NAME=EVENT_PAYMENT_OIDSNP$CRTYPE_NAME=STRINGSNP$CRORDER=1SNP$CRLENGTH=50SNP$CRPRECISION=50SNP$CRSNP$CRDWG_COLSNP$CRCOL_NAME=PAYMENT_DATESNP$CRTYPE_NAME=STRINGSNP$CRORDER=2SNP$CRLENGTH=50SNP$CRPRECISION=50SNP$CRSNP$CRDWG_COLSNP$CRCOL_NAME=LIFETOUCH_IDSNP$CRTYPE_NAME=STRINGSNP$CRORDER=3SNP$CRLENGTH=50SNP$CRPRECISION=50SNP$CRSNP$CRDWG_COLSNP$CRCOL_NAME=EVENT_REF_IDSNP$CRTYPE_NAME=STRINGSNP$CRORDER=4SNP$CRLENGTH=50SNP$CRPRECISION=50SNP$CRSNP$CRDWG_COLSNP$CRCOL_NAME=SUB_PROGRAM_NAMESNP$CRTYPE_NAME=STRINGSNP$CRORDER=5SNP$CRLENGTH=100SNP$CRPRECISION=50SNP$CRSNP$CRDWG_COLSNP$CRCOL_NAME=SUBJECT_FIRST_NAMESNP$CRTYPE_NAME=STRINGSNP$CRORDER=6SNP$CRLENGTH=100SNP$CRPRECISION=50SNP$CRSNP$CRDWG_COLSNP$CRCOL_NAME=SUBJECT_LAST_NAMESNP$CRTYPE_NAME=STRINGSNP$CRORDER=7SNP$CRLENGTH=100SNP$CRPRECISION=50SNP$CRSNP$CRDWG_COLSNP$CRCOL_NAME=PAYMENT_CATEGORYSNP$CRTYPE_NAME=STRINGSNP$CRORDER=8SNP$CRLENGTH=50SNP$CRPRECISION=50SNP$CRSNP$CRDWG_COLSNP$CRCOL_NAME=PAYMENT_AMOUNTSNP$CRTYPE_NAME=STRINGSNP$CRORDER=9SNP$CRLENGTH=50SNP$CRPRECISION=50SNP$CRSNP$CRDWG_COLSNP$CRCOL_NAME=SRM_TAXSNP$CRTYPE_NAME=STRINGSNP$CRORDER=10SNP$CRLENGTH=50SNP$CRPRECISION=50SNP$CRSNP$CRDWG_COLSNP$CRCOL_NAME=OMS_TAXSNP$CRTYPE_NAME=STRINGSNP$CRORDER=11SNP$CRLENGTH=50SNP$CRPRECISION=50SNP$CRSNP$CRDWG_COLSNP$CRCOL_NAME=TAX_EXEMPT_FLAGSNP$CRTYPE_NAME=STRINGSNP$CRORDER=12SNP$CRLENGTH=50SNP$CRPRECISION=50SNP$CR$$SNPS_END_KEY*/



/*-----------------------------------------------*/
/* TASK No. 20 */

chmod 644 /dw_export/PROD/EP_DUMP_FOR_AUDITORS.csv

&


/*-----------------------------------------------*/
/* TASK No. 21 */

mv /dw_export/PROD/EP_DUMP_FOR_AUDITORS.csv /dw_export/PROD/finance/Audit/MONTHLY_CASH_CHECK-:v_ep_dump_file_num-:v_actuate_sysdate.csv


&


/*-----------------------------------------------*/
/* TASK No. 22 */

/* SELECT STATEMENT FOUND, CHECK ODI TASK NO. 22 */




/*-----------------------------------------------*/
/* TASK No. 23 */

/* NONE or SET VARIABLE STATEMENT FOUND, CHECK ODI TASK NO. 23 */




/*-----------------------------------------------*/
/* TASK No. 24 */

OdiSendMail "-MAILHOST=LTIVRS1.LIFETOUCH.NET" "-FROM=ODI_EMAIL-PROD@Lifetouch.com" "-SUBJECT=Monthly Cash/Check Payment Files for Auditors Created" "-TO=:v_error_email_to"
:v_ep_dump_file_num Monthly Cash/Check Payment File(s) Created in:

Path : \\sgsphnas02\lnss_dw_export\PROD\finance\Audit

To discontinue receiving this email, please submit a ticket to the Data Warehouse team.

&


/*-----------------------------------------------*/
/* TASK No. 25 */
/* Drop temp table */

drop table rax_app_user.monthly_ep_audit

&


/*-----------------------------------------------*/
/* TASK No. 26 */
/* Create and load temp table */

CREATE TABLE rax_app_user.monthly_ep_audit AS
SELECT EVENT_PAYMENT.EVENT_PAYMENT_OID,
       EVENT_PAYMENT.PAYMENT_DATE,
       EVENT.LIFETOUCH_ID,
       EVENT.EVENT_REF_ID,
       SUB_PROGRAM.SUB_PROGRAM_NAME,
       EVENT_PAYMENT.SUBJECT_FIRST_NAME,
       EVENT_PAYMENT.SUBJECT_LAST_NAME,
       PAYMENT_TYPE.PAYMENT_CATEGORY,
       EVENT_PAYMENT.PAYMENT_AMOUNT,
       ORDER_HEADER.TAX     AS SRM_TAX,
       ORDER_HEADER.OMS_TAX,
       ORDER_HEADER.TAX_EXEMPT_FLAG
  FROM ODS_OWN.EVENT_PAYMENT  EVENT_PAYMENT,
       ODS_OWN.EVENT          EVENT,
       ODS_OWN.APO            APO,
       ODS_OWN.SUB_PROGRAM    SUB_PROGRAM,
       ODS_OWN.PAYMENT_TYPE   PAYMENT_TYPE,
       ODS_OWN.ORDER_HEADER   ORDER_HEADER
 WHERE     (EVENT_PAYMENT.PAYMENT_DATE  BETWEEN TRUNC (TRUNC (SYSDATE, 'MM') - 1, 'MM')
                                 AND TRUNC (SYSDATE, 'MM') - 1)
       AND (PAYMENT_TYPE.PAYMENT_CATEGORY IN ('CreditCard', 'Paypal','Venmo'))
       AND (EVENT_PAYMENT.PAYMENT_AMOUNT != 0)
       AND (EVENT_PAYMENT.EVENT_OID = EVENT.EVENT_OID)
       AND (EVENT.APO_OID = APO.APO_OID)
       AND (APO.SUB_PROGRAM_OID = SUB_PROGRAM.SUB_PROGRAM_OID)
       AND (EVENT_PAYMENT.PAYMENT_TYPE_OID =
            PAYMENT_TYPE.PAYMENT_TYPE_OID(+))
       AND (EVENT_PAYMENT.ORDER_HEADER_OID =
            ORDER_HEADER.ORDER_HEADER_OID(+))

&


/*-----------------------------------------------*/
/* TASK No. 27 */

/* SELECT STATEMENT FOUND, CHECK ODI TASK NO. 27 */




/*-----------------------------------------------*/
/* TASK No. 28 */

/* NONE or SET VARIABLE STATEMENT FOUND, CHECK ODI TASK NO. 28 */




/*-----------------------------------------------*/
/* TASK No. 29 */

/* NONE or SET VARIABLE STATEMENT FOUND, CHECK ODI TASK NO. 29 */




/*-----------------------------------------------*/
/* TASK No. 30 */

/* NONE or SET VARIABLE STATEMENT FOUND, CHECK ODI TASK NO. 30 */




/*-----------------------------------------------*/
/* TASK No. 31 */

/* NONE or SET VARIABLE STATEMENT FOUND, CHECK ODI TASK NO. 31 */




/*-----------------------------------------------*/
/* TASK No. 32 */
/* Drop Temp Table */

drop table rax_app_user.monthly_ep_audit_num


&


/*-----------------------------------------------*/
/* TASK No. 33 */
/* Create and load temp table */

CREATE TABLE RAX_APP_USER.MONTHLY_EP_AUDIT_NUM
AS
SELECT EVENT_PAYMENT_OID,
       PAYMENT_DATE,
       LIFETOUCH_ID,
       EVENT_REF_ID,
       SUB_PROGRAM_NAME,
       SUBJECT_FIRST_NAME,
       SUBJECT_LAST_NAME,
       PAYMENT_CATEGORY,
       PAYMENT_AMOUNT,
       SRM_TAX,
       OMS_TAX,
       TAX_EXEMPT_FLAG
  FROM (SELECT EVENT_PAYMENT_OID,
               PAYMENT_DATE,
               LIFETOUCH_ID,
               EVENT_REF_ID,
               SUB_PROGRAM_NAME,
               SUBJECT_FIRST_NAME,
               SUBJECT_LAST_NAME,
               PAYMENT_CATEGORY,
               PAYMENT_AMOUNT,
               SRM_TAX,
               OMS_TAX,
               TAX_EXEMPT_FLAG,
               ROW_NUMBER () OVER (ORDER BY event_payment_oid)     r
          FROM RAX_APP_USER.MONTHLY_EP_AUDIT)
 WHERE r BETWEEN :v_ep_auditors_ctr AND :v_ep_auditors_ctr + :v_ep_dump_file_max - 1

&


/*-----------------------------------------------*/
/* TASK No. 34 */

OdiFileDelete "-DIR=//dw_export/PROD" "-FILE=MONTHLY_EP_AUDIT_NUM.csv" "-RECURSE=NO" "-CASESENS=YES" "-NOFILE_ERROR=NO"

&


/*-----------------------------------------------*/
/* TASK No. 35 */
/* Generate header */

create header	(EVENT_PAYMENT_OID,
	PAYMENT_DATE,
	LIFETOUCH_ID,
	EVENT_REF_ID,
	SUB_PROGRAM_NAME,
	SUBJECT_FIRST_NAME,
	SUBJECT_LAST_NAME,
	PAYMENT_CATEGORY,
	PAYMENT_AMOUNT,
	SRM_TAX,
	OMS_TAX,
	TAX_EXEMPT_FLAG)

/*$$SNPS_START_KEYSNP$CRDWG_TABLESNP$CRTABLE_NAME=EP_DUMP_FOR_AUDITORS.csvSNP$CRLOAD_FILE=/dw_export/PROD/EP_DUMP_FOR_AUDITORS.csvSNP$CRFILE_FORMAT=DSNP$CRFILE_SEP_FIELD=0x002cSNP$CRFILE_SEP_LINE=0x000D0x000ASNP$CRFILE_FIRST_ROW=0SNP$CRFILE_ENC_FIELD="SNP$CRFILE_DEC_SEP=SNP$CRSNP$CRDWG_COLSNP$CRCOL_NAME=EVENT_PAYMENT_OIDSNP$CRTYPE_NAME=STRINGSNP$CRORDER=1SNP$CRLENGTH=50SNP$CRPRECISION=50SNP$CRSNP$CRDWG_COLSNP$CRCOL_NAME=PAYMENT_DATESNP$CRTYPE_NAME=STRINGSNP$CRORDER=2SNP$CRLENGTH=50SNP$CRPRECISION=50SNP$CRSNP$CRDWG_COLSNP$CRCOL_NAME=LIFETOUCH_IDSNP$CRTYPE_NAME=STRINGSNP$CRORDER=3SNP$CRLENGTH=50SNP$CRPRECISION=50SNP$CRSNP$CRDWG_COLSNP$CRCOL_NAME=EVENT_REF_IDSNP$CRTYPE_NAME=STRINGSNP$CRORDER=4SNP$CRLENGTH=50SNP$CRPRECISION=50SNP$CRSNP$CRDWG_COLSNP$CRCOL_NAME=SUB_PROGRAM_NAMESNP$CRTYPE_NAME=STRINGSNP$CRORDER=5SNP$CRLENGTH=100SNP$CRPRECISION=50SNP$CRSNP$CRDWG_COLSNP$CRCOL_NAME=SUBJECT_FIRST_NAMESNP$CRTYPE_NAME=STRINGSNP$CRORDER=6SNP$CRLENGTH=100SNP$CRPRECISION=50SNP$CRSNP$CRDWG_COLSNP$CRCOL_NAME=SUBJECT_LAST_NAMESNP$CRTYPE_NAME=STRINGSNP$CRORDER=7SNP$CRLENGTH=100SNP$CRPRECISION=50SNP$CRSNP$CRDWG_COLSNP$CRCOL_NAME=PAYMENT_CATEGORYSNP$CRTYPE_NAME=STRINGSNP$CRORDER=8SNP$CRLENGTH=50SNP$CRPRECISION=50SNP$CRSNP$CRDWG_COLSNP$CRCOL_NAME=PAYMENT_AMOUNTSNP$CRTYPE_NAME=STRINGSNP$CRORDER=9SNP$CRLENGTH=50SNP$CRPRECISION=50SNP$CRSNP$CRDWG_COLSNP$CRCOL_NAME=SRM_TAXSNP$CRTYPE_NAME=STRINGSNP$CRORDER=10SNP$CRLENGTH=50SNP$CRPRECISION=50SNP$CRSNP$CRDWG_COLSNP$CRCOL_NAME=OMS_TAXSNP$CRTYPE_NAME=STRINGSNP$CRORDER=11SNP$CRLENGTH=50SNP$CRPRECISION=50SNP$CRSNP$CRDWG_COLSNP$CRCOL_NAME=TAX_EXEMPT_FLAGSNP$CRTYPE_NAME=STRINGSNP$CRORDER=12SNP$CRLENGTH=50SNP$CRPRECISION=50SNP$CR$$SNPS_END_KEY*/


&


/*-----------------------------------------------*/
/* TASK No. 36 */
/* Insert new rows */

/* SOURCE CODE */


select 	
	MONTHLY_EP_AUDIT_NUM.EVENT_PAYMENT_OID	   EVENT_PAYMENT_OID,
	MONTHLY_EP_AUDIT_NUM.PAYMENT_DATE	   PAYMENT_DATE,
	MONTHLY_EP_AUDIT_NUM.LIFETOUCH_ID	   LIFETOUCH_ID,
	MONTHLY_EP_AUDIT_NUM.EVENT_REF_ID	   EVENT_REF_ID,
	MONTHLY_EP_AUDIT_NUM.SUB_PROGRAM_NAME	   SUB_PROGRAM_NAME,
	MONTHLY_EP_AUDIT_NUM.SUBJECT_FIRST_NAME	   SUBJECT_FIRST_NAME,
	MONTHLY_EP_AUDIT_NUM.SUBJECT_LAST_NAME	   SUBJECT_LAST_NAME,
	MONTHLY_EP_AUDIT_NUM.PAYMENT_CATEGORY	   PAYMENT_CATEGORY,
	MONTHLY_EP_AUDIT_NUM.PAYMENT_AMOUNT	   PAYMENT_AMOUNT,
	MONTHLY_EP_AUDIT_NUM.SRM_TAX	   SRM_TAX,
	MONTHLY_EP_AUDIT_NUM.OMS_TAX	   OMS_TAX,
	MONTHLY_EP_AUDIT_NUM.TAX_EXEMPT_FLAG	   TAX_EXEMPT_FLAG
from	RAX_APP_USER.MONTHLY_EP_AUDIT_NUM   MONTHLY_EP_AUDIT_NUM
where	
	(1=1)	
	





/* Order the output by the UD1, UD2, UD3, UD4, UD5, UD6 Fields. */



&

/* TARGET CODE */
insert into "/dw_export/PROD/EP_DUMP_FOR_AUDITORS.csv"
(
	EVENT_PAYMENT_OID,
	PAYMENT_DATE,
	LIFETOUCH_ID,
	EVENT_REF_ID,
	SUB_PROGRAM_NAME,
	SUBJECT_FIRST_NAME,
	SUBJECT_LAST_NAME,
	PAYMENT_CATEGORY,
	PAYMENT_AMOUNT,
	SRM_TAX,
	OMS_TAX,
	TAX_EXEMPT_FLAG
                     
)
values 
(
	:EVENT_PAYMENT_OID,
	:PAYMENT_DATE,
	:LIFETOUCH_ID,
	:EVENT_REF_ID,
	:SUB_PROGRAM_NAME,
	:SUBJECT_FIRST_NAME,
	:SUBJECT_LAST_NAME,
	:PAYMENT_CATEGORY,
	:PAYMENT_AMOUNT,
	:SRM_TAX,
	:OMS_TAX,
	:TAX_EXEMPT_FLAG
                     
)
/*$$SNPS_START_KEYSNP$CRDWG_TABLESNP$CRTABLE_NAME=EP_DUMP_FOR_AUDITORS.csvSNP$CRLOAD_FILE=/dw_export/PROD/EP_DUMP_FOR_AUDITORS.csvSNP$CRFILE_FORMAT=DSNP$CRFILE_SEP_FIELD=0x002cSNP$CRFILE_SEP_LINE=0x000D0x000ASNP$CRFILE_FIRST_ROW=0SNP$CRFILE_ENC_FIELD="SNP$CRFILE_DEC_SEP=SNP$CRSNP$CRDWG_COLSNP$CRCOL_NAME=EVENT_PAYMENT_OIDSNP$CRTYPE_NAME=STRINGSNP$CRORDER=1SNP$CRLENGTH=50SNP$CRPRECISION=50SNP$CRSNP$CRDWG_COLSNP$CRCOL_NAME=PAYMENT_DATESNP$CRTYPE_NAME=STRINGSNP$CRORDER=2SNP$CRLENGTH=50SNP$CRPRECISION=50SNP$CRSNP$CRDWG_COLSNP$CRCOL_NAME=LIFETOUCH_IDSNP$CRTYPE_NAME=STRINGSNP$CRORDER=3SNP$CRLENGTH=50SNP$CRPRECISION=50SNP$CRSNP$CRDWG_COLSNP$CRCOL_NAME=EVENT_REF_IDSNP$CRTYPE_NAME=STRINGSNP$CRORDER=4SNP$CRLENGTH=50SNP$CRPRECISION=50SNP$CRSNP$CRDWG_COLSNP$CRCOL_NAME=SUB_PROGRAM_NAMESNP$CRTYPE_NAME=STRINGSNP$CRORDER=5SNP$CRLENGTH=100SNP$CRPRECISION=50SNP$CRSNP$CRDWG_COLSNP$CRCOL_NAME=SUBJECT_FIRST_NAMESNP$CRTYPE_NAME=STRINGSNP$CRORDER=6SNP$CRLENGTH=100SNP$CRPRECISION=50SNP$CRSNP$CRDWG_COLSNP$CRCOL_NAME=SUBJECT_LAST_NAMESNP$CRTYPE_NAME=STRINGSNP$CRORDER=7SNP$CRLENGTH=100SNP$CRPRECISION=50SNP$CRSNP$CRDWG_COLSNP$CRCOL_NAME=PAYMENT_CATEGORYSNP$CRTYPE_NAME=STRINGSNP$CRORDER=8SNP$CRLENGTH=50SNP$CRPRECISION=50SNP$CRSNP$CRDWG_COLSNP$CRCOL_NAME=PAYMENT_AMOUNTSNP$CRTYPE_NAME=STRINGSNP$CRORDER=9SNP$CRLENGTH=50SNP$CRPRECISION=50SNP$CRSNP$CRDWG_COLSNP$CRCOL_NAME=SRM_TAXSNP$CRTYPE_NAME=STRINGSNP$CRORDER=10SNP$CRLENGTH=50SNP$CRPRECISION=50SNP$CRSNP$CRDWG_COLSNP$CRCOL_NAME=OMS_TAXSNP$CRTYPE_NAME=STRINGSNP$CRORDER=11SNP$CRLENGTH=50SNP$CRPRECISION=50SNP$CRSNP$CRDWG_COLSNP$CRCOL_NAME=TAX_EXEMPT_FLAGSNP$CRTYPE_NAME=STRINGSNP$CRORDER=12SNP$CRLENGTH=50SNP$CRPRECISION=50SNP$CR$$SNPS_END_KEY*/



/*-----------------------------------------------*/
/* TASK No. 37 */

chmod 644 /dw_export/PROD/EP_DUMP_FOR_AUDITORS.csv

&


/*-----------------------------------------------*/
/* TASK No. 38 */

mv /dw_export/PROD/EP_DUMP_FOR_AUDITORS.csv /dw_export/PROD/finance/Audit/MONTHLY_CREDIT-:v_ep_dump_file_num-:v_actuate_sysdate.csv


&


/*-----------------------------------------------*/
/* TASK No. 39 */

/* SELECT STATEMENT FOUND, CHECK ODI TASK NO. 39 */




/*-----------------------------------------------*/
/* TASK No. 40 */

/* NONE or SET VARIABLE STATEMENT FOUND, CHECK ODI TASK NO. 40 */




/*-----------------------------------------------*/
/* TASK No. 41 */

OdiSendMail "-MAILHOST=LTIVRS1.LIFETOUCH.NET" "-FROM=ODI_EMAIL-PROD@Lifetouch.com" "-SUBJECT=Monthly Credit Card/PayPal/Venmo Payment Files for Auditors Created" "-TO=:v_error_email_to"
:v_ep_dump_file_num Monthly Credit Card/PayPal/Venmo Payment File(s) Created in:

Path : \\sgsphnas02\lnss_dw_export\PROD\finance\Audit

To discontinue receiving this email, please submit a ticket to the Data Warehouse team.

&


/*-----------------------------------------------*/
/* TASK No. 42 */
/* Update CDC Load Status */

UPDATE ODS_OWN.ODS_CDC_LOAD_STATUS
SET LAST_CDC_COMPLETION_DATE=TO_DATE(
             SUBSTR(:v_sess_beg, 1, 19), 'RRRR-MM-DD HH24:MI:SS')
+ nvl((TIMEZONE_OFFSET/24), 0) 
WHERE ODS_TABLE_NAME=:v_cdc_load_table_name
AND CONTEXT_NAME = :v_env


&


/*-----------------------------------------------*/
/* TASK No. 43 */
/* Insert CDC Audit Record */

INSERT INTO RAX_APP_USER.ODS_CDC_LOAD_STATUS_AUDIT
(TABLE_NAME,
SESS_NO,                      
SESS_NAME,                    
SCEN_VERSION,                 
SESS_BEG,                     
ORIG_LAST_CDC_COMPLETION_DATE,
OVERLAP,
CREATE_DATE,              
CONTEXT_NAME,
TIMEZONE_OFFSET              
)
select 
:v_cdc_load_table_name
,:v_sess_no
,'99_PAYMENTS_FOR_AUDITORS_PKG'
,'004'
,TO_DATE(SUBSTR(:v_sess_beg, 1, 19), 'RRRR-MM-DD HH24:MI:SS')
,TO_DATE (SUBSTR(:v_cdc_load_date, 1, 19),'YYYY-MM-DD HH24:MI:SS')
,:v_cdc_overlap
,SYSDATE
,:v_env
,TIMEZONE_OFFSET
from 
ODS_OWN.ODS_CDC_LOAD_STATUS
WHERE ODS_TABLE_NAME=:v_cdc_load_table_name
AND CONTEXT_NAME = :v_env


&


/*-----------------------------------------------*/
