


select 	
	MONTHLY_EP_AUDIT_NUM.EVENT_PAYMENT_OID	   EVENT_PAYMENT_OID,
	MONTHLY_EP_AUDIT_NUM.PAYMENT_DATE	   PAYMENT_DATE,
	MONTHLY_EP_AUDIT_NUM.LIFETOUCH_ID	   LIFETOUCH_ID,
	MONTHLY_EP_AUDIT_NUM.EVENT_REF_ID	   EVENT_REF_ID,
	MONTHLY_EP_AUDIT_NUM.SUB_PROGRAM_NAME	   SUB_PROGRAM_NAME,
	MONTHLY_EP_AUDIT_NUM.SUBJECT_FIRST_NAME	   SUBJECT_FIRST_NAME,
	MONTHLY_EP_AUDIT_NUM.SUBJECT_LAST_NAME	   SUBJECT_LAST_NAME,
	MONTHLY_EP_AUDIT_NUM.PAYMENT_CATEGORY	   PAYMENT_CATEGORY,
	MONTHLY_EP_AUDIT_NUM.PAYMENT_AMOUNT	   PAYMENT_AMOUNT,
	MONTHLY_EP_AUDIT_NUM.SRM_TAX	   SRM_TAX,
	MONTHLY_EP_AUDIT_NUM.OMS_TAX	   OMS_TAX,
	MONTHLY_EP_AUDIT_NUM.TAX_EXEMPT_FLAG	   TAX_EXEMPT_FLAG
from	RAX_APP_USER.MONTHLY_EP_AUDIT_NUM   MONTHLY_EP_AUDIT_NUM
where	
	(1=1)	

	