select	
	LT_CHILD_ORDER_INFO.CHILD_ORDER_INFO_KEY	   C1_CHILD_ORDER_INFO_KEY,
	LT_CHILD_ORDER_INFO.PARENT_ORDER_HEADER_KEY	   C2_PARENT_ORDER_HEADER_KEY,
	LT_CHILD_ORDER_INFO.PARENT_ORDER_LINE_KEY	   C3_PARENT_ORDER_LINE_KEY,
	LT_CHILD_ORDER_INFO.STATUS	   C4_STATUS,
	LT_CHILD_ORDER_INFO.MULTIPLICITY	   C5_MULTIPLICITY,
	LT_CHILD_ORDER_INFO.ROLE_INFO	   C6_ROLE_INFO,
	LT_CHILD_ORDER_INFO.GROUP_INFO	   C7_GROUP_INFO,
	LT_CHILD_ORDER_INFO.TOTAL_CHILD_ORDERS	   C8_TOTAL_CHILD_ORDERS,
	LT_CHILD_ORDER_INFO.SUBJECT_COUNT	   C9_SUBJECT_COUNT,
	LT_CHILD_ORDER_INFO.ITEM_ID	   C10_ITEM_ID,
	LT_CHILD_ORDER_INFO.AVAILABLE_DATE	   C11_AVAILABLE_DATE,
	LT_CHILD_ORDER_INFO.CREATETS	   C12_CREATETS,
	LT_CHILD_ORDER_INFO.MODIFYTS	   C13_MODIFYTS,
	LT_CHILD_ORDER_INFO.CREATEUSERID	   C14_CREATEUSERID,
	LT_CHILD_ORDER_INFO.MODIFYUSERID	   C15_MODIFYUSERID,
	LT_CHILD_ORDER_INFO.CREATEPROGID	   C16_CREATEPROGID,
	LT_CHILD_ORDER_INFO.MODIFYPROGID	   C17_MODIFYPROGID,
	LT_CHILD_ORDER_INFO.LOCKID	   C18_LOCKID
from	<schema_name>.LT_CHILD_ORDER_INFO   LT_CHILD_ORDER_INFO
where	(1=1)
And (LT_CHILD_ORDER_INFO.MODIFYTS >= TO_DATE(SUBSTR(:v_cdc_load_date, 1, 19), 'YYYY-MM-DD HH24:MI:SS')  -:v_cdc_oms_overlap)


