DECLARE create_query CLOB;  
   BEGIN  
      BEGIN  
         EXECUTE IMMEDIATE 'drop table RAX_APP_USER.C$_0IM_SELECTION_FIELD_STG purge';  
      EXCEPTION  
         WHEN OTHERS THEN  
            IF SQLCODE != -942 THEN  
               RAISE;  
            END IF;   
      END;  
      create_query := 'create table RAX_APP_USER.C$_0IM_SELECTION_FIELD_STG ( C1_ID	NUMBER NULL, C2_CREATED_BY	VARCHAR2(255) NULL, C3_DATE_CREATED	DATE NULL, C4_DEFAULT_VALUE	VARCHAR2(255) NULL, C5_LAB_TYPE	VARCHAR2(255) NULL, C6_LABEL	VARCHAR2(255) NULL, C7_LAST_UPDATED	DATE NULL, C8_LENGTH	NUMBER NULL, C9_MAX	VARCHAR2(255) NULL, C10_MIN	VARCHAR2(255) NULL, C11_NAME	VARCHAR2(255) NULL, C12_REGEXP	VARCHAR2(255) NULL, C13_REQUIRED_BY_LAB	NUMBER NULL, C14_SELECTION_TEMPLATE_ID	NUMBER NULL, C15_TARGET	VARCHAR2(255) NULL, C16_TYPE	VARCHAR2(255) NULL, C17_UPDATED_BY	VARCHAR2(255) NULL, C18_SORT_SEQUENCE	NUMBER NULL ) NOLOGGING';  
      EXECUTE IMMEDIATE create_query;  
   END;  
   