select	
	SELECTION_FIELD_CHOICE.ID	   C1_ID,
	SELECTION_FIELD_CHOICE.CHOICE_ID	   C2_CHOICE_ID,
	SELECTION_FIELD_CHOICE.LABEL	   C3_LABEL,
	SELECTION_FIELD_CHOICE.SELECTION_FIELD_ID	   C4_SELECTION_FIELD_ID
from	<schema_name>.SELECTION_FIELD_CHOICE   SELECTION_FIELD_CHOICE, <schema_name>.SELECTION_FIELD   SELECTION_FIELD
where	(1=1)
And (SELECTION_FIELD.LAST_UPDATED >= TO_DATE(SUBSTR(:v_cdc_load_date, 1, 19), 'YYYY-MM-DD HH24:MI:SS')  -:v_cdc_oms_overlap)
And (SELECTION_FIELD_CHOICE.SELECTION_FIELD_ID=SELECTION_FIELD.ID)