select	
	SELECTION_FIELD.ID	   C1_ID,
	SELECTION_FIELD.CREATED_BY	   C2_CREATED_BY,
	SELECTION_FIELD.DATE_CREATED	   C3_DATE_CREATED,
	SELECTION_FIELD.DEFAULT_VALUE	   C4_DEFAULT_VALUE,
	SELECTION_FIELD.LAB_TYPE	   C5_LAB_TYPE,
	SELECTION_FIELD.LABEL	   C6_LABEL,
	SELECTION_FIELD.LAST_UPDATED	   C7_LAST_UPDATED,
	SELECTION_FIELD.LENGTH	   C8_LENGTH,
	SELECTION_FIELD.MAX	   C9_MAX,
	SELECTION_FIELD.MIN	   C10_MIN,
	SELECTION_FIELD.NAME	   C11_NAME,
	SELECTION_FIELD.REGEXP	   C12_REGEXP,
	SELECTION_FIELD.REQUIRED_BY_LAB	   C13_REQUIRED_BY_LAB,
	SELECTION_FIELD.SELECTION_TEMPLATE_ID	   C14_SELECTION_TEMPLATE_ID,
	SELECTION_FIELD.TARGET	   C15_TARGET,
	SELECTION_FIELD.TYPE	   C16_TYPE,
	SELECTION_FIELD.UPDATED_BY	   C17_UPDATED_BY,
	SELECTION_FIELD.SORT_SEQUENCE	   C18_SORT_SEQUENCE
from	<schema_name>.SELECTION_FIELD   SELECTION_FIELD
where	(1=1)
And (SELECTION_FIELD.LAST_UPDATED >= TO_DATE(SUBSTR(:v_cdc_load_date, 1, 19), 'YYYY-MM-DD HH24:MI:SS')  -:v_cdc_oms_overlap)