/* TASK No. 1 */

/* SELECT STATEMENT FOUND, CHECK ODI TASK NO. 1 */




/*-----------------------------------------------*/
/* TASK No. 2 */
/* drop report table */

-- drop table RAX_APP_USER.actuate_solo_proof_deposit_stg

-- &


-- /*-----------------------------------------------*/
-- /* TASK No. 3 */
-- /* create report table */

-- create table RAX_APP_USER.actuate_solo_proof_deposit_stg as
-- select s.subject_id
-- ,  s.last_name || ', ' || s.first_name subject_name
-- , solo.order_no as solo_order_no
-- , solo.order_sales_channel as solo_order_sales_channel
-- , solo.order_date as solo_order_date
-- , solo.bill_to_address as solo_bill_to_address
-- , solo.bill_to_city as solo_bill_to_city
-- , solo.bill_to_state as solo_bill_to_state
-- , pd.order_no as pd_order_no
-- , pd.order_sales_channel as pd_order_sales_channel
-- , pd.order_date as pd_order_date
-- , pd.bill_to_address as pd_bill_to_address
-- , pd.bill_to_city as pd_bill_to_city
-- , pd.bill_to_state as pd_bill_to_state
-- , pd.item_id
-- , pd.item_description
-- , pd.ordered_qty
-- , pd.extended_price
-- , pd.status
-- from
-- (
-- select oh.extn_subject_key
-- , oh.order_no
-- , oh.entry_type as order_sales_channel
-- , oh.order_date
-- , p.address_line1 as bill_to_address
-- , p.city as bill_to_city
-- , p.state as bill_to_state
-- from ods.y0yfs_order_header_curr oh
-- , ods.y0yfs_person_info_curr p
-- where oh.entry_type = 'Solo'
-- and oh.bill_to_key = p.person_info_key
-- ) solo
-- , (
-- select oh.extn_subject_key
-- , oh.order_no
-- , oh.entry_type as order_sales_channel
-- , oh.order_date
-- , p.address_line1 as bill_to_address
-- , p.city as bill_to_city
-- , p.state as bill_to_state
-- , ol.item_id
-- , ol.item_description
-- , ol.ordered_qty
-- , ((ol.ordered_qty * ol.unit_price) + ol.other_charges) as extended_price
-- , st.description as status
-- from ods.y0yfs_order_line_curr ol
-- , ods.y0yfs_order_header_curr oh
-- , ods.y0yfs_order_rel_stat_curr ors
-- , ods.y0yfs_status_curr st
-- , ods.y0yfs_person_info_curr p
-- where ol.order_header_key=oh.order_header_key
-- and ol.product_line='ProofDeposit'
-- and ors.order_line_key=ol.order_line_key
-- and ors.status_quantity>0
-- and st.process_type_key = 'ORDER_FULFILLMENT'
-- and st.description in ('Forfeited', 'Collected')
-- and ors.status=st.status
-- and oh.bill_to_key = p.person_info_key
-- and ((ol.ordered_qty * ol.unit_price) + ol.other_charges) > 0 
-- ) pd
-- , ods.y0lt_subject_curr s
-- where pd.extn_subject_key = solo.extn_subject_key
-- and solo.extn_subject_key = s.subject_key
-- and pd.extn_subject_key = s.subject_key

-- &


-- /*-----------------------------------------------*/
-- /* TASK No. 4 */
-- /* Generate header */

-- create header	(SUBJECT_ID,
-- 	SUBJECT_NAME,
-- 	SOLO_ORDER_NO,
-- 	SOLO_ORDER_SALES_CHANNEL,
-- 	SOLO_ORDER_DATE,
-- 	SOLO_BILL_TO_ADDRESS,
-- 	SOLO_BILL_TO_CITY,
-- 	SOLO_BILL_TO_STATE,
-- 	PD_ORDER_NO,
-- 	PD_ORDER_SALES_CHANNEL,
-- 	PD_ORDER_DATE,
-- 	PD_BILL_TO_ADDRESS,
-- 	PD_BILL_TO_CITY,
-- 	PD_BILL_TO_STATE,
-- 	ITEM_ID,
-- 	ITEM_DESCRIPTION,
-- 	ORDERED_QTY,
-- 	EXTENDED_PRICE,
-- 	STATUS)

-- /*$$SNPS_START_KEYSNP$CRDWG_TABLESNP$CRTABLE_NAME=solo_proof_deposit.csvSNP$CRLOAD_FILE=/dw_export/PROD/solo_proof_deposit.csvSNP$CRFILE_FORMAT=DSNP$CRFILE_SEP_FIELD=0x002cSNP$CRFILE_SEP_LINE=0x000D0x000ASNP$CRFILE_FIRST_ROW=0SNP$CRFILE_ENC_FIELD="SNP$CRFILE_DEC_SEP=SNP$CRSNP$CRDWG_COLSNP$CRCOL_NAME=SUBJECT_IDSNP$CRTYPE_NAME=STRINGSNP$CRORDER=1SNP$CRLENGTH=15SNP$CRPRECISION=15SNP$CRSNP$CRDWG_COLSNP$CRCOL_NAME=SUBJECT_NAMESNP$CRTYPE_NAME=STRINGSNP$CRORDER=2SNP$CRLENGTH=80SNP$CRPRECISION=80SNP$CRSNP$CRDWG_COLSNP$CRCOL_NAME=SOLO_ORDER_NOSNP$CRTYPE_NAME=STRINGSNP$CRORDER=3SNP$CRLENGTH=40SNP$CRPRECISION=40SNP$CRSNP$CRDWG_COLSNP$CRCOL_NAME=SOLO_ORDER_SALES_CHANNELSNP$CRTYPE_NAME=STRINGSNP$CRORDER=4SNP$CRLENGTH=20SNP$CRPRECISION=20SNP$CRSNP$CRDWG_COLSNP$CRCOL_NAME=SOLO_ORDER_DATESNP$CRTYPE_NAME=STRINGSNP$CRORDER=5SNP$CRLENGTH=50SNP$CRPRECISION=50SNP$CRSNP$CRDWG_COLSNP$CRCOL_NAME=SOLO_BILL_TO_ADDRESSSNP$CRTYPE_NAME=STRINGSNP$CRORDER=6SNP$CRLENGTH=70SNP$CRPRECISION=70SNP$CRSNP$CRDWG_COLSNP$CRCOL_NAME=SOLO_BILL_TO_CITYSNP$CRTYPE_NAME=STRINGSNP$CRORDER=7SNP$CRLENGTH=35SNP$CRPRECISION=35SNP$CRSNP$CRDWG_COLSNP$CRCOL_NAME=SOLO_BILL_TO_STATESNP$CRTYPE_NAME=STRINGSNP$CRORDER=8SNP$CRLENGTH=35SNP$CRPRECISION=35SNP$CRSNP$CRDWG_COLSNP$CRCOL_NAME=PD_ORDER_NOSNP$CRTYPE_NAME=STRINGSNP$CRORDER=9SNP$CRLENGTH=40SNP$CRPRECISION=40SNP$CRSNP$CRDWG_COLSNP$CRCOL_NAME=PD_ORDER_SALES_CHANNELSNP$CRTYPE_NAME=STRINGSNP$CRORDER=10SNP$CRLENGTH=20SNP$CRPRECISION=20SNP$CRSNP$CRDWG_COLSNP$CRCOL_NAME=PD_ORDER_DATESNP$CRTYPE_NAME=STRINGSNP$CRORDER=11SNP$CRLENGTH=50SNP$CRPRECISION=50SNP$CRSNP$CRDWG_COLSNP$CRCOL_NAME=PD_BILL_TO_ADDRESSSNP$CRTYPE_NAME=STRINGSNP$CRORDER=12SNP$CRLENGTH=70SNP$CRPRECISION=70SNP$CRSNP$CRDWG_COLSNP$CRCOL_NAME=PD_BILL_TO_CITYSNP$CRTYPE_NAME=STRINGSNP$CRORDER=13SNP$CRLENGTH=35SNP$CRPRECISION=35SNP$CRSNP$CRDWG_COLSNP$CRCOL_NAME=PD_BILL_TO_STATESNP$CRTYPE_NAME=STRINGSNP$CRORDER=14SNP$CRLENGTH=35SNP$CRPRECISION=35SNP$CRSNP$CRDWG_COLSNP$CRCOL_NAME=ITEM_IDSNP$CRTYPE_NAME=STRINGSNP$CRORDER=15SNP$CRLENGTH=40SNP$CRPRECISION=40SNP$CRSNP$CRDWG_COLSNP$CRCOL_NAME=ITEM_DESCRIPTIONSNP$CRTYPE_NAME=STRINGSNP$CRORDER=16SNP$CRLENGTH=200SNP$CRPRECISION=200SNP$CRSNP$CRDWG_COLSNP$CRCOL_NAME=ORDERED_QTYSNP$CRTYPE_NAME=STRINGSNP$CRORDER=17SNP$CRLENGTH=50SNP$CRPRECISION=50SNP$CRSNP$CRDWG_COLSNP$CRCOL_NAME=EXTENDED_PRICESNP$CRTYPE_NAME=STRINGSNP$CRORDER=18SNP$CRLENGTH=50SNP$CRPRECISION=50SNP$CRSNP$CRDWG_COLSNP$CRCOL_NAME=STATUSSNP$CRTYPE_NAME=STRINGSNP$CRORDER=19SNP$CRLENGTH=100SNP$CRPRECISION=100SNP$CR$$SNPS_END_KEY*/


-- &


-- /*-----------------------------------------------*/
-- /* TASK No. 5 */
-- /* Insert new rows */

-- /* SOURCE CODE */


-- select 	
-- 	SNG_SOLO.SUBJECT_ID	   SUBJECT_ID,
-- 	SNG_SOLO.SUBJECT_NAME	   SUBJECT_NAME,
-- 	SNG_SOLO.SOLO_ORDER_NO	   SOLO_ORDER_NO,
-- 	SNG_SOLO.SOLO_ORDER_SALES_CHANNEL	   SOLO_ORDER_SALES_CHANNEL,
-- 	SNG_SOLO.SOLO_ORDER_DATE	   SOLO_ORDER_DATE,
-- 	SNG_SOLO.SOLO_BILL_TO_ADDRESS	   SOLO_BILL_TO_ADDRESS,
-- 	SNG_SOLO.SOLO_BILL_TO_CITY	   SOLO_BILL_TO_CITY,
-- 	SNG_SOLO.SOLO_BILL_TO_STATE	   SOLO_BILL_TO_STATE,
-- 	SNG_SOLO.PD_ORDER_NO	   PD_ORDER_NO,
-- 	SNG_SOLO.PD_ORDER_SALES_CHANNEL	   PD_ORDER_SALES_CHANNEL,
-- 	SNG_SOLO.PD_ORDER_DATE	   PD_ORDER_DATE,
-- 	SNG_SOLO.PD_BILL_TO_ADDRESS	   PD_BILL_TO_ADDRESS,
-- 	SNG_SOLO.PD_BILL_TO_CITY	   PD_BILL_TO_CITY,
-- 	SNG_SOLO.PD_BILL_TO_STATE	   PD_BILL_TO_STATE,
-- 	SNG_SOLO.ITEM_ID	   ITEM_ID,
-- 	SNG_SOLO.ITEM_DESCRIPTION	   ITEM_DESCRIPTION,
-- 	SNG_SOLO.ORDERED_QTY	   ORDERED_QTY,
-- 	SNG_SOLO.EXTENDED_PRICE	   EXTENDED_PRICE,
-- 	SNG_SOLO.STATUS	   STATUS
-- from	RAX_APP_USER.ACTUATE_SOLO_PROOF_DEPOSIT_STG   SNG_SOLO
-- where	
-- 	(1=1)	
	





-- /* Order the output by the UD1, UD2, UD3, UD4, UD5, UD6 Fields. */



-- &

-- /* TARGET CODE */
-- insert into "/dw_export/PROD/solo_proof_deposit.csv"
-- (
-- 	SUBJECT_ID,
-- 	SUBJECT_NAME,
-- 	SOLO_ORDER_NO,
-- 	SOLO_ORDER_SALES_CHANNEL,
-- 	SOLO_ORDER_DATE,
-- 	SOLO_BILL_TO_ADDRESS,
-- 	SOLO_BILL_TO_CITY,
-- 	SOLO_BILL_TO_STATE,
-- 	PD_ORDER_NO,
-- 	PD_ORDER_SALES_CHANNEL,
-- 	PD_ORDER_DATE,
-- 	PD_BILL_TO_ADDRESS,
-- 	PD_BILL_TO_CITY,
-- 	PD_BILL_TO_STATE,
-- 	ITEM_ID,
-- 	ITEM_DESCRIPTION,
-- 	ORDERED_QTY,
-- 	EXTENDED_PRICE,
-- 	STATUS
                     
-- )
-- values 
-- (
-- 	:SUBJECT_ID,
-- 	:SUBJECT_NAME,
-- 	:SOLO_ORDER_NO,
-- 	:SOLO_ORDER_SALES_CHANNEL,
-- 	:SOLO_ORDER_DATE,
-- 	:SOLO_BILL_TO_ADDRESS,
-- 	:SOLO_BILL_TO_CITY,
-- 	:SOLO_BILL_TO_STATE,
-- 	:PD_ORDER_NO,
-- 	:PD_ORDER_SALES_CHANNEL,
-- 	:PD_ORDER_DATE,
-- 	:PD_BILL_TO_ADDRESS,
-- 	:PD_BILL_TO_CITY,
-- 	:PD_BILL_TO_STATE,
-- 	:ITEM_ID,
-- 	:ITEM_DESCRIPTION,
-- 	:ORDERED_QTY,
-- 	:EXTENDED_PRICE,
-- 	:STATUS
                     
-- )
-- /*$$SNPS_START_KEYSNP$CRDWG_TABLESNP$CRTABLE_NAME=solo_proof_deposit.csvSNP$CRLOAD_FILE=/dw_export/PROD/solo_proof_deposit.csvSNP$CRFILE_FORMAT=DSNP$CRFILE_SEP_FIELD=0x002cSNP$CRFILE_SEP_LINE=0x000D0x000ASNP$CRFILE_FIRST_ROW=0SNP$CRFILE_ENC_FIELD="SNP$CRFILE_DEC_SEP=SNP$CRSNP$CRDWG_COLSNP$CRCOL_NAME=SUBJECT_IDSNP$CRTYPE_NAME=STRINGSNP$CRORDER=1SNP$CRLENGTH=15SNP$CRPRECISION=15SNP$CRSNP$CRDWG_COLSNP$CRCOL_NAME=SUBJECT_NAMESNP$CRTYPE_NAME=STRINGSNP$CRORDER=2SNP$CRLENGTH=80SNP$CRPRECISION=80SNP$CRSNP$CRDWG_COLSNP$CRCOL_NAME=SOLO_ORDER_NOSNP$CRTYPE_NAME=STRINGSNP$CRORDER=3SNP$CRLENGTH=40SNP$CRPRECISION=40SNP$CRSNP$CRDWG_COLSNP$CRCOL_NAME=SOLO_ORDER_SALES_CHANNELSNP$CRTYPE_NAME=STRINGSNP$CRORDER=4SNP$CRLENGTH=20SNP$CRPRECISION=20SNP$CRSNP$CRDWG_COLSNP$CRCOL_NAME=SOLO_ORDER_DATESNP$CRTYPE_NAME=STRINGSNP$CRORDER=5SNP$CRLENGTH=50SNP$CRPRECISION=50SNP$CRSNP$CRDWG_COLSNP$CRCOL_NAME=SOLO_BILL_TO_ADDRESSSNP$CRTYPE_NAME=STRINGSNP$CRORDER=6SNP$CRLENGTH=70SNP$CRPRECISION=70SNP$CRSNP$CRDWG_COLSNP$CRCOL_NAME=SOLO_BILL_TO_CITYSNP$CRTYPE_NAME=STRINGSNP$CRORDER=7SNP$CRLENGTH=35SNP$CRPRECISION=35SNP$CRSNP$CRDWG_COLSNP$CRCOL_NAME=SOLO_BILL_TO_STATESNP$CRTYPE_NAME=STRINGSNP$CRORDER=8SNP$CRLENGTH=35SNP$CRPRECISION=35SNP$CRSNP$CRDWG_COLSNP$CRCOL_NAME=PD_ORDER_NOSNP$CRTYPE_NAME=STRINGSNP$CRORDER=9SNP$CRLENGTH=40SNP$CRPRECISION=40SNP$CRSNP$CRDWG_COLSNP$CRCOL_NAME=PD_ORDER_SALES_CHANNELSNP$CRTYPE_NAME=STRINGSNP$CRORDER=10SNP$CRLENGTH=20SNP$CRPRECISION=20SNP$CRSNP$CRDWG_COLSNP$CRCOL_NAME=PD_ORDER_DATESNP$CRTYPE_NAME=STRINGSNP$CRORDER=11SNP$CRLENGTH=50SNP$CRPRECISION=50SNP$CRSNP$CRDWG_COLSNP$CRCOL_NAME=PD_BILL_TO_ADDRESSSNP$CRTYPE_NAME=STRINGSNP$CRORDER=12SNP$CRLENGTH=70SNP$CRPRECISION=70SNP$CRSNP$CRDWG_COLSNP$CRCOL_NAME=PD_BILL_TO_CITYSNP$CRTYPE_NAME=STRINGSNP$CRORDER=13SNP$CRLENGTH=35SNP$CRPRECISION=35SNP$CRSNP$CRDWG_COLSNP$CRCOL_NAME=PD_BILL_TO_STATESNP$CRTYPE_NAME=STRINGSNP$CRORDER=14SNP$CRLENGTH=35SNP$CRPRECISION=35SNP$CRSNP$CRDWG_COLSNP$CRCOL_NAME=ITEM_IDSNP$CRTYPE_NAME=STRINGSNP$CRORDER=15SNP$CRLENGTH=40SNP$CRPRECISION=40SNP$CRSNP$CRDWG_COLSNP$CRCOL_NAME=ITEM_DESCRIPTIONSNP$CRTYPE_NAME=STRINGSNP$CRORDER=16SNP$CRLENGTH=200SNP$CRPRECISION=200SNP$CRSNP$CRDWG_COLSNP$CRCOL_NAME=ORDERED_QTYSNP$CRTYPE_NAME=STRINGSNP$CRORDER=17SNP$CRLENGTH=50SNP$CRPRECISION=50SNP$CRSNP$CRDWG_COLSNP$CRCOL_NAME=EXTENDED_PRICESNP$CRTYPE_NAME=STRINGSNP$CRORDER=18SNP$CRLENGTH=50SNP$CRPRECISION=50SNP$CRSNP$CRDWG_COLSNP$CRCOL_NAME=STATUSSNP$CRTYPE_NAME=STRINGSNP$CRORDER=19SNP$CRLENGTH=100SNP$CRPRECISION=100SNP$CR$$SNPS_END_KEY*/



-- /*-----------------------------------------------*/
-- /* TASK No. 6 */

-- chmod 644 /dw_export/PROD/solo_proof_deposit.csv

-- &


-- /*-----------------------------------------------*/
-- /* TASK No. 7 */

-- mv /dw_export/PROD/solo_proof_deposit.csv /dw_export/PROD/finance/solo_proof_deposit/solo_proof_depositr:v_actuate_sysdate.csv

-- &


/*-----------------------------------------------*/
