/* TASK No. 1 */

/* NONE or SET VARIABLE STATEMENT FOUND, CHECK ODI TASK NO. 1 */




/*-----------------------------------------------*/
/* TASK No. 2 */

/* SELECT STATEMENT FOUND, CHECK ODI TASK NO. 2 */




/*-----------------------------------------------*/
/* TASK No. 3 */

/* SELECT STATEMENT FOUND, CHECK ODI TASK NO. 3 */




/*-----------------------------------------------*/
/* TASK No. 4 */
/* Drop work table */

-- drop table RAX_APP_USER.C$_0STG_HEADER_CHARGE 

-- &


-- /*-----------------------------------------------*/
-- /* TASK No. 5 */
-- /* Create work table */

-- create table RAX_APP_USER.C$_0STG_HEADER_CHARGE
-- (
-- 	C1_CHARGE_NAME	VARCHAR2(40) NULL,
-- 	C2_HEADER_KEY	CHAR(24) NULL,
-- 	C3_CHARGE	NUMBER(15,2) NULL,
-- 	C4_EXTN_CHARGE_DESCRIPTION	VARCHAR2(100) NULL,
-- 	C5_MODIFYTS	DATE NULL,
-- 	C6_MODIFYPROGID	VARCHAR2(40) NULL,
-- 	C7_CHARGE_CATEGORY	VARCHAR2(20) NULL,
-- 	C8_EXTN_TAXABLE	CHAR(1) NULL,
-- 	C9_CREATEPROGID	VARCHAR2(40) NULL,
-- 	C10_MODIFYUSERID	VARCHAR2(40) NULL,
-- 	C11_REFERENCE	VARCHAR2(50) NULL,
-- 	C12_CREATETS	DATE NULL,
-- 	C13_EXTN_ACCOUNTING_TYPE	VARCHAR2(40) NULL,
-- 	C14_LOCKID	NUMBER(5) NULL,
-- 	C15_INVOICED_CHARGE	NUMBER(15,2) NULL,
-- 	C16_EXTN_TAX_INCLUSIVE	CHAR(1) NULL,
-- 	C17_EXTN_TCREDIT_PERCENTAGE	NUMBER(3) NULL,
-- 	C18_EXTN_TAX_CODE	VARCHAR2(20) NULL,
-- 	C19_CREATEUSERID	VARCHAR2(40) NULL,
-- 	C20_RECORD_TYPE	VARCHAR2(20) NULL,
-- 	C21_ORIGINAL_CHARGE	NUMBER(15,2) NULL,
-- 	C22_HEADER_CHARGES_KEY	CHAR(24) NULL
-- )
-- NOLOGGING

-- &


-- /*-----------------------------------------------*/
-- /* TASK No. 6 */
-- /* Load data */

-- /* SOURCE CODE */
-- select	
-- 	HC.CHARGE_NAME	   C1_CHARGE_NAME,
-- 	HC.HEADER_KEY	   C2_HEADER_KEY,
-- 	HC.CHARGE	   C3_CHARGE,
-- 	HC.EXTN_CHARGE_DESCRIPTION	   C4_EXTN_CHARGE_DESCRIPTION,
-- 	HC.MODIFYTS	   C5_MODIFYTS,
-- 	HC.MODIFYPROGID	   C6_MODIFYPROGID,
-- 	HC.CHARGE_CATEGORY	   C7_CHARGE_CATEGORY,
-- 	HC.EXTN_TAXABLE	   C8_EXTN_TAXABLE,
-- 	HC.CREATEPROGID	   C9_CREATEPROGID,
-- 	HC.MODIFYUSERID	   C10_MODIFYUSERID,
-- 	HC.REFERENCE	   C11_REFERENCE,
-- 	HC.CREATETS	   C12_CREATETS,
-- 	HC.EXTN_ACCOUNTING_TYPE	   C13_EXTN_ACCOUNTING_TYPE,
-- 	HC.LOCKID	   C14_LOCKID,
-- 	HC.INVOICED_CHARGE	   C15_INVOICED_CHARGE,
-- 	HC.EXTN_TAX_INCLUSIVE	   C16_EXTN_TAX_INCLUSIVE,
-- 	HC.EXTN_TCREDIT_PERCENTAGE	   C17_EXTN_TCREDIT_PERCENTAGE,
-- 	HC.EXTN_TAX_CODE	   C18_EXTN_TAX_CODE,
-- 	HC.CREATEUSERID	   C19_CREATEUSERID,
-- 	HC.RECORD_TYPE	   C20_RECORD_TYPE,
-- 	HC.ORIGINAL_CHARGE	   C21_ORIGINAL_CHARGE,
-- 	HC.HEADER_CHARGES_KEY	   C22_HEADER_CHARGES_KEY
-- from	OMS3_OWN.YFS_HEADER_CHARGES   HC
-- where	(1=1)
-- And (HC.MODIFYTS >= TO_DATE(SUBSTR(:v_cdc_load_date, 1, 19), 'YYYY-MM-DD HH24:MI:SS')  -:v_cdc_oms_overlap)





-- &

-- /* TARGET CODE */
-- insert into RAX_APP_USER.C$_0STG_HEADER_CHARGE
-- (
-- 	C1_CHARGE_NAME,
-- 	C2_HEADER_KEY,
-- 	C3_CHARGE,
-- 	C4_EXTN_CHARGE_DESCRIPTION,
-- 	C5_MODIFYTS,
-- 	C6_MODIFYPROGID,
-- 	C7_CHARGE_CATEGORY,
-- 	C8_EXTN_TAXABLE,
-- 	C9_CREATEPROGID,
-- 	C10_MODIFYUSERID,
-- 	C11_REFERENCE,
-- 	C12_CREATETS,
-- 	C13_EXTN_ACCOUNTING_TYPE,
-- 	C14_LOCKID,
-- 	C15_INVOICED_CHARGE,
-- 	C16_EXTN_TAX_INCLUSIVE,
-- 	C17_EXTN_TCREDIT_PERCENTAGE,
-- 	C18_EXTN_TAX_CODE,
-- 	C19_CREATEUSERID,
-- 	C20_RECORD_TYPE,
-- 	C21_ORIGINAL_CHARGE,
-- 	C22_HEADER_CHARGES_KEY
-- )
-- values
-- (
-- 	:C1_CHARGE_NAME,
-- 	:C2_HEADER_KEY,
-- 	:C3_CHARGE,
-- 	:C4_EXTN_CHARGE_DESCRIPTION,
-- 	:C5_MODIFYTS,
-- 	:C6_MODIFYPROGID,
-- 	:C7_CHARGE_CATEGORY,
-- 	:C8_EXTN_TAXABLE,
-- 	:C9_CREATEPROGID,
-- 	:C10_MODIFYUSERID,
-- 	:C11_REFERENCE,
-- 	:C12_CREATETS,
-- 	:C13_EXTN_ACCOUNTING_TYPE,
-- 	:C14_LOCKID,
-- 	:C15_INVOICED_CHARGE,
-- 	:C16_EXTN_TAX_INCLUSIVE,
-- 	:C17_EXTN_TCREDIT_PERCENTAGE,
-- 	:C18_EXTN_TAX_CODE,
-- 	:C19_CREATEUSERID,
-- 	:C20_RECORD_TYPE,
-- 	:C21_ORIGINAL_CHARGE,
-- 	:C22_HEADER_CHARGES_KEY
-- )

-- &


/*-----------------------------------------------*/
/* TASK No. 7 */
/* Analyze work table */



BEGIN
DBMS_STATS.GATHER_TABLE_STATS (
    ownname =>	'RAX_APP_USER',
    tabname =>	'C$_0STG_HEADER_CHARGE',
    estimate_percent =>	DBMS_STATS.AUTO_SAMPLE_SIZE
);
END;




&


/*-----------------------------------------------*/
/* TASK No. 9 */
/* Create target table  */

BEGIN  
   EXECUTE IMMEDIATE 'create table RAX_APP_USER.STG_HEADER_CHARGE
						(
							CHARGE_NAME	VARCHAR2(40) NULL,
							HEADER_KEY	CHAR(24) NULL,
							CHARGE	NUMBER(15,2) NULL,
							EXTN_CHARGE_DESCRIPTION	VARCHAR2(100) NULL,
							MODIFYTS	DATE NULL,
							MODIFYPROGID	VARCHAR2(40) NULL,
							CHARGE_CATEGORY	VARCHAR2(20) NULL,
							EXTN_TAXABLE	CHAR(1) NULL,
							CREATEPROGID	VARCHAR2(40) NULL,
							MODIFYUSERID	VARCHAR2(40) NULL,
							REFERENCE	VARCHAR2(50) NULL,
							CREATETS	DATE NULL,
							EXTN_ACCOUNTING_TYPE	VARCHAR2(40) NULL,
							LOCKID	NUMBER(5) NULL,
							INVOICED_CHARGE	NUMBER(15,2) NULL,
							EXTN_TAX_INCLUSIVE	CHAR(1) NULL,
							EXTN_TCREDIT_PERCENTAGE	NUMBER(3) NULL,
							EXTN_TAX_CODE	VARCHAR2(20) NULL,
							CREATEUSERID	VARCHAR2(40) NULL,
							RECORD_TYPE	VARCHAR2(20) NULL,
							ORIGINAL_CHARGE	NUMBER(15,2) NULL,
							HEADER_CHARGES_KEY	CHAR(24) NULL
						)';  
EXCEPTION  
   WHEN OTHERS THEN  
      IF SQLCODE != -955 THEN  
         RAISE;  
      END IF;  
END;

&


/*-----------------------------------------------*/
/* TASK No. 10 */
/* Truncate target table */

truncate table RAX_APP_USER.STG_HEADER_CHARGE


&


/*-----------------------------------------------*/
/* TASK No. 11 */
/* Insert new rows */

 
insert into	RAX_APP_USER.STG_HEADER_CHARGE 
( 
	CHARGE_NAME,
	HEADER_KEY,
	CHARGE,
	EXTN_CHARGE_DESCRIPTION,
	MODIFYTS,
	MODIFYPROGID,
	CHARGE_CATEGORY,
	EXTN_TAXABLE,
	CREATEPROGID,
	MODIFYUSERID,
	REFERENCE,
	CREATETS,
	EXTN_ACCOUNTING_TYPE,
	LOCKID,
	INVOICED_CHARGE,
	EXTN_TAX_INCLUSIVE,
	EXTN_TCREDIT_PERCENTAGE,
	EXTN_TAX_CODE,
	CREATEUSERID,
	RECORD_TYPE,
	ORIGINAL_CHARGE,
	HEADER_CHARGES_KEY 
	 
) 

select
    CHARGE_NAME,
	HEADER_KEY,
	CHARGE,
	EXTN_CHARGE_DESCRIPTION,
	MODIFYTS,
	MODIFYPROGID,
	CHARGE_CATEGORY,
	EXTN_TAXABLE,
	CREATEPROGID,
	MODIFYUSERID,
	REFERENCE,
	CREATETS,
	EXTN_ACCOUNTING_TYPE,
	LOCKID,
	INVOICED_CHARGE,
	EXTN_TAX_INCLUSIVE,
	EXTN_TCREDIT_PERCENTAGE,
	EXTN_TAX_CODE,
	CREATEUSERID,
	RECORD_TYPE,
	ORIGINAL_CHARGE,
	HEADER_CHARGES_KEY   
   
FROM (	


select 	
	C1_CHARGE_NAME CHARGE_NAME,
	C2_HEADER_KEY HEADER_KEY,
	C3_CHARGE CHARGE,
	C4_EXTN_CHARGE_DESCRIPTION EXTN_CHARGE_DESCRIPTION,
	C5_MODIFYTS MODIFYTS,
	C6_MODIFYPROGID MODIFYPROGID,
	C7_CHARGE_CATEGORY CHARGE_CATEGORY,
	C8_EXTN_TAXABLE EXTN_TAXABLE,
	C9_CREATEPROGID CREATEPROGID,
	C10_MODIFYUSERID MODIFYUSERID,
	C11_REFERENCE REFERENCE,
	C12_CREATETS CREATETS,
	C13_EXTN_ACCOUNTING_TYPE EXTN_ACCOUNTING_TYPE,
	C14_LOCKID LOCKID,
	C15_INVOICED_CHARGE INVOICED_CHARGE,
	C16_EXTN_TAX_INCLUSIVE EXTN_TAX_INCLUSIVE,
	C17_EXTN_TCREDIT_PERCENTAGE EXTN_TCREDIT_PERCENTAGE,
	C18_EXTN_TAX_CODE EXTN_TAX_CODE,
	C19_CREATEUSERID CREATEUSERID,
	C20_RECORD_TYPE RECORD_TYPE,
	C21_ORIGINAL_CHARGE ORIGINAL_CHARGE,
	C22_HEADER_CHARGES_KEY HEADER_CHARGES_KEY 
from	RAX_APP_USER.C$_0STG_HEADER_CHARGE
where		(1=1)	






)    ODI_GET_FROM




&


/*-----------------------------------------------*/
/* TASK No. 12 */
/* Commit transaction */

/* commit */


/*-----------------------------------------------*/
/* TASK No. 1000008 */
/* Drop work table */

drop table RAX_APP_USER.C$_0STG_HEADER_CHARGE 

&


/*-----------------------------------------------*/
/* TASK No. 13 */
/* Set vID */

/* NONE or SET VARIABLE STATEMENT FOUND, CHECK ODI TASK NO. 13 */




/*-----------------------------------------------*/
/* TASK No. 14 */
/* Drop flow table */

BEGIN  
   EXECUTE IMMEDIATE 'drop table RAX_APP_USER.I$_OMS_HEADER_CHARGE_XR97001 ';  
EXCEPTION  
   WHEN OTHERS THEN  
      IF SQLCODE != -942 THEN  
         RAISE;  
      END IF;  
END;

&


/*-----------------------------------------------*/
/* TASK No. 15 */
/* Create flow table I$ */

create table RAX_APP_USER.I$_OMS_HEADER_CHARGE_XR97001
(
	HEADER_CHARGE_OID	NUMBER NULL,
	HEADER_CHARGES_KEY	VARCHAR2(24) NULL,
	ODS_CREATE_DATE	DATE NULL,
	HEADER_KEY	VARCHAR2(24) NULL
	,IND_UPDATE		char(1)
)
NOLOGGING

&


/*-----------------------------------------------*/
/* TASK No. 16 */
/* Insert flow into I$ table */

/* DETECTION_STRATEGY = NOT_EXISTS */
 


  


insert into	RAX_APP_USER.I$_OMS_HEADER_CHARGE_XR97001
(
	HEADER_CHARGES_KEY,
	HEADER_KEY,
	IND_UPDATE
)
select 
HEADER_CHARGES_KEY,
	HEADER_KEY,
	IND_UPDATE
 from (


select 	 
	DISTINCT
	TRIM(HC.HEADER_CHARGES_KEY) HEADER_CHARGES_KEY,
	TRIM(HC.HEADER_KEY) HEADER_KEY,

	'I' IND_UPDATE

from	RAX_APP_USER.STG_HEADER_CHARGE   HC, ODS_STAGE.OMS_HEADER_CHARGE_XR   OMS_HEADER_CHARGE_XR
where	(1=1)
 And (TRIM(HC.HEADER_CHARGES_KEY)=OMS_HEADER_CHARGE_XR.HEADER_CHARGES_KEY (+)
AND OMS_HEADER_CHARGE_XR.HEADER_CHARGES_KEY IS NULL)





) S
where NOT EXISTS 
	( select 1 from ODS_STAGE.OMS_HEADER_CHARGE_XR T
	where	T.HEADER_CHARGES_KEY	= S.HEADER_CHARGES_KEY 
		 and ((T.HEADER_KEY = S.HEADER_KEY) or (T.HEADER_KEY IS NULL and S.HEADER_KEY IS NULL))
        )

  
  

  



&


/*-----------------------------------------------*/
/* TASK No. 17 */
/* Analyze integration table */



begin
    dbms_stats.gather_table_stats(
	ownname => 'RAX_APP_USER',
	tabname => 'I$_OMS_HEADER_CHARGE_XR97001',
	estimate_percent => dbms_stats.auto_sample_size
    );
end;



&


/*-----------------------------------------------*/
/* TASK No. 18 */
/* Create Index on flow table */

BEGIN  
   EXECUTE IMMEDIATE 'create index	RAX_APP_USER.I$_OMS_HEADER_CHARGE_XR_IDX97001 on RAX_APP_USER.I$_OMS_HEADER_CHARGE_XR97001 (HEADER_CHARGES_KEY) NOLOGGING';  
EXCEPTION  
   WHEN OTHERS THEN  
      IF SQLCODE != -955 and SQLCODE != -01408 and SQLCODE != -972 THEN  
         RAISE;  
      END IF;  
END;

&


/*-----------------------------------------------*/
/* TASK No. 19 */
/* Merge Rows */

merge into	ODS_STAGE.OMS_HEADER_CHARGE_XR T
using	RAX_APP_USER.I$_OMS_HEADER_CHARGE_XR97001 S
on	(
		T.HEADER_CHARGES_KEY=S.HEADER_CHARGES_KEY
	)
when matched
then update set
	T.HEADER_KEY	= S.HEADER_KEY
	
when not matched
then insert
	(
	T.HEADER_CHARGES_KEY,
	T.HEADER_KEY
	,  T.HEADER_CHARGE_OID,
	T.ODS_CREATE_DATE
	)
values
	(
	S.HEADER_CHARGES_KEY,
	S.HEADER_KEY
	,  ODS_STAGE.HEADER_CHARGE_OID_SEQ.nextval,
	SYSDATE
	)

&


/*-----------------------------------------------*/
/* TASK No. 20 */
/* Commit transaction */

/*commit*/


/*-----------------------------------------------*/
/* TASK No. 21 */
/* Drop flow table */

drop table RAX_APP_USER.I$_OMS_HEADER_CHARGE_XR97001 

&


/*-----------------------------------------------*/
/* TASK No. 22 */
/* Set vID */

/* NONE or SET VARIABLE STATEMENT FOUND, CHECK ODI TASK NO. 22 */




/*-----------------------------------------------*/
/* TASK No. 23 */
/* Drop flow table */

BEGIN  
   EXECUTE IMMEDIATE 'drop table RAX_APP_USER.I$_HEADER_CHARGE98001';  
EXCEPTION  
   WHEN OTHERS THEN  
      IF SQLCODE != -942 THEN  
         RAISE;  
      END IF;  
END;

&


/*-----------------------------------------------*/
/* TASK No. 24 */
/* Create flow table I$ */

create table RAX_APP_USER.I$_HEADER_CHARGE98001
(
	HEADER_CHARGE_OID	NUMBER NULL,
	ORDER_HEADER_OID	NUMBER NULL,
	CHARGE	NUMBER NULL,
	CHARGE_CATEGORY	VARCHAR2(20) NULL,
	CHARGE_NAME	VARCHAR2(40) NULL,
	ACCOUNTING_TYPE	VARCHAR2(40) NULL,
	CHARGE_DESCRIPTION	VARCHAR2(100) NULL,
	TAXABLE	VARCHAR2(1) NULL,
	TAX_CODE	VARCHAR2(20) NULL,
	TAX_INCLUSIVE	VARCHAR2(1) NULL,
	TCREDIT_PERCENTAGE	NUMBER NULL,
	INVOICED_CHARGE	NUMBER NULL,
	ORIGINAL_CHARGE	NUMBER NULL,
	RECORD_TYPE	VARCHAR2(20) NULL,
	REFERENCE	VARCHAR2(50) NULL,
	ODS_CREATE_DATE	DATE NULL,
	ODS_MODIFY_DATE	DATE NULL,
	SOURCE_SYSTEM_OID	NUMBER NULL
	,IND_UPDATE		char(1)
)
NOLOGGING

&


/*-----------------------------------------------*/
/* TASK No. 25 */
/* Insert flow into I$ table */

/* DETECTION_STRATEGY = NOT_EXISTS */
 


  


insert into	RAX_APP_USER.I$_HEADER_CHARGE98001
(
	HEADER_CHARGE_OID,
	ORDER_HEADER_OID,
	CHARGE,
	CHARGE_CATEGORY,
	CHARGE_NAME,
	ACCOUNTING_TYPE,
	CHARGE_DESCRIPTION,
	TAXABLE,
	TAX_CODE,
	TAX_INCLUSIVE,
	TCREDIT_PERCENTAGE,
	INVOICED_CHARGE,
	ORIGINAL_CHARGE,
	RECORD_TYPE,
	REFERENCE,
	SOURCE_SYSTEM_OID,
	IND_UPDATE
)
select 
HEADER_CHARGE_OID,
	ORDER_HEADER_OID,
	CHARGE,
	CHARGE_CATEGORY,
	CHARGE_NAME,
	ACCOUNTING_TYPE,
	CHARGE_DESCRIPTION,
	TAXABLE,
	TAX_CODE,
	TAX_INCLUSIVE,
	TCREDIT_PERCENTAGE,
	INVOICED_CHARGE,
	ORIGINAL_CHARGE,
	RECORD_TYPE,
	REFERENCE,
	SOURCE_SYSTEM_OID,
	IND_UPDATE
 from (


select 	 
	
	OMS_HEADER_CHARGE_XR.HEADER_CHARGE_OID HEADER_CHARGE_OID,
	OMS_ORDER_HEADER_XR.ORDER_HEADER_OID ORDER_HEADER_OID,
	HC.CHARGE CHARGE,
	HC.CHARGE_CATEGORY CHARGE_CATEGORY,
	HC.CHARGE_NAME CHARGE_NAME,
	HC.EXTN_ACCOUNTING_TYPE ACCOUNTING_TYPE,
	HC.EXTN_CHARGE_DESCRIPTION CHARGE_DESCRIPTION,
	HC.EXTN_TAXABLE TAXABLE,
	HC.EXTN_TAX_CODE TAX_CODE,
	'Y' TAX_INCLUSIVE,
	HC.EXTN_TCREDIT_PERCENTAGE TCREDIT_PERCENTAGE,
	HC.INVOICED_CHARGE INVOICED_CHARGE,
	HC.ORIGINAL_CHARGE ORIGINAL_CHARGE,
	HC.RECORD_TYPE RECORD_TYPE,
	HC.REFERENCE REFERENCE,
	SOURCE_SYSTEM.SOURCE_SYSTEM_OID SOURCE_SYSTEM_OID,

	'I' IND_UPDATE

from	RAX_APP_USER.STG_HEADER_CHARGE   HC, ODS_OWN.SOURCE_SYSTEM   SOURCE_SYSTEM, ODS_STAGE.OMS_HEADER_CHARGE_XR   OMS_HEADER_CHARGE_XR, ODS_STAGE.OMS_ORDER_HEADER_XR   OMS_ORDER_HEADER_XR
where	(1=1)
 And (TRIM(HC.HEADER_CHARGES_KEY)=OMS_HEADER_CHARGE_XR.HEADER_CHARGES_KEY)
AND (TRIM(HC.HEADER_KEY)=OMS_ORDER_HEADER_XR.ORDER_HEADER_KEY)
And (SOURCE_SYSTEM.SOURCE_SYSTEM_SHORT_NAME='OMS')




) S
where NOT EXISTS 
	( select 1 from ODS_OWN.HEADER_CHARGE T
	where	T.HEADER_CHARGE_OID	= S.HEADER_CHARGE_OID 
		 and ((T.ORDER_HEADER_OID = S.ORDER_HEADER_OID) or (T.ORDER_HEADER_OID IS NULL and S.ORDER_HEADER_OID IS NULL)) and
		((T.CHARGE = S.CHARGE) or (T.CHARGE IS NULL and S.CHARGE IS NULL)) and
		((T.CHARGE_CATEGORY = S.CHARGE_CATEGORY) or (T.CHARGE_CATEGORY IS NULL and S.CHARGE_CATEGORY IS NULL)) and
		((T.CHARGE_NAME = S.CHARGE_NAME) or (T.CHARGE_NAME IS NULL and S.CHARGE_NAME IS NULL)) and
		((T.ACCOUNTING_TYPE = S.ACCOUNTING_TYPE) or (T.ACCOUNTING_TYPE IS NULL and S.ACCOUNTING_TYPE IS NULL)) and
		((T.CHARGE_DESCRIPTION = S.CHARGE_DESCRIPTION) or (T.CHARGE_DESCRIPTION IS NULL and S.CHARGE_DESCRIPTION IS NULL)) and
		((T.TAXABLE = S.TAXABLE) or (T.TAXABLE IS NULL and S.TAXABLE IS NULL)) and
		((T.TAX_CODE = S.TAX_CODE) or (T.TAX_CODE IS NULL and S.TAX_CODE IS NULL)) and
		((T.TAX_INCLUSIVE = S.TAX_INCLUSIVE) or (T.TAX_INCLUSIVE IS NULL and S.TAX_INCLUSIVE IS NULL)) and
		((T.TCREDIT_PERCENTAGE = S.TCREDIT_PERCENTAGE) or (T.TCREDIT_PERCENTAGE IS NULL and S.TCREDIT_PERCENTAGE IS NULL)) and
		((T.INVOICED_CHARGE = S.INVOICED_CHARGE) or (T.INVOICED_CHARGE IS NULL and S.INVOICED_CHARGE IS NULL)) and
		((T.ORIGINAL_CHARGE = S.ORIGINAL_CHARGE) or (T.ORIGINAL_CHARGE IS NULL and S.ORIGINAL_CHARGE IS NULL)) and
		((T.RECORD_TYPE = S.RECORD_TYPE) or (T.RECORD_TYPE IS NULL and S.RECORD_TYPE IS NULL)) and
		((T.REFERENCE = S.REFERENCE) or (T.REFERENCE IS NULL and S.REFERENCE IS NULL)) and
		((T.SOURCE_SYSTEM_OID = S.SOURCE_SYSTEM_OID) or (T.SOURCE_SYSTEM_OID IS NULL and S.SOURCE_SYSTEM_OID IS NULL))
        )

  
  

  



&


/*-----------------------------------------------*/
/* TASK No. 26 */
/* Recycle previous errors */
BEGIN  
   EXECUTE IMMEDIATE 'insert into RAX_APP_USER.I$_HEADER_CHARGE98001
						(
							HEADER_CHARGE_OID,
							ORDER_HEADER_OID,
							CHARGE,
							CHARGE_CATEGORY,
							CHARGE_NAME,
							ACCOUNTING_TYPE,
							CHARGE_DESCRIPTION,
							TAXABLE,
							TAX_CODE,
							TAX_INCLUSIVE,
							TCREDIT_PERCENTAGE,
							INVOICED_CHARGE,
							ORIGINAL_CHARGE,
							RECORD_TYPE,
							REFERENCE,
							SOURCE_SYSTEM_OID,
							IND_UPDATE
						)
						select	DISTINCT HEADER_CHARGE_OID,
							ORDER_HEADER_OID,
							CHARGE,
							CHARGE_CATEGORY,
							CHARGE_NAME,
							ACCOUNTING_TYPE,
							CHARGE_DESCRIPTION,
							TAXABLE,
							TAX_CODE,
							TAX_INCLUSIVE,
							TCREDIT_PERCENTAGE,
							INVOICED_CHARGE,
							ORIGINAL_CHARGE,
							RECORD_TYPE,
							REFERENCE,
							SOURCE_SYSTEM_OID,
							''I'' IND_UPDATE
						from	RAX_APP_USER.E$_HEADER_CHARGE98001 E
						where 	not exists (
								select	''?''
								from	RAX_APP_USER.I$_HEADER_CHARGE98001 T
								where			T.HEADER_CHARGE_OID=E.HEADER_CHARGE_OID
								)
						and	E.ODI_ORIGIN	= ''(98001)ODS_Project.LOAD_HEADER_CHARGE_INT''
						and	E.ODI_ERR_TYPE	= ''F''';  
EXCEPTION  
   WHEN OTHERS THEN  
      IF SQLCODE != -942 THEN  
         RAISE;  
      END IF;  
END;

&


/*-----------------------------------------------*/
/* TASK No. 27 */
/* Analyze integration table */



begin
    dbms_stats.gather_table_stats(
	ownname => 'RAX_APP_USER',
	tabname => 'I$_HEADER_CHARGE98001',
	estimate_percent => dbms_stats.auto_sample_size
    );
end;



&


/*-----------------------------------------------*/
/* TASK No. 28 */
/* Create Index on flow table */

create index	RAX_APP_USER.I$_HEADER_CHARGE_IDX98001
on		RAX_APP_USER.I$_HEADER_CHARGE98001 (HEADER_CHARGE_OID)
NOLOGGING

&


/*-----------------------------------------------*/
/* TASK No. 29 */
/* create check table */


BEGIN  
   EXECUTE IMMEDIATE 'create table RAX_APP_USER.SNP_CHECK_TAB
						(
							CATALOG_NAME	VARCHAR2(100 CHAR) NULL ,
							SCHEMA_NAME	VARCHAR2(100 CHAR) NULL ,
							RESOURCE_NAME	VARCHAR2(100 CHAR) NULL,
							FULL_RES_NAME	VARCHAR2(100 CHAR) NULL,
							ERR_TYPE		VARCHAR2(1 CHAR) NULL,
							ERR_MESS		VARCHAR2(250 CHAR) NULL ,
							CHECK_DATE	DATE NULL,
							ORIGIN		VARCHAR2(100 CHAR) NULL,
							CONS_NAME	VARCHAR2(35 CHAR) NULL,
							CONS_TYPE		VARCHAR2(2 CHAR) NULL,
							ERR_COUNT		NUMBER(10) NULL
						)';  
EXCEPTION  
   WHEN OTHERS THEN  
      IF SQLCODE != -955 THEN  
         RAISE;  
      END IF;  
END;
	

&


/*-----------------------------------------------*/
/* TASK No. 30 */
/* delete previous check sum */

delete from	RAX_APP_USER.SNP_CHECK_TAB
where	SCHEMA_NAME	= 'ODS_OWN'
and	ORIGIN 		= '(98001)ODS_Project.LOAD_HEADER_CHARGE_INT'
and	ERR_TYPE 		= 'F'


&


/*-----------------------------------------------*/
/* TASK No. 31 */
/* create error table */

BEGIN  
   EXECUTE IMMEDIATE 'create table RAX_APP_USER.E$_HEADER_CHARGE98001
						(
							ODI_ROW_ID 		UROWID,
							ODI_ERR_TYPE		VARCHAR2(1 CHAR) NULL, 
							ODI_ERR_MESS		VARCHAR2(250 CHAR) NULL,
							ODI_CHECK_DATE	DATE NULL, 
							HEADER_CHARGE_OID	NUMBER NULL,
							ORDER_HEADER_OID	NUMBER NULL,
							CHARGE	NUMBER NULL,
							CHARGE_CATEGORY	VARCHAR2(20) NULL,
							CHARGE_NAME	VARCHAR2(40) NULL,
							ACCOUNTING_TYPE	VARCHAR2(40) NULL,
							CHARGE_DESCRIPTION	VARCHAR2(100) NULL,
							TAXABLE	VARCHAR2(1) NULL,
							TAX_CODE	VARCHAR2(20) NULL,
							TAX_INCLUSIVE	VARCHAR2(1) NULL,
							TCREDIT_PERCENTAGE	NUMBER NULL,
							INVOICED_CHARGE	NUMBER NULL,
							ORIGINAL_CHARGE	NUMBER NULL,
							RECORD_TYPE	VARCHAR2(20) NULL,
							REFERENCE	VARCHAR2(50) NULL,
							ODS_CREATE_DATE	DATE NULL,
							ODS_MODIFY_DATE	DATE NULL,
							SOURCE_SYSTEM_OID	NUMBER NULL,
							EST_TAX_RATE	NUMBER NULL,
							EST_PRETAX_AMOUNT	NUMBER NULL,
							EST_TAX_AMOUNT	NUMBER NULL,
							ODI_ORIGIN		VARCHAR2(100 CHAR) NULL,
							ODI_CONS_NAME	VARCHAR2(35 CHAR) NULL,
							ODI_CONS_TYPE		VARCHAR2(2 CHAR) NULL,
							ODI_PK			VARCHAR2(32 CHAR) PRIMARY KEY,
							ODI_SESS_NO		VARCHAR2(19 CHAR)
						)';  
EXCEPTION  
   WHEN OTHERS THEN  
      IF SQLCODE != -955 THEN  
         RAISE;  
      END IF;  
END;



&


/*-----------------------------------------------*/
/* TASK No. 32 */
/* delete previous errors */

delete from 	RAX_APP_USER.E$_HEADER_CHARGE98001
where	(ODI_ERR_TYPE = 'S'	and 'F' = 'S')
or	(ODI_ERR_TYPE = 'F'	and ODI_ORIGIN = '(98001)ODS_Project.LOAD_HEADER_CHARGE_INT')


&


/*-----------------------------------------------*/
/* TASK No. 33 */
/* Create index on PK */

 
/* FLOW CONTROL CREATE THE iNDEX ON THE I$TABLE */
BEGIN  
   EXECUTE IMMEDIATE 'create index 	RAX_APP_USER.I$_HEADER_CHARGE98001 on RAX_APP_USER.I$_HEADER_CHARGE98001 (HEADER_CHARGE_OID)';  
EXCEPTION  
   WHEN OTHERS THEN  
      IF SQLCODE != -955 and SQLCODE != -01408 THEN  
         RAISE;  
      END IF;  
END;


&


/*-----------------------------------------------*/
/* TASK No. 34 */
/* insert PK errors */

DECLARE
               CheckTable                             VarChar2(60);
               TargetTable                            VarChar2(60);
               VariableCheckTable                     VarChar2(60);

BEGIN
               SELECT 'RAX_APP_USER.I$_HEADER_CHARGE' INTO CheckTable FROM DUAL;
               SELECT 'ODS_OWN.HEADER_CHARGE' INTO TargetTable FROM DUAL;

IF CheckTable = TargetTable THEN
   VariableCheckTable := CheckTable; 
ELSE
   VariableCheckTable := CheckTable || '98001';
END IF;

execute immediate '
insert into RAX_APP_USER.E$_HEADER_CHARGE98001
(
	ODI_PK,
	ODI_SESS_NO,
	ODI_ROW_ID,
	ODI_ERR_TYPE,
	ODI_ERR_MESS,
	ODI_ORIGIN,
	ODI_CHECK_DATE,
	ODI_CONS_NAME,
	ODI_CONS_TYPE,
	HEADER_CHARGE_OID,
	ORDER_HEADER_OID,
	CHARGE,
	CHARGE_CATEGORY,
	CHARGE_NAME,
	ACCOUNTING_TYPE,
	CHARGE_DESCRIPTION,
	TAXABLE,
	TAX_CODE,
	TAX_INCLUSIVE,
	TCREDIT_PERCENTAGE,
	INVOICED_CHARGE,
	ORIGINAL_CHARGE,
	RECORD_TYPE,
	REFERENCE,
	ODS_CREATE_DATE,
	ODS_MODIFY_DATE,
	SOURCE_SYSTEM_OID
)
select	SYS_GUID(),
	:v_sess_no, 
	rowid,
	''F'', 
	''ODI-15064: The primary key HEADER_CHARGE_PK is not unique.'',
	''(98001)ODS_Project.LOAD_HEADER_CHARGE_INT'',
	sysdate,
	''HEADER_CHARGE_PK'',
	''PK'',	
	HEADER_CHARGE.HEADER_CHARGE_OID,
	HEADER_CHARGE.ORDER_HEADER_OID,
	HEADER_CHARGE.CHARGE,
	HEADER_CHARGE.CHARGE_CATEGORY,
	HEADER_CHARGE.CHARGE_NAME,
	HEADER_CHARGE.ACCOUNTING_TYPE,
	HEADER_CHARGE.CHARGE_DESCRIPTION,
	HEADER_CHARGE.TAXABLE,
	HEADER_CHARGE.TAX_CODE,
	HEADER_CHARGE.TAX_INCLUSIVE,
	HEADER_CHARGE.TCREDIT_PERCENTAGE,
	HEADER_CHARGE.INVOICED_CHARGE,
	HEADER_CHARGE.ORIGINAL_CHARGE,
	HEADER_CHARGE.RECORD_TYPE,
	HEADER_CHARGE.REFERENCE,
	HEADER_CHARGE.ODS_CREATE_DATE,
	HEADER_CHARGE.ODS_MODIFY_DATE,
	HEADER_CHARGE.SOURCE_SYSTEM_OID
from	'
 || VariableCheckTable || 
' HEADER_CHARGE 
where	exists  (
		select	SUB1.HEADER_CHARGE_OID
		from 	' 
|| VariableCheckTable ||
'  SUB1
		where 	SUB1.HEADER_CHARGE_OID=HEADER_CHARGE.HEADER_CHARGE_OID
		group by 	SUB1.HEADER_CHARGE_OID
		having 	count(1) > 1
		)
';

END;


&


/*-----------------------------------------------*/
/* TASK No. 35 */
/* Create index on AK */

 
/* FLOW CONTROL CREATE THE iNDEX ON THE I$TABLE */
BEGIN  
   EXECUTE IMMEDIATE 'create index 	HEADER_CHARGE_PKX_flow on RAX_APP_USER.I$_HEADER_CHARGE98001 (HEADER_CHARGE_OID)';  
EXCEPTION  
   WHEN OTHERS THEN  
      IF SQLCODE != -955 and SQLCODE != -01408 THEN  
         RAISE;  
      END IF;  
END;


&


/*-----------------------------------------------*/
/* TASK No. 36 */
/* insert AK errors */

DECLARE
               CheckTable                             VarChar2(60);
               TargetTable                            VarChar2(60);
               VariableCheckTable                VarChar2(60);

BEGIN
               SELECT 'RAX_APP_USER.I$_HEADER_CHARGE' INTO CheckTable FROM DUAL;
               SELECT 'ODS_OWN.HEADER_CHARGE' INTO TargetTable FROM DUAL;

IF CheckTable = TargetTable THEN
   VariableCheckTable := CheckTable; 
ELSE
   VariableCheckTable := CheckTable || '98001';
END IF;

execute immediate '
insert into RAX_APP_USER.E$_HEADER_CHARGE98001
(
	ODI_PK,
	ODI_SESS_NO,
	ODI_ROW_ID,
	ODI_ERR_TYPE,
	ODI_ERR_MESS,
	ODI_ORIGIN,
	ODI_CHECK_DATE,
	ODI_CONS_NAME,
	ODI_CONS_TYPE,
	HEADER_CHARGE_OID,
	ORDER_HEADER_OID,
	CHARGE,
	CHARGE_CATEGORY,
	CHARGE_NAME,
	ACCOUNTING_TYPE,
	CHARGE_DESCRIPTION,
	TAXABLE,
	TAX_CODE,
	TAX_INCLUSIVE,
	TCREDIT_PERCENTAGE,
	INVOICED_CHARGE,
	ORIGINAL_CHARGE,
	RECORD_TYPE,
	REFERENCE,
	ODS_CREATE_DATE,
	ODS_MODIFY_DATE,
	SOURCE_SYSTEM_OID
)
select	SYS_GUID(),
	:v_sess_no, 
	rowid,
	''F'', 
	''ODI-15063: The alternate key HEADER_CHARGE_PKX is not unique.'',
	''(98001)ODS_Project.LOAD_HEADER_CHARGE_INT'',
	sysdate,
	''HEADER_CHARGE_PKX'',
	''AK'',	
	HEADER_CHARGE.HEADER_CHARGE_OID,
	HEADER_CHARGE.ORDER_HEADER_OID,
	HEADER_CHARGE.CHARGE,
	HEADER_CHARGE.CHARGE_CATEGORY,
	HEADER_CHARGE.CHARGE_NAME,
	HEADER_CHARGE.ACCOUNTING_TYPE,
	HEADER_CHARGE.CHARGE_DESCRIPTION,
	HEADER_CHARGE.TAXABLE,
	HEADER_CHARGE.TAX_CODE,
	HEADER_CHARGE.TAX_INCLUSIVE,
	HEADER_CHARGE.TCREDIT_PERCENTAGE,
	HEADER_CHARGE.INVOICED_CHARGE,
	HEADER_CHARGE.ORIGINAL_CHARGE,
	HEADER_CHARGE.RECORD_TYPE,
	HEADER_CHARGE.REFERENCE,
	HEADER_CHARGE.ODS_CREATE_DATE,
	HEADER_CHARGE.ODS_MODIFY_DATE,
	HEADER_CHARGE.SOURCE_SYSTEM_OID
from              '	
 || VariableCheckTable || 
' HEADER_CHARGE
where	exists  (
		select	SUB.HEADER_CHARGE_OID
		from 	'
 || VariableCheckTable || 
' SUB
		where 	SUB.HEADER_CHARGE_OID=HEADER_CHARGE.HEADER_CHARGE_OID
		group by 	SUB.HEADER_CHARGE_OID
		having 	count(1) > 1
		)
 ';

END;

/*  Checked Datastore =RAX_APP_USER.I$_HEADER_CHARGE  */
/*  Integration Datastore =RAX_APP_USER.I$_HEADER_CHARGE   */
/*  Target Datastore =ODS_OWN.HEADER_CHARGE */



&


/*-----------------------------------------------*/
/* TASK No. 37 */
/* insert FK errors */

DECLARE
               CheckTable                             VarChar2(60);
               TargetTable                            VarChar2(60);
               VariableCheckTable                VarChar2(60);

BEGIN
               SELECT 'RAX_APP_USER.I$_HEADER_CHARGE' INTO CheckTable FROM DUAL;
               SELECT 'ODS_OWN.HEADER_CHARGE' INTO TargetTable FROM DUAL;

IF CheckTable = TargetTable THEN
   VariableCheckTable := CheckTable; 
ELSE
   VariableCheckTable := CheckTable || '98001';
END IF;

execute immediate '
insert into RAX_APP_USER.E$_HEADER_CHARGE98001
(
	ODI_PK,
	ODI_SESS_NO,
	ODI_ROW_ID,
	ODI_ERR_TYPE,
	ODI_ERR_MESS,
	ODI_CHECK_DATE,
	ODI_ORIGIN,
	ODI_CONS_NAME,
	ODI_CONS_TYPE,
	HEADER_CHARGE_OID,
	ORDER_HEADER_OID,
	CHARGE,
	CHARGE_CATEGORY,
	CHARGE_NAME,
	ACCOUNTING_TYPE,
	CHARGE_DESCRIPTION,
	TAXABLE,
	TAX_CODE,
	TAX_INCLUSIVE,
	TCREDIT_PERCENTAGE,
	INVOICED_CHARGE,
	ORIGINAL_CHARGE,
	RECORD_TYPE,
	REFERENCE,
	ODS_CREATE_DATE,
	ODS_MODIFY_DATE,
	SOURCE_SYSTEM_OID
)
select	SYS_GUID(),
	:v_sess_no, 
	rowid,
	''F'', 
	''ODI-15065: Join error (HC_ORDER_HEADER) between the table HEADER_CHARGE and the table ORDER_HEADER.'',
	sysdate,
	''(98001)ODS_Project.LOAD_HEADER_CHARGE_INT'',
	''HC_ORDER_HEADER'',
	''FK'',	
	HEADER_CHARGE_OID,
	ORDER_HEADER_OID,
	CHARGE,
	CHARGE_CATEGORY,
	CHARGE_NAME,
	ACCOUNTING_TYPE,
	CHARGE_DESCRIPTION,
	TAXABLE,
	TAX_CODE,
	TAX_INCLUSIVE,
	TCREDIT_PERCENTAGE,
	INVOICED_CHARGE,
	ORIGINAL_CHARGE,
	RECORD_TYPE,
	REFERENCE,
	ODS_CREATE_DATE,
	ODS_MODIFY_DATE,
	SOURCE_SYSTEM_OID

from	'
 || VariableCheckTable || 
' HEADER_CHARGE 
where 	(
		HEADER_CHARGE.ORDER_HEADER_OID 
	) not in 	(
		select 	ORDER_HEADER_OID
		from 	ODS_OWN.ORDER_HEADER
		)
and	(
		HEADER_CHARGE.ORDER_HEADER_OID is not null 
	)

';

END;

/*  Checked Datastore =RAX_APP_USER.I$_HEADER_CHARGE  */
/*  Integration Datastore =RAX_APP_USER.I$_HEADER_CHARGE   */
/*  Target Datastore =ODS_OWN.HEADER_CHARGE */


&


/*-----------------------------------------------*/
/* TASK No. 38 */
/* insert Not Null errors */

insert into RAX_APP_USER.E$_HEADER_CHARGE98001
(
	ODI_PK,
	ODI_SESS_NO,
	ODI_ROW_ID,
	ODI_ERR_TYPE,
	ODI_ERR_MESS,
	ODI_CHECK_DATE,
	ODI_ORIGIN,
	ODI_CONS_NAME,
	ODI_CONS_TYPE,
	HEADER_CHARGE_OID,
	ORDER_HEADER_OID,
	CHARGE,
	CHARGE_CATEGORY,
	CHARGE_NAME,
	ACCOUNTING_TYPE,
	CHARGE_DESCRIPTION,
	TAXABLE,
	TAX_CODE,
	TAX_INCLUSIVE,
	TCREDIT_PERCENTAGE,
	INVOICED_CHARGE,
	ORIGINAL_CHARGE,
	RECORD_TYPE,
	REFERENCE,
	ODS_CREATE_DATE,
	ODS_MODIFY_DATE,
	SOURCE_SYSTEM_OID
)
select
	SYS_GUID(),
	:v_sess_no, 
	rowid,
	'F', 
	'ODI-15066: The column HEADER_CHARGE_OID cannot be null.',
	sysdate,
	'(98001)ODS_Project.LOAD_HEADER_CHARGE_INT',
	'HEADER_CHARGE_OID',
	'NN',	
	HEADER_CHARGE_OID,
	ORDER_HEADER_OID,
	CHARGE,
	CHARGE_CATEGORY,
	CHARGE_NAME,
	ACCOUNTING_TYPE,
	CHARGE_DESCRIPTION,
	TAXABLE,
	TAX_CODE,
	TAX_INCLUSIVE,
	TCREDIT_PERCENTAGE,
	INVOICED_CHARGE,
	ORIGINAL_CHARGE,
	RECORD_TYPE,
	REFERENCE,
	ODS_CREATE_DATE,
	ODS_MODIFY_DATE,
	SOURCE_SYSTEM_OID
from	RAX_APP_USER.I$_HEADER_CHARGE98001
where	HEADER_CHARGE_OID is null



&


/*-----------------------------------------------*/
/* TASK No. 39 */
/* insert Not Null errors */

insert into RAX_APP_USER.E$_HEADER_CHARGE98001
(
	ODI_PK,
	ODI_SESS_NO,
	ODI_ROW_ID,
	ODI_ERR_TYPE,
	ODI_ERR_MESS,
	ODI_CHECK_DATE,
	ODI_ORIGIN,
	ODI_CONS_NAME,
	ODI_CONS_TYPE,
	HEADER_CHARGE_OID,
	ORDER_HEADER_OID,
	CHARGE,
	CHARGE_CATEGORY,
	CHARGE_NAME,
	ACCOUNTING_TYPE,
	CHARGE_DESCRIPTION,
	TAXABLE,
	TAX_CODE,
	TAX_INCLUSIVE,
	TCREDIT_PERCENTAGE,
	INVOICED_CHARGE,
	ORIGINAL_CHARGE,
	RECORD_TYPE,
	REFERENCE,
	ODS_CREATE_DATE,
	ODS_MODIFY_DATE,
	SOURCE_SYSTEM_OID
)
select
	SYS_GUID(),
	:v_sess_no, 
	rowid,
	'F', 
	'ODI-15066: The column ORDER_HEADER_OID cannot be null.',
	sysdate,
	'(98001)ODS_Project.LOAD_HEADER_CHARGE_INT',
	'ORDER_HEADER_OID',
	'NN',	
	HEADER_CHARGE_OID,
	ORDER_HEADER_OID,
	CHARGE,
	CHARGE_CATEGORY,
	CHARGE_NAME,
	ACCOUNTING_TYPE,
	CHARGE_DESCRIPTION,
	TAXABLE,
	TAX_CODE,
	TAX_INCLUSIVE,
	TCREDIT_PERCENTAGE,
	INVOICED_CHARGE,
	ORIGINAL_CHARGE,
	RECORD_TYPE,
	REFERENCE,
	ODS_CREATE_DATE,
	ODS_MODIFY_DATE,
	SOURCE_SYSTEM_OID
from	RAX_APP_USER.I$_HEADER_CHARGE98001
where	ORDER_HEADER_OID is null



&


/*-----------------------------------------------*/
/* TASK No. 40 */
/* insert Not Null errors */

insert into RAX_APP_USER.E$_HEADER_CHARGE98001
(
	ODI_PK,
	ODI_SESS_NO,
	ODI_ROW_ID,
	ODI_ERR_TYPE,
	ODI_ERR_MESS,
	ODI_CHECK_DATE,
	ODI_ORIGIN,
	ODI_CONS_NAME,
	ODI_CONS_TYPE,
	HEADER_CHARGE_OID,
	ORDER_HEADER_OID,
	CHARGE,
	CHARGE_CATEGORY,
	CHARGE_NAME,
	ACCOUNTING_TYPE,
	CHARGE_DESCRIPTION,
	TAXABLE,
	TAX_CODE,
	TAX_INCLUSIVE,
	TCREDIT_PERCENTAGE,
	INVOICED_CHARGE,
	ORIGINAL_CHARGE,
	RECORD_TYPE,
	REFERENCE,
	ODS_CREATE_DATE,
	ODS_MODIFY_DATE,
	SOURCE_SYSTEM_OID
)
select
	SYS_GUID(),
	:v_sess_no, 
	rowid,
	'F', 
	'ODI-15066: The column SOURCE_SYSTEM_OID cannot be null.',
	sysdate,
	'(98001)ODS_Project.LOAD_HEADER_CHARGE_INT',
	'SOURCE_SYSTEM_OID',
	'NN',	
	HEADER_CHARGE_OID,
	ORDER_HEADER_OID,
	CHARGE,
	CHARGE_CATEGORY,
	CHARGE_NAME,
	ACCOUNTING_TYPE,
	CHARGE_DESCRIPTION,
	TAXABLE,
	TAX_CODE,
	TAX_INCLUSIVE,
	TCREDIT_PERCENTAGE,
	INVOICED_CHARGE,
	ORIGINAL_CHARGE,
	RECORD_TYPE,
	REFERENCE,
	ODS_CREATE_DATE,
	ODS_MODIFY_DATE,
	SOURCE_SYSTEM_OID
from	RAX_APP_USER.I$_HEADER_CHARGE98001
where	SOURCE_SYSTEM_OID is null



&


/*-----------------------------------------------*/
/* TASK No. 41 */
/* create index on error table */

 
/* FLOW CONTROL CREATE INDEX ON THE E$TABLE */
BEGIN  
   EXECUTE IMMEDIATE 'create index 	RAX_APP_USER.E$_HEADER_CHARGE98001 on RAX_APP_USER.E$_HEADER_CHARGE98001 (ODI_ROW_ID)';  
EXCEPTION  
   WHEN OTHERS THEN  
      IF SQLCODE != -955 and SQLCODE != -01408 THEN  
         RAISE;  
      END IF;  
END;


&


/*-----------------------------------------------*/
/* TASK No. 42 */
/* delete errors from controlled table */

delete from	RAX_APP_USER.I$_HEADER_CHARGE98001  T
where	exists 	(
		select	1
		from	RAX_APP_USER.E$_HEADER_CHARGE98001 E
		where ODI_SESS_NO = :v_sess_no
		and T.rowid = E.ODI_ROW_ID
		)


&


/*-----------------------------------------------*/
/* TASK No. 43 */
/* insert check sum into check table */

insert into RAX_APP_USER.SNP_CHECK_TAB
(
	SCHEMA_NAME,
	RESOURCE_NAME,
	FULL_RES_NAME,
	ERR_TYPE,
	ERR_MESS,
	CHECK_DATE,
	ORIGIN,
	CONS_NAME,
	CONS_TYPE,
	ERR_COUNT
)
select	
	'ODS_OWN',
	'HEADER_CHARGE',
	'ODS_OWN.HEADER_CHARGE98001',
	E.ODI_ERR_TYPE,
	E.ODI_ERR_MESS,
	E.ODI_CHECK_DATE,
	E.ODI_ORIGIN,
	E.ODI_CONS_NAME,
	E.ODI_CONS_TYPE,
	count(1) 
from	RAX_APP_USER.E$_HEADER_CHARGE98001 E
where	E.ODI_ERR_TYPE	= 'F'
and	E.ODI_ORIGIN 	= '(98001)ODS_Project.LOAD_HEADER_CHARGE_INT'
group by	E.ODI_ERR_TYPE,
	E.ODI_ERR_MESS,
	E.ODI_CHECK_DATE,
	E.ODI_ORIGIN,
	E.ODI_CONS_NAME,
	E.ODI_CONS_TYPE


&


/*-----------------------------------------------*/
/* TASK No. 44 */
/* Merge Rows */

merge into	ODS_OWN.HEADER_CHARGE T
using	RAX_APP_USER.I$_HEADER_CHARGE98001 S
on	(
		T.HEADER_CHARGE_OID=S.HEADER_CHARGE_OID
	)
when matched
then update set
	T.ORDER_HEADER_OID	= S.ORDER_HEADER_OID,
	T.CHARGE	= S.CHARGE,
	T.CHARGE_CATEGORY	= S.CHARGE_CATEGORY,
	T.CHARGE_NAME	= S.CHARGE_NAME,
	T.ACCOUNTING_TYPE	= S.ACCOUNTING_TYPE,
	T.CHARGE_DESCRIPTION	= S.CHARGE_DESCRIPTION,
	T.TAXABLE	= S.TAXABLE,
	T.TAX_CODE	= S.TAX_CODE,
	T.TAX_INCLUSIVE	= S.TAX_INCLUSIVE,
	T.TCREDIT_PERCENTAGE	= S.TCREDIT_PERCENTAGE,
	T.INVOICED_CHARGE	= S.INVOICED_CHARGE,
	T.ORIGINAL_CHARGE	= S.ORIGINAL_CHARGE,
	T.RECORD_TYPE	= S.RECORD_TYPE,
	T.REFERENCE	= S.REFERENCE,
	T.SOURCE_SYSTEM_OID	= S.SOURCE_SYSTEM_OID
	,               T.ODS_MODIFY_DATE	= SYSDATE
when not matched
then insert
	(
	T.HEADER_CHARGE_OID,
	T.ORDER_HEADER_OID,
	T.CHARGE,
	T.CHARGE_CATEGORY,
	T.CHARGE_NAME,
	T.ACCOUNTING_TYPE,
	T.CHARGE_DESCRIPTION,
	T.TAXABLE,
	T.TAX_CODE,
	T.TAX_INCLUSIVE,
	T.TCREDIT_PERCENTAGE,
	T.INVOICED_CHARGE,
	T.ORIGINAL_CHARGE,
	T.RECORD_TYPE,
	T.REFERENCE,
	T.SOURCE_SYSTEM_OID
	,                T.ODS_CREATE_DATE,
	T.ODS_MODIFY_DATE
	)
values
	(
	S.HEADER_CHARGE_OID,
	S.ORDER_HEADER_OID,
	S.CHARGE,
	S.CHARGE_CATEGORY,
	S.CHARGE_NAME,
	S.ACCOUNTING_TYPE,
	S.CHARGE_DESCRIPTION,
	S.TAXABLE,
	S.TAX_CODE,
	S.TAX_INCLUSIVE,
	S.TCREDIT_PERCENTAGE,
	S.INVOICED_CHARGE,
	S.ORIGINAL_CHARGE,
	S.RECORD_TYPE,
	S.REFERENCE,
	S.SOURCE_SYSTEM_OID
	,                SYSDATE,
	SYSDATE
	)

&


/*-----------------------------------------------*/
/* TASK No. 45 */
/* Commit transaction */

/*commit*/


/*-----------------------------------------------*/
/* TASK No. 46 */
/* Drop flow table */

drop table RAX_APP_USER.I$_HEADER_CHARGE98001 

&


/*-----------------------------------------------*/
/* TASK No. 47 */
/* Update CDC Load Status */

UPDATE ODS_OWN.ODS_CDC_LOAD_STATUS
SET LAST_CDC_COMPLETION_DATE=TO_DATE(
             SUBSTR(:v_sess_beg, 1, 19), 'RRRR-MM-DD HH24:MI:SS')
+ nvl((TIMEZONE_OFFSET/24), 0) 
WHERE ODS_TABLE_NAME=:v_cdc_load_table_name
AND CONTEXT_NAME = :v_env

/*
UPDATE ODS_OWN.ODS_CDC_LOAD_STATUS
SET LAST_CDC_COMPLETION_DATE=TO_DATE(
             SUBSTR(:v_sess_beg, 1, 19), 'RRRR-MM-DD HH24:MI:SS')
WHERE ODS_TABLE_NAME=:v_cdc_load_table_name
AND CONTEXT_NAME = :v_env
*/

&


/*-----------------------------------------------*/
/* TASK No. 48 */
/* Insert CDC Audit Record */

INSERT INTO RAX_APP_USER.ODS_CDC_LOAD_STATUS_AUDIT
(TABLE_NAME,
SESS_NO,                      
SESS_NAME,                    
SCEN_VERSION,                 
SESS_BEG,                     
ORIG_LAST_CDC_COMPLETION_DATE,
OVERLAP,
CREATE_DATE,
CONTEXT_NAME,
TIMEZONE_OFFSET              
)
select 
:v_cdc_load_table_name
,:v_sess_no
,'LOAD_HEADER_CHARGE_PKG'
,'013'
,TO_DATE(SUBSTR(:v_sess_beg, 1, 19), 'RRRR-MM-DD HH24:MI:SS')
,TO_DATE (SUBSTR(:v_cdc_load_date, 1, 19),'YYYY-MM-DD HH24:MI:SS')
,:v_cdc_overlap
,SYSDATE
,:v_env
,TIMEZONE_OFFSET
from 
ODS_OWN.ODS_CDC_LOAD_STATUS
WHERE ODS_TABLE_NAME=:v_cdc_load_table_name
AND CONTEXT_NAME = :v_env

/*
INSERT INTO RAX_APP_USER.ODS_CDC_LOAD_STATUS_AUDIT
(TABLE_NAME,
SESS_NO,                      
SESS_NAME,                    
SCEN_VERSION,                 
SESS_BEG,                     
ORIG_LAST_CDC_COMPLETION_DATE,
OVERLAP,
CREATE_DATE,
CONTEXT_NAME              
)
values (
:v_cdc_load_table_name,
:v_sess_no,
'LOAD_HEADER_CHARGE_PKG',
'013',
TO_DATE(
             SUBSTR(:v_sess_beg, 1, 19), 'RRRR-MM-DD HH24:MI:SS'),
TO_DATE (SUBSTR (:v_cdc_load_date, 1, 19),
                           'YYYY-MM-DD HH24:MI:SS'
                          )
,:v_cdc_overlap,
SYSDATE,
 :v_env)
*/


&


/*-----------------------------------------------*/
