/* TASK No. 1 */

/* NONE or SET VARIABLE STATEMENT FOUND, CHECK ODI TASK NO. 1 */




/*-----------------------------------------------*/
/* TASK No. 2 */

/* SELECT STATEMENT FOUND, CHECK ODI TASK NO. 2 */




/*-----------------------------------------------*/
/* TASK No. 3 */

/* SELECT STATEMENT FOUND, CHECK ODI TASK NO. 3 */




/*-----------------------------------------------*/
/* TASK No. 4 */
/* Drop work table */

-- drop table RAX_APP_USER.C$_0OMS3_ITEM_STG purge

-- &


-- /*-----------------------------------------------*/
-- /* TASK No. 5 */
-- /* Create work table */

-- create table RAX_APP_USER.C$_0OMS3_ITEM_STG
-- (
-- 	C1_ITEM_KEY	VARCHAR2(24) NULL,
-- 	C2_ITEM_ID	VARCHAR2(40) NULL,
-- 	C3_SCHEDULE_B_CODE	VARCHAR2(40) NULL,
-- 	C4_KIT_CODE	VARCHAR2(20) NULL,
-- 	C5_FUTURE_SAFETY_FACTOR_PCT	NUMBER NULL,
-- 	C6_IS_SUB_ON_ORDER_ALLOWED	VARCHAR2(1) NULL,
-- 	C7_PRIMARY_ENTERPRISE_CODE	VARCHAR2(24) NULL,
-- 	C8_MINIMUM_CAPACITY_QUANTITY	NUMBER NULL,
-- 	C9_UNSPSC	VARCHAR2(40) NULL,
-- 	C10_PRIMARY_SUPPLIER	VARCHAR2(24) NULL,
-- 	C11_COMMODITY_CODE	VARCHAR2(40) NULL,
-- 	C12_CONFIGURED_MODEL_KEY	VARCHAR2(24) NULL,
-- 	C13_MIN_NOTIFICATION_TIME	NUMBER NULL,
-- 	C14_UNIT_HEIGHT	NUMBER NULL,
-- 	C15_NAICS_CODE	VARCHAR2(40) NULL,
-- 	C16_MODEL_ITEM_UOM	VARCHAR2(40) NULL,
-- 	C17_CREATEPROGID	VARCHAR2(40) NULL,
-- 	C18_NMFC_CODE	VARCHAR2(40) NULL,
-- 	C19_REQUIRES_PROD_ASSOCIATION	VARCHAR2(1) NULL,
-- 	C20_IS_PROCUREMENT_ALLOWED	VARCHAR2(1) NULL,
-- 	C21_INVOLVES_SEGMENT_CHANGE	VARCHAR2(1) NULL,
-- 	C22_DESCRIPTION	VARCHAR2(200) NULL,
-- 	C23_SYNCTS	DATE NULL,
-- 	C24_MAX_ORDER_QUANTITY	NUMBER NULL,
-- 	C25_IS_PARCEL_SHIPPING_ALLOWED	VARCHAR2(1) NULL,
-- 	C26_IS_RETURNABLE	VARCHAR2(1) NULL,
-- 	C27_POSTING_CLASSIFICATION	VARCHAR2(40) NULL,
-- 	C28_MODIFYUSERID	VARCHAR2(40) NULL,
-- 	C29_MODIFYPROGID	VARCHAR2(40) NULL,
-- 	C30_CAPACITY_VOLUME_UOM	VARCHAR2(40) NULL,
-- 	C31_IS_PICKUP_ALLOWED	VARCHAR2(1) NULL,
-- 	C32_LEAD_TIME	NUMBER NULL,
-- 	C33_EXTN_LOOK_SELECTION_ALLOWE	VARCHAR2(1) NULL,
-- 	C34_IS_DELIVERY_ALLOWED	VARCHAR2(1) NULL,
-- 	C35_LOCKID	NUMBER NULL,
-- 	C36_IS_CONFIGURABLE	VARCHAR2(1) NULL,
-- 	C37_SHP_CONSOL_WINDOW	NUMBER NULL,
-- 	C38_HAZMAT_CLASS	VARCHAR2(40) NULL,
-- 	C39_TAX_PRODUCT_CODE	VARCHAR2(40) NULL,
-- 	C40_UNIT_COST	NUMBER NULL,
-- 	C41_ITEM_TYPE	VARCHAR2(40) NULL,
-- 	C42_ORGANIZATION_CODE	VARCHAR2(24) NULL,
-- 	C43_ASSUME_INFINITE_INVENTORY	VARCHAR2(1) NULL,
-- 	C44_MAX_CNTR_WEIGHT_UOM	VARCHAR2(40) NULL,
-- 	C45_STORAGE_TYPE	VARCHAR2(40) NULL,
-- 	C46_MANUFACTURER_ITEM	VARCHAR2(100) NULL,
-- 	C47_NUM_SECONDARY_SERIALS	NUMBER NULL,
-- 	C48_UPC_COM_PRE_LEN	NUMBER NULL,
-- 	C49_IS_PRE_CONFIGURED	VARCHAR2(1) NULL,
-- 	C50_SUB_CLASS	VARCHAR2(100) NULL,
-- 	C51_EMPTY_CNTR_WEIGHT	NUMBER NULL,
-- 	C52_TAG_REQ_AT_SHIPMENT	VARCHAR2(1) NULL,
-- 	C53_PICKING_TYPE	VARCHAR2(40) NULL,
-- 	C54_DEPARTMENT	VARCHAR2(100) NULL,
-- 	C55_CAPACITY_QUANTITY_STRATEGY	VARCHAR2(20) NULL,
-- 	C56_CAPACITY_VOLUME	NUMBER NULL,
-- 	C57_USE_UNPLANNED_INV	VARCHAR2(1) NULL,
-- 	C58_PRODUCT_LINE	VARCHAR2(100) NULL,
-- 	C59_UNIT_HEIGHT_UOM	VARCHAR2(40) NULL,
-- 	C60_IS_FREEZER_REQUIRED	VARCHAR2(1) NULL,
-- 	C61_PRICING_QUANTITY_STRATEGY	VARCHAR2(20) NULL,
-- 	C62_ONHAND_SAFETY_FACTOR_PCT	NUMBER NULL,
-- 	C63_COMPUTED_UNIT_COST	NUMBER NULL,
-- 	C64_UNIT_WIDTH	NUMBER NULL,
-- 	C65_SHORT_DESCRIPTION	VARCHAR2(100) NULL,
-- 	C66_TAXABLE_FLAG	VARCHAR2(1) NULL,
-- 	C67_CONTAINER_SIZE	VARCHAR2(24) NULL,
-- 	C68_ECCN_NO	VARCHAR2(40) NULL,
-- 	C69_TAG_CONTROL_FLAG	VARCHAR2(1) NULL,
-- 	C70_IS_IBA_ALLOWED	VARCHAR2(1) NULL,
-- 	C71_CLASS	VARCHAR2(100) NULL,
-- 	C72_CAPACITY_PER_ORDERED_QTY	NUMBER NULL,
-- 	C73_COST_CURRENCY	VARCHAR2(20) NULL,
-- 	C74_IS_HAZMAT	VARCHAR2(1) NULL,
-- 	C75_DEFAULT_EXPIRATION_DAYS	NUMBER NULL,
-- 	C76_FIXED_CAPACITY_QTY_PER_LIN	NUMBER NULL,
-- 	C77_PRICING_UOM	VARCHAR2(40) NULL,
-- 	C78_EXTENDED_DESCRIPTION	VARCHAR2(2000) NULL,
-- 	C79_PROCESSING_TIME	NUMBER NULL,
-- 	C80_INVENTORY_MONITOR_RULE	VARCHAR2(24) NULL,
-- 	C81_CAN_USE_AS_SERVICE_TOOL	VARCHAR2(1) NULL,
-- 	C82_NMFC_CLASS	VARCHAR2(100) NULL,
-- 	C83_RETURN_SHIPPING_LABEL_LEVE	VARCHAR2(1) NULL,
-- 	C84_MAX_CNTR_WEIGHT	NUMBER NULL,
-- 	C85_HARMONIZED_CODE	VARCHAR2(40) NULL,
-- 	C86_ORDERING_QUANTITY_STRATEGY	VARCHAR2(20) NULL,
-- 	C87_SIZE_CODE	VARCHAR2(40) NULL,
-- 	C88_OPERATIONAL_CONFIG_COMPLET	VARCHAR2(1) NULL,
-- 	C89_INVOICE_BASED_ON_ACTUALS	VARCHAR2(1) NULL,
-- 	C90_UNIT_WEIGHT_UOM	VARCHAR2(40) NULL,
-- 	C91_MASTER_CATALOG_ID	VARCHAR2(40) NULL,
-- 	C92_GLOBAL_ITEM_ID	VARCHAR2(128) NULL,
-- 	C93_ATP_RULE	VARCHAR2(24) NULL,
-- 	C94_TAG_REQ_AT_RECEIPT	VARCHAR2(1) NULL,
-- 	C95_UNIT_LENGTH_UOM	VARCHAR2(40) NULL,
-- 	C96_MODEL	VARCHAR2(40) NULL,
-- 	C97_CONTAINER_TYPE	VARCHAR2(24) NULL,
-- 	C98_PRICING_UOM_STRATEGY	VARCHAR2(20) NULL,
-- 	C99_IS_FIFO_TRACKED	VARCHAR2(1) NULL,
-- 	C100_IS_SHIPPING_ALLOWED	VARCHAR2(1) NULL,
-- 	C101_IS_AIR_SHIPPING_ALLOWED	VARCHAR2(1) NULL,
-- 	C102_RETURN_WINDOW	NUMBER NULL,
-- 	C103_CREDIT_WO_RECEIPT	VARCHAR2(1) NULL,
-- 	C104_UNIT_WEIGHT	NUMBER NULL,
-- 	C105_VOLUME_ALLOWANCE	NUMBER NULL,
-- 	C106_VELOCITY_CODE	VARCHAR2(40) NULL,
-- 	C107_IS_RETURN_SERVICE	VARCHAR2(1) NULL,
-- 	C108_MANUFACTURER_NAME	VARCHAR2(50) NULL,
-- 	C109_TIME_SENSITIVE	VARCHAR2(1) NULL,
-- 	C110_DEFAULT_PRODUCT_CLASS	VARCHAR2(10) NULL,
-- 	C111_IS_SERIAL_TRACKED	VARCHAR2(1) NULL,
-- 	C112_ADVANCE_NOTIFICATION_TIME	NUMBER NULL,
-- 	C113_MAX_MODIFYTS	DATE NULL,
-- 	C114_REMOTE_MODIFYTS	DATE NULL,
-- 	C115_ONHAND_SAFETY_FACTOR_QTY	NUMBER NULL,
-- 	C116_IS_MODEL_ITEM	VARCHAR2(1) NULL,
-- 	C117_STATUS	VARCHAR2(15) NULL,
-- 	C118_IS_STANDALONE_SERVICE	VARCHAR2(1) NULL,
-- 	C119_CREATETS	DATE NULL,
-- 	C120_MIN_ORDER_QUANTITY	NUMBER NULL,
-- 	C121_PRICING_QUANTITY_CONV_FAC	NUMBER NULL,
-- 	C122_RUN_QUANTITY	NUMBER NULL,
-- 	C123_IS_FORWARDING_ALLOWED	VARCHAR2(1) NULL,
-- 	C124_NODE_LEVEL_INV_MONITOR_RU	VARCHAR2(24) NULL,
-- 	C125_COLOR_CODE	VARCHAR2(40) NULL,
-- 	C126_UNIT_WIDTH_UOM	VARCHAR2(40) NULL,
-- 	C127_EXTN_SKU_LAYOUT_ID	VARCHAR2(40) NULL,
-- 	C128_MODIFYTS	DATE NULL,
-- 	C129_SERIALIZED_FLAG	VARCHAR2(1) NULL,
-- 	C130_CREATEUSERID	VARCHAR2(40) NULL,
-- 	C131_ITEM_GROUP_CODE	VARCHAR2(20) NULL,
-- 	C132_IS_SHIPPING_CNTR	VARCHAR2(1) NULL,
-- 	C133_CAPACITY_UOM	VARCHAR2(40) NULL,
-- 	C134_UNIT_LENGTH	NUMBER NULL,
-- 	C135_BUNDLE_FULFILLMENT_MODE	VARCHAR2(2) NULL,
-- 	C136_FIXED_PRICING_QTY_PER_LIN	NUMBER NULL,
-- 	C137_MANUFACTURER_ITEM_DESC	VARCHAR2(255) NULL,
-- 	C138_UOM	VARCHAR2(40) NULL,
-- 	C139_COUNTRY_OF_ORIGIN	VARCHAR2(40) NULL,
-- 	C140_SERVICE_TYPE_ID	VARCHAR2(24) NULL,
-- 	C141_CHARGEBACK_CATEGORY	VARCHAR2(100) NULL,
-- 	C142_EQUIV_35_UNIT	NUMBER NULL,
-- 	C143_FULFILLMENT_TYPE	VARCHAR2(25) NULL,
-- 	C144_SELECTION_TEMPLATE	VARCHAR2(50) NULL,
-- 	C145_SHUTTERFLY_ELIGIBLE	VARCHAR2(2000) NULL
-- )
-- NOLOGGING

-- &


-- /*-----------------------------------------------*/
-- /* TASK No. 6 */
-- /* Load data */

-- /* SOURCE CODE */


-- select	
-- 	trim(ITM.ITEM_KEY)	   C1_ITEM_KEY,
-- 	trim(ITM.ITEM_ID)	   C2_ITEM_ID,
-- 	ITM.SCHEDULE_B_CODE	   C3_SCHEDULE_B_CODE,
-- 	ITM.KIT_CODE	   C4_KIT_CODE,
-- 	ITM.FUTURE_SAFETY_FACTOR_PCT	   C5_FUTURE_SAFETY_FACTOR_PCT,
-- 	ITM.IS_SUB_ON_ORDER_ALLOWED	   C6_IS_SUB_ON_ORDER_ALLOWED,
-- 	ITM.PRIMARY_ENTERPRISE_CODE	   C7_PRIMARY_ENTERPRISE_CODE,
-- 	ITM.MINIMUM_CAPACITY_QUANTITY	   C8_MINIMUM_CAPACITY_QUANTITY,
-- 	ITM.UNSPSC	   C9_UNSPSC,
-- 	ITM.PRIMARY_SUPPLIER	   C10_PRIMARY_SUPPLIER,
-- 	ITM.COMMODITY_CODE	   C11_COMMODITY_CODE,
-- 	ITM.CONFIGURED_MODEL_KEY	   C12_CONFIGURED_MODEL_KEY,
-- 	ITM.MIN_NOTIFICATION_TIME	   C13_MIN_NOTIFICATION_TIME,
-- 	ITM.UNIT_HEIGHT	   C14_UNIT_HEIGHT,
-- 	ITM.NAICS_CODE	   C15_NAICS_CODE,
-- 	ITM.MODEL_ITEM_UOM	   C16_MODEL_ITEM_UOM,
-- 	ITM.CREATEPROGID	   C17_CREATEPROGID,
-- 	ITM.NMFC_CODE	   C18_NMFC_CODE,
-- 	ITM.REQUIRES_PROD_ASSOCIATION	   C19_REQUIRES_PROD_ASSOCIATION,
-- 	ITM.IS_PROCUREMENT_ALLOWED	   C20_IS_PROCUREMENT_ALLOWED,
-- 	ITM.INVOLVES_SEGMENT_CHANGE	   C21_INVOLVES_SEGMENT_CHANGE,
-- 	ITM.DESCRIPTION	   C22_DESCRIPTION,
-- 	ITM.SYNCTS	   C23_SYNCTS,
-- 	ITM.MAX_ORDER_QUANTITY	   C24_MAX_ORDER_QUANTITY,
-- 	ITM.IS_PARCEL_SHIPPING_ALLOWED	   C25_IS_PARCEL_SHIPPING_ALLOWED,
-- 	ITM.IS_RETURNABLE	   C26_IS_RETURNABLE,
-- 	ITM.POSTING_CLASSIFICATION	   C27_POSTING_CLASSIFICATION,
-- 	ITM.MODIFYUSERID	   C28_MODIFYUSERID,
-- 	ITM.MODIFYPROGID	   C29_MODIFYPROGID,
-- 	ITM.CAPACITY_VOLUME_UOM	   C30_CAPACITY_VOLUME_UOM,
-- 	ITM.IS_PICKUP_ALLOWED	   C31_IS_PICKUP_ALLOWED,
-- 	ITM.LEAD_TIME	   C32_LEAD_TIME,
-- 	ITM.EXTN_LOOK_SELECTION_ALLOWED	   C33_EXTN_LOOK_SELECTION_ALLOWE,
-- 	ITM.IS_DELIVERY_ALLOWED	   C34_IS_DELIVERY_ALLOWED,
-- 	ITM.LOCKID	   C35_LOCKID,
-- 	ITM.IS_CONFIGURABLE	   C36_IS_CONFIGURABLE,
-- 	ITM.SHP_CONSOL_WINDOW	   C37_SHP_CONSOL_WINDOW,
-- 	ITM.HAZMAT_CLASS	   C38_HAZMAT_CLASS,
-- 	ITM.TAX_PRODUCT_CODE	   C39_TAX_PRODUCT_CODE,
-- 	ITM.UNIT_COST	   C40_UNIT_COST,
-- 	ITM.ITEM_TYPE	   C41_ITEM_TYPE,
-- 	ITM.ORGANIZATION_CODE	   C42_ORGANIZATION_CODE,
-- 	ITM.ASSUME_INFINITE_INVENTORY	   C43_ASSUME_INFINITE_INVENTORY,
-- 	ITM.MAX_CNTR_WEIGHT_UOM	   C44_MAX_CNTR_WEIGHT_UOM,
-- 	ITM.STORAGE_TYPE	   C45_STORAGE_TYPE,
-- 	ITM.MANUFACTURER_ITEM	   C46_MANUFACTURER_ITEM,
-- 	ITM.NUM_SECONDARY_SERIALS	   C47_NUM_SECONDARY_SERIALS,
-- 	ITM.UPC_COM_PRE_LEN	   C48_UPC_COM_PRE_LEN,
-- 	ITM.IS_PRE_CONFIGURED	   C49_IS_PRE_CONFIGURED,
-- 	ITM.SUB_CLASS	   C50_SUB_CLASS,
-- 	ITM.EMPTY_CNTR_WEIGHT	   C51_EMPTY_CNTR_WEIGHT,
-- 	ITM.TAG_REQ_AT_SHIPMENT	   C52_TAG_REQ_AT_SHIPMENT,
-- 	ITM.PICKING_TYPE	   C53_PICKING_TYPE,
-- 	ITM.DEPARTMENT	   C54_DEPARTMENT,
-- 	ITM.CAPACITY_QUANTITY_STRATEGY	   C55_CAPACITY_QUANTITY_STRATEGY,
-- 	ITM.CAPACITY_VOLUME	   C56_CAPACITY_VOLUME,
-- 	ITM.USE_UNPLANNED_INV	   C57_USE_UNPLANNED_INV,
-- 	ITM.PRODUCT_LINE	   C58_PRODUCT_LINE,
-- 	ITM.UNIT_HEIGHT_UOM	   C59_UNIT_HEIGHT_UOM,
-- 	ITM.IS_FREEZER_REQUIRED	   C60_IS_FREEZER_REQUIRED,
-- 	ITM.PRICING_QUANTITY_STRATEGY	   C61_PRICING_QUANTITY_STRATEGY,
-- 	ITM.ONHAND_SAFETY_FACTOR_PCT	   C62_ONHAND_SAFETY_FACTOR_PCT,
-- 	ITM.COMPUTED_UNIT_COST	   C63_COMPUTED_UNIT_COST,
-- 	ITM.UNIT_WIDTH	   C64_UNIT_WIDTH,
-- 	ITM.SHORT_DESCRIPTION	   C65_SHORT_DESCRIPTION,
-- 	ITM.TAXABLE_FLAG	   C66_TAXABLE_FLAG,
-- 	ITM.CONTAINER_SIZE	   C67_CONTAINER_SIZE,
-- 	ITM.ECCN_NO	   C68_ECCN_NO,
-- 	ITM.TAG_CONTROL_FLAG	   C69_TAG_CONTROL_FLAG,
-- 	ITM.IS_IBA_ALLOWED	   C70_IS_IBA_ALLOWED,
-- 	ITM.CLASS	   C71_CLASS,
-- 	ITM.CAPACITY_PER_ORDERED_QTY	   C72_CAPACITY_PER_ORDERED_QTY,
-- 	ITM.COST_CURRENCY	   C73_COST_CURRENCY,
-- 	ITM.IS_HAZMAT	   C74_IS_HAZMAT,
-- 	ITM.DEFAULT_EXPIRATION_DAYS	   C75_DEFAULT_EXPIRATION_DAYS,
-- 	ITM.FIXED_CAPACITY_QTY_PER_LINE	   C76_FIXED_CAPACITY_QTY_PER_LIN,
-- 	ITM.PRICING_UOM	   C77_PRICING_UOM,
-- 	ITM.EXTENDED_DESCRIPTION	   C78_EXTENDED_DESCRIPTION,
-- 	ITM.PROCESSING_TIME	   C79_PROCESSING_TIME,
-- 	ITM.INVENTORY_MONITOR_RULE	   C80_INVENTORY_MONITOR_RULE,
-- 	ITM.CAN_USE_AS_SERVICE_TOOL	   C81_CAN_USE_AS_SERVICE_TOOL,
-- 	ITM.NMFC_CLASS	   C82_NMFC_CLASS,
-- 	ITM.RETURN_SHIPPING_LABEL_LEVEL	   C83_RETURN_SHIPPING_LABEL_LEVE,
-- 	ITM.MAX_CNTR_WEIGHT	   C84_MAX_CNTR_WEIGHT,
-- 	ITM.HARMONIZED_CODE	   C85_HARMONIZED_CODE,
-- 	ITM.ORDERING_QUANTITY_STRATEGY	   C86_ORDERING_QUANTITY_STRATEGY,
-- 	ITM.SIZE_CODE	   C87_SIZE_CODE,
-- 	ITM.OPERATIONAL_CONFIG_COMPLETE	   C88_OPERATIONAL_CONFIG_COMPLET,
-- 	ITM.INVOICE_BASED_ON_ACTUALS	   C89_INVOICE_BASED_ON_ACTUALS,
-- 	ITM.UNIT_WEIGHT_UOM	   C90_UNIT_WEIGHT_UOM,
-- 	ITM.MASTER_CATALOG_ID	   C91_MASTER_CATALOG_ID,
-- 	ITM.GLOBAL_ITEM_ID	   C92_GLOBAL_ITEM_ID,
-- 	ITM.ATP_RULE	   C93_ATP_RULE,
-- 	ITM.TAG_REQ_AT_RECEIPT	   C94_TAG_REQ_AT_RECEIPT,
-- 	ITM.UNIT_LENGTH_UOM	   C95_UNIT_LENGTH_UOM,
-- 	ITM.MODEL	   C96_MODEL,
-- 	ITM.CONTAINER_TYPE	   C97_CONTAINER_TYPE,
-- 	ITM.PRICING_UOM_STRATEGY	   C98_PRICING_UOM_STRATEGY,
-- 	ITM.IS_FIFO_TRACKED	   C99_IS_FIFO_TRACKED,
-- 	ITM.IS_SHIPPING_ALLOWED	   C100_IS_SHIPPING_ALLOWED,
-- 	ITM.IS_AIR_SHIPPING_ALLOWED	   C101_IS_AIR_SHIPPING_ALLOWED,
-- 	ITM.RETURN_WINDOW	   C102_RETURN_WINDOW,
-- 	ITM.CREDIT_WO_RECEIPT	   C103_CREDIT_WO_RECEIPT,
-- 	ITM.UNIT_WEIGHT	   C104_UNIT_WEIGHT,
-- 	ITM.VOLUME_ALLOWANCE	   C105_VOLUME_ALLOWANCE,
-- 	ITM.VELOCITY_CODE	   C106_VELOCITY_CODE,
-- 	ITM.IS_RETURN_SERVICE	   C107_IS_RETURN_SERVICE,
-- 	ITM.MANUFACTURER_NAME	   C108_MANUFACTURER_NAME,
-- 	ITM.TIME_SENSITIVE	   C109_TIME_SENSITIVE,
-- 	ITM.DEFAULT_PRODUCT_CLASS	   C110_DEFAULT_PRODUCT_CLASS,
-- 	ITM.IS_SERIAL_TRACKED	   C111_IS_SERIAL_TRACKED,
-- 	ITM.ADVANCE_NOTIFICATION_TIME	   C112_ADVANCE_NOTIFICATION_TIME,
-- 	ITM.MAX_MODIFYTS	   C113_MAX_MODIFYTS,
-- 	ITM.REMOTE_MODIFYTS	   C114_REMOTE_MODIFYTS,
-- 	ITM.ONHAND_SAFETY_FACTOR_QTY	   C115_ONHAND_SAFETY_FACTOR_QTY,
-- 	ITM.IS_MODEL_ITEM	   C116_IS_MODEL_ITEM,
-- 	trim(ITM.STATUS)	   C117_STATUS,
-- 	ITM.IS_STANDALONE_SERVICE	   C118_IS_STANDALONE_SERVICE,
-- 	ITM.CREATETS	   C119_CREATETS,
-- 	ITM.MIN_ORDER_QUANTITY	   C120_MIN_ORDER_QUANTITY,
-- 	ITM.PRICING_QUANTITY_CONV_FACTOR	   C121_PRICING_QUANTITY_CONV_FAC,
-- 	ITM.RUN_QUANTITY	   C122_RUN_QUANTITY,
-- 	ITM.IS_FORWARDING_ALLOWED	   C123_IS_FORWARDING_ALLOWED,
-- 	ITM.NODE_LEVEL_INV_MONITOR_RULE	   C124_NODE_LEVEL_INV_MONITOR_RU,
-- 	ITM.COLOR_CODE	   C125_COLOR_CODE,
-- 	ITM.UNIT_WIDTH_UOM	   C126_UNIT_WIDTH_UOM,
-- 	ITM.EXTN_SKU_LAYOUT_ID	   C127_EXTN_SKU_LAYOUT_ID,
-- 	ITM.MODIFYTS	   C128_MODIFYTS,
-- 	ITM.SERIALIZED_FLAG	   C129_SERIALIZED_FLAG,
-- 	ITM.CREATEUSERID	   C130_CREATEUSERID,
-- 	ITM.ITEM_GROUP_CODE	   C131_ITEM_GROUP_CODE,
-- 	ITM.IS_SHIPPING_CNTR	   C132_IS_SHIPPING_CNTR,
-- 	ITM.CAPACITY_UOM	   C133_CAPACITY_UOM,
-- 	ITM.UNIT_LENGTH	   C134_UNIT_LENGTH,
-- 	ITM.BUNDLE_FULFILLMENT_MODE	   C135_BUNDLE_FULFILLMENT_MODE,
-- 	ITM.FIXED_PRICING_QTY_PER_LINE	   C136_FIXED_PRICING_QTY_PER_LIN,
-- 	ITM.MANUFACTURER_ITEM_DESC	   C137_MANUFACTURER_ITEM_DESC,
-- 	ITM.UOM	   C138_UOM,
-- 	ITM.COUNTRY_OF_ORIGIN	   C139_COUNTRY_OF_ORIGIN,
-- 	ITM.SERVICE_TYPE_ID	   C140_SERVICE_TYPE_ID,
-- 	nvl(YAA.VALUE,'NoChargeback')	   C141_CHARGEBACK_CATEGORY,
-- 	CASE WHEN trim(TRANSLATE(YAA2.VALUE,'0123456789', ' ')) is null
-- THEN YAA2.VALUE
-- ELSE NULL
-- END	   C142_EQUIV_35_UNIT,
-- 	YAA3.VALUE	   C143_FULFILLMENT_TYPE,
-- 	trim(ITM.EXTN_TEMPLATE)	   C144_SELECTION_TEMPLATE,
-- 	YAA4.VALUE	   C145_SHUTTERFLY_ELIGIBLE
-- from	OMS3_OWN.YFS_ITEM   ITM, OMS3_OWN.YFS_ADDITIONAL_ATTRIBUTE   YAA, OMS3_OWN.YFS_ADDITIONAL_ATTRIBUTE   YAA2, OMS3_OWN.YFS_ADDITIONAL_ATTRIBUTE   YAA3, OMS3_OWN.YFS_ADDITIONAL_ATTRIBUTE   YAA4
-- where	(1=1)
-- And (ITM.MODIFYTS >= TO_DATE(SUBSTR(:v_cdc_load_date, 1, 19), 'YYYY-MM-DD HH24:MI:SS')  -:v_cdc_overlap
-- )

--  And (trim(ITM.ITEM_KEY)=trim(YAA.PARENT_KEY(+)) and 'YFS_ITEM' = YAA.parent_table(+)
-- and 'ChargebackCategory' = YAA.name(+)




-- )
-- AND (trim(ITM.ITEM_KEY)=trim(YAA2.PARENT_KEY(+)) and 'YFS_ITEM' = YAA2.parent_table(+)
-- and 'EquivalentUnit' = YAA2.name(+)
-- )
-- AND (trim(ITM.ITEM_KEY)=trim(YAA3.PARENT_KEY(+)) and 'YFS_ITEM' = YAA3.parent_table(+)
-- and 'FulfillmentType' = YAA3.name(+)
-- )
-- AND (trim(ITM.ITEM_KEY)=trim(YAA4.PARENT_KEY(+)) and 'YFS_ITEM' = YAA4.parent_table(+)
-- and 'ShutterflyEligible' = YAA4.name(+))





-- &

-- /* TARGET CODE */
-- insert /*+ append */ into RAX_APP_USER.C$_0OMS3_ITEM_STG
-- (
-- 	C1_ITEM_KEY,
-- 	C2_ITEM_ID,
-- 	C3_SCHEDULE_B_CODE,
-- 	C4_KIT_CODE,
-- 	C5_FUTURE_SAFETY_FACTOR_PCT,
-- 	C6_IS_SUB_ON_ORDER_ALLOWED,
-- 	C7_PRIMARY_ENTERPRISE_CODE,
-- 	C8_MINIMUM_CAPACITY_QUANTITY,
-- 	C9_UNSPSC,
-- 	C10_PRIMARY_SUPPLIER,
-- 	C11_COMMODITY_CODE,
-- 	C12_CONFIGURED_MODEL_KEY,
-- 	C13_MIN_NOTIFICATION_TIME,
-- 	C14_UNIT_HEIGHT,
-- 	C15_NAICS_CODE,
-- 	C16_MODEL_ITEM_UOM,
-- 	C17_CREATEPROGID,
-- 	C18_NMFC_CODE,
-- 	C19_REQUIRES_PROD_ASSOCIATION,
-- 	C20_IS_PROCUREMENT_ALLOWED,
-- 	C21_INVOLVES_SEGMENT_CHANGE,
-- 	C22_DESCRIPTION,
-- 	C23_SYNCTS,
-- 	C24_MAX_ORDER_QUANTITY,
-- 	C25_IS_PARCEL_SHIPPING_ALLOWED,
-- 	C26_IS_RETURNABLE,
-- 	C27_POSTING_CLASSIFICATION,
-- 	C28_MODIFYUSERID,
-- 	C29_MODIFYPROGID,
-- 	C30_CAPACITY_VOLUME_UOM,
-- 	C31_IS_PICKUP_ALLOWED,
-- 	C32_LEAD_TIME,
-- 	C33_EXTN_LOOK_SELECTION_ALLOWE,
-- 	C34_IS_DELIVERY_ALLOWED,
-- 	C35_LOCKID,
-- 	C36_IS_CONFIGURABLE,
-- 	C37_SHP_CONSOL_WINDOW,
-- 	C38_HAZMAT_CLASS,
-- 	C39_TAX_PRODUCT_CODE,
-- 	C40_UNIT_COST,
-- 	C41_ITEM_TYPE,
-- 	C42_ORGANIZATION_CODE,
-- 	C43_ASSUME_INFINITE_INVENTORY,
-- 	C44_MAX_CNTR_WEIGHT_UOM,
-- 	C45_STORAGE_TYPE,
-- 	C46_MANUFACTURER_ITEM,
-- 	C47_NUM_SECONDARY_SERIALS,
-- 	C48_UPC_COM_PRE_LEN,
-- 	C49_IS_PRE_CONFIGURED,
-- 	C50_SUB_CLASS,
-- 	C51_EMPTY_CNTR_WEIGHT,
-- 	C52_TAG_REQ_AT_SHIPMENT,
-- 	C53_PICKING_TYPE,
-- 	C54_DEPARTMENT,
-- 	C55_CAPACITY_QUANTITY_STRATEGY,
-- 	C56_CAPACITY_VOLUME,
-- 	C57_USE_UNPLANNED_INV,
-- 	C58_PRODUCT_LINE,
-- 	C59_UNIT_HEIGHT_UOM,
-- 	C60_IS_FREEZER_REQUIRED,
-- 	C61_PRICING_QUANTITY_STRATEGY,
-- 	C62_ONHAND_SAFETY_FACTOR_PCT,
-- 	C63_COMPUTED_UNIT_COST,
-- 	C64_UNIT_WIDTH,
-- 	C65_SHORT_DESCRIPTION,
-- 	C66_TAXABLE_FLAG,
-- 	C67_CONTAINER_SIZE,
-- 	C68_ECCN_NO,
-- 	C69_TAG_CONTROL_FLAG,
-- 	C70_IS_IBA_ALLOWED,
-- 	C71_CLASS,
-- 	C72_CAPACITY_PER_ORDERED_QTY,
-- 	C73_COST_CURRENCY,
-- 	C74_IS_HAZMAT,
-- 	C75_DEFAULT_EXPIRATION_DAYS,
-- 	C76_FIXED_CAPACITY_QTY_PER_LIN,
-- 	C77_PRICING_UOM,
-- 	C78_EXTENDED_DESCRIPTION,
-- 	C79_PROCESSING_TIME,
-- 	C80_INVENTORY_MONITOR_RULE,
-- 	C81_CAN_USE_AS_SERVICE_TOOL,
-- 	C82_NMFC_CLASS,
-- 	C83_RETURN_SHIPPING_LABEL_LEVE,
-- 	C84_MAX_CNTR_WEIGHT,
-- 	C85_HARMONIZED_CODE,
-- 	C86_ORDERING_QUANTITY_STRATEGY,
-- 	C87_SIZE_CODE,
-- 	C88_OPERATIONAL_CONFIG_COMPLET,
-- 	C89_INVOICE_BASED_ON_ACTUALS,
-- 	C90_UNIT_WEIGHT_UOM,
-- 	C91_MASTER_CATALOG_ID,
-- 	C92_GLOBAL_ITEM_ID,
-- 	C93_ATP_RULE,
-- 	C94_TAG_REQ_AT_RECEIPT,
-- 	C95_UNIT_LENGTH_UOM,
-- 	C96_MODEL,
-- 	C97_CONTAINER_TYPE,
-- 	C98_PRICING_UOM_STRATEGY,
-- 	C99_IS_FIFO_TRACKED,
-- 	C100_IS_SHIPPING_ALLOWED,
-- 	C101_IS_AIR_SHIPPING_ALLOWED,
-- 	C102_RETURN_WINDOW,
-- 	C103_CREDIT_WO_RECEIPT,
-- 	C104_UNIT_WEIGHT,
-- 	C105_VOLUME_ALLOWANCE,
-- 	C106_VELOCITY_CODE,
-- 	C107_IS_RETURN_SERVICE,
-- 	C108_MANUFACTURER_NAME,
-- 	C109_TIME_SENSITIVE,
-- 	C110_DEFAULT_PRODUCT_CLASS,
-- 	C111_IS_SERIAL_TRACKED,
-- 	C112_ADVANCE_NOTIFICATION_TIME,
-- 	C113_MAX_MODIFYTS,
-- 	C114_REMOTE_MODIFYTS,
-- 	C115_ONHAND_SAFETY_FACTOR_QTY,
-- 	C116_IS_MODEL_ITEM,
-- 	C117_STATUS,
-- 	C118_IS_STANDALONE_SERVICE,
-- 	C119_CREATETS,
-- 	C120_MIN_ORDER_QUANTITY,
-- 	C121_PRICING_QUANTITY_CONV_FAC,
-- 	C122_RUN_QUANTITY,
-- 	C123_IS_FORWARDING_ALLOWED,
-- 	C124_NODE_LEVEL_INV_MONITOR_RU,
-- 	C125_COLOR_CODE,
-- 	C126_UNIT_WIDTH_UOM,
-- 	C127_EXTN_SKU_LAYOUT_ID,
-- 	C128_MODIFYTS,
-- 	C129_SERIALIZED_FLAG,
-- 	C130_CREATEUSERID,
-- 	C131_ITEM_GROUP_CODE,
-- 	C132_IS_SHIPPING_CNTR,
-- 	C133_CAPACITY_UOM,
-- 	C134_UNIT_LENGTH,
-- 	C135_BUNDLE_FULFILLMENT_MODE,
-- 	C136_FIXED_PRICING_QTY_PER_LIN,
-- 	C137_MANUFACTURER_ITEM_DESC,
-- 	C138_UOM,
-- 	C139_COUNTRY_OF_ORIGIN,
-- 	C140_SERVICE_TYPE_ID,
-- 	C141_CHARGEBACK_CATEGORY,
-- 	C142_EQUIV_35_UNIT,
-- 	C143_FULFILLMENT_TYPE,
-- 	C144_SELECTION_TEMPLATE,
-- 	C145_SHUTTERFLY_ELIGIBLE
-- )
-- values
-- (
-- 	:C1_ITEM_KEY,
-- 	:C2_ITEM_ID,
-- 	:C3_SCHEDULE_B_CODE,
-- 	:C4_KIT_CODE,
-- 	:C5_FUTURE_SAFETY_FACTOR_PCT,
-- 	:C6_IS_SUB_ON_ORDER_ALLOWED,
-- 	:C7_PRIMARY_ENTERPRISE_CODE,
-- 	:C8_MINIMUM_CAPACITY_QUANTITY,
-- 	:C9_UNSPSC,
-- 	:C10_PRIMARY_SUPPLIER,
-- 	:C11_COMMODITY_CODE,
-- 	:C12_CONFIGURED_MODEL_KEY,
-- 	:C13_MIN_NOTIFICATION_TIME,
-- 	:C14_UNIT_HEIGHT,
-- 	:C15_NAICS_CODE,
-- 	:C16_MODEL_ITEM_UOM,
-- 	:C17_CREATEPROGID,
-- 	:C18_NMFC_CODE,
-- 	:C19_REQUIRES_PROD_ASSOCIATION,
-- 	:C20_IS_PROCUREMENT_ALLOWED,
-- 	:C21_INVOLVES_SEGMENT_CHANGE,
-- 	:C22_DESCRIPTION,
-- 	:C23_SYNCTS,
-- 	:C24_MAX_ORDER_QUANTITY,
-- 	:C25_IS_PARCEL_SHIPPING_ALLOWED,
-- 	:C26_IS_RETURNABLE,
-- 	:C27_POSTING_CLASSIFICATION,
-- 	:C28_MODIFYUSERID,
-- 	:C29_MODIFYPROGID,
-- 	:C30_CAPACITY_VOLUME_UOM,
-- 	:C31_IS_PICKUP_ALLOWED,
-- 	:C32_LEAD_TIME,
-- 	:C33_EXTN_LOOK_SELECTION_ALLOWE,
-- 	:C34_IS_DELIVERY_ALLOWED,
-- 	:C35_LOCKID,
-- 	:C36_IS_CONFIGURABLE,
-- 	:C37_SHP_CONSOL_WINDOW,
-- 	:C38_HAZMAT_CLASS,
-- 	:C39_TAX_PRODUCT_CODE,
-- 	:C40_UNIT_COST,
-- 	:C41_ITEM_TYPE,
-- 	:C42_ORGANIZATION_CODE,
-- 	:C43_ASSUME_INFINITE_INVENTORY,
-- 	:C44_MAX_CNTR_WEIGHT_UOM,
-- 	:C45_STORAGE_TYPE,
-- 	:C46_MANUFACTURER_ITEM,
-- 	:C47_NUM_SECONDARY_SERIALS,
-- 	:C48_UPC_COM_PRE_LEN,
-- 	:C49_IS_PRE_CONFIGURED,
-- 	:C50_SUB_CLASS,
-- 	:C51_EMPTY_CNTR_WEIGHT,
-- 	:C52_TAG_REQ_AT_SHIPMENT,
-- 	:C53_PICKING_TYPE,
-- 	:C54_DEPARTMENT,
-- 	:C55_CAPACITY_QUANTITY_STRATEGY,
-- 	:C56_CAPACITY_VOLUME,
-- 	:C57_USE_UNPLANNED_INV,
-- 	:C58_PRODUCT_LINE,
-- 	:C59_UNIT_HEIGHT_UOM,
-- 	:C60_IS_FREEZER_REQUIRED,
-- 	:C61_PRICING_QUANTITY_STRATEGY,
-- 	:C62_ONHAND_SAFETY_FACTOR_PCT,
-- 	:C63_COMPUTED_UNIT_COST,
-- 	:C64_UNIT_WIDTH,
-- 	:C65_SHORT_DESCRIPTION,
-- 	:C66_TAXABLE_FLAG,
-- 	:C67_CONTAINER_SIZE,
-- 	:C68_ECCN_NO,
-- 	:C69_TAG_CONTROL_FLAG,
-- 	:C70_IS_IBA_ALLOWED,
-- 	:C71_CLASS,
-- 	:C72_CAPACITY_PER_ORDERED_QTY,
-- 	:C73_COST_CURRENCY,
-- 	:C74_IS_HAZMAT,
-- 	:C75_DEFAULT_EXPIRATION_DAYS,
-- 	:C76_FIXED_CAPACITY_QTY_PER_LIN,
-- 	:C77_PRICING_UOM,
-- 	:C78_EXTENDED_DESCRIPTION,
-- 	:C79_PROCESSING_TIME,
-- 	:C80_INVENTORY_MONITOR_RULE,
-- 	:C81_CAN_USE_AS_SERVICE_TOOL,
-- 	:C82_NMFC_CLASS,
-- 	:C83_RETURN_SHIPPING_LABEL_LEVE,
-- 	:C84_MAX_CNTR_WEIGHT,
-- 	:C85_HARMONIZED_CODE,
-- 	:C86_ORDERING_QUANTITY_STRATEGY,
-- 	:C87_SIZE_CODE,
-- 	:C88_OPERATIONAL_CONFIG_COMPLET,
-- 	:C89_INVOICE_BASED_ON_ACTUALS,
-- 	:C90_UNIT_WEIGHT_UOM,
-- 	:C91_MASTER_CATALOG_ID,
-- 	:C92_GLOBAL_ITEM_ID,
-- 	:C93_ATP_RULE,
-- 	:C94_TAG_REQ_AT_RECEIPT,
-- 	:C95_UNIT_LENGTH_UOM,
-- 	:C96_MODEL,
-- 	:C97_CONTAINER_TYPE,
-- 	:C98_PRICING_UOM_STRATEGY,
-- 	:C99_IS_FIFO_TRACKED,
-- 	:C100_IS_SHIPPING_ALLOWED,
-- 	:C101_IS_AIR_SHIPPING_ALLOWED,
-- 	:C102_RETURN_WINDOW,
-- 	:C103_CREDIT_WO_RECEIPT,
-- 	:C104_UNIT_WEIGHT,
-- 	:C105_VOLUME_ALLOWANCE,
-- 	:C106_VELOCITY_CODE,
-- 	:C107_IS_RETURN_SERVICE,
-- 	:C108_MANUFACTURER_NAME,
-- 	:C109_TIME_SENSITIVE,
-- 	:C110_DEFAULT_PRODUCT_CLASS,
-- 	:C111_IS_SERIAL_TRACKED,
-- 	:C112_ADVANCE_NOTIFICATION_TIME,
-- 	:C113_MAX_MODIFYTS,
-- 	:C114_REMOTE_MODIFYTS,
-- 	:C115_ONHAND_SAFETY_FACTOR_QTY,
-- 	:C116_IS_MODEL_ITEM,
-- 	:C117_STATUS,
-- 	:C118_IS_STANDALONE_SERVICE,
-- 	:C119_CREATETS,
-- 	:C120_MIN_ORDER_QUANTITY,
-- 	:C121_PRICING_QUANTITY_CONV_FAC,
-- 	:C122_RUN_QUANTITY,
-- 	:C123_IS_FORWARDING_ALLOWED,
-- 	:C124_NODE_LEVEL_INV_MONITOR_RU,
-- 	:C125_COLOR_CODE,
-- 	:C126_UNIT_WIDTH_UOM,
-- 	:C127_EXTN_SKU_LAYOUT_ID,
-- 	:C128_MODIFYTS,
-- 	:C129_SERIALIZED_FLAG,
-- 	:C130_CREATEUSERID,
-- 	:C131_ITEM_GROUP_CODE,
-- 	:C132_IS_SHIPPING_CNTR,
-- 	:C133_CAPACITY_UOM,
-- 	:C134_UNIT_LENGTH,
-- 	:C135_BUNDLE_FULFILLMENT_MODE,
-- 	:C136_FIXED_PRICING_QTY_PER_LIN,
-- 	:C137_MANUFACTURER_ITEM_DESC,
-- 	:C138_UOM,
-- 	:C139_COUNTRY_OF_ORIGIN,
-- 	:C140_SERVICE_TYPE_ID,
-- 	:C141_CHARGEBACK_CATEGORY,
-- 	:C142_EQUIV_35_UNIT,
-- 	:C143_FULFILLMENT_TYPE,
-- 	:C144_SELECTION_TEMPLATE,
-- 	:C145_SHUTTERFLY_ELIGIBLE
-- )

-- &


/*-----------------------------------------------*/
/* TASK No. 7 */
/* Analyze work table */



BEGIN
DBMS_STATS.GATHER_TABLE_STATS (
    ownname =>	'RAX_APP_USER',
    tabname =>	'C$_0OMS3_ITEM_STG',
    estimate_percent =>	DBMS_STATS.AUTO_SAMPLE_SIZE
);
END;




&


/*-----------------------------------------------*/
/* TASK No. 9 */
/* Set vID */

/* NONE or SET VARIABLE STATEMENT FOUND, CHECK ODI TASK NO. 9 */




/*-----------------------------------------------*/
/* TASK No. 10 */
/* Drop flow table */

BEGIN  
   EXECUTE IMMEDIATE 'drop table RAX_APP_USER.I$_OMS3_ITEM_STG2079001';  
EXCEPTION  
   WHEN OTHERS THEN  
      IF SQLCODE != -942 THEN  
         RAISE;  
      END IF;  
END;

&


/*-----------------------------------------------*/
/* TASK No. 11 */
/* Create flow table I$ */

create table RAX_APP_USER.I$_OMS3_ITEM_STG2079001
(
	ITEM_KEY	VARCHAR2(24) NULL,
	ITEM_ID	VARCHAR2(40) NULL,
	SCHEDULE_B_CODE	VARCHAR2(40) NULL,
	KIT_CODE	VARCHAR2(20) NULL,
	FUTURE_SAFETY_FACTOR_PCT	NUMBER NULL,
	IS_SUB_ON_ORDER_ALLOWED	VARCHAR2(1) NULL,
	PRIMARY_ENTERPRISE_CODE	VARCHAR2(24) NULL,
	MINIMUM_CAPACITY_QUANTITY	NUMBER NULL,
	UNSPSC	VARCHAR2(40) NULL,
	PRIMARY_SUPPLIER	VARCHAR2(24) NULL,
	COMMODITY_CODE	VARCHAR2(40) NULL,
	CONFIGURED_MODEL_KEY	VARCHAR2(24) NULL,
	MIN_NOTIFICATION_TIME	NUMBER NULL,
	UNIT_HEIGHT	NUMBER NULL,
	NAICS_CODE	VARCHAR2(40) NULL,
	MODEL_ITEM_UOM	VARCHAR2(40) NULL,
	CREATEPROGID	VARCHAR2(40) NULL,
	NMFC_CODE	VARCHAR2(40) NULL,
	REQUIRES_PROD_ASSOCIATION	VARCHAR2(1) NULL,
	IS_PROCUREMENT_ALLOWED	VARCHAR2(1) NULL,
	INVOLVES_SEGMENT_CHANGE	VARCHAR2(1) NULL,
	DESCRIPTION	VARCHAR2(200) NULL,
	SYNCTS	DATE NULL,
	MAX_ORDER_QUANTITY	NUMBER NULL,
	IS_PARCEL_SHIPPING_ALLOWED	VARCHAR2(1) NULL,
	IS_RETURNABLE	VARCHAR2(1) NULL,
	POSTING_CLASSIFICATION	VARCHAR2(40) NULL,
	MODIFYUSERID	VARCHAR2(40) NULL,
	MODIFYPROGID	VARCHAR2(40) NULL,
	CAPACITY_VOLUME_UOM	VARCHAR2(40) NULL,
	IS_PICKUP_ALLOWED	VARCHAR2(1) NULL,
	LEAD_TIME	NUMBER NULL,
	EXTN_LOOK_SELECTION_ALLOWED	VARCHAR2(1) NULL,
	IS_DELIVERY_ALLOWED	VARCHAR2(1) NULL,
	LOCKID	NUMBER NULL,
	IS_CONFIGURABLE	VARCHAR2(1) NULL,
	SHP_CONSOL_WINDOW	NUMBER NULL,
	HAZMAT_CLASS	VARCHAR2(40) NULL,
	TAX_PRODUCT_CODE	VARCHAR2(40) NULL,
	UNIT_COST	NUMBER NULL,
	ITEM_TYPE	VARCHAR2(40) NULL,
	ORGANIZATION_CODE	VARCHAR2(24) NULL,
	ASSUME_INFINITE_INVENTORY	VARCHAR2(1) NULL,
	MAX_CNTR_WEIGHT_UOM	VARCHAR2(40) NULL,
	STORAGE_TYPE	VARCHAR2(40) NULL,
	MANUFACTURER_ITEM	VARCHAR2(100) NULL,
	NUM_SECONDARY_SERIALS	NUMBER NULL,
	UPC_COM_PRE_LEN	NUMBER NULL,
	IS_PRE_CONFIGURED	VARCHAR2(1) NULL,
	SUB_CLASS	VARCHAR2(100) NULL,
	EMPTY_CNTR_WEIGHT	NUMBER NULL,
	TAG_REQ_AT_SHIPMENT	VARCHAR2(1) NULL,
	PICKING_TYPE	VARCHAR2(40) NULL,
	DEPARTMENT	VARCHAR2(100) NULL,
	CAPACITY_QUANTITY_STRATEGY	VARCHAR2(20) NULL,
	CAPACITY_VOLUME	NUMBER NULL,
	USE_UNPLANNED_INV	VARCHAR2(1) NULL,
	PRODUCT_LINE	VARCHAR2(100) NULL,
	UNIT_HEIGHT_UOM	VARCHAR2(40) NULL,
	IS_FREEZER_REQUIRED	VARCHAR2(1) NULL,
	PRICING_QUANTITY_STRATEGY	VARCHAR2(20) NULL,
	ONHAND_SAFETY_FACTOR_PCT	NUMBER NULL,
	COMPUTED_UNIT_COST	NUMBER NULL,
	UNIT_WIDTH	NUMBER NULL,
	SHORT_DESCRIPTION	VARCHAR2(100) NULL,
	TAXABLE_FLAG	VARCHAR2(1) NULL,
	CONTAINER_SIZE	VARCHAR2(24) NULL,
	ECCN_NO	VARCHAR2(40) NULL,
	TAG_CONTROL_FLAG	VARCHAR2(1) NULL,
	IS_IBA_ALLOWED	VARCHAR2(1) NULL,
	CLASS	VARCHAR2(100) NULL,
	CAPACITY_PER_ORDERED_QTY	NUMBER NULL,
	COST_CURRENCY	VARCHAR2(20) NULL,
	IS_HAZMAT	VARCHAR2(1) NULL,
	DEFAULT_EXPIRATION_DAYS	NUMBER NULL,
	FIXED_CAPACITY_QTY_PER_LINE	NUMBER NULL,
	PRICING_UOM	VARCHAR2(40) NULL,
	EXTENDED_DESCRIPTION	VARCHAR2(2000) NULL,
	PROCESSING_TIME	NUMBER NULL,
	INVENTORY_MONITOR_RULE	VARCHAR2(24) NULL,
	CAN_USE_AS_SERVICE_TOOL	VARCHAR2(1) NULL,
	NMFC_CLASS	VARCHAR2(100) NULL,
	RETURN_SHIPPING_LABEL_LEVEL	VARCHAR2(1) NULL,
	MAX_CNTR_WEIGHT	NUMBER NULL,
	HARMONIZED_CODE	VARCHAR2(40) NULL,
	ORDERING_QUANTITY_STRATEGY	VARCHAR2(20) NULL,
	SIZE_CODE	VARCHAR2(40) NULL,
	OPERATIONAL_CONFIG_COMPLETE	VARCHAR2(1) NULL,
	INVOICE_BASED_ON_ACTUALS	VARCHAR2(1) NULL,
	UNIT_WEIGHT_UOM	VARCHAR2(40) NULL,
	MASTER_CATALOG_ID	VARCHAR2(40) NULL,
	GLOBAL_ITEM_ID	VARCHAR2(128) NULL,
	ATP_RULE	VARCHAR2(24) NULL,
	TAG_REQ_AT_RECEIPT	VARCHAR2(1) NULL,
	UNIT_LENGTH_UOM	VARCHAR2(40) NULL,
	MODEL	VARCHAR2(40) NULL,
	CONTAINER_TYPE	VARCHAR2(24) NULL,
	PRICING_UOM_STRATEGY	VARCHAR2(20) NULL,
	IS_FIFO_TRACKED	VARCHAR2(1) NULL,
	IS_SHIPPING_ALLOWED	VARCHAR2(1) NULL,
	IS_AIR_SHIPPING_ALLOWED	VARCHAR2(1) NULL,
	RETURN_WINDOW	NUMBER NULL,
	CREDIT_WO_RECEIPT	VARCHAR2(1) NULL,
	UNIT_WEIGHT	NUMBER NULL,
	VOLUME_ALLOWANCE	NUMBER NULL,
	VELOCITY_CODE	VARCHAR2(40) NULL,
	IS_RETURN_SERVICE	VARCHAR2(1) NULL,
	MANUFACTURER_NAME	VARCHAR2(50) NULL,
	TIME_SENSITIVE	VARCHAR2(1) NULL,
	DEFAULT_PRODUCT_CLASS	VARCHAR2(10) NULL,
	IS_SERIAL_TRACKED	VARCHAR2(1) NULL,
	ADVANCE_NOTIFICATION_TIME	NUMBER NULL,
	MAX_MODIFYTS	DATE NULL,
	REMOTE_MODIFYTS	DATE NULL,
	ONHAND_SAFETY_FACTOR_QTY	NUMBER NULL,
	IS_MODEL_ITEM	VARCHAR2(1) NULL,
	STATUS	VARCHAR2(15) NULL,
	IS_STANDALONE_SERVICE	VARCHAR2(1) NULL,
	CREATETS	DATE NULL,
	MIN_ORDER_QUANTITY	NUMBER NULL,
	PRICING_QUANTITY_CONV_FACTOR	NUMBER NULL,
	RUN_QUANTITY	NUMBER NULL,
	IS_FORWARDING_ALLOWED	VARCHAR2(1) NULL,
	NODE_LEVEL_INV_MONITOR_RULE	VARCHAR2(24) NULL,
	COLOR_CODE	VARCHAR2(40) NULL,
	UNIT_WIDTH_UOM	VARCHAR2(40) NULL,
	EXTN_SKU_LAYOUT_ID	VARCHAR2(40) NULL,
	MODIFYTS	DATE NULL,
	SERIALIZED_FLAG	VARCHAR2(1) NULL,
	CREATEUSERID	VARCHAR2(40) NULL,
	ITEM_GROUP_CODE	VARCHAR2(20) NULL,
	IS_SHIPPING_CNTR	VARCHAR2(1) NULL,
	CAPACITY_UOM	VARCHAR2(40) NULL,
	UNIT_LENGTH	NUMBER NULL,
	BUNDLE_FULFILLMENT_MODE	VARCHAR2(2) NULL,
	FIXED_PRICING_QTY_PER_LINE	NUMBER NULL,
	MANUFACTURER_ITEM_DESC	VARCHAR2(255) NULL,
	UOM	VARCHAR2(40) NULL,
	COUNTRY_OF_ORIGIN	VARCHAR2(40) NULL,
	SERVICE_TYPE_ID	VARCHAR2(24) NULL,
	CHARGEBACK_CATEGORY	VARCHAR2(100) NULL,
	EQUIV_35_UNIT	NUMBER NULL,
	ODS_CREATE_DATE	DATE NULL,
	ODS_MODIFY_DATE	DATE NULL,
	FULFILLMENT_TYPE	VARCHAR2(25) NULL,
	SELECTION_TEMPLATE	VARCHAR2(50) NULL,
	SHUTTERFLY_ELIGIBLE	VARCHAR2(2000) NULL
	,IND_UPDATE		char(1)
)
NOLOGGING

&


/*-----------------------------------------------*/
/* TASK No. 12 */
/* Insert flow into I$ table */

/* DETECTION_STRATEGY = NOT_EXISTS */
 


  


insert into	RAX_APP_USER.I$_OMS3_ITEM_STG2079001
(
	ITEM_KEY,
	ITEM_ID,
	SCHEDULE_B_CODE,
	KIT_CODE,
	FUTURE_SAFETY_FACTOR_PCT,
	IS_SUB_ON_ORDER_ALLOWED,
	PRIMARY_ENTERPRISE_CODE,
	MINIMUM_CAPACITY_QUANTITY,
	UNSPSC,
	PRIMARY_SUPPLIER,
	COMMODITY_CODE,
	CONFIGURED_MODEL_KEY,
	MIN_NOTIFICATION_TIME,
	UNIT_HEIGHT,
	NAICS_CODE,
	MODEL_ITEM_UOM,
	CREATEPROGID,
	NMFC_CODE,
	REQUIRES_PROD_ASSOCIATION,
	IS_PROCUREMENT_ALLOWED,
	INVOLVES_SEGMENT_CHANGE,
	DESCRIPTION,
	SYNCTS,
	MAX_ORDER_QUANTITY,
	IS_PARCEL_SHIPPING_ALLOWED,
	IS_RETURNABLE,
	POSTING_CLASSIFICATION,
	MODIFYUSERID,
	MODIFYPROGID,
	CAPACITY_VOLUME_UOM,
	IS_PICKUP_ALLOWED,
	LEAD_TIME,
	EXTN_LOOK_SELECTION_ALLOWED,
	IS_DELIVERY_ALLOWED,
	LOCKID,
	IS_CONFIGURABLE,
	SHP_CONSOL_WINDOW,
	HAZMAT_CLASS,
	TAX_PRODUCT_CODE,
	UNIT_COST,
	ITEM_TYPE,
	ORGANIZATION_CODE,
	ASSUME_INFINITE_INVENTORY,
	MAX_CNTR_WEIGHT_UOM,
	STORAGE_TYPE,
	MANUFACTURER_ITEM,
	NUM_SECONDARY_SERIALS,
	UPC_COM_PRE_LEN,
	IS_PRE_CONFIGURED,
	SUB_CLASS,
	EMPTY_CNTR_WEIGHT,
	TAG_REQ_AT_SHIPMENT,
	PICKING_TYPE,
	DEPARTMENT,
	CAPACITY_QUANTITY_STRATEGY,
	CAPACITY_VOLUME,
	USE_UNPLANNED_INV,
	PRODUCT_LINE,
	UNIT_HEIGHT_UOM,
	IS_FREEZER_REQUIRED,
	PRICING_QUANTITY_STRATEGY,
	ONHAND_SAFETY_FACTOR_PCT,
	COMPUTED_UNIT_COST,
	UNIT_WIDTH,
	SHORT_DESCRIPTION,
	TAXABLE_FLAG,
	CONTAINER_SIZE,
	ECCN_NO,
	TAG_CONTROL_FLAG,
	IS_IBA_ALLOWED,
	CLASS,
	CAPACITY_PER_ORDERED_QTY,
	COST_CURRENCY,
	IS_HAZMAT,
	DEFAULT_EXPIRATION_DAYS,
	FIXED_CAPACITY_QTY_PER_LINE,
	PRICING_UOM,
	EXTENDED_DESCRIPTION,
	PROCESSING_TIME,
	INVENTORY_MONITOR_RULE,
	CAN_USE_AS_SERVICE_TOOL,
	NMFC_CLASS,
	RETURN_SHIPPING_LABEL_LEVEL,
	MAX_CNTR_WEIGHT,
	HARMONIZED_CODE,
	ORDERING_QUANTITY_STRATEGY,
	SIZE_CODE,
	OPERATIONAL_CONFIG_COMPLETE,
	INVOICE_BASED_ON_ACTUALS,
	UNIT_WEIGHT_UOM,
	MASTER_CATALOG_ID,
	GLOBAL_ITEM_ID,
	ATP_RULE,
	TAG_REQ_AT_RECEIPT,
	UNIT_LENGTH_UOM,
	MODEL,
	CONTAINER_TYPE,
	PRICING_UOM_STRATEGY,
	IS_FIFO_TRACKED,
	IS_SHIPPING_ALLOWED,
	IS_AIR_SHIPPING_ALLOWED,
	RETURN_WINDOW,
	CREDIT_WO_RECEIPT,
	UNIT_WEIGHT,
	VOLUME_ALLOWANCE,
	VELOCITY_CODE,
	IS_RETURN_SERVICE,
	MANUFACTURER_NAME,
	TIME_SENSITIVE,
	DEFAULT_PRODUCT_CLASS,
	IS_SERIAL_TRACKED,
	ADVANCE_NOTIFICATION_TIME,
	MAX_MODIFYTS,
	REMOTE_MODIFYTS,
	ONHAND_SAFETY_FACTOR_QTY,
	IS_MODEL_ITEM,
	STATUS,
	IS_STANDALONE_SERVICE,
	CREATETS,
	MIN_ORDER_QUANTITY,
	PRICING_QUANTITY_CONV_FACTOR,
	RUN_QUANTITY,
	IS_FORWARDING_ALLOWED,
	NODE_LEVEL_INV_MONITOR_RULE,
	COLOR_CODE,
	UNIT_WIDTH_UOM,
	EXTN_SKU_LAYOUT_ID,
	MODIFYTS,
	SERIALIZED_FLAG,
	CREATEUSERID,
	ITEM_GROUP_CODE,
	IS_SHIPPING_CNTR,
	CAPACITY_UOM,
	UNIT_LENGTH,
	BUNDLE_FULFILLMENT_MODE,
	FIXED_PRICING_QTY_PER_LINE,
	MANUFACTURER_ITEM_DESC,
	UOM,
	COUNTRY_OF_ORIGIN,
	SERVICE_TYPE_ID,
	CHARGEBACK_CATEGORY,
	EQUIV_35_UNIT,
	FULFILLMENT_TYPE,
	SELECTION_TEMPLATE,
	SHUTTERFLY_ELIGIBLE,
	IND_UPDATE
)
select 
ITEM_KEY,
	ITEM_ID,
	SCHEDULE_B_CODE,
	KIT_CODE,
	FUTURE_SAFETY_FACTOR_PCT,
	IS_SUB_ON_ORDER_ALLOWED,
	PRIMARY_ENTERPRISE_CODE,
	MINIMUM_CAPACITY_QUANTITY,
	UNSPSC,
	PRIMARY_SUPPLIER,
	COMMODITY_CODE,
	CONFIGURED_MODEL_KEY,
	MIN_NOTIFICATION_TIME,
	UNIT_HEIGHT,
	NAICS_CODE,
	MODEL_ITEM_UOM,
	CREATEPROGID,
	NMFC_CODE,
	REQUIRES_PROD_ASSOCIATION,
	IS_PROCUREMENT_ALLOWED,
	INVOLVES_SEGMENT_CHANGE,
	DESCRIPTION,
	SYNCTS,
	MAX_ORDER_QUANTITY,
	IS_PARCEL_SHIPPING_ALLOWED,
	IS_RETURNABLE,
	POSTING_CLASSIFICATION,
	MODIFYUSERID,
	MODIFYPROGID,
	CAPACITY_VOLUME_UOM,
	IS_PICKUP_ALLOWED,
	LEAD_TIME,
	EXTN_LOOK_SELECTION_ALLOWED,
	IS_DELIVERY_ALLOWED,
	LOCKID,
	IS_CONFIGURABLE,
	SHP_CONSOL_WINDOW,
	HAZMAT_CLASS,
	TAX_PRODUCT_CODE,
	UNIT_COST,
	ITEM_TYPE,
	ORGANIZATION_CODE,
	ASSUME_INFINITE_INVENTORY,
	MAX_CNTR_WEIGHT_UOM,
	STORAGE_TYPE,
	MANUFACTURER_ITEM,
	NUM_SECONDARY_SERIALS,
	UPC_COM_PRE_LEN,
	IS_PRE_CONFIGURED,
	SUB_CLASS,
	EMPTY_CNTR_WEIGHT,
	TAG_REQ_AT_SHIPMENT,
	PICKING_TYPE,
	DEPARTMENT,
	CAPACITY_QUANTITY_STRATEGY,
	CAPACITY_VOLUME,
	USE_UNPLANNED_INV,
	PRODUCT_LINE,
	UNIT_HEIGHT_UOM,
	IS_FREEZER_REQUIRED,
	PRICING_QUANTITY_STRATEGY,
	ONHAND_SAFETY_FACTOR_PCT,
	COMPUTED_UNIT_COST,
	UNIT_WIDTH,
	SHORT_DESCRIPTION,
	TAXABLE_FLAG,
	CONTAINER_SIZE,
	ECCN_NO,
	TAG_CONTROL_FLAG,
	IS_IBA_ALLOWED,
	CLASS,
	CAPACITY_PER_ORDERED_QTY,
	COST_CURRENCY,
	IS_HAZMAT,
	DEFAULT_EXPIRATION_DAYS,
	FIXED_CAPACITY_QTY_PER_LINE,
	PRICING_UOM,
	EXTENDED_DESCRIPTION,
	PROCESSING_TIME,
	INVENTORY_MONITOR_RULE,
	CAN_USE_AS_SERVICE_TOOL,
	NMFC_CLASS,
	RETURN_SHIPPING_LABEL_LEVEL,
	MAX_CNTR_WEIGHT,
	HARMONIZED_CODE,
	ORDERING_QUANTITY_STRATEGY,
	SIZE_CODE,
	OPERATIONAL_CONFIG_COMPLETE,
	INVOICE_BASED_ON_ACTUALS,
	UNIT_WEIGHT_UOM,
	MASTER_CATALOG_ID,
	GLOBAL_ITEM_ID,
	ATP_RULE,
	TAG_REQ_AT_RECEIPT,
	UNIT_LENGTH_UOM,
	MODEL,
	CONTAINER_TYPE,
	PRICING_UOM_STRATEGY,
	IS_FIFO_TRACKED,
	IS_SHIPPING_ALLOWED,
	IS_AIR_SHIPPING_ALLOWED,
	RETURN_WINDOW,
	CREDIT_WO_RECEIPT,
	UNIT_WEIGHT,
	VOLUME_ALLOWANCE,
	VELOCITY_CODE,
	IS_RETURN_SERVICE,
	MANUFACTURER_NAME,
	TIME_SENSITIVE,
	DEFAULT_PRODUCT_CLASS,
	IS_SERIAL_TRACKED,
	ADVANCE_NOTIFICATION_TIME,
	MAX_MODIFYTS,
	REMOTE_MODIFYTS,
	ONHAND_SAFETY_FACTOR_QTY,
	IS_MODEL_ITEM,
	STATUS,
	IS_STANDALONE_SERVICE,
	CREATETS,
	MIN_ORDER_QUANTITY,
	PRICING_QUANTITY_CONV_FACTOR,
	RUN_QUANTITY,
	IS_FORWARDING_ALLOWED,
	NODE_LEVEL_INV_MONITOR_RULE,
	COLOR_CODE,
	UNIT_WIDTH_UOM,
	EXTN_SKU_LAYOUT_ID,
	MODIFYTS,
	SERIALIZED_FLAG,
	CREATEUSERID,
	ITEM_GROUP_CODE,
	IS_SHIPPING_CNTR,
	CAPACITY_UOM,
	UNIT_LENGTH,
	BUNDLE_FULFILLMENT_MODE,
	FIXED_PRICING_QTY_PER_LINE,
	MANUFACTURER_ITEM_DESC,
	UOM,
	COUNTRY_OF_ORIGIN,
	SERVICE_TYPE_ID,
	CHARGEBACK_CATEGORY,
	EQUIV_35_UNIT,
	FULFILLMENT_TYPE,
	SELECTION_TEMPLATE,
	SHUTTERFLY_ELIGIBLE,
	IND_UPDATE
 from (


select 	 
	
	C1_ITEM_KEY ITEM_KEY,
	C2_ITEM_ID ITEM_ID,
	C3_SCHEDULE_B_CODE SCHEDULE_B_CODE,
	C4_KIT_CODE KIT_CODE,
	C5_FUTURE_SAFETY_FACTOR_PCT FUTURE_SAFETY_FACTOR_PCT,
	C6_IS_SUB_ON_ORDER_ALLOWED IS_SUB_ON_ORDER_ALLOWED,
	C7_PRIMARY_ENTERPRISE_CODE PRIMARY_ENTERPRISE_CODE,
	C8_MINIMUM_CAPACITY_QUANTITY MINIMUM_CAPACITY_QUANTITY,
	C9_UNSPSC UNSPSC,
	C10_PRIMARY_SUPPLIER PRIMARY_SUPPLIER,
	C11_COMMODITY_CODE COMMODITY_CODE,
	C12_CONFIGURED_MODEL_KEY CONFIGURED_MODEL_KEY,
	C13_MIN_NOTIFICATION_TIME MIN_NOTIFICATION_TIME,
	C14_UNIT_HEIGHT UNIT_HEIGHT,
	C15_NAICS_CODE NAICS_CODE,
	C16_MODEL_ITEM_UOM MODEL_ITEM_UOM,
	C17_CREATEPROGID CREATEPROGID,
	C18_NMFC_CODE NMFC_CODE,
	C19_REQUIRES_PROD_ASSOCIATION REQUIRES_PROD_ASSOCIATION,
	C20_IS_PROCUREMENT_ALLOWED IS_PROCUREMENT_ALLOWED,
	C21_INVOLVES_SEGMENT_CHANGE INVOLVES_SEGMENT_CHANGE,
	C22_DESCRIPTION DESCRIPTION,
	C23_SYNCTS SYNCTS,
	C24_MAX_ORDER_QUANTITY MAX_ORDER_QUANTITY,
	C25_IS_PARCEL_SHIPPING_ALLOWED IS_PARCEL_SHIPPING_ALLOWED,
	C26_IS_RETURNABLE IS_RETURNABLE,
	C27_POSTING_CLASSIFICATION POSTING_CLASSIFICATION,
	C28_MODIFYUSERID MODIFYUSERID,
	C29_MODIFYPROGID MODIFYPROGID,
	C30_CAPACITY_VOLUME_UOM CAPACITY_VOLUME_UOM,
	C31_IS_PICKUP_ALLOWED IS_PICKUP_ALLOWED,
	C32_LEAD_TIME LEAD_TIME,
	C33_EXTN_LOOK_SELECTION_ALLOWE EXTN_LOOK_SELECTION_ALLOWED,
	C34_IS_DELIVERY_ALLOWED IS_DELIVERY_ALLOWED,
	C35_LOCKID LOCKID,
	C36_IS_CONFIGURABLE IS_CONFIGURABLE,
	C37_SHP_CONSOL_WINDOW SHP_CONSOL_WINDOW,
	C38_HAZMAT_CLASS HAZMAT_CLASS,
	C39_TAX_PRODUCT_CODE TAX_PRODUCT_CODE,
	C40_UNIT_COST UNIT_COST,
	C41_ITEM_TYPE ITEM_TYPE,
	C42_ORGANIZATION_CODE ORGANIZATION_CODE,
	C43_ASSUME_INFINITE_INVENTORY ASSUME_INFINITE_INVENTORY,
	C44_MAX_CNTR_WEIGHT_UOM MAX_CNTR_WEIGHT_UOM,
	C45_STORAGE_TYPE STORAGE_TYPE,
	C46_MANUFACTURER_ITEM MANUFACTURER_ITEM,
	C47_NUM_SECONDARY_SERIALS NUM_SECONDARY_SERIALS,
	C48_UPC_COM_PRE_LEN UPC_COM_PRE_LEN,
	C49_IS_PRE_CONFIGURED IS_PRE_CONFIGURED,
	C50_SUB_CLASS SUB_CLASS,
	C51_EMPTY_CNTR_WEIGHT EMPTY_CNTR_WEIGHT,
	C52_TAG_REQ_AT_SHIPMENT TAG_REQ_AT_SHIPMENT,
	C53_PICKING_TYPE PICKING_TYPE,
	C54_DEPARTMENT DEPARTMENT,
	C55_CAPACITY_QUANTITY_STRATEGY CAPACITY_QUANTITY_STRATEGY,
	C56_CAPACITY_VOLUME CAPACITY_VOLUME,
	C57_USE_UNPLANNED_INV USE_UNPLANNED_INV,
	C58_PRODUCT_LINE PRODUCT_LINE,
	C59_UNIT_HEIGHT_UOM UNIT_HEIGHT_UOM,
	C60_IS_FREEZER_REQUIRED IS_FREEZER_REQUIRED,
	C61_PRICING_QUANTITY_STRATEGY PRICING_QUANTITY_STRATEGY,
	C62_ONHAND_SAFETY_FACTOR_PCT ONHAND_SAFETY_FACTOR_PCT,
	C63_COMPUTED_UNIT_COST COMPUTED_UNIT_COST,
	C64_UNIT_WIDTH UNIT_WIDTH,
	C65_SHORT_DESCRIPTION SHORT_DESCRIPTION,
	C66_TAXABLE_FLAG TAXABLE_FLAG,
	C67_CONTAINER_SIZE CONTAINER_SIZE,
	C68_ECCN_NO ECCN_NO,
	C69_TAG_CONTROL_FLAG TAG_CONTROL_FLAG,
	C70_IS_IBA_ALLOWED IS_IBA_ALLOWED,
	C71_CLASS CLASS,
	C72_CAPACITY_PER_ORDERED_QTY CAPACITY_PER_ORDERED_QTY,
	C73_COST_CURRENCY COST_CURRENCY,
	C74_IS_HAZMAT IS_HAZMAT,
	C75_DEFAULT_EXPIRATION_DAYS DEFAULT_EXPIRATION_DAYS,
	C76_FIXED_CAPACITY_QTY_PER_LIN FIXED_CAPACITY_QTY_PER_LINE,
	C77_PRICING_UOM PRICING_UOM,
	C78_EXTENDED_DESCRIPTION EXTENDED_DESCRIPTION,
	C79_PROCESSING_TIME PROCESSING_TIME,
	C80_INVENTORY_MONITOR_RULE INVENTORY_MONITOR_RULE,
	C81_CAN_USE_AS_SERVICE_TOOL CAN_USE_AS_SERVICE_TOOL,
	C82_NMFC_CLASS NMFC_CLASS,
	C83_RETURN_SHIPPING_LABEL_LEVE RETURN_SHIPPING_LABEL_LEVEL,
	C84_MAX_CNTR_WEIGHT MAX_CNTR_WEIGHT,
	C85_HARMONIZED_CODE HARMONIZED_CODE,
	C86_ORDERING_QUANTITY_STRATEGY ORDERING_QUANTITY_STRATEGY,
	C87_SIZE_CODE SIZE_CODE,
	C88_OPERATIONAL_CONFIG_COMPLET OPERATIONAL_CONFIG_COMPLETE,
	C89_INVOICE_BASED_ON_ACTUALS INVOICE_BASED_ON_ACTUALS,
	C90_UNIT_WEIGHT_UOM UNIT_WEIGHT_UOM,
	C91_MASTER_CATALOG_ID MASTER_CATALOG_ID,
	C92_GLOBAL_ITEM_ID GLOBAL_ITEM_ID,
	C93_ATP_RULE ATP_RULE,
	C94_TAG_REQ_AT_RECEIPT TAG_REQ_AT_RECEIPT,
	C95_UNIT_LENGTH_UOM UNIT_LENGTH_UOM,
	C96_MODEL MODEL,
	C97_CONTAINER_TYPE CONTAINER_TYPE,
	C98_PRICING_UOM_STRATEGY PRICING_UOM_STRATEGY,
	C99_IS_FIFO_TRACKED IS_FIFO_TRACKED,
	C100_IS_SHIPPING_ALLOWED IS_SHIPPING_ALLOWED,
	C101_IS_AIR_SHIPPING_ALLOWED IS_AIR_SHIPPING_ALLOWED,
	C102_RETURN_WINDOW RETURN_WINDOW,
	C103_CREDIT_WO_RECEIPT CREDIT_WO_RECEIPT,
	C104_UNIT_WEIGHT UNIT_WEIGHT,
	C105_VOLUME_ALLOWANCE VOLUME_ALLOWANCE,
	C106_VELOCITY_CODE VELOCITY_CODE,
	C107_IS_RETURN_SERVICE IS_RETURN_SERVICE,
	C108_MANUFACTURER_NAME MANUFACTURER_NAME,
	C109_TIME_SENSITIVE TIME_SENSITIVE,
	C110_DEFAULT_PRODUCT_CLASS DEFAULT_PRODUCT_CLASS,
	C111_IS_SERIAL_TRACKED IS_SERIAL_TRACKED,
	C112_ADVANCE_NOTIFICATION_TIME ADVANCE_NOTIFICATION_TIME,
	C113_MAX_MODIFYTS MAX_MODIFYTS,
	C114_REMOTE_MODIFYTS REMOTE_MODIFYTS,
	C115_ONHAND_SAFETY_FACTOR_QTY ONHAND_SAFETY_FACTOR_QTY,
	C116_IS_MODEL_ITEM IS_MODEL_ITEM,
	C117_STATUS STATUS,
	C118_IS_STANDALONE_SERVICE IS_STANDALONE_SERVICE,
	C119_CREATETS CREATETS,
	C120_MIN_ORDER_QUANTITY MIN_ORDER_QUANTITY,
	C121_PRICING_QUANTITY_CONV_FAC PRICING_QUANTITY_CONV_FACTOR,
	C122_RUN_QUANTITY RUN_QUANTITY,
	C123_IS_FORWARDING_ALLOWED IS_FORWARDING_ALLOWED,
	C124_NODE_LEVEL_INV_MONITOR_RU NODE_LEVEL_INV_MONITOR_RULE,
	C125_COLOR_CODE COLOR_CODE,
	C126_UNIT_WIDTH_UOM UNIT_WIDTH_UOM,
	C127_EXTN_SKU_LAYOUT_ID EXTN_SKU_LAYOUT_ID,
	C128_MODIFYTS MODIFYTS,
	C129_SERIALIZED_FLAG SERIALIZED_FLAG,
	C130_CREATEUSERID CREATEUSERID,
	C131_ITEM_GROUP_CODE ITEM_GROUP_CODE,
	C132_IS_SHIPPING_CNTR IS_SHIPPING_CNTR,
	C133_CAPACITY_UOM CAPACITY_UOM,
	C134_UNIT_LENGTH UNIT_LENGTH,
	C135_BUNDLE_FULFILLMENT_MODE BUNDLE_FULFILLMENT_MODE,
	C136_FIXED_PRICING_QTY_PER_LIN FIXED_PRICING_QTY_PER_LINE,
	C137_MANUFACTURER_ITEM_DESC MANUFACTURER_ITEM_DESC,
	C138_UOM UOM,
	C139_COUNTRY_OF_ORIGIN COUNTRY_OF_ORIGIN,
	C140_SERVICE_TYPE_ID SERVICE_TYPE_ID,
	C141_CHARGEBACK_CATEGORY CHARGEBACK_CATEGORY,
	C142_EQUIV_35_UNIT EQUIV_35_UNIT,
	C143_FULFILLMENT_TYPE FULFILLMENT_TYPE,
	C144_SELECTION_TEMPLATE SELECTION_TEMPLATE,
	C145_SHUTTERFLY_ELIGIBLE SHUTTERFLY_ELIGIBLE,

	'I' IND_UPDATE

from	RAX_APP_USER.C$_0OMS3_ITEM_STG
where	(1=1)






) S
where NOT EXISTS 
	( select 1 from ODS_STAGE.OMS3_ITEM_STG T
	where	T.ITEM_KEY	= S.ITEM_KEY 
		 and ((T.ITEM_ID = S.ITEM_ID) or (T.ITEM_ID IS NULL and S.ITEM_ID IS NULL)) and
		((T.SCHEDULE_B_CODE = S.SCHEDULE_B_CODE) or (T.SCHEDULE_B_CODE IS NULL and S.SCHEDULE_B_CODE IS NULL)) and
		((T.KIT_CODE = S.KIT_CODE) or (T.KIT_CODE IS NULL and S.KIT_CODE IS NULL)) and
		((T.FUTURE_SAFETY_FACTOR_PCT = S.FUTURE_SAFETY_FACTOR_PCT) or (T.FUTURE_SAFETY_FACTOR_PCT IS NULL and S.FUTURE_SAFETY_FACTOR_PCT IS NULL)) and
		((T.IS_SUB_ON_ORDER_ALLOWED = S.IS_SUB_ON_ORDER_ALLOWED) or (T.IS_SUB_ON_ORDER_ALLOWED IS NULL and S.IS_SUB_ON_ORDER_ALLOWED IS NULL)) and
		((T.PRIMARY_ENTERPRISE_CODE = S.PRIMARY_ENTERPRISE_CODE) or (T.PRIMARY_ENTERPRISE_CODE IS NULL and S.PRIMARY_ENTERPRISE_CODE IS NULL)) and
		((T.MINIMUM_CAPACITY_QUANTITY = S.MINIMUM_CAPACITY_QUANTITY) or (T.MINIMUM_CAPACITY_QUANTITY IS NULL and S.MINIMUM_CAPACITY_QUANTITY IS NULL)) and
		((T.UNSPSC = S.UNSPSC) or (T.UNSPSC IS NULL and S.UNSPSC IS NULL)) and
		((T.PRIMARY_SUPPLIER = S.PRIMARY_SUPPLIER) or (T.PRIMARY_SUPPLIER IS NULL and S.PRIMARY_SUPPLIER IS NULL)) and
		((T.COMMODITY_CODE = S.COMMODITY_CODE) or (T.COMMODITY_CODE IS NULL and S.COMMODITY_CODE IS NULL)) and
		((T.CONFIGURED_MODEL_KEY = S.CONFIGURED_MODEL_KEY) or (T.CONFIGURED_MODEL_KEY IS NULL and S.CONFIGURED_MODEL_KEY IS NULL)) and
		((T.MIN_NOTIFICATION_TIME = S.MIN_NOTIFICATION_TIME) or (T.MIN_NOTIFICATION_TIME IS NULL and S.MIN_NOTIFICATION_TIME IS NULL)) and
		((T.UNIT_HEIGHT = S.UNIT_HEIGHT) or (T.UNIT_HEIGHT IS NULL and S.UNIT_HEIGHT IS NULL)) and
		((T.NAICS_CODE = S.NAICS_CODE) or (T.NAICS_CODE IS NULL and S.NAICS_CODE IS NULL)) and
		((T.MODEL_ITEM_UOM = S.MODEL_ITEM_UOM) or (T.MODEL_ITEM_UOM IS NULL and S.MODEL_ITEM_UOM IS NULL)) and
		((T.CREATEPROGID = S.CREATEPROGID) or (T.CREATEPROGID IS NULL and S.CREATEPROGID IS NULL)) and
		((T.NMFC_CODE = S.NMFC_CODE) or (T.NMFC_CODE IS NULL and S.NMFC_CODE IS NULL)) and
		((T.REQUIRES_PROD_ASSOCIATION = S.REQUIRES_PROD_ASSOCIATION) or (T.REQUIRES_PROD_ASSOCIATION IS NULL and S.REQUIRES_PROD_ASSOCIATION IS NULL)) and
		((T.IS_PROCUREMENT_ALLOWED = S.IS_PROCUREMENT_ALLOWED) or (T.IS_PROCUREMENT_ALLOWED IS NULL and S.IS_PROCUREMENT_ALLOWED IS NULL)) and
		((T.INVOLVES_SEGMENT_CHANGE = S.INVOLVES_SEGMENT_CHANGE) or (T.INVOLVES_SEGMENT_CHANGE IS NULL and S.INVOLVES_SEGMENT_CHANGE IS NULL)) and
		((T.DESCRIPTION = S.DESCRIPTION) or (T.DESCRIPTION IS NULL and S.DESCRIPTION IS NULL)) and
		((T.SYNCTS = S.SYNCTS) or (T.SYNCTS IS NULL and S.SYNCTS IS NULL)) and
		((T.MAX_ORDER_QUANTITY = S.MAX_ORDER_QUANTITY) or (T.MAX_ORDER_QUANTITY IS NULL and S.MAX_ORDER_QUANTITY IS NULL)) and
		((T.IS_PARCEL_SHIPPING_ALLOWED = S.IS_PARCEL_SHIPPING_ALLOWED) or (T.IS_PARCEL_SHIPPING_ALLOWED IS NULL and S.IS_PARCEL_SHIPPING_ALLOWED IS NULL)) and
		((T.IS_RETURNABLE = S.IS_RETURNABLE) or (T.IS_RETURNABLE IS NULL and S.IS_RETURNABLE IS NULL)) and
		((T.POSTING_CLASSIFICATION = S.POSTING_CLASSIFICATION) or (T.POSTING_CLASSIFICATION IS NULL and S.POSTING_CLASSIFICATION IS NULL)) and
		((T.MODIFYUSERID = S.MODIFYUSERID) or (T.MODIFYUSERID IS NULL and S.MODIFYUSERID IS NULL)) and
		((T.MODIFYPROGID = S.MODIFYPROGID) or (T.MODIFYPROGID IS NULL and S.MODIFYPROGID IS NULL)) and
		((T.CAPACITY_VOLUME_UOM = S.CAPACITY_VOLUME_UOM) or (T.CAPACITY_VOLUME_UOM IS NULL and S.CAPACITY_VOLUME_UOM IS NULL)) and
		((T.IS_PICKUP_ALLOWED = S.IS_PICKUP_ALLOWED) or (T.IS_PICKUP_ALLOWED IS NULL and S.IS_PICKUP_ALLOWED IS NULL)) and
		((T.LEAD_TIME = S.LEAD_TIME) or (T.LEAD_TIME IS NULL and S.LEAD_TIME IS NULL)) and
		((T.EXTN_LOOK_SELECTION_ALLOWED = S.EXTN_LOOK_SELECTION_ALLOWED) or (T.EXTN_LOOK_SELECTION_ALLOWED IS NULL and S.EXTN_LOOK_SELECTION_ALLOWED IS NULL)) and
		((T.IS_DELIVERY_ALLOWED = S.IS_DELIVERY_ALLOWED) or (T.IS_DELIVERY_ALLOWED IS NULL and S.IS_DELIVERY_ALLOWED IS NULL)) and
		((T.LOCKID = S.LOCKID) or (T.LOCKID IS NULL and S.LOCKID IS NULL)) and
		((T.IS_CONFIGURABLE = S.IS_CONFIGURABLE) or (T.IS_CONFIGURABLE IS NULL and S.IS_CONFIGURABLE IS NULL)) and
		((T.SHP_CONSOL_WINDOW = S.SHP_CONSOL_WINDOW) or (T.SHP_CONSOL_WINDOW IS NULL and S.SHP_CONSOL_WINDOW IS NULL)) and
		((T.HAZMAT_CLASS = S.HAZMAT_CLASS) or (T.HAZMAT_CLASS IS NULL and S.HAZMAT_CLASS IS NULL)) and
		((T.TAX_PRODUCT_CODE = S.TAX_PRODUCT_CODE) or (T.TAX_PRODUCT_CODE IS NULL and S.TAX_PRODUCT_CODE IS NULL)) and
		((T.UNIT_COST = S.UNIT_COST) or (T.UNIT_COST IS NULL and S.UNIT_COST IS NULL)) and
		((T.ITEM_TYPE = S.ITEM_TYPE) or (T.ITEM_TYPE IS NULL and S.ITEM_TYPE IS NULL)) and
		((T.ORGANIZATION_CODE = S.ORGANIZATION_CODE) or (T.ORGANIZATION_CODE IS NULL and S.ORGANIZATION_CODE IS NULL)) and
		((T.ASSUME_INFINITE_INVENTORY = S.ASSUME_INFINITE_INVENTORY) or (T.ASSUME_INFINITE_INVENTORY IS NULL and S.ASSUME_INFINITE_INVENTORY IS NULL)) and
		((T.MAX_CNTR_WEIGHT_UOM = S.MAX_CNTR_WEIGHT_UOM) or (T.MAX_CNTR_WEIGHT_UOM IS NULL and S.MAX_CNTR_WEIGHT_UOM IS NULL)) and
		((T.STORAGE_TYPE = S.STORAGE_TYPE) or (T.STORAGE_TYPE IS NULL and S.STORAGE_TYPE IS NULL)) and
		((T.MANUFACTURER_ITEM = S.MANUFACTURER_ITEM) or (T.MANUFACTURER_ITEM IS NULL and S.MANUFACTURER_ITEM IS NULL)) and
		((T.NUM_SECONDARY_SERIALS = S.NUM_SECONDARY_SERIALS) or (T.NUM_SECONDARY_SERIALS IS NULL and S.NUM_SECONDARY_SERIALS IS NULL)) and
		((T.UPC_COM_PRE_LEN = S.UPC_COM_PRE_LEN) or (T.UPC_COM_PRE_LEN IS NULL and S.UPC_COM_PRE_LEN IS NULL)) and
		((T.IS_PRE_CONFIGURED = S.IS_PRE_CONFIGURED) or (T.IS_PRE_CONFIGURED IS NULL and S.IS_PRE_CONFIGURED IS NULL)) and
		((T.SUB_CLASS = S.SUB_CLASS) or (T.SUB_CLASS IS NULL and S.SUB_CLASS IS NULL)) and
		((T.EMPTY_CNTR_WEIGHT = S.EMPTY_CNTR_WEIGHT) or (T.EMPTY_CNTR_WEIGHT IS NULL and S.EMPTY_CNTR_WEIGHT IS NULL)) and
		((T.TAG_REQ_AT_SHIPMENT = S.TAG_REQ_AT_SHIPMENT) or (T.TAG_REQ_AT_SHIPMENT IS NULL and S.TAG_REQ_AT_SHIPMENT IS NULL)) and
		((T.PICKING_TYPE = S.PICKING_TYPE) or (T.PICKING_TYPE IS NULL and S.PICKING_TYPE IS NULL)) and
		((T.DEPARTMENT = S.DEPARTMENT) or (T.DEPARTMENT IS NULL and S.DEPARTMENT IS NULL)) and
		((T.CAPACITY_QUANTITY_STRATEGY = S.CAPACITY_QUANTITY_STRATEGY) or (T.CAPACITY_QUANTITY_STRATEGY IS NULL and S.CAPACITY_QUANTITY_STRATEGY IS NULL)) and
		((T.CAPACITY_VOLUME = S.CAPACITY_VOLUME) or (T.CAPACITY_VOLUME IS NULL and S.CAPACITY_VOLUME IS NULL)) and
		((T.USE_UNPLANNED_INV = S.USE_UNPLANNED_INV) or (T.USE_UNPLANNED_INV IS NULL and S.USE_UNPLANNED_INV IS NULL)) and
		((T.PRODUCT_LINE = S.PRODUCT_LINE) or (T.PRODUCT_LINE IS NULL and S.PRODUCT_LINE IS NULL)) and
		((T.UNIT_HEIGHT_UOM = S.UNIT_HEIGHT_UOM) or (T.UNIT_HEIGHT_UOM IS NULL and S.UNIT_HEIGHT_UOM IS NULL)) and
		((T.IS_FREEZER_REQUIRED = S.IS_FREEZER_REQUIRED) or (T.IS_FREEZER_REQUIRED IS NULL and S.IS_FREEZER_REQUIRED IS NULL)) and
		((T.PRICING_QUANTITY_STRATEGY = S.PRICING_QUANTITY_STRATEGY) or (T.PRICING_QUANTITY_STRATEGY IS NULL and S.PRICING_QUANTITY_STRATEGY IS NULL)) and
		((T.ONHAND_SAFETY_FACTOR_PCT = S.ONHAND_SAFETY_FACTOR_PCT) or (T.ONHAND_SAFETY_FACTOR_PCT IS NULL and S.ONHAND_SAFETY_FACTOR_PCT IS NULL)) and
		((T.COMPUTED_UNIT_COST = S.COMPUTED_UNIT_COST) or (T.COMPUTED_UNIT_COST IS NULL and S.COMPUTED_UNIT_COST IS NULL)) and
		((T.UNIT_WIDTH = S.UNIT_WIDTH) or (T.UNIT_WIDTH IS NULL and S.UNIT_WIDTH IS NULL)) and
		((T.SHORT_DESCRIPTION = S.SHORT_DESCRIPTION) or (T.SHORT_DESCRIPTION IS NULL and S.SHORT_DESCRIPTION IS NULL)) and
		((T.TAXABLE_FLAG = S.TAXABLE_FLAG) or (T.TAXABLE_FLAG IS NULL and S.TAXABLE_FLAG IS NULL)) and
		((T.CONTAINER_SIZE = S.CONTAINER_SIZE) or (T.CONTAINER_SIZE IS NULL and S.CONTAINER_SIZE IS NULL)) and
		((T.ECCN_NO = S.ECCN_NO) or (T.ECCN_NO IS NULL and S.ECCN_NO IS NULL)) and
		((T.TAG_CONTROL_FLAG = S.TAG_CONTROL_FLAG) or (T.TAG_CONTROL_FLAG IS NULL and S.TAG_CONTROL_FLAG IS NULL)) and
		((T.IS_IBA_ALLOWED = S.IS_IBA_ALLOWED) or (T.IS_IBA_ALLOWED IS NULL and S.IS_IBA_ALLOWED IS NULL)) and
		((T.CLASS = S.CLASS) or (T.CLASS IS NULL and S.CLASS IS NULL)) and
		((T.CAPACITY_PER_ORDERED_QTY = S.CAPACITY_PER_ORDERED_QTY) or (T.CAPACITY_PER_ORDERED_QTY IS NULL and S.CAPACITY_PER_ORDERED_QTY IS NULL)) and
		((T.COST_CURRENCY = S.COST_CURRENCY) or (T.COST_CURRENCY IS NULL and S.COST_CURRENCY IS NULL)) and
		((T.IS_HAZMAT = S.IS_HAZMAT) or (T.IS_HAZMAT IS NULL and S.IS_HAZMAT IS NULL)) and
		((T.DEFAULT_EXPIRATION_DAYS = S.DEFAULT_EXPIRATION_DAYS) or (T.DEFAULT_EXPIRATION_DAYS IS NULL and S.DEFAULT_EXPIRATION_DAYS IS NULL)) and
		((T.FIXED_CAPACITY_QTY_PER_LINE = S.FIXED_CAPACITY_QTY_PER_LINE) or (T.FIXED_CAPACITY_QTY_PER_LINE IS NULL and S.FIXED_CAPACITY_QTY_PER_LINE IS NULL)) and
		((T.PRICING_UOM = S.PRICING_UOM) or (T.PRICING_UOM IS NULL and S.PRICING_UOM IS NULL)) and
		((T.EXTENDED_DESCRIPTION = S.EXTENDED_DESCRIPTION) or (T.EXTENDED_DESCRIPTION IS NULL and S.EXTENDED_DESCRIPTION IS NULL)) and
		((T.PROCESSING_TIME = S.PROCESSING_TIME) or (T.PROCESSING_TIME IS NULL and S.PROCESSING_TIME IS NULL)) and
		((T.INVENTORY_MONITOR_RULE = S.INVENTORY_MONITOR_RULE) or (T.INVENTORY_MONITOR_RULE IS NULL and S.INVENTORY_MONITOR_RULE IS NULL)) and
		((T.CAN_USE_AS_SERVICE_TOOL = S.CAN_USE_AS_SERVICE_TOOL) or (T.CAN_USE_AS_SERVICE_TOOL IS NULL and S.CAN_USE_AS_SERVICE_TOOL IS NULL)) and
		((T.NMFC_CLASS = S.NMFC_CLASS) or (T.NMFC_CLASS IS NULL and S.NMFC_CLASS IS NULL)) and
		((T.RETURN_SHIPPING_LABEL_LEVEL = S.RETURN_SHIPPING_LABEL_LEVEL) or (T.RETURN_SHIPPING_LABEL_LEVEL IS NULL and S.RETURN_SHIPPING_LABEL_LEVEL IS NULL)) and
		((T.MAX_CNTR_WEIGHT = S.MAX_CNTR_WEIGHT) or (T.MAX_CNTR_WEIGHT IS NULL and S.MAX_CNTR_WEIGHT IS NULL)) and
		((T.HARMONIZED_CODE = S.HARMONIZED_CODE) or (T.HARMONIZED_CODE IS NULL and S.HARMONIZED_CODE IS NULL)) and
		((T.ORDERING_QUANTITY_STRATEGY = S.ORDERING_QUANTITY_STRATEGY) or (T.ORDERING_QUANTITY_STRATEGY IS NULL and S.ORDERING_QUANTITY_STRATEGY IS NULL)) and
		((T.SIZE_CODE = S.SIZE_CODE) or (T.SIZE_CODE IS NULL and S.SIZE_CODE IS NULL)) and
		((T.OPERATIONAL_CONFIG_COMPLETE = S.OPERATIONAL_CONFIG_COMPLETE) or (T.OPERATIONAL_CONFIG_COMPLETE IS NULL and S.OPERATIONAL_CONFIG_COMPLETE IS NULL)) and
		((T.INVOICE_BASED_ON_ACTUALS = S.INVOICE_BASED_ON_ACTUALS) or (T.INVOICE_BASED_ON_ACTUALS IS NULL and S.INVOICE_BASED_ON_ACTUALS IS NULL)) and
		((T.UNIT_WEIGHT_UOM = S.UNIT_WEIGHT_UOM) or (T.UNIT_WEIGHT_UOM IS NULL and S.UNIT_WEIGHT_UOM IS NULL)) and
		((T.MASTER_CATALOG_ID = S.MASTER_CATALOG_ID) or (T.MASTER_CATALOG_ID IS NULL and S.MASTER_CATALOG_ID IS NULL)) and
		((T.GLOBAL_ITEM_ID = S.GLOBAL_ITEM_ID) or (T.GLOBAL_ITEM_ID IS NULL and S.GLOBAL_ITEM_ID IS NULL)) and
		((T.ATP_RULE = S.ATP_RULE) or (T.ATP_RULE IS NULL and S.ATP_RULE IS NULL)) and
		((T.TAG_REQ_AT_RECEIPT = S.TAG_REQ_AT_RECEIPT) or (T.TAG_REQ_AT_RECEIPT IS NULL and S.TAG_REQ_AT_RECEIPT IS NULL)) and
		((T.UNIT_LENGTH_UOM = S.UNIT_LENGTH_UOM) or (T.UNIT_LENGTH_UOM IS NULL and S.UNIT_LENGTH_UOM IS NULL)) and
		((T.MODEL = S.MODEL) or (T.MODEL IS NULL and S.MODEL IS NULL)) and
		((T.CONTAINER_TYPE = S.CONTAINER_TYPE) or (T.CONTAINER_TYPE IS NULL and S.CONTAINER_TYPE IS NULL)) and
		((T.PRICING_UOM_STRATEGY = S.PRICING_UOM_STRATEGY) or (T.PRICING_UOM_STRATEGY IS NULL and S.PRICING_UOM_STRATEGY IS NULL)) and
		((T.IS_FIFO_TRACKED = S.IS_FIFO_TRACKED) or (T.IS_FIFO_TRACKED IS NULL and S.IS_FIFO_TRACKED IS NULL)) and
		((T.IS_SHIPPING_ALLOWED = S.IS_SHIPPING_ALLOWED) or (T.IS_SHIPPING_ALLOWED IS NULL and S.IS_SHIPPING_ALLOWED IS NULL)) and
		((T.IS_AIR_SHIPPING_ALLOWED = S.IS_AIR_SHIPPING_ALLOWED) or (T.IS_AIR_SHIPPING_ALLOWED IS NULL and S.IS_AIR_SHIPPING_ALLOWED IS NULL)) and
		((T.RETURN_WINDOW = S.RETURN_WINDOW) or (T.RETURN_WINDOW IS NULL and S.RETURN_WINDOW IS NULL)) and
		((T.CREDIT_WO_RECEIPT = S.CREDIT_WO_RECEIPT) or (T.CREDIT_WO_RECEIPT IS NULL and S.CREDIT_WO_RECEIPT IS NULL)) and
		((T.UNIT_WEIGHT = S.UNIT_WEIGHT) or (T.UNIT_WEIGHT IS NULL and S.UNIT_WEIGHT IS NULL)) and
		((T.VOLUME_ALLOWANCE = S.VOLUME_ALLOWANCE) or (T.VOLUME_ALLOWANCE IS NULL and S.VOLUME_ALLOWANCE IS NULL)) and
		((T.VELOCITY_CODE = S.VELOCITY_CODE) or (T.VELOCITY_CODE IS NULL and S.VELOCITY_CODE IS NULL)) and
		((T.IS_RETURN_SERVICE = S.IS_RETURN_SERVICE) or (T.IS_RETURN_SERVICE IS NULL and S.IS_RETURN_SERVICE IS NULL)) and
		((T.MANUFACTURER_NAME = S.MANUFACTURER_NAME) or (T.MANUFACTURER_NAME IS NULL and S.MANUFACTURER_NAME IS NULL)) and
		((T.TIME_SENSITIVE = S.TIME_SENSITIVE) or (T.TIME_SENSITIVE IS NULL and S.TIME_SENSITIVE IS NULL)) and
		((T.DEFAULT_PRODUCT_CLASS = S.DEFAULT_PRODUCT_CLASS) or (T.DEFAULT_PRODUCT_CLASS IS NULL and S.DEFAULT_PRODUCT_CLASS IS NULL)) and
		((T.IS_SERIAL_TRACKED = S.IS_SERIAL_TRACKED) or (T.IS_SERIAL_TRACKED IS NULL and S.IS_SERIAL_TRACKED IS NULL)) and
		((T.ADVANCE_NOTIFICATION_TIME = S.ADVANCE_NOTIFICATION_TIME) or (T.ADVANCE_NOTIFICATION_TIME IS NULL and S.ADVANCE_NOTIFICATION_TIME IS NULL)) and
		((T.MAX_MODIFYTS = S.MAX_MODIFYTS) or (T.MAX_MODIFYTS IS NULL and S.MAX_MODIFYTS IS NULL)) and
		((T.REMOTE_MODIFYTS = S.REMOTE_MODIFYTS) or (T.REMOTE_MODIFYTS IS NULL and S.REMOTE_MODIFYTS IS NULL)) and
		((T.ONHAND_SAFETY_FACTOR_QTY = S.ONHAND_SAFETY_FACTOR_QTY) or (T.ONHAND_SAFETY_FACTOR_QTY IS NULL and S.ONHAND_SAFETY_FACTOR_QTY IS NULL)) and
		((T.IS_MODEL_ITEM = S.IS_MODEL_ITEM) or (T.IS_MODEL_ITEM IS NULL and S.IS_MODEL_ITEM IS NULL)) and
		((T.STATUS = S.STATUS) or (T.STATUS IS NULL and S.STATUS IS NULL)) and
		((T.IS_STANDALONE_SERVICE = S.IS_STANDALONE_SERVICE) or (T.IS_STANDALONE_SERVICE IS NULL and S.IS_STANDALONE_SERVICE IS NULL)) and
		((T.CREATETS = S.CREATETS) or (T.CREATETS IS NULL and S.CREATETS IS NULL)) and
		((T.MIN_ORDER_QUANTITY = S.MIN_ORDER_QUANTITY) or (T.MIN_ORDER_QUANTITY IS NULL and S.MIN_ORDER_QUANTITY IS NULL)) and
		((T.PRICING_QUANTITY_CONV_FACTOR = S.PRICING_QUANTITY_CONV_FACTOR) or (T.PRICING_QUANTITY_CONV_FACTOR IS NULL and S.PRICING_QUANTITY_CONV_FACTOR IS NULL)) and
		((T.RUN_QUANTITY = S.RUN_QUANTITY) or (T.RUN_QUANTITY IS NULL and S.RUN_QUANTITY IS NULL)) and
		((T.IS_FORWARDING_ALLOWED = S.IS_FORWARDING_ALLOWED) or (T.IS_FORWARDING_ALLOWED IS NULL and S.IS_FORWARDING_ALLOWED IS NULL)) and
		((T.NODE_LEVEL_INV_MONITOR_RULE = S.NODE_LEVEL_INV_MONITOR_RULE) or (T.NODE_LEVEL_INV_MONITOR_RULE IS NULL and S.NODE_LEVEL_INV_MONITOR_RULE IS NULL)) and
		((T.COLOR_CODE = S.COLOR_CODE) or (T.COLOR_CODE IS NULL and S.COLOR_CODE IS NULL)) and
		((T.UNIT_WIDTH_UOM = S.UNIT_WIDTH_UOM) or (T.UNIT_WIDTH_UOM IS NULL and S.UNIT_WIDTH_UOM IS NULL)) and
		((T.EXTN_SKU_LAYOUT_ID = S.EXTN_SKU_LAYOUT_ID) or (T.EXTN_SKU_LAYOUT_ID IS NULL and S.EXTN_SKU_LAYOUT_ID IS NULL)) and
		((T.MODIFYTS = S.MODIFYTS) or (T.MODIFYTS IS NULL and S.MODIFYTS IS NULL)) and
		((T.SERIALIZED_FLAG = S.SERIALIZED_FLAG) or (T.SERIALIZED_FLAG IS NULL and S.SERIALIZED_FLAG IS NULL)) and
		((T.CREATEUSERID = S.CREATEUSERID) or (T.CREATEUSERID IS NULL and S.CREATEUSERID IS NULL)) and
		((T.ITEM_GROUP_CODE = S.ITEM_GROUP_CODE) or (T.ITEM_GROUP_CODE IS NULL and S.ITEM_GROUP_CODE IS NULL)) and
		((T.IS_SHIPPING_CNTR = S.IS_SHIPPING_CNTR) or (T.IS_SHIPPING_CNTR IS NULL and S.IS_SHIPPING_CNTR IS NULL)) and
		((T.CAPACITY_UOM = S.CAPACITY_UOM) or (T.CAPACITY_UOM IS NULL and S.CAPACITY_UOM IS NULL)) and
		((T.UNIT_LENGTH = S.UNIT_LENGTH) or (T.UNIT_LENGTH IS NULL and S.UNIT_LENGTH IS NULL)) and
		((T.BUNDLE_FULFILLMENT_MODE = S.BUNDLE_FULFILLMENT_MODE) or (T.BUNDLE_FULFILLMENT_MODE IS NULL and S.BUNDLE_FULFILLMENT_MODE IS NULL)) and
		((T.FIXED_PRICING_QTY_PER_LINE = S.FIXED_PRICING_QTY_PER_LINE) or (T.FIXED_PRICING_QTY_PER_LINE IS NULL and S.FIXED_PRICING_QTY_PER_LINE IS NULL)) and
		((T.MANUFACTURER_ITEM_DESC = S.MANUFACTURER_ITEM_DESC) or (T.MANUFACTURER_ITEM_DESC IS NULL and S.MANUFACTURER_ITEM_DESC IS NULL)) and
		((T.UOM = S.UOM) or (T.UOM IS NULL and S.UOM IS NULL)) and
		((T.COUNTRY_OF_ORIGIN = S.COUNTRY_OF_ORIGIN) or (T.COUNTRY_OF_ORIGIN IS NULL and S.COUNTRY_OF_ORIGIN IS NULL)) and
		((T.SERVICE_TYPE_ID = S.SERVICE_TYPE_ID) or (T.SERVICE_TYPE_ID IS NULL and S.SERVICE_TYPE_ID IS NULL)) and
		((T.CHARGEBACK_CATEGORY = S.CHARGEBACK_CATEGORY) or (T.CHARGEBACK_CATEGORY IS NULL and S.CHARGEBACK_CATEGORY IS NULL)) and
		((T.EQUIV_35_UNIT = S.EQUIV_35_UNIT) or (T.EQUIV_35_UNIT IS NULL and S.EQUIV_35_UNIT IS NULL)) and
		((T.FULFILLMENT_TYPE = S.FULFILLMENT_TYPE) or (T.FULFILLMENT_TYPE IS NULL and S.FULFILLMENT_TYPE IS NULL)) and
		((T.SELECTION_TEMPLATE = S.SELECTION_TEMPLATE) or (T.SELECTION_TEMPLATE IS NULL and S.SELECTION_TEMPLATE IS NULL)) and
		((T.SHUTTERFLY_ELIGIBLE = S.SHUTTERFLY_ELIGIBLE) or (T.SHUTTERFLY_ELIGIBLE IS NULL and S.SHUTTERFLY_ELIGIBLE IS NULL))
        )

  
  

  



&


/*-----------------------------------------------*/
/* TASK No. 13 */
/* Analyze integration table */



begin
    dbms_stats.gather_table_stats(
	ownname => 'RAX_APP_USER',
	tabname => 'I$_OMS3_ITEM_STG2079001',
	estimate_percent => dbms_stats.auto_sample_size
    );
end;



&


/*-----------------------------------------------*/
/* TASK No. 14 */
/* Create Index on flow table */

create index	RAX_APP_USER.I$_OMS3_ITEM_STG_IDX2079001
on		RAX_APP_USER.I$_OMS3_ITEM_STG2079001 (ITEM_KEY)
NOLOGGING

&


/*-----------------------------------------------*/
/* TASK No. 15 */
/* Merge Rows */

merge into	ODS_STAGE.OMS3_ITEM_STG T
using	RAX_APP_USER.I$_OMS3_ITEM_STG2079001 S
on	(
		T.ITEM_KEY=S.ITEM_KEY
	)
when matched
then update set
	T.ITEM_ID	= S.ITEM_ID,
	T.SCHEDULE_B_CODE	= S.SCHEDULE_B_CODE,
	T.KIT_CODE	= S.KIT_CODE,
	T.FUTURE_SAFETY_FACTOR_PCT	= S.FUTURE_SAFETY_FACTOR_PCT,
	T.IS_SUB_ON_ORDER_ALLOWED	= S.IS_SUB_ON_ORDER_ALLOWED,
	T.PRIMARY_ENTERPRISE_CODE	= S.PRIMARY_ENTERPRISE_CODE,
	T.MINIMUM_CAPACITY_QUANTITY	= S.MINIMUM_CAPACITY_QUANTITY,
	T.UNSPSC	= S.UNSPSC,
	T.PRIMARY_SUPPLIER	= S.PRIMARY_SUPPLIER,
	T.COMMODITY_CODE	= S.COMMODITY_CODE,
	T.CONFIGURED_MODEL_KEY	= S.CONFIGURED_MODEL_KEY,
	T.MIN_NOTIFICATION_TIME	= S.MIN_NOTIFICATION_TIME,
	T.UNIT_HEIGHT	= S.UNIT_HEIGHT,
	T.NAICS_CODE	= S.NAICS_CODE,
	T.MODEL_ITEM_UOM	= S.MODEL_ITEM_UOM,
	T.CREATEPROGID	= S.CREATEPROGID,
	T.NMFC_CODE	= S.NMFC_CODE,
	T.REQUIRES_PROD_ASSOCIATION	= S.REQUIRES_PROD_ASSOCIATION,
	T.IS_PROCUREMENT_ALLOWED	= S.IS_PROCUREMENT_ALLOWED,
	T.INVOLVES_SEGMENT_CHANGE	= S.INVOLVES_SEGMENT_CHANGE,
	T.DESCRIPTION	= S.DESCRIPTION,
	T.SYNCTS	= S.SYNCTS,
	T.MAX_ORDER_QUANTITY	= S.MAX_ORDER_QUANTITY,
	T.IS_PARCEL_SHIPPING_ALLOWED	= S.IS_PARCEL_SHIPPING_ALLOWED,
	T.IS_RETURNABLE	= S.IS_RETURNABLE,
	T.POSTING_CLASSIFICATION	= S.POSTING_CLASSIFICATION,
	T.MODIFYUSERID	= S.MODIFYUSERID,
	T.MODIFYPROGID	= S.MODIFYPROGID,
	T.CAPACITY_VOLUME_UOM	= S.CAPACITY_VOLUME_UOM,
	T.IS_PICKUP_ALLOWED	= S.IS_PICKUP_ALLOWED,
	T.LEAD_TIME	= S.LEAD_TIME,
	T.EXTN_LOOK_SELECTION_ALLOWED	= S.EXTN_LOOK_SELECTION_ALLOWED,
	T.IS_DELIVERY_ALLOWED	= S.IS_DELIVERY_ALLOWED,
	T.LOCKID	= S.LOCKID,
	T.IS_CONFIGURABLE	= S.IS_CONFIGURABLE,
	T.SHP_CONSOL_WINDOW	= S.SHP_CONSOL_WINDOW,
	T.HAZMAT_CLASS	= S.HAZMAT_CLASS,
	T.TAX_PRODUCT_CODE	= S.TAX_PRODUCT_CODE,
	T.UNIT_COST	= S.UNIT_COST,
	T.ITEM_TYPE	= S.ITEM_TYPE,
	T.ORGANIZATION_CODE	= S.ORGANIZATION_CODE,
	T.ASSUME_INFINITE_INVENTORY	= S.ASSUME_INFINITE_INVENTORY,
	T.MAX_CNTR_WEIGHT_UOM	= S.MAX_CNTR_WEIGHT_UOM,
	T.STORAGE_TYPE	= S.STORAGE_TYPE,
	T.MANUFACTURER_ITEM	= S.MANUFACTURER_ITEM,
	T.NUM_SECONDARY_SERIALS	= S.NUM_SECONDARY_SERIALS,
	T.UPC_COM_PRE_LEN	= S.UPC_COM_PRE_LEN,
	T.IS_PRE_CONFIGURED	= S.IS_PRE_CONFIGURED,
	T.SUB_CLASS	= S.SUB_CLASS,
	T.EMPTY_CNTR_WEIGHT	= S.EMPTY_CNTR_WEIGHT,
	T.TAG_REQ_AT_SHIPMENT	= S.TAG_REQ_AT_SHIPMENT,
	T.PICKING_TYPE	= S.PICKING_TYPE,
	T.DEPARTMENT	= S.DEPARTMENT,
	T.CAPACITY_QUANTITY_STRATEGY	= S.CAPACITY_QUANTITY_STRATEGY,
	T.CAPACITY_VOLUME	= S.CAPACITY_VOLUME,
	T.USE_UNPLANNED_INV	= S.USE_UNPLANNED_INV,
	T.PRODUCT_LINE	= S.PRODUCT_LINE,
	T.UNIT_HEIGHT_UOM	= S.UNIT_HEIGHT_UOM,
	T.IS_FREEZER_REQUIRED	= S.IS_FREEZER_REQUIRED,
	T.PRICING_QUANTITY_STRATEGY	= S.PRICING_QUANTITY_STRATEGY,
	T.ONHAND_SAFETY_FACTOR_PCT	= S.ONHAND_SAFETY_FACTOR_PCT,
	T.COMPUTED_UNIT_COST	= S.COMPUTED_UNIT_COST,
	T.UNIT_WIDTH	= S.UNIT_WIDTH,
	T.SHORT_DESCRIPTION	= S.SHORT_DESCRIPTION,
	T.TAXABLE_FLAG	= S.TAXABLE_FLAG,
	T.CONTAINER_SIZE	= S.CONTAINER_SIZE,
	T.ECCN_NO	= S.ECCN_NO,
	T.TAG_CONTROL_FLAG	= S.TAG_CONTROL_FLAG,
	T.IS_IBA_ALLOWED	= S.IS_IBA_ALLOWED,
	T.CLASS	= S.CLASS,
	T.CAPACITY_PER_ORDERED_QTY	= S.CAPACITY_PER_ORDERED_QTY,
	T.COST_CURRENCY	= S.COST_CURRENCY,
	T.IS_HAZMAT	= S.IS_HAZMAT,
	T.DEFAULT_EXPIRATION_DAYS	= S.DEFAULT_EXPIRATION_DAYS,
	T.FIXED_CAPACITY_QTY_PER_LINE	= S.FIXED_CAPACITY_QTY_PER_LINE,
	T.PRICING_UOM	= S.PRICING_UOM,
	T.EXTENDED_DESCRIPTION	= S.EXTENDED_DESCRIPTION,
	T.PROCESSING_TIME	= S.PROCESSING_TIME,
	T.INVENTORY_MONITOR_RULE	= S.INVENTORY_MONITOR_RULE,
	T.CAN_USE_AS_SERVICE_TOOL	= S.CAN_USE_AS_SERVICE_TOOL,
	T.NMFC_CLASS	= S.NMFC_CLASS,
	T.RETURN_SHIPPING_LABEL_LEVEL	= S.RETURN_SHIPPING_LABEL_LEVEL,
	T.MAX_CNTR_WEIGHT	= S.MAX_CNTR_WEIGHT,
	T.HARMONIZED_CODE	= S.HARMONIZED_CODE,
	T.ORDERING_QUANTITY_STRATEGY	= S.ORDERING_QUANTITY_STRATEGY,
	T.SIZE_CODE	= S.SIZE_CODE,
	T.OPERATIONAL_CONFIG_COMPLETE	= S.OPERATIONAL_CONFIG_COMPLETE,
	T.INVOICE_BASED_ON_ACTUALS	= S.INVOICE_BASED_ON_ACTUALS,
	T.UNIT_WEIGHT_UOM	= S.UNIT_WEIGHT_UOM,
	T.MASTER_CATALOG_ID	= S.MASTER_CATALOG_ID,
	T.GLOBAL_ITEM_ID	= S.GLOBAL_ITEM_ID,
	T.ATP_RULE	= S.ATP_RULE,
	T.TAG_REQ_AT_RECEIPT	= S.TAG_REQ_AT_RECEIPT,
	T.UNIT_LENGTH_UOM	= S.UNIT_LENGTH_UOM,
	T.MODEL	= S.MODEL,
	T.CONTAINER_TYPE	= S.CONTAINER_TYPE,
	T.PRICING_UOM_STRATEGY	= S.PRICING_UOM_STRATEGY,
	T.IS_FIFO_TRACKED	= S.IS_FIFO_TRACKED,
	T.IS_SHIPPING_ALLOWED	= S.IS_SHIPPING_ALLOWED,
	T.IS_AIR_SHIPPING_ALLOWED	= S.IS_AIR_SHIPPING_ALLOWED,
	T.RETURN_WINDOW	= S.RETURN_WINDOW,
	T.CREDIT_WO_RECEIPT	= S.CREDIT_WO_RECEIPT,
	T.UNIT_WEIGHT	= S.UNIT_WEIGHT,
	T.VOLUME_ALLOWANCE	= S.VOLUME_ALLOWANCE,
	T.VELOCITY_CODE	= S.VELOCITY_CODE,
	T.IS_RETURN_SERVICE	= S.IS_RETURN_SERVICE,
	T.MANUFACTURER_NAME	= S.MANUFACTURER_NAME,
	T.TIME_SENSITIVE	= S.TIME_SENSITIVE,
	T.DEFAULT_PRODUCT_CLASS	= S.DEFAULT_PRODUCT_CLASS,
	T.IS_SERIAL_TRACKED	= S.IS_SERIAL_TRACKED,
	T.ADVANCE_NOTIFICATION_TIME	= S.ADVANCE_NOTIFICATION_TIME,
	T.MAX_MODIFYTS	= S.MAX_MODIFYTS,
	T.REMOTE_MODIFYTS	= S.REMOTE_MODIFYTS,
	T.ONHAND_SAFETY_FACTOR_QTY	= S.ONHAND_SAFETY_FACTOR_QTY,
	T.IS_MODEL_ITEM	= S.IS_MODEL_ITEM,
	T.STATUS	= S.STATUS,
	T.IS_STANDALONE_SERVICE	= S.IS_STANDALONE_SERVICE,
	T.CREATETS	= S.CREATETS,
	T.MIN_ORDER_QUANTITY	= S.MIN_ORDER_QUANTITY,
	T.PRICING_QUANTITY_CONV_FACTOR	= S.PRICING_QUANTITY_CONV_FACTOR,
	T.RUN_QUANTITY	= S.RUN_QUANTITY,
	T.IS_FORWARDING_ALLOWED	= S.IS_FORWARDING_ALLOWED,
	T.NODE_LEVEL_INV_MONITOR_RULE	= S.NODE_LEVEL_INV_MONITOR_RULE,
	T.COLOR_CODE	= S.COLOR_CODE,
	T.UNIT_WIDTH_UOM	= S.UNIT_WIDTH_UOM,
	T.EXTN_SKU_LAYOUT_ID	= S.EXTN_SKU_LAYOUT_ID,
	T.MODIFYTS	= S.MODIFYTS,
	T.SERIALIZED_FLAG	= S.SERIALIZED_FLAG,
	T.CREATEUSERID	= S.CREATEUSERID,
	T.ITEM_GROUP_CODE	= S.ITEM_GROUP_CODE,
	T.IS_SHIPPING_CNTR	= S.IS_SHIPPING_CNTR,
	T.CAPACITY_UOM	= S.CAPACITY_UOM,
	T.UNIT_LENGTH	= S.UNIT_LENGTH,
	T.BUNDLE_FULFILLMENT_MODE	= S.BUNDLE_FULFILLMENT_MODE,
	T.FIXED_PRICING_QTY_PER_LINE	= S.FIXED_PRICING_QTY_PER_LINE,
	T.MANUFACTURER_ITEM_DESC	= S.MANUFACTURER_ITEM_DESC,
	T.UOM	= S.UOM,
	T.COUNTRY_OF_ORIGIN	= S.COUNTRY_OF_ORIGIN,
	T.SERVICE_TYPE_ID	= S.SERVICE_TYPE_ID,
	T.CHARGEBACK_CATEGORY	= S.CHARGEBACK_CATEGORY,
	T.EQUIV_35_UNIT	= S.EQUIV_35_UNIT,
	T.FULFILLMENT_TYPE	= S.FULFILLMENT_TYPE,
	T.SELECTION_TEMPLATE	= S.SELECTION_TEMPLATE,
	T.SHUTTERFLY_ELIGIBLE	= S.SHUTTERFLY_ELIGIBLE
	,                                                                                                                                                T.ODS_MODIFY_DATE	= sysdate
when not matched
then insert
	(
	T.ITEM_KEY,
	T.ITEM_ID,
	T.SCHEDULE_B_CODE,
	T.KIT_CODE,
	T.FUTURE_SAFETY_FACTOR_PCT,
	T.IS_SUB_ON_ORDER_ALLOWED,
	T.PRIMARY_ENTERPRISE_CODE,
	T.MINIMUM_CAPACITY_QUANTITY,
	T.UNSPSC,
	T.PRIMARY_SUPPLIER,
	T.COMMODITY_CODE,
	T.CONFIGURED_MODEL_KEY,
	T.MIN_NOTIFICATION_TIME,
	T.UNIT_HEIGHT,
	T.NAICS_CODE,
	T.MODEL_ITEM_UOM,
	T.CREATEPROGID,
	T.NMFC_CODE,
	T.REQUIRES_PROD_ASSOCIATION,
	T.IS_PROCUREMENT_ALLOWED,
	T.INVOLVES_SEGMENT_CHANGE,
	T.DESCRIPTION,
	T.SYNCTS,
	T.MAX_ORDER_QUANTITY,
	T.IS_PARCEL_SHIPPING_ALLOWED,
	T.IS_RETURNABLE,
	T.POSTING_CLASSIFICATION,
	T.MODIFYUSERID,
	T.MODIFYPROGID,
	T.CAPACITY_VOLUME_UOM,
	T.IS_PICKUP_ALLOWED,
	T.LEAD_TIME,
	T.EXTN_LOOK_SELECTION_ALLOWED,
	T.IS_DELIVERY_ALLOWED,
	T.LOCKID,
	T.IS_CONFIGURABLE,
	T.SHP_CONSOL_WINDOW,
	T.HAZMAT_CLASS,
	T.TAX_PRODUCT_CODE,
	T.UNIT_COST,
	T.ITEM_TYPE,
	T.ORGANIZATION_CODE,
	T.ASSUME_INFINITE_INVENTORY,
	T.MAX_CNTR_WEIGHT_UOM,
	T.STORAGE_TYPE,
	T.MANUFACTURER_ITEM,
	T.NUM_SECONDARY_SERIALS,
	T.UPC_COM_PRE_LEN,
	T.IS_PRE_CONFIGURED,
	T.SUB_CLASS,
	T.EMPTY_CNTR_WEIGHT,
	T.TAG_REQ_AT_SHIPMENT,
	T.PICKING_TYPE,
	T.DEPARTMENT,
	T.CAPACITY_QUANTITY_STRATEGY,
	T.CAPACITY_VOLUME,
	T.USE_UNPLANNED_INV,
	T.PRODUCT_LINE,
	T.UNIT_HEIGHT_UOM,
	T.IS_FREEZER_REQUIRED,
	T.PRICING_QUANTITY_STRATEGY,
	T.ONHAND_SAFETY_FACTOR_PCT,
	T.COMPUTED_UNIT_COST,
	T.UNIT_WIDTH,
	T.SHORT_DESCRIPTION,
	T.TAXABLE_FLAG,
	T.CONTAINER_SIZE,
	T.ECCN_NO,
	T.TAG_CONTROL_FLAG,
	T.IS_IBA_ALLOWED,
	T.CLASS,
	T.CAPACITY_PER_ORDERED_QTY,
	T.COST_CURRENCY,
	T.IS_HAZMAT,
	T.DEFAULT_EXPIRATION_DAYS,
	T.FIXED_CAPACITY_QTY_PER_LINE,
	T.PRICING_UOM,
	T.EXTENDED_DESCRIPTION,
	T.PROCESSING_TIME,
	T.INVENTORY_MONITOR_RULE,
	T.CAN_USE_AS_SERVICE_TOOL,
	T.NMFC_CLASS,
	T.RETURN_SHIPPING_LABEL_LEVEL,
	T.MAX_CNTR_WEIGHT,
	T.HARMONIZED_CODE,
	T.ORDERING_QUANTITY_STRATEGY,
	T.SIZE_CODE,
	T.OPERATIONAL_CONFIG_COMPLETE,
	T.INVOICE_BASED_ON_ACTUALS,
	T.UNIT_WEIGHT_UOM,
	T.MASTER_CATALOG_ID,
	T.GLOBAL_ITEM_ID,
	T.ATP_RULE,
	T.TAG_REQ_AT_RECEIPT,
	T.UNIT_LENGTH_UOM,
	T.MODEL,
	T.CONTAINER_TYPE,
	T.PRICING_UOM_STRATEGY,
	T.IS_FIFO_TRACKED,
	T.IS_SHIPPING_ALLOWED,
	T.IS_AIR_SHIPPING_ALLOWED,
	T.RETURN_WINDOW,
	T.CREDIT_WO_RECEIPT,
	T.UNIT_WEIGHT,
	T.VOLUME_ALLOWANCE,
	T.VELOCITY_CODE,
	T.IS_RETURN_SERVICE,
	T.MANUFACTURER_NAME,
	T.TIME_SENSITIVE,
	T.DEFAULT_PRODUCT_CLASS,
	T.IS_SERIAL_TRACKED,
	T.ADVANCE_NOTIFICATION_TIME,
	T.MAX_MODIFYTS,
	T.REMOTE_MODIFYTS,
	T.ONHAND_SAFETY_FACTOR_QTY,
	T.IS_MODEL_ITEM,
	T.STATUS,
	T.IS_STANDALONE_SERVICE,
	T.CREATETS,
	T.MIN_ORDER_QUANTITY,
	T.PRICING_QUANTITY_CONV_FACTOR,
	T.RUN_QUANTITY,
	T.IS_FORWARDING_ALLOWED,
	T.NODE_LEVEL_INV_MONITOR_RULE,
	T.COLOR_CODE,
	T.UNIT_WIDTH_UOM,
	T.EXTN_SKU_LAYOUT_ID,
	T.MODIFYTS,
	T.SERIALIZED_FLAG,
	T.CREATEUSERID,
	T.ITEM_GROUP_CODE,
	T.IS_SHIPPING_CNTR,
	T.CAPACITY_UOM,
	T.UNIT_LENGTH,
	T.BUNDLE_FULFILLMENT_MODE,
	T.FIXED_PRICING_QTY_PER_LINE,
	T.MANUFACTURER_ITEM_DESC,
	T.UOM,
	T.COUNTRY_OF_ORIGIN,
	T.SERVICE_TYPE_ID,
	T.CHARGEBACK_CATEGORY,
	T.EQUIV_35_UNIT,
	T.FULFILLMENT_TYPE,
	T.SELECTION_TEMPLATE,
	T.SHUTTERFLY_ELIGIBLE
	,                                                                                                                                                 T.ODS_CREATE_DATE,
	T.ODS_MODIFY_DATE
	)
values
	(
	S.ITEM_KEY,
	S.ITEM_ID,
	S.SCHEDULE_B_CODE,
	S.KIT_CODE,
	S.FUTURE_SAFETY_FACTOR_PCT,
	S.IS_SUB_ON_ORDER_ALLOWED,
	S.PRIMARY_ENTERPRISE_CODE,
	S.MINIMUM_CAPACITY_QUANTITY,
	S.UNSPSC,
	S.PRIMARY_SUPPLIER,
	S.COMMODITY_CODE,
	S.CONFIGURED_MODEL_KEY,
	S.MIN_NOTIFICATION_TIME,
	S.UNIT_HEIGHT,
	S.NAICS_CODE,
	S.MODEL_ITEM_UOM,
	S.CREATEPROGID,
	S.NMFC_CODE,
	S.REQUIRES_PROD_ASSOCIATION,
	S.IS_PROCUREMENT_ALLOWED,
	S.INVOLVES_SEGMENT_CHANGE,
	S.DESCRIPTION,
	S.SYNCTS,
	S.MAX_ORDER_QUANTITY,
	S.IS_PARCEL_SHIPPING_ALLOWED,
	S.IS_RETURNABLE,
	S.POSTING_CLASSIFICATION,
	S.MODIFYUSERID,
	S.MODIFYPROGID,
	S.CAPACITY_VOLUME_UOM,
	S.IS_PICKUP_ALLOWED,
	S.LEAD_TIME,
	S.EXTN_LOOK_SELECTION_ALLOWED,
	S.IS_DELIVERY_ALLOWED,
	S.LOCKID,
	S.IS_CONFIGURABLE,
	S.SHP_CONSOL_WINDOW,
	S.HAZMAT_CLASS,
	S.TAX_PRODUCT_CODE,
	S.UNIT_COST,
	S.ITEM_TYPE,
	S.ORGANIZATION_CODE,
	S.ASSUME_INFINITE_INVENTORY,
	S.MAX_CNTR_WEIGHT_UOM,
	S.STORAGE_TYPE,
	S.MANUFACTURER_ITEM,
	S.NUM_SECONDARY_SERIALS,
	S.UPC_COM_PRE_LEN,
	S.IS_PRE_CONFIGURED,
	S.SUB_CLASS,
	S.EMPTY_CNTR_WEIGHT,
	S.TAG_REQ_AT_SHIPMENT,
	S.PICKING_TYPE,
	S.DEPARTMENT,
	S.CAPACITY_QUANTITY_STRATEGY,
	S.CAPACITY_VOLUME,
	S.USE_UNPLANNED_INV,
	S.PRODUCT_LINE,
	S.UNIT_HEIGHT_UOM,
	S.IS_FREEZER_REQUIRED,
	S.PRICING_QUANTITY_STRATEGY,
	S.ONHAND_SAFETY_FACTOR_PCT,
	S.COMPUTED_UNIT_COST,
	S.UNIT_WIDTH,
	S.SHORT_DESCRIPTION,
	S.TAXABLE_FLAG,
	S.CONTAINER_SIZE,
	S.ECCN_NO,
	S.TAG_CONTROL_FLAG,
	S.IS_IBA_ALLOWED,
	S.CLASS,
	S.CAPACITY_PER_ORDERED_QTY,
	S.COST_CURRENCY,
	S.IS_HAZMAT,
	S.DEFAULT_EXPIRATION_DAYS,
	S.FIXED_CAPACITY_QTY_PER_LINE,
	S.PRICING_UOM,
	S.EXTENDED_DESCRIPTION,
	S.PROCESSING_TIME,
	S.INVENTORY_MONITOR_RULE,
	S.CAN_USE_AS_SERVICE_TOOL,
	S.NMFC_CLASS,
	S.RETURN_SHIPPING_LABEL_LEVEL,
	S.MAX_CNTR_WEIGHT,
	S.HARMONIZED_CODE,
	S.ORDERING_QUANTITY_STRATEGY,
	S.SIZE_CODE,
	S.OPERATIONAL_CONFIG_COMPLETE,
	S.INVOICE_BASED_ON_ACTUALS,
	S.UNIT_WEIGHT_UOM,
	S.MASTER_CATALOG_ID,
	S.GLOBAL_ITEM_ID,
	S.ATP_RULE,
	S.TAG_REQ_AT_RECEIPT,
	S.UNIT_LENGTH_UOM,
	S.MODEL,
	S.CONTAINER_TYPE,
	S.PRICING_UOM_STRATEGY,
	S.IS_FIFO_TRACKED,
	S.IS_SHIPPING_ALLOWED,
	S.IS_AIR_SHIPPING_ALLOWED,
	S.RETURN_WINDOW,
	S.CREDIT_WO_RECEIPT,
	S.UNIT_WEIGHT,
	S.VOLUME_ALLOWANCE,
	S.VELOCITY_CODE,
	S.IS_RETURN_SERVICE,
	S.MANUFACTURER_NAME,
	S.TIME_SENSITIVE,
	S.DEFAULT_PRODUCT_CLASS,
	S.IS_SERIAL_TRACKED,
	S.ADVANCE_NOTIFICATION_TIME,
	S.MAX_MODIFYTS,
	S.REMOTE_MODIFYTS,
	S.ONHAND_SAFETY_FACTOR_QTY,
	S.IS_MODEL_ITEM,
	S.STATUS,
	S.IS_STANDALONE_SERVICE,
	S.CREATETS,
	S.MIN_ORDER_QUANTITY,
	S.PRICING_QUANTITY_CONV_FACTOR,
	S.RUN_QUANTITY,
	S.IS_FORWARDING_ALLOWED,
	S.NODE_LEVEL_INV_MONITOR_RULE,
	S.COLOR_CODE,
	S.UNIT_WIDTH_UOM,
	S.EXTN_SKU_LAYOUT_ID,
	S.MODIFYTS,
	S.SERIALIZED_FLAG,
	S.CREATEUSERID,
	S.ITEM_GROUP_CODE,
	S.IS_SHIPPING_CNTR,
	S.CAPACITY_UOM,
	S.UNIT_LENGTH,
	S.BUNDLE_FULFILLMENT_MODE,
	S.FIXED_PRICING_QTY_PER_LINE,
	S.MANUFACTURER_ITEM_DESC,
	S.UOM,
	S.COUNTRY_OF_ORIGIN,
	S.SERVICE_TYPE_ID,
	S.CHARGEBACK_CATEGORY,
	S.EQUIV_35_UNIT,
	S.FULFILLMENT_TYPE,
	S.SELECTION_TEMPLATE,
	S.SHUTTERFLY_ELIGIBLE
	,                                                                                                                                                 sysdate,
	sysdate
	)

&


/*-----------------------------------------------*/
/* TASK No. 16 */
/* Commit transaction */

/*commit*/


/*-----------------------------------------------*/
/* TASK No. 17 */
/* Drop flow table */

drop table RAX_APP_USER.I$_OMS3_ITEM_STG2079001 

&


/*-----------------------------------------------*/
/* TASK No. 1000008 */
/* Drop work table */

drop table RAX_APP_USER.C$_0OMS3_ITEM_STG purge

&


/*-----------------------------------------------*/
/* TASK No. 18 */
/* ODS_STAGE.ITEM_XR */

-- oms3_xr
MERGE INTO ODS_STAGE.ITEM_XR d
USING (
    Select
         item.ITEM_oid as ITEM_ITEM_oid
        ,xr.ITEM_oid as xr_ITEM_oid
        ,nvl(item.ITEM_oid,xr.ITEM_oid) ITEM_oid
        ,STG.ITEM_ID as ITEM_ID
        ,stg.ITEM_KEY as OMS3_ITEM_KEY
        ,xr.OMS2_ITEM_KEY
        ,xr.DW_ITEM_KEY
        ,'OMS' as SYSTEM_OF_RECORD
        ,sysdate as ODS_CREATE_DATE
        ,sysdate as ODS_MODIFY_DATE
    -- select *
    FROM 
        ODS_STAGE.OMS3_ITEM_STG stg
        ,ODS_OWN.ITEM item
        ,ODS_STAGE.ITEM_XR xr
    WHERE (1=1)
        and trim(stg.ITEM_ID)=trim(xr.ITEM_ID(+))
--        and trim(stg.ITEM_KEY)=trim(xr.OMS3_ITEM_KEY(+))
        and stg.ITEM_ID=item.ITEM_ID(+)
) s 
ON
  (s.ITEM_ID=d.ITEM_ID)
WHEN MATCHED THEN UPDATE SET
  d.ITEM_OID = s.ITEM_OID,
  d.OMS3_ITEM_KEY = s.OMS3_ITEM_KEY,
  d.OMS2_ITEM_KEY = s.OMS2_ITEM_KEY,
  d.DW_ITEM_KEY = s.DW_ITEM_KEY,
  d.SYSTEM_OF_RECORD = s.SYSTEM_OF_RECORD,
  d.ODS_MODIFY_DATE = s.ODS_MODIFY_DATE
WHERE
    decode(s.ITEM_OID,d.ITEM_OID,1,0) = 0
    or decode(s.OMS3_ITEM_KEY,d.OMS3_ITEM_KEY,1,0) = 0
    or decode(s.OMS2_ITEM_KEY,d.OMS2_ITEM_KEY,1,0) = 0
    or decode(s.DW_ITEM_KEY,d.DW_ITEM_KEY,1,0) = 0
    or decode(s.SYSTEM_OF_RECORD,d.SYSTEM_OF_RECORD,1,0) = 0
WHEN NOT MATCHED THEN INSERT 
(
  ITEM_OID, ITEM_ID, OMS3_ITEM_KEY, OMS2_ITEM_KEY,
  DW_ITEM_KEY, SYSTEM_OF_RECORD, ODS_CREATE_DATE, ODS_MODIFY_DATE)
VALUES (
  nvl(s.ITEM_OID, ODS_STAGE.ITEM_OID_SEQ.nextval), s.ITEM_ID, s.OMS3_ITEM_KEY, s.OMS2_ITEM_KEY,
  s.DW_ITEM_KEY, s.SYSTEM_OF_RECORD, s.ODS_CREATE_DATE, s.ODS_MODIFY_DATE)

&


/*-----------------------------------------------*/
/* TASK No. 19 */
/* ODS_OWN.ITEM */

-- oms3
merge into	ODS_OWN.ITEM T
using (	
select 	 
	xr.ITEM_OID ITEM_OID
	,stg.ITEM_ID
	,stg.DESCRIPTION 
	,stg.PRODUCT_LINE 
	,stg.ITEM_TYPE 
	,stg.TAX_PRODUCT_CODE 
	,stg.ITEM_GROUP_CODE 
	,ss.SOURCE_SYSTEM_OID 
	,stg.CHARGEBACK_CATEGORY 
	,case when stg.item_type = 'NonPortraitProducts' then stg.PRODUCT_LINE else 'N/A' end CHARGE_TYPE
	,nvl( trim(stg.POSTING_CLASSIFICATION), 'Unknown') POSTING_CLASSIFICATION
	--,ig.ITEM_GROUP_OID 
	,stg.MANUFACTURER_ITEM 
	,stg.SUB_CLASS 
	,stg.SHORT_DESCRIPTION 
	,stg.STATUS STATUS
	,stg.EXTN_SKU_LAYOUT_ID SKU_LAYOUT_ID
    ,sku.CATEGORY SKU_CATEGORY
    ,stg.DESCRIPTION PRODUCT_DETAIL_DESCRIPTION
	,sysdate ODS_MODIFY_DATE
	,sysdate ODS_CREATE_DATE
                        , stg.FULFILLMENT_TYPE
                        , stg.SELECTION_TEMPLATE
from	
    ODS_STAGE.OMS3_ITEM_STG stg   
    ,ODS_STAGE.ITEM_XR   xr
  -- ,ODS_OWN.ITEM_GROUP   ig
    ,ODS_OWN.SOURCE_SYSTEM   ss
    ,ODS_OWN.STOCK_KEEPING_UNIT sku
where	(1=1)
    and stg.ITEM_ID=xr.ITEM_ID
   -- and stg.ITEM_GROUP=ig.ITEM_GROUP (+)
    and ss.SOURCE_SYSTEM_SHORT_NAME='OMS'
    and stg.ITEM_ID = sku.SKU_CODE(+)
    and xr.SYSTEM_OF_RECORD = 'OMS'
) S
on	(T.ITEM_OID=S.ITEM_OID)
when matched then update set
	T.ITEM_ID	= S.ITEM_ID,
	T.DESCRIPTION	= S.DESCRIPTION,
	T.PRODUCT_LINE	= S.PRODUCT_LINE,
	T.ITEM_TYPE	= S.ITEM_TYPE,
	T.TAX_PRODUCT_CODE	= S.TAX_PRODUCT_CODE,
	T.ITEM_GROUP_CODE	= S.ITEM_GROUP_CODE,
	T.SOURCE_SYSTEM_OID	= S.SOURCE_SYSTEM_OID,
	T.CHARGEBACK_CATEGORY	= S.CHARGEBACK_CATEGORY,
	T.CHARGE_TYPE	= S.CHARGE_TYPE,
	T.POSTING_CLASSIFICATION	= S.POSTING_CLASSIFICATION,
	--T.ITEM_GROUP_OID	= S.ITEM_GROUP_OID,
	T.MANUFACTURER_ITEM	= S.MANUFACTURER_ITEM,
	T.SUB_CLASS	= S.SUB_CLASS,
	T.SHORT_DESCRIPTION	= S.SHORT_DESCRIPTION,
	T.STATUS	= S.STATUS,
	T.SKU_LAYOUT_ID = S.SKU_LAYOUT_ID,
    T.SKU_CATEGORY = S.SKU_CATEGORY,
    T.PRODUCT_DETAIL_DESCRIPTION = S.PRODUCT_DETAIL_DESCRIPTION,
	T.ODS_MODIFY_DATE	= S.ODS_MODIFY_DATE,
                        T.FULFILLMENT_TYPE               = S.FULFILLMENT_TYPE,
                        T.SELECTION_TEMPLATE          = S.SELECTION_TEMPLATE
where
    decode(s.ITEM_ID,t.ITEM_ID,1,0) = 0
    or decode(s.DESCRIPTION,t.DESCRIPTION,1,0) = 0
    or decode(s.PRODUCT_LINE,t.PRODUCT_LINE,1,0) = 0
    or decode(s.ITEM_TYPE,t.ITEM_TYPE,1,0) = 0
    or decode(s.TAX_PRODUCT_CODE,t.TAX_PRODUCT_CODE,1,0) = 0
    or decode(s.ITEM_GROUP_CODE,t.ITEM_GROUP_CODE,1,0) = 0
    or decode(s.SOURCE_SYSTEM_OID,t.SOURCE_SYSTEM_OID,1,0) = 0
    or decode(s.CHARGEBACK_CATEGORY,t.CHARGEBACK_CATEGORY,1,0) = 0
    or decode(s.CHARGE_TYPE,t.CHARGE_TYPE,1,0) = 0
    or decode(s.POSTING_CLASSIFICATION,t.POSTING_CLASSIFICATION,1,0) = 0
    --or decode(s.ITEM_GROUP_OID,t.ITEM_GROUP_OID,1,0) = 0
    or decode(s.MANUFACTURER_ITEM,t.MANUFACTURER_ITEM,1,0) = 0
    or decode(s.SUB_CLASS,t.SUB_CLASS,1,0) = 0
    or decode(s.SHORT_DESCRIPTION,t.SHORT_DESCRIPTION,1,0) = 0
    or decode(s.STATUS,t.STATUS,1,0) = 0
    or decode(s.SKU_LAYOUT_ID,t.SKU_LAYOUT_ID,1,0) = 0
    or decode(s.SKU_CATEGORY,t.SKU_CATEGORY,1,0) = 0
    or decode(s.PRODUCT_DETAIL_DESCRIPTION,t.PRODUCT_DETAIL_DESCRIPTION,1,0) = 0
    or decode(s.FULFILLMENT_TYPE ,t.FULFILLMENT_TYPE ,1,0) = 0
    or decode(s.SELECTION_TEMPLATE ,t.SELECTION_TEMPLATE ,1,0) = 0
when not matched then insert
	(
	ITEM_OID,
	ITEM_ID,
	DESCRIPTION,
	PRODUCT_LINE,
	ITEM_TYPE,
	TAX_PRODUCT_CODE,
	ITEM_GROUP_CODE,
	SKU_LAYOUT_ID,
	SOURCE_SYSTEM_OID,
	CHARGEBACK_CATEGORY,
	CHARGE_TYPE,
	POSTING_CLASSIFICATION,
	--ITEM_GROUP_OID,
                        SKU_CATEGORY,
	MANUFACTURER_ITEM,
	SUB_CLASS,
                        PRODUCT_DETAIL_DESCRIPTION,
	SHORT_DESCRIPTION,
	STATUS,
	ODS_CREATE_DATE,
	ODS_MODIFY_DATE,
                        FULFILLMENT_TYPE,
                        SELECTION_TEMPLATE
	)
values
	(
	S.ITEM_OID,
	S.ITEM_ID,
	S.DESCRIPTION,
	S.PRODUCT_LINE,
	S.ITEM_TYPE,
	S.TAX_PRODUCT_CODE,
	S.ITEM_GROUP_CODE,
	S.SKU_LAYOUT_ID,
	S.SOURCE_SYSTEM_OID,
	S.CHARGEBACK_CATEGORY,
	S.CHARGE_TYPE,
	S.POSTING_CLASSIFICATION,
	--S.ITEM_GROUP_OID,
    S.SKU_CATEGORY,
	S.MANUFACTURER_ITEM,
	S.SUB_CLASS,
    S.PRODUCT_DETAIL_DESCRIPTION,
	S.SHORT_DESCRIPTION,
	S.STATUS,
	S.ODS_CREATE_DATE,
	S.ODS_MODIFY_DATE,
                        S.FULFILLMENT_TYPE,
                        S.SELECTION_TEMPLATE
	)


&


/*-----------------------------------------------*/
/* TASK No. 20 */
/* Update CDC Load Status */

UPDATE ODS_OWN.ODS_CDC_LOAD_STATUS
SET LAST_CDC_COMPLETION_DATE=TO_DATE(
             SUBSTR(:v_sess_beg, 1, 19), 'RRRR-MM-DD HH24:MI:SS')
+ nvl((TIMEZONE_OFFSET/24), 0) 
WHERE ODS_TABLE_NAME=:v_cdc_load_table_name
AND CONTEXT_NAME = :v_env

/*
UPDATE ODS_OWN.ODS_CDC_LOAD_STATUS
SET LAST_CDC_COMPLETION_DATE=TO_DATE(
             SUBSTR(:v_sess_beg, 1, 19), 'RRRR-MM-DD HH24:MI:SS')
WHERE ODS_TABLE_NAME=:v_cdc_load_table_name
AND CONTEXT_NAME = :v_env
*/

&


/*-----------------------------------------------*/
/* TASK No. 21 */
/* Insert CDC Audit Record */

INSERT INTO RAX_APP_USER.ODS_CDC_LOAD_STATUS_AUDIT
(TABLE_NAME,
SESS_NO,                      
SESS_NAME,                    
SCEN_VERSION,                 
SESS_BEG,                     
ORIG_LAST_CDC_COMPLETION_DATE,
OVERLAP,
CREATE_DATE,
CONTEXT_NAME,
TIMEZONE_OFFSET              
)
select 
:v_cdc_load_table_name
,:v_sess_no
,'LOAD_ITEM_PKG'
,'028'
,TO_DATE(SUBSTR(:v_sess_beg, 1, 19), 'RRRR-MM-DD HH24:MI:SS')
,TO_DATE (SUBSTR(:v_cdc_load_date, 1, 19),'YYYY-MM-DD HH24:MI:SS')
,:v_cdc_overlap
,SYSDATE
,:v_env
,TIMEZONE_OFFSET
from 
ODS_OWN.ODS_CDC_LOAD_STATUS
WHERE ODS_TABLE_NAME=:v_cdc_load_table_name
AND CONTEXT_NAME = :v_env

/*
INSERT INTO RAX_APP_USER.ODS_CDC_LOAD_STATUS_AUDIT
(TABLE_NAME,
SESS_NO,                      
SESS_NAME,                    
SCEN_VERSION,                 
SESS_BEG,                     
ORIG_LAST_CDC_COMPLETION_DATE,
OVERLAP,
CREATE_DATE,
CONTEXT_NAME              
)
values (
:v_cdc_load_table_name,
:v_sess_no,
'LOAD_ITEM_PKG',
'028',
TO_DATE(
             SUBSTR(:v_sess_beg, 1, 19), 'RRRR-MM-DD HH24:MI:SS'),
TO_DATE (SUBSTR (:v_cdc_load_date, 1, 19),
                           'YYYY-MM-DD HH24:MI:SS'
                          )
,:v_cdc_overlap,
SYSDATE,
 :v_env)
*/


&


/*-----------------------------------------------*/
