/* TASK No. 1 */

/* NONE or SET VARIABLE STATEMENT FOUND, CHECK ODI TASK NO. 1 */




/*-----------------------------------------------*/
/* TASK No. 2 */

/* SELECT STATEMENT FOUND, CHECK ODI TASK NO. 2 */




/*-----------------------------------------------*/
/* TASK No. 3 */

/* SELECT STATEMENT FOUND, CHECK ODI TASK NO. 3 */




/*-----------------------------------------------*/
/* TASK No. 4 */
/* Drop work table */

-- drop table RAX_APP_USER.C$_0STG_SHIPMENT 

-- &


-- /*-----------------------------------------------*/
-- /* TASK No. 5 */
-- /* Create work table */

-- create table RAX_APP_USER.C$_0STG_SHIPMENT
-- (
-- 	C1_NEXT_ALERT_TS	DATE NULL,
-- 	C2_BILL_TO_ADDRESS_KEY	CHAR(24) NULL,
-- 	C3_IS_PACK_PROCESS_COMPLETE	CHAR(1) NULL,
-- 	C4_SHIPMENT_SORT_LOCATION_ID	VARCHAR2(40) NULL,
-- 	C5_EXPORT_TAXPAYER_ID	VARCHAR2(40) NULL,
-- 	C6_TOTAL_ESTIMATED_CHARGE	NUMBER(15,2) NULL,
-- 	C7_ROUTING_SOURCE	CHAR(2) NULL,
-- 	C8_CREATETS	DATE NULL,
-- 	C9_TRAILER_NO	CHAR(40) NULL,
-- 	C10_SHIPMENT_NO	CHAR(40) NULL,
-- 	C11_ACTUAL_DELIVERY_DATE	DATE NULL,
-- 	C12_EXPORT_LICENSE_EXP_DATE	DATE NULL,
-- 	C13_INVOICE_COMPLETE	CHAR(1) NULL,
-- 	C14_CARRIER_PICKUP_TIME	DATE NULL,
-- 	C15_EXPORT_LICENSE_NO	VARCHAR2(40) NULL,
-- 	C16_DOWNLOAD_COUNT	NUMBER(5) NULL,
-- 	C17_MODIFYTS	DATE NULL,
-- 	C18_REQUESTED_DELIVERY_DATE	DATE NULL,
-- 	C19_ALLOW_OVERAGE	CHAR(1) NULL,
-- 	C20_MUST_SHIP_BEFORE_DATE	DATE NULL,
-- 	C21_LOCKID	NUMBER(5) NULL,
-- 	C22_SHIPMENT_PLANNED_FLAG	CHAR(1) NULL,
-- 	C23_UNPLACED_QUANTITY	NUMBER(14,4) NULL,
-- 	C24_REQUESTED_CARRIER_SERVICE_	VARCHAR2(40) NULL,
-- 	C25_REQUIRES_APPT_CONFIRMATION	CHAR(1) NULL,
-- 	C26_IT_NO	CHAR(30) NULL,
-- 	C27_BOL_NO	CHAR(40) NULL,
-- 	C28_OVERRIDE_MANUAL_SHIPMENT_E	CHAR(1) NULL,
-- 	C29_DELIVERY_TS	DATE NULL,
-- 	C30_PARENT_SHIPMENT_KEY	CHAR(24) NULL,
-- 	C31_COD_PAY_METHOD	VARCHAR2(40) NULL,
-- 	C32_NUM_OF_CARTONS	NUMBER(5) NULL,
-- 	C33_WORK_ORDER_APPT_KEY	CHAR(24) NULL,
-- 	C34_PLACED_QUANTITY	NUMBER(14,4) NULL,
-- 	C35_LINES_ENTERED	CHAR(1) NULL,
-- 	C36_CARRIER_SORT_LOCATION_ID	VARCHAR2(40) NULL,
-- 	C37_REQUESTED_SHIPMENT_DATE	DATE NULL,
-- 	C38_TOTAL_WEIGHT_UOM	VARCHAR2(40) NULL,
-- 	C39_ACTUAL_SHIPMENT_DATE	DATE NULL,
-- 	C40_IS_PRODUCT_PLACING_COMPLET	CHAR(1) NULL,
-- 	C41_SHIPMENT_KEY	CHAR(24) NULL,
-- 	C42_TO_ADDRESS_KEY	CHAR(24) NULL,
-- 	C43_SHIP_DATE	DATE NULL,
-- 	C44_CODE	VARCHAR2(40) NULL,
-- 	C45_ACTUAL_FREIGHT_CHARGE	NUMBER(15,2) NULL,
-- 	C46_PICKTICKET_NO	CHAR(24) NULL,
-- 	C47_RETURN_FREIGHT_TERMS	CHAR(3) NULL,
-- 	C48_EXPECTED_PICK_DATE	DATE NULL,
-- 	C49_DEPARTMENT_CODE	VARCHAR2(20) NULL,
-- 	C50_ITN_NO	VARCHAR2(40) NULL,
-- 	C51_PACKLIST_TYPE	VARCHAR2(20) NULL,
-- 	C52_ITEM_CLASSIFICATION	VARCHAR2(40) NULL,
-- 	C53_SHIPMENT_DELIVER_UPDATES_D	CHAR(1) NULL,
-- 	C54_SELLER_ORGANIZATION_CODE	CHAR(24) NULL,
-- 	C55_BBN_MIN_VOLUME	NUMBER(14,4) NULL,
-- 	C56_APPOINTMENT_NO	CHAR(40) NULL,
-- 	C57_ALLOW_NEW_ITEM_RECEIPT	VARCHAR2(20) NULL,
-- 	C58_ORDER_HEADER_KEY	CHAR(24) NULL,
-- 	C59_GIFT_FLAG	CHAR(1) NULL,
-- 	C60_FROM_ADDRESS_KEY	CHAR(24) NULL,
-- 	C61_TRACKING_NO	CHAR(40) NULL,
-- 	C62_ORDER_AVAILABLE_ON_SYSTEM	CHAR(1) NULL,
-- 	C63_MANIFEST_NO	CHAR(40) NULL,
-- 	C64_DELIVERY_CODE	VARCHAR2(40) NULL,
-- 	C65_STATUS_DATE	DATE NULL,
-- 	C66_MODIFYUSERID	VARCHAR2(40) NULL,
-- 	C67_CUSTOMER_PO_NO	VARCHAR2(100) NULL,
-- 	C68_RETURN_BILLING_ACCOUNT	VARCHAR2(40) NULL,
-- 	C69_DO_NOT_CONSOLIDATE	CHAR(1) NULL,
-- 	C70_SHIP_VIA	VARCHAR2(10) NULL,
-- 	C71_DESTINATION_ZONE	VARCHAR2(40) NULL,
-- 	C72_EXTN_SORT_TYPE	VARCHAR2(10) NULL,
-- 	C73_EXTN_ROOM_BOARD_ITEM_ID	VARCHAR2(5) NULL,
-- 	C74_MODIFYPROGID	VARCHAR2(40) NULL,
-- 	C75_PROFILEID_PROVIDED_BY_STER	CHAR(1) NULL,
-- 	C76_ORDER_TYPE	VARCHAR2(20) NULL,
-- 	C77_COMMERCIAL_VALUE	NUMBER(15,2) NULL,
-- 	C78_SHIP_MODE	VARCHAR2(40) NULL,
-- 	C79_AIRWAY_BILL_NO	CHAR(40) NULL,
-- 	C80_MARK_FOR_KEY	CHAR(24) NULL,
-- 	C81_HAS_OTHER_SHIPMENTS	CHAR(1) NULL,
-- 	C82_ORIGIN_ZONE	VARCHAR2(40) NULL,
-- 	C83_RETURN_BY_DATE	DATE NULL,
-- 	C84_ORDER_NO	CHAR(40) NULL,
-- 	C85_SHIPMENT_CONSOL_GROUP_ID	CHAR(24) NULL,
-- 	C86_IT_DATE	DATE NULL,
-- 	C87_CONTAINERIZED_QUANTITY	NUMBER(14,4) NULL,
-- 	C88_STATUS	CHAR(15) NULL,
-- 	C89_SHIPMENT_CONTAINERIZED_FLA	CHAR(2) NULL,
-- 	C90_RETURN_CARRIER_SERVICE	VARCHAR2(40) NULL,
-- 	C91_HAZARDOUS_MATERIAL_FLAG	CHAR(1) NULL,
-- 	C92_RECEIVING_NODE	CHAR(24) NULL,
-- 	C93_ORIGINAL_SHIPMENT_KEY	CHAR(24) NULL,
-- 	C94_DO_NOT_VERIFY_CASE_CONTENT	CHAR(1) NULL,
-- 	C95_BREAK_BULK_NODE	CHAR(24) NULL,
-- 	C96_EXPECTED_SHIPMENT_DATE	DATE NULL,
-- 	C97_TO_APPOINTMENT	DATE NULL,
-- 	C98_SHIP_TO_CUSTOMER_ID	VARCHAR2(40) NULL,
-- 	C99_SCAC_INTEGRATION_REQUIRED	CHAR(1) NULL,
-- 	C100_IS_SINGLE_ORDER	CHAR(1) NULL,
-- 	C101_ROUTING_ERROR_CODE	VARCHAR2(100) NULL,
-- 	C102_CREATEPROGID	VARCHAR2(40) NULL,
-- 	C103_SEAL_NO	CHAR(40) NULL,
-- 	C104_DELIVERY_METHOD	VARCHAR2(40) NULL,
-- 	C105_TOTAL_QUANTITY	NUMBER(14,4) NULL,
-- 	C106_EMAIL_RETURN_LABEL	CHAR(1) NULL,
-- 	C107_BBN_MIN_WEIGHT	NUMBER(14,4) NULL,
-- 	C108_ROUTING_GUIDE_MAINTAINED	CHAR(2) NULL,
-- 	C109_TOTAL_VOLUME_UOM	VARCHAR2(40) NULL,
-- 	C110_MANUALLY_ENTERED	CHAR(1) NULL,
-- 	C111_DO_NOT_VERIFY_PALLET_CONT	CHAR(1) NULL,
-- 	C112_IS_APPOINTMENT_REQD	CHAR(1) NULL,
-- 	C113_CARRIER_TYPE	VARCHAR2(40) NULL,
-- 	C114_CURRENCY	VARCHAR2(20) NULL,
-- 	C115_EXTN_ROOM_BOARD_URL	VARCHAR2(100) NULL,
-- 	C116_BUYER_RECEIVING_NODE_ID	CHAR(24) NULL,
-- 	C117_FREIGHT_TERMS	VARCHAR2(40) NULL,
-- 	C118_WORK_ORDER_KEY	CHAR(24) NULL,
-- 	C119_HAS_NODE_EXCEPTIONS	CHAR(1) NULL,
-- 	C120_FEDX_OPEN_SHIP_INDEX	VARCHAR2(10) NULL,
-- 	C121_ORDER_RELEASE_KEY	CHAR(24) NULL,
-- 	C122_TOTAL_VOLUME	NUMBER(14,4) NULL,
-- 	C123_POD_NO	CHAR(40) NULL,
-- 	C124_FROM_APPOINTMENT	DATE NULL,
-- 	C125_BUYER_ORGANIZATION_CODE	CHAR(24) NULL,
-- 	C126_RETURN_AUTHORIZATION_NUMB	VARCHAR2(40) NULL,
-- 	C127_SCAC	CHAR(24) NULL,
-- 	C128_IS_REVISED	CHAR(1) NULL,
-- 	C129_HOLD_FLAG	CHAR(1) NULL,
-- 	C130_ROUTING_CONTACT_INFO	VARCHAR2(250) NULL,
-- 	C131_EXPECTED_DELIVERY_DATE	DATE NULL,
-- 	C132_PRIORITY_CODE	VARCHAR2(256) NULL,
-- 	C133_DOCUMENT_TYPE	VARCHAR2(40) NULL,
-- 	C134_SHIPMENT_TYPE	VARCHAR2(40) NULL,
-- 	C135_ENTERPRISE_CODE	CHAR(24) NULL,
-- 	C136_CUSTCARRIER_ACCOUNT_NO	VARCHAR2(40) NULL,
-- 	C137_SHIPMENT_GROUP_ID	CHAR(10) NULL,
-- 	C138_PICK_LIST_NO	CHAR(40) NULL,
-- 	C139_CREATEUSERID	VARCHAR2(40) NULL,
-- 	C140_NUM_OF_PALLETS	NUMBER(5) NULL,
-- 	C141_DELIVERY_PLAN_KEY	CHAR(24) NULL,
-- 	C142_SHIPNODE_KEY	CHAR(24) NULL,
-- 	C143_MERGE_NODE	CHAR(24) NULL,
-- 	C144_CARRIER_SERVICE_CODE	VARCHAR2(40) NULL,
-- 	C145_BUYER_MARK_FOR_NODE_ID	CHAR(24) NULL,
-- 	C146_TOTAL_ACTUAL_CHARGE	NUMBER(15,2) NULL,
-- 	C147_SHIPMENT_CLOSED_FLAG	CHAR(1) NULL,
-- 	C148_ESTIMATED_PRICE	NUMBER(15,2) NULL,
-- 	C149_ESP_CHECK_REQUIRED	CHAR(1) NULL,
-- 	C150_BILL_TO_CUSTOMER_ID	CHAR(40) NULL,
-- 	C151_PIPELINE_KEY	CHAR(24) NULL,
-- 	C152_PRO_NO	CHAR(40) NULL,
-- 	C153_MANIFEST_KEY	CHAR(24) NULL,
-- 	C154_SHIPMENT_CONFIRM_UPDATES_	CHAR(1) NULL,
-- 	C155_TOTAL_WEIGHT	NUMBER(14,4) NULL,
-- 	C156_PROFILE_ID	VARCHAR2(200) NULL,
-- 	C157_RELEASE_NO	NUMBER(5) NULL,
-- 	C158_PACK_AND_HOLD	CHAR(1) NULL,
-- 	C159_WO_BATCH_ID	VARCHAR2(40) NULL,
-- 	C160_EXTN_ACCOUNT_NAME	VARCHAR2(40) NULL
-- )
-- NOLOGGING

-- &


-- /*-----------------------------------------------*/
-- /* TASK No. 6 */
-- /* Load data */

-- /* SOURCE CODE */
-- select	
-- 	SHP.NEXT_ALERT_TS	   C1_NEXT_ALERT_TS,
-- 	SHP.BILL_TO_ADDRESS_KEY	   C2_BILL_TO_ADDRESS_KEY,
-- 	SHP.IS_PACK_PROCESS_COMPLETE	   C3_IS_PACK_PROCESS_COMPLETE,
-- 	SHP.SHIPMENT_SORT_LOCATION_ID	   C4_SHIPMENT_SORT_LOCATION_ID,
-- 	SHP.EXPORT_TAXPAYER_ID	   C5_EXPORT_TAXPAYER_ID,
-- 	SHP.TOTAL_ESTIMATED_CHARGE	   C6_TOTAL_ESTIMATED_CHARGE,
-- 	SHP.ROUTING_SOURCE	   C7_ROUTING_SOURCE,
-- 	SHP.CREATETS	   C8_CREATETS,
-- 	SHP.TRAILER_NO	   C9_TRAILER_NO,
-- 	SHP.SHIPMENT_NO	   C10_SHIPMENT_NO,
-- 	SHP.ACTUAL_DELIVERY_DATE	   C11_ACTUAL_DELIVERY_DATE,
-- 	SHP.EXPORT_LICENSE_EXP_DATE	   C12_EXPORT_LICENSE_EXP_DATE,
-- 	SHP.INVOICE_COMPLETE	   C13_INVOICE_COMPLETE,
-- 	SHP.CARRIER_PICKUP_TIME	   C14_CARRIER_PICKUP_TIME,
-- 	SHP.EXPORT_LICENSE_NO	   C15_EXPORT_LICENSE_NO,
-- 	SHP.DOWNLOAD_COUNT	   C16_DOWNLOAD_COUNT,
-- 	SHP.MODIFYTS	   C17_MODIFYTS,
-- 	SHP.REQUESTED_DELIVERY_DATE	   C18_REQUESTED_DELIVERY_DATE,
-- 	SHP.ALLOW_OVERAGE	   C19_ALLOW_OVERAGE,
-- 	SHP.MUST_SHIP_BEFORE_DATE	   C20_MUST_SHIP_BEFORE_DATE,
-- 	SHP.LOCKID	   C21_LOCKID,
-- 	SHP.SHIPMENT_PLANNED_FLAG	   C22_SHIPMENT_PLANNED_FLAG,
-- 	SHP.UNPLACED_QUANTITY	   C23_UNPLACED_QUANTITY,
-- 	SHP.REQUESTED_CARRIER_SERVICE_CODE	   C24_REQUESTED_CARRIER_SERVICE_,
-- 	SHP.REQUIRES_APPT_CONFIRMATION	   C25_REQUIRES_APPT_CONFIRMATION,
-- 	SHP.IT_NO	   C26_IT_NO,
-- 	SHP.BOL_NO	   C27_BOL_NO,
-- 	SHP.OVERRIDE_MANUAL_SHIPMENT_ENTRY	   C28_OVERRIDE_MANUAL_SHIPMENT_E,
-- 	SHP.DELIVERY_TS	   C29_DELIVERY_TS,
-- 	SHP.PARENT_SHIPMENT_KEY	   C30_PARENT_SHIPMENT_KEY,
-- 	SHP.COD_PAY_METHOD	   C31_COD_PAY_METHOD,
-- 	SHP.NUM_OF_CARTONS	   C32_NUM_OF_CARTONS,
-- 	SHP.WORK_ORDER_APPT_KEY	   C33_WORK_ORDER_APPT_KEY,
-- 	SHP.PLACED_QUANTITY	   C34_PLACED_QUANTITY,
-- 	SHP.LINES_ENTERED	   C35_LINES_ENTERED,
-- 	SHP.CARRIER_SORT_LOCATION_ID	   C36_CARRIER_SORT_LOCATION_ID,
-- 	SHP.REQUESTED_SHIPMENT_DATE	   C37_REQUESTED_SHIPMENT_DATE,
-- 	SHP.TOTAL_WEIGHT_UOM	   C38_TOTAL_WEIGHT_UOM,
-- 	SHP.ACTUAL_SHIPMENT_DATE	   C39_ACTUAL_SHIPMENT_DATE,
-- 	SHP.IS_PRODUCT_PLACING_COMPLETE	   C40_IS_PRODUCT_PLACING_COMPLET,
-- 	SHP.SHIPMENT_KEY	   C41_SHIPMENT_KEY,
-- 	SHP.TO_ADDRESS_KEY	   C42_TO_ADDRESS_KEY,
-- 	SHP.SHIP_DATE	   C43_SHIP_DATE,
-- 	SHP.CODE	   C44_CODE,
-- 	SHP.ACTUAL_FREIGHT_CHARGE	   C45_ACTUAL_FREIGHT_CHARGE,
-- 	SHP.PICKTICKET_NO	   C46_PICKTICKET_NO,
-- 	SHP.RETURN_FREIGHT_TERMS	   C47_RETURN_FREIGHT_TERMS,
-- 	SHP.EXPECTED_PICK_DATE	   C48_EXPECTED_PICK_DATE,
-- 	SHP.DEPARTMENT_CODE	   C49_DEPARTMENT_CODE,
-- 	SHP.ITN_NO	   C50_ITN_NO,
-- 	SHP.PACKLIST_TYPE	   C51_PACKLIST_TYPE,
-- 	SHP.ITEM_CLASSIFICATION	   C52_ITEM_CLASSIFICATION,
-- 	SHP.SHIPMENT_DELIVER_UPDATES_DONE	   C53_SHIPMENT_DELIVER_UPDATES_D,
-- 	SHP.SELLER_ORGANIZATION_CODE	   C54_SELLER_ORGANIZATION_CODE,
-- 	SHP.BBN_MIN_VOLUME	   C55_BBN_MIN_VOLUME,
-- 	SHP.APPOINTMENT_NO	   C56_APPOINTMENT_NO,
-- 	SHP.ALLOW_NEW_ITEM_RECEIPT	   C57_ALLOW_NEW_ITEM_RECEIPT,
-- 	SHP.ORDER_HEADER_KEY	   C58_ORDER_HEADER_KEY,
-- 	SHP.GIFT_FLAG	   C59_GIFT_FLAG,
-- 	SHP.FROM_ADDRESS_KEY	   C60_FROM_ADDRESS_KEY,
-- 	SHP.TRACKING_NO	   C61_TRACKING_NO,
-- 	SHP.ORDER_AVAILABLE_ON_SYSTEM	   C62_ORDER_AVAILABLE_ON_SYSTEM,
-- 	SHP.MANIFEST_NO	   C63_MANIFEST_NO,
-- 	SHP.DELIVERY_CODE	   C64_DELIVERY_CODE,
-- 	SHP.STATUS_DATE	   C65_STATUS_DATE,
-- 	SHP.MODIFYUSERID	   C66_MODIFYUSERID,
-- 	SHP.CUSTOMER_PO_NO	   C67_CUSTOMER_PO_NO,
-- 	SHP.RETURN_BILLING_ACCOUNT	   C68_RETURN_BILLING_ACCOUNT,
-- 	SHP.DO_NOT_CONSOLIDATE	   C69_DO_NOT_CONSOLIDATE,
-- 	SHP.SHIP_VIA	   C70_SHIP_VIA,
-- 	SHP.DESTINATION_ZONE	   C71_DESTINATION_ZONE,
-- 	SHP.EXTN_SORT_TYPE	   C72_EXTN_SORT_TYPE,
-- 	SHP.EXTN_ROOM_BOARD_ITEM_ID	   C73_EXTN_ROOM_BOARD_ITEM_ID,
-- 	SHP.MODIFYPROGID	   C74_MODIFYPROGID,
-- 	SHP.PROFILEID_PROVIDED_BY_STERLING	   C75_PROFILEID_PROVIDED_BY_STER,
-- 	SHP.ORDER_TYPE	   C76_ORDER_TYPE,
-- 	SHP.COMMERCIAL_VALUE	   C77_COMMERCIAL_VALUE,
-- 	SHP.SHIP_MODE	   C78_SHIP_MODE,
-- 	SHP.AIRWAY_BILL_NO	   C79_AIRWAY_BILL_NO,
-- 	SHP.MARK_FOR_KEY	   C80_MARK_FOR_KEY,
-- 	SHP.HAS_OTHER_SHIPMENTS	   C81_HAS_OTHER_SHIPMENTS,
-- 	SHP.ORIGIN_ZONE	   C82_ORIGIN_ZONE,
-- 	SHP.RETURN_BY_DATE	   C83_RETURN_BY_DATE,
-- 	SHP.ORDER_NO	   C84_ORDER_NO,
-- 	SHP.SHIPMENT_CONSOL_GROUP_ID	   C85_SHIPMENT_CONSOL_GROUP_ID,
-- 	SHP.IT_DATE	   C86_IT_DATE,
-- 	SHP.CONTAINERIZED_QUANTITY	   C87_CONTAINERIZED_QUANTITY,
-- 	SHP.STATUS	   C88_STATUS,
-- 	SHP.SHIPMENT_CONTAINERIZED_FLAG	   C89_SHIPMENT_CONTAINERIZED_FLA,
-- 	SHP.RETURN_CARRIER_SERVICE	   C90_RETURN_CARRIER_SERVICE,
-- 	SHP.HAZARDOUS_MATERIAL_FLAG	   C91_HAZARDOUS_MATERIAL_FLAG,
-- 	SHP.RECEIVING_NODE	   C92_RECEIVING_NODE,
-- 	SHP.ORIGINAL_SHIPMENT_KEY	   C93_ORIGINAL_SHIPMENT_KEY,
-- 	SHP.DO_NOT_VERIFY_CASE_CONTENT	   C94_DO_NOT_VERIFY_CASE_CONTENT,
-- 	SHP.BREAK_BULK_NODE	   C95_BREAK_BULK_NODE,
-- 	SHP.EXPECTED_SHIPMENT_DATE	   C96_EXPECTED_SHIPMENT_DATE,
-- 	SHP.TO_APPOINTMENT	   C97_TO_APPOINTMENT,
-- 	SHP.SHIP_TO_CUSTOMER_ID	   C98_SHIP_TO_CUSTOMER_ID,
-- 	SHP.SCAC_INTEGRATION_REQUIRED	   C99_SCAC_INTEGRATION_REQUIRED,
-- 	SHP.IS_SINGLE_ORDER	   C100_IS_SINGLE_ORDER,
-- 	SHP.ROUTING_ERROR_CODE	   C101_ROUTING_ERROR_CODE,
-- 	SHP.CREATEPROGID	   C102_CREATEPROGID,
-- 	SHP.SEAL_NO	   C103_SEAL_NO,
-- 	SHP.DELIVERY_METHOD	   C104_DELIVERY_METHOD,
-- 	SHP.TOTAL_QUANTITY	   C105_TOTAL_QUANTITY,
-- 	SHP.EMAIL_RETURN_LABEL	   C106_EMAIL_RETURN_LABEL,
-- 	SHP.BBN_MIN_WEIGHT	   C107_BBN_MIN_WEIGHT,
-- 	SHP.ROUTING_GUIDE_MAINTAINED	   C108_ROUTING_GUIDE_MAINTAINED,
-- 	SHP.TOTAL_VOLUME_UOM	   C109_TOTAL_VOLUME_UOM,
-- 	SHP.MANUALLY_ENTERED	   C110_MANUALLY_ENTERED,
-- 	SHP.DO_NOT_VERIFY_PALLET_CONTENT	   C111_DO_NOT_VERIFY_PALLET_CONT,
-- 	SHP.IS_APPOINTMENT_REQD	   C112_IS_APPOINTMENT_REQD,
-- 	SHP.CARRIER_TYPE	   C113_CARRIER_TYPE,
-- 	SHP.CURRENCY	   C114_CURRENCY,
-- 	SHP.EXTN_ROOM_BOARD_URL	   C115_EXTN_ROOM_BOARD_URL,
-- 	SHP.BUYER_RECEIVING_NODE_ID	   C116_BUYER_RECEIVING_NODE_ID,
-- 	SHP.FREIGHT_TERMS	   C117_FREIGHT_TERMS,
-- 	SHP.WORK_ORDER_KEY	   C118_WORK_ORDER_KEY,
-- 	SHP.HAS_NODE_EXCEPTIONS	   C119_HAS_NODE_EXCEPTIONS,
-- 	SHP.FEDX_OPEN_SHIP_INDEX	   C120_FEDX_OPEN_SHIP_INDEX,
-- 	SHP.ORDER_RELEASE_KEY	   C121_ORDER_RELEASE_KEY,
-- 	SHP.TOTAL_VOLUME	   C122_TOTAL_VOLUME,
-- 	SHP.POD_NO	   C123_POD_NO,
-- 	SHP.FROM_APPOINTMENT	   C124_FROM_APPOINTMENT,
-- 	SHP.BUYER_ORGANIZATION_CODE	   C125_BUYER_ORGANIZATION_CODE,
-- 	SHP.RETURN_AUTHORIZATION_NUMBER	   C126_RETURN_AUTHORIZATION_NUMB,
-- 	SHP.SCAC	   C127_SCAC,
-- 	SHP.IS_REVISED	   C128_IS_REVISED,
-- 	SHP.HOLD_FLAG	   C129_HOLD_FLAG,
-- 	SHP.ROUTING_CONTACT_INFO	   C130_ROUTING_CONTACT_INFO,
-- 	SHP.EXPECTED_DELIVERY_DATE	   C131_EXPECTED_DELIVERY_DATE,
-- 	SHP.PRIORITY_CODE	   C132_PRIORITY_CODE,
-- 	SHP.DOCUMENT_TYPE	   C133_DOCUMENT_TYPE,
-- 	SHP.SHIPMENT_TYPE	   C134_SHIPMENT_TYPE,
-- 	SHP.ENTERPRISE_CODE	   C135_ENTERPRISE_CODE,
-- 	SHP.CUSTCARRIER_ACCOUNT_NO	   C136_CUSTCARRIER_ACCOUNT_NO,
-- 	SHP.SHIPMENT_GROUP_ID	   C137_SHIPMENT_GROUP_ID,
-- 	SHP.PICK_LIST_NO	   C138_PICK_LIST_NO,
-- 	SHP.CREATEUSERID	   C139_CREATEUSERID,
-- 	SHP.NUM_OF_PALLETS	   C140_NUM_OF_PALLETS,
-- 	SHP.DELIVERY_PLAN_KEY	   C141_DELIVERY_PLAN_KEY,
-- 	SHP.SHIPNODE_KEY	   C142_SHIPNODE_KEY,
-- 	SHP.MERGE_NODE	   C143_MERGE_NODE,
-- 	SHP.CARRIER_SERVICE_CODE	   C144_CARRIER_SERVICE_CODE,
-- 	SHP.BUYER_MARK_FOR_NODE_ID	   C145_BUYER_MARK_FOR_NODE_ID,
-- 	SHP.TOTAL_ACTUAL_CHARGE	   C146_TOTAL_ACTUAL_CHARGE,
-- 	SHP.SHIPMENT_CLOSED_FLAG	   C147_SHIPMENT_CLOSED_FLAG,
-- 	SHP.ESTIMATED_PRICE	   C148_ESTIMATED_PRICE,
-- 	SHP.ESP_CHECK_REQUIRED	   C149_ESP_CHECK_REQUIRED,
-- 	SHP.BILL_TO_CUSTOMER_ID	   C150_BILL_TO_CUSTOMER_ID,
-- 	SHP.PIPELINE_KEY	   C151_PIPELINE_KEY,
-- 	SHP.PRO_NO	   C152_PRO_NO,
-- 	SHP.MANIFEST_KEY	   C153_MANIFEST_KEY,
-- 	SHP.SHIPMENT_CONFIRM_UPDATES_DONE	   C154_SHIPMENT_CONFIRM_UPDATES_,
-- 	SHP.TOTAL_WEIGHT	   C155_TOTAL_WEIGHT,
-- 	SHP.PROFILE_ID	   C156_PROFILE_ID,
-- 	SHP.RELEASE_NO	   C157_RELEASE_NO,
-- 	SHP.PACK_AND_HOLD	   C158_PACK_AND_HOLD,
-- 	TRIM(SHP.EXTN_WO_BATCH_ID)	   C159_WO_BATCH_ID,
-- 	SHP.EXTN_ACCOUNT_NAME	   C160_EXTN_ACCOUNT_NAME
-- from	OMS3_OWN.YFS_SHIPMENT   SHP
-- where	(1=1)
-- And (SHP.MODIFYTS >= TO_DATE(SUBSTR(:v_cdc_load_date, 1, 19), 'YYYY-MM-DD HH24:MI:SS')  -:v_cdc_oms_overlap
-- )





-- &

-- /* TARGET CODE */
-- insert into RAX_APP_USER.C$_0STG_SHIPMENT
-- (
-- 	C1_NEXT_ALERT_TS,
-- 	C2_BILL_TO_ADDRESS_KEY,
-- 	C3_IS_PACK_PROCESS_COMPLETE,
-- 	C4_SHIPMENT_SORT_LOCATION_ID,
-- 	C5_EXPORT_TAXPAYER_ID,
-- 	C6_TOTAL_ESTIMATED_CHARGE,
-- 	C7_ROUTING_SOURCE,
-- 	C8_CREATETS,
-- 	C9_TRAILER_NO,
-- 	C10_SHIPMENT_NO,
-- 	C11_ACTUAL_DELIVERY_DATE,
-- 	C12_EXPORT_LICENSE_EXP_DATE,
-- 	C13_INVOICE_COMPLETE,
-- 	C14_CARRIER_PICKUP_TIME,
-- 	C15_EXPORT_LICENSE_NO,
-- 	C16_DOWNLOAD_COUNT,
-- 	C17_MODIFYTS,
-- 	C18_REQUESTED_DELIVERY_DATE,
-- 	C19_ALLOW_OVERAGE,
-- 	C20_MUST_SHIP_BEFORE_DATE,
-- 	C21_LOCKID,
-- 	C22_SHIPMENT_PLANNED_FLAG,
-- 	C23_UNPLACED_QUANTITY,
-- 	C24_REQUESTED_CARRIER_SERVICE_,
-- 	C25_REQUIRES_APPT_CONFIRMATION,
-- 	C26_IT_NO,
-- 	C27_BOL_NO,
-- 	C28_OVERRIDE_MANUAL_SHIPMENT_E,
-- 	C29_DELIVERY_TS,
-- 	C30_PARENT_SHIPMENT_KEY,
-- 	C31_COD_PAY_METHOD,
-- 	C32_NUM_OF_CARTONS,
-- 	C33_WORK_ORDER_APPT_KEY,
-- 	C34_PLACED_QUANTITY,
-- 	C35_LINES_ENTERED,
-- 	C36_CARRIER_SORT_LOCATION_ID,
-- 	C37_REQUESTED_SHIPMENT_DATE,
-- 	C38_TOTAL_WEIGHT_UOM,
-- 	C39_ACTUAL_SHIPMENT_DATE,
-- 	C40_IS_PRODUCT_PLACING_COMPLET,
-- 	C41_SHIPMENT_KEY,
-- 	C42_TO_ADDRESS_KEY,
-- 	C43_SHIP_DATE,
-- 	C44_CODE,
-- 	C45_ACTUAL_FREIGHT_CHARGE,
-- 	C46_PICKTICKET_NO,
-- 	C47_RETURN_FREIGHT_TERMS,
-- 	C48_EXPECTED_PICK_DATE,
-- 	C49_DEPARTMENT_CODE,
-- 	C50_ITN_NO,
-- 	C51_PACKLIST_TYPE,
-- 	C52_ITEM_CLASSIFICATION,
-- 	C53_SHIPMENT_DELIVER_UPDATES_D,
-- 	C54_SELLER_ORGANIZATION_CODE,
-- 	C55_BBN_MIN_VOLUME,
-- 	C56_APPOINTMENT_NO,
-- 	C57_ALLOW_NEW_ITEM_RECEIPT,
-- 	C58_ORDER_HEADER_KEY,
-- 	C59_GIFT_FLAG,
-- 	C60_FROM_ADDRESS_KEY,
-- 	C61_TRACKING_NO,
-- 	C62_ORDER_AVAILABLE_ON_SYSTEM,
-- 	C63_MANIFEST_NO,
-- 	C64_DELIVERY_CODE,
-- 	C65_STATUS_DATE,
-- 	C66_MODIFYUSERID,
-- 	C67_CUSTOMER_PO_NO,
-- 	C68_RETURN_BILLING_ACCOUNT,
-- 	C69_DO_NOT_CONSOLIDATE,
-- 	C70_SHIP_VIA,
-- 	C71_DESTINATION_ZONE,
-- 	C72_EXTN_SORT_TYPE,
-- 	C73_EXTN_ROOM_BOARD_ITEM_ID,
-- 	C74_MODIFYPROGID,
-- 	C75_PROFILEID_PROVIDED_BY_STER,
-- 	C76_ORDER_TYPE,
-- 	C77_COMMERCIAL_VALUE,
-- 	C78_SHIP_MODE,
-- 	C79_AIRWAY_BILL_NO,
-- 	C80_MARK_FOR_KEY,
-- 	C81_HAS_OTHER_SHIPMENTS,
-- 	C82_ORIGIN_ZONE,
-- 	C83_RETURN_BY_DATE,
-- 	C84_ORDER_NO,
-- 	C85_SHIPMENT_CONSOL_GROUP_ID,
-- 	C86_IT_DATE,
-- 	C87_CONTAINERIZED_QUANTITY,
-- 	C88_STATUS,
-- 	C89_SHIPMENT_CONTAINERIZED_FLA,
-- 	C90_RETURN_CARRIER_SERVICE,
-- 	C91_HAZARDOUS_MATERIAL_FLAG,
-- 	C92_RECEIVING_NODE,
-- 	C93_ORIGINAL_SHIPMENT_KEY,
-- 	C94_DO_NOT_VERIFY_CASE_CONTENT,
-- 	C95_BREAK_BULK_NODE,
-- 	C96_EXPECTED_SHIPMENT_DATE,
-- 	C97_TO_APPOINTMENT,
-- 	C98_SHIP_TO_CUSTOMER_ID,
-- 	C99_SCAC_INTEGRATION_REQUIRED,
-- 	C100_IS_SINGLE_ORDER,
-- 	C101_ROUTING_ERROR_CODE,
-- 	C102_CREATEPROGID,
-- 	C103_SEAL_NO,
-- 	C104_DELIVERY_METHOD,
-- 	C105_TOTAL_QUANTITY,
-- 	C106_EMAIL_RETURN_LABEL,
-- 	C107_BBN_MIN_WEIGHT,
-- 	C108_ROUTING_GUIDE_MAINTAINED,
-- 	C109_TOTAL_VOLUME_UOM,
-- 	C110_MANUALLY_ENTERED,
-- 	C111_DO_NOT_VERIFY_PALLET_CONT,
-- 	C112_IS_APPOINTMENT_REQD,
-- 	C113_CARRIER_TYPE,
-- 	C114_CURRENCY,
-- 	C115_EXTN_ROOM_BOARD_URL,
-- 	C116_BUYER_RECEIVING_NODE_ID,
-- 	C117_FREIGHT_TERMS,
-- 	C118_WORK_ORDER_KEY,
-- 	C119_HAS_NODE_EXCEPTIONS,
-- 	C120_FEDX_OPEN_SHIP_INDEX,
-- 	C121_ORDER_RELEASE_KEY,
-- 	C122_TOTAL_VOLUME,
-- 	C123_POD_NO,
-- 	C124_FROM_APPOINTMENT,
-- 	C125_BUYER_ORGANIZATION_CODE,
-- 	C126_RETURN_AUTHORIZATION_NUMB,
-- 	C127_SCAC,
-- 	C128_IS_REVISED,
-- 	C129_HOLD_FLAG,
-- 	C130_ROUTING_CONTACT_INFO,
-- 	C131_EXPECTED_DELIVERY_DATE,
-- 	C132_PRIORITY_CODE,
-- 	C133_DOCUMENT_TYPE,
-- 	C134_SHIPMENT_TYPE,
-- 	C135_ENTERPRISE_CODE,
-- 	C136_CUSTCARRIER_ACCOUNT_NO,
-- 	C137_SHIPMENT_GROUP_ID,
-- 	C138_PICK_LIST_NO,
-- 	C139_CREATEUSERID,
-- 	C140_NUM_OF_PALLETS,
-- 	C141_DELIVERY_PLAN_KEY,
-- 	C142_SHIPNODE_KEY,
-- 	C143_MERGE_NODE,
-- 	C144_CARRIER_SERVICE_CODE,
-- 	C145_BUYER_MARK_FOR_NODE_ID,
-- 	C146_TOTAL_ACTUAL_CHARGE,
-- 	C147_SHIPMENT_CLOSED_FLAG,
-- 	C148_ESTIMATED_PRICE,
-- 	C149_ESP_CHECK_REQUIRED,
-- 	C150_BILL_TO_CUSTOMER_ID,
-- 	C151_PIPELINE_KEY,
-- 	C152_PRO_NO,
-- 	C153_MANIFEST_KEY,
-- 	C154_SHIPMENT_CONFIRM_UPDATES_,
-- 	C155_TOTAL_WEIGHT,
-- 	C156_PROFILE_ID,
-- 	C157_RELEASE_NO,
-- 	C158_PACK_AND_HOLD,
-- 	C159_WO_BATCH_ID,
-- 	C160_EXTN_ACCOUNT_NAME
-- )
-- values
-- (
-- 	:C1_NEXT_ALERT_TS,
-- 	:C2_BILL_TO_ADDRESS_KEY,
-- 	:C3_IS_PACK_PROCESS_COMPLETE,
-- 	:C4_SHIPMENT_SORT_LOCATION_ID,
-- 	:C5_EXPORT_TAXPAYER_ID,
-- 	:C6_TOTAL_ESTIMATED_CHARGE,
-- 	:C7_ROUTING_SOURCE,
-- 	:C8_CREATETS,
-- 	:C9_TRAILER_NO,
-- 	:C10_SHIPMENT_NO,
-- 	:C11_ACTUAL_DELIVERY_DATE,
-- 	:C12_EXPORT_LICENSE_EXP_DATE,
-- 	:C13_INVOICE_COMPLETE,
-- 	:C14_CARRIER_PICKUP_TIME,
-- 	:C15_EXPORT_LICENSE_NO,
-- 	:C16_DOWNLOAD_COUNT,
-- 	:C17_MODIFYTS,
-- 	:C18_REQUESTED_DELIVERY_DATE,
-- 	:C19_ALLOW_OVERAGE,
-- 	:C20_MUST_SHIP_BEFORE_DATE,
-- 	:C21_LOCKID,
-- 	:C22_SHIPMENT_PLANNED_FLAG,
-- 	:C23_UNPLACED_QUANTITY,
-- 	:C24_REQUESTED_CARRIER_SERVICE_,
-- 	:C25_REQUIRES_APPT_CONFIRMATION,
-- 	:C26_IT_NO,
-- 	:C27_BOL_NO,
-- 	:C28_OVERRIDE_MANUAL_SHIPMENT_E,
-- 	:C29_DELIVERY_TS,
-- 	:C30_PARENT_SHIPMENT_KEY,
-- 	:C31_COD_PAY_METHOD,
-- 	:C32_NUM_OF_CARTONS,
-- 	:C33_WORK_ORDER_APPT_KEY,
-- 	:C34_PLACED_QUANTITY,
-- 	:C35_LINES_ENTERED,
-- 	:C36_CARRIER_SORT_LOCATION_ID,
-- 	:C37_REQUESTED_SHIPMENT_DATE,
-- 	:C38_TOTAL_WEIGHT_UOM,
-- 	:C39_ACTUAL_SHIPMENT_DATE,
-- 	:C40_IS_PRODUCT_PLACING_COMPLET,
-- 	:C41_SHIPMENT_KEY,
-- 	:C42_TO_ADDRESS_KEY,
-- 	:C43_SHIP_DATE,
-- 	:C44_CODE,
-- 	:C45_ACTUAL_FREIGHT_CHARGE,
-- 	:C46_PICKTICKET_NO,
-- 	:C47_RETURN_FREIGHT_TERMS,
-- 	:C48_EXPECTED_PICK_DATE,
-- 	:C49_DEPARTMENT_CODE,
-- 	:C50_ITN_NO,
-- 	:C51_PACKLIST_TYPE,
-- 	:C52_ITEM_CLASSIFICATION,
-- 	:C53_SHIPMENT_DELIVER_UPDATES_D,
-- 	:C54_SELLER_ORGANIZATION_CODE,
-- 	:C55_BBN_MIN_VOLUME,
-- 	:C56_APPOINTMENT_NO,
-- 	:C57_ALLOW_NEW_ITEM_RECEIPT,
-- 	:C58_ORDER_HEADER_KEY,
-- 	:C59_GIFT_FLAG,
-- 	:C60_FROM_ADDRESS_KEY,
-- 	:C61_TRACKING_NO,
-- 	:C62_ORDER_AVAILABLE_ON_SYSTEM,
-- 	:C63_MANIFEST_NO,
-- 	:C64_DELIVERY_CODE,
-- 	:C65_STATUS_DATE,
-- 	:C66_MODIFYUSERID,
-- 	:C67_CUSTOMER_PO_NO,
-- 	:C68_RETURN_BILLING_ACCOUNT,
-- 	:C69_DO_NOT_CONSOLIDATE,
-- 	:C70_SHIP_VIA,
-- 	:C71_DESTINATION_ZONE,
-- 	:C72_EXTN_SORT_TYPE,
-- 	:C73_EXTN_ROOM_BOARD_ITEM_ID,
-- 	:C74_MODIFYPROGID,
-- 	:C75_PROFILEID_PROVIDED_BY_STER,
-- 	:C76_ORDER_TYPE,
-- 	:C77_COMMERCIAL_VALUE,
-- 	:C78_SHIP_MODE,
-- 	:C79_AIRWAY_BILL_NO,
-- 	:C80_MARK_FOR_KEY,
-- 	:C81_HAS_OTHER_SHIPMENTS,
-- 	:C82_ORIGIN_ZONE,
-- 	:C83_RETURN_BY_DATE,
-- 	:C84_ORDER_NO,
-- 	:C85_SHIPMENT_CONSOL_GROUP_ID,
-- 	:C86_IT_DATE,
-- 	:C87_CONTAINERIZED_QUANTITY,
-- 	:C88_STATUS,
-- 	:C89_SHIPMENT_CONTAINERIZED_FLA,
-- 	:C90_RETURN_CARRIER_SERVICE,
-- 	:C91_HAZARDOUS_MATERIAL_FLAG,
-- 	:C92_RECEIVING_NODE,
-- 	:C93_ORIGINAL_SHIPMENT_KEY,
-- 	:C94_DO_NOT_VERIFY_CASE_CONTENT,
-- 	:C95_BREAK_BULK_NODE,
-- 	:C96_EXPECTED_SHIPMENT_DATE,
-- 	:C97_TO_APPOINTMENT,
-- 	:C98_SHIP_TO_CUSTOMER_ID,
-- 	:C99_SCAC_INTEGRATION_REQUIRED,
-- 	:C100_IS_SINGLE_ORDER,
-- 	:C101_ROUTING_ERROR_CODE,
-- 	:C102_CREATEPROGID,
-- 	:C103_SEAL_NO,
-- 	:C104_DELIVERY_METHOD,
-- 	:C105_TOTAL_QUANTITY,
-- 	:C106_EMAIL_RETURN_LABEL,
-- 	:C107_BBN_MIN_WEIGHT,
-- 	:C108_ROUTING_GUIDE_MAINTAINED,
-- 	:C109_TOTAL_VOLUME_UOM,
-- 	:C110_MANUALLY_ENTERED,
-- 	:C111_DO_NOT_VERIFY_PALLET_CONT,
-- 	:C112_IS_APPOINTMENT_REQD,
-- 	:C113_CARRIER_TYPE,
-- 	:C114_CURRENCY,
-- 	:C115_EXTN_ROOM_BOARD_URL,
-- 	:C116_BUYER_RECEIVING_NODE_ID,
-- 	:C117_FREIGHT_TERMS,
-- 	:C118_WORK_ORDER_KEY,
-- 	:C119_HAS_NODE_EXCEPTIONS,
-- 	:C120_FEDX_OPEN_SHIP_INDEX,
-- 	:C121_ORDER_RELEASE_KEY,
-- 	:C122_TOTAL_VOLUME,
-- 	:C123_POD_NO,
-- 	:C124_FROM_APPOINTMENT,
-- 	:C125_BUYER_ORGANIZATION_CODE,
-- 	:C126_RETURN_AUTHORIZATION_NUMB,
-- 	:C127_SCAC,
-- 	:C128_IS_REVISED,
-- 	:C129_HOLD_FLAG,
-- 	:C130_ROUTING_CONTACT_INFO,
-- 	:C131_EXPECTED_DELIVERY_DATE,
-- 	:C132_PRIORITY_CODE,
-- 	:C133_DOCUMENT_TYPE,
-- 	:C134_SHIPMENT_TYPE,
-- 	:C135_ENTERPRISE_CODE,
-- 	:C136_CUSTCARRIER_ACCOUNT_NO,
-- 	:C137_SHIPMENT_GROUP_ID,
-- 	:C138_PICK_LIST_NO,
-- 	:C139_CREATEUSERID,
-- 	:C140_NUM_OF_PALLETS,
-- 	:C141_DELIVERY_PLAN_KEY,
-- 	:C142_SHIPNODE_KEY,
-- 	:C143_MERGE_NODE,
-- 	:C144_CARRIER_SERVICE_CODE,
-- 	:C145_BUYER_MARK_FOR_NODE_ID,
-- 	:C146_TOTAL_ACTUAL_CHARGE,
-- 	:C147_SHIPMENT_CLOSED_FLAG,
-- 	:C148_ESTIMATED_PRICE,
-- 	:C149_ESP_CHECK_REQUIRED,
-- 	:C150_BILL_TO_CUSTOMER_ID,
-- 	:C151_PIPELINE_KEY,
-- 	:C152_PRO_NO,
-- 	:C153_MANIFEST_KEY,
-- 	:C154_SHIPMENT_CONFIRM_UPDATES_,
-- 	:C155_TOTAL_WEIGHT,
-- 	:C156_PROFILE_ID,
-- 	:C157_RELEASE_NO,
-- 	:C158_PACK_AND_HOLD,
-- 	:C159_WO_BATCH_ID,
-- 	:C160_EXTN_ACCOUNT_NAME
-- )

-- &


/*-----------------------------------------------*/
/* TASK No. 7 */
/* Analyze work table */



BEGIN
DBMS_STATS.GATHER_TABLE_STATS (
    ownname =>	'RAX_APP_USER',
    tabname =>	'C$_0STG_SHIPMENT',
    estimate_percent =>	DBMS_STATS.AUTO_SAMPLE_SIZE
);
END;




&


/*-----------------------------------------------*/
/* TASK No. 9 */
/* Create target table  */
BEGIN  
   EXECUTE IMMEDIATE 'create table RAX_APP_USER.STG_SHIPMENT
						(
							NEXT_ALERT_TS	DATE NULL,
							BILL_TO_ADDRESS_KEY	CHAR(24) NULL,
							IS_PACK_PROCESS_COMPLETE	CHAR(1) NULL,
							SHIPMENT_SORT_LOCATION_ID	VARCHAR2(40) NULL,
							EXPORT_TAXPAYER_ID	VARCHAR2(40) NULL,
							TOTAL_ESTIMATED_CHARGE	NUMBER(15,2) NULL,
							ROUTING_SOURCE	CHAR(2) NULL,
							CREATETS	DATE NULL,
							TRAILER_NO	CHAR(40) NULL,
							SHIPMENT_NO	CHAR(40) NULL,
							ACTUAL_DELIVERY_DATE	DATE NULL,
							EXPORT_LICENSE_EXP_DATE	DATE NULL,
							INVOICE_COMPLETE	CHAR(1) NULL,
							CARRIER_PICKUP_TIME	DATE NULL,
							EXPORT_LICENSE_NO	VARCHAR2(40) NULL,
							DOWNLOAD_COUNT	NUMBER(5) NULL,
							MODIFYTS	DATE NULL,
							REQUESTED_DELIVERY_DATE	DATE NULL,
							ALLOW_OVERAGE	CHAR(1) NULL,
							MUST_SHIP_BEFORE_DATE	DATE NULL,
							LOCKID	NUMBER(5) NULL,
							SHIPMENT_PLANNED_FLAG	CHAR(1) NULL,
							UNPLACED_QUANTITY	NUMBER(14,4) NULL,
							REQUESTED_CARRIER_SERVICE_CODE	VARCHAR2(40) NULL,
							REQUIRES_APPT_CONFIRMATION	CHAR(1) NULL,
							IT_NO	CHAR(30) NULL,
							BOL_NO	CHAR(40) NULL,
							OVERRIDE_MANUAL_SHIPMENT_ENTRY	CHAR(1) NULL,
							DELIVERY_TS	DATE NULL,
							PARENT_SHIPMENT_KEY	CHAR(24) NULL,
							COD_PAY_METHOD	VARCHAR2(40) NULL,
							NUM_OF_CARTONS	NUMBER(5) NULL,
							WORK_ORDER_APPT_KEY	CHAR(24) NULL,
							PLACED_QUANTITY	NUMBER(14,4) NULL,
							LINES_ENTERED	CHAR(1) NULL,
							CARRIER_SORT_LOCATION_ID	VARCHAR2(40) NULL,
							REQUESTED_SHIPMENT_DATE	DATE NULL,
							TOTAL_WEIGHT_UOM	VARCHAR2(40) NULL,
							ACTUAL_SHIPMENT_DATE	DATE NULL,
							IS_PRODUCT_PLACING_COMPLETE	CHAR(1) NULL,
							SHIPMENT_KEY	CHAR(24) NULL,
							TO_ADDRESS_KEY	CHAR(24) NULL,
							SHIP_DATE	DATE NULL,
							CODE	VARCHAR2(40) NULL,
							ACTUAL_FREIGHT_CHARGE	NUMBER(15,2) NULL,
							PICKTICKET_NO	CHAR(24) NULL,
							RETURN_FREIGHT_TERMS	CHAR(3) NULL,
							EXPECTED_PICK_DATE	DATE NULL,
							DEPARTMENT_CODE	VARCHAR2(20) NULL,
							ITN_NO	VARCHAR2(40) NULL,
							PACKLIST_TYPE	VARCHAR2(20) NULL,
							ITEM_CLASSIFICATION	VARCHAR2(40) NULL,
							SHIPMENT_DELIVER_UPDATES_DONE	CHAR(1) NULL,
							SELLER_ORGANIZATION_CODE	CHAR(24) NULL,
							BBN_MIN_VOLUME	NUMBER(14,4) NULL,
							APPOINTMENT_NO	CHAR(40) NULL,
							ALLOW_NEW_ITEM_RECEIPT	VARCHAR2(20) NULL,
							ORDER_HEADER_KEY	CHAR(24) NULL,
							GIFT_FLAG	CHAR(1) NULL,
							FROM_ADDRESS_KEY	CHAR(24) NULL,
							TRACKING_NO	CHAR(40) NULL,
							ORDER_AVAILABLE_ON_SYSTEM	CHAR(1) NULL,
							MANIFEST_NO	CHAR(40) NULL,
							DELIVERY_CODE	VARCHAR2(40) NULL,
							STATUS_DATE	DATE NULL,
							MODIFYUSERID	VARCHAR2(40) NULL,
							CUSTOMER_PO_NO	VARCHAR2(100) NULL,
							RETURN_BILLING_ACCOUNT	VARCHAR2(40) NULL,
							DO_NOT_CONSOLIDATE	CHAR(1) NULL,
							SHIP_VIA	VARCHAR2(10) NULL,
							DESTINATION_ZONE	VARCHAR2(40) NULL,
							EXTN_SORT_TYPE	VARCHAR2(10) NULL,
							EXTN_ROOM_BOARD_ITEM_ID	VARCHAR2(5) NULL,
							MODIFYPROGID	VARCHAR2(40) NULL,
							PROFILEID_PROVIDED_BY_STERLING	CHAR(1) NULL,
							ORDER_TYPE	VARCHAR2(20) NULL,
							COMMERCIAL_VALUE	NUMBER(15,2) NULL,
							SHIP_MODE	VARCHAR2(40) NULL,
							AIRWAY_BILL_NO	CHAR(40) NULL,
							MARK_FOR_KEY	CHAR(24) NULL,
							HAS_OTHER_SHIPMENTS	CHAR(1) NULL,
							ORIGIN_ZONE	VARCHAR2(40) NULL,
							RETURN_BY_DATE	DATE NULL,
							ORDER_NO	CHAR(40) NULL,
							SHIPMENT_CONSOL_GROUP_ID	CHAR(24) NULL,
							IT_DATE	DATE NULL,
							CONTAINERIZED_QUANTITY	NUMBER(14,4) NULL,
							STATUS	CHAR(15) NULL,
							SHIPMENT_CONTAINERIZED_FLAG	CHAR(2) NULL,
							RETURN_CARRIER_SERVICE	VARCHAR2(40) NULL,
							HAZARDOUS_MATERIAL_FLAG	CHAR(1) NULL,
							RECEIVING_NODE	CHAR(24) NULL,
							ORIGINAL_SHIPMENT_KEY	CHAR(24) NULL,
							DO_NOT_VERIFY_CASE_CONTENT	CHAR(1) NULL,
							BREAK_BULK_NODE	CHAR(24) NULL,
							EXPECTED_SHIPMENT_DATE	DATE NULL,
							TO_APPOINTMENT	DATE NULL,
							SHIP_TO_CUSTOMER_ID	VARCHAR2(40) NULL,
							SCAC_INTEGRATION_REQUIRED	CHAR(1) NULL,
							IS_SINGLE_ORDER	CHAR(1) NULL,
							ROUTING_ERROR_CODE	VARCHAR2(100) NULL,
							CREATEPROGID	VARCHAR2(40) NULL,
							SEAL_NO	CHAR(40) NULL,
							DELIVERY_METHOD	VARCHAR2(40) NULL,
							TOTAL_QUANTITY	NUMBER(14,4) NULL,
							EMAIL_RETURN_LABEL	CHAR(1) NULL,
							BBN_MIN_WEIGHT	NUMBER(14,4) NULL,
							ROUTING_GUIDE_MAINTAINED	CHAR(2) NULL,
							TOTAL_VOLUME_UOM	VARCHAR2(40) NULL,
							MANUALLY_ENTERED	CHAR(1) NULL,
							DO_NOT_VERIFY_PALLET_CONTENT	CHAR(1) NULL,
							IS_APPOINTMENT_REQD	CHAR(1) NULL,
							CARRIER_TYPE	VARCHAR2(40) NULL,
							CURRENCY	VARCHAR2(20) NULL,
							EXTN_ROOM_BOARD_URL	VARCHAR2(100) NULL,
							BUYER_RECEIVING_NODE_ID	CHAR(24) NULL,
							FREIGHT_TERMS	VARCHAR2(40) NULL,
							WORK_ORDER_KEY	CHAR(24) NULL,
							HAS_NODE_EXCEPTIONS	CHAR(1) NULL,
							FEDX_OPEN_SHIP_INDEX	VARCHAR2(10) NULL,
							ORDER_RELEASE_KEY	CHAR(24) NULL,
							TOTAL_VOLUME	NUMBER(14,4) NULL,
							POD_NO	CHAR(40) NULL,
							FROM_APPOINTMENT	DATE NULL,
							BUYER_ORGANIZATION_CODE	CHAR(24) NULL,
							RETURN_AUTHORIZATION_NUMBER	VARCHAR2(40) NULL,
							SCAC	CHAR(24) NULL,
							IS_REVISED	CHAR(1) NULL,
							HOLD_FLAG	CHAR(1) NULL,
							ROUTING_CONTACT_INFO	VARCHAR2(250) NULL,
							EXPECTED_DELIVERY_DATE	DATE NULL,
							PRIORITY_CODE	VARCHAR2(256) NULL,
							DOCUMENT_TYPE	VARCHAR2(40) NULL,
							SHIPMENT_TYPE	VARCHAR2(40) NULL,
							ENTERPRISE_CODE	CHAR(24) NULL,
							CUSTCARRIER_ACCOUNT_NO	VARCHAR2(40) NULL,
							SHIPMENT_GROUP_ID	CHAR(10) NULL,
							PICK_LIST_NO	CHAR(40) NULL,
							CREATEUSERID	VARCHAR2(40) NULL,
							NUM_OF_PALLETS	NUMBER(5) NULL,
							DELIVERY_PLAN_KEY	CHAR(24) NULL,
							SHIPNODE_KEY	CHAR(24) NULL,
							MERGE_NODE	CHAR(24) NULL,
							CARRIER_SERVICE_CODE	VARCHAR2(40) NULL,
							BUYER_MARK_FOR_NODE_ID	CHAR(24) NULL,
							TOTAL_ACTUAL_CHARGE	NUMBER(15,2) NULL,
							SHIPMENT_CLOSED_FLAG	CHAR(1) NULL,
							ESTIMATED_PRICE	NUMBER(15,2) NULL,
							ESP_CHECK_REQUIRED	CHAR(1) NULL,
							BILL_TO_CUSTOMER_ID	CHAR(40) NULL,
							PIPELINE_KEY	CHAR(24) NULL,
							PRO_NO	CHAR(40) NULL,
							MANIFEST_KEY	CHAR(24) NULL,
							SHIPMENT_CONFIRM_UPDATES_DONE	CHAR(1) NULL,
							TOTAL_WEIGHT	NUMBER(14,4) NULL,
							PROFILE_ID	VARCHAR2(200) NULL,
							RELEASE_NO	NUMBER(5) NULL,
							PACK_AND_HOLD	CHAR(1) NULL,
							WO_BATCH_ID	VARCHAR2(40) NULL,
							EXTN_ACCOUNT_NAME	VARCHAR2(40) NULL
						)';  
EXCEPTION  
   WHEN OTHERS THEN  
      IF SQLCODE != -955 THEN  
         RAISE;  
      END IF;  
END;



&


/*-----------------------------------------------*/
/* TASK No. 10 */
/* Truncate target table */

truncate table RAX_APP_USER.STG_SHIPMENT


&


/*-----------------------------------------------*/
/* TASK No. 11 */
/* Insert new rows */

 
insert into	RAX_APP_USER.STG_SHIPMENT 
( 
	NEXT_ALERT_TS,
	BILL_TO_ADDRESS_KEY,
	IS_PACK_PROCESS_COMPLETE,
	SHIPMENT_SORT_LOCATION_ID,
	EXPORT_TAXPAYER_ID,
	TOTAL_ESTIMATED_CHARGE,
	ROUTING_SOURCE,
	CREATETS,
	TRAILER_NO,
	SHIPMENT_NO,
	ACTUAL_DELIVERY_DATE,
	EXPORT_LICENSE_EXP_DATE,
	INVOICE_COMPLETE,
	CARRIER_PICKUP_TIME,
	EXPORT_LICENSE_NO,
	DOWNLOAD_COUNT,
	MODIFYTS,
	REQUESTED_DELIVERY_DATE,
	ALLOW_OVERAGE,
	MUST_SHIP_BEFORE_DATE,
	LOCKID,
	SHIPMENT_PLANNED_FLAG,
	UNPLACED_QUANTITY,
	REQUESTED_CARRIER_SERVICE_CODE,
	REQUIRES_APPT_CONFIRMATION,
	IT_NO,
	BOL_NO,
	OVERRIDE_MANUAL_SHIPMENT_ENTRY,
	DELIVERY_TS,
	PARENT_SHIPMENT_KEY,
	COD_PAY_METHOD,
	NUM_OF_CARTONS,
	WORK_ORDER_APPT_KEY,
	PLACED_QUANTITY,
	LINES_ENTERED,
	CARRIER_SORT_LOCATION_ID,
	REQUESTED_SHIPMENT_DATE,
	TOTAL_WEIGHT_UOM,
	ACTUAL_SHIPMENT_DATE,
	IS_PRODUCT_PLACING_COMPLETE,
	SHIPMENT_KEY,
	TO_ADDRESS_KEY,
	SHIP_DATE,
	CODE,
	ACTUAL_FREIGHT_CHARGE,
	PICKTICKET_NO,
	RETURN_FREIGHT_TERMS,
	EXPECTED_PICK_DATE,
	DEPARTMENT_CODE,
	ITN_NO,
	PACKLIST_TYPE,
	ITEM_CLASSIFICATION,
	SHIPMENT_DELIVER_UPDATES_DONE,
	SELLER_ORGANIZATION_CODE,
	BBN_MIN_VOLUME,
	APPOINTMENT_NO,
	ALLOW_NEW_ITEM_RECEIPT,
	ORDER_HEADER_KEY,
	GIFT_FLAG,
	FROM_ADDRESS_KEY,
	TRACKING_NO,
	ORDER_AVAILABLE_ON_SYSTEM,
	MANIFEST_NO,
	DELIVERY_CODE,
	STATUS_DATE,
	MODIFYUSERID,
	CUSTOMER_PO_NO,
	RETURN_BILLING_ACCOUNT,
	DO_NOT_CONSOLIDATE,
	SHIP_VIA,
	DESTINATION_ZONE,
	EXTN_SORT_TYPE,
	EXTN_ROOM_BOARD_ITEM_ID,
	MODIFYPROGID,
	PROFILEID_PROVIDED_BY_STERLING,
	ORDER_TYPE,
	COMMERCIAL_VALUE,
	SHIP_MODE,
	AIRWAY_BILL_NO,
	MARK_FOR_KEY,
	HAS_OTHER_SHIPMENTS,
	ORIGIN_ZONE,
	RETURN_BY_DATE,
	ORDER_NO,
	SHIPMENT_CONSOL_GROUP_ID,
	IT_DATE,
	CONTAINERIZED_QUANTITY,
	STATUS,
	SHIPMENT_CONTAINERIZED_FLAG,
	RETURN_CARRIER_SERVICE,
	HAZARDOUS_MATERIAL_FLAG,
	RECEIVING_NODE,
	ORIGINAL_SHIPMENT_KEY,
	DO_NOT_VERIFY_CASE_CONTENT,
	BREAK_BULK_NODE,
	EXPECTED_SHIPMENT_DATE,
	TO_APPOINTMENT,
	SHIP_TO_CUSTOMER_ID,
	SCAC_INTEGRATION_REQUIRED,
	IS_SINGLE_ORDER,
	ROUTING_ERROR_CODE,
	CREATEPROGID,
	SEAL_NO,
	DELIVERY_METHOD,
	TOTAL_QUANTITY,
	EMAIL_RETURN_LABEL,
	BBN_MIN_WEIGHT,
	ROUTING_GUIDE_MAINTAINED,
	TOTAL_VOLUME_UOM,
	MANUALLY_ENTERED,
	DO_NOT_VERIFY_PALLET_CONTENT,
	IS_APPOINTMENT_REQD,
	CARRIER_TYPE,
	CURRENCY,
	EXTN_ROOM_BOARD_URL,
	BUYER_RECEIVING_NODE_ID,
	FREIGHT_TERMS,
	WORK_ORDER_KEY,
	HAS_NODE_EXCEPTIONS,
	FEDX_OPEN_SHIP_INDEX,
	ORDER_RELEASE_KEY,
	TOTAL_VOLUME,
	POD_NO,
	FROM_APPOINTMENT,
	BUYER_ORGANIZATION_CODE,
	RETURN_AUTHORIZATION_NUMBER,
	SCAC,
	IS_REVISED,
	HOLD_FLAG,
	ROUTING_CONTACT_INFO,
	EXPECTED_DELIVERY_DATE,
	PRIORITY_CODE,
	DOCUMENT_TYPE,
	SHIPMENT_TYPE,
	ENTERPRISE_CODE,
	CUSTCARRIER_ACCOUNT_NO,
	SHIPMENT_GROUP_ID,
	PICK_LIST_NO,
	CREATEUSERID,
	NUM_OF_PALLETS,
	DELIVERY_PLAN_KEY,
	SHIPNODE_KEY,
	MERGE_NODE,
	CARRIER_SERVICE_CODE,
	BUYER_MARK_FOR_NODE_ID,
	TOTAL_ACTUAL_CHARGE,
	SHIPMENT_CLOSED_FLAG,
	ESTIMATED_PRICE,
	ESP_CHECK_REQUIRED,
	BILL_TO_CUSTOMER_ID,
	PIPELINE_KEY,
	PRO_NO,
	MANIFEST_KEY,
	SHIPMENT_CONFIRM_UPDATES_DONE,
	TOTAL_WEIGHT,
	PROFILE_ID,
	RELEASE_NO,
	PACK_AND_HOLD,
	WO_BATCH_ID,
	EXTN_ACCOUNT_NAME 
	 
) 

select
    NEXT_ALERT_TS,
	BILL_TO_ADDRESS_KEY,
	IS_PACK_PROCESS_COMPLETE,
	SHIPMENT_SORT_LOCATION_ID,
	EXPORT_TAXPAYER_ID,
	TOTAL_ESTIMATED_CHARGE,
	ROUTING_SOURCE,
	CREATETS,
	TRAILER_NO,
	SHIPMENT_NO,
	ACTUAL_DELIVERY_DATE,
	EXPORT_LICENSE_EXP_DATE,
	INVOICE_COMPLETE,
	CARRIER_PICKUP_TIME,
	EXPORT_LICENSE_NO,
	DOWNLOAD_COUNT,
	MODIFYTS,
	REQUESTED_DELIVERY_DATE,
	ALLOW_OVERAGE,
	MUST_SHIP_BEFORE_DATE,
	LOCKID,
	SHIPMENT_PLANNED_FLAG,
	UNPLACED_QUANTITY,
	REQUESTED_CARRIER_SERVICE_CODE,
	REQUIRES_APPT_CONFIRMATION,
	IT_NO,
	BOL_NO,
	OVERRIDE_MANUAL_SHIPMENT_ENTRY,
	DELIVERY_TS,
	PARENT_SHIPMENT_KEY,
	COD_PAY_METHOD,
	NUM_OF_CARTONS,
	WORK_ORDER_APPT_KEY,
	PLACED_QUANTITY,
	LINES_ENTERED,
	CARRIER_SORT_LOCATION_ID,
	REQUESTED_SHIPMENT_DATE,
	TOTAL_WEIGHT_UOM,
	ACTUAL_SHIPMENT_DATE,
	IS_PRODUCT_PLACING_COMPLETE,
	SHIPMENT_KEY,
	TO_ADDRESS_KEY,
	SHIP_DATE,
	CODE,
	ACTUAL_FREIGHT_CHARGE,
	PICKTICKET_NO,
	RETURN_FREIGHT_TERMS,
	EXPECTED_PICK_DATE,
	DEPARTMENT_CODE,
	ITN_NO,
	PACKLIST_TYPE,
	ITEM_CLASSIFICATION,
	SHIPMENT_DELIVER_UPDATES_DONE,
	SELLER_ORGANIZATION_CODE,
	BBN_MIN_VOLUME,
	APPOINTMENT_NO,
	ALLOW_NEW_ITEM_RECEIPT,
	ORDER_HEADER_KEY,
	GIFT_FLAG,
	FROM_ADDRESS_KEY,
	TRACKING_NO,
	ORDER_AVAILABLE_ON_SYSTEM,
	MANIFEST_NO,
	DELIVERY_CODE,
	STATUS_DATE,
	MODIFYUSERID,
	CUSTOMER_PO_NO,
	RETURN_BILLING_ACCOUNT,
	DO_NOT_CONSOLIDATE,
	SHIP_VIA,
	DESTINATION_ZONE,
	EXTN_SORT_TYPE,
	EXTN_ROOM_BOARD_ITEM_ID,
	MODIFYPROGID,
	PROFILEID_PROVIDED_BY_STERLING,
	ORDER_TYPE,
	COMMERCIAL_VALUE,
	SHIP_MODE,
	AIRWAY_BILL_NO,
	MARK_FOR_KEY,
	HAS_OTHER_SHIPMENTS,
	ORIGIN_ZONE,
	RETURN_BY_DATE,
	ORDER_NO,
	SHIPMENT_CONSOL_GROUP_ID,
	IT_DATE,
	CONTAINERIZED_QUANTITY,
	STATUS,
	SHIPMENT_CONTAINERIZED_FLAG,
	RETURN_CARRIER_SERVICE,
	HAZARDOUS_MATERIAL_FLAG,
	RECEIVING_NODE,
	ORIGINAL_SHIPMENT_KEY,
	DO_NOT_VERIFY_CASE_CONTENT,
	BREAK_BULK_NODE,
	EXPECTED_SHIPMENT_DATE,
	TO_APPOINTMENT,
	SHIP_TO_CUSTOMER_ID,
	SCAC_INTEGRATION_REQUIRED,
	IS_SINGLE_ORDER,
	ROUTING_ERROR_CODE,
	CREATEPROGID,
	SEAL_NO,
	DELIVERY_METHOD,
	TOTAL_QUANTITY,
	EMAIL_RETURN_LABEL,
	BBN_MIN_WEIGHT,
	ROUTING_GUIDE_MAINTAINED,
	TOTAL_VOLUME_UOM,
	MANUALLY_ENTERED,
	DO_NOT_VERIFY_PALLET_CONTENT,
	IS_APPOINTMENT_REQD,
	CARRIER_TYPE,
	CURRENCY,
	EXTN_ROOM_BOARD_URL,
	BUYER_RECEIVING_NODE_ID,
	FREIGHT_TERMS,
	WORK_ORDER_KEY,
	HAS_NODE_EXCEPTIONS,
	FEDX_OPEN_SHIP_INDEX,
	ORDER_RELEASE_KEY,
	TOTAL_VOLUME,
	POD_NO,
	FROM_APPOINTMENT,
	BUYER_ORGANIZATION_CODE,
	RETURN_AUTHORIZATION_NUMBER,
	SCAC,
	IS_REVISED,
	HOLD_FLAG,
	ROUTING_CONTACT_INFO,
	EXPECTED_DELIVERY_DATE,
	PRIORITY_CODE,
	DOCUMENT_TYPE,
	SHIPMENT_TYPE,
	ENTERPRISE_CODE,
	CUSTCARRIER_ACCOUNT_NO,
	SHIPMENT_GROUP_ID,
	PICK_LIST_NO,
	CREATEUSERID,
	NUM_OF_PALLETS,
	DELIVERY_PLAN_KEY,
	SHIPNODE_KEY,
	MERGE_NODE,
	CARRIER_SERVICE_CODE,
	BUYER_MARK_FOR_NODE_ID,
	TOTAL_ACTUAL_CHARGE,
	SHIPMENT_CLOSED_FLAG,
	ESTIMATED_PRICE,
	ESP_CHECK_REQUIRED,
	BILL_TO_CUSTOMER_ID,
	PIPELINE_KEY,
	PRO_NO,
	MANIFEST_KEY,
	SHIPMENT_CONFIRM_UPDATES_DONE,
	TOTAL_WEIGHT,
	PROFILE_ID,
	RELEASE_NO,
	PACK_AND_HOLD,
	WO_BATCH_ID,
	EXTN_ACCOUNT_NAME   
   
FROM (	


select 	
	C1_NEXT_ALERT_TS NEXT_ALERT_TS,
	C2_BILL_TO_ADDRESS_KEY BILL_TO_ADDRESS_KEY,
	C3_IS_PACK_PROCESS_COMPLETE IS_PACK_PROCESS_COMPLETE,
	C4_SHIPMENT_SORT_LOCATION_ID SHIPMENT_SORT_LOCATION_ID,
	C5_EXPORT_TAXPAYER_ID EXPORT_TAXPAYER_ID,
	C6_TOTAL_ESTIMATED_CHARGE TOTAL_ESTIMATED_CHARGE,
	C7_ROUTING_SOURCE ROUTING_SOURCE,
	C8_CREATETS CREATETS,
	C9_TRAILER_NO TRAILER_NO,
	C10_SHIPMENT_NO SHIPMENT_NO,
	C11_ACTUAL_DELIVERY_DATE ACTUAL_DELIVERY_DATE,
	C12_EXPORT_LICENSE_EXP_DATE EXPORT_LICENSE_EXP_DATE,
	C13_INVOICE_COMPLETE INVOICE_COMPLETE,
	C14_CARRIER_PICKUP_TIME CARRIER_PICKUP_TIME,
	C15_EXPORT_LICENSE_NO EXPORT_LICENSE_NO,
	C16_DOWNLOAD_COUNT DOWNLOAD_COUNT,
	C17_MODIFYTS MODIFYTS,
	C18_REQUESTED_DELIVERY_DATE REQUESTED_DELIVERY_DATE,
	C19_ALLOW_OVERAGE ALLOW_OVERAGE,
	C20_MUST_SHIP_BEFORE_DATE MUST_SHIP_BEFORE_DATE,
	C21_LOCKID LOCKID,
	C22_SHIPMENT_PLANNED_FLAG SHIPMENT_PLANNED_FLAG,
	C23_UNPLACED_QUANTITY UNPLACED_QUANTITY,
	C24_REQUESTED_CARRIER_SERVICE_ REQUESTED_CARRIER_SERVICE_CODE,
	C25_REQUIRES_APPT_CONFIRMATION REQUIRES_APPT_CONFIRMATION,
	C26_IT_NO IT_NO,
	C27_BOL_NO BOL_NO,
	C28_OVERRIDE_MANUAL_SHIPMENT_E OVERRIDE_MANUAL_SHIPMENT_ENTRY,
	C29_DELIVERY_TS DELIVERY_TS,
	C30_PARENT_SHIPMENT_KEY PARENT_SHIPMENT_KEY,
	C31_COD_PAY_METHOD COD_PAY_METHOD,
	C32_NUM_OF_CARTONS NUM_OF_CARTONS,
	C33_WORK_ORDER_APPT_KEY WORK_ORDER_APPT_KEY,
	C34_PLACED_QUANTITY PLACED_QUANTITY,
	C35_LINES_ENTERED LINES_ENTERED,
	C36_CARRIER_SORT_LOCATION_ID CARRIER_SORT_LOCATION_ID,
	C37_REQUESTED_SHIPMENT_DATE REQUESTED_SHIPMENT_DATE,
	C38_TOTAL_WEIGHT_UOM TOTAL_WEIGHT_UOM,
	C39_ACTUAL_SHIPMENT_DATE ACTUAL_SHIPMENT_DATE,
	C40_IS_PRODUCT_PLACING_COMPLET IS_PRODUCT_PLACING_COMPLETE,
	C41_SHIPMENT_KEY SHIPMENT_KEY,
	C42_TO_ADDRESS_KEY TO_ADDRESS_KEY,
	C43_SHIP_DATE SHIP_DATE,
	C44_CODE CODE,
	C45_ACTUAL_FREIGHT_CHARGE ACTUAL_FREIGHT_CHARGE,
	C46_PICKTICKET_NO PICKTICKET_NO,
	C47_RETURN_FREIGHT_TERMS RETURN_FREIGHT_TERMS,
	C48_EXPECTED_PICK_DATE EXPECTED_PICK_DATE,
	C49_DEPARTMENT_CODE DEPARTMENT_CODE,
	C50_ITN_NO ITN_NO,
	C51_PACKLIST_TYPE PACKLIST_TYPE,
	C52_ITEM_CLASSIFICATION ITEM_CLASSIFICATION,
	C53_SHIPMENT_DELIVER_UPDATES_D SHIPMENT_DELIVER_UPDATES_DONE,
	C54_SELLER_ORGANIZATION_CODE SELLER_ORGANIZATION_CODE,
	C55_BBN_MIN_VOLUME BBN_MIN_VOLUME,
	C56_APPOINTMENT_NO APPOINTMENT_NO,
	C57_ALLOW_NEW_ITEM_RECEIPT ALLOW_NEW_ITEM_RECEIPT,
	C58_ORDER_HEADER_KEY ORDER_HEADER_KEY,
	C59_GIFT_FLAG GIFT_FLAG,
	C60_FROM_ADDRESS_KEY FROM_ADDRESS_KEY,
	C61_TRACKING_NO TRACKING_NO,
	C62_ORDER_AVAILABLE_ON_SYSTEM ORDER_AVAILABLE_ON_SYSTEM,
	C63_MANIFEST_NO MANIFEST_NO,
	C64_DELIVERY_CODE DELIVERY_CODE,
	C65_STATUS_DATE STATUS_DATE,
	C66_MODIFYUSERID MODIFYUSERID,
	C67_CUSTOMER_PO_NO CUSTOMER_PO_NO,
	C68_RETURN_BILLING_ACCOUNT RETURN_BILLING_ACCOUNT,
	C69_DO_NOT_CONSOLIDATE DO_NOT_CONSOLIDATE,
	C70_SHIP_VIA SHIP_VIA,
	C71_DESTINATION_ZONE DESTINATION_ZONE,
	C72_EXTN_SORT_TYPE EXTN_SORT_TYPE,
	C73_EXTN_ROOM_BOARD_ITEM_ID EXTN_ROOM_BOARD_ITEM_ID,
	C74_MODIFYPROGID MODIFYPROGID,
	C75_PROFILEID_PROVIDED_BY_STER PROFILEID_PROVIDED_BY_STERLING,
	C76_ORDER_TYPE ORDER_TYPE,
	C77_COMMERCIAL_VALUE COMMERCIAL_VALUE,
	C78_SHIP_MODE SHIP_MODE,
	C79_AIRWAY_BILL_NO AIRWAY_BILL_NO,
	C80_MARK_FOR_KEY MARK_FOR_KEY,
	C81_HAS_OTHER_SHIPMENTS HAS_OTHER_SHIPMENTS,
	C82_ORIGIN_ZONE ORIGIN_ZONE,
	C83_RETURN_BY_DATE RETURN_BY_DATE,
	C84_ORDER_NO ORDER_NO,
	C85_SHIPMENT_CONSOL_GROUP_ID SHIPMENT_CONSOL_GROUP_ID,
	C86_IT_DATE IT_DATE,
	C87_CONTAINERIZED_QUANTITY CONTAINERIZED_QUANTITY,
	C88_STATUS STATUS,
	C89_SHIPMENT_CONTAINERIZED_FLA SHIPMENT_CONTAINERIZED_FLAG,
	C90_RETURN_CARRIER_SERVICE RETURN_CARRIER_SERVICE,
	C91_HAZARDOUS_MATERIAL_FLAG HAZARDOUS_MATERIAL_FLAG,
	C92_RECEIVING_NODE RECEIVING_NODE,
	C93_ORIGINAL_SHIPMENT_KEY ORIGINAL_SHIPMENT_KEY,
	C94_DO_NOT_VERIFY_CASE_CONTENT DO_NOT_VERIFY_CASE_CONTENT,
	C95_BREAK_BULK_NODE BREAK_BULK_NODE,
	C96_EXPECTED_SHIPMENT_DATE EXPECTED_SHIPMENT_DATE,
	C97_TO_APPOINTMENT TO_APPOINTMENT,
	C98_SHIP_TO_CUSTOMER_ID SHIP_TO_CUSTOMER_ID,
	C99_SCAC_INTEGRATION_REQUIRED SCAC_INTEGRATION_REQUIRED,
	C100_IS_SINGLE_ORDER IS_SINGLE_ORDER,
	C101_ROUTING_ERROR_CODE ROUTING_ERROR_CODE,
	C102_CREATEPROGID CREATEPROGID,
	C103_SEAL_NO SEAL_NO,
	C104_DELIVERY_METHOD DELIVERY_METHOD,
	C105_TOTAL_QUANTITY TOTAL_QUANTITY,
	C106_EMAIL_RETURN_LABEL EMAIL_RETURN_LABEL,
	C107_BBN_MIN_WEIGHT BBN_MIN_WEIGHT,
	C108_ROUTING_GUIDE_MAINTAINED ROUTING_GUIDE_MAINTAINED,
	C109_TOTAL_VOLUME_UOM TOTAL_VOLUME_UOM,
	C110_MANUALLY_ENTERED MANUALLY_ENTERED,
	C111_DO_NOT_VERIFY_PALLET_CONT DO_NOT_VERIFY_PALLET_CONTENT,
	C112_IS_APPOINTMENT_REQD IS_APPOINTMENT_REQD,
	C113_CARRIER_TYPE CARRIER_TYPE,
	C114_CURRENCY CURRENCY,
	C115_EXTN_ROOM_BOARD_URL EXTN_ROOM_BOARD_URL,
	C116_BUYER_RECEIVING_NODE_ID BUYER_RECEIVING_NODE_ID,
	C117_FREIGHT_TERMS FREIGHT_TERMS,
	C118_WORK_ORDER_KEY WORK_ORDER_KEY,
	C119_HAS_NODE_EXCEPTIONS HAS_NODE_EXCEPTIONS,
	C120_FEDX_OPEN_SHIP_INDEX FEDX_OPEN_SHIP_INDEX,
	C121_ORDER_RELEASE_KEY ORDER_RELEASE_KEY,
	C122_TOTAL_VOLUME TOTAL_VOLUME,
	C123_POD_NO POD_NO,
	C124_FROM_APPOINTMENT FROM_APPOINTMENT,
	C125_BUYER_ORGANIZATION_CODE BUYER_ORGANIZATION_CODE,
	C126_RETURN_AUTHORIZATION_NUMB RETURN_AUTHORIZATION_NUMBER,
	C127_SCAC SCAC,
	C128_IS_REVISED IS_REVISED,
	C129_HOLD_FLAG HOLD_FLAG,
	C130_ROUTING_CONTACT_INFO ROUTING_CONTACT_INFO,
	C131_EXPECTED_DELIVERY_DATE EXPECTED_DELIVERY_DATE,
	C132_PRIORITY_CODE PRIORITY_CODE,
	C133_DOCUMENT_TYPE DOCUMENT_TYPE,
	C134_SHIPMENT_TYPE SHIPMENT_TYPE,
	C135_ENTERPRISE_CODE ENTERPRISE_CODE,
	C136_CUSTCARRIER_ACCOUNT_NO CUSTCARRIER_ACCOUNT_NO,
	C137_SHIPMENT_GROUP_ID SHIPMENT_GROUP_ID,
	C138_PICK_LIST_NO PICK_LIST_NO,
	C139_CREATEUSERID CREATEUSERID,
	C140_NUM_OF_PALLETS NUM_OF_PALLETS,
	C141_DELIVERY_PLAN_KEY DELIVERY_PLAN_KEY,
	C142_SHIPNODE_KEY SHIPNODE_KEY,
	C143_MERGE_NODE MERGE_NODE,
	C144_CARRIER_SERVICE_CODE CARRIER_SERVICE_CODE,
	C145_BUYER_MARK_FOR_NODE_ID BUYER_MARK_FOR_NODE_ID,
	C146_TOTAL_ACTUAL_CHARGE TOTAL_ACTUAL_CHARGE,
	C147_SHIPMENT_CLOSED_FLAG SHIPMENT_CLOSED_FLAG,
	C148_ESTIMATED_PRICE ESTIMATED_PRICE,
	C149_ESP_CHECK_REQUIRED ESP_CHECK_REQUIRED,
	C150_BILL_TO_CUSTOMER_ID BILL_TO_CUSTOMER_ID,
	C151_PIPELINE_KEY PIPELINE_KEY,
	C152_PRO_NO PRO_NO,
	C153_MANIFEST_KEY MANIFEST_KEY,
	C154_SHIPMENT_CONFIRM_UPDATES_ SHIPMENT_CONFIRM_UPDATES_DONE,
	C155_TOTAL_WEIGHT TOTAL_WEIGHT,
	C156_PROFILE_ID PROFILE_ID,
	C157_RELEASE_NO RELEASE_NO,
	C158_PACK_AND_HOLD PACK_AND_HOLD,
	C159_WO_BATCH_ID WO_BATCH_ID,
	C160_EXTN_ACCOUNT_NAME EXTN_ACCOUNT_NAME 
from	RAX_APP_USER.C$_0STG_SHIPMENT
where		(1=1)	






)    ODI_GET_FROM




&


/*-----------------------------------------------*/
/* TASK No. 12 */
/* Commit transaction */

/* commit */


/*-----------------------------------------------*/
/* TASK No. 1000008 */
/* Drop work table */

drop table RAX_APP_USER.C$_0STG_SHIPMENT 

&


/*-----------------------------------------------*/
/* TASK No. 13 */
/* Set vID */

/* NONE or SET VARIABLE STATEMENT FOUND, CHECK ODI TASK NO. 13 */




/*-----------------------------------------------*/
/* TASK No. 14 */
/* Drop flow table */

BEGIN  
   EXECUTE IMMEDIATE 'drop table RAX_APP_USER.I$_OMS_SHIPMENT_XR59001';  
EXCEPTION  
   WHEN OTHERS THEN  
      IF SQLCODE != -942 THEN  
         RAISE;  
      END IF;  
END; 

&


/*-----------------------------------------------*/
/* TASK No. 15 */
/* Create flow table I$ */

create table RAX_APP_USER.I$_OMS_SHIPMENT_XR59001
(
	SHIPMENT_OID	NUMBER(22) NULL,
	SHIPMENT_KEY	VARCHAR2(24) NULL,
	ODS_CREATE_DATE	DATE NULL,
	ORDER_HEADER_KEY	VARCHAR2(24) NULL,
	TO_ADDRESS_KEY	VARCHAR2(24) NULL
	,IND_UPDATE		char(1)
)
NOLOGGING

&


/*-----------------------------------------------*/
/* TASK No. 16 */
/* Insert flow into I$ table */

/* DETECTION_STRATEGY = NOT_EXISTS */
 


  


insert into	RAX_APP_USER.I$_OMS_SHIPMENT_XR59001
(
	SHIPMENT_KEY,
	ORDER_HEADER_KEY,
	TO_ADDRESS_KEY,
	IND_UPDATE
)
select 
SHIPMENT_KEY,
	ORDER_HEADER_KEY,
	TO_ADDRESS_KEY,
	IND_UPDATE
 from (


select 	 
	DISTINCT
	TRIM(SHP.SHIPMENT_KEY) SHIPMENT_KEY,
	TRIM(SHP.ORDER_HEADER_KEY) ORDER_HEADER_KEY,
	TRIM(SHP.TO_ADDRESS_KEY) TO_ADDRESS_KEY,

	'I' IND_UPDATE

from	RAX_APP_USER.STG_SHIPMENT   SHP, ODS_STAGE.OMS_SHIPMENT_XR   OMS_SHIPMENT_XR
where	(1=1)
 And (TRIM(SHP.SHIPMENT_KEY)=OMS_SHIPMENT_XR.SHIPMENT_KEY (+)
AND OMS_SHIPMENT_XR.SHIPMENT_KEY IS NULL)





) S
where NOT EXISTS 
	( select 1 from ODS_STAGE.OMS_SHIPMENT_XR T
	where	T.SHIPMENT_KEY	= S.SHIPMENT_KEY 
		 and ((T.ORDER_HEADER_KEY = S.ORDER_HEADER_KEY) or (T.ORDER_HEADER_KEY IS NULL and S.ORDER_HEADER_KEY IS NULL)) and
		((T.TO_ADDRESS_KEY = S.TO_ADDRESS_KEY) or (T.TO_ADDRESS_KEY IS NULL and S.TO_ADDRESS_KEY IS NULL))
        )

  
  

  



&


/*-----------------------------------------------*/
/* TASK No. 17 */
/* Analyze integration table */



begin
    dbms_stats.gather_table_stats(
	ownname => 'RAX_APP_USER',
	tabname => 'I$_OMS_SHIPMENT_XR59001',
	estimate_percent => dbms_stats.auto_sample_size
    );
end;



&


/*-----------------------------------------------*/
/* TASK No. 18 */
/* Create Index on flow table */

create index	RAX_APP_USER.I$_OMS_SHIPMENT_XR_IDX59001
on		RAX_APP_USER.I$_OMS_SHIPMENT_XR59001 (SHIPMENT_KEY)
NOLOGGING

&


/*-----------------------------------------------*/
/* TASK No. 19 */
/* Merge Rows */

merge into	ODS_STAGE.OMS_SHIPMENT_XR T
using	RAX_APP_USER.I$_OMS_SHIPMENT_XR59001 S
on	(
		T.SHIPMENT_KEY=S.SHIPMENT_KEY
	)
when matched
then update set
	T.ORDER_HEADER_KEY	= S.ORDER_HEADER_KEY,
	T.TO_ADDRESS_KEY	= S.TO_ADDRESS_KEY
	
when not matched
then insert
	(
	T.SHIPMENT_KEY,
	T.ORDER_HEADER_KEY,
	T.TO_ADDRESS_KEY
	,   T.SHIPMENT_OID,
	T.ODS_CREATE_DATE
	)
values
	(
	S.SHIPMENT_KEY,
	S.ORDER_HEADER_KEY,
	S.TO_ADDRESS_KEY
	,   ODS_STAGE.SHIPMENT_OID_SEQ.nextval,
	SYSDATE
	)

&


/*-----------------------------------------------*/
/* TASK No. 20 */
/* Commit transaction */

/*commit*/


/*-----------------------------------------------*/
/* TASK No. 21 */
/* Drop flow table */

drop table RAX_APP_USER.I$_OMS_SHIPMENT_XR59001 

&


/*-----------------------------------------------*/
/* TASK No. 22 */
/* Set vID */

/* NONE or SET VARIABLE STATEMENT FOUND, CHECK ODI TASK NO. 22 */




/*-----------------------------------------------*/
/* TASK No. 23 */
/* Drop flow table */

BEGIN  
   EXECUTE IMMEDIATE 'drop table RAX_APP_USER.I$_SHIPMENT60001';  
EXCEPTION  
   WHEN OTHERS THEN  
      IF SQLCODE != -942 THEN  
         RAISE;  
      END IF;  
END;

&


/*-----------------------------------------------*/
/* TASK No. 24 */
/* Create flow table I$ */

create table RAX_APP_USER.I$_SHIPMENT60001
(
	SHIPMENT_OID	NUMBER NULL,
	SHIPMENT_NO	VARCHAR2(40) NULL,
	SHIP_DATE	DATE NULL,
	SHIP_NODE	VARCHAR2(100) NULL,
	TRACKING_NO	VARCHAR2(40) NULL,
	STATUS	VARCHAR2(15) NULL,
	ACTUAL_SHIPMENT_DATE	DATE NULL,
	ACTUAL_DELIVERY_DATE	DATE NULL,
	PERSON_INFO_OID	NUMBER NULL,
	ODS_CREATE_DATE	DATE NULL,
	ODS_MODIFY_DATE	DATE NULL,
	SOURCE_SYSTEM_OID	NUMBER NULL,
	SHIP_VIA	VARCHAR2(35) NULL,
	TOTAL_ACTUAL_CHARGE	NUMBER NULL,
	ACTUAL_FREIGHT_CHARGE	NUMBER NULL,
	WO_BATCH_ID	VARCHAR2(40) NULL,
	SHIP_MODE	VARCHAR2(40) NULL,
	SCAC	CHAR(24) NULL,
	CARRIER_SERVICE_CODE	VARCHAR2(40) NULL,
	REQUESTED_CARRIER_SERVICE_CODE	VARCHAR2(40) NULL,
	TOTAL_WEIGHT	NUMBER(14,4) NULL,
	TOTAL_VOLUME	NUMBER(14,4) NULL,
	TOTAL_VOLUME_UOM	VARCHAR2(40) NULL,
	TOTAL_QUANTITY	NUMBER(14,4) NULL,
	NUM_OF_PALLETS	NUMBER(5) NULL,
	NUM_OF_CARTONS	NUMBER(5) NULL,
	CARRIER_TYPE	VARCHAR2(40) NULL,
	ORDER_TYPE	VARCHAR2(20) NULL,
	SHIPMENT_CONFIRM_UPDATES_DONE	CHAR(1) NULL,
	SHIPMENT_CLOSED_FLAG	VARCHAR2(40) NULL,
	ENTERPRISE_CODE	VARCHAR2(40) NULL,
	EXTN_ACCOUNT_NAME	VARCHAR2(40) NULL,
	FROM_ADDRESS_KEY	CHAR(24) NULL,
	TO_ADDRESS_KEY	CHAR(24) NULL
	,IND_UPDATE		char(1)
)
NOLOGGING

&


/*-----------------------------------------------*/
/* TASK No. 25 */
/* Insert flow into I$ table */

/* DETECTION_STRATEGY = NOT_EXISTS */
 


  


insert into	RAX_APP_USER.I$_SHIPMENT60001
(
	SHIPMENT_OID,
	SHIPMENT_NO,
	SHIP_DATE,
	SHIP_NODE,
	TRACKING_NO,
	STATUS,
	ACTUAL_SHIPMENT_DATE,
	ACTUAL_DELIVERY_DATE,
	PERSON_INFO_OID,
	SOURCE_SYSTEM_OID,
	SHIP_VIA,
	TOTAL_ACTUAL_CHARGE,
	ACTUAL_FREIGHT_CHARGE,
	WO_BATCH_ID,
	SHIP_MODE,
	SCAC,
	CARRIER_SERVICE_CODE,
	REQUESTED_CARRIER_SERVICE_CODE,
	TOTAL_WEIGHT,
	TOTAL_VOLUME,
	TOTAL_VOLUME_UOM,
	TOTAL_QUANTITY,
	NUM_OF_PALLETS,
	NUM_OF_CARTONS,
	CARRIER_TYPE,
	ORDER_TYPE,
	SHIPMENT_CONFIRM_UPDATES_DONE,
	SHIPMENT_CLOSED_FLAG,
	ENTERPRISE_CODE,
	EXTN_ACCOUNT_NAME,
	FROM_ADDRESS_KEY,
	TO_ADDRESS_KEY,
	IND_UPDATE
)
select 
SHIPMENT_OID,
	SHIPMENT_NO,
	SHIP_DATE,
	SHIP_NODE,
	TRACKING_NO,
	STATUS,
	ACTUAL_SHIPMENT_DATE,
	ACTUAL_DELIVERY_DATE,
	PERSON_INFO_OID,
	SOURCE_SYSTEM_OID,
	SHIP_VIA,
	TOTAL_ACTUAL_CHARGE,
	ACTUAL_FREIGHT_CHARGE,
	WO_BATCH_ID,
	SHIP_MODE,
	SCAC,
	CARRIER_SERVICE_CODE,
	REQUESTED_CARRIER_SERVICE_CODE,
	TOTAL_WEIGHT,
	TOTAL_VOLUME,
	TOTAL_VOLUME_UOM,
	TOTAL_QUANTITY,
	NUM_OF_PALLETS,
	NUM_OF_CARTONS,
	CARRIER_TYPE,
	ORDER_TYPE,
	SHIPMENT_CONFIRM_UPDATES_DONE,
	SHIPMENT_CLOSED_FLAG,
	ENTERPRISE_CODE,
	EXTN_ACCOUNT_NAME,
	FROM_ADDRESS_KEY,
	TO_ADDRESS_KEY,
	IND_UPDATE
 from (


select 	 
	
	OMS_SHIPMENT_XR1.SHIPMENT_OID SHIPMENT_OID,
	trim(SHP.SHIPMENT_NO) SHIPMENT_NO,
	SHP.SHIP_DATE SHIP_DATE,
	trim(SHP.SHIPNODE_KEY) SHIP_NODE,
	trim(SHP.TRACKING_NO) TRACKING_NO,
	trim(SHP.STATUS) STATUS,
	SHP.ACTUAL_SHIPMENT_DATE ACTUAL_SHIPMENT_DATE,
	SHP.ACTUAL_DELIVERY_DATE ACTUAL_DELIVERY_DATE,
	NVL(OMS_PERSON_INFO_XR1.PERSON_INFO_OID, -1) PERSON_INFO_OID,
	SOURCE_SYSTEM.SOURCE_SYSTEM_OID SOURCE_SYSTEM_OID,
	SHP.SHIP_VIA SHIP_VIA,
	SHP.TOTAL_ACTUAL_CHARGE TOTAL_ACTUAL_CHARGE,
	SHP.ACTUAL_FREIGHT_CHARGE ACTUAL_FREIGHT_CHARGE,
	SHP.WO_BATCH_ID WO_BATCH_ID,
	SHP.SHIP_MODE SHIP_MODE,
	SHP.SCAC SCAC,
	SHP.CARRIER_SERVICE_CODE CARRIER_SERVICE_CODE,
	SHP.REQUESTED_CARRIER_SERVICE_CODE REQUESTED_CARRIER_SERVICE_CODE,
	SHP.TOTAL_WEIGHT TOTAL_WEIGHT,
	SHP.TOTAL_VOLUME TOTAL_VOLUME,
	SHP.TOTAL_VOLUME_UOM TOTAL_VOLUME_UOM,
	SHP.TOTAL_QUANTITY TOTAL_QUANTITY,
	SHP.NUM_OF_PALLETS NUM_OF_PALLETS,
	SHP.NUM_OF_CARTONS NUM_OF_CARTONS,
	SHP.CARRIER_TYPE CARRIER_TYPE,
	SHP.ORDER_TYPE ORDER_TYPE,
	SHP.SHIPMENT_CONFIRM_UPDATES_DONE SHIPMENT_CONFIRM_UPDATES_DONE,
	SHP.SHIPMENT_CLOSED_FLAG SHIPMENT_CLOSED_FLAG,
	SHP.ENTERPRISE_CODE ENTERPRISE_CODE,
	SHP.EXTN_ACCOUNT_NAME EXTN_ACCOUNT_NAME,
	SHP.FROM_ADDRESS_KEY FROM_ADDRESS_KEY,
	SHP.TO_ADDRESS_KEY TO_ADDRESS_KEY,

	'I' IND_UPDATE

from	RAX_APP_USER.STG_SHIPMENT   SHP, ODS_OWN.SOURCE_SYSTEM   SOURCE_SYSTEM, ODS_STAGE.OMS_SHIPMENT_XR   OMS_SHIPMENT_XR1, ODS_STAGE.OMS_PERSON_INFO_XR   OMS_PERSON_INFO_XR1
where	(1=1)
 And (TRIM(SHP.SHIPMENT_KEY)=OMS_SHIPMENT_XR1.SHIPMENT_KEY (+))
AND (TRIM(OMS_SHIPMENT_XR1.TO_ADDRESS_KEY)=OMS_PERSON_INFO_XR1.PERSON_INFO_KEY (+))
And (SOURCE_SYSTEM.SOURCE_SYSTEM_SHORT_NAME='OMS')




) S
where NOT EXISTS 
	( select 1 from ODS_OWN.SHIPMENT T
	where	T.SHIPMENT_OID	= S.SHIPMENT_OID 
		 and ((T.SHIPMENT_NO = S.SHIPMENT_NO) or (T.SHIPMENT_NO IS NULL and S.SHIPMENT_NO IS NULL)) and
		((T.SHIP_DATE = S.SHIP_DATE) or (T.SHIP_DATE IS NULL and S.SHIP_DATE IS NULL)) and
		((T.SHIP_NODE = S.SHIP_NODE) or (T.SHIP_NODE IS NULL and S.SHIP_NODE IS NULL)) and
		((T.TRACKING_NO = S.TRACKING_NO) or (T.TRACKING_NO IS NULL and S.TRACKING_NO IS NULL)) and
		((T.STATUS = S.STATUS) or (T.STATUS IS NULL and S.STATUS IS NULL)) and
		((T.ACTUAL_SHIPMENT_DATE = S.ACTUAL_SHIPMENT_DATE) or (T.ACTUAL_SHIPMENT_DATE IS NULL and S.ACTUAL_SHIPMENT_DATE IS NULL)) and
		((T.ACTUAL_DELIVERY_DATE = S.ACTUAL_DELIVERY_DATE) or (T.ACTUAL_DELIVERY_DATE IS NULL and S.ACTUAL_DELIVERY_DATE IS NULL)) and
		((T.PERSON_INFO_OID = S.PERSON_INFO_OID) or (T.PERSON_INFO_OID IS NULL and S.PERSON_INFO_OID IS NULL)) and
		((T.SOURCE_SYSTEM_OID = S.SOURCE_SYSTEM_OID) or (T.SOURCE_SYSTEM_OID IS NULL and S.SOURCE_SYSTEM_OID IS NULL)) and
		((T.SHIP_VIA = S.SHIP_VIA) or (T.SHIP_VIA IS NULL and S.SHIP_VIA IS NULL)) and
		((T.TOTAL_ACTUAL_CHARGE = S.TOTAL_ACTUAL_CHARGE) or (T.TOTAL_ACTUAL_CHARGE IS NULL and S.TOTAL_ACTUAL_CHARGE IS NULL)) and
		((T.ACTUAL_FREIGHT_CHARGE = S.ACTUAL_FREIGHT_CHARGE) or (T.ACTUAL_FREIGHT_CHARGE IS NULL and S.ACTUAL_FREIGHT_CHARGE IS NULL)) and
		((T.WO_BATCH_ID = S.WO_BATCH_ID) or (T.WO_BATCH_ID IS NULL and S.WO_BATCH_ID IS NULL)) and
		((T.SHIP_MODE = S.SHIP_MODE) or (T.SHIP_MODE IS NULL and S.SHIP_MODE IS NULL)) and
		((T.SCAC = S.SCAC) or (T.SCAC IS NULL and S.SCAC IS NULL)) and
		((T.CARRIER_SERVICE_CODE = S.CARRIER_SERVICE_CODE) or (T.CARRIER_SERVICE_CODE IS NULL and S.CARRIER_SERVICE_CODE IS NULL)) and
		((T.REQUESTED_CARRIER_SERVICE_CODE = S.REQUESTED_CARRIER_SERVICE_CODE) or (T.REQUESTED_CARRIER_SERVICE_CODE IS NULL and S.REQUESTED_CARRIER_SERVICE_CODE IS NULL)) and
		((T.TOTAL_WEIGHT = S.TOTAL_WEIGHT) or (T.TOTAL_WEIGHT IS NULL and S.TOTAL_WEIGHT IS NULL)) and
		((T.TOTAL_VOLUME = S.TOTAL_VOLUME) or (T.TOTAL_VOLUME IS NULL and S.TOTAL_VOLUME IS NULL)) and
		((T.TOTAL_VOLUME_UOM = S.TOTAL_VOLUME_UOM) or (T.TOTAL_VOLUME_UOM IS NULL and S.TOTAL_VOLUME_UOM IS NULL)) and
		((T.TOTAL_QUANTITY = S.TOTAL_QUANTITY) or (T.TOTAL_QUANTITY IS NULL and S.TOTAL_QUANTITY IS NULL)) and
		((T.NUM_OF_PALLETS = S.NUM_OF_PALLETS) or (T.NUM_OF_PALLETS IS NULL and S.NUM_OF_PALLETS IS NULL)) and
		((T.NUM_OF_CARTONS = S.NUM_OF_CARTONS) or (T.NUM_OF_CARTONS IS NULL and S.NUM_OF_CARTONS IS NULL)) and
		((T.CARRIER_TYPE = S.CARRIER_TYPE) or (T.CARRIER_TYPE IS NULL and S.CARRIER_TYPE IS NULL)) and
		((T.ORDER_TYPE = S.ORDER_TYPE) or (T.ORDER_TYPE IS NULL and S.ORDER_TYPE IS NULL)) and
		((T.SHIPMENT_CONFIRM_UPDATES_DONE = S.SHIPMENT_CONFIRM_UPDATES_DONE) or (T.SHIPMENT_CONFIRM_UPDATES_DONE IS NULL and S.SHIPMENT_CONFIRM_UPDATES_DONE IS NULL)) and
		((T.SHIPMENT_CLOSED_FLAG = S.SHIPMENT_CLOSED_FLAG) or (T.SHIPMENT_CLOSED_FLAG IS NULL and S.SHIPMENT_CLOSED_FLAG IS NULL)) and
		((T.ENTERPRISE_CODE = S.ENTERPRISE_CODE) or (T.ENTERPRISE_CODE IS NULL and S.ENTERPRISE_CODE IS NULL)) and
		((T.EXTN_ACCOUNT_NAME = S.EXTN_ACCOUNT_NAME) or (T.EXTN_ACCOUNT_NAME IS NULL and S.EXTN_ACCOUNT_NAME IS NULL)) and
		((T.FROM_ADDRESS_KEY = S.FROM_ADDRESS_KEY) or (T.FROM_ADDRESS_KEY IS NULL and S.FROM_ADDRESS_KEY IS NULL)) and
		((T.TO_ADDRESS_KEY = S.TO_ADDRESS_KEY) or (T.TO_ADDRESS_KEY IS NULL and S.TO_ADDRESS_KEY IS NULL))
        )

  
  

  



&


/*-----------------------------------------------*/
/* TASK No. 26 */
/* Recycle previous errors */
BEGIN
   EXECUTE IMMEDIATE 'insert into RAX_APP_USER.I$_SHIPMENT60001
						(
							SHIPMENT_OID,
							SHIPMENT_NO,
							SHIP_DATE,
							SHIP_NODE,
							TRACKING_NO,
							STATUS,
							ACTUAL_SHIPMENT_DATE,
							ACTUAL_DELIVERY_DATE,
							PERSON_INFO_OID,
							SOURCE_SYSTEM_OID,
							SHIP_VIA,
							TOTAL_ACTUAL_CHARGE,
							ACTUAL_FREIGHT_CHARGE,
							WO_BATCH_ID,
							SHIP_MODE,
							SCAC,
							CARRIER_SERVICE_CODE,
							REQUESTED_CARRIER_SERVICE_CODE,
							TOTAL_WEIGHT,
							TOTAL_VOLUME,
							TOTAL_VOLUME_UOM,
							TOTAL_QUANTITY,
							NUM_OF_PALLETS,
							NUM_OF_CARTONS,
							CARRIER_TYPE,
							ORDER_TYPE,
							SHIPMENT_CONFIRM_UPDATES_DONE,
							SHIPMENT_CLOSED_FLAG,
							ENTERPRISE_CODE,
							EXTN_ACCOUNT_NAME,
							FROM_ADDRESS_KEY,
							TO_ADDRESS_KEY,
							IND_UPDATE
						)
						select	DISTINCT SHIPMENT_OID,
							SHIPMENT_NO,
							SHIP_DATE,
							SHIP_NODE,
							TRACKING_NO,
							STATUS,
							ACTUAL_SHIPMENT_DATE,
							ACTUAL_DELIVERY_DATE,
							PERSON_INFO_OID,
							SOURCE_SYSTEM_OID,
							SHIP_VIA,
							TOTAL_ACTUAL_CHARGE,
							ACTUAL_FREIGHT_CHARGE,
							WO_BATCH_ID,
							SHIP_MODE,
							SCAC,
							CARRIER_SERVICE_CODE,
							REQUESTED_CARRIER_SERVICE_CODE,
							TOTAL_WEIGHT,
							TOTAL_VOLUME,
							TOTAL_VOLUME_UOM,
							TOTAL_QUANTITY,
							NUM_OF_PALLETS,
							NUM_OF_CARTONS,
							CARRIER_TYPE,
							ORDER_TYPE,
							SHIPMENT_CONFIRM_UPDATES_DONE,
							SHIPMENT_CLOSED_FLAG,
							ENTERPRISE_CODE,
							EXTN_ACCOUNT_NAME,
							FROM_ADDRESS_KEY,
							TO_ADDRESS_KEY,
							''I'' IND_UPDATE
						from	RAX_APP_USER.E$_SHIPMENT60001 E
						where 	not exists (
								select	''?''
								from	RAX_APP_USER.I$_SHIPMENT60001 T
								where			T.SHIPMENT_OID=E.SHIPMENT_OID
								)
						and	E.ODI_ORIGIN	= ''(60001)ODS_Project.LOAD_SHIPMENT_INT''
						and	E.ODI_ERR_TYPE	= ''F''';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;

&


/*-----------------------------------------------*/
/* TASK No. 27 */
/* Analyze integration table */



begin
    dbms_stats.gather_table_stats(
	ownname => 'RAX_APP_USER',
	tabname => 'I$_SHIPMENT60001',
	estimate_percent => dbms_stats.auto_sample_size
    );
end;



&


/*-----------------------------------------------*/
/* TASK No. 28 */
/* Create Index on flow table */

create index	RAX_APP_USER.I$_SHIPMENT_IDX60001
on		RAX_APP_USER.I$_SHIPMENT60001 (SHIPMENT_OID)
NOLOGGING

&


/*-----------------------------------------------*/
/* TASK No. 29 */
/* create check table */


BEGIN  
   EXECUTE IMMEDIATE 'create table RAX_APP_USER.SNP_CHECK_TAB
						(
							CATALOG_NAME	VARCHAR2(100 CHAR) NULL ,
							SCHEMA_NAME	VARCHAR2(100 CHAR) NULL ,
							RESOURCE_NAME	VARCHAR2(100 CHAR) NULL,
							FULL_RES_NAME	VARCHAR2(100 CHAR) NULL,
							ERR_TYPE		VARCHAR2(1 CHAR) NULL,
							ERR_MESS		VARCHAR2(250 CHAR) NULL ,
							CHECK_DATE	DATE NULL,
							ORIGIN		VARCHAR2(100 CHAR) NULL,
							CONS_NAME	VARCHAR2(35 CHAR) NULL,
							CONS_TYPE		VARCHAR2(2 CHAR) NULL,
							ERR_COUNT		NUMBER(10) NULL
						)';  
EXCEPTION  
   WHEN OTHERS THEN  
      IF SQLCODE != -955 THEN  
         RAISE;  
      END IF;  
END;
	

&


/*-----------------------------------------------*/
/* TASK No. 30 */
/* delete previous check sum */

delete from	RAX_APP_USER.SNP_CHECK_TAB
where	SCHEMA_NAME	= 'ODS_OWN'
and	ORIGIN 		= '(60001)ODS_Project.LOAD_SHIPMENT_INT'
and	ERR_TYPE 		= 'F'


&


/*-----------------------------------------------*/
/* TASK No. 31 */
/* create error table */
BEGIN  
   EXECUTE IMMEDIATE 'create table RAX_APP_USER.E$_SHIPMENT60001
						(
							ODI_ROW_ID 		UROWID,
							ODI_ERR_TYPE		VARCHAR2(1 CHAR) NULL, 
							ODI_ERR_MESS		VARCHAR2(250 CHAR) NULL,
							ODI_CHECK_DATE	DATE NULL, 
							SHIPMENT_OID	NUMBER NULL,
							SHIPMENT_NO	VARCHAR2(40) NULL,
							SHIP_DATE	DATE NULL,
							SORT_TYPE	VARCHAR2(10) NULL,
							ROOM_BOARD_URL	VARCHAR2(100) NULL,
							ROOM_BOARD_ITEM_ID	VARCHAR2(5) NULL,
							SHIP_NODE	VARCHAR2(100) NULL,
							TRACKING_NO	VARCHAR2(40) NULL,
							STATUS	VARCHAR2(15) NULL,
							ACTUAL_SHIPMENT_DATE	DATE NULL,
							ACTUAL_DELIVERY_DATE	DATE NULL,
							PERSON_INFO_OID	NUMBER NULL,
							ODS_CREATE_DATE	DATE NULL,
							ODS_MODIFY_DATE	DATE NULL,
							SOURCE_SYSTEM_OID	NUMBER NULL,
							SHIP_VIA	VARCHAR2(35) NULL,
							TOTAL_ACTUAL_CHARGE	NUMBER NULL,
							ACTUAL_FREIGHT_CHARGE	NUMBER NULL,
							WO_BATCH_ID	VARCHAR2(40) NULL,
							SHIP_MODE	VARCHAR2(40) NULL,
							SCAC	CHAR(24) NULL,
							CARRIER_SERVICE_CODE	VARCHAR2(40) NULL,
							REQUESTED_CARRIER_SERVICE_CODE	VARCHAR2(40) NULL,
							TOTAL_WEIGHT	NUMBER(14,4) NULL,
							TOTAL_VOLUME	NUMBER(14,4) NULL,
							TOTAL_VOLUME_UOM	VARCHAR2(40) NULL,
							TOTAL_QUANTITY	NUMBER(14,4) NULL,
							NUM_OF_PALLETS	NUMBER(5) NULL,
							NUM_OF_CARTONS	NUMBER(5) NULL,
							CARRIER_TYPE	VARCHAR2(40) NULL,
							ORDER_TYPE	VARCHAR2(20) NULL,
							SHIPMENT_CONFIRM_UPDATES_DONE	CHAR(1) NULL,
							SHIPMENT_CLOSED_FLAG	VARCHAR2(40) NULL,
							ENTERPRISE_CODE	VARCHAR2(40) NULL,
							TOTAL_UOM	CHAR(24) NULL,
							CONFIRMED_QUANTITY	NUMBER(14,4) NULL,
							EXTN_ACCOUNT_NAME	VARCHAR2(40) NULL,
							FROM_ADDRESS_KEY	CHAR(24) NULL,
							TO_ADDRESS_KEY	CHAR(24) NULL,
							ODI_ORIGIN		VARCHAR2(100 CHAR) NULL,
							ODI_CONS_NAME	VARCHAR2(35 CHAR) NULL,
							ODI_CONS_TYPE		VARCHAR2(2 CHAR) NULL,
							ODI_PK			VARCHAR2(32 CHAR) PRIMARY KEY,
							ODI_SESS_NO		VARCHAR2(19 CHAR)
						)';  
EXCEPTION  
   WHEN OTHERS THEN  
      IF SQLCODE != -955 THEN  
         RAISE;  
      END IF;  
END;



&


/*-----------------------------------------------*/
/* TASK No. 32 */
/* delete previous errors */

delete from 	RAX_APP_USER.E$_SHIPMENT60001
where	(ODI_ERR_TYPE = 'S'	and 'F' = 'S')
or	(ODI_ERR_TYPE = 'F'	and ODI_ORIGIN = '(60001)ODS_Project.LOAD_SHIPMENT_INT')


&


/*-----------------------------------------------*/
/* TASK No. 33 */
/* Create index on PK */

 
/* FLOW CONTROL CREATE THE iNDEX ON THE I$TABLE */
BEGIN  
   EXECUTE IMMEDIATE 'create index 	RAX_APP_USER.I$_SHIPMENT60001 on RAX_APP_USER.I$_SHIPMENT60001 (SHIPMENT_OID)';  
EXCEPTION  
   WHEN OTHERS THEN  
      IF SQLCODE != -955 and SQLCODE != -01408 THEN  
         RAISE;  
      END IF;  
END;


&


/*-----------------------------------------------*/
/* TASK No. 34 */
/* insert PK errors */

DECLARE
               CheckTable                             VarChar2(60);
               TargetTable                            VarChar2(60);
               VariableCheckTable                     VarChar2(60);

BEGIN
               SELECT 'RAX_APP_USER.I$_SHIPMENT' INTO CheckTable FROM DUAL;
               SELECT 'ODS_OWN.SHIPMENT' INTO TargetTable FROM DUAL;

IF CheckTable = TargetTable THEN
   VariableCheckTable := CheckTable; 
ELSE
   VariableCheckTable := CheckTable || '60001';
END IF;

execute immediate '
insert into RAX_APP_USER.E$_SHIPMENT60001
(
	ODI_PK,
	ODI_SESS_NO,
	ODI_ROW_ID,
	ODI_ERR_TYPE,
	ODI_ERR_MESS,
	ODI_ORIGIN,
	ODI_CHECK_DATE,
	ODI_CONS_NAME,
	ODI_CONS_TYPE,
	SHIPMENT_OID,
	SHIPMENT_NO,
	SHIP_DATE,
	SHIP_NODE,
	TRACKING_NO,
	STATUS,
	ACTUAL_SHIPMENT_DATE,
	ACTUAL_DELIVERY_DATE,
	PERSON_INFO_OID,
	ODS_CREATE_DATE,
	ODS_MODIFY_DATE,
	SOURCE_SYSTEM_OID,
	SHIP_VIA,
	TOTAL_ACTUAL_CHARGE,
	ACTUAL_FREIGHT_CHARGE,
	WO_BATCH_ID,
	SHIP_MODE,
	SCAC,
	CARRIER_SERVICE_CODE,
	REQUESTED_CARRIER_SERVICE_CODE,
	TOTAL_WEIGHT,
	TOTAL_VOLUME,
	TOTAL_VOLUME_UOM,
	TOTAL_QUANTITY,
	NUM_OF_PALLETS,
	NUM_OF_CARTONS,
	CARRIER_TYPE,
	ORDER_TYPE,
	SHIPMENT_CONFIRM_UPDATES_DONE,
	SHIPMENT_CLOSED_FLAG,
	ENTERPRISE_CODE,
	EXTN_ACCOUNT_NAME,
	FROM_ADDRESS_KEY,
	TO_ADDRESS_KEY
)
select	SYS_GUID(),
	:v_sess_no, 
	rowid,
	''F'', 
	''ODI-15064: The primary key SHIPMENT_PK is not unique.'',
	''(60001)ODS_Project.LOAD_SHIPMENT_INT'',
	sysdate,
	''SHIPMENT_PK'',
	''PK'',	
	SHIPMENT.SHIPMENT_OID,
	SHIPMENT.SHIPMENT_NO,
	SHIPMENT.SHIP_DATE,
	SHIPMENT.SHIP_NODE,
	SHIPMENT.TRACKING_NO,
	SHIPMENT.STATUS,
	SHIPMENT.ACTUAL_SHIPMENT_DATE,
	SHIPMENT.ACTUAL_DELIVERY_DATE,
	SHIPMENT.PERSON_INFO_OID,
	SHIPMENT.ODS_CREATE_DATE,
	SHIPMENT.ODS_MODIFY_DATE,
	SHIPMENT.SOURCE_SYSTEM_OID,
	SHIPMENT.SHIP_VIA,
	SHIPMENT.TOTAL_ACTUAL_CHARGE,
	SHIPMENT.ACTUAL_FREIGHT_CHARGE,
	SHIPMENT.WO_BATCH_ID,
	SHIPMENT.SHIP_MODE,
	SHIPMENT.SCAC,
	SHIPMENT.CARRIER_SERVICE_CODE,
	SHIPMENT.REQUESTED_CARRIER_SERVICE_CODE,
	SHIPMENT.TOTAL_WEIGHT,
	SHIPMENT.TOTAL_VOLUME,
	SHIPMENT.TOTAL_VOLUME_UOM,
	SHIPMENT.TOTAL_QUANTITY,
	SHIPMENT.NUM_OF_PALLETS,
	SHIPMENT.NUM_OF_CARTONS,
	SHIPMENT.CARRIER_TYPE,
	SHIPMENT.ORDER_TYPE,
	SHIPMENT.SHIPMENT_CONFIRM_UPDATES_DONE,
	SHIPMENT.SHIPMENT_CLOSED_FLAG,
	SHIPMENT.ENTERPRISE_CODE,
	SHIPMENT.EXTN_ACCOUNT_NAME,
	SHIPMENT.FROM_ADDRESS_KEY,
	SHIPMENT.TO_ADDRESS_KEY
from	'
 || VariableCheckTable || 
' SHIPMENT 
where	exists  (
		select	SUB1.SHIPMENT_OID
		from 	' 
|| VariableCheckTable ||
'  SUB1
		where 	SUB1.SHIPMENT_OID=SHIPMENT.SHIPMENT_OID
		group by 	SUB1.SHIPMENT_OID
		having 	count(1) > 1
		)
';

END;


&


/*-----------------------------------------------*/
/* TASK No. 35 */
/* Create index on AK */

 
/* FLOW CONTROL CREATE THE iNDEX ON THE I$TABLE */
BEGIN  
   EXECUTE IMMEDIATE 'create index 	SHIPMENT_PKX_flow on RAX_APP_USER.I$_SHIPMENT60001 (SHIPMENT_OID)';  
EXCEPTION  
   WHEN OTHERS THEN  
      IF SQLCODE != -955 and SQLCODE != -01408 THEN  
         RAISE;  
      END IF;  
END;


&


/*-----------------------------------------------*/
/* TASK No. 36 */
/* insert AK errors */

DECLARE
               CheckTable                             VarChar2(60);
               TargetTable                            VarChar2(60);
               VariableCheckTable                VarChar2(60);

BEGIN
               SELECT 'RAX_APP_USER.I$_SHIPMENT' INTO CheckTable FROM DUAL;
               SELECT 'ODS_OWN.SHIPMENT' INTO TargetTable FROM DUAL;

IF CheckTable = TargetTable THEN
   VariableCheckTable := CheckTable; 
ELSE
   VariableCheckTable := CheckTable || '60001';
END IF;

execute immediate '
insert into RAX_APP_USER.E$_SHIPMENT60001
(
	ODI_PK,
	ODI_SESS_NO,
	ODI_ROW_ID,
	ODI_ERR_TYPE,
	ODI_ERR_MESS,
	ODI_ORIGIN,
	ODI_CHECK_DATE,
	ODI_CONS_NAME,
	ODI_CONS_TYPE,
	SHIPMENT_OID,
	SHIPMENT_NO,
	SHIP_DATE,
	SHIP_NODE,
	TRACKING_NO,
	STATUS,
	ACTUAL_SHIPMENT_DATE,
	ACTUAL_DELIVERY_DATE,
	PERSON_INFO_OID,
	ODS_CREATE_DATE,
	ODS_MODIFY_DATE,
	SOURCE_SYSTEM_OID,
	SHIP_VIA,
	TOTAL_ACTUAL_CHARGE,
	ACTUAL_FREIGHT_CHARGE,
	WO_BATCH_ID,
	SHIP_MODE,
	SCAC,
	CARRIER_SERVICE_CODE,
	REQUESTED_CARRIER_SERVICE_CODE,
	TOTAL_WEIGHT,
	TOTAL_VOLUME,
	TOTAL_VOLUME_UOM,
	TOTAL_QUANTITY,
	NUM_OF_PALLETS,
	NUM_OF_CARTONS,
	CARRIER_TYPE,
	ORDER_TYPE,
	SHIPMENT_CONFIRM_UPDATES_DONE,
	SHIPMENT_CLOSED_FLAG,
	ENTERPRISE_CODE,
	EXTN_ACCOUNT_NAME,
	FROM_ADDRESS_KEY,
	TO_ADDRESS_KEY
)
select	SYS_GUID(),
	:v_sess_no, 
	rowid,
	''F'', 
	''ODI-15063: The alternate key SHIPMENT_PKX is not unique.'',
	''(60001)ODS_Project.LOAD_SHIPMENT_INT'',
	sysdate,
	''SHIPMENT_PKX'',
	''AK'',	
	SHIPMENT.SHIPMENT_OID,
	SHIPMENT.SHIPMENT_NO,
	SHIPMENT.SHIP_DATE,
	SHIPMENT.SHIP_NODE,
	SHIPMENT.TRACKING_NO,
	SHIPMENT.STATUS,
	SHIPMENT.ACTUAL_SHIPMENT_DATE,
	SHIPMENT.ACTUAL_DELIVERY_DATE,
	SHIPMENT.PERSON_INFO_OID,
	SHIPMENT.ODS_CREATE_DATE,
	SHIPMENT.ODS_MODIFY_DATE,
	SHIPMENT.SOURCE_SYSTEM_OID,
	SHIPMENT.SHIP_VIA,
	SHIPMENT.TOTAL_ACTUAL_CHARGE,
	SHIPMENT.ACTUAL_FREIGHT_CHARGE,
	SHIPMENT.WO_BATCH_ID,
	SHIPMENT.SHIP_MODE,
	SHIPMENT.SCAC,
	SHIPMENT.CARRIER_SERVICE_CODE,
	SHIPMENT.REQUESTED_CARRIER_SERVICE_CODE,
	SHIPMENT.TOTAL_WEIGHT,
	SHIPMENT.TOTAL_VOLUME,
	SHIPMENT.TOTAL_VOLUME_UOM,
	SHIPMENT.TOTAL_QUANTITY,
	SHIPMENT.NUM_OF_PALLETS,
	SHIPMENT.NUM_OF_CARTONS,
	SHIPMENT.CARRIER_TYPE,
	SHIPMENT.ORDER_TYPE,
	SHIPMENT.SHIPMENT_CONFIRM_UPDATES_DONE,
	SHIPMENT.SHIPMENT_CLOSED_FLAG,
	SHIPMENT.ENTERPRISE_CODE,
	SHIPMENT.EXTN_ACCOUNT_NAME,
	SHIPMENT.FROM_ADDRESS_KEY,
	SHIPMENT.TO_ADDRESS_KEY
from              '	
 || VariableCheckTable || 
' SHIPMENT
where	exists  (
		select	SUB.SHIPMENT_OID
		from 	'
 || VariableCheckTable || 
' SUB
		where 	SUB.SHIPMENT_OID=SHIPMENT.SHIPMENT_OID
		group by 	SUB.SHIPMENT_OID
		having 	count(1) > 1
		)
 ';

END;

/*  Checked Datastore =RAX_APP_USER.I$_SHIPMENT  */
/*  Integration Datastore =RAX_APP_USER.I$_SHIPMENT   */
/*  Target Datastore =ODS_OWN.SHIPMENT */



&


/*-----------------------------------------------*/
/* TASK No. 37 */
/* insert FK errors */

DECLARE
               CheckTable                             VarChar2(60);
               TargetTable                            VarChar2(60);
               VariableCheckTable                VarChar2(60);

BEGIN
               SELECT 'RAX_APP_USER.I$_SHIPMENT' INTO CheckTable FROM DUAL;
               SELECT 'ODS_OWN.SHIPMENT' INTO TargetTable FROM DUAL;

IF CheckTable = TargetTable THEN
   VariableCheckTable := CheckTable; 
ELSE
   VariableCheckTable := CheckTable || '60001';
END IF;

execute immediate '
insert into RAX_APP_USER.E$_SHIPMENT60001
(
	ODI_PK,
	ODI_SESS_NO,
	ODI_ROW_ID,
	ODI_ERR_TYPE,
	ODI_ERR_MESS,
	ODI_CHECK_DATE,
	ODI_ORIGIN,
	ODI_CONS_NAME,
	ODI_CONS_TYPE,
	SHIPMENT_OID,
	SHIPMENT_NO,
	SHIP_DATE,
	SHIP_NODE,
	TRACKING_NO,
	STATUS,
	ACTUAL_SHIPMENT_DATE,
	ACTUAL_DELIVERY_DATE,
	PERSON_INFO_OID,
	ODS_CREATE_DATE,
	ODS_MODIFY_DATE,
	SOURCE_SYSTEM_OID,
	SHIP_VIA,
	TOTAL_ACTUAL_CHARGE,
	ACTUAL_FREIGHT_CHARGE,
	WO_BATCH_ID,
	SHIP_MODE,
	SCAC,
	CARRIER_SERVICE_CODE,
	REQUESTED_CARRIER_SERVICE_CODE,
	TOTAL_WEIGHT,
	TOTAL_VOLUME,
	TOTAL_VOLUME_UOM,
	TOTAL_QUANTITY,
	NUM_OF_PALLETS,
	NUM_OF_CARTONS,
	CARRIER_TYPE,
	ORDER_TYPE,
	SHIPMENT_CONFIRM_UPDATES_DONE,
	SHIPMENT_CLOSED_FLAG,
	ENTERPRISE_CODE,
	EXTN_ACCOUNT_NAME,
	FROM_ADDRESS_KEY,
	TO_ADDRESS_KEY
)
select	SYS_GUID(),
	:v_sess_no, 
	rowid,
	''F'', 
	''ODI-15065: Join error (SHIP_TO_ADDRESS) between the table SHIPMENT and the table PERSON_INFO.'',
	sysdate,
	''(60001)ODS_Project.LOAD_SHIPMENT_INT'',
	''SHIP_TO_ADDRESS'',
	''FK'',	
	SHIPMENT_OID,
	SHIPMENT_NO,
	SHIP_DATE,
	SHIP_NODE,
	TRACKING_NO,
	STATUS,
	ACTUAL_SHIPMENT_DATE,
	ACTUAL_DELIVERY_DATE,
	PERSON_INFO_OID,
	ODS_CREATE_DATE,
	ODS_MODIFY_DATE,
	SOURCE_SYSTEM_OID,
	SHIP_VIA,
	TOTAL_ACTUAL_CHARGE,
	ACTUAL_FREIGHT_CHARGE,
	WO_BATCH_ID,
	SHIP_MODE,
	SCAC,
	CARRIER_SERVICE_CODE,
	REQUESTED_CARRIER_SERVICE_CODE,
	TOTAL_WEIGHT,
	TOTAL_VOLUME,
	TOTAL_VOLUME_UOM,
	TOTAL_QUANTITY,
	NUM_OF_PALLETS,
	NUM_OF_CARTONS,
	CARRIER_TYPE,
	ORDER_TYPE,
	SHIPMENT_CONFIRM_UPDATES_DONE,
	SHIPMENT_CLOSED_FLAG,
	ENTERPRISE_CODE,
	EXTN_ACCOUNT_NAME,
	FROM_ADDRESS_KEY,
	TO_ADDRESS_KEY

from	'
 || VariableCheckTable || 
' SHIPMENT 
where 	(
		SHIPMENT.PERSON_INFO_OID 
	) not in 	(
		select 	PERSON_INFO_OID
		from 	ODS_OWN.PERSON_INFO
		)
and	(
		SHIPMENT.PERSON_INFO_OID is not null 
	)

';

END;

/*  Checked Datastore =RAX_APP_USER.I$_SHIPMENT  */
/*  Integration Datastore =RAX_APP_USER.I$_SHIPMENT   */
/*  Target Datastore =ODS_OWN.SHIPMENT */


&


/*-----------------------------------------------*/
/* TASK No. 38 */
/* insert Not Null errors */

insert into RAX_APP_USER.E$_SHIPMENT60001
(
	ODI_PK,
	ODI_SESS_NO,
	ODI_ROW_ID,
	ODI_ERR_TYPE,
	ODI_ERR_MESS,
	ODI_CHECK_DATE,
	ODI_ORIGIN,
	ODI_CONS_NAME,
	ODI_CONS_TYPE,
	SHIPMENT_OID,
	SHIPMENT_NO,
	SHIP_DATE,
	SHIP_NODE,
	TRACKING_NO,
	STATUS,
	ACTUAL_SHIPMENT_DATE,
	ACTUAL_DELIVERY_DATE,
	PERSON_INFO_OID,
	ODS_CREATE_DATE,
	ODS_MODIFY_DATE,
	SOURCE_SYSTEM_OID,
	SHIP_VIA,
	TOTAL_ACTUAL_CHARGE,
	ACTUAL_FREIGHT_CHARGE,
	WO_BATCH_ID,
	SHIP_MODE,
	SCAC,
	CARRIER_SERVICE_CODE,
	REQUESTED_CARRIER_SERVICE_CODE,
	TOTAL_WEIGHT,
	TOTAL_VOLUME,
	TOTAL_VOLUME_UOM,
	TOTAL_QUANTITY,
	NUM_OF_PALLETS,
	NUM_OF_CARTONS,
	CARRIER_TYPE,
	ORDER_TYPE,
	SHIPMENT_CONFIRM_UPDATES_DONE,
	SHIPMENT_CLOSED_FLAG,
	ENTERPRISE_CODE,
	EXTN_ACCOUNT_NAME,
	FROM_ADDRESS_KEY,
	TO_ADDRESS_KEY
)
select
	SYS_GUID(),
	:v_sess_no, 
	rowid,
	'F', 
	'ODI-15066: The column SHIPMENT_OID cannot be null.',
	sysdate,
	'(60001)ODS_Project.LOAD_SHIPMENT_INT',
	'SHIPMENT_OID',
	'NN',	
	SHIPMENT_OID,
	SHIPMENT_NO,
	SHIP_DATE,
	SHIP_NODE,
	TRACKING_NO,
	STATUS,
	ACTUAL_SHIPMENT_DATE,
	ACTUAL_DELIVERY_DATE,
	PERSON_INFO_OID,
	ODS_CREATE_DATE,
	ODS_MODIFY_DATE,
	SOURCE_SYSTEM_OID,
	SHIP_VIA,
	TOTAL_ACTUAL_CHARGE,
	ACTUAL_FREIGHT_CHARGE,
	WO_BATCH_ID,
	SHIP_MODE,
	SCAC,
	CARRIER_SERVICE_CODE,
	REQUESTED_CARRIER_SERVICE_CODE,
	TOTAL_WEIGHT,
	TOTAL_VOLUME,
	TOTAL_VOLUME_UOM,
	TOTAL_QUANTITY,
	NUM_OF_PALLETS,
	NUM_OF_CARTONS,
	CARRIER_TYPE,
	ORDER_TYPE,
	SHIPMENT_CONFIRM_UPDATES_DONE,
	SHIPMENT_CLOSED_FLAG,
	ENTERPRISE_CODE,
	EXTN_ACCOUNT_NAME,
	FROM_ADDRESS_KEY,
	TO_ADDRESS_KEY
from	RAX_APP_USER.I$_SHIPMENT60001
where	SHIPMENT_OID is null



&


/*-----------------------------------------------*/
/* TASK No. 39 */
/* insert Not Null errors */

insert into RAX_APP_USER.E$_SHIPMENT60001
(
	ODI_PK,
	ODI_SESS_NO,
	ODI_ROW_ID,
	ODI_ERR_TYPE,
	ODI_ERR_MESS,
	ODI_CHECK_DATE,
	ODI_ORIGIN,
	ODI_CONS_NAME,
	ODI_CONS_TYPE,
	SHIPMENT_OID,
	SHIPMENT_NO,
	SHIP_DATE,
	SHIP_NODE,
	TRACKING_NO,
	STATUS,
	ACTUAL_SHIPMENT_DATE,
	ACTUAL_DELIVERY_DATE,
	PERSON_INFO_OID,
	ODS_CREATE_DATE,
	ODS_MODIFY_DATE,
	SOURCE_SYSTEM_OID,
	SHIP_VIA,
	TOTAL_ACTUAL_CHARGE,
	ACTUAL_FREIGHT_CHARGE,
	WO_BATCH_ID,
	SHIP_MODE,
	SCAC,
	CARRIER_SERVICE_CODE,
	REQUESTED_CARRIER_SERVICE_CODE,
	TOTAL_WEIGHT,
	TOTAL_VOLUME,
	TOTAL_VOLUME_UOM,
	TOTAL_QUANTITY,
	NUM_OF_PALLETS,
	NUM_OF_CARTONS,
	CARRIER_TYPE,
	ORDER_TYPE,
	SHIPMENT_CONFIRM_UPDATES_DONE,
	SHIPMENT_CLOSED_FLAG,
	ENTERPRISE_CODE,
	EXTN_ACCOUNT_NAME,
	FROM_ADDRESS_KEY,
	TO_ADDRESS_KEY
)
select
	SYS_GUID(),
	:v_sess_no, 
	rowid,
	'F', 
	'ODI-15066: The column PERSON_INFO_OID cannot be null.',
	sysdate,
	'(60001)ODS_Project.LOAD_SHIPMENT_INT',
	'PERSON_INFO_OID',
	'NN',	
	SHIPMENT_OID,
	SHIPMENT_NO,
	SHIP_DATE,
	SHIP_NODE,
	TRACKING_NO,
	STATUS,
	ACTUAL_SHIPMENT_DATE,
	ACTUAL_DELIVERY_DATE,
	PERSON_INFO_OID,
	ODS_CREATE_DATE,
	ODS_MODIFY_DATE,
	SOURCE_SYSTEM_OID,
	SHIP_VIA,
	TOTAL_ACTUAL_CHARGE,
	ACTUAL_FREIGHT_CHARGE,
	WO_BATCH_ID,
	SHIP_MODE,
	SCAC,
	CARRIER_SERVICE_CODE,
	REQUESTED_CARRIER_SERVICE_CODE,
	TOTAL_WEIGHT,
	TOTAL_VOLUME,
	TOTAL_VOLUME_UOM,
	TOTAL_QUANTITY,
	NUM_OF_PALLETS,
	NUM_OF_CARTONS,
	CARRIER_TYPE,
	ORDER_TYPE,
	SHIPMENT_CONFIRM_UPDATES_DONE,
	SHIPMENT_CLOSED_FLAG,
	ENTERPRISE_CODE,
	EXTN_ACCOUNT_NAME,
	FROM_ADDRESS_KEY,
	TO_ADDRESS_KEY
from	RAX_APP_USER.I$_SHIPMENT60001
where	PERSON_INFO_OID is null



&


/*-----------------------------------------------*/
/* TASK No. 40 */
/* create index on error table */

 
/* FLOW CONTROL CREATE INDEX ON THE E$TABLE */
BEGIN  
   EXECUTE IMMEDIATE 'create index 	RAX_APP_USER.E$_SHIPMENT60001 on RAX_APP_USER.E$_SHIPMENT60001 (ODI_ROW_ID)';  
EXCEPTION  
   WHEN OTHERS THEN  
      IF SQLCODE != -955 and SQLCODE != -01408 THEN  
         RAISE;  
      END IF;  
END;


&


/*-----------------------------------------------*/
/* TASK No. 41 */
/* delete errors from controlled table */

delete from	RAX_APP_USER.I$_SHIPMENT60001  T
where	exists 	(
		select	1
		from	RAX_APP_USER.E$_SHIPMENT60001 E
		where ODI_SESS_NO = :v_sess_no
		and T.rowid = E.ODI_ROW_ID
		)


&


/*-----------------------------------------------*/
/* TASK No. 42 */
/* insert check sum into check table */

insert into RAX_APP_USER.SNP_CHECK_TAB
(
	SCHEMA_NAME,
	RESOURCE_NAME,
	FULL_RES_NAME,
	ERR_TYPE,
	ERR_MESS,
	CHECK_DATE,
	ORIGIN,
	CONS_NAME,
	CONS_TYPE,
	ERR_COUNT
)
select	
	'ODS_OWN',
	'SHIPMENT',
	'ODS_OWN.SHIPMENT60001',
	E.ODI_ERR_TYPE,
	E.ODI_ERR_MESS,
	E.ODI_CHECK_DATE,
	E.ODI_ORIGIN,
	E.ODI_CONS_NAME,
	E.ODI_CONS_TYPE,
	count(1) 
from	RAX_APP_USER.E$_SHIPMENT60001 E
where	E.ODI_ERR_TYPE	= 'F'
and	E.ODI_ORIGIN 	= '(60001)ODS_Project.LOAD_SHIPMENT_INT'
group by	E.ODI_ERR_TYPE,
	E.ODI_ERR_MESS,
	E.ODI_CHECK_DATE,
	E.ODI_ORIGIN,
	E.ODI_CONS_NAME,
	E.ODI_CONS_TYPE


&


/*-----------------------------------------------*/
/* TASK No. 43 */
/* Merge Rows */

merge into	ODS_OWN.SHIPMENT T
using	RAX_APP_USER.I$_SHIPMENT60001 S
on	(
		T.SHIPMENT_OID=S.SHIPMENT_OID
	)
when matched
then update set
	T.SHIPMENT_NO	= S.SHIPMENT_NO,
	T.SHIP_DATE	= S.SHIP_DATE,
	T.SHIP_NODE	= S.SHIP_NODE,
	T.TRACKING_NO	= S.TRACKING_NO,
	T.STATUS	= S.STATUS,
	T.ACTUAL_SHIPMENT_DATE	= S.ACTUAL_SHIPMENT_DATE,
	T.ACTUAL_DELIVERY_DATE	= S.ACTUAL_DELIVERY_DATE,
	T.PERSON_INFO_OID	= S.PERSON_INFO_OID,
	T.SOURCE_SYSTEM_OID	= S.SOURCE_SYSTEM_OID,
	T.SHIP_VIA	= S.SHIP_VIA,
	T.TOTAL_ACTUAL_CHARGE	= S.TOTAL_ACTUAL_CHARGE,
	T.ACTUAL_FREIGHT_CHARGE	= S.ACTUAL_FREIGHT_CHARGE,
	T.WO_BATCH_ID	= S.WO_BATCH_ID,
	T.SHIP_MODE	= S.SHIP_MODE,
	T.SCAC	= S.SCAC,
	T.CARRIER_SERVICE_CODE	= S.CARRIER_SERVICE_CODE,
	T.REQUESTED_CARRIER_SERVICE_CODE	= S.REQUESTED_CARRIER_SERVICE_CODE,
	T.TOTAL_WEIGHT	= S.TOTAL_WEIGHT,
	T.TOTAL_VOLUME	= S.TOTAL_VOLUME,
	T.TOTAL_VOLUME_UOM	= S.TOTAL_VOLUME_UOM,
	T.TOTAL_QUANTITY	= S.TOTAL_QUANTITY,
	T.NUM_OF_PALLETS	= S.NUM_OF_PALLETS,
	T.NUM_OF_CARTONS	= S.NUM_OF_CARTONS,
	T.CARRIER_TYPE	= S.CARRIER_TYPE,
	T.ORDER_TYPE	= S.ORDER_TYPE,
	T.SHIPMENT_CONFIRM_UPDATES_DONE	= S.SHIPMENT_CONFIRM_UPDATES_DONE,
	T.SHIPMENT_CLOSED_FLAG	= S.SHIPMENT_CLOSED_FLAG,
	T.ENTERPRISE_CODE	= S.ENTERPRISE_CODE,
	T.EXTN_ACCOUNT_NAME	= S.EXTN_ACCOUNT_NAME,
	T.FROM_ADDRESS_KEY	= S.FROM_ADDRESS_KEY,
	T.TO_ADDRESS_KEY	= S.TO_ADDRESS_KEY
	,                               T.ODS_MODIFY_DATE	= SYSDATE
when not matched
then insert
	(
	T.SHIPMENT_OID,
	T.SHIPMENT_NO,
	T.SHIP_DATE,
	T.SHIP_NODE,
	T.TRACKING_NO,
	T.STATUS,
	T.ACTUAL_SHIPMENT_DATE,
	T.ACTUAL_DELIVERY_DATE,
	T.PERSON_INFO_OID,
	T.SOURCE_SYSTEM_OID,
	T.SHIP_VIA,
	T.TOTAL_ACTUAL_CHARGE,
	T.ACTUAL_FREIGHT_CHARGE,
	T.WO_BATCH_ID,
	T.SHIP_MODE,
	T.SCAC,
	T.CARRIER_SERVICE_CODE,
	T.REQUESTED_CARRIER_SERVICE_CODE,
	T.TOTAL_WEIGHT,
	T.TOTAL_VOLUME,
	T.TOTAL_VOLUME_UOM,
	T.TOTAL_QUANTITY,
	T.NUM_OF_PALLETS,
	T.NUM_OF_CARTONS,
	T.CARRIER_TYPE,
	T.ORDER_TYPE,
	T.SHIPMENT_CONFIRM_UPDATES_DONE,
	T.SHIPMENT_CLOSED_FLAG,
	T.ENTERPRISE_CODE,
	T.EXTN_ACCOUNT_NAME,
	T.FROM_ADDRESS_KEY,
	T.TO_ADDRESS_KEY
	,                                T.ODS_CREATE_DATE,
	T.ODS_MODIFY_DATE
	)
values
	(
	S.SHIPMENT_OID,
	S.SHIPMENT_NO,
	S.SHIP_DATE,
	S.SHIP_NODE,
	S.TRACKING_NO,
	S.STATUS,
	S.ACTUAL_SHIPMENT_DATE,
	S.ACTUAL_DELIVERY_DATE,
	S.PERSON_INFO_OID,
	S.SOURCE_SYSTEM_OID,
	S.SHIP_VIA,
	S.TOTAL_ACTUAL_CHARGE,
	S.ACTUAL_FREIGHT_CHARGE,
	S.WO_BATCH_ID,
	S.SHIP_MODE,
	S.SCAC,
	S.CARRIER_SERVICE_CODE,
	S.REQUESTED_CARRIER_SERVICE_CODE,
	S.TOTAL_WEIGHT,
	S.TOTAL_VOLUME,
	S.TOTAL_VOLUME_UOM,
	S.TOTAL_QUANTITY,
	S.NUM_OF_PALLETS,
	S.NUM_OF_CARTONS,
	S.CARRIER_TYPE,
	S.ORDER_TYPE,
	S.SHIPMENT_CONFIRM_UPDATES_DONE,
	S.SHIPMENT_CLOSED_FLAG,
	S.ENTERPRISE_CODE,
	S.EXTN_ACCOUNT_NAME,
	S.FROM_ADDRESS_KEY,
	S.TO_ADDRESS_KEY
	,                                SYSDATE,
	SYSDATE
	)

&


/*-----------------------------------------------*/
/* TASK No. 44 */
/* Commit transaction */

/*commit*/


/*-----------------------------------------------*/
/* TASK No. 45 */
/* Drop flow table */

drop table RAX_APP_USER.I$_SHIPMENT60001 

&


/*-----------------------------------------------*/
/* TASK No. 46 */
/* Update CDC Load Status */

UPDATE ODS_OWN.ODS_CDC_LOAD_STATUS
SET LAST_CDC_COMPLETION_DATE=TO_DATE(
             SUBSTR(:v_sess_beg, 1, 19), 'RRRR-MM-DD HH24:MI:SS')
+ nvl((TIMEZONE_OFFSET/24), 0) 
WHERE ODS_TABLE_NAME=:v_cdc_load_table_name
AND CONTEXT_NAME = :v_env

/*
UPDATE ODS_OWN.ODS_CDC_LOAD_STATUS
SET LAST_CDC_COMPLETION_DATE=TO_DATE(
             SUBSTR(:v_sess_beg, 1, 19), 'RRRR-MM-DD HH24:MI:SS')
WHERE ODS_TABLE_NAME=:v_cdc_load_table_name
AND CONTEXT_NAME = :v_env
*/

&


/*-----------------------------------------------*/
/* TASK No. 47 */
/* Insert CDC Audit Record */

INSERT INTO RAX_APP_USER.ODS_CDC_LOAD_STATUS_AUDIT
(TABLE_NAME,
SESS_NO,                      
SESS_NAME,                    
SCEN_VERSION,                 
SESS_BEG,                     
ORIG_LAST_CDC_COMPLETION_DATE,
OVERLAP,
CREATE_DATE,
CONTEXT_NAME,
TIMEZONE_OFFSET              
)
select 
:v_cdc_load_table_name
,:v_sess_no
,'LOAD_SHIPMENT_PKG'
,'013'
,TO_DATE(SUBSTR(:v_sess_beg, 1, 19), 'RRRR-MM-DD HH24:MI:SS')
,TO_DATE (SUBSTR(:v_cdc_load_date, 1, 19),'YYYY-MM-DD HH24:MI:SS')
,:v_cdc_overlap
,SYSDATE
,:v_env
,TIMEZONE_OFFSET
from 
ODS_OWN.ODS_CDC_LOAD_STATUS
WHERE ODS_TABLE_NAME=:v_cdc_load_table_name
AND CONTEXT_NAME = :v_env

/*
INSERT INTO RAX_APP_USER.ODS_CDC_LOAD_STATUS_AUDIT
(TABLE_NAME,
SESS_NO,                      
SESS_NAME,                    
SCEN_VERSION,                 
SESS_BEG,                     
ORIG_LAST_CDC_COMPLETION_DATE,
OVERLAP,
CREATE_DATE,
CONTEXT_NAME              
)
values (
:v_cdc_load_table_name,
:v_sess_no,
'LOAD_SHIPMENT_PKG',
'013',
TO_DATE(
             SUBSTR(:v_sess_beg, 1, 19), 'RRRR-MM-DD HH24:MI:SS'),
TO_DATE (SUBSTR (:v_cdc_load_date, 1, 19),
                           'YYYY-MM-DD HH24:MI:SS'
                          )
,:v_cdc_overlap,
SYSDATE,
 :v_env)
*/


&


/*-----------------------------------------------*/
