/* TASK No. 1 */

/* NONE or SET VARIABLE STATEMENT FOUND, CHECK ODI TASK NO. 1 */




/*-----------------------------------------------*/
/* TASK No. 2 */

/* SELECT STATEMENT FOUND, CHECK ODI TASK NO. 2 */




/*-----------------------------------------------*/
/* TASK No. 3 */

/* SELECT STATEMENT FOUND, CHECK ODI TASK NO. 3 */




/*-----------------------------------------------*/
/* TASK No. 4 */
/* Drop work table */

-- drop table RAX_APP_USER.C$_0OMS3_LT_APO_STG purge

-- &


-- /*-----------------------------------------------*/
-- /* TASK No. 5 */
-- /* Create work table */

-- create table RAX_APP_USER.C$_0OMS3_LT_APO_STG
-- (
-- 	C1_APO_KEY	VARCHAR2(24) NULL,
-- 	C2_DESCRIPTION	VARCHAR2(100) NULL,
-- 	C3_ACCOUNT_ID	VARCHAR2(15) NULL,
-- 	C4_GRAD_YEAR	NUMBER NULL,
-- 	C5_STATUS	VARCHAR2(10) NULL,
-- 	C6_ACCOUNT_NAME	VARCHAR2(40) NULL,
-- 	C7_PROGRAM_TYPE	VARCHAR2(20) NULL,
-- 	C8_PRICE_PROGRAM_NAME	VARCHAR2(50) NULL,
-- 	C9_PHOTOGRAPHY_LOCATION	VARCHAR2(15) NULL,
-- 	C10_GLOSSIES_REQD	VARCHAR2(1) NULL,
-- 	C11_YEARBOOK_POSE_REQD	VARCHAR2(1) NULL,
-- 	C12_PUBLISHER	VARCHAR2(20) NULL,
-- 	C13_OTHER_PUBLISHER	VARCHAR2(20) NULL,
-- 	C14_SHIP_PROOFS_TO	VARCHAR2(15) NULL,
-- 	C15_SHIP_ORDERS_TO	VARCHAR2(15) NULL,
-- 	C16_SHIP_GLOSSIES_TO	VARCHAR2(15) NULL,
-- 	C17_SHIP_PROOFS_STUDIO_CODE	VARCHAR2(24) NULL,
-- 	C18_SHIP_ORDERS_STUDIO_CODE	VARCHAR2(24) NULL,
-- 	C19_SHIP_GLOSSIES_STUDIO_CODE	VARCHAR2(24) NULL,
-- 	C20_TERRITORY_GROUP_ID	VARCHAR2(80) NULL,
-- 	C21_SHIP_PROOFS_STUDIO_ATTN	VARCHAR2(25) NULL,
-- 	C22_SHIP_ORDERS_STUDIO_ATTN	VARCHAR2(25) NULL,
-- 	C23_SHIP_GLOSSIES_STUDIO_ATTN	VARCHAR2(25) NULL,
-- 	C24_COMMISSION_PER_CUST	NUMBER NULL,
-- 	C25_COMMISSION_PERCENTAGE	NUMBER NULL,
-- 	C26_COMMISSION_GUARANTEED	NUMBER NULL,
-- 	C27_COMMISSION_SPECIAL	NUMBER NULL,
-- 	C28_ORDER_RETURN_MSG_REQD	VARCHAR2(1) NULL,
-- 	C29_ORDER_REMINDER_REQD	VARCHAR2(1) NULL,
-- 	C30_ORDER_ASSIST_REQD	VARCHAR2(1) NULL,
-- 	C31_INCLUDE_ORDER_FORM	VARCHAR2(1) NULL,
-- 	C32_INCLUDE_RETURN_ENVELOPE	VARCHAR2(1) NULL,
-- 	C33_ORDER_BY_PHONE_NO	VARCHAR2(15) NULL,
-- 	C34_ORDER_ENQUIRY_NO	VARCHAR2(15) NULL,
-- 	C35_YEARBOOK_POSESTYLE_1	VARCHAR2(20) NULL,
-- 	C36_YEARBOOK_POSESTYLE_2	VARCHAR2(20) NULL,
-- 	C37_YEARBOOK_POSESTYLE_OTHER1	VARCHAR2(100) NULL,
-- 	C38_YEARBOOK_POSESTYLE_OTHER2	VARCHAR2(100) NULL,
-- 	C39_YEARBOOK_BACKGROUND1	VARCHAR2(20) NULL,
-- 	C40_YEARBOOK_BACKGROUND2	VARCHAR2(20) NULL,
-- 	C41_YEARBOOK_BGROUND_OTHER1	VARCHAR2(100) NULL,
-- 	C42_YEARBOOK_BGROUND_OTHER2	VARCHAR2(100) NULL,
-- 	C43_YEARBOOK_OUTFIT1	VARCHAR2(20) NULL,
-- 	C44_YEARBOOK_OUTFIT2	VARCHAR2(20) NULL,
-- 	C45_YEARBOOK_OUTFIT_OTHER1	VARCHAR2(100) NULL,
-- 	C46_YEARBOOK_OUTFIT_OTHER2	VARCHAR2(100) NULL,
-- 	C47_YEARBOOK_SPL_INST	VARCHAR2(400) NULL,
-- 	C48_GLOSSIES_OUTPUT	VARCHAR2(40) NULL,
-- 	C49_GLOSSIES_PAPER_DEADLINE	DATE NULL,
-- 	C50_GLOSSIES_DEL_DEADLINE	DATE NULL,
-- 	C51_MULTIPLE_IMAGES_OPTION	VARCHAR2(30) NULL,
-- 	C52_PRINTABLE_FRAMES	VARCHAR2(30) NULL,
-- 	C53_TERRITORY_ID	VARCHAR2(24) NULL,
-- 	C54_STUDIO_ID	VARCHAR2(24) NULL,
-- 	C55_PROCESSING_LAB	VARCHAR2(24) NULL,
-- 	C56_PUBLISHER_ADDRESS_LINE1	VARCHAR2(30) NULL,
-- 	C57_PUBLISHER_ADDRESS_LINE2	VARCHAR2(30) NULL,
-- 	C58_PUBLISHER_ADDRESS_LINE3	VARCHAR2(30) NULL,
-- 	C59_PUBLISHER_CITY	VARCHAR2(20) NULL,
-- 	C60_PUBLISHER_STATE	VARCHAR2(15) NULL,
-- 	C61_PUBLISHER_ZIP_CODE	VARCHAR2(10) NULL,
-- 	C62_PUBLISHER_COUNTRY	VARCHAR2(10) NULL,
-- 	C63_PUBLISHER_PHONENO	VARCHAR2(15) NULL,
-- 	C64_PUBLISHER_FAXNO	VARCHAR2(15) NULL,
-- 	C65_PUBLISHER_EMAIL	VARCHAR2(30) NULL,
-- 	C66_PUBLISHER_CONTACT_PERSON	VARCHAR2(30) NULL,
-- 	C67_ACCOUNT_ADDRESS_LINE1	VARCHAR2(30) NULL,
-- 	C68_ACCOUNT_ADDRESS_LINE2	VARCHAR2(30) NULL,
-- 	C69_ACCOUNT_ADDRESS_LINE3	VARCHAR2(30) NULL,
-- 	C70_ACCOUNT_CITY	VARCHAR2(20) NULL,
-- 	C71_ACCOUNT_STATE	VARCHAR2(15) NULL,
-- 	C72_ACCOUNT_ZIP_CODE	VARCHAR2(10) NULL,
-- 	C73_ACCOUNT_COUNTRY	VARCHAR2(10) NULL,
-- 	C74_ACCOUNT_PHONENO	VARCHAR2(15) NULL,
-- 	C75_ACCOUNT_CONTACT_PERSON	VARCHAR2(30) NULL,
-- 	C76_ACCOUNT_FAXNO	VARCHAR2(15) NULL,
-- 	C77_ACCOUNT_EMAIL	VARCHAR2(30) NULL,
-- 	C78_PUBLISHER_ACCT_NO	VARCHAR2(24) NULL,
-- 	C79_VISION_JOB_NO	VARCHAR2(24) NULL,
-- 	C80_CURRENCY	VARCHAR2(10) NULL,
-- 	C81_CREATETS	DATE NULL,
-- 	C82_MODIFYTS	DATE NULL,
-- 	C83_CREATEUSERID	VARCHAR2(40) NULL,
-- 	C84_MODIFYUSERID	VARCHAR2(40) NULL,
-- 	C85_CREATEPROGID	VARCHAR2(40) NULL,
-- 	C86_MODIFYPROGID	VARCHAR2(40) NULL,
-- 	C87_LOCKID	NUMBER NULL,
-- 	C88_APO_ID	VARCHAR2(15) NULL,
-- 	C89_CONFIRMED_PROCESSING_LAB	VARCHAR2(24) NULL,
-- 	C90_PHOTOTRACKER_DEL_DATE	DATE NULL,
-- 	C91_SOLO_ACCESS	VARCHAR2(1) NULL,
-- 	C92_ESTIMATED_ENROLLMENT	NUMBER NULL,
-- 	C93_TERRITORY_NOTES	VARCHAR2(250) NULL,
-- 	C94_SELLER_FOR_ORDER	VARCHAR2(24) NULL,
-- 	C95_LAB_REVISION_NO	NUMBER NULL,
-- 	C96_LAB_NOTES	VARCHAR2(200) NULL,
-- 	C97_BOYS_GOWN_COLOR_1	VARCHAR2(15) NULL,
-- 	C98_BOYS_TASSEL_COLOR_1	VARCHAR2(15) NULL,
-- 	C99_GIRLS_GOWN_COLOR_1	VARCHAR2(15) NULL,
-- 	C100_GIRLS_TASSEL_COLOR_1	VARCHAR2(15) NULL,
-- 	C101_BOYS_GOWN_COLOR_2	VARCHAR2(15) NULL,
-- 	C102_BOYS_TASSEL_COLOR_2	VARCHAR2(15) NULL,
-- 	C103_GIRLS_GOWN_COLOR_2	VARCHAR2(15) NULL,
-- 	C104_GIRLS_TASSEL_COLOR_2	VARCHAR2(15) NULL,
-- 	C105_NO_OF_PROOF_SETS	NUMBER NULL,
-- 	C106_NO_OF_GLOSSY_SETS	NUMBER NULL,
-- 	C107_STUDENT_ID_REQD	VARCHAR2(1) NULL,
-- 	C108_TAX_EXEMPT_CERTIFICATE_NU	VARCHAR2(40) NULL,
-- 	C109_TAX_EXEMPT	VARCHAR2(1) NULL,
-- 	C110_SELECT_ORDER_BY_PHONE_NO	VARCHAR2(15) NULL,
-- 	C111_SELECT_ORDER_ENQUIRY_NO	VARCHAR2(15) NULL,
-- 	C112_IS_PROOF_EXPRESS	VARCHAR2(1) NULL,
-- 	C113_GUARANTEED_DOLLAR_AMOUNT	NUMBER NULL,
-- 	C114_GRAD_ANNOUNCE_POSTER_INS	VARCHAR2(1) NULL,
-- 	C115_CUSTOM_LANGUAGE	VARCHAR2(40) NULL,
-- 	C116_YB_SELECTION_ONLINE	VARCHAR2(1) NULL,
-- 	C117_ORDER_FORM_ITEM_ID	VARCHAR2(40) NULL,
-- 	C118_SUB_PROGRAM_TYPE	VARCHAR2(20) NULL,
-- 	C119_MARKETING_CODE	VARCHAR2(10) NULL,
-- 	C120_FLYER_ID	VARCHAR2(20) NULL,
-- 	C121_SORT_TYPE	VARCHAR2(20) NULL,
-- 	C122_ENVELOPE_TYPE	VARCHAR2(20) NULL,
-- 	C123_VISUAL_MERCH_KEY	VARCHAR2(24) NULL,
-- 	C124_VISUAL_MERCH_ID	VARCHAR2(24) NULL,
-- 	C125_REVISION_NO	NUMBER NULL,
-- 	C126_COMP_PROD_CODE	VARCHAR2(24) NULL,
-- 	C127_COMP_DLVRY_TYPE	VARCHAR2(24) NULL,
-- 	C128_GRP_PROD_CODE	VARCHAR2(24) NULL,
-- 	C129_GRP_DLVRY_TYPE	VARCHAR2(24) NULL,
-- 	C130_MODEL_GRADE	VARCHAR2(20) NULL,
-- 	C131_MODEL_ETHNICITY	VARCHAR2(20) NULL,
-- 	C132_MODEL_GENDER	VARCHAR2(2) NULL,
-- 	C133_SERVICE_CENTER	VARCHAR2(24) NULL,
-- 	C134_EVENT_IMAGE_COMPLETE	VARCHAR2(1) NULL,
-- 	C135_SHIP_TO_ACCOUNT_BUFFER_DA	NUMBER NULL,
-- 	C136_ORIGINAL_ORDER_FORM_DUE_D	NUMBER NULL,
-- 	C137_RETAKE_ORDER_FORM_DUE_DAT	NUMBER NULL,
-- 	C138_EXTERNAL_SYNC_FLAG	VARCHAR2(1) NULL,
-- 	C139_FULFILLING_LAB_SYSTEM	VARCHAR2(24) NULL,
-- 	C140_FINANCIAL_PROCESSING_SYST	VARCHAR2(50) NULL,
-- 	C141_ORIGINAL_BOOKING_REP	VARCHAR2(255) NULL,
-- 	C142_ORIGINAL_BOOKING_REP_NAME	VARCHAR2(255) NULL,
-- 	C143_SHIP_TO_SATELLITE_LOCATIO	VARCHAR2(10) NULL,
-- 	C144_CLASS_PICTURE_RELEASE_DAT	DATE NULL
-- )
-- NOLOGGING

-- &


-- /*-----------------------------------------------*/
-- /* TASK No. 6 */
-- /* Load data */

-- /* SOURCE CODE */


-- select	
-- 	S.APO_KEY	   C1_APO_KEY,
-- 	S.DESCRIPTION	   C2_DESCRIPTION,
-- 	S.ACCOUNT_ID	   C3_ACCOUNT_ID,
-- 	S.GRAD_YEAR	   C4_GRAD_YEAR,
-- 	S.STATUS	   C5_STATUS,
-- 	substr(S.ACCOUNT_NAME,1,40)	   C6_ACCOUNT_NAME,
-- 	S.PROGRAM_TYPE	   C7_PROGRAM_TYPE,
-- 	S.PRICE_PROGRAM_NAME	   C8_PRICE_PROGRAM_NAME,
-- 	S.PHOTOGRAPHY_LOCATION	   C9_PHOTOGRAPHY_LOCATION,
-- 	S.GLOSSIES_REQD	   C10_GLOSSIES_REQD,
-- 	S.YEARBOOK_POSE_REQD	   C11_YEARBOOK_POSE_REQD,
-- 	S.PUBLISHER	   C12_PUBLISHER,
-- 	S.OTHER_PUBLISHER	   C13_OTHER_PUBLISHER,
-- 	S.SHIP_PROOFS_TO	   C14_SHIP_PROOFS_TO,
-- 	S.SHIP_ORDERS_TO	   C15_SHIP_ORDERS_TO,
-- 	S.SHIP_GLOSSIES_TO	   C16_SHIP_GLOSSIES_TO,
-- 	S.SHIP_PROOFS_STUDIO_CODE	   C17_SHIP_PROOFS_STUDIO_CODE,
-- 	S.SHIP_ORDERS_STUDIO_CODE	   C18_SHIP_ORDERS_STUDIO_CODE,
-- 	S.SHIP_GLOSSIES_STUDIO_CODE	   C19_SHIP_GLOSSIES_STUDIO_CODE,
-- 	S.TERRITORY_GROUP_ID	   C20_TERRITORY_GROUP_ID,
-- 	S.SHIP_PROOFS_STUDIO_ATTN	   C21_SHIP_PROOFS_STUDIO_ATTN,
-- 	S.SHIP_ORDERS_STUDIO_ATTN	   C22_SHIP_ORDERS_STUDIO_ATTN,
-- 	S.SHIP_GLOSSIES_STUDIO_ATTN	   C23_SHIP_GLOSSIES_STUDIO_ATTN,
-- 	S.COMMISSION_PER_CUST	   C24_COMMISSION_PER_CUST,
-- 	S.COMMISSION_PERCENTAGE	   C25_COMMISSION_PERCENTAGE,
-- 	S.COMMISSION_GUARANTEED	   C26_COMMISSION_GUARANTEED,
-- 	S.COMMISSION_SPECIAL	   C27_COMMISSION_SPECIAL,
-- 	S.ORDER_RETURN_MSG_REQD	   C28_ORDER_RETURN_MSG_REQD,
-- 	S.ORDER_REMINDER_REQD	   C29_ORDER_REMINDER_REQD,
-- 	S.ORDER_ASSIST_REQD	   C30_ORDER_ASSIST_REQD,
-- 	S.INCLUDE_ORDER_FORM	   C31_INCLUDE_ORDER_FORM,
-- 	S.INCLUDE_RETURN_ENVELOPE	   C32_INCLUDE_RETURN_ENVELOPE,
-- 	S.ORDER_BY_PHONE_NO	   C33_ORDER_BY_PHONE_NO,
-- 	S.ORDER_ENQUIRY_NO	   C34_ORDER_ENQUIRY_NO,
-- 	S.YEARBOOK_POSESTYLE_1	   C35_YEARBOOK_POSESTYLE_1,
-- 	S.YEARBOOK_POSESTYLE_2	   C36_YEARBOOK_POSESTYLE_2,
-- 	S.YEARBOOK_POSESTYLE_OTHER1	   C37_YEARBOOK_POSESTYLE_OTHER1,
-- 	S.YEARBOOK_POSESTYLE_OTHER2	   C38_YEARBOOK_POSESTYLE_OTHER2,
-- 	S.YEARBOOK_BACKGROUND1	   C39_YEARBOOK_BACKGROUND1,
-- 	S.YEARBOOK_BACKGROUND2	   C40_YEARBOOK_BACKGROUND2,
-- 	S.YEARBOOK_BGROUND_OTHER1	   C41_YEARBOOK_BGROUND_OTHER1,
-- 	S.YEARBOOK_BGROUND_OTHER2	   C42_YEARBOOK_BGROUND_OTHER2,
-- 	S.YEARBOOK_OUTFIT1	   C43_YEARBOOK_OUTFIT1,
-- 	S.YEARBOOK_OUTFIT2	   C44_YEARBOOK_OUTFIT2,
-- 	S.YEARBOOK_OUTFIT_OTHER1	   C45_YEARBOOK_OUTFIT_OTHER1,
-- 	S.YEARBOOK_OUTFIT_OTHER2	   C46_YEARBOOK_OUTFIT_OTHER2,
-- 	S.YEARBOOK_SPL_INST	   C47_YEARBOOK_SPL_INST,
-- 	S.GLOSSIES_OUTPUT	   C48_GLOSSIES_OUTPUT,
-- 	S.GLOSSIES_PAPER_DEADLINE	   C49_GLOSSIES_PAPER_DEADLINE,
-- 	S.GLOSSIES_DEL_DEADLINE	   C50_GLOSSIES_DEL_DEADLINE,
-- 	S.MULTIPLE_IMAGES_OPTION	   C51_MULTIPLE_IMAGES_OPTION,
-- 	S.PRINTABLE_FRAMES	   C52_PRINTABLE_FRAMES,
-- 	S.TERRITORY_ID	   C53_TERRITORY_ID,
-- 	S.STUDIO_ID	   C54_STUDIO_ID,
-- 	S.PROCESSING_LAB	   C55_PROCESSING_LAB,
-- 	S.PUBLISHER_ADDRESS_LINE1	   C56_PUBLISHER_ADDRESS_LINE1,
-- 	S.PUBLISHER_ADDRESS_LINE2	   C57_PUBLISHER_ADDRESS_LINE2,
-- 	S.PUBLISHER_ADDRESS_LINE3	   C58_PUBLISHER_ADDRESS_LINE3,
-- 	S.PUBLISHER_CITY	   C59_PUBLISHER_CITY,
-- 	S.PUBLISHER_STATE	   C60_PUBLISHER_STATE,
-- 	S.PUBLISHER_ZIP_CODE	   C61_PUBLISHER_ZIP_CODE,
-- 	S.PUBLISHER_COUNTRY	   C62_PUBLISHER_COUNTRY,
-- 	S.PUBLISHER_PHONENO	   C63_PUBLISHER_PHONENO,
-- 	S.PUBLISHER_FAXNO	   C64_PUBLISHER_FAXNO,
-- 	S.PUBLISHER_EMAIL	   C65_PUBLISHER_EMAIL,
-- 	S.PUBLISHER_CONTACT_PERSON	   C66_PUBLISHER_CONTACT_PERSON,
-- 	S.ACCOUNT_ADDRESS_LINE1	   C67_ACCOUNT_ADDRESS_LINE1,
-- 	S.ACCOUNT_ADDRESS_LINE2	   C68_ACCOUNT_ADDRESS_LINE2,
-- 	S.ACCOUNT_ADDRESS_LINE3	   C69_ACCOUNT_ADDRESS_LINE3,
-- 	S.ACCOUNT_CITY	   C70_ACCOUNT_CITY,
-- 	S.ACCOUNT_STATE	   C71_ACCOUNT_STATE,
-- 	S.ACCOUNT_ZIP_CODE	   C72_ACCOUNT_ZIP_CODE,
-- 	S.ACCOUNT_COUNTRY	   C73_ACCOUNT_COUNTRY,
-- 	S.ACCOUNT_PHONENO	   C74_ACCOUNT_PHONENO,
-- 	S.ACCOUNT_CONTACT_PERSON	   C75_ACCOUNT_CONTACT_PERSON,
-- 	S.ACCOUNT_FAXNO	   C76_ACCOUNT_FAXNO,
-- 	S.ACCOUNT_EMAIL	   C77_ACCOUNT_EMAIL,
-- 	S.PUBLISHER_ACCT_NO	   C78_PUBLISHER_ACCT_NO,
-- 	S.VISION_JOB_NO	   C79_VISION_JOB_NO,
-- 	S.CURRENCY	   C80_CURRENCY,
-- 	S.CREATETS	   C81_CREATETS,
-- 	S.MODIFYTS	   C82_MODIFYTS,
-- 	S.CREATEUSERID	   C83_CREATEUSERID,
-- 	S.MODIFYUSERID	   C84_MODIFYUSERID,
-- 	S.CREATEPROGID	   C85_CREATEPROGID,
-- 	S.MODIFYPROGID	   C86_MODIFYPROGID,
-- 	S.LOCKID	   C87_LOCKID,
-- 	S.APO_ID	   C88_APO_ID,
-- 	S.CONFIRMED_PROCESSING_LAB	   C89_CONFIRMED_PROCESSING_LAB,
-- 	S.PHOTOTRACKER_DEL_DATE	   C90_PHOTOTRACKER_DEL_DATE,
-- 	S.SOLO_ACCESS	   C91_SOLO_ACCESS,
-- 	S.ESTIMATED_ENROLLMENT	   C92_ESTIMATED_ENROLLMENT,
-- 	S.TERRITORY_NOTES	   C93_TERRITORY_NOTES,
-- 	S.SELLER_FOR_ORDER	   C94_SELLER_FOR_ORDER,
-- 	S.LAB_REVISION_NO	   C95_LAB_REVISION_NO,
-- 	S.LAB_NOTES	   C96_LAB_NOTES,
-- 	S.BOYS_GOWN_COLOR_1	   C97_BOYS_GOWN_COLOR_1,
-- 	S.BOYS_TASSEL_COLOR_1	   C98_BOYS_TASSEL_COLOR_1,
-- 	S.GIRLS_GOWN_COLOR_1	   C99_GIRLS_GOWN_COLOR_1,
-- 	S.GIRLS_TASSEL_COLOR_1	   C100_GIRLS_TASSEL_COLOR_1,
-- 	S.BOYS_GOWN_COLOR_2	   C101_BOYS_GOWN_COLOR_2,
-- 	S.BOYS_TASSEL_COLOR_2	   C102_BOYS_TASSEL_COLOR_2,
-- 	S.GIRLS_GOWN_COLOR_2	   C103_GIRLS_GOWN_COLOR_2,
-- 	S.GIRLS_TASSEL_COLOR_2	   C104_GIRLS_TASSEL_COLOR_2,
-- 	S.NO_OF_PROOF_SETS	   C105_NO_OF_PROOF_SETS,
-- 	S.NO_OF_GLOSSY_SETS	   C106_NO_OF_GLOSSY_SETS,
-- 	S.STUDENT_ID_REQD	   C107_STUDENT_ID_REQD,
-- 	S.TAX_EXEMPT_CERTIFICATE_NUMBER	   C108_TAX_EXEMPT_CERTIFICATE_NU,
-- 	S.TAX_EXEMPT	   C109_TAX_EXEMPT,
-- 	S.SELECT_ORDER_BY_PHONE_NO	   C110_SELECT_ORDER_BY_PHONE_NO,
-- 	S.SELECT_ORDER_ENQUIRY_NO	   C111_SELECT_ORDER_ENQUIRY_NO,
-- 	S.IS_PROOF_EXPRESS	   C112_IS_PROOF_EXPRESS,
-- 	S.GUARANTEED_DOLLAR_AMOUNT	   C113_GUARANTEED_DOLLAR_AMOUNT,
-- 	S.GRAD_ANNOUNCE_POSTER_INS	   C114_GRAD_ANNOUNCE_POSTER_INS,
-- 	S.CUSTOM_LANGUAGE	   C115_CUSTOM_LANGUAGE,
-- 	S.YB_SELECTION_ONLINE	   C116_YB_SELECTION_ONLINE,
-- 	S.ORDER_FORM_ITEM_ID	   C117_ORDER_FORM_ITEM_ID,
-- 	S.SUB_PROGRAM_TYPE	   C118_SUB_PROGRAM_TYPE,
-- 	S.MARKETING_CODE	   C119_MARKETING_CODE,
-- 	S.FLYER_ID	   C120_FLYER_ID,
-- 	S.SORT_TYPE	   C121_SORT_TYPE,
-- 	S.ENVELOPE_TYPE	   C122_ENVELOPE_TYPE,
-- 	S.VISUAL_MERCH_KEY	   C123_VISUAL_MERCH_KEY,
-- 	S.VISUAL_MERCH_ID	   C124_VISUAL_MERCH_ID,
-- 	S.REVISION_NO	   C125_REVISION_NO,
-- 	S.COMP_PROD_CODE	   C126_COMP_PROD_CODE,
-- 	S.COMP_DLVRY_TYPE	   C127_COMP_DLVRY_TYPE,
-- 	S.GRP_PROD_CODE	   C128_GRP_PROD_CODE,
-- 	S.GRP_DLVRY_TYPE	   C129_GRP_DLVRY_TYPE,
-- 	S.MODEL_GRADE	   C130_MODEL_GRADE,
-- 	S.MODEL_ETHNICITY	   C131_MODEL_ETHNICITY,
-- 	S.MODEL_GENDER	   C132_MODEL_GENDER,
-- 	S.SERVICE_CENTER	   C133_SERVICE_CENTER,
-- 	S.EVENT_IMAGE_COMPLETE	   C134_EVENT_IMAGE_COMPLETE,
-- 	S.SHIP_TO_ACCOUNT_BUFFER_DAYS	   C135_SHIP_TO_ACCOUNT_BUFFER_DA,
-- 	S.ORIGINAL_ORDER_FORM_DUE_DATE	   C136_ORIGINAL_ORDER_FORM_DUE_D,
-- 	S.RETAKE_ORDER_FORM_DUE_DATE	   C137_RETAKE_ORDER_FORM_DUE_DAT,
-- 	S.EXTERNAL_SYNC_FLAG	   C138_EXTERNAL_SYNC_FLAG,
-- 	S.FULFILLING_LAB_SYSTEM	   C139_FULFILLING_LAB_SYSTEM,
-- 	S.FINANCIAL_PROCESSING_SYSTEM	   C140_FINANCIAL_PROCESSING_SYST,
-- 	S.ORIGINAL_BOOKING_REP	   C141_ORIGINAL_BOOKING_REP,
-- 	S.ORIGINAL_BOOKING_REP_NAME	   C142_ORIGINAL_BOOKING_REP_NAME,
-- 	S.SHIP_TO_SATELLITE_LOCATION	   C143_SHIP_TO_SATELLITE_LOCATIO,
-- 	S.CLASS_PICTURE_RELEASE_DATE	   C144_CLASS_PICTURE_RELEASE_DAT
-- from	OMS3_OWN.LT_APO   S
-- where	(1=1)
-- And (S.MODIFYTS >= TO_DATE(SUBSTR(:v_cdc_load_date, 1, 19), 'YYYY-MM-DD HH24:MI:SS')  -:v_cdc_overlap)







-- &

-- /* TARGET CODE */
-- insert /*+ append */ into RAX_APP_USER.C$_0OMS3_LT_APO_STG
-- (
-- 	C1_APO_KEY,
-- 	C2_DESCRIPTION,
-- 	C3_ACCOUNT_ID,
-- 	C4_GRAD_YEAR,
-- 	C5_STATUS,
-- 	C6_ACCOUNT_NAME,
-- 	C7_PROGRAM_TYPE,
-- 	C8_PRICE_PROGRAM_NAME,
-- 	C9_PHOTOGRAPHY_LOCATION,
-- 	C10_GLOSSIES_REQD,
-- 	C11_YEARBOOK_POSE_REQD,
-- 	C12_PUBLISHER,
-- 	C13_OTHER_PUBLISHER,
-- 	C14_SHIP_PROOFS_TO,
-- 	C15_SHIP_ORDERS_TO,
-- 	C16_SHIP_GLOSSIES_TO,
-- 	C17_SHIP_PROOFS_STUDIO_CODE,
-- 	C18_SHIP_ORDERS_STUDIO_CODE,
-- 	C19_SHIP_GLOSSIES_STUDIO_CODE,
-- 	C20_TERRITORY_GROUP_ID,
-- 	C21_SHIP_PROOFS_STUDIO_ATTN,
-- 	C22_SHIP_ORDERS_STUDIO_ATTN,
-- 	C23_SHIP_GLOSSIES_STUDIO_ATTN,
-- 	C24_COMMISSION_PER_CUST,
-- 	C25_COMMISSION_PERCENTAGE,
-- 	C26_COMMISSION_GUARANTEED,
-- 	C27_COMMISSION_SPECIAL,
-- 	C28_ORDER_RETURN_MSG_REQD,
-- 	C29_ORDER_REMINDER_REQD,
-- 	C30_ORDER_ASSIST_REQD,
-- 	C31_INCLUDE_ORDER_FORM,
-- 	C32_INCLUDE_RETURN_ENVELOPE,
-- 	C33_ORDER_BY_PHONE_NO,
-- 	C34_ORDER_ENQUIRY_NO,
-- 	C35_YEARBOOK_POSESTYLE_1,
-- 	C36_YEARBOOK_POSESTYLE_2,
-- 	C37_YEARBOOK_POSESTYLE_OTHER1,
-- 	C38_YEARBOOK_POSESTYLE_OTHER2,
-- 	C39_YEARBOOK_BACKGROUND1,
-- 	C40_YEARBOOK_BACKGROUND2,
-- 	C41_YEARBOOK_BGROUND_OTHER1,
-- 	C42_YEARBOOK_BGROUND_OTHER2,
-- 	C43_YEARBOOK_OUTFIT1,
-- 	C44_YEARBOOK_OUTFIT2,
-- 	C45_YEARBOOK_OUTFIT_OTHER1,
-- 	C46_YEARBOOK_OUTFIT_OTHER2,
-- 	C47_YEARBOOK_SPL_INST,
-- 	C48_GLOSSIES_OUTPUT,
-- 	C49_GLOSSIES_PAPER_DEADLINE,
-- 	C50_GLOSSIES_DEL_DEADLINE,
-- 	C51_MULTIPLE_IMAGES_OPTION,
-- 	C52_PRINTABLE_FRAMES,
-- 	C53_TERRITORY_ID,
-- 	C54_STUDIO_ID,
-- 	C55_PROCESSING_LAB,
-- 	C56_PUBLISHER_ADDRESS_LINE1,
-- 	C57_PUBLISHER_ADDRESS_LINE2,
-- 	C58_PUBLISHER_ADDRESS_LINE3,
-- 	C59_PUBLISHER_CITY,
-- 	C60_PUBLISHER_STATE,
-- 	C61_PUBLISHER_ZIP_CODE,
-- 	C62_PUBLISHER_COUNTRY,
-- 	C63_PUBLISHER_PHONENO,
-- 	C64_PUBLISHER_FAXNO,
-- 	C65_PUBLISHER_EMAIL,
-- 	C66_PUBLISHER_CONTACT_PERSON,
-- 	C67_ACCOUNT_ADDRESS_LINE1,
-- 	C68_ACCOUNT_ADDRESS_LINE2,
-- 	C69_ACCOUNT_ADDRESS_LINE3,
-- 	C70_ACCOUNT_CITY,
-- 	C71_ACCOUNT_STATE,
-- 	C72_ACCOUNT_ZIP_CODE,
-- 	C73_ACCOUNT_COUNTRY,
-- 	C74_ACCOUNT_PHONENO,
-- 	C75_ACCOUNT_CONTACT_PERSON,
-- 	C76_ACCOUNT_FAXNO,
-- 	C77_ACCOUNT_EMAIL,
-- 	C78_PUBLISHER_ACCT_NO,
-- 	C79_VISION_JOB_NO,
-- 	C80_CURRENCY,
-- 	C81_CREATETS,
-- 	C82_MODIFYTS,
-- 	C83_CREATEUSERID,
-- 	C84_MODIFYUSERID,
-- 	C85_CREATEPROGID,
-- 	C86_MODIFYPROGID,
-- 	C87_LOCKID,
-- 	C88_APO_ID,
-- 	C89_CONFIRMED_PROCESSING_LAB,
-- 	C90_PHOTOTRACKER_DEL_DATE,
-- 	C91_SOLO_ACCESS,
-- 	C92_ESTIMATED_ENROLLMENT,
-- 	C93_TERRITORY_NOTES,
-- 	C94_SELLER_FOR_ORDER,
-- 	C95_LAB_REVISION_NO,
-- 	C96_LAB_NOTES,
-- 	C97_BOYS_GOWN_COLOR_1,
-- 	C98_BOYS_TASSEL_COLOR_1,
-- 	C99_GIRLS_GOWN_COLOR_1,
-- 	C100_GIRLS_TASSEL_COLOR_1,
-- 	C101_BOYS_GOWN_COLOR_2,
-- 	C102_BOYS_TASSEL_COLOR_2,
-- 	C103_GIRLS_GOWN_COLOR_2,
-- 	C104_GIRLS_TASSEL_COLOR_2,
-- 	C105_NO_OF_PROOF_SETS,
-- 	C106_NO_OF_GLOSSY_SETS,
-- 	C107_STUDENT_ID_REQD,
-- 	C108_TAX_EXEMPT_CERTIFICATE_NU,
-- 	C109_TAX_EXEMPT,
-- 	C110_SELECT_ORDER_BY_PHONE_NO,
-- 	C111_SELECT_ORDER_ENQUIRY_NO,
-- 	C112_IS_PROOF_EXPRESS,
-- 	C113_GUARANTEED_DOLLAR_AMOUNT,
-- 	C114_GRAD_ANNOUNCE_POSTER_INS,
-- 	C115_CUSTOM_LANGUAGE,
-- 	C116_YB_SELECTION_ONLINE,
-- 	C117_ORDER_FORM_ITEM_ID,
-- 	C118_SUB_PROGRAM_TYPE,
-- 	C119_MARKETING_CODE,
-- 	C120_FLYER_ID,
-- 	C121_SORT_TYPE,
-- 	C122_ENVELOPE_TYPE,
-- 	C123_VISUAL_MERCH_KEY,
-- 	C124_VISUAL_MERCH_ID,
-- 	C125_REVISION_NO,
-- 	C126_COMP_PROD_CODE,
-- 	C127_COMP_DLVRY_TYPE,
-- 	C128_GRP_PROD_CODE,
-- 	C129_GRP_DLVRY_TYPE,
-- 	C130_MODEL_GRADE,
-- 	C131_MODEL_ETHNICITY,
-- 	C132_MODEL_GENDER,
-- 	C133_SERVICE_CENTER,
-- 	C134_EVENT_IMAGE_COMPLETE,
-- 	C135_SHIP_TO_ACCOUNT_BUFFER_DA,
-- 	C136_ORIGINAL_ORDER_FORM_DUE_D,
-- 	C137_RETAKE_ORDER_FORM_DUE_DAT,
-- 	C138_EXTERNAL_SYNC_FLAG,
-- 	C139_FULFILLING_LAB_SYSTEM,
-- 	C140_FINANCIAL_PROCESSING_SYST,
-- 	C141_ORIGINAL_BOOKING_REP,
-- 	C142_ORIGINAL_BOOKING_REP_NAME,
-- 	C143_SHIP_TO_SATELLITE_LOCATIO,
-- 	C144_CLASS_PICTURE_RELEASE_DAT
-- )
-- values
-- (
-- 	:C1_APO_KEY,
-- 	:C2_DESCRIPTION,
-- 	:C3_ACCOUNT_ID,
-- 	:C4_GRAD_YEAR,
-- 	:C5_STATUS,
-- 	:C6_ACCOUNT_NAME,
-- 	:C7_PROGRAM_TYPE,
-- 	:C8_PRICE_PROGRAM_NAME,
-- 	:C9_PHOTOGRAPHY_LOCATION,
-- 	:C10_GLOSSIES_REQD,
-- 	:C11_YEARBOOK_POSE_REQD,
-- 	:C12_PUBLISHER,
-- 	:C13_OTHER_PUBLISHER,
-- 	:C14_SHIP_PROOFS_TO,
-- 	:C15_SHIP_ORDERS_TO,
-- 	:C16_SHIP_GLOSSIES_TO,
-- 	:C17_SHIP_PROOFS_STUDIO_CODE,
-- 	:C18_SHIP_ORDERS_STUDIO_CODE,
-- 	:C19_SHIP_GLOSSIES_STUDIO_CODE,
-- 	:C20_TERRITORY_GROUP_ID,
-- 	:C21_SHIP_PROOFS_STUDIO_ATTN,
-- 	:C22_SHIP_ORDERS_STUDIO_ATTN,
-- 	:C23_SHIP_GLOSSIES_STUDIO_ATTN,
-- 	:C24_COMMISSION_PER_CUST,
-- 	:C25_COMMISSION_PERCENTAGE,
-- 	:C26_COMMISSION_GUARANTEED,
-- 	:C27_COMMISSION_SPECIAL,
-- 	:C28_ORDER_RETURN_MSG_REQD,
-- 	:C29_ORDER_REMINDER_REQD,
-- 	:C30_ORDER_ASSIST_REQD,
-- 	:C31_INCLUDE_ORDER_FORM,
-- 	:C32_INCLUDE_RETURN_ENVELOPE,
-- 	:C33_ORDER_BY_PHONE_NO,
-- 	:C34_ORDER_ENQUIRY_NO,
-- 	:C35_YEARBOOK_POSESTYLE_1,
-- 	:C36_YEARBOOK_POSESTYLE_2,
-- 	:C37_YEARBOOK_POSESTYLE_OTHER1,
-- 	:C38_YEARBOOK_POSESTYLE_OTHER2,
-- 	:C39_YEARBOOK_BACKGROUND1,
-- 	:C40_YEARBOOK_BACKGROUND2,
-- 	:C41_YEARBOOK_BGROUND_OTHER1,
-- 	:C42_YEARBOOK_BGROUND_OTHER2,
-- 	:C43_YEARBOOK_OUTFIT1,
-- 	:C44_YEARBOOK_OUTFIT2,
-- 	:C45_YEARBOOK_OUTFIT_OTHER1,
-- 	:C46_YEARBOOK_OUTFIT_OTHER2,
-- 	:C47_YEARBOOK_SPL_INST,
-- 	:C48_GLOSSIES_OUTPUT,
-- 	:C49_GLOSSIES_PAPER_DEADLINE,
-- 	:C50_GLOSSIES_DEL_DEADLINE,
-- 	:C51_MULTIPLE_IMAGES_OPTION,
-- 	:C52_PRINTABLE_FRAMES,
-- 	:C53_TERRITORY_ID,
-- 	:C54_STUDIO_ID,
-- 	:C55_PROCESSING_LAB,
-- 	:C56_PUBLISHER_ADDRESS_LINE1,
-- 	:C57_PUBLISHER_ADDRESS_LINE2,
-- 	:C58_PUBLISHER_ADDRESS_LINE3,
-- 	:C59_PUBLISHER_CITY,
-- 	:C60_PUBLISHER_STATE,
-- 	:C61_PUBLISHER_ZIP_CODE,
-- 	:C62_PUBLISHER_COUNTRY,
-- 	:C63_PUBLISHER_PHONENO,
-- 	:C64_PUBLISHER_FAXNO,
-- 	:C65_PUBLISHER_EMAIL,
-- 	:C66_PUBLISHER_CONTACT_PERSON,
-- 	:C67_ACCOUNT_ADDRESS_LINE1,
-- 	:C68_ACCOUNT_ADDRESS_LINE2,
-- 	:C69_ACCOUNT_ADDRESS_LINE3,
-- 	:C70_ACCOUNT_CITY,
-- 	:C71_ACCOUNT_STATE,
-- 	:C72_ACCOUNT_ZIP_CODE,
-- 	:C73_ACCOUNT_COUNTRY,
-- 	:C74_ACCOUNT_PHONENO,
-- 	:C75_ACCOUNT_CONTACT_PERSON,
-- 	:C76_ACCOUNT_FAXNO,
-- 	:C77_ACCOUNT_EMAIL,
-- 	:C78_PUBLISHER_ACCT_NO,
-- 	:C79_VISION_JOB_NO,
-- 	:C80_CURRENCY,
-- 	:C81_CREATETS,
-- 	:C82_MODIFYTS,
-- 	:C83_CREATEUSERID,
-- 	:C84_MODIFYUSERID,
-- 	:C85_CREATEPROGID,
-- 	:C86_MODIFYPROGID,
-- 	:C87_LOCKID,
-- 	:C88_APO_ID,
-- 	:C89_CONFIRMED_PROCESSING_LAB,
-- 	:C90_PHOTOTRACKER_DEL_DATE,
-- 	:C91_SOLO_ACCESS,
-- 	:C92_ESTIMATED_ENROLLMENT,
-- 	:C93_TERRITORY_NOTES,
-- 	:C94_SELLER_FOR_ORDER,
-- 	:C95_LAB_REVISION_NO,
-- 	:C96_LAB_NOTES,
-- 	:C97_BOYS_GOWN_COLOR_1,
-- 	:C98_BOYS_TASSEL_COLOR_1,
-- 	:C99_GIRLS_GOWN_COLOR_1,
-- 	:C100_GIRLS_TASSEL_COLOR_1,
-- 	:C101_BOYS_GOWN_COLOR_2,
-- 	:C102_BOYS_TASSEL_COLOR_2,
-- 	:C103_GIRLS_GOWN_COLOR_2,
-- 	:C104_GIRLS_TASSEL_COLOR_2,
-- 	:C105_NO_OF_PROOF_SETS,
-- 	:C106_NO_OF_GLOSSY_SETS,
-- 	:C107_STUDENT_ID_REQD,
-- 	:C108_TAX_EXEMPT_CERTIFICATE_NU,
-- 	:C109_TAX_EXEMPT,
-- 	:C110_SELECT_ORDER_BY_PHONE_NO,
-- 	:C111_SELECT_ORDER_ENQUIRY_NO,
-- 	:C112_IS_PROOF_EXPRESS,
-- 	:C113_GUARANTEED_DOLLAR_AMOUNT,
-- 	:C114_GRAD_ANNOUNCE_POSTER_INS,
-- 	:C115_CUSTOM_LANGUAGE,
-- 	:C116_YB_SELECTION_ONLINE,
-- 	:C117_ORDER_FORM_ITEM_ID,
-- 	:C118_SUB_PROGRAM_TYPE,
-- 	:C119_MARKETING_CODE,
-- 	:C120_FLYER_ID,
-- 	:C121_SORT_TYPE,
-- 	:C122_ENVELOPE_TYPE,
-- 	:C123_VISUAL_MERCH_KEY,
-- 	:C124_VISUAL_MERCH_ID,
-- 	:C125_REVISION_NO,
-- 	:C126_COMP_PROD_CODE,
-- 	:C127_COMP_DLVRY_TYPE,
-- 	:C128_GRP_PROD_CODE,
-- 	:C129_GRP_DLVRY_TYPE,
-- 	:C130_MODEL_GRADE,
-- 	:C131_MODEL_ETHNICITY,
-- 	:C132_MODEL_GENDER,
-- 	:C133_SERVICE_CENTER,
-- 	:C134_EVENT_IMAGE_COMPLETE,
-- 	:C135_SHIP_TO_ACCOUNT_BUFFER_DA,
-- 	:C136_ORIGINAL_ORDER_FORM_DUE_D,
-- 	:C137_RETAKE_ORDER_FORM_DUE_DAT,
-- 	:C138_EXTERNAL_SYNC_FLAG,
-- 	:C139_FULFILLING_LAB_SYSTEM,
-- 	:C140_FINANCIAL_PROCESSING_SYST,
-- 	:C141_ORIGINAL_BOOKING_REP,
-- 	:C142_ORIGINAL_BOOKING_REP_NAME,
-- 	:C143_SHIP_TO_SATELLITE_LOCATIO,
-- 	:C144_CLASS_PICTURE_RELEASE_DAT
-- )

-- &


/*-----------------------------------------------*/
/* TASK No. 7 */
/* Analyze work table */



BEGIN
DBMS_STATS.GATHER_TABLE_STATS (
    ownname =>	'RAX_APP_USER',
    tabname =>	'C$_0OMS3_LT_APO_STG',
    estimate_percent =>	DBMS_STATS.AUTO_SAMPLE_SIZE
);
END;




&


/*-----------------------------------------------*/
/* TASK No. 9 */
/* Set vID */

/* NONE or SET VARIABLE STATEMENT FOUND, CHECK ODI TASK NO. 9 */




/*-----------------------------------------------*/
/* TASK No. 10 */
/* Drop flow table */

BEGIN  
   EXECUTE IMMEDIATE 'drop table RAX_APP_USER.I$_OMS3_LT_APO_STG2015001';  
EXCEPTION  
   WHEN OTHERS THEN  
      IF SQLCODE != -942 THEN  
         RAISE;  
      END IF;  
END;

&


/*-----------------------------------------------*/
/* TASK No. 11 */
/* Create flow table I$ */

create table RAX_APP_USER.I$_OMS3_LT_APO_STG2015001
(
	APO_KEY	VARCHAR2(24) NULL,
	DESCRIPTION	VARCHAR2(100) NULL,
	ACCOUNT_ID	VARCHAR2(15) NULL,
	GRAD_YEAR	NUMBER NULL,
	STATUS	VARCHAR2(10) NULL,
	ACCOUNT_NAME	VARCHAR2(40) NULL,
	PROGRAM_TYPE	VARCHAR2(20) NULL,
	PRICE_PROGRAM_NAME	VARCHAR2(50) NULL,
	PHOTOGRAPHY_LOCATION	VARCHAR2(15) NULL,
	GLOSSIES_REQD	VARCHAR2(1) NULL,
	YEARBOOK_POSE_REQD	VARCHAR2(1) NULL,
	PUBLISHER	VARCHAR2(20) NULL,
	OTHER_PUBLISHER	VARCHAR2(20) NULL,
	SHIP_PROOFS_TO	VARCHAR2(15) NULL,
	SHIP_ORDERS_TO	VARCHAR2(15) NULL,
	SHIP_GLOSSIES_TO	VARCHAR2(15) NULL,
	SHIP_PROOFS_STUDIO_CODE	VARCHAR2(24) NULL,
	SHIP_ORDERS_STUDIO_CODE	VARCHAR2(24) NULL,
	SHIP_GLOSSIES_STUDIO_CODE	VARCHAR2(24) NULL,
	TERRITORY_GROUP_ID	VARCHAR2(80) NULL,
	SHIP_PROOFS_STUDIO_ATTN	VARCHAR2(25) NULL,
	SHIP_ORDERS_STUDIO_ATTN	VARCHAR2(25) NULL,
	SHIP_GLOSSIES_STUDIO_ATTN	VARCHAR2(25) NULL,
	COMMISSION_PER_CUST	NUMBER NULL,
	COMMISSION_PERCENTAGE	NUMBER NULL,
	COMMISSION_GUARANTEED	NUMBER NULL,
	COMMISSION_SPECIAL	NUMBER NULL,
	ORDER_RETURN_MSG_REQD	VARCHAR2(1) NULL,
	ORDER_REMINDER_REQD	VARCHAR2(1) NULL,
	ORDER_ASSIST_REQD	VARCHAR2(1) NULL,
	INCLUDE_ORDER_FORM	VARCHAR2(1) NULL,
	INCLUDE_RETURN_ENVELOPE	VARCHAR2(1) NULL,
	ORDER_BY_PHONE_NO	VARCHAR2(15) NULL,
	ORDER_ENQUIRY_NO	VARCHAR2(15) NULL,
	YEARBOOK_POSESTYLE_1	VARCHAR2(20) NULL,
	YEARBOOK_POSESTYLE_2	VARCHAR2(20) NULL,
	YEARBOOK_POSESTYLE_OTHER1	VARCHAR2(100) NULL,
	YEARBOOK_POSESTYLE_OTHER2	VARCHAR2(100) NULL,
	YEARBOOK_BACKGROUND1	VARCHAR2(20) NULL,
	YEARBOOK_BACKGROUND2	VARCHAR2(20) NULL,
	YEARBOOK_BGROUND_OTHER1	VARCHAR2(100) NULL,
	YEARBOOK_BGROUND_OTHER2	VARCHAR2(100) NULL,
	YEARBOOK_OUTFIT1	VARCHAR2(20) NULL,
	YEARBOOK_OUTFIT2	VARCHAR2(20) NULL,
	YEARBOOK_OUTFIT_OTHER1	VARCHAR2(100) NULL,
	YEARBOOK_OUTFIT_OTHER2	VARCHAR2(100) NULL,
	YEARBOOK_SPL_INST	VARCHAR2(400) NULL,
	GLOSSIES_OUTPUT	VARCHAR2(40) NULL,
	GLOSSIES_PAPER_DEADLINE	DATE NULL,
	GLOSSIES_DEL_DEADLINE	DATE NULL,
	MULTIPLE_IMAGES_OPTION	VARCHAR2(30) NULL,
	PRINTABLE_FRAMES	VARCHAR2(30) NULL,
	TERRITORY_ID	VARCHAR2(24) NULL,
	STUDIO_ID	VARCHAR2(24) NULL,
	PROCESSING_LAB	VARCHAR2(24) NULL,
	PUBLISHER_ADDRESS_LINE1	VARCHAR2(30) NULL,
	PUBLISHER_ADDRESS_LINE2	VARCHAR2(30) NULL,
	PUBLISHER_ADDRESS_LINE3	VARCHAR2(30) NULL,
	PUBLISHER_CITY	VARCHAR2(20) NULL,
	PUBLISHER_STATE	VARCHAR2(15) NULL,
	PUBLISHER_ZIP_CODE	VARCHAR2(10) NULL,
	PUBLISHER_COUNTRY	VARCHAR2(10) NULL,
	PUBLISHER_PHONENO	VARCHAR2(15) NULL,
	PUBLISHER_FAXNO	VARCHAR2(15) NULL,
	PUBLISHER_EMAIL	VARCHAR2(30) NULL,
	PUBLISHER_CONTACT_PERSON	VARCHAR2(30) NULL,
	ACCOUNT_ADDRESS_LINE1	VARCHAR2(30) NULL,
	ACCOUNT_ADDRESS_LINE2	VARCHAR2(30) NULL,
	ACCOUNT_ADDRESS_LINE3	VARCHAR2(30) NULL,
	ACCOUNT_CITY	VARCHAR2(20) NULL,
	ACCOUNT_STATE	VARCHAR2(15) NULL,
	ACCOUNT_ZIP_CODE	VARCHAR2(10) NULL,
	ACCOUNT_COUNTRY	VARCHAR2(10) NULL,
	ACCOUNT_PHONENO	VARCHAR2(15) NULL,
	ACCOUNT_CONTACT_PERSON	VARCHAR2(30) NULL,
	ACCOUNT_FAXNO	VARCHAR2(15) NULL,
	ACCOUNT_EMAIL	VARCHAR2(30) NULL,
	PUBLISHER_ACCT_NO	VARCHAR2(24) NULL,
	VISION_JOB_NO	VARCHAR2(24) NULL,
	CURRENCY	VARCHAR2(10) NULL,
	CREATETS	DATE NULL,
	MODIFYTS	DATE NULL,
	CREATEUSERID	VARCHAR2(40) NULL,
	MODIFYUSERID	VARCHAR2(40) NULL,
	CREATEPROGID	VARCHAR2(40) NULL,
	MODIFYPROGID	VARCHAR2(40) NULL,
	LOCKID	NUMBER NULL,
	APO_ID	VARCHAR2(15) NULL,
	CONFIRMED_PROCESSING_LAB	VARCHAR2(24) NULL,
	PHOTOTRACKER_DEL_DATE	DATE NULL,
	SOLO_ACCESS	VARCHAR2(1) NULL,
	ESTIMATED_ENROLLMENT	NUMBER NULL,
	TERRITORY_NOTES	VARCHAR2(250) NULL,
	SELLER_FOR_ORDER	VARCHAR2(24) NULL,
	LAB_REVISION_NO	NUMBER NULL,
	LAB_NOTES	VARCHAR2(200) NULL,
	BOYS_GOWN_COLOR_1	VARCHAR2(15) NULL,
	BOYS_TASSEL_COLOR_1	VARCHAR2(15) NULL,
	GIRLS_GOWN_COLOR_1	VARCHAR2(15) NULL,
	GIRLS_TASSEL_COLOR_1	VARCHAR2(15) NULL,
	BOYS_GOWN_COLOR_2	VARCHAR2(15) NULL,
	BOYS_TASSEL_COLOR_2	VARCHAR2(15) NULL,
	GIRLS_GOWN_COLOR_2	VARCHAR2(15) NULL,
	GIRLS_TASSEL_COLOR_2	VARCHAR2(15) NULL,
	NO_OF_PROOF_SETS	NUMBER NULL,
	NO_OF_GLOSSY_SETS	NUMBER NULL,
	STUDENT_ID_REQD	VARCHAR2(1) NULL,
	TAX_EXEMPT_CERTIFICATE_NUMBER	VARCHAR2(40) NULL,
	TAX_EXEMPT	VARCHAR2(1) NULL,
	SELECT_ORDER_BY_PHONE_NO	VARCHAR2(15) NULL,
	SELECT_ORDER_ENQUIRY_NO	VARCHAR2(15) NULL,
	IS_PROOF_EXPRESS	VARCHAR2(1) NULL,
	GUARANTEED_DOLLAR_AMOUNT	NUMBER NULL,
	GRAD_ANNOUNCE_POSTER_INS	VARCHAR2(1) NULL,
	CUSTOM_LANGUAGE	VARCHAR2(40) NULL,
	YB_SELECTION_ONLINE	VARCHAR2(1) NULL,
	ORDER_FORM_ITEM_ID	VARCHAR2(40) NULL,
	SUB_PROGRAM_TYPE	VARCHAR2(20) NULL,
	MARKETING_CODE	VARCHAR2(10) NULL,
	FLYER_ID	VARCHAR2(20) NULL,
	SORT_TYPE	VARCHAR2(20) NULL,
	ENVELOPE_TYPE	VARCHAR2(20) NULL,
	VISUAL_MERCH_KEY	VARCHAR2(24) NULL,
	VISUAL_MERCH_ID	VARCHAR2(24) NULL,
	REVISION_NO	NUMBER NULL,
	COMP_PROD_CODE	VARCHAR2(24) NULL,
	COMP_DLVRY_TYPE	VARCHAR2(24) NULL,
	GRP_PROD_CODE	VARCHAR2(24) NULL,
	GRP_DLVRY_TYPE	VARCHAR2(24) NULL,
	MODEL_GRADE	VARCHAR2(20) NULL,
	MODEL_ETHNICITY	VARCHAR2(20) NULL,
	MODEL_GENDER	VARCHAR2(2) NULL,
	SERVICE_CENTER	VARCHAR2(24) NULL,
	EVENT_IMAGE_COMPLETE	VARCHAR2(1) NULL,
	SHIP_TO_ACCOUNT_BUFFER_DAYS	NUMBER NULL,
	ORIGINAL_ORDER_FORM_DUE_DATE	NUMBER NULL,
	RETAKE_ORDER_FORM_DUE_DATE	NUMBER NULL,
	EXTERNAL_SYNC_FLAG	VARCHAR2(1) NULL,
	FULFILLING_LAB_SYSTEM	VARCHAR2(24) NULL,
	FINANCIAL_PROCESSING_SYSTEM	VARCHAR2(50) NULL,
	ORIGINAL_BOOKING_REP	VARCHAR2(255) NULL,
	ORIGINAL_BOOKING_REP_NAME	VARCHAR2(255) NULL,
	SHIP_TO_SATELLITE_LOCATION	VARCHAR2(10) NULL,
	ODS_CREATE_DATE	DATE NULL,
	ODS_MODIFY_DATE	DATE NULL,
	CLASS_PICTURE_RELEASE_DATE	DATE NULL
	,IND_UPDATE		char(1)
)
NOLOGGING

&


/*-----------------------------------------------*/
/* TASK No. 12 */
/* Insert flow into I$ table */

/* DETECTION_STRATEGY = NOT_EXISTS */
 


  


insert into	RAX_APP_USER.I$_OMS3_LT_APO_STG2015001
(
	APO_KEY,
	DESCRIPTION,
	ACCOUNT_ID,
	GRAD_YEAR,
	STATUS,
	ACCOUNT_NAME,
	PROGRAM_TYPE,
	PRICE_PROGRAM_NAME,
	PHOTOGRAPHY_LOCATION,
	GLOSSIES_REQD,
	YEARBOOK_POSE_REQD,
	PUBLISHER,
	OTHER_PUBLISHER,
	SHIP_PROOFS_TO,
	SHIP_ORDERS_TO,
	SHIP_GLOSSIES_TO,
	SHIP_PROOFS_STUDIO_CODE,
	SHIP_ORDERS_STUDIO_CODE,
	SHIP_GLOSSIES_STUDIO_CODE,
	TERRITORY_GROUP_ID,
	SHIP_PROOFS_STUDIO_ATTN,
	SHIP_ORDERS_STUDIO_ATTN,
	SHIP_GLOSSIES_STUDIO_ATTN,
	COMMISSION_PER_CUST,
	COMMISSION_PERCENTAGE,
	COMMISSION_GUARANTEED,
	COMMISSION_SPECIAL,
	ORDER_RETURN_MSG_REQD,
	ORDER_REMINDER_REQD,
	ORDER_ASSIST_REQD,
	INCLUDE_ORDER_FORM,
	INCLUDE_RETURN_ENVELOPE,
	ORDER_BY_PHONE_NO,
	ORDER_ENQUIRY_NO,
	YEARBOOK_POSESTYLE_1,
	YEARBOOK_POSESTYLE_2,
	YEARBOOK_POSESTYLE_OTHER1,
	YEARBOOK_POSESTYLE_OTHER2,
	YEARBOOK_BACKGROUND1,
	YEARBOOK_BACKGROUND2,
	YEARBOOK_BGROUND_OTHER1,
	YEARBOOK_BGROUND_OTHER2,
	YEARBOOK_OUTFIT1,
	YEARBOOK_OUTFIT2,
	YEARBOOK_OUTFIT_OTHER1,
	YEARBOOK_OUTFIT_OTHER2,
	YEARBOOK_SPL_INST,
	GLOSSIES_OUTPUT,
	GLOSSIES_PAPER_DEADLINE,
	GLOSSIES_DEL_DEADLINE,
	MULTIPLE_IMAGES_OPTION,
	PRINTABLE_FRAMES,
	TERRITORY_ID,
	STUDIO_ID,
	PROCESSING_LAB,
	PUBLISHER_ADDRESS_LINE1,
	PUBLISHER_ADDRESS_LINE2,
	PUBLISHER_ADDRESS_LINE3,
	PUBLISHER_CITY,
	PUBLISHER_STATE,
	PUBLISHER_ZIP_CODE,
	PUBLISHER_COUNTRY,
	PUBLISHER_PHONENO,
	PUBLISHER_FAXNO,
	PUBLISHER_EMAIL,
	PUBLISHER_CONTACT_PERSON,
	ACCOUNT_ADDRESS_LINE1,
	ACCOUNT_ADDRESS_LINE2,
	ACCOUNT_ADDRESS_LINE3,
	ACCOUNT_CITY,
	ACCOUNT_STATE,
	ACCOUNT_ZIP_CODE,
	ACCOUNT_COUNTRY,
	ACCOUNT_PHONENO,
	ACCOUNT_CONTACT_PERSON,
	ACCOUNT_FAXNO,
	ACCOUNT_EMAIL,
	PUBLISHER_ACCT_NO,
	VISION_JOB_NO,
	CURRENCY,
	CREATETS,
	MODIFYTS,
	CREATEUSERID,
	MODIFYUSERID,
	CREATEPROGID,
	MODIFYPROGID,
	LOCKID,
	APO_ID,
	CONFIRMED_PROCESSING_LAB,
	PHOTOTRACKER_DEL_DATE,
	SOLO_ACCESS,
	ESTIMATED_ENROLLMENT,
	TERRITORY_NOTES,
	SELLER_FOR_ORDER,
	LAB_REVISION_NO,
	LAB_NOTES,
	BOYS_GOWN_COLOR_1,
	BOYS_TASSEL_COLOR_1,
	GIRLS_GOWN_COLOR_1,
	GIRLS_TASSEL_COLOR_1,
	BOYS_GOWN_COLOR_2,
	BOYS_TASSEL_COLOR_2,
	GIRLS_GOWN_COLOR_2,
	GIRLS_TASSEL_COLOR_2,
	NO_OF_PROOF_SETS,
	NO_OF_GLOSSY_SETS,
	STUDENT_ID_REQD,
	TAX_EXEMPT_CERTIFICATE_NUMBER,
	TAX_EXEMPT,
	SELECT_ORDER_BY_PHONE_NO,
	SELECT_ORDER_ENQUIRY_NO,
	IS_PROOF_EXPRESS,
	GUARANTEED_DOLLAR_AMOUNT,
	GRAD_ANNOUNCE_POSTER_INS,
	CUSTOM_LANGUAGE,
	YB_SELECTION_ONLINE,
	ORDER_FORM_ITEM_ID,
	SUB_PROGRAM_TYPE,
	MARKETING_CODE,
	FLYER_ID,
	SORT_TYPE,
	ENVELOPE_TYPE,
	VISUAL_MERCH_KEY,
	VISUAL_MERCH_ID,
	REVISION_NO,
	COMP_PROD_CODE,
	COMP_DLVRY_TYPE,
	GRP_PROD_CODE,
	GRP_DLVRY_TYPE,
	MODEL_GRADE,
	MODEL_ETHNICITY,
	MODEL_GENDER,
	SERVICE_CENTER,
	EVENT_IMAGE_COMPLETE,
	SHIP_TO_ACCOUNT_BUFFER_DAYS,
	ORIGINAL_ORDER_FORM_DUE_DATE,
	RETAKE_ORDER_FORM_DUE_DATE,
	EXTERNAL_SYNC_FLAG,
	FULFILLING_LAB_SYSTEM,
	FINANCIAL_PROCESSING_SYSTEM,
	ORIGINAL_BOOKING_REP,
	ORIGINAL_BOOKING_REP_NAME,
	SHIP_TO_SATELLITE_LOCATION,
	CLASS_PICTURE_RELEASE_DATE,
	IND_UPDATE
)
select 
APO_KEY,
	DESCRIPTION,
	ACCOUNT_ID,
	GRAD_YEAR,
	STATUS,
	ACCOUNT_NAME,
	PROGRAM_TYPE,
	PRICE_PROGRAM_NAME,
	PHOTOGRAPHY_LOCATION,
	GLOSSIES_REQD,
	YEARBOOK_POSE_REQD,
	PUBLISHER,
	OTHER_PUBLISHER,
	SHIP_PROOFS_TO,
	SHIP_ORDERS_TO,
	SHIP_GLOSSIES_TO,
	SHIP_PROOFS_STUDIO_CODE,
	SHIP_ORDERS_STUDIO_CODE,
	SHIP_GLOSSIES_STUDIO_CODE,
	TERRITORY_GROUP_ID,
	SHIP_PROOFS_STUDIO_ATTN,
	SHIP_ORDERS_STUDIO_ATTN,
	SHIP_GLOSSIES_STUDIO_ATTN,
	COMMISSION_PER_CUST,
	COMMISSION_PERCENTAGE,
	COMMISSION_GUARANTEED,
	COMMISSION_SPECIAL,
	ORDER_RETURN_MSG_REQD,
	ORDER_REMINDER_REQD,
	ORDER_ASSIST_REQD,
	INCLUDE_ORDER_FORM,
	INCLUDE_RETURN_ENVELOPE,
	ORDER_BY_PHONE_NO,
	ORDER_ENQUIRY_NO,
	YEARBOOK_POSESTYLE_1,
	YEARBOOK_POSESTYLE_2,
	YEARBOOK_POSESTYLE_OTHER1,
	YEARBOOK_POSESTYLE_OTHER2,
	YEARBOOK_BACKGROUND1,
	YEARBOOK_BACKGROUND2,
	YEARBOOK_BGROUND_OTHER1,
	YEARBOOK_BGROUND_OTHER2,
	YEARBOOK_OUTFIT1,
	YEARBOOK_OUTFIT2,
	YEARBOOK_OUTFIT_OTHER1,
	YEARBOOK_OUTFIT_OTHER2,
	YEARBOOK_SPL_INST,
	GLOSSIES_OUTPUT,
	GLOSSIES_PAPER_DEADLINE,
	GLOSSIES_DEL_DEADLINE,
	MULTIPLE_IMAGES_OPTION,
	PRINTABLE_FRAMES,
	TERRITORY_ID,
	STUDIO_ID,
	PROCESSING_LAB,
	PUBLISHER_ADDRESS_LINE1,
	PUBLISHER_ADDRESS_LINE2,
	PUBLISHER_ADDRESS_LINE3,
	PUBLISHER_CITY,
	PUBLISHER_STATE,
	PUBLISHER_ZIP_CODE,
	PUBLISHER_COUNTRY,
	PUBLISHER_PHONENO,
	PUBLISHER_FAXNO,
	PUBLISHER_EMAIL,
	PUBLISHER_CONTACT_PERSON,
	ACCOUNT_ADDRESS_LINE1,
	ACCOUNT_ADDRESS_LINE2,
	ACCOUNT_ADDRESS_LINE3,
	ACCOUNT_CITY,
	ACCOUNT_STATE,
	ACCOUNT_ZIP_CODE,
	ACCOUNT_COUNTRY,
	ACCOUNT_PHONENO,
	ACCOUNT_CONTACT_PERSON,
	ACCOUNT_FAXNO,
	ACCOUNT_EMAIL,
	PUBLISHER_ACCT_NO,
	VISION_JOB_NO,
	CURRENCY,
	CREATETS,
	MODIFYTS,
	CREATEUSERID,
	MODIFYUSERID,
	CREATEPROGID,
	MODIFYPROGID,
	LOCKID,
	APO_ID,
	CONFIRMED_PROCESSING_LAB,
	PHOTOTRACKER_DEL_DATE,
	SOLO_ACCESS,
	ESTIMATED_ENROLLMENT,
	TERRITORY_NOTES,
	SELLER_FOR_ORDER,
	LAB_REVISION_NO,
	LAB_NOTES,
	BOYS_GOWN_COLOR_1,
	BOYS_TASSEL_COLOR_1,
	GIRLS_GOWN_COLOR_1,
	GIRLS_TASSEL_COLOR_1,
	BOYS_GOWN_COLOR_2,
	BOYS_TASSEL_COLOR_2,
	GIRLS_GOWN_COLOR_2,
	GIRLS_TASSEL_COLOR_2,
	NO_OF_PROOF_SETS,
	NO_OF_GLOSSY_SETS,
	STUDENT_ID_REQD,
	TAX_EXEMPT_CERTIFICATE_NUMBER,
	TAX_EXEMPT,
	SELECT_ORDER_BY_PHONE_NO,
	SELECT_ORDER_ENQUIRY_NO,
	IS_PROOF_EXPRESS,
	GUARANTEED_DOLLAR_AMOUNT,
	GRAD_ANNOUNCE_POSTER_INS,
	CUSTOM_LANGUAGE,
	YB_SELECTION_ONLINE,
	ORDER_FORM_ITEM_ID,
	SUB_PROGRAM_TYPE,
	MARKETING_CODE,
	FLYER_ID,
	SORT_TYPE,
	ENVELOPE_TYPE,
	VISUAL_MERCH_KEY,
	VISUAL_MERCH_ID,
	REVISION_NO,
	COMP_PROD_CODE,
	COMP_DLVRY_TYPE,
	GRP_PROD_CODE,
	GRP_DLVRY_TYPE,
	MODEL_GRADE,
	MODEL_ETHNICITY,
	MODEL_GENDER,
	SERVICE_CENTER,
	EVENT_IMAGE_COMPLETE,
	SHIP_TO_ACCOUNT_BUFFER_DAYS,
	ORIGINAL_ORDER_FORM_DUE_DATE,
	RETAKE_ORDER_FORM_DUE_DATE,
	EXTERNAL_SYNC_FLAG,
	FULFILLING_LAB_SYSTEM,
	FINANCIAL_PROCESSING_SYSTEM,
	ORIGINAL_BOOKING_REP,
	ORIGINAL_BOOKING_REP_NAME,
	SHIP_TO_SATELLITE_LOCATION,
	CLASS_PICTURE_RELEASE_DATE,
	IND_UPDATE
 from (


select 	 
	
	C1_APO_KEY APO_KEY,
	C2_DESCRIPTION DESCRIPTION,
	C3_ACCOUNT_ID ACCOUNT_ID,
	C4_GRAD_YEAR GRAD_YEAR,
	C5_STATUS STATUS,
	C6_ACCOUNT_NAME ACCOUNT_NAME,
	C7_PROGRAM_TYPE PROGRAM_TYPE,
	C8_PRICE_PROGRAM_NAME PRICE_PROGRAM_NAME,
	C9_PHOTOGRAPHY_LOCATION PHOTOGRAPHY_LOCATION,
	C10_GLOSSIES_REQD GLOSSIES_REQD,
	C11_YEARBOOK_POSE_REQD YEARBOOK_POSE_REQD,
	C12_PUBLISHER PUBLISHER,
	C13_OTHER_PUBLISHER OTHER_PUBLISHER,
	C14_SHIP_PROOFS_TO SHIP_PROOFS_TO,
	C15_SHIP_ORDERS_TO SHIP_ORDERS_TO,
	C16_SHIP_GLOSSIES_TO SHIP_GLOSSIES_TO,
	C17_SHIP_PROOFS_STUDIO_CODE SHIP_PROOFS_STUDIO_CODE,
	C18_SHIP_ORDERS_STUDIO_CODE SHIP_ORDERS_STUDIO_CODE,
	C19_SHIP_GLOSSIES_STUDIO_CODE SHIP_GLOSSIES_STUDIO_CODE,
	C20_TERRITORY_GROUP_ID TERRITORY_GROUP_ID,
	C21_SHIP_PROOFS_STUDIO_ATTN SHIP_PROOFS_STUDIO_ATTN,
	C22_SHIP_ORDERS_STUDIO_ATTN SHIP_ORDERS_STUDIO_ATTN,
	C23_SHIP_GLOSSIES_STUDIO_ATTN SHIP_GLOSSIES_STUDIO_ATTN,
	C24_COMMISSION_PER_CUST COMMISSION_PER_CUST,
	C25_COMMISSION_PERCENTAGE COMMISSION_PERCENTAGE,
	C26_COMMISSION_GUARANTEED COMMISSION_GUARANTEED,
	C27_COMMISSION_SPECIAL COMMISSION_SPECIAL,
	C28_ORDER_RETURN_MSG_REQD ORDER_RETURN_MSG_REQD,
	C29_ORDER_REMINDER_REQD ORDER_REMINDER_REQD,
	C30_ORDER_ASSIST_REQD ORDER_ASSIST_REQD,
	C31_INCLUDE_ORDER_FORM INCLUDE_ORDER_FORM,
	C32_INCLUDE_RETURN_ENVELOPE INCLUDE_RETURN_ENVELOPE,
	C33_ORDER_BY_PHONE_NO ORDER_BY_PHONE_NO,
	C34_ORDER_ENQUIRY_NO ORDER_ENQUIRY_NO,
	C35_YEARBOOK_POSESTYLE_1 YEARBOOK_POSESTYLE_1,
	C36_YEARBOOK_POSESTYLE_2 YEARBOOK_POSESTYLE_2,
	C37_YEARBOOK_POSESTYLE_OTHER1 YEARBOOK_POSESTYLE_OTHER1,
	C38_YEARBOOK_POSESTYLE_OTHER2 YEARBOOK_POSESTYLE_OTHER2,
	C39_YEARBOOK_BACKGROUND1 YEARBOOK_BACKGROUND1,
	C40_YEARBOOK_BACKGROUND2 YEARBOOK_BACKGROUND2,
	C41_YEARBOOK_BGROUND_OTHER1 YEARBOOK_BGROUND_OTHER1,
	C42_YEARBOOK_BGROUND_OTHER2 YEARBOOK_BGROUND_OTHER2,
	C43_YEARBOOK_OUTFIT1 YEARBOOK_OUTFIT1,
	C44_YEARBOOK_OUTFIT2 YEARBOOK_OUTFIT2,
	C45_YEARBOOK_OUTFIT_OTHER1 YEARBOOK_OUTFIT_OTHER1,
	C46_YEARBOOK_OUTFIT_OTHER2 YEARBOOK_OUTFIT_OTHER2,
	C47_YEARBOOK_SPL_INST YEARBOOK_SPL_INST,
	C48_GLOSSIES_OUTPUT GLOSSIES_OUTPUT,
	C49_GLOSSIES_PAPER_DEADLINE GLOSSIES_PAPER_DEADLINE,
	C50_GLOSSIES_DEL_DEADLINE GLOSSIES_DEL_DEADLINE,
	C51_MULTIPLE_IMAGES_OPTION MULTIPLE_IMAGES_OPTION,
	C52_PRINTABLE_FRAMES PRINTABLE_FRAMES,
	C53_TERRITORY_ID TERRITORY_ID,
	C54_STUDIO_ID STUDIO_ID,
	C55_PROCESSING_LAB PROCESSING_LAB,
	C56_PUBLISHER_ADDRESS_LINE1 PUBLISHER_ADDRESS_LINE1,
	C57_PUBLISHER_ADDRESS_LINE2 PUBLISHER_ADDRESS_LINE2,
	C58_PUBLISHER_ADDRESS_LINE3 PUBLISHER_ADDRESS_LINE3,
	C59_PUBLISHER_CITY PUBLISHER_CITY,
	C60_PUBLISHER_STATE PUBLISHER_STATE,
	C61_PUBLISHER_ZIP_CODE PUBLISHER_ZIP_CODE,
	C62_PUBLISHER_COUNTRY PUBLISHER_COUNTRY,
	C63_PUBLISHER_PHONENO PUBLISHER_PHONENO,
	C64_PUBLISHER_FAXNO PUBLISHER_FAXNO,
	C65_PUBLISHER_EMAIL PUBLISHER_EMAIL,
	C66_PUBLISHER_CONTACT_PERSON PUBLISHER_CONTACT_PERSON,
	C67_ACCOUNT_ADDRESS_LINE1 ACCOUNT_ADDRESS_LINE1,
	C68_ACCOUNT_ADDRESS_LINE2 ACCOUNT_ADDRESS_LINE2,
	C69_ACCOUNT_ADDRESS_LINE3 ACCOUNT_ADDRESS_LINE3,
	C70_ACCOUNT_CITY ACCOUNT_CITY,
	C71_ACCOUNT_STATE ACCOUNT_STATE,
	C72_ACCOUNT_ZIP_CODE ACCOUNT_ZIP_CODE,
	C73_ACCOUNT_COUNTRY ACCOUNT_COUNTRY,
	C74_ACCOUNT_PHONENO ACCOUNT_PHONENO,
	C75_ACCOUNT_CONTACT_PERSON ACCOUNT_CONTACT_PERSON,
	C76_ACCOUNT_FAXNO ACCOUNT_FAXNO,
	C77_ACCOUNT_EMAIL ACCOUNT_EMAIL,
	C78_PUBLISHER_ACCT_NO PUBLISHER_ACCT_NO,
	C79_VISION_JOB_NO VISION_JOB_NO,
	C80_CURRENCY CURRENCY,
	C81_CREATETS CREATETS,
	C82_MODIFYTS MODIFYTS,
	C83_CREATEUSERID CREATEUSERID,
	C84_MODIFYUSERID MODIFYUSERID,
	C85_CREATEPROGID CREATEPROGID,
	C86_MODIFYPROGID MODIFYPROGID,
	C87_LOCKID LOCKID,
	C88_APO_ID APO_ID,
	C89_CONFIRMED_PROCESSING_LAB CONFIRMED_PROCESSING_LAB,
	C90_PHOTOTRACKER_DEL_DATE PHOTOTRACKER_DEL_DATE,
	C91_SOLO_ACCESS SOLO_ACCESS,
	C92_ESTIMATED_ENROLLMENT ESTIMATED_ENROLLMENT,
	C93_TERRITORY_NOTES TERRITORY_NOTES,
	C94_SELLER_FOR_ORDER SELLER_FOR_ORDER,
	C95_LAB_REVISION_NO LAB_REVISION_NO,
	C96_LAB_NOTES LAB_NOTES,
	C97_BOYS_GOWN_COLOR_1 BOYS_GOWN_COLOR_1,
	C98_BOYS_TASSEL_COLOR_1 BOYS_TASSEL_COLOR_1,
	C99_GIRLS_GOWN_COLOR_1 GIRLS_GOWN_COLOR_1,
	C100_GIRLS_TASSEL_COLOR_1 GIRLS_TASSEL_COLOR_1,
	C101_BOYS_GOWN_COLOR_2 BOYS_GOWN_COLOR_2,
	C102_BOYS_TASSEL_COLOR_2 BOYS_TASSEL_COLOR_2,
	C103_GIRLS_GOWN_COLOR_2 GIRLS_GOWN_COLOR_2,
	C104_GIRLS_TASSEL_COLOR_2 GIRLS_TASSEL_COLOR_2,
	C105_NO_OF_PROOF_SETS NO_OF_PROOF_SETS,
	C106_NO_OF_GLOSSY_SETS NO_OF_GLOSSY_SETS,
	C107_STUDENT_ID_REQD STUDENT_ID_REQD,
	C108_TAX_EXEMPT_CERTIFICATE_NU TAX_EXEMPT_CERTIFICATE_NUMBER,
	C109_TAX_EXEMPT TAX_EXEMPT,
	C110_SELECT_ORDER_BY_PHONE_NO SELECT_ORDER_BY_PHONE_NO,
	C111_SELECT_ORDER_ENQUIRY_NO SELECT_ORDER_ENQUIRY_NO,
	C112_IS_PROOF_EXPRESS IS_PROOF_EXPRESS,
	C113_GUARANTEED_DOLLAR_AMOUNT GUARANTEED_DOLLAR_AMOUNT,
	C114_GRAD_ANNOUNCE_POSTER_INS GRAD_ANNOUNCE_POSTER_INS,
	C115_CUSTOM_LANGUAGE CUSTOM_LANGUAGE,
	C116_YB_SELECTION_ONLINE YB_SELECTION_ONLINE,
	C117_ORDER_FORM_ITEM_ID ORDER_FORM_ITEM_ID,
	C118_SUB_PROGRAM_TYPE SUB_PROGRAM_TYPE,
	C119_MARKETING_CODE MARKETING_CODE,
	C120_FLYER_ID FLYER_ID,
	C121_SORT_TYPE SORT_TYPE,
	C122_ENVELOPE_TYPE ENVELOPE_TYPE,
	C123_VISUAL_MERCH_KEY VISUAL_MERCH_KEY,
	C124_VISUAL_MERCH_ID VISUAL_MERCH_ID,
	C125_REVISION_NO REVISION_NO,
	C126_COMP_PROD_CODE COMP_PROD_CODE,
	C127_COMP_DLVRY_TYPE COMP_DLVRY_TYPE,
	C128_GRP_PROD_CODE GRP_PROD_CODE,
	C129_GRP_DLVRY_TYPE GRP_DLVRY_TYPE,
	C130_MODEL_GRADE MODEL_GRADE,
	C131_MODEL_ETHNICITY MODEL_ETHNICITY,
	C132_MODEL_GENDER MODEL_GENDER,
	C133_SERVICE_CENTER SERVICE_CENTER,
	C134_EVENT_IMAGE_COMPLETE EVENT_IMAGE_COMPLETE,
	C135_SHIP_TO_ACCOUNT_BUFFER_DA SHIP_TO_ACCOUNT_BUFFER_DAYS,
	C136_ORIGINAL_ORDER_FORM_DUE_D ORIGINAL_ORDER_FORM_DUE_DATE,
	C137_RETAKE_ORDER_FORM_DUE_DAT RETAKE_ORDER_FORM_DUE_DATE,
	C138_EXTERNAL_SYNC_FLAG EXTERNAL_SYNC_FLAG,
	C139_FULFILLING_LAB_SYSTEM FULFILLING_LAB_SYSTEM,
	C140_FINANCIAL_PROCESSING_SYST FINANCIAL_PROCESSING_SYSTEM,
	C141_ORIGINAL_BOOKING_REP ORIGINAL_BOOKING_REP,
	C142_ORIGINAL_BOOKING_REP_NAME ORIGINAL_BOOKING_REP_NAME,
	C143_SHIP_TO_SATELLITE_LOCATIO SHIP_TO_SATELLITE_LOCATION,
	C144_CLASS_PICTURE_RELEASE_DAT CLASS_PICTURE_RELEASE_DATE,

	'I' IND_UPDATE

from	RAX_APP_USER.C$_0OMS3_LT_APO_STG
where	(1=1)






) S
where NOT EXISTS 
	( select 1 from ODS_STAGE.OMS3_LT_APO_STG T
	where	T.APO_KEY	= S.APO_KEY 
		 and ((T.DESCRIPTION = S.DESCRIPTION) or (T.DESCRIPTION IS NULL and S.DESCRIPTION IS NULL)) and
		((T.ACCOUNT_ID = S.ACCOUNT_ID) or (T.ACCOUNT_ID IS NULL and S.ACCOUNT_ID IS NULL)) and
		((T.GRAD_YEAR = S.GRAD_YEAR) or (T.GRAD_YEAR IS NULL and S.GRAD_YEAR IS NULL)) and
		((T.STATUS = S.STATUS) or (T.STATUS IS NULL and S.STATUS IS NULL)) and
		((T.ACCOUNT_NAME = S.ACCOUNT_NAME) or (T.ACCOUNT_NAME IS NULL and S.ACCOUNT_NAME IS NULL)) and
		((T.PROGRAM_TYPE = S.PROGRAM_TYPE) or (T.PROGRAM_TYPE IS NULL and S.PROGRAM_TYPE IS NULL)) and
		((T.PRICE_PROGRAM_NAME = S.PRICE_PROGRAM_NAME) or (T.PRICE_PROGRAM_NAME IS NULL and S.PRICE_PROGRAM_NAME IS NULL)) and
		((T.PHOTOGRAPHY_LOCATION = S.PHOTOGRAPHY_LOCATION) or (T.PHOTOGRAPHY_LOCATION IS NULL and S.PHOTOGRAPHY_LOCATION IS NULL)) and
		((T.GLOSSIES_REQD = S.GLOSSIES_REQD) or (T.GLOSSIES_REQD IS NULL and S.GLOSSIES_REQD IS NULL)) and
		((T.YEARBOOK_POSE_REQD = S.YEARBOOK_POSE_REQD) or (T.YEARBOOK_POSE_REQD IS NULL and S.YEARBOOK_POSE_REQD IS NULL)) and
		((T.PUBLISHER = S.PUBLISHER) or (T.PUBLISHER IS NULL and S.PUBLISHER IS NULL)) and
		((T.OTHER_PUBLISHER = S.OTHER_PUBLISHER) or (T.OTHER_PUBLISHER IS NULL and S.OTHER_PUBLISHER IS NULL)) and
		((T.SHIP_PROOFS_TO = S.SHIP_PROOFS_TO) or (T.SHIP_PROOFS_TO IS NULL and S.SHIP_PROOFS_TO IS NULL)) and
		((T.SHIP_ORDERS_TO = S.SHIP_ORDERS_TO) or (T.SHIP_ORDERS_TO IS NULL and S.SHIP_ORDERS_TO IS NULL)) and
		((T.SHIP_GLOSSIES_TO = S.SHIP_GLOSSIES_TO) or (T.SHIP_GLOSSIES_TO IS NULL and S.SHIP_GLOSSIES_TO IS NULL)) and
		((T.SHIP_PROOFS_STUDIO_CODE = S.SHIP_PROOFS_STUDIO_CODE) or (T.SHIP_PROOFS_STUDIO_CODE IS NULL and S.SHIP_PROOFS_STUDIO_CODE IS NULL)) and
		((T.SHIP_ORDERS_STUDIO_CODE = S.SHIP_ORDERS_STUDIO_CODE) or (T.SHIP_ORDERS_STUDIO_CODE IS NULL and S.SHIP_ORDERS_STUDIO_CODE IS NULL)) and
		((T.SHIP_GLOSSIES_STUDIO_CODE = S.SHIP_GLOSSIES_STUDIO_CODE) or (T.SHIP_GLOSSIES_STUDIO_CODE IS NULL and S.SHIP_GLOSSIES_STUDIO_CODE IS NULL)) and
		((T.TERRITORY_GROUP_ID = S.TERRITORY_GROUP_ID) or (T.TERRITORY_GROUP_ID IS NULL and S.TERRITORY_GROUP_ID IS NULL)) and
		((T.SHIP_PROOFS_STUDIO_ATTN = S.SHIP_PROOFS_STUDIO_ATTN) or (T.SHIP_PROOFS_STUDIO_ATTN IS NULL and S.SHIP_PROOFS_STUDIO_ATTN IS NULL)) and
		((T.SHIP_ORDERS_STUDIO_ATTN = S.SHIP_ORDERS_STUDIO_ATTN) or (T.SHIP_ORDERS_STUDIO_ATTN IS NULL and S.SHIP_ORDERS_STUDIO_ATTN IS NULL)) and
		((T.SHIP_GLOSSIES_STUDIO_ATTN = S.SHIP_GLOSSIES_STUDIO_ATTN) or (T.SHIP_GLOSSIES_STUDIO_ATTN IS NULL and S.SHIP_GLOSSIES_STUDIO_ATTN IS NULL)) and
		((T.COMMISSION_PER_CUST = S.COMMISSION_PER_CUST) or (T.COMMISSION_PER_CUST IS NULL and S.COMMISSION_PER_CUST IS NULL)) and
		((T.COMMISSION_PERCENTAGE = S.COMMISSION_PERCENTAGE) or (T.COMMISSION_PERCENTAGE IS NULL and S.COMMISSION_PERCENTAGE IS NULL)) and
		((T.COMMISSION_GUARANTEED = S.COMMISSION_GUARANTEED) or (T.COMMISSION_GUARANTEED IS NULL and S.COMMISSION_GUARANTEED IS NULL)) and
		((T.COMMISSION_SPECIAL = S.COMMISSION_SPECIAL) or (T.COMMISSION_SPECIAL IS NULL and S.COMMISSION_SPECIAL IS NULL)) and
		((T.ORDER_RETURN_MSG_REQD = S.ORDER_RETURN_MSG_REQD) or (T.ORDER_RETURN_MSG_REQD IS NULL and S.ORDER_RETURN_MSG_REQD IS NULL)) and
		((T.ORDER_REMINDER_REQD = S.ORDER_REMINDER_REQD) or (T.ORDER_REMINDER_REQD IS NULL and S.ORDER_REMINDER_REQD IS NULL)) and
		((T.ORDER_ASSIST_REQD = S.ORDER_ASSIST_REQD) or (T.ORDER_ASSIST_REQD IS NULL and S.ORDER_ASSIST_REQD IS NULL)) and
		((T.INCLUDE_ORDER_FORM = S.INCLUDE_ORDER_FORM) or (T.INCLUDE_ORDER_FORM IS NULL and S.INCLUDE_ORDER_FORM IS NULL)) and
		((T.INCLUDE_RETURN_ENVELOPE = S.INCLUDE_RETURN_ENVELOPE) or (T.INCLUDE_RETURN_ENVELOPE IS NULL and S.INCLUDE_RETURN_ENVELOPE IS NULL)) and
		((T.ORDER_BY_PHONE_NO = S.ORDER_BY_PHONE_NO) or (T.ORDER_BY_PHONE_NO IS NULL and S.ORDER_BY_PHONE_NO IS NULL)) and
		((T.ORDER_ENQUIRY_NO = S.ORDER_ENQUIRY_NO) or (T.ORDER_ENQUIRY_NO IS NULL and S.ORDER_ENQUIRY_NO IS NULL)) and
		((T.YEARBOOK_POSESTYLE_1 = S.YEARBOOK_POSESTYLE_1) or (T.YEARBOOK_POSESTYLE_1 IS NULL and S.YEARBOOK_POSESTYLE_1 IS NULL)) and
		((T.YEARBOOK_POSESTYLE_2 = S.YEARBOOK_POSESTYLE_2) or (T.YEARBOOK_POSESTYLE_2 IS NULL and S.YEARBOOK_POSESTYLE_2 IS NULL)) and
		((T.YEARBOOK_POSESTYLE_OTHER1 = S.YEARBOOK_POSESTYLE_OTHER1) or (T.YEARBOOK_POSESTYLE_OTHER1 IS NULL and S.YEARBOOK_POSESTYLE_OTHER1 IS NULL)) and
		((T.YEARBOOK_POSESTYLE_OTHER2 = S.YEARBOOK_POSESTYLE_OTHER2) or (T.YEARBOOK_POSESTYLE_OTHER2 IS NULL and S.YEARBOOK_POSESTYLE_OTHER2 IS NULL)) and
		((T.YEARBOOK_BACKGROUND1 = S.YEARBOOK_BACKGROUND1) or (T.YEARBOOK_BACKGROUND1 IS NULL and S.YEARBOOK_BACKGROUND1 IS NULL)) and
		((T.YEARBOOK_BACKGROUND2 = S.YEARBOOK_BACKGROUND2) or (T.YEARBOOK_BACKGROUND2 IS NULL and S.YEARBOOK_BACKGROUND2 IS NULL)) and
		((T.YEARBOOK_BGROUND_OTHER1 = S.YEARBOOK_BGROUND_OTHER1) or (T.YEARBOOK_BGROUND_OTHER1 IS NULL and S.YEARBOOK_BGROUND_OTHER1 IS NULL)) and
		((T.YEARBOOK_BGROUND_OTHER2 = S.YEARBOOK_BGROUND_OTHER2) or (T.YEARBOOK_BGROUND_OTHER2 IS NULL and S.YEARBOOK_BGROUND_OTHER2 IS NULL)) and
		((T.YEARBOOK_OUTFIT1 = S.YEARBOOK_OUTFIT1) or (T.YEARBOOK_OUTFIT1 IS NULL and S.YEARBOOK_OUTFIT1 IS NULL)) and
		((T.YEARBOOK_OUTFIT2 = S.YEARBOOK_OUTFIT2) or (T.YEARBOOK_OUTFIT2 IS NULL and S.YEARBOOK_OUTFIT2 IS NULL)) and
		((T.YEARBOOK_OUTFIT_OTHER1 = S.YEARBOOK_OUTFIT_OTHER1) or (T.YEARBOOK_OUTFIT_OTHER1 IS NULL and S.YEARBOOK_OUTFIT_OTHER1 IS NULL)) and
		((T.YEARBOOK_OUTFIT_OTHER2 = S.YEARBOOK_OUTFIT_OTHER2) or (T.YEARBOOK_OUTFIT_OTHER2 IS NULL and S.YEARBOOK_OUTFIT_OTHER2 IS NULL)) and
		((T.YEARBOOK_SPL_INST = S.YEARBOOK_SPL_INST) or (T.YEARBOOK_SPL_INST IS NULL and S.YEARBOOK_SPL_INST IS NULL)) and
		((T.GLOSSIES_OUTPUT = S.GLOSSIES_OUTPUT) or (T.GLOSSIES_OUTPUT IS NULL and S.GLOSSIES_OUTPUT IS NULL)) and
		((T.GLOSSIES_PAPER_DEADLINE = S.GLOSSIES_PAPER_DEADLINE) or (T.GLOSSIES_PAPER_DEADLINE IS NULL and S.GLOSSIES_PAPER_DEADLINE IS NULL)) and
		((T.GLOSSIES_DEL_DEADLINE = S.GLOSSIES_DEL_DEADLINE) or (T.GLOSSIES_DEL_DEADLINE IS NULL and S.GLOSSIES_DEL_DEADLINE IS NULL)) and
		((T.MULTIPLE_IMAGES_OPTION = S.MULTIPLE_IMAGES_OPTION) or (T.MULTIPLE_IMAGES_OPTION IS NULL and S.MULTIPLE_IMAGES_OPTION IS NULL)) and
		((T.PRINTABLE_FRAMES = S.PRINTABLE_FRAMES) or (T.PRINTABLE_FRAMES IS NULL and S.PRINTABLE_FRAMES IS NULL)) and
		((T.TERRITORY_ID = S.TERRITORY_ID) or (T.TERRITORY_ID IS NULL and S.TERRITORY_ID IS NULL)) and
		((T.STUDIO_ID = S.STUDIO_ID) or (T.STUDIO_ID IS NULL and S.STUDIO_ID IS NULL)) and
		((T.PROCESSING_LAB = S.PROCESSING_LAB) or (T.PROCESSING_LAB IS NULL and S.PROCESSING_LAB IS NULL)) and
		((T.PUBLISHER_ADDRESS_LINE1 = S.PUBLISHER_ADDRESS_LINE1) or (T.PUBLISHER_ADDRESS_LINE1 IS NULL and S.PUBLISHER_ADDRESS_LINE1 IS NULL)) and
		((T.PUBLISHER_ADDRESS_LINE2 = S.PUBLISHER_ADDRESS_LINE2) or (T.PUBLISHER_ADDRESS_LINE2 IS NULL and S.PUBLISHER_ADDRESS_LINE2 IS NULL)) and
		((T.PUBLISHER_ADDRESS_LINE3 = S.PUBLISHER_ADDRESS_LINE3) or (T.PUBLISHER_ADDRESS_LINE3 IS NULL and S.PUBLISHER_ADDRESS_LINE3 IS NULL)) and
		((T.PUBLISHER_CITY = S.PUBLISHER_CITY) or (T.PUBLISHER_CITY IS NULL and S.PUBLISHER_CITY IS NULL)) and
		((T.PUBLISHER_STATE = S.PUBLISHER_STATE) or (T.PUBLISHER_STATE IS NULL and S.PUBLISHER_STATE IS NULL)) and
		((T.PUBLISHER_ZIP_CODE = S.PUBLISHER_ZIP_CODE) or (T.PUBLISHER_ZIP_CODE IS NULL and S.PUBLISHER_ZIP_CODE IS NULL)) and
		((T.PUBLISHER_COUNTRY = S.PUBLISHER_COUNTRY) or (T.PUBLISHER_COUNTRY IS NULL and S.PUBLISHER_COUNTRY IS NULL)) and
		((T.PUBLISHER_PHONENO = S.PUBLISHER_PHONENO) or (T.PUBLISHER_PHONENO IS NULL and S.PUBLISHER_PHONENO IS NULL)) and
		((T.PUBLISHER_FAXNO = S.PUBLISHER_FAXNO) or (T.PUBLISHER_FAXNO IS NULL and S.PUBLISHER_FAXNO IS NULL)) and
		((T.PUBLISHER_EMAIL = S.PUBLISHER_EMAIL) or (T.PUBLISHER_EMAIL IS NULL and S.PUBLISHER_EMAIL IS NULL)) and
		((T.PUBLISHER_CONTACT_PERSON = S.PUBLISHER_CONTACT_PERSON) or (T.PUBLISHER_CONTACT_PERSON IS NULL and S.PUBLISHER_CONTACT_PERSON IS NULL)) and
		((T.ACCOUNT_ADDRESS_LINE1 = S.ACCOUNT_ADDRESS_LINE1) or (T.ACCOUNT_ADDRESS_LINE1 IS NULL and S.ACCOUNT_ADDRESS_LINE1 IS NULL)) and
		((T.ACCOUNT_ADDRESS_LINE2 = S.ACCOUNT_ADDRESS_LINE2) or (T.ACCOUNT_ADDRESS_LINE2 IS NULL and S.ACCOUNT_ADDRESS_LINE2 IS NULL)) and
		((T.ACCOUNT_ADDRESS_LINE3 = S.ACCOUNT_ADDRESS_LINE3) or (T.ACCOUNT_ADDRESS_LINE3 IS NULL and S.ACCOUNT_ADDRESS_LINE3 IS NULL)) and
		((T.ACCOUNT_CITY = S.ACCOUNT_CITY) or (T.ACCOUNT_CITY IS NULL and S.ACCOUNT_CITY IS NULL)) and
		((T.ACCOUNT_STATE = S.ACCOUNT_STATE) or (T.ACCOUNT_STATE IS NULL and S.ACCOUNT_STATE IS NULL)) and
		((T.ACCOUNT_ZIP_CODE = S.ACCOUNT_ZIP_CODE) or (T.ACCOUNT_ZIP_CODE IS NULL and S.ACCOUNT_ZIP_CODE IS NULL)) and
		((T.ACCOUNT_COUNTRY = S.ACCOUNT_COUNTRY) or (T.ACCOUNT_COUNTRY IS NULL and S.ACCOUNT_COUNTRY IS NULL)) and
		((T.ACCOUNT_PHONENO = S.ACCOUNT_PHONENO) or (T.ACCOUNT_PHONENO IS NULL and S.ACCOUNT_PHONENO IS NULL)) and
		((T.ACCOUNT_CONTACT_PERSON = S.ACCOUNT_CONTACT_PERSON) or (T.ACCOUNT_CONTACT_PERSON IS NULL and S.ACCOUNT_CONTACT_PERSON IS NULL)) and
		((T.ACCOUNT_FAXNO = S.ACCOUNT_FAXNO) or (T.ACCOUNT_FAXNO IS NULL and S.ACCOUNT_FAXNO IS NULL)) and
		((T.ACCOUNT_EMAIL = S.ACCOUNT_EMAIL) or (T.ACCOUNT_EMAIL IS NULL and S.ACCOUNT_EMAIL IS NULL)) and
		((T.PUBLISHER_ACCT_NO = S.PUBLISHER_ACCT_NO) or (T.PUBLISHER_ACCT_NO IS NULL and S.PUBLISHER_ACCT_NO IS NULL)) and
		((T.VISION_JOB_NO = S.VISION_JOB_NO) or (T.VISION_JOB_NO IS NULL and S.VISION_JOB_NO IS NULL)) and
		((T.CURRENCY = S.CURRENCY) or (T.CURRENCY IS NULL and S.CURRENCY IS NULL)) and
		((T.CREATETS = S.CREATETS) or (T.CREATETS IS NULL and S.CREATETS IS NULL)) and
		((T.MODIFYTS = S.MODIFYTS) or (T.MODIFYTS IS NULL and S.MODIFYTS IS NULL)) and
		((T.CREATEUSERID = S.CREATEUSERID) or (T.CREATEUSERID IS NULL and S.CREATEUSERID IS NULL)) and
		((T.MODIFYUSERID = S.MODIFYUSERID) or (T.MODIFYUSERID IS NULL and S.MODIFYUSERID IS NULL)) and
		((T.CREATEPROGID = S.CREATEPROGID) or (T.CREATEPROGID IS NULL and S.CREATEPROGID IS NULL)) and
		((T.MODIFYPROGID = S.MODIFYPROGID) or (T.MODIFYPROGID IS NULL and S.MODIFYPROGID IS NULL)) and
		((T.LOCKID = S.LOCKID) or (T.LOCKID IS NULL and S.LOCKID IS NULL)) and
		((T.APO_ID = S.APO_ID) or (T.APO_ID IS NULL and S.APO_ID IS NULL)) and
		((T.CONFIRMED_PROCESSING_LAB = S.CONFIRMED_PROCESSING_LAB) or (T.CONFIRMED_PROCESSING_LAB IS NULL and S.CONFIRMED_PROCESSING_LAB IS NULL)) and
		((T.PHOTOTRACKER_DEL_DATE = S.PHOTOTRACKER_DEL_DATE) or (T.PHOTOTRACKER_DEL_DATE IS NULL and S.PHOTOTRACKER_DEL_DATE IS NULL)) and
		((T.SOLO_ACCESS = S.SOLO_ACCESS) or (T.SOLO_ACCESS IS NULL and S.SOLO_ACCESS IS NULL)) and
		((T.ESTIMATED_ENROLLMENT = S.ESTIMATED_ENROLLMENT) or (T.ESTIMATED_ENROLLMENT IS NULL and S.ESTIMATED_ENROLLMENT IS NULL)) and
		((T.TERRITORY_NOTES = S.TERRITORY_NOTES) or (T.TERRITORY_NOTES IS NULL and S.TERRITORY_NOTES IS NULL)) and
		((T.SELLER_FOR_ORDER = S.SELLER_FOR_ORDER) or (T.SELLER_FOR_ORDER IS NULL and S.SELLER_FOR_ORDER IS NULL)) and
		((T.LAB_REVISION_NO = S.LAB_REVISION_NO) or (T.LAB_REVISION_NO IS NULL and S.LAB_REVISION_NO IS NULL)) and
		((T.LAB_NOTES = S.LAB_NOTES) or (T.LAB_NOTES IS NULL and S.LAB_NOTES IS NULL)) and
		((T.BOYS_GOWN_COLOR_1 = S.BOYS_GOWN_COLOR_1) or (T.BOYS_GOWN_COLOR_1 IS NULL and S.BOYS_GOWN_COLOR_1 IS NULL)) and
		((T.BOYS_TASSEL_COLOR_1 = S.BOYS_TASSEL_COLOR_1) or (T.BOYS_TASSEL_COLOR_1 IS NULL and S.BOYS_TASSEL_COLOR_1 IS NULL)) and
		((T.GIRLS_GOWN_COLOR_1 = S.GIRLS_GOWN_COLOR_1) or (T.GIRLS_GOWN_COLOR_1 IS NULL and S.GIRLS_GOWN_COLOR_1 IS NULL)) and
		((T.GIRLS_TASSEL_COLOR_1 = S.GIRLS_TASSEL_COLOR_1) or (T.GIRLS_TASSEL_COLOR_1 IS NULL and S.GIRLS_TASSEL_COLOR_1 IS NULL)) and
		((T.BOYS_GOWN_COLOR_2 = S.BOYS_GOWN_COLOR_2) or (T.BOYS_GOWN_COLOR_2 IS NULL and S.BOYS_GOWN_COLOR_2 IS NULL)) and
		((T.BOYS_TASSEL_COLOR_2 = S.BOYS_TASSEL_COLOR_2) or (T.BOYS_TASSEL_COLOR_2 IS NULL and S.BOYS_TASSEL_COLOR_2 IS NULL)) and
		((T.GIRLS_GOWN_COLOR_2 = S.GIRLS_GOWN_COLOR_2) or (T.GIRLS_GOWN_COLOR_2 IS NULL and S.GIRLS_GOWN_COLOR_2 IS NULL)) and
		((T.GIRLS_TASSEL_COLOR_2 = S.GIRLS_TASSEL_COLOR_2) or (T.GIRLS_TASSEL_COLOR_2 IS NULL and S.GIRLS_TASSEL_COLOR_2 IS NULL)) and
		((T.NO_OF_PROOF_SETS = S.NO_OF_PROOF_SETS) or (T.NO_OF_PROOF_SETS IS NULL and S.NO_OF_PROOF_SETS IS NULL)) and
		((T.NO_OF_GLOSSY_SETS = S.NO_OF_GLOSSY_SETS) or (T.NO_OF_GLOSSY_SETS IS NULL and S.NO_OF_GLOSSY_SETS IS NULL)) and
		((T.STUDENT_ID_REQD = S.STUDENT_ID_REQD) or (T.STUDENT_ID_REQD IS NULL and S.STUDENT_ID_REQD IS NULL)) and
		((T.TAX_EXEMPT_CERTIFICATE_NUMBER = S.TAX_EXEMPT_CERTIFICATE_NUMBER) or (T.TAX_EXEMPT_CERTIFICATE_NUMBER IS NULL and S.TAX_EXEMPT_CERTIFICATE_NUMBER IS NULL)) and
		((T.TAX_EXEMPT = S.TAX_EXEMPT) or (T.TAX_EXEMPT IS NULL and S.TAX_EXEMPT IS NULL)) and
		((T.SELECT_ORDER_BY_PHONE_NO = S.SELECT_ORDER_BY_PHONE_NO) or (T.SELECT_ORDER_BY_PHONE_NO IS NULL and S.SELECT_ORDER_BY_PHONE_NO IS NULL)) and
		((T.SELECT_ORDER_ENQUIRY_NO = S.SELECT_ORDER_ENQUIRY_NO) or (T.SELECT_ORDER_ENQUIRY_NO IS NULL and S.SELECT_ORDER_ENQUIRY_NO IS NULL)) and
		((T.IS_PROOF_EXPRESS = S.IS_PROOF_EXPRESS) or (T.IS_PROOF_EXPRESS IS NULL and S.IS_PROOF_EXPRESS IS NULL)) and
		((T.GUARANTEED_DOLLAR_AMOUNT = S.GUARANTEED_DOLLAR_AMOUNT) or (T.GUARANTEED_DOLLAR_AMOUNT IS NULL and S.GUARANTEED_DOLLAR_AMOUNT IS NULL)) and
		((T.GRAD_ANNOUNCE_POSTER_INS = S.GRAD_ANNOUNCE_POSTER_INS) or (T.GRAD_ANNOUNCE_POSTER_INS IS NULL and S.GRAD_ANNOUNCE_POSTER_INS IS NULL)) and
		((T.CUSTOM_LANGUAGE = S.CUSTOM_LANGUAGE) or (T.CUSTOM_LANGUAGE IS NULL and S.CUSTOM_LANGUAGE IS NULL)) and
		((T.YB_SELECTION_ONLINE = S.YB_SELECTION_ONLINE) or (T.YB_SELECTION_ONLINE IS NULL and S.YB_SELECTION_ONLINE IS NULL)) and
		((T.ORDER_FORM_ITEM_ID = S.ORDER_FORM_ITEM_ID) or (T.ORDER_FORM_ITEM_ID IS NULL and S.ORDER_FORM_ITEM_ID IS NULL)) and
		((T.SUB_PROGRAM_TYPE = S.SUB_PROGRAM_TYPE) or (T.SUB_PROGRAM_TYPE IS NULL and S.SUB_PROGRAM_TYPE IS NULL)) and
		((T.MARKETING_CODE = S.MARKETING_CODE) or (T.MARKETING_CODE IS NULL and S.MARKETING_CODE IS NULL)) and
		((T.FLYER_ID = S.FLYER_ID) or (T.FLYER_ID IS NULL and S.FLYER_ID IS NULL)) and
		((T.SORT_TYPE = S.SORT_TYPE) or (T.SORT_TYPE IS NULL and S.SORT_TYPE IS NULL)) and
		((T.ENVELOPE_TYPE = S.ENVELOPE_TYPE) or (T.ENVELOPE_TYPE IS NULL and S.ENVELOPE_TYPE IS NULL)) and
		((T.VISUAL_MERCH_KEY = S.VISUAL_MERCH_KEY) or (T.VISUAL_MERCH_KEY IS NULL and S.VISUAL_MERCH_KEY IS NULL)) and
		((T.VISUAL_MERCH_ID = S.VISUAL_MERCH_ID) or (T.VISUAL_MERCH_ID IS NULL and S.VISUAL_MERCH_ID IS NULL)) and
		((T.REVISION_NO = S.REVISION_NO) or (T.REVISION_NO IS NULL and S.REVISION_NO IS NULL)) and
		((T.COMP_PROD_CODE = S.COMP_PROD_CODE) or (T.COMP_PROD_CODE IS NULL and S.COMP_PROD_CODE IS NULL)) and
		((T.COMP_DLVRY_TYPE = S.COMP_DLVRY_TYPE) or (T.COMP_DLVRY_TYPE IS NULL and S.COMP_DLVRY_TYPE IS NULL)) and
		((T.GRP_PROD_CODE = S.GRP_PROD_CODE) or (T.GRP_PROD_CODE IS NULL and S.GRP_PROD_CODE IS NULL)) and
		((T.GRP_DLVRY_TYPE = S.GRP_DLVRY_TYPE) or (T.GRP_DLVRY_TYPE IS NULL and S.GRP_DLVRY_TYPE IS NULL)) and
		((T.MODEL_GRADE = S.MODEL_GRADE) or (T.MODEL_GRADE IS NULL and S.MODEL_GRADE IS NULL)) and
		((T.MODEL_ETHNICITY = S.MODEL_ETHNICITY) or (T.MODEL_ETHNICITY IS NULL and S.MODEL_ETHNICITY IS NULL)) and
		((T.MODEL_GENDER = S.MODEL_GENDER) or (T.MODEL_GENDER IS NULL and S.MODEL_GENDER IS NULL)) and
		((T.SERVICE_CENTER = S.SERVICE_CENTER) or (T.SERVICE_CENTER IS NULL and S.SERVICE_CENTER IS NULL)) and
		((T.EVENT_IMAGE_COMPLETE = S.EVENT_IMAGE_COMPLETE) or (T.EVENT_IMAGE_COMPLETE IS NULL and S.EVENT_IMAGE_COMPLETE IS NULL)) and
		((T.SHIP_TO_ACCOUNT_BUFFER_DAYS = S.SHIP_TO_ACCOUNT_BUFFER_DAYS) or (T.SHIP_TO_ACCOUNT_BUFFER_DAYS IS NULL and S.SHIP_TO_ACCOUNT_BUFFER_DAYS IS NULL)) and
		((T.ORIGINAL_ORDER_FORM_DUE_DATE = S.ORIGINAL_ORDER_FORM_DUE_DATE) or (T.ORIGINAL_ORDER_FORM_DUE_DATE IS NULL and S.ORIGINAL_ORDER_FORM_DUE_DATE IS NULL)) and
		((T.RETAKE_ORDER_FORM_DUE_DATE = S.RETAKE_ORDER_FORM_DUE_DATE) or (T.RETAKE_ORDER_FORM_DUE_DATE IS NULL and S.RETAKE_ORDER_FORM_DUE_DATE IS NULL)) and
		((T.EXTERNAL_SYNC_FLAG = S.EXTERNAL_SYNC_FLAG) or (T.EXTERNAL_SYNC_FLAG IS NULL and S.EXTERNAL_SYNC_FLAG IS NULL)) and
		((T.FULFILLING_LAB_SYSTEM = S.FULFILLING_LAB_SYSTEM) or (T.FULFILLING_LAB_SYSTEM IS NULL and S.FULFILLING_LAB_SYSTEM IS NULL)) and
		((T.FINANCIAL_PROCESSING_SYSTEM = S.FINANCIAL_PROCESSING_SYSTEM) or (T.FINANCIAL_PROCESSING_SYSTEM IS NULL and S.FINANCIAL_PROCESSING_SYSTEM IS NULL)) and
		((T.ORIGINAL_BOOKING_REP = S.ORIGINAL_BOOKING_REP) or (T.ORIGINAL_BOOKING_REP IS NULL and S.ORIGINAL_BOOKING_REP IS NULL)) and
		((T.ORIGINAL_BOOKING_REP_NAME = S.ORIGINAL_BOOKING_REP_NAME) or (T.ORIGINAL_BOOKING_REP_NAME IS NULL and S.ORIGINAL_BOOKING_REP_NAME IS NULL)) and
		((T.SHIP_TO_SATELLITE_LOCATION = S.SHIP_TO_SATELLITE_LOCATION) or (T.SHIP_TO_SATELLITE_LOCATION IS NULL and S.SHIP_TO_SATELLITE_LOCATION IS NULL)) and
		((T.CLASS_PICTURE_RELEASE_DATE = S.CLASS_PICTURE_RELEASE_DATE) or (T.CLASS_PICTURE_RELEASE_DATE IS NULL and S.CLASS_PICTURE_RELEASE_DATE IS NULL))
        )

  
  

  



&


/*-----------------------------------------------*/
/* TASK No. 13 */
/* Analyze integration table */



begin
    dbms_stats.gather_table_stats(
	ownname => 'RAX_APP_USER',
	tabname => 'I$_OMS3_LT_APO_STG2015001',
	estimate_percent => dbms_stats.auto_sample_size
    );
end;



&


/*-----------------------------------------------*/
/* TASK No. 14 */
/* Create Index on flow table */

create index	RAX_APP_USER.I$_OMS3_LT_APO_STG_IDX2015001
on		RAX_APP_USER.I$_OMS3_LT_APO_STG2015001 (APO_KEY)
NOLOGGING

&


/*-----------------------------------------------*/
/* TASK No. 15 */
/* Merge Rows */

merge into	ODS_STAGE.OMS3_LT_APO_STG T
using	RAX_APP_USER.I$_OMS3_LT_APO_STG2015001 S
on	(
		T.APO_KEY=S.APO_KEY
	)
when matched
then update set
	T.DESCRIPTION	= S.DESCRIPTION,
	T.ACCOUNT_ID	= S.ACCOUNT_ID,
	T.GRAD_YEAR	= S.GRAD_YEAR,
	T.STATUS	= S.STATUS,
	T.ACCOUNT_NAME	= S.ACCOUNT_NAME,
	T.PROGRAM_TYPE	= S.PROGRAM_TYPE,
	T.PRICE_PROGRAM_NAME	= S.PRICE_PROGRAM_NAME,
	T.PHOTOGRAPHY_LOCATION	= S.PHOTOGRAPHY_LOCATION,
	T.GLOSSIES_REQD	= S.GLOSSIES_REQD,
	T.YEARBOOK_POSE_REQD	= S.YEARBOOK_POSE_REQD,
	T.PUBLISHER	= S.PUBLISHER,
	T.OTHER_PUBLISHER	= S.OTHER_PUBLISHER,
	T.SHIP_PROOFS_TO	= S.SHIP_PROOFS_TO,
	T.SHIP_ORDERS_TO	= S.SHIP_ORDERS_TO,
	T.SHIP_GLOSSIES_TO	= S.SHIP_GLOSSIES_TO,
	T.SHIP_PROOFS_STUDIO_CODE	= S.SHIP_PROOFS_STUDIO_CODE,
	T.SHIP_ORDERS_STUDIO_CODE	= S.SHIP_ORDERS_STUDIO_CODE,
	T.SHIP_GLOSSIES_STUDIO_CODE	= S.SHIP_GLOSSIES_STUDIO_CODE,
	T.TERRITORY_GROUP_ID	= S.TERRITORY_GROUP_ID,
	T.SHIP_PROOFS_STUDIO_ATTN	= S.SHIP_PROOFS_STUDIO_ATTN,
	T.SHIP_ORDERS_STUDIO_ATTN	= S.SHIP_ORDERS_STUDIO_ATTN,
	T.SHIP_GLOSSIES_STUDIO_ATTN	= S.SHIP_GLOSSIES_STUDIO_ATTN,
	T.COMMISSION_PER_CUST	= S.COMMISSION_PER_CUST,
	T.COMMISSION_PERCENTAGE	= S.COMMISSION_PERCENTAGE,
	T.COMMISSION_GUARANTEED	= S.COMMISSION_GUARANTEED,
	T.COMMISSION_SPECIAL	= S.COMMISSION_SPECIAL,
	T.ORDER_RETURN_MSG_REQD	= S.ORDER_RETURN_MSG_REQD,
	T.ORDER_REMINDER_REQD	= S.ORDER_REMINDER_REQD,
	T.ORDER_ASSIST_REQD	= S.ORDER_ASSIST_REQD,
	T.INCLUDE_ORDER_FORM	= S.INCLUDE_ORDER_FORM,
	T.INCLUDE_RETURN_ENVELOPE	= S.INCLUDE_RETURN_ENVELOPE,
	T.ORDER_BY_PHONE_NO	= S.ORDER_BY_PHONE_NO,
	T.ORDER_ENQUIRY_NO	= S.ORDER_ENQUIRY_NO,
	T.YEARBOOK_POSESTYLE_1	= S.YEARBOOK_POSESTYLE_1,
	T.YEARBOOK_POSESTYLE_2	= S.YEARBOOK_POSESTYLE_2,
	T.YEARBOOK_POSESTYLE_OTHER1	= S.YEARBOOK_POSESTYLE_OTHER1,
	T.YEARBOOK_POSESTYLE_OTHER2	= S.YEARBOOK_POSESTYLE_OTHER2,
	T.YEARBOOK_BACKGROUND1	= S.YEARBOOK_BACKGROUND1,
	T.YEARBOOK_BACKGROUND2	= S.YEARBOOK_BACKGROUND2,
	T.YEARBOOK_BGROUND_OTHER1	= S.YEARBOOK_BGROUND_OTHER1,
	T.YEARBOOK_BGROUND_OTHER2	= S.YEARBOOK_BGROUND_OTHER2,
	T.YEARBOOK_OUTFIT1	= S.YEARBOOK_OUTFIT1,
	T.YEARBOOK_OUTFIT2	= S.YEARBOOK_OUTFIT2,
	T.YEARBOOK_OUTFIT_OTHER1	= S.YEARBOOK_OUTFIT_OTHER1,
	T.YEARBOOK_OUTFIT_OTHER2	= S.YEARBOOK_OUTFIT_OTHER2,
	T.YEARBOOK_SPL_INST	= S.YEARBOOK_SPL_INST,
	T.GLOSSIES_OUTPUT	= S.GLOSSIES_OUTPUT,
	T.GLOSSIES_PAPER_DEADLINE	= S.GLOSSIES_PAPER_DEADLINE,
	T.GLOSSIES_DEL_DEADLINE	= S.GLOSSIES_DEL_DEADLINE,
	T.MULTIPLE_IMAGES_OPTION	= S.MULTIPLE_IMAGES_OPTION,
	T.PRINTABLE_FRAMES	= S.PRINTABLE_FRAMES,
	T.TERRITORY_ID	= S.TERRITORY_ID,
	T.STUDIO_ID	= S.STUDIO_ID,
	T.PROCESSING_LAB	= S.PROCESSING_LAB,
	T.PUBLISHER_ADDRESS_LINE1	= S.PUBLISHER_ADDRESS_LINE1,
	T.PUBLISHER_ADDRESS_LINE2	= S.PUBLISHER_ADDRESS_LINE2,
	T.PUBLISHER_ADDRESS_LINE3	= S.PUBLISHER_ADDRESS_LINE3,
	T.PUBLISHER_CITY	= S.PUBLISHER_CITY,
	T.PUBLISHER_STATE	= S.PUBLISHER_STATE,
	T.PUBLISHER_ZIP_CODE	= S.PUBLISHER_ZIP_CODE,
	T.PUBLISHER_COUNTRY	= S.PUBLISHER_COUNTRY,
	T.PUBLISHER_PHONENO	= S.PUBLISHER_PHONENO,
	T.PUBLISHER_FAXNO	= S.PUBLISHER_FAXNO,
	T.PUBLISHER_EMAIL	= S.PUBLISHER_EMAIL,
	T.PUBLISHER_CONTACT_PERSON	= S.PUBLISHER_CONTACT_PERSON,
	T.ACCOUNT_ADDRESS_LINE1	= S.ACCOUNT_ADDRESS_LINE1,
	T.ACCOUNT_ADDRESS_LINE2	= S.ACCOUNT_ADDRESS_LINE2,
	T.ACCOUNT_ADDRESS_LINE3	= S.ACCOUNT_ADDRESS_LINE3,
	T.ACCOUNT_CITY	= S.ACCOUNT_CITY,
	T.ACCOUNT_STATE	= S.ACCOUNT_STATE,
	T.ACCOUNT_ZIP_CODE	= S.ACCOUNT_ZIP_CODE,
	T.ACCOUNT_COUNTRY	= S.ACCOUNT_COUNTRY,
	T.ACCOUNT_PHONENO	= S.ACCOUNT_PHONENO,
	T.ACCOUNT_CONTACT_PERSON	= S.ACCOUNT_CONTACT_PERSON,
	T.ACCOUNT_FAXNO	= S.ACCOUNT_FAXNO,
	T.ACCOUNT_EMAIL	= S.ACCOUNT_EMAIL,
	T.PUBLISHER_ACCT_NO	= S.PUBLISHER_ACCT_NO,
	T.VISION_JOB_NO	= S.VISION_JOB_NO,
	T.CURRENCY	= S.CURRENCY,
	T.CREATETS	= S.CREATETS,
	T.MODIFYTS	= S.MODIFYTS,
	T.CREATEUSERID	= S.CREATEUSERID,
	T.MODIFYUSERID	= S.MODIFYUSERID,
	T.CREATEPROGID	= S.CREATEPROGID,
	T.MODIFYPROGID	= S.MODIFYPROGID,
	T.LOCKID	= S.LOCKID,
	T.APO_ID	= S.APO_ID,
	T.CONFIRMED_PROCESSING_LAB	= S.CONFIRMED_PROCESSING_LAB,
	T.PHOTOTRACKER_DEL_DATE	= S.PHOTOTRACKER_DEL_DATE,
	T.SOLO_ACCESS	= S.SOLO_ACCESS,
	T.ESTIMATED_ENROLLMENT	= S.ESTIMATED_ENROLLMENT,
	T.TERRITORY_NOTES	= S.TERRITORY_NOTES,
	T.SELLER_FOR_ORDER	= S.SELLER_FOR_ORDER,
	T.LAB_REVISION_NO	= S.LAB_REVISION_NO,
	T.LAB_NOTES	= S.LAB_NOTES,
	T.BOYS_GOWN_COLOR_1	= S.BOYS_GOWN_COLOR_1,
	T.BOYS_TASSEL_COLOR_1	= S.BOYS_TASSEL_COLOR_1,
	T.GIRLS_GOWN_COLOR_1	= S.GIRLS_GOWN_COLOR_1,
	T.GIRLS_TASSEL_COLOR_1	= S.GIRLS_TASSEL_COLOR_1,
	T.BOYS_GOWN_COLOR_2	= S.BOYS_GOWN_COLOR_2,
	T.BOYS_TASSEL_COLOR_2	= S.BOYS_TASSEL_COLOR_2,
	T.GIRLS_GOWN_COLOR_2	= S.GIRLS_GOWN_COLOR_2,
	T.GIRLS_TASSEL_COLOR_2	= S.GIRLS_TASSEL_COLOR_2,
	T.NO_OF_PROOF_SETS	= S.NO_OF_PROOF_SETS,
	T.NO_OF_GLOSSY_SETS	= S.NO_OF_GLOSSY_SETS,
	T.STUDENT_ID_REQD	= S.STUDENT_ID_REQD,
	T.TAX_EXEMPT_CERTIFICATE_NUMBER	= S.TAX_EXEMPT_CERTIFICATE_NUMBER,
	T.TAX_EXEMPT	= S.TAX_EXEMPT,
	T.SELECT_ORDER_BY_PHONE_NO	= S.SELECT_ORDER_BY_PHONE_NO,
	T.SELECT_ORDER_ENQUIRY_NO	= S.SELECT_ORDER_ENQUIRY_NO,
	T.IS_PROOF_EXPRESS	= S.IS_PROOF_EXPRESS,
	T.GUARANTEED_DOLLAR_AMOUNT	= S.GUARANTEED_DOLLAR_AMOUNT,
	T.GRAD_ANNOUNCE_POSTER_INS	= S.GRAD_ANNOUNCE_POSTER_INS,
	T.CUSTOM_LANGUAGE	= S.CUSTOM_LANGUAGE,
	T.YB_SELECTION_ONLINE	= S.YB_SELECTION_ONLINE,
	T.ORDER_FORM_ITEM_ID	= S.ORDER_FORM_ITEM_ID,
	T.SUB_PROGRAM_TYPE	= S.SUB_PROGRAM_TYPE,
	T.MARKETING_CODE	= S.MARKETING_CODE,
	T.FLYER_ID	= S.FLYER_ID,
	T.SORT_TYPE	= S.SORT_TYPE,
	T.ENVELOPE_TYPE	= S.ENVELOPE_TYPE,
	T.VISUAL_MERCH_KEY	= S.VISUAL_MERCH_KEY,
	T.VISUAL_MERCH_ID	= S.VISUAL_MERCH_ID,
	T.REVISION_NO	= S.REVISION_NO,
	T.COMP_PROD_CODE	= S.COMP_PROD_CODE,
	T.COMP_DLVRY_TYPE	= S.COMP_DLVRY_TYPE,
	T.GRP_PROD_CODE	= S.GRP_PROD_CODE,
	T.GRP_DLVRY_TYPE	= S.GRP_DLVRY_TYPE,
	T.MODEL_GRADE	= S.MODEL_GRADE,
	T.MODEL_ETHNICITY	= S.MODEL_ETHNICITY,
	T.MODEL_GENDER	= S.MODEL_GENDER,
	T.SERVICE_CENTER	= S.SERVICE_CENTER,
	T.EVENT_IMAGE_COMPLETE	= S.EVENT_IMAGE_COMPLETE,
	T.SHIP_TO_ACCOUNT_BUFFER_DAYS	= S.SHIP_TO_ACCOUNT_BUFFER_DAYS,
	T.ORIGINAL_ORDER_FORM_DUE_DATE	= S.ORIGINAL_ORDER_FORM_DUE_DATE,
	T.RETAKE_ORDER_FORM_DUE_DATE	= S.RETAKE_ORDER_FORM_DUE_DATE,
	T.EXTERNAL_SYNC_FLAG	= S.EXTERNAL_SYNC_FLAG,
	T.FULFILLING_LAB_SYSTEM	= S.FULFILLING_LAB_SYSTEM,
	T.FINANCIAL_PROCESSING_SYSTEM	= S.FINANCIAL_PROCESSING_SYSTEM,
	T.ORIGINAL_BOOKING_REP	= S.ORIGINAL_BOOKING_REP,
	T.ORIGINAL_BOOKING_REP_NAME	= S.ORIGINAL_BOOKING_REP_NAME,
	T.SHIP_TO_SATELLITE_LOCATION	= S.SHIP_TO_SATELLITE_LOCATION,
	T.CLASS_PICTURE_RELEASE_DATE	= S.CLASS_PICTURE_RELEASE_DATE
	,                                                                                                                                               T.ODS_MODIFY_DATE	= sysdate
when not matched
then insert
	(
	T.APO_KEY,
	T.DESCRIPTION,
	T.ACCOUNT_ID,
	T.GRAD_YEAR,
	T.STATUS,
	T.ACCOUNT_NAME,
	T.PROGRAM_TYPE,
	T.PRICE_PROGRAM_NAME,
	T.PHOTOGRAPHY_LOCATION,
	T.GLOSSIES_REQD,
	T.YEARBOOK_POSE_REQD,
	T.PUBLISHER,
	T.OTHER_PUBLISHER,
	T.SHIP_PROOFS_TO,
	T.SHIP_ORDERS_TO,
	T.SHIP_GLOSSIES_TO,
	T.SHIP_PROOFS_STUDIO_CODE,
	T.SHIP_ORDERS_STUDIO_CODE,
	T.SHIP_GLOSSIES_STUDIO_CODE,
	T.TERRITORY_GROUP_ID,
	T.SHIP_PROOFS_STUDIO_ATTN,
	T.SHIP_ORDERS_STUDIO_ATTN,
	T.SHIP_GLOSSIES_STUDIO_ATTN,
	T.COMMISSION_PER_CUST,
	T.COMMISSION_PERCENTAGE,
	T.COMMISSION_GUARANTEED,
	T.COMMISSION_SPECIAL,
	T.ORDER_RETURN_MSG_REQD,
	T.ORDER_REMINDER_REQD,
	T.ORDER_ASSIST_REQD,
	T.INCLUDE_ORDER_FORM,
	T.INCLUDE_RETURN_ENVELOPE,
	T.ORDER_BY_PHONE_NO,
	T.ORDER_ENQUIRY_NO,
	T.YEARBOOK_POSESTYLE_1,
	T.YEARBOOK_POSESTYLE_2,
	T.YEARBOOK_POSESTYLE_OTHER1,
	T.YEARBOOK_POSESTYLE_OTHER2,
	T.YEARBOOK_BACKGROUND1,
	T.YEARBOOK_BACKGROUND2,
	T.YEARBOOK_BGROUND_OTHER1,
	T.YEARBOOK_BGROUND_OTHER2,
	T.YEARBOOK_OUTFIT1,
	T.YEARBOOK_OUTFIT2,
	T.YEARBOOK_OUTFIT_OTHER1,
	T.YEARBOOK_OUTFIT_OTHER2,
	T.YEARBOOK_SPL_INST,
	T.GLOSSIES_OUTPUT,
	T.GLOSSIES_PAPER_DEADLINE,
	T.GLOSSIES_DEL_DEADLINE,
	T.MULTIPLE_IMAGES_OPTION,
	T.PRINTABLE_FRAMES,
	T.TERRITORY_ID,
	T.STUDIO_ID,
	T.PROCESSING_LAB,
	T.PUBLISHER_ADDRESS_LINE1,
	T.PUBLISHER_ADDRESS_LINE2,
	T.PUBLISHER_ADDRESS_LINE3,
	T.PUBLISHER_CITY,
	T.PUBLISHER_STATE,
	T.PUBLISHER_ZIP_CODE,
	T.PUBLISHER_COUNTRY,
	T.PUBLISHER_PHONENO,
	T.PUBLISHER_FAXNO,
	T.PUBLISHER_EMAIL,
	T.PUBLISHER_CONTACT_PERSON,
	T.ACCOUNT_ADDRESS_LINE1,
	T.ACCOUNT_ADDRESS_LINE2,
	T.ACCOUNT_ADDRESS_LINE3,
	T.ACCOUNT_CITY,
	T.ACCOUNT_STATE,
	T.ACCOUNT_ZIP_CODE,
	T.ACCOUNT_COUNTRY,
	T.ACCOUNT_PHONENO,
	T.ACCOUNT_CONTACT_PERSON,
	T.ACCOUNT_FAXNO,
	T.ACCOUNT_EMAIL,
	T.PUBLISHER_ACCT_NO,
	T.VISION_JOB_NO,
	T.CURRENCY,
	T.CREATETS,
	T.MODIFYTS,
	T.CREATEUSERID,
	T.MODIFYUSERID,
	T.CREATEPROGID,
	T.MODIFYPROGID,
	T.LOCKID,
	T.APO_ID,
	T.CONFIRMED_PROCESSING_LAB,
	T.PHOTOTRACKER_DEL_DATE,
	T.SOLO_ACCESS,
	T.ESTIMATED_ENROLLMENT,
	T.TERRITORY_NOTES,
	T.SELLER_FOR_ORDER,
	T.LAB_REVISION_NO,
	T.LAB_NOTES,
	T.BOYS_GOWN_COLOR_1,
	T.BOYS_TASSEL_COLOR_1,
	T.GIRLS_GOWN_COLOR_1,
	T.GIRLS_TASSEL_COLOR_1,
	T.BOYS_GOWN_COLOR_2,
	T.BOYS_TASSEL_COLOR_2,
	T.GIRLS_GOWN_COLOR_2,
	T.GIRLS_TASSEL_COLOR_2,
	T.NO_OF_PROOF_SETS,
	T.NO_OF_GLOSSY_SETS,
	T.STUDENT_ID_REQD,
	T.TAX_EXEMPT_CERTIFICATE_NUMBER,
	T.TAX_EXEMPT,
	T.SELECT_ORDER_BY_PHONE_NO,
	T.SELECT_ORDER_ENQUIRY_NO,
	T.IS_PROOF_EXPRESS,
	T.GUARANTEED_DOLLAR_AMOUNT,
	T.GRAD_ANNOUNCE_POSTER_INS,
	T.CUSTOM_LANGUAGE,
	T.YB_SELECTION_ONLINE,
	T.ORDER_FORM_ITEM_ID,
	T.SUB_PROGRAM_TYPE,
	T.MARKETING_CODE,
	T.FLYER_ID,
	T.SORT_TYPE,
	T.ENVELOPE_TYPE,
	T.VISUAL_MERCH_KEY,
	T.VISUAL_MERCH_ID,
	T.REVISION_NO,
	T.COMP_PROD_CODE,
	T.COMP_DLVRY_TYPE,
	T.GRP_PROD_CODE,
	T.GRP_DLVRY_TYPE,
	T.MODEL_GRADE,
	T.MODEL_ETHNICITY,
	T.MODEL_GENDER,
	T.SERVICE_CENTER,
	T.EVENT_IMAGE_COMPLETE,
	T.SHIP_TO_ACCOUNT_BUFFER_DAYS,
	T.ORIGINAL_ORDER_FORM_DUE_DATE,
	T.RETAKE_ORDER_FORM_DUE_DATE,
	T.EXTERNAL_SYNC_FLAG,
	T.FULFILLING_LAB_SYSTEM,
	T.FINANCIAL_PROCESSING_SYSTEM,
	T.ORIGINAL_BOOKING_REP,
	T.ORIGINAL_BOOKING_REP_NAME,
	T.SHIP_TO_SATELLITE_LOCATION,
	T.CLASS_PICTURE_RELEASE_DATE
	,                                                                                                                                                T.ODS_CREATE_DATE,
	T.ODS_MODIFY_DATE
	)
values
	(
	S.APO_KEY,
	S.DESCRIPTION,
	S.ACCOUNT_ID,
	S.GRAD_YEAR,
	S.STATUS,
	S.ACCOUNT_NAME,
	S.PROGRAM_TYPE,
	S.PRICE_PROGRAM_NAME,
	S.PHOTOGRAPHY_LOCATION,
	S.GLOSSIES_REQD,
	S.YEARBOOK_POSE_REQD,
	S.PUBLISHER,
	S.OTHER_PUBLISHER,
	S.SHIP_PROOFS_TO,
	S.SHIP_ORDERS_TO,
	S.SHIP_GLOSSIES_TO,
	S.SHIP_PROOFS_STUDIO_CODE,
	S.SHIP_ORDERS_STUDIO_CODE,
	S.SHIP_GLOSSIES_STUDIO_CODE,
	S.TERRITORY_GROUP_ID,
	S.SHIP_PROOFS_STUDIO_ATTN,
	S.SHIP_ORDERS_STUDIO_ATTN,
	S.SHIP_GLOSSIES_STUDIO_ATTN,
	S.COMMISSION_PER_CUST,
	S.COMMISSION_PERCENTAGE,
	S.COMMISSION_GUARANTEED,
	S.COMMISSION_SPECIAL,
	S.ORDER_RETURN_MSG_REQD,
	S.ORDER_REMINDER_REQD,
	S.ORDER_ASSIST_REQD,
	S.INCLUDE_ORDER_FORM,
	S.INCLUDE_RETURN_ENVELOPE,
	S.ORDER_BY_PHONE_NO,
	S.ORDER_ENQUIRY_NO,
	S.YEARBOOK_POSESTYLE_1,
	S.YEARBOOK_POSESTYLE_2,
	S.YEARBOOK_POSESTYLE_OTHER1,
	S.YEARBOOK_POSESTYLE_OTHER2,
	S.YEARBOOK_BACKGROUND1,
	S.YEARBOOK_BACKGROUND2,
	S.YEARBOOK_BGROUND_OTHER1,
	S.YEARBOOK_BGROUND_OTHER2,
	S.YEARBOOK_OUTFIT1,
	S.YEARBOOK_OUTFIT2,
	S.YEARBOOK_OUTFIT_OTHER1,
	S.YEARBOOK_OUTFIT_OTHER2,
	S.YEARBOOK_SPL_INST,
	S.GLOSSIES_OUTPUT,
	S.GLOSSIES_PAPER_DEADLINE,
	S.GLOSSIES_DEL_DEADLINE,
	S.MULTIPLE_IMAGES_OPTION,
	S.PRINTABLE_FRAMES,
	S.TERRITORY_ID,
	S.STUDIO_ID,
	S.PROCESSING_LAB,
	S.PUBLISHER_ADDRESS_LINE1,
	S.PUBLISHER_ADDRESS_LINE2,
	S.PUBLISHER_ADDRESS_LINE3,
	S.PUBLISHER_CITY,
	S.PUBLISHER_STATE,
	S.PUBLISHER_ZIP_CODE,
	S.PUBLISHER_COUNTRY,
	S.PUBLISHER_PHONENO,
	S.PUBLISHER_FAXNO,
	S.PUBLISHER_EMAIL,
	S.PUBLISHER_CONTACT_PERSON,
	S.ACCOUNT_ADDRESS_LINE1,
	S.ACCOUNT_ADDRESS_LINE2,
	S.ACCOUNT_ADDRESS_LINE3,
	S.ACCOUNT_CITY,
	S.ACCOUNT_STATE,
	S.ACCOUNT_ZIP_CODE,
	S.ACCOUNT_COUNTRY,
	S.ACCOUNT_PHONENO,
	S.ACCOUNT_CONTACT_PERSON,
	S.ACCOUNT_FAXNO,
	S.ACCOUNT_EMAIL,
	S.PUBLISHER_ACCT_NO,
	S.VISION_JOB_NO,
	S.CURRENCY,
	S.CREATETS,
	S.MODIFYTS,
	S.CREATEUSERID,
	S.MODIFYUSERID,
	S.CREATEPROGID,
	S.MODIFYPROGID,
	S.LOCKID,
	S.APO_ID,
	S.CONFIRMED_PROCESSING_LAB,
	S.PHOTOTRACKER_DEL_DATE,
	S.SOLO_ACCESS,
	S.ESTIMATED_ENROLLMENT,
	S.TERRITORY_NOTES,
	S.SELLER_FOR_ORDER,
	S.LAB_REVISION_NO,
	S.LAB_NOTES,
	S.BOYS_GOWN_COLOR_1,
	S.BOYS_TASSEL_COLOR_1,
	S.GIRLS_GOWN_COLOR_1,
	S.GIRLS_TASSEL_COLOR_1,
	S.BOYS_GOWN_COLOR_2,
	S.BOYS_TASSEL_COLOR_2,
	S.GIRLS_GOWN_COLOR_2,
	S.GIRLS_TASSEL_COLOR_2,
	S.NO_OF_PROOF_SETS,
	S.NO_OF_GLOSSY_SETS,
	S.STUDENT_ID_REQD,
	S.TAX_EXEMPT_CERTIFICATE_NUMBER,
	S.TAX_EXEMPT,
	S.SELECT_ORDER_BY_PHONE_NO,
	S.SELECT_ORDER_ENQUIRY_NO,
	S.IS_PROOF_EXPRESS,
	S.GUARANTEED_DOLLAR_AMOUNT,
	S.GRAD_ANNOUNCE_POSTER_INS,
	S.CUSTOM_LANGUAGE,
	S.YB_SELECTION_ONLINE,
	S.ORDER_FORM_ITEM_ID,
	S.SUB_PROGRAM_TYPE,
	S.MARKETING_CODE,
	S.FLYER_ID,
	S.SORT_TYPE,
	S.ENVELOPE_TYPE,
	S.VISUAL_MERCH_KEY,
	S.VISUAL_MERCH_ID,
	S.REVISION_NO,
	S.COMP_PROD_CODE,
	S.COMP_DLVRY_TYPE,
	S.GRP_PROD_CODE,
	S.GRP_DLVRY_TYPE,
	S.MODEL_GRADE,
	S.MODEL_ETHNICITY,
	S.MODEL_GENDER,
	S.SERVICE_CENTER,
	S.EVENT_IMAGE_COMPLETE,
	S.SHIP_TO_ACCOUNT_BUFFER_DAYS,
	S.ORIGINAL_ORDER_FORM_DUE_DATE,
	S.RETAKE_ORDER_FORM_DUE_DATE,
	S.EXTERNAL_SYNC_FLAG,
	S.FULFILLING_LAB_SYSTEM,
	S.FINANCIAL_PROCESSING_SYSTEM,
	S.ORIGINAL_BOOKING_REP,
	S.ORIGINAL_BOOKING_REP_NAME,
	S.SHIP_TO_SATELLITE_LOCATION,
	S.CLASS_PICTURE_RELEASE_DATE
	,                                                                                                                                                sysdate,
	sysdate
	)

&


/*-----------------------------------------------*/
/* TASK No. 16 */
/* Commit transaction */

/*commit*/


/*-----------------------------------------------*/
/* TASK No. 17 */
/* Drop flow table */

drop table RAX_APP_USER.I$_OMS3_LT_APO_STG2015001 

&


/*-----------------------------------------------*/
/* TASK No. 1000008 */
/* Drop work table */

drop table RAX_APP_USER.C$_0OMS3_LT_APO_STG purge

&


/*-----------------------------------------------*/
/* TASK No. 18 */
/* Update CDC Load Status */

UPDATE ODS_OWN.ODS_CDC_LOAD_STATUS
SET LAST_CDC_COMPLETION_DATE=TO_DATE(
             SUBSTR(:v_sess_beg, 1, 19), 'RRRR-MM-DD HH24:MI:SS')
+ nvl((TIMEZONE_OFFSET/24), 0) 
WHERE ODS_TABLE_NAME=:v_cdc_load_table_name
AND CONTEXT_NAME = :v_env

/*
UPDATE ODS_OWN.ODS_CDC_LOAD_STATUS
SET LAST_CDC_COMPLETION_DATE=TO_DATE(
             SUBSTR(:v_sess_beg, 1, 19), 'RRRR-MM-DD HH24:MI:SS')
WHERE ODS_TABLE_NAME=:v_cdc_load_table_name
AND CONTEXT_NAME = :v_env
*/

&


/*-----------------------------------------------*/
/* TASK No. 19 */
/* Insert CDC Audit Record */

INSERT INTO RAX_APP_USER.ODS_CDC_LOAD_STATUS_AUDIT
(TABLE_NAME,
SESS_NO,                      
SESS_NAME,                    
SCEN_VERSION,                 
SESS_BEG,                     
ORIG_LAST_CDC_COMPLETION_DATE,
OVERLAP,
CREATE_DATE,
CONTEXT_NAME,
TIMEZONE_OFFSET              
)
select 
:v_cdc_load_table_name
,:v_sess_no
,'LOAD_ORDER_HEADER_PKG'
,'047'
,TO_DATE(SUBSTR(:v_sess_beg, 1, 19), 'RRRR-MM-DD HH24:MI:SS')
,TO_DATE (SUBSTR(:v_cdc_load_date, 1, 19),'YYYY-MM-DD HH24:MI:SS')
,:v_cdc_overlap
,SYSDATE
,:v_env
,TIMEZONE_OFFSET
from 
ODS_OWN.ODS_CDC_LOAD_STATUS
WHERE ODS_TABLE_NAME=:v_cdc_load_table_name
AND CONTEXT_NAME = :v_env

/*
INSERT INTO RAX_APP_USER.ODS_CDC_LOAD_STATUS_AUDIT
(TABLE_NAME,
SESS_NO,                      
SESS_NAME,                    
SCEN_VERSION,                 
SESS_BEG,                     
ORIG_LAST_CDC_COMPLETION_DATE,
OVERLAP,
CREATE_DATE,
CONTEXT_NAME              
)
values (
:v_cdc_load_table_name,
:v_sess_no,
'LOAD_ORDER_HEADER_PKG',
'047',
TO_DATE(
             SUBSTR(:v_sess_beg, 1, 19), 'RRRR-MM-DD HH24:MI:SS'),
TO_DATE (SUBSTR (:v_cdc_load_date, 1, 19),
                           'YYYY-MM-DD HH24:MI:SS'
                          )
,:v_cdc_overlap,
SYSDATE,
 :v_env)
*/


&
/*-----------------------------------------------*/