/* TASK No. 1 */

/* NONE or SET VARIABLE STATEMENT FOUND, CHECK ODI TASK NO. 1 */




/*-----------------------------------------------*/
/* TASK No. 2 */

/* SELECT STATEMENT FOUND, CHECK ODI TASK NO. 2 */




/*-----------------------------------------------*/
/* TASK No. 3 */

/* SELECT STATEMENT FOUND, CHECK ODI TASK NO. 3 */




/*-----------------------------------------------*/
/* TASK No. 4 */
/* Drop work table */

-- drop table RAX_APP_USER.C$_0STG_ORDER_LINE 

-- &


-- /*-----------------------------------------------*/
-- /* TASK No. 5 */
-- /* Create work table */

-- create table RAX_APP_USER.C$_0STG_ORDER_LINE
-- (
-- 	C1_SETTLED_AMOUNT	NUMBER(15,2) NULL,
-- 	C2_CUSTOMER_PO_NO	VARCHAR2(100) NULL,
-- 	C3_PRICING_UOM	VARCHAR2(40) NULL,
-- 	C4_PRIME_LINE_NO	NUMBER(5) NULL,
-- 	C5_ALLOCATION_LEAD_TIME	NUMBER(5) NULL,
-- 	C6_INVOICED_QUANTITY	NUMBER(14,4) NULL,
-- 	C7_DERIVED_FROM_ORDER_LINE_KEY	CHAR(24) NULL,
-- 	C8_CURRENT_WORK_ORDER_KEY	CHAR(24) NULL,
-- 	C9_DEPENDENCY_RATIO	NUMBER(14,4) NULL,
-- 	C10_CUSTOMER_PO_LINE_NO	VARCHAR2(10) NULL,
-- 	C11_DEPARTMENT_CODE	VARCHAR2(20) NULL,
-- 	C12_REQ_DELIVERY_DATE	DATE NULL,
-- 	C13_EXTN_SECONDARY_REASON_CODE	VARCHAR2(120) NULL,
-- 	C14_DISCOUNT_REFERENCE	VARCHAR2(100) NULL,
-- 	C15_EXTN_SPRAY_FINISH_INCLUDED	CHAR(1) NULL,
-- 	C16_ITEM_GROUP_CODE	VARCHAR2(20) NULL,
-- 	C17_GIFT_FLAG	CHAR(1) NULL,
-- 	C18_IS_COST_OVERRIDDEN	CHAR(1) NULL,
-- 	C19_MIN_SHIP_BY_DATE	DATE NULL,
-- 	C20_EXTN_LINEN_INCLUDED	CHAR(1) NULL,
-- 	C21_CHAINED_FROM_ORDER_HEADER_	CHAR(24) NULL,
-- 	C22_FULFILLMENT_TYPE	VARCHAR2(40) NULL,
-- 	C23_EXTN_CSR_CODE	VARCHAR2(20) NULL,
-- 	C24_UNIT_PRICE	NUMBER(19,6) NULL,
-- 	C25_EXTN_CURRENT_SHEET_EQUIVAL	NUMBER(4) NULL,
-- 	C26_APPT_STATUS	VARCHAR2(40) NULL,
-- 	C27_WAIT_FOR_SEQ_LINE	CHAR(1) NULL,
-- 	C28_IS_PRICE_LOCKED	CHAR(1) NULL,
-- 	C29_DEPENDENT_ON_LINE_KEY	CHAR(24) NULL,
-- 	C30_SEGMENT_TYPE	VARCHAR2(40) NULL,
-- 	C31_CREATEUSERID	VARCHAR2(40) NULL,
-- 	C32_ITEM_WEIGHT_UOM	VARCHAR2(40) NULL,
-- 	C33_ALTERNATE_ITEM_ID	CHAR(40) NULL,
-- 	C34_SCHED_FAILURE_REASON_CODE	VARCHAR2(40) NULL,
-- 	C35_PROMISED_APPT_START_DATE	DATE NULL,
-- 	C36_RESERVATION_ID	VARCHAR2(40) NULL,
-- 	C37_PIPELINE_KEY	CHAR(24) NULL,
-- 	C38_ITEM_ID	CHAR(40) NULL,
-- 	C39_EXTN_NO_OF_POSES_PER_UNIT	NUMBER(2) NULL,
-- 	C40_BASIC_CAPACITY_REQUIRED	NUMBER(14,4) NULL,
-- 	C41_UNIT_COST	NUMBER(19,6) NULL,
-- 	C42_OVER_RECEIPT_QUANTITY	NUMBER(14,4) NULL,
-- 	C43_CANNOT_COMPLETE_AFTER_DATE	DATE NULL,
-- 	C44_ECCN_NO	VARCHAR2(40) NULL,
-- 	C45_SUB_LINE_NO	NUMBER(5) NULL,
-- 	C46_CREATEPROGID	VARCHAR2(40) NULL,
-- 	C47_HOLD_FLAG	CHAR(1) NULL,
-- 	C48_MODIFYPROGID	VARCHAR2(40) NULL,
-- 	C49_UOM	VARCHAR2(40) NULL,
-- 	C50_DISTRIBUTION_RULE_ID	CHAR(40) NULL,
-- 	C51_PRODUCT_LINE	VARCHAR2(100) NULL,
-- 	C52_SHIP_TO_ID	VARCHAR2(40) NULL,
-- 	C53_INVOICED_EXTENDED_PRICE	NUMBER(15,2) NULL,
-- 	C54_SPLIT_QTY	NUMBER(14,4) NULL,
-- 	C55_ISBN	VARCHAR2(40) NULL,
-- 	C56_CANNOT_COMPLETE_BEFORE_DAT	DATE NULL,
-- 	C57_EARLIEST_DELIVERY_DATE	DATE NULL,
-- 	C58_LINE_TOTAL	NUMBER(15,2) NULL,
-- 	C59_OTHER_CHARGES	NUMBER(15,2) NULL,
-- 	C60_CARRIER_SERVICE_CODE	VARCHAR2(40) NULL,
-- 	C61_SCAC	VARCHAR2(40) NULL,
-- 	C62_SUPPLIER_ITEM_DESCRIPTION	VARCHAR2(200) NULL,
-- 	C63_ORDERED_QTY	NUMBER(14,4) NULL,
-- 	C64_IS_FIRM_PREDEFINED_NODE	CHAR(1) NULL,
-- 	C65_EXTN_PRIMARY_REASON_CODE	VARCHAR2(120) NULL,
-- 	C66_NMFC_CODE	VARCHAR2(40) NULL,
-- 	C67_CARRIER_ACCOUNT_NO	VARCHAR2(40) NULL,
-- 	C68_LINE_SEQ_NO	VARCHAR2(40) NULL,
-- 	C69_RESHIP_PARENT_LINE_KEY	CHAR(24) NULL,
-- 	C70_INTENTIONAL_BACKORDER	CHAR(1) NULL,
-- 	C71_SERIAL_NO	VARCHAR2(40) NULL,
-- 	C72_IS_PRICE_INFO_ONLY	CHAR(1) NULL,
-- 	C73_ITEM_DESCRIPTION	VARCHAR2(200) NULL,
-- 	C74_PACKLIST_TYPE	VARCHAR2(20) NULL,
-- 	C75_LIST_PRICE	NUMBER(19,6) NULL,
-- 	C76_FIXED_CAPACITY_QTY_PER_LIN	NUMBER(14,4) NULL,
-- 	C77_MODIFYUSERID	VARCHAR2(40) NULL,
-- 	C78_EXTN_IS_TERRITORY_PROOF_SA	CHAR(1) NULL,
-- 	C79_RECEIVED_QUANTITY	NUMBER(14,4) NULL,
-- 	C80_EXTN_TAXABLE	CHAR(1) NULL,
-- 	C81_SEGMENT	VARCHAR2(40) NULL,
-- 	C82_EXTN_TRAN_DEPENDENCY	VARCHAR2(40) NULL,
-- 	C83_IS_CAPACITY_OVERRIDDEN	CHAR(1) NULL,
-- 	C84_DERIVED_FROM_ORDER_RELEASE	CHAR(24) NULL,
-- 	C85_NMFC_CLASS	VARCHAR2(100) NULL,
-- 	C86_UPC_CODE	VARCHAR2(40) NULL,
-- 	C87_DEPENDENCY_SHIPPING_RULE	CHAR(2) NULL,
-- 	C88_ACTUAL_PRICING_QUANTITY	NUMBER(14,4) NULL,
-- 	C89_ORDER_LINE_KEY	CHAR(24) NULL,
-- 	C90_EXTN_ACCOUNTING_TYPE	VARCHAR2(40) NULL,
-- 	C91_LOCKID	NUMBER(5) NULL,
-- 	C92_FOB	VARCHAR2(40) NULL,
-- 	C93_MANUFACTURER_ITEM_DESC	VARCHAR2(254) NULL,
-- 	C94_FUTURE_AVAIL_DATE	DATE NULL,
-- 	C95_TAX_PRODUCT_CODE	VARCHAR2(40) NULL,
-- 	C96_EXTN_DISTINCT_NO_OF_POSES	NUMBER(5) NULL,
-- 	C97_FIRST_ITER_SEQ_NO	NUMBER(10) NULL,
-- 	C98_EXTN_ADDITIONAL_POSES	NUMBER(4) NULL,
-- 	C99_RECEIVING_NODE	CHAR(24) NULL,
-- 	C100_SETTLED_QUANTITY	NUMBER(14,4) NULL,
-- 	C101_EXTN_SPRAY_FINISH_ALLOWED	CHAR(1) NULL,
-- 	C102_SHIPMENT_CONSOL_GROUP_ID	CHAR(24) NULL,
-- 	C103_CUSTOMER_ITEM	VARCHAR2(40) NULL,
-- 	C104_HOLD_REASON_CODE	VARCHAR2(40) NULL,
-- 	C105_KIT_CODE	VARCHAR2(20) NULL,
-- 	C106_EARLIEST_SHIP_DATE	DATE NULL,
-- 	C107_CAN_ADD_SERVICE_LINES	CHAR(1) NULL,
-- 	C108_CONDITION_VARIABLE_2	VARCHAR2(40) NULL,
-- 	C109_ORDER_CLASS	VARCHAR2(20) NULL,
-- 	C110_CREATETS	DATE NULL,
-- 	C111_SHIPPED_QUANTITY	NUMBER(14,4) NULL,
-- 	C112_RESERVATION_MANDATORY	CHAR(1) NULL,
-- 	C113_EXTN_IS_PACKAGE_SUBSTITUT	CHAR(1) NULL,
-- 	C114_EXTN_CR_NUMBER	VARCHAR2(12) NULL,
-- 	C115_CONDITION_VARIABLE_1	VARCHAR2(40) NULL,
-- 	C116_IS_PROCUREMENT_ALLOWED	CHAR(1) NULL,
-- 	C117_SUPPLIER_ITEM	VARCHAR2(40) NULL,
-- 	C118_PERSONALIZE_FLAG	CHAR(1) NULL,
-- 	C119_KIT_QTY	NUMBER(14,4) NULL,
-- 	C120_DERIVED_FROM_ORDER_HEADER	CHAR(24) NULL,
-- 	C121_ORDERING_UOM	VARCHAR2(40) NULL,
-- 	C122_TAX	NUMBER(15,2) NULL,
-- 	C123_CUSTOMER_ITEM_DESCRIPTION	VARCHAR2(200) NULL,
-- 	C124_RESERVATION_POOL	VARCHAR2(40) NULL,
-- 	C125_LINE_TYPE	VARCHAR2(20) NULL,
-- 	C126_MARK_FOR_KEY	CHAR(24) NULL,
-- 	C127_IS_FORWARDING_ALLOWED	CHAR(1) NULL,
-- 	C128_EXTN_LOC_PER_QTY	NUMBER(2) NULL,
-- 	C129_NMFC_DESCRIPTION	VARCHAR2(100) NULL,
-- 	C130_PROMISED_APPT_END_DATE	DATE NULL,
-- 	C131_CAPACITY_UOM	VARCHAR2(40) NULL,
-- 	C132_ORDER_HEADER_KEY	CHAR(24) NULL,
-- 	C133_IMPORT_LICENSE_EXP_DATE	DATE NULL,
-- 	C134_ORIG_ORDER_LINE_KEY	CHAR(24) NULL,
-- 	C135_EARLIEST_SCHEDULE_DATE	DATE NULL,
-- 	C136_EXTN_CAN_SUBSTITUTE_PACKA	CHAR(1) NULL,
-- 	C137_COMMITTED_QUANTITY	NUMBER(14,4) NULL,
-- 	C138_IS_STANDALONE_SERVICE	CHAR(1) NULL,
-- 	C139_TAXABLE_FLAG	CHAR(1) NULL,
-- 	C140_FIXED_PRICING_QTY_PER_LIN	NUMBER(14,4) NULL,
-- 	C141_EXTN_CONFIG_POINT_EQUIVAL	NUMBER(4) NULL,
-- 	C142_BUNDLE_PARENT_ORDER_LINE_	CHAR(24) NULL,
-- 	C143_EXTN_PKG_REFERENCE	VARCHAR2(40) NULL,
-- 	C144_EXTN_IS_PERFECT_PACKAGE	CHAR(1) NULL,
-- 	C145_INVOICE_COMPLETE	CHAR(1) NULL,
-- 	C146_RETURN_REASON	VARCHAR2(40) NULL,
-- 	C147_BUYER_RECEIVING_NODE_ID	CHAR(24) NULL,
-- 	C148_SHIPNODE_KEY	CHAR(24) NULL,
-- 	C149_SHIP_TO_KEY	CHAR(24) NULL,
-- 	C150_EXTN_REQUESTED_BY	VARCHAR2(40) NULL,
-- 	C151_EXTN_REQUESTED_DATE	DATE NULL,
-- 	C152_PROCURE_FROM_NODE	CHAR(24) NULL,
-- 	C153_BUYER_MARK_FOR_NODE_ID	CHAR(24) NULL,
-- 	C154_CHAINED_FROM_ORDER_LINE_K	CHAR(24) NULL,
-- 	C155_PERSONALIZE_CODE	VARCHAR2(20) NULL,
-- 	C156_REPRICING_QUANTITY	NUMBER(14,4) NULL,
-- 	C157_EXTN_IS_PROOF_EXPRESS	CHAR(1) NULL,
-- 	C158_EXTN_TAX_CODE	VARCHAR2(20) NULL,
-- 	C159_HARMONIZED_CODE	VARCHAR2(40) NULL,
-- 	C160_DISCOUNT_PERCENTAGE	NUMBER(5,2) NULL,
-- 	C161_EXTN_CURRENT_NO_OF_POSES	NUMBER(4) NULL,
-- 	C162_RETAIL_PRICE	NUMBER(19,6) NULL,
-- 	C163_PRICING_QUANTITY_CONV_FAC	NUMBER(14,4) NULL,
-- 	C164_EXTN_CURRENT_POINT_EQUIVA	NUMBER(4) NULL,
-- 	C165_INVOICED_LINE_TOTAL	NUMBER(15,2) NULL,
-- 	C166_ITEM_WEIGHT	NUMBER(14,4) NULL,
-- 	C167_SUPPLIER_CODE	CHAR(30) NULL,
-- 	C168_TAX_EXEMPTION_CERTIFICATE	VARCHAR2(40) NULL,
-- 	C169_MODIFYTS	DATE NULL,
-- 	C170_DELIVERY_CODE	VARCHAR2(40) NULL,
-- 	C171_EXTN_SORT_SEQ_NO	VARCHAR2(40) NULL,
-- 	C172_ITEM_SHORT_DESCRIPTION	VARCHAR2(100) NULL,
-- 	C173_PARENT_OF_DEPENDENT_GROUP	CHAR(1) NULL,
-- 	C174_PICKABLE_FLAG	CHAR(1) NULL,
-- 	C175_REQ_SHIP_DATE	DATE NULL,
-- 	C176_EXTN_CONFIG_SHEET_EQUIVAL	NUMBER(4) NULL,
-- 	C177_EXTN_ADDITIONAL_POINTS	NUMBER(4) NULL,
-- 	C178_OPTION_CAPACITY_REQUIRED	NUMBER(14,4) NULL,
-- 	C179_EXTN_LINEN_ALLOWED	CHAR(1) NULL,
-- 	C180_CANNOT_MEET_APPT	CHAR(1) NULL,
-- 	C181_MANUFACTURER_NAME	VARCHAR2(50) NULL,
-- 	C182_EXTN_SHEET_UNITS_PER_QTY	NUMBER(2) NULL,
-- 	C183_COST_CURRENCY	VARCHAR2(20) NULL,
-- 	C184_DELIVERY_METHOD	VARCHAR2(40) NULL,
-- 	C185_INVOICE_BASED_ON_ACTUALS	CHAR(1) NULL,
-- 	C186_PURPOSE	VARCHAR2(40) NULL,
-- 	C187_REQ_CANCEL_DATE	DATE NULL,
-- 	C188_MAINTAIN_RATIO	CHAR(1) NULL,
-- 	C189_IMPORT_LICENSE_NO	VARCHAR2(40) NULL,
-- 	C190_FILL_QUANTITY	NUMBER(14,4) NULL,
-- 	C191_COUNTRY_OF_ORIGIN	VARCHAR2(40) NULL,
-- 	C192_TRAN_DISCREPANCY_QTY	NUMBER(14,4) NULL,
-- 	C193_MERGE_NODE	CHAR(24) NULL,
-- 	C194_PRODUCT_CLASS	CHAR(10) NULL,
-- 	C195_DISCOUNT_TYPE	VARCHAR2(20) NULL,
-- 	C196_ALLOCATE_DATE	DATE NULL,
-- 	C197_EXTN_PERSONALIZATION_INCL	CHAR(1) NULL,
-- 	C198_PRICING_QUANTITY_STRATEGY	VARCHAR2(20) NULL,
-- 	C199_EXTN_TCREDIT_PERCENTAGE	NUMBER(3) NULL,
-- 	C200_ORIGINAL_ORDERED_QTY	NUMBER(14,4) NULL,
-- 	C201_SHIP_TOGETHER_NO	VARCHAR2(40) NULL,
-- 	C202_EXTN_ADDITIONAL_SHEETS	NUMBER(4) NULL,
-- 	C203_PRICING_QUANTITY	NUMBER(14,4) NULL,
-- 	C204_EXTN_TAX_INCLUSIVE	CHAR(1) NULL,
-- 	C205_SOURCE_FROM_ORGANIZATION	CHAR(24) NULL,
-- 	C206_PRICING_DATE	DATE NULL,
-- 	C207_MANUFACTURER_ITEM	VARCHAR2(100) NULL,
-- 	C208_LAST_ITER_SEQ_NO	NUMBER(10) NULL,
-- 	C209_SCHEDULE_B_CODE	VARCHAR2(40) NULL,
-- 	C210_TIMEZONE	VARCHAR2(40) NULL,
-- 	C211_INVOICED_PRICING_QUANTITY	NUMBER(14,4) NULL
-- )
-- NOLOGGING

-- &


-- /*-----------------------------------------------*/
-- /* TASK No. 6 */
-- /* Load data */

-- /* SOURCE CODE */
-- select	
-- 	OL.SETTLED_AMOUNT	   C1_SETTLED_AMOUNT,
-- 	OL.CUSTOMER_PO_NO	   C2_CUSTOMER_PO_NO,
-- 	OL.PRICING_UOM	   C3_PRICING_UOM,
-- 	OL.PRIME_LINE_NO	   C4_PRIME_LINE_NO,
-- 	OL.ALLOCATION_LEAD_TIME	   C5_ALLOCATION_LEAD_TIME,
-- 	OL.INVOICED_QUANTITY	   C6_INVOICED_QUANTITY,
-- 	OL.DERIVED_FROM_ORDER_LINE_KEY	   C7_DERIVED_FROM_ORDER_LINE_KEY,
-- 	OL.CURRENT_WORK_ORDER_KEY	   C8_CURRENT_WORK_ORDER_KEY,
-- 	OL.DEPENDENCY_RATIO	   C9_DEPENDENCY_RATIO,
-- 	OL.CUSTOMER_PO_LINE_NO	   C10_CUSTOMER_PO_LINE_NO,
-- 	OL.DEPARTMENT_CODE	   C11_DEPARTMENT_CODE,
-- 	OL.REQ_DELIVERY_DATE	   C12_REQ_DELIVERY_DATE,
-- 	OL.EXTN_SECONDARY_REASON_CODE	   C13_EXTN_SECONDARY_REASON_CODE,
-- 	OL.DISCOUNT_REFERENCE	   C14_DISCOUNT_REFERENCE,
-- 	OL.EXTN_SPRAY_FINISH_INCLUDED	   C15_EXTN_SPRAY_FINISH_INCLUDED,
-- 	OL.ITEM_GROUP_CODE	   C16_ITEM_GROUP_CODE,
-- 	OL.GIFT_FLAG	   C17_GIFT_FLAG,
-- 	OL.IS_COST_OVERRIDDEN	   C18_IS_COST_OVERRIDDEN,
-- 	OL.MIN_SHIP_BY_DATE	   C19_MIN_SHIP_BY_DATE,
-- 	OL.EXTN_LINEN_INCLUDED	   C20_EXTN_LINEN_INCLUDED,
-- 	OL.CHAINED_FROM_ORDER_HEADER_KEY	   C21_CHAINED_FROM_ORDER_HEADER_,
-- 	OL.FULFILLMENT_TYPE	   C22_FULFILLMENT_TYPE,
-- 	OL.EXTN_CSR_CODE	   C23_EXTN_CSR_CODE,
-- 	OL.UNIT_PRICE	   C24_UNIT_PRICE,
-- 	OL.EXTN_CURRENT_SHEET_EQUIVALENT	   C25_EXTN_CURRENT_SHEET_EQUIVAL,
-- 	OL.APPT_STATUS	   C26_APPT_STATUS,
-- 	OL.WAIT_FOR_SEQ_LINE	   C27_WAIT_FOR_SEQ_LINE,
-- 	OL.IS_PRICE_LOCKED	   C28_IS_PRICE_LOCKED,
-- 	OL.DEPENDENT_ON_LINE_KEY	   C29_DEPENDENT_ON_LINE_KEY,
-- 	OL.SEGMENT_TYPE	   C30_SEGMENT_TYPE,
-- 	OL.CREATEUSERID	   C31_CREATEUSERID,
-- 	OL.ITEM_WEIGHT_UOM	   C32_ITEM_WEIGHT_UOM,
-- 	OL.ALTERNATE_ITEM_ID	   C33_ALTERNATE_ITEM_ID,
-- 	OL.SCHED_FAILURE_REASON_CODE	   C34_SCHED_FAILURE_REASON_CODE,
-- 	OL.PROMISED_APPT_START_DATE	   C35_PROMISED_APPT_START_DATE,
-- 	OL.RESERVATION_ID	   C36_RESERVATION_ID,
-- 	OL.PIPELINE_KEY	   C37_PIPELINE_KEY,
-- 	OL.ITEM_ID	   C38_ITEM_ID,
-- 	OL.EXTN_NO_OF_POSES_PER_UNIT	   C39_EXTN_NO_OF_POSES_PER_UNIT,
-- 	OL.BASIC_CAPACITY_REQUIRED	   C40_BASIC_CAPACITY_REQUIRED,
-- 	OL.UNIT_COST	   C41_UNIT_COST,
-- 	OL.OVER_RECEIPT_QUANTITY	   C42_OVER_RECEIPT_QUANTITY,
-- 	OL.CANNOT_COMPLETE_AFTER_DATE	   C43_CANNOT_COMPLETE_AFTER_DATE,
-- 	OL.ECCN_NO	   C44_ECCN_NO,
-- 	OL.SUB_LINE_NO	   C45_SUB_LINE_NO,
-- 	OL.CREATEPROGID	   C46_CREATEPROGID,
-- 	OL.HOLD_FLAG	   C47_HOLD_FLAG,
-- 	OL.MODIFYPROGID	   C48_MODIFYPROGID,
-- 	OL.UOM	   C49_UOM,
-- 	OL.DISTRIBUTION_RULE_ID	   C50_DISTRIBUTION_RULE_ID,
-- 	OL.PRODUCT_LINE	   C51_PRODUCT_LINE,
-- 	OL.SHIP_TO_ID	   C52_SHIP_TO_ID,
-- 	OL.INVOICED_EXTENDED_PRICE	   C53_INVOICED_EXTENDED_PRICE,
-- 	OL.SPLIT_QTY	   C54_SPLIT_QTY,
-- 	OL.ISBN	   C55_ISBN,
-- 	OL.CANNOT_COMPLETE_BEFORE_DATE	   C56_CANNOT_COMPLETE_BEFORE_DAT,
-- 	OL.EARLIEST_DELIVERY_DATE	   C57_EARLIEST_DELIVERY_DATE,
-- 	OL.LINE_TOTAL	   C58_LINE_TOTAL,
-- 	OL.OTHER_CHARGES	   C59_OTHER_CHARGES,
-- 	OL.CARRIER_SERVICE_CODE	   C60_CARRIER_SERVICE_CODE,
-- 	OL.SCAC	   C61_SCAC,
-- 	OL.SUPPLIER_ITEM_DESCRIPTION	   C62_SUPPLIER_ITEM_DESCRIPTION,
-- 	OL.ORDERED_QTY	   C63_ORDERED_QTY,
-- 	OL.IS_FIRM_PREDEFINED_NODE	   C64_IS_FIRM_PREDEFINED_NODE,
-- 	OL.EXTN_PRIMARY_REASON_CODE	   C65_EXTN_PRIMARY_REASON_CODE,
-- 	OL.NMFC_CODE	   C66_NMFC_CODE,
-- 	OL.CARRIER_ACCOUNT_NO	   C67_CARRIER_ACCOUNT_NO,
-- 	OL.LINE_SEQ_NO	   C68_LINE_SEQ_NO,
-- 	OL.RESHIP_PARENT_LINE_KEY	   C69_RESHIP_PARENT_LINE_KEY,
-- 	OL.INTENTIONAL_BACKORDER	   C70_INTENTIONAL_BACKORDER,
-- 	OL.SERIAL_NO	   C71_SERIAL_NO,
-- 	OL.IS_PRICE_INFO_ONLY	   C72_IS_PRICE_INFO_ONLY,
-- 	OL.ITEM_DESCRIPTION	   C73_ITEM_DESCRIPTION,
-- 	OL.PACKLIST_TYPE	   C74_PACKLIST_TYPE,
-- 	OL.LIST_PRICE	   C75_LIST_PRICE,
-- 	OL.FIXED_CAPACITY_QTY_PER_LINE	   C76_FIXED_CAPACITY_QTY_PER_LIN,
-- 	OL.MODIFYUSERID	   C77_MODIFYUSERID,
-- 	OL.EXTN_IS_TERRITORY_PROOF_SAMPLE	   C78_EXTN_IS_TERRITORY_PROOF_SA,
-- 	OL.RECEIVED_QUANTITY	   C79_RECEIVED_QUANTITY,
-- 	OL.EXTN_TAXABLE	   C80_EXTN_TAXABLE,
-- 	OL.SEGMENT	   C81_SEGMENT,
-- 	OL.EXTN_TRAN_DEPENDENCY	   C82_EXTN_TRAN_DEPENDENCY,
-- 	OL.IS_CAPACITY_OVERRIDDEN	   C83_IS_CAPACITY_OVERRIDDEN,
-- 	OL.DERIVED_FROM_ORDER_RELEASE_KEY	   C84_DERIVED_FROM_ORDER_RELEASE,
-- 	OL.NMFC_CLASS	   C85_NMFC_CLASS,
-- 	OL.UPC_CODE	   C86_UPC_CODE,
-- 	OL.DEPENDENCY_SHIPPING_RULE	   C87_DEPENDENCY_SHIPPING_RULE,
-- 	OL.ACTUAL_PRICING_QUANTITY	   C88_ACTUAL_PRICING_QUANTITY,
-- 	OL.ORDER_LINE_KEY	   C89_ORDER_LINE_KEY,
-- 	OL.EXTN_ACCOUNTING_TYPE	   C90_EXTN_ACCOUNTING_TYPE,
-- 	OL.LOCKID	   C91_LOCKID,
-- 	OL.FOB	   C92_FOB,
-- 	OL.MANUFACTURER_ITEM_DESC	   C93_MANUFACTURER_ITEM_DESC,
-- 	OL.FUTURE_AVAIL_DATE	   C94_FUTURE_AVAIL_DATE,
-- 	OL.TAX_PRODUCT_CODE	   C95_TAX_PRODUCT_CODE,
-- 	OL.EXTN_DISTINCT_NO_OF_POSES	   C96_EXTN_DISTINCT_NO_OF_POSES,
-- 	OL.FIRST_ITER_SEQ_NO	   C97_FIRST_ITER_SEQ_NO,
-- 	OL.EXTN_ADDITIONAL_POSES	   C98_EXTN_ADDITIONAL_POSES,
-- 	OL.RECEIVING_NODE	   C99_RECEIVING_NODE,
-- 	OL.SETTLED_QUANTITY	   C100_SETTLED_QUANTITY,
-- 	OL.EXTN_SPRAY_FINISH_ALLOWED	   C101_EXTN_SPRAY_FINISH_ALLOWED,
-- 	OL.SHIPMENT_CONSOL_GROUP_ID	   C102_SHIPMENT_CONSOL_GROUP_ID,
-- 	OL.CUSTOMER_ITEM	   C103_CUSTOMER_ITEM,
-- 	OL.HOLD_REASON_CODE	   C104_HOLD_REASON_CODE,
-- 	OL.KIT_CODE	   C105_KIT_CODE,
-- 	OL.EARLIEST_SHIP_DATE	   C106_EARLIEST_SHIP_DATE,
-- 	OL.CAN_ADD_SERVICE_LINES	   C107_CAN_ADD_SERVICE_LINES,
-- 	OL.CONDITION_VARIABLE_2	   C108_CONDITION_VARIABLE_2,
-- 	OL.ORDER_CLASS	   C109_ORDER_CLASS,
-- 	OL.CREATETS	   C110_CREATETS,
-- 	OL.SHIPPED_QUANTITY	   C111_SHIPPED_QUANTITY,
-- 	OL.RESERVATION_MANDATORY	   C112_RESERVATION_MANDATORY,
-- 	OL.EXTN_IS_PACKAGE_SUBSTITUTED	   C113_EXTN_IS_PACKAGE_SUBSTITUT,
-- 	OL.EXTN_CR_NUMBER	   C114_EXTN_CR_NUMBER,
-- 	OL.CONDITION_VARIABLE_1	   C115_CONDITION_VARIABLE_1,
-- 	OL.IS_PROCUREMENT_ALLOWED	   C116_IS_PROCUREMENT_ALLOWED,
-- 	OL.SUPPLIER_ITEM	   C117_SUPPLIER_ITEM,
-- 	OL.PERSONALIZE_FLAG	   C118_PERSONALIZE_FLAG,
-- 	OL.KIT_QTY	   C119_KIT_QTY,
-- 	OL.DERIVED_FROM_ORDER_HEADER_KEY	   C120_DERIVED_FROM_ORDER_HEADER,
-- 	OL.ORDERING_UOM	   C121_ORDERING_UOM,
-- 	OL.TAX	   C122_TAX,
-- 	OL.CUSTOMER_ITEM_DESCRIPTION	   C123_CUSTOMER_ITEM_DESCRIPTION,
-- 	OL.RESERVATION_POOL	   C124_RESERVATION_POOL,
-- 	OL.LINE_TYPE	   C125_LINE_TYPE,
-- 	OL.MARK_FOR_KEY	   C126_MARK_FOR_KEY,
-- 	OL.IS_FORWARDING_ALLOWED	   C127_IS_FORWARDING_ALLOWED,
-- 	OL.EXTN_LOC_PER_QTY	   C128_EXTN_LOC_PER_QTY,
-- 	OL.NMFC_DESCRIPTION	   C129_NMFC_DESCRIPTION,
-- 	OL.PROMISED_APPT_END_DATE	   C130_PROMISED_APPT_END_DATE,
-- 	OL.CAPACITY_UOM	   C131_CAPACITY_UOM,
-- 	OL.ORDER_HEADER_KEY	   C132_ORDER_HEADER_KEY,
-- 	OL.IMPORT_LICENSE_EXP_DATE	   C133_IMPORT_LICENSE_EXP_DATE,
-- 	OL.ORIG_ORDER_LINE_KEY	   C134_ORIG_ORDER_LINE_KEY,
-- 	OL.EARLIEST_SCHEDULE_DATE	   C135_EARLIEST_SCHEDULE_DATE,
-- 	OL.EXTN_CAN_SUBSTITUTE_PACKAGE	   C136_EXTN_CAN_SUBSTITUTE_PACKA,
-- 	OL.COMMITTED_QUANTITY	   C137_COMMITTED_QUANTITY,
-- 	OL.IS_STANDALONE_SERVICE	   C138_IS_STANDALONE_SERVICE,
-- 	OL.TAXABLE_FLAG	   C139_TAXABLE_FLAG,
-- 	OL.FIXED_PRICING_QTY_PER_LINE	   C140_FIXED_PRICING_QTY_PER_LIN,
-- 	OL.EXTN_CONFIG_POINT_EQUIVALENT	   C141_EXTN_CONFIG_POINT_EQUIVAL,
-- 	OL.BUNDLE_PARENT_ORDER_LINE_KEY	   C142_BUNDLE_PARENT_ORDER_LINE_,
-- 	OL.EXTN_PKG_REFERENCE	   C143_EXTN_PKG_REFERENCE,
-- 	OL.EXTN_IS_PERFECT_PACKAGE	   C144_EXTN_IS_PERFECT_PACKAGE,
-- 	OL.INVOICE_COMPLETE	   C145_INVOICE_COMPLETE,
-- 	OL.RETURN_REASON	   C146_RETURN_REASON,
-- 	OL.BUYER_RECEIVING_NODE_ID	   C147_BUYER_RECEIVING_NODE_ID,
-- 	OL.SHIPNODE_KEY	   C148_SHIPNODE_KEY,
-- 	OL.SHIP_TO_KEY	   C149_SHIP_TO_KEY,
-- 	OL.EXTN_REQUESTED_BY	   C150_EXTN_REQUESTED_BY,
-- 	OL.EXTN_REQUESTED_DATE	   C151_EXTN_REQUESTED_DATE,
-- 	OL.PROCURE_FROM_NODE	   C152_PROCURE_FROM_NODE,
-- 	OL.BUYER_MARK_FOR_NODE_ID	   C153_BUYER_MARK_FOR_NODE_ID,
-- 	OL.CHAINED_FROM_ORDER_LINE_KEY	   C154_CHAINED_FROM_ORDER_LINE_K,
-- 	OL.PERSONALIZE_CODE	   C155_PERSONALIZE_CODE,
-- 	OL.REPRICING_QUANTITY	   C156_REPRICING_QUANTITY,
-- 	OL.EXTN_IS_PROOF_EXPRESS	   C157_EXTN_IS_PROOF_EXPRESS,
-- 	OL.EXTN_TAX_CODE	   C158_EXTN_TAX_CODE,
-- 	OL.HARMONIZED_CODE	   C159_HARMONIZED_CODE,
-- 	OL.DISCOUNT_PERCENTAGE	   C160_DISCOUNT_PERCENTAGE,
-- 	OL.EXTN_CURRENT_NO_OF_POSES	   C161_EXTN_CURRENT_NO_OF_POSES,
-- 	OL.RETAIL_PRICE	   C162_RETAIL_PRICE,
-- 	OL.PRICING_QUANTITY_CONV_FACTOR	   C163_PRICING_QUANTITY_CONV_FAC,
-- 	OL.EXTN_CURRENT_POINT_EQUIVALENT	   C164_EXTN_CURRENT_POINT_EQUIVA,
-- 	OL.INVOICED_LINE_TOTAL	   C165_INVOICED_LINE_TOTAL,
-- 	OL.ITEM_WEIGHT	   C166_ITEM_WEIGHT,
-- 	OL.SUPPLIER_CODE	   C167_SUPPLIER_CODE,
-- 	OL.TAX_EXEMPTION_CERTIFICATE	   C168_TAX_EXEMPTION_CERTIFICATE,
-- 	OL.MODIFYTS	   C169_MODIFYTS,
-- 	OL.DELIVERY_CODE	   C170_DELIVERY_CODE,
-- 	OL.EXTN_SORT_SEQ_NO	   C171_EXTN_SORT_SEQ_NO,
-- 	OL.ITEM_SHORT_DESCRIPTION	   C172_ITEM_SHORT_DESCRIPTION,
-- 	OL.PARENT_OF_DEPENDENT_GROUP	   C173_PARENT_OF_DEPENDENT_GROUP,
-- 	OL.PICKABLE_FLAG	   C174_PICKABLE_FLAG,
-- 	OL.REQ_SHIP_DATE	   C175_REQ_SHIP_DATE,
-- 	OL.EXTN_CONFIG_SHEET_EQUIVALENT	   C176_EXTN_CONFIG_SHEET_EQUIVAL,
-- 	OL.EXTN_ADDITIONAL_POINTS	   C177_EXTN_ADDITIONAL_POINTS,
-- 	OL.OPTION_CAPACITY_REQUIRED	   C178_OPTION_CAPACITY_REQUIRED,
-- 	OL.EXTN_LINEN_ALLOWED	   C179_EXTN_LINEN_ALLOWED,
-- 	OL.CANNOT_MEET_APPT	   C180_CANNOT_MEET_APPT,
-- 	OL.MANUFACTURER_NAME	   C181_MANUFACTURER_NAME,
-- 	OL.EXTN_SHEET_UNITS_PER_QTY	   C182_EXTN_SHEET_UNITS_PER_QTY,
-- 	OL.COST_CURRENCY	   C183_COST_CURRENCY,
-- 	OL.DELIVERY_METHOD	   C184_DELIVERY_METHOD,
-- 	OL.INVOICE_BASED_ON_ACTUALS	   C185_INVOICE_BASED_ON_ACTUALS,
-- 	OL.PURPOSE	   C186_PURPOSE,
-- 	OL.REQ_CANCEL_DATE	   C187_REQ_CANCEL_DATE,
-- 	OL.MAINTAIN_RATIO	   C188_MAINTAIN_RATIO,
-- 	OL.IMPORT_LICENSE_NO	   C189_IMPORT_LICENSE_NO,
-- 	OL.FILL_QUANTITY	   C190_FILL_QUANTITY,
-- 	OL.COUNTRY_OF_ORIGIN	   C191_COUNTRY_OF_ORIGIN,
-- 	OL.TRAN_DISCREPANCY_QTY	   C192_TRAN_DISCREPANCY_QTY,
-- 	OL.MERGE_NODE	   C193_MERGE_NODE,
-- 	OL.PRODUCT_CLASS	   C194_PRODUCT_CLASS,
-- 	OL.DISCOUNT_TYPE	   C195_DISCOUNT_TYPE,
-- 	OL.ALLOCATE_DATE	   C196_ALLOCATE_DATE,
-- 	OL.EXTN_PERSONALIZATION_INCLUDED	   C197_EXTN_PERSONALIZATION_INCL,
-- 	OL.PRICING_QUANTITY_STRATEGY	   C198_PRICING_QUANTITY_STRATEGY,
-- 	OL.EXTN_TCREDIT_PERCENTAGE	   C199_EXTN_TCREDIT_PERCENTAGE,
-- 	OL.ORIGINAL_ORDERED_QTY	   C200_ORIGINAL_ORDERED_QTY,
-- 	OL.SHIP_TOGETHER_NO	   C201_SHIP_TOGETHER_NO,
-- 	OL.EXTN_ADDITIONAL_SHEETS	   C202_EXTN_ADDITIONAL_SHEETS,
-- 	OL.PRICING_QUANTITY	   C203_PRICING_QUANTITY,
-- 	OL.EXTN_TAX_INCLUSIVE	   C204_EXTN_TAX_INCLUSIVE,
-- 	OL.SOURCE_FROM_ORGANIZATION	   C205_SOURCE_FROM_ORGANIZATION,
-- 	OL.PRICING_DATE	   C206_PRICING_DATE,
-- 	OL.MANUFACTURER_ITEM	   C207_MANUFACTURER_ITEM,
-- 	OL.LAST_ITER_SEQ_NO	   C208_LAST_ITER_SEQ_NO,
-- 	OL.SCHEDULE_B_CODE	   C209_SCHEDULE_B_CODE,
-- 	OL.TIMEZONE	   C210_TIMEZONE,
-- 	OL.INVOICED_PRICING_QUANTITY	   C211_INVOICED_PRICING_QUANTITY
-- from	OMS3_OWN.YFS_ORDER_LINE   OL
-- where	(1=1)
-- And (OL.MODIFYTS >= TO_DATE(SUBSTR(:v_cdc_load_date, 1, 19), 'YYYY-MM-DD HH24:MI:SS')  -:v_cdc_oms_overlap)





-- &

-- /* TARGET CODE */
-- insert into RAX_APP_USER.C$_0STG_ORDER_LINE
-- (
-- 	C1_SETTLED_AMOUNT,
-- 	C2_CUSTOMER_PO_NO,
-- 	C3_PRICING_UOM,
-- 	C4_PRIME_LINE_NO,
-- 	C5_ALLOCATION_LEAD_TIME,
-- 	C6_INVOICED_QUANTITY,
-- 	C7_DERIVED_FROM_ORDER_LINE_KEY,
-- 	C8_CURRENT_WORK_ORDER_KEY,
-- 	C9_DEPENDENCY_RATIO,
-- 	C10_CUSTOMER_PO_LINE_NO,
-- 	C11_DEPARTMENT_CODE,
-- 	C12_REQ_DELIVERY_DATE,
-- 	C13_EXTN_SECONDARY_REASON_CODE,
-- 	C14_DISCOUNT_REFERENCE,
-- 	C15_EXTN_SPRAY_FINISH_INCLUDED,
-- 	C16_ITEM_GROUP_CODE,
-- 	C17_GIFT_FLAG,
-- 	C18_IS_COST_OVERRIDDEN,
-- 	C19_MIN_SHIP_BY_DATE,
-- 	C20_EXTN_LINEN_INCLUDED,
-- 	C21_CHAINED_FROM_ORDER_HEADER_,
-- 	C22_FULFILLMENT_TYPE,
-- 	C23_EXTN_CSR_CODE,
-- 	C24_UNIT_PRICE,
-- 	C25_EXTN_CURRENT_SHEET_EQUIVAL,
-- 	C26_APPT_STATUS,
-- 	C27_WAIT_FOR_SEQ_LINE,
-- 	C28_IS_PRICE_LOCKED,
-- 	C29_DEPENDENT_ON_LINE_KEY,
-- 	C30_SEGMENT_TYPE,
-- 	C31_CREATEUSERID,
-- 	C32_ITEM_WEIGHT_UOM,
-- 	C33_ALTERNATE_ITEM_ID,
-- 	C34_SCHED_FAILURE_REASON_CODE,
-- 	C35_PROMISED_APPT_START_DATE,
-- 	C36_RESERVATION_ID,
-- 	C37_PIPELINE_KEY,
-- 	C38_ITEM_ID,
-- 	C39_EXTN_NO_OF_POSES_PER_UNIT,
-- 	C40_BASIC_CAPACITY_REQUIRED,
-- 	C41_UNIT_COST,
-- 	C42_OVER_RECEIPT_QUANTITY,
-- 	C43_CANNOT_COMPLETE_AFTER_DATE,
-- 	C44_ECCN_NO,
-- 	C45_SUB_LINE_NO,
-- 	C46_CREATEPROGID,
-- 	C47_HOLD_FLAG,
-- 	C48_MODIFYPROGID,
-- 	C49_UOM,
-- 	C50_DISTRIBUTION_RULE_ID,
-- 	C51_PRODUCT_LINE,
-- 	C52_SHIP_TO_ID,
-- 	C53_INVOICED_EXTENDED_PRICE,
-- 	C54_SPLIT_QTY,
-- 	C55_ISBN,
-- 	C56_CANNOT_COMPLETE_BEFORE_DAT,
-- 	C57_EARLIEST_DELIVERY_DATE,
-- 	C58_LINE_TOTAL,
-- 	C59_OTHER_CHARGES,
-- 	C60_CARRIER_SERVICE_CODE,
-- 	C61_SCAC,
-- 	C62_SUPPLIER_ITEM_DESCRIPTION,
-- 	C63_ORDERED_QTY,
-- 	C64_IS_FIRM_PREDEFINED_NODE,
-- 	C65_EXTN_PRIMARY_REASON_CODE,
-- 	C66_NMFC_CODE,
-- 	C67_CARRIER_ACCOUNT_NO,
-- 	C68_LINE_SEQ_NO,
-- 	C69_RESHIP_PARENT_LINE_KEY,
-- 	C70_INTENTIONAL_BACKORDER,
-- 	C71_SERIAL_NO,
-- 	C72_IS_PRICE_INFO_ONLY,
-- 	C73_ITEM_DESCRIPTION,
-- 	C74_PACKLIST_TYPE,
-- 	C75_LIST_PRICE,
-- 	C76_FIXED_CAPACITY_QTY_PER_LIN,
-- 	C77_MODIFYUSERID,
-- 	C78_EXTN_IS_TERRITORY_PROOF_SA,
-- 	C79_RECEIVED_QUANTITY,
-- 	C80_EXTN_TAXABLE,
-- 	C81_SEGMENT,
-- 	C82_EXTN_TRAN_DEPENDENCY,
-- 	C83_IS_CAPACITY_OVERRIDDEN,
-- 	C84_DERIVED_FROM_ORDER_RELEASE,
-- 	C85_NMFC_CLASS,
-- 	C86_UPC_CODE,
-- 	C87_DEPENDENCY_SHIPPING_RULE,
-- 	C88_ACTUAL_PRICING_QUANTITY,
-- 	C89_ORDER_LINE_KEY,
-- 	C90_EXTN_ACCOUNTING_TYPE,
-- 	C91_LOCKID,
-- 	C92_FOB,
-- 	C93_MANUFACTURER_ITEM_DESC,
-- 	C94_FUTURE_AVAIL_DATE,
-- 	C95_TAX_PRODUCT_CODE,
-- 	C96_EXTN_DISTINCT_NO_OF_POSES,
-- 	C97_FIRST_ITER_SEQ_NO,
-- 	C98_EXTN_ADDITIONAL_POSES,
-- 	C99_RECEIVING_NODE,
-- 	C100_SETTLED_QUANTITY,
-- 	C101_EXTN_SPRAY_FINISH_ALLOWED,
-- 	C102_SHIPMENT_CONSOL_GROUP_ID,
-- 	C103_CUSTOMER_ITEM,
-- 	C104_HOLD_REASON_CODE,
-- 	C105_KIT_CODE,
-- 	C106_EARLIEST_SHIP_DATE,
-- 	C107_CAN_ADD_SERVICE_LINES,
-- 	C108_CONDITION_VARIABLE_2,
-- 	C109_ORDER_CLASS,
-- 	C110_CREATETS,
-- 	C111_SHIPPED_QUANTITY,
-- 	C112_RESERVATION_MANDATORY,
-- 	C113_EXTN_IS_PACKAGE_SUBSTITUT,
-- 	C114_EXTN_CR_NUMBER,
-- 	C115_CONDITION_VARIABLE_1,
-- 	C116_IS_PROCUREMENT_ALLOWED,
-- 	C117_SUPPLIER_ITEM,
-- 	C118_PERSONALIZE_FLAG,
-- 	C119_KIT_QTY,
-- 	C120_DERIVED_FROM_ORDER_HEADER,
-- 	C121_ORDERING_UOM,
-- 	C122_TAX,
-- 	C123_CUSTOMER_ITEM_DESCRIPTION,
-- 	C124_RESERVATION_POOL,
-- 	C125_LINE_TYPE,
-- 	C126_MARK_FOR_KEY,
-- 	C127_IS_FORWARDING_ALLOWED,
-- 	C128_EXTN_LOC_PER_QTY,
-- 	C129_NMFC_DESCRIPTION,
-- 	C130_PROMISED_APPT_END_DATE,
-- 	C131_CAPACITY_UOM,
-- 	C132_ORDER_HEADER_KEY,
-- 	C133_IMPORT_LICENSE_EXP_DATE,
-- 	C134_ORIG_ORDER_LINE_KEY,
-- 	C135_EARLIEST_SCHEDULE_DATE,
-- 	C136_EXTN_CAN_SUBSTITUTE_PACKA,
-- 	C137_COMMITTED_QUANTITY,
-- 	C138_IS_STANDALONE_SERVICE,
-- 	C139_TAXABLE_FLAG,
-- 	C140_FIXED_PRICING_QTY_PER_LIN,
-- 	C141_EXTN_CONFIG_POINT_EQUIVAL,
-- 	C142_BUNDLE_PARENT_ORDER_LINE_,
-- 	C143_EXTN_PKG_REFERENCE,
-- 	C144_EXTN_IS_PERFECT_PACKAGE,
-- 	C145_INVOICE_COMPLETE,
-- 	C146_RETURN_REASON,
-- 	C147_BUYER_RECEIVING_NODE_ID,
-- 	C148_SHIPNODE_KEY,
-- 	C149_SHIP_TO_KEY,
-- 	C150_EXTN_REQUESTED_BY,
-- 	C151_EXTN_REQUESTED_DATE,
-- 	C152_PROCURE_FROM_NODE,
-- 	C153_BUYER_MARK_FOR_NODE_ID,
-- 	C154_CHAINED_FROM_ORDER_LINE_K,
-- 	C155_PERSONALIZE_CODE,
-- 	C156_REPRICING_QUANTITY,
-- 	C157_EXTN_IS_PROOF_EXPRESS,
-- 	C158_EXTN_TAX_CODE,
-- 	C159_HARMONIZED_CODE,
-- 	C160_DISCOUNT_PERCENTAGE,
-- 	C161_EXTN_CURRENT_NO_OF_POSES,
-- 	C162_RETAIL_PRICE,
-- 	C163_PRICING_QUANTITY_CONV_FAC,
-- 	C164_EXTN_CURRENT_POINT_EQUIVA,
-- 	C165_INVOICED_LINE_TOTAL,
-- 	C166_ITEM_WEIGHT,
-- 	C167_SUPPLIER_CODE,
-- 	C168_TAX_EXEMPTION_CERTIFICATE,
-- 	C169_MODIFYTS,
-- 	C170_DELIVERY_CODE,
-- 	C171_EXTN_SORT_SEQ_NO,
-- 	C172_ITEM_SHORT_DESCRIPTION,
-- 	C173_PARENT_OF_DEPENDENT_GROUP,
-- 	C174_PICKABLE_FLAG,
-- 	C175_REQ_SHIP_DATE,
-- 	C176_EXTN_CONFIG_SHEET_EQUIVAL,
-- 	C177_EXTN_ADDITIONAL_POINTS,
-- 	C178_OPTION_CAPACITY_REQUIRED,
-- 	C179_EXTN_LINEN_ALLOWED,
-- 	C180_CANNOT_MEET_APPT,
-- 	C181_MANUFACTURER_NAME,
-- 	C182_EXTN_SHEET_UNITS_PER_QTY,
-- 	C183_COST_CURRENCY,
-- 	C184_DELIVERY_METHOD,
-- 	C185_INVOICE_BASED_ON_ACTUALS,
-- 	C186_PURPOSE,
-- 	C187_REQ_CANCEL_DATE,
-- 	C188_MAINTAIN_RATIO,
-- 	C189_IMPORT_LICENSE_NO,
-- 	C190_FILL_QUANTITY,
-- 	C191_COUNTRY_OF_ORIGIN,
-- 	C192_TRAN_DISCREPANCY_QTY,
-- 	C193_MERGE_NODE,
-- 	C194_PRODUCT_CLASS,
-- 	C195_DISCOUNT_TYPE,
-- 	C196_ALLOCATE_DATE,
-- 	C197_EXTN_PERSONALIZATION_INCL,
-- 	C198_PRICING_QUANTITY_STRATEGY,
-- 	C199_EXTN_TCREDIT_PERCENTAGE,
-- 	C200_ORIGINAL_ORDERED_QTY,
-- 	C201_SHIP_TOGETHER_NO,
-- 	C202_EXTN_ADDITIONAL_SHEETS,
-- 	C203_PRICING_QUANTITY,
-- 	C204_EXTN_TAX_INCLUSIVE,
-- 	C205_SOURCE_FROM_ORGANIZATION,
-- 	C206_PRICING_DATE,
-- 	C207_MANUFACTURER_ITEM,
-- 	C208_LAST_ITER_SEQ_NO,
-- 	C209_SCHEDULE_B_CODE,
-- 	C210_TIMEZONE,
-- 	C211_INVOICED_PRICING_QUANTITY
-- )
-- values
-- (
-- 	:C1_SETTLED_AMOUNT,
-- 	:C2_CUSTOMER_PO_NO,
-- 	:C3_PRICING_UOM,
-- 	:C4_PRIME_LINE_NO,
-- 	:C5_ALLOCATION_LEAD_TIME,
-- 	:C6_INVOICED_QUANTITY,
-- 	:C7_DERIVED_FROM_ORDER_LINE_KEY,
-- 	:C8_CURRENT_WORK_ORDER_KEY,
-- 	:C9_DEPENDENCY_RATIO,
-- 	:C10_CUSTOMER_PO_LINE_NO,
-- 	:C11_DEPARTMENT_CODE,
-- 	:C12_REQ_DELIVERY_DATE,
-- 	:C13_EXTN_SECONDARY_REASON_CODE,
-- 	:C14_DISCOUNT_REFERENCE,
-- 	:C15_EXTN_SPRAY_FINISH_INCLUDED,
-- 	:C16_ITEM_GROUP_CODE,
-- 	:C17_GIFT_FLAG,
-- 	:C18_IS_COST_OVERRIDDEN,
-- 	:C19_MIN_SHIP_BY_DATE,
-- 	:C20_EXTN_LINEN_INCLUDED,
-- 	:C21_CHAINED_FROM_ORDER_HEADER_,
-- 	:C22_FULFILLMENT_TYPE,
-- 	:C23_EXTN_CSR_CODE,
-- 	:C24_UNIT_PRICE,
-- 	:C25_EXTN_CURRENT_SHEET_EQUIVAL,
-- 	:C26_APPT_STATUS,
-- 	:C27_WAIT_FOR_SEQ_LINE,
-- 	:C28_IS_PRICE_LOCKED,
-- 	:C29_DEPENDENT_ON_LINE_KEY,
-- 	:C30_SEGMENT_TYPE,
-- 	:C31_CREATEUSERID,
-- 	:C32_ITEM_WEIGHT_UOM,
-- 	:C33_ALTERNATE_ITEM_ID,
-- 	:C34_SCHED_FAILURE_REASON_CODE,
-- 	:C35_PROMISED_APPT_START_DATE,
-- 	:C36_RESERVATION_ID,
-- 	:C37_PIPELINE_KEY,
-- 	:C38_ITEM_ID,
-- 	:C39_EXTN_NO_OF_POSES_PER_UNIT,
-- 	:C40_BASIC_CAPACITY_REQUIRED,
-- 	:C41_UNIT_COST,
-- 	:C42_OVER_RECEIPT_QUANTITY,
-- 	:C43_CANNOT_COMPLETE_AFTER_DATE,
-- 	:C44_ECCN_NO,
-- 	:C45_SUB_LINE_NO,
-- 	:C46_CREATEPROGID,
-- 	:C47_HOLD_FLAG,
-- 	:C48_MODIFYPROGID,
-- 	:C49_UOM,
-- 	:C50_DISTRIBUTION_RULE_ID,
-- 	:C51_PRODUCT_LINE,
-- 	:C52_SHIP_TO_ID,
-- 	:C53_INVOICED_EXTENDED_PRICE,
-- 	:C54_SPLIT_QTY,
-- 	:C55_ISBN,
-- 	:C56_CANNOT_COMPLETE_BEFORE_DAT,
-- 	:C57_EARLIEST_DELIVERY_DATE,
-- 	:C58_LINE_TOTAL,
-- 	:C59_OTHER_CHARGES,
-- 	:C60_CARRIER_SERVICE_CODE,
-- 	:C61_SCAC,
-- 	:C62_SUPPLIER_ITEM_DESCRIPTION,
-- 	:C63_ORDERED_QTY,
-- 	:C64_IS_FIRM_PREDEFINED_NODE,
-- 	:C65_EXTN_PRIMARY_REASON_CODE,
-- 	:C66_NMFC_CODE,
-- 	:C67_CARRIER_ACCOUNT_NO,
-- 	:C68_LINE_SEQ_NO,
-- 	:C69_RESHIP_PARENT_LINE_KEY,
-- 	:C70_INTENTIONAL_BACKORDER,
-- 	:C71_SERIAL_NO,
-- 	:C72_IS_PRICE_INFO_ONLY,
-- 	:C73_ITEM_DESCRIPTION,
-- 	:C74_PACKLIST_TYPE,
-- 	:C75_LIST_PRICE,
-- 	:C76_FIXED_CAPACITY_QTY_PER_LIN,
-- 	:C77_MODIFYUSERID,
-- 	:C78_EXTN_IS_TERRITORY_PROOF_SA,
-- 	:C79_RECEIVED_QUANTITY,
-- 	:C80_EXTN_TAXABLE,
-- 	:C81_SEGMENT,
-- 	:C82_EXTN_TRAN_DEPENDENCY,
-- 	:C83_IS_CAPACITY_OVERRIDDEN,
-- 	:C84_DERIVED_FROM_ORDER_RELEASE,
-- 	:C85_NMFC_CLASS,
-- 	:C86_UPC_CODE,
-- 	:C87_DEPENDENCY_SHIPPING_RULE,
-- 	:C88_ACTUAL_PRICING_QUANTITY,
-- 	:C89_ORDER_LINE_KEY,
-- 	:C90_EXTN_ACCOUNTING_TYPE,
-- 	:C91_LOCKID,
-- 	:C92_FOB,
-- 	:C93_MANUFACTURER_ITEM_DESC,
-- 	:C94_FUTURE_AVAIL_DATE,
-- 	:C95_TAX_PRODUCT_CODE,
-- 	:C96_EXTN_DISTINCT_NO_OF_POSES,
-- 	:C97_FIRST_ITER_SEQ_NO,
-- 	:C98_EXTN_ADDITIONAL_POSES,
-- 	:C99_RECEIVING_NODE,
-- 	:C100_SETTLED_QUANTITY,
-- 	:C101_EXTN_SPRAY_FINISH_ALLOWED,
-- 	:C102_SHIPMENT_CONSOL_GROUP_ID,
-- 	:C103_CUSTOMER_ITEM,
-- 	:C104_HOLD_REASON_CODE,
-- 	:C105_KIT_CODE,
-- 	:C106_EARLIEST_SHIP_DATE,
-- 	:C107_CAN_ADD_SERVICE_LINES,
-- 	:C108_CONDITION_VARIABLE_2,
-- 	:C109_ORDER_CLASS,
-- 	:C110_CREATETS,
-- 	:C111_SHIPPED_QUANTITY,
-- 	:C112_RESERVATION_MANDATORY,
-- 	:C113_EXTN_IS_PACKAGE_SUBSTITUT,
-- 	:C114_EXTN_CR_NUMBER,
-- 	:C115_CONDITION_VARIABLE_1,
-- 	:C116_IS_PROCUREMENT_ALLOWED,
-- 	:C117_SUPPLIER_ITEM,
-- 	:C118_PERSONALIZE_FLAG,
-- 	:C119_KIT_QTY,
-- 	:C120_DERIVED_FROM_ORDER_HEADER,
-- 	:C121_ORDERING_UOM,
-- 	:C122_TAX,
-- 	:C123_CUSTOMER_ITEM_DESCRIPTION,
-- 	:C124_RESERVATION_POOL,
-- 	:C125_LINE_TYPE,
-- 	:C126_MARK_FOR_KEY,
-- 	:C127_IS_FORWARDING_ALLOWED,
-- 	:C128_EXTN_LOC_PER_QTY,
-- 	:C129_NMFC_DESCRIPTION,
-- 	:C130_PROMISED_APPT_END_DATE,
-- 	:C131_CAPACITY_UOM,
-- 	:C132_ORDER_HEADER_KEY,
-- 	:C133_IMPORT_LICENSE_EXP_DATE,
-- 	:C134_ORIG_ORDER_LINE_KEY,
-- 	:C135_EARLIEST_SCHEDULE_DATE,
-- 	:C136_EXTN_CAN_SUBSTITUTE_PACKA,
-- 	:C137_COMMITTED_QUANTITY,
-- 	:C138_IS_STANDALONE_SERVICE,
-- 	:C139_TAXABLE_FLAG,
-- 	:C140_FIXED_PRICING_QTY_PER_LIN,
-- 	:C141_EXTN_CONFIG_POINT_EQUIVAL,
-- 	:C142_BUNDLE_PARENT_ORDER_LINE_,
-- 	:C143_EXTN_PKG_REFERENCE,
-- 	:C144_EXTN_IS_PERFECT_PACKAGE,
-- 	:C145_INVOICE_COMPLETE,
-- 	:C146_RETURN_REASON,
-- 	:C147_BUYER_RECEIVING_NODE_ID,
-- 	:C148_SHIPNODE_KEY,
-- 	:C149_SHIP_TO_KEY,
-- 	:C150_EXTN_REQUESTED_BY,
-- 	:C151_EXTN_REQUESTED_DATE,
-- 	:C152_PROCURE_FROM_NODE,
-- 	:C153_BUYER_MARK_FOR_NODE_ID,
-- 	:C154_CHAINED_FROM_ORDER_LINE_K,
-- 	:C155_PERSONALIZE_CODE,
-- 	:C156_REPRICING_QUANTITY,
-- 	:C157_EXTN_IS_PROOF_EXPRESS,
-- 	:C158_EXTN_TAX_CODE,
-- 	:C159_HARMONIZED_CODE,
-- 	:C160_DISCOUNT_PERCENTAGE,
-- 	:C161_EXTN_CURRENT_NO_OF_POSES,
-- 	:C162_RETAIL_PRICE,
-- 	:C163_PRICING_QUANTITY_CONV_FAC,
-- 	:C164_EXTN_CURRENT_POINT_EQUIVA,
-- 	:C165_INVOICED_LINE_TOTAL,
-- 	:C166_ITEM_WEIGHT,
-- 	:C167_SUPPLIER_CODE,
-- 	:C168_TAX_EXEMPTION_CERTIFICATE,
-- 	:C169_MODIFYTS,
-- 	:C170_DELIVERY_CODE,
-- 	:C171_EXTN_SORT_SEQ_NO,
-- 	:C172_ITEM_SHORT_DESCRIPTION,
-- 	:C173_PARENT_OF_DEPENDENT_GROUP,
-- 	:C174_PICKABLE_FLAG,
-- 	:C175_REQ_SHIP_DATE,
-- 	:C176_EXTN_CONFIG_SHEET_EQUIVAL,
-- 	:C177_EXTN_ADDITIONAL_POINTS,
-- 	:C178_OPTION_CAPACITY_REQUIRED,
-- 	:C179_EXTN_LINEN_ALLOWED,
-- 	:C180_CANNOT_MEET_APPT,
-- 	:C181_MANUFACTURER_NAME,
-- 	:C182_EXTN_SHEET_UNITS_PER_QTY,
-- 	:C183_COST_CURRENCY,
-- 	:C184_DELIVERY_METHOD,
-- 	:C185_INVOICE_BASED_ON_ACTUALS,
-- 	:C186_PURPOSE,
-- 	:C187_REQ_CANCEL_DATE,
-- 	:C188_MAINTAIN_RATIO,
-- 	:C189_IMPORT_LICENSE_NO,
-- 	:C190_FILL_QUANTITY,
-- 	:C191_COUNTRY_OF_ORIGIN,
-- 	:C192_TRAN_DISCREPANCY_QTY,
-- 	:C193_MERGE_NODE,
-- 	:C194_PRODUCT_CLASS,
-- 	:C195_DISCOUNT_TYPE,
-- 	:C196_ALLOCATE_DATE,
-- 	:C197_EXTN_PERSONALIZATION_INCL,
-- 	:C198_PRICING_QUANTITY_STRATEGY,
-- 	:C199_EXTN_TCREDIT_PERCENTAGE,
-- 	:C200_ORIGINAL_ORDERED_QTY,
-- 	:C201_SHIP_TOGETHER_NO,
-- 	:C202_EXTN_ADDITIONAL_SHEETS,
-- 	:C203_PRICING_QUANTITY,
-- 	:C204_EXTN_TAX_INCLUSIVE,
-- 	:C205_SOURCE_FROM_ORGANIZATION,
-- 	:C206_PRICING_DATE,
-- 	:C207_MANUFACTURER_ITEM,
-- 	:C208_LAST_ITER_SEQ_NO,
-- 	:C209_SCHEDULE_B_CODE,
-- 	:C210_TIMEZONE,
-- 	:C211_INVOICED_PRICING_QUANTITY
-- )

-- &


/*-----------------------------------------------*/
/* TASK No. 7 */
/* Analyze work table */



BEGIN
DBMS_STATS.GATHER_TABLE_STATS (
    ownname =>	'RAX_APP_USER',
    tabname =>	'C$_0STG_ORDER_LINE',
    estimate_percent =>	DBMS_STATS.AUTO_SAMPLE_SIZE
);
END;




&


/*-----------------------------------------------*/
/* TASK No. 9 */
/* Create target table  */
BEGIN  
   EXECUTE IMMEDIATE 'create table RAX_APP_USER.STG_ORDER_LINE
						(
							SETTLED_AMOUNT	NUMBER(15,2) NULL,
							CUSTOMER_PO_NO	VARCHAR2(100) NULL,
							PRICING_UOM	VARCHAR2(40) NULL,
							PRIME_LINE_NO	NUMBER(5) NULL,
							ALLOCATION_LEAD_TIME	NUMBER(5) NULL,
							INVOICED_QUANTITY	NUMBER(14,4) NULL,
							DERIVED_FROM_ORDER_LINE_KEY	CHAR(24) NULL,
							CURRENT_WORK_ORDER_KEY	CHAR(24) NULL,
							DEPENDENCY_RATIO	NUMBER(14,4) NULL,
							CUSTOMER_PO_LINE_NO	VARCHAR2(10) NULL,
							DEPARTMENT_CODE	VARCHAR2(20) NULL,
							REQ_DELIVERY_DATE	DATE NULL,
							EXTN_SECONDARY_REASON_CODE	VARCHAR2(120) NULL,
							DISCOUNT_REFERENCE	VARCHAR2(100) NULL,
							EXTN_SPRAY_FINISH_INCLUDED	CHAR(1) NULL,
							ITEM_GROUP_CODE	VARCHAR2(20) NULL,
							GIFT_FLAG	CHAR(1) NULL,
							IS_COST_OVERRIDDEN	CHAR(1) NULL,
							MIN_SHIP_BY_DATE	DATE NULL,
							EXTN_LINEN_INCLUDED	CHAR(1) NULL,
							CHAINED_FROM_ORDER_HEADER_KEY	CHAR(24) NULL,
							FULFILLMENT_TYPE	VARCHAR2(40) NULL,
							EXTN_CSR_CODE	VARCHAR2(20) NULL,
							UNIT_PRICE	NUMBER(19,6) NULL,
							EXTN_CURRENT_SHEET_EQUIVALENT	NUMBER(4) NULL,
							APPT_STATUS	VARCHAR2(40) NULL,
							WAIT_FOR_SEQ_LINE	CHAR(1) NULL,
							IS_PRICE_LOCKED	CHAR(1) NULL,
							DEPENDENT_ON_LINE_KEY	CHAR(24) NULL,
							SEGMENT_TYPE	VARCHAR2(40) NULL,
							CREATEUSERID	VARCHAR2(40) NULL,
							ITEM_WEIGHT_UOM	VARCHAR2(40) NULL,
							ALTERNATE_ITEM_ID	CHAR(40) NULL,
							SCHED_FAILURE_REASON_CODE	VARCHAR2(40) NULL,
							PROMISED_APPT_START_DATE	DATE NULL,
							RESERVATION_ID	VARCHAR2(40) NULL,
							PIPELINE_KEY	CHAR(24) NULL,
							ITEM_ID	CHAR(40) NULL,
							EXTN_NO_OF_POSES_PER_UNIT	NUMBER(2) NULL,
							BASIC_CAPACITY_REQUIRED	NUMBER(14,4) NULL,
							UNIT_COST	NUMBER(19,6) NULL,
							OVER_RECEIPT_QUANTITY	NUMBER(14,4) NULL,
							CANNOT_COMPLETE_AFTER_DATE	DATE NULL,
							ECCN_NO	VARCHAR2(40) NULL,
							SUB_LINE_NO	NUMBER(5) NULL,
							CREATEPROGID	VARCHAR2(40) NULL,
							HOLD_FLAG	CHAR(1) NULL,
							MODIFYPROGID	VARCHAR2(40) NULL,
							UOM	VARCHAR2(40) NULL,
							DISTRIBUTION_RULE_ID	CHAR(40) NULL,
							PRODUCT_LINE	VARCHAR2(100) NULL,
							SHIP_TO_ID	VARCHAR2(40) NULL,
							INVOICED_EXTENDED_PRICE	NUMBER(15,2) NULL,
							SPLIT_QTY	NUMBER(14,4) NULL,
							ISBN	VARCHAR2(40) NULL,
							CANNOT_COMPLETE_BEFORE_DATE	DATE NULL,
							EARLIEST_DELIVERY_DATE	DATE NULL,
							LINE_TOTAL	NUMBER(15,2) NULL,
							OTHER_CHARGES	NUMBER(15,2) NULL,
							CARRIER_SERVICE_CODE	VARCHAR2(40) NULL,
							SCAC	VARCHAR2(40) NULL,
							SUPPLIER_ITEM_DESCRIPTION	VARCHAR2(200) NULL,
							ORDERED_QTY	NUMBER(14,4) NULL,
							IS_FIRM_PREDEFINED_NODE	CHAR(1) NULL,
							EXTN_PRIMARY_REASON_CODE	VARCHAR2(120) NULL,
							NMFC_CODE	VARCHAR2(40) NULL,
							CARRIER_ACCOUNT_NO	VARCHAR2(40) NULL,
							LINE_SEQ_NO	VARCHAR2(40) NULL,
							RESHIP_PARENT_LINE_KEY	CHAR(24) NULL,
							INTENTIONAL_BACKORDER	CHAR(1) NULL,
							SERIAL_NO	VARCHAR2(40) NULL,
							IS_PRICE_INFO_ONLY	CHAR(1) NULL,
							ITEM_DESCRIPTION	VARCHAR2(200) NULL,
							PACKLIST_TYPE	VARCHAR2(20) NULL,
							LIST_PRICE	NUMBER(19,6) NULL,
							FIXED_CAPACITY_QTY_PER_LINE	NUMBER(14,4) NULL,
							MODIFYUSERID	VARCHAR2(40) NULL,
							EXTN_IS_TERRITORY_PROOF_SAMPLE	CHAR(1) NULL,
							RECEIVED_QUANTITY	NUMBER(14,4) NULL,
							EXTN_TAXABLE	CHAR(1) NULL,
							SEGMENT	VARCHAR2(40) NULL,
							EXTN_TRAN_DEPENDENCY	VARCHAR2(40) NULL,
							IS_CAPACITY_OVERRIDDEN	CHAR(1) NULL,
							DERIVED_FROM_ORDER_RELEASE_KEY	CHAR(24) NULL,
							NMFC_CLASS	VARCHAR2(100) NULL,
							UPC_CODE	VARCHAR2(40) NULL,
							DEPENDENCY_SHIPPING_RULE	CHAR(2) NULL,
							ACTUAL_PRICING_QUANTITY	NUMBER(14,4) NULL,
							ORDER_LINE_KEY	CHAR(24) NULL,
							EXTN_ACCOUNTING_TYPE	VARCHAR2(40) NULL,
							LOCKID	NUMBER(5) NULL,
							FOB	VARCHAR2(40) NULL,
							MANUFACTURER_ITEM_DESC	VARCHAR2(254) NULL,
							FUTURE_AVAIL_DATE	DATE NULL,
							TAX_PRODUCT_CODE	VARCHAR2(40) NULL,
							EXTN_DISTINCT_NO_OF_POSES	NUMBER(5) NULL,
							FIRST_ITER_SEQ_NO	NUMBER(10) NULL,
							EXTN_ADDITIONAL_POSES	NUMBER(4) NULL,
							RECEIVING_NODE	CHAR(24) NULL,
							SETTLED_QUANTITY	NUMBER(14,4) NULL,
							EXTN_SPRAY_FINISH_ALLOWED	CHAR(1) NULL,
							SHIPMENT_CONSOL_GROUP_ID	CHAR(24) NULL,
							CUSTOMER_ITEM	VARCHAR2(40) NULL,
							HOLD_REASON_CODE	VARCHAR2(40) NULL,
							KIT_CODE	VARCHAR2(20) NULL,
							EARLIEST_SHIP_DATE	DATE NULL,
							CAN_ADD_SERVICE_LINES	CHAR(1) NULL,
							CONDITION_VARIABLE_2	VARCHAR2(40) NULL,
							ORDER_CLASS	VARCHAR2(20) NULL,
							CREATETS	DATE NULL,
							SHIPPED_QUANTITY	NUMBER(14,4) NULL,
							RESERVATION_MANDATORY	CHAR(1) NULL,
							EXTN_IS_PACKAGE_SUBSTITUTED	CHAR(1) NULL,
							EXTN_CR_NUMBER	VARCHAR2(12) NULL,
							CONDITION_VARIABLE_1	VARCHAR2(40) NULL,
							IS_PROCUREMENT_ALLOWED	CHAR(1) NULL,
							SUPPLIER_ITEM	VARCHAR2(40) NULL,
							PERSONALIZE_FLAG	CHAR(1) NULL,
							KIT_QTY	NUMBER(14,4) NULL,
							DERIVED_FROM_ORDER_HEADER_KEY	CHAR(24) NULL,
							ORDERING_UOM	VARCHAR2(40) NULL,
							TAX	NUMBER(15,2) NULL,
							CUSTOMER_ITEM_DESCRIPTION	VARCHAR2(200) NULL,
							RESERVATION_POOL	VARCHAR2(40) NULL,
							LINE_TYPE	VARCHAR2(20) NULL,
							MARK_FOR_KEY	CHAR(24) NULL,
							IS_FORWARDING_ALLOWED	CHAR(1) NULL,
							EXTN_LOC_PER_QTY	NUMBER(2) NULL,
							NMFC_DESCRIPTION	VARCHAR2(100) NULL,
							PROMISED_APPT_END_DATE	DATE NULL,
							CAPACITY_UOM	VARCHAR2(40) NULL,
							ORDER_HEADER_KEY	CHAR(24) NULL,
							IMPORT_LICENSE_EXP_DATE	DATE NULL,
							ORIG_ORDER_LINE_KEY	CHAR(24) NULL,
							EARLIEST_SCHEDULE_DATE	DATE NULL,
							EXTN_CAN_SUBSTITUTE_PACKAGE	CHAR(1) NULL,
							COMMITTED_QUANTITY	NUMBER(14,4) NULL,
							IS_STANDALONE_SERVICE	CHAR(1) NULL,
							TAXABLE_FLAG	CHAR(1) NULL,
							FIXED_PRICING_QTY_PER_LINE	NUMBER(14,4) NULL,
							EXTN_CONFIG_POINT_EQUIVALENT	NUMBER(4) NULL,
							BUNDLE_PARENT_ORDER_LINE_KEY	CHAR(24) NULL,
							EXTN_PKG_REFERENCE	VARCHAR2(40) NULL,
							EXTN_IS_PERFECT_PACKAGE	CHAR(1) NULL,
							INVOICE_COMPLETE	CHAR(1) NULL,
							RETURN_REASON	VARCHAR2(40) NULL,
							BUYER_RECEIVING_NODE_ID	CHAR(24) NULL,
							SHIPNODE_KEY	CHAR(24) NULL,
							SHIP_TO_KEY	CHAR(24) NULL,
							EXTN_REQUESTED_BY	VARCHAR2(40) NULL,
							EXTN_REQUESTED_DATE	DATE NULL,
							PROCURE_FROM_NODE	CHAR(24) NULL,
							BUYER_MARK_FOR_NODE_ID	CHAR(24) NULL,
							CHAINED_FROM_ORDER_LINE_KEY	CHAR(24) NULL,
							PERSONALIZE_CODE	VARCHAR2(20) NULL,
							REPRICING_QUANTITY	NUMBER(14,4) NULL,
							EXTN_IS_PROOF_EXPRESS	CHAR(1) NULL,
							EXTN_TAX_CODE	VARCHAR2(20) NULL,
							HARMONIZED_CODE	VARCHAR2(40) NULL,
							DISCOUNT_PERCENTAGE	NUMBER(5,2) NULL,
							EXTN_CURRENT_NO_OF_POSES	NUMBER(4) NULL,
							RETAIL_PRICE	NUMBER(19,6) NULL,
							PRICING_QUANTITY_CONV_FACTOR	NUMBER(14,4) NULL,
							EXTN_CURRENT_POINT_EQUIVALENT	NUMBER(4) NULL,
							INVOICED_LINE_TOTAL	NUMBER(15,2) NULL,
							ITEM_WEIGHT	NUMBER(14,4) NULL,
							SUPPLIER_CODE	CHAR(30) NULL,
							TAX_EXEMPTION_CERTIFICATE	VARCHAR2(40) NULL,
							MODIFYTS	DATE NULL,
							DELIVERY_CODE	VARCHAR2(40) NULL,
							EXTN_SORT_SEQ_NO	VARCHAR2(40) NULL,
							ITEM_SHORT_DESCRIPTION	VARCHAR2(100) NULL,
							PARENT_OF_DEPENDENT_GROUP	CHAR(1) NULL,
							PICKABLE_FLAG	CHAR(1) NULL,
							REQ_SHIP_DATE	DATE NULL,
							EXTN_CONFIG_SHEET_EQUIVALENT	NUMBER(4) NULL,
							EXTN_ADDITIONAL_POINTS	NUMBER(4) NULL,
							OPTION_CAPACITY_REQUIRED	NUMBER(14,4) NULL,
							EXTN_LINEN_ALLOWED	CHAR(1) NULL,
							CANNOT_MEET_APPT	CHAR(1) NULL,
							MANUFACTURER_NAME	VARCHAR2(50) NULL,
							EXTN_SHEET_UNITS_PER_QTY	NUMBER(2) NULL,
							COST_CURRENCY	VARCHAR2(20) NULL,
							DELIVERY_METHOD	VARCHAR2(40) NULL,
							INVOICE_BASED_ON_ACTUALS	CHAR(1) NULL,
							PURPOSE	VARCHAR2(40) NULL,
							REQ_CANCEL_DATE	DATE NULL,
							MAINTAIN_RATIO	CHAR(1) NULL,
							IMPORT_LICENSE_NO	VARCHAR2(40) NULL,
							FILL_QUANTITY	NUMBER(14,4) NULL,
							COUNTRY_OF_ORIGIN	VARCHAR2(40) NULL,
							TRAN_DISCREPANCY_QTY	NUMBER(14,4) NULL,
							MERGE_NODE	CHAR(24) NULL,
							PRODUCT_CLASS	CHAR(10) NULL,
							DISCOUNT_TYPE	VARCHAR2(20) NULL,
							ALLOCATE_DATE	DATE NULL,
							EXTN_PERSONALIZATION_INCLUDED	CHAR(1) NULL,
							PRICING_QUANTITY_STRATEGY	VARCHAR2(20) NULL,
							EXTN_TCREDIT_PERCENTAGE	NUMBER(3) NULL,
							ORIGINAL_ORDERED_QTY	NUMBER(14,4) NULL,
							SHIP_TOGETHER_NO	VARCHAR2(40) NULL,
							EXTN_ADDITIONAL_SHEETS	NUMBER(4) NULL,
							PRICING_QUANTITY	NUMBER(14,4) NULL,
							EXTN_TAX_INCLUSIVE	CHAR(1) NULL,
							SOURCE_FROM_ORGANIZATION	CHAR(24) NULL,
							PRICING_DATE	DATE NULL,
							MANUFACTURER_ITEM	VARCHAR2(100) NULL,
							LAST_ITER_SEQ_NO	NUMBER(10) NULL,
							SCHEDULE_B_CODE	VARCHAR2(40) NULL,
							TIMEZONE	VARCHAR2(40) NULL,
							INVOICED_PRICING_QUANTITY	NUMBER(14,4) NULL
						)';  
EXCEPTION  
   WHEN OTHERS THEN  
      IF SQLCODE != -955 THEN  
         RAISE;  
      END IF;  
END;

&


/*-----------------------------------------------*/
/* TASK No. 10 */
/* Truncate target table */

truncate table RAX_APP_USER.STG_ORDER_LINE


&


/*-----------------------------------------------*/
/* TASK No. 11 */
/* Insert new rows */

 
insert into	RAX_APP_USER.STG_ORDER_LINE 
( 
	SETTLED_AMOUNT,
	CUSTOMER_PO_NO,
	PRICING_UOM,
	PRIME_LINE_NO,
	ALLOCATION_LEAD_TIME,
	INVOICED_QUANTITY,
	DERIVED_FROM_ORDER_LINE_KEY,
	CURRENT_WORK_ORDER_KEY,
	DEPENDENCY_RATIO,
	CUSTOMER_PO_LINE_NO,
	DEPARTMENT_CODE,
	REQ_DELIVERY_DATE,
	EXTN_SECONDARY_REASON_CODE,
	DISCOUNT_REFERENCE,
	EXTN_SPRAY_FINISH_INCLUDED,
	ITEM_GROUP_CODE,
	GIFT_FLAG,
	IS_COST_OVERRIDDEN,
	MIN_SHIP_BY_DATE,
	EXTN_LINEN_INCLUDED,
	CHAINED_FROM_ORDER_HEADER_KEY,
	FULFILLMENT_TYPE,
	EXTN_CSR_CODE,
	UNIT_PRICE,
	EXTN_CURRENT_SHEET_EQUIVALENT,
	APPT_STATUS,
	WAIT_FOR_SEQ_LINE,
	IS_PRICE_LOCKED,
	DEPENDENT_ON_LINE_KEY,
	SEGMENT_TYPE,
	CREATEUSERID,
	ITEM_WEIGHT_UOM,
	ALTERNATE_ITEM_ID,
	SCHED_FAILURE_REASON_CODE,
	PROMISED_APPT_START_DATE,
	RESERVATION_ID,
	PIPELINE_KEY,
	ITEM_ID,
	EXTN_NO_OF_POSES_PER_UNIT,
	BASIC_CAPACITY_REQUIRED,
	UNIT_COST,
	OVER_RECEIPT_QUANTITY,
	CANNOT_COMPLETE_AFTER_DATE,
	ECCN_NO,
	SUB_LINE_NO,
	CREATEPROGID,
	HOLD_FLAG,
	MODIFYPROGID,
	UOM,
	DISTRIBUTION_RULE_ID,
	PRODUCT_LINE,
	SHIP_TO_ID,
	INVOICED_EXTENDED_PRICE,
	SPLIT_QTY,
	ISBN,
	CANNOT_COMPLETE_BEFORE_DATE,
	EARLIEST_DELIVERY_DATE,
	LINE_TOTAL,
	OTHER_CHARGES,
	CARRIER_SERVICE_CODE,
	SCAC,
	SUPPLIER_ITEM_DESCRIPTION,
	ORDERED_QTY,
	IS_FIRM_PREDEFINED_NODE,
	EXTN_PRIMARY_REASON_CODE,
	NMFC_CODE,
	CARRIER_ACCOUNT_NO,
	LINE_SEQ_NO,
	RESHIP_PARENT_LINE_KEY,
	INTENTIONAL_BACKORDER,
	SERIAL_NO,
	IS_PRICE_INFO_ONLY,
	ITEM_DESCRIPTION,
	PACKLIST_TYPE,
	LIST_PRICE,
	FIXED_CAPACITY_QTY_PER_LINE,
	MODIFYUSERID,
	EXTN_IS_TERRITORY_PROOF_SAMPLE,
	RECEIVED_QUANTITY,
	EXTN_TAXABLE,
	SEGMENT,
	EXTN_TRAN_DEPENDENCY,
	IS_CAPACITY_OVERRIDDEN,
	DERIVED_FROM_ORDER_RELEASE_KEY,
	NMFC_CLASS,
	UPC_CODE,
	DEPENDENCY_SHIPPING_RULE,
	ACTUAL_PRICING_QUANTITY,
	ORDER_LINE_KEY,
	EXTN_ACCOUNTING_TYPE,
	LOCKID,
	FOB,
	MANUFACTURER_ITEM_DESC,
	FUTURE_AVAIL_DATE,
	TAX_PRODUCT_CODE,
	EXTN_DISTINCT_NO_OF_POSES,
	FIRST_ITER_SEQ_NO,
	EXTN_ADDITIONAL_POSES,
	RECEIVING_NODE,
	SETTLED_QUANTITY,
	EXTN_SPRAY_FINISH_ALLOWED,
	SHIPMENT_CONSOL_GROUP_ID,
	CUSTOMER_ITEM,
	HOLD_REASON_CODE,
	KIT_CODE,
	EARLIEST_SHIP_DATE,
	CAN_ADD_SERVICE_LINES,
	CONDITION_VARIABLE_2,
	ORDER_CLASS,
	CREATETS,
	SHIPPED_QUANTITY,
	RESERVATION_MANDATORY,
	EXTN_IS_PACKAGE_SUBSTITUTED,
	EXTN_CR_NUMBER,
	CONDITION_VARIABLE_1,
	IS_PROCUREMENT_ALLOWED,
	SUPPLIER_ITEM,
	PERSONALIZE_FLAG,
	KIT_QTY,
	DERIVED_FROM_ORDER_HEADER_KEY,
	ORDERING_UOM,
	TAX,
	CUSTOMER_ITEM_DESCRIPTION,
	RESERVATION_POOL,
	LINE_TYPE,
	MARK_FOR_KEY,
	IS_FORWARDING_ALLOWED,
	EXTN_LOC_PER_QTY,
	NMFC_DESCRIPTION,
	PROMISED_APPT_END_DATE,
	CAPACITY_UOM,
	ORDER_HEADER_KEY,
	IMPORT_LICENSE_EXP_DATE,
	ORIG_ORDER_LINE_KEY,
	EARLIEST_SCHEDULE_DATE,
	EXTN_CAN_SUBSTITUTE_PACKAGE,
	COMMITTED_QUANTITY,
	IS_STANDALONE_SERVICE,
	TAXABLE_FLAG,
	FIXED_PRICING_QTY_PER_LINE,
	EXTN_CONFIG_POINT_EQUIVALENT,
	BUNDLE_PARENT_ORDER_LINE_KEY,
	EXTN_PKG_REFERENCE,
	EXTN_IS_PERFECT_PACKAGE,
	INVOICE_COMPLETE,
	RETURN_REASON,
	BUYER_RECEIVING_NODE_ID,
	SHIPNODE_KEY,
	SHIP_TO_KEY,
	EXTN_REQUESTED_BY,
	EXTN_REQUESTED_DATE,
	PROCURE_FROM_NODE,
	BUYER_MARK_FOR_NODE_ID,
	CHAINED_FROM_ORDER_LINE_KEY,
	PERSONALIZE_CODE,
	REPRICING_QUANTITY,
	EXTN_IS_PROOF_EXPRESS,
	EXTN_TAX_CODE,
	HARMONIZED_CODE,
	DISCOUNT_PERCENTAGE,
	EXTN_CURRENT_NO_OF_POSES,
	RETAIL_PRICE,
	PRICING_QUANTITY_CONV_FACTOR,
	EXTN_CURRENT_POINT_EQUIVALENT,
	INVOICED_LINE_TOTAL,
	ITEM_WEIGHT,
	SUPPLIER_CODE,
	TAX_EXEMPTION_CERTIFICATE,
	MODIFYTS,
	DELIVERY_CODE,
	EXTN_SORT_SEQ_NO,
	ITEM_SHORT_DESCRIPTION,
	PARENT_OF_DEPENDENT_GROUP,
	PICKABLE_FLAG,
	REQ_SHIP_DATE,
	EXTN_CONFIG_SHEET_EQUIVALENT,
	EXTN_ADDITIONAL_POINTS,
	OPTION_CAPACITY_REQUIRED,
	EXTN_LINEN_ALLOWED,
	CANNOT_MEET_APPT,
	MANUFACTURER_NAME,
	EXTN_SHEET_UNITS_PER_QTY,
	COST_CURRENCY,
	DELIVERY_METHOD,
	INVOICE_BASED_ON_ACTUALS,
	PURPOSE,
	REQ_CANCEL_DATE,
	MAINTAIN_RATIO,
	IMPORT_LICENSE_NO,
	FILL_QUANTITY,
	COUNTRY_OF_ORIGIN,
	TRAN_DISCREPANCY_QTY,
	MERGE_NODE,
	PRODUCT_CLASS,
	DISCOUNT_TYPE,
	ALLOCATE_DATE,
	EXTN_PERSONALIZATION_INCLUDED,
	PRICING_QUANTITY_STRATEGY,
	EXTN_TCREDIT_PERCENTAGE,
	ORIGINAL_ORDERED_QTY,
	SHIP_TOGETHER_NO,
	EXTN_ADDITIONAL_SHEETS,
	PRICING_QUANTITY,
	EXTN_TAX_INCLUSIVE,
	SOURCE_FROM_ORGANIZATION,
	PRICING_DATE,
	MANUFACTURER_ITEM,
	LAST_ITER_SEQ_NO,
	SCHEDULE_B_CODE,
	TIMEZONE,
	INVOICED_PRICING_QUANTITY 
	 
) 

select
    SETTLED_AMOUNT,
	CUSTOMER_PO_NO,
	PRICING_UOM,
	PRIME_LINE_NO,
	ALLOCATION_LEAD_TIME,
	INVOICED_QUANTITY,
	DERIVED_FROM_ORDER_LINE_KEY,
	CURRENT_WORK_ORDER_KEY,
	DEPENDENCY_RATIO,
	CUSTOMER_PO_LINE_NO,
	DEPARTMENT_CODE,
	REQ_DELIVERY_DATE,
	EXTN_SECONDARY_REASON_CODE,
	DISCOUNT_REFERENCE,
	EXTN_SPRAY_FINISH_INCLUDED,
	ITEM_GROUP_CODE,
	GIFT_FLAG,
	IS_COST_OVERRIDDEN,
	MIN_SHIP_BY_DATE,
	EXTN_LINEN_INCLUDED,
	CHAINED_FROM_ORDER_HEADER_KEY,
	FULFILLMENT_TYPE,
	EXTN_CSR_CODE,
	UNIT_PRICE,
	EXTN_CURRENT_SHEET_EQUIVALENT,
	APPT_STATUS,
	WAIT_FOR_SEQ_LINE,
	IS_PRICE_LOCKED,
	DEPENDENT_ON_LINE_KEY,
	SEGMENT_TYPE,
	CREATEUSERID,
	ITEM_WEIGHT_UOM,
	ALTERNATE_ITEM_ID,
	SCHED_FAILURE_REASON_CODE,
	PROMISED_APPT_START_DATE,
	RESERVATION_ID,
	PIPELINE_KEY,
	ITEM_ID,
	EXTN_NO_OF_POSES_PER_UNIT,
	BASIC_CAPACITY_REQUIRED,
	UNIT_COST,
	OVER_RECEIPT_QUANTITY,
	CANNOT_COMPLETE_AFTER_DATE,
	ECCN_NO,
	SUB_LINE_NO,
	CREATEPROGID,
	HOLD_FLAG,
	MODIFYPROGID,
	UOM,
	DISTRIBUTION_RULE_ID,
	PRODUCT_LINE,
	SHIP_TO_ID,
	INVOICED_EXTENDED_PRICE,
	SPLIT_QTY,
	ISBN,
	CANNOT_COMPLETE_BEFORE_DATE,
	EARLIEST_DELIVERY_DATE,
	LINE_TOTAL,
	OTHER_CHARGES,
	CARRIER_SERVICE_CODE,
	SCAC,
	SUPPLIER_ITEM_DESCRIPTION,
	ORDERED_QTY,
	IS_FIRM_PREDEFINED_NODE,
	EXTN_PRIMARY_REASON_CODE,
	NMFC_CODE,
	CARRIER_ACCOUNT_NO,
	LINE_SEQ_NO,
	RESHIP_PARENT_LINE_KEY,
	INTENTIONAL_BACKORDER,
	SERIAL_NO,
	IS_PRICE_INFO_ONLY,
	ITEM_DESCRIPTION,
	PACKLIST_TYPE,
	LIST_PRICE,
	FIXED_CAPACITY_QTY_PER_LINE,
	MODIFYUSERID,
	EXTN_IS_TERRITORY_PROOF_SAMPLE,
	RECEIVED_QUANTITY,
	EXTN_TAXABLE,
	SEGMENT,
	EXTN_TRAN_DEPENDENCY,
	IS_CAPACITY_OVERRIDDEN,
	DERIVED_FROM_ORDER_RELEASE_KEY,
	NMFC_CLASS,
	UPC_CODE,
	DEPENDENCY_SHIPPING_RULE,
	ACTUAL_PRICING_QUANTITY,
	ORDER_LINE_KEY,
	EXTN_ACCOUNTING_TYPE,
	LOCKID,
	FOB,
	MANUFACTURER_ITEM_DESC,
	FUTURE_AVAIL_DATE,
	TAX_PRODUCT_CODE,
	EXTN_DISTINCT_NO_OF_POSES,
	FIRST_ITER_SEQ_NO,
	EXTN_ADDITIONAL_POSES,
	RECEIVING_NODE,
	SETTLED_QUANTITY,
	EXTN_SPRAY_FINISH_ALLOWED,
	SHIPMENT_CONSOL_GROUP_ID,
	CUSTOMER_ITEM,
	HOLD_REASON_CODE,
	KIT_CODE,
	EARLIEST_SHIP_DATE,
	CAN_ADD_SERVICE_LINES,
	CONDITION_VARIABLE_2,
	ORDER_CLASS,
	CREATETS,
	SHIPPED_QUANTITY,
	RESERVATION_MANDATORY,
	EXTN_IS_PACKAGE_SUBSTITUTED,
	EXTN_CR_NUMBER,
	CONDITION_VARIABLE_1,
	IS_PROCUREMENT_ALLOWED,
	SUPPLIER_ITEM,
	PERSONALIZE_FLAG,
	KIT_QTY,
	DERIVED_FROM_ORDER_HEADER_KEY,
	ORDERING_UOM,
	TAX,
	CUSTOMER_ITEM_DESCRIPTION,
	RESERVATION_POOL,
	LINE_TYPE,
	MARK_FOR_KEY,
	IS_FORWARDING_ALLOWED,
	EXTN_LOC_PER_QTY,
	NMFC_DESCRIPTION,
	PROMISED_APPT_END_DATE,
	CAPACITY_UOM,
	ORDER_HEADER_KEY,
	IMPORT_LICENSE_EXP_DATE,
	ORIG_ORDER_LINE_KEY,
	EARLIEST_SCHEDULE_DATE,
	EXTN_CAN_SUBSTITUTE_PACKAGE,
	COMMITTED_QUANTITY,
	IS_STANDALONE_SERVICE,
	TAXABLE_FLAG,
	FIXED_PRICING_QTY_PER_LINE,
	EXTN_CONFIG_POINT_EQUIVALENT,
	BUNDLE_PARENT_ORDER_LINE_KEY,
	EXTN_PKG_REFERENCE,
	EXTN_IS_PERFECT_PACKAGE,
	INVOICE_COMPLETE,
	RETURN_REASON,
	BUYER_RECEIVING_NODE_ID,
	SHIPNODE_KEY,
	SHIP_TO_KEY,
	EXTN_REQUESTED_BY,
	EXTN_REQUESTED_DATE,
	PROCURE_FROM_NODE,
	BUYER_MARK_FOR_NODE_ID,
	CHAINED_FROM_ORDER_LINE_KEY,
	PERSONALIZE_CODE,
	REPRICING_QUANTITY,
	EXTN_IS_PROOF_EXPRESS,
	EXTN_TAX_CODE,
	HARMONIZED_CODE,
	DISCOUNT_PERCENTAGE,
	EXTN_CURRENT_NO_OF_POSES,
	RETAIL_PRICE,
	PRICING_QUANTITY_CONV_FACTOR,
	EXTN_CURRENT_POINT_EQUIVALENT,
	INVOICED_LINE_TOTAL,
	ITEM_WEIGHT,
	SUPPLIER_CODE,
	TAX_EXEMPTION_CERTIFICATE,
	MODIFYTS,
	DELIVERY_CODE,
	EXTN_SORT_SEQ_NO,
	ITEM_SHORT_DESCRIPTION,
	PARENT_OF_DEPENDENT_GROUP,
	PICKABLE_FLAG,
	REQ_SHIP_DATE,
	EXTN_CONFIG_SHEET_EQUIVALENT,
	EXTN_ADDITIONAL_POINTS,
	OPTION_CAPACITY_REQUIRED,
	EXTN_LINEN_ALLOWED,
	CANNOT_MEET_APPT,
	MANUFACTURER_NAME,
	EXTN_SHEET_UNITS_PER_QTY,
	COST_CURRENCY,
	DELIVERY_METHOD,
	INVOICE_BASED_ON_ACTUALS,
	PURPOSE,
	REQ_CANCEL_DATE,
	MAINTAIN_RATIO,
	IMPORT_LICENSE_NO,
	FILL_QUANTITY,
	COUNTRY_OF_ORIGIN,
	TRAN_DISCREPANCY_QTY,
	MERGE_NODE,
	PRODUCT_CLASS,
	DISCOUNT_TYPE,
	ALLOCATE_DATE,
	EXTN_PERSONALIZATION_INCLUDED,
	PRICING_QUANTITY_STRATEGY,
	EXTN_TCREDIT_PERCENTAGE,
	ORIGINAL_ORDERED_QTY,
	SHIP_TOGETHER_NO,
	EXTN_ADDITIONAL_SHEETS,
	PRICING_QUANTITY,
	EXTN_TAX_INCLUSIVE,
	SOURCE_FROM_ORGANIZATION,
	PRICING_DATE,
	MANUFACTURER_ITEM,
	LAST_ITER_SEQ_NO,
	SCHEDULE_B_CODE,
	TIMEZONE,
	INVOICED_PRICING_QUANTITY   
   
FROM (	


select 	
	C1_SETTLED_AMOUNT SETTLED_AMOUNT,
	C2_CUSTOMER_PO_NO CUSTOMER_PO_NO,
	C3_PRICING_UOM PRICING_UOM,
	C4_PRIME_LINE_NO PRIME_LINE_NO,
	C5_ALLOCATION_LEAD_TIME ALLOCATION_LEAD_TIME,
	C6_INVOICED_QUANTITY INVOICED_QUANTITY,
	C7_DERIVED_FROM_ORDER_LINE_KEY DERIVED_FROM_ORDER_LINE_KEY,
	C8_CURRENT_WORK_ORDER_KEY CURRENT_WORK_ORDER_KEY,
	C9_DEPENDENCY_RATIO DEPENDENCY_RATIO,
	C10_CUSTOMER_PO_LINE_NO CUSTOMER_PO_LINE_NO,
	C11_DEPARTMENT_CODE DEPARTMENT_CODE,
	C12_REQ_DELIVERY_DATE REQ_DELIVERY_DATE,
	C13_EXTN_SECONDARY_REASON_CODE EXTN_SECONDARY_REASON_CODE,
	C14_DISCOUNT_REFERENCE DISCOUNT_REFERENCE,
	C15_EXTN_SPRAY_FINISH_INCLUDED EXTN_SPRAY_FINISH_INCLUDED,
	C16_ITEM_GROUP_CODE ITEM_GROUP_CODE,
	C17_GIFT_FLAG GIFT_FLAG,
	C18_IS_COST_OVERRIDDEN IS_COST_OVERRIDDEN,
	C19_MIN_SHIP_BY_DATE MIN_SHIP_BY_DATE,
	C20_EXTN_LINEN_INCLUDED EXTN_LINEN_INCLUDED,
	C21_CHAINED_FROM_ORDER_HEADER_ CHAINED_FROM_ORDER_HEADER_KEY,
	C22_FULFILLMENT_TYPE FULFILLMENT_TYPE,
	C23_EXTN_CSR_CODE EXTN_CSR_CODE,
	C24_UNIT_PRICE UNIT_PRICE,
	C25_EXTN_CURRENT_SHEET_EQUIVAL EXTN_CURRENT_SHEET_EQUIVALENT,
	C26_APPT_STATUS APPT_STATUS,
	C27_WAIT_FOR_SEQ_LINE WAIT_FOR_SEQ_LINE,
	C28_IS_PRICE_LOCKED IS_PRICE_LOCKED,
	C29_DEPENDENT_ON_LINE_KEY DEPENDENT_ON_LINE_KEY,
	C30_SEGMENT_TYPE SEGMENT_TYPE,
	C31_CREATEUSERID CREATEUSERID,
	C32_ITEM_WEIGHT_UOM ITEM_WEIGHT_UOM,
	C33_ALTERNATE_ITEM_ID ALTERNATE_ITEM_ID,
	C34_SCHED_FAILURE_REASON_CODE SCHED_FAILURE_REASON_CODE,
	C35_PROMISED_APPT_START_DATE PROMISED_APPT_START_DATE,
	C36_RESERVATION_ID RESERVATION_ID,
	C37_PIPELINE_KEY PIPELINE_KEY,
	C38_ITEM_ID ITEM_ID,
	C39_EXTN_NO_OF_POSES_PER_UNIT EXTN_NO_OF_POSES_PER_UNIT,
	C40_BASIC_CAPACITY_REQUIRED BASIC_CAPACITY_REQUIRED,
	C41_UNIT_COST UNIT_COST,
	C42_OVER_RECEIPT_QUANTITY OVER_RECEIPT_QUANTITY,
	C43_CANNOT_COMPLETE_AFTER_DATE CANNOT_COMPLETE_AFTER_DATE,
	C44_ECCN_NO ECCN_NO,
	C45_SUB_LINE_NO SUB_LINE_NO,
	C46_CREATEPROGID CREATEPROGID,
	C47_HOLD_FLAG HOLD_FLAG,
	C48_MODIFYPROGID MODIFYPROGID,
	C49_UOM UOM,
	C50_DISTRIBUTION_RULE_ID DISTRIBUTION_RULE_ID,
	C51_PRODUCT_LINE PRODUCT_LINE,
	C52_SHIP_TO_ID SHIP_TO_ID,
	C53_INVOICED_EXTENDED_PRICE INVOICED_EXTENDED_PRICE,
	C54_SPLIT_QTY SPLIT_QTY,
	C55_ISBN ISBN,
	C56_CANNOT_COMPLETE_BEFORE_DAT CANNOT_COMPLETE_BEFORE_DATE,
	C57_EARLIEST_DELIVERY_DATE EARLIEST_DELIVERY_DATE,
	C58_LINE_TOTAL LINE_TOTAL,
	C59_OTHER_CHARGES OTHER_CHARGES,
	C60_CARRIER_SERVICE_CODE CARRIER_SERVICE_CODE,
	C61_SCAC SCAC,
	C62_SUPPLIER_ITEM_DESCRIPTION SUPPLIER_ITEM_DESCRIPTION,
	C63_ORDERED_QTY ORDERED_QTY,
	C64_IS_FIRM_PREDEFINED_NODE IS_FIRM_PREDEFINED_NODE,
	C65_EXTN_PRIMARY_REASON_CODE EXTN_PRIMARY_REASON_CODE,
	C66_NMFC_CODE NMFC_CODE,
	C67_CARRIER_ACCOUNT_NO CARRIER_ACCOUNT_NO,
	C68_LINE_SEQ_NO LINE_SEQ_NO,
	C69_RESHIP_PARENT_LINE_KEY RESHIP_PARENT_LINE_KEY,
	C70_INTENTIONAL_BACKORDER INTENTIONAL_BACKORDER,
	C71_SERIAL_NO SERIAL_NO,
	C72_IS_PRICE_INFO_ONLY IS_PRICE_INFO_ONLY,
	C73_ITEM_DESCRIPTION ITEM_DESCRIPTION,
	C74_PACKLIST_TYPE PACKLIST_TYPE,
	C75_LIST_PRICE LIST_PRICE,
	C76_FIXED_CAPACITY_QTY_PER_LIN FIXED_CAPACITY_QTY_PER_LINE,
	C77_MODIFYUSERID MODIFYUSERID,
	C78_EXTN_IS_TERRITORY_PROOF_SA EXTN_IS_TERRITORY_PROOF_SAMPLE,
	C79_RECEIVED_QUANTITY RECEIVED_QUANTITY,
	C80_EXTN_TAXABLE EXTN_TAXABLE,
	C81_SEGMENT SEGMENT,
	C82_EXTN_TRAN_DEPENDENCY EXTN_TRAN_DEPENDENCY,
	C83_IS_CAPACITY_OVERRIDDEN IS_CAPACITY_OVERRIDDEN,
	C84_DERIVED_FROM_ORDER_RELEASE DERIVED_FROM_ORDER_RELEASE_KEY,
	C85_NMFC_CLASS NMFC_CLASS,
	C86_UPC_CODE UPC_CODE,
	C87_DEPENDENCY_SHIPPING_RULE DEPENDENCY_SHIPPING_RULE,
	C88_ACTUAL_PRICING_QUANTITY ACTUAL_PRICING_QUANTITY,
	C89_ORDER_LINE_KEY ORDER_LINE_KEY,
	C90_EXTN_ACCOUNTING_TYPE EXTN_ACCOUNTING_TYPE,
	C91_LOCKID LOCKID,
	C92_FOB FOB,
	C93_MANUFACTURER_ITEM_DESC MANUFACTURER_ITEM_DESC,
	C94_FUTURE_AVAIL_DATE FUTURE_AVAIL_DATE,
	C95_TAX_PRODUCT_CODE TAX_PRODUCT_CODE,
	C96_EXTN_DISTINCT_NO_OF_POSES EXTN_DISTINCT_NO_OF_POSES,
	C97_FIRST_ITER_SEQ_NO FIRST_ITER_SEQ_NO,
	C98_EXTN_ADDITIONAL_POSES EXTN_ADDITIONAL_POSES,
	C99_RECEIVING_NODE RECEIVING_NODE,
	C100_SETTLED_QUANTITY SETTLED_QUANTITY,
	C101_EXTN_SPRAY_FINISH_ALLOWED EXTN_SPRAY_FINISH_ALLOWED,
	C102_SHIPMENT_CONSOL_GROUP_ID SHIPMENT_CONSOL_GROUP_ID,
	C103_CUSTOMER_ITEM CUSTOMER_ITEM,
	C104_HOLD_REASON_CODE HOLD_REASON_CODE,
	C105_KIT_CODE KIT_CODE,
	C106_EARLIEST_SHIP_DATE EARLIEST_SHIP_DATE,
	C107_CAN_ADD_SERVICE_LINES CAN_ADD_SERVICE_LINES,
	C108_CONDITION_VARIABLE_2 CONDITION_VARIABLE_2,
	C109_ORDER_CLASS ORDER_CLASS,
	C110_CREATETS CREATETS,
	C111_SHIPPED_QUANTITY SHIPPED_QUANTITY,
	C112_RESERVATION_MANDATORY RESERVATION_MANDATORY,
	C113_EXTN_IS_PACKAGE_SUBSTITUT EXTN_IS_PACKAGE_SUBSTITUTED,
	C114_EXTN_CR_NUMBER EXTN_CR_NUMBER,
	C115_CONDITION_VARIABLE_1 CONDITION_VARIABLE_1,
	C116_IS_PROCUREMENT_ALLOWED IS_PROCUREMENT_ALLOWED,
	C117_SUPPLIER_ITEM SUPPLIER_ITEM,
	C118_PERSONALIZE_FLAG PERSONALIZE_FLAG,
	C119_KIT_QTY KIT_QTY,
	C120_DERIVED_FROM_ORDER_HEADER DERIVED_FROM_ORDER_HEADER_KEY,
	C121_ORDERING_UOM ORDERING_UOM,
	C122_TAX TAX,
	C123_CUSTOMER_ITEM_DESCRIPTION CUSTOMER_ITEM_DESCRIPTION,
	C124_RESERVATION_POOL RESERVATION_POOL,
	C125_LINE_TYPE LINE_TYPE,
	C126_MARK_FOR_KEY MARK_FOR_KEY,
	C127_IS_FORWARDING_ALLOWED IS_FORWARDING_ALLOWED,
	C128_EXTN_LOC_PER_QTY EXTN_LOC_PER_QTY,
	C129_NMFC_DESCRIPTION NMFC_DESCRIPTION,
	C130_PROMISED_APPT_END_DATE PROMISED_APPT_END_DATE,
	C131_CAPACITY_UOM CAPACITY_UOM,
	C132_ORDER_HEADER_KEY ORDER_HEADER_KEY,
	C133_IMPORT_LICENSE_EXP_DATE IMPORT_LICENSE_EXP_DATE,
	C134_ORIG_ORDER_LINE_KEY ORIG_ORDER_LINE_KEY,
	C135_EARLIEST_SCHEDULE_DATE EARLIEST_SCHEDULE_DATE,
	C136_EXTN_CAN_SUBSTITUTE_PACKA EXTN_CAN_SUBSTITUTE_PACKAGE,
	C137_COMMITTED_QUANTITY COMMITTED_QUANTITY,
	C138_IS_STANDALONE_SERVICE IS_STANDALONE_SERVICE,
	C139_TAXABLE_FLAG TAXABLE_FLAG,
	C140_FIXED_PRICING_QTY_PER_LIN FIXED_PRICING_QTY_PER_LINE,
	C141_EXTN_CONFIG_POINT_EQUIVAL EXTN_CONFIG_POINT_EQUIVALENT,
	C142_BUNDLE_PARENT_ORDER_LINE_ BUNDLE_PARENT_ORDER_LINE_KEY,
	C143_EXTN_PKG_REFERENCE EXTN_PKG_REFERENCE,
	C144_EXTN_IS_PERFECT_PACKAGE EXTN_IS_PERFECT_PACKAGE,
	C145_INVOICE_COMPLETE INVOICE_COMPLETE,
	C146_RETURN_REASON RETURN_REASON,
	C147_BUYER_RECEIVING_NODE_ID BUYER_RECEIVING_NODE_ID,
	C148_SHIPNODE_KEY SHIPNODE_KEY,
	C149_SHIP_TO_KEY SHIP_TO_KEY,
	C150_EXTN_REQUESTED_BY EXTN_REQUESTED_BY,
	C151_EXTN_REQUESTED_DATE EXTN_REQUESTED_DATE,
	C152_PROCURE_FROM_NODE PROCURE_FROM_NODE,
	C153_BUYER_MARK_FOR_NODE_ID BUYER_MARK_FOR_NODE_ID,
	C154_CHAINED_FROM_ORDER_LINE_K CHAINED_FROM_ORDER_LINE_KEY,
	C155_PERSONALIZE_CODE PERSONALIZE_CODE,
	C156_REPRICING_QUANTITY REPRICING_QUANTITY,
	C157_EXTN_IS_PROOF_EXPRESS EXTN_IS_PROOF_EXPRESS,
	C158_EXTN_TAX_CODE EXTN_TAX_CODE,
	C159_HARMONIZED_CODE HARMONIZED_CODE,
	C160_DISCOUNT_PERCENTAGE DISCOUNT_PERCENTAGE,
	C161_EXTN_CURRENT_NO_OF_POSES EXTN_CURRENT_NO_OF_POSES,
	C162_RETAIL_PRICE RETAIL_PRICE,
	C163_PRICING_QUANTITY_CONV_FAC PRICING_QUANTITY_CONV_FACTOR,
	C164_EXTN_CURRENT_POINT_EQUIVA EXTN_CURRENT_POINT_EQUIVALENT,
	C165_INVOICED_LINE_TOTAL INVOICED_LINE_TOTAL,
	C166_ITEM_WEIGHT ITEM_WEIGHT,
	C167_SUPPLIER_CODE SUPPLIER_CODE,
	C168_TAX_EXEMPTION_CERTIFICATE TAX_EXEMPTION_CERTIFICATE,
	C169_MODIFYTS MODIFYTS,
	C170_DELIVERY_CODE DELIVERY_CODE,
	C171_EXTN_SORT_SEQ_NO EXTN_SORT_SEQ_NO,
	C172_ITEM_SHORT_DESCRIPTION ITEM_SHORT_DESCRIPTION,
	C173_PARENT_OF_DEPENDENT_GROUP PARENT_OF_DEPENDENT_GROUP,
	C174_PICKABLE_FLAG PICKABLE_FLAG,
	C175_REQ_SHIP_DATE REQ_SHIP_DATE,
	C176_EXTN_CONFIG_SHEET_EQUIVAL EXTN_CONFIG_SHEET_EQUIVALENT,
	C177_EXTN_ADDITIONAL_POINTS EXTN_ADDITIONAL_POINTS,
	C178_OPTION_CAPACITY_REQUIRED OPTION_CAPACITY_REQUIRED,
	C179_EXTN_LINEN_ALLOWED EXTN_LINEN_ALLOWED,
	C180_CANNOT_MEET_APPT CANNOT_MEET_APPT,
	C181_MANUFACTURER_NAME MANUFACTURER_NAME,
	C182_EXTN_SHEET_UNITS_PER_QTY EXTN_SHEET_UNITS_PER_QTY,
	C183_COST_CURRENCY COST_CURRENCY,
	C184_DELIVERY_METHOD DELIVERY_METHOD,
	C185_INVOICE_BASED_ON_ACTUALS INVOICE_BASED_ON_ACTUALS,
	C186_PURPOSE PURPOSE,
	C187_REQ_CANCEL_DATE REQ_CANCEL_DATE,
	C188_MAINTAIN_RATIO MAINTAIN_RATIO,
	C189_IMPORT_LICENSE_NO IMPORT_LICENSE_NO,
	C190_FILL_QUANTITY FILL_QUANTITY,
	C191_COUNTRY_OF_ORIGIN COUNTRY_OF_ORIGIN,
	C192_TRAN_DISCREPANCY_QTY TRAN_DISCREPANCY_QTY,
	C193_MERGE_NODE MERGE_NODE,
	C194_PRODUCT_CLASS PRODUCT_CLASS,
	C195_DISCOUNT_TYPE DISCOUNT_TYPE,
	C196_ALLOCATE_DATE ALLOCATE_DATE,
	C197_EXTN_PERSONALIZATION_INCL EXTN_PERSONALIZATION_INCLUDED,
	C198_PRICING_QUANTITY_STRATEGY PRICING_QUANTITY_STRATEGY,
	C199_EXTN_TCREDIT_PERCENTAGE EXTN_TCREDIT_PERCENTAGE,
	C200_ORIGINAL_ORDERED_QTY ORIGINAL_ORDERED_QTY,
	C201_SHIP_TOGETHER_NO SHIP_TOGETHER_NO,
	C202_EXTN_ADDITIONAL_SHEETS EXTN_ADDITIONAL_SHEETS,
	C203_PRICING_QUANTITY PRICING_QUANTITY,
	C204_EXTN_TAX_INCLUSIVE EXTN_TAX_INCLUSIVE,
	C205_SOURCE_FROM_ORGANIZATION SOURCE_FROM_ORGANIZATION,
	C206_PRICING_DATE PRICING_DATE,
	C207_MANUFACTURER_ITEM MANUFACTURER_ITEM,
	C208_LAST_ITER_SEQ_NO LAST_ITER_SEQ_NO,
	C209_SCHEDULE_B_CODE SCHEDULE_B_CODE,
	C210_TIMEZONE TIMEZONE,
	C211_INVOICED_PRICING_QUANTITY INVOICED_PRICING_QUANTITY 
from	RAX_APP_USER.C$_0STG_ORDER_LINE
where		(1=1)	






)    ODI_GET_FROM




&


/*-----------------------------------------------*/
/* TASK No. 12 */
/* Commit transaction */

/* commit */


/*-----------------------------------------------*/
/* TASK No. 1000008 */
/* Drop work table */

drop table RAX_APP_USER.C$_0STG_ORDER_LINE 

&


/*-----------------------------------------------*/
/* TASK No. 13 */
/* Set vID */

/* NONE or SET VARIABLE STATEMENT FOUND, CHECK ODI TASK NO. 13 */




/*-----------------------------------------------*/
/* TASK No. 14 */
/* Drop flow table */

BEGIN  
   EXECUTE IMMEDIATE 'drop table RAX_APP_USER.I$_OMS_ORDER_LINE_XR68001';  
EXCEPTION  
   WHEN OTHERS THEN  
      IF SQLCODE != -942 THEN  
         RAISE;  
      END IF;  
END;

&


/*-----------------------------------------------*/
/* TASK No. 15 */
/* Create flow table I$ */

create table RAX_APP_USER.I$_OMS_ORDER_LINE_XR68001
(
	ORDER_LINE_OID	NUMBER(22) NULL,
	ORDER_LINE_KEY	VARCHAR2(24) NULL,
	ODS_CREATE_DATE	DATE NULL,
	ORDER_HEADER_KEY	VARCHAR2(24) NULL,
	ITEM_KEY	VARCHAR2(24) NULL,
	BUNDLE_PARENT_ORDER_LINE_KEY	VARCHAR2(24) NULL
	,IND_UPDATE		char(1)
)
NOLOGGING

&


/*-----------------------------------------------*/
/* TASK No. 16 */
/* Insert flow into I$ table */

/* DETECTION_STRATEGY = NOT_EXISTS */
 


  


insert into	RAX_APP_USER.I$_OMS_ORDER_LINE_XR68001
(
	ORDER_LINE_KEY,
	ORDER_HEADER_KEY,
	ITEM_KEY,
	BUNDLE_PARENT_ORDER_LINE_KEY,
	IND_UPDATE
)
select 
ORDER_LINE_KEY,
	ORDER_HEADER_KEY,
	ITEM_KEY,
	BUNDLE_PARENT_ORDER_LINE_KEY,
	IND_UPDATE
 from (


select 	 
	DISTINCT
	TRIM(OL.ORDER_LINE_KEY) ORDER_LINE_KEY,
	TRIM(OL.ORDER_HEADER_KEY) ORDER_HEADER_KEY,
	TRIM(OL.ITEM_ID) ITEM_KEY,
	TRIM(OL.BUNDLE_PARENT_ORDER_LINE_KEY) BUNDLE_PARENT_ORDER_LINE_KEY,

	'I' IND_UPDATE

from	RAX_APP_USER.STG_ORDER_LINE   OL, ODS_STAGE.OMS_ORDER_LINE_XR   OMS_ORDER_LINE_XR
where	(1=1)
 And (TRIM(OL.ORDER_LINE_KEY)=OMS_ORDER_LINE_XR.ORDER_LINE_KEY (+)
AND OMS_ORDER_LINE_XR.ORDER_LINE_KEY IS NULL)





) S
where NOT EXISTS 
	( select 1 from ODS_STAGE.OMS_ORDER_LINE_XR T
	where	T.ORDER_LINE_KEY	= S.ORDER_LINE_KEY 
		 and ((T.ORDER_HEADER_KEY = S.ORDER_HEADER_KEY) or (T.ORDER_HEADER_KEY IS NULL and S.ORDER_HEADER_KEY IS NULL)) and
		((T.ITEM_KEY = S.ITEM_KEY) or (T.ITEM_KEY IS NULL and S.ITEM_KEY IS NULL)) and
		((T.BUNDLE_PARENT_ORDER_LINE_KEY = S.BUNDLE_PARENT_ORDER_LINE_KEY) or (T.BUNDLE_PARENT_ORDER_LINE_KEY IS NULL and S.BUNDLE_PARENT_ORDER_LINE_KEY IS NULL))
        )

  
  

  



&


/*-----------------------------------------------*/
/* TASK No. 17 */
/* Analyze integration table */



begin
    dbms_stats.gather_table_stats(
	ownname => 'RAX_APP_USER',
	tabname => 'I$_OMS_ORDER_LINE_XR68001',
	estimate_percent => dbms_stats.auto_sample_size
    );
end;



&


/*-----------------------------------------------*/
/* TASK No. 18 */
/* Create Index on flow table */

create index	RAX_APP_USER.I$_OMS_ORDER_LINE_XR_IDX68001
on		RAX_APP_USER.I$_OMS_ORDER_LINE_XR68001 (ORDER_LINE_KEY)
NOLOGGING

&


/*-----------------------------------------------*/
/* TASK No. 19 */
/* Merge Rows */

merge into	ODS_STAGE.OMS_ORDER_LINE_XR T
using	RAX_APP_USER.I$_OMS_ORDER_LINE_XR68001 S
on	(
		T.ORDER_LINE_KEY=S.ORDER_LINE_KEY
	)
when matched
then update set
	T.ORDER_HEADER_KEY	= S.ORDER_HEADER_KEY,
	T.ITEM_KEY	= S.ITEM_KEY,
	T.BUNDLE_PARENT_ORDER_LINE_KEY	= S.BUNDLE_PARENT_ORDER_LINE_KEY
	
when not matched
then insert
	(
	T.ORDER_LINE_KEY,
	T.ORDER_HEADER_KEY,
	T.ITEM_KEY,
	T.BUNDLE_PARENT_ORDER_LINE_KEY
	,    T.ORDER_LINE_OID,
	T.ODS_CREATE_DATE
	)
values
	(
	S.ORDER_LINE_KEY,
	S.ORDER_HEADER_KEY,
	S.ITEM_KEY,
	S.BUNDLE_PARENT_ORDER_LINE_KEY
	,    ODS_STAGE.ORDER_LINE_OID_SEQ.nextval,
	SYSDATE
	)

&


/*-----------------------------------------------*/
/* TASK No. 20 */
/* Commit transaction */

/*commit*/


/*-----------------------------------------------*/
/* TASK No. 21 */
/* Drop flow table */

drop table RAX_APP_USER.I$_OMS_ORDER_LINE_XR68001 

&


/*-----------------------------------------------*/
/* TASK No. 22 */
/* Drop flow table */

BEGIN  
   EXECUTE IMMEDIATE 'drop table RAX_APP_USER.I$_ORDER_LINE';  
EXCEPTION  
   WHEN OTHERS THEN  
      IF SQLCODE != -942 THEN  
         RAISE;  
      END IF;  
END;

&


/*-----------------------------------------------*/
/* TASK No. 23 */
/* Create flow table I$ */

create table RAX_APP_USER.I$_ORDER_LINE
(
	ORDER_LINE_OID		NUMBER NULL,
	UNIT_PRICE		NUMBER NULL,
	ORDERED_QUANTITY		NUMBER NULL,
	LIST_PRICE		NUMBER NULL,
	RETAIL_PRICE		NUMBER NULL,
	ORDER_HEADER_OID		NUMBER NULL,
	ITEM_OID		NUMBER NULL,
	BUNDLE_PARENT_ORDER_LINE_OID		NUMBER NULL,
	PACKAGE_REF		VARCHAR2(40) NULL,
	SHIPPED_QTY		NUMBER NULL,
	SORT_SEQ_NO		VARCHAR2(40) NULL,
	HOLD_FLAG		VARCHAR2(1) NULL,
	LINE_SEQ_NO		VARCHAR2(40) NULL,
	ODS_CREATE_DATE		DATE NULL,
	ODS_MODIFY_DATE		DATE NULL,
	SOURCE_SYSTEM_OID		NUMBER NULL,
	KIT_CODE		VARCHAR2(20) NULL,
	LINE_TOTAL		NUMBER NULL,
	EARLIEST_SCHEDULE_DATE		DATE NULL,
	SHIP_NODE_OID		NUMBER NULL,
	IND_UPDATE		CHAR(1)
)
NOLOGGING

&


/*-----------------------------------------------*/
/* TASK No. 24 */
/* Insert flow into I$ table */

/* DETECTION_STRATEGY = NOT_EXISTS */
 


  


insert into	RAX_APP_USER.I$_ORDER_LINE
(
	ORDER_LINE_OID,
	UNIT_PRICE,
	ORDERED_QUANTITY,
	LIST_PRICE,
	RETAIL_PRICE,
	ORDER_HEADER_OID,
	ITEM_OID,
	BUNDLE_PARENT_ORDER_LINE_OID,
	PACKAGE_REF,
	SHIPPED_QTY,
	SORT_SEQ_NO,
	HOLD_FLAG,
	LINE_SEQ_NO,
	SOURCE_SYSTEM_OID,
	KIT_CODE,
	LINE_TOTAL,
	EARLIEST_SCHEDULE_DATE,
	SHIP_NODE_OID,
	IND_UPDATE
)
select 
ORDER_LINE_OID,
	UNIT_PRICE,
	ORDERED_QUANTITY,
	LIST_PRICE,
	RETAIL_PRICE,
	ORDER_HEADER_OID,
	ITEM_OID,
	BUNDLE_PARENT_ORDER_LINE_OID,
	PACKAGE_REF,
	SHIPPED_QTY,
	SORT_SEQ_NO,
	HOLD_FLAG,
	LINE_SEQ_NO,
	SOURCE_SYSTEM_OID,
	KIT_CODE,
	LINE_TOTAL,
	EARLIEST_SCHEDULE_DATE,
	SHIP_NODE_OID,
	IND_UPDATE
 from (


select 	 
	
	XR.ORDER_LINE_OID ORDER_LINE_OID,
	OL.UNIT_PRICE UNIT_PRICE,
	OL.ORDERED_QTY ORDERED_QUANTITY,
	OL.LIST_PRICE LIST_PRICE,
	OL.RETAIL_PRICE RETAIL_PRICE,
	OMS_OH_XR.ORDER_HEADER_OID ORDER_HEADER_OID,
	ITEM.ITEM_OID ITEM_OID,
	OMS_PARENT_OL_XR.ORDER_LINE_OID BUNDLE_PARENT_ORDER_LINE_OID,
	OL.EXTN_PKG_REFERENCE PACKAGE_REF,
	OL.SHIPPED_QUANTITY SHIPPED_QTY,
	OL.EXTN_SORT_SEQ_NO SORT_SEQ_NO,
	OL.HOLD_FLAG HOLD_FLAG,
	OL.LINE_SEQ_NO LINE_SEQ_NO,
	SOURCE_SYSTEM.SOURCE_SYSTEM_OID SOURCE_SYSTEM_OID,
	OL.KIT_CODE KIT_CODE,
	OL.LINE_TOTAL LINE_TOTAL,
	OL.EARLIEST_SCHEDULE_DATE EARLIEST_SCHEDULE_DATE,
	SHIP_NODE.SHIP_NODE_OID SHIP_NODE_OID,

	'I' IND_UPDATE

from	RAX_APP_USER.STG_ORDER_LINE   OL, ODS_OWN.SOURCE_SYSTEM   SOURCE_SYSTEM, ODS_STAGE.OMS_ORDER_LINE_XR   XR, ODS_OWN.ITEM   ITEM, ODS_STAGE.OMS_ORDER_HEADER_XR   OMS_OH_XR, ODS_STAGE.OMS_ORDER_LINE_XR   OMS_PARENT_OL_XR, ODS_OWN.SHIP_NODE   SHIP_NODE
where	(1=1)
 And (TRIM(OL.ORDER_LINE_KEY)=XR.ORDER_LINE_KEY)
AND (trim(XR.ITEM_KEY)=ITEM.ITEM_ID (+))
AND (TRIM(XR.ORDER_HEADER_KEY)=OMS_OH_XR.ORDER_HEADER_KEY (+))
AND (TRIM(XR.BUNDLE_PARENT_ORDER_LINE_KEY)=OMS_PARENT_OL_XR.ORDER_LINE_KEY (+))
AND (TRIM(OL.SHIPNODE_KEY)=SHIP_NODE.SHIP_NODE (+))
And (SOURCE_SYSTEM.SOURCE_SYSTEM_SHORT_NAME='OMS')




) S
where NOT EXISTS 
	( select 1 from ODS_OWN.ORDER_LINE T
	where	T.ORDER_LINE_OID	= S.ORDER_LINE_OID 
		 and ((T.UNIT_PRICE = S.UNIT_PRICE) or (T.UNIT_PRICE IS NULL and S.UNIT_PRICE IS NULL)) and
		((T.ORDERED_QUANTITY = S.ORDERED_QUANTITY) or (T.ORDERED_QUANTITY IS NULL and S.ORDERED_QUANTITY IS NULL)) and
		((T.LIST_PRICE = S.LIST_PRICE) or (T.LIST_PRICE IS NULL and S.LIST_PRICE IS NULL)) and
		((T.RETAIL_PRICE = S.RETAIL_PRICE) or (T.RETAIL_PRICE IS NULL and S.RETAIL_PRICE IS NULL)) and
		((T.ORDER_HEADER_OID = S.ORDER_HEADER_OID) or (T.ORDER_HEADER_OID IS NULL and S.ORDER_HEADER_OID IS NULL)) and
		((T.ITEM_OID = S.ITEM_OID) or (T.ITEM_OID IS NULL and S.ITEM_OID IS NULL)) and
		((T.BUNDLE_PARENT_ORDER_LINE_OID = S.BUNDLE_PARENT_ORDER_LINE_OID) or (T.BUNDLE_PARENT_ORDER_LINE_OID IS NULL and S.BUNDLE_PARENT_ORDER_LINE_OID IS NULL)) and
		((T.PACKAGE_REF = S.PACKAGE_REF) or (T.PACKAGE_REF IS NULL and S.PACKAGE_REF IS NULL)) and
		((T.SHIPPED_QTY = S.SHIPPED_QTY) or (T.SHIPPED_QTY IS NULL and S.SHIPPED_QTY IS NULL)) and
		((T.SORT_SEQ_NO = S.SORT_SEQ_NO) or (T.SORT_SEQ_NO IS NULL and S.SORT_SEQ_NO IS NULL)) and
		((T.HOLD_FLAG = S.HOLD_FLAG) or (T.HOLD_FLAG IS NULL and S.HOLD_FLAG IS NULL)) and
		((T.LINE_SEQ_NO = S.LINE_SEQ_NO) or (T.LINE_SEQ_NO IS NULL and S.LINE_SEQ_NO IS NULL)) and
		((T.SOURCE_SYSTEM_OID = S.SOURCE_SYSTEM_OID) or (T.SOURCE_SYSTEM_OID IS NULL and S.SOURCE_SYSTEM_OID IS NULL)) and
		((T.KIT_CODE = S.KIT_CODE) or (T.KIT_CODE IS NULL and S.KIT_CODE IS NULL)) and
		((T.LINE_TOTAL = S.LINE_TOTAL) or (T.LINE_TOTAL IS NULL and S.LINE_TOTAL IS NULL)) and
		((T.EARLIEST_SCHEDULE_DATE = S.EARLIEST_SCHEDULE_DATE) or (T.EARLIEST_SCHEDULE_DATE IS NULL and S.EARLIEST_SCHEDULE_DATE IS NULL)) and
		((T.SHIP_NODE_OID = S.SHIP_NODE_OID) or (T.SHIP_NODE_OID IS NULL and S.SHIP_NODE_OID IS NULL))
        )

  
  

  

 


&


/*-----------------------------------------------*/
/* TASK No. 25 */
/* Recycle previous errors */

BEGIN  
   EXECUTE IMMEDIATE 'insert into RAX_APP_USER.I$_ORDER_LINE
						(
							ORDER_LINE_OID,
							UNIT_PRICE,
							ORDERED_QUANTITY,
							LIST_PRICE,
							RETAIL_PRICE,
							ORDER_HEADER_OID,
							ITEM_OID,
							BUNDLE_PARENT_ORDER_LINE_OID,
							PACKAGE_REF,
							SHIPPED_QTY,
							SORT_SEQ_NO,
							HOLD_FLAG,
							LINE_SEQ_NO,
							SOURCE_SYSTEM_OID,
							KIT_CODE,
							LINE_TOTAL,
							EARLIEST_SCHEDULE_DATE,
							SHIP_NODE_OID,
							IND_UPDATE
						)
						select 	ORDER_LINE_OID,
							UNIT_PRICE,
							ORDERED_QUANTITY,
							LIST_PRICE,
							RETAIL_PRICE,
							ORDER_HEADER_OID,
							ITEM_OID,
							BUNDLE_PARENT_ORDER_LINE_OID,
							PACKAGE_REF,
							SHIPPED_QTY,
							SORT_SEQ_NO,
							HOLD_FLAG,
							LINE_SEQ_NO,
							SOURCE_SYSTEM_OID,
							KIT_CODE,
							LINE_TOTAL,
							EARLIEST_SCHEDULE_DATE,
							SHIP_NODE_OID,
							''I''	IND_UPDATE
						from 	RAX_APP_USER.E$_ORDER_LINE
						where 	(ORDER_LINE_OID, ROWID)  in ( 
								select	ORDER_LINE_OID,MAX(ROWID)
								from RAX_APP_USER.E$_ORDER_LINE E
								where not exists (select 1  
									from	RAX_APP_USER.I$_ORDER_LINE T
									where	T.ORDER_LINE_OID = E.ORDER_LINE_OID)
								and	E.ODI_ORIGIN	= ''(70001)ODS_Project.LOAD_ORDER_LINE_INT''
								and	E.ODI_ERR_TYPE	= ''F''
								group by E.ORDER_LINE_OID
								)';  
EXCEPTION  
   WHEN OTHERS THEN  
      IF SQLCODE != -942 THEN  
         RAISE;  
      END IF;  
END;

&


/*-----------------------------------------------*/
/* TASK No. 26 */
/* Create Index on flow table */

create index	RAX_APP_USER.I$_ORDER_LINE_IDX
on		RAX_APP_USER.I$_ORDER_LINE (ORDER_LINE_OID)
NOLOGGING

&


/*-----------------------------------------------*/
/* TASK No. 27 */
/* Analyze integration table */



begin
    dbms_stats.gather_table_stats(
	ownname => 'RAX_APP_USER',
	tabname => 'I$_ORDER_LINE',
	estimate_percent => dbms_stats.auto_sample_size
    );
end;



&


/*-----------------------------------------------*/
/* TASK No. 28 */
/* create check table */


BEGIN  
   EXECUTE IMMEDIATE 'create table RAX_APP_USER.SNP_CHECK_TAB
						(
							CATALOG_NAME	VARCHAR2(100 CHAR) NULL ,
							SCHEMA_NAME	VARCHAR2(100 CHAR) NULL ,
							RESOURCE_NAME	VARCHAR2(100 CHAR) NULL,
							FULL_RES_NAME	VARCHAR2(100 CHAR) NULL,
							ERR_TYPE		VARCHAR2(1 CHAR) NULL,
							ERR_MESS		VARCHAR2(250 CHAR) NULL ,
							CHECK_DATE	DATE NULL,
							ORIGIN		VARCHAR2(100 CHAR) NULL,
							CONS_NAME	VARCHAR2(35 CHAR) NULL,
							CONS_TYPE		VARCHAR2(2 CHAR) NULL,
							ERR_COUNT		NUMBER(10) NULL
						)';  
EXCEPTION  
   WHEN OTHERS THEN  
      IF SQLCODE != -955 THEN  
         RAISE;  
      END IF;  
END;
	

&


/*-----------------------------------------------*/
/* TASK No. 29 */
/* delete previous check sum */

delete from	RAX_APP_USER.SNP_CHECK_TAB
where	SCHEMA_NAME	= 'ODS_OWN'
and	ORIGIN 		= '(70001)ODS_Project.LOAD_ORDER_LINE_INT'
and	ERR_TYPE 		= 'F'


&


/*-----------------------------------------------*/
/* TASK No. 30 */
/* create error table */


BEGIN  
   EXECUTE IMMEDIATE 'create table RAX_APP_USER.E$_ORDER_LINE
						(
							ODI_ROW_ID 		UROWID,
							ODI_ERR_TYPE		VARCHAR2(1 CHAR) NULL, 
							ODI_ERR_MESS		VARCHAR2(250 CHAR) NULL,
							ODI_CHECK_DATE	DATE NULL, 
							ORDER_LINE_OID	NUMBER NULL,
							UNIT_PRICE	NUMBER NULL,
							ORDERED_QUANTITY	NUMBER NULL,
							LIST_PRICE	NUMBER NULL,
							RETAIL_PRICE	NUMBER NULL,
							ORDER_HEADER_OID	NUMBER NULL,
							ITEM_OID	NUMBER NULL,
							BUNDLE_PARENT_ORDER_LINE_OID	NUMBER NULL,
							PACKAGE_REF	VARCHAR2(40) NULL,
							SHIPPED_QTY	NUMBER NULL,
							SORT_SEQ_NO	VARCHAR2(40) NULL,
							TAX_INCLUSIVE_IND	VARCHAR2(1) NULL,
							EST_TAX_AMOUNT	NUMBER NULL,
							HOLD_FLAG	VARCHAR2(1) NULL,
							LINE_SEQ_NO	VARCHAR2(40) NULL,
							ODS_CREATE_DATE	DATE NULL,
							ODS_MODIFY_DATE	DATE NULL,
							SOURCE_SYSTEM_OID	NUMBER NULL,
							ESTIMATED_ACCOUNT_COMMISSION	NUMBER NULL,
							KIT_CODE	VARCHAR2(20) NULL,
							SI_ADDITIONAL_QTY	NUMBER NULL,
							SI_SHIP_DATE	DATE NULL,
							GCP_ROOM_NEGS	NUMBER NULL,
							EST_TAX_RATE	NUMBER NULL,
							LINE_TOTAL	NUMBER NULL,
							EST_PRETAX_AMOUNT	NUMBER NULL,
							EARLIEST_SCHEDULE_DATE	DATE NULL,
							SI_ORDERED_QTY	NUMBER NULL,
							SI_SHIPPED_QTY	NUMBER NULL,
							SHIP_NODE_OID	NUMBER NULL,
							ODI_ORIGIN		VARCHAR2(100 CHAR) NULL,
							ODI_CONS_NAME	VARCHAR2(35 CHAR) NULL,
							ODI_CONS_TYPE		VARCHAR2(2 CHAR) NULL,
							ODI_PK			VARCHAR2(32 CHAR) PRIMARY KEY,
							ODI_SESS_NO		VARCHAR2(19 CHAR)
						)';  
EXCEPTION  
   WHEN OTHERS THEN  
      IF SQLCODE != -955 THEN  
         RAISE;  
      END IF;  
END;



&


/*-----------------------------------------------*/
/* TASK No. 31 */
/* delete previous errors */

delete from 	RAX_APP_USER.E$_ORDER_LINE
where	(ODI_ERR_TYPE = 'S'	and 'F' = 'S')
or	(ODI_ERR_TYPE = 'F'	and ODI_ORIGIN = '(70001)ODS_Project.LOAD_ORDER_LINE_INT')


&


/*-----------------------------------------------*/
/* TASK No. 32 */
/* Create index on PK */

 
/* FLOW CONTROL CREATE THE iNDEX ON THE I$TABLE */
BEGIN  
   EXECUTE IMMEDIATE 'create index 	RAX_APP_USER.I$_ORDER_LINE_IDX on RAX_APP_USER.I$_ORDER_LINE (ORDER_LINE_OID)';  
EXCEPTION  
   WHEN OTHERS THEN  
      IF SQLCODE != -955 and SQLCODE != -01408 THEN  
         RAISE;  
      END IF;  
END;


&


/*-----------------------------------------------*/
/* TASK No. 33 */
/* insert PK errors */

insert into RAX_APP_USER.E$_ORDER_LINE
(
	ODI_PK,
	ODI_SESS_NO,
	ODI_ROW_ID,
	ODI_ERR_TYPE,
	ODI_ERR_MESS,
	ODI_ORIGIN,
	ODI_CHECK_DATE,
	ODI_CONS_NAME,
	ODI_CONS_TYPE,
	ORDER_LINE_OID,
	UNIT_PRICE,
	ORDERED_QUANTITY,
	LIST_PRICE,
	RETAIL_PRICE,
	ORDER_HEADER_OID,
	ITEM_OID,
	BUNDLE_PARENT_ORDER_LINE_OID,
	PACKAGE_REF,
	SHIPPED_QTY,
	SORT_SEQ_NO,
	HOLD_FLAG,
	LINE_SEQ_NO,
	ODS_CREATE_DATE,
	ODS_MODIFY_DATE,
	SOURCE_SYSTEM_OID,
	KIT_CODE,
	LINE_TOTAL,
	EARLIEST_SCHEDULE_DATE,
	SHIP_NODE_OID
)
select	SYS_GUID(),
	:v_sess_no, 
	rowid,
	'F', 
	'ODI-15064: The primary key ORDER_LINE_PK is not unique.',
	'(70001)ODS_Project.LOAD_ORDER_LINE_INT',
	sysdate,
	'ORDER_LINE_PK',
	'PK',	
	ORDER_LINE.ORDER_LINE_OID,
	ORDER_LINE.UNIT_PRICE,
	ORDER_LINE.ORDERED_QUANTITY,
	ORDER_LINE.LIST_PRICE,
	ORDER_LINE.RETAIL_PRICE,
	ORDER_LINE.ORDER_HEADER_OID,
	ORDER_LINE.ITEM_OID,
	ORDER_LINE.BUNDLE_PARENT_ORDER_LINE_OID,
	ORDER_LINE.PACKAGE_REF,
	ORDER_LINE.SHIPPED_QTY,
	ORDER_LINE.SORT_SEQ_NO,
	ORDER_LINE.HOLD_FLAG,
	ORDER_LINE.LINE_SEQ_NO,
	ORDER_LINE.ODS_CREATE_DATE,
	ORDER_LINE.ODS_MODIFY_DATE,
	ORDER_LINE.SOURCE_SYSTEM_OID,
	ORDER_LINE.KIT_CODE,
	ORDER_LINE.LINE_TOTAL,
	ORDER_LINE.EARLIEST_SCHEDULE_DATE,
	ORDER_LINE.SHIP_NODE_OID
from	RAX_APP_USER.I$_ORDER_LINE   ORDER_LINE
where	exists  (
		select	SUB.ORDER_LINE_OID
		from 	RAX_APP_USER.I$_ORDER_LINE SUB
		where 	SUB.ORDER_LINE_OID=ORDER_LINE.ORDER_LINE_OID
		group by 	SUB.ORDER_LINE_OID
		having 	count(1) > 1
		)



&


/*-----------------------------------------------*/
/* TASK No. 34 */
/* insert FK errors */

insert into RAX_APP_USER.E$_ORDER_LINE
(
	ODI_PK,
	ODI_SESS_NO,
	ODI_ROW_ID,
	ODI_ERR_TYPE,
	ODI_ERR_MESS,
	ODI_CHECK_DATE,
	ODI_ORIGIN,
	ODI_CONS_NAME,
	ODI_CONS_TYPE,
	ORDER_LINE_OID,
	UNIT_PRICE,
	ORDERED_QUANTITY,
	LIST_PRICE,
	RETAIL_PRICE,
	ORDER_HEADER_OID,
	ITEM_OID,
	BUNDLE_PARENT_ORDER_LINE_OID,
	PACKAGE_REF,
	SHIPPED_QTY,
	SORT_SEQ_NO,
	HOLD_FLAG,
	LINE_SEQ_NO,
	ODS_CREATE_DATE,
	ODS_MODIFY_DATE,
	SOURCE_SYSTEM_OID,
	KIT_CODE,
	LINE_TOTAL,
	EARLIEST_SCHEDULE_DATE,
	SHIP_NODE_OID
)
select	SYS_GUID(),
	:v_sess_no, 
	rowid,
	'F', 
	'ODI-15065: Join error (OL_ITEM) between the table ORDER_LINE and the table ITEM.',
	sysdate,
	'(70001)ODS_Project.LOAD_ORDER_LINE_INT',
	'OL_ITEM',
	'FK',	
	ORDER_LINE_OID,
	UNIT_PRICE,
	ORDERED_QUANTITY,
	LIST_PRICE,
	RETAIL_PRICE,
	ORDER_HEADER_OID,
	ITEM_OID,
	BUNDLE_PARENT_ORDER_LINE_OID,
	PACKAGE_REF,
	SHIPPED_QTY,
	SORT_SEQ_NO,
	HOLD_FLAG,
	LINE_SEQ_NO,
	ODS_CREATE_DATE,
	ODS_MODIFY_DATE,
	SOURCE_SYSTEM_OID,
	KIT_CODE,
	LINE_TOTAL,
	EARLIEST_SCHEDULE_DATE,
	SHIP_NODE_OID

from	RAX_APP_USER.I$_ORDER_LINE ORDER_LINE 
where 	(
		ORDER_LINE.ITEM_OID 
	) not in 	(
		select 	ITEM_OID
		from 	ODS_OWN.ITEM
		)
and	(
		ORDER_LINE.ITEM_OID is not null 
	)




&


/*-----------------------------------------------*/
/* TASK No. 35 */
/* insert FK errors */

insert into RAX_APP_USER.E$_ORDER_LINE
(
	ODI_PK,
	ODI_SESS_NO,
	ODI_ROW_ID,
	ODI_ERR_TYPE,
	ODI_ERR_MESS,
	ODI_CHECK_DATE,
	ODI_ORIGIN,
	ODI_CONS_NAME,
	ODI_CONS_TYPE,
	ORDER_LINE_OID,
	UNIT_PRICE,
	ORDERED_QUANTITY,
	LIST_PRICE,
	RETAIL_PRICE,
	ORDER_HEADER_OID,
	ITEM_OID,
	BUNDLE_PARENT_ORDER_LINE_OID,
	PACKAGE_REF,
	SHIPPED_QTY,
	SORT_SEQ_NO,
	HOLD_FLAG,
	LINE_SEQ_NO,
	ODS_CREATE_DATE,
	ODS_MODIFY_DATE,
	SOURCE_SYSTEM_OID,
	KIT_CODE,
	LINE_TOTAL,
	EARLIEST_SCHEDULE_DATE,
	SHIP_NODE_OID
)
select	SYS_GUID(),
	:v_sess_no, 
	rowid,
	'F', 
	'ODI-15065: Join error (OL_ORDER_HEADER) between the table ORDER_LINE and the table ORDER_HEADER.',
	sysdate,
	'(70001)ODS_Project.LOAD_ORDER_LINE_INT',
	'OL_ORDER_HEADER',
	'FK',	
	ORDER_LINE_OID,
	UNIT_PRICE,
	ORDERED_QUANTITY,
	LIST_PRICE,
	RETAIL_PRICE,
	ORDER_HEADER_OID,
	ITEM_OID,
	BUNDLE_PARENT_ORDER_LINE_OID,
	PACKAGE_REF,
	SHIPPED_QTY,
	SORT_SEQ_NO,
	HOLD_FLAG,
	LINE_SEQ_NO,
	ODS_CREATE_DATE,
	ODS_MODIFY_DATE,
	SOURCE_SYSTEM_OID,
	KIT_CODE,
	LINE_TOTAL,
	EARLIEST_SCHEDULE_DATE,
	SHIP_NODE_OID

from	RAX_APP_USER.I$_ORDER_LINE ORDER_LINE 
where 	(
		ORDER_LINE.ORDER_HEADER_OID 
	) not in 	(
		select 	ORDER_HEADER_OID
		from 	ODS_OWN.ORDER_HEADER
		)
and	(
		ORDER_LINE.ORDER_HEADER_OID is not null 
	)




&


/*-----------------------------------------------*/
/* TASK No. 36 */
/* insert FK errors */

insert into RAX_APP_USER.E$_ORDER_LINE
(
	ODI_PK,
	ODI_SESS_NO,
	ODI_ROW_ID,
	ODI_ERR_TYPE,
	ODI_ERR_MESS,
	ODI_CHECK_DATE,
	ODI_ORIGIN,
	ODI_CONS_NAME,
	ODI_CONS_TYPE,
	ORDER_LINE_OID,
	UNIT_PRICE,
	ORDERED_QUANTITY,
	LIST_PRICE,
	RETAIL_PRICE,
	ORDER_HEADER_OID,
	ITEM_OID,
	BUNDLE_PARENT_ORDER_LINE_OID,
	PACKAGE_REF,
	SHIPPED_QTY,
	SORT_SEQ_NO,
	HOLD_FLAG,
	LINE_SEQ_NO,
	ODS_CREATE_DATE,
	ODS_MODIFY_DATE,
	SOURCE_SYSTEM_OID,
	KIT_CODE,
	LINE_TOTAL,
	EARLIEST_SCHEDULE_DATE,
	SHIP_NODE_OID
)
select	SYS_GUID(),
	:v_sess_no, 
	rowid,
	'F', 
	'ODI-15065: Join error (OL_PARENT_ORDER_LINE) between the table ORDER_LINE and the table ORDER_LINE.',
	sysdate,
	'(70001)ODS_Project.LOAD_ORDER_LINE_INT',
	'OL_PARENT_ORDER_LINE',
	'FK',	
	ORDER_LINE_OID,
	UNIT_PRICE,
	ORDERED_QUANTITY,
	LIST_PRICE,
	RETAIL_PRICE,
	ORDER_HEADER_OID,
	ITEM_OID,
	BUNDLE_PARENT_ORDER_LINE_OID,
	PACKAGE_REF,
	SHIPPED_QTY,
	SORT_SEQ_NO,
	HOLD_FLAG,
	LINE_SEQ_NO,
	ODS_CREATE_DATE,
	ODS_MODIFY_DATE,
	SOURCE_SYSTEM_OID,
	KIT_CODE,
	LINE_TOTAL,
	EARLIEST_SCHEDULE_DATE,
	SHIP_NODE_OID

from	RAX_APP_USER.I$_ORDER_LINE ORDER_LINE 
where 	(
		ORDER_LINE.BUNDLE_PARENT_ORDER_LINE_OID 
	) not in 	(
		select 	ORDER_LINE_OID
		from 	ODS_OWN.ORDER_LINE
		)
and	(
		ORDER_LINE.BUNDLE_PARENT_ORDER_LINE_OID is not null 
	)




&


/*-----------------------------------------------*/
/* TASK No. 37 */
/* insert Not Null errors */

insert into RAX_APP_USER.E$_ORDER_LINE
(
	ODI_PK,
	ODI_SESS_NO,
	ODI_ROW_ID,
	ODI_ERR_TYPE,
	ODI_ERR_MESS,
	ODI_CHECK_DATE,
	ODI_ORIGIN,
	ODI_CONS_NAME,
	ODI_CONS_TYPE,
	ORDER_LINE_OID,
	UNIT_PRICE,
	ORDERED_QUANTITY,
	LIST_PRICE,
	RETAIL_PRICE,
	ORDER_HEADER_OID,
	ITEM_OID,
	BUNDLE_PARENT_ORDER_LINE_OID,
	PACKAGE_REF,
	SHIPPED_QTY,
	SORT_SEQ_NO,
	HOLD_FLAG,
	LINE_SEQ_NO,
	ODS_CREATE_DATE,
	ODS_MODIFY_DATE,
	SOURCE_SYSTEM_OID,
	KIT_CODE,
	LINE_TOTAL,
	EARLIEST_SCHEDULE_DATE,
	SHIP_NODE_OID
)
select
	SYS_GUID(),
	:v_sess_no, 
	rowid,
	'F', 
	'ODI-15066: The column ORDER_LINE_OID cannot be null.',
	sysdate,
	'(70001)ODS_Project.LOAD_ORDER_LINE_INT',
	'ORDER_LINE_OID',
	'NN',	
	ORDER_LINE_OID,
	UNIT_PRICE,
	ORDERED_QUANTITY,
	LIST_PRICE,
	RETAIL_PRICE,
	ORDER_HEADER_OID,
	ITEM_OID,
	BUNDLE_PARENT_ORDER_LINE_OID,
	PACKAGE_REF,
	SHIPPED_QTY,
	SORT_SEQ_NO,
	HOLD_FLAG,
	LINE_SEQ_NO,
	ODS_CREATE_DATE,
	ODS_MODIFY_DATE,
	SOURCE_SYSTEM_OID,
	KIT_CODE,
	LINE_TOTAL,
	EARLIEST_SCHEDULE_DATE,
	SHIP_NODE_OID
from	RAX_APP_USER.I$_ORDER_LINE
where	ORDER_LINE_OID is null



&


/*-----------------------------------------------*/
/* TASK No. 38 */
/* insert Not Null errors */

insert into RAX_APP_USER.E$_ORDER_LINE
(
	ODI_PK,
	ODI_SESS_NO,
	ODI_ROW_ID,
	ODI_ERR_TYPE,
	ODI_ERR_MESS,
	ODI_CHECK_DATE,
	ODI_ORIGIN,
	ODI_CONS_NAME,
	ODI_CONS_TYPE,
	ORDER_LINE_OID,
	UNIT_PRICE,
	ORDERED_QUANTITY,
	LIST_PRICE,
	RETAIL_PRICE,
	ORDER_HEADER_OID,
	ITEM_OID,
	BUNDLE_PARENT_ORDER_LINE_OID,
	PACKAGE_REF,
	SHIPPED_QTY,
	SORT_SEQ_NO,
	HOLD_FLAG,
	LINE_SEQ_NO,
	ODS_CREATE_DATE,
	ODS_MODIFY_DATE,
	SOURCE_SYSTEM_OID,
	KIT_CODE,
	LINE_TOTAL,
	EARLIEST_SCHEDULE_DATE,
	SHIP_NODE_OID
)
select
	SYS_GUID(),
	:v_sess_no, 
	rowid,
	'F', 
	'ODI-15066: The column ORDER_HEADER_OID cannot be null.',
	sysdate,
	'(70001)ODS_Project.LOAD_ORDER_LINE_INT',
	'ORDER_HEADER_OID',
	'NN',	
	ORDER_LINE_OID,
	UNIT_PRICE,
	ORDERED_QUANTITY,
	LIST_PRICE,
	RETAIL_PRICE,
	ORDER_HEADER_OID,
	ITEM_OID,
	BUNDLE_PARENT_ORDER_LINE_OID,
	PACKAGE_REF,
	SHIPPED_QTY,
	SORT_SEQ_NO,
	HOLD_FLAG,
	LINE_SEQ_NO,
	ODS_CREATE_DATE,
	ODS_MODIFY_DATE,
	SOURCE_SYSTEM_OID,
	KIT_CODE,
	LINE_TOTAL,
	EARLIEST_SCHEDULE_DATE,
	SHIP_NODE_OID
from	RAX_APP_USER.I$_ORDER_LINE
where	ORDER_HEADER_OID is null



&


/*-----------------------------------------------*/
/* TASK No. 39 */
/* insert Not Null errors */

insert into RAX_APP_USER.E$_ORDER_LINE
(
	ODI_PK,
	ODI_SESS_NO,
	ODI_ROW_ID,
	ODI_ERR_TYPE,
	ODI_ERR_MESS,
	ODI_CHECK_DATE,
	ODI_ORIGIN,
	ODI_CONS_NAME,
	ODI_CONS_TYPE,
	ORDER_LINE_OID,
	UNIT_PRICE,
	ORDERED_QUANTITY,
	LIST_PRICE,
	RETAIL_PRICE,
	ORDER_HEADER_OID,
	ITEM_OID,
	BUNDLE_PARENT_ORDER_LINE_OID,
	PACKAGE_REF,
	SHIPPED_QTY,
	SORT_SEQ_NO,
	HOLD_FLAG,
	LINE_SEQ_NO,
	ODS_CREATE_DATE,
	ODS_MODIFY_DATE,
	SOURCE_SYSTEM_OID,
	KIT_CODE,
	LINE_TOTAL,
	EARLIEST_SCHEDULE_DATE,
	SHIP_NODE_OID
)
select
	SYS_GUID(),
	:v_sess_no, 
	rowid,
	'F', 
	'ODI-15066: The column ITEM_OID cannot be null.',
	sysdate,
	'(70001)ODS_Project.LOAD_ORDER_LINE_INT',
	'ITEM_OID',
	'NN',	
	ORDER_LINE_OID,
	UNIT_PRICE,
	ORDERED_QUANTITY,
	LIST_PRICE,
	RETAIL_PRICE,
	ORDER_HEADER_OID,
	ITEM_OID,
	BUNDLE_PARENT_ORDER_LINE_OID,
	PACKAGE_REF,
	SHIPPED_QTY,
	SORT_SEQ_NO,
	HOLD_FLAG,
	LINE_SEQ_NO,
	ODS_CREATE_DATE,
	ODS_MODIFY_DATE,
	SOURCE_SYSTEM_OID,
	KIT_CODE,
	LINE_TOTAL,
	EARLIEST_SCHEDULE_DATE,
	SHIP_NODE_OID
from	RAX_APP_USER.I$_ORDER_LINE
where	ITEM_OID is null



&


/*-----------------------------------------------*/
/* TASK No. 40 */
/* create index on error table */

 
/* FLOW CONTROL CREATE INDEX ON THE E$TABLE */
BEGIN  
   EXECUTE IMMEDIATE 'create index 	RAX_APP_USER.E$_ORDER_LINE_IDX on RAX_APP_USER.E$_ORDER_LINE (ODI_ROW_ID)';  
EXCEPTION  
   WHEN OTHERS THEN  
      IF SQLCODE != -955 and SQLCODE != -01408 THEN  
         RAISE;  
      END IF;  
END;


&


/*-----------------------------------------------*/
/* TASK No. 41 */
/* delete errors from controlled table */

delete from	RAX_APP_USER.I$_ORDER_LINE  T
where	exists 	(
		select	1
		from	RAX_APP_USER.E$_ORDER_LINE E
		where ODI_SESS_NO = :v_sess_no
		and T.rowid = E.ODI_ROW_ID
		)


&


/*-----------------------------------------------*/
/* TASK No. 42 */
/* insert check sum into check table */

insert into RAX_APP_USER.SNP_CHECK_TAB
(
	SCHEMA_NAME,
	RESOURCE_NAME,
	FULL_RES_NAME,
	ERR_TYPE,
	ERR_MESS,
	CHECK_DATE,
	ORIGIN,
	CONS_NAME,
	CONS_TYPE,
	ERR_COUNT
)
select	
	'ODS_OWN',
	'ORDER_LINE',
	'ODS_OWN.ORDER_LINE',
	E.ODI_ERR_TYPE,
	E.ODI_ERR_MESS,
	E.ODI_CHECK_DATE,
	E.ODI_ORIGIN,
	E.ODI_CONS_NAME,
	E.ODI_CONS_TYPE,
	count(1) 
from	RAX_APP_USER.E$_ORDER_LINE E
where	E.ODI_ERR_TYPE	= 'F'
and	E.ODI_ORIGIN 	= '(70001)ODS_Project.LOAD_ORDER_LINE_INT'
group by	E.ODI_ERR_TYPE,
	E.ODI_ERR_MESS,
	E.ODI_CHECK_DATE,
	E.ODI_ORIGIN,
	E.ODI_CONS_NAME,
	E.ODI_CONS_TYPE


&


/*-----------------------------------------------*/
/* TASK No. 43 */
/* Flag rows for update */

/* DETECTION_STRATEGY = NOT_EXISTS */


update	RAX_APP_USER.I$_ORDER_LINE
set	IND_UPDATE = 'U'
where	(ORDER_LINE_OID)
	in	(
		select	ORDER_LINE_OID
		from	ODS_OWN.ORDER_LINE
		)



&


/*-----------------------------------------------*/
/* TASK No. 44 */
/* Flag useless rows */

/* DETECTION_STRATEGY = NOT_EXISTS */

/* Command skipped due to chosen DETECTION_STRATEGY */



/*-----------------------------------------------*/
/* TASK No. 45 */
/* Update existing rows */

/* DETECTION_STRATEGY = NOT_EXISTS */
update	ODS_OWN.ORDER_LINE T
set 	
	(
	T.UNIT_PRICE,
	T.ORDERED_QUANTITY,
	T.LIST_PRICE,
	T.RETAIL_PRICE,
	T.ORDER_HEADER_OID,
	T.ITEM_OID,
	T.BUNDLE_PARENT_ORDER_LINE_OID,
	T.PACKAGE_REF,
	T.SHIPPED_QTY,
	T.SORT_SEQ_NO,
	T.HOLD_FLAG,
	T.LINE_SEQ_NO,
	T.SOURCE_SYSTEM_OID,
	T.KIT_CODE,
	T.LINE_TOTAL,
	T.EARLIEST_SCHEDULE_DATE,
	T.SHIP_NODE_OID
	) =
		(
		select	S.UNIT_PRICE,
			S.ORDERED_QUANTITY,
			S.LIST_PRICE,
			S.RETAIL_PRICE,
			S.ORDER_HEADER_OID,
			S.ITEM_OID,
			S.BUNDLE_PARENT_ORDER_LINE_OID,
			S.PACKAGE_REF,
			S.SHIPPED_QTY,
			S.SORT_SEQ_NO,
			S.HOLD_FLAG,
			S.LINE_SEQ_NO,
			S.SOURCE_SYSTEM_OID,
			S.KIT_CODE,
			S.LINE_TOTAL,
			S.EARLIEST_SCHEDULE_DATE,
			S.SHIP_NODE_OID
		from	RAX_APP_USER.I$_ORDER_LINE S
		where	T.ORDER_LINE_OID	=S.ORDER_LINE_OID
	    	 )
	,                 T.ODS_MODIFY_DATE = SYSDATE

where	(ORDER_LINE_OID)
	in	(
		select	ORDER_LINE_OID
		from	RAX_APP_USER.I$_ORDER_LINE
		where	IND_UPDATE = 'U'
		)




&


/*-----------------------------------------------*/
/* TASK No. 46 */
/* Insert new rows */

/* DETECTION_STRATEGY = NOT_EXISTS */
insert into 	ODS_OWN.ORDER_LINE T
	(
	ORDER_LINE_OID,
	UNIT_PRICE,
	ORDERED_QUANTITY,
	LIST_PRICE,
	RETAIL_PRICE,
	ORDER_HEADER_OID,
	ITEM_OID,
	BUNDLE_PARENT_ORDER_LINE_OID,
	PACKAGE_REF,
	SHIPPED_QTY,
	SORT_SEQ_NO,
	HOLD_FLAG,
	LINE_SEQ_NO,
	SOURCE_SYSTEM_OID,
	KIT_CODE,
	LINE_TOTAL,
	EARLIEST_SCHEDULE_DATE,
	SHIP_NODE_OID
	,                  ODS_CREATE_DATE,
	ODS_MODIFY_DATE
	)
select 	ORDER_LINE_OID,
	UNIT_PRICE,
	ORDERED_QUANTITY,
	LIST_PRICE,
	RETAIL_PRICE,
	ORDER_HEADER_OID,
	ITEM_OID,
	BUNDLE_PARENT_ORDER_LINE_OID,
	PACKAGE_REF,
	SHIPPED_QTY,
	SORT_SEQ_NO,
	HOLD_FLAG,
	LINE_SEQ_NO,
	SOURCE_SYSTEM_OID,
	KIT_CODE,
	LINE_TOTAL,
	EARLIEST_SCHEDULE_DATE,
	SHIP_NODE_OID
	,                  SYSDATE,
	SYSDATE
from	RAX_APP_USER.I$_ORDER_LINE S



where	IND_UPDATE = 'I'



&


/*-----------------------------------------------*/
/* TASK No. 47 */
/* Commit transaction */

/*commit*/


/*-----------------------------------------------*/
/* TASK No. 48 */
/* Drop flow table */

drop table RAX_APP_USER.I$_ORDER_LINE 

&


/*-----------------------------------------------*/
/* TASK No. 49 */
/* Update CDC Load Status */

UPDATE ODS_OWN.ODS_CDC_LOAD_STATUS
SET LAST_CDC_COMPLETION_DATE=TO_DATE(
             SUBSTR(:v_sess_beg, 1, 19), 'RRRR-MM-DD HH24:MI:SS')
+ nvl((TIMEZONE_OFFSET/24), 0) 
WHERE ODS_TABLE_NAME=:v_cdc_load_table_name
AND CONTEXT_NAME = :v_env

/*
UPDATE ODS_OWN.ODS_CDC_LOAD_STATUS
SET LAST_CDC_COMPLETION_DATE=TO_DATE(
             SUBSTR(:v_sess_beg, 1, 19), 'RRRR-MM-DD HH24:MI:SS')
WHERE ODS_TABLE_NAME=:v_cdc_load_table_name
AND CONTEXT_NAME = :v_env
*/

&


/*-----------------------------------------------*/
/* TASK No. 50 */
/* Insert CDC Audit Record */

INSERT INTO RAX_APP_USER.ODS_CDC_LOAD_STATUS_AUDIT
(TABLE_NAME,
SESS_NO,                      
SESS_NAME,                    
SCEN_VERSION,                 
SESS_BEG,                     
ORIG_LAST_CDC_COMPLETION_DATE,
OVERLAP,
CREATE_DATE,
CONTEXT_NAME,
TIMEZONE_OFFSET              
)
select 
:v_cdc_load_table_name
,:v_sess_no
,'LOAD_ORDER_LINE_PKG'
,'019'
,TO_DATE(SUBSTR(:v_sess_beg, 1, 19), 'RRRR-MM-DD HH24:MI:SS')
,TO_DATE (SUBSTR(:v_cdc_load_date, 1, 19),'YYYY-MM-DD HH24:MI:SS')
,:v_cdc_overlap
,SYSDATE
,:v_env
,TIMEZONE_OFFSET
from 
ODS_OWN.ODS_CDC_LOAD_STATUS
WHERE ODS_TABLE_NAME=:v_cdc_load_table_name
AND CONTEXT_NAME = :v_env

/*
INSERT INTO RAX_APP_USER.ODS_CDC_LOAD_STATUS_AUDIT
(TABLE_NAME,
SESS_NO,                      
SESS_NAME,                    
SCEN_VERSION,                 
SESS_BEG,                     
ORIG_LAST_CDC_COMPLETION_DATE,
OVERLAP,
CREATE_DATE,
CONTEXT_NAME              
)
values (
:v_cdc_load_table_name,
:v_sess_no,
'LOAD_ORDER_LINE_PKG',
'019',
TO_DATE(
             SUBSTR(:v_sess_beg, 1, 19), 'RRRR-MM-DD HH24:MI:SS'),
TO_DATE (SUBSTR (:v_cdc_load_date, 1, 19),
                           'YYYY-MM-DD HH24:MI:SS'
                          )
,:v_cdc_overlap,
SYSDATE,
 :v_env)
*/


&


/*-----------------------------------------------*/
