CREATE TABLE RAX_APP_USER.LTLPIADM_TBLENRLMNT09HIST_STG AS 
(
    SELECT * FROM ODS_ETL_OWNER.LTLPIADM_TBLENRLMNT09HIST_STG
)
;

CREATE TABLE RAX_APP_USER.LTLPIADM_TBLENRLMNT09_STG AS 
(
    SELECT * FROM ODS_ETL_OWNER.LTLPIADM_TBLENRLMNT09_STG
)
;
