---

pipeline:
  name: lt_MERCH_FACT_LOAD_PKG_dag
  description: merch fact load pipeline
  schedule: "39 */4 * * *"
  tags:
    - lifetouch
    - MERCH_FACT_LOAD_PKG
  task_groups:
    - name: MERCH_FACT_LOAD_ODI_Transformation
      description: ODI SQL Transformation Logic
      pre_sql:
        v_cdc_load_date: dags/sql/pre_sql/pre_v_cdc_ld_date.sql
      default_args:
        v_cdc_overlap: 0.02083333333
      tasks:
        - description: LOAD_MART_SUBJECT_APO subpackage
          type: oracle
          script_location: dags/sql/MERCH_FACT_LOAD_PKG/LOAD_MART_SUBJECT_APO_PKG.sql
          args:
            v_cdc_load_table_name: MART_SUBJECT_APO
        - description: MERCH_FACT subpackage
          type: oracle
          script_location: dags/sql/MERCH_FACT_LOAD_PKG/MERCH_FACT_PKG.sql
          args:
            v_cdc_load_table_name: MERCH_FACT
            
        
