/* TASK No. 1 */

/* NONE or SET VARIABLE STATEMENT FOUND, CHECK ODI TASK NO. 1 */




/*-----------------------------------------------*/
/* TASK No. 2 */

/* SELECT STATEMENT FOUND, CHECK ODI TASK NO. 2 */




/*-----------------------------------------------*/
/* TASK No. 3 */

/* SELECT STATEMENT FOUND, CHECK ODI TASK NO. 3 */




/*-----------------------------------------------*/
/* TASK No. 4 */
/* Drop work table */

-- drop table RAX_APP_USER.C$_0FOW_FRNG_STG 

-- &


-- /*-----------------------------------------------*/
-- /* TASK No. 5 */
-- /* Create work table */

-- create table RAX_APP_USER.C$_0FOW_FRNG_STG
-- (
-- 	C1_ID	NUMBER NULL,
-- 	C2_VERSION	NUMBER NULL,
-- 	C3_APO_ID	NUMBER NULL,
-- 	C4_COMPOSITE_CODE	VARCHAR2(255) NULL,
-- 	C5_COMPOSITE_DELIVERY_METHOD	VARCHAR2(255) NULL,
-- 	C6_CREATED_BY	VARCHAR2(255) NULL,
-- 	C7_DATE_CREATED	DATE NULL,
-- 	C8_DEFAULT_SERVICE_LOOK	VARCHAR2(255) NULL,
-- 	C9_ENVELOPE_TYPE	VARCHAR2(255) NULL,
-- 	C10_GROUP_CODE	VARCHAR2(255) NULL,
-- 	C11_GROUP_DELIVERY_METHOD	VARCHAR2(255) NULL,
-- 	C12_LAST_UPDATED	DATE NULL,
-- 	C13_MODEL_ETHNICITY	VARCHAR2(255) NULL,
-- 	C14_MODEL_GENDER	VARCHAR2(255) NULL,
-- 	C15_MODEL_GRADE	VARCHAR2(255) NULL,
-- 	C16_PRICE_PROGRAM_ID	VARCHAR2(255) NULL,
-- 	C17_STAFF_PACKAGE	NUMBER NULL,
-- 	C18_STYLE	VARCHAR2(255) NULL,
-- 	C19_UPDATED_BY	VARCHAR2(255) NULL,
-- 	C20_VISUAL_MERCH_ID	VARCHAR2(255) NULL,
-- 	C21_YEAR_BOOK_LOOK	VARCHAR2(255) NULL,
-- 	C22_COMMISSION_TYPE	VARCHAR2(255) NULL,
-- 	C23_COMMISSION_RATE	NUMBER NULL,
-- 	C24_NO_TOUCH_YEARBOOK_LOOK	VARCHAR2(255) NULL,
-- 	C25_MINIMUM_REQUIREMENTS	NUMBER NULL,
-- 	C26_FLYER_ID	VARCHAR2(255) NULL,
-- 	C27_PART_NUMBER	VARCHAR2(255) NULL,
-- 	C28_FLYER_SIZE	VARCHAR2(255) NULL,
-- 	C29_FLYER_STYLE	VARCHAR2(255) NULL,
-- 	C30_LAYOUT_CODE	VARCHAR2(255) NULL,
-- 	C31_PAYMENT_MESSAGE_TEXT	VARCHAR2(255) NULL,
-- 	C32_CREDIT_CARD_ALLOWED	NUMBER NULL,
-- 	C33_CHECK_PAYABLE_TO	VARCHAR2(255) NULL,
-- 	C34_SMALL_NOTICE_TEXT	VARCHAR2(255) NULL,
-- 	C35_ADDITIONAL_INFO_TEXT	VARCHAR2(255) NULL,
-- 	C36_ADDITIONAL_INFO_PROOF_TEXT	VARCHAR2(255) NULL,
-- 	C37_FAMILY_PLAN_VERBIAGE	VARCHAR2(255) NULL,
-- 	C38_PAYMENT_DUE_TIMING_TEXT	VARCHAR2(255) NULL,
-- 	C39_SPANISH_CAPTION_CODE1	VARCHAR2(255) NULL,
-- 	C40_SPANISH_CAPTION_CODE2	VARCHAR2(255) NULL,
-- 	C41_SPANISH_CAPTION_CODE3	VARCHAR2(255) NULL,
-- 	C42_INSERT_NO	VARCHAR2(255) NULL,
-- 	C43_INSERT_TYPE	VARCHAR2(255) NULL,
-- 	C44_MASCOT	VARCHAR2(255) NULL,
-- 	C45_PAYMENT_METHOD	VARCHAR2(255) NULL,
-- 	C46_POST_PIC_DAY_CUST_INQ_PHON	VARCHAR2(255) NULL,
-- 	C47_POST_PIC_DAY_CUST_INQ_PHON	VARCHAR2(255) NULL,
-- 	C48_PRE_PIC_DAY_CUST_INQ_PHONE	VARCHAR2(255) NULL,
-- 	C49_PRE_PIC_DAY_CUST_INQ_PHONE	VARCHAR2(255) NULL,
-- 	C50_THEME	VARCHAR2(255) NULL,
-- 	C51_OFFERING_TEMPLATE_ID	NUMBER NULL,
-- 	C52_CASUAL_CODE	VARCHAR2(255) NULL,
-- 	C53_CUSTOMER_SERVICE_EMAIL	VARCHAR2(255) NULL,
-- 	C54_CUSTOMER_SERVICE_HOURS	VARCHAR2(255) NULL
-- )
-- NOLOGGING

-- &


-- /*-----------------------------------------------*/
-- /* TASK No. 6 */
-- /* Load data */

-- /* SOURCE CODE */
-- select	
-- 	OFFERING.ID	   C1_ID,
-- 	OFFERING.VERSION	   C2_VERSION,
-- 	OFFERING.APO_ID	   C3_APO_ID,
-- 	OFFERING.COMPOSITE_CODE	   C4_COMPOSITE_CODE,
-- 	OFFERING.COMPOSITE_DELIVERY_METHOD	   C5_COMPOSITE_DELIVERY_METHOD,
-- 	OFFERING.CREATED_BY	   C6_CREATED_BY,
-- 	OFFERING.DATE_CREATED	   C7_DATE_CREATED,
-- 	OFFERING.DEFAULT_SERVICE_LOOK	   C8_DEFAULT_SERVICE_LOOK,
-- 	OFFERING.ENVELOPE_TYPE	   C9_ENVELOPE_TYPE,
-- 	OFFERING.GROUP_CODE	   C10_GROUP_CODE,
-- 	OFFERING.GROUP_DELIVERY_METHOD	   C11_GROUP_DELIVERY_METHOD,
-- 	OFFERING.LAST_UPDATED	   C12_LAST_UPDATED,
-- 	OFFERING.MODEL_ETHNICITY	   C13_MODEL_ETHNICITY,
-- 	OFFERING.MODEL_GENDER	   C14_MODEL_GENDER,
-- 	OFFERING.MODEL_GRADE	   C15_MODEL_GRADE,
-- 	OFFERING.PRICE_PROGRAM_ID	   C16_PRICE_PROGRAM_ID,
-- 	OFFERING.STAFF_PACKAGE	   C17_STAFF_PACKAGE,
-- 	OFFERING.STYLE	   C18_STYLE,
-- 	OFFERING.UPDATED_BY	   C19_UPDATED_BY,
-- 	OFFERING.VISUAL_MERCH_ID	   C20_VISUAL_MERCH_ID,
-- 	OFFERING.YEAR_BOOK_LOOK	   C21_YEAR_BOOK_LOOK,
-- 	OFFERING.COMMISSION_TYPE	   C22_COMMISSION_TYPE,
-- 	OFFERING.COMMISSION_RATE	   C23_COMMISSION_RATE,
-- 	OFFERING.NO_TOUCH_YEARBOOK_LOOK	   C24_NO_TOUCH_YEARBOOK_LOOK,
-- 	OFFERING.MINIMUM_REQUIREMENTS	   C25_MINIMUM_REQUIREMENTS,
-- 	OFFERING.FLYER_ID	   C26_FLYER_ID,
-- 	OFFERING.PART_NUMBER	   C27_PART_NUMBER,
-- 	OFFERING.FLYER_SIZE	   C28_FLYER_SIZE,
-- 	OFFERING.FLYER_STYLE	   C29_FLYER_STYLE,
-- 	OFFERING.LAYOUT_CODE	   C30_LAYOUT_CODE,
-- 	OFFERING.PAYMENT_MESSAGE_TEXT	   C31_PAYMENT_MESSAGE_TEXT,
-- 	OFFERING.CREDIT_CARD_ALLOWED	   C32_CREDIT_CARD_ALLOWED,
-- 	OFFERING.CHECK_PAYABLE_TO	   C33_CHECK_PAYABLE_TO,
-- 	OFFERING.SMALL_NOTICE_TEXT	   C34_SMALL_NOTICE_TEXT,
-- 	OFFERING.ADDITIONAL_INFO_TEXT	   C35_ADDITIONAL_INFO_TEXT,
-- 	OFFERING.ADDITIONAL_INFO_PROOF_TEXT	   C36_ADDITIONAL_INFO_PROOF_TEXT,
-- 	OFFERING.FAMILY_PLAN_VERBIAGE	   C37_FAMILY_PLAN_VERBIAGE,
-- 	OFFERING.PAYMENT_DUE_TIMING_TEXT	   C38_PAYMENT_DUE_TIMING_TEXT,
-- 	OFFERING.SPANISH_CAPTION_CODE1	   C39_SPANISH_CAPTION_CODE1,
-- 	OFFERING.SPANISH_CAPTION_CODE2	   C40_SPANISH_CAPTION_CODE2,
-- 	OFFERING.SPANISH_CAPTION_CODE3	   C41_SPANISH_CAPTION_CODE3,
-- 	OFFERING.INSERT_NO	   C42_INSERT_NO,
-- 	OFFERING.INSERT_TYPE	   C43_INSERT_TYPE,
-- 	OFFERING.MASCOT	   C44_MASCOT,
-- 	OFFERING.PAYMENT_METHOD	   C45_PAYMENT_METHOD,
-- 	OFFERING.POST_PIC_DAY_CUST_INQ_PHONE1	   C46_POST_PIC_DAY_CUST_INQ_PHON,
-- 	OFFERING.POST_PIC_DAY_CUST_INQ_PHONE2	   C47_POST_PIC_DAY_CUST_INQ_PHON,
-- 	OFFERING.PRE_PIC_DAY_CUST_INQ_PHONE1	   C48_PRE_PIC_DAY_CUST_INQ_PHONE,
-- 	OFFERING.PRE_PIC_DAY_CUST_INQ_PHONE2	   C49_PRE_PIC_DAY_CUST_INQ_PHONE,
-- 	OFFERING.THEME	   C50_THEME,
-- 	OFFERING.OFFERING_TEMPLATE_ID	   C51_OFFERING_TEMPLATE_ID,
-- 	OFFERING.CAUSAL_CODE	   C52_CASUAL_CODE,
-- 	OFFERING.CUSTOMER_SERVICE_EMAIL	   C53_CUSTOMER_SERVICE_EMAIL,
-- 	OFFERING.CUSTOMER_SERVICE_HOURS	   C54_CUSTOMER_SERVICE_HOURS
-- from	FOW_OWN.OFFERING   OFFERING
-- where	(1=1)
-- And (OFFERING.LAST_UPDATED >= TO_DATE(SUBSTR(:v_cdc_load_date, 1, 19), 'YYYY-MM-DD HH24:MI:SS')  -:v_cdc_oms_overlap)





-- &

-- /* TARGET CODE */
-- insert into RAX_APP_USER.C$_0FOW_FRNG_STG
-- (
-- 	C1_ID,
-- 	C2_VERSION,
-- 	C3_APO_ID,
-- 	C4_COMPOSITE_CODE,
-- 	C5_COMPOSITE_DELIVERY_METHOD,
-- 	C6_CREATED_BY,
-- 	C7_DATE_CREATED,
-- 	C8_DEFAULT_SERVICE_LOOK,
-- 	C9_ENVELOPE_TYPE,
-- 	C10_GROUP_CODE,
-- 	C11_GROUP_DELIVERY_METHOD,
-- 	C12_LAST_UPDATED,
-- 	C13_MODEL_ETHNICITY,
-- 	C14_MODEL_GENDER,
-- 	C15_MODEL_GRADE,
-- 	C16_PRICE_PROGRAM_ID,
-- 	C17_STAFF_PACKAGE,
-- 	C18_STYLE,
-- 	C19_UPDATED_BY,
-- 	C20_VISUAL_MERCH_ID,
-- 	C21_YEAR_BOOK_LOOK,
-- 	C22_COMMISSION_TYPE,
-- 	C23_COMMISSION_RATE,
-- 	C24_NO_TOUCH_YEARBOOK_LOOK,
-- 	C25_MINIMUM_REQUIREMENTS,
-- 	C26_FLYER_ID,
-- 	C27_PART_NUMBER,
-- 	C28_FLYER_SIZE,
-- 	C29_FLYER_STYLE,
-- 	C30_LAYOUT_CODE,
-- 	C31_PAYMENT_MESSAGE_TEXT,
-- 	C32_CREDIT_CARD_ALLOWED,
-- 	C33_CHECK_PAYABLE_TO,
-- 	C34_SMALL_NOTICE_TEXT,
-- 	C35_ADDITIONAL_INFO_TEXT,
-- 	C36_ADDITIONAL_INFO_PROOF_TEXT,
-- 	C37_FAMILY_PLAN_VERBIAGE,
-- 	C38_PAYMENT_DUE_TIMING_TEXT,
-- 	C39_SPANISH_CAPTION_CODE1,
-- 	C40_SPANISH_CAPTION_CODE2,
-- 	C41_SPANISH_CAPTION_CODE3,
-- 	C42_INSERT_NO,
-- 	C43_INSERT_TYPE,
-- 	C44_MASCOT,
-- 	C45_PAYMENT_METHOD,
-- 	C46_POST_PIC_DAY_CUST_INQ_PHON,
-- 	C47_POST_PIC_DAY_CUST_INQ_PHON,
-- 	C48_PRE_PIC_DAY_CUST_INQ_PHONE,
-- 	C49_PRE_PIC_DAY_CUST_INQ_PHONE,
-- 	C50_THEME,
-- 	C51_OFFERING_TEMPLATE_ID,
-- 	C52_CASUAL_CODE,
-- 	C53_CUSTOMER_SERVICE_EMAIL,
-- 	C54_CUSTOMER_SERVICE_HOURS
-- )
-- values
-- (
-- 	:C1_ID,
-- 	:C2_VERSION,
-- 	:C3_APO_ID,
-- 	:C4_COMPOSITE_CODE,
-- 	:C5_COMPOSITE_DELIVERY_METHOD,
-- 	:C6_CREATED_BY,
-- 	:C7_DATE_CREATED,
-- 	:C8_DEFAULT_SERVICE_LOOK,
-- 	:C9_ENVELOPE_TYPE,
-- 	:C10_GROUP_CODE,
-- 	:C11_GROUP_DELIVERY_METHOD,
-- 	:C12_LAST_UPDATED,
-- 	:C13_MODEL_ETHNICITY,
-- 	:C14_MODEL_GENDER,
-- 	:C15_MODEL_GRADE,
-- 	:C16_PRICE_PROGRAM_ID,
-- 	:C17_STAFF_PACKAGE,
-- 	:C18_STYLE,
-- 	:C19_UPDATED_BY,
-- 	:C20_VISUAL_MERCH_ID,
-- 	:C21_YEAR_BOOK_LOOK,
-- 	:C22_COMMISSION_TYPE,
-- 	:C23_COMMISSION_RATE,
-- 	:C24_NO_TOUCH_YEARBOOK_LOOK,
-- 	:C25_MINIMUM_REQUIREMENTS,
-- 	:C26_FLYER_ID,
-- 	:C27_PART_NUMBER,
-- 	:C28_FLYER_SIZE,
-- 	:C29_FLYER_STYLE,
-- 	:C30_LAYOUT_CODE,
-- 	:C31_PAYMENT_MESSAGE_TEXT,
-- 	:C32_CREDIT_CARD_ALLOWED,
-- 	:C33_CHECK_PAYABLE_TO,
-- 	:C34_SMALL_NOTICE_TEXT,
-- 	:C35_ADDITIONAL_INFO_TEXT,
-- 	:C36_ADDITIONAL_INFO_PROOF_TEXT,
-- 	:C37_FAMILY_PLAN_VERBIAGE,
-- 	:C38_PAYMENT_DUE_TIMING_TEXT,
-- 	:C39_SPANISH_CAPTION_CODE1,
-- 	:C40_SPANISH_CAPTION_CODE2,
-- 	:C41_SPANISH_CAPTION_CODE3,
-- 	:C42_INSERT_NO,
-- 	:C43_INSERT_TYPE,
-- 	:C44_MASCOT,
-- 	:C45_PAYMENT_METHOD,
-- 	:C46_POST_PIC_DAY_CUST_INQ_PHON,
-- 	:C47_POST_PIC_DAY_CUST_INQ_PHON,
-- 	:C48_PRE_PIC_DAY_CUST_INQ_PHONE,
-- 	:C49_PRE_PIC_DAY_CUST_INQ_PHONE,
-- 	:C50_THEME,
-- 	:C51_OFFERING_TEMPLATE_ID,
-- 	:C52_CASUAL_CODE,
-- 	:C53_CUSTOMER_SERVICE_EMAIL,
-- 	:C54_CUSTOMER_SERVICE_HOURS
-- )

-- &


/*-----------------------------------------------*/
/* TASK No. 7 */
/* Analyze work table */



BEGIN
DBMS_STATS.GATHER_TABLE_STATS (
    ownname =>	'RAX_APP_USER',
    tabname =>	'C$_0FOW_FRNG_STG',
    estimate_percent =>	DBMS_STATS.AUTO_SAMPLE_SIZE
);
END;




&


/*-----------------------------------------------*/
/* TASK No. 9 */
/* Set vID */

/* NONE or SET VARIABLE STATEMENT FOUND, CHECK ODI TASK NO. 9 */




/*-----------------------------------------------*/
/* TASK No. 10 */
/* Drop flow table */

BEGIN  
   EXECUTE IMMEDIATE 'drop table RAX_APP_USER.I$_FOW_FRNG_STG648001';  
EXCEPTION  
   WHEN OTHERS THEN  
      IF SQLCODE != -942 THEN  
         RAISE;  
      END IF;  
END;

&


/*-----------------------------------------------*/
/* TASK No. 11 */
/* Create flow table I$ */

create table RAX_APP_USER.I$_FOW_FRNG_STG648001
(
	ID	NUMBER NULL,
	VERSION	NUMBER NULL,
	APO_ID	NUMBER NULL,
	COMPOSITE_CODE	VARCHAR2(255) NULL,
	COMPOSITE_DELIVERY_METHOD	VARCHAR2(255) NULL,
	CREATED_BY	VARCHAR2(255) NULL,
	DATE_CREATED	DATE NULL,
	DEFAULT_SERVICE_LOOK	VARCHAR2(255) NULL,
	ENVELOPE_TYPE	VARCHAR2(255) NULL,
	GROUP_CODE	VARCHAR2(255) NULL,
	GROUP_DELIVERY_METHOD	VARCHAR2(255) NULL,
	LAST_UPDATED	DATE NULL,
	MODEL_ETHNICITY	VARCHAR2(255) NULL,
	MODEL_GENDER	VARCHAR2(255) NULL,
	MODEL_GRADE	VARCHAR2(255) NULL,
	PRICE_PROGRAM_ID	VARCHAR2(255) NULL,
	STAFF_PACKAGE	NUMBER NULL,
	STYLE	VARCHAR2(255) NULL,
	UPDATED_BY	VARCHAR2(255) NULL,
	VISUAL_MERCH_ID	VARCHAR2(255) NULL,
	YEAR_BOOK_LOOK	VARCHAR2(255) NULL,
	COMMISSION_TYPE	VARCHAR2(255) NULL,
	COMMISSION_RATE	NUMBER NULL,
	NO_TOUCH_YEARBOOK_LOOK	VARCHAR2(255) NULL,
	MINIMUM_REQUIREMENTS	NUMBER NULL,
	FLYER_ID	VARCHAR2(255) NULL,
	PART_NUMBER	VARCHAR2(255) NULL,
	FLYER_SIZE	VARCHAR2(255) NULL,
	FLYER_STYLE	VARCHAR2(255) NULL,
	LAYOUT_CODE	VARCHAR2(255) NULL,
	PAYMENT_MESSAGE_TEXT	VARCHAR2(255) NULL,
	CREDIT_CARD_ALLOWED	NUMBER NULL,
	CHECK_PAYABLE_TO	VARCHAR2(255) NULL,
	SMALL_NOTICE_TEXT	VARCHAR2(255) NULL,
	ADDITIONAL_INFO_TEXT	VARCHAR2(255) NULL,
	ADDITIONAL_INFO_PROOF_TEXT	VARCHAR2(255) NULL,
	FAMILY_PLAN_VERBIAGE	VARCHAR2(255) NULL,
	PAYMENT_DUE_TIMING_TEXT	VARCHAR2(255) NULL,
	SPANISH_CAPTION_CODE1	VARCHAR2(255) NULL,
	SPANISH_CAPTION_CODE2	VARCHAR2(255) NULL,
	SPANISH_CAPTION_CODE3	VARCHAR2(255) NULL,
	INSERT_NO	VARCHAR2(255) NULL,
	INSERT_TYPE	VARCHAR2(255) NULL,
	MASCOT	VARCHAR2(255) NULL,
	PAYMENT_METHOD	VARCHAR2(255) NULL,
	POST_PIC_DAY_CUST_INQ_PHONE1	VARCHAR2(255) NULL,
	POST_PIC_DAY_CUST_INQ_PHONE2	VARCHAR2(255) NULL,
	PRE_PIC_DAY_CUST_INQ_PHONE1	VARCHAR2(255) NULL,
	PRE_PIC_DAY_CUST_INQ_PHONE2	VARCHAR2(255) NULL,
	THEME	VARCHAR2(255) NULL,
	ODS_CREATE_DATE	DATE NULL,
	ODS_MODIFY_DATE	DATE NULL,
	OFFERING_TEMPLATE_ID	NUMBER NULL,
	CASUAL_CODE	VARCHAR2(255) NULL,
	CUSTOMER_SERVICE_EMAIL	VARCHAR2(255) NULL,
	CUSTOMER_SERVICE_HOURS	VARCHAR2(255) NULL
	,IND_UPDATE		char(1)
)
NOLOGGING

&


/*-----------------------------------------------*/
/* TASK No. 12 */
/* Insert flow into I$ table */

/* DETECTION_STRATEGY = NOT_EXISTS */
 


  


insert into	RAX_APP_USER.I$_FOW_FRNG_STG648001
(
	ID,
	VERSION,
	APO_ID,
	COMPOSITE_CODE,
	COMPOSITE_DELIVERY_METHOD,
	CREATED_BY,
	DATE_CREATED,
	DEFAULT_SERVICE_LOOK,
	ENVELOPE_TYPE,
	GROUP_CODE,
	GROUP_DELIVERY_METHOD,
	LAST_UPDATED,
	MODEL_ETHNICITY,
	MODEL_GENDER,
	MODEL_GRADE,
	PRICE_PROGRAM_ID,
	STAFF_PACKAGE,
	STYLE,
	UPDATED_BY,
	VISUAL_MERCH_ID,
	YEAR_BOOK_LOOK,
	COMMISSION_TYPE,
	COMMISSION_RATE,
	NO_TOUCH_YEARBOOK_LOOK,
	MINIMUM_REQUIREMENTS,
	FLYER_ID,
	PART_NUMBER,
	FLYER_SIZE,
	FLYER_STYLE,
	LAYOUT_CODE,
	PAYMENT_MESSAGE_TEXT,
	CREDIT_CARD_ALLOWED,
	CHECK_PAYABLE_TO,
	SMALL_NOTICE_TEXT,
	ADDITIONAL_INFO_TEXT,
	ADDITIONAL_INFO_PROOF_TEXT,
	FAMILY_PLAN_VERBIAGE,
	PAYMENT_DUE_TIMING_TEXT,
	SPANISH_CAPTION_CODE1,
	SPANISH_CAPTION_CODE2,
	SPANISH_CAPTION_CODE3,
	INSERT_NO,
	INSERT_TYPE,
	MASCOT,
	PAYMENT_METHOD,
	POST_PIC_DAY_CUST_INQ_PHONE1,
	POST_PIC_DAY_CUST_INQ_PHONE2,
	PRE_PIC_DAY_CUST_INQ_PHONE1,
	PRE_PIC_DAY_CUST_INQ_PHONE2,
	THEME,
	OFFERING_TEMPLATE_ID,
	CASUAL_CODE,
	CUSTOMER_SERVICE_EMAIL,
	CUSTOMER_SERVICE_HOURS,
	IND_UPDATE
)
select 
ID,
	VERSION,
	APO_ID,
	COMPOSITE_CODE,
	COMPOSITE_DELIVERY_METHOD,
	CREATED_BY,
	DATE_CREATED,
	DEFAULT_SERVICE_LOOK,
	ENVELOPE_TYPE,
	GROUP_CODE,
	GROUP_DELIVERY_METHOD,
	LAST_UPDATED,
	MODEL_ETHNICITY,
	MODEL_GENDER,
	MODEL_GRADE,
	PRICE_PROGRAM_ID,
	STAFF_PACKAGE,
	STYLE,
	UPDATED_BY,
	VISUAL_MERCH_ID,
	YEAR_BOOK_LOOK,
	COMMISSION_TYPE,
	COMMISSION_RATE,
	NO_TOUCH_YEARBOOK_LOOK,
	MINIMUM_REQUIREMENTS,
	FLYER_ID,
	PART_NUMBER,
	FLYER_SIZE,
	FLYER_STYLE,
	LAYOUT_CODE,
	PAYMENT_MESSAGE_TEXT,
	CREDIT_CARD_ALLOWED,
	CHECK_PAYABLE_TO,
	SMALL_NOTICE_TEXT,
	ADDITIONAL_INFO_TEXT,
	ADDITIONAL_INFO_PROOF_TEXT,
	FAMILY_PLAN_VERBIAGE,
	PAYMENT_DUE_TIMING_TEXT,
	SPANISH_CAPTION_CODE1,
	SPANISH_CAPTION_CODE2,
	SPANISH_CAPTION_CODE3,
	INSERT_NO,
	INSERT_TYPE,
	MASCOT,
	PAYMENT_METHOD,
	POST_PIC_DAY_CUST_INQ_PHONE1,
	POST_PIC_DAY_CUST_INQ_PHONE2,
	PRE_PIC_DAY_CUST_INQ_PHONE1,
	PRE_PIC_DAY_CUST_INQ_PHONE2,
	THEME,
	OFFERING_TEMPLATE_ID,
	CASUAL_CODE,
	CUSTOMER_SERVICE_EMAIL,
	CUSTOMER_SERVICE_HOURS,
	IND_UPDATE
 from (


select 	 
	
	C1_ID ID,
	C2_VERSION VERSION,
	C3_APO_ID APO_ID,
	C4_COMPOSITE_CODE COMPOSITE_CODE,
	C5_COMPOSITE_DELIVERY_METHOD COMPOSITE_DELIVERY_METHOD,
	C6_CREATED_BY CREATED_BY,
	C7_DATE_CREATED DATE_CREATED,
	C8_DEFAULT_SERVICE_LOOK DEFAULT_SERVICE_LOOK,
	C9_ENVELOPE_TYPE ENVELOPE_TYPE,
	C10_GROUP_CODE GROUP_CODE,
	C11_GROUP_DELIVERY_METHOD GROUP_DELIVERY_METHOD,
	C12_LAST_UPDATED LAST_UPDATED,
	C13_MODEL_ETHNICITY MODEL_ETHNICITY,
	C14_MODEL_GENDER MODEL_GENDER,
	C15_MODEL_GRADE MODEL_GRADE,
	C16_PRICE_PROGRAM_ID PRICE_PROGRAM_ID,
	C17_STAFF_PACKAGE STAFF_PACKAGE,
	C18_STYLE STYLE,
	C19_UPDATED_BY UPDATED_BY,
	C20_VISUAL_MERCH_ID VISUAL_MERCH_ID,
	C21_YEAR_BOOK_LOOK YEAR_BOOK_LOOK,
	C22_COMMISSION_TYPE COMMISSION_TYPE,
	C23_COMMISSION_RATE COMMISSION_RATE,
	C24_NO_TOUCH_YEARBOOK_LOOK NO_TOUCH_YEARBOOK_LOOK,
	C25_MINIMUM_REQUIREMENTS MINIMUM_REQUIREMENTS,
	C26_FLYER_ID FLYER_ID,
	C27_PART_NUMBER PART_NUMBER,
	C28_FLYER_SIZE FLYER_SIZE,
	C29_FLYER_STYLE FLYER_STYLE,
	C30_LAYOUT_CODE LAYOUT_CODE,
	C31_PAYMENT_MESSAGE_TEXT PAYMENT_MESSAGE_TEXT,
	C32_CREDIT_CARD_ALLOWED CREDIT_CARD_ALLOWED,
	C33_CHECK_PAYABLE_TO CHECK_PAYABLE_TO,
	C34_SMALL_NOTICE_TEXT SMALL_NOTICE_TEXT,
	C35_ADDITIONAL_INFO_TEXT ADDITIONAL_INFO_TEXT,
	C36_ADDITIONAL_INFO_PROOF_TEXT ADDITIONAL_INFO_PROOF_TEXT,
	C37_FAMILY_PLAN_VERBIAGE FAMILY_PLAN_VERBIAGE,
	C38_PAYMENT_DUE_TIMING_TEXT PAYMENT_DUE_TIMING_TEXT,
	C39_SPANISH_CAPTION_CODE1 SPANISH_CAPTION_CODE1,
	C40_SPANISH_CAPTION_CODE2 SPANISH_CAPTION_CODE2,
	C41_SPANISH_CAPTION_CODE3 SPANISH_CAPTION_CODE3,
	C42_INSERT_NO INSERT_NO,
	C43_INSERT_TYPE INSERT_TYPE,
	C44_MASCOT MASCOT,
	C45_PAYMENT_METHOD PAYMENT_METHOD,
	C46_POST_PIC_DAY_CUST_INQ_PHON POST_PIC_DAY_CUST_INQ_PHONE1,
	C47_POST_PIC_DAY_CUST_INQ_PHON POST_PIC_DAY_CUST_INQ_PHONE2,
	C48_PRE_PIC_DAY_CUST_INQ_PHONE PRE_PIC_DAY_CUST_INQ_PHONE1,
	C49_PRE_PIC_DAY_CUST_INQ_PHONE PRE_PIC_DAY_CUST_INQ_PHONE2,
	C50_THEME THEME,
	C51_OFFERING_TEMPLATE_ID OFFERING_TEMPLATE_ID,
	C52_CASUAL_CODE CASUAL_CODE,
	C53_CUSTOMER_SERVICE_EMAIL CUSTOMER_SERVICE_EMAIL,
	C54_CUSTOMER_SERVICE_HOURS CUSTOMER_SERVICE_HOURS,

	'I' IND_UPDATE

from	RAX_APP_USER.C$_0FOW_FRNG_STG
where	(1=1)






) S
where NOT EXISTS 
	( select 1 from ODS_STAGE_CA.FOW_OFFERING_STG T
	where	T.ID	= S.ID 
		 and ((T.VERSION = S.VERSION) or (T.VERSION IS NULL and S.VERSION IS NULL)) and
		((T.APO_ID = S.APO_ID) or (T.APO_ID IS NULL and S.APO_ID IS NULL)) and
		((T.COMPOSITE_CODE = S.COMPOSITE_CODE) or (T.COMPOSITE_CODE IS NULL and S.COMPOSITE_CODE IS NULL)) and
		((T.COMPOSITE_DELIVERY_METHOD = S.COMPOSITE_DELIVERY_METHOD) or (T.COMPOSITE_DELIVERY_METHOD IS NULL and S.COMPOSITE_DELIVERY_METHOD IS NULL)) and
		((T.CREATED_BY = S.CREATED_BY) or (T.CREATED_BY IS NULL and S.CREATED_BY IS NULL)) and
		((T.DATE_CREATED = S.DATE_CREATED) or (T.DATE_CREATED IS NULL and S.DATE_CREATED IS NULL)) and
		((T.DEFAULT_SERVICE_LOOK = S.DEFAULT_SERVICE_LOOK) or (T.DEFAULT_SERVICE_LOOK IS NULL and S.DEFAULT_SERVICE_LOOK IS NULL)) and
		((T.ENVELOPE_TYPE = S.ENVELOPE_TYPE) or (T.ENVELOPE_TYPE IS NULL and S.ENVELOPE_TYPE IS NULL)) and
		((T.GROUP_CODE = S.GROUP_CODE) or (T.GROUP_CODE IS NULL and S.GROUP_CODE IS NULL)) and
		((T.GROUP_DELIVERY_METHOD = S.GROUP_DELIVERY_METHOD) or (T.GROUP_DELIVERY_METHOD IS NULL and S.GROUP_DELIVERY_METHOD IS NULL)) and
		((T.LAST_UPDATED = S.LAST_UPDATED) or (T.LAST_UPDATED IS NULL and S.LAST_UPDATED IS NULL)) and
		((T.MODEL_ETHNICITY = S.MODEL_ETHNICITY) or (T.MODEL_ETHNICITY IS NULL and S.MODEL_ETHNICITY IS NULL)) and
		((T.MODEL_GENDER = S.MODEL_GENDER) or (T.MODEL_GENDER IS NULL and S.MODEL_GENDER IS NULL)) and
		((T.MODEL_GRADE = S.MODEL_GRADE) or (T.MODEL_GRADE IS NULL and S.MODEL_GRADE IS NULL)) and
		((T.PRICE_PROGRAM_ID = S.PRICE_PROGRAM_ID) or (T.PRICE_PROGRAM_ID IS NULL and S.PRICE_PROGRAM_ID IS NULL)) and
		((T.STAFF_PACKAGE = S.STAFF_PACKAGE) or (T.STAFF_PACKAGE IS NULL and S.STAFF_PACKAGE IS NULL)) and
		((T.STYLE = S.STYLE) or (T.STYLE IS NULL and S.STYLE IS NULL)) and
		((T.UPDATED_BY = S.UPDATED_BY) or (T.UPDATED_BY IS NULL and S.UPDATED_BY IS NULL)) and
		((T.VISUAL_MERCH_ID = S.VISUAL_MERCH_ID) or (T.VISUAL_MERCH_ID IS NULL and S.VISUAL_MERCH_ID IS NULL)) and
		((T.YEAR_BOOK_LOOK = S.YEAR_BOOK_LOOK) or (T.YEAR_BOOK_LOOK IS NULL and S.YEAR_BOOK_LOOK IS NULL)) and
		((T.COMMISSION_TYPE = S.COMMISSION_TYPE) or (T.COMMISSION_TYPE IS NULL and S.COMMISSION_TYPE IS NULL)) and
		((T.COMMISSION_RATE = S.COMMISSION_RATE) or (T.COMMISSION_RATE IS NULL and S.COMMISSION_RATE IS NULL)) and
		((T.NO_TOUCH_YEARBOOK_LOOK = S.NO_TOUCH_YEARBOOK_LOOK) or (T.NO_TOUCH_YEARBOOK_LOOK IS NULL and S.NO_TOUCH_YEARBOOK_LOOK IS NULL)) and
		((T.MINIMUM_REQUIREMENTS = S.MINIMUM_REQUIREMENTS) or (T.MINIMUM_REQUIREMENTS IS NULL and S.MINIMUM_REQUIREMENTS IS NULL)) and
		((T.FLYER_ID = S.FLYER_ID) or (T.FLYER_ID IS NULL and S.FLYER_ID IS NULL)) and
		((T.PART_NUMBER = S.PART_NUMBER) or (T.PART_NUMBER IS NULL and S.PART_NUMBER IS NULL)) and
		((T.FLYER_SIZE = S.FLYER_SIZE) or (T.FLYER_SIZE IS NULL and S.FLYER_SIZE IS NULL)) and
		((T.FLYER_STYLE = S.FLYER_STYLE) or (T.FLYER_STYLE IS NULL and S.FLYER_STYLE IS NULL)) and
		((T.LAYOUT_CODE = S.LAYOUT_CODE) or (T.LAYOUT_CODE IS NULL and S.LAYOUT_CODE IS NULL)) and
		((T.PAYMENT_MESSAGE_TEXT = S.PAYMENT_MESSAGE_TEXT) or (T.PAYMENT_MESSAGE_TEXT IS NULL and S.PAYMENT_MESSAGE_TEXT IS NULL)) and
		((T.CREDIT_CARD_ALLOWED = S.CREDIT_CARD_ALLOWED) or (T.CREDIT_CARD_ALLOWED IS NULL and S.CREDIT_CARD_ALLOWED IS NULL)) and
		((T.CHECK_PAYABLE_TO = S.CHECK_PAYABLE_TO) or (T.CHECK_PAYABLE_TO IS NULL and S.CHECK_PAYABLE_TO IS NULL)) and
		((T.SMALL_NOTICE_TEXT = S.SMALL_NOTICE_TEXT) or (T.SMALL_NOTICE_TEXT IS NULL and S.SMALL_NOTICE_TEXT IS NULL)) and
		((T.ADDITIONAL_INFO_TEXT = S.ADDITIONAL_INFO_TEXT) or (T.ADDITIONAL_INFO_TEXT IS NULL and S.ADDITIONAL_INFO_TEXT IS NULL)) and
		((T.ADDITIONAL_INFO_PROOF_TEXT = S.ADDITIONAL_INFO_PROOF_TEXT) or (T.ADDITIONAL_INFO_PROOF_TEXT IS NULL and S.ADDITIONAL_INFO_PROOF_TEXT IS NULL)) and
		((T.FAMILY_PLAN_VERBIAGE = S.FAMILY_PLAN_VERBIAGE) or (T.FAMILY_PLAN_VERBIAGE IS NULL and S.FAMILY_PLAN_VERBIAGE IS NULL)) and
		((T.PAYMENT_DUE_TIMING_TEXT = S.PAYMENT_DUE_TIMING_TEXT) or (T.PAYMENT_DUE_TIMING_TEXT IS NULL and S.PAYMENT_DUE_TIMING_TEXT IS NULL)) and
		((T.SPANISH_CAPTION_CODE1 = S.SPANISH_CAPTION_CODE1) or (T.SPANISH_CAPTION_CODE1 IS NULL and S.SPANISH_CAPTION_CODE1 IS NULL)) and
		((T.SPANISH_CAPTION_CODE2 = S.SPANISH_CAPTION_CODE2) or (T.SPANISH_CAPTION_CODE2 IS NULL and S.SPANISH_CAPTION_CODE2 IS NULL)) and
		((T.SPANISH_CAPTION_CODE3 = S.SPANISH_CAPTION_CODE3) or (T.SPANISH_CAPTION_CODE3 IS NULL and S.SPANISH_CAPTION_CODE3 IS NULL)) and
		((T.INSERT_NO = S.INSERT_NO) or (T.INSERT_NO IS NULL and S.INSERT_NO IS NULL)) and
		((T.INSERT_TYPE = S.INSERT_TYPE) or (T.INSERT_TYPE IS NULL and S.INSERT_TYPE IS NULL)) and
		((T.MASCOT = S.MASCOT) or (T.MASCOT IS NULL and S.MASCOT IS NULL)) and
		((T.PAYMENT_METHOD = S.PAYMENT_METHOD) or (T.PAYMENT_METHOD IS NULL and S.PAYMENT_METHOD IS NULL)) and
		((T.POST_PIC_DAY_CUST_INQ_PHONE1 = S.POST_PIC_DAY_CUST_INQ_PHONE1) or (T.POST_PIC_DAY_CUST_INQ_PHONE1 IS NULL and S.POST_PIC_DAY_CUST_INQ_PHONE1 IS NULL)) and
		((T.POST_PIC_DAY_CUST_INQ_PHONE2 = S.POST_PIC_DAY_CUST_INQ_PHONE2) or (T.POST_PIC_DAY_CUST_INQ_PHONE2 IS NULL and S.POST_PIC_DAY_CUST_INQ_PHONE2 IS NULL)) and
		((T.PRE_PIC_DAY_CUST_INQ_PHONE1 = S.PRE_PIC_DAY_CUST_INQ_PHONE1) or (T.PRE_PIC_DAY_CUST_INQ_PHONE1 IS NULL and S.PRE_PIC_DAY_CUST_INQ_PHONE1 IS NULL)) and
		((T.PRE_PIC_DAY_CUST_INQ_PHONE2 = S.PRE_PIC_DAY_CUST_INQ_PHONE2) or (T.PRE_PIC_DAY_CUST_INQ_PHONE2 IS NULL and S.PRE_PIC_DAY_CUST_INQ_PHONE2 IS NULL)) and
		((T.THEME = S.THEME) or (T.THEME IS NULL and S.THEME IS NULL)) and
		((T.OFFERING_TEMPLATE_ID = S.OFFERING_TEMPLATE_ID) or (T.OFFERING_TEMPLATE_ID IS NULL and S.OFFERING_TEMPLATE_ID IS NULL)) and
		((T.CASUAL_CODE = S.CASUAL_CODE) or (T.CASUAL_CODE IS NULL and S.CASUAL_CODE IS NULL)) and
		((T.CUSTOMER_SERVICE_EMAIL = S.CUSTOMER_SERVICE_EMAIL) or (T.CUSTOMER_SERVICE_EMAIL IS NULL and S.CUSTOMER_SERVICE_EMAIL IS NULL)) and
		((T.CUSTOMER_SERVICE_HOURS = S.CUSTOMER_SERVICE_HOURS) or (T.CUSTOMER_SERVICE_HOURS IS NULL and S.CUSTOMER_SERVICE_HOURS IS NULL))
        )

  
  

  



&


/*-----------------------------------------------*/
/* TASK No. 13 */
/* Analyze integration table */



begin
    dbms_stats.gather_table_stats(
	ownname => 'RAX_APP_USER',
	tabname => 'I$_FOW_FRNG_STG648001',
	estimate_percent => dbms_stats.auto_sample_size
    );
end;



&


/*-----------------------------------------------*/
/* TASK No. 14 */
/* Create Index on flow table */

create index	RAX_APP_USER.I$_FOW_FRNG_STG_IDX648001
on		RAX_APP_USER.I$_FOW_FRNG_STG648001 (ID)
NOLOGGING

&


/*-----------------------------------------------*/
/* TASK No. 15 */
/* Merge Rows */

merge into	ODS_STAGE_CA.FOW_OFFERING_STG T
using	RAX_APP_USER.I$_FOW_FRNG_STG648001 S
on	(
		T.ID=S.ID
	)
when matched
then update set
	T.VERSION	= S.VERSION,
	T.APO_ID	= S.APO_ID,
	T.COMPOSITE_CODE	= S.COMPOSITE_CODE,
	T.COMPOSITE_DELIVERY_METHOD	= S.COMPOSITE_DELIVERY_METHOD,
	T.CREATED_BY	= S.CREATED_BY,
	T.DATE_CREATED	= S.DATE_CREATED,
	T.DEFAULT_SERVICE_LOOK	= S.DEFAULT_SERVICE_LOOK,
	T.ENVELOPE_TYPE	= S.ENVELOPE_TYPE,
	T.GROUP_CODE	= S.GROUP_CODE,
	T.GROUP_DELIVERY_METHOD	= S.GROUP_DELIVERY_METHOD,
	T.LAST_UPDATED	= S.LAST_UPDATED,
	T.MODEL_ETHNICITY	= S.MODEL_ETHNICITY,
	T.MODEL_GENDER	= S.MODEL_GENDER,
	T.MODEL_GRADE	= S.MODEL_GRADE,
	T.PRICE_PROGRAM_ID	= S.PRICE_PROGRAM_ID,
	T.STAFF_PACKAGE	= S.STAFF_PACKAGE,
	T.STYLE	= S.STYLE,
	T.UPDATED_BY	= S.UPDATED_BY,
	T.VISUAL_MERCH_ID	= S.VISUAL_MERCH_ID,
	T.YEAR_BOOK_LOOK	= S.YEAR_BOOK_LOOK,
	T.COMMISSION_TYPE	= S.COMMISSION_TYPE,
	T.COMMISSION_RATE	= S.COMMISSION_RATE,
	T.NO_TOUCH_YEARBOOK_LOOK	= S.NO_TOUCH_YEARBOOK_LOOK,
	T.MINIMUM_REQUIREMENTS	= S.MINIMUM_REQUIREMENTS,
	T.FLYER_ID	= S.FLYER_ID,
	T.PART_NUMBER	= S.PART_NUMBER,
	T.FLYER_SIZE	= S.FLYER_SIZE,
	T.FLYER_STYLE	= S.FLYER_STYLE,
	T.LAYOUT_CODE	= S.LAYOUT_CODE,
	T.PAYMENT_MESSAGE_TEXT	= S.PAYMENT_MESSAGE_TEXT,
	T.CREDIT_CARD_ALLOWED	= S.CREDIT_CARD_ALLOWED,
	T.CHECK_PAYABLE_TO	= S.CHECK_PAYABLE_TO,
	T.SMALL_NOTICE_TEXT	= S.SMALL_NOTICE_TEXT,
	T.ADDITIONAL_INFO_TEXT	= S.ADDITIONAL_INFO_TEXT,
	T.ADDITIONAL_INFO_PROOF_TEXT	= S.ADDITIONAL_INFO_PROOF_TEXT,
	T.FAMILY_PLAN_VERBIAGE	= S.FAMILY_PLAN_VERBIAGE,
	T.PAYMENT_DUE_TIMING_TEXT	= S.PAYMENT_DUE_TIMING_TEXT,
	T.SPANISH_CAPTION_CODE1	= S.SPANISH_CAPTION_CODE1,
	T.SPANISH_CAPTION_CODE2	= S.SPANISH_CAPTION_CODE2,
	T.SPANISH_CAPTION_CODE3	= S.SPANISH_CAPTION_CODE3,
	T.INSERT_NO	= S.INSERT_NO,
	T.INSERT_TYPE	= S.INSERT_TYPE,
	T.MASCOT	= S.MASCOT,
	T.PAYMENT_METHOD	= S.PAYMENT_METHOD,
	T.POST_PIC_DAY_CUST_INQ_PHONE1	= S.POST_PIC_DAY_CUST_INQ_PHONE1,
	T.POST_PIC_DAY_CUST_INQ_PHONE2	= S.POST_PIC_DAY_CUST_INQ_PHONE2,
	T.PRE_PIC_DAY_CUST_INQ_PHONE1	= S.PRE_PIC_DAY_CUST_INQ_PHONE1,
	T.PRE_PIC_DAY_CUST_INQ_PHONE2	= S.PRE_PIC_DAY_CUST_INQ_PHONE2,
	T.THEME	= S.THEME,
	T.OFFERING_TEMPLATE_ID	= S.OFFERING_TEMPLATE_ID,
	T.CASUAL_CODE	= S.CASUAL_CODE,
	T.CUSTOMER_SERVICE_EMAIL	= S.CUSTOMER_SERVICE_EMAIL,
	T.CUSTOMER_SERVICE_HOURS	= S.CUSTOMER_SERVICE_HOURS
	,                                                     T.ODS_MODIFY_DATE	= SYSDATE
when not matched
then insert
	(
	T.ID,
	T.VERSION,
	T.APO_ID,
	T.COMPOSITE_CODE,
	T.COMPOSITE_DELIVERY_METHOD,
	T.CREATED_BY,
	T.DATE_CREATED,
	T.DEFAULT_SERVICE_LOOK,
	T.ENVELOPE_TYPE,
	T.GROUP_CODE,
	T.GROUP_DELIVERY_METHOD,
	T.LAST_UPDATED,
	T.MODEL_ETHNICITY,
	T.MODEL_GENDER,
	T.MODEL_GRADE,
	T.PRICE_PROGRAM_ID,
	T.STAFF_PACKAGE,
	T.STYLE,
	T.UPDATED_BY,
	T.VISUAL_MERCH_ID,
	T.YEAR_BOOK_LOOK,
	T.COMMISSION_TYPE,
	T.COMMISSION_RATE,
	T.NO_TOUCH_YEARBOOK_LOOK,
	T.MINIMUM_REQUIREMENTS,
	T.FLYER_ID,
	T.PART_NUMBER,
	T.FLYER_SIZE,
	T.FLYER_STYLE,
	T.LAYOUT_CODE,
	T.PAYMENT_MESSAGE_TEXT,
	T.CREDIT_CARD_ALLOWED,
	T.CHECK_PAYABLE_TO,
	T.SMALL_NOTICE_TEXT,
	T.ADDITIONAL_INFO_TEXT,
	T.ADDITIONAL_INFO_PROOF_TEXT,
	T.FAMILY_PLAN_VERBIAGE,
	T.PAYMENT_DUE_TIMING_TEXT,
	T.SPANISH_CAPTION_CODE1,
	T.SPANISH_CAPTION_CODE2,
	T.SPANISH_CAPTION_CODE3,
	T.INSERT_NO,
	T.INSERT_TYPE,
	T.MASCOT,
	T.PAYMENT_METHOD,
	T.POST_PIC_DAY_CUST_INQ_PHONE1,
	T.POST_PIC_DAY_CUST_INQ_PHONE2,
	T.PRE_PIC_DAY_CUST_INQ_PHONE1,
	T.PRE_PIC_DAY_CUST_INQ_PHONE2,
	T.THEME,
	T.OFFERING_TEMPLATE_ID,
	T.CASUAL_CODE,
	T.CUSTOMER_SERVICE_EMAIL,
	T.CUSTOMER_SERVICE_HOURS
	,                                                      T.ODS_CREATE_DATE,
	T.ODS_MODIFY_DATE
	)
values
	(
	S.ID,
	S.VERSION,
	S.APO_ID,
	S.COMPOSITE_CODE,
	S.COMPOSITE_DELIVERY_METHOD,
	S.CREATED_BY,
	S.DATE_CREATED,
	S.DEFAULT_SERVICE_LOOK,
	S.ENVELOPE_TYPE,
	S.GROUP_CODE,
	S.GROUP_DELIVERY_METHOD,
	S.LAST_UPDATED,
	S.MODEL_ETHNICITY,
	S.MODEL_GENDER,
	S.MODEL_GRADE,
	S.PRICE_PROGRAM_ID,
	S.STAFF_PACKAGE,
	S.STYLE,
	S.UPDATED_BY,
	S.VISUAL_MERCH_ID,
	S.YEAR_BOOK_LOOK,
	S.COMMISSION_TYPE,
	S.COMMISSION_RATE,
	S.NO_TOUCH_YEARBOOK_LOOK,
	S.MINIMUM_REQUIREMENTS,
	S.FLYER_ID,
	S.PART_NUMBER,
	S.FLYER_SIZE,
	S.FLYER_STYLE,
	S.LAYOUT_CODE,
	S.PAYMENT_MESSAGE_TEXT,
	S.CREDIT_CARD_ALLOWED,
	S.CHECK_PAYABLE_TO,
	S.SMALL_NOTICE_TEXT,
	S.ADDITIONAL_INFO_TEXT,
	S.ADDITIONAL_INFO_PROOF_TEXT,
	S.FAMILY_PLAN_VERBIAGE,
	S.PAYMENT_DUE_TIMING_TEXT,
	S.SPANISH_CAPTION_CODE1,
	S.SPANISH_CAPTION_CODE2,
	S.SPANISH_CAPTION_CODE3,
	S.INSERT_NO,
	S.INSERT_TYPE,
	S.MASCOT,
	S.PAYMENT_METHOD,
	S.POST_PIC_DAY_CUST_INQ_PHONE1,
	S.POST_PIC_DAY_CUST_INQ_PHONE2,
	S.PRE_PIC_DAY_CUST_INQ_PHONE1,
	S.PRE_PIC_DAY_CUST_INQ_PHONE2,
	S.THEME,
	S.OFFERING_TEMPLATE_ID,
	S.CASUAL_CODE,
	S.CUSTOMER_SERVICE_EMAIL,
	S.CUSTOMER_SERVICE_HOURS
	,                                                      SYSDATE,
	SYSDATE
	)

&


/*-----------------------------------------------*/
/* TASK No. 16 */
/* Commit transaction */

/*commit*/


/*-----------------------------------------------*/
/* TASK No. 17 */
/* Drop flow table */

drop table RAX_APP_USER.I$_FOW_FRNG_STG648001 

&


/*-----------------------------------------------*/
/* TASK No. 1000008 */
/* Drop work table */

drop table RAX_APP_USER.C$_0FOW_FRNG_STG 

&


/*-----------------------------------------------*/
/* TASK No. 18 */
/* merge into ODS_STAGE_CA.fow_offering_xr */

Merge Into ODS_STAGE_CA.Fow_Offering_Xr T
Using (Select ID, Offering_Template_Id, Apo_Id From ODS_STAGE_CA.Fow_Offering_Stg 
       where ODS_MODIFY_DATE> TO_DATE(SUBSTR(:v_cdc_load_date,1,19),'YYYY-MM-DD HH24:MI:SS') - :v_cdc_oms_overlap
       
)S
on(
T.ID=S.ID	
)
when matched
Then Update Set
	T.Apo_Id= S.Apo_Id,
 	T.OFFERING_MODEL_ID = S.OFFERING_TEMPLATE_ID	
when not matched
then insert(
T.ID,
T.Apo_Id,
T.Offering_Model_Id,   
 T.OFFERING_OID,
T.ODS_CREATE_DATE
)
values
(
S.ID,
S.Apo_Id,
S.OFFERING_TEMPLATE_ID,   
 ODS_STAGE_CA.FOW_OFFERING_OID_SEQ.nextval,
SYSDATE
)

&


/*-----------------------------------------------*/
/* TASK No. 19 */
/* Drop flow table */

BEGIN  
   EXECUTE IMMEDIATE 'drop table RAX_APP_USER.I$_OFFERING';  
EXCEPTION  
   WHEN OTHERS THEN  
      IF SQLCODE != -942 THEN  
         RAISE;  
      END IF;  
END;

&


/*-----------------------------------------------*/
/* TASK No. 20 */
/* Create flow table I$ */

create table RAX_APP_USER.I$_OFFERING
(
	OFFERING_OID		NUMBER NULL,
	APO_OID		NUMBER NULL,
	OFFERING_MODEL_OID		NUMBER NULL,
	COMPOSITE_CODE		VARCHAR2(255) NULL,
	COMPOSITE_DELIVERY_METHOD		VARCHAR2(255) NULL,
	CREATED_BY		VARCHAR2(255) NULL,
	DATE_CREATED		DATE NULL,
	DEFAULT_SERVICE_LOOK		VARCHAR2(255) NULL,
	ENVELOPE_TYPE		VARCHAR2(255) NULL,
	GROUP_CODE		VARCHAR2(255) NULL,
	GROUP_DELIVERY_METHOD		VARCHAR2(255) NULL,
	LAST_UPDATED		DATE NULL,
	MODEL_ETHNICITY		VARCHAR2(255) NULL,
	MODEL_GENDER		VARCHAR2(255) NULL,
	MODEL_GRADE		VARCHAR2(255) NULL,
	PRICE_PROGRAM_ID		VARCHAR2(255) NULL,
	STAFF_PACKAGE		NUMBER NULL,
	STYLE		VARCHAR2(255) NULL,
	UPDATED_BY		VARCHAR2(255) NULL,
	VISUAL_MERCH_ID		VARCHAR2(255) NULL,
	YEAR_BOOK_LOOK		VARCHAR2(255) NULL,
	COMMISSION_TYPE		VARCHAR2(255) NULL,
	COMMISSION_RATE		NUMBER NULL,
	NO_TOUCH_YEARBOOK_LOOK		VARCHAR2(255) NULL,
	MINIMUM_REQUIREMENTS		NUMBER NULL,
	FLYER_ID		VARCHAR2(255) NULL,
	PART_NUMBER		VARCHAR2(255) NULL,
	FLYER_SIZE		VARCHAR2(255) NULL,
	FLYER_STYLE		VARCHAR2(255) NULL,
	LAYOUT_CODE		VARCHAR2(255) NULL,
	PAYMENT_MESSAGE_TEXT		VARCHAR2(255) NULL,
	CREDIT_CARD_ALLOWED		NUMBER NULL,
	CHECK_PAYABLE_TO		VARCHAR2(255) NULL,
	SMALL_NOTICE_TEXT		VARCHAR2(255) NULL,
	ADDITIONAL_INFO_TEXT		VARCHAR2(255) NULL,
	ADDITIONAL_INFO_PROOF_TEXT		VARCHAR2(255) NULL,
	FAMILY_PLAN_VERBIAGE		VARCHAR2(255) NULL,
	PAYMENT_DUE_TIMING_TEXT		VARCHAR2(255) NULL,
	SPANISH_CAPTION_CODE1		VARCHAR2(255) NULL,
	SPANISH_CAPTION_CODE2		VARCHAR2(255) NULL,
	SPANISH_CAPTION_CODE3		VARCHAR2(255) NULL,
	INSERT_NO		VARCHAR2(255) NULL,
	INSERT_TYPE		VARCHAR2(255) NULL,
	MASCOT		VARCHAR2(255) NULL,
	PAYMENT_METHOD		VARCHAR2(255) NULL,
	POST_PIC_DAY_CUST_INQ_PHONE1		VARCHAR2(255) NULL,
	POST_PIC_DAY_CUST_INQ_PHONE2		VARCHAR2(255) NULL,
	PRE_PIC_DAY_CUST_INQ_PHONE1		VARCHAR2(255) NULL,
	PRE_PIC_DAY_CUST_INQ_PHONE2		VARCHAR2(255) NULL,
	THEME		VARCHAR2(255) NULL,
	CASUAL_CODE		VARCHAR2(255) NULL,
	CUSTOMER_SERVICE_EMAIL		VARCHAR2(255) NULL,
	CUSTOMER_SERVICE_HOURS		VARCHAR2(255) NULL,
	ODS_CREATE_DATE		DATE NULL,
	ODS_MODIFY_DATE		DATE NULL,
	SOURCE_SYSTEM_OID		NUMBER NULL,
	IND_UPDATE		CHAR(1)
)
NOLOGGING

&


/*-----------------------------------------------*/
/* TASK No. 21 */
/* Insert flow into I$ table */

/* DETECTION_STRATEGY = NOT_EXISTS */
 


  


insert into	RAX_APP_USER.I$_OFFERING
(
	OFFERING_OID,
	APO_OID,
	OFFERING_MODEL_OID,
	COMPOSITE_CODE,
	COMPOSITE_DELIVERY_METHOD,
	CREATED_BY,
	DATE_CREATED,
	DEFAULT_SERVICE_LOOK,
	ENVELOPE_TYPE,
	GROUP_CODE,
	GROUP_DELIVERY_METHOD,
	LAST_UPDATED,
	MODEL_ETHNICITY,
	MODEL_GENDER,
	MODEL_GRADE,
	PRICE_PROGRAM_ID,
	STAFF_PACKAGE,
	STYLE,
	UPDATED_BY,
	VISUAL_MERCH_ID,
	YEAR_BOOK_LOOK,
	COMMISSION_TYPE,
	COMMISSION_RATE,
	NO_TOUCH_YEARBOOK_LOOK,
	MINIMUM_REQUIREMENTS,
	FLYER_ID,
	PART_NUMBER,
	FLYER_SIZE,
	FLYER_STYLE,
	LAYOUT_CODE,
	PAYMENT_MESSAGE_TEXT,
	CREDIT_CARD_ALLOWED,
	CHECK_PAYABLE_TO,
	SMALL_NOTICE_TEXT,
	ADDITIONAL_INFO_TEXT,
	ADDITIONAL_INFO_PROOF_TEXT,
	FAMILY_PLAN_VERBIAGE,
	PAYMENT_DUE_TIMING_TEXT,
	SPANISH_CAPTION_CODE1,
	SPANISH_CAPTION_CODE2,
	SPANISH_CAPTION_CODE3,
	INSERT_NO,
	INSERT_TYPE,
	MASCOT,
	PAYMENT_METHOD,
	POST_PIC_DAY_CUST_INQ_PHONE1,
	POST_PIC_DAY_CUST_INQ_PHONE2,
	PRE_PIC_DAY_CUST_INQ_PHONE1,
	PRE_PIC_DAY_CUST_INQ_PHONE2,
	THEME,
	CASUAL_CODE,
	CUSTOMER_SERVICE_EMAIL,
	CUSTOMER_SERVICE_HOURS,
	ODS_CREATE_DATE,
	ODS_MODIFY_DATE,
	SOURCE_SYSTEM_OID,
	IND_UPDATE
)
select 
OFFERING_OID,
	APO_OID,
	OFFERING_MODEL_OID,
	COMPOSITE_CODE,
	COMPOSITE_DELIVERY_METHOD,
	CREATED_BY,
	DATE_CREATED,
	DEFAULT_SERVICE_LOOK,
	ENVELOPE_TYPE,
	GROUP_CODE,
	GROUP_DELIVERY_METHOD,
	LAST_UPDATED,
	MODEL_ETHNICITY,
	MODEL_GENDER,
	MODEL_GRADE,
	PRICE_PROGRAM_ID,
	STAFF_PACKAGE,
	STYLE,
	UPDATED_BY,
	VISUAL_MERCH_ID,
	YEAR_BOOK_LOOK,
	COMMISSION_TYPE,
	COMMISSION_RATE,
	NO_TOUCH_YEARBOOK_LOOK,
	MINIMUM_REQUIREMENTS,
	FLYER_ID,
	PART_NUMBER,
	FLYER_SIZE,
	FLYER_STYLE,
	LAYOUT_CODE,
	PAYMENT_MESSAGE_TEXT,
	CREDIT_CARD_ALLOWED,
	CHECK_PAYABLE_TO,
	SMALL_NOTICE_TEXT,
	ADDITIONAL_INFO_TEXT,
	ADDITIONAL_INFO_PROOF_TEXT,
	FAMILY_PLAN_VERBIAGE,
	PAYMENT_DUE_TIMING_TEXT,
	SPANISH_CAPTION_CODE1,
	SPANISH_CAPTION_CODE2,
	SPANISH_CAPTION_CODE3,
	INSERT_NO,
	INSERT_TYPE,
	MASCOT,
	PAYMENT_METHOD,
	POST_PIC_DAY_CUST_INQ_PHONE1,
	POST_PIC_DAY_CUST_INQ_PHONE2,
	PRE_PIC_DAY_CUST_INQ_PHONE1,
	PRE_PIC_DAY_CUST_INQ_PHONE2,
	THEME,
	CASUAL_CODE,
	CUSTOMER_SERVICE_EMAIL,
	CUSTOMER_SERVICE_HOURS,
	ODS_CREATE_DATE,
	ODS_MODIFY_DATE,
	SOURCE_SYSTEM_OID,
	IND_UPDATE
 from (


select 	 
	
	FOW_OFFERING_XR.OFFERING_OID OFFERING_OID,
	APO.APO_OID APO_OID,
	OFFERING_MODEL_XR.OFFERING_MODEL_OID OFFERING_MODEL_OID,
	FOW_OFFERING_STG.COMPOSITE_CODE COMPOSITE_CODE,
	FOW_OFFERING_STG.COMPOSITE_DELIVERY_METHOD COMPOSITE_DELIVERY_METHOD,
	FOW_OFFERING_STG.CREATED_BY CREATED_BY,
	FOW_OFFERING_STG.DATE_CREATED DATE_CREATED,
	FOW_OFFERING_STG.DEFAULT_SERVICE_LOOK DEFAULT_SERVICE_LOOK,
	FOW_OFFERING_STG.ENVELOPE_TYPE ENVELOPE_TYPE,
	FOW_OFFERING_STG.GROUP_CODE GROUP_CODE,
	FOW_OFFERING_STG.GROUP_DELIVERY_METHOD GROUP_DELIVERY_METHOD,
	FOW_OFFERING_STG.LAST_UPDATED LAST_UPDATED,
	FOW_OFFERING_STG.MODEL_ETHNICITY MODEL_ETHNICITY,
	FOW_OFFERING_STG.MODEL_GENDER MODEL_GENDER,
	FOW_OFFERING_STG.MODEL_GRADE MODEL_GRADE,
	FOW_OFFERING_STG.PRICE_PROGRAM_ID PRICE_PROGRAM_ID,
	FOW_OFFERING_STG.STAFF_PACKAGE STAFF_PACKAGE,
	FOW_OFFERING_STG.STYLE STYLE,
	FOW_OFFERING_STG.UPDATED_BY UPDATED_BY,
	FOW_OFFERING_STG.VISUAL_MERCH_ID VISUAL_MERCH_ID,
	FOW_OFFERING_STG.YEAR_BOOK_LOOK YEAR_BOOK_LOOK,
	FOW_OFFERING_STG.COMMISSION_TYPE COMMISSION_TYPE,
	FOW_OFFERING_STG.COMMISSION_RATE COMMISSION_RATE,
	FOW_OFFERING_STG.NO_TOUCH_YEARBOOK_LOOK NO_TOUCH_YEARBOOK_LOOK,
	FOW_OFFERING_STG.MINIMUM_REQUIREMENTS MINIMUM_REQUIREMENTS,
	FOW_OFFERING_STG.FLYER_ID FLYER_ID,
	FOW_OFFERING_STG.PART_NUMBER PART_NUMBER,
	FOW_OFFERING_STG.FLYER_SIZE FLYER_SIZE,
	FOW_OFFERING_STG.FLYER_STYLE FLYER_STYLE,
	FOW_OFFERING_STG.LAYOUT_CODE LAYOUT_CODE,
	FOW_OFFERING_STG.PAYMENT_MESSAGE_TEXT PAYMENT_MESSAGE_TEXT,
	FOW_OFFERING_STG.CREDIT_CARD_ALLOWED CREDIT_CARD_ALLOWED,
	FOW_OFFERING_STG.CHECK_PAYABLE_TO CHECK_PAYABLE_TO,
	FOW_OFFERING_STG.SMALL_NOTICE_TEXT SMALL_NOTICE_TEXT,
	FOW_OFFERING_STG.ADDITIONAL_INFO_TEXT ADDITIONAL_INFO_TEXT,
	FOW_OFFERING_STG.ADDITIONAL_INFO_PROOF_TEXT ADDITIONAL_INFO_PROOF_TEXT,
	FOW_OFFERING_STG.FAMILY_PLAN_VERBIAGE FAMILY_PLAN_VERBIAGE,
	FOW_OFFERING_STG.PAYMENT_DUE_TIMING_TEXT PAYMENT_DUE_TIMING_TEXT,
	FOW_OFFERING_STG.SPANISH_CAPTION_CODE1 SPANISH_CAPTION_CODE1,
	FOW_OFFERING_STG.SPANISH_CAPTION_CODE2 SPANISH_CAPTION_CODE2,
	FOW_OFFERING_STG.SPANISH_CAPTION_CODE3 SPANISH_CAPTION_CODE3,
	FOW_OFFERING_STG.INSERT_NO INSERT_NO,
	FOW_OFFERING_STG.INSERT_TYPE INSERT_TYPE,
	FOW_OFFERING_STG.MASCOT MASCOT,
	FOW_OFFERING_STG.PAYMENT_METHOD PAYMENT_METHOD,
	FOW_OFFERING_STG.POST_PIC_DAY_CUST_INQ_PHONE1 POST_PIC_DAY_CUST_INQ_PHONE1,
	FOW_OFFERING_STG.POST_PIC_DAY_CUST_INQ_PHONE2 POST_PIC_DAY_CUST_INQ_PHONE2,
	FOW_OFFERING_STG.PRE_PIC_DAY_CUST_INQ_PHONE1 PRE_PIC_DAY_CUST_INQ_PHONE1,
	FOW_OFFERING_STG.PRE_PIC_DAY_CUST_INQ_PHONE2 PRE_PIC_DAY_CUST_INQ_PHONE2,
	FOW_OFFERING_STG.THEME THEME,
	FOW_OFFERING_STG.CASUAL_CODE CASUAL_CODE,
	FOW_OFFERING_STG.CUSTOMER_SERVICE_EMAIL CUSTOMER_SERVICE_EMAIL,
	FOW_OFFERING_STG.CUSTOMER_SERVICE_HOURS CUSTOMER_SERVICE_HOURS,
	SYSDATE ODS_CREATE_DATE,
	SYSDATE ODS_MODIFY_DATE,
	SOURCE_SYSTEM.SOURCE_SYSTEM_OID SOURCE_SYSTEM_OID,

	'I' IND_UPDATE

from	ODS_STAGE_CA.FOW_OFFERING_STG   FOW_OFFERING_STG, ODS_STAGE_CA.FOW_OFFERING_XR   FOW_OFFERING_XR, ODS_STAGE_CA.APO_XR   APO_XR, ODS_STAGE_CA.FOW_OFFERING_MODEL_XR   OFFERING_MODEL_XR, ODS_OWN.SOURCE_SYSTEM   SOURCE_SYSTEM, ODS_OWN.APO   APO
where	(1=1)
 And (FOW_OFFERING_STG.ID=FOW_OFFERING_XR.ID (+))
AND (FOW_OFFERING_STG.APO_ID=APO_XR.FOW_SK_ID (+))
AND (FOW_OFFERING_STG.OFFERING_TEMPLATE_ID=OFFERING_MODEL_XR.ID (+))
AND (APO_XR.APO_OID=APO.APO_OID (+))
And (SOURCE_SYSTEM.SOURCE_SYSTEM_SHORT_NAME='FOW')
 And (FOW_OFFERING_STG.ODS_MODIFY_DATE >= TO_DATE(SUBSTR(:v_cdc_load_date, 1, 19), 'YYYY-MM-DD HH24:MI:SS')  -:v_cdc_oms_overlap)




) S
where NOT EXISTS 
	( select 1 from ODS_OWN.OFFERING T
	where	T.OFFERING_OID	= S.OFFERING_OID 
		 and ((T.APO_OID = S.APO_OID) or (T.APO_OID IS NULL and S.APO_OID IS NULL)) and
		((T.OFFERING_MODEL_OID = S.OFFERING_MODEL_OID) or (T.OFFERING_MODEL_OID IS NULL and S.OFFERING_MODEL_OID IS NULL)) and
		((T.COMPOSITE_CODE = S.COMPOSITE_CODE) or (T.COMPOSITE_CODE IS NULL and S.COMPOSITE_CODE IS NULL)) and
		((T.COMPOSITE_DELIVERY_METHOD = S.COMPOSITE_DELIVERY_METHOD) or (T.COMPOSITE_DELIVERY_METHOD IS NULL and S.COMPOSITE_DELIVERY_METHOD IS NULL)) and
		((T.CREATED_BY = S.CREATED_BY) or (T.CREATED_BY IS NULL and S.CREATED_BY IS NULL)) and
		((T.DATE_CREATED = S.DATE_CREATED) or (T.DATE_CREATED IS NULL and S.DATE_CREATED IS NULL)) and
		((T.DEFAULT_SERVICE_LOOK = S.DEFAULT_SERVICE_LOOK) or (T.DEFAULT_SERVICE_LOOK IS NULL and S.DEFAULT_SERVICE_LOOK IS NULL)) and
		((T.ENVELOPE_TYPE = S.ENVELOPE_TYPE) or (T.ENVELOPE_TYPE IS NULL and S.ENVELOPE_TYPE IS NULL)) and
		((T.GROUP_CODE = S.GROUP_CODE) or (T.GROUP_CODE IS NULL and S.GROUP_CODE IS NULL)) and
		((T.GROUP_DELIVERY_METHOD = S.GROUP_DELIVERY_METHOD) or (T.GROUP_DELIVERY_METHOD IS NULL and S.GROUP_DELIVERY_METHOD IS NULL)) and
		((T.LAST_UPDATED = S.LAST_UPDATED) or (T.LAST_UPDATED IS NULL and S.LAST_UPDATED IS NULL)) and
		((T.MODEL_ETHNICITY = S.MODEL_ETHNICITY) or (T.MODEL_ETHNICITY IS NULL and S.MODEL_ETHNICITY IS NULL)) and
		((T.MODEL_GENDER = S.MODEL_GENDER) or (T.MODEL_GENDER IS NULL and S.MODEL_GENDER IS NULL)) and
		((T.MODEL_GRADE = S.MODEL_GRADE) or (T.MODEL_GRADE IS NULL and S.MODEL_GRADE IS NULL)) and
		((T.PRICE_PROGRAM_ID = S.PRICE_PROGRAM_ID) or (T.PRICE_PROGRAM_ID IS NULL and S.PRICE_PROGRAM_ID IS NULL)) and
		((T.STAFF_PACKAGE = S.STAFF_PACKAGE) or (T.STAFF_PACKAGE IS NULL and S.STAFF_PACKAGE IS NULL)) and
		((T.STYLE = S.STYLE) or (T.STYLE IS NULL and S.STYLE IS NULL)) and
		((T.UPDATED_BY = S.UPDATED_BY) or (T.UPDATED_BY IS NULL and S.UPDATED_BY IS NULL)) and
		((T.VISUAL_MERCH_ID = S.VISUAL_MERCH_ID) or (T.VISUAL_MERCH_ID IS NULL and S.VISUAL_MERCH_ID IS NULL)) and
		((T.YEAR_BOOK_LOOK = S.YEAR_BOOK_LOOK) or (T.YEAR_BOOK_LOOK IS NULL and S.YEAR_BOOK_LOOK IS NULL)) and
		((T.COMMISSION_TYPE = S.COMMISSION_TYPE) or (T.COMMISSION_TYPE IS NULL and S.COMMISSION_TYPE IS NULL)) and
		((T.COMMISSION_RATE = S.COMMISSION_RATE) or (T.COMMISSION_RATE IS NULL and S.COMMISSION_RATE IS NULL)) and
		((T.NO_TOUCH_YEARBOOK_LOOK = S.NO_TOUCH_YEARBOOK_LOOK) or (T.NO_TOUCH_YEARBOOK_LOOK IS NULL and S.NO_TOUCH_YEARBOOK_LOOK IS NULL)) and
		((T.MINIMUM_REQUIREMENTS = S.MINIMUM_REQUIREMENTS) or (T.MINIMUM_REQUIREMENTS IS NULL and S.MINIMUM_REQUIREMENTS IS NULL)) and
		((T.FLYER_ID = S.FLYER_ID) or (T.FLYER_ID IS NULL and S.FLYER_ID IS NULL)) and
		((T.PART_NUMBER = S.PART_NUMBER) or (T.PART_NUMBER IS NULL and S.PART_NUMBER IS NULL)) and
		((T.FLYER_SIZE = S.FLYER_SIZE) or (T.FLYER_SIZE IS NULL and S.FLYER_SIZE IS NULL)) and
		((T.FLYER_STYLE = S.FLYER_STYLE) or (T.FLYER_STYLE IS NULL and S.FLYER_STYLE IS NULL)) and
		((T.LAYOUT_CODE = S.LAYOUT_CODE) or (T.LAYOUT_CODE IS NULL and S.LAYOUT_CODE IS NULL)) and
		((T.PAYMENT_MESSAGE_TEXT = S.PAYMENT_MESSAGE_TEXT) or (T.PAYMENT_MESSAGE_TEXT IS NULL and S.PAYMENT_MESSAGE_TEXT IS NULL)) and
		((T.CREDIT_CARD_ALLOWED = S.CREDIT_CARD_ALLOWED) or (T.CREDIT_CARD_ALLOWED IS NULL and S.CREDIT_CARD_ALLOWED IS NULL)) and
		((T.CHECK_PAYABLE_TO = S.CHECK_PAYABLE_TO) or (T.CHECK_PAYABLE_TO IS NULL and S.CHECK_PAYABLE_TO IS NULL)) and
		((T.SMALL_NOTICE_TEXT = S.SMALL_NOTICE_TEXT) or (T.SMALL_NOTICE_TEXT IS NULL and S.SMALL_NOTICE_TEXT IS NULL)) and
		((T.ADDITIONAL_INFO_TEXT = S.ADDITIONAL_INFO_TEXT) or (T.ADDITIONAL_INFO_TEXT IS NULL and S.ADDITIONAL_INFO_TEXT IS NULL)) and
		((T.ADDITIONAL_INFO_PROOF_TEXT = S.ADDITIONAL_INFO_PROOF_TEXT) or (T.ADDITIONAL_INFO_PROOF_TEXT IS NULL and S.ADDITIONAL_INFO_PROOF_TEXT IS NULL)) and
		((T.FAMILY_PLAN_VERBIAGE = S.FAMILY_PLAN_VERBIAGE) or (T.FAMILY_PLAN_VERBIAGE IS NULL and S.FAMILY_PLAN_VERBIAGE IS NULL)) and
		((T.PAYMENT_DUE_TIMING_TEXT = S.PAYMENT_DUE_TIMING_TEXT) or (T.PAYMENT_DUE_TIMING_TEXT IS NULL and S.PAYMENT_DUE_TIMING_TEXT IS NULL)) and
		((T.SPANISH_CAPTION_CODE1 = S.SPANISH_CAPTION_CODE1) or (T.SPANISH_CAPTION_CODE1 IS NULL and S.SPANISH_CAPTION_CODE1 IS NULL)) and
		((T.SPANISH_CAPTION_CODE2 = S.SPANISH_CAPTION_CODE2) or (T.SPANISH_CAPTION_CODE2 IS NULL and S.SPANISH_CAPTION_CODE2 IS NULL)) and
		((T.SPANISH_CAPTION_CODE3 = S.SPANISH_CAPTION_CODE3) or (T.SPANISH_CAPTION_CODE3 IS NULL and S.SPANISH_CAPTION_CODE3 IS NULL)) and
		((T.INSERT_NO = S.INSERT_NO) or (T.INSERT_NO IS NULL and S.INSERT_NO IS NULL)) and
		((T.INSERT_TYPE = S.INSERT_TYPE) or (T.INSERT_TYPE IS NULL and S.INSERT_TYPE IS NULL)) and
		((T.MASCOT = S.MASCOT) or (T.MASCOT IS NULL and S.MASCOT IS NULL)) and
		((T.PAYMENT_METHOD = S.PAYMENT_METHOD) or (T.PAYMENT_METHOD IS NULL and S.PAYMENT_METHOD IS NULL)) and
		((T.POST_PIC_DAY_CUST_INQ_PHONE1 = S.POST_PIC_DAY_CUST_INQ_PHONE1) or (T.POST_PIC_DAY_CUST_INQ_PHONE1 IS NULL and S.POST_PIC_DAY_CUST_INQ_PHONE1 IS NULL)) and
		((T.POST_PIC_DAY_CUST_INQ_PHONE2 = S.POST_PIC_DAY_CUST_INQ_PHONE2) or (T.POST_PIC_DAY_CUST_INQ_PHONE2 IS NULL and S.POST_PIC_DAY_CUST_INQ_PHONE2 IS NULL)) and
		((T.PRE_PIC_DAY_CUST_INQ_PHONE1 = S.PRE_PIC_DAY_CUST_INQ_PHONE1) or (T.PRE_PIC_DAY_CUST_INQ_PHONE1 IS NULL and S.PRE_PIC_DAY_CUST_INQ_PHONE1 IS NULL)) and
		((T.PRE_PIC_DAY_CUST_INQ_PHONE2 = S.PRE_PIC_DAY_CUST_INQ_PHONE2) or (T.PRE_PIC_DAY_CUST_INQ_PHONE2 IS NULL and S.PRE_PIC_DAY_CUST_INQ_PHONE2 IS NULL)) and
		((T.THEME = S.THEME) or (T.THEME IS NULL and S.THEME IS NULL)) and
		((T.CASUAL_CODE = S.CASUAL_CODE) or (T.CASUAL_CODE IS NULL and S.CASUAL_CODE IS NULL)) and
		((T.CUSTOMER_SERVICE_EMAIL = S.CUSTOMER_SERVICE_EMAIL) or (T.CUSTOMER_SERVICE_EMAIL IS NULL and S.CUSTOMER_SERVICE_EMAIL IS NULL)) and
		((T.CUSTOMER_SERVICE_HOURS = S.CUSTOMER_SERVICE_HOURS) or (T.CUSTOMER_SERVICE_HOURS IS NULL and S.CUSTOMER_SERVICE_HOURS IS NULL)) and
		((T.ODS_MODIFY_DATE = S.ODS_MODIFY_DATE) or (T.ODS_MODIFY_DATE IS NULL and S.ODS_MODIFY_DATE IS NULL)) and
		((T.SOURCE_SYSTEM_OID = S.SOURCE_SYSTEM_OID) or (T.SOURCE_SYSTEM_OID IS NULL and S.SOURCE_SYSTEM_OID IS NULL))
        )

  
  

  

 


&


/*-----------------------------------------------*/
/* TASK No. 22 */
/* Create Index on flow table */

create index	RAX_APP_USER.I$_OFFERING_IDX
on		RAX_APP_USER.I$_OFFERING (OFFERING_OID)
NOLOGGING

&


/*-----------------------------------------------*/
/* TASK No. 23 */
/* Analyze integration table */



begin
    dbms_stats.gather_table_stats(
	ownname => 'RAX_APP_USER',
	tabname => 'I$_OFFERING',
	estimate_percent => dbms_stats.auto_sample_size
    );
end;



&


/*-----------------------------------------------*/
/* TASK No. 24 */
/* create check table */


BEGIN  
   EXECUTE IMMEDIATE 'create table RAX_APP_USER.SNP_CHECK_TAB
						(
							CATALOG_NAME	VARCHAR2(100 CHAR) NULL ,
							SCHEMA_NAME	VARCHAR2(100 CHAR) NULL ,
							RESOURCE_NAME	VARCHAR2(100 CHAR) NULL,
							FULL_RES_NAME	VARCHAR2(100 CHAR) NULL,
							ERR_TYPE		VARCHAR2(1 CHAR) NULL,
							ERR_MESS		VARCHAR2(250 CHAR) NULL ,
							CHECK_DATE	DATE NULL,
							ORIGIN		VARCHAR2(100 CHAR) NULL,
							CONS_NAME	VARCHAR2(35 CHAR) NULL,
							CONS_TYPE		VARCHAR2(2 CHAR) NULL,
							ERR_COUNT		NUMBER(10) NULL
						)';  
EXCEPTION  
   WHEN OTHERS THEN  
      IF SQLCODE != -955 THEN  
         RAISE;  
      END IF;  
END;
	

&


/*-----------------------------------------------*/
/* TASK No. 25 */
/* delete previous check sum */

delete from	RAX_APP_USER.SNP_CHECK_TAB
where	SCHEMA_NAME	= 'ODS_OWN'
and	ORIGIN 		= '(1525001)ODS_Project.LOAD_FOW_OFFERING_INT'
and	ERR_TYPE 		= 'F'


&


/*-----------------------------------------------*/
/* TASK No. 26 */
/* create error table */

BEGIN  
   EXECUTE IMMEDIATE 'create table RAX_APP_USER.E$_OFFERING
						(
							ODI_ROW_ID 		UROWID,
							ODI_ERR_TYPE		VARCHAR2(1 CHAR) NULL, 
							ODI_ERR_MESS		VARCHAR2(250 CHAR) NULL,
							ODI_CHECK_DATE	DATE NULL, 
							OFFERING_OID	NUMBER NULL,
							APO_OID	NUMBER NULL,
							OFFERING_MODEL_OID	NUMBER NULL,
							COMPOSITE_CODE	VARCHAR2(255) NULL,
							COMPOSITE_DELIVERY_METHOD	VARCHAR2(255) NULL,
							CREATED_BY	VARCHAR2(255) NULL,
							DATE_CREATED	DATE NULL,
							DEFAULT_SERVICE_LOOK	VARCHAR2(255) NULL,
							ENVELOPE_TYPE	VARCHAR2(255) NULL,
							GROUP_CODE	VARCHAR2(255) NULL,
							GROUP_DELIVERY_METHOD	VARCHAR2(255) NULL,
							LAST_UPDATED	DATE NULL,
							MODEL_ETHNICITY	VARCHAR2(255) NULL,
							MODEL_GENDER	VARCHAR2(255) NULL,
							MODEL_GRADE	VARCHAR2(255) NULL,
							PRICE_PROGRAM_ID	VARCHAR2(255) NULL,
							STAFF_PACKAGE	NUMBER NULL,
							STYLE	VARCHAR2(255) NULL,
							UPDATED_BY	VARCHAR2(255) NULL,
							VISUAL_MERCH_ID	VARCHAR2(255) NULL,
							YEAR_BOOK_LOOK	VARCHAR2(255) NULL,
							COMMISSION_TYPE	VARCHAR2(255) NULL,
							COMMISSION_RATE	NUMBER NULL,
							NO_TOUCH_YEARBOOK_LOOK	VARCHAR2(255) NULL,
							MINIMUM_REQUIREMENTS	NUMBER NULL,
							FLYER_ID	VARCHAR2(255) NULL,
							PART_NUMBER	VARCHAR2(255) NULL,
							FLYER_SIZE	VARCHAR2(255) NULL,
							FLYER_STYLE	VARCHAR2(255) NULL,
							LAYOUT_CODE	VARCHAR2(255) NULL,
							PAYMENT_MESSAGE_TEXT	VARCHAR2(255) NULL,
							CREDIT_CARD_ALLOWED	NUMBER NULL,
							CHECK_PAYABLE_TO	VARCHAR2(255) NULL,
							SMALL_NOTICE_TEXT	VARCHAR2(255) NULL,
							ADDITIONAL_INFO_TEXT	VARCHAR2(255) NULL,
							ADDITIONAL_INFO_PROOF_TEXT	VARCHAR2(255) NULL,
							FAMILY_PLAN_VERBIAGE	VARCHAR2(255) NULL,
							PAYMENT_DUE_TIMING_TEXT	VARCHAR2(255) NULL,
							SPANISH_CAPTION_CODE1	VARCHAR2(255) NULL,
							SPANISH_CAPTION_CODE2	VARCHAR2(255) NULL,
							SPANISH_CAPTION_CODE3	VARCHAR2(255) NULL,
							INSERT_DESC	VARCHAR2(255) NULL,
							INSERT_NO	VARCHAR2(255) NULL,
							INSERT_TYPE	VARCHAR2(255) NULL,
							MASCOT	VARCHAR2(255) NULL,
							PAYMENT_METHOD	VARCHAR2(255) NULL,
							POST_PIC_DAY_CUST_INQ_PHONE1	VARCHAR2(255) NULL,
							POST_PIC_DAY_CUST_INQ_PHONE2	VARCHAR2(255) NULL,
							PRE_PIC_DAY_CUST_INQ_PHONE1	VARCHAR2(255) NULL,
							PRE_PIC_DAY_CUST_INQ_PHONE2	VARCHAR2(255) NULL,
							THEME	VARCHAR2(255) NULL,
							CASUAL_CODE	VARCHAR2(255) NULL,
							CUSTOMER_SERVICE_EMAIL	VARCHAR2(255) NULL,
							CUSTOMER_SERVICE_HOURS	VARCHAR2(255) NULL,
							ODS_CREATE_DATE	DATE NULL,
							ODS_MODIFY_DATE	DATE NULL,
							SOURCE_SYSTEM_OID	NUMBER NULL,
							ODI_ORIGIN		VARCHAR2(100 CHAR) NULL,
							ODI_CONS_NAME	VARCHAR2(35 CHAR) NULL,
							ODI_CONS_TYPE		VARCHAR2(2 CHAR) NULL,
							ODI_PK			VARCHAR2(32 CHAR) PRIMARY KEY,
							ODI_SESS_NO		VARCHAR2(19 CHAR)
						)';  
EXCEPTION  
   WHEN OTHERS THEN  
      IF SQLCODE != -955 THEN  
         RAISE;  
      END IF;  
END;


&


/*-----------------------------------------------*/
/* TASK No. 27 */
/* delete previous errors */

delete from 	RAX_APP_USER.E$_OFFERING
where	(ODI_ERR_TYPE = 'S'	and 'F' = 'S')
or	(ODI_ERR_TYPE = 'F'	and ODI_ORIGIN = '(1525001)ODS_Project.LOAD_FOW_OFFERING_INT')


&


/*-----------------------------------------------*/
/* TASK No. 28 */
/* Create index on PK */

 
/* FLOW CONTROL CREATE THE iNDEX ON THE I$TABLE */
BEGIN  
   EXECUTE IMMEDIATE 'create index 	RAX_APP_USER.I$_OFFERING_IDX on	RAX_APP_USER.I$_OFFERING (OFFERING_OID)';  
EXCEPTION  
   WHEN OTHERS THEN  
      IF SQLCODE != -955 THEN  
         RAISE;  
      END IF;  
END;


&


/*-----------------------------------------------*/
/* TASK No. 29 */
/* insert PK errors */

insert into RAX_APP_USER.E$_OFFERING
(
	ODI_PK,
	ODI_SESS_NO,
	ODI_ROW_ID,
	ODI_ERR_TYPE,
	ODI_ERR_MESS,
	ODI_ORIGIN,
	ODI_CHECK_DATE,
	ODI_CONS_NAME,
	ODI_CONS_TYPE,
	OFFERING_OID,
	APO_OID,
	OFFERING_MODEL_OID,
	COMPOSITE_CODE,
	COMPOSITE_DELIVERY_METHOD,
	CREATED_BY,
	DATE_CREATED,
	DEFAULT_SERVICE_LOOK,
	ENVELOPE_TYPE,
	GROUP_CODE,
	GROUP_DELIVERY_METHOD,
	LAST_UPDATED,
	MODEL_ETHNICITY,
	MODEL_GENDER,
	MODEL_GRADE,
	PRICE_PROGRAM_ID,
	STAFF_PACKAGE,
	STYLE,
	UPDATED_BY,
	VISUAL_MERCH_ID,
	YEAR_BOOK_LOOK,
	COMMISSION_TYPE,
	COMMISSION_RATE,
	NO_TOUCH_YEARBOOK_LOOK,
	MINIMUM_REQUIREMENTS,
	FLYER_ID,
	PART_NUMBER,
	FLYER_SIZE,
	FLYER_STYLE,
	LAYOUT_CODE,
	PAYMENT_MESSAGE_TEXT,
	CREDIT_CARD_ALLOWED,
	CHECK_PAYABLE_TO,
	SMALL_NOTICE_TEXT,
	ADDITIONAL_INFO_TEXT,
	ADDITIONAL_INFO_PROOF_TEXT,
	FAMILY_PLAN_VERBIAGE,
	PAYMENT_DUE_TIMING_TEXT,
	SPANISH_CAPTION_CODE1,
	SPANISH_CAPTION_CODE2,
	SPANISH_CAPTION_CODE3,
	INSERT_NO,
	INSERT_TYPE,
	MASCOT,
	PAYMENT_METHOD,
	POST_PIC_DAY_CUST_INQ_PHONE1,
	POST_PIC_DAY_CUST_INQ_PHONE2,
	PRE_PIC_DAY_CUST_INQ_PHONE1,
	PRE_PIC_DAY_CUST_INQ_PHONE2,
	THEME,
	CASUAL_CODE,
	CUSTOMER_SERVICE_EMAIL,
	CUSTOMER_SERVICE_HOURS,
	ODS_CREATE_DATE,
	ODS_MODIFY_DATE,
	SOURCE_SYSTEM_OID
)
select	SYS_GUID(),
	:v_sess_no, 
	rowid,
	'F', 
	'ODI-15064: The primary key OFFERING_PK is not unique.',
	'(1525001)ODS_Project.LOAD_FOW_OFFERING_INT',
	sysdate,
	'OFFERING_PK',
	'PK',	
	OFFERING.OFFERING_OID,
	OFFERING.APO_OID,
	OFFERING.OFFERING_MODEL_OID,
	OFFERING.COMPOSITE_CODE,
	OFFERING.COMPOSITE_DELIVERY_METHOD,
	OFFERING.CREATED_BY,
	OFFERING.DATE_CREATED,
	OFFERING.DEFAULT_SERVICE_LOOK,
	OFFERING.ENVELOPE_TYPE,
	OFFERING.GROUP_CODE,
	OFFERING.GROUP_DELIVERY_METHOD,
	OFFERING.LAST_UPDATED,
	OFFERING.MODEL_ETHNICITY,
	OFFERING.MODEL_GENDER,
	OFFERING.MODEL_GRADE,
	OFFERING.PRICE_PROGRAM_ID,
	OFFERING.STAFF_PACKAGE,
	OFFERING.STYLE,
	OFFERING.UPDATED_BY,
	OFFERING.VISUAL_MERCH_ID,
	OFFERING.YEAR_BOOK_LOOK,
	OFFERING.COMMISSION_TYPE,
	OFFERING.COMMISSION_RATE,
	OFFERING.NO_TOUCH_YEARBOOK_LOOK,
	OFFERING.MINIMUM_REQUIREMENTS,
	OFFERING.FLYER_ID,
	OFFERING.PART_NUMBER,
	OFFERING.FLYER_SIZE,
	OFFERING.FLYER_STYLE,
	OFFERING.LAYOUT_CODE,
	OFFERING.PAYMENT_MESSAGE_TEXT,
	OFFERING.CREDIT_CARD_ALLOWED,
	OFFERING.CHECK_PAYABLE_TO,
	OFFERING.SMALL_NOTICE_TEXT,
	OFFERING.ADDITIONAL_INFO_TEXT,
	OFFERING.ADDITIONAL_INFO_PROOF_TEXT,
	OFFERING.FAMILY_PLAN_VERBIAGE,
	OFFERING.PAYMENT_DUE_TIMING_TEXT,
	OFFERING.SPANISH_CAPTION_CODE1,
	OFFERING.SPANISH_CAPTION_CODE2,
	OFFERING.SPANISH_CAPTION_CODE3,
	OFFERING.INSERT_NO,
	OFFERING.INSERT_TYPE,
	OFFERING.MASCOT,
	OFFERING.PAYMENT_METHOD,
	OFFERING.POST_PIC_DAY_CUST_INQ_PHONE1,
	OFFERING.POST_PIC_DAY_CUST_INQ_PHONE2,
	OFFERING.PRE_PIC_DAY_CUST_INQ_PHONE1,
	OFFERING.PRE_PIC_DAY_CUST_INQ_PHONE2,
	OFFERING.THEME,
	OFFERING.CASUAL_CODE,
	OFFERING.CUSTOMER_SERVICE_EMAIL,
	OFFERING.CUSTOMER_SERVICE_HOURS,
	OFFERING.ODS_CREATE_DATE,
	OFFERING.ODS_MODIFY_DATE,
	OFFERING.SOURCE_SYSTEM_OID
from	RAX_APP_USER.I$_OFFERING   OFFERING
where	exists  (
		select	SUB.OFFERING_OID
		from 	RAX_APP_USER.I$_OFFERING SUB
		where 	SUB.OFFERING_OID=OFFERING.OFFERING_OID
		group by 	SUB.OFFERING_OID
		having 	count(1) > 1
		)



&


/*-----------------------------------------------*/
/* TASK No. 30 */
/* insert Not Null errors */

insert into RAX_APP_USER.E$_OFFERING
(
	ODI_PK,
	ODI_SESS_NO,
	ODI_ROW_ID,
	ODI_ERR_TYPE,
	ODI_ERR_MESS,
	ODI_CHECK_DATE,
	ODI_ORIGIN,
	ODI_CONS_NAME,
	ODI_CONS_TYPE,
	OFFERING_OID,
	APO_OID,
	OFFERING_MODEL_OID,
	COMPOSITE_CODE,
	COMPOSITE_DELIVERY_METHOD,
	CREATED_BY,
	DATE_CREATED,
	DEFAULT_SERVICE_LOOK,
	ENVELOPE_TYPE,
	GROUP_CODE,
	GROUP_DELIVERY_METHOD,
	LAST_UPDATED,
	MODEL_ETHNICITY,
	MODEL_GENDER,
	MODEL_GRADE,
	PRICE_PROGRAM_ID,
	STAFF_PACKAGE,
	STYLE,
	UPDATED_BY,
	VISUAL_MERCH_ID,
	YEAR_BOOK_LOOK,
	COMMISSION_TYPE,
	COMMISSION_RATE,
	NO_TOUCH_YEARBOOK_LOOK,
	MINIMUM_REQUIREMENTS,
	FLYER_ID,
	PART_NUMBER,
	FLYER_SIZE,
	FLYER_STYLE,
	LAYOUT_CODE,
	PAYMENT_MESSAGE_TEXT,
	CREDIT_CARD_ALLOWED,
	CHECK_PAYABLE_TO,
	SMALL_NOTICE_TEXT,
	ADDITIONAL_INFO_TEXT,
	ADDITIONAL_INFO_PROOF_TEXT,
	FAMILY_PLAN_VERBIAGE,
	PAYMENT_DUE_TIMING_TEXT,
	SPANISH_CAPTION_CODE1,
	SPANISH_CAPTION_CODE2,
	SPANISH_CAPTION_CODE3,
	INSERT_NO,
	INSERT_TYPE,
	MASCOT,
	PAYMENT_METHOD,
	POST_PIC_DAY_CUST_INQ_PHONE1,
	POST_PIC_DAY_CUST_INQ_PHONE2,
	PRE_PIC_DAY_CUST_INQ_PHONE1,
	PRE_PIC_DAY_CUST_INQ_PHONE2,
	THEME,
	CASUAL_CODE,
	CUSTOMER_SERVICE_EMAIL,
	CUSTOMER_SERVICE_HOURS,
	ODS_CREATE_DATE,
	ODS_MODIFY_DATE,
	SOURCE_SYSTEM_OID
)
select
	SYS_GUID(),
	:v_sess_no, 
	rowid,
	'F', 
	'ODI-15066: The column OFFERING_OID cannot be null.',
	sysdate,
	'(1525001)ODS_Project.LOAD_FOW_OFFERING_INT',
	'OFFERING_OID',
	'NN',	
	OFFERING_OID,
	APO_OID,
	OFFERING_MODEL_OID,
	COMPOSITE_CODE,
	COMPOSITE_DELIVERY_METHOD,
	CREATED_BY,
	DATE_CREATED,
	DEFAULT_SERVICE_LOOK,
	ENVELOPE_TYPE,
	GROUP_CODE,
	GROUP_DELIVERY_METHOD,
	LAST_UPDATED,
	MODEL_ETHNICITY,
	MODEL_GENDER,
	MODEL_GRADE,
	PRICE_PROGRAM_ID,
	STAFF_PACKAGE,
	STYLE,
	UPDATED_BY,
	VISUAL_MERCH_ID,
	YEAR_BOOK_LOOK,
	COMMISSION_TYPE,
	COMMISSION_RATE,
	NO_TOUCH_YEARBOOK_LOOK,
	MINIMUM_REQUIREMENTS,
	FLYER_ID,
	PART_NUMBER,
	FLYER_SIZE,
	FLYER_STYLE,
	LAYOUT_CODE,
	PAYMENT_MESSAGE_TEXT,
	CREDIT_CARD_ALLOWED,
	CHECK_PAYABLE_TO,
	SMALL_NOTICE_TEXT,
	ADDITIONAL_INFO_TEXT,
	ADDITIONAL_INFO_PROOF_TEXT,
	FAMILY_PLAN_VERBIAGE,
	PAYMENT_DUE_TIMING_TEXT,
	SPANISH_CAPTION_CODE1,
	SPANISH_CAPTION_CODE2,
	SPANISH_CAPTION_CODE3,
	INSERT_NO,
	INSERT_TYPE,
	MASCOT,
	PAYMENT_METHOD,
	POST_PIC_DAY_CUST_INQ_PHONE1,
	POST_PIC_DAY_CUST_INQ_PHONE2,
	PRE_PIC_DAY_CUST_INQ_PHONE1,
	PRE_PIC_DAY_CUST_INQ_PHONE2,
	THEME,
	CASUAL_CODE,
	CUSTOMER_SERVICE_EMAIL,
	CUSTOMER_SERVICE_HOURS,
	ODS_CREATE_DATE,
	ODS_MODIFY_DATE,
	SOURCE_SYSTEM_OID
from	RAX_APP_USER.I$_OFFERING
where	OFFERING_OID is null



&


/*-----------------------------------------------*/
/* TASK No. 31 */
/* insert Not Null errors */

insert into RAX_APP_USER.E$_OFFERING
(
	ODI_PK,
	ODI_SESS_NO,
	ODI_ROW_ID,
	ODI_ERR_TYPE,
	ODI_ERR_MESS,
	ODI_CHECK_DATE,
	ODI_ORIGIN,
	ODI_CONS_NAME,
	ODI_CONS_TYPE,
	OFFERING_OID,
	APO_OID,
	OFFERING_MODEL_OID,
	COMPOSITE_CODE,
	COMPOSITE_DELIVERY_METHOD,
	CREATED_BY,
	DATE_CREATED,
	DEFAULT_SERVICE_LOOK,
	ENVELOPE_TYPE,
	GROUP_CODE,
	GROUP_DELIVERY_METHOD,
	LAST_UPDATED,
	MODEL_ETHNICITY,
	MODEL_GENDER,
	MODEL_GRADE,
	PRICE_PROGRAM_ID,
	STAFF_PACKAGE,
	STYLE,
	UPDATED_BY,
	VISUAL_MERCH_ID,
	YEAR_BOOK_LOOK,
	COMMISSION_TYPE,
	COMMISSION_RATE,
	NO_TOUCH_YEARBOOK_LOOK,
	MINIMUM_REQUIREMENTS,
	FLYER_ID,
	PART_NUMBER,
	FLYER_SIZE,
	FLYER_STYLE,
	LAYOUT_CODE,
	PAYMENT_MESSAGE_TEXT,
	CREDIT_CARD_ALLOWED,
	CHECK_PAYABLE_TO,
	SMALL_NOTICE_TEXT,
	ADDITIONAL_INFO_TEXT,
	ADDITIONAL_INFO_PROOF_TEXT,
	FAMILY_PLAN_VERBIAGE,
	PAYMENT_DUE_TIMING_TEXT,
	SPANISH_CAPTION_CODE1,
	SPANISH_CAPTION_CODE2,
	SPANISH_CAPTION_CODE3,
	INSERT_NO,
	INSERT_TYPE,
	MASCOT,
	PAYMENT_METHOD,
	POST_PIC_DAY_CUST_INQ_PHONE1,
	POST_PIC_DAY_CUST_INQ_PHONE2,
	PRE_PIC_DAY_CUST_INQ_PHONE1,
	PRE_PIC_DAY_CUST_INQ_PHONE2,
	THEME,
	CASUAL_CODE,
	CUSTOMER_SERVICE_EMAIL,
	CUSTOMER_SERVICE_HOURS,
	ODS_CREATE_DATE,
	ODS_MODIFY_DATE,
	SOURCE_SYSTEM_OID
)
select
	SYS_GUID(),
	:v_sess_no, 
	rowid,
	'F', 
	'ODI-15066: The column APO_OID cannot be null.',
	sysdate,
	'(1525001)ODS_Project.LOAD_FOW_OFFERING_INT',
	'APO_OID',
	'NN',	
	OFFERING_OID,
	APO_OID,
	OFFERING_MODEL_OID,
	COMPOSITE_CODE,
	COMPOSITE_DELIVERY_METHOD,
	CREATED_BY,
	DATE_CREATED,
	DEFAULT_SERVICE_LOOK,
	ENVELOPE_TYPE,
	GROUP_CODE,
	GROUP_DELIVERY_METHOD,
	LAST_UPDATED,
	MODEL_ETHNICITY,
	MODEL_GENDER,
	MODEL_GRADE,
	PRICE_PROGRAM_ID,
	STAFF_PACKAGE,
	STYLE,
	UPDATED_BY,
	VISUAL_MERCH_ID,
	YEAR_BOOK_LOOK,
	COMMISSION_TYPE,
	COMMISSION_RATE,
	NO_TOUCH_YEARBOOK_LOOK,
	MINIMUM_REQUIREMENTS,
	FLYER_ID,
	PART_NUMBER,
	FLYER_SIZE,
	FLYER_STYLE,
	LAYOUT_CODE,
	PAYMENT_MESSAGE_TEXT,
	CREDIT_CARD_ALLOWED,
	CHECK_PAYABLE_TO,
	SMALL_NOTICE_TEXT,
	ADDITIONAL_INFO_TEXT,
	ADDITIONAL_INFO_PROOF_TEXT,
	FAMILY_PLAN_VERBIAGE,
	PAYMENT_DUE_TIMING_TEXT,
	SPANISH_CAPTION_CODE1,
	SPANISH_CAPTION_CODE2,
	SPANISH_CAPTION_CODE3,
	INSERT_NO,
	INSERT_TYPE,
	MASCOT,
	PAYMENT_METHOD,
	POST_PIC_DAY_CUST_INQ_PHONE1,
	POST_PIC_DAY_CUST_INQ_PHONE2,
	PRE_PIC_DAY_CUST_INQ_PHONE1,
	PRE_PIC_DAY_CUST_INQ_PHONE2,
	THEME,
	CASUAL_CODE,
	CUSTOMER_SERVICE_EMAIL,
	CUSTOMER_SERVICE_HOURS,
	ODS_CREATE_DATE,
	ODS_MODIFY_DATE,
	SOURCE_SYSTEM_OID
from	RAX_APP_USER.I$_OFFERING
where	APO_OID is null



&


/*-----------------------------------------------*/
/* TASK No. 32 */
/* create index on error table */

 
/* FLOW CONTROL CREATE INDEX ON THE E$TABLE */
BEGIN  
   EXECUTE IMMEDIATE 'create index 	RAX_APP_USER.E$_OFFERING_IDX on	RAX_APP_USER.E$_OFFERING (ODI_ROW_ID)';  
EXCEPTION  
   WHEN OTHERS THEN  
      IF SQLCODE != -955 THEN  
         RAISE;  
      END IF;  
END;


&


/*-----------------------------------------------*/
/* TASK No. 33 */
/* delete errors from controlled table */

delete from	RAX_APP_USER.I$_OFFERING  T
where	exists 	(
		select	1
		from	RAX_APP_USER.E$_OFFERING E
		where ODI_SESS_NO = :v_sess_no
		and T.rowid = E.ODI_ROW_ID
		)


&


/*-----------------------------------------------*/
/* TASK No. 34 */
/* insert check sum into check table */

insert into RAX_APP_USER.SNP_CHECK_TAB
(
	SCHEMA_NAME,
	RESOURCE_NAME,
	FULL_RES_NAME,
	ERR_TYPE,
	ERR_MESS,
	CHECK_DATE,
	ORIGIN,
	CONS_NAME,
	CONS_TYPE,
	ERR_COUNT
)
select	
	'ODS_OWN',
	'OFFERING',
	'ODS_OWN.OFFERING',
	E.ODI_ERR_TYPE,
	E.ODI_ERR_MESS,
	E.ODI_CHECK_DATE,
	E.ODI_ORIGIN,
	E.ODI_CONS_NAME,
	E.ODI_CONS_TYPE,
	count(1) 
from	RAX_APP_USER.E$_OFFERING E
where	E.ODI_ERR_TYPE	= 'F'
and	E.ODI_ORIGIN 	= '(1525001)ODS_Project.LOAD_FOW_OFFERING_INT'
group by	E.ODI_ERR_TYPE,
	E.ODI_ERR_MESS,
	E.ODI_CHECK_DATE,
	E.ODI_ORIGIN,
	E.ODI_CONS_NAME,
	E.ODI_CONS_TYPE


&


/*-----------------------------------------------*/
/* TASK No. 35 */
/* Flag rows for update */

/* DETECTION_STRATEGY = NOT_EXISTS */


update	RAX_APP_USER.I$_OFFERING
set	IND_UPDATE = 'U'
where	(OFFERING_OID)
	in	(
		select	OFFERING_OID
		from	ODS_OWN.OFFERING
		)



&


/*-----------------------------------------------*/
/* TASK No. 36 */
/* Flag useless rows */

/* DETECTION_STRATEGY = NOT_EXISTS */

/* Command skipped due to chosen DETECTION_STRATEGY */



/*-----------------------------------------------*/
/* TASK No. 37 */
/* Update existing rows */

/* DETECTION_STRATEGY = NOT_EXISTS */
update	ODS_OWN.OFFERING T
set 	
	(
	T.APO_OID,
	T.OFFERING_MODEL_OID,
	T.COMPOSITE_CODE,
	T.COMPOSITE_DELIVERY_METHOD,
	T.CREATED_BY,
	T.DATE_CREATED,
	T.DEFAULT_SERVICE_LOOK,
	T.ENVELOPE_TYPE,
	T.GROUP_CODE,
	T.GROUP_DELIVERY_METHOD,
	T.LAST_UPDATED,
	T.MODEL_ETHNICITY,
	T.MODEL_GENDER,
	T.MODEL_GRADE,
	T.PRICE_PROGRAM_ID,
	T.STAFF_PACKAGE,
	T.STYLE,
	T.UPDATED_BY,
	T.VISUAL_MERCH_ID,
	T.YEAR_BOOK_LOOK,
	T.COMMISSION_TYPE,
	T.COMMISSION_RATE,
	T.NO_TOUCH_YEARBOOK_LOOK,
	T.MINIMUM_REQUIREMENTS,
	T.FLYER_ID,
	T.PART_NUMBER,
	T.FLYER_SIZE,
	T.FLYER_STYLE,
	T.LAYOUT_CODE,
	T.PAYMENT_MESSAGE_TEXT,
	T.CREDIT_CARD_ALLOWED,
	T.CHECK_PAYABLE_TO,
	T.SMALL_NOTICE_TEXT,
	T.ADDITIONAL_INFO_TEXT,
	T.ADDITIONAL_INFO_PROOF_TEXT,
	T.FAMILY_PLAN_VERBIAGE,
	T.PAYMENT_DUE_TIMING_TEXT,
	T.SPANISH_CAPTION_CODE1,
	T.SPANISH_CAPTION_CODE2,
	T.SPANISH_CAPTION_CODE3,
	T.INSERT_NO,
	T.INSERT_TYPE,
	T.MASCOT,
	T.PAYMENT_METHOD,
	T.POST_PIC_DAY_CUST_INQ_PHONE1,
	T.POST_PIC_DAY_CUST_INQ_PHONE2,
	T.PRE_PIC_DAY_CUST_INQ_PHONE1,
	T.PRE_PIC_DAY_CUST_INQ_PHONE2,
	T.THEME,
	T.CASUAL_CODE,
	T.CUSTOMER_SERVICE_EMAIL,
	T.CUSTOMER_SERVICE_HOURS,
	T.ODS_MODIFY_DATE,
	T.SOURCE_SYSTEM_OID
	) =
		(
		select	S.APO_OID,
			S.OFFERING_MODEL_OID,
			S.COMPOSITE_CODE,
			S.COMPOSITE_DELIVERY_METHOD,
			S.CREATED_BY,
			S.DATE_CREATED,
			S.DEFAULT_SERVICE_LOOK,
			S.ENVELOPE_TYPE,
			S.GROUP_CODE,
			S.GROUP_DELIVERY_METHOD,
			S.LAST_UPDATED,
			S.MODEL_ETHNICITY,
			S.MODEL_GENDER,
			S.MODEL_GRADE,
			S.PRICE_PROGRAM_ID,
			S.STAFF_PACKAGE,
			S.STYLE,
			S.UPDATED_BY,
			S.VISUAL_MERCH_ID,
			S.YEAR_BOOK_LOOK,
			S.COMMISSION_TYPE,
			S.COMMISSION_RATE,
			S.NO_TOUCH_YEARBOOK_LOOK,
			S.MINIMUM_REQUIREMENTS,
			S.FLYER_ID,
			S.PART_NUMBER,
			S.FLYER_SIZE,
			S.FLYER_STYLE,
			S.LAYOUT_CODE,
			S.PAYMENT_MESSAGE_TEXT,
			S.CREDIT_CARD_ALLOWED,
			S.CHECK_PAYABLE_TO,
			S.SMALL_NOTICE_TEXT,
			S.ADDITIONAL_INFO_TEXT,
			S.ADDITIONAL_INFO_PROOF_TEXT,
			S.FAMILY_PLAN_VERBIAGE,
			S.PAYMENT_DUE_TIMING_TEXT,
			S.SPANISH_CAPTION_CODE1,
			S.SPANISH_CAPTION_CODE2,
			S.SPANISH_CAPTION_CODE3,
			S.INSERT_NO,
			S.INSERT_TYPE,
			S.MASCOT,
			S.PAYMENT_METHOD,
			S.POST_PIC_DAY_CUST_INQ_PHONE1,
			S.POST_PIC_DAY_CUST_INQ_PHONE2,
			S.PRE_PIC_DAY_CUST_INQ_PHONE1,
			S.PRE_PIC_DAY_CUST_INQ_PHONE2,
			S.THEME,
			S.CASUAL_CODE,
			S.CUSTOMER_SERVICE_EMAIL,
			S.CUSTOMER_SERVICE_HOURS,
			S.ODS_MODIFY_DATE,
			S.SOURCE_SYSTEM_OID
		from	RAX_APP_USER.I$_OFFERING S
		where	T.OFFERING_OID	=S.OFFERING_OID
	    	 )
	

where	(OFFERING_OID)
	in	(
		select	OFFERING_OID
		from	RAX_APP_USER.I$_OFFERING
		where	IND_UPDATE = 'U'
		)




&


/*-----------------------------------------------*/
/* TASK No. 38 */
/* Insert new rows */

/* DETECTION_STRATEGY = NOT_EXISTS */
insert into 	ODS_OWN.OFFERING T
	(
	OFFERING_OID,
	APO_OID,
	OFFERING_MODEL_OID,
	COMPOSITE_CODE,
	COMPOSITE_DELIVERY_METHOD,
	CREATED_BY,
	DATE_CREATED,
	DEFAULT_SERVICE_LOOK,
	ENVELOPE_TYPE,
	GROUP_CODE,
	GROUP_DELIVERY_METHOD,
	LAST_UPDATED,
	MODEL_ETHNICITY,
	MODEL_GENDER,
	MODEL_GRADE,
	PRICE_PROGRAM_ID,
	STAFF_PACKAGE,
	STYLE,
	UPDATED_BY,
	VISUAL_MERCH_ID,
	YEAR_BOOK_LOOK,
	COMMISSION_TYPE,
	COMMISSION_RATE,
	NO_TOUCH_YEARBOOK_LOOK,
	MINIMUM_REQUIREMENTS,
	FLYER_ID,
	PART_NUMBER,
	FLYER_SIZE,
	FLYER_STYLE,
	LAYOUT_CODE,
	PAYMENT_MESSAGE_TEXT,
	CREDIT_CARD_ALLOWED,
	CHECK_PAYABLE_TO,
	SMALL_NOTICE_TEXT,
	ADDITIONAL_INFO_TEXT,
	ADDITIONAL_INFO_PROOF_TEXT,
	FAMILY_PLAN_VERBIAGE,
	PAYMENT_DUE_TIMING_TEXT,
	SPANISH_CAPTION_CODE1,
	SPANISH_CAPTION_CODE2,
	SPANISH_CAPTION_CODE3,
	INSERT_NO,
	INSERT_TYPE,
	MASCOT,
	PAYMENT_METHOD,
	POST_PIC_DAY_CUST_INQ_PHONE1,
	POST_PIC_DAY_CUST_INQ_PHONE2,
	PRE_PIC_DAY_CUST_INQ_PHONE1,
	PRE_PIC_DAY_CUST_INQ_PHONE2,
	THEME,
	CASUAL_CODE,
	CUSTOMER_SERVICE_EMAIL,
	CUSTOMER_SERVICE_HOURS,
	ODS_CREATE_DATE,
	ODS_MODIFY_DATE,
	SOURCE_SYSTEM_OID
	
	)
select 	OFFERING_OID,
	APO_OID,
	OFFERING_MODEL_OID,
	COMPOSITE_CODE,
	COMPOSITE_DELIVERY_METHOD,
	CREATED_BY,
	DATE_CREATED,
	DEFAULT_SERVICE_LOOK,
	ENVELOPE_TYPE,
	GROUP_CODE,
	GROUP_DELIVERY_METHOD,
	LAST_UPDATED,
	MODEL_ETHNICITY,
	MODEL_GENDER,
	MODEL_GRADE,
	PRICE_PROGRAM_ID,
	STAFF_PACKAGE,
	STYLE,
	UPDATED_BY,
	VISUAL_MERCH_ID,
	YEAR_BOOK_LOOK,
	COMMISSION_TYPE,
	COMMISSION_RATE,
	NO_TOUCH_YEARBOOK_LOOK,
	MINIMUM_REQUIREMENTS,
	FLYER_ID,
	PART_NUMBER,
	FLYER_SIZE,
	FLYER_STYLE,
	LAYOUT_CODE,
	PAYMENT_MESSAGE_TEXT,
	CREDIT_CARD_ALLOWED,
	CHECK_PAYABLE_TO,
	SMALL_NOTICE_TEXT,
	ADDITIONAL_INFO_TEXT,
	ADDITIONAL_INFO_PROOF_TEXT,
	FAMILY_PLAN_VERBIAGE,
	PAYMENT_DUE_TIMING_TEXT,
	SPANISH_CAPTION_CODE1,
	SPANISH_CAPTION_CODE2,
	SPANISH_CAPTION_CODE3,
	INSERT_NO,
	INSERT_TYPE,
	MASCOT,
	PAYMENT_METHOD,
	POST_PIC_DAY_CUST_INQ_PHONE1,
	POST_PIC_DAY_CUST_INQ_PHONE2,
	PRE_PIC_DAY_CUST_INQ_PHONE1,
	PRE_PIC_DAY_CUST_INQ_PHONE2,
	THEME,
	CASUAL_CODE,
	CUSTOMER_SERVICE_EMAIL,
	CUSTOMER_SERVICE_HOURS,
	ODS_CREATE_DATE,
	ODS_MODIFY_DATE,
	SOURCE_SYSTEM_OID
	
from	RAX_APP_USER.I$_OFFERING S



where	IND_UPDATE = 'I'



&


/*-----------------------------------------------*/
/* TASK No. 39 */
/* Commit transaction */

/*commit*/


/*-----------------------------------------------*/
/* TASK No. 40 */
/* Drop flow table */

drop table RAX_APP_USER.I$_OFFERING 

&


/*-----------------------------------------------*/
/* TASK No. 41 */
/* Repair OFFERING APO_OID */

merge into RAX_APP_USER.E$_OFFERING   c 
using (
    select o.apo_OID, e.ODI_PK         
    from 
        RAX_APP_USER.E$_Offering  E
     ,ODS_STAGE_CA.FOW_OFFERING_XR  F
     ,ODS_OWN.Apo  O
     ,ODS_STAGE_CA.apo_xr xr
    where (1=1) 
    And F.Offering_Oid = E.Offering_Oid
    And O.Apo_Id = Xr.Apo_Id
    and F.Apo_Id = Xr.Fow_Sk_Id
    and nvl(o.APO_OID,-11111) <> nvl(e.APO_OID,-11111)
) s
   on (c.ODI_PK = s.ODI_PK)
when matched then update
set 
c.APO_OID = s.APO_OID

&


/*-----------------------------------------------*/
/* TASK No. 42 */
/* Update CDC Load Status */

/*
UPDATE ODS_OWN.ODS_CDC_LOAD_STATUS
SET LAST_CDC_COMPLETION_DATE=TO_DATE(
             SUBSTR(:v_sess_beg, 1, 19), 'RRRR-MM-DD HH24:MI:SS')
+ nvl((TIMEZONE_OFFSET/24), 0) 
WHERE ODS_TABLE_NAME=:v_cdc_load_table_name
AND CONTEXT_NAME = :v_env
*/

UPDATE ODS_OWN.ODS_CDC_LOAD_STATUS
SET LAST_CDC_COMPLETION_DATE=TO_DATE(
             SUBSTR(:v_sess_beg, 1, 19), 'RRRR-MM-DD HH24:MI:SS')
WHERE ODS_TABLE_NAME=:v_cdc_load_table_name
AND CONTEXT_NAME = :v_env

&


/*-----------------------------------------------*/
/* TASK No. 43 */
/* Insert CDC Audit Record */

/*
INSERT INTO RAX_APP_USER.ODS_CDC_LOAD_STATUS_AUDIT
(TABLE_NAME,
SESS_NO,                      
SESS_NAME,                    
SCEN_VERSION,                 
SESS_BEG,                     
ORIG_LAST_CDC_COMPLETION_DATE,
OVERLAP,
CREATE_DATE,
CONTEXT_NAME,
TIMEZONE_OFFSET              
)
select 
:v_cdc_load_table_name
,:v_sess_no
,'LOAD_FOW_OFFERING_PKG'
,'002'
,TO_DATE(SUBSTR(:v_sess_beg, 1, 19), 'RRRR-MM-DD HH24:MI:SS')
,TO_DATE (SUBSTR(:v_cdc_load_date, 1, 19),'YYYY-MM-DD HH24:MI:SS')
,:v_cdc_overlap
,SYSDATE
,:v_env
,TIMEZONE_OFFSET
from 
ODS_OWN.ODS_CDC_LOAD_STATUS
WHERE ODS_TABLE_NAME=:v_cdc_load_table_name
AND CONTEXT_NAME = :v_env

*/


INSERT INTO RAX_APP_USER.ODS_CDC_LOAD_STATUS_AUDIT
(TABLE_NAME,
SESS_NO,                      
SESS_NAME,                    
SCEN_VERSION,                 
SESS_BEG,                     
ORIG_LAST_CDC_COMPLETION_DATE,
OVERLAP,
CREATE_DATE,
CONTEXT_NAME              
)
values (
:v_cdc_load_table_name,
:v_sess_no,
'LOAD_FOW_OFFERING_PKG',
'002',
TO_DATE(
             SUBSTR(:v_sess_beg, 1, 19), 'RRRR-MM-DD HH24:MI:SS'),
TO_DATE (SUBSTR (:v_cdc_load_date, 1, 19),
                           'YYYY-MM-DD HH24:MI:SS'
                          )
,:v_cdc_overlap,
SYSDATE,
 :v_env)


&


/*-----------------------------------------------*/
