/* TASK No. 1 */

/* NONE or SET VARIABLE STATEMENT FOUND, CHECK ODI TASK NO. 1 */




/*-----------------------------------------------*/
/* TASK No. 2 */

/* SELECT STATEMENT FOUND, CHECK ODI TASK NO. 2 */




/*-----------------------------------------------*/
/* TASK No. 3 */

/* SELECT STATEMENT FOUND, CHECK ODI TASK NO. 3 */




/*-----------------------------------------------*/
/* TASK No. 4 */
/* Drop work table */

-- drop table RAX_APP_USER.C$_0STG_FOW_APO 

-- &


-- /*-----------------------------------------------*/
-- /* TASK No. 5 */
-- /* Create work table */

-- create table RAX_APP_USER.C$_0STG_FOW_APO
-- (
-- 	C1_CAMERA_PLATFORM	VARCHAR2(255) NULL,
-- 	C2_CONFIRMED_LAB	VARCHAR2(255) NULL,
-- 	C3_COUNTRY	VARCHAR2(255) NULL,
-- 	C4_POSTAL_CODE	VARCHAR2(255) NULL,
-- 	C5_CITY	VARCHAR2(255) NULL,
-- 	C6_ADDRESS	VARCHAR2(255) NULL,
-- 	C7_COUNTY	VARCHAR2(255) NULL,
-- 	C8_VERSION	NUMBER(19) NULL,
-- 	C9_FINANCIAL_PROCESSING_SYSTEM	VARCHAR2(10) NULL,
-- 	C10_RISK_IND	NUMBER(1) NULL,
-- 	C11_LANGUAGE2	VARCHAR2(255) NULL,
-- 	C12_FULFILLING_LAB_SYSTEM	VARCHAR2(10) NULL,
-- 	C13_ENVELOPE_ID	VARCHAR2(20) NULL,
-- 	C14_SUBCATEGORY	VARCHAR2(255) NULL,
-- 	C15_ORIGINAL_BOOKING_REP	VARCHAR2(255) NULL,
-- 	C16_VALIDATION_ERROR	VARCHAR2(1024) NULL,
-- 	C17_ORIGINAL_BOOKING_REP_NAME	VARCHAR2(255) NULL,
-- 	C18_LOCK_ON_NAME	NUMBER(1) NULL,
-- 	C19_CATEGORY	VARCHAR2(255) NULL,
-- 	C20_EST_TO_BE_PHOTOED	VARCHAR2(255) NULL,
-- 	C21_MARKETING_CODE	VARCHAR2(255) NULL,
-- 	C22_OPERATIONS_REP_NAME	VARCHAR2(255) NULL,
-- 	C23_CONSUMER_ENQ_PHONE	VARCHAR2(255) NULL,
-- 	C24_ORDER_FORM	VARCHAR2(255) NULL,
-- 	C25_LANGUAGE	VARCHAR2(255) NULL,
-- 	C26_TERRITORY	VARCHAR2(255) NULL,
-- 	C27_SELLING_METHOD	VARCHAR2(255) NULL,
-- 	C28_LOC_CODE	VARCHAR2(255) NULL,
-- 	C29_LOW_GRADE	VARCHAR2(255) NULL,
-- 	C30_ACCOUNT_NAME	VARCHAR2(255) NULL,
-- 	C31_REMINDER_POSTCARD	NUMBER(1) NULL,
-- 	C32_RISK_TEXT	VARCHAR2(255) NULL,
-- 	C33_FAX	VARCHAR2(255) NULL,
-- 	C34_CREATED_BY	VARCHAR2(255) NULL,
-- 	C35_STATUS	VARCHAR2(255) NULL,
-- 	C36_REPORT_GRP	VARCHAR2(255) NULL,
-- 	C37_SERVICE_PRODUCT_SORT	VARCHAR2(255) NULL,
-- 	C38_SHIP_TO	VARCHAR2(255) NULL,
-- 	C39_PROCESSING_LAB	VARCHAR2(255) NULL,
-- 	C40_SCHOOL_YR_END	NUMBER(10) NULL,
-- 	C41_ID	NUMBER(19) NULL,
-- 	C42_PHOTO_LOCATION	VARCHAR2(255) NULL,
-- 	C43_APO_TAG	VARCHAR2(255) NULL,
-- 	C44_RISK_CODE	VARCHAR2(255) NULL,
-- 	C45_OFFER_ONLINE_ORDERING	NUMBER(1) NULL,
-- 	C46_PHONE_ORDER	VARCHAR2(255) NULL,
-- 	C47_BOOKING_YEAR	VARCHAR2(255) NULL,
-- 	C48_SALES_REP_CODE	VARCHAR2(255) NULL,
-- 	C49_DESCRIPTION	VARCHAR2(255) NULL,
-- 	C50_REVISION_NO	NUMBER(19) NULL,
-- 	C51_HIGH_GRADE	VARCHAR2(255) NULL,
-- 	C52_CONSUMER_MODEL	VARCHAR2(255) NULL,
-- 	C53_SUB_PROGRAM	VARCHAR2(255) NULL,
-- 	C54_PUBLISHED	NUMBER(1) NULL,
-- 	C55_PHONE	VARCHAR2(255) NULL,
-- 	C56_TAX_CERTIFICATE	VARCHAR2(255) NULL,
-- 	C57_BOOKING_OPP_ID	NUMBER(19) NULL,
-- 	C58_ORDER_FORM_ITEM_ID	VARCHAR2(255) NULL,
-- 	C59_DEFAULT_ORD_PKG	VARCHAR2(255) NULL,
-- 	C60_DATE_CREATED	TIMESTAMP(6) NULL,
-- 	C61_VISION_JOB	VARCHAR2(255) NULL,
-- 	C62_SVC_PROD_MODEL	VARCHAR2(255) NULL,
-- 	C63_BUS_CONTEXT_NAME	VARCHAR2(255) NULL,
-- 	C64_PROGRAM	VARCHAR2(255) NULL,
-- 	C65_NACAM_OVERALL	VARCHAR2(255) NULL,
-- 	C66_JOB_IDENTIFIER	VARCHAR2(255) NULL,
-- 	C67_TAX_EXEMPT	NUMBER(1) NULL,
-- 	C68_SALES_REP_NAME	VARCHAR2(255) NULL,
-- 	C69_UPDATED_BY	VARCHAR2(255) NULL,
-- 	C70_LAST_UPDATED	TIMESTAMP(6) NULL,
-- 	C71_ENROLLMENT_COUNT	NUMBER(10) NULL,
-- 	C72_TWO_WEEK_RETURN_MSG	NUMBER(1) NULL,
-- 	C73_CONSUMER_SORT	VARCHAR2(255) NULL,
-- 	C74_PROOF_EXPRESS	NUMBER(1) NULL,
-- 	C75_CONTACT	VARCHAR2(255) NULL,
-- 	C76_SERVICE_CENTER	VARCHAR2(255) NULL,
-- 	C77_CURRENCY	VARCHAR2(255) NULL,
-- 	C78_LAB_INSTRUCTIONS	VARCHAR2(255) NULL,
-- 	C79_LID	NUMBER(19) NULL,
-- 	C80_COPIED_FROM_ODS	VARCHAR2(1) NULL,
-- 	C81_CONTRACT_RECEIVED	TIMESTAMP(6) NULL,
-- 	C82_APO_TYPE	VARCHAR2(255) NULL,
-- 	C83_YB_PROGRAM	VARCHAR2(255) NULL,
-- 	C84_SALES_REP_EMAIL	VARCHAR2(255) NULL,
-- 	C85_FINALIZED_DATE	TIMESTAMP(6) NULL,
-- 	C86_COVER_RECEIVED	TIMESTAMP(6) NULL,
-- 	C87_SALE_TYPE	VARCHAR2(10) NULL,
-- 	C88_ENABLE_PRISM	NUMBER(19) NULL,
-- 	C89_BOOK_OFFERING	VARCHAR2(255) NULL,
-- 	C90_INCENTIVE_GRANTED	VARCHAR2(10) NULL,
-- 	C91_CONTRACT_STATUS	VARCHAR2(255) NULL,
-- 	C92_ALLOW_EXTRA_COVERAGE_DEADL	NUMBER(19) NULL,
-- 	C93_PRODUCT_RELEASE_COMPLETED_	VARCHAR2(255) NULL,
-- 	C94_PRODUCT_RELEASE_COMPLETED_	DATE NULL,
-- 	C95_COVER_DETAILS_PROVIDED	DATE NULL,
-- 	C96_COVER_APPROVED	DATE NULL,
-- 	C97_SIGNING_INFO	VARCHAR2(255) NULL,
-- 	C98_YB_ENROLLED	NUMBER(1) NULL,
-- 	C99_YB_ENROLLED_DATE	TIMESTAMP(6) NULL,
-- 	C100_LIFETOUCH_PHOTOGRAPHED	VARCHAR2(1) NULL
-- )
-- NOLOGGING

-- &


-- /*-----------------------------------------------*/
-- /* TASK No. 6 */
-- /* Load data */

-- /* SOURCE CODE */
-- select	
-- 	APO.CAMERA_PLATFORM	   C1_CAMERA_PLATFORM,
-- 	APO.CONFIRMED_LAB	   C2_CONFIRMED_LAB,
-- 	APO.COUNTRY	   C3_COUNTRY,
-- 	APO.POSTAL_CODE	   C4_POSTAL_CODE,
-- 	APO.CITY	   C5_CITY,
-- 	APO.ADDRESS	   C6_ADDRESS,
-- 	APO.COUNTY	   C7_COUNTY,
-- 	APO.VERSION	   C8_VERSION,
-- 	APO.FINANCIAL_PROCESSING_SYSTEM	   C9_FINANCIAL_PROCESSING_SYSTEM,
-- 	APO.RISK_IND	   C10_RISK_IND,
-- 	APO.LANGUAGE2	   C11_LANGUAGE2,
-- 	APO.FULFILLING_LAB_SYSTEM	   C12_FULFILLING_LAB_SYSTEM,
-- 	APO.ENVELOPE_ID	   C13_ENVELOPE_ID,
-- 	APO.SUBCATEGORY	   C14_SUBCATEGORY,
-- 	APO.ORIGINAL_BOOKING_REP	   C15_ORIGINAL_BOOKING_REP,
-- 	APO.VALIDATION_ERROR	   C16_VALIDATION_ERROR,
-- 	APO.ORIGINAL_BOOKING_REP_NAME	   C17_ORIGINAL_BOOKING_REP_NAME,
-- 	APO.LOCK_ON_NAME	   C18_LOCK_ON_NAME,
-- 	APO.CATEGORY	   C19_CATEGORY,
-- 	APO.EST_TO_BE_PHOTOED	   C20_EST_TO_BE_PHOTOED,
-- 	APO.MARKETING_CODE	   C21_MARKETING_CODE,
-- 	APO.OPERATIONS_REP_NAME	   C22_OPERATIONS_REP_NAME,
-- 	APO.CONSUMER_ENQ_PHONE	   C23_CONSUMER_ENQ_PHONE,
-- 	APO.ORDER_FORM	   C24_ORDER_FORM,
-- 	APO.LANGUAGE	   C25_LANGUAGE,
-- 	APO.TERRITORY	   C26_TERRITORY,
-- 	APO.SELLING_METHOD	   C27_SELLING_METHOD,
-- 	APO.LOC_CODE	   C28_LOC_CODE,
-- 	APO.LOW_GRADE	   C29_LOW_GRADE,
-- 	APO.ACCOUNT_NAME	   C30_ACCOUNT_NAME,
-- 	APO.REMINDER_POSTCARD	   C31_REMINDER_POSTCARD,
-- 	APO.RISK_TEXT	   C32_RISK_TEXT,
-- 	APO.FAX	   C33_FAX,
-- 	APO.CREATED_BY	   C34_CREATED_BY,
-- 	APO.STATUS	   C35_STATUS,
-- 	APO.REPORT_GRP	   C36_REPORT_GRP,
-- 	APO.SERVICE_PRODUCT_SORT	   C37_SERVICE_PRODUCT_SORT,
-- 	APO.SHIP_TO	   C38_SHIP_TO,
-- 	LAB.NAME	   C39_PROCESSING_LAB,
-- 	APO.SCHOOL_YR_END	   C40_SCHOOL_YR_END,
-- 	APO.ID	   C41_ID,
-- 	APO.PHOTO_LOCATION	   C42_PHOTO_LOCATION,
-- 	APO.APO_TAG	   C43_APO_TAG,
-- 	APO.RISK_CODE	   C44_RISK_CODE,
-- 	APO.OFFER_ONLINE_ORDERING	   C45_OFFER_ONLINE_ORDERING,
-- 	APO.PHONE_ORDER	   C46_PHONE_ORDER,
-- 	APO.BOOKING_YEAR	   C47_BOOKING_YEAR,
-- 	APO.SALES_REP_CODE	   C48_SALES_REP_CODE,
-- 	APO.DESCRIPTION	   C49_DESCRIPTION,
-- 	APO.REVISION_NO	   C50_REVISION_NO,
-- 	APO.HIGH_GRADE	   C51_HIGH_GRADE,
-- 	APO.CONSUMER_MODEL	   C52_CONSUMER_MODEL,
-- 	APO.SUB_PROGRAM	   C53_SUB_PROGRAM,
-- 	APO.PUBLISHED	   C54_PUBLISHED,
-- 	APO.PHONE	   C55_PHONE,
-- 	APO.TAX_CERTIFICATE	   C56_TAX_CERTIFICATE,
-- 	APO.BOOKING_OPP_ID	   C57_BOOKING_OPP_ID,
-- 	APO.ORDER_FORM_ITEM_ID	   C58_ORDER_FORM_ITEM_ID,
-- 	APO.DEFAULT_ORD_PKG	   C59_DEFAULT_ORD_PKG,
-- 	APO.DATE_CREATED	   C60_DATE_CREATED,
-- 	APO.VISION_JOB	   C61_VISION_JOB,
-- 	APO.SVC_PROD_MODEL	   C62_SVC_PROD_MODEL,
-- 	APO.BUS_CONTEXT_NAME	   C63_BUS_CONTEXT_NAME,
-- 	APO.PROGRAM	   C64_PROGRAM,
-- 	APO.NACAM_OVERALL	   C65_NACAM_OVERALL,
-- 	APO.JOB_IDENTIFIER	   C66_JOB_IDENTIFIER,
-- 	APO.TAX_EXEMPT	   C67_TAX_EXEMPT,
-- 	APO.SALES_REP_NAME	   C68_SALES_REP_NAME,
-- 	APO.UPDATED_BY	   C69_UPDATED_BY,
-- 	APO.LAST_UPDATED	   C70_LAST_UPDATED,
-- 	APO.ENROLLMENT_COUNT	   C71_ENROLLMENT_COUNT,
-- 	APO.TWO_WEEK_RETURN_MSG	   C72_TWO_WEEK_RETURN_MSG,
-- 	APO.CONSUMER_SORT	   C73_CONSUMER_SORT,
-- 	APO.PROOF_EXPRESS	   C74_PROOF_EXPRESS,
-- 	APO.CONTACT	   C75_CONTACT,
-- 	APO.SERVICE_CENTER	   C76_SERVICE_CENTER,
-- 	APO.CURRENCY	   C77_CURRENCY,
-- 	APO.LAB_INSTRUCTIONS	   C78_LAB_INSTRUCTIONS,
-- 	APO.LID	   C79_LID,
-- 	APO.COPIED_FROM_ODS	   C80_COPIED_FROM_ODS,
-- 	APO.CONTRACT_RECEIVED	   C81_CONTRACT_RECEIVED,
-- 	APO.APO_TYPE	   C82_APO_TYPE,
-- 	APO.YB_PROGRAM	   C83_YB_PROGRAM,
-- 	APO.SALES_REP_EMAIL	   C84_SALES_REP_EMAIL,
-- 	APO.FINALIZED_DATE	   C85_FINALIZED_DATE,
-- 	APO.COVER_RECEIVED	   C86_COVER_RECEIVED,
-- 	APO.SALE_TYPE	   C87_SALE_TYPE,
-- 	APO.ENABLE_PRISM	   C88_ENABLE_PRISM,
-- 	APO.BOOK_OFFERING	   C89_BOOK_OFFERING,
-- 	APO.INCENTIVE_GRANTED	   C90_INCENTIVE_GRANTED,
-- 	APO.CONTRACT_STATUS	   C91_CONTRACT_STATUS,
-- 	APO.ALLOW_EXTRA_COVERAGE_DEADLINE	   C92_ALLOW_EXTRA_COVERAGE_DEADL,
-- 	APO.PRODUCT_RELEASE_COMPLETED_BY	   C93_PRODUCT_RELEASE_COMPLETED_,
-- 	APO.PRODUCT_RELEASE_COMPLETED_DATE	   C94_PRODUCT_RELEASE_COMPLETED_,
-- 	APO.COVER_DETAILS_PROVIDED	   C95_COVER_DETAILS_PROVIDED,
-- 	APO.COVER_APPROVED	   C96_COVER_APPROVED,
-- 	APO.SIGNING_INFO	   C97_SIGNING_INFO,
-- 	APO.YB_ENROLLED	   C98_YB_ENROLLED,
-- 	APO.YB_ENROLLED_DATE	   C99_YB_ENROLLED_DATE,
-- 	TRIM(APO.LIFETOUCH_PHOTOGRAPHED)	   C100_LIFETOUCH_PHOTOGRAPHED
-- from	FOW_OWN.APO   APO, FOW_OWN.LAB   LAB
-- where	(1=1)
-- And (APO.LAST_UPDATED >= TO_DATE(SUBSTR(:v_cdc_load_date, 1, 19), 'YYYY-MM-DD HH24:MI:SS')  -:v_cdc_oms_overlap)
--  And (APO.SCHOOL_YR_END is not null)
--  And (APO.PROCESSING_LAB_ID=LAB.ID (+))




-- &

-- /* TARGET CODE */
-- insert into RAX_APP_USER.C$_0STG_FOW_APO
-- (
-- 	C1_CAMERA_PLATFORM,
-- 	C2_CONFIRMED_LAB,
-- 	C3_COUNTRY,
-- 	C4_POSTAL_CODE,
-- 	C5_CITY,
-- 	C6_ADDRESS,
-- 	C7_COUNTY,
-- 	C8_VERSION,
-- 	C9_FINANCIAL_PROCESSING_SYSTEM,
-- 	C10_RISK_IND,
-- 	C11_LANGUAGE2,
-- 	C12_FULFILLING_LAB_SYSTEM,
-- 	C13_ENVELOPE_ID,
-- 	C14_SUBCATEGORY,
-- 	C15_ORIGINAL_BOOKING_REP,
-- 	C16_VALIDATION_ERROR,
-- 	C17_ORIGINAL_BOOKING_REP_NAME,
-- 	C18_LOCK_ON_NAME,
-- 	C19_CATEGORY,
-- 	C20_EST_TO_BE_PHOTOED,
-- 	C21_MARKETING_CODE,
-- 	C22_OPERATIONS_REP_NAME,
-- 	C23_CONSUMER_ENQ_PHONE,
-- 	C24_ORDER_FORM,
-- 	C25_LANGUAGE,
-- 	C26_TERRITORY,
-- 	C27_SELLING_METHOD,
-- 	C28_LOC_CODE,
-- 	C29_LOW_GRADE,
-- 	C30_ACCOUNT_NAME,
-- 	C31_REMINDER_POSTCARD,
-- 	C32_RISK_TEXT,
-- 	C33_FAX,
-- 	C34_CREATED_BY,
-- 	C35_STATUS,
-- 	C36_REPORT_GRP,
-- 	C37_SERVICE_PRODUCT_SORT,
-- 	C38_SHIP_TO,
-- 	C39_PROCESSING_LAB,
-- 	C40_SCHOOL_YR_END,
-- 	C41_ID,
-- 	C42_PHOTO_LOCATION,
-- 	C43_APO_TAG,
-- 	C44_RISK_CODE,
-- 	C45_OFFER_ONLINE_ORDERING,
-- 	C46_PHONE_ORDER,
-- 	C47_BOOKING_YEAR,
-- 	C48_SALES_REP_CODE,
-- 	C49_DESCRIPTION,
-- 	C50_REVISION_NO,
-- 	C51_HIGH_GRADE,
-- 	C52_CONSUMER_MODEL,
-- 	C53_SUB_PROGRAM,
-- 	C54_PUBLISHED,
-- 	C55_PHONE,
-- 	C56_TAX_CERTIFICATE,
-- 	C57_BOOKING_OPP_ID,
-- 	C58_ORDER_FORM_ITEM_ID,
-- 	C59_DEFAULT_ORD_PKG,
-- 	C60_DATE_CREATED,
-- 	C61_VISION_JOB,
-- 	C62_SVC_PROD_MODEL,
-- 	C63_BUS_CONTEXT_NAME,
-- 	C64_PROGRAM,
-- 	C65_NACAM_OVERALL,
-- 	C66_JOB_IDENTIFIER,
-- 	C67_TAX_EXEMPT,
-- 	C68_SALES_REP_NAME,
-- 	C69_UPDATED_BY,
-- 	C70_LAST_UPDATED,
-- 	C71_ENROLLMENT_COUNT,
-- 	C72_TWO_WEEK_RETURN_MSG,
-- 	C73_CONSUMER_SORT,
-- 	C74_PROOF_EXPRESS,
-- 	C75_CONTACT,
-- 	C76_SERVICE_CENTER,
-- 	C77_CURRENCY,
-- 	C78_LAB_INSTRUCTIONS,
-- 	C79_LID,
-- 	C80_COPIED_FROM_ODS,
-- 	C81_CONTRACT_RECEIVED,
-- 	C82_APO_TYPE,
-- 	C83_YB_PROGRAM,
-- 	C84_SALES_REP_EMAIL,
-- 	C85_FINALIZED_DATE,
-- 	C86_COVER_RECEIVED,
-- 	C87_SALE_TYPE,
-- 	C88_ENABLE_PRISM,
-- 	C89_BOOK_OFFERING,
-- 	C90_INCENTIVE_GRANTED,
-- 	C91_CONTRACT_STATUS,
-- 	C92_ALLOW_EXTRA_COVERAGE_DEADL,
-- 	C93_PRODUCT_RELEASE_COMPLETED_,
-- 	C94_PRODUCT_RELEASE_COMPLETED_,
-- 	C95_COVER_DETAILS_PROVIDED,
-- 	C96_COVER_APPROVED,
-- 	C97_SIGNING_INFO,
-- 	C98_YB_ENROLLED,
-- 	C99_YB_ENROLLED_DATE,
-- 	C100_LIFETOUCH_PHOTOGRAPHED
-- )
-- values
-- (
-- 	:C1_CAMERA_PLATFORM,
-- 	:C2_CONFIRMED_LAB,
-- 	:C3_COUNTRY,
-- 	:C4_POSTAL_CODE,
-- 	:C5_CITY,
-- 	:C6_ADDRESS,
-- 	:C7_COUNTY,
-- 	:C8_VERSION,
-- 	:C9_FINANCIAL_PROCESSING_SYSTEM,
-- 	:C10_RISK_IND,
-- 	:C11_LANGUAGE2,
-- 	:C12_FULFILLING_LAB_SYSTEM,
-- 	:C13_ENVELOPE_ID,
-- 	:C14_SUBCATEGORY,
-- 	:C15_ORIGINAL_BOOKING_REP,
-- 	:C16_VALIDATION_ERROR,
-- 	:C17_ORIGINAL_BOOKING_REP_NAME,
-- 	:C18_LOCK_ON_NAME,
-- 	:C19_CATEGORY,
-- 	:C20_EST_TO_BE_PHOTOED,
-- 	:C21_MARKETING_CODE,
-- 	:C22_OPERATIONS_REP_NAME,
-- 	:C23_CONSUMER_ENQ_PHONE,
-- 	:C24_ORDER_FORM,
-- 	:C25_LANGUAGE,
-- 	:C26_TERRITORY,
-- 	:C27_SELLING_METHOD,
-- 	:C28_LOC_CODE,
-- 	:C29_LOW_GRADE,
-- 	:C30_ACCOUNT_NAME,
-- 	:C31_REMINDER_POSTCARD,
-- 	:C32_RISK_TEXT,
-- 	:C33_FAX,
-- 	:C34_CREATED_BY,
-- 	:C35_STATUS,
-- 	:C36_REPORT_GRP,
-- 	:C37_SERVICE_PRODUCT_SORT,
-- 	:C38_SHIP_TO,
-- 	:C39_PROCESSING_LAB,
-- 	:C40_SCHOOL_YR_END,
-- 	:C41_ID,
-- 	:C42_PHOTO_LOCATION,
-- 	:C43_APO_TAG,
-- 	:C44_RISK_CODE,
-- 	:C45_OFFER_ONLINE_ORDERING,
-- 	:C46_PHONE_ORDER,
-- 	:C47_BOOKING_YEAR,
-- 	:C48_SALES_REP_CODE,
-- 	:C49_DESCRIPTION,
-- 	:C50_REVISION_NO,
-- 	:C51_HIGH_GRADE,
-- 	:C52_CONSUMER_MODEL,
-- 	:C53_SUB_PROGRAM,
-- 	:C54_PUBLISHED,
-- 	:C55_PHONE,
-- 	:C56_TAX_CERTIFICATE,
-- 	:C57_BOOKING_OPP_ID,
-- 	:C58_ORDER_FORM_ITEM_ID,
-- 	:C59_DEFAULT_ORD_PKG,
-- 	:C60_DATE_CREATED,
-- 	:C61_VISION_JOB,
-- 	:C62_SVC_PROD_MODEL,
-- 	:C63_BUS_CONTEXT_NAME,
-- 	:C64_PROGRAM,
-- 	:C65_NACAM_OVERALL,
-- 	:C66_JOB_IDENTIFIER,
-- 	:C67_TAX_EXEMPT,
-- 	:C68_SALES_REP_NAME,
-- 	:C69_UPDATED_BY,
-- 	:C70_LAST_UPDATED,
-- 	:C71_ENROLLMENT_COUNT,
-- 	:C72_TWO_WEEK_RETURN_MSG,
-- 	:C73_CONSUMER_SORT,
-- 	:C74_PROOF_EXPRESS,
-- 	:C75_CONTACT,
-- 	:C76_SERVICE_CENTER,
-- 	:C77_CURRENCY,
-- 	:C78_LAB_INSTRUCTIONS,
-- 	:C79_LID,
-- 	:C80_COPIED_FROM_ODS,
-- 	:C81_CONTRACT_RECEIVED,
-- 	:C82_APO_TYPE,
-- 	:C83_YB_PROGRAM,
-- 	:C84_SALES_REP_EMAIL,
-- 	:C85_FINALIZED_DATE,
-- 	:C86_COVER_RECEIVED,
-- 	:C87_SALE_TYPE,
-- 	:C88_ENABLE_PRISM,
-- 	:C89_BOOK_OFFERING,
-- 	:C90_INCENTIVE_GRANTED,
-- 	:C91_CONTRACT_STATUS,
-- 	:C92_ALLOW_EXTRA_COVERAGE_DEADL,
-- 	:C93_PRODUCT_RELEASE_COMPLETED_,
-- 	:C94_PRODUCT_RELEASE_COMPLETED_,
-- 	:C95_COVER_DETAILS_PROVIDED,
-- 	:C96_COVER_APPROVED,
-- 	:C97_SIGNING_INFO,
-- 	:C98_YB_ENROLLED,
-- 	:C99_YB_ENROLLED_DATE,
-- 	:C100_LIFETOUCH_PHOTOGRAPHED
-- )

-- &


/*-----------------------------------------------*/
/* TASK No. 7 */
/* Analyze work table */



BEGIN
DBMS_STATS.GATHER_TABLE_STATS (
    ownname =>	'RAX_APP_USER',
    tabname =>	'C$_0STG_FOW_APO',
    estimate_percent =>	DBMS_STATS.AUTO_SAMPLE_SIZE
);
END;




&


/*-----------------------------------------------*/
/* TASK No. 9 */
/* Create target table  */

BEGIN  
   EXECUTE IMMEDIATE 'create table RAX_APP_USER.STG_FOW_APO
(
	CAMERA_PLATFORM	VARCHAR2(255) NULL,
	CONFIRMED_LAB	VARCHAR2(255) NULL,
	COUNTRY	VARCHAR2(255) NULL,
	POSTAL_CODE	VARCHAR2(255) NULL,
	CITY	VARCHAR2(255) NULL,
	ADDRESS	VARCHAR2(255) NULL,
	COUNTY	VARCHAR2(255) NULL,
	VERSION	NUMBER(19) NULL,
	FINANCIAL_PROCESSING_SYSTEM	VARCHAR2(10) NULL,
	RISK_IND	NUMBER(1) NULL,
	LANGUAGE2	VARCHAR2(255) NULL,
	FULFILLING_LAB_SYSTEM	VARCHAR2(10) NULL,
	ENVELOPE_ID	VARCHAR2(20) NULL,
	SUBCATEGORY	VARCHAR2(255) NULL,
	ORIGINAL_BOOKING_REP	VARCHAR2(255) NULL,
	VALIDATION_ERROR	VARCHAR2(1024) NULL,
	ORIGINAL_BOOKING_REP_NAME	VARCHAR2(255) NULL,
	LOCK_ON_NAME	NUMBER(1) NULL,
	CATEGORY	VARCHAR2(255) NULL,
	EST_TO_BE_PHOTOED	VARCHAR2(255) NULL,
	MARKETING_CODE	VARCHAR2(255) NULL,
	OPERATIONS_REP_NAME	VARCHAR2(255) NULL,
	CONSUMER_ENQ_PHONE	VARCHAR2(255) NULL,
	ORDER_FORM	VARCHAR2(255) NULL,
	LANGUAGE	VARCHAR2(255) NULL,
	TERRITORY	VARCHAR2(255) NULL,
	SELLING_METHOD	VARCHAR2(255) NULL,
	LOC_CODE	VARCHAR2(255) NULL,
	LOW_GRADE	VARCHAR2(255) NULL,
	ACCOUNT_NAME	VARCHAR2(255) NULL,
	REMINDER_POSTCARD	NUMBER(1) NULL,
	RISK_TEXT	VARCHAR2(255) NULL,
	FAX	VARCHAR2(255) NULL,
	CREATED_BY	VARCHAR2(255) NULL,
	STATUS	VARCHAR2(255) NULL,
	REPORT_GRP	VARCHAR2(255) NULL,
	SERVICE_PRODUCT_SORT	VARCHAR2(255) NULL,
	SHIP_TO	VARCHAR2(255) NULL,
	PROCESSING_LAB	VARCHAR2(255) NULL,
	SCHOOL_YR_END	NUMBER(10) NULL,
	ID	NUMBER(19) NULL,
	PHOTO_LOCATION	VARCHAR2(255) NULL,
	APO_TAG	VARCHAR2(255) NULL,
	RISK_CODE	VARCHAR2(255) NULL,
	OFFER_ONLINE_ORDERING	NUMBER(1) NULL,
	PHONE_ORDER	VARCHAR2(255) NULL,
	BOOKING_YEAR	VARCHAR2(255) NULL,
	SALES_REP_CODE	VARCHAR2(255) NULL,
	DESCRIPTION	VARCHAR2(255) NULL,
	REVISION_NO	NUMBER(19) NULL,
	HIGH_GRADE	VARCHAR2(255) NULL,
	CONSUMER_MODEL	VARCHAR2(255) NULL,
	SUB_PROGRAM	VARCHAR2(255) NULL,
	PUBLISHED	NUMBER(1) NULL,
	PHONE	VARCHAR2(255) NULL,
	TAX_CERTIFICATE	VARCHAR2(255) NULL,
	BOOKING_OPP_ID	NUMBER(19) NULL,
	ORDER_FORM_ITEM_ID	VARCHAR2(255) NULL,
	DEFAULT_ORD_PKG	VARCHAR2(255) NULL,
	DATE_CREATED	TIMESTAMP(6) NULL,
	VISION_JOB	VARCHAR2(255) NULL,
	SVC_PROD_MODEL	VARCHAR2(255) NULL,
	BUS_CONTEXT_NAME	VARCHAR2(255) NULL,
	PROGRAM	VARCHAR2(255) NULL,
	NACAM_OVERALL	VARCHAR2(255) NULL,
	JOB_IDENTIFIER	VARCHAR2(255) NULL,
	TAX_EXEMPT	NUMBER(1) NULL,
	SALES_REP_NAME	VARCHAR2(255) NULL,
	UPDATED_BY	VARCHAR2(255) NULL,
	LAST_UPDATED	TIMESTAMP(6) NULL,
	ENROLLMENT_COUNT	NUMBER(10) NULL,
	TWO_WEEK_RETURN_MSG	NUMBER(1) NULL,
	CONSUMER_SORT	VARCHAR2(255) NULL,
	PROOF_EXPRESS	NUMBER(1) NULL,
	CONTACT	VARCHAR2(255) NULL,
	SERVICE_CENTER	VARCHAR2(255) NULL,
	CURRENCY	VARCHAR2(255) NULL,
	LAB_INSTRUCTIONS	VARCHAR2(255) NULL,
	LID	NUMBER(19) NULL,
	COPIED_FROM_ODS	VARCHAR2(1) NULL,
	CONTRACT_RECEIVED	TIMESTAMP(6) NULL,
	APO_TYPE	VARCHAR2(255) NULL,
	YB_PROGRAM	VARCHAR2(255) NULL,
	SALES_REP_EMAIL	VARCHAR2(255) NULL,
	FINALIZED_DATE	TIMESTAMP(6) NULL,
	COVER_RECEIVED	TIMESTAMP(6) NULL,
	SALE_TYPE	VARCHAR2(10) NULL,
	ENABLE_PRISM	NUMBER(19) NULL,
	BOOK_OFFERING	VARCHAR2(255) NULL,
	INCENTIVE_GRANTED	VARCHAR2(10) NULL,
	CONTRACT_STATUS	VARCHAR2(255) NULL,
	ALLOW_EXTRA_COVERAGE_DEADLINE	NUMBER(19) NULL,
	PRODUCT_RELEASE_COMPLETED_BY	VARCHAR2(255) NULL,
	PRODUCT_RELEASE_COMPLETED_DATE	DATE NULL,
	COVER_DETAILS_PROVIDED	DATE NULL,
	COVER_APPROVED	DATE NULL,
	SIGNING_INFO	VARCHAR2(255) NULL,
	YB_ENROLLED	NUMBER(1) NULL,
	YB_ENROLLED_DATE	TIMESTAMP(6) NULL,
	LIFETOUCH_PHOTOGRAPHED	VARCHAR2(1) NULL
)';  
EXCEPTION  
   WHEN OTHERS THEN  
      IF SQLCODE != -955 THEN  
         RAISE;  
      END IF;  
END;

&


/*-----------------------------------------------*/
/* TASK No. 10 */
/* Truncate target table */

truncate table RAX_APP_USER.STG_FOW_APO


&


/*-----------------------------------------------*/
/* TASK No. 11 */
/* Insert new rows */

 
insert into	RAX_APP_USER.STG_FOW_APO 
( 
	CAMERA_PLATFORM,
	CONFIRMED_LAB,
	COUNTRY,
	POSTAL_CODE,
	CITY,
	ADDRESS,
	COUNTY,
	VERSION,
	FINANCIAL_PROCESSING_SYSTEM,
	RISK_IND,
	LANGUAGE2,
	FULFILLING_LAB_SYSTEM,
	ENVELOPE_ID,
	SUBCATEGORY,
	ORIGINAL_BOOKING_REP,
	VALIDATION_ERROR,
	ORIGINAL_BOOKING_REP_NAME,
	LOCK_ON_NAME,
	CATEGORY,
	EST_TO_BE_PHOTOED,
	MARKETING_CODE,
	OPERATIONS_REP_NAME,
	CONSUMER_ENQ_PHONE,
	ORDER_FORM,
	LANGUAGE,
	TERRITORY,
	SELLING_METHOD,
	LOC_CODE,
	LOW_GRADE,
	ACCOUNT_NAME,
	REMINDER_POSTCARD,
	RISK_TEXT,
	FAX,
	CREATED_BY,
	STATUS,
	REPORT_GRP,
	SERVICE_PRODUCT_SORT,
	SHIP_TO,
	PROCESSING_LAB,
	SCHOOL_YR_END,
	ID,
	PHOTO_LOCATION,
	APO_TAG,
	RISK_CODE,
	OFFER_ONLINE_ORDERING,
	PHONE_ORDER,
	BOOKING_YEAR,
	SALES_REP_CODE,
	DESCRIPTION,
	REVISION_NO,
	HIGH_GRADE,
	CONSUMER_MODEL,
	SUB_PROGRAM,
	PUBLISHED,
	PHONE,
	TAX_CERTIFICATE,
	BOOKING_OPP_ID,
	ORDER_FORM_ITEM_ID,
	DEFAULT_ORD_PKG,
	DATE_CREATED,
	VISION_JOB,
	SVC_PROD_MODEL,
	BUS_CONTEXT_NAME,
	PROGRAM,
	NACAM_OVERALL,
	JOB_IDENTIFIER,
	TAX_EXEMPT,
	SALES_REP_NAME,
	UPDATED_BY,
	LAST_UPDATED,
	ENROLLMENT_COUNT,
	TWO_WEEK_RETURN_MSG,
	CONSUMER_SORT,
	PROOF_EXPRESS,
	CONTACT,
	SERVICE_CENTER,
	CURRENCY,
	LAB_INSTRUCTIONS,
	LID,
	COPIED_FROM_ODS,
	CONTRACT_RECEIVED,
	APO_TYPE,
	YB_PROGRAM,
	SALES_REP_EMAIL,
	FINALIZED_DATE,
	COVER_RECEIVED,
	SALE_TYPE,
	ENABLE_PRISM,
	BOOK_OFFERING,
	INCENTIVE_GRANTED,
	CONTRACT_STATUS,
	ALLOW_EXTRA_COVERAGE_DEADLINE,
	PRODUCT_RELEASE_COMPLETED_BY,
	PRODUCT_RELEASE_COMPLETED_DATE,
	COVER_DETAILS_PROVIDED,
	COVER_APPROVED,
	SIGNING_INFO,
	YB_ENROLLED,
	YB_ENROLLED_DATE,
	LIFETOUCH_PHOTOGRAPHED 
	 
) 

select
    CAMERA_PLATFORM,
	CONFIRMED_LAB,
	COUNTRY,
	POSTAL_CODE,
	CITY,
	ADDRESS,
	COUNTY,
	VERSION,
	FINANCIAL_PROCESSING_SYSTEM,
	RISK_IND,
	LANGUAGE2,
	FULFILLING_LAB_SYSTEM,
	ENVELOPE_ID,
	SUBCATEGORY,
	ORIGINAL_BOOKING_REP,
	VALIDATION_ERROR,
	ORIGINAL_BOOKING_REP_NAME,
	LOCK_ON_NAME,
	CATEGORY,
	EST_TO_BE_PHOTOED,
	MARKETING_CODE,
	OPERATIONS_REP_NAME,
	CONSUMER_ENQ_PHONE,
	ORDER_FORM,
	LANGUAGE,
	TERRITORY,
	SELLING_METHOD,
	LOC_CODE,
	LOW_GRADE,
	ACCOUNT_NAME,
	REMINDER_POSTCARD,
	RISK_TEXT,
	FAX,
	CREATED_BY,
	STATUS,
	REPORT_GRP,
	SERVICE_PRODUCT_SORT,
	SHIP_TO,
	PROCESSING_LAB,
	SCHOOL_YR_END,
	ID,
	PHOTO_LOCATION,
	APO_TAG,
	RISK_CODE,
	OFFER_ONLINE_ORDERING,
	PHONE_ORDER,
	BOOKING_YEAR,
	SALES_REP_CODE,
	DESCRIPTION,
	REVISION_NO,
	HIGH_GRADE,
	CONSUMER_MODEL,
	SUB_PROGRAM,
	PUBLISHED,
	PHONE,
	TAX_CERTIFICATE,
	BOOKING_OPP_ID,
	ORDER_FORM_ITEM_ID,
	DEFAULT_ORD_PKG,
	DATE_CREATED,
	VISION_JOB,
	SVC_PROD_MODEL,
	BUS_CONTEXT_NAME,
	PROGRAM,
	NACAM_OVERALL,
	JOB_IDENTIFIER,
	TAX_EXEMPT,
	SALES_REP_NAME,
	UPDATED_BY,
	LAST_UPDATED,
	ENROLLMENT_COUNT,
	TWO_WEEK_RETURN_MSG,
	CONSUMER_SORT,
	PROOF_EXPRESS,
	CONTACT,
	SERVICE_CENTER,
	CURRENCY,
	LAB_INSTRUCTIONS,
	LID,
	COPIED_FROM_ODS,
	CONTRACT_RECEIVED,
	APO_TYPE,
	YB_PROGRAM,
	SALES_REP_EMAIL,
	FINALIZED_DATE,
	COVER_RECEIVED,
	SALE_TYPE,
	ENABLE_PRISM,
	BOOK_OFFERING,
	INCENTIVE_GRANTED,
	CONTRACT_STATUS,
	ALLOW_EXTRA_COVERAGE_DEADLINE,
	PRODUCT_RELEASE_COMPLETED_BY,
	PRODUCT_RELEASE_COMPLETED_DATE,
	COVER_DETAILS_PROVIDED,
	COVER_APPROVED,
	SIGNING_INFO,
	YB_ENROLLED,
	YB_ENROLLED_DATE,
	LIFETOUCH_PHOTOGRAPHED   
   
FROM (	


select 	
	C1_CAMERA_PLATFORM CAMERA_PLATFORM,
	C2_CONFIRMED_LAB CONFIRMED_LAB,
	C3_COUNTRY COUNTRY,
	C4_POSTAL_CODE POSTAL_CODE,
	C5_CITY CITY,
	C6_ADDRESS ADDRESS,
	C7_COUNTY COUNTY,
	C8_VERSION VERSION,
	C9_FINANCIAL_PROCESSING_SYSTEM FINANCIAL_PROCESSING_SYSTEM,
	C10_RISK_IND RISK_IND,
	C11_LANGUAGE2 LANGUAGE2,
	C12_FULFILLING_LAB_SYSTEM FULFILLING_LAB_SYSTEM,
	C13_ENVELOPE_ID ENVELOPE_ID,
	C14_SUBCATEGORY SUBCATEGORY,
	C15_ORIGINAL_BOOKING_REP ORIGINAL_BOOKING_REP,
	C16_VALIDATION_ERROR VALIDATION_ERROR,
	C17_ORIGINAL_BOOKING_REP_NAME ORIGINAL_BOOKING_REP_NAME,
	C18_LOCK_ON_NAME LOCK_ON_NAME,
	C19_CATEGORY CATEGORY,
	C20_EST_TO_BE_PHOTOED EST_TO_BE_PHOTOED,
	C21_MARKETING_CODE MARKETING_CODE,
	C22_OPERATIONS_REP_NAME OPERATIONS_REP_NAME,
	C23_CONSUMER_ENQ_PHONE CONSUMER_ENQ_PHONE,
	C24_ORDER_FORM ORDER_FORM,
	C25_LANGUAGE LANGUAGE,
	C26_TERRITORY TERRITORY,
	C27_SELLING_METHOD SELLING_METHOD,
	C28_LOC_CODE LOC_CODE,
	C29_LOW_GRADE LOW_GRADE,
	C30_ACCOUNT_NAME ACCOUNT_NAME,
	C31_REMINDER_POSTCARD REMINDER_POSTCARD,
	C32_RISK_TEXT RISK_TEXT,
	C33_FAX FAX,
	C34_CREATED_BY CREATED_BY,
	C35_STATUS STATUS,
	C36_REPORT_GRP REPORT_GRP,
	C37_SERVICE_PRODUCT_SORT SERVICE_PRODUCT_SORT,
	C38_SHIP_TO SHIP_TO,
	C39_PROCESSING_LAB PROCESSING_LAB,
	C40_SCHOOL_YR_END SCHOOL_YR_END,
	C41_ID ID,
	C42_PHOTO_LOCATION PHOTO_LOCATION,
	C43_APO_TAG APO_TAG,
	C44_RISK_CODE RISK_CODE,
	C45_OFFER_ONLINE_ORDERING OFFER_ONLINE_ORDERING,
	C46_PHONE_ORDER PHONE_ORDER,
	C47_BOOKING_YEAR BOOKING_YEAR,
	C48_SALES_REP_CODE SALES_REP_CODE,
	C49_DESCRIPTION DESCRIPTION,
	C50_REVISION_NO REVISION_NO,
	C51_HIGH_GRADE HIGH_GRADE,
	C52_CONSUMER_MODEL CONSUMER_MODEL,
	C53_SUB_PROGRAM SUB_PROGRAM,
	C54_PUBLISHED PUBLISHED,
	C55_PHONE PHONE,
	C56_TAX_CERTIFICATE TAX_CERTIFICATE,
	C57_BOOKING_OPP_ID BOOKING_OPP_ID,
	C58_ORDER_FORM_ITEM_ID ORDER_FORM_ITEM_ID,
	C59_DEFAULT_ORD_PKG DEFAULT_ORD_PKG,
	C60_DATE_CREATED DATE_CREATED,
	C61_VISION_JOB VISION_JOB,
	C62_SVC_PROD_MODEL SVC_PROD_MODEL,
	C63_BUS_CONTEXT_NAME BUS_CONTEXT_NAME,
	C64_PROGRAM PROGRAM,
	C65_NACAM_OVERALL NACAM_OVERALL,
	C66_JOB_IDENTIFIER JOB_IDENTIFIER,
	C67_TAX_EXEMPT TAX_EXEMPT,
	C68_SALES_REP_NAME SALES_REP_NAME,
	C69_UPDATED_BY UPDATED_BY,
	C70_LAST_UPDATED LAST_UPDATED,
	C71_ENROLLMENT_COUNT ENROLLMENT_COUNT,
	C72_TWO_WEEK_RETURN_MSG TWO_WEEK_RETURN_MSG,
	C73_CONSUMER_SORT CONSUMER_SORT,
	C74_PROOF_EXPRESS PROOF_EXPRESS,
	C75_CONTACT CONTACT,
	C76_SERVICE_CENTER SERVICE_CENTER,
	C77_CURRENCY CURRENCY,
	C78_LAB_INSTRUCTIONS LAB_INSTRUCTIONS,
	C79_LID LID,
	C80_COPIED_FROM_ODS COPIED_FROM_ODS,
	C81_CONTRACT_RECEIVED CONTRACT_RECEIVED,
	C82_APO_TYPE APO_TYPE,
	C83_YB_PROGRAM YB_PROGRAM,
	C84_SALES_REP_EMAIL SALES_REP_EMAIL,
	C85_FINALIZED_DATE FINALIZED_DATE,
	C86_COVER_RECEIVED COVER_RECEIVED,
	C87_SALE_TYPE SALE_TYPE,
	C88_ENABLE_PRISM ENABLE_PRISM,
	C89_BOOK_OFFERING BOOK_OFFERING,
	C90_INCENTIVE_GRANTED INCENTIVE_GRANTED,
	C91_CONTRACT_STATUS CONTRACT_STATUS,
	C92_ALLOW_EXTRA_COVERAGE_DEADL ALLOW_EXTRA_COVERAGE_DEADLINE,
	C93_PRODUCT_RELEASE_COMPLETED_ PRODUCT_RELEASE_COMPLETED_BY,
	C94_PRODUCT_RELEASE_COMPLETED_ PRODUCT_RELEASE_COMPLETED_DATE,
	C95_COVER_DETAILS_PROVIDED COVER_DETAILS_PROVIDED,
	C96_COVER_APPROVED COVER_APPROVED,
	C97_SIGNING_INFO SIGNING_INFO,
	C98_YB_ENROLLED YB_ENROLLED,
	C99_YB_ENROLLED_DATE YB_ENROLLED_DATE,
	C100_LIFETOUCH_PHOTOGRAPHED LIFETOUCH_PHOTOGRAPHED 
from	RAX_APP_USER.C$_0STG_FOW_APO
where		(1=1)	






)    ODI_GET_FROM




&


/*-----------------------------------------------*/
/* TASK No. 12 */
/* Commit transaction */

/* commit */


/*-----------------------------------------------*/
/* TASK No. 1000008 */
/* Drop work table */

BEGIN  
   EXECUTE IMMEDIATE 'drop table RAX_APP_USER.C$_0STG_FOW_APO';  
EXCEPTION  
   WHEN OTHERS THEN  
      IF SQLCODE != -942 THEN  
         RAISE;  
      END IF;  
END;

&


/*-----------------------------------------------*/
/* TASK No. 13 */
/* MERGE INTO ODS_STAGE.APO_XR */

-- fow_xr
MERGE INTO ODS_STAGE.APO_XR d
USING (
select * from
    (  Select
    apo.apo_oid as apo_apo_oid,xr.apo_oid as xr_apo_oid,
    nvl(apo.apo_oid,xr.apo_oid) apo_oid,
    COPIED_FROM_ODS,
    case when xr.SYSTEM_OF_RECORD in ('OMS2','APOCS') then xr.SYSTEM_OF_RECORD 
         when nvl(COPIED_FROM_ODS,'N') <> 'Y' then 'FOW'
         else xr.SYSTEM_OF_RECORD 
    end as SYSTEM_OF_RECORD,
        STG.APO_TAG as APO_ID,
        xr.APOCS_SK_APO_ID,
        STG.ID as FOW_SK_ID,
        xr.OMS2_SK_BUSINESS_KEY,
        xr.LPIP_SK_APO_ID,
        xr.ODS_SK_FAUX_APO_ID,
        case when xr.SYSTEM_OF_RECORD in ('OMS2','APOCS') or nvl(COPIED_FROM_ODS,'N') = 'Y' then xr.SCHOOL_YEAR else STG.SCHOOL_YR_END end as SCHOOL_YEAR,
        case when xr.SYSTEM_OF_RECORD in ('OMS2','APOCS') or nvl(COPIED_FROM_ODS,'N') = 'Y' then xr.PRICE_PROGRAM_NAME else off.PRICE_PROGRAM_ID end as PRICE_PROGRAM_NAME,
        case when xr.SYSTEM_OF_RECORD in ('OMS2','APOCS') or nvl(COPIED_FROM_ODS,'N') = 'Y' then xr.LIFETOUCH_ID else STG.LID end as LIFETOUCH_ID,
        case when xr.SYSTEM_OF_RECORD in ('OMS2','APOCS') or nvl(COPIED_FROM_ODS,'N') = 'Y' then xr.SUB_PROGRAM_NAME else STG.SUB_PROGRAM end as SUB_PROGRAM_NAME,
        case when xr.SYSTEM_OF_RECORD in ('OMS2','APOCS') or nvl(COPIED_FROM_ODS,'N') = 'Y' then xr.TERRITORY_CODE else STG.TERRITORY end as TERRITORY_CODE,
        case when xr.SYSTEM_OF_RECORD in ('OMS2','APOCS') or nvl(COPIED_FROM_ODS,'N') = 'Y' then xr.VISUAL_MERCH_ID else OFF.VISUAL_MERCH_ID end as VISUAL_MERCH_ID,
        case when xr.SYSTEM_OF_RECORD in ('OMS2','APOCS') or nvl(COPIED_FROM_ODS,'N') = 'Y' then xr.SELLING_METHOD else STG.SELLING_METHOD end as SELLING_METHOD,
        STG.BOOKING_OPP_ID as BOOKING_OPP_ID,   /* FOW always wins here */
        sysdate as ODS_CREATE_DATE,
        sysdate as ODS_MODIFY_DATE
    -- select *
    FROM 
        RAX_APP_USER.STG_FOW_APO stg
        ,ODS_STAGE.FOW_OFFERING_STG off
        ,ODS_OWN.APO apo
        ,ODS_STAGE.APO_XR xr
    WHERE (1=1)
        and off.ID(+) = STG.ID
        and stg.APO_TAG=APO.APO_ID(+)
        and stg.APO_TAG=XR.APO_ID(+)
     ) s
where NOT EXISTS 
	( select 1 from ODS_STAGE.APO_XR T
	where	T.APO_ID	= S.APO_ID 
		 and
		((T.APO_OID = S.APO_OID) or (T.APO_OID IS NULL and S.APO_OID IS NULL))  and
		((T.FOW_SK_ID = S.FOW_SK_ID) or (T.FOW_SK_ID IS NULL and S.FOW_SK_ID IS NULL)) and
		((T.SYSTEM_OF_RECORD = S.SYSTEM_OF_RECORD) or (T.SYSTEM_OF_RECORD IS NULL and S.SYSTEM_OF_RECORD IS NULL))  and
		((T.SCHOOL_YEAR = S.SCHOOL_YEAR) or (T.SCHOOL_YEAR IS NULL and S.SCHOOL_YEAR IS NULL))  and
		((T.PRICE_PROGRAM_NAME = S.PRICE_PROGRAM_NAME) or (T.PRICE_PROGRAM_NAME IS NULL and S.PRICE_PROGRAM_NAME IS NULL))  and
		((T.LIFETOUCH_ID = S.LIFETOUCH_ID) or (T.LIFETOUCH_ID IS NULL and S.LIFETOUCH_ID IS NULL))  and
		((T.SUB_PROGRAM_NAME = S.SUB_PROGRAM_NAME) or (T.SUB_PROGRAM_NAME IS NULL and S.SUB_PROGRAM_NAME IS NULL))  and
		((T.TERRITORY_CODE = S.TERRITORY_CODE) or (T.TERRITORY_CODE IS NULL and S.TERRITORY_CODE IS NULL))  and
		((T.VISUAL_MERCH_ID = S.VISUAL_MERCH_ID) or (T.VISUAL_MERCH_ID IS NULL and S.VISUAL_MERCH_ID IS NULL))  and
		((T.SELLING_METHOD = S.SELLING_METHOD) or (T.SELLING_METHOD IS NULL and S.SELLING_METHOD IS NULL))  and
    ((T.BOOKING_OPP_ID = S.BOOKING_OPP_ID) or (T.BOOKING_OPP_ID IS NULL and S.BOOKING_OPP_ID IS NULL)) 
        )
) s 
ON
  (s.APO_ID=d.APO_ID)
WHEN MATCHED
THEN
UPDATE SET
  d.APO_OID = s.APO_OID,
  d.FOW_SK_ID = s.FOW_SK_ID,
  d.SYSTEM_OF_RECORD = s.SYSTEM_OF_RECORD,
  d.SCHOOL_YEAR = s.SCHOOL_YEAR,
  d.PRICE_PROGRAM_NAME = s.PRICE_PROGRAM_NAME,
  d.LIFETOUCH_ID = s.LIFETOUCH_ID,
  d.SUB_PROGRAM_NAME = s.SUB_PROGRAM_NAME,
  d.TERRITORY_CODE = s.TERRITORY_CODE,
  d.VISUAL_MERCH_ID = s.VISUAL_MERCH_ID,
  d.SELLING_METHOD = s.SELLING_METHOD,
  d.BOOKING_OPP_ID = s.BOOKING_OPP_ID,
  d.ODS_MODIFY_DATE = s.ODS_MODIFY_DATE
WHEN NOT MATCHED
THEN
INSERT (
  APO_OID, APO_ID, APOCS_SK_APO_ID,SYSTEM_OF_RECORD,
  FOW_SK_ID, OMS2_SK_BUSINESS_KEY, LPIP_SK_APO_ID,ODS_SK_FAUX_APO_ID,
  SCHOOL_YEAR, PRICE_PROGRAM_NAME, LIFETOUCH_ID,
  SUB_PROGRAM_NAME, TERRITORY_CODE, VISUAL_MERCH_ID,
  SELLING_METHOD, BOOKING_OPP_ID, ODS_CREATE_DATE, ODS_MODIFY_DATE)
VALUES (
  nvl(s.apo_oid,ODS_STAGE.APO_OID_SEQ.nextval), s.APO_ID, s.APOCS_SK_APO_ID,s.SYSTEM_OF_RECORD,
  s.FOW_SK_ID, s.OMS2_SK_BUSINESS_KEY, s.LPIP_SK_APO_ID,s.ODS_SK_FAUX_APO_ID,
  s.SCHOOL_YEAR, s.PRICE_PROGRAM_NAME, s.LIFETOUCH_ID,
  s.SUB_PROGRAM_NAME, s.TERRITORY_CODE, s.VISUAL_MERCH_ID,
  s.SELLING_METHOD,s.BOOKING_OPP_ID, s.ODS_CREATE_DATE, s.ODS_MODIFY_DATE)

&


/*-----------------------------------------------*/
/* TASK No. 14 */
/* Override when Selling Method = Service Non Rev */

--
-- Handles rare scenario where APO is sourced from APOCS before FOW
-- 
MERGE INTO ODS_STAGE.APO_XR t
     USING (SELECT xr.APO_OID, s.SELLING_METHOD
              FROM RAX_APP_USER.STG_FOW_APO s, 
                          ODS_STAGE.APO_XR xr
             WHERE     s.APO_TAG = xr.APO_ID
                   AND s.SELLING_METHOD = 'Service Non Rev') s
        ON (t.apo_oid = s.apo_oid)
WHEN MATCHED
THEN
    UPDATE SET
        t.selling_method = s.selling_method,
        t.ods_modify_date = SYSDATE
             WHERE DECODE (t.SELLING_METHOD, s.SELLING_METHOD, 1, 0) = 0

&


/*-----------------------------------------------*/
/* TASK No. 15 */
/* MERGE INTO ODS_OWN.APO */

  -- FOW
MERGE INTO ODS_OWN.APO d
USING (
select * from (
      Select
        xr.APO_OID as APO_OID,
        xr.APO_ID as APO_ID,
        xr.SYSTEM_OF_RECORD,
        nvl(acc.ACCOUNT_OID,-1) as ACCOUNT_OID,
        XR.SCHOOL_YEAR as SCHOOL_YEAR,
        nvl(SP.SUB_PROGRAM_OID,-1) as SUB_PROGRAM_OID,
        nvl(ORG.ORGANIZATION_OID,-1) as ORGANIZATION_OID,
        STG.DESCRIPTION as DESCRIPTION,
        XR.LIFETOUCH_ID as LIFETOUCH_ID,
        XR.TERRITORY_CODE as TERRITORY_CODE,
        XR.SELLING_METHOD as SELLING_METHOD,
--        STG.PROCESSING_LAB as PROCESSING_LAB,
case 
    when STG.APO_TYPE in ('Shutterware') then nvl(STG.PROCESSING_LAB,'Chattanooga')
    when STG.APO_TYPE in ('Infinity') then nvl(STG.PROCESSING_LAB,'Minneapolis')
    else STG.PROCESSING_LAB 
end as PROCESSING_LAB,
        trim(STG.PHOTO_LOCATION) as PHOTOGAPHY_LOCIATION,
        substr(STG.VISION_JOB,1,40) as VISION_JOB_NO,
        VM.VISUAL_MERCH_OID as VISUAL_MERCH_OID,
        XR.PRICE_PROGRAM_NAME as PRICE_PROGRAM_NAME,
        STG.MARKETING_CODE as MARKETING_CODE,
        sysdate as ODS_CREATE_DATE,
        sysdate as ODS_MODIFY_DATE,
        SS.SOURCE_SYSTEM_OID as SOURCE_SYSTEM_OID,
        STG.FULFILLING_LAB_SYSTEM as FULFILLING_LAB_SYSTEM,
        case when dc.data_center_name is null 
                         then STG.FINANCIAL_PROCESSING_SYSTEM
                when ((org_vw.business_unit_name like '%' || dc.data_center_name || '%')
                   or (nvl(dc.data_center_name,'United States') = 'United States' and org_vw.BUSINESS_UNIT_NAME = 'Lifetouch Preschool Portraits')
                     ) then STG.FINANCIAL_PROCESSING_SYSTEM 
                else 'OtherSRM' 
/*                when org_vw.business_unit_name like '%' || dc.data_center_name || '%'
                         then STG.FINANCIAL_PROCESSING_SYSTEM
                         else 'GDT'
*/
        end as FINANCIAL_PROCESSING_SYSTEM,
        PP.PRICE_PROGRAM_OID as PRICE_PROGRAM_OID,
        STG.OPERATIONS_REP_NAME as OPERATIONS_REP_NAME,
        STG.ORIGINAL_BOOKING_REP as ORIGINAL_BOOKING_REP,
        STG.ORIGINAL_BOOKING_REP_NAME as ORIGINAL_BOOKING_REP_NAME,
        STG.ENROLLMENT_COUNT as ESTIMATED_ENROLLMENT,
        STG.CAMERA_PLATFORM as CAMERA_PLATFORM,
        STG.STATUS as STATUS,
        SM.SELLING_METHOD_OID as SELLING_METHOD_OID,
         STG.TAX_EXEMPT as IS_TAX_EXEMPT,
        xr.APOCS_SK_APO_ID,
       bo.BOOKING_OPPORTUNITY_OID as BOOKING_OPP_OID
       ,stg.CONTRACT_RECEIVED
       ,stg.APO_TYPE
       ,stg.YB_PROGRAM
       ,stg.SALES_REP_NAME
       ,stg.SALES_REP_EMAIL
        --select *
        ,stg.PROGRAM as BOOKING_PROGRAM
        ,stg.finalized_date
        ,stg.cover_received
        ,stg.book_offering
        ,stg.last_updated
       ,stg.SIGNING_INFO
      ,stg.INCENTIVE_GRANTED
      ,stg.HIGH_GRADE
      ,stg.LOW_GRADE
      ,stg.LIFETOUCH_PHOTOGRAPHED
,stg.product_release_completed_date
,stg.product_release_completed_by
    from
        RAX_APP_USER.STG_FOW_APO stg
        ,ODS_STAGE.APO_XR xr 
        ,ODS_OWN.ACCOUNT acc
        ,ODS_OWN.SUB_PROGRAM sp
        ,ODS_OWN.ORGANIZATION org
        ,ODS_OWN.VISUAL_MERCH vm
        ,ODS_OWN.SOURCE_SYSTEM ss
        ,ODS_OWN.PRICE_PROGRAM pp
        ,ODS_OWN.SELLING_METHOD sm
        ,ODS_OWN.BOOKING_OPPORTUNITY bo
        ,ODS_OWN.ORGANIZATION_VW org_vw
        ,ODS_OWN.DATA_CENTER dc
     where (1=1)
        and STG.APO_TAG=XR.APO_ID
        and xr.LIFETOUCH_ID=acc.LIFETOUCH_ID(+)
        and XR.SUB_PROGRAM_NAME=SP.SUB_PROGRAM_NAME(+)
        and XR.TERRITORY_CODE=ORG.ORG_CODE(+)
        and XR.VISUAL_MERCH_ID=VM.VISUAL_MERCH_ID(+)
        and SS.SOURCE_SYSTEM_SHORT_NAME='FOW'
        and XR.PRICE_PROGRAM_NAME=PP.PRICE_PROGRAM_NAME(+)
        and XR.SELLING_METHOD=SM.SELLING_METHOD(+)
        and XR.BOOKING_OPP_ID=BO.BOOKING_OPP_KEY(+)
        and org.org_code = org_vw.territory_code(+)
        and xr.SYSTEM_OF_RECORD = 'FOW'
        ) s
where NOT EXISTS 
    ( select 1 from ODS_OWN.APO T
    where    T.APO_OID    = S.APO_OID 
         and ((T.APO_ID = S.APO_ID) or (T.APO_ID IS NULL and S.APO_ID IS NULL)) and
        ((T.ACCOUNT_OID = S.ACCOUNT_OID) or (T.ACCOUNT_OID IS NULL and S.ACCOUNT_OID IS NULL)) and
        ((T.SCHOOL_YEAR = S.SCHOOL_YEAR) or (T.SCHOOL_YEAR IS NULL and S.SCHOOL_YEAR IS NULL)) and
        ((T.SUB_PROGRAM_OID = S.SUB_PROGRAM_OID) or (T.SUB_PROGRAM_OID IS NULL and S.SUB_PROGRAM_OID IS NULL)) and
        ((T.ORGANIZATION_OID = S.ORGANIZATION_OID) or (T.ORGANIZATION_OID IS NULL and S.ORGANIZATION_OID IS NULL)) and
        ((T.DESCRIPTION = S.DESCRIPTION) or (T.DESCRIPTION IS NULL and S.DESCRIPTION IS NULL)) and
        ((T.LIFETOUCH_ID = S.LIFETOUCH_ID) or (T.LIFETOUCH_ID IS NULL and S.LIFETOUCH_ID IS NULL)) and
        ((T.TERRITORY_CODE = S.TERRITORY_CODE) or (T.TERRITORY_CODE IS NULL and S.TERRITORY_CODE IS NULL)) and
        ((T.SELLING_METHOD = S.SELLING_METHOD) or (T.SELLING_METHOD IS NULL and S.SELLING_METHOD IS NULL)) and
        ((T.PROCESSING_LAB = S.PROCESSING_LAB) or (T.PROCESSING_LAB IS NULL and S.PROCESSING_LAB IS NULL)) and
        ((T.PHOTOGAPHY_LOCIATION = S.PHOTOGAPHY_LOCIATION) or (T.PHOTOGAPHY_LOCIATION IS NULL and S.PHOTOGAPHY_LOCIATION IS NULL)) and
        ((T.VISION_JOB_NO = S.VISION_JOB_NO) or (T.VISION_JOB_NO IS NULL and S.VISION_JOB_NO IS NULL)) and
        ((T.VISUAL_MERCH_OID = S.VISUAL_MERCH_OID) or (T.VISUAL_MERCH_OID IS NULL and S.VISUAL_MERCH_OID IS NULL)) and
        ((T.PRICE_PROGRAM_NAME = S.PRICE_PROGRAM_NAME) or (T.PRICE_PROGRAM_NAME IS NULL and S.PRICE_PROGRAM_NAME IS NULL)) and
        ((T.MARKETING_CODE = S.MARKETING_CODE) or (T.MARKETING_CODE IS NULL and S.MARKETING_CODE IS NULL)) and
        ((T.SOURCE_SYSTEM_OID = S.SOURCE_SYSTEM_OID) or (T.SOURCE_SYSTEM_OID IS NULL and S.SOURCE_SYSTEM_OID IS NULL)) and
        ((T.FULFILLING_LAB_SYSTEM = S.FULFILLING_LAB_SYSTEM) or (T.FULFILLING_LAB_SYSTEM IS NULL and S.FULFILLING_LAB_SYSTEM IS NULL)) and
        ((T.FINANCIAL_PROCESSING_SYSTEM = S.FINANCIAL_PROCESSING_SYSTEM) or (T.FINANCIAL_PROCESSING_SYSTEM IS NULL and S.FINANCIAL_PROCESSING_SYSTEM IS NULL)) and
        ((T.PRICE_PROGRAM_OID = S.PRICE_PROGRAM_OID) or (T.PRICE_PROGRAM_OID IS NULL and S.PRICE_PROGRAM_OID IS NULL)) and
        ((T.OPERATIONS_REP_NAME = S.OPERATIONS_REP_NAME) or (T.OPERATIONS_REP_NAME IS NULL and S.OPERATIONS_REP_NAME IS NULL)) and
        ((T.ORIGINAL_BOOKING_REP = S.ORIGINAL_BOOKING_REP) or (T.ORIGINAL_BOOKING_REP IS NULL and S.ORIGINAL_BOOKING_REP IS NULL)) and
        ((T.ORIGINAL_BOOKING_REP_NAME = S.ORIGINAL_BOOKING_REP_NAME) or (T.ORIGINAL_BOOKING_REP_NAME IS NULL and S.ORIGINAL_BOOKING_REP_NAME IS NULL)) and
        ((T.ESTIMATED_ENROLLMENT = S.ESTIMATED_ENROLLMENT) or (T.ESTIMATED_ENROLLMENT IS NULL and S.ESTIMATED_ENROLLMENT IS NULL)) and
        ((T.CAMERA_PLATFORM = S.CAMERA_PLATFORM) or (T.CAMERA_PLATFORM IS NULL and S.CAMERA_PLATFORM IS NULL)) and
        ((T.STATUS = S.STATUS) or (T.STATUS IS NULL and S.STATUS IS NULL)) and
        ((T.SELLING_METHOD_OID = S.SELLING_METHOD_OID) or (T.SELLING_METHOD_OID IS NULL and S.SELLING_METHOD_OID IS NULL)) and
        ((T.IS_TAX_EXEMPT = S.IS_TAX_EXEMPT) or (T.IS_TAX_EXEMPT IS NULL and S.IS_TAX_EXEMPT IS NULL)) and
        ((T.CONTRACT_RECEIVED = S.CONTRACT_RECEIVED) or (T.CONTRACT_RECEIVED IS NULL and S.CONTRACT_RECEIVED IS NULL)) and
          ((T.BOOKING_OPP_OID = S.BOOKING_OPP_OID) or (T.BOOKING_OPP_OID IS NULL and S.BOOKING_OPP_OID IS NULL)) and
          ((T.YB_PROGRAM = S.YB_PROGRAM) or (T.YB_PROGRAM IS NULL and S.YB_PROGRAM IS NULL)) and
         ((T.APO_TYPE = S.APO_TYPE) or (T.APO_TYPE IS NULL and S.APO_TYPE IS NULL)) and 
         ((T.SALES_REP_NAME = S.SALES_REP_NAME) or (T.SALES_REP_NAME IS NULL and S.SALES_REP_NAME IS NULL)) and
         ((T.SALES_REP_EMAIL = S.SALES_REP_EMAIL) or (T.SALES_REP_EMAIL IS NULL and S.SALES_REP_EMAIL IS NULL)) and
          ((T.BOOKING_PROGRAM = S.BOOKING_PROGRAM) or (T.BOOKING_PROGRAM IS NULL and S.BOOKING_PROGRAM IS NULL)) and
          ((T.FINALIZED_DATE = S.FINALIZED_DATE) or (T.FINALIZED_DATE IS NULL and S.FINALIZED_DATE IS NULL)) and
          ((T.COVER_RECEIVED = S.COVER_RECEIVED) or (T.COVER_RECEIVED IS NULL and S.COVER_RECEIVED IS NULL)) and
          ((T.BOOK_OFFERING = S.BOOK_OFFERING) or (T.BOOK_OFFERING IS NULL and S.BOOK_OFFERING IS NULL)) and 
          ((T.LAST_UPDATED = S.LAST_UPDATED) or (T.LAST_UPDATED IS NULL and S.LAST_UPDATED IS NULL)) and
	 ((T.SIGNING_INFO = S.SIGNING_INFO) or (T.SIGNING_INFO IS NULL and S.SIGNING_INFO IS NULL)) and 
	 ((T.INCENTIVE_GRANTED = S.INCENTIVE_GRANTED) or (T.INCENTIVE_GRANTED IS NULL and S.INCENTIVE_GRANTED IS NULL))  and
  	((T.HIGH_GRADE = S.HIGH_GRADE) or (T.HIGH_GRADE IS NULL and S.HIGH_GRADE IS NULL)) and
	((T.LOW_GRADE = S.LOW_GRADE) or (T.LOW_GRADE IS NULL and S.LOW_GRADE IS NULL)) and
                     ((T.LIFETOUCH_PHOTOGRAPHED = S.LIFETOUCH_PHOTOGRAPHED) or (T.LIFETOUCH_PHOTOGRAPHED IS NULL and S.LIFETOUCH_PHOTOGRAPHED IS NULL)) and
                     ((T.product_release_completed_date = S.product_release_completed_date) or (T.product_release_completed_date IS NULL and S.product_release_completed_date IS NULL)) and
                     ((T.product_release_completed_by = S.product_release_completed_by) or (T.product_release_completed_by IS NULL and S.product_release_completed_by IS NULL))
        )
) s ON
  (d.APO_ID = s.APO_ID)
WHEN MATCHED
THEN
UPDATE SET
  d.ACCOUNT_OID = s.ACCOUNT_OID,
  d.SCHOOL_YEAR = s.SCHOOL_YEAR,
  d.SUB_PROGRAM_OID = s.SUB_PROGRAM_OID,
  d.ORGANIZATION_OID = s.ORGANIZATION_OID,
  d.DESCRIPTION = s.DESCRIPTION,
  d.LIFETOUCH_ID = s.LIFETOUCH_ID,
  d.TERRITORY_CODE = s.TERRITORY_CODE,
  d.SELLING_METHOD = s.SELLING_METHOD,
  d.PROCESSING_LAB = s.PROCESSING_LAB,
  d.PHOTOGAPHY_LOCIATION = s.PHOTOGAPHY_LOCIATION,
  d.VISION_JOB_NO = s.VISION_JOB_NO,
  d.VISUAL_MERCH_OID = s.VISUAL_MERCH_OID,
  d.PRICE_PROGRAM_NAME = s.PRICE_PROGRAM_NAME,
  d.MARKETING_CODE = s.MARKETING_CODE,
  d.ODS_MODIFY_DATE = s.ODS_MODIFY_DATE,
  d.SOURCE_SYSTEM_OID = s.SOURCE_SYSTEM_OID,
  d.FULFILLING_LAB_SYSTEM = s.FULFILLING_LAB_SYSTEM,
  d.FINANCIAL_PROCESSING_SYSTEM = s.FINANCIAL_PROCESSING_SYSTEM,
  d.PRICE_PROGRAM_OID = s.PRICE_PROGRAM_OID,
  d.OPERATIONS_REP_NAME = s.OPERATIONS_REP_NAME,
  d.ORIGINAL_BOOKING_REP = s.ORIGINAL_BOOKING_REP,
  d.ORIGINAL_BOOKING_REP_NAME = s.ORIGINAL_BOOKING_REP_NAME,
  d.ESTIMATED_ENROLLMENT = s.ESTIMATED_ENROLLMENT,
  d.CAMERA_PLATFORM = s.CAMERA_PLATFORM,
  d.STATUS = s.STATUS,
  d.SELLING_METHOD_OID = s.SELLING_METHOD_OID,
  d.IS_TAX_EXEMPT = s.IS_TAX_EXEMPT,
  d.CONTRACT_RECEIVED = s.CONTRACT_RECEIVED,
  d.BOOKING_OPP_OID = S.BOOKING_OPP_OID,
  d.YB_PROGRAM = S.YB_PROGRAM,
  d.APO_TYPE = s.APO_TYPE,
  d.SALES_REP_NAME = s.SALES_REP_NAME,
  d.SALES_REP_EMAIL = s.SALES_REP_EMAIL,
  d.BOOKING_PROGRAM = s.BOOKING_PROGRAM,
  d.FINALIZED_DATE = s.FINALIZED_DATE,
  d.COVER_RECEIVED = s.COVER_RECEIVED,
  d.BOOK_OFFERING = s.BOOK_OFFERING,
 d.LAST_UPDATED = s.LAST_UPDATED,
 d.SIGNING_INFO  = s.SIGNING_INFO,
  d.INCENTIVE_GRANTED  = s.INCENTIVE_GRANTED,
  d.HIGH_GRADE=s.HIGH_GRADE,
  d.LOW_GRADE=s.LOW_GRADE,
  d.LIFETOUCH_PHOTOGRAPHED = s.LIFETOUCH_PHOTOGRAPHED,
  d.product_release_completed_date = s.product_release_completed_date,
  d.product_release_completed_by = s.product_release_completed_date
WHEN NOT MATCHED
THEN
INSERT (
    APO_OID
    ,APO_ID 
    ,ACCOUNT_OID
    ,SCHOOL_YEAR
    ,SUB_PROGRAM_OID 
    ,ORGANIZATION_OID
    ,DESCRIPTION
    ,LIFETOUCH_ID
    ,TERRITORY_CODE 
    ,SELLING_METHOD 
    ,PROCESSING_LAB
    ,PHOTOGAPHY_LOCIATION 
    ,VISION_JOB_NO
    ,VISUAL_MERCH_OID
    ,PRICE_PROGRAM_NAME
    ,MARKETING_CODE
    ,ODS_CREATE_DATE
    ,ODS_MODIFY_DATE 
    ,SOURCE_SYSTEM_OID
    ,FULFILLING_LAB_SYSTEM 
    ,FINANCIAL_PROCESSING_SYSTEM
    ,PRICE_PROGRAM_OID
    ,OPERATIONS_REP_NAME
    ,ORIGINAL_BOOKING_REP 
    ,ORIGINAL_BOOKING_REP_NAME
    ,ESTIMATED_ENROLLMENT
    ,CAMERA_PLATFORM 
    ,STATUS
    ,SELLING_METHOD_OID
    ,IS_TAX_EXEMPT
    ,CONTRACT_RECEIVED
    ,BOOKING_OPP_OID
    ,YB_PROGRAM
   ,APO_TYPE
   ,SALES_REP_NAME
   ,SALES_REP_EMAIL
   ,BOOKING_PROGRAM
   ,FINALIZED_DATE
   ,COVER_RECEIVED
   ,BOOK_OFFERING
   ,LAST_UPDATED
   , SIGNING_INFO
  , INCENTIVE_GRANTED
  ,HIGH_GRADE
  ,LOW_GRADE
  ,LIFETOUCH_PHOTOGRAPHED
,product_release_completed_date
,product_release_completed_by
  )
VALUES (
    s.APO_OID
    ,s.APO_ID 
    ,s.ACCOUNT_OID
    ,s.SCHOOL_YEAR
    ,s.SUB_PROGRAM_OID 
    ,s.ORGANIZATION_OID
    ,s.DESCRIPTION
    ,s.LIFETOUCH_ID
    ,s.TERRITORY_CODE 
    ,s.SELLING_METHOD 
    ,s.PROCESSING_LAB
    ,s.PHOTOGAPHY_LOCIATION 
    ,s.VISION_JOB_NO
    ,s.VISUAL_MERCH_OID
    ,s.PRICE_PROGRAM_NAME
    ,s.MARKETING_CODE
    ,s.ODS_CREATE_DATE
    ,s.ODS_MODIFY_DATE 
    ,s.SOURCE_SYSTEM_OID
    ,s.FULFILLING_LAB_SYSTEM 
    ,s.FINANCIAL_PROCESSING_SYSTEM
    ,s.PRICE_PROGRAM_OID
    ,s.OPERATIONS_REP_NAME
    ,s.ORIGINAL_BOOKING_REP 
    ,s.ORIGINAL_BOOKING_REP_NAME
    ,s.ESTIMATED_ENROLLMENT
    ,s.CAMERA_PLATFORM 
    ,s.STATUS
    ,s.SELLING_METHOD_OID
    ,s.IS_TAX_EXEMPT
    ,s.CONTRACT_RECEIVED
    ,s.BOOKING_OPP_OID
    ,s.YB_PROGRAM
    ,s.APO_TYPE
    ,s.SALES_REP_NAME
    ,s.SALES_REP_EMAIL
    ,s.BOOKING_PROGRAM
    ,s.FINALIZED_DATE
    ,s.COVER_RECEIVED
    ,s.BOOK_OFFERING
    ,s.LAST_UPDATED
   ,s. SIGNING_INFO
  ,s.INCENTIVE_GRANTED
  ,s.HIGH_GRADE
  ,s.LOW_GRADE
  ,s.LIFETOUCH_PHOTOGRAPHED
,s.product_release_completed_date
,s.product_release_completed_by
)

&


/*-----------------------------------------------*/
/* TASK No. 16 */
/* Update BOOKING_OPP_OID for all from APO_XR */

MERGE INTO ODS_OWN.APO d
USING (
select * from (
      Select
        xr.APO_OID as APO_OID,
        xr.APO_ID as APO_ID,
        bo.BOOKING_OPPORTUNITY_OID as BOOKING_OPP_OID
    from
         ODS_STAGE.APO_XR xr 
        ,ODS_OWN.BOOKING_OPPORTUNITY bo
    where (1=1)
        and XR.BOOKING_OPP_ID=BO.BOOKING_OPP_KEY
         ) s
) s ON
  (d.APO_ID = s.APO_ID)
WHEN MATCHED
THEN
UPDATE SET
  d.BOOKING_OPP_OID = S.BOOKING_OPP_OID
WHERE
    decode(d.BOOKING_OPP_OID,s.BOOKING_OPP_OID,1,0) = 0

&


/*-----------------------------------------------*/
/* TASK No. 17 */
/* Update APO_TYPE, YB_PROGRAM and CONTRACT_RECEIVED, etc regardless of SYSTEM_OF_RECORD */

MERGE INTO ODS_OWN.APO d
USING (
select * from (
      Select
        xr.APO_OID as APO_OID,
        xr.APO_ID as APO_ID,
        xr.SYSTEM_OF_RECORD,
        stg.APO_TYPE,
        stg.YB_PROGRAM,
        stg.CONTRACT_RECEIVED,
        stg.FINALIZED_DATE,
        stg.COVER_RECEIVED,
        stg.BOOK_OFFERING,
       stg.LAST_UPDATED,
       stg.SIGNING_INFO,
       stg.INCENTIVE_GRANTED,
       stg.HIGH_GRADE,
       stg.LOW_GRADE,
       stg.STATUS as FOW_STATUS,
       stg.COVER_APPROVED,
       stg.COVER_DETAILS_PROVIDED,
       stg.YB_ENROLLED,
       stg.YB_ENROLLED_DATE
    from
        ODS_STAGE.FOW_APO_STAGE stg
        ,ODS_STAGE.APO_XR xr 
    where (1=1)
        and STG.APO_TAG=XR.APO_ID
         ) s
where NOT EXISTS 
    ( select 1 from ODS_OWN.APO T
    where    T.APO_OID    = S.APO_OID 
         and ((T.APO_ID = S.APO_ID) or (T.APO_ID IS NULL and S.APO_ID IS NULL)) and
          ((T.YB_PROGRAM = S.YB_PROGRAM) or (T.YB_PROGRAM IS NULL and S.YB_PROGRAM IS NULL)) and
         ((T.APO_TYPE = S.APO_TYPE) or (T.APO_TYPE IS NULL and S.APO_TYPE IS NULL)) and
          ((T.CONTRACT_RECEIVED = S.CONTRACT_RECEIVED) or (T.CONTRACT_RECEIVED IS NULL and S.CONTRACT_RECEIVED IS NULL)) and
         ((T.FINALIZED_DATE = S.FINALIZED_DATE) or (T.FINALIZED_DATE IS NULL and S.FINALIZED_DATE IS NULL)) and
         ((T.COVER_RECEIVED = S.COVER_RECEIVED) or (T.COVER_RECEIVED IS NULL and S.COVER_RECEIVED IS NULL)) and
          ((T.BOOK_OFFERING = S.BOOK_OFFERING) or (T.BOOK_OFFERING IS NULL and S.BOOK_OFFERING IS NULL)) and 
          ((T.LAST_UPDATED = S.LAST_UPDATED) or (T.LAST_UPDATED IS NULL and S.LAST_UPDATED IS NULL)) and
 	((T.SIGNING_INFO = S.SIGNING_INFO) or (T.SIGNING_INFO IS NULL and S.SIGNING_INFO IS NULL)) and 
	 ((T.INCENTIVE_GRANTED = S.INCENTIVE_GRANTED) or (T.INCENTIVE_GRANTED IS NULL and S.INCENTIVE_GRANTED IS NULL)) and
((T.HIGH_GRADE = S.HIGH_GRADE) or (T.HIGH_GRADE IS NULL and S.HIGH_GRADE IS NULL)) and
((T.LOW_GRADE = S.LOW_GRADE) or (T.LOW_GRADE IS NULL and S.LOW_GRADE IS NULL)) and
((T.FOW_STATUS = S.FOW_STATUS) or (T.FOW_STATUS IS NULL and S.FOW_STATUS IS NULL)) and
  ((T.COVER_APPROVED = S.COVER_APPROVED) or (T.COVER_APPROVED IS NULL and S.COVER_APPROVED IS NULL)) and
  ((T.COVER_DETAILS_PROVIDED = S.COVER_DETAILS_PROVIDED) or (T.COVER_DETAILS_PROVIDED IS NULL and S.COVER_DETAILS_PROVIDED IS NULL)) and
  ((T.YB_ENROLLED = S.YB_ENROLLED) or (T.YB_ENROLLED IS NULL and S.YB_ENROLLED IS NULL)) and
  ((T.YB_ENROLLED_DATE = S.YB_ENROLLED_DATE) or (T.YB_ENROLLED_DATE IS NULL and S.YB_ENROLLED_DATE IS NULL))
        )
) s ON
  (d.APO_ID = s.APO_ID)
WHEN MATCHED
THEN
UPDATE SET
  d.YB_PROGRAM = S.YB_PROGRAM,
  d.APO_TYPE = s.APO_TYPE,
  d.CONTRACT_RECEIVED = s.CONTRACT_RECEIVED,
  d.FINALIZED_DATE = s.FINALIZED_DATE,
  d.COVER_RECEIVED = s.COVER_RECEIVED,
  d.BOOK_OFFERING = s.BOOK_OFFERING,
 d.LAST_UPDATED = s.LAST_UPDATED,
 d.SIGNING_INFO  = s.SIGNING_INFO,
  d.INCENTIVE_GRANTED  = s.INCENTIVE_GRANTED,
  d.ods_modify_date = sysdate,
  d.HIGH_GRADE=s.HIGH_GRADE,
  d.LOW_GRADE=s.LOW_GRADE,
  d.FOW_STATUS = s.FOW_STATUS,
  d.COVER_APPROVED = s.COVER_APPROVED,
  d.COVER_DETAILS_PROVIDED = s.COVER_DETAILS_PROVIDED,
  d.YB_ENROLLED = s.YB_ENROLLED,
  d.YB_ENROLLED_DATE = s.YB_ENROLLED_DATE


&


/*-----------------------------------------------*/
/* TASK No. 18 */
/* Update class_picture_release_date from OMS3 */

MERGE INTO ODS_OWN.APO d
USING 
(
select oms.apo_id
, oms.class_picture_release_date 
from ods_stage.oms3_lt_apo_stg oms
where oms.class_picture_release_date  is not null
and oms.ods_modify_date >= TO_DATE(SUBSTR(:v_cdc_load_date,1,19),'YYYY-MM-DD HH24:MI:SS') - :v_cdc_oms_overlap
) s ON
  (d.APO_ID = s.APO_ID)
WHEN MATCHED
THEN
UPDATE SET
  d.class_picture_release_date = s.class_picture_release_date
, d.ods_modify_date = sysdate
WHERE
    decode(d.class_picture_release_date,s.class_picture_release_date,1,0) = 0

&


/*-----------------------------------------------*/
/* TASK No. 19 */
/* Set vID */

/* NONE or SET VARIABLE STATEMENT FOUND, CHECK ODI TASK NO. 19 */




/*-----------------------------------------------*/
/* TASK No. 20 */
/* Drop flow table */

BEGIN  
   EXECUTE IMMEDIATE 'drop table RAX_APP_USER.I$_FOW_APO_STAGE646001';  
EXCEPTION  
   WHEN OTHERS THEN  
      IF SQLCODE != -942 THEN  
         RAISE;  
      END IF;  
END;

&


/*-----------------------------------------------*/
/* TASK No. 21 */
/* Create flow table I$ */

create table RAX_APP_USER.I$_FOW_APO_STAGE646001
(
	APO_OID	NUMBER NULL,
	ACCOUNT_NAME	VARCHAR2(255) NULL,
	APO_TAG	VARCHAR2(255) NULL,
	BOOKING_OPP_ID	NUMBER NULL,
	BOOKING_YEAR	VARCHAR2(255) NULL,
	BUS_CONTEXT_NAME	VARCHAR2(255) NULL,
	CONSUMER_ENQ_PHONE	VARCHAR2(255) NULL,
	CONSUMER_MODEL	VARCHAR2(255) NULL,
	CONSUMER_SORT	VARCHAR2(255) NULL,
	CONTACT	VARCHAR2(255) NULL,
	CREATED_BY	VARCHAR2(255) NULL,
	CURRENCY	VARCHAR2(255) NULL,
	DATE_CREATED	TIMESTAMP(6) NULL,
	DEFAULT_ORD_PKG	VARCHAR2(255) NULL,
	DESCRIPTION	VARCHAR2(255) NULL,
	ENROLLMENT_COUNT	NUMBER NULL,
	FAX	VARCHAR2(255) NULL,
	HIGH_GRADE	VARCHAR2(255) NULL,
	JOB_IDENTIFIER	VARCHAR2(255) NULL,
	LAB_INSTRUCTIONS	VARCHAR2(255) NULL,
	LANGUAGE	VARCHAR2(255) NULL,
	LAST_UPDATED	TIMESTAMP(6) NULL,
	LID	NUMBER NULL,
	LOC_CODE	VARCHAR2(255) NULL,
	LOW_GRADE	VARCHAR2(255) NULL,
	MARKETING_CODE	VARCHAR2(255) NULL,
	NACAM_OVERALL	VARCHAR2(255) NULL,
	OFFER_ONLINE_ORDERING	NUMBER NULL,
	ORDER_FORM	VARCHAR2(255) NULL,
	ORDER_FORM_ITEM_ID	VARCHAR2(255) NULL,
	PHONE	VARCHAR2(255) NULL,
	PHONE_ORDER	VARCHAR2(255) NULL,
	PHOTO_LOCATION	VARCHAR2(255) NULL,
	PROCESSING_LAB	VARCHAR2(255) NULL,
	PROGRAM	VARCHAR2(255) NULL,
	PROOF_EXPRESS	NUMBER NULL,
	PUBLISHED	NUMBER NULL,
	REMINDER_POSTCARD	NUMBER NULL,
	REPORT_GRP	VARCHAR2(255) NULL,
	REVISION_NO	NUMBER NULL,
	RISK_CODE	VARCHAR2(255) NULL,
	RISK_TEXT	VARCHAR2(255) NULL,
	SALES_REP_CODE	VARCHAR2(255) NULL,
	SALES_REP_NAME	VARCHAR2(255) NULL,
	SCHOOL_YR_END	NUMBER NULL,
	SELLING_METHOD	VARCHAR2(255) NULL,
	SERVICE_CENTER	VARCHAR2(255) NULL,
	SERVICE_PRODUCT_SORT	VARCHAR2(255) NULL,
	SHIP_TO	VARCHAR2(255) NULL,
	STATUS	VARCHAR2(255) NULL,
	SUB_PROGRAM	VARCHAR2(255) NULL,
	SVC_PROD_MODEL	VARCHAR2(255) NULL,
	TAX_CERTIFICATE	VARCHAR2(255) NULL,
	TAX_EXEMPT	NUMBER NULL,
	TERRITORY	VARCHAR2(255) NULL,
	TWO_WEEK_RETURN_MSG	NUMBER NULL,
	UPDATED_BY	VARCHAR2(255) NULL,
	VISION_JOB	VARCHAR2(255) NULL,
	SOURCE_SYSTEM_OID	NUMBER NULL,
	ODS_CREATE_DATE	DATE NULL,
	ODS_MODIFY_DATE	DATE NULL,
	ID	NUMBER NULL,
	VERSION	NUMBER NULL,
	ADDRESS	VARCHAR2(255) NULL,
	CITY	VARCHAR2(255) NULL,
	COUNTRY	VARCHAR2(255) NULL,
	COUNTY	VARCHAR2(255) NULL,
	FINANCIAL_PROCESSING_SYSTEM	VARCHAR2(255) NULL,
	FULFILLING_LAB_SYSTEM	VARCHAR2(255) NULL,
	LANGUAGE2	VARCHAR2(255) NULL,
	OPERATIONS_REP_NAME	VARCHAR2(255) NULL,
	POSTAL_CODE	VARCHAR2(255) NULL,
	RISK_IND	NUMBER NULL,
	VALIDATION_ERROR	VARCHAR2(1024) NULL,
	CATEGORY	VARCHAR2(255) NULL,
	SUBCATEGORY	VARCHAR2(255) NULL,
	LOCK_ON_NAME	NUMBER NULL,
	ORIGINAL_BOOKING_REP	VARCHAR2(255) NULL,
	ORIGINAL_BOOKING_REP_NAME	VARCHAR2(255) NULL,
	EST_TO_BE_PHOTOED	VARCHAR2(255) NULL,
	ENVELOPE_ID	VARCHAR2(20) NULL,
	CAMERA_PLATFORM	VARCHAR2(255) NULL,
	CONFIRMED_LAB	VARCHAR2(255) NULL,
	CONTRACT_RECEIVED	DATE NULL,
	APO_TYPE	VARCHAR2(255) NULL,
	YB_PROGRAM	VARCHAR2(255) NULL,
	FINALIZED_DATE	DATE NULL,
	COVER_RECEIVED	DATE NULL,
	SALE_TYPE	VARCHAR2(10) NULL,
	ENABLE_PRISM	NUMBER NULL,
	BOOK_OFFERING	VARCHAR2(255) NULL,
	INCENTIVE_GRANTED	VARCHAR2(10) NULL,
	CONTRACT_STATUS	VARCHAR2(255) NULL,
	ALLOW_EXTRA_COVERAGE_DEADLINE	NUMBER NULL,
	PRODUCT_RELEASE_COMPLETED_BY	VARCHAR2(255) NULL,
	PRODUCT_RELEASE_COMPLETED_DATE	DATE NULL,
	COVER_DETAILS_PROVIDED	DATE NULL,
	COVER_APPROVED	DATE NULL,
	SIGNING_INFO	VARCHAR2(255) NULL,
	YB_ENROLLED	NUMBER(1) NULL,
	YB_ENROLLED_DATE	TIMESTAMP(6) NULL
	,IND_UPDATE		char(1)
)
NOLOGGING

&


/*-----------------------------------------------*/
/* TASK No. 22 */
/* Insert flow into I$ table */

/* DETECTION_STRATEGY = NOT_EXISTS */
 


  


insert into	RAX_APP_USER.I$_FOW_APO_STAGE646001
(
	APO_OID,
	ACCOUNT_NAME,
	APO_TAG,
	BOOKING_OPP_ID,
	BOOKING_YEAR,
	BUS_CONTEXT_NAME,
	CONSUMER_ENQ_PHONE,
	CONSUMER_MODEL,
	CONSUMER_SORT,
	CONTACT,
	CREATED_BY,
	CURRENCY,
	DATE_CREATED,
	DEFAULT_ORD_PKG,
	DESCRIPTION,
	ENROLLMENT_COUNT,
	FAX,
	HIGH_GRADE,
	JOB_IDENTIFIER,
	LAB_INSTRUCTIONS,
	LANGUAGE,
	LAST_UPDATED,
	LID,
	LOC_CODE,
	LOW_GRADE,
	MARKETING_CODE,
	NACAM_OVERALL,
	OFFER_ONLINE_ORDERING,
	ORDER_FORM,
	ORDER_FORM_ITEM_ID,
	PHONE,
	PHONE_ORDER,
	PHOTO_LOCATION,
	PROCESSING_LAB,
	PROGRAM,
	PROOF_EXPRESS,
	PUBLISHED,
	REMINDER_POSTCARD,
	REPORT_GRP,
	REVISION_NO,
	RISK_CODE,
	RISK_TEXT,
	SALES_REP_CODE,
	SALES_REP_NAME,
	SCHOOL_YR_END,
	SELLING_METHOD,
	SERVICE_CENTER,
	SERVICE_PRODUCT_SORT,
	SHIP_TO,
	STATUS,
	SUB_PROGRAM,
	SVC_PROD_MODEL,
	TAX_CERTIFICATE,
	TAX_EXEMPT,
	TERRITORY,
	TWO_WEEK_RETURN_MSG,
	UPDATED_BY,
	VISION_JOB,
	SOURCE_SYSTEM_OID,
	ID,
	VERSION,
	ADDRESS,
	CITY,
	COUNTRY,
	COUNTY,
	FINANCIAL_PROCESSING_SYSTEM,
	FULFILLING_LAB_SYSTEM,
	LANGUAGE2,
	OPERATIONS_REP_NAME,
	POSTAL_CODE,
	RISK_IND,
	VALIDATION_ERROR,
	CATEGORY,
	SUBCATEGORY,
	LOCK_ON_NAME,
	ORIGINAL_BOOKING_REP,
	ORIGINAL_BOOKING_REP_NAME,
	EST_TO_BE_PHOTOED,
	ENVELOPE_ID,
	CAMERA_PLATFORM,
	CONFIRMED_LAB,
	CONTRACT_RECEIVED,
	APO_TYPE,
	YB_PROGRAM,
	FINALIZED_DATE,
	COVER_RECEIVED,
	SALE_TYPE,
	ENABLE_PRISM,
	BOOK_OFFERING,
	INCENTIVE_GRANTED,
	CONTRACT_STATUS,
	ALLOW_EXTRA_COVERAGE_DEADLINE,
	PRODUCT_RELEASE_COMPLETED_BY,
	PRODUCT_RELEASE_COMPLETED_DATE,
	COVER_DETAILS_PROVIDED,
	COVER_APPROVED,
	SIGNING_INFO,
	YB_ENROLLED,
	YB_ENROLLED_DATE,
	IND_UPDATE
)
select 
APO_OID,
	ACCOUNT_NAME,
	APO_TAG,
	BOOKING_OPP_ID,
	BOOKING_YEAR,
	BUS_CONTEXT_NAME,
	CONSUMER_ENQ_PHONE,
	CONSUMER_MODEL,
	CONSUMER_SORT,
	CONTACT,
	CREATED_BY,
	CURRENCY,
	DATE_CREATED,
	DEFAULT_ORD_PKG,
	DESCRIPTION,
	ENROLLMENT_COUNT,
	FAX,
	HIGH_GRADE,
	JOB_IDENTIFIER,
	LAB_INSTRUCTIONS,
	LANGUAGE,
	LAST_UPDATED,
	LID,
	LOC_CODE,
	LOW_GRADE,
	MARKETING_CODE,
	NACAM_OVERALL,
	OFFER_ONLINE_ORDERING,
	ORDER_FORM,
	ORDER_FORM_ITEM_ID,
	PHONE,
	PHONE_ORDER,
	PHOTO_LOCATION,
	PROCESSING_LAB,
	PROGRAM,
	PROOF_EXPRESS,
	PUBLISHED,
	REMINDER_POSTCARD,
	REPORT_GRP,
	REVISION_NO,
	RISK_CODE,
	RISK_TEXT,
	SALES_REP_CODE,
	SALES_REP_NAME,
	SCHOOL_YR_END,
	SELLING_METHOD,
	SERVICE_CENTER,
	SERVICE_PRODUCT_SORT,
	SHIP_TO,
	STATUS,
	SUB_PROGRAM,
	SVC_PROD_MODEL,
	TAX_CERTIFICATE,
	TAX_EXEMPT,
	TERRITORY,
	TWO_WEEK_RETURN_MSG,
	UPDATED_BY,
	VISION_JOB,
	SOURCE_SYSTEM_OID,
	ID,
	VERSION,
	ADDRESS,
	CITY,
	COUNTRY,
	COUNTY,
	FINANCIAL_PROCESSING_SYSTEM,
	FULFILLING_LAB_SYSTEM,
	LANGUAGE2,
	OPERATIONS_REP_NAME,
	POSTAL_CODE,
	RISK_IND,
	VALIDATION_ERROR,
	CATEGORY,
	SUBCATEGORY,
	LOCK_ON_NAME,
	ORIGINAL_BOOKING_REP,
	ORIGINAL_BOOKING_REP_NAME,
	EST_TO_BE_PHOTOED,
	ENVELOPE_ID,
	CAMERA_PLATFORM,
	CONFIRMED_LAB,
	CONTRACT_RECEIVED,
	APO_TYPE,
	YB_PROGRAM,
	FINALIZED_DATE,
	COVER_RECEIVED,
	SALE_TYPE,
	ENABLE_PRISM,
	BOOK_OFFERING,
	INCENTIVE_GRANTED,
	CONTRACT_STATUS,
	ALLOW_EXTRA_COVERAGE_DEADLINE,
	PRODUCT_RELEASE_COMPLETED_BY,
	PRODUCT_RELEASE_COMPLETED_DATE,
	COVER_DETAILS_PROVIDED,
	COVER_APPROVED,
	SIGNING_INFO,
	YB_ENROLLED,
	YB_ENROLLED_DATE,
	IND_UPDATE
 from (


select 	 
	
	APO_XR.APO_OID APO_OID,
	STG_FOW_APO.ACCOUNT_NAME ACCOUNT_NAME,
	STG_FOW_APO.APO_TAG APO_TAG,
	STG_FOW_APO.BOOKING_OPP_ID BOOKING_OPP_ID,
	STG_FOW_APO.BOOKING_YEAR BOOKING_YEAR,
	STG_FOW_APO.BUS_CONTEXT_NAME BUS_CONTEXT_NAME,
	STG_FOW_APO.CONSUMER_ENQ_PHONE CONSUMER_ENQ_PHONE,
	STG_FOW_APO.CONSUMER_MODEL CONSUMER_MODEL,
	STG_FOW_APO.CONSUMER_SORT CONSUMER_SORT,
	STG_FOW_APO.CONTACT CONTACT,
	STG_FOW_APO.CREATED_BY CREATED_BY,
	STG_FOW_APO.CURRENCY CURRENCY,
	STG_FOW_APO.DATE_CREATED DATE_CREATED,
	STG_FOW_APO.DEFAULT_ORD_PKG DEFAULT_ORD_PKG,
	STG_FOW_APO.DESCRIPTION DESCRIPTION,
	STG_FOW_APO.ENROLLMENT_COUNT ENROLLMENT_COUNT,
	STG_FOW_APO.FAX FAX,
	STG_FOW_APO.HIGH_GRADE HIGH_GRADE,
	STG_FOW_APO.JOB_IDENTIFIER JOB_IDENTIFIER,
	STG_FOW_APO.LAB_INSTRUCTIONS LAB_INSTRUCTIONS,
	STG_FOW_APO.LANGUAGE LANGUAGE,
	STG_FOW_APO.LAST_UPDATED LAST_UPDATED,
	STG_FOW_APO.LID LID,
	STG_FOW_APO.LOC_CODE LOC_CODE,
	STG_FOW_APO.LOW_GRADE LOW_GRADE,
	STG_FOW_APO.MARKETING_CODE MARKETING_CODE,
	STG_FOW_APO.NACAM_OVERALL NACAM_OVERALL,
	STG_FOW_APO.OFFER_ONLINE_ORDERING OFFER_ONLINE_ORDERING,
	STG_FOW_APO.ORDER_FORM ORDER_FORM,
	STG_FOW_APO.ORDER_FORM_ITEM_ID ORDER_FORM_ITEM_ID,
	STG_FOW_APO.PHONE PHONE,
	STG_FOW_APO.PHONE_ORDER PHONE_ORDER,
	STG_FOW_APO.PHOTO_LOCATION PHOTO_LOCATION,
	case 
    when STG_FOW_APO.APO_TYPE in ('Shutterware') then nvl(STG_FOW_APO.PROCESSING_LAB,'Chattanooga')
    when STG_FOW_APO.APO_TYPE in ('Infinity') then nvl(STG_FOW_APO.PROCESSING_LAB,'Minneapolis')
    else STG_FOW_APO.PROCESSING_LAB 
end PROCESSING_LAB,
	STG_FOW_APO.PROGRAM PROGRAM,
	STG_FOW_APO.PROOF_EXPRESS PROOF_EXPRESS,
	STG_FOW_APO.PUBLISHED PUBLISHED,
	STG_FOW_APO.REMINDER_POSTCARD REMINDER_POSTCARD,
	STG_FOW_APO.REPORT_GRP REPORT_GRP,
	STG_FOW_APO.REVISION_NO REVISION_NO,
	STG_FOW_APO.RISK_CODE RISK_CODE,
	STG_FOW_APO.RISK_TEXT RISK_TEXT,
	STG_FOW_APO.SALES_REP_CODE SALES_REP_CODE,
	STG_FOW_APO.SALES_REP_NAME SALES_REP_NAME,
	STG_FOW_APO.SCHOOL_YR_END SCHOOL_YR_END,
	STG_FOW_APO.SELLING_METHOD SELLING_METHOD,
	STG_FOW_APO.SERVICE_CENTER SERVICE_CENTER,
	STG_FOW_APO.SERVICE_PRODUCT_SORT SERVICE_PRODUCT_SORT,
	STG_FOW_APO.SHIP_TO SHIP_TO,
	STG_FOW_APO.STATUS STATUS,
	STG_FOW_APO.SUB_PROGRAM SUB_PROGRAM,
	STG_FOW_APO.SVC_PROD_MODEL SVC_PROD_MODEL,
	STG_FOW_APO.TAX_CERTIFICATE TAX_CERTIFICATE,
	STG_FOW_APO.TAX_EXEMPT TAX_EXEMPT,
	STG_FOW_APO.TERRITORY TERRITORY,
	STG_FOW_APO.TWO_WEEK_RETURN_MSG TWO_WEEK_RETURN_MSG,
	STG_FOW_APO.UPDATED_BY UPDATED_BY,
	STG_FOW_APO.VISION_JOB VISION_JOB,
	SOURCE_SYSTEM.SOURCE_SYSTEM_OID SOURCE_SYSTEM_OID,
	STG_FOW_APO.ID ID,
	STG_FOW_APO.VERSION VERSION,
	STG_FOW_APO.ADDRESS ADDRESS,
	STG_FOW_APO.CITY CITY,
	STG_FOW_APO.COUNTRY COUNTRY,
	STG_FOW_APO.COUNTY COUNTY,
	STG_FOW_APO.FINANCIAL_PROCESSING_SYSTEM FINANCIAL_PROCESSING_SYSTEM,
	STG_FOW_APO.FULFILLING_LAB_SYSTEM FULFILLING_LAB_SYSTEM,
	STG_FOW_APO.LANGUAGE2 LANGUAGE2,
	STG_FOW_APO.OPERATIONS_REP_NAME OPERATIONS_REP_NAME,
	STG_FOW_APO.POSTAL_CODE POSTAL_CODE,
	STG_FOW_APO.RISK_IND RISK_IND,
	STG_FOW_APO.VALIDATION_ERROR VALIDATION_ERROR,
	STG_FOW_APO.CATEGORY CATEGORY,
	STG_FOW_APO.SUBCATEGORY SUBCATEGORY,
	STG_FOW_APO.LOCK_ON_NAME LOCK_ON_NAME,
	STG_FOW_APO.ORIGINAL_BOOKING_REP ORIGINAL_BOOKING_REP,
	STG_FOW_APO.ORIGINAL_BOOKING_REP_NAME ORIGINAL_BOOKING_REP_NAME,
	STG_FOW_APO.EST_TO_BE_PHOTOED EST_TO_BE_PHOTOED,
	STG_FOW_APO.ENVELOPE_ID ENVELOPE_ID,
	STG_FOW_APO.CAMERA_PLATFORM CAMERA_PLATFORM,
	STG_FOW_APO.CONFIRMED_LAB CONFIRMED_LAB,
	STG_FOW_APO.CONTRACT_RECEIVED CONTRACT_RECEIVED,
	STG_FOW_APO.APO_TYPE APO_TYPE,
	STG_FOW_APO.YB_PROGRAM YB_PROGRAM,
	STG_FOW_APO.FINALIZED_DATE FINALIZED_DATE,
	STG_FOW_APO.COVER_RECEIVED COVER_RECEIVED,
	STG_FOW_APO.SALE_TYPE SALE_TYPE,
	STG_FOW_APO.ENABLE_PRISM ENABLE_PRISM,
	STG_FOW_APO.BOOK_OFFERING BOOK_OFFERING,
	STG_FOW_APO.INCENTIVE_GRANTED INCENTIVE_GRANTED,
	STG_FOW_APO.CONTRACT_STATUS CONTRACT_STATUS,
	STG_FOW_APO.ALLOW_EXTRA_COVERAGE_DEADLINE ALLOW_EXTRA_COVERAGE_DEADLINE,
	STG_FOW_APO.PRODUCT_RELEASE_COMPLETED_BY PRODUCT_RELEASE_COMPLETED_BY,
	STG_FOW_APO.PRODUCT_RELEASE_COMPLETED_DATE PRODUCT_RELEASE_COMPLETED_DATE,
	STG_FOW_APO.COVER_DETAILS_PROVIDED COVER_DETAILS_PROVIDED,
	STG_FOW_APO.COVER_APPROVED COVER_APPROVED,
	STG_FOW_APO.SIGNING_INFO SIGNING_INFO,
	STG_FOW_APO.YB_ENROLLED YB_ENROLLED,
	STG_FOW_APO.YB_ENROLLED_DATE YB_ENROLLED_DATE,

	'I' IND_UPDATE

from	RAX_APP_USER.STG_FOW_APO   STG_FOW_APO, ODS_OWN.SOURCE_SYSTEM   SOURCE_SYSTEM, ODS_STAGE.APO_XR   APO_XR
where	(1=1)
 And (STG_FOW_APO.CITY=SOURCE_SYSTEM.SOURCE_SYSTEM_SHORT_NAME (+))
AND (STG_FOW_APO.APO_TAG=APO_XR.APO_ID)
And (SOURCE_SYSTEM.SOURCE_SYSTEM_SHORT_NAME (+) = 'FOW')




) S
where NOT EXISTS 
	( select 1 from ODS_STAGE.FOW_APO_STAGE T
	where	T.APO_OID	= S.APO_OID 
		 and ((T.ACCOUNT_NAME = S.ACCOUNT_NAME) or (T.ACCOUNT_NAME IS NULL and S.ACCOUNT_NAME IS NULL)) and
		((T.APO_TAG = S.APO_TAG) or (T.APO_TAG IS NULL and S.APO_TAG IS NULL)) and
		((T.BOOKING_OPP_ID = S.BOOKING_OPP_ID) or (T.BOOKING_OPP_ID IS NULL and S.BOOKING_OPP_ID IS NULL)) and
		((T.BOOKING_YEAR = S.BOOKING_YEAR) or (T.BOOKING_YEAR IS NULL and S.BOOKING_YEAR IS NULL)) and
		((T.BUS_CONTEXT_NAME = S.BUS_CONTEXT_NAME) or (T.BUS_CONTEXT_NAME IS NULL and S.BUS_CONTEXT_NAME IS NULL)) and
		((T.CONSUMER_ENQ_PHONE = S.CONSUMER_ENQ_PHONE) or (T.CONSUMER_ENQ_PHONE IS NULL and S.CONSUMER_ENQ_PHONE IS NULL)) and
		((T.CONSUMER_MODEL = S.CONSUMER_MODEL) or (T.CONSUMER_MODEL IS NULL and S.CONSUMER_MODEL IS NULL)) and
		((T.CONSUMER_SORT = S.CONSUMER_SORT) or (T.CONSUMER_SORT IS NULL and S.CONSUMER_SORT IS NULL)) and
		((T.CONTACT = S.CONTACT) or (T.CONTACT IS NULL and S.CONTACT IS NULL)) and
		((T.CREATED_BY = S.CREATED_BY) or (T.CREATED_BY IS NULL and S.CREATED_BY IS NULL)) and
		((T.CURRENCY = S.CURRENCY) or (T.CURRENCY IS NULL and S.CURRENCY IS NULL)) and
		((T.DATE_CREATED = S.DATE_CREATED) or (T.DATE_CREATED IS NULL and S.DATE_CREATED IS NULL)) and
		((T.DEFAULT_ORD_PKG = S.DEFAULT_ORD_PKG) or (T.DEFAULT_ORD_PKG IS NULL and S.DEFAULT_ORD_PKG IS NULL)) and
		((T.DESCRIPTION = S.DESCRIPTION) or (T.DESCRIPTION IS NULL and S.DESCRIPTION IS NULL)) and
		((T.ENROLLMENT_COUNT = S.ENROLLMENT_COUNT) or (T.ENROLLMENT_COUNT IS NULL and S.ENROLLMENT_COUNT IS NULL)) and
		((T.FAX = S.FAX) or (T.FAX IS NULL and S.FAX IS NULL)) and
		((T.HIGH_GRADE = S.HIGH_GRADE) or (T.HIGH_GRADE IS NULL and S.HIGH_GRADE IS NULL)) and
		((T.JOB_IDENTIFIER = S.JOB_IDENTIFIER) or (T.JOB_IDENTIFIER IS NULL and S.JOB_IDENTIFIER IS NULL)) and
		((T.LAB_INSTRUCTIONS = S.LAB_INSTRUCTIONS) or (T.LAB_INSTRUCTIONS IS NULL and S.LAB_INSTRUCTIONS IS NULL)) and
		((T.LANGUAGE = S.LANGUAGE) or (T.LANGUAGE IS NULL and S.LANGUAGE IS NULL)) and
		((T.LAST_UPDATED = S.LAST_UPDATED) or (T.LAST_UPDATED IS NULL and S.LAST_UPDATED IS NULL)) and
		((T.LID = S.LID) or (T.LID IS NULL and S.LID IS NULL)) and
		((T.LOC_CODE = S.LOC_CODE) or (T.LOC_CODE IS NULL and S.LOC_CODE IS NULL)) and
		((T.LOW_GRADE = S.LOW_GRADE) or (T.LOW_GRADE IS NULL and S.LOW_GRADE IS NULL)) and
		((T.MARKETING_CODE = S.MARKETING_CODE) or (T.MARKETING_CODE IS NULL and S.MARKETING_CODE IS NULL)) and
		((T.NACAM_OVERALL = S.NACAM_OVERALL) or (T.NACAM_OVERALL IS NULL and S.NACAM_OVERALL IS NULL)) and
		((T.OFFER_ONLINE_ORDERING = S.OFFER_ONLINE_ORDERING) or (T.OFFER_ONLINE_ORDERING IS NULL and S.OFFER_ONLINE_ORDERING IS NULL)) and
		((T.ORDER_FORM = S.ORDER_FORM) or (T.ORDER_FORM IS NULL and S.ORDER_FORM IS NULL)) and
		((T.ORDER_FORM_ITEM_ID = S.ORDER_FORM_ITEM_ID) or (T.ORDER_FORM_ITEM_ID IS NULL and S.ORDER_FORM_ITEM_ID IS NULL)) and
		((T.PHONE = S.PHONE) or (T.PHONE IS NULL and S.PHONE IS NULL)) and
		((T.PHONE_ORDER = S.PHONE_ORDER) or (T.PHONE_ORDER IS NULL and S.PHONE_ORDER IS NULL)) and
		((T.PHOTO_LOCATION = S.PHOTO_LOCATION) or (T.PHOTO_LOCATION IS NULL and S.PHOTO_LOCATION IS NULL)) and
		((T.PROCESSING_LAB = S.PROCESSING_LAB) or (T.PROCESSING_LAB IS NULL and S.PROCESSING_LAB IS NULL)) and
		((T.PROGRAM = S.PROGRAM) or (T.PROGRAM IS NULL and S.PROGRAM IS NULL)) and
		((T.PROOF_EXPRESS = S.PROOF_EXPRESS) or (T.PROOF_EXPRESS IS NULL and S.PROOF_EXPRESS IS NULL)) and
		((T.PUBLISHED = S.PUBLISHED) or (T.PUBLISHED IS NULL and S.PUBLISHED IS NULL)) and
		((T.REMINDER_POSTCARD = S.REMINDER_POSTCARD) or (T.REMINDER_POSTCARD IS NULL and S.REMINDER_POSTCARD IS NULL)) and
		((T.REPORT_GRP = S.REPORT_GRP) or (T.REPORT_GRP IS NULL and S.REPORT_GRP IS NULL)) and
		((T.REVISION_NO = S.REVISION_NO) or (T.REVISION_NO IS NULL and S.REVISION_NO IS NULL)) and
		((T.RISK_CODE = S.RISK_CODE) or (T.RISK_CODE IS NULL and S.RISK_CODE IS NULL)) and
		((T.RISK_TEXT = S.RISK_TEXT) or (T.RISK_TEXT IS NULL and S.RISK_TEXT IS NULL)) and
		((T.SALES_REP_CODE = S.SALES_REP_CODE) or (T.SALES_REP_CODE IS NULL and S.SALES_REP_CODE IS NULL)) and
		((T.SALES_REP_NAME = S.SALES_REP_NAME) or (T.SALES_REP_NAME IS NULL and S.SALES_REP_NAME IS NULL)) and
		((T.SCHOOL_YR_END = S.SCHOOL_YR_END) or (T.SCHOOL_YR_END IS NULL and S.SCHOOL_YR_END IS NULL)) and
		((T.SELLING_METHOD = S.SELLING_METHOD) or (T.SELLING_METHOD IS NULL and S.SELLING_METHOD IS NULL)) and
		((T.SERVICE_CENTER = S.SERVICE_CENTER) or (T.SERVICE_CENTER IS NULL and S.SERVICE_CENTER IS NULL)) and
		((T.SERVICE_PRODUCT_SORT = S.SERVICE_PRODUCT_SORT) or (T.SERVICE_PRODUCT_SORT IS NULL and S.SERVICE_PRODUCT_SORT IS NULL)) and
		((T.SHIP_TO = S.SHIP_TO) or (T.SHIP_TO IS NULL and S.SHIP_TO IS NULL)) and
		((T.STATUS = S.STATUS) or (T.STATUS IS NULL and S.STATUS IS NULL)) and
		((T.SUB_PROGRAM = S.SUB_PROGRAM) or (T.SUB_PROGRAM IS NULL and S.SUB_PROGRAM IS NULL)) and
		((T.SVC_PROD_MODEL = S.SVC_PROD_MODEL) or (T.SVC_PROD_MODEL IS NULL and S.SVC_PROD_MODEL IS NULL)) and
		((T.TAX_CERTIFICATE = S.TAX_CERTIFICATE) or (T.TAX_CERTIFICATE IS NULL and S.TAX_CERTIFICATE IS NULL)) and
		((T.TAX_EXEMPT = S.TAX_EXEMPT) or (T.TAX_EXEMPT IS NULL and S.TAX_EXEMPT IS NULL)) and
		((T.TERRITORY = S.TERRITORY) or (T.TERRITORY IS NULL and S.TERRITORY IS NULL)) and
		((T.TWO_WEEK_RETURN_MSG = S.TWO_WEEK_RETURN_MSG) or (T.TWO_WEEK_RETURN_MSG IS NULL and S.TWO_WEEK_RETURN_MSG IS NULL)) and
		((T.UPDATED_BY = S.UPDATED_BY) or (T.UPDATED_BY IS NULL and S.UPDATED_BY IS NULL)) and
		((T.VISION_JOB = S.VISION_JOB) or (T.VISION_JOB IS NULL and S.VISION_JOB IS NULL)) and
		((T.SOURCE_SYSTEM_OID = S.SOURCE_SYSTEM_OID) or (T.SOURCE_SYSTEM_OID IS NULL and S.SOURCE_SYSTEM_OID IS NULL)) and
		((T.ID = S.ID) or (T.ID IS NULL and S.ID IS NULL)) and
		((T.VERSION = S.VERSION) or (T.VERSION IS NULL and S.VERSION IS NULL)) and
		((T.ADDRESS = S.ADDRESS) or (T.ADDRESS IS NULL and S.ADDRESS IS NULL)) and
		((T.CITY = S.CITY) or (T.CITY IS NULL and S.CITY IS NULL)) and
		((T.COUNTRY = S.COUNTRY) or (T.COUNTRY IS NULL and S.COUNTRY IS NULL)) and
		((T.COUNTY = S.COUNTY) or (T.COUNTY IS NULL and S.COUNTY IS NULL)) and
		((T.FINANCIAL_PROCESSING_SYSTEM = S.FINANCIAL_PROCESSING_SYSTEM) or (T.FINANCIAL_PROCESSING_SYSTEM IS NULL and S.FINANCIAL_PROCESSING_SYSTEM IS NULL)) and
		((T.FULFILLING_LAB_SYSTEM = S.FULFILLING_LAB_SYSTEM) or (T.FULFILLING_LAB_SYSTEM IS NULL and S.FULFILLING_LAB_SYSTEM IS NULL)) and
		((T.LANGUAGE2 = S.LANGUAGE2) or (T.LANGUAGE2 IS NULL and S.LANGUAGE2 IS NULL)) and
		((T.OPERATIONS_REP_NAME = S.OPERATIONS_REP_NAME) or (T.OPERATIONS_REP_NAME IS NULL and S.OPERATIONS_REP_NAME IS NULL)) and
		((T.POSTAL_CODE = S.POSTAL_CODE) or (T.POSTAL_CODE IS NULL and S.POSTAL_CODE IS NULL)) and
		((T.RISK_IND = S.RISK_IND) or (T.RISK_IND IS NULL and S.RISK_IND IS NULL)) and
		((T.VALIDATION_ERROR = S.VALIDATION_ERROR) or (T.VALIDATION_ERROR IS NULL and S.VALIDATION_ERROR IS NULL)) and
		((T.CATEGORY = S.CATEGORY) or (T.CATEGORY IS NULL and S.CATEGORY IS NULL)) and
		((T.SUBCATEGORY = S.SUBCATEGORY) or (T.SUBCATEGORY IS NULL and S.SUBCATEGORY IS NULL)) and
		((T.LOCK_ON_NAME = S.LOCK_ON_NAME) or (T.LOCK_ON_NAME IS NULL and S.LOCK_ON_NAME IS NULL)) and
		((T.ORIGINAL_BOOKING_REP = S.ORIGINAL_BOOKING_REP) or (T.ORIGINAL_BOOKING_REP IS NULL and S.ORIGINAL_BOOKING_REP IS NULL)) and
		((T.ORIGINAL_BOOKING_REP_NAME = S.ORIGINAL_BOOKING_REP_NAME) or (T.ORIGINAL_BOOKING_REP_NAME IS NULL and S.ORIGINAL_BOOKING_REP_NAME IS NULL)) and
		((T.EST_TO_BE_PHOTOED = S.EST_TO_BE_PHOTOED) or (T.EST_TO_BE_PHOTOED IS NULL and S.EST_TO_BE_PHOTOED IS NULL)) and
		((T.ENVELOPE_ID = S.ENVELOPE_ID) or (T.ENVELOPE_ID IS NULL and S.ENVELOPE_ID IS NULL)) and
		((T.CAMERA_PLATFORM = S.CAMERA_PLATFORM) or (T.CAMERA_PLATFORM IS NULL and S.CAMERA_PLATFORM IS NULL)) and
		((T.CONFIRMED_LAB = S.CONFIRMED_LAB) or (T.CONFIRMED_LAB IS NULL and S.CONFIRMED_LAB IS NULL)) and
		((T.CONTRACT_RECEIVED = S.CONTRACT_RECEIVED) or (T.CONTRACT_RECEIVED IS NULL and S.CONTRACT_RECEIVED IS NULL)) and
		((T.APO_TYPE = S.APO_TYPE) or (T.APO_TYPE IS NULL and S.APO_TYPE IS NULL)) and
		((T.YB_PROGRAM = S.YB_PROGRAM) or (T.YB_PROGRAM IS NULL and S.YB_PROGRAM IS NULL)) and
		((T.FINALIZED_DATE = S.FINALIZED_DATE) or (T.FINALIZED_DATE IS NULL and S.FINALIZED_DATE IS NULL)) and
		((T.COVER_RECEIVED = S.COVER_RECEIVED) or (T.COVER_RECEIVED IS NULL and S.COVER_RECEIVED IS NULL)) and
		((T.SALE_TYPE = S.SALE_TYPE) or (T.SALE_TYPE IS NULL and S.SALE_TYPE IS NULL)) and
		((T.ENABLE_PRISM = S.ENABLE_PRISM) or (T.ENABLE_PRISM IS NULL and S.ENABLE_PRISM IS NULL)) and
		((T.BOOK_OFFERING = S.BOOK_OFFERING) or (T.BOOK_OFFERING IS NULL and S.BOOK_OFFERING IS NULL)) and
		((T.INCENTIVE_GRANTED = S.INCENTIVE_GRANTED) or (T.INCENTIVE_GRANTED IS NULL and S.INCENTIVE_GRANTED IS NULL)) and
		((T.CONTRACT_STATUS = S.CONTRACT_STATUS) or (T.CONTRACT_STATUS IS NULL and S.CONTRACT_STATUS IS NULL)) and
		((T.ALLOW_EXTRA_COVERAGE_DEADLINE = S.ALLOW_EXTRA_COVERAGE_DEADLINE) or (T.ALLOW_EXTRA_COVERAGE_DEADLINE IS NULL and S.ALLOW_EXTRA_COVERAGE_DEADLINE IS NULL)) and
		((T.PRODUCT_RELEASE_COMPLETED_BY = S.PRODUCT_RELEASE_COMPLETED_BY) or (T.PRODUCT_RELEASE_COMPLETED_BY IS NULL and S.PRODUCT_RELEASE_COMPLETED_BY IS NULL)) and
		((T.PRODUCT_RELEASE_COMPLETED_DATE = S.PRODUCT_RELEASE_COMPLETED_DATE) or (T.PRODUCT_RELEASE_COMPLETED_DATE IS NULL and S.PRODUCT_RELEASE_COMPLETED_DATE IS NULL)) and
		((T.COVER_DETAILS_PROVIDED = S.COVER_DETAILS_PROVIDED) or (T.COVER_DETAILS_PROVIDED IS NULL and S.COVER_DETAILS_PROVIDED IS NULL)) and
		((T.COVER_APPROVED = S.COVER_APPROVED) or (T.COVER_APPROVED IS NULL and S.COVER_APPROVED IS NULL)) and
		((T.SIGNING_INFO = S.SIGNING_INFO) or (T.SIGNING_INFO IS NULL and S.SIGNING_INFO IS NULL)) and
		((T.YB_ENROLLED = S.YB_ENROLLED) or (T.YB_ENROLLED IS NULL and S.YB_ENROLLED IS NULL)) and
		((T.YB_ENROLLED_DATE = S.YB_ENROLLED_DATE) or (T.YB_ENROLLED_DATE IS NULL and S.YB_ENROLLED_DATE IS NULL))
        )

  
  

  



&


/*-----------------------------------------------*/
/* TASK No. 23 */
/* Analyze integration table */



begin
    dbms_stats.gather_table_stats(
	ownname => 'RAX_APP_USER',
	tabname => 'I$_FOW_APO_STAGE646001',
	estimate_percent => dbms_stats.auto_sample_size
    );
end;



&


/*-----------------------------------------------*/
/* TASK No. 24 */
/* Create Index on flow table */

create index	RAX_APP_USER.I$_FOW_APO_STAGE_IDX646001
on		RAX_APP_USER.I$_FOW_APO_STAGE646001 (APO_OID)
NOLOGGING

&


/*-----------------------------------------------*/
/* TASK No. 25 */
/* Merge Rows */

merge into	ODS_STAGE.FOW_APO_STAGE T
using	RAX_APP_USER.I$_FOW_APO_STAGE646001 S
on	(
		T.APO_OID=S.APO_OID
	)
when matched
then update set
	T.ACCOUNT_NAME	= S.ACCOUNT_NAME,
	T.APO_TAG	= S.APO_TAG,
	T.BOOKING_OPP_ID	= S.BOOKING_OPP_ID,
	T.BOOKING_YEAR	= S.BOOKING_YEAR,
	T.BUS_CONTEXT_NAME	= S.BUS_CONTEXT_NAME,
	T.CONSUMER_ENQ_PHONE	= S.CONSUMER_ENQ_PHONE,
	T.CONSUMER_MODEL	= S.CONSUMER_MODEL,
	T.CONSUMER_SORT	= S.CONSUMER_SORT,
	T.CONTACT	= S.CONTACT,
	T.CREATED_BY	= S.CREATED_BY,
	T.CURRENCY	= S.CURRENCY,
	T.DATE_CREATED	= S.DATE_CREATED,
	T.DEFAULT_ORD_PKG	= S.DEFAULT_ORD_PKG,
	T.DESCRIPTION	= S.DESCRIPTION,
	T.ENROLLMENT_COUNT	= S.ENROLLMENT_COUNT,
	T.FAX	= S.FAX,
	T.HIGH_GRADE	= S.HIGH_GRADE,
	T.JOB_IDENTIFIER	= S.JOB_IDENTIFIER,
	T.LAB_INSTRUCTIONS	= S.LAB_INSTRUCTIONS,
	T.LANGUAGE	= S.LANGUAGE,
	T.LAST_UPDATED	= S.LAST_UPDATED,
	T.LID	= S.LID,
	T.LOC_CODE	= S.LOC_CODE,
	T.LOW_GRADE	= S.LOW_GRADE,
	T.MARKETING_CODE	= S.MARKETING_CODE,
	T.NACAM_OVERALL	= S.NACAM_OVERALL,
	T.OFFER_ONLINE_ORDERING	= S.OFFER_ONLINE_ORDERING,
	T.ORDER_FORM	= S.ORDER_FORM,
	T.ORDER_FORM_ITEM_ID	= S.ORDER_FORM_ITEM_ID,
	T.PHONE	= S.PHONE,
	T.PHONE_ORDER	= S.PHONE_ORDER,
	T.PHOTO_LOCATION	= S.PHOTO_LOCATION,
	T.PROCESSING_LAB	= S.PROCESSING_LAB,
	T.PROGRAM	= S.PROGRAM,
	T.PROOF_EXPRESS	= S.PROOF_EXPRESS,
	T.PUBLISHED	= S.PUBLISHED,
	T.REMINDER_POSTCARD	= S.REMINDER_POSTCARD,
	T.REPORT_GRP	= S.REPORT_GRP,
	T.REVISION_NO	= S.REVISION_NO,
	T.RISK_CODE	= S.RISK_CODE,
	T.RISK_TEXT	= S.RISK_TEXT,
	T.SALES_REP_CODE	= S.SALES_REP_CODE,
	T.SALES_REP_NAME	= S.SALES_REP_NAME,
	T.SCHOOL_YR_END	= S.SCHOOL_YR_END,
	T.SELLING_METHOD	= S.SELLING_METHOD,
	T.SERVICE_CENTER	= S.SERVICE_CENTER,
	T.SERVICE_PRODUCT_SORT	= S.SERVICE_PRODUCT_SORT,
	T.SHIP_TO	= S.SHIP_TO,
	T.STATUS	= S.STATUS,
	T.SUB_PROGRAM	= S.SUB_PROGRAM,
	T.SVC_PROD_MODEL	= S.SVC_PROD_MODEL,
	T.TAX_CERTIFICATE	= S.TAX_CERTIFICATE,
	T.TAX_EXEMPT	= S.TAX_EXEMPT,
	T.TERRITORY	= S.TERRITORY,
	T.TWO_WEEK_RETURN_MSG	= S.TWO_WEEK_RETURN_MSG,
	T.UPDATED_BY	= S.UPDATED_BY,
	T.VISION_JOB	= S.VISION_JOB,
	T.SOURCE_SYSTEM_OID	= S.SOURCE_SYSTEM_OID,
	T.ID	= S.ID,
	T.VERSION	= S.VERSION,
	T.ADDRESS	= S.ADDRESS,
	T.CITY	= S.CITY,
	T.COUNTRY	= S.COUNTRY,
	T.COUNTY	= S.COUNTY,
	T.FINANCIAL_PROCESSING_SYSTEM	= S.FINANCIAL_PROCESSING_SYSTEM,
	T.FULFILLING_LAB_SYSTEM	= S.FULFILLING_LAB_SYSTEM,
	T.LANGUAGE2	= S.LANGUAGE2,
	T.OPERATIONS_REP_NAME	= S.OPERATIONS_REP_NAME,
	T.POSTAL_CODE	= S.POSTAL_CODE,
	T.RISK_IND	= S.RISK_IND,
	T.VALIDATION_ERROR	= S.VALIDATION_ERROR,
	T.CATEGORY	= S.CATEGORY,
	T.SUBCATEGORY	= S.SUBCATEGORY,
	T.LOCK_ON_NAME	= S.LOCK_ON_NAME,
	T.ORIGINAL_BOOKING_REP	= S.ORIGINAL_BOOKING_REP,
	T.ORIGINAL_BOOKING_REP_NAME	= S.ORIGINAL_BOOKING_REP_NAME,
	T.EST_TO_BE_PHOTOED	= S.EST_TO_BE_PHOTOED,
	T.ENVELOPE_ID	= S.ENVELOPE_ID,
	T.CAMERA_PLATFORM	= S.CAMERA_PLATFORM,
	T.CONFIRMED_LAB	= S.CONFIRMED_LAB,
	T.CONTRACT_RECEIVED	= S.CONTRACT_RECEIVED,
	T.APO_TYPE	= S.APO_TYPE,
	T.YB_PROGRAM	= S.YB_PROGRAM,
	T.FINALIZED_DATE	= S.FINALIZED_DATE,
	T.COVER_RECEIVED	= S.COVER_RECEIVED,
	T.SALE_TYPE	= S.SALE_TYPE,
	T.ENABLE_PRISM	= S.ENABLE_PRISM,
	T.BOOK_OFFERING	= S.BOOK_OFFERING,
	T.INCENTIVE_GRANTED	= S.INCENTIVE_GRANTED,
	T.CONTRACT_STATUS	= S.CONTRACT_STATUS,
	T.ALLOW_EXTRA_COVERAGE_DEADLINE	= S.ALLOW_EXTRA_COVERAGE_DEADLINE,
	T.PRODUCT_RELEASE_COMPLETED_BY	= S.PRODUCT_RELEASE_COMPLETED_BY,
	T.PRODUCT_RELEASE_COMPLETED_DATE	= S.PRODUCT_RELEASE_COMPLETED_DATE,
	T.COVER_DETAILS_PROVIDED	= S.COVER_DETAILS_PROVIDED,
	T.COVER_APPROVED	= S.COVER_APPROVED,
	T.SIGNING_INFO	= S.SIGNING_INFO,
	T.YB_ENROLLED	= S.YB_ENROLLED,
	T.YB_ENROLLED_DATE	= S.YB_ENROLLED_DATE
	,                                                                                                  T.ODS_MODIFY_DATE	= SYSDATE
when not matched
then insert
	(
	T.APO_OID,
	T.ACCOUNT_NAME,
	T.APO_TAG,
	T.BOOKING_OPP_ID,
	T.BOOKING_YEAR,
	T.BUS_CONTEXT_NAME,
	T.CONSUMER_ENQ_PHONE,
	T.CONSUMER_MODEL,
	T.CONSUMER_SORT,
	T.CONTACT,
	T.CREATED_BY,
	T.CURRENCY,
	T.DATE_CREATED,
	T.DEFAULT_ORD_PKG,
	T.DESCRIPTION,
	T.ENROLLMENT_COUNT,
	T.FAX,
	T.HIGH_GRADE,
	T.JOB_IDENTIFIER,
	T.LAB_INSTRUCTIONS,
	T.LANGUAGE,
	T.LAST_UPDATED,
	T.LID,
	T.LOC_CODE,
	T.LOW_GRADE,
	T.MARKETING_CODE,
	T.NACAM_OVERALL,
	T.OFFER_ONLINE_ORDERING,
	T.ORDER_FORM,
	T.ORDER_FORM_ITEM_ID,
	T.PHONE,
	T.PHONE_ORDER,
	T.PHOTO_LOCATION,
	T.PROCESSING_LAB,
	T.PROGRAM,
	T.PROOF_EXPRESS,
	T.PUBLISHED,
	T.REMINDER_POSTCARD,
	T.REPORT_GRP,
	T.REVISION_NO,
	T.RISK_CODE,
	T.RISK_TEXT,
	T.SALES_REP_CODE,
	T.SALES_REP_NAME,
	T.SCHOOL_YR_END,
	T.SELLING_METHOD,
	T.SERVICE_CENTER,
	T.SERVICE_PRODUCT_SORT,
	T.SHIP_TO,
	T.STATUS,
	T.SUB_PROGRAM,
	T.SVC_PROD_MODEL,
	T.TAX_CERTIFICATE,
	T.TAX_EXEMPT,
	T.TERRITORY,
	T.TWO_WEEK_RETURN_MSG,
	T.UPDATED_BY,
	T.VISION_JOB,
	T.SOURCE_SYSTEM_OID,
	T.ID,
	T.VERSION,
	T.ADDRESS,
	T.CITY,
	T.COUNTRY,
	T.COUNTY,
	T.FINANCIAL_PROCESSING_SYSTEM,
	T.FULFILLING_LAB_SYSTEM,
	T.LANGUAGE2,
	T.OPERATIONS_REP_NAME,
	T.POSTAL_CODE,
	T.RISK_IND,
	T.VALIDATION_ERROR,
	T.CATEGORY,
	T.SUBCATEGORY,
	T.LOCK_ON_NAME,
	T.ORIGINAL_BOOKING_REP,
	T.ORIGINAL_BOOKING_REP_NAME,
	T.EST_TO_BE_PHOTOED,
	T.ENVELOPE_ID,
	T.CAMERA_PLATFORM,
	T.CONFIRMED_LAB,
	T.CONTRACT_RECEIVED,
	T.APO_TYPE,
	T.YB_PROGRAM,
	T.FINALIZED_DATE,
	T.COVER_RECEIVED,
	T.SALE_TYPE,
	T.ENABLE_PRISM,
	T.BOOK_OFFERING,
	T.INCENTIVE_GRANTED,
	T.CONTRACT_STATUS,
	T.ALLOW_EXTRA_COVERAGE_DEADLINE,
	T.PRODUCT_RELEASE_COMPLETED_BY,
	T.PRODUCT_RELEASE_COMPLETED_DATE,
	T.COVER_DETAILS_PROVIDED,
	T.COVER_APPROVED,
	T.SIGNING_INFO,
	T.YB_ENROLLED,
	T.YB_ENROLLED_DATE
	,                                                                                                   T.ODS_CREATE_DATE,
	T.ODS_MODIFY_DATE
	)
values
	(
	S.APO_OID,
	S.ACCOUNT_NAME,
	S.APO_TAG,
	S.BOOKING_OPP_ID,
	S.BOOKING_YEAR,
	S.BUS_CONTEXT_NAME,
	S.CONSUMER_ENQ_PHONE,
	S.CONSUMER_MODEL,
	S.CONSUMER_SORT,
	S.CONTACT,
	S.CREATED_BY,
	S.CURRENCY,
	S.DATE_CREATED,
	S.DEFAULT_ORD_PKG,
	S.DESCRIPTION,
	S.ENROLLMENT_COUNT,
	S.FAX,
	S.HIGH_GRADE,
	S.JOB_IDENTIFIER,
	S.LAB_INSTRUCTIONS,
	S.LANGUAGE,
	S.LAST_UPDATED,
	S.LID,
	S.LOC_CODE,
	S.LOW_GRADE,
	S.MARKETING_CODE,
	S.NACAM_OVERALL,
	S.OFFER_ONLINE_ORDERING,
	S.ORDER_FORM,
	S.ORDER_FORM_ITEM_ID,
	S.PHONE,
	S.PHONE_ORDER,
	S.PHOTO_LOCATION,
	S.PROCESSING_LAB,
	S.PROGRAM,
	S.PROOF_EXPRESS,
	S.PUBLISHED,
	S.REMINDER_POSTCARD,
	S.REPORT_GRP,
	S.REVISION_NO,
	S.RISK_CODE,
	S.RISK_TEXT,
	S.SALES_REP_CODE,
	S.SALES_REP_NAME,
	S.SCHOOL_YR_END,
	S.SELLING_METHOD,
	S.SERVICE_CENTER,
	S.SERVICE_PRODUCT_SORT,
	S.SHIP_TO,
	S.STATUS,
	S.SUB_PROGRAM,
	S.SVC_PROD_MODEL,
	S.TAX_CERTIFICATE,
	S.TAX_EXEMPT,
	S.TERRITORY,
	S.TWO_WEEK_RETURN_MSG,
	S.UPDATED_BY,
	S.VISION_JOB,
	S.SOURCE_SYSTEM_OID,
	S.ID,
	S.VERSION,
	S.ADDRESS,
	S.CITY,
	S.COUNTRY,
	S.COUNTY,
	S.FINANCIAL_PROCESSING_SYSTEM,
	S.FULFILLING_LAB_SYSTEM,
	S.LANGUAGE2,
	S.OPERATIONS_REP_NAME,
	S.POSTAL_CODE,
	S.RISK_IND,
	S.VALIDATION_ERROR,
	S.CATEGORY,
	S.SUBCATEGORY,
	S.LOCK_ON_NAME,
	S.ORIGINAL_BOOKING_REP,
	S.ORIGINAL_BOOKING_REP_NAME,
	S.EST_TO_BE_PHOTOED,
	S.ENVELOPE_ID,
	S.CAMERA_PLATFORM,
	S.CONFIRMED_LAB,
	S.CONTRACT_RECEIVED,
	S.APO_TYPE,
	S.YB_PROGRAM,
	S.FINALIZED_DATE,
	S.COVER_RECEIVED,
	S.SALE_TYPE,
	S.ENABLE_PRISM,
	S.BOOK_OFFERING,
	S.INCENTIVE_GRANTED,
	S.CONTRACT_STATUS,
	S.ALLOW_EXTRA_COVERAGE_DEADLINE,
	S.PRODUCT_RELEASE_COMPLETED_BY,
	S.PRODUCT_RELEASE_COMPLETED_DATE,
	S.COVER_DETAILS_PROVIDED,
	S.COVER_APPROVED,
	S.SIGNING_INFO,
	S.YB_ENROLLED,
	S.YB_ENROLLED_DATE
	,                                                                                                   SYSDATE,
	SYSDATE
	)

&


/*-----------------------------------------------*/
/* TASK No. 26 */
/* Commit transaction */

/*commit*/


/*-----------------------------------------------*/
/* TASK No. 27 */
/* Drop flow table */

BEGIN  
   EXECUTE IMMEDIATE 'drop table RAX_APP_USER.I$_FOW_APO_STAGE646001';  
EXCEPTION  
   WHEN OTHERS THEN  
      IF SQLCODE != -942 THEN  
         RAISE;  
      END IF;  
END;

&


/*-----------------------------------------------*/
/* TASK No. 28 */
/* Drop driver table */

BEGIN  
   EXECUTE IMMEDIATE 'DROP TABLE RAX_APP_USER.TMP_IAPO_SI_D';  
EXCEPTION  
   WHEN OTHERS THEN  
      IF SQLCODE != -942 THEN  
         RAISE;  
      END IF;  
END;

&


/*-----------------------------------------------*/
/* TASK No. 29 */
/* Create driver table */

CREATE TABLE RAX_APP_USER.TMP_IAPO_SI_D (
EVENT_OID number,
SPECTRUM_IND number
)



&


/*-----------------------------------------------*/
/* TASK No. 30 */
/* insert into driver table */

insert into RAX_APP_USER.TMP_IAPO_SI_D
( event_oid, spectrum_ind )
select 
    event.event_oid, 0
from
    ODS_OWN.APO apo
    ,ODS_OWN.EVENT event
    ,ODS_OWN.SOURCE_SYSTEM ss   	
where (1=1)
   and apo.SOURCE_SYSTEM_OID = SS.SOURCE_SYSTEM_OID and SS.SOURCE_SYSTEM_SHORT_NAME = 'FOW'
   and not exists (select 1 from  RAX_APP_USER.TMP_IAPO_SI_D s where s.event_oid = event.event_oid)   
    and apo.APO_OID = event.APO_OID
    and apo.STATUS = 'Inactive'    
    and apo.ODS_MODIFY_DATE >=  TO_DATE(SUBSTR(:v_cdc_load_date,1,19),'YYYY-MM-DD HH24:MI:SS') - :v_cdc_oms_overlap
group by
    event.event_oid



&


/*-----------------------------------------------*/
/* TASK No. 31 */
/* UPDATE ODS_OWN.EVENT.SPECTRUM_IND */

MERGE INTO ODS_OWN.EVENT EVENT
USING
(
SELECT EVENT_OID, SPECTRUM_IND FROM RAX_APP_USER.TMP_IAPO_SI_D where SPECTRUM_IND is not null 
) driver
ON
( 
 EVENT.EVENT_OID=driver.EVENT_OID
)
WHEN MATCHED THEN UPDATE
SET EVENT.SPECTRUM_IND=driver.SPECTRUM_IND ,
ODS_MODIFY_DATE=SYSDATE

&


/*-----------------------------------------------*/
/* TASK No. 32 */
/* Update CDC Load Status */

UPDATE ODS_OWN.ODS_CDC_LOAD_STATUS
SET LAST_CDC_COMPLETION_DATE=TO_DATE(
             SUBSTR(:v_sess_beg, 1, 19), 'RRRR-MM-DD HH24:MI:SS')
+ nvl((TIMEZONE_OFFSET/24), 0) 
WHERE ODS_TABLE_NAME=:v_cdc_load_table_name
AND CONTEXT_NAME = :v_env

/*
UPDATE ODS_OWN.ODS_CDC_LOAD_STATUS
SET LAST_CDC_COMPLETION_DATE=TO_DATE(
             SUBSTR(:v_sess_beg, 1, 19), 'RRRR-MM-DD HH24:MI:SS')
WHERE ODS_TABLE_NAME=:v_cdc_load_table_name
AND CONTEXT_NAME = :v_env
*/

&


/*-----------------------------------------------*/
/* TASK No. 33 */
/* Insert CDC Audit Record */

INSERT INTO RAX_APP_USER.ODS_CDC_LOAD_STATUS_AUDIT
(TABLE_NAME,
SESS_NO,                      
SESS_NAME,                    
SCEN_VERSION,                 
SESS_BEG,                     
ORIG_LAST_CDC_COMPLETION_DATE,
OVERLAP,
CREATE_DATE,
CONTEXT_NAME,
TIMEZONE_OFFSET              
)
select 
:v_cdc_load_table_name
,:v_sess_no
,'LOAD_FOW_APO_PKG'
,'049'
,TO_DATE(SUBSTR(:v_sess_beg, 1, 19), 'RRRR-MM-DD HH24:MI:SS')
,TO_DATE (SUBSTR(:v_cdc_load_date, 1, 19),'YYYY-MM-DD HH24:MI:SS')
,:v_cdc_overlap
,SYSDATE
,:v_env
,TIMEZONE_OFFSET
from 
ODS_OWN.ODS_CDC_LOAD_STATUS
WHERE ODS_TABLE_NAME=:v_cdc_load_table_name
AND CONTEXT_NAME = :v_env

/*
INSERT INTO RAX_APP_USER.ODS_CDC_LOAD_STATUS_AUDIT
(TABLE_NAME,
SESS_NO,                      
SESS_NAME,                    
SCEN_VERSION,                 
SESS_BEG,                     
ORIG_LAST_CDC_COMPLETION_DATE,
OVERLAP,
CREATE_DATE,
CONTEXT_NAME              
)
values (
:v_cdc_load_table_name,
:v_sess_no,
'LOAD_FOW_APO_PKG',
'049',
TO_DATE(
             SUBSTR(:v_sess_beg, 1, 19), 'RRRR-MM-DD HH24:MI:SS'),
TO_DATE (SUBSTR (:v_cdc_load_date, 1, 19),
                           'YYYY-MM-DD HH24:MI:SS'
                          )
,:v_cdc_overlap,
SYSDATE,
 :v_env)
*/


&


/*-----------------------------------------------*/
