
            DECLARE create_query CLOB;  
            BEGIN  
                BEGIN  
                    EXECUTE IMMEDIATE 'DROP TABLE RAX_APP_USER.c$_0ybpy_orderline';  
                EXCEPTION  
                    WHEN OTHERS THEN NULL;  
                END;  
                create_query := 'create table RAX_APP_USER.C$_0YBPY_ORDERLINE
(
	C1_ID	NUMBER NULL,
	C2_ORDERID	NUMBER NULL,
	C3_STUDENTID	NUMBER NULL,
	C4_FIRSTNAME	VARCHAR2(80) NULL,
	C5_LASTNAME	VARCHAR2(80) NULL,
	C6_GRADEID	NUMBER NULL,
	C7_GRADEDESCRIPTION	VARCHAR2(50) NULL,
	C8_PACKAGESCHOOLPRICINGID	NUMBER NULL,
	C9_PACKAGENAME	VARCHAR2(200) NULL,
	C10_QUANTITY	NUMBER NULL,
	C11_YEARBOOKPRICE	NUMBER NULL,
	C12_YEARBOOKTAX	NUMBER NULL,
	C13_DONATIONAMOUNT	NUMBER NULL,
	C14_TOTALAMOUNT	NUMBER NULL,
	C15_TOTALTAX	NUMBER NULL,
	C16_CREATEDATE	DATE NULL,
	C17_LASTCHANGEDATE	DATE NULL,
	C18_INCLUDEDLINE	NUMBER NULL,
	C19_INCLUDEDICON	NUMBER NULL
)
NOLOGGING';
                EXECUTE IMMEDIATE create_query;
            END;  
            