
            DECLARE create_query CLOB;  
            BEGIN  
                BEGIN  
                    EXECUTE IMMEDIATE 'DROP TABLE RAX_APP_USER.c$_0ybpy_order';  
                EXCEPTION  
                    WHEN OTHERS THEN NULL;  
                END;  
                create_query := 'create table RAX_APP_USER.C$_0YBPY_ORDER
(
	C1_ID	NUMBER NULL,
	C2_ORDERDATE	DATE NULL,
	C3_TRANSACTIONDATE	DATE NULL,
	C4_TRANSACTIONID	VARCHAR2(50) NULL,
	C5_JOBNUMBER	NUMBER NULL,
	C6_SCHOOLNAME	VARCHAR2(35) NULL,
	C7_SCHOOLCOUNTRY	VARCHAR2(2) NULL,
	C8_TOTALAMOUNT	NUMBER NULL,
	C9_TAXAMOUNT	NUMBER NULL,
	C10_TAXEXEMPTIND	NUMBER NULL,
	C11_CREATEDATE	DATE NULL,
	C12_LASTCHANGEDATE	DATE NULL,
	C13_ISSUBMITTEDTONEXTTOOLS	NUMBER NULL
)
NOLOGGING';
                EXECUTE IMMEDIATE create_query;
            END;  
            