select	
	KI.MODIFYUSERID	   C1_MODIFYUSERID,
	KI.ITEM_KEY	   C2_ITEM_KEY,
	KI.CREATEPROGID	   C3_CREATEPROGID,
	KI.KIT_ITEM_KEY	   C4_KIT_ITEM_KEY,
	KI.COMPONENT_ITEM_KEY	   C5_COMPONENT_ITEM_KEY,
	KI.MODIFYTS	   C6_MODIFYTS,
	KI.KIT_QUANTITY	   C7_KIT_QUANTITY,
	KI.MODIFYPROGID	   C8_MODIFYPROGID,
	KI.CREATETS	   C9_CREATETS,
	KI.LOCKID	   C10_LOCKID,
	KI.CREATEUSERID	   C11_CREATEUSERID
from	<schema_name>.YFS_KIT_ITEM   KI
where	(1=1)
And (KI.MODIFYTS >= TO_DATE(SUBSTR(:v_cdc_load_date, 1, 19), 'YYYY-MM-DD HH24:MI:SS')  -:v_cdc_oms_overlap)
