select	
	PROMO.DESCRIPTION	   C1_DESCRIPTION,
	PROMO.PROMOTION_ID	   C2_PROMOTION_ID,
	trim(PROMO.ORDER_HEADER_KEY)	   C3_ORDER_HEADER_KEY,
	PROMO.PROMOTION_TYPE	   C4_PROMOTION_TYPE,
	PROMO.DENIAL_REASON	   C5_DENIAL_REASON,
	PROMO.MODIFYTS	   C6_MODIFYTS,
	PROMO.MODIFYUSERID	   C7_MODIFYUSERID,
	PROMO.PROMOTION_APPLIED	   C8_PROMOTION_APPLIED,
	PROMO.CREATETS	   C9_CREATETS,
	PROMO.CREATEUSERID	   C10_CREATEUSERID,
	PROMO.MODIFYPROGID	   C11_MODIFYPROGID,
	trim(PROMO.PROMOTION_KEY)	   C12_PROMOTION_KEY,
	PROMO.CREATEPROGID	   C13_CREATEPROGID,
	PROMO.LOCKID	   C14_LOCKID
from	<schema_name>.YFS_PROMOTION   PROMO
where	(1=1)
And (PROMO.MODIFYTS >= TO_DATE(SUBSTR(:v_cdc_load_date, 1, 19), 'YYYY-MM-DD HH24:MI:SS')  -:v_cdc_oms_overlap)
