select	
	HC.CHARGE_NAME	   C1_CHARGE_NAME,
	HC.HEADER_KEY	   C2_HEADER_KEY,
	HC.CHARGE	   C3_CHARGE,
	HC.EXTN_CHARGE_DESCRIPTION	   C4_EXTN_CHARGE_DESCRIPTION,
	HC.MODIFYTS	   C5_MODIFYTS,
	HC.MODIFYPROGID	   C6_MODIFYPROGID,
	HC.CHARGE_CATEGORY	   C7_CHARGE_CATEGORY,
	HC.EXTN_TAXABLE	   C8_EXTN_TAXABLE,
	HC.CREATEPROGID	   C9_CREATEPROGID,
	HC.MODIFYUSERID	   C10_MODIFYUSERID,
	HC.REFERENCE	   C11_REFERENCE,
	HC.CREATETS	   C12_CREATETS,
	HC.EXTN_ACCOUNTING_TYPE	   C13_EXTN_ACCOUNTING_TYPE,
	HC.LOCKID	   C14_LOCKID,
	HC.INVOICED_CHARGE	   C15_INVOICED_CHARGE,
	HC.EXTN_TAX_INCLUSIVE	   C16_EXTN_TAX_INCLUSIVE,
	HC.EXTN_TCREDIT_PERCENTAGE	   C17_EXTN_TCREDIT_PERCENTAGE,
	HC.EXTN_TAX_CODE	   C18_EXTN_TAX_CODE,
	HC.CREATEUSERID	   C19_CREATEUSERID,
	HC.RECORD_TYPE	   C20_RECORD_TYPE,
	HC.ORIGINAL_CHARGE	   C21_ORIGINAL_CHARGE,
	HC.HEADER_CHARGES_KEY	   C22_HEADER_CHARGES_KEY
from	<schema_name>.YFS_HEADER_CHARGES   HC
where	(1=1)
And (HC.MODIFYTS >= TO_DATE(SUBSTR(:v_cdc_load_date, 1, 19), 'YYYY-MM-DD HH24:MI:SS')  -:v_cdc_oms_overlap)
