---

pipeline:
  name: lt_99_yearbook_freight_dag
  description: lifetouch 99_yearbook_freight_chargebacks package
  schedule: "* 7 * * *"
  tags:
    - lifetouch
    - 99_YEARBOOK_FREIGHT_CHARGEBACKS
  
  task_groups:
    - name: 99_YEARBOOK_FREIGHT_CHARGEBACKS_export
      description: drop and recreate table then extract data and load to s3
      export_file_name:
        v_data_export_run_date: dags/sql/pre_sql/v_data_export_run_date.sql

      tasks:
        - script_location: dags/sql/99_YEARBOOK_FREIGHT_CHARGEBACKS_PKG/create_tmp_FREIGHT_CHARGEBACKS.sql
          export_files:
            - extract_query: '99_YEARBOOK_FREIGHT_CHARGEBACKS_PKG/export_YB_FREIGHT_CHARGEBACKS.sql'
              export_location: finance/yearbook_sales/YearbookFreightChargebacksByJob
