select 	
	SENIORS_D42_PAYMENTS_TMP.PAYMENT_REFERENCE2	   PAYMENT_REFERENCE2,
	SENIORS_D42_PAYMENTS_TMP.REF_DATE	   REF_DATE,
	SENIORS_D42_PAYMENTS_TMP.DR_CR	   DR_CR,
	SENIORS_D42_PAYMENTS_TMP.AMOUNT	   AMOUNT,
	SENIORS_D42_PAYMENTS_TMP.PAYMENT_REFERENCE3	   PAYMENT_REFERENCE3,
	SENIORS_D42_PAYMENTS_TMP.ORDER_NO	   ORDER_NO,
	SENIORS_D42_PAYMENTS_TMP.TERRITORY_CODE	   TERRITORY_CODE
from	RAX_APP_USER.SENIORS_D42_PAYMENTS_TMP   SENIORS_D42_PAYMENTS_TMP
where	
	(1=1)	
