
            DECLARE create_query CLOB;  
            BEGIN  
                BEGIN  
                    EXECUTE IMMEDIATE 'DROP TABLE rax_app_user.c$_0nxtl_schoolpricing';  
                EXCEPTION  
                    WHEN OTHERS THEN NULL;  
                END;  
                create_query := 'create table RAX_APP_USER.C$_0NXTL_SCHOOLPRICING
(
	C1_SCHOOLPRICINGID	NUMBER NULL,
	C2_JOBID	NUMBER NULL,
	C3_BOOKOPTIONCODE	NUMBER NULL,
	C4_PRICE	NUMBER NULL,
	C5_PRICEPERLINE	NUMBER NULL,
	C6_PRICEPERICON	NUMBER NULL,
	C7_QUANTITY	NUMBER NULL,
	C8_DISCOUNT	NUMBER NULL,
	C9_DROPCONFIRMED	NUMBER NULL,
	C10_DESCRIPTION	VARCHAR2(200) NULL,
	C11_PRICEPERLINE2	NUMBER NULL,
	C12_PRODUCTCATEGORYID	NUMBER NULL,
	C13_ADVERTISEMENTSIZEID	NUMBER NULL,
	C14_ADVERTISEMENTINITIALQUANTI	NUMBER NULL,
	C15_ISACTIVEYBPAY	NUMBER NULL,
	C16_QUANTITYORDERED	NUMBER NULL,
	C17_INCLUDEDLINE	NUMBER NULL,
	C18_INCLUDEDICON	NUMBER NULL,
	C19_PRECONFIGUREDPACKAGEID	NUMBER NULL
)
NOLOGGING';
                EXECUTE IMMEDIATE create_query;
            END;  
            