
            DECLARE create_query CLOB;  
            BEGIN  
                BEGIN  
                    EXECUTE IMMEDIATE 'DROP TABLE rax_app_user.c$_0nxtl_person';  
                EXCEPTION  
                    WHEN OTHERS THEN NULL;  
                END;  
                create_query := 'create table RAX_APP_USER.C$_0NXTL_PERSON
(
	C1_PERSONID	NUMBER NULL,
	C2_PORTRAITGROUPTYPEID	NUMBER NULL,
	C3_FIRSTNAME	VARCHAR2(80) NULL,
	C4_LASTNAME	VARCHAR2(80) NULL,
	C5_PERSONTYPE	NUMBER NULL,
	C6_COURTESY	VARCHAR2(5) NULL,
	C7_JOBID	NUMBER NULL,
	C8_STDBOOKCOUNT	NUMBER NULL,
	C9_IMPRINTLNONE	VARCHAR2(32) NULL,
	C10_IMPRINTLNTWO	VARCHAR2(32) NULL,
	C11_MODIFIEDBY	NUMBER NULL,
	C12_MODIFIEDDATE	DATE NULL,
	C13_UPLOADCODE	VARCHAR2(50) NULL,
	C14_CREATEDDATE	DATE NULL,
	C15_ISTEACHER	NUMBER NULL,
	C16_PAYMENTDATE	DATE NULL,
	C17_PAYMENTREC	NUMBER NULL,
	C18_NOTES	VARCHAR2(255) NULL,
	C19_EXTERNALID	NUMBER NULL,
	C20_CURRENTPORTRAIT	NUMBER NULL,
	C21_ORDERORIGINID	NUMBER NULL,
	C22_ORIGINREFERENCENUMBER	VARCHAR2(50) NULL,
	C23_PACKAGESCHOOLPRICINGID	NUMBER NULL,
	C24_EFFECTIVEPRICE	NUMBER NULL,
	C25_TOTALAMOUNT	NUMBER NULL,
	C26_TOTALTAX	NUMBER NULL,
	C27_DONATIONAMOUNT	NUMBER NULL,
	C28_PORTRAITIMAGEURL	VARCHAR2(200) NULL,
	C29_ORDERDATE	DATE NULL,
	C30_LASTMODIFIEDDATE	DATE NULL,
	C31_LASTMODIFIEDBY	VARCHAR2(50) NULL,
	C32_DISCOUNT	NUMBER NULL,
	C33_GRADEID	NUMBER NULL,
	C34_JOBPRICINGOVERRIDEID	NUMBER NULL,
	C35_INCLUDEDLINE	NUMBER NULL,
	C36_INCLUDEDICON	NUMBER NULL,
	C37_CIRID	VARCHAR2(50) NULL,
	C38_PORTRAITPOSEENABLE	NUMBER NULL,
	C39_CURRENTPORTRAITPOSE	NUMBER NULL,
	C40_CUSTOMEREMAIL	VARCHAR2(256) NULL,
	C41_SUBJECT_KEY	VARCHAR2(255) NULL
)
NOLOGGING';
                EXECUTE IMMEDIATE create_query;
            END;  
            