select	
	SCHOOLPRICING.SchoolPricingId	 as  C1_SCHOOLPRICINGID,
	SCHOOLPRICING.JobId	 as  C2_JOBID,
	SCHOOLPRICING.BookOptionCode	 as  C3_BOOKOPTIONCODE,
	SCHOOLPRICING.Price	 as  C4_PRICE,
	SCHOOLPRICING.PricePerLine	 as  C5_PRICEPERLINE,
	SCHOOLPRICING.PricePerIcon	 as  C6_PRICEPERICON,
	SCHOOLPRICING.Quantity	 as  C7_QUANTITY,
	SCHOOLPRICING.Discount	 as  C8_DISCOUNT,
	SCHOOLPRICING.DropConfirmed	 as  C9_DROPCONFIRMED,
	SCHOOLPRICING.Description	 as  C10_DESCRIPTION,
	SCHOOLPRICING.PricePerLine2	 as  C11_PRICEPERLINE2,
	SCHOOLPRICING.ProductCategoryId	 as  C12_PRODUCTCATEGORYID,
	SCHOOLPRICING.AdvertisementSizeId	 as  C13_ADVERTISEMENTSIZEID,
	SCHOOLPRICING.AdvertisementInitialQuantity	 as  C14_ADVERTISEMENTINITIALQUANTI,
	SCHOOLPRICING.IsActiveYbPay	 as  C15_ISACTIVEYBPAY,
	SCHOOLPRICING.QuantityOrdered	 as  C16_QUANTITYORDERED,
	SCHOOLPRICING.IncludedLine	 as  C17_INCLUDEDLINE,
	SCHOOLPRICING.IncludedIcon	 as  C18_INCLUDEDICON,
	SCHOOLPRICING.PreConfiguredPackageId	 as  C19_PRECONFIGUREDPACKAGEID
from	<schema_name>.dbo.SchoolPricing as SCHOOLPRICING
where	(1=1)