select	
	PERSONBOOKOPTION.PersonId	 as  C1_PERSONID,
	PERSONBOOKOPTION.BookOptionId	 as  C2_BOOKOPTIONID,
	PERSONBOOKOPTION.DiscountOverride	 as  C3_DISCOUNTOVERRIDE,
	PERSONBOOKOPTION.RefundDate	 as  C4_REFUNDDATE,
	PERSONBOOKOPTION.ImprintLine1EffectivePrice	 as  C5_IMPRINTLINE1EFFECTIVEPRICE,
	PERSONBOOKOPTION.ImprintLine2EffectivePrice	 as  C6_IMPRINTLINE2EFFECTIVEPRICE,
	PERSONBOOKOPTION.IconEffectivePrice	 as  C7_ICONEFFECTIVEPRICE,
	PERSONBOOKOPTION.EffectivePrice	 as  C8_EFFECTIVEPRICE,
	PERSONBOOKOPTION.IsPackageComponent	 as  C9_ISPACKAGECOMPONENT
from	<schema_name>.dbo.PersonBookOption as PERSONBOOKOPTION
where	(1=1)