select	
	JOBUSERSURVEYANSWER.JobUserSurveyAnswerId	 as  C1_JOBUSERSURVEYANSWERID,
	JOBUSERSURVEYANSWER.JobUserId	 as  C2_JOBUSERID,
	JOBUSERSURVEYANSWER.QuestionId	 as  C3_QUESTIONID,
	JOBUSERSURVEYANSWER.AnswerSelection	 as  C4_ANSWERSELECTION,
	JOBUSERSURVEYANSWER.AnswerText	 as  C5_ANSWERTEXT,
	JOBUSERSURVEYANSWER.AnswerDate	 as  C6_ANSWERDATE
from	<schema_name>.dbo.JobUserSurveyAnswer as JOBUSERSURVEYANSWER
where	(1=1)