select	
	JOBFINAL.JobId	 as  C1_JOBID,
	JOBFINAL.Books	 as  C2_BOOKS,
	JOBFINAL.HardCount	 as  C3_HARDCOUNT,
	JOBFINAL.SoftCount	 as  C4_SOFTCOUNT,
	JOBFINAL.BookSubmitDate	 as  C5_BOOKSUBMITDATE,
	JOBFINAL.BookSubmitUserId	 as  C6_BOOKSUBMITUSERID,
	JOBFINAL.AutographSignPenCount	 as  C7_AUTOGRAPHSIGNPENCOUNT,
	JOBFINAL.CoverKeeperCount	 as  C8_COVERKEEPERCOUNT,
	JOBFINAL.TapedZoomCount	 as  C9_TAPEDZOOMCOUNT,
	JOBFINAL.EnhancementSubmitDate	 as  C10_ENHANCEMENTSUBMITDATE,
	JOBFINAL.EnhancementSubmitUserId	 as  C11_ENHANCEMENTSUBMITUSERID,
	JOBFINAL.ToSellViaBestSeller	 as  C12_TOSELLVIABESTSELLER,
	JOBFINAL.AutographInsertCount	 as  C13_AUTOGRAPHINSERTCOUNT,
	JOBFINAL.YearbookStickyCount	 as  C14_YEARBOOKSTICKYCOUNT,
	JOBFINAL.SignPenOnlyCount	 as  C15_SIGNPENONLYCOUNT
from	<schema_name>.dbo.JobFinal as JOBFINAL
where	(1=1)