select	
	JOBUSER.JOBID	 as  C1_JOBID,
	JOBUSER.JOBUSERID	 as  C2_JOBUSERID,
	JOBUSER.JOBUSERTYPEID	 as  C3_JOBUSERTYPEID,
	JOBUSER.STARTDATE	 as  C4_STARTDATE,
	JOBUSER.LASTSIGNIN	 as  C5_LASTSIGNIN,
	JOBUSER.SIGNINCOUNT	 as  C6_SIGNINCOUNT,
	JOBUSER.ISACTIVE	 as  C7_ISACTIVE,
	JOBUSER.LEGALACCEPTED	 as  C8_LEGALACCEPTED,
	JOBUSER.FIRSTNAME	 as  C9_FIRSTNAME,
	JOBUSER.LASTNAME	 as  C10_LASTNAME,
	JOBUSER.LOGINNAME	 as  C11_LOGINNAME,
	JOBUSER.EMAILADDRESS	 as  C12_EMAILADDRESS,
	JOBUSER.EMPLOYEEID	 as  C13_EMPLOYEEID,
	JOBUSER.PAGEACCESSTYPE	 as  C14_PAGEACCESSTYPE,
	JOBUSER.ACCOUNTPRINCIPALID	 as  C15_ACCOUNTPRINCIPALID,
	JOBUSER.INVITATIONID	 as  C16_INVITATIONID,
	JOBUSER.ISUSERMANAGED	 as  C17_ISUSERMANAGED
from	<schema_name>.dbo.JobUser as JOBUSER
where	(1=1)