select	
	JOBUSERTYPE.JOBUSERTYPEID	 as  C1_JOBUSERTYPEID,
	JOBUSERTYPE.DESCRIPTION	 as  C2_DESCRIPTION,
	JOBUSERTYPE.ROLERANK	 as  C3_ROLERANK,
	JOBUSERTYPE.ROLECODE	 as  C4_ROLECODE
from	<schema_name>.dbo.JobUserType as JOBUSERTYPE
where	(1=1)