select	
	LT_SUBJECT_OPT_IN_AUDIT.SUBJECT_OPT_IN_AUDIT_KEY	   C1_SUBJECT_OPT_IN_AUDIT_KEY,
	LT_SUBJECT_OPT_IN_AUDIT.SUBJECT_KEY	   C2_SUBJECT_KEY,
	LT_SUBJECT_OPT_IN_AUDIT.SUBJECT_ID	   C3_SUBJECT_ID,
	LT_SUBJECT_OPT_IN_AUDIT.TCPA_OPT_IN_OLD	   C4_TCPA_OPT_IN_OLD,
	LT_SUBJECT_OPT_IN_AUDIT.CASL_OPT_IN_OLD	   C5_CASL_OPT_IN_OLD,
	LT_SUBJECT_OPT_IN_AUDIT.TCPA_OPT_IN_NEW	   C6_TCPA_OPT_IN_NEW,
	LT_SUBJECT_OPT_IN_AUDIT.CASL_OPT_IN_NEW	   C7_CASL_OPT_IN_NEW,
	LT_SUBJECT_OPT_IN_AUDIT.EMAIL_ADDRESS_OLD	   C8_EMAIL_ADDRESS_OLD,
	LT_SUBJECT_OPT_IN_AUDIT.PHONE_NUMBER_OLD	   C9_PHONE_NUMBER_OLD,
	LT_SUBJECT_OPT_IN_AUDIT.EMAIL_ADDRESS_NEW	   C10_EMAIL_ADDRESS_NEW,
	LT_SUBJECT_OPT_IN_AUDIT.PHONE_NUMBER_NEW	   C11_PHONE_NUMBER_NEW,
	LT_SUBJECT_OPT_IN_AUDIT.CREATETS	   C12_CREATETS,
	LT_SUBJECT_OPT_IN_AUDIT.MODIFYTS	   C13_MODIFYTS,
	LT_SUBJECT_OPT_IN_AUDIT.CREATEUSERID	   C14_CREATEUSERID,
	LT_SUBJECT_OPT_IN_AUDIT.MODIFYUSERID	   C15_MODIFYUSERID,
	LT_SUBJECT_OPT_IN_AUDIT.CREATEPROGID	   C16_CREATEPROGID,
	LT_SUBJECT_OPT_IN_AUDIT.MODIFYPROGID	   C17_MODIFYPROGID,
	LT_SUBJECT_OPT_IN_AUDIT.LOCKID	   C18_LOCKID,
	LT_SUBJECT_OPT_IN_AUDIT.ALT_EMAIL_ADDRESS_OLD	   C19_ALT_EMAIL_ADDRESS_OLD,
	LT_SUBJECT_OPT_IN_AUDIT.ALT_EMAIL_ADDRESS_NEW	   C20_ALT_EMAIL_ADDRESS_NEW,
	LT_SUBJECT_OPT_IN_AUDIT.ALTERNATE_PHONE_NUMBER_OLD	   C21_ALTERNATE_PHONE_NUMBER_OLD,
	LT_SUBJECT_OPT_IN_AUDIT.ALTERNATE_PHONE_NUMBER_NEW	   C22_ALTERNATE_PHONE_NUMBER_NEW
from	<schema_name>.LT_SUBJECT_OPT_IN_AUDIT   LT_SUBJECT_OPT_IN_AUDIT
where	(1=1)
And (LT_SUBJECT_OPT_IN_AUDIT.MODIFYTS >=  TO_DATE(SUBSTR(:v_cdc_load_date,1,10),'YYYY-MM-DD')-1)