/* TASK No. 1 */

/* NONE or SET VARIABLE STATEMENT FOUND, CHECK ODI TASK NO. 1 */




/*-----------------------------------------------*/
/* TASK No. 2 */

/* NONE or SET VARIABLE STATEMENT FOUND, CHECK ODI TASK NO. 2 */




/*-----------------------------------------------*/
/* TASK No. 3 */

/* NONE or SET VARIABLE STATEMENT FOUND, CHECK ODI TASK NO. 3 */




/*-----------------------------------------------*/
/* TASK No. 4 */

/* SELECT STATEMENT FOUND, CHECK ODI TASK NO. 4 */




/*-----------------------------------------------*/
/* TASK No. 5 */
/* Drop work table */

-- drop table ODS_ETL_OWNER.C$_0Y0LT_SUBJECT_OPT_IN_AUDIT 

-- &


/*-----------------------------------------------*/
/* TASK No. 6 */
/* Create work table */

-- create table ODS_ETL_OWNER.C$_0Y0LT_SUBJECT_OPT_IN_AUDIT
-- (
-- 	C1_SUBJECT_OPT_IN_AUDIT_KEY	CHAR(24) NULL,
-- 	C2_SUBJECT_KEY	CHAR(24) NULL,
-- 	C3_SUBJECT_ID	VARCHAR2(15) NULL,
-- 	C4_TCPA_OPT_IN_OLD	CHAR(1) NULL,
-- 	C5_CASL_OPT_IN_OLD	CHAR(1) NULL,
-- 	C6_TCPA_OPT_IN_NEW	CHAR(1) NULL,
-- 	C7_CASL_OPT_IN_NEW	CHAR(1) NULL,
-- 	C8_EMAIL_ADDRESS_OLD	VARCHAR2(50) NULL,
-- 	C9_PHONE_NUMBER_OLD	VARCHAR2(12) NULL,
-- 	C10_EMAIL_ADDRESS_NEW	VARCHAR2(50) NULL,
-- 	C11_PHONE_NUMBER_NEW	VARCHAR2(12) NULL,
-- 	C12_CREATETS	DATE NULL,
-- 	C13_MODIFYTS	DATE NULL,
-- 	C14_CREATEUSERID	VARCHAR2(40) NULL,
-- 	C15_MODIFYUSERID	VARCHAR2(40) NULL,
-- 	C16_CREATEPROGID	VARCHAR2(40) NULL,
-- 	C17_MODIFYPROGID	VARCHAR2(40) NULL,
-- 	C18_LOCKID	NUMBER(5) NULL,
-- 	C19_ALT_EMAIL_ADDRESS_OLD	VARCHAR2(50) NULL,
-- 	C20_ALT_EMAIL_ADDRESS_NEW	VARCHAR2(50) NULL,
-- 	C21_ALTERNATE_PHONE_NUMBER_OLD	VARCHAR2(12) NULL,
-- 	C22_ALTERNATE_PHONE_NUMBER_NEW	VARCHAR2(12) NULL
-- )
-- NOLOGGING

-- &


/*-----------------------------------------------*/
/* TASK No. 7 */
/* Load data */

/* SOURCE CODE */
-- select	
-- 	LT_SUBJECT_OPT_IN_AUDIT.SUBJECT_OPT_IN_AUDIT_KEY	   C1_SUBJECT_OPT_IN_AUDIT_KEY,
-- 	LT_SUBJECT_OPT_IN_AUDIT.SUBJECT_KEY	   C2_SUBJECT_KEY,
-- 	LT_SUBJECT_OPT_IN_AUDIT.SUBJECT_ID	   C3_SUBJECT_ID,
-- 	LT_SUBJECT_OPT_IN_AUDIT.TCPA_OPT_IN_OLD	   C4_TCPA_OPT_IN_OLD,
-- 	LT_SUBJECT_OPT_IN_AUDIT.CASL_OPT_IN_OLD	   C5_CASL_OPT_IN_OLD,
-- 	LT_SUBJECT_OPT_IN_AUDIT.TCPA_OPT_IN_NEW	   C6_TCPA_OPT_IN_NEW,
-- 	LT_SUBJECT_OPT_IN_AUDIT.CASL_OPT_IN_NEW	   C7_CASL_OPT_IN_NEW,
-- 	LT_SUBJECT_OPT_IN_AUDIT.EMAIL_ADDRESS_OLD	   C8_EMAIL_ADDRESS_OLD,
-- 	LT_SUBJECT_OPT_IN_AUDIT.PHONE_NUMBER_OLD	   C9_PHONE_NUMBER_OLD,
-- 	LT_SUBJECT_OPT_IN_AUDIT.EMAIL_ADDRESS_NEW	   C10_EMAIL_ADDRESS_NEW,
-- 	LT_SUBJECT_OPT_IN_AUDIT.PHONE_NUMBER_NEW	   C11_PHONE_NUMBER_NEW,
-- 	LT_SUBJECT_OPT_IN_AUDIT.CREATETS	   C12_CREATETS,
-- 	LT_SUBJECT_OPT_IN_AUDIT.MODIFYTS	   C13_MODIFYTS,
-- 	LT_SUBJECT_OPT_IN_AUDIT.CREATEUSERID	   C14_CREATEUSERID,
-- 	LT_SUBJECT_OPT_IN_AUDIT.MODIFYUSERID	   C15_MODIFYUSERID,
-- 	LT_SUBJECT_OPT_IN_AUDIT.CREATEPROGID	   C16_CREATEPROGID,
-- 	LT_SUBJECT_OPT_IN_AUDIT.MODIFYPROGID	   C17_MODIFYPROGID,
-- 	LT_SUBJECT_OPT_IN_AUDIT.LOCKID	   C18_LOCKID,
-- 	LT_SUBJECT_OPT_IN_AUDIT.ALT_EMAIL_ADDRESS_OLD	   C19_ALT_EMAIL_ADDRESS_OLD,
-- 	LT_SUBJECT_OPT_IN_AUDIT.ALT_EMAIL_ADDRESS_NEW	   C20_ALT_EMAIL_ADDRESS_NEW,
-- 	LT_SUBJECT_OPT_IN_AUDIT.ALTERNATE_PHONE_NUMBER_OLD	   C21_ALTERNATE_PHONE_NUMBER_OLD,
-- 	LT_SUBJECT_OPT_IN_AUDIT.ALTERNATE_PHONE_NUMBER_NEW	   C22_ALTERNATE_PHONE_NUMBER_NEW
-- from	OMS2_OWN.LT_SUBJECT_OPT_IN_AUDIT   LT_SUBJECT_OPT_IN_AUDIT
-- where	(1=1)
-- And (LT_SUBJECT_OPT_IN_AUDIT.MODIFYTS >=  TO_DATE(SUBSTR(:v_cdc_load_date,1,10),'YYYY-MM-DD')-1)





-- &

-- /* TARGET CODE */
-- insert into ODS_ETL_OWNER.C$_0Y0LT_SUBJECT_OPT_IN_AUDIT
-- (
-- 	C1_SUBJECT_OPT_IN_AUDIT_KEY,
-- 	C2_SUBJECT_KEY,
-- 	C3_SUBJECT_ID,
-- 	C4_TCPA_OPT_IN_OLD,
-- 	C5_CASL_OPT_IN_OLD,
-- 	C6_TCPA_OPT_IN_NEW,
-- 	C7_CASL_OPT_IN_NEW,
-- 	C8_EMAIL_ADDRESS_OLD,
-- 	C9_PHONE_NUMBER_OLD,
-- 	C10_EMAIL_ADDRESS_NEW,
-- 	C11_PHONE_NUMBER_NEW,
-- 	C12_CREATETS,
-- 	C13_MODIFYTS,
-- 	C14_CREATEUSERID,
-- 	C15_MODIFYUSERID,
-- 	C16_CREATEPROGID,
-- 	C17_MODIFYPROGID,
-- 	C18_LOCKID,
-- 	C19_ALT_EMAIL_ADDRESS_OLD,
-- 	C20_ALT_EMAIL_ADDRESS_NEW,
-- 	C21_ALTERNATE_PHONE_NUMBER_OLD,
-- 	C22_ALTERNATE_PHONE_NUMBER_NEW
-- )
-- values
-- (
-- 	:C1_SUBJECT_OPT_IN_AUDIT_KEY,
-- 	:C2_SUBJECT_KEY,
-- 	:C3_SUBJECT_ID,
-- 	:C4_TCPA_OPT_IN_OLD,
-- 	:C5_CASL_OPT_IN_OLD,
-- 	:C6_TCPA_OPT_IN_NEW,
-- 	:C7_CASL_OPT_IN_NEW,
-- 	:C8_EMAIL_ADDRESS_OLD,
-- 	:C9_PHONE_NUMBER_OLD,
-- 	:C10_EMAIL_ADDRESS_NEW,
-- 	:C11_PHONE_NUMBER_NEW,
-- 	:C12_CREATETS,
-- 	:C13_MODIFYTS,
-- 	:C14_CREATEUSERID,
-- 	:C15_MODIFYUSERID,
-- 	:C16_CREATEPROGID,
-- 	:C17_MODIFYPROGID,
-- 	:C18_LOCKID,
-- 	:C19_ALT_EMAIL_ADDRESS_OLD,
-- 	:C20_ALT_EMAIL_ADDRESS_NEW,
-- 	:C21_ALTERNATE_PHONE_NUMBER_OLD,
-- 	:C22_ALTERNATE_PHONE_NUMBER_NEW
-- )

-- &


/*-----------------------------------------------*/
/* TASK No. 8 */
/* Analyze work table */



BEGIN
DBMS_STATS.GATHER_TABLE_STATS (
    ownname =>	'RAX_APP_USER',
    tabname =>	'C$_0Y0LT_SUBJECT_OPT_IN_AUDIT',
    estimate_percent =>	DBMS_STATS.AUTO_SAMPLE_SIZE
);
END;




&


/*-----------------------------------------------*/
/* TASK No. 10 */
/* Drop flow table */
 
BEGIN
   EXECUTE IMMEDIATE 'drop table RAX_APP_USER.I$_Y0LT_SUBJECT_OPT_IN_AUDIT';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;

&


/*-----------------------------------------------*/
/* TASK No. 11 */
/* Create flow table I$ */

create table RAX_APP_USER.I$_Y0LT_SUBJECT_OPT_IN_AUDIT
(
	EFFECTIVE_DATE	DATE NULL,
	SUBJECT_OPT_IN_AUDIT_KEY	CHAR(24) NULL,
	SUBJECT_KEY	CHAR(24) NULL,
	SUBJECT_ID	VARCHAR2(15) NULL,
	TCPA_OPT_IN_OLD	CHAR(1) NULL,
	CASL_OPT_IN_OLD	CHAR(1) NULL,
	TCPA_OPT_IN_NEW	CHAR(1) NULL,
	CASL_OPT_IN_NEW	CHAR(1) NULL,
	EMAIL_ADDRESS_OLD	VARCHAR2(50) NULL,
	PHONE_NUMBER_OLD	VARCHAR2(12) NULL,
	EMAIL_ADDRESS_NEW	VARCHAR2(50) NULL,
	PHONE_NUMBER_NEW	VARCHAR2(12) NULL,
	CREATETS	DATE NULL,
	MODIFYTS	DATE NULL,
	CREATEUSERID	VARCHAR2(40) NULL,
	MODIFYUSERID	VARCHAR2(40) NULL,
	CREATEPROGID	VARCHAR2(40) NULL,
	MODIFYPROGID	VARCHAR2(40) NULL,
	LOCKID	NUMBER(5) NULL,
	ALT_EMAIL_ADDRESS_OLD	VARCHAR2(50) NULL,
	ALT_EMAIL_ADDRESS_NEW	VARCHAR2(50) NULL,
	ALTERNATE_PHONE_NUMBER_OLD	VARCHAR2(12) NULL,
	ALTERNATE_PHONE_NUMBER_NEW	VARCHAR2(12) NULL
	,IND_UPDATE		char(1)
)
NOLOGGING

&


/*-----------------------------------------------*/
/* TASK No. 12 */
/* Insert flow into I$ table */

insert /*+ APPEND */  into RAX_APP_USER.I$_Y0LT_SUBJECT_OPT_IN_AUDIT
	(
	SUBJECT_OPT_IN_AUDIT_KEY,
	SUBJECT_KEY,
	SUBJECT_ID,
	TCPA_OPT_IN_OLD,
	CASL_OPT_IN_OLD,
	TCPA_OPT_IN_NEW,
	CASL_OPT_IN_NEW,
	EMAIL_ADDRESS_OLD,
	PHONE_NUMBER_OLD,
	EMAIL_ADDRESS_NEW,
	PHONE_NUMBER_NEW,
	CREATETS,
	MODIFYTS,
	CREATEUSERID,
	MODIFYUSERID,
	CREATEPROGID,
	MODIFYPROGID,
	LOCKID,
	ALT_EMAIL_ADDRESS_OLD,
	ALT_EMAIL_ADDRESS_NEW,
	ALTERNATE_PHONE_NUMBER_OLD,
	ALTERNATE_PHONE_NUMBER_NEW
	,IND_UPDATE
	)


select 	 
	
	C1_SUBJECT_OPT_IN_AUDIT_KEY,
	C2_SUBJECT_KEY,
	C3_SUBJECT_ID,
	C4_TCPA_OPT_IN_OLD,
	C5_CASL_OPT_IN_OLD,
	C6_TCPA_OPT_IN_NEW,
	C7_CASL_OPT_IN_NEW,
	C8_EMAIL_ADDRESS_OLD,
	C9_PHONE_NUMBER_OLD,
	C10_EMAIL_ADDRESS_NEW,
	C11_PHONE_NUMBER_NEW,
	C12_CREATETS,
	C13_MODIFYTS,
	C14_CREATEUSERID,
	C15_MODIFYUSERID,
	C16_CREATEPROGID,
	C17_MODIFYPROGID,
	C18_LOCKID,
	C19_ALT_EMAIL_ADDRESS_OLD,
	C20_ALT_EMAIL_ADDRESS_NEW,
	C21_ALTERNATE_PHONE_NUMBER_OLD,
	C22_ALTERNATE_PHONE_NUMBER_NEW,

	'I' IND_UPDATE

from	RAX_APP_USER.C$_0Y0LT_SUBJECT_OPT_IN_AUDIT
where	(1=1)






minus
select
	SUBJECT_OPT_IN_AUDIT_KEY,
	SUBJECT_KEY,
	SUBJECT_ID,
	TCPA_OPT_IN_OLD,
	CASL_OPT_IN_OLD,
	TCPA_OPT_IN_NEW,
	CASL_OPT_IN_NEW,
	EMAIL_ADDRESS_OLD,
	PHONE_NUMBER_OLD,
	EMAIL_ADDRESS_NEW,
	PHONE_NUMBER_NEW,
	CREATETS,
	MODIFYTS,
	CREATEUSERID,
	MODIFYUSERID,
	CREATEPROGID,
	MODIFYPROGID,
	LOCKID,
	ALT_EMAIL_ADDRESS_OLD,
	ALT_EMAIL_ADDRESS_NEW,
	ALTERNATE_PHONE_NUMBER_OLD,
	ALTERNATE_PHONE_NUMBER_NEW
	,'I'	IND_UPDATE
from	ODS.Y0LT_SUBJECT_OPT_IN_AUDIT

&


/*-----------------------------------------------*/
/* TASK No. 13 */
/* Analyze integration table */



begin
    dbms_stats.gather_table_stats(
	ownname => 'RAX_APP_USER',
	tabname => 'I$_Y0LT_SUBJECT_OPT_IN_AUDIT',
	estimate_percent => dbms_stats.auto_sample_size
    );
end;



&


/*-----------------------------------------------*/
/* TASK No. 14 */
/* Create Index on flow table */

create index	RAX_APP_USER.I$_Y0LT_SUBJECT_OPT_IN_AUDIT_I
on		RAX_APP_USER.I$_Y0LT_SUBJECT_OPT_IN_AUDIT (SUBJECT_OPT_IN_AUDIT_KEY)
NOLOGGING

&


/*-----------------------------------------------*/
/* TASK No. 15 */
/* Merge Rows */

merge into	ODS.Y0LT_SUBJECT_OPT_IN_AUDIT T
using	RAX_APP_USER.I$_Y0LT_SUBJECT_OPT_IN_AUDIT S
on	(
		T.SUBJECT_OPT_IN_AUDIT_KEY=S.SUBJECT_OPT_IN_AUDIT_KEY
	)
when matched
then update set
	T.SUBJECT_KEY	= S.SUBJECT_KEY,
	T.SUBJECT_ID	= S.SUBJECT_ID,
	T.TCPA_OPT_IN_OLD	= S.TCPA_OPT_IN_OLD,
	T.CASL_OPT_IN_OLD	= S.CASL_OPT_IN_OLD,
	T.TCPA_OPT_IN_NEW	= S.TCPA_OPT_IN_NEW,
	T.CASL_OPT_IN_NEW	= S.CASL_OPT_IN_NEW,
	T.EMAIL_ADDRESS_OLD	= S.EMAIL_ADDRESS_OLD,
	T.PHONE_NUMBER_OLD	= S.PHONE_NUMBER_OLD,
	T.EMAIL_ADDRESS_NEW	= S.EMAIL_ADDRESS_NEW,
	T.PHONE_NUMBER_NEW	= S.PHONE_NUMBER_NEW,
	T.CREATETS	= S.CREATETS,
	T.MODIFYTS	= S.MODIFYTS,
	T.CREATEUSERID	= S.CREATEUSERID,
	T.MODIFYUSERID	= S.MODIFYUSERID,
	T.CREATEPROGID	= S.CREATEPROGID,
	T.MODIFYPROGID	= S.MODIFYPROGID,
	T.LOCKID	= S.LOCKID,
	T.ALT_EMAIL_ADDRESS_OLD	= S.ALT_EMAIL_ADDRESS_OLD,
	T.ALT_EMAIL_ADDRESS_NEW	= S.ALT_EMAIL_ADDRESS_NEW,
	T.ALTERNATE_PHONE_NUMBER_OLD	= S.ALTERNATE_PHONE_NUMBER_OLD,
	T.ALTERNATE_PHONE_NUMBER_NEW	= S.ALTERNATE_PHONE_NUMBER_NEW
	,                     T.EFFECTIVE_DATE	= SYSDATE
when not matched
then insert
	(
	T.SUBJECT_OPT_IN_AUDIT_KEY,
	T.SUBJECT_KEY,
	T.SUBJECT_ID,
	T.TCPA_OPT_IN_OLD,
	T.CASL_OPT_IN_OLD,
	T.TCPA_OPT_IN_NEW,
	T.CASL_OPT_IN_NEW,
	T.EMAIL_ADDRESS_OLD,
	T.PHONE_NUMBER_OLD,
	T.EMAIL_ADDRESS_NEW,
	T.PHONE_NUMBER_NEW,
	T.CREATETS,
	T.MODIFYTS,
	T.CREATEUSERID,
	T.MODIFYUSERID,
	T.CREATEPROGID,
	T.MODIFYPROGID,
	T.LOCKID,
	T.ALT_EMAIL_ADDRESS_OLD,
	T.ALT_EMAIL_ADDRESS_NEW,
	T.ALTERNATE_PHONE_NUMBER_OLD,
	T.ALTERNATE_PHONE_NUMBER_NEW
	,                      T.EFFECTIVE_DATE
	)
values
	(
	S.SUBJECT_OPT_IN_AUDIT_KEY,
	S.SUBJECT_KEY,
	S.SUBJECT_ID,
	S.TCPA_OPT_IN_OLD,
	S.CASL_OPT_IN_OLD,
	S.TCPA_OPT_IN_NEW,
	S.CASL_OPT_IN_NEW,
	S.EMAIL_ADDRESS_OLD,
	S.PHONE_NUMBER_OLD,
	S.EMAIL_ADDRESS_NEW,
	S.PHONE_NUMBER_NEW,
	S.CREATETS,
	S.MODIFYTS,
	S.CREATEUSERID,
	S.MODIFYUSERID,
	S.CREATEPROGID,
	S.MODIFYPROGID,
	S.LOCKID,
	S.ALT_EMAIL_ADDRESS_OLD,
	S.ALT_EMAIL_ADDRESS_NEW,
	S.ALTERNATE_PHONE_NUMBER_OLD,
	S.ALTERNATE_PHONE_NUMBER_NEW
	,                      SYSDATE
	)

&


/*-----------------------------------------------*/
/* TASK No. 16 */
/* Commit transaction */

/*commit*/


/*-----------------------------------------------*/
/* TASK No. 17 */
/* Drop flow table */

drop table RAX_APP_USER.I$_Y0LT_SUBJECT_OPT_IN_AUDIT 

&


/*-----------------------------------------------*/
/* TASK No. 1000009 */
/* Drop work table */

drop table RAX_APP_USER.C$_0Y0LT_SUBJECT_OPT_IN_AUDIT 

&


/*-----------------------------------------------*/
/* TASK No. 18 */
/* Update CDC Load Status */

UPDATE ODS.DW_CDC_LOAD_STATUS
SET LAST_CDC_COMPLETION_DATE=TO_DATE(
             SUBSTR(:v_sess_beg, 1, 19), 'RRRR-MM-DD HH24:MI:SS')
WHERE DW_TABLE_NAME=:v_cdc_load_table_name

&


/*-----------------------------------------------*/
/* TASK No. 19 */
/* Insert Audit Record */

INSERT INTO RAX_APP_USER.DW_CDC_LOAD_STATUS_AUDIT
(TABLE_NAME,
SESS_NO,                      
SESS_NAME,                    
SCEN_VERSION,                 
SESS_BEG,                     
ORIG_LAST_CDC_COMPLETION_DATE,
OVERLAP,
CREATE_DATE              
)
values (
:v_cdc_load_table_name,
:v_sess_no,
'LOAD_OPT_IN_AUDIT_PKG',
'002',
TO_DATE(
             SUBSTR(:v_sess_beg, 1, 19), 'RRRR-MM-DD HH24:MI:SS'),
TO_DATE (SUBSTR (:v_cdc_load_date, 1, 19),
                           'YYYY-MM-DD HH24:MI:SS'
                          ),
:v_cdc_ods_overlap,
SYSDATE)

&


/*-----------------------------------------------*/
