DECLARE create_query CLOB;  
   BEGIN  
      BEGIN  
         EXECUTE IMMEDIATE 'drop table RAX_APP_USER.C$_0Y0LT_SUBJECT_OPT_IN_AUDIT';  
      EXCEPTION  
         WHEN OTHERS THEN NULL;  
      END;  
      create_query := 'create table RAX_APP_USER.C$_0Y0LT_SUBJECT_OPT_IN_AUDIT
(
	C1_SUBJECT_OPT_IN_AUDIT_KEY	CHAR(24) NULL,
	C2_SUBJECT_KEY	CHAR(24) NULL,
	C3_SUBJECT_ID	VARCHAR2(15) NULL,
	C4_TCPA_OPT_IN_OLD	CHAR(1) NULL,
	C5_CASL_OPT_IN_OLD	CHAR(1) NULL,
	C6_TCPA_OPT_IN_NEW	CHAR(1) NULL,
	C7_CASL_OPT_IN_NEW	CHAR(1) NULL,
	C8_EMAIL_ADDRESS_OLD	VARCHAR2(50) NULL,
	C9_PHONE_NUMBER_OLD	VARCHAR2(12) NULL,
	C10_EMAIL_ADDRESS_NEW	VARCHAR2(50) NULL,
	C11_PHONE_NUMBER_NEW	VARCHAR2(12) NULL,
	C12_CREATETS	DATE NULL,
	C13_MODIFYTS	DATE NULL,
	C14_CREATEUSERID	VARCHAR2(40) NULL,
	C15_MODIFYUSERID	VARCHAR2(40) NULL,
	C16_CREATEPROGID	VARCHAR2(40) NULL,
	C17_MODIFYPROGID	VARCHAR2(40) NULL,
	C18_LOCKID	NUMBER(5) NULL,
	C19_ALT_EMAIL_ADDRESS_OLD	VARCHAR2(50) NULL,
	C20_ALT_EMAIL_ADDRESS_NEW	VARCHAR2(50) NULL,
	C21_ALTERNATE_PHONE_NUMBER_OLD	VARCHAR2(12) NULL,
	C22_ALTERNATE_PHONE_NUMBER_NEW	VARCHAR2(12) NULL
)
NOLOGGING
';  
      EXECUTE IMMEDIATE create_query;  
   END;  