/* TASK No. 1 */
/* Drop work table */

-- drop table RAX_APP_USER.C$_0BOC_DRAFT_ORD_STG 

-- &


/*-----------------------------------------------*/
/* TASK No. 2 */
/* Create work table */

-- create table RAX_APP_USER.C$_0BOC_DRAFT_ORD_STG
-- (
-- 	C1_DRAFT_ORDER_ID	NUMBER(19) NULL,
-- 	C2_CREATEDATE	TIMESTAMP(6) NULL,
-- 	C3_CREATEDBY	VARCHAR2(255) NULL,
-- 	C4_MODIFIEDBY	VARCHAR2(255) NULL,
-- 	C5_MODIFYDATE	TIMESTAMP(6) NULL,
-- 	C6_EMAIL_ADDRESS	VARCHAR2(255) NULL,
-- 	C7_EVENT_REF_ID	VARCHAR2(255) NULL,
-- 	C8_MATCH_TYPE	VARCHAR2(255) NULL,
-- 	C9_ORDER_FORM_ID	VARCHAR2(255) NULL,
-- 	C10_ORDER_TYPE	VARCHAR2(255) NULL,
-- 	C11_PARENT_FIRST_NAME	VARCHAR2(255) NULL,
-- 	C12_PARENT_LAST_NAME	VARCHAR2(255) NULL,
-- 	C13_PARENT_PHONE_NUMBER	VARCHAR2(255) NULL,
-- 	C14_REQUIRES_ATTENTION	NUMBER(1) NULL,
-- 	C15_SESSION_ID	VARCHAR2(255) NULL,
-- 	C16_SHIPPING_AMOUNT	VARCHAR2(255) NULL,
-- 	C17_SOURCE_SYSTEM_ID	VARCHAR2(255) NULL,
-- 	C18_STATUS	VARCHAR2(255) NULL,
-- 	C19_SUBJECT_ALPHA_NUMBER	VARCHAR2(255) NULL,
-- 	C20_SUBJECT_FIRST_NAME	VARCHAR2(255) NULL,
-- 	C21_SUBJECT_GRADE	VARCHAR2(255) NULL,
-- 	C22_SUBJECT_LAST_NAME	VARCHAR2(255) NULL,
-- 	C23_UNPAID	NUMBER(1) NULL,
-- 	C24_BILL_TO_ADDRESS	NUMBER(19) NULL,
-- 	C25_SHIP_TO_ADDRESS	NUMBER(19) NULL,
-- 	C26_SM_SUBJECT_FIRST_NAME	VARCHAR2(255) NULL,
-- 	C27_SM_SUBJECT_LAST_NAME	VARCHAR2(255) NULL,
-- 	C28_EXCEPTION_REASON	VARCHAR2(255) NULL,
-- 	C29_ORDER_BATCH_ID	NUMBER(19) NULL,
-- 	C30_EVENT_ID	NUMBER(19) NULL,
-- 	C31_MATCHED_EVENT_ID	NUMBER(19) NULL,
-- 	C32_ORIG_DRAFT_ORDER_ID	NUMBER(19) NULL,
-- 	C33_PRICING_CONTEXT	VARCHAR2(25) NULL,
-- 	C34_GENERATED	NUMBER(1) NULL,
-- 	C35_ORIG_RETAKE_NUMBER	VARCHAR2(20) NULL,
-- 	C36_PROCESSED_AMOUNT	VARCHAR2(20) NULL,
-- 	C37_EXTERNAL_ORDER_NUMBER	VARCHAR2(100) NULL,
-- 	C38_MATCHING_REQUIRED	NUMBER(1) NULL,
-- 	C39_BATCHING_REQUIRED	NUMBER(1) NULL,
-- 	C40_ORDER_PROCESSING_TYPE	VARCHAR2(50) NULL
-- )
-- NOLOGGING

-- &


/*-----------------------------------------------*/
/* TASK No. 3 */
/* Load data */

/* SOURCE CODE */
-- select	
-- 	DRAFT_ORDER.DRAFT_ORDER_ID	   C1_DRAFT_ORDER_ID,
-- 	DRAFT_ORDER.CREATEDATE	   C2_CREATEDATE,
-- 	DRAFT_ORDER.CREATEDBY	   C3_CREATEDBY,
-- 	DRAFT_ORDER.MODIFIEDBY	   C4_MODIFIEDBY,
-- 	DRAFT_ORDER.MODIFYDATE	   C5_MODIFYDATE,
-- 	DRAFT_ORDER.EMAIL_ADDRESS	   C6_EMAIL_ADDRESS,
-- 	DRAFT_ORDER.EVENT_REF_ID	   C7_EVENT_REF_ID,
-- 	DRAFT_ORDER.MATCH_TYPE	   C8_MATCH_TYPE,
-- 	DRAFT_ORDER.ORDER_FORM_ID	   C9_ORDER_FORM_ID,
-- 	DRAFT_ORDER.ORDER_TYPE	   C10_ORDER_TYPE,
-- 	DRAFT_ORDER.PARENT_FIRST_NAME	   C11_PARENT_FIRST_NAME,
-- 	DRAFT_ORDER.PARENT_LAST_NAME	   C12_PARENT_LAST_NAME,
-- 	DRAFT_ORDER.PARENT_PHONE_NUMBER	   C13_PARENT_PHONE_NUMBER,
-- 	DRAFT_ORDER.REQUIRES_ATTENTION	   C14_REQUIRES_ATTENTION,
-- 	DRAFT_ORDER.SESSION_ID	   C15_SESSION_ID,
-- 	DRAFT_ORDER.SHIPPING_AMOUNT	   C16_SHIPPING_AMOUNT,
-- 	DRAFT_ORDER.SOURCE_SYSTEM_ID	   C17_SOURCE_SYSTEM_ID,
-- 	DRAFT_ORDER.STATUS	   C18_STATUS,
-- 	DRAFT_ORDER.SUBJECT_ALPHA_NUMBER	   C19_SUBJECT_ALPHA_NUMBER,
-- 	DRAFT_ORDER.SUBJECT_FIRST_NAME	   C20_SUBJECT_FIRST_NAME,
-- 	DRAFT_ORDER.SUBJECT_GRADE	   C21_SUBJECT_GRADE,
-- 	DRAFT_ORDER.SUBJECT_LAST_NAME	   C22_SUBJECT_LAST_NAME,
-- 	DRAFT_ORDER.UNPAID	   C23_UNPAID,
-- 	DRAFT_ORDER.BILL_TO_ADDRESS	   C24_BILL_TO_ADDRESS,
-- 	DRAFT_ORDER.SHIP_TO_ADDRESS	   C25_SHIP_TO_ADDRESS,
-- 	DRAFT_ORDER.SM_SUBJECT_FIRST_NAME	   C26_SM_SUBJECT_FIRST_NAME,
-- 	DRAFT_ORDER.SM_SUBJECT_LAST_NAME	   C27_SM_SUBJECT_LAST_NAME,
-- 	DRAFT_ORDER.EXCEPTION_REASON	   C28_EXCEPTION_REASON,
-- 	DRAFT_ORDER.ORDER_BATCH_ID	   C29_ORDER_BATCH_ID,
-- 	DRAFT_ORDER.EVENT_ID	   C30_EVENT_ID,
-- 	DRAFT_ORDER.MATCHED_EVENT_ID	   C31_MATCHED_EVENT_ID,
-- 	DRAFT_ORDER.ORIG_DRAFT_ORDER_ID	   C32_ORIG_DRAFT_ORDER_ID,
-- 	DRAFT_ORDER.PRICING_CONTEXT	   C33_PRICING_CONTEXT,
-- 	DRAFT_ORDER.GENERATED	   C34_GENERATED,
-- 	DRAFT_ORDER.ORIG_RETAKE_NUMBER	   C35_ORIG_RETAKE_NUMBER,
-- 	DRAFT_ORDER.PROCESSED_AMOUNT	   C36_PROCESSED_AMOUNT,
-- 	DRAFT_ORDER.EXTERNAL_ORDER_NUMBER	   C37_EXTERNAL_ORDER_NUMBER,
-- 	DRAFT_ORDER.MATCHING_REQUIRED	   C38_MATCHING_REQUIRED,
-- 	DRAFT_ORDER.BATCHING_REQUIRED	   C39_BATCHING_REQUIRED,
-- 	DRAFT_ORDER.ORDER_PROCESSING_TYPE	   C40_ORDER_PROCESSING_TYPE
-- from	BOC_OWN.DRAFT_ORDER   DRAFT_ORDER
-- where	(1=1)
-- And (DRAFT_ORDER.MODIFYDATE >=  ( TO_DATE(SUBSTR(:v_cdc_ld_date, 1, 19), 'YYYY-MM-DD HH24:MI:SS')  - :v_cdc_oms_overlap))





-- &

/* TARGET CODE */
-- insert into RAX_APP_USER.C$_0BOC_DRAFT_ORD_STG
-- (
-- 	C1_DRAFT_ORDER_ID,
-- 	C2_CREATEDATE,
-- 	C3_CREATEDBY,
-- 	C4_MODIFIEDBY,
-- 	C5_MODIFYDATE,
-- 	C6_EMAIL_ADDRESS,
-- 	C7_EVENT_REF_ID,
-- 	C8_MATCH_TYPE,
-- 	C9_ORDER_FORM_ID,
-- 	C10_ORDER_TYPE,
-- 	C11_PARENT_FIRST_NAME,
-- 	C12_PARENT_LAST_NAME,
-- 	C13_PARENT_PHONE_NUMBER,
-- 	C14_REQUIRES_ATTENTION,
-- 	C15_SESSION_ID,
-- 	C16_SHIPPING_AMOUNT,
-- 	C17_SOURCE_SYSTEM_ID,
-- 	C18_STATUS,
-- 	C19_SUBJECT_ALPHA_NUMBER,
-- 	C20_SUBJECT_FIRST_NAME,
-- 	C21_SUBJECT_GRADE,
-- 	C22_SUBJECT_LAST_NAME,
-- 	C23_UNPAID,
-- 	C24_BILL_TO_ADDRESS,
-- 	C25_SHIP_TO_ADDRESS,
-- 	C26_SM_SUBJECT_FIRST_NAME,
-- 	C27_SM_SUBJECT_LAST_NAME,
-- 	C28_EXCEPTION_REASON,
-- 	C29_ORDER_BATCH_ID,
-- 	C30_EVENT_ID,
-- 	C31_MATCHED_EVENT_ID,
-- 	C32_ORIG_DRAFT_ORDER_ID,
-- 	C33_PRICING_CONTEXT,
-- 	C34_GENERATED,
-- 	C35_ORIG_RETAKE_NUMBER,
-- 	C36_PROCESSED_AMOUNT,
-- 	C37_EXTERNAL_ORDER_NUMBER,
-- 	C38_MATCHING_REQUIRED,
-- 	C39_BATCHING_REQUIRED,
-- 	C40_ORDER_PROCESSING_TYPE
-- )
-- values
-- (
-- 	:C1_DRAFT_ORDER_ID,
-- 	:C2_CREATEDATE,
-- 	:C3_CREATEDBY,
-- 	:C4_MODIFIEDBY,
-- 	:C5_MODIFYDATE,
-- 	:C6_EMAIL_ADDRESS,
-- 	:C7_EVENT_REF_ID,
-- 	:C8_MATCH_TYPE,
-- 	:C9_ORDER_FORM_ID,
-- 	:C10_ORDER_TYPE,
-- 	:C11_PARENT_FIRST_NAME,
-- 	:C12_PARENT_LAST_NAME,
-- 	:C13_PARENT_PHONE_NUMBER,
-- 	:C14_REQUIRES_ATTENTION,
-- 	:C15_SESSION_ID,
-- 	:C16_SHIPPING_AMOUNT,
-- 	:C17_SOURCE_SYSTEM_ID,
-- 	:C18_STATUS,
-- 	:C19_SUBJECT_ALPHA_NUMBER,
-- 	:C20_SUBJECT_FIRST_NAME,
-- 	:C21_SUBJECT_GRADE,
-- 	:C22_SUBJECT_LAST_NAME,
-- 	:C23_UNPAID,
-- 	:C24_BILL_TO_ADDRESS,
-- 	:C25_SHIP_TO_ADDRESS,
-- 	:C26_SM_SUBJECT_FIRST_NAME,
-- 	:C27_SM_SUBJECT_LAST_NAME,
-- 	:C28_EXCEPTION_REASON,
-- 	:C29_ORDER_BATCH_ID,
-- 	:C30_EVENT_ID,
-- 	:C31_MATCHED_EVENT_ID,
-- 	:C32_ORIG_DRAFT_ORDER_ID,
-- 	:C33_PRICING_CONTEXT,
-- 	:C34_GENERATED,
-- 	:C35_ORIG_RETAKE_NUMBER,
-- 	:C36_PROCESSED_AMOUNT,
-- 	:C37_EXTERNAL_ORDER_NUMBER,
-- 	:C38_MATCHING_REQUIRED,
-- 	:C39_BATCHING_REQUIRED,
-- 	:C40_ORDER_PROCESSING_TYPE
-- )

-- &


/*-----------------------------------------------*/
/* TASK No. 4 */
/* Analyze work table */



BEGIN
DBMS_STATS.GATHER_TABLE_STATS (
    ownname =>	'RAX_APP_USER',
    tabname =>	'C$_0BOC_DRAFT_ORD_STG',
    estimate_percent =>	DBMS_STATS.AUTO_SAMPLE_SIZE
);
END;




&


/*-----------------------------------------------*/
/* TASK No. 6 */
/* Set vID */

/* NONE or SET VARIABLE STATEMENT FOUND, CHECK ODI TASK NO. 6 */




/*-----------------------------------------------*/
/* TASK No. 7 */
/* Drop flow table */

-- drop table RAX_APP_USER.I$_BOC_DRAFT_ORD_STG726001

BEGIN  
   EXECUTE IMMEDIATE 'drop table RAX_APP_USER.I$_BOC_DRAFT_ORD_STG726001 ';  
EXCEPTION  
   WHEN OTHERS THEN  
      IF SQLCODE != -942 THEN  
         RAISE;  
      END IF;  
END;

&


/*-----------------------------------------------*/
/* TASK No. 8 */
/* Create flow table I$ */

create table RAX_APP_USER.I$_BOC_DRAFT_ORD_STG726001
(
	DRAFT_ORDER_ID		NUMBER(19) NULL,
	CREATEDATE		TIMESTAMP(6) NULL,
	CREATEDBY		VARCHAR2(255) NULL,
	MODIFIEDBY		VARCHAR2(255) NULL,
	MODIFYDATE		TIMESTAMP(6) NULL,
	EMAIL_ADDRESS		VARCHAR2(255) NULL,
	EVENT_REF_ID		VARCHAR2(255) NULL,
	MATCH_TYPE		VARCHAR2(255) NULL,
	ORDER_FORM_ID		VARCHAR2(255) NULL,
	ORDER_TYPE		VARCHAR2(255) NULL,
	PARENT_FIRST_NAME		VARCHAR2(255) NULL,
	PARENT_LAST_NAME		VARCHAR2(255) NULL,
	PARENT_PHONE_NUMBER		VARCHAR2(255) NULL,
	REQUIRES_ATTENTION		NUMBER(1) NULL,
	SESSION_ID		VARCHAR2(255) NULL,
	SHIPPING_AMOUNT		VARCHAR2(255) NULL,
	SOURCE_SYSTEM_ID		VARCHAR2(255) NULL,
	STATUS		VARCHAR2(255) NULL,
	SUBJECT_ALPHA_NUMBER		VARCHAR2(255) NULL,
	SUBJECT_FIRST_NAME		VARCHAR2(255) NULL,
	SUBJECT_GRADE		VARCHAR2(255) NULL,
	SUBJECT_LAST_NAME		VARCHAR2(255) NULL,
	UNPAID		NUMBER(1) NULL,
	BILL_TO_ADDRESS		NUMBER(19) NULL,
	SHIP_TO_ADDRESS		NUMBER(19) NULL,
	SM_SUBJECT_FIRST_NAME		VARCHAR2(255) NULL,
	SM_SUBJECT_LAST_NAME		VARCHAR2(255) NULL,
	EXCEPTION_REASON		VARCHAR2(255) NULL,
	ORDER_BATCH_ID		NUMBER(19) NULL,
	EVENT_ID		NUMBER(19) NULL,
	MATCHED_EVENT_ID		NUMBER(19) NULL,
	ORIG_DRAFT_ORDER_ID		NUMBER(19) NULL,
	PRICING_CONTEXT		VARCHAR2(25) NULL,
	GENERATED		NUMBER(1) NULL,
	ORIG_RETAKE_NUMBER		VARCHAR2(20) NULL,
	PROCESSED_AMOUNT		VARCHAR2(20) NULL,
	EXTERNAL_ORDER_NUMBER		VARCHAR2(100) NULL,
	MATCHING_REQUIRED		NUMBER(1) NULL,
	BATCHING_REQUIRED		NUMBER(1) NULL,
	ORDER_PROCESSING_TYPE		VARCHAR2(50) NULL,
	ODS_CREATE_DATE		DATE NULL,
	ODS_MODIFY_DATE		DATE NULL,
	DRAFT_ORDER_OID		NUMBER NULL,
	IND_UPDATE		CHAR(1)
)
NOLOGGING

&


/*-----------------------------------------------*/
/* TASK No. 9 */
/* Insert flow into I$ table */

/* DETECTION_STRATEGY = POST_FLOW */
 


  
  
  


insert into	RAX_APP_USER.I$_BOC_DRAFT_ORD_STG726001
(
	DRAFT_ORDER_ID,
	CREATEDATE,
	CREATEDBY,
	MODIFIEDBY,
	MODIFYDATE,
	EMAIL_ADDRESS,
	EVENT_REF_ID,
	MATCH_TYPE,
	ORDER_FORM_ID,
	ORDER_TYPE,
	PARENT_FIRST_NAME,
	PARENT_LAST_NAME,
	PARENT_PHONE_NUMBER,
	REQUIRES_ATTENTION,
	SESSION_ID,
	SHIPPING_AMOUNT,
	SOURCE_SYSTEM_ID,
	STATUS,
	SUBJECT_ALPHA_NUMBER,
	SUBJECT_FIRST_NAME,
	SUBJECT_GRADE,
	SUBJECT_LAST_NAME,
	UNPAID,
	BILL_TO_ADDRESS,
	SHIP_TO_ADDRESS,
	SM_SUBJECT_FIRST_NAME,
	SM_SUBJECT_LAST_NAME,
	EXCEPTION_REASON,
	ORDER_BATCH_ID,
	EVENT_ID,
	MATCHED_EVENT_ID,
	ORIG_DRAFT_ORDER_ID,
	PRICING_CONTEXT,
	GENERATED,
	ORIG_RETAKE_NUMBER,
	PROCESSED_AMOUNT,
	EXTERNAL_ORDER_NUMBER,
	MATCHING_REQUIRED,
	BATCHING_REQUIRED,
	ORDER_PROCESSING_TYPE,
	IND_UPDATE
)


select 	 
	
	C1_DRAFT_ORDER_ID,
	C2_CREATEDATE,
	C3_CREATEDBY,
	C4_MODIFIEDBY,
	C5_MODIFYDATE,
	C6_EMAIL_ADDRESS,
	C7_EVENT_REF_ID,
	C8_MATCH_TYPE,
	C9_ORDER_FORM_ID,
	C10_ORDER_TYPE,
	C11_PARENT_FIRST_NAME,
	C12_PARENT_LAST_NAME,
	C13_PARENT_PHONE_NUMBER,
	C14_REQUIRES_ATTENTION,
	C15_SESSION_ID,
	C16_SHIPPING_AMOUNT,
	C17_SOURCE_SYSTEM_ID,
	C18_STATUS,
	C19_SUBJECT_ALPHA_NUMBER,
	C20_SUBJECT_FIRST_NAME,
	C21_SUBJECT_GRADE,
	C22_SUBJECT_LAST_NAME,
	C23_UNPAID,
	C24_BILL_TO_ADDRESS,
	C25_SHIP_TO_ADDRESS,
	C26_SM_SUBJECT_FIRST_NAME,
	C27_SM_SUBJECT_LAST_NAME,
	C28_EXCEPTION_REASON,
	C29_ORDER_BATCH_ID,
	C30_EVENT_ID,
	C31_MATCHED_EVENT_ID,
	C32_ORIG_DRAFT_ORDER_ID,
	C33_PRICING_CONTEXT,
	C34_GENERATED,
	C35_ORIG_RETAKE_NUMBER,
	C36_PROCESSED_AMOUNT,
	C37_EXTERNAL_ORDER_NUMBER,
	C38_MATCHING_REQUIRED,
	C39_BATCHING_REQUIRED,
	C40_ORDER_PROCESSING_TYPE,

	'I' IND_UPDATE

from	RAX_APP_USER.C$_0BOC_DRAFT_ORD_STG
where	(1=1)






  

 


&


/*-----------------------------------------------*/
/* TASK No. 10 */
/* Create Index on flow table */

create index	RAX_APP_USER.I$_BOC_DRAFT_ORD_STG_IDX726001
on		RAX_APP_USER.I$_BOC_DRAFT_ORD_STG726001 (DRAFT_ORDER_ID)
NOLOGGING

&


/*-----------------------------------------------*/
/* TASK No. 11 */
/* Analyze integration table */



begin
    dbms_stats.gather_table_stats(
	ownname => 'RAX_APP_USER',
	tabname => 'I$_BOC_DRAFT_ORD_STG726001',
	estimate_percent => dbms_stats.auto_sample_size
    );
end;



&


/*-----------------------------------------------*/
/* TASK No. 12 */
/* Flag rows for update */

/* DETECTION_STRATEGY = POST_FLOW */


update	RAX_APP_USER.I$_BOC_DRAFT_ORD_STG726001
set	IND_UPDATE = 'U'
where	(DRAFT_ORDER_ID)
	in	(
		select	DRAFT_ORDER_ID
		from	ODS_STAGE.BOC_DRAFT_ORDER_STAGE
		)



&


/*-----------------------------------------------*/
/* TASK No. 13 */
/* Flag useless rows */

/* DETECTION_STRATEGY = POST_FLOW */


update	RAX_APP_USER.I$_BOC_DRAFT_ORD_STG726001 S
set	IND_UPDATE = 'N'
where	exists (
	select 	'X'
	from 	ODS_STAGE.BOC_DRAFT_ORDER_STAGE 	T
	where	T.DRAFT_ORDER_ID	= S.DRAFT_ORDER_ID
		and	((T.CREATEDATE = S.CREATEDATE) or (T.CREATEDATE IS NULL and S.CREATEDATE IS NULL))
and	((T.CREATEDBY = S.CREATEDBY) or (T.CREATEDBY IS NULL and S.CREATEDBY IS NULL))
and	((T.MODIFIEDBY = S.MODIFIEDBY) or (T.MODIFIEDBY IS NULL and S.MODIFIEDBY IS NULL))
and	((T.MODIFYDATE = S.MODIFYDATE) or (T.MODIFYDATE IS NULL and S.MODIFYDATE IS NULL))
and	((T.EMAIL_ADDRESS = S.EMAIL_ADDRESS) or (T.EMAIL_ADDRESS IS NULL and S.EMAIL_ADDRESS IS NULL))
and	((T.EVENT_REF_ID = S.EVENT_REF_ID) or (T.EVENT_REF_ID IS NULL and S.EVENT_REF_ID IS NULL))
and	((T.MATCH_TYPE = S.MATCH_TYPE) or (T.MATCH_TYPE IS NULL and S.MATCH_TYPE IS NULL))
and	((T.ORDER_FORM_ID = S.ORDER_FORM_ID) or (T.ORDER_FORM_ID IS NULL and S.ORDER_FORM_ID IS NULL))
and	((T.ORDER_TYPE = S.ORDER_TYPE) or (T.ORDER_TYPE IS NULL and S.ORDER_TYPE IS NULL))
and	((T.PARENT_FIRST_NAME = S.PARENT_FIRST_NAME) or (T.PARENT_FIRST_NAME IS NULL and S.PARENT_FIRST_NAME IS NULL))
and	((T.PARENT_LAST_NAME = S.PARENT_LAST_NAME) or (T.PARENT_LAST_NAME IS NULL and S.PARENT_LAST_NAME IS NULL))
and	((T.PARENT_PHONE_NUMBER = S.PARENT_PHONE_NUMBER) or (T.PARENT_PHONE_NUMBER IS NULL and S.PARENT_PHONE_NUMBER IS NULL))
and	((T.REQUIRES_ATTENTION = S.REQUIRES_ATTENTION) or (T.REQUIRES_ATTENTION IS NULL and S.REQUIRES_ATTENTION IS NULL))
and	((T.SESSION_ID = S.SESSION_ID) or (T.SESSION_ID IS NULL and S.SESSION_ID IS NULL))
and	((T.SHIPPING_AMOUNT = S.SHIPPING_AMOUNT) or (T.SHIPPING_AMOUNT IS NULL and S.SHIPPING_AMOUNT IS NULL))
and	((T.SOURCE_SYSTEM_ID = S.SOURCE_SYSTEM_ID) or (T.SOURCE_SYSTEM_ID IS NULL and S.SOURCE_SYSTEM_ID IS NULL))
and	((T.STATUS = S.STATUS) or (T.STATUS IS NULL and S.STATUS IS NULL))
and	((T.SUBJECT_ALPHA_NUMBER = S.SUBJECT_ALPHA_NUMBER) or (T.SUBJECT_ALPHA_NUMBER IS NULL and S.SUBJECT_ALPHA_NUMBER IS NULL))
and	((T.SUBJECT_FIRST_NAME = S.SUBJECT_FIRST_NAME) or (T.SUBJECT_FIRST_NAME IS NULL and S.SUBJECT_FIRST_NAME IS NULL))
and	((T.SUBJECT_GRADE = S.SUBJECT_GRADE) or (T.SUBJECT_GRADE IS NULL and S.SUBJECT_GRADE IS NULL))
and	((T.SUBJECT_LAST_NAME = S.SUBJECT_LAST_NAME) or (T.SUBJECT_LAST_NAME IS NULL and S.SUBJECT_LAST_NAME IS NULL))
and	((T.UNPAID = S.UNPAID) or (T.UNPAID IS NULL and S.UNPAID IS NULL))
and	((T.BILL_TO_ADDRESS = S.BILL_TO_ADDRESS) or (T.BILL_TO_ADDRESS IS NULL and S.BILL_TO_ADDRESS IS NULL))
and	((T.SHIP_TO_ADDRESS = S.SHIP_TO_ADDRESS) or (T.SHIP_TO_ADDRESS IS NULL and S.SHIP_TO_ADDRESS IS NULL))
and	((T.SM_SUBJECT_FIRST_NAME = S.SM_SUBJECT_FIRST_NAME) or (T.SM_SUBJECT_FIRST_NAME IS NULL and S.SM_SUBJECT_FIRST_NAME IS NULL))
and	((T.SM_SUBJECT_LAST_NAME = S.SM_SUBJECT_LAST_NAME) or (T.SM_SUBJECT_LAST_NAME IS NULL and S.SM_SUBJECT_LAST_NAME IS NULL))
and	((T.EXCEPTION_REASON = S.EXCEPTION_REASON) or (T.EXCEPTION_REASON IS NULL and S.EXCEPTION_REASON IS NULL))
and	((T.ORDER_BATCH_ID = S.ORDER_BATCH_ID) or (T.ORDER_BATCH_ID IS NULL and S.ORDER_BATCH_ID IS NULL))
and	((T.EVENT_ID = S.EVENT_ID) or (T.EVENT_ID IS NULL and S.EVENT_ID IS NULL))
and	((T.MATCHED_EVENT_ID = S.MATCHED_EVENT_ID) or (T.MATCHED_EVENT_ID IS NULL and S.MATCHED_EVENT_ID IS NULL))
and	((T.ORIG_DRAFT_ORDER_ID = S.ORIG_DRAFT_ORDER_ID) or (T.ORIG_DRAFT_ORDER_ID IS NULL and S.ORIG_DRAFT_ORDER_ID IS NULL))
and	((T.PRICING_CONTEXT = S.PRICING_CONTEXT) or (T.PRICING_CONTEXT IS NULL and S.PRICING_CONTEXT IS NULL))
and	((T.GENERATED = S.GENERATED) or (T.GENERATED IS NULL and S.GENERATED IS NULL))
and	((T.ORIG_RETAKE_NUMBER = S.ORIG_RETAKE_NUMBER) or (T.ORIG_RETAKE_NUMBER IS NULL and S.ORIG_RETAKE_NUMBER IS NULL))
and	((T.PROCESSED_AMOUNT = S.PROCESSED_AMOUNT) or (T.PROCESSED_AMOUNT IS NULL and S.PROCESSED_AMOUNT IS NULL))
and	((T.EXTERNAL_ORDER_NUMBER = S.EXTERNAL_ORDER_NUMBER) or (T.EXTERNAL_ORDER_NUMBER IS NULL and S.EXTERNAL_ORDER_NUMBER IS NULL))
and	((T.MATCHING_REQUIRED = S.MATCHING_REQUIRED) or (T.MATCHING_REQUIRED IS NULL and S.MATCHING_REQUIRED IS NULL))
and	((T.BATCHING_REQUIRED = S.BATCHING_REQUIRED) or (T.BATCHING_REQUIRED IS NULL and S.BATCHING_REQUIRED IS NULL))
and	((T.ORDER_PROCESSING_TYPE = S.ORDER_PROCESSING_TYPE) or (T.ORDER_PROCESSING_TYPE IS NULL and S.ORDER_PROCESSING_TYPE IS NULL))
	)



&


/*-----------------------------------------------*/
/* TASK No. 14 */
/* Update existing rows */

/* DETECTION_STRATEGY = POST_FLOW */
update	ODS_STAGE.BOC_DRAFT_ORDER_STAGE T
set 	
	(
	T.CREATEDATE,
	T.CREATEDBY,
	T.MODIFIEDBY,
	T.MODIFYDATE,
	T.EMAIL_ADDRESS,
	T.EVENT_REF_ID,
	T.MATCH_TYPE,
	T.ORDER_FORM_ID,
	T.ORDER_TYPE,
	T.PARENT_FIRST_NAME,
	T.PARENT_LAST_NAME,
	T.PARENT_PHONE_NUMBER,
	T.REQUIRES_ATTENTION,
	T.SESSION_ID,
	T.SHIPPING_AMOUNT,
	T.SOURCE_SYSTEM_ID,
	T.STATUS,
	T.SUBJECT_ALPHA_NUMBER,
	T.SUBJECT_FIRST_NAME,
	T.SUBJECT_GRADE,
	T.SUBJECT_LAST_NAME,
	T.UNPAID,
	T.BILL_TO_ADDRESS,
	T.SHIP_TO_ADDRESS,
	T.SM_SUBJECT_FIRST_NAME,
	T.SM_SUBJECT_LAST_NAME,
	T.EXCEPTION_REASON,
	T.ORDER_BATCH_ID,
	T.EVENT_ID,
	T.MATCHED_EVENT_ID,
	T.ORIG_DRAFT_ORDER_ID,
	T.PRICING_CONTEXT,
	T.GENERATED,
	T.ORIG_RETAKE_NUMBER,
	T.PROCESSED_AMOUNT,
	T.EXTERNAL_ORDER_NUMBER,
	T.MATCHING_REQUIRED,
	T.BATCHING_REQUIRED,
	T.ORDER_PROCESSING_TYPE
	) =
		(
		select	S.CREATEDATE,
			S.CREATEDBY,
			S.MODIFIEDBY,
			S.MODIFYDATE,
			S.EMAIL_ADDRESS,
			S.EVENT_REF_ID,
			S.MATCH_TYPE,
			S.ORDER_FORM_ID,
			S.ORDER_TYPE,
			S.PARENT_FIRST_NAME,
			S.PARENT_LAST_NAME,
			S.PARENT_PHONE_NUMBER,
			S.REQUIRES_ATTENTION,
			S.SESSION_ID,
			S.SHIPPING_AMOUNT,
			S.SOURCE_SYSTEM_ID,
			S.STATUS,
			S.SUBJECT_ALPHA_NUMBER,
			S.SUBJECT_FIRST_NAME,
			S.SUBJECT_GRADE,
			S.SUBJECT_LAST_NAME,
			S.UNPAID,
			S.BILL_TO_ADDRESS,
			S.SHIP_TO_ADDRESS,
			S.SM_SUBJECT_FIRST_NAME,
			S.SM_SUBJECT_LAST_NAME,
			S.EXCEPTION_REASON,
			S.ORDER_BATCH_ID,
			S.EVENT_ID,
			S.MATCHED_EVENT_ID,
			S.ORIG_DRAFT_ORDER_ID,
			S.PRICING_CONTEXT,
			S.GENERATED,
			S.ORIG_RETAKE_NUMBER,
			S.PROCESSED_AMOUNT,
			S.EXTERNAL_ORDER_NUMBER,
			S.MATCHING_REQUIRED,
			S.BATCHING_REQUIRED,
			S.ORDER_PROCESSING_TYPE
		from	RAX_APP_USER.I$_BOC_DRAFT_ORD_STG726001 S
		where	T.DRAFT_ORDER_ID	=S.DRAFT_ORDER_ID
	    	 )
	,                                       T.ODS_MODIFY_DATE = SYSDATE,
	T.DRAFT_ORDER_OID = ODS_STAGE.BOC_DRAFT_ORDER_SEQ.NEXTVAL

where	(DRAFT_ORDER_ID)
	in	(
		select	DRAFT_ORDER_ID
		from	RAX_APP_USER.I$_BOC_DRAFT_ORD_STG726001
		where	IND_UPDATE = 'U'
		)




&


/*-----------------------------------------------*/
/* TASK No. 15 */
/* Insert new rows */

/* DETECTION_STRATEGY = POST_FLOW */
insert into 	ODS_STAGE.BOC_DRAFT_ORDER_STAGE T
	(
	DRAFT_ORDER_ID,
	CREATEDATE,
	CREATEDBY,
	MODIFIEDBY,
	MODIFYDATE,
	EMAIL_ADDRESS,
	EVENT_REF_ID,
	MATCH_TYPE,
	ORDER_FORM_ID,
	ORDER_TYPE,
	PARENT_FIRST_NAME,
	PARENT_LAST_NAME,
	PARENT_PHONE_NUMBER,
	REQUIRES_ATTENTION,
	SESSION_ID,
	SHIPPING_AMOUNT,
	SOURCE_SYSTEM_ID,
	STATUS,
	SUBJECT_ALPHA_NUMBER,
	SUBJECT_FIRST_NAME,
	SUBJECT_GRADE,
	SUBJECT_LAST_NAME,
	UNPAID,
	BILL_TO_ADDRESS,
	SHIP_TO_ADDRESS,
	SM_SUBJECT_FIRST_NAME,
	SM_SUBJECT_LAST_NAME,
	EXCEPTION_REASON,
	ORDER_BATCH_ID,
	EVENT_ID,
	MATCHED_EVENT_ID,
	ORIG_DRAFT_ORDER_ID,
	PRICING_CONTEXT,
	GENERATED,
	ORIG_RETAKE_NUMBER,
	PROCESSED_AMOUNT,
	EXTERNAL_ORDER_NUMBER,
	MATCHING_REQUIRED,
	BATCHING_REQUIRED,
	ORDER_PROCESSING_TYPE
	,                                        ODS_CREATE_DATE,
	ODS_MODIFY_DATE,
	DRAFT_ORDER_OID
	)
select 	DRAFT_ORDER_ID,
	CREATEDATE,
	CREATEDBY,
	MODIFIEDBY,
	MODIFYDATE,
	EMAIL_ADDRESS,
	EVENT_REF_ID,
	MATCH_TYPE,
	ORDER_FORM_ID,
	ORDER_TYPE,
	PARENT_FIRST_NAME,
	PARENT_LAST_NAME,
	PARENT_PHONE_NUMBER,
	REQUIRES_ATTENTION,
	SESSION_ID,
	SHIPPING_AMOUNT,
	SOURCE_SYSTEM_ID,
	STATUS,
	SUBJECT_ALPHA_NUMBER,
	SUBJECT_FIRST_NAME,
	SUBJECT_GRADE,
	SUBJECT_LAST_NAME,
	UNPAID,
	BILL_TO_ADDRESS,
	SHIP_TO_ADDRESS,
	SM_SUBJECT_FIRST_NAME,
	SM_SUBJECT_LAST_NAME,
	EXCEPTION_REASON,
	ORDER_BATCH_ID,
	EVENT_ID,
	MATCHED_EVENT_ID,
	ORIG_DRAFT_ORDER_ID,
	PRICING_CONTEXT,
	GENERATED,
	ORIG_RETAKE_NUMBER,
	PROCESSED_AMOUNT,
	EXTERNAL_ORDER_NUMBER,
	MATCHING_REQUIRED,
	BATCHING_REQUIRED,
	ORDER_PROCESSING_TYPE
	,                                        SYSDATE,
	SYSDATE,
	ODS_STAGE.BOC_DRAFT_ORDER_SEQ.NEXTVAL
from	RAX_APP_USER.I$_BOC_DRAFT_ORD_STG726001 S



where	IND_UPDATE = 'I'



&


/*-----------------------------------------------*/
/* TASK No. 16 */
/* Commit transaction */

/*commit*/


/*-----------------------------------------------*/
/* TASK No. 17 */
/* Drop flow table */

drop table RAX_APP_USER.I$_BOC_DRAFT_ORD_STG726001 

&


/*-----------------------------------------------*/
/* TASK No. 18 */
/* sub-select inline view */

(


select 	 
	
	C1_DRAFT_ORDER_ID    DRAFT_ORDER_ID,
	C2_CREATEDATE    CREATEDATE,
	C3_CREATEDBY    CREATEDBY,
	C4_MODIFIEDBY    MODIFIEDBY,
	C5_MODIFYDATE    MODIFYDATE,
	C6_EMAIL_ADDRESS    EMAIL_ADDRESS,
	C7_EVENT_REF_ID    EVENT_REF_ID,
	C8_MATCH_TYPE    MATCH_TYPE,
	C9_ORDER_FORM_ID    ORDER_FORM_ID,
	C10_ORDER_TYPE    ORDER_TYPE,
	C11_PARENT_FIRST_NAME    PARENT_FIRST_NAME,
	C12_PARENT_LAST_NAME    PARENT_LAST_NAME,
	C13_PARENT_PHONE_NUMBER    PARENT_PHONE_NUMBER,
	C14_REQUIRES_ATTENTION    REQUIRES_ATTENTION,
	C15_SESSION_ID    SESSION_ID,
	C16_SHIPPING_AMOUNT    SHIPPING_AMOUNT,
	C17_SOURCE_SYSTEM_ID    SOURCE_SYSTEM_ID,
	C18_STATUS    STATUS,
	C19_SUBJECT_ALPHA_NUMBER    SUBJECT_ALPHA_NUMBER,
	C20_SUBJECT_FIRST_NAME    SUBJECT_FIRST_NAME,
	C21_SUBJECT_GRADE    SUBJECT_GRADE,
	C22_SUBJECT_LAST_NAME    SUBJECT_LAST_NAME,
	C23_UNPAID    UNPAID,
	C24_BILL_TO_ADDRESS    BILL_TO_ADDRESS,
	C25_SHIP_TO_ADDRESS    SHIP_TO_ADDRESS,
	C26_SM_SUBJECT_FIRST_NAME    SM_SUBJECT_FIRST_NAME,
	C27_SM_SUBJECT_LAST_NAME    SM_SUBJECT_LAST_NAME,
	C28_EXCEPTION_REASON    EXCEPTION_REASON,
	C29_ORDER_BATCH_ID    ORDER_BATCH_ID,
	C30_EVENT_ID    EVENT_ID,
	C31_MATCHED_EVENT_ID    MATCHED_EVENT_ID,
	C32_ORIG_DRAFT_ORDER_ID    ORIG_DRAFT_ORDER_ID,
	C33_PRICING_CONTEXT    PRICING_CONTEXT,
	C34_GENERATED    GENERATED,
	C35_ORIG_RETAKE_NUMBER    ORIG_RETAKE_NUMBER,
	C36_PROCESSED_AMOUNT    PROCESSED_AMOUNT,
	C37_EXTERNAL_ORDER_NUMBER    EXTERNAL_ORDER_NUMBER,
	C38_MATCHING_REQUIRED    MATCHING_REQUIRED,
	C39_BATCHING_REQUIRED    BATCHING_REQUIRED,
	C40_ORDER_PROCESSING_TYPE    ORDER_PROCESSING_TYPE,
	SYSDATE    ODS_CREATE_DATE,
	SYSDATE    ODS_MODIFY_DATE,
	ODS_STAGE.BOC_DRAFT_ORDER_SEQ.NEXTVAL    DRAFT_ORDER_OID
from	RAX_APP_USER.C$_0BOC_DRAFT_ORD_STG
where	(1=1)





)

&


/*-----------------------------------------------*/
/* TASK No. 1000005 */
/* Drop work table */

drop table RAX_APP_USER.C$_0BOC_DRAFT_ORD_STG 

&


/*-----------------------------------------------*/
