/* TASK No. 1 */
/* Drop work table */

-- drop table RAX_APP_USER.C$_0BOC_EVENT 

-- &


/*-----------------------------------------------*/
/* TASK No. 2 */
/* Create work table */

-- create table RAX_APP_USER.C$_0BOC_EVENT
-- (
-- 	C1_EVENT_ID	NUMBER(19) NULL,
-- 	C2_CREATEDATE	TIMESTAMP(6) NULL,
-- 	C3_CREATEDBY	VARCHAR2(255) NULL,
-- 	C4_MODIFIEDBY	VARCHAR2(255) NULL,
-- 	C5_MODIFYDATE	TIMESTAMP(6) NULL,
-- 	C6_EVENT_DATE	TIMESTAMP(6) NULL,
-- 	C7_EVENT_REF_ID	VARCHAR2(12) NULL,
-- 	C8_EVENT_STATUS	VARCHAR2(255) NULL,
-- 	C9_IS_XORDERS_CREATED	NUMBER(1) NULL,
-- 	C10_ACCOUNT_PROGRAM_OCCURENCE_	NUMBER(19) NULL,
-- 	C11_IS_STAFF_ORDERS_CREATED	NUMBER(1) NULL,
-- 	C12_IS_MISSING_XORDERS_CREATED	NUMBER(1) NULL,
-- 	C13_IS_EVENT_IMAGE_COMPLETED	NUMBER(1) NULL,
-- 	C14_IS_RETAKE_ORDERS_CREATED	NUMBER(1) NULL
-- )
-- NOLOGGING

-- &


/*-----------------------------------------------*/
/* TASK No. 3 */
/* Load data */

/* SOURCE CODE */
-- select	
-- 	EVENT.EVENT_ID	   C1_EVENT_ID,
-- 	to_date(to_char(EVENT.CREATEDATE,'YYYY-MM-DD hh24:mi:ss'), 'YYYY-MM-DD hh24:mi:ss')	   C2_CREATEDATE,
-- 	EVENT.CREATEDBY	   C3_CREATEDBY,
-- 	EVENT.MODIFIEDBY	   C4_MODIFIEDBY,
-- 	to_date(to_char(EVENT.MODIFYDATE,'YYYY-MM-DD hh24:mi:ss'), 'YYYY-MM-DD hh24:mi:ss')	   C5_MODIFYDATE,
-- 	to_date(substr(to_char(EVENT.EVENT_DATE),1,18),'DD-MON-YY HH24:MI:SS')	   C6_EVENT_DATE,
-- 	EVENT.EVENT_REF_ID	   C7_EVENT_REF_ID,
-- 	EVENT.EVENT_STATUS	   C8_EVENT_STATUS,
-- 	EVENT.IS_XORDERS_CREATED	   C9_IS_XORDERS_CREATED,
-- 	EVENT.ACCOUNT_PROGRAM_OCCURENCE_ID	   C10_ACCOUNT_PROGRAM_OCCURENCE_,
-- 	EVENT.IS_STAFF_ORDERS_CREATED	   C11_IS_STAFF_ORDERS_CREATED,
-- 	EVENT.IS_MISSING_XORDERS_CREATED	   C12_IS_MISSING_XORDERS_CREATED,
-- 	EVENT.IS_EVENT_IMAGE_COMPLETED	   C13_IS_EVENT_IMAGE_COMPLETED,
-- 	EVENT.IS_RETAKE_ORDERS_CREATED	   C14_IS_RETAKE_ORDERS_CREATED
-- from	BOC_OWN.EVENT   EVENT
-- where	(1=1)
-- And (EVENT.MODIFYDATE >=  ( TO_DATE(SUBSTR(:v_cdc_ld_date, 1, 19), 'YYYY-MM-DD HH24:MI:SS')  - :v_cdc_oms_overlap))





-- &

/* TARGET CODE */
-- insert into RAX_APP_USER.C$_0BOC_EVENT
-- (
-- 	C1_EVENT_ID,
-- 	C2_CREATEDATE,
-- 	C3_CREATEDBY,
-- 	C4_MODIFIEDBY,
-- 	C5_MODIFYDATE,
-- 	C6_EVENT_DATE,
-- 	C7_EVENT_REF_ID,
-- 	C8_EVENT_STATUS,
-- 	C9_IS_XORDERS_CREATED,
-- 	C10_ACCOUNT_PROGRAM_OCCURENCE_,
-- 	C11_IS_STAFF_ORDERS_CREATED,
-- 	C12_IS_MISSING_XORDERS_CREATED,
-- 	C13_IS_EVENT_IMAGE_COMPLETED,
-- 	C14_IS_RETAKE_ORDERS_CREATED
-- )
-- values
-- (
-- 	:C1_EVENT_ID,
-- 	:C2_CREATEDATE,
-- 	:C3_CREATEDBY,
-- 	:C4_MODIFIEDBY,
-- 	:C5_MODIFYDATE,
-- 	:C6_EVENT_DATE,
-- 	:C7_EVENT_REF_ID,
-- 	:C8_EVENT_STATUS,
-- 	:C9_IS_XORDERS_CREATED,
-- 	:C10_ACCOUNT_PROGRAM_OCCURENCE_,
-- 	:C11_IS_STAFF_ORDERS_CREATED,
-- 	:C12_IS_MISSING_XORDERS_CREATED,
-- 	:C13_IS_EVENT_IMAGE_COMPLETED,
-- 	:C14_IS_RETAKE_ORDERS_CREATED
-- )

-- &


/*-----------------------------------------------*/
/* TASK No. 4 */
/* Analyze work table */



BEGIN
DBMS_STATS.GATHER_TABLE_STATS (
    ownname =>	'RAX_APP_USER',
    tabname =>	'C$_0BOC_EVENT',
    estimate_percent =>	DBMS_STATS.AUTO_SAMPLE_SIZE
);
END;




&


/*-----------------------------------------------*/
/* TASK No. 6 */
/* Set vID */

/* NONE or SET VARIABLE STATEMENT FOUND, CHECK ODI TASK NO. 6 */




/*-----------------------------------------------*/
/* TASK No. 7 */
/* Drop flow table */

drop table RAX_APP_USER.I$_BOC_EVENT763001

-- BEGIN  
--    EXECUTE IMMEDIATE 'drop table RAX_APP_USER.I$_BOC_EVENT763001';  
-- EXCEPTION  
--    WHEN OTHERS THEN  
--       IF SQLCODE != -942 THEN  
--          RAISE;  
--       END IF;  
-- END;


&


/*-----------------------------------------------*/
/* TASK No. 8 */
/* Create flow table I$ */

create table RAX_APP_USER.I$_BOC_EVENT763001
(
	EVENT_ID		NUMBER(19) NULL,
	CREATEDATE		TIMESTAMP(6) NULL,
	CREATEDBY		VARCHAR2(255) NULL,
	MODIFIEDBY		VARCHAR2(255) NULL,
	MODIFYDATE		TIMESTAMP(6) NULL,
	EVENT_DATE		TIMESTAMP(6) NULL,
	EVENT_REF_ID		VARCHAR2(12) NULL,
	EVENT_STATUS		VARCHAR2(255) NULL,
	IS_XORDERS_CREATED		NUMBER(1) NULL,
	ACCOUNT_PROGRAM_OCCURENCE_ID		NUMBER(19) NULL,
	IS_STAFF_ORDERS_CREATED		NUMBER(1) NULL,
	IS_MISSING_XORDERS_CREATED		NUMBER(1) NULL,
	IS_EVENT_IMAGE_COMPLETED		NUMBER(1) NULL,
	IS_RETAKE_ORDERS_CREATED		NUMBER(1) NULL,
	ODS_CREATE_DATE		DATE NULL,
	ODS_MODIFY_DATE		DATE NULL,
	IND_UPDATE		CHAR(1)
)
NOLOGGING

&


/*-----------------------------------------------*/
/* TASK No. 9 */
/* Insert flow into I$ table */

/* DETECTION_STRATEGY = POST_FLOW */
 


  
  
  


insert into	RAX_APP_USER.I$_BOC_EVENT763001
(
	EVENT_ID,
	CREATEDATE,
	CREATEDBY,
	MODIFIEDBY,
	MODIFYDATE,
	EVENT_DATE,
	EVENT_REF_ID,
	EVENT_STATUS,
	IS_XORDERS_CREATED,
	ACCOUNT_PROGRAM_OCCURENCE_ID,
	IS_STAFF_ORDERS_CREATED,
	IS_MISSING_XORDERS_CREATED,
	IS_EVENT_IMAGE_COMPLETED,
	IS_RETAKE_ORDERS_CREATED,
	IND_UPDATE
)


select 	 
	
	C1_EVENT_ID,
	C2_CREATEDATE,
	C3_CREATEDBY,
	C4_MODIFIEDBY,
	C5_MODIFYDATE,
	C6_EVENT_DATE,
	C7_EVENT_REF_ID,
	C8_EVENT_STATUS,
	C9_IS_XORDERS_CREATED,
	C10_ACCOUNT_PROGRAM_OCCURENCE_,
	C11_IS_STAFF_ORDERS_CREATED,
	C12_IS_MISSING_XORDERS_CREATED,
	C13_IS_EVENT_IMAGE_COMPLETED,
	C14_IS_RETAKE_ORDERS_CREATED,

	'I' IND_UPDATE

from	RAX_APP_USER.C$_0BOC_EVENT
where	(1=1)






  

 


&


/*-----------------------------------------------*/
/* TASK No. 10 */
/* Create Index on flow table */

create index	RAX_APP_USER.I$_BOC_EVENT_IDX763001
on		RAX_APP_USER.I$_BOC_EVENT763001 (EVENT_ID)
NOLOGGING

&


/*-----------------------------------------------*/
/* TASK No. 11 */
/* Analyze integration table */



begin
    dbms_stats.gather_table_stats(
	ownname => 'RAX_APP_USER',
	tabname => 'I$_BOC_EVENT763001',
	estimate_percent => dbms_stats.auto_sample_size
    );
end;



&


/*-----------------------------------------------*/
/* TASK No. 12 */
/* Flag rows for update */

/* DETECTION_STRATEGY = POST_FLOW */


update	RAX_APP_USER.I$_BOC_EVENT763001
set	IND_UPDATE = 'U'
where	(EVENT_ID)
	in	(
		select	EVENT_ID
		from	ODS_STAGE.BOC_EVENT
		)



&


/*-----------------------------------------------*/
/* TASK No. 13 */
/* Flag useless rows */

/* DETECTION_STRATEGY = POST_FLOW */


update	RAX_APP_USER.I$_BOC_EVENT763001 S
set	IND_UPDATE = 'N'
where	exists (
	select 	'X'
	from 	ODS_STAGE.BOC_EVENT 	T
	where	T.EVENT_ID	= S.EVENT_ID
		and	((T.CREATEDATE = S.CREATEDATE) or (T.CREATEDATE IS NULL and S.CREATEDATE IS NULL))
and	((T.CREATEDBY = S.CREATEDBY) or (T.CREATEDBY IS NULL and S.CREATEDBY IS NULL))
and	((T.MODIFIEDBY = S.MODIFIEDBY) or (T.MODIFIEDBY IS NULL and S.MODIFIEDBY IS NULL))
and	((T.MODIFYDATE = S.MODIFYDATE) or (T.MODIFYDATE IS NULL and S.MODIFYDATE IS NULL))
and	((T.EVENT_DATE = S.EVENT_DATE) or (T.EVENT_DATE IS NULL and S.EVENT_DATE IS NULL))
and	((T.EVENT_REF_ID = S.EVENT_REF_ID) or (T.EVENT_REF_ID IS NULL and S.EVENT_REF_ID IS NULL))
and	((T.EVENT_STATUS = S.EVENT_STATUS) or (T.EVENT_STATUS IS NULL and S.EVENT_STATUS IS NULL))
and	((T.IS_XORDERS_CREATED = S.IS_XORDERS_CREATED) or (T.IS_XORDERS_CREATED IS NULL and S.IS_XORDERS_CREATED IS NULL))
and	((T.ACCOUNT_PROGRAM_OCCURENCE_ID = S.ACCOUNT_PROGRAM_OCCURENCE_ID) or (T.ACCOUNT_PROGRAM_OCCURENCE_ID IS NULL and S.ACCOUNT_PROGRAM_OCCURENCE_ID IS NULL))
and	((T.IS_STAFF_ORDERS_CREATED = S.IS_STAFF_ORDERS_CREATED) or (T.IS_STAFF_ORDERS_CREATED IS NULL and S.IS_STAFF_ORDERS_CREATED IS NULL))
and	((T.IS_MISSING_XORDERS_CREATED = S.IS_MISSING_XORDERS_CREATED) or (T.IS_MISSING_XORDERS_CREATED IS NULL and S.IS_MISSING_XORDERS_CREATED IS NULL))
and	((T.IS_EVENT_IMAGE_COMPLETED = S.IS_EVENT_IMAGE_COMPLETED) or (T.IS_EVENT_IMAGE_COMPLETED IS NULL and S.IS_EVENT_IMAGE_COMPLETED IS NULL))
and	((T.IS_RETAKE_ORDERS_CREATED = S.IS_RETAKE_ORDERS_CREATED) or (T.IS_RETAKE_ORDERS_CREATED IS NULL and S.IS_RETAKE_ORDERS_CREATED IS NULL))
	)



&


/*-----------------------------------------------*/
/* TASK No. 14 */
/* Update existing rows */

/* DETECTION_STRATEGY = POST_FLOW */
update	ODS_STAGE.BOC_EVENT T
set 	
	(
	T.CREATEDATE,
	T.CREATEDBY,
	T.MODIFIEDBY,
	T.MODIFYDATE,
	T.EVENT_DATE,
	T.EVENT_REF_ID,
	T.EVENT_STATUS,
	T.IS_XORDERS_CREATED,
	T.ACCOUNT_PROGRAM_OCCURENCE_ID,
	T.IS_STAFF_ORDERS_CREATED,
	T.IS_MISSING_XORDERS_CREATED,
	T.IS_EVENT_IMAGE_COMPLETED,
	T.IS_RETAKE_ORDERS_CREATED
	) =
		(
		select	S.CREATEDATE,
			S.CREATEDBY,
			S.MODIFIEDBY,
			S.MODIFYDATE,
			S.EVENT_DATE,
			S.EVENT_REF_ID,
			S.EVENT_STATUS,
			S.IS_XORDERS_CREATED,
			S.ACCOUNT_PROGRAM_OCCURENCE_ID,
			S.IS_STAFF_ORDERS_CREATED,
			S.IS_MISSING_XORDERS_CREATED,
			S.IS_EVENT_IMAGE_COMPLETED,
			S.IS_RETAKE_ORDERS_CREATED
		from	RAX_APP_USER.I$_BOC_EVENT763001 S
		where	T.EVENT_ID	=S.EVENT_ID
	    	 )
	,             T.ODS_MODIFY_DATE = SYSDATE

where	(EVENT_ID)
	in	(
		select	EVENT_ID
		from	RAX_APP_USER.I$_BOC_EVENT763001
		where	IND_UPDATE = 'U'
		)




&


/*-----------------------------------------------*/
/* TASK No. 15 */
/* Insert new rows */

/* DETECTION_STRATEGY = POST_FLOW */
insert into 	ODS_STAGE.BOC_EVENT T
	(
	EVENT_ID,
	CREATEDATE,
	CREATEDBY,
	MODIFIEDBY,
	MODIFYDATE,
	EVENT_DATE,
	EVENT_REF_ID,
	EVENT_STATUS,
	IS_XORDERS_CREATED,
	ACCOUNT_PROGRAM_OCCURENCE_ID,
	IS_STAFF_ORDERS_CREATED,
	IS_MISSING_XORDERS_CREATED,
	IS_EVENT_IMAGE_COMPLETED,
	IS_RETAKE_ORDERS_CREATED
	,              ODS_CREATE_DATE,
	ODS_MODIFY_DATE
	)
select 	EVENT_ID,
	CREATEDATE,
	CREATEDBY,
	MODIFIEDBY,
	MODIFYDATE,
	EVENT_DATE,
	EVENT_REF_ID,
	EVENT_STATUS,
	IS_XORDERS_CREATED,
	ACCOUNT_PROGRAM_OCCURENCE_ID,
	IS_STAFF_ORDERS_CREATED,
	IS_MISSING_XORDERS_CREATED,
	IS_EVENT_IMAGE_COMPLETED,
	IS_RETAKE_ORDERS_CREATED
	,              SYSDATE,
	SYSDATE
from	RAX_APP_USER.I$_BOC_EVENT763001 S



where	IND_UPDATE = 'I'



&


/*-----------------------------------------------*/
/* TASK No. 16 */
/* Commit transaction */

/*commit*/


/*-----------------------------------------------*/
/* TASK No. 17 */
/* Drop flow table */

drop table RAX_APP_USER.I$_BOC_EVENT763001 

&


/*-----------------------------------------------*/
/* TASK No. 18 */
/* sub-select inline view */

(


select 	 
	
	C1_EVENT_ID    EVENT_ID,
	C2_CREATEDATE    CREATEDATE,
	C3_CREATEDBY    CREATEDBY,
	C4_MODIFIEDBY    MODIFIEDBY,
	C5_MODIFYDATE    MODIFYDATE,
	C6_EVENT_DATE    EVENT_DATE,
	C7_EVENT_REF_ID    EVENT_REF_ID,
	C8_EVENT_STATUS    EVENT_STATUS,
	C9_IS_XORDERS_CREATED    IS_XORDERS_CREATED,
	C10_ACCOUNT_PROGRAM_OCCURENCE_    ACCOUNT_PROGRAM_OCCURENCE_ID,
	C11_IS_STAFF_ORDERS_CREATED    IS_STAFF_ORDERS_CREATED,
	C12_IS_MISSING_XORDERS_CREATED    IS_MISSING_XORDERS_CREATED,
	C13_IS_EVENT_IMAGE_COMPLETED    IS_EVENT_IMAGE_COMPLETED,
	C14_IS_RETAKE_ORDERS_CREATED    IS_RETAKE_ORDERS_CREATED,
	SYSDATE    ODS_CREATE_DATE,
	SYSDATE    ODS_MODIFY_DATE
from	RAX_APP_USER.C$_0BOC_EVENT
where	(1=1)





)

&


/*-----------------------------------------------*/
/* TASK No. 1000005 */
/* Drop work table */

drop table RAX_APP_USER.C$_0BOC_EVENT 

&


/*-----------------------------------------------*/
