/* TASK No. 1 */

/* SELECT STATEMENT FOUND, CHECK ODI TASK NO. 1 */

--Refresh Variable LIFETOUCH_PROJECT.v_data_export_run_date:
--select to_char(sysdate,'YYYYMMDD') from dual
--
--
--Refresh Variable LIFETOUCH_PROJECT.v_data_export_last_month_begin_date:
--select
--to_char(my_t2.CALENDAR_MONTH_BEGIN,'YYYYMMDD') CALENDAR_MONTH_BEGIN
-- from
--MART.TIME my_t
--,MART.TIME my_t2
--where (1=1) and my_t.DATE_KEY= trunc(sysdate)
--and case when my_t.MONTH_NUMBER = 1 then 12 else my_t.MONTH_NUMBER -1 end = my_t2.MONTH_NUMBER
--and case when my_t.MONTH_NUMBER = 1 then my_t.CALENDAR_YEAR -1 else my_t.CALENDAR_YEAR end  = my_t2.CALENDAR_YEAR
--and my_t2.MONTH_DAY_NUMBER=1
--
--
--Refresh Variable LIFETOUCH_PROJECT.v_data_export_last_month_end_date:
--select
--to_char(my_t2.CALENDAR_MONTH_END,'YYYYMMDD') CALENDAR_MONTH_END
--from
--MART.TIME my_t
--,MART.TIME my_t2
--where (1=1) and my_t.DATE_KEY= trunc(sysdate)
--and case when my_t.MONTH_NUMBER = 1 then 12 else my_t.MONTH_NUMBER -1 end = my_t2.MONTH_NUMBER
--and case when my_t.MONTH_NUMBER = 1 then my_t.CALENDAR_YEAR -1 else my_t.CALENDAR_YEAR end  = my_t2.CALENDAR_YEAR
--and my_t2.MONTH_DAY_NUMBER=1


/*-----------------------------------------------*/
/* TASK No. 2 */

/* SELECT STATEMENT FOUND, CHECK ODI TASK NO. 2 */




/*-----------------------------------------------*/
/* TASK No. 3 */

/* SELECT STATEMENT FOUND, CHECK ODI TASK NO. 3 */




/*-----------------------------------------------*/
/* TASK No. 4 */
/* drop table */

drop table RAX_APP_USER.POSTED_UNPOSTED_BATCHES

&


/*-----------------------------------------------*/
/* TASK No. 5 */
/* create table */

create table RAX_APP_USER.POSTED_UNPOSTED_BATCHES
(
  BEGIN_DATE          VARCHAR2(10 BYTE),
  END_DATE            VARCHAR2(10 BYTE),
  PAYMENT_TYPE   VARCHAR2(50 BYTE),
  PAYMENT_ID      NUMBER,
  LAST_MODIFIED          VARCHAR2(10 BYTE),
  LAST_MODIFIED_BY   VARCHAR2(50 BYTE),
  DATE_CREATED            VARCHAR2(10 BYTE),
  CREATED_BY   VARCHAR2(50 BYTE),
  AMOUNT          NUMBER(19,2),
  PAYMENT_DATE          VARCHAR2(10 BYTE),
  PAYMENT_BATCH_ID   NUMBER,
  CUSTOMER_ORDER_ID   NUMBER,
  PAYMENT_STATUS  VARCHAR2(50 BYTE),
  JOB_NUMBER  VARCHAR2(50 BYTE),
  CURRENCY_CODE  VARCHAR2(50 BYTE),
  SOURCE_SYSTEM VARCHAR2(50 BYTE)
)



&


/*-----------------------------------------------*/
/* TASK No. 6 */
/* insert CSP */

INSERT INTO RAX_APP_USER.POSTED_UNPOSTED_BATCHES
 (
  BEGIN_DATE
, END_DATE
, PAYMENT_TYPE
, PAYMENT_ID
, LAST_MODIFIED
, LAST_MODIFIED_BY
, DATE_CREATED
, CREATED_BY
, AMOUNT
, PAYMENT_DATE
, PAYMENT_BATCH_ID
, CUSTOMER_ORDER_ID
, PAYMENT_STATUS
, JOB_NUMBER
, CURRENCY_CODE
, SOURCE_SYSTEM
) 
select
    to_char(case when to_date(:v_data_export_last_month_begin_date,'YYYYMMDD') is null then to_date('19000101','YYYYMMDD') else to_date(:v_data_export_last_month_begin_date,'YYYYMMDD') end,'MM/DD/YYYY') BEGIN_DATE
    ,to_char(case when to_date(:v_data_export_last_month_end_date,'YYYYMMDD') is null then to_date('21000101','YYYYMMDD') else to_date(:v_data_export_last_month_end_date,'YYYYMMDD') end,'MM/DD/YYYY') END_DATE,
    pay.PAYMENT_TYPE
    ,pay.PAYMENT_ID
    ,to_char(pay.modified_on,'MM/DD/YYYY')  LAST_MODIFIED
    ,pay.modified_by LAST_MODIFIED_BY
    ,to_char(pay.created_on,'MM/DD/YYYY') DATE_CREATED
    ,pay.created_by CREATED_BY
    ,op.payment_amount AMOUNT
    ,to_char(op.posted_date,'MM/DD/YYYY') PAYMENT_DATE
    ,null PAYMENT_BATCH_ID
    ,o.order_id CUSTOMER_ORDER_ID
    ,pay.status PAYMENT_STATUS
    ,o.event_ref_id JOB_NUMBER 
    ,pay.currency_code
    ,'CSP' as SOURCE_SYSTEM
from
    ods_stage.csp_payment_stg pay
    ,ods_stage.csp_order_payment_stg op
    ,ods_stage.csp_order_stg o
where (1=1)
    and op.posted_date >= case when to_date(:v_data_export_last_month_begin_date,'YYYYMMDD') is null then to_date('19000101','YYYYMMDD') else to_date(:v_data_export_last_month_begin_date,'YYYYMMDD') end
    and op.posted_date <= case when to_date(:v_data_export_last_month_end_date,'YYYYMMDD') is null then to_date('21000101','YYYMMDD') else to_date(:v_data_export_last_month_end_date,'YYYYMMDD') end
    and op.payment_id=pay.payment_id
    and op.order_id=o.order_id

&


/*-----------------------------------------------*/
/* TASK No. 7 */
/* Generate header */

create header	(BEGIN_DATE,
	END_DATE,
	PAYMENT_TYPE,
	PAYMENT_ID,
	LAST_MODIFIED,
	LAST_MODIFIED_BY,
	DATE_CREATED,
	CREATED_BY,
	AMOUNT,
	PAYMENT_DATE,
	PAYMENT_BATCH_ID,
	CUSTOMER_ORDER_ID,
	PAYMENT_STATUS,
	JOB_NUMBER,
	CURRENCY_CODE,
	SOURCE_SYSTEM)

/*$$SNPS_START_KEYSNP$CRDWG_TABLESNP$CRTABLE_NAME=POSTED_UNPOSTED_BATCHES.csvSNP$CRLOAD_FILE=/dw_export/PROD/POSTED_UNPOSTED_BATCHES.csvSNP$CRFILE_FORMAT=DSNP$CRFILE_SEP_FIELD=0x002cSNP$CRFILE_SEP_LINE=0x000D0x000ASNP$CRFILE_FIRST_ROW=0SNP$CRFILE_ENC_FIELD="SNP$CRFILE_DEC_SEP=SNP$CRSNP$CRDWG_COLSNP$CRCOL_NAME=BEGIN_DATESNP$CRTYPE_NAME=STRINGSNP$CRORDER=1SNP$CRLENGTH=50SNP$CRPRECISION=50SNP$CRSNP$CRDWG_COLSNP$CRCOL_NAME=END_DATESNP$CRTYPE_NAME=STRINGSNP$CRORDER=2SNP$CRLENGTH=50SNP$CRPRECISION=50SNP$CRSNP$CRDWG_COLSNP$CRCOL_NAME=PAYMENT_TYPESNP$CRTYPE_NAME=STRINGSNP$CRORDER=3SNP$CRLENGTH=50SNP$CRPRECISION=50SNP$CRSNP$CRDWG_COLSNP$CRCOL_NAME=PAYMENT_IDSNP$CRTYPE_NAME=STRINGSNP$CRORDER=4SNP$CRLENGTH=50SNP$CRPRECISION=50SNP$CRSNP$CRDWG_COLSNP$CRCOL_NAME=LAST_MODIFIEDSNP$CRTYPE_NAME=STRINGSNP$CRORDER=5SNP$CRLENGTH=50SNP$CRPRECISION=50SNP$CRSNP$CRDWG_COLSNP$CRCOL_NAME=LAST_MODIFIED_BYSNP$CRTYPE_NAME=STRINGSNP$CRORDER=6SNP$CRLENGTH=50SNP$CRPRECISION=50SNP$CRSNP$CRDWG_COLSNP$CRCOL_NAME=DATE_CREATEDSNP$CRTYPE_NAME=STRINGSNP$CRORDER=7SNP$CRLENGTH=50SNP$CRPRECISION=50SNP$CRSNP$CRDWG_COLSNP$CRCOL_NAME=CREATED_BYSNP$CRTYPE_NAME=STRINGSNP$CRORDER=8SNP$CRLENGTH=50SNP$CRPRECISION=50SNP$CRSNP$CRDWG_COLSNP$CRCOL_NAME=AMOUNTSNP$CRTYPE_NAME=STRINGSNP$CRORDER=9SNP$CRLENGTH=50SNP$CRPRECISION=50SNP$CRSNP$CRDWG_COLSNP$CRCOL_NAME=PAYMENT_DATESNP$CRTYPE_NAME=STRINGSNP$CRORDER=10SNP$CRLENGTH=50SNP$CRPRECISION=50SNP$CRSNP$CRDWG_COLSNP$CRCOL_NAME=PAYMENT_BATCH_IDSNP$CRTYPE_NAME=STRINGSNP$CRORDER=11SNP$CRLENGTH=50SNP$CRPRECISION=50SNP$CRSNP$CRDWG_COLSNP$CRCOL_NAME=CUSTOMER_ORDER_IDSNP$CRTYPE_NAME=STRINGSNP$CRORDER=12SNP$CRLENGTH=50SNP$CRPRECISION=50SNP$CRSNP$CRDWG_COLSNP$CRCOL_NAME=PAYMENT_STATUSSNP$CRTYPE_NAME=STRINGSNP$CRORDER=13SNP$CRLENGTH=50SNP$CRPRECISION=50SNP$CRSNP$CRDWG_COLSNP$CRCOL_NAME=JOB_NUMBERSNP$CRTYPE_NAME=STRINGSNP$CRORDER=14SNP$CRLENGTH=50SNP$CRPRECISION=50SNP$CRSNP$CRDWG_COLSNP$CRCOL_NAME=CURRENCY_CODESNP$CRTYPE_NAME=STRINGSNP$CRORDER=15SNP$CRLENGTH=50SNP$CRPRECISION=50SNP$CRSNP$CRDWG_COLSNP$CRCOL_NAME=SOURCE_SYSTEMSNP$CRTYPE_NAME=STRINGSNP$CRORDER=16SNP$CRLENGTH=50SNP$CRPRECISION=50SNP$CR$$SNPS_END_KEY*/


&


/*-----------------------------------------------*/
/* TASK No. 8 */
/* Insert new rows */

/* SOURCE CODE */


select 	
	PB.BEGIN_DATE	   BEGIN_DATE,
	PB.END_DATE	   END_DATE,
	PB.PAYMENT_TYPE	   PAYMENT_TYPE,
	PB.PAYMENT_ID	   PAYMENT_ID,
	PB.LAST_MODIFIED	   LAST_MODIFIED,
	PB.LAST_MODIFIED_BY	   LAST_MODIFIED_BY,
	PB.DATE_CREATED	   DATE_CREATED,
	PB.CREATED_BY	   CREATED_BY,
	PB.AMOUNT	   AMOUNT,
	PB.PAYMENT_DATE	   PAYMENT_DATE,
	PB.PAYMENT_BATCH_ID	   PAYMENT_BATCH_ID,
	PB.CUSTOMER_ORDER_ID	   CUSTOMER_ORDER_ID,
	PB.PAYMENT_STATUS	   PAYMENT_STATUS,
	PB.JOB_NUMBER	   JOB_NUMBER,
	PB.CURRENCY_CODE	   CURRENCY_CODE,
	PB.SOURCE_SYSTEM	   SOURCE_SYSTEM
from	RAX_APP_USER.POSTED_UNPOSTED_BATCHES   PB
where	
	(1=1)	
	





/* Order the output by the UD1, UD2, UD3, UD4, UD5, UD6 Fields. */
 
ORDER BY  SOURCE_SYSTEM
, PAYMENT_TYPE
, PAYMENT_DATE
, PAYMENT_ID









&

/* TARGET CODE */
insert into "/dw_export/PROD/POSTED_UNPOSTED_BATCHES.csv"
(
	BEGIN_DATE,
	END_DATE,
	PAYMENT_TYPE,
	PAYMENT_ID,
	LAST_MODIFIED,
	LAST_MODIFIED_BY,
	DATE_CREATED,
	CREATED_BY,
	AMOUNT,
	PAYMENT_DATE,
	PAYMENT_BATCH_ID,
	CUSTOMER_ORDER_ID,
	PAYMENT_STATUS,
	JOB_NUMBER,
	CURRENCY_CODE,
	SOURCE_SYSTEM
                     
)
values 
(
	:BEGIN_DATE,
	:END_DATE,
	:PAYMENT_TYPE,
	:PAYMENT_ID,
	:LAST_MODIFIED,
	:LAST_MODIFIED_BY,
	:DATE_CREATED,
	:CREATED_BY,
	:AMOUNT,
	:PAYMENT_DATE,
	:PAYMENT_BATCH_ID,
	:CUSTOMER_ORDER_ID,
	:PAYMENT_STATUS,
	:JOB_NUMBER,
	:CURRENCY_CODE,
	:SOURCE_SYSTEM
                     
)
/*$$SNPS_START_KEYSNP$CRDWG_TABLESNP$CRTABLE_NAME=POSTED_UNPOSTED_BATCHES.csvSNP$CRLOAD_FILE=/dw_export/PROD/POSTED_UNPOSTED_BATCHES.csvSNP$CRFILE_FORMAT=DSNP$CRFILE_SEP_FIELD=0x002cSNP$CRFILE_SEP_LINE=0x000D0x000ASNP$CRFILE_FIRST_ROW=0SNP$CRFILE_ENC_FIELD="SNP$CRFILE_DEC_SEP=SNP$CRSNP$CRDWG_COLSNP$CRCOL_NAME=BEGIN_DATESNP$CRTYPE_NAME=STRINGSNP$CRORDER=1SNP$CRLENGTH=50SNP$CRPRECISION=50SNP$CRSNP$CRDWG_COLSNP$CRCOL_NAME=END_DATESNP$CRTYPE_NAME=STRINGSNP$CRORDER=2SNP$CRLENGTH=50SNP$CRPRECISION=50SNP$CRSNP$CRDWG_COLSNP$CRCOL_NAME=PAYMENT_TYPESNP$CRTYPE_NAME=STRINGSNP$CRORDER=3SNP$CRLENGTH=50SNP$CRPRECISION=50SNP$CRSNP$CRDWG_COLSNP$CRCOL_NAME=PAYMENT_IDSNP$CRTYPE_NAME=STRINGSNP$CRORDER=4SNP$CRLENGTH=50SNP$CRPRECISION=50SNP$CRSNP$CRDWG_COLSNP$CRCOL_NAME=LAST_MODIFIEDSNP$CRTYPE_NAME=STRINGSNP$CRORDER=5SNP$CRLENGTH=50SNP$CRPRECISION=50SNP$CRSNP$CRDWG_COLSNP$CRCOL_NAME=LAST_MODIFIED_BYSNP$CRTYPE_NAME=STRINGSNP$CRORDER=6SNP$CRLENGTH=50SNP$CRPRECISION=50SNP$CRSNP$CRDWG_COLSNP$CRCOL_NAME=DATE_CREATEDSNP$CRTYPE_NAME=STRINGSNP$CRORDER=7SNP$CRLENGTH=50SNP$CRPRECISION=50SNP$CRSNP$CRDWG_COLSNP$CRCOL_NAME=CREATED_BYSNP$CRTYPE_NAME=STRINGSNP$CRORDER=8SNP$CRLENGTH=50SNP$CRPRECISION=50SNP$CRSNP$CRDWG_COLSNP$CRCOL_NAME=AMOUNTSNP$CRTYPE_NAME=STRINGSNP$CRORDER=9SNP$CRLENGTH=50SNP$CRPRECISION=50SNP$CRSNP$CRDWG_COLSNP$CRCOL_NAME=PAYMENT_DATESNP$CRTYPE_NAME=STRINGSNP$CRORDER=10SNP$CRLENGTH=50SNP$CRPRECISION=50SNP$CRSNP$CRDWG_COLSNP$CRCOL_NAME=PAYMENT_BATCH_IDSNP$CRTYPE_NAME=STRINGSNP$CRORDER=11SNP$CRLENGTH=50SNP$CRPRECISION=50SNP$CRSNP$CRDWG_COLSNP$CRCOL_NAME=CUSTOMER_ORDER_IDSNP$CRTYPE_NAME=STRINGSNP$CRORDER=12SNP$CRLENGTH=50SNP$CRPRECISION=50SNP$CRSNP$CRDWG_COLSNP$CRCOL_NAME=PAYMENT_STATUSSNP$CRTYPE_NAME=STRINGSNP$CRORDER=13SNP$CRLENGTH=50SNP$CRPRECISION=50SNP$CRSNP$CRDWG_COLSNP$CRCOL_NAME=JOB_NUMBERSNP$CRTYPE_NAME=STRINGSNP$CRORDER=14SNP$CRLENGTH=50SNP$CRPRECISION=50SNP$CRSNP$CRDWG_COLSNP$CRCOL_NAME=CURRENCY_CODESNP$CRTYPE_NAME=STRINGSNP$CRORDER=15SNP$CRLENGTH=50SNP$CRPRECISION=50SNP$CRSNP$CRDWG_COLSNP$CRCOL_NAME=SOURCE_SYSTEMSNP$CRTYPE_NAME=STRINGSNP$CRORDER=16SNP$CRLENGTH=50SNP$CRPRECISION=50SNP$CR$$SNPS_END_KEY*/



/*-----------------------------------------------*/
/* TASK No. 9 */

chmod 644 /dw_export/PROD/POSTED_UNPOSTED_BATCHES.csv

&


/*-----------------------------------------------*/
/* TASK No. 10 */

mv /dw_export/PROD/POSTED_UNPOSTED_BATCHES.csv /dw_export/PROD/finance/posted_batches/CSS_CSP_PostedUnpostedBatches:v_data_export_run_date.csv

&


/*-----------------------------------------------*/
/* TASK No. 11 */
/* drop table */

drop table RAX_APP_USER.POSTED_BATCHES

&


/*-----------------------------------------------*/
/* TASK No. 12 */
/* create table */

create table RAX_APP_USER.POSTED_BATCHES
(
  BEGIN_DATE          VARCHAR2(10 BYTE),
  END_DATE            VARCHAR2(10 BYTE),
  JOB_NUMBER  VARCHAR2(50 BYTE),
  TERRITORY_ACCOUNT_TYPE  VARCHAR2(50 BYTE),
  AMT          NUMBER(19,2),
  DEPOSIT_DATE          VARCHAR2(10 BYTE),
  BANK_ACCOUNT_CODE   VARCHAR2(50 BYTE),
  SOURCE_SYSTEM VARCHAR2(50 BYTE),
  VENDOR   VARCHAR2(50 BYTE),
  ENTRY_TYPE   VARCHAR2(50 BYTE),
  ERROR_MESSAGE   VARCHAR2(250 BYTE),
  POSTED_DATE          VARCHAR2(10 BYTE)
)



&


/*-----------------------------------------------*/
/* TASK No. 13 */
/* insert CSS CSP */

INSERT INTO RAX_APP_USER.POSTED_BATCHES
 (
  BEGIN_DATE
  ,END_DATE
  ,JOB_NUMBER
  ,TERRITORY_ACCOUNT_TYPE  
  ,AMT   
  ,DEPOSIT_DATE    
  ,BANK_ACCOUNT_CODE  
  ,SOURCE_SYSTEM
  ,VENDOR   
  ,ENTRY_TYPE   
  ,ERROR_MESSAGE   
  ,POSTED_DATE        
) 
select 
    to_char(case when to_date(:v_data_export_last_month_begin_date,'YYYYMMDD') is null then to_date('19000101','YYYYMMDD') else to_date(:v_data_export_last_month_begin_date,'YYYYMMDD') end,'MM/DD/YYYY') BEGIN_DATE
    ,to_char(case when to_date(:v_data_export_last_month_end_date,'YYYYMMDD') is null then to_date('21000101','YYYYMMDD') else to_date(:v_data_export_last_month_end_date,'YYYYMMDD') end,'MM/DD/YYYY') END_DATE,
    TA.JOB_NUM JOB_NUMBER
    ,TA.TERRITORY_ACCOUNT_TYPE
    ,TAE.AMT
    ,to_char(be.DEPOSIT_DATE, 'mm-dd-yyyy') DEPOSIT_DATE  
    ,ba.BANK_CODE BANK_ACCOUNT_CODE
    ,be.SOURCE_SYSTEM
    ,be.VENDOR
    ,be.ENTRY_TYPE
    ,TAE.POSTING_ERROR_MESSAGE ERROR_MESSAGE
    ,to_char(TAE.POSTED_DATE, 'mm-dd-yyyy') POSTED_DATE  
from
    ODS_STAGE.WC_TERRITORY_ACCOUNT_STG TA
    ,ODS_STAGE.WC_TERRITORY_ACCOUNT_ENTRY_STG TAE
    ,ODS_STAGE.WC_BANK_ENTRY_STG be
    ,ODS_OWN.BANK_ACCOUNT ba
    ,ODS_STAGE.WC_BANK_ACCOUNT_XR ba_xr
where (1=1)
    and trunc(TAE.POSTED_DATE) >= case when to_date(:v_data_export_last_month_begin_date,'YYYYMMDD') is null then to_date('19000101','YYYYMMDD') else to_date(:v_data_export_last_month_begin_date,'YYYYMMDD') end
    and trunc(TAE.POSTED_DATE) <= case when to_date(:v_data_export_last_month_end_date,'YYYYMMDD') is null then to_date('21000101','YYYYMMDD') else to_date(:v_data_export_last_month_end_date,'YYYYMMDD') end
    and be.SOURCE_SYSTEM in ('CSP','CSS')
    and TAE.TERRITORY_ACCOUNT_ID=TA.TERRITORY_ACCOUNT_ID
    and TAE.BANK_ENTRY_ID=be.BANK_ENTRY_ID
    and ba.BANK_ACCOUNT_OID=ba_xr.BANK_ACCOUNT_OID
    and ba_xr.BANK_ACCOUNT_KEY=be.BANK_ACCOUNT_ID
order by 
    be.SOURCE_SYSTEM
    ,TA.JOB_NUM
    ,be.DEPOSIT_DATE
    ,TAE.AMT

&


/*-----------------------------------------------*/
/* TASK No. 14 */
/* Generate header */

create header	(BEGIN_DATE,
	END_DATE,
	JOB_NUMBER,
	TERRITORY_ACCOUNT_TYPE,
	AMT,
	DEPOSIT_DATE,
	BANK_ACCOUNT_CODE,
	SOURCE_SYSTEM,
	VENDOR,
	ENTRY_TYPE,
	ERROR_MESSAGE,
	POSTED_DATE)

/*$$SNPS_START_KEYSNP$CRDWG_TABLESNP$CRTABLE_NAME=POSTED_BATCHES.csvSNP$CRLOAD_FILE=/dw_export/PROD/POSTED_BATCHES.csvSNP$CRFILE_FORMAT=DSNP$CRFILE_SEP_FIELD=0x002cSNP$CRFILE_SEP_LINE=0x000D0x000ASNP$CRFILE_FIRST_ROW=0SNP$CRFILE_ENC_FIELD="SNP$CRFILE_DEC_SEP=SNP$CRSNP$CRDWG_COLSNP$CRCOL_NAME=BEGIN_DATESNP$CRTYPE_NAME=STRINGSNP$CRORDER=1SNP$CRLENGTH=50SNP$CRPRECISION=50SNP$CRSNP$CRDWG_COLSNP$CRCOL_NAME=END_DATESNP$CRTYPE_NAME=STRINGSNP$CRORDER=2SNP$CRLENGTH=50SNP$CRPRECISION=50SNP$CRSNP$CRDWG_COLSNP$CRCOL_NAME=JOB_NUMBERSNP$CRTYPE_NAME=STRINGSNP$CRORDER=3SNP$CRLENGTH=50SNP$CRPRECISION=50SNP$CRSNP$CRDWG_COLSNP$CRCOL_NAME=TERRITORY_ACCOUNT_TYPESNP$CRTYPE_NAME=STRINGSNP$CRORDER=4SNP$CRLENGTH=50SNP$CRPRECISION=50SNP$CRSNP$CRDWG_COLSNP$CRCOL_NAME=AMTSNP$CRTYPE_NAME=STRINGSNP$CRORDER=5SNP$CRLENGTH=50SNP$CRPRECISION=50SNP$CRSNP$CRDWG_COLSNP$CRCOL_NAME=DEPOSIT_DATESNP$CRTYPE_NAME=STRINGSNP$CRORDER=6SNP$CRLENGTH=50SNP$CRPRECISION=50SNP$CRSNP$CRDWG_COLSNP$CRCOL_NAME=BANK_ACCOUNT_CODESNP$CRTYPE_NAME=STRINGSNP$CRORDER=7SNP$CRLENGTH=50SNP$CRPRECISION=50SNP$CRSNP$CRDWG_COLSNP$CRCOL_NAME=SOURCE_SYSTEMSNP$CRTYPE_NAME=STRINGSNP$CRORDER=8SNP$CRLENGTH=50SNP$CRPRECISION=50SNP$CRSNP$CRDWG_COLSNP$CRCOL_NAME=VENDORSNP$CRTYPE_NAME=STRINGSNP$CRORDER=9SNP$CRLENGTH=50SNP$CRPRECISION=50SNP$CRSNP$CRDWG_COLSNP$CRCOL_NAME=ENTRY_TYPESNP$CRTYPE_NAME=STRINGSNP$CRORDER=10SNP$CRLENGTH=50SNP$CRPRECISION=50SNP$CRSNP$CRDWG_COLSNP$CRCOL_NAME=ERROR_MESSAGESNP$CRTYPE_NAME=STRINGSNP$CRORDER=11SNP$CRLENGTH=250SNP$CRPRECISION=250SNP$CRSNP$CRDWG_COLSNP$CRCOL_NAME=POSTED_DATESNP$CRTYPE_NAME=STRINGSNP$CRORDER=12SNP$CRLENGTH=50SNP$CRPRECISION=50SNP$CR$$SNPS_END_KEY*/


&


/*-----------------------------------------------*/
/* TASK No. 15 */
/* Insert new rows */

/* SOURCE CODE */


select 	
	PB.BEGIN_DATE	   BEGIN_DATE,
	PB.END_DATE	   END_DATE,
	PB.JOB_NUMBER	   JOB_NUMBER,
	PB.TERRITORY_ACCOUNT_TYPE	   TERRITORY_ACCOUNT_TYPE,
	PB.AMT	   AMT,
	PB.DEPOSIT_DATE	   DEPOSIT_DATE,
	PB.BANK_ACCOUNT_CODE	   BANK_ACCOUNT_CODE,
	PB.SOURCE_SYSTEM	   SOURCE_SYSTEM,
	PB.VENDOR	   VENDOR,
	PB.ENTRY_TYPE	   ENTRY_TYPE,
	PB.ERROR_MESSAGE	   ERROR_MESSAGE,
	PB.POSTED_DATE	   POSTED_DATE
from	RAX_APP_USER.POSTED_BATCHES   PB
where	
	(1=1)	
	





/* Order the output by the UD1, UD2, UD3, UD4, UD5, UD6 Fields. */
 
ORDER BY  SOURCE_SYSTEM
, JOB_NUMBER
, DEPOSIT_DATE
, AMT









&

/* TARGET CODE */
insert into "/dw_export/PROD/POSTED_BATCHES.csv"
(
	BEGIN_DATE,
	END_DATE,
	JOB_NUMBER,
	TERRITORY_ACCOUNT_TYPE,
	AMT,
	DEPOSIT_DATE,
	BANK_ACCOUNT_CODE,
	SOURCE_SYSTEM,
	VENDOR,
	ENTRY_TYPE,
	ERROR_MESSAGE,
	POSTED_DATE
                     
)
values 
(
	:BEGIN_DATE,
	:END_DATE,
	:JOB_NUMBER,
	:TERRITORY_ACCOUNT_TYPE,
	:AMT,
	:DEPOSIT_DATE,
	:BANK_ACCOUNT_CODE,
	:SOURCE_SYSTEM,
	:VENDOR,
	:ENTRY_TYPE,
	:ERROR_MESSAGE,
	:POSTED_DATE
                     
)
/*$$SNPS_START_KEYSNP$CRDWG_TABLESNP$CRTABLE_NAME=POSTED_BATCHES.csvSNP$CRLOAD_FILE=/dw_export/PROD/POSTED_BATCHES.csvSNP$CRFILE_FORMAT=DSNP$CRFILE_SEP_FIELD=0x002cSNP$CRFILE_SEP_LINE=0x000D0x000ASNP$CRFILE_FIRST_ROW=0SNP$CRFILE_ENC_FIELD="SNP$CRFILE_DEC_SEP=SNP$CRSNP$CRDWG_COLSNP$CRCOL_NAME=BEGIN_DATESNP$CRTYPE_NAME=STRINGSNP$CRORDER=1SNP$CRLENGTH=50SNP$CRPRECISION=50SNP$CRSNP$CRDWG_COLSNP$CRCOL_NAME=END_DATESNP$CRTYPE_NAME=STRINGSNP$CRORDER=2SNP$CRLENGTH=50SNP$CRPRECISION=50SNP$CRSNP$CRDWG_COLSNP$CRCOL_NAME=JOB_NUMBERSNP$CRTYPE_NAME=STRINGSNP$CRORDER=3SNP$CRLENGTH=50SNP$CRPRECISION=50SNP$CRSNP$CRDWG_COLSNP$CRCOL_NAME=TERRITORY_ACCOUNT_TYPESNP$CRTYPE_NAME=STRINGSNP$CRORDER=4SNP$CRLENGTH=50SNP$CRPRECISION=50SNP$CRSNP$CRDWG_COLSNP$CRCOL_NAME=AMTSNP$CRTYPE_NAME=STRINGSNP$CRORDER=5SNP$CRLENGTH=50SNP$CRPRECISION=50SNP$CRSNP$CRDWG_COLSNP$CRCOL_NAME=DEPOSIT_DATESNP$CRTYPE_NAME=STRINGSNP$CRORDER=6SNP$CRLENGTH=50SNP$CRPRECISION=50SNP$CRSNP$CRDWG_COLSNP$CRCOL_NAME=BANK_ACCOUNT_CODESNP$CRTYPE_NAME=STRINGSNP$CRORDER=7SNP$CRLENGTH=50SNP$CRPRECISION=50SNP$CRSNP$CRDWG_COLSNP$CRCOL_NAME=SOURCE_SYSTEMSNP$CRTYPE_NAME=STRINGSNP$CRORDER=8SNP$CRLENGTH=50SNP$CRPRECISION=50SNP$CRSNP$CRDWG_COLSNP$CRCOL_NAME=VENDORSNP$CRTYPE_NAME=STRINGSNP$CRORDER=9SNP$CRLENGTH=50SNP$CRPRECISION=50SNP$CRSNP$CRDWG_COLSNP$CRCOL_NAME=ENTRY_TYPESNP$CRTYPE_NAME=STRINGSNP$CRORDER=10SNP$CRLENGTH=50SNP$CRPRECISION=50SNP$CRSNP$CRDWG_COLSNP$CRCOL_NAME=ERROR_MESSAGESNP$CRTYPE_NAME=STRINGSNP$CRORDER=11SNP$CRLENGTH=250SNP$CRPRECISION=250SNP$CRSNP$CRDWG_COLSNP$CRCOL_NAME=POSTED_DATESNP$CRTYPE_NAME=STRINGSNP$CRORDER=12SNP$CRLENGTH=50SNP$CRPRECISION=50SNP$CR$$SNPS_END_KEY*/



/*-----------------------------------------------*/
/* TASK No. 16 */

chmod 644 /dw_export/PROD/POSTED_BATCHES.csv

&


/*-----------------------------------------------*/
/* TASK No. 17 */

mv /dw_export/PROD/POSTED_BATCHES.csv /dw_export/PROD/finance/posted_batches/CSS_CSP_PostedBatches:v_data_export_run_date.csv

&


/*-----------------------------------------------*/
