select
	PB.BEGIN_DATE	   BEGIN_DATE,
	PB.END_DATE	   END_DATE,
	PB.JOB_NUMBER	   JOB_NUMBER,
	PB.TERRITORY_ACCOUNT_TYPE	   TERRITORY_ACCOUNT_TYPE,
	PB.AMT	   AMT,
	PB.DEPOSIT_DATE	   DEPOSIT_DATE,
	PB.BANK_ACCOUNT_CODE	   BANK_ACCOUNT_CODE,
	PB.SOURCE_SYSTEM	   SOURCE_SYSTEM,
	PB.VENDOR	   VENDOR,
	PB.ENTRY_TYPE	   ENTRY_TYPE,
	PB.ERROR_MESSAGE	   ERROR_MESSAGE,
	PB.POSTED_DATE	   POSTED_DATE
from	RAX_APP_USER.POSTED_BATCHES   PB
where
	(1=1)
/* Order the output by the UD1, UD2, UD3, UD4, UD5, UD6 Fields. */

ORDER BY  SOURCE_SYSTEM
, JOB_NUMBER
, DEPOSIT_DATE
, AMT