select
	PB.BEGIN_DATE	   BEGIN_DATE,
	PB.END_DATE	   END_DATE,
	PB.PAYMENT_TYPE	   PAYMENT_TYPE,
	PB.PAYMENT_ID	   PAYMENT_ID,
	PB.LAST_MODIFIED	   LAST_MODIFIED,
	PB.LAST_MODIFIED_BY	   LAST_MODIFIED_BY,
	PB.DATE_CREATED	   DATE_CREATED,
	PB.CREATED_BY	   CREATED_BY,
	PB.AMOUNT	   AMOUNT,
	PB.PAYMENT_DATE	   PAYMENT_DATE,
	PB.PAYMENT_BATCH_ID	   PAYMENT_BATCH_ID,
	PB.CUSTOMER_ORDER_ID	   CUSTOMER_ORDER_ID,
	PB.PAYMENT_STATUS	   PAYMENT_STATUS,
	PB.JOB_NUMBER	   JOB_NUMBER,
	PB.CURRENCY_CODE	   CURRENCY_CODE,
	PB.SOURCE_SYSTEM	   SOURCE_SYSTEM
from	RAX_APP_USER.POSTED_UNPOSTED_BATCHES   PB
where
	(1=1)






/* Order the output by the UD1, UD2, UD3, UD4, UD5, UD6 Fields. */

ORDER BY  SOURCE_SYSTEM
, PAYMENT_TYPE
, PAYMENT_DATE
, PAYMENT_ID