/* TASK No. 1 */

/* NONE or SET VARIABLE STATEMENT FOUND, CHECK ODI TASK NO. 1 */




/*-----------------------------------------------*/
/* TASK No. 2 */

/* SELECT STATEMENT FOUND, CHECK ODI TASK NO. 2 */




/*-----------------------------------------------*/
/* TASK No. 3 */

/* SELECT STATEMENT FOUND, CHECK ODI TASK NO. 3 */




/*-----------------------------------------------*/
/* TASK No. 4 */
/* Drop work table */

/*
drop table RAX_APP_USER.C$_0OMS3_ST_DTL_STG purge

&
*/

/*-----------------------------------------------*/
/* TASK No. 5 */
/* Create work table */
/*
create table RAX_APP_USER.C$_0OMS3_ST_DTL_STG
(
	C1_STATISTICS_DETAIL_KEY	CHAR(24) NULL,
	C2_START_TIME_STAMP	DATE NULL,
	C3_END_TIME_STAMP	DATE NULL,
	C4_SERVER_NAME	VARCHAR2(100) NULL,
	C5_SERVER_ID	VARCHAR2(100) NULL,
	C6_HOSTNAME	VARCHAR2(100) NULL,
	C7_SERVICE_NAME	VARCHAR2(100) NULL,
	C8_SERVICE_TYPE	VARCHAR2(40) NULL,
	C9_CONTEXT_NAME	VARCHAR2(80) NULL,
	C10_STATISTIC_NAME	VARCHAR2(80) NULL,
	C11_STATISTIC_VALUE	NUMBER(15,2) NULL,
	C12_CREATEUSERID	VARCHAR2(40) NULL,
	C13_MODIFYUSERID	VARCHAR2(40) NULL,
	C14_CREATEPROGID	VARCHAR2(40) NULL,
	C15_MODIFYPROGID	VARCHAR2(40) NULL,
	C16_CREATETS	DATE NULL,
	C17_MODIFYTS	DATE NULL,
	C18_LOCKID	NUMBER(5) NULL,
	C19_START_DATE	DATE NULL,
	C20_END_DATE	DATE NULL
)
NOLOGGING

&
*/

/*-----------------------------------------------*/
/* TASK No. 6 */
/* Load data */

/* SOURCE CODE */

/*
select	
	YFS_STATISTICS_DETAIL.STATISTICS_DETAIL_KEY	   C1_STATISTICS_DETAIL_KEY,
	YFS_STATISTICS_DETAIL.START_TIME_STAMP	   C2_START_TIME_STAMP,
	YFS_STATISTICS_DETAIL.END_TIME_STAMP	   C3_END_TIME_STAMP,
	YFS_STATISTICS_DETAIL.SERVER_NAME	   C4_SERVER_NAME,
	YFS_STATISTICS_DETAIL.SERVER_ID	   C5_SERVER_ID,
	YFS_STATISTICS_DETAIL.HOSTNAME	   C6_HOSTNAME,
	YFS_STATISTICS_DETAIL.SERVICE_NAME	   C7_SERVICE_NAME,
	YFS_STATISTICS_DETAIL.SERVICE_TYPE	   C8_SERVICE_TYPE,
	YFS_STATISTICS_DETAIL.CONTEXT_NAME	   C9_CONTEXT_NAME,
	YFS_STATISTICS_DETAIL.STATISTIC_NAME	   C10_STATISTIC_NAME,
	YFS_STATISTICS_DETAIL.STATISTIC_VALUE	   C11_STATISTIC_VALUE,
	YFS_STATISTICS_DETAIL.CREATEUSERID	   C12_CREATEUSERID,
	YFS_STATISTICS_DETAIL.MODIFYUSERID	   C13_MODIFYUSERID,
	YFS_STATISTICS_DETAIL.CREATEPROGID	   C14_CREATEPROGID,
	YFS_STATISTICS_DETAIL.MODIFYPROGID	   C15_MODIFYPROGID,
	YFS_STATISTICS_DETAIL.CREATETS	   C16_CREATETS,
	YFS_STATISTICS_DETAIL.MODIFYTS	   C17_MODIFYTS,
	YFS_STATISTICS_DETAIL.LOCKID	   C18_LOCKID,
	TRUNC(YFS_STATISTICS_DETAIL.START_TIME_STAMP)	   C19_START_DATE,
	TRUNC(YFS_STATISTICS_DETAIL.END_TIME_STAMP)	   C20_END_DATE
from	OMS3_OWN.YFS_STATISTICS_DETAIL   YFS_STATISTICS_DETAIL
where	(1=1)
And (YFS_STATISTICS_DETAIL.CREATETS >= TO_DATE(SUBSTR(:v_cdc_load_date, 1, 19), 'YYYY-MM-DD HH24:MI:SS')  - :v_cdc_oms_overlap
)







&
*/
/* TARGET CODE */

/*-----------------------------------------------*/
/* TASK No. 7 */
/* Analyze work table */



BEGIN
DBMS_STATS.GATHER_TABLE_STATS (
    ownname =>	'RAX_APP_USER',
    tabname =>	'C$_0OMS3_ST_DTL_STG',
    estimate_percent =>	DBMS_STATS.AUTO_SAMPLE_SIZE
);
END;




&


/*-----------------------------------------------*/
/* TASK No. 9 */
/* Set vID */

/* NONE or SET VARIABLE STATEMENT FOUND, CHECK ODI TASK NO. 9 */




/*-----------------------------------------------*/
/* TASK No. 10 */
/* Drop flow table */

 

BEGIN  
   EXECUTE IMMEDIATE 'drop table RAX_APP_USER.I$_OMS3_ST_DTL_STG2691001';  
EXCEPTION  
   WHEN OTHERS THEN  
      IF SQLCODE != -942 THEN  
         RAISE;  
      END IF;  
END;  


&


/*-----------------------------------------------*/
/* TASK No. 11 */
/* Create flow table I$ */

create table RAX_APP_USER.I$_OMS3_ST_DTL_STG2691001
(
	STATISTICS_DETAIL_KEY	CHAR(24) NULL,
	START_TIME_STAMP	DATE NULL,
	END_TIME_STAMP	DATE NULL,
	SERVER_NAME	VARCHAR2(100) NULL,
	SERVER_ID	VARCHAR2(100) NULL,
	HOSTNAME	VARCHAR2(100) NULL,
	SERVICE_NAME	VARCHAR2(100) NULL,
	SERVICE_TYPE	VARCHAR2(40) NULL,
	CONTEXT_NAME	VARCHAR2(80) NULL,
	STATISTIC_NAME	VARCHAR2(80) NULL,
	STATISTIC_VALUE	NUMBER(15,2) NULL,
	CREATEUSERID	VARCHAR2(40) NULL,
	MODIFYUSERID	VARCHAR2(40) NULL,
	CREATEPROGID	VARCHAR2(40) NULL,
	MODIFYPROGID	VARCHAR2(40) NULL,
	CREATETS	DATE NULL,
	MODIFYTS	DATE NULL,
	LOCKID	NUMBER(5) NULL,
	START_DATE	DATE NULL,
	END_DATE	DATE NULL,
	ODS_CREATE_DATE	DATE NULL,
	ODS_MODIFY_DATE	DATE NULL
	,IND_UPDATE		char(1)
)
NOLOGGING

&


/*-----------------------------------------------*/
/* TASK No. 12 */
/* Insert flow into I$ table */

/* DETECTION_STRATEGY = NOT_EXISTS */
 


  


insert into	RAX_APP_USER.I$_OMS3_ST_DTL_STG2691001
(
	STATISTICS_DETAIL_KEY,
	START_TIME_STAMP,
	END_TIME_STAMP,
	SERVER_NAME,
	SERVER_ID,
	HOSTNAME,
	SERVICE_NAME,
	SERVICE_TYPE,
	CONTEXT_NAME,
	STATISTIC_NAME,
	STATISTIC_VALUE,
	CREATEUSERID,
	MODIFYUSERID,
	CREATEPROGID,
	MODIFYPROGID,
	CREATETS,
	MODIFYTS,
	LOCKID,
	START_DATE,
	END_DATE,
	IND_UPDATE
)
select 
STATISTICS_DETAIL_KEY,
	START_TIME_STAMP,
	END_TIME_STAMP,
	SERVER_NAME,
	SERVER_ID,
	HOSTNAME,
	SERVICE_NAME,
	SERVICE_TYPE,
	CONTEXT_NAME,
	STATISTIC_NAME,
	STATISTIC_VALUE,
	CREATEUSERID,
	MODIFYUSERID,
	CREATEPROGID,
	MODIFYPROGID,
	CREATETS,
	MODIFYTS,
	LOCKID,
	START_DATE,
	END_DATE,
	IND_UPDATE
 from (


select 	 
	
	C1_STATISTICS_DETAIL_KEY STATISTICS_DETAIL_KEY,
	C2_START_TIME_STAMP START_TIME_STAMP,
	C3_END_TIME_STAMP END_TIME_STAMP,
	C4_SERVER_NAME SERVER_NAME,
	C5_SERVER_ID SERVER_ID,
	C6_HOSTNAME HOSTNAME,
	C7_SERVICE_NAME SERVICE_NAME,
	C8_SERVICE_TYPE SERVICE_TYPE,
	C9_CONTEXT_NAME CONTEXT_NAME,
	C10_STATISTIC_NAME STATISTIC_NAME,
	C11_STATISTIC_VALUE STATISTIC_VALUE,
	C12_CREATEUSERID CREATEUSERID,
	C13_MODIFYUSERID MODIFYUSERID,
	C14_CREATEPROGID CREATEPROGID,
	C15_MODIFYPROGID MODIFYPROGID,
	C16_CREATETS CREATETS,
	C17_MODIFYTS MODIFYTS,
	C18_LOCKID LOCKID,
	C19_START_DATE START_DATE,
	C20_END_DATE END_DATE,

	'I' IND_UPDATE

from	RAX_APP_USER.C$_0OMS3_ST_DTL_STG
where	(1=1)






) S
where NOT EXISTS 
	( select 1 from ODS_STAGE.OMS3_STATISTICS_DETAIL_STG T
	where	T.STATISTICS_DETAIL_KEY	= S.STATISTICS_DETAIL_KEY 
		 and ((T.START_TIME_STAMP = S.START_TIME_STAMP) or (T.START_TIME_STAMP IS NULL and S.START_TIME_STAMP IS NULL)) and
		((T.END_TIME_STAMP = S.END_TIME_STAMP) or (T.END_TIME_STAMP IS NULL and S.END_TIME_STAMP IS NULL)) and
		((T.SERVER_NAME = S.SERVER_NAME) or (T.SERVER_NAME IS NULL and S.SERVER_NAME IS NULL)) and
		((T.SERVER_ID = S.SERVER_ID) or (T.SERVER_ID IS NULL and S.SERVER_ID IS NULL)) and
		((T.HOSTNAME = S.HOSTNAME) or (T.HOSTNAME IS NULL and S.HOSTNAME IS NULL)) and
		((T.SERVICE_NAME = S.SERVICE_NAME) or (T.SERVICE_NAME IS NULL and S.SERVICE_NAME IS NULL)) and
		((T.SERVICE_TYPE = S.SERVICE_TYPE) or (T.SERVICE_TYPE IS NULL and S.SERVICE_TYPE IS NULL)) and
		((T.CONTEXT_NAME = S.CONTEXT_NAME) or (T.CONTEXT_NAME IS NULL and S.CONTEXT_NAME IS NULL)) and
		((T.STATISTIC_NAME = S.STATISTIC_NAME) or (T.STATISTIC_NAME IS NULL and S.STATISTIC_NAME IS NULL)) and
		((T.STATISTIC_VALUE = S.STATISTIC_VALUE) or (T.STATISTIC_VALUE IS NULL and S.STATISTIC_VALUE IS NULL)) and
		((T.CREATEUSERID = S.CREATEUSERID) or (T.CREATEUSERID IS NULL and S.CREATEUSERID IS NULL)) and
		((T.MODIFYUSERID = S.MODIFYUSERID) or (T.MODIFYUSERID IS NULL and S.MODIFYUSERID IS NULL)) and
		((T.CREATEPROGID = S.CREATEPROGID) or (T.CREATEPROGID IS NULL and S.CREATEPROGID IS NULL)) and
		((T.MODIFYPROGID = S.MODIFYPROGID) or (T.MODIFYPROGID IS NULL and S.MODIFYPROGID IS NULL)) and
		((T.CREATETS = S.CREATETS) or (T.CREATETS IS NULL and S.CREATETS IS NULL)) and
		((T.MODIFYTS = S.MODIFYTS) or (T.MODIFYTS IS NULL and S.MODIFYTS IS NULL)) and
		((T.LOCKID = S.LOCKID) or (T.LOCKID IS NULL and S.LOCKID IS NULL)) and
		((T.START_DATE = S.START_DATE) or (T.START_DATE IS NULL and S.START_DATE IS NULL)) and
		((T.END_DATE = S.END_DATE) or (T.END_DATE IS NULL and S.END_DATE IS NULL))
        )

  
  

  



&


/*-----------------------------------------------*/
/* TASK No. 13 */
/* Analyze integration table */



begin
    dbms_stats.gather_table_stats(
	ownname => 'RAX_APP_USER',
	tabname => 'I$_OMS3_ST_DTL_STG2691001',
	estimate_percent => dbms_stats.auto_sample_size
    );
end;



&


/*-----------------------------------------------*/
/* TASK No. 14 */
/* Create Index on flow table */

create index	RAX_APP_USER.I$_OMS3_ST_DTL_STG_IDX2691001
on		RAX_APP_USER.I$_OMS3_ST_DTL_STG2691001 (STATISTICS_DETAIL_KEY)
NOLOGGING

&


/*-----------------------------------------------*/
/* TASK No. 15 */
/* create check table */




BEGIN  
   EXECUTE IMMEDIATE 'create table RAX_APP_USER.SNP_CHECK_TAB
(
	CATALOG_NAME	VARCHAR2(100 CHAR) NULL ,
	SCHEMA_NAME	VARCHAR2(100 CHAR) NULL ,
	RESOURCE_NAME	VARCHAR2(100 CHAR) NULL,
	FULL_RES_NAME	VARCHAR2(100 CHAR) NULL,
	ERR_TYPE		VARCHAR2(1 CHAR) NULL,
	ERR_MESS		VARCHAR2(250 CHAR) NULL ,
	CHECK_DATE	DATE NULL,
	ORIGIN		VARCHAR2(100 CHAR) NULL,
	CONS_NAME	VARCHAR2(35 CHAR) NULL,
	CONS_TYPE		VARCHAR2(2 CHAR) NULL,
	ERR_COUNT		NUMBER(10) NULL
)';  
EXCEPTION  
   WHEN OTHERS THEN  
      NULL;
END;  
	

&


/*-----------------------------------------------*/
/* TASK No. 16 */
/* delete previous check sum */

delete from	RAX_APP_USER.SNP_CHECK_TAB
where	SCHEMA_NAME	= 'ODS_STAGE'
and	ORIGIN 		= '(2691001)ODS_Project.LOAD_OMS3_STATISTICS_DETAIL_STG_INT'
and	ERR_TYPE 		= 'F'


&


/*-----------------------------------------------*/
/* TASK No. 17 */
/* create error table */




BEGIN  
   EXECUTE IMMEDIATE 'create table RAX_APP_USER.E$_OMS3_ST_DTL_STG2691001
(
	ODI_ROW_ID 		UROWID,
	ODI_ERR_TYPE		VARCHAR2(1 CHAR) NULL, 
	ODI_ERR_MESS		VARCHAR2(250 CHAR) NULL,
	ODI_CHECK_DATE	DATE NULL, 
	STATISTICS_DETAIL_KEY	CHAR(24) NULL,
	START_TIME_STAMP	DATE NULL,
	END_TIME_STAMP	DATE NULL,
	SERVER_NAME	VARCHAR2(100) NULL,
	SERVER_ID	VARCHAR2(100) NULL,
	HOSTNAME	VARCHAR2(100) NULL,
	SERVICE_NAME	VARCHAR2(100) NULL,
	SERVICE_TYPE	VARCHAR2(40) NULL,
	CONTEXT_NAME	VARCHAR2(80) NULL,
	STATISTIC_NAME	VARCHAR2(80) NULL,
	STATISTIC_VALUE	NUMBER(15,2) NULL,
	CREATEUSERID	VARCHAR2(40) NULL,
	MODIFYUSERID	VARCHAR2(40) NULL,
	CREATEPROGID	VARCHAR2(40) NULL,
	MODIFYPROGID	VARCHAR2(40) NULL,
	CREATETS	DATE NULL,
	MODIFYTS	DATE NULL,
	LOCKID	NUMBER(5) NULL,
	START_DATE	DATE NULL,
	END_DATE	DATE NULL,
	ODS_CREATE_DATE	DATE NULL,
	ODS_MODIFY_DATE	DATE NULL,
	ODI_ORIGIN		VARCHAR2(100 CHAR) NULL,
	ODI_CONS_NAME	VARCHAR2(35 CHAR) NULL,
	ODI_CONS_TYPE		VARCHAR2(2 CHAR) NULL,
	ODI_PK			VARCHAR2(32 CHAR) PRIMARY KEY,
	ODI_SESS_NO		VARCHAR2(19 CHAR)
)';  
EXCEPTION  
   WHEN OTHERS THEN  
      NULL;
END;  


&


/*-----------------------------------------------*/
/* TASK No. 18 */
/* delete previous errors */

delete from 	RAX_APP_USER.E$_OMS3_ST_DTL_STG2691001
where	(ODI_ERR_TYPE = 'S'	and 'F' = 'S')
or	(ODI_ERR_TYPE = 'F'	and ODI_ORIGIN = '(2691001)ODS_Project.LOAD_OMS3_STATISTICS_DETAIL_STG_INT')


&


/*-----------------------------------------------*/
/* TASK No. 19 */
/* insert Not Null errors */

insert into RAX_APP_USER.E$_OMS3_ST_DTL_STG2691001
(
	ODI_PK,
	ODI_SESS_NO,
	ODI_ROW_ID,
	ODI_ERR_TYPE,
	ODI_ERR_MESS,
	ODI_CHECK_DATE,
	ODI_ORIGIN,
	ODI_CONS_NAME,
	ODI_CONS_TYPE,
	STATISTICS_DETAIL_KEY,
	START_TIME_STAMP,
	END_TIME_STAMP,
	SERVER_NAME,
	SERVER_ID,
	HOSTNAME,
	SERVICE_NAME,
	SERVICE_TYPE,
	CONTEXT_NAME,
	STATISTIC_NAME,
	STATISTIC_VALUE,
	CREATEUSERID,
	MODIFYUSERID,
	CREATEPROGID,
	MODIFYPROGID,
	CREATETS,
	MODIFYTS,
	LOCKID,
	START_DATE,
	END_DATE,
	ODS_CREATE_DATE,
	ODS_MODIFY_DATE
)
select
	SYS_GUID(),
	:v_sess_no, 
	rowid,
	'F', 
	'ODI-15066: The column STATISTICS_DETAIL_KEY cannot be null.',
	sysdate,
	'(2691001)ODS_Project.LOAD_OMS3_STATISTICS_DETAIL_STG_INT',
	'STATISTICS_DETAIL_KEY',
	'NN',	
	STATISTICS_DETAIL_KEY,
	START_TIME_STAMP,
	END_TIME_STAMP,
	SERVER_NAME,
	SERVER_ID,
	HOSTNAME,
	SERVICE_NAME,
	SERVICE_TYPE,
	CONTEXT_NAME,
	STATISTIC_NAME,
	STATISTIC_VALUE,
	CREATEUSERID,
	MODIFYUSERID,
	CREATEPROGID,
	MODIFYPROGID,
	CREATETS,
	MODIFYTS,
	LOCKID,
	START_DATE,
	END_DATE,
	ODS_CREATE_DATE,
	ODS_MODIFY_DATE
from	RAX_APP_USER.I$_OMS3_ST_DTL_STG2691001
where	STATISTICS_DETAIL_KEY is null



&


/*-----------------------------------------------*/
/* TASK No. 20 */
/* create index on error table */

 
/* FLOW CONTROL CREATE INDEX ON THE E$TABLE */


BEGIN  
   EXECUTE IMMEDIATE 'create index 	RAX_APP_USER.E$_OMS3_ST_DTL_STG2691001
on	RAX_APP_USER.E$_OMS3_ST_DTL_STG2691001 (ODI_ROW_ID)';  
EXCEPTION  
   WHEN OTHERS THEN  
      NULL;
END;

&


/*-----------------------------------------------*/
/* TASK No. 21 */
/* delete errors from controlled table */

delete from	RAX_APP_USER.I$_OMS3_ST_DTL_STG2691001  T
where	exists 	(
		select	1
		from	RAX_APP_USER.E$_OMS3_ST_DTL_STG2691001 E
		where ODI_SESS_NO = :v_sess_no
		and T.rowid = E.ODI_ROW_ID
		)


&


/*-----------------------------------------------*/
/* TASK No. 22 */
/* insert check sum into check table */

insert into RAX_APP_USER.SNP_CHECK_TAB
(
	SCHEMA_NAME,
	RESOURCE_NAME,
	FULL_RES_NAME,
	ERR_TYPE,
	ERR_MESS,
	CHECK_DATE,
	ORIGIN,
	CONS_NAME,
	CONS_TYPE,
	ERR_COUNT
)
select	
	'ODS_STAGE',
	'OMS3_ST_DTL_STG',
	'ODS_STAGE.OMS3_STATISTICS_DETAIL_STG2691001',
	E.ODI_ERR_TYPE,
	E.ODI_ERR_MESS,
	E.ODI_CHECK_DATE,
	E.ODI_ORIGIN,
	E.ODI_CONS_NAME,
	E.ODI_CONS_TYPE,
	count(1) 
from	RAX_APP_USER.E$_OMS3_ST_DTL_STG2691001 E
where	E.ODI_ERR_TYPE	= 'F'
and	E.ODI_ORIGIN 	= '(2691001)ODS_Project.LOAD_OMS3_STATISTICS_DETAIL_STG_INT'
group by	E.ODI_ERR_TYPE,
	E.ODI_ERR_MESS,
	E.ODI_CHECK_DATE,
	E.ODI_ORIGIN,
	E.ODI_CONS_NAME,
	E.ODI_CONS_TYPE


&


/*-----------------------------------------------*/
/* TASK No. 23 */
/* Merge Rows */

merge into	ODS_STAGE.OMS3_STATISTICS_DETAIL_STG T
using	RAX_APP_USER.I$_OMS3_ST_DTL_STG2691001 S
on	(
		T.STATISTICS_DETAIL_KEY=S.STATISTICS_DETAIL_KEY
	)
when matched
then update set
	T.START_TIME_STAMP	= S.START_TIME_STAMP,
	T.END_TIME_STAMP	= S.END_TIME_STAMP,
	T.SERVER_NAME	= S.SERVER_NAME,
	T.SERVER_ID	= S.SERVER_ID,
	T.HOSTNAME	= S.HOSTNAME,
	T.SERVICE_NAME	= S.SERVICE_NAME,
	T.SERVICE_TYPE	= S.SERVICE_TYPE,
	T.CONTEXT_NAME	= S.CONTEXT_NAME,
	T.STATISTIC_NAME	= S.STATISTIC_NAME,
	T.STATISTIC_VALUE	= S.STATISTIC_VALUE,
	T.CREATEUSERID	= S.CREATEUSERID,
	T.MODIFYUSERID	= S.MODIFYUSERID,
	T.CREATEPROGID	= S.CREATEPROGID,
	T.MODIFYPROGID	= S.MODIFYPROGID,
	T.CREATETS	= S.CREATETS,
	T.MODIFYTS	= S.MODIFYTS,
	T.LOCKID	= S.LOCKID,
	T.START_DATE	= S.START_DATE,
	T.END_DATE	= S.END_DATE
	,                   T.ODS_MODIFY_DATE	= SYSDATE

when not matched
then insert
	(
	T.STATISTICS_DETAIL_KEY,
	T.START_TIME_STAMP,
	T.END_TIME_STAMP,
	T.SERVER_NAME,
	T.SERVER_ID,
	T.HOSTNAME,
	T.SERVICE_NAME,
	T.SERVICE_TYPE,
	T.CONTEXT_NAME,
	T.STATISTIC_NAME,
	T.STATISTIC_VALUE,
	T.CREATEUSERID,
	T.MODIFYUSERID,
	T.CREATEPROGID,
	T.MODIFYPROGID,
	T.CREATETS,
	T.MODIFYTS,
	T.LOCKID,
	T.START_DATE,
	T.END_DATE
	,                    T.ODS_CREATE_DATE,
	T.ODS_MODIFY_DATE
	)
values
	(
	S.STATISTICS_DETAIL_KEY,
	S.START_TIME_STAMP,
	S.END_TIME_STAMP,
	S.SERVER_NAME,
	S.SERVER_ID,
	S.HOSTNAME,
	S.SERVICE_NAME,
	S.SERVICE_TYPE,
	S.CONTEXT_NAME,
	S.STATISTIC_NAME,
	S.STATISTIC_VALUE,
	S.CREATEUSERID,
	S.MODIFYUSERID,
	S.CREATEPROGID,
	S.MODIFYPROGID,
	S.CREATETS,
	S.MODIFYTS,
	S.LOCKID,
	S.START_DATE,
	S.END_DATE
	,                    SYSDATE
,
	SYSDATE

	)

&


/*-----------------------------------------------*/
/* TASK No. 24 */
/* Commit transaction */

/*commit*/


/*-----------------------------------------------*/
/* TASK No. 25 */
/* Drop flow table */

drop table RAX_APP_USER.I$_OMS3_ST_DTL_STG2691001 

&


/*-----------------------------------------------*/
/* TASK No. 1000008 */
/* Drop work table */

drop table RAX_APP_USER.C$_0OMS3_ST_DTL_STG purge

&


/*-----------------------------------------------*/
/* TASK No. 26 */
/* Update CDC Load Status */

UPDATE ODS_OWN.ODS_CDC_LOAD_STATUS
SET LAST_CDC_COMPLETION_DATE=TO_DATE(
             SUBSTR(:v_sess_beg, 1, 19), 'RRRR-MM-DD HH24:MI:SS')
+ nvl((TIMEZONE_OFFSET/24), 0) 
WHERE ODS_TABLE_NAME=:v_cdc_load_table_name
AND CONTEXT_NAME = :v_env

/*
UPDATE ODS_OWN.ODS_CDC_LOAD_STATUS
SET LAST_CDC_COMPLETION_DATE=TO_DATE(
             SUBSTR(:v_sess_beg, 1, 19), 'RRRR-MM-DD HH24:MI:SS')
WHERE ODS_TABLE_NAME=:v_cdc_load_table_name
AND CONTEXT_NAME = :v_env
*/

&


/*-----------------------------------------------*/
/* TASK No. 27 */
/* Insert CDC Audit Record */

INSERT INTO RAX_APP_USER.ODS_CDC_LOAD_STATUS_AUDIT
(TABLE_NAME,
SESS_NO,                      
SESS_NAME,                    
SCEN_VERSION,                 
SESS_BEG,                     
ORIG_LAST_CDC_COMPLETION_DATE,
OVERLAP,
CREATE_DATE,
CONTEXT_NAME,
TIMEZONE_OFFSET              
)
select 
:v_cdc_load_table_name
,:v_sess_no
,'LOAD_STATISTICS_DETAIL_PKG'
,'002'
,TO_DATE(SUBSTR(:v_sess_beg, 1, 19), 'RRRR-MM-DD HH24:MI:SS')
,TO_DATE (SUBSTR(:v_cdc_load_date, 1, 19),'YYYY-MM-DD HH24:MI:SS')
,:v_cdc_overlap
,SYSDATE
,:v_env
,TIMEZONE_OFFSET
from 
ODS_OWN.ODS_CDC_LOAD_STATUS
WHERE ODS_TABLE_NAME=:v_cdc_load_table_name
AND CONTEXT_NAME = :v_env

/*
INSERT INTO RAX_APP_USER.ODS_CDC_LOAD_STATUS_AUDIT
(TABLE_NAME,
SESS_NO,                      
SESS_NAME,                    
SCEN_VERSION,                 
SESS_BEG,                     
ORIG_LAST_CDC_COMPLETION_DATE,
OVERLAP,
CREATE_DATE,
CONTEXT_NAME              
)
values (
:v_cdc_load_table_name,
:v_sess_no,
'LOAD_STATISTICS_DETAIL_PKG',
'002',
TO_DATE(
             SUBSTR(:v_sess_beg, 1, 19), 'RRRR-MM-DD HH24:MI:SS'),
TO_DATE (SUBSTR (:v_cdc_load_date, 1, 19),
                           'YYYY-MM-DD HH24:MI:SS'
                          )
,:v_cdc_overlap,
SYSDATE,
 :v_env)
*/


&


/*-----------------------------------------------*/
