-- /* TASK No. 1 */

-- /* SELECT STATEMENT FOUND, CHECK ODI TASK NO. 1 */




-- /*-----------------------------------------------*/
-- /* TASK No. 2 */

-- /* SELECT STATEMENT FOUND, CHECK ODI TASK NO. 2 */




-- /*-----------------------------------------------*/
-- /* TASK No. 3 */
-- /* drop report table */

-- drop table RAX_APP_USER.actuate_unpostedterrdep_stage 


-- &


-- /*-----------------------------------------------*/
-- /* TASK No. 4 */
-- /* create  report table */

-- create table RAX_APP_USER.actuate_unpostedterrdep_stage  as
-- Select
--     o.country_name,
--     o.company_name,
--     o.area_name,
--     o.region_name,
--     nvl(o.territory_code,'.') territory_code,
--     tac.job_num job_number,
--     bec.deposit_method_type,
--     tac.account_name,
--     tac.lifetouch_id,
--     tac.commission_type,
--     bec.seq_num batch_number,
--     taec.amt deposit_amount,
--     bec.deposit_date,
--     bac.bank_account_code,
--     trunc(bec.audit_create_date) create_date,
--     bec.audit_created_by,
--     taec.terr_emp_code photographer_id,
--     nvl(taec.posting_error_message, decode(tac.unknown_account, 1, 'Unknown Account', 0, null)) as posting_error_message,
--     trunc(sysdate) - trunc(bec.audit_create_date) as days_outstanding
-- from 
--  ODS.rev_bank_entry_curr bec,
--   ODS.rev_territory_account_curr tac,
--   ODS.rev_terr_account_entry_curr taec,
--  ODS.rev_bank_account_curr bac,
--     time t,
--     organization o,
--     (select (case when  to_number(:v_actuate_fiscal_year) = 9999 then fiscal_year else  to_number(:v_actuate_fiscal_year) end) fiscal_year
--                 from time
--                where trunc(sysdate) - 5 = date_key) cfy
-- where 
--      bec.deposit_date = t.date_key
--        and t.fiscal_year in (cfy.fiscal_year, cfy.fiscal_year-1) 
--      and bec.bank_entry_id = taec.bank_entry_id
--      and taec.territory_account_id = tac.territory_account_id
--      and bec.bank_account_id = bac.bank_account_id
--      and taec.posted_date is null
--      and nvl(bec.AUTHORIZATION_STATUS,'Approved')='Approved'
--      and (tac.PROGRAM_NAME<>'Preschools' or tac.PROGRAM_NAME is null) 
--      and tac.territory_code = o.territory_code(+)
--      and (o.area_name not in ('Area 61 United States','Area 62 United States') or o.area_name is null)
--      and taec.active = 1
--      and tac.active = 1
--      and bec.active = 1

-- &


-- /*-----------------------------------------------*/
-- /* TASK No. 5 */
-- /* Generate header */

-- create header	(COUNTRY_NAME,
-- 	COMPANY_NAME,
-- 	AREA_NAME,
-- 	REGION_NAME,
-- 	TERRITORY_CODE,
-- 	JOB_NUMBER,
-- 	DEPOSIT_METHOD_TYPE,
-- 	ACCOUNT_NAME,
-- 	LIFETOUCH_ID,
-- 	COMMISSION_TYPE,
-- 	BATCH_NUMBER,
-- 	DEPOSIT_AMOUNT,
-- 	DEPOSIT_DATE,
-- 	BANK_ACCOUNT_CODE,
-- 	CREATE_DATE,
-- 	AUDIT_CREATED_BY,
-- 	PHOTOGRAPHER_ID,
-- 	POSTING_ERROR_MESSAGE,
-- 	DAYS_OUTSTANDING)

-- /*$$SNPS_START_KEYSNP$CRDWG_TABLESNP$CRTABLE_NAME=unposted_territory_deposit.csvSNP$CRLOAD_FILE=/dw_export/PROD/unposted_territory_deposit.csvSNP$CRFILE_FORMAT=DSNP$CRFILE_SEP_FIELD=0x002cSNP$CRFILE_SEP_LINE=0x000D0x000ASNP$CRFILE_FIRST_ROW=0SNP$CRFILE_ENC_FIELD="SNP$CRFILE_DEC_SEP=SNP$CRSNP$CRDWG_COLSNP$CRCOL_NAME=COUNTRY_NAMESNP$CRTYPE_NAME=STRINGSNP$CRORDER=1SNP$CRLENGTH=50SNP$CRPRECISION=50SNP$CRSNP$CRDWG_COLSNP$CRCOL_NAME=COMPANY_NAMESNP$CRTYPE_NAME=STRINGSNP$CRORDER=2SNP$CRLENGTH=50SNP$CRPRECISION=50SNP$CRSNP$CRDWG_COLSNP$CRCOL_NAME=AREA_NAMESNP$CRTYPE_NAME=STRINGSNP$CRORDER=3SNP$CRLENGTH=50SNP$CRPRECISION=50SNP$CRSNP$CRDWG_COLSNP$CRCOL_NAME=REGION_NAMESNP$CRTYPE_NAME=STRINGSNP$CRORDER=4SNP$CRLENGTH=50SNP$CRPRECISION=50SNP$CRSNP$CRDWG_COLSNP$CRCOL_NAME=TERRITORY_CODESNP$CRTYPE_NAME=STRINGSNP$CRORDER=5SNP$CRLENGTH=50SNP$CRPRECISION=50SNP$CRSNP$CRDWG_COLSNP$CRCOL_NAME=JOB_NUMBERSNP$CRTYPE_NAME=STRINGSNP$CRORDER=6SNP$CRLENGTH=255SNP$CRPRECISION=255SNP$CRSNP$CRDWG_COLSNP$CRCOL_NAME=DEPOSIT_METHOD_TYPESNP$CRTYPE_NAME=STRINGSNP$CRORDER=7SNP$CRLENGTH=255SNP$CRPRECISION=255SNP$CRSNP$CRDWG_COLSNP$CRCOL_NAME=ACCOUNT_NAMESNP$CRTYPE_NAME=STRINGSNP$CRORDER=8SNP$CRLENGTH=255SNP$CRPRECISION=255SNP$CRSNP$CRDWG_COLSNP$CRCOL_NAME=LIFETOUCH_IDSNP$CRTYPE_NAME=STRINGSNP$CRORDER=9SNP$CRLENGTH=50SNP$CRPRECISION=50SNP$CRSNP$CRDWG_COLSNP$CRCOL_NAME=COMMISSION_TYPESNP$CRTYPE_NAME=STRINGSNP$CRORDER=10SNP$CRLENGTH=255SNP$CRPRECISION=255SNP$CRSNP$CRDWG_COLSNP$CRCOL_NAME=BATCH_NUMBERSNP$CRTYPE_NAME=STRINGSNP$CRORDER=11SNP$CRLENGTH=255SNP$CRPRECISION=255SNP$CRSNP$CRDWG_COLSNP$CRCOL_NAME=DEPOSIT_AMOUNTSNP$CRTYPE_NAME=STRINGSNP$CRORDER=12SNP$CRLENGTH=50SNP$CRPRECISION=50SNP$CRSNP$CRDWG_COLSNP$CRCOL_NAME=DEPOSIT_DATESNP$CRTYPE_NAME=DATESNP$CRORDER=13SNP$CRLENGTH=50SNP$CRPRECISION=50SNP$CRSNP$CRDWG_COLSNP$CRCOL_NAME=BANK_ACCOUNT_CODESNP$CRTYPE_NAME=STRINGSNP$CRORDER=14SNP$CRLENGTH=255SNP$CRPRECISION=255SNP$CRSNP$CRDWG_COLSNP$CRCOL_NAME=CREATE_DATESNP$CRTYPE_NAME=DATESNP$CRORDER=15SNP$CRLENGTH=50SNP$CRPRECISION=50SNP$CRSNP$CRDWG_COLSNP$CRCOL_NAME=AUDIT_CREATED_BYSNP$CRTYPE_NAME=STRINGSNP$CRORDER=16SNP$CRLENGTH=255SNP$CRPRECISION=255SNP$CRSNP$CRDWG_COLSNP$CRCOL_NAME=PHOTOGRAPHER_IDSNP$CRTYPE_NAME=STRINGSNP$CRORDER=17SNP$CRLENGTH=4SNP$CRPRECISION=4SNP$CRSNP$CRDWG_COLSNP$CRCOL_NAME=POSTING_ERROR_MESSAGESNP$CRTYPE_NAME=STRINGSNP$CRORDER=18SNP$CRLENGTH=255SNP$CRPRECISION=255SNP$CRSNP$CRDWG_COLSNP$CRCOL_NAME=DAYS_OUTSTANDINGSNP$CRTYPE_NAME=STRINGSNP$CRORDER=19SNP$CRLENGTH=50SNP$CRPRECISION=50SNP$CR$$SNPS_END_KEY*/


-- &


-- /*-----------------------------------------------*/
-- /* TASK No. 6 */
-- /* Insert new rows */

-- /* SOURCE CODE */


-- select 	
-- 	ACT_UNPOSTED.COUNTRY_NAME	   COUNTRY_NAME,
-- 	ACT_UNPOSTED.COMPANY_NAME	   COMPANY_NAME,
-- 	ACT_UNPOSTED.AREA_NAME	   AREA_NAME,
-- 	ACT_UNPOSTED.REGION_NAME	   REGION_NAME,
-- 	ACT_UNPOSTED.TERRITORY_CODE	   TERRITORY_CODE,
-- 	ACT_UNPOSTED.JOB_NUMBER	   JOB_NUMBER,
-- 	ACT_UNPOSTED.DEPOSIT_METHOD_TYPE	   DEPOSIT_METHOD_TYPE,
-- 	ACT_UNPOSTED.ACCOUNT_NAME	   ACCOUNT_NAME,
-- 	ACT_UNPOSTED.LIFETOUCH_ID	   LIFETOUCH_ID,
-- 	ACT_UNPOSTED.COMMISSION_TYPE	   COMMISSION_TYPE,
-- 	ACT_UNPOSTED.BATCH_NUMBER	   BATCH_NUMBER,
-- 	ACT_UNPOSTED.DEPOSIT_AMOUNT	   DEPOSIT_AMOUNT,
-- 	ACT_UNPOSTED.DEPOSIT_DATE	   DEPOSIT_DATE,
-- 	ACT_UNPOSTED.BANK_ACCOUNT_CODE	   BANK_ACCOUNT_CODE,
-- 	ACT_UNPOSTED.CREATE_DATE	   CREATE_DATE,
-- 	ACT_UNPOSTED.AUDIT_CREATED_BY	   AUDIT_CREATED_BY,
-- 	ACT_UNPOSTED.PHOTOGRAPHER_ID	   PHOTOGRAPHER_ID,
-- 	ACT_UNPOSTED.POSTING_ERROR_MESSAGE	   POSTING_ERROR_MESSAGE,
-- 	ACT_UNPOSTED.DAYS_OUTSTANDING	   DAYS_OUTSTANDING
-- from	RAX_APP_USER.ACTUATE_UNPOSTEDTERRDEP_STAGE   ACT_UNPOSTED
-- where	
-- 	(1=1)	
	





-- /* Order the output by the UD1, UD2, UD3, UD4, UD5, UD6 Fields. */



-- &

-- /* TARGET CODE */
-- insert into "/dw_export/PROD/unposted_territory_deposit.csv"
-- (
-- 	COUNTRY_NAME,
-- 	COMPANY_NAME,
-- 	AREA_NAME,
-- 	REGION_NAME,
-- 	TERRITORY_CODE,
-- 	JOB_NUMBER,
-- 	DEPOSIT_METHOD_TYPE,
-- 	ACCOUNT_NAME,
-- 	LIFETOUCH_ID,
-- 	COMMISSION_TYPE,
-- 	BATCH_NUMBER,
-- 	DEPOSIT_AMOUNT,
-- 	DEPOSIT_DATE,
-- 	BANK_ACCOUNT_CODE,
-- 	CREATE_DATE,
-- 	AUDIT_CREATED_BY,
-- 	PHOTOGRAPHER_ID,
-- 	POSTING_ERROR_MESSAGE,
-- 	DAYS_OUTSTANDING
                     
-- )
-- values 
-- (
-- 	:COUNTRY_NAME,
-- 	:COMPANY_NAME,
-- 	:AREA_NAME,
-- 	:REGION_NAME,
-- 	:TERRITORY_CODE,
-- 	:JOB_NUMBER,
-- 	:DEPOSIT_METHOD_TYPE,
-- 	:ACCOUNT_NAME,
-- 	:LIFETOUCH_ID,
-- 	:COMMISSION_TYPE,
-- 	:BATCH_NUMBER,
-- 	:DEPOSIT_AMOUNT,
-- 	:DEPOSIT_DATE,
-- 	:BANK_ACCOUNT_CODE,
-- 	:CREATE_DATE,
-- 	:AUDIT_CREATED_BY,
-- 	:PHOTOGRAPHER_ID,
-- 	:POSTING_ERROR_MESSAGE,
-- 	:DAYS_OUTSTANDING
                     
-- )
-- /*$$SNPS_START_KEYSNP$CRDWG_TABLESNP$CRTABLE_NAME=unposted_territory_deposit.csvSNP$CRLOAD_FILE=/dw_export/PROD/unposted_territory_deposit.csvSNP$CRFILE_FORMAT=DSNP$CRFILE_SEP_FIELD=0x002cSNP$CRFILE_SEP_LINE=0x000D0x000ASNP$CRFILE_FIRST_ROW=0SNP$CRFILE_ENC_FIELD="SNP$CRFILE_DEC_SEP=SNP$CRSNP$CRDWG_COLSNP$CRCOL_NAME=COUNTRY_NAMESNP$CRTYPE_NAME=STRINGSNP$CRORDER=1SNP$CRLENGTH=50SNP$CRPRECISION=50SNP$CRSNP$CRDWG_COLSNP$CRCOL_NAME=COMPANY_NAMESNP$CRTYPE_NAME=STRINGSNP$CRORDER=2SNP$CRLENGTH=50SNP$CRPRECISION=50SNP$CRSNP$CRDWG_COLSNP$CRCOL_NAME=AREA_NAMESNP$CRTYPE_NAME=STRINGSNP$CRORDER=3SNP$CRLENGTH=50SNP$CRPRECISION=50SNP$CRSNP$CRDWG_COLSNP$CRCOL_NAME=REGION_NAMESNP$CRTYPE_NAME=STRINGSNP$CRORDER=4SNP$CRLENGTH=50SNP$CRPRECISION=50SNP$CRSNP$CRDWG_COLSNP$CRCOL_NAME=TERRITORY_CODESNP$CRTYPE_NAME=STRINGSNP$CRORDER=5SNP$CRLENGTH=50SNP$CRPRECISION=50SNP$CRSNP$CRDWG_COLSNP$CRCOL_NAME=JOB_NUMBERSNP$CRTYPE_NAME=STRINGSNP$CRORDER=6SNP$CRLENGTH=255SNP$CRPRECISION=255SNP$CRSNP$CRDWG_COLSNP$CRCOL_NAME=DEPOSIT_METHOD_TYPESNP$CRTYPE_NAME=STRINGSNP$CRORDER=7SNP$CRLENGTH=255SNP$CRPRECISION=255SNP$CRSNP$CRDWG_COLSNP$CRCOL_NAME=ACCOUNT_NAMESNP$CRTYPE_NAME=STRINGSNP$CRORDER=8SNP$CRLENGTH=255SNP$CRPRECISION=255SNP$CRSNP$CRDWG_COLSNP$CRCOL_NAME=LIFETOUCH_IDSNP$CRTYPE_NAME=STRINGSNP$CRORDER=9SNP$CRLENGTH=50SNP$CRPRECISION=50SNP$CRSNP$CRDWG_COLSNP$CRCOL_NAME=COMMISSION_TYPESNP$CRTYPE_NAME=STRINGSNP$CRORDER=10SNP$CRLENGTH=255SNP$CRPRECISION=255SNP$CRSNP$CRDWG_COLSNP$CRCOL_NAME=BATCH_NUMBERSNP$CRTYPE_NAME=STRINGSNP$CRORDER=11SNP$CRLENGTH=255SNP$CRPRECISION=255SNP$CRSNP$CRDWG_COLSNP$CRCOL_NAME=DEPOSIT_AMOUNTSNP$CRTYPE_NAME=STRINGSNP$CRORDER=12SNP$CRLENGTH=50SNP$CRPRECISION=50SNP$CRSNP$CRDWG_COLSNP$CRCOL_NAME=DEPOSIT_DATESNP$CRTYPE_NAME=DATESNP$CRORDER=13SNP$CRLENGTH=50SNP$CRPRECISION=50SNP$CRSNP$CRDWG_COLSNP$CRCOL_NAME=BANK_ACCOUNT_CODESNP$CRTYPE_NAME=STRINGSNP$CRORDER=14SNP$CRLENGTH=255SNP$CRPRECISION=255SNP$CRSNP$CRDWG_COLSNP$CRCOL_NAME=CREATE_DATESNP$CRTYPE_NAME=DATESNP$CRORDER=15SNP$CRLENGTH=50SNP$CRPRECISION=50SNP$CRSNP$CRDWG_COLSNP$CRCOL_NAME=AUDIT_CREATED_BYSNP$CRTYPE_NAME=STRINGSNP$CRORDER=16SNP$CRLENGTH=255SNP$CRPRECISION=255SNP$CRSNP$CRDWG_COLSNP$CRCOL_NAME=PHOTOGRAPHER_IDSNP$CRTYPE_NAME=STRINGSNP$CRORDER=17SNP$CRLENGTH=4SNP$CRPRECISION=4SNP$CRSNP$CRDWG_COLSNP$CRCOL_NAME=POSTING_ERROR_MESSAGESNP$CRTYPE_NAME=STRINGSNP$CRORDER=18SNP$CRLENGTH=255SNP$CRPRECISION=255SNP$CRSNP$CRDWG_COLSNP$CRCOL_NAME=DAYS_OUTSTANDINGSNP$CRTYPE_NAME=STRINGSNP$CRORDER=19SNP$CRLENGTH=50SNP$CRPRECISION=50SNP$CR$$SNPS_END_KEY*/



-- /*-----------------------------------------------*/
-- /* TASK No. 7 */

-- chmod 644 /dw_export/PROD/unposted_territory_deposit.csv

-- &


-- /*-----------------------------------------------*/
-- /* TASK No. 8 */

-- mv /dw_export/PROD/unposted_territory_deposit.csv /dw_export/PROD/finance/unposted_territory_deposit/unposted_territory_deposit:v_actuate_sysdate.csv

-- &


-- /*-----------------------------------------------*/
