select	
	YFS_STATISTICS_DETAIL.STATISTICS_DETAIL_KEY	   C1_STATISTICS_DETAIL_KEY,
	YFS_STATISTICS_DETAIL.START_TIME_STAMP	   C2_START_TIME_STAMP,
	YFS_STATISTICS_DETAIL.END_TIME_STAMP	   C3_END_TIME_STAMP,
	YFS_STATISTICS_DETAIL.SERVER_NAME	   C4_SERVER_NAME,
	YFS_STATISTICS_DETAIL.SERVER_ID	   C5_SERVER_ID,
	YFS_STATISTICS_DETAIL.HOSTNAME	   C6_HOSTNAME,
	YFS_STATISTICS_DETAIL.SERVICE_NAME	   C7_SERVICE_NAME,
	YFS_STATISTICS_DETAIL.SERVICE_TYPE	   C8_SERVICE_TYPE,
	YFS_STATISTICS_DETAIL.CONTEXT_NAME	   C9_CONTEXT_NAME,
	YFS_STATISTICS_DETAIL.STATISTIC_NAME	   C10_STATISTIC_NAME,
	YFS_STATISTICS_DETAIL.STATISTIC_VALUE	   C11_STATISTIC_VALUE,
	YFS_STATISTICS_DETAIL.CREATEUSERID	   C12_CREATEUSERID,
	YFS_STATISTICS_DETAIL.MODIFYUSERID	   C13_MODIFYUSERID,
	YFS_STATISTICS_DETAIL.CREATEPROGID	   C14_CREATEPROGID,
	YFS_STATISTICS_DETAIL.MODIFYPROGID	   C15_MODIFYPROGID,
	YFS_STATISTICS_DETAIL.CREATETS	   C16_CREATETS,
	YFS_STATISTICS_DETAIL.MODIFYTS	   C17_MODIFYTS,
	YFS_STATISTICS_DETAIL.LOCKID	   C18_LOCKID,
	TRUNC(YFS_STATISTICS_DETAIL.START_TIME_STAMP)	   C19_START_DATE,
	TRUNC(YFS_STATISTICS_DETAIL.END_TIME_STAMP)	   C20_END_DATE
from	<schema_name>.YFS_STATISTICS_DETAIL   YFS_STATISTICS_DETAIL
where	(1=1)
And (YFS_STATISTICS_DETAIL.CREATETS >= TO_DATE(SUBSTR(:v_cdc_load_date, 1, 19), 'YYYY-MM-DD HH24:MI:SS')  - :v_cdc_oms_overlap
)
