DECLARE create_query CLOB;  
   BEGIN  
      BEGIN  
         EXECUTE IMMEDIATE 'drop table RAX_APP_USER.C$_0OMS3_ST_DTL_STG purge';  
      EXCEPTION  
         WHEN OTHERS THEN NULL;  
      END;  
      create_query := 'create table RAX_APP_USER.C$_0OMS3_ST_DTL_STG
(
	C1_STATISTICS_DETAIL_KEY	CHAR(24) NULL,
	C2_START_TIME_STAMP	DATE NULL,
	C3_END_TIME_STAMP	DATE NULL,
	C4_SERVER_NAME	VARCHAR2(100) NULL,
	C5_SERVER_ID	VARCHAR2(100) NULL,
	C6_HOSTNAME	VARCHAR2(100) NULL,
	C7_SERVICE_NAME	VARCHAR2(100) NULL,
	C8_SERVICE_TYPE	VARCHAR2(40) NULL,
	C9_CONTEXT_NAME	VARCHAR2(80) NULL,
	C10_STATISTIC_NAME	VARCHAR2(80) NULL,
	C11_STATISTIC_VALUE	NUMBER(15,2) NULL,
	C12_CREATEUSERID	VARCHAR2(40) NULL,
	C13_MODIFYUSERID	VARCHAR2(40) NULL,
	C14_CREATEPROGID	VARCHAR2(40) NULL,
	C15_MODIFYPROGID	VARCHAR2(40) NULL,
	C16_CREATETS	DATE NULL,
	C17_MODIFYTS	DATE NULL,
	C18_LOCKID	NUMBER(5) NULL,
	C19_START_DATE	DATE NULL,
	C20_END_DATE	DATE NULL
)';  
      EXECUTE IMMEDIATE create_query;  
   END;  