GRANT SELECT, INSERT, UPDATE, DELETE ON ODS_APP_USER.KREPORT_DATA_FEED TO RAX_APP_USER; -- in ODS_APP_USER

CREATE TABLE RAX_APP_USER.KREPORT_DATA_FEED AS SELECT * FROM ODS_APP_USER.KREPORT_DATA_FEED; -- in RAX_APP_USER