DECLARE  
  create_query CLOB;  
BEGIN  
  BEGIN  
    EXECUTE IMMEDIATE 'drop table RAX_APP_USER.C$_0STG_VISUAL_MERCH ';  
  EXCEPTION  
    WHEN OTHERS THEN  
      IF SQLCODE != -942 THEN  
        RAISE;  
      END IF;  
  END;  
  
  create_query := 'create table RAX_APP_USER.C$_0STG_VISUAL_MERCH(C1_REVISION_NO	NUMBER(5) NULL,C2_VISUAL_MERCH_KEY	CHAR(24) NULL,C3_VISUAL_MERCH_NAME	VARCHAR2(128) NULL,C4_VISUAL_MERCH_PAYMENT_MODE	VARCHAR2(31) NULL,C5_STATUS	CHAR(15) NULL,C6_MODIFYTS	DATE NULL,C7_MODIFYUSERID	VARCHAR2(40) NULL,C8_CREATETS	DATE NULL,C9_CREATEUSERID	VARCHAR2(40) NULL,C10_MODIFYPROGID	VARCHAR2(40) NULL,C11_VISUAL_MERCH_DESCRIPTION	VARCHAR2(128) NULL,C12_CREATEPROGID	VARCHAR2(40) NULL,C13_VISUAL_MERCH_ID	CHAR(24) NULL,C14_LOCKID	NUMBER(5) NULL)';  
  
  EXECUTE IMMEDIATE create_query;  
END;  

