SELECT     AUTO_ADD_ID       
,AUDIT_CREATE_DATE
,AUDIT_CREATED_BY  
,AUDIT_MODIFIED_BY   
,AUDIT_MODIFY_DATE  
,BUSINESS_KEY   
,ADD_TO_ORDER_TYPE   
,ADDED_ON_EVENT    
,DISCOUNT_PERCENT   
,ITEM_DESC   
,ITEMID      
,LOCKID       
,LOOK_NO   
,VM_ID      
,ENABLE      
,QUANTITY   
,APO_OVERRIDE_KEY  
,FULFILLMENT_TYPE   
  FROM <schema_name>.AUTO_ADD
 WHERE AUDIT_MODIFY_DATE >= TO_DATE(SUBSTR(:v_cdc_load_date, 1, 19), 'YYYY-MM-DD HH24:MI:SS')  - 1