select	
	PC.CREATETS	   C1_CREATETS,
	PC.CREATEUSERID	   C2_CREATEUSERID,
	PC.MODIFYPROGID	   C3_MODIFYPROGID,
	PC.PRICING_CONTEXT_REF	   C4_PRICING_CONTEXT_REF,
	PC.VISUAL_MERCH_KEY	   C5_VISUAL_MERCH_KEY,
	PC.CREATEPROGID	   C6_CREATEPROGID,
	PC.PRICING_CONTEXT_ID	   C7_PRICING_CONTEXT_ID,
	PC.PRICING_CONTEXT_TYPE	   C8_PRICING_CONTEXT_TYPE,
	PC.LOCKID	   C9_LOCKID,
	PC.VM_PRICING_CONTEXT_KEY	   C10_VM_PRICING_CONTEXT_KEY,
	PC.MODIFYTS	   C11_MODIFYTS,
	PC.MODIFYUSERID	   C12_MODIFYUSERID
from	<schema_name>.LT_VM_PRICING_CONTEXT   PC
where	(1=1)