select	
	OLS_DEFAULT_ATTRIBUTE.OLS_DEFAULT_ATTRIBUTE_ID	   C1_OLS_DEFAULT_ATTRIBUTE_ID,
	OLS_DEFAULT_ATTRIBUTE.NAME	   C2_NAME,
	OLS_DEFAULT_ATTRIBUTE.VALUE	   C3_VALUE,
	OLS_DEFAULT_ATTRIBUTE.OLS_DEFAULT_ID	   C4_OLS_DEFAULT_ID,
	OLS_DEFAULT_ATTRIBUTE.AUDIT_CREATE_DATE	   C5_AUDIT_CREATE_DATE,
	OLS_DEFAULT_ATTRIBUTE.AUDIT_CREATED_BY	   C6_AUDIT_CREATED_BY,
	OLS_DEFAULT_ATTRIBUTE.AUDIT_MODIFIED_BY	   C7_AUDIT_MODIFIED_BY,
	OLS_DEFAULT_ATTRIBUTE.AUDIT_MODIFY_DATE	   C8_AUDIT_MODIFY_DATE
from	<schema_name>.OLS_DEFAULT_ATTRIBUTE   OLS_DEFAULT_ATTRIBUTE
where	(1=1)
And (OLS_DEFAULT_ATTRIBUTE.AUDIT_MODIFY_DATE  >= TO_DATE(SUBSTR(:v_cdc_load_date, 1, 19), 'YYYY-MM-DD HH24:MI:SS')  - 1
)