select	
	BC.CREATETS	   C1_CREATETS,
	BC.CREATEUSERID	   C2_CREATEUSERID,
	BC.MODIFYPROGID	   C3_MODIFYPROGID,
	BC.VISUAL_MERCH_KEY	   C4_VISUAL_MERCH_KEY,
	BC.CREATEPROGID	   C5_CREATEPROGID,
	BC.VM_BUSINESS_CONTEXT_KEY	   C6_VM_BUSINESS_CONTEXT_KEY,
	BC.LOCKID	   C7_LOCKID,
	BC.VM_BUSINESS_CONTEXT_NAME	   C8_VM_BUSINESS_CONTEXT_NAME,
	BC.ENTRY_MODE	   C9_ENTRY_MODE,
	BC.MODIFYTS	   C10_MODIFYTS,
	BC.MODIFYUSERID	   C11_MODIFYUSERID
from	<schema_name>.LT_VM_BUSINESS_CONTEXT   BC
where	(1=1)