SELECT     VM_ID
,AUDIT_CREATE_DATE  
,AUDIT_CREATED_BY 
,AUDIT_MODIFIED_BY 
,AUDIT_MODIFY_DATE 
,BUSINESS_KEY 
,LOCKID 
,REVISION_NO
,STATUS 
,VISUAL_MERCH_DESCRIPTION
,VISUAL_MERCH_NAME
,VISUAL_MERCH_PAYMENT_MODE
,USE_SUBJECT_IMAGES 
,CLICK_SELECTION 
,CAMERA_POSE_SET 
,CAMERA_POSE_SET_DESC
,CAMERA_PROGRAM_CODE  
,CAMERA_TYPE
,EXTEND_PRE_PICTURE_DAY_PRICING 
,PHOTOGRAPH_NON_BUYERS 
,PREPAY_PAY_ONLY_ON_MLT 
  FROM <schema_name>.visual_merchandise
 WHERE AUDIT_MODIFY_DATE >= TO_DATE(SUBSTR(:v_cdc_load_date, 1, 19), 'YYYY-MM-DD HH24:MI:SS')  - 1