select	
	OLS_DEFAULT.OLS_DEFAULT_ID	   C1_OLS_DEFAULT_ID,
	OLS_DEFAULT.ORDER_TYPE	   C2_ORDER_TYPE,
	OLS_DEFAULT.SKU_ID	   C3_SKU_ID,
	OLS_DEFAULT.APO_ID	   C4_APO_ID,
	OLS_DEFAULT.AUDIT_CREATE_DATE	   C5_AUDIT_CREATE_DATE,
	OLS_DEFAULT.AUDIT_CREATED_BY	   C6_AUDIT_CREATED_BY,
	OLS_DEFAULT.AUDIT_MODIFIED_BY	   C7_AUDIT_MODIFIED_BY,
	OLS_DEFAULT.AUDIT_MODIFY_DATE	   C8_AUDIT_MODIFY_DATE
from	<schema_name>.OLS_DEFAULT   OLS_DEFAULT
where	(1=1)
And (OLS_DEFAULT.AUDIT_MODIFY_DATE >= TO_DATE(SUBSTR(:v_cdc_load_date, 1, 19), 'YYYY-MM-DD HH24:MI:SS')  - 1
)