select
LOOK_LAYOUT_THEME_ASSOC_ID
,AUDIT_CREATE_DATE
,AUDIT_CREATED_BY
,AUDIT_MODIFIED_BY
,AUDIT_MODIFY_DATE 
,BUSINESS_KEY  
,LOCKID 
,LOOK_LAYOUT_THEMEID
,LOOK_NO
,VM_ID
,IS_DEFAULT
FROM <schema_name>.LOOK_LAYOUT_THEME_ASSOC
 WHERE AUDIT_MODIFY_DATE >= TO_DATE(SUBSTR(:v_cdc_load_date, 1, 19), 'YYYY-MM-DD HH24:MI:SS')  - 1