select	
	VM.REVISION_NO	   C1_REVISION_NO,
	VM.VISUAL_MERCH_KEY	   C2_VISUAL_MERCH_KEY,
	VM.VISUAL_MERCH_NAME	   C3_VISUAL_MERCH_NAME,
	VM.VISUAL_MERCH_PAYMENT_MODE	   C4_VISUAL_MERCH_PAYMENT_MODE,
	VM.STATUS	   C5_STATUS,
	VM.MODIFYTS	   C6_MODIFYTS,
	VM.MODIFYUSERID	   C7_MODIFYUSERID,
	VM.CREATETS	   C8_CREATETS,
	VM.CREATEUSERID	   C9_CREATEUSERID,
	VM.MODIFYPROGID	   C10_MODIFYPROGID,
	VM.VISUAL_MERCH_DESCRIPTION	   C11_VISUAL_MERCH_DESCRIPTION,
	VM.CREATEPROGID	   C12_CREATEPROGID,
	VM.VISUAL_MERCH_ID	   C13_VISUAL_MERCH_ID,
	VM.LOCKID	   C14_LOCKID
from	<schema_name>.LT_VISUAL_MERCH   VM
where	(1=1)
And (VM.MODIFYTS >= TO_DATE(SUBSTR(:v_cdc_load_date, 1, 19), 'YYYY-MM-DD HH24:MI:SS')  -:v_cdc_oms_overlap)