/*-----------------------------------------------*/
/* TASK No. 8 */
/* Insert new rows */

/* SOURCE CODE */


select 	
	ACTUATE_JAF_JOBSTATUS.TERRITORY_CODE	   TERRITORY_CODE,
	ACTUATE_JAF_JOBSTATUS.TERRITORY_NAME	   TERRITORY_NAME,
	ACTUATE_JAF_JOBSTATUS.REGION_NAME	   REGION_NAME,
	ACTUATE_JAF_JOBSTATUS.AREA_NAME	   AREA_NAME,
	ACTUATE_JAF_JOBSTATUS.COMPANY_NAME	   COMPANY_NAME,
	ACTUATE_JAF_JOBSTATUS.COUNTRY_NAME	   COUNTRY_NAME,
	ACTUATE_JAF_JOBSTATUS.JOB_NBR	   JOB_NBR,
	ACTUATE_JAF_JOBSTATUS.MARKETING_CODE	   MARKETING_CODE,
	ACTUATE_JAF_JOBSTATUS.LIFETOUCH_ID	   LIFETOUCH_ID,
	ACTUATE_JAF_JOBSTATUS.AMS_BUSINESS_UNIT_NAME	   AMS_BUSINESS_UNIT_NAME,
	ACTUATE_JAF_JOBSTATUS.SUBTERRITORYCODE	   SUBTERRITORYCODE,
	ACTUATE_JAF_JOBSTATUS.ACCOUNT_NAME	   ACCOUNT_NAME,
	ACTUATE_JAF_JOBSTATUS.ADDRESS_LINE_1	   ADDRESS_LINE_1,
	ACTUATE_JAF_JOBSTATUS.CITY	   CITY,
	ACTUATE_JAF_JOBSTATUS.STATE	   STATE,
	ACTUATE_JAF_JOBSTATUS.POSTAL_CODE	   POSTAL_CODE,
	ACTUATE_JAF_JOBSTATUS.COUNTY	   COUNTY,
	ACTUATE_JAF_JOBSTATUS.DISTRICT_NAME	   DISTRICT_NAME,
	ACTUATE_JAF_JOBSTATUS.SELLING_METHOD_NAME	   SELLING_METHOD_NAME,
	ACTUATE_JAF_JOBSTATUS.PLANT_CODE	   PLANT_CODE,
	ACTUATE_JAF_JOBSTATUS.PHOTOGRAPHY_DATE	   PHOTOGRAPHY_DATE,
	ACTUATE_JAF_JOBSTATUS.SHIP_DATE	   SHIP_DATE,
	ACTUATE_JAF_JOBSTATUS.CMSN_STATUS_CODE	   CMSN_STATUS_CODE,
	ACTUATE_JAF_JOBSTATUS.GROSSCASH	   GROSSCASH,
	ACTUATE_JAF_JOBSTATUS.SCHOOLCOMM	   SCHOOLCOMM,
	ACTUATE_JAF_JOBSTATUS.SALESTAXAMT	   SALESTAXAMT,
	ACTUATE_JAF_JOBSTATUS.CASHRETAINEDAMT	   CASHRETAINEDAMT,
	ACTUATE_JAF_JOBSTATUS.EXPECTEDCASHAMT	   EXPECTEDCASHAMT,
	ACTUATE_JAF_JOBSTATUS.CHARGEBACKAMT	   CHARGEBACKAMT,
	ACTUATE_JAF_JOBSTATUS.SHIPPEDPACKAGEQTY	   SHIPPEDPACKAGEQTY,
	ACTUATE_JAF_JOBSTATUS.PAIDPACKAGEQTY	   PAIDPACKAGEQTY,
	ACTUATE_JAF_JOBSTATUS.SHOTQTY	   SHOTQTY,
	ACTUATE_JAF_JOBSTATUS.TERRITORYCMSNAMT	   TERRITORYCMSNAMT,
	ACTUATE_JAF_JOBSTATUS.TERRITORYEARNINGSAMT	   TERRITORYEARNINGSAMT,
	ACTUATE_JAF_JOBSTATUS.XNOPURCHASEQTY	   XNOPURCHASEQTY,
	ACTUATE_JAF_JOBSTATUS.PROOF_POSES	   PROOF_POSES,
	ACTUATE_JAF_JOBSTATUS.PROOF_QTY	   PROOF_QTY,
	ACTUATE_JAF_JOBSTATUS.SUB_PROGRAM_NAME	   SUB_PROGRAM_NAME
from	RAX_APP_USER.ACTUATE_JAF_JOBSTATUS   ACTUATE_JAF_JOBSTATUS
where	
	(1=1)	
	




