DECLARE create_query CLOB;  
   BEGIN  
      BEGIN  
         EXECUTE IMMEDIATE 'drop table rax_app_user.layout';  
      EXCEPTION  
         WHEN OTHERS THEN NULL;  
      END;  
      create_query := 'CREATE TABLE rax_app_user.layout
(
LAYOUT_ID NUMBER
,AUDIT_CREATE_DATE DATE
,AUDIT_CREATED_BY VARCHAR2(255)
,AUDIT_MODIFIED_BY VARCHAR2(255)
,AUDIT_MODIFY_DATE DATE
,CONTENT_AUTHOR	VARCHAR2(255)
,CONTENT_DATE_CREATED DATE
,DESCRIPTION	VARCHAR2(255)
,EXTERNAL_KEY NUMBER
,LAYOUT_FILE_PATH_NAME VARCHAR2(512)
,NAME	VARCHAR2(255)
,PROVIDER_ID	VARCHAR2(255)
,REQUIREMENT_FILE_NAME	VARCHAR2(255)
,SCHEMA_VERSION	VARCHAR2(100)
,STATUS_TYPE	VARCHAR2(255)
,VOCABULARY_TYPE	VARCHAR2(255)
,LAYOUT_THEME_ID NUMBER
)
';  
      EXECUTE IMMEDIATE create_query;  
   END;  