select 
	ID ,
	InternalID ,
	UserID ,
	MachineName ,
	OrderNumber ,
	Company ,
	Contact ,
	Address1 ,
	Address2 ,
	Address3 ,
	City ,
	State ,
	Zip ,
	Country ,
	ServiceCode ,
	PlainTextService ,
	Shipper ,
	ShipDate ,
	ConsigneeReference ,
	PaymentTerms ,
	SatDelFlag ,
	ResDelFlag ,
	CODFlag ,
	CODAmt ,
	InsAmt ,
	AdditionalHandlingCharge,
	Dimensions ,
	Weight ,
	NumberofPallets ,
	NumberofPackages ,
	SigReqFlag ,
	MiscRef1 ,
	MiscRef2 ,
	MiscRef3 ,
	MiscRef4 ,
	MiscRef5 ,
	cast(TrackingNumber as varchar) as TrackingNumber ,
	Base ,
	Discount ,
	Special ,
	FuelSurcharge ,
	Total ,
	ErrMsg ,
	Status ,
	AltKey ,
	Winner ,
	Override ,
	ProcessDate ,
	TransitTime ,
	WriteBack ,
	TransmittingStatus ,
	scac ,
	boln ,
	class ,
	com_desc ,
	special_inst ,
	nmfc_item ,
	nmfc_sub ,
	ltl_ctns ,
	pkg_cost ,
	DimH ,
	DimL ,
	DimW ,
	Void_ID ,
	MbtDate,
	pkg_type ,
	TNT ,
	[Zone] ,
	Resolved ,
	Pickup_dt ,
	Delivery_dt
	from <schema_name>.dbo.ShipHeader s 
where s.ShipDate >=  DATEADD(DAY,-3,CONVERT(DATETIME,(SUBSTRING(:v_cdc_load_date,1,19)),121))