/* TASK No. 1 */

/* SELECT STATEMENT FOUND, CHECK ODI TASK NO. 1 */




/*-----------------------------------------------*/
/* TASK No. 2 */
/* drop report table */
BEGIN
  EXECUTE IMMEDIATE 'drop table RAX_APP_USER.PPS_UNSHIPPED_WOB_STG';
EXCEPTION
  WHEN OTHERS THEN
   IF SQLCODE != -942 THEN
     RAISE;
   END IF;
END;


-- drop table RAX_APP_USER.PPS_UNSHIPPED_WOB_STG

&


/*-----------------------------------------------*/
/* TASK No. 3 */
/* create report table */

CREATE TABLE RAX_APP_USER.PPS_UNSHIPPED_WOB_STG AS
SELECT
WOB.LAB,
APO.SCHOOL_YEAR, 
T.FISCAL_YEAR,
T.WEEK_NUMBER AS CALENDAR_WEEK,
T.SAT_PRODUCTION_WEEK_NUMBER PRODUCTION_WEEK,
P.PROGRAM_NAME,
SP.SUB_PROGRAM_NAME,
APO.TERRITORY_CODE,
E.SELLING_METHOD,
WOB.APO_ID,
WOB.APO_DESC,
WOB.SHIP_TO,
WOB.EVENT_REF_ID,
WOB.PRODUCT_LINE,
WOB.MANUFACTURER_FAMILY,
WOB.MANUFACTURER_ITEM,
WOB.MANUFACTURER_ITEM_DESC,
WOB.BATCH_ID,
WOB.ORDER_NO,
E.PLANT_RECEIPT_DATE,
WOB.BATCH_CREATE_DATE,
WOB.READY_FULLFILLMENT_DATE,
WOB.REQ_SHIP_DATE,
WOB.SHIPPED_DATE,
WOB.STATUS,
WOB.STATUS_DESC,
WOB.CURRENT_STATUS_DATE,
CASE WHEN
     (WOB.SHIPPED_DATE IS NULL AND WOB.REQ_SHIP_DATE < TRUNC(SYSDATE))
     THEN 'Delayed'
     WHEN 
     (WOB.SHIPPED_DATE IS NULL AND WOB.REQ_SHIP_DATE>TRUNC(SYSDATE) AND ROUND(WOB.REQ_SHIP_DATE - SYSDATE,2) BETWEEN 0 AND 2)
     THEN  '1-2 Day to Fulfill'
     WHEN 
     (WOB.SHIPPED_DATE IS NULL AND WOB.REQ_SHIP_DATE>TRUNC(SYSDATE) AND ROUND(WOB.REQ_SHIP_DATE - SYSDATE,2) >2)
     THEN  '>2 Day to Fulfill' END TIME_FACTOR,
WOB.MANUFACTURING_BATCH_ID,
WOB.TOTAL_WORK_ORDERS,
WOB.TOTAL_PAGES,
WOB.TOTAL_ORDERS,
WOB.BUYER_COUNT,
WOB.MAKEOVER_REASON,
WOB.REASON_DESC
FROM  ODS_OWN.WORK_ORDER_BATCH WOB,          
      ODS_OWN.APO,
      ODS_OWN.EVENT E,
      ODS_OWN.SUB_PROGRAM SP,
      ODS_OWN.PROGRAM P,      
      MART.TIME T                       
      WHERE 1 = 1      
      AND WOB.EVENT_OID = E.EVENT_OID(+)
      AND WOB.APO_OID = APO.APO_OID(+)
      AND APO.SUB_PROGRAM_OID = SP.SUB_PROGRAM_OID(+)   
      AND SP.PROGRAM_OID = P.PROGRAM_OID                
      AND TRUNC(WOB.BATCH_CREATE_DATE) = T.DATE_KEY                
      AND WOB.STATUS_DESC NOT IN ('Cancelled')
      AND WOB.SHIPPED_DATE IS NULL
      AND APO.TERRITORY_CODE NOT IN ('LN')   
      AND APO.SCHOOL_YEAR >= (SELECT FISCAL_YEAR - 1 FROM MART.TIME WHERE DATE_KEY = trunc(sysdate))
ORDER BY WOB.LAB,WOB.BATCH_CREATE_DATE



&


/*-----------------------------------------------*/
/* TASK No. 4 */
/* Grants1 */

GRANT SELECT ON RAX_APP_USER.PPS_UNSHIPPED_WOB_STG  TO MART_USER



&


/*-----------------------------------------------*/
/* TASK No. 5 */
/* Grants2 */

GRANT SELECT ON RAX_APP_USER.PPS_UNSHIPPED_WOB_STG  TO ODS_SELECT_ROLE

&


/*-----------------------------------------------*/
