---

pipeline:
  name: lt_event_payment_fact_dag
  description: Event Payment Fact Package
  schedule: "0 */4 * * *"
  tags:
    - lifetouch
    - event_payment_fact
  task_groups:

    - name: EVENT_PAYMENT_FACT_ODI_Transformation
      description: ODI SQL Transformation Logic for EVENT PAYMENT FACT
      pre_sql:
        v_cdc_load_date: dags/sql/pre_sql.sql
      default_args:
        v_cdc_overlap: 0.02083333333
      tasks: 
        - description: load event_payment_fact subpackage
          type: oracle_sql
          script_location: dags/sql/LOAD_EVENT_PAYMENT_FACT_PKG/LOAD_EVENT_PAYMENT_FACT_PKG.sql
          args:
            v_cdc_load_table_name: EVENT_PAYMENT_FACT
            v_cdc_oms_overlap: 0.02083333333
        
