select	
	ACCOUNT_PROGRAM_OCCURENCE.ACCOUNT_PROGRAM_OCCURENCE_ID	   C1_ACCOUNT_PROGRAM_OCCURENCE_I,
	ACCOUNT_PROGRAM_OCCURENCE.APO_ID	   C2_APO_ID,
	ACCOUNT_PROGRAM_OCCURENCE.ACCOUNT_NAME	   C3_ACCOUNT_NAME,
	ACCOUNT_PROGRAM_OCCURENCE.ACTIVE	   C4_ACTIVE,
	ACCOUNT_PROGRAM_OCCURENCE.CREATEDATE	   C5_CREATEDATE,
	ACCOUNT_PROGRAM_OCCURENCE.CREATEDBY	   C6_CREATEDBY,
	ACCOUNT_PROGRAM_OCCURENCE.MODIFIEDBY	   C7_MODIFIEDBY,
	ACCOUNT_PROGRAM_OCCURENCE.MODIFYDATE	   C8_MODIFYDATE,
	ACCOUNT_PROGRAM_OCCURENCE.COUNTRY_CODE	   C9_COUNTRY_CODE,
	ACCOUNT_PROGRAM_OCCURENCE.CURRENCY_CODE	   C10_CURRENCY_CODE,
	ACCOUNT_PROGRAM_OCCURENCE.VISION_JOB_NUMBER	   C11_VISION_JOB_NUMBER,
	ACCOUNT_PROGRAM_OCCURENCE.LOCK_ID	   C12_LOCK_ID,
	ACCOUNT_PROGRAM_OCCURENCE.PROGRAM_TYPE	   C13_PROGRAM_TYPE,
	ACCOUNT_PROGRAM_OCCURENCE.YEAR_ENDING	   C14_YEAR_ENDING,
	ACCOUNT_PROGRAM_OCCURENCE.LOCKED	   C15_LOCKED,
	ACCOUNT_PROGRAM_OCCURENCE.SERVICE_CENTER_NAME	   C16_SERVICE_CENTER_NAME
from	<schema_name>.ACCOUNT_PROGRAM_OCCURENCE   ACCOUNT_PROGRAM_OCCURENCE
where	(1=1)
And (ACCOUNT_PROGRAM_OCCURENCE.MODIFYDATE >= ( TO_DATE(SUBSTR(:v_cdc_load_date, 1, 19), 'YYYY-MM-DD HH24:MI:SS')  - :v_cdc_oms_overlap))

