select	
	ORDER_BATCH.ORDER_BATCH_ID	   C1_ORDER_BATCH_ID,
	ORDER_BATCH.APO_ID	   C2_APO_ID,
	ORDER_BATCH.CREATEDATE	   C3_CREATEDATE,
	ORDER_BATCH.CREATEDBY	   C4_CREATEDBY,
	ORDER_BATCH.MODIFIEDBY	   C5_MODIFIEDBY,
	ORDER_BATCH.MODIFYDATE	   C6_MODIFYDATE,
	ORDER_BATCH.OMS_BATCH_ID	   C7_OMS_BATCH_ID,
	ORDER_BATCH.COUNTRY_CODE	   C8_COUNTRY_CODE,
	ORDER_BATCH.EXPECTED_ORDERS	   C9_EXPECTED_ORDERS,
	ORDER_BATCH.BATCH_SEQ	   C10_BATCH_SEQ,
	ORDER_BATCH.STATUS	   C11_STATUS,
	ORDER_BATCH.EXCEPTION_COUNT	   C12_EXCEPTION_COUNT,
	ORDER_BATCH.LAST_EXCEPTION_MESSAGE	   C13_LAST_EXCEPTION_MESSAGE,
	ORDER_BATCH.SHIP_TYPE	   C14_SHIP_TYPE,
	ORDER_BATCH.PROCESS_TYPE	   C15_PROCESS_TYPE,
	ORDER_BATCH.ACCOUNT_PROGRAM_OCCURENCE_ID	   C16_ACCOUNT_PROGRAM_OCCURENCE_
from	<schema_name>.ORDER_BATCH   ORDER_BATCH
where	(1=1)
And (ORDER_BATCH.MODIFYDATE >= ( TO_DATE(SUBSTR(:v_cdc_load_date, 1, 19), 'YYYY-MM-DD HH24:MI:SS')  - :v_cdc_oms_overlap))

