select	
	LT_BATCH_SHIP_PROP.BATCH_SHIP_PROP_KEY	   C1_BATCH_SHIP_PROP_KEY,
	LT_BATCH_SHIP_PROP.BATCH_ID	   C2_BATCH_ID,
	LT_BATCH_SHIP_PROP.SHIP_NODE	   C3_SHIP_NODE,
	LT_BATCH_SHIP_PROP.SHIP_PROP_ID	   C4_SHIP_PROP_ID,
	LT_BATCH_SHIP_PROP.STATUS	   C5_STATUS,
	LT_BATCH_SHIP_PROP.CREATETS	   C6_CREATETS,
	LT_BATCH_SHIP_PROP.MODIFYTS	   C7_MODIFYTS,
	LT_BATCH_SHIP_PROP.CREATEUSERID	   C8_CREATEUSERID,
	LT_BATCH_SHIP_PROP.MODIFYUSERID	   C9_MODIFYUSERID,
	LT_BATCH_SHIP_PROP.CREATEPROGID	   C10_CREATEPROGID,
	LT_BATCH_SHIP_PROP.MODIFYPROGID	   C11_MODIFYPROGID,
	LT_BATCH_SHIP_PROP.LOCKID	   C12_LOCKID
from	<schema_name>.LT_BATCH_SHIP_PROP   LT_BATCH_SHIP_PROP
where	(1=1)
And (LT_BATCH_SHIP_PROP.MODIFYTS >= ( TO_DATE(SUBSTR(:v_cdc_load_date, 1, 19), 'YYYY-MM-DD HH24:MI:SS')  - :v_cdc_oms_overlap))
