select	
	EVENT.EVENT_ID	   C1_EVENT_ID,
	to_date(to_char(EVENT.CREATEDATE,'YYYY-MM-DD hh24:mi:ss'), 'YYYY-MM-DD hh24:mi:ss')	   C2_CREATEDATE,
	EVENT.CREATEDBY	   C3_CREATEDBY,
	EVENT.MODIFIEDBY	   C4_MODIFIEDBY,
	to_date(to_char(EVENT.MODIFYDATE,'YYYY-MM-DD hh24:mi:ss'), 'YYYY-MM-DD hh24:mi:ss')	   C5_MODIFYDATE,
	to_date(substr(to_char(EVENT.EVENT_DATE),1,18),'DD-MON-YY HH24:MI:SS')	   C6_EVENT_DATE,
	EVENT.EVENT_REF_ID	   C7_EVENT_REF_ID,
	EVENT.EVENT_STATUS	   C8_EVENT_STATUS,
	EVENT.IS_XORDERS_CREATED	   C9_IS_XORDERS_CREATED,
	EVENT.ACCOUNT_PROGRAM_OCCURENCE_ID	   C10_ACCOUNT_PROGRAM_OCCURENCE_,
	EVENT.IS_STAFF_ORDERS_CREATED	   C11_IS_STAFF_ORDERS_CREATED,
	EVENT.IS_MISSING_XORDERS_CREATED	   C12_IS_MISSING_XORDERS_CREATED,
	EVENT.IS_EVENT_IMAGE_COMPLETED	   C13_IS_EVENT_IMAGE_COMPLETED,
	EVENT.IS_RETAKE_ORDERS_CREATED	   C14_IS_RETAKE_ORDERS_CREATED
from	<schema_name>.EVENT   EVENT