DECLARE create_query CLOB;  
   BEGIN  
      BEGIN  
         EXECUTE IMMEDIATE 'DROP TABLE RAX_APP_USER.C$_0BOC_ACC_PRG_OCCR_STG';  
      EXCEPTION  
         WHEN OTHERS THEN NULL;  
      END;  
      create_query := 'create table RAX_APP_USER.C$_0BOC_ACC_PRG_OCCR_STG ( C1_ACCOUNT_PROGRAM_OCCURENCE_I	NUMBER(19) NULL, C2_APO_ID	VARCHAR2(9) NULL, C3_ACCOUNT_NAME	VARCHAR2(255) NULL, C4_ACTIVE	NUMBER(1) NULL, C5_CREATEDATE	TIMESTAMP(6) NULL, C6_CREATEDBY	VARCHAR2(255) NULL, C7_MODIFIEDBY	VARCHAR2(255) NULL, C8_MODIFYDATE	TIMESTAMP(6) NULL, C9_COUNTRY_CODE	VARCHAR2(6) NULL, C10_CURRENCY_CODE	VARCHAR2(3) NULL, C11_VISION_JOB_NUMBER	VARCHAR2(255) NULL, C12_LOCK_ID	NUMBER(19) NULL, C13_PROGRAM_TYPE	VARCHAR2(255) NULL, C14_YEAR_ENDING	NUMBER(8) NULL, C15_LOCKED	NUMBER(1) NULL, C16_SERVICE_CENTER_NAME	VARCHAR2(20) NULL )';  
      EXECUTE IMMEDIATE create_query;
   END;  