DECLARE create_query CLOB;  
   BEGIN  
      BEGIN  
         EXECUTE IMMEDIATE 'DROP TABLE RAX_APP_USER.C$_0BOC_ORDER_BATCH_STAGE';  
      EXCEPTION  
         WHEN OTHERS THEN NULL;  
      END;  
      create_query := 'create table RAX_APP_USER.C$_0BOC_ORDER_BATCH_STAGE ( C1_ORDER_BATCH_ID	NUMBER(19) NULL, C2_APO_ID	VARCHAR2(255) NULL, C3_CREATEDATE	TIMESTAMP(6) NULL, C4_CREATEDBY	VARCHAR2(255) NULL, C5_MODIFIEDBY	VARCHAR2(255) NULL, C6_MODIFYDATE	TIMESTAMP(6) NULL, C7_OMS_BATCH_ID	VARCHAR2(255) NULL, C8_COUNTRY_CODE	VARCHAR2(255) NULL, C9_EXPECTED_ORDERS	VARCHAR2(255) NULL, C10_BATCH_SEQ	NUMBER(19) NULL, C11_STATUS	VARCHAR2(255) NULL, C12_EXCEPTION_COUNT	NUMBER(10) NULL, C13_LAST_EXCEPTION_MESSAGE	VARCHAR2(255) NULL, C14_SHIP_TYPE	VARCHAR2(255) NULL, C15_PROCESS_TYPE	VARCHAR2(255) NULL, C16_ACCOUNT_PROGRAM_OCCURENCE_	NUMBER(19) NULL )';  
      EXECUTE IMMEDIATE create_query;
   END;  