DECLARE create_query CLOB;  
   BEGIN  
      BEGIN  
         EXECUTE IMMEDIATE 'DROP TABLE RAX_APP_USER.C$_0OMS_LT_SHIP_PROP_STG';  
      EXCEPTION  
         WHEN OTHERS THEN NULL;  
      END;  
      create_query := 'create table RAX_APP_USER.C$_0OMS_LT_SHIP_PROP_STG ( C1_BATCH_SHIP_PROP_KEY	CHAR(24) NULL, C2_BATCH_ID	VARCHAR2(20) NULL, C3_SHIP_NODE	CHAR(24) NULL, C4_SHIP_PROP_ID	VARCHAR2(40) NULL, C5_STATUS	VARCHAR2(20) NULL, C6_CREATETS	DATE NULL, C7_MODIFYTS	DATE NULL, C8_CREATEUSERID	VARCHAR2(40) NULL, C9_MODIFYUSERID	VARCHAR2(40) NULL, C10_CREATEPROGID	VARCHAR2(40) NULL, C11_MODIFYPROGID	VARCHAR2(40) NULL, C12_LOCKID	NUMBER(5) NULL )';  
      EXECUTE IMMEDIATE create_query;
   END;  