select	
	TASK.ID	   C1_ID,
	TASK.VERSION	   C2_VERSION,
	TASK.ASSIGNED_TO	   C3_ASSIGNED_TO,
	TASK.CREATED_BY	   C4_CREATED_BY,
	TASK.DATE_CREATED	   C5_DATE_CREATED,
	TASK.DESCRIPTION	   C6_DESCRIPTION,
	TASK.DUE_DATE	   C7_DUE_DATE,
	TASK.DUE_DATE_OFFSET	   C8_DUE_DATE_OFFSET,
	TASK.LAST_UPDATED	   C9_LAST_UPDATED,
	TASK.LID	   C10_LID,
	TASK.NOTE	   C11_NOTE,
	TASK.PARENT_ID	   C12_PARENT_ID,
	TASK.REFERENCE_ID	   C13_REFERENCE_ID,
	TASK.STATUS	   C14_STATUS,
	TASK.TASK_GROUP	   C15_TASK_GROUP,
	TASK.TASK_LEVEL	   C16_TASK_LEVEL,
	TASK.TASK_TYPE	   C17_TASK_TYPE,
	TASK.UPDATED_BY	   C18_UPDATED_BY,
	TASK.TERRITORY_CODE	   C19_TERRITORY_CODE,
	TASK.TASK_CATEGORY	   C20_TASK_CATEGORY,
	TASK.LAST_TASK	   C21_LAST_TASK,
	TASK.TARGET_TAB	   C22_TARGET_TAB,
	TASK.TASK_TEMPLATE_ID	   C23_TASK_TEMPLATE_ID
from	<schema_name>.TASK   TASK
where	(1=1)
And (TASK.LAST_UPDATED >= TO_DATE(SUBSTR(:v_cdc_load_date, 1, 19), 'YYYY-MM-DD HH24:MI:SS')  -:v_cdc_oms_overlap)
