
BEGIN  
   EXECUTE IMMEDIATE 'DROP TABLE RAX_APP_USER.LKP_WOMS_PENDING_COMPS1';  
EXCEPTION  
   WHEN OTHERS THEN  
      IF SQLCODE != -942 THEN  
         RAISE;  
      END IF;  
END;  
&

CREATE TABLE RAX_APP_USER.LKP_WOMS_PENDING_COMPS1
(
 WORK_ORDER_ID NUMBER,
 WOMS_NODE VARCHAR2(50),
 UNDERCLASS_PRODUCT_CODE  VARCHAR2(50)
)
&
CREATE INDEX WOMS_PENDING_COMPS1_IX1 ON RAX_APP_USER.LKP_WOMS_PENDING_COMPS1
(WORK_ORDER_ID,WOMS_NODE)
--LOGGING
--NOPARALLEL
&
CREATE INDEX WOMS_PENDING_COMPS1_IX2 ON RAX_APP_USER.LKP_WOMS_PENDING_COMPS1
(UNDERCLASS_PRODUCT_CODE)
--LOGGING
--NOPARALLEL
&

INSERT INTO RAX_APP_USER.LKP_WOMS_PENDING_COMPS1
SELECT 
DISTINCT WOD.WORK_ORDER_ID,WOD.WOMS_NODE,OMS.UNDERCLASS_PRODUCT_CODE  
FROM
ODS_STAGE.X1_WO_UNSHIPPED_HIST TEMP,
ODS_STAGE.WOMS_WORK_ORDER_DETAIL_STG WOD,
ODS_STAGE.WOMS_ITEM_ID_REFERENCE_STG ITEM,
ODS_STAGE.WOMS_XREF_OMS_PROD_STG OMS,
ODS_STAGE.WOMS_STATUS_STAGE STAT
WHERE 1 = 1
         AND TEMP.WORK_ORDER_ID = WOD.WORK_ORDER_ID  
         AND TEMP.WOMS_NODE  = WOD.WOMS_NODE
         AND WOD.ITEM_ID_REFERENCE_ID = ITEM.ITEM_ID_REFERENCE_ID
         AND ITEM.XREF_OMS_PROD_ID = OMS.XREF_OMS_PROD_ID
         AND WOD.STATUS_ID = STAT.STATUS_ID
         AND WOD.WOMS_NODE = STAT.SOURCE_NODE
         --AND ITEM.ITEM_ID_REFERENCE_ID IN (51,52,53,5)
         --AND WOD.STATUS_ID NOT IN (4,7,8,9,10)
         AND STAT.CODE NOT IN ('CA','LC','LS','SA')
         AND TEMP.MANUAL_DEACTIVATED_FLAG IS NULL
         AND TEMP.CLASS_QTY IS NOT NULL
         AND WOD.ODS_CREATE_DATE >= (SELECT MIN(DATE_KEY) FROM MART.TIME
                                                                   WHERE FISCAL_YEAR = (SELECT FISCAL_YEAR FROM MART.TIME 
                                                                                                            WHERE DATE_KEY = TRUNC(SYSDATE))-1)
             
                                                                                                

&

BEGIN  
   EXECUTE IMMEDIATE 'DROP TABLE RAX_APP_USER.LKP_WOMS_PENDING_COMPS2';  
EXCEPTION  
   WHEN OTHERS THEN  
      IF SQLCODE != -942 THEN  
         RAISE;  
      END IF;  
END;  
&
CREATE TABLE RAX_APP_USER.LKP_WOMS_PENDING_COMPS2
(
 WORK_ORDER_ID NUMBER,
 WOMS_NODE VARCHAR2(50),
 UNDERCLASS_PRODUCT_CODE  VARCHAR2(50)
)
&
CREATE INDEX WOMS_PENDING_COMPS2_IX1 ON RAX_APP_USER.LKP_WOMS_PENDING_COMPS2
(WORK_ORDER_ID,WOMS_NODE)
--LOGGING
--NOPARALLEL
&
CREATE INDEX WOMS_PENDING_COMPS2_IX2 ON RAX_APP_USER.LKP_WOMS_PENDING_COMPS2
(UNDERCLASS_PRODUCT_CODE)
--LOGGING
--NOPARALLEL
&


INSERT INTO RAX_APP_USER.LKP_WOMS_PENDING_COMPS2
SELECT * FROM RAX_APP_USER.LKP_WOMS_PENDING_COMPS1
        WHERE (WORK_ORDER_ID,WOMS_NODE) 
                IN (
                SELECT WORK_ORDER_ID,WOMS_NODE FROM
                (
                SELECT 
                WORK_ORDER_ID,
                WOMS_NODE,
                COUNT(UNDERCLASS_PRODUCT_CODE) 
                FROM    
                RAX_APP_USER.LKP_WOMS_PENDING_COMPS1
                GROUP BY 
                WORK_ORDER_ID,WOMS_NODE
                HAVING COUNT(UNDERCLASS_PRODUCT_CODE) = 1
                ORDER BY WORK_ORDER_ID,WOMS_NODE ASC
                )   
                    )
            AND UNDERCLASS_PRODUCT_CODE IN ('CMP','G08')   
    
&

BEGIN  
   EXECUTE IMMEDIATE 'DROP TABLE RAX_APP_USER.LOOKUP_WOMS_STATUS_HISTORY';  
EXCEPTION  
   WHEN OTHERS THEN  
      IF SQLCODE != -942 THEN  
         RAISE;  
      END IF;  
END;  

&

CREATE TABLE RAX_APP_USER.LOOKUP_WOMS_STATUS_HISTORY
(
 WORK_ORDER_ID                             NUMBER,
 WOMS_NODE                  	                 VARCHAR2(30),
 WORK_ORDER_DETAIL_ID_COUNT  NUMBER,
 STATUS_ID_COUNT                           NUMBER,
 STATUS_ID                                         NUMBER,
 SHIPPED                    	                  VARCHAR2(1),
 ODS_CREATE_DATE                           DATE,
 ODS_MODIFY_DATE                           DATE
)

&

INSERT INTO RAX_APP_USER.LOOKUP_WOMS_STATUS_HISTORY
SELECT /*+ PARALLEL(A,12)*/
         WORK_ORDER_ID
        ,WOMS_NODE
        ,SUM(WORK_ORDER_DETAIL_ID_COUNT) WORK_ORDER_DETAIL_ID_COUNT
        ,SUM(STATUS_ID_COUNT) STATUS_ID_COUNT
        ,8
        ,NULL       
        ,TRUNC(SYSDATE)
        ,TRUNC(SYSDATE)
  FROM     
     (
        SELECT 
        TEMP.WORK_ORDER_ID
       ,TEMP.WOMS_NODE
       ,COUNT(*) OVER(PARTITION BY TEMP.WORK_ORDER_ID,TEMP.WOMS_NODE,WOD.WORK_ORDER_DETAIL_ID) WORK_ORDER_DETAIL_ID_COUNT
       ,(SELECT 
         COUNT(SH.WORK_ORDER_DETAIL_ID) 
         FROM 
         ODS_STAGE.WOMS_STATUS_HISTORY_STG SH
         WHERE 1 = 1
         AND SH.WORK_ORDER_ID IS NULL
         AND SH.STATUS_ID = 8
         AND WOD.WORK_ORDER_DETAIL_ID = SH.WORK_ORDER_DETAIL_ID   
         AND WOD.WOMS_NODE = SH.WOMS_NODE
         AND SH.ODS_CREATE_DATE  >= (SELECT MIN(DATE_KEY) FROM MART.TIME
                                           WHERE FISCAL_YEAR = (SELECT FISCAL_YEAR FROM MART.TIME 
                                                               WHERE DATE_KEY = TRUNC(SYSDATE))-1)         
         )AS STATUS_ID_COUNT 
       ,8
       ,NULL       
       ,TRUNC(SYSDATE)
       ,TRUNC(SYSDATE)
    FROM 
    ODS_STAGE.X1_WO_UNSHIPPED_HIST TEMP,
    ODS_STAGE.WOMS_WORK_ORDER_DETAIL_STG WOD,
    ODS_STAGE.WOMS_ITEM_ID_REFERENCE_STG I,
    ODS_STAGE.WOMS_XREF_OMS_PROD_STG X    
    WHERE  1 = 1 
    AND TEMP.WORK_ORDER_ID = WOD.WORK_ORDER_ID
    AND TEMP.WOMS_NODE = WOD.WOMS_NODE
    AND WOD.ITEM_ID_REFERENCE_ID = I.ITEM_ID_REFERENCE_ID
    AND I.XREF_OMS_PROD_ID = X.XREF_OMS_PROD_ID
    AND I.PRODUCIBLE_FLAG = 1
    AND WOD.DEACTIVATED_DATE IS NULL
    AND TEMP.MANUAL_DEACTIVATED_FLAG IS NULL
    AND WOD.ODS_CREATE_DATE >= (SELECT MIN(DATE_KEY) FROM MART.TIME
                                              WHERE FISCAL_YEAR = (SELECT FISCAL_YEAR FROM MART.TIME 
                                                               WHERE DATE_KEY = TRUNC(SYSDATE))-1)
 --AND TEMP.WORK_ORDER_ID = '7894347'                                                                  
)A
         
         GROUP BY 
             WORK_ORDER_ID
            ,WOMS_NODE
            ,8
            ,NULL       
            ,TRUNC(SYSDATE)
            ,TRUNC(SYSDATE)

&

UPDATE RAX_APP_USER.LOOKUP_WOMS_STATUS_HISTORY
SET SHIPPED = 'Y'
WHERE work_order_detail_id_count = status_id_count
&
MERGE INTO ODS_STAGE.X1_WO_UNSHIPPED_HIST TGT
    USING  
    (  
    SELECT 
    DISTINCT
    X.WORK_ORDER_ID,X.WOMS_NODE,
    CASE WHEN T.WORK_ORDER_ID IS NOT NULL THEN  'Y' ELSE NULL END PENDING_CLASS_PRODUCT,
    CASE WHEN SH.SHIPPED IS NOT NULL THEN 'Y' ELSE NULL END MANUALLY_SHIPPED
    FROM 
      ODS_STAGE.X1_WO_UNSHIPPED_HIST X,
     (SELECT * FROM RAX_APP_USER.LKP_WOMS_PENDING_COMPS2 
        WHERE (WORK_ORDER_ID,WOMS_NODE) 
                IN (
                SELECT WORK_ORDER_ID,WOMS_NODE FROM
                (
                SELECT WORK_ORDER_ID,WOMS_NODE,COUNT(UNDERCLASS_PRODUCT_CODE) 
                FROM 
                RAX_APP_USER.LKP_WOMS_PENDING_COMPS2     
                GROUP BY WORK_ORDER_ID,WOMS_NODE
                HAVING COUNT(UNDERCLASS_PRODUCT_CODE) = 1
                ORDER BY WORK_ORDER_ID,WOMS_NODE ASC
                )   
                    )
            AND UNDERCLASS_PRODUCT_CODE IN ('CMP','G08')   
    ) T,    
    RAX_APP_USER.LOOKUP_WOMS_STATUS_HISTORY SH
    WHERE 1 = 1
    AND X.WORK_ORDER_ID = T.WORK_ORDER_ID(+)
    AND X.WOMS_NODE = T.WOMS_NODE(+)
    AND X.WORK_ORDER_ID = SH.WORK_ORDER_ID(+)
    AND X.WOMS_NODE = SH.WOMS_NODE(+)
    AND X.MANUAL_DEACTIVATED_FLAG IS NULL
    ORDER BY 2 ASC           
    )SRC
      ON (TGT.WORK_ORDER_ID = SRC.WORK_ORDER_ID 
             AND TGT.WOMS_NODE = SRC.WOMS_NODE          
         )          
  WHEN MATCHED THEN
    UPDATE 
     SET  
          TGT.PENDING_CLASS_PRODUCT =  SRC.PENDING_CLASS_PRODUCT,
          TGT.MANUALLY_SHIPPED = SRC.MANUALLY_SHIPPED,
          TGT.ODS_MODIFY_DATE = SYSDATE          
&
UPDATE  ODS_STAGE.X1_WO_UNSHIPPED_HIST_X T1
   SET (T1.PENDING_CLASS_PRODUCT) = ( SELECT DISTINCT T2.PENDING_CLASS_PRODUCT 
                                      FROM ODS_STAGE.X1_WO_UNSHIPPED_HIST T2
                                      WHERE T1.WORK_ORDER_ID = T2.WORK_ORDER_ID
                                      AND T1.LID = T2.LID
                                      AND T1.WOMS_NODE = T2.WOMS_NODE
                                      AND T2.PENDING_CLASS_PRODUCT IS NOT NULL                        
                                    )
 WHERE EXISTS (
    SELECT 1
      FROM ODS_STAGE.X1_WO_UNSHIPPED_HIST T2
     WHERE T1.WORK_ORDER_ID = T2.WORK_ORDER_ID
           AND T1.LID = T2.LID
           AND T1.WOMS_NODE = T2.WOMS_NODE
           AND T2.PENDING_CLASS_PRODUCT IS NOT NULL
           )
           
           

           
           
&
UPDATE  ODS_STAGE.X1_WO_UNSHIPPED_HIST_X T1
   SET (T1.MANUALLY_SHIPPED) = ( SELECT DISTINCT T2.MANUALLY_SHIPPED 
                                      FROM ODS_STAGE.X1_WO_UNSHIPPED_HIST T2
                                      WHERE T1.WORK_ORDER_ID = T2.WORK_ORDER_ID
                                      AND T1.LID = T2.LID
                                      AND T1.WOMS_NODE = T2.WOMS_NODE
                                      AND T2.MANUALLY_SHIPPED IS NOT NULL                        
                                    )
 WHERE EXISTS (
    SELECT 1
      FROM ODS_STAGE.X1_WO_UNSHIPPED_HIST T2
     WHERE T1.WORK_ORDER_ID = T2.WORK_ORDER_ID
           AND T1.LID = T2.LID
           AND T1.WOMS_NODE = T2.WOMS_NODE
           AND T2.MANUALLY_SHIPPED IS NOT NULL
           )
           
           
           
&


