select 	
	ACTUATE_SRM_CUST_DEPO_STAGE."Territory Code"	   TERRITORY_CODE,
	ACTUATE_SRM_CUST_DEPO_STAGE."Lifetouch ID"	   LIFETOUCH_ID,
	ACTUATE_SRM_CUST_DEPO_STAGE."Account Name"	   ACCOUNT_NAME,
	ACTUATE_SRM_CUST_DEPO_STAGE."APO ID"	   APO_ID,
	ACTUATE_SRM_CUST_DEPO_STAGE."Selling Method"	   SELLING_METHOD,
	ACTUATE_SRM_CUST_DEPO_STAGE."Sub Program"	   SUB_PROGRAM,
	ACTUATE_SRM_CUST_DEPO_STAGE."Event Ref ID"	   EVENT_REF_ID,
	ACTUATE_SRM_CUST_DEPO_STAGE."Photo Date"	   PHOTO_DATE,
	ACTUATE_SRM_CUST_DEPO_STAGE."Ship Date"	   SHIP_DATE,
	ACTUATE_SRM_CUST_DEPO_STAGE."Payment Amount"	   PAYMENT_AMOUNT,
	ACTUATE_SRM_CUST_DEPO_STAGE."Shipped Order Amount"	   SHIPPED_ORDER_AMOUNT,
	ACTUATE_SRM_CUST_DEPO_STAGE."Recognized Revenue"	   RECOGNIZED_REVENUE,
	ACTUATE_SRM_CUST_DEPO_STAGE."Customer Deposits"	   CUSTOMER_DEPOSITS,
	ACTUATE_SRM_CUST_DEPO_STAGE."School Year"	   SCHOOL_YEAR
from	RAX_APP_USER.ACTUATE_SRM_CUST_DEPO_STAGE   ACTUATE_SRM_CUST_DEPO_STAGE
where	
	(1=1)	