select 	
	YITP.BEGIN_DATE	   BEGIN_DATE,
	YITP.END_DATE	   END_DATE,
	YITP.EVENT_REF_ID	   EVENT_REF_ID,
	YITP.PROGRAM	   PROGRAM,
	YITP.TERRITORY_CODE	   TERRITORY_CODE,
	YITP.LID	   LID,
	YITP.ACCOUNT_NAME	   ACCOUNT_NAME,
	YITP.PAYMENT_AMOUNT	   PAYMENT_AMOUNT,
	YITP.PAYMENT_DATE	   PAYMENT_DATE,
	YITP.SCHOOL_YEAR	   SCHOOL_YEAR,
	YITP.BUSINESS_UNIT_NAME	   BUSINESS_UNIT_NAME,
	YITP.PAYMENT_SOURCE	   PAYMENT_SOURCE,
	YITP.PAYMENT_TYPE	   PAYMENT_TYPE,
	YITP.APO_ID	   APO_ID
from	RAX_APP_USER.YEARBOOK_IN_THE_PACK   YITP
where	
	(1=1)	
	





/* Order the output by the UD1, UD2, UD3, UD4, UD5, UD6 Fields. */
 
ORDER BY  SCHOOL_YEAR
, EVENT_REF_ID
, PAYMENT_DATE
, PAYMENT_AMOUNT
