select	
	IMAGESTREAM.IMAGESTREAM_OID	   C1_IMAGESTREAM_OID,
	IMAGESTREAM.LID	   C2_LID,
	IMAGESTREAM.LOCAL_LOCATION	   C3_LOCAL_LOCATION,
	IMAGESTREAM.CENTRAL_LOCATION	   C4_CENTRAL_LOCATION,
	IMAGESTREAM.ACADEMIC_YEAR	   C5_ACADEMIC_YEAR,
	IMAGESTREAM.MD5	   C6_MD5,
	IMAGESTREAM.RETAKE_INDICATOR	   C7_RETAKE_INDICATOR,
	IMAGESTREAM.CREATED_DATE	   C8_CREATED_DATE,
	IMAGESTREAM.STATUS	   C9_STATUS,
	IMAGESTREAM.UPDATED_ON	   C10_UPDATED_ON
from	<schema_name>.IMAGESTREAM   IMAGESTREAM
where	(1=1)
And (NVL(IMAGESTREAM.UPDATED_ON, IMAGESTREAM.CREATED_DATE)>= TO_DATE(SUBSTR(:v_cdc_load_date, 1, 19), 'YYYY-MM-DD HH24:MI:SS')  -:v_cdc_oms_overlap)