select	
	AA.LIFETOUCH_ID	   C1_LIFETOUCH_ID,
	AA.USER_ID	   C2_USER_ID,
	AA.USER_TYPE	   C3_USER_TYPE,
	AA.PROFILE_ID	   C4_PROFILE_ID,
	AA.APP_AUDIT_OID	   C5_APP_AUDIT_OID,
	AA.ACTION	   C6_ACTION,
	AA.ACTION_TIME	   C7_ACTION_TIME
from	<schema_name>.APP_AUDIT   AA
where	(1=1)
And (AA.ACTION_TIME >= TO_DATE(SUBSTR(:v_cdc_load_date, 1, 19), 'YYYY-MM-DD HH24:MI:SS')  -:v_cdc_oms_overlap
)