DECLARE create_query CLOB;  
   BEGIN  
      BEGIN  
         EXECUTE IMMEDIATE 'DROP TABLE RAX_APP_USER.C$_0HP_IMAGESTREAM_STG';  
      EXCEPTION  
         WHEN OTHERS THEN NULL;  
      END;  
      create_query := 'create table RAX_APP_USER.C$_0HP_IMAGESTREAM_STG (C1_IMAGESTREAM_OID	NUMBER NULL,C2_LID	NUMBER NULL,C3_LOCAL_LOCATION	VARCHAR2(500) NULL,C4_CENTRAL_LOCATION	VARCHAR2(500) NULL,C5_ACADEMIC_YEAR	VARCHAR2(20) NULL,C6_MD5	VARCHAR2(32) NULL,C7_RETAKE_INDICATOR	NUMBER NULL,C8_CREATED_DATE	DATE NULL,C9_STATUS	VARCHAR2(20) NULL,C10_UPDATED_ON	DATE NULL)';
      EXECUTE IMMEDIATE create_query;  
   END;  