DECLARE create_query CLOB;  
   BEGIN  
      BEGIN  
         EXECUTE IMMEDIATE 'DROP TABLE RAX_APP_USER.C$_0STG_APP_AUDIT';  
      EXCEPTION  
         WHEN OTHERS THEN NULL;  
      END;  
      create_query := 'CREATE TABLE RAX_APP_USER.C$_0STG_APP_AUDIT(C1_LIFETOUCH_ID NUMBER NULL,C2_USER_ID VARCHAR2(60) NULL,C3_USER_TYPE VARCHAR2(25) NULL,C4_PROFILE_ID VARCHAR2(60) NULL,C5_APP_AUDIT_OID NUMBER NULL,C6_ACTION VARCHAR2(60) NULL,C7_ACTION_TIME TIMESTAMP(6) NULL)';  
      EXECUTE IMMEDIATE create_query;  
   END;  