CREATE TABLE "RAX_APP_USER"."YB_DOMINO_DRIVER" 
   (	"JOB_NUMBER" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ODS_DATA" ;
  
 
 -- ODS_APP_USER.YB_DOMINO_NULL_QC_LOG definition

CREATE TABLE "RAX_APP_USER"."YB_DOMINO_NULL_QC_LOG" 
   (	"JOB_NUMBER" NUMBER, 
	"EVENT_OID" NUMBER NOT NULL ENABLE, 
	"TRACKING_PID" NUMBER, 
	"IN_DATE" DATE, 
	"QUALITY_CHECK" DATE, 
	"REASON_CATEGORY" VARCHAR2(10), 
	"AREA" VARCHAR2(50), 
	"MATERIAL_CLASS" VARCHAR2(10), 
	"EVENT_TYPE" VARCHAR2(255), 
	"PROCESSED_DATE" DATE, 
	"ODS_CREATE_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ODS_DATA" ;
  
 -- ODS_APP_USER.YB_DOMINO_SET_QC_LOG definition

CREATE TABLE "RAX_APP_USER"."YB_DOMINO_SET_QC_LOG" 
   (	"JOB_NUMBER" NUMBER, 
	"EVENT_OID" NUMBER NOT NULL ENABLE, 
	"TRACKING_PID" NUMBER, 
	"IN_DATE" DATE, 
	"DEPT" VARCHAR2(4), 
	"AREA" VARCHAR2(50), 
	"MATERIAL_CLASS" VARCHAR2(10), 
	"SEQ" NUMBER, 
	"EVENT_TYPE" VARCHAR2(255), 
	"PROCESSED_DATE" DATE, 
	"ODS_CREATE_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ODS_DATA" ;
 
 -- ODS_APP_USER.LPS_LAKE1_DEPT_YB_EXT_STG definition

CREATE TABLE "RAX_APP_USER"."LPS_LAKE1_DEPT_YB_EXT_STG" 
   (	"PLANT" VARCHAR2(50) NOT NULL ENABLE, 
	"DEPT" VARCHAR2(50) NOT NULL ENABLE, 
	"DEPT_DESC" VARCHAR2(50), 
	"AREA" VARCHAR2(50), 
	"ODS_CREATE_DATE" DATE, 
	"ODS_MODIFY_DATE" DATE, 
	 CONSTRAINT "LPS_LAKE1_DEPT_YB_EXT_STG_PKX" PRIMARY KEY ("PLANT", "DEPT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ODS_INDX"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ODS_DATA" ;

CREATE UNIQUE INDEX "RAX_APP_USER"."LPS_LAKE1_DEPT_YB_EXT_STG_PKX" ON "RAX_APP_USER"."LPS_LAKE1_DEPT_YB_EXT_STG" ("PLANT", "DEPT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ODS_INDX" ;

 -- ODS_APP_USER.LPS_LAKE1_DEPT_YB_STG definition

CREATE TABLE "RAX_APP_USER"."LPS_LAKE1_DEPT_YB_STG" 
   (	"PLANT" VARCHAR2(50) NOT NULL ENABLE, 
	"DEPT" VARCHAR2(50) NOT NULL ENABLE, 
	"DEPT_DESC" VARCHAR2(50), 
	"AREA" VARCHAR2(50), 
	"ODS_CREATE_DATE" DATE, 
	"ODS_MODIFY_DATE" DATE, 
	 CONSTRAINT "LPS_LAKE1_DEPT_YB_STG_PKX" PRIMARY KEY ("PLANT", "DEPT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ODS_INDX"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ODS_DATA" ;

CREATE UNIQUE INDEX "RAX_APP_USER"."LPS_LAKE1_DEPT_YB_STG_PKX" ON "RAX_APP_USER"."LPS_LAKE1_DEPT_YB_STG" ("PLANT", "DEPT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ODS_INDX" ;

GRANT SELECT ON "RAX_APP_USER"."LPS_LAKE1_DEPT_YB_STG" TO "ODS_SELECT_USER";
  GRANT SELECT ON "RAX_APP_USER"."LPS_LAKE1_DEPT_YB_STG" TO "ODS_SELECT_ROLE";