---
pipeline:
  name: lt_99_COUNTING_FEE_NEW_PKG_dag
  description: 99_COUNTING_FEE package
  schedule: "30 4 * * 1"
  tags:
    - lifetouch
    - 99_COUNTING_FEE
  task_groups:
    - name: 99_COUNTING_FEE_NEW_PKG_export
      description: drop and recreate table then extract data and load to s3
      export_file_name:
        v_actuate_sysdate: dags/sql/pre_sql/v_actuate_sysdate.sql
      pre_sql:
        v_actuate_sysdate:  dags/sql/pre_sql/v_actuate_sysdate.sql
      tasks:
        - script_location: dags/sql/99_COUNTING_FEE_NEW_PKG/counting_fee_create_tmp.sql
          export_files:
            - extract_query: '99_COUNTING_FEE_NEW_PKG/counting_fee_export.sql'
              export_location: finance/counting_fee_new/counting_fee_new
