select 	
	YEA.EVENT_REF_ID	   EVENT_REF_ID,
	YEA.RECOGNIZED_DATE	   RECOGNIZED_DATE,
	YEA.SALES	   SALES,
	YEA.ACCOUNT_COMMISSION	   ACCOUNT_COMMISSION,
	YEA.CHARGE_BACK	   CHARGE_BACK,
	YEA.TERRITORY_COMMISSION	   TERRITORY_COMMISSION,
	YEA.ORDER_SHIPPING_HANDLING	   ORDER_SHIPPING_HANDLING,
	YEA.WRITE_OFF	   WRITE_OFF,
	YEA.UPDATED_BY	   UPDATED_BY,
	YEA.REASON	   REASON,
	YEA.NOTE	   NOTE,
	YEA.APO_ID	   APO_ID
from	RAX_APP_USER.YEARBOOK_SALESADJUSTMENT_STAGE   YEA
where	
	(1=1)	
	
ORDER BY  EVENT_REF_ID