-- /* TASK No. 1 */

-- /* SELECT STATEMENT FOUND, CHECK ODI TASK NO. 1 */




-- /*-----------------------------------------------*/
-- /* TASK No. 2 */

-- /* SELECT STATEMENT FOUND, CHECK ODI TASK NO. 2 */




-- /*-----------------------------------------------*/
-- /* TASK No. 3 */
-- /* Drop table */

-- drop table rax_app_user.yearbook_tax_exempt_export

-- &


-- /*-----------------------------------------------*/
-- /* TASK No. 4 */
-- /* Create table  */

-- create table rax_app_user.yearbook_tax_exempt_export
-- as
-- SELECT   a.territory_code, a.lifetouch_id, a.apo_id,
--          a.lpip_job_number, e.event_ref_id, acct.account_name,
--          a.contract_received,
--          CASE
--             WHEN a.is_tax_exempt = 1
--                THEN 'True'
--             ELSE 'False'
--          END AS is_tax_exempt,
--          acct.state
--     FROM ods_own.apo a,
--          ods_own.sub_program sp,
--          ods_own.event e,
--          ods_own.ACCOUNT acct,
--          ods_own.organization_vw vw
--    WHERE a.sub_program_oid = sp.sub_program_oid
--      AND a.apo_oid = e.apo_oid
--      AND a.account_oid = acct.account_oid
--      AND a.territory_code = vw.territory_code
--      AND vw.business_unit_name != 'Test Organization'
--      AND sp.sub_program_name = 'Yearbook'
--      AND a.status = 'Active'
--      AND a.school_year = :v_actuate_fiscal_year

-- &


-- /*-----------------------------------------------*/
-- /* TASK No. 5 */
-- /* Generate header */

-- create header	(TERRITORY_CODE,
-- 	LIFETOUCH_ID,
-- 	APO_ID,
-- 	LPIP_JOB_NUMBER,
-- 	EVENT_REF_ID,
-- 	ACCOUNT_NAME,
-- 	CONTRACT_RECEIVED,
-- 	IS_TAX_EXEMPT,
-- 	STATE)

-- /*$$SNPS_START_KEYSNP$CRDWG_TABLESNP$CRTABLE_NAME=YEARBOOK_TAX_EXEMPT.csvSNP$CRLOAD_FILE=/dw_export/PROD/YEARBOOK_TAX_EXEMPT.csvSNP$CRFILE_FORMAT=DSNP$CRFILE_SEP_FIELD=0x002cSNP$CRFILE_SEP_LINE=0x000D0x000ASNP$CRFILE_FIRST_ROW=0SNP$CRFILE_ENC_FIELD="SNP$CRFILE_DEC_SEP=SNP$CRSNP$CRDWG_COLSNP$CRCOL_NAME=TERRITORY_CODESNP$CRTYPE_NAME=STRINGSNP$CRORDER=1SNP$CRLENGTH=50SNP$CRPRECISION=50SNP$CRSNP$CRDWG_COLSNP$CRCOL_NAME=LIFETOUCH_IDSNP$CRTYPE_NAME=STRINGSNP$CRORDER=2SNP$CRLENGTH=50SNP$CRPRECISION=50SNP$CRSNP$CRDWG_COLSNP$CRCOL_NAME=APO_IDSNP$CRTYPE_NAME=STRINGSNP$CRORDER=3SNP$CRLENGTH=50SNP$CRPRECISION=50SNP$CRSNP$CRDWG_COLSNP$CRCOL_NAME=LPIP_JOB_NUMBERSNP$CRTYPE_NAME=STRINGSNP$CRORDER=4SNP$CRLENGTH=50SNP$CRPRECISION=50SNP$CRSNP$CRDWG_COLSNP$CRCOL_NAME=EVENT_REF_IDSNP$CRTYPE_NAME=STRINGSNP$CRORDER=5SNP$CRLENGTH=50SNP$CRPRECISION=50SNP$CRSNP$CRDWG_COLSNP$CRCOL_NAME=ACCOUNT_NAMESNP$CRTYPE_NAME=STRINGSNP$CRORDER=6SNP$CRLENGTH=50SNP$CRPRECISION=50SNP$CRSNP$CRDWG_COLSNP$CRCOL_NAME=CONTRACT_RECEIVEDSNP$CRTYPE_NAME=STRINGSNP$CRORDER=7SNP$CRLENGTH=50SNP$CRPRECISION=50SNP$CRSNP$CRDWG_COLSNP$CRCOL_NAME=IS_TAX_EXEMPTSNP$CRTYPE_NAME=STRINGSNP$CRORDER=8SNP$CRLENGTH=50SNP$CRPRECISION=50SNP$CRSNP$CRDWG_COLSNP$CRCOL_NAME=STATESNP$CRTYPE_NAME=STRINGSNP$CRORDER=9SNP$CRLENGTH=50SNP$CRPRECISION=50SNP$CR$$SNPS_END_KEY*/


-- &


-- /*-----------------------------------------------*/
-- /* TASK No. 6 */
-- /* Insert new rows */

-- /* SOURCE CODE */


-- select 	
-- 	YEARBOOK_TAX_EXEMPT_EXPORT.TERRITORY_CODE	   TERRITORY_CODE,
-- 	YEARBOOK_TAX_EXEMPT_EXPORT.LIFETOUCH_ID	   LIFETOUCH_ID,
-- 	YEARBOOK_TAX_EXEMPT_EXPORT.APO_ID	   APO_ID,
-- 	YEARBOOK_TAX_EXEMPT_EXPORT.LPIP_JOB_NUMBER	   LPIP_JOB_NUMBER,
-- 	YEARBOOK_TAX_EXEMPT_EXPORT.EVENT_REF_ID	   EVENT_REF_ID,
-- 	YEARBOOK_TAX_EXEMPT_EXPORT.ACCOUNT_NAME	   ACCOUNT_NAME,
-- 	YEARBOOK_TAX_EXEMPT_EXPORT.CONTRACT_RECEIVED	   CONTRACT_RECEIVED,
-- 	YEARBOOK_TAX_EXEMPT_EXPORT.IS_TAX_EXEMPT	   IS_TAX_EXEMPT,
-- 	YEARBOOK_TAX_EXEMPT_EXPORT.STATE	   STATE
-- from	RAX_APP_USER.YEARBOOK_TAX_EXEMPT_EXPORT   YEARBOOK_TAX_EXEMPT_EXPORT
-- where	
-- 	(1=1)	
	





-- /* Order the output by the UD1, UD2, UD3, UD4, UD5, UD6 Fields. */



-- &

-- /* TARGET CODE */
-- insert into "/dw_export/PROD/YEARBOOK_TAX_EXEMPT.csv"
-- (
-- 	TERRITORY_CODE,
-- 	LIFETOUCH_ID,
-- 	APO_ID,
-- 	LPIP_JOB_NUMBER,
-- 	EVENT_REF_ID,
-- 	ACCOUNT_NAME,
-- 	CONTRACT_RECEIVED,
-- 	IS_TAX_EXEMPT,
-- 	STATE
                     
-- )
-- values 
-- (
-- 	:TERRITORY_CODE,
-- 	:LIFETOUCH_ID,
-- 	:APO_ID,
-- 	:LPIP_JOB_NUMBER,
-- 	:EVENT_REF_ID,
-- 	:ACCOUNT_NAME,
-- 	:CONTRACT_RECEIVED,
-- 	:IS_TAX_EXEMPT,
-- 	:STATE
                     
-- )
-- /*$$SNPS_START_KEYSNP$CRDWG_TABLESNP$CRTABLE_NAME=YEARBOOK_TAX_EXEMPT.csvSNP$CRLOAD_FILE=/dw_export/PROD/YEARBOOK_TAX_EXEMPT.csvSNP$CRFILE_FORMAT=DSNP$CRFILE_SEP_FIELD=0x002cSNP$CRFILE_SEP_LINE=0x000D0x000ASNP$CRFILE_FIRST_ROW=0SNP$CRFILE_ENC_FIELD="SNP$CRFILE_DEC_SEP=SNP$CRSNP$CRDWG_COLSNP$CRCOL_NAME=TERRITORY_CODESNP$CRTYPE_NAME=STRINGSNP$CRORDER=1SNP$CRLENGTH=50SNP$CRPRECISION=50SNP$CRSNP$CRDWG_COLSNP$CRCOL_NAME=LIFETOUCH_IDSNP$CRTYPE_NAME=STRINGSNP$CRORDER=2SNP$CRLENGTH=50SNP$CRPRECISION=50SNP$CRSNP$CRDWG_COLSNP$CRCOL_NAME=APO_IDSNP$CRTYPE_NAME=STRINGSNP$CRORDER=3SNP$CRLENGTH=50SNP$CRPRECISION=50SNP$CRSNP$CRDWG_COLSNP$CRCOL_NAME=LPIP_JOB_NUMBERSNP$CRTYPE_NAME=STRINGSNP$CRORDER=4SNP$CRLENGTH=50SNP$CRPRECISION=50SNP$CRSNP$CRDWG_COLSNP$CRCOL_NAME=EVENT_REF_IDSNP$CRTYPE_NAME=STRINGSNP$CRORDER=5SNP$CRLENGTH=50SNP$CRPRECISION=50SNP$CRSNP$CRDWG_COLSNP$CRCOL_NAME=ACCOUNT_NAMESNP$CRTYPE_NAME=STRINGSNP$CRORDER=6SNP$CRLENGTH=50SNP$CRPRECISION=50SNP$CRSNP$CRDWG_COLSNP$CRCOL_NAME=CONTRACT_RECEIVEDSNP$CRTYPE_NAME=STRINGSNP$CRORDER=7SNP$CRLENGTH=50SNP$CRPRECISION=50SNP$CRSNP$CRDWG_COLSNP$CRCOL_NAME=IS_TAX_EXEMPTSNP$CRTYPE_NAME=STRINGSNP$CRORDER=8SNP$CRLENGTH=50SNP$CRPRECISION=50SNP$CRSNP$CRDWG_COLSNP$CRCOL_NAME=STATESNP$CRTYPE_NAME=STRINGSNP$CRORDER=9SNP$CRLENGTH=50SNP$CRPRECISION=50SNP$CR$$SNPS_END_KEY*/



-- /*-----------------------------------------------*/
-- /* TASK No. 7 */

-- chmod 644 /dw_export/PROD/YEARBOOK_TAX_EXEMPT.csv

-- &


-- /*-----------------------------------------------*/
-- /* TASK No. 8 */

-- mv /dw_export/PROD/YEARBOOK_TAX_EXEMPT.csv /dw_export/PROD/finance/yearbook_sales/YB_TAX_EXEMPT:v_data_export_run_date.csv

-- &


-- /*-----------------------------------------------*/
