select	
	CT_BATCH.ID	   C1_ID,
	CT_BATCH.BATCH_NAME	   C2_BATCH_NAME,
	CT_BATCH.DATE_CREATED	   C3_DATE_CREATED,
	CT_BATCH.CREATED_BY	   C4_CREATED_BY,
	CT_BATCH.UPDATED_BY	   C5_UPDATED_BY,
	CT_BATCH.LAST_UPDATED	   C6_LAST_UPDATED
from	<schema_name>.CT_BATCH   CT_BATCH
where	(1=1)
And (CT_BATCH.LAST_UPDATED  >= TO_DATE(SUBSTR(:v_cdc_load_date, 1, 19), 'YYYY-MM-DD HH24:MI:SS')  -:v_cdc_oms_overlap)