select	
	CT_SUBJECT.ID	   C1_ID,
	CT_SUBJECT.SUBJECT_OID	   C2_SUBJECT_OID,
	CT_SUBJECT.ALTERNATE_NAMES	   C3_ALTERNATE_NAMES,
	CT_SUBJECT.DATE_CREATED	   C4_DATE_CREATED,
	CT_SUBJECT.CREATED_BY	   C5_CREATED_BY,
	CT_SUBJECT.UPDATED_BY	   C6_UPDATED_BY,
	CT_SUBJECT.LAST_UPDATED	   C7_LAST_UPDATED,
	CT_SUBJECT.APO_ID	   C8_APO_ID,
	CT_SUBJECT.EVENT_REF_ID	   C9_EVENT_REF_ID
from	<schema_name>.CT_SUBJECT   CT_SUBJECT
where	(1=1)
And (NVL(CT_SUBJECT.LAST_UPDATED, CT_SUBJECT.DATE_CREATED) >= TO_DATE(SUBSTR(:v_cdc_load_date, 1, 19), 'YYYY-MM-DD HH24:MI:SS')  -:v_cdc_oms_overlap)