select	
	CT_SUBJECT_BATCH.ID	   C1_ID,
	CT_SUBJECT_BATCH.SUBJECT_ID	   C2_SUBJECT_ID,
	CT_SUBJECT_BATCH.BATCH_ID	   C3_BATCH_ID,
	CT_SUBJECT_BATCH.RETURNED_MATERIAL_TYPE	   C4_RETURNED_MATERIAL_TYPE,
	CT_SUBJECT_BATCH.BARCODE	   C5_BARCODE,
	CT_SUBJECT_BATCH.LAST_UPDATED	   C6_LAST_UPDATED
from	<schema_name>.CT_SUBJECT_BATCH   CT_SUBJECT_BATCH
where	(1=1)
And (CT_SUBJECT_BATCH.LAST_UPDATED  >= TO_DATE(SUBSTR(:v_cdc_load_date, 1, 19), 'YYYY-MM-DD HH24:MI:SS')  -:v_cdc_oms_overlap)