select	
	YB_AUDIT.ID	   C1_ID,
	YB_AUDIT.APO_TAG	   C2_APO_TAG,
	YB_AUDIT.EVENT_REF_ID	   C3_EVENT_REF_ID,
	YB_AUDIT.AUDIT_DATE_CREATED	   C4_AUDIT_DATE_CREATED,
	YB_AUDIT.AUDIT_CREATED_BY	   C5_AUDIT_CREATED_BY,
	YB_AUDIT.PUBLISHED_AUDIT_ID	   C6_PUBLISHED_AUDIT_ID,
	YB_AUDIT.PUBLISHED_ATTRIBUTE_NAME	   C7_PUBLISHED_ATTRIBUTE_NAME,
	YB_AUDIT.PUBLISHED_ATTRIBUTE_VALUE	   C8_PUBLISHED_ATTRIBUTE_VALUE
from	<schema_name>.YB_AUDIT   YB_AUDIT
where	(1=1)
And (YB_AUDIT.AUDIT_DATE_CREATED >= TO_DATE(SUBSTR(:v_cdc_load_date, 1, 19), 'YYYY-MM-DD HH24:MI:SS')  -:v_cdc_overlap)