select	
	YB_OFFERING_CONFIG.ID	   C1_ID,
	YB_OFFERING_CONFIG.OFFERING_ID	   C2_OFFERING_ID,
	TRIM(YB_OFFERING_CONFIG.CONFIG_NAME)	   C3_CONFIG_NAME,
	TRIM(YB_OFFERING_CONFIG.CONFIG_VALUE)	   C4_CONFIG_VALUE,
	YB_OFFERING_CONFIG.DATE_CREATED	   C5_DATE_CREATED,
	TRIM(YB_OFFERING_CONFIG.CREATED_BY)	   C6_CREATED_BY,
	TRIM(YB_OFFERING_CONFIG.TYPE)	   C7_TYPE,
	YB_OFFERING_CONFIG.LAST_UPDATED	   C8_LAST_UPDATED,
	YB_OFFERING_CONFIG.UPDATED_BY	   C9_UPDATED_BY
from	<schema_name>.YB_OFFERING_CONFIG   YB_OFFERING_CONFIG
where	(1=1)
And (YB_OFFERING_CONFIG.LAST_UPDATED  >= TO_DATE(SUBSTR(:v_cdc_load_date, 1, 19), 'YYYY-MM-DD HH24:MI:SS')  -:v_cdc_oms_overlap)