select	
	YB_PRICING.ID	   C1_ID,
	YB_PRICING.OFFERING_ID	   C2_OFFERING_ID,
	YB_PRICING.PRICE_SET_NAME	   C3_PRICE_SET_NAME,
	YB_PRICING.ITEM_ID	   C4_ITEM_ID,
	YB_PRICING.SCHOOL_PRICE	   C5_SCHOOL_PRICE,
	YB_PRICING.CONSUMER_PRICE	   C6_CONSUMER_PRICE,
	YB_PRICING.CHANNEL	   C7_CHANNEL,
	YB_PRICING.DATE_CREATED	   C8_DATE_CREATED,
	YB_PRICING.CREATED_BY	   C9_CREATED_BY,
	YB_PRICING.NO_SHOW_INVOICE	   C10_NO_SHOW_INVOICE,
	YB_PRICING.QUANTITY	   C11_QUANTITY
from	<schema_name>.YB_PRICING   YB_PRICING
where	(1=1)
And (YB_PRICING.DATE_CREATED >= TO_DATE(SUBSTR(:v_cdc_load_date, 1, 19), 'YYYY-MM-DD HH24:MI:SS')  -:v_cdc_overlap)