
                    DECLARE create_query CLOB;  
                    BEGIN  
                        BEGIN  
                            EXECUTE IMMEDIATE 'drop table RAX_APP_USER.C$_0PS_PROMOTION_STG purge';  
                        EXCEPTION  
                            WHEN OTHERS THEN NULL;  
                        END;  
                        create_query := 'create table RAX_APP_USER.C$_0PS_PROMOTION_STG
(
	C1_PROMOTION_ID	NUMBER(19) NULL,
	C2_PROMOTION_CODE	VARCHAR2(255) NULL,
	C3_DESCRIPTION	VARCHAR2(255) NULL,
	C4_ORDER_PRICE_DISCOUNT	NUMBER(8,2) NULL,
	C5_ORDER_PERCENT_DISCOUNT	NUMBER(8,2) NULL,
	C6_ITEM_PRICE_DISCOUNT	NUMBER(8,2) NULL,
	C7_ITEM_PERCENT_DISCOUNT	NUMBER(8,2) NULL,
	C8_START_DATE	DATE NULL,
	C9_END_DATE	DATE NULL,
	C10_ACTIVE	NUMBER(1) NULL,
	C11_SEQUENCE	NUMBER(8) NULL,
	C12_ALGORITHM	NUMBER(19) NULL,
	C13_ALWAYS_APPLIES	NUMBER(1) NULL,
	C14_CHANNEL	NUMBER(19) NULL,
	C15_RESULT_PRODUCT_LINE	NUMBER(19) NULL,
	C16_RESULT_SKU	NUMBER(19) NULL,
	C17_ORDER_MIN_COST	NUMBER(8,2) NULL,
	C18_ORDER_MAX_COST	NUMBER(8,2) NULL,
	C19_NUMBER_REQUIRED_ATTACHED_S	NUMBER(8) NULL,
	C20_MAX_PROMOTION_APPLICATIONS	NUMBER(8) NULL,
	C21_PER_QUANTITY	NUMBER(8,2) NULL,
	C22_SKU_CATEGORY	VARCHAR2(50) NULL,
	C23_DISABLE_ON_CATEGORY_TRIGGE	NUMBER(1) NULL,
	C24_SHIPPING_PRICE_DISCOUNT	NUMBER(19,2) NULL,
	C25_SHIPPING_PERCENT_DISCOUNT	NUMBER(19,2) NULL,
	C26_SHIPPING_METHOD_FOR_DISCOU	VARCHAR2(255) NULL,
	C27_PROMOTION_USE_TYPE	VARCHAR2(32) NULL,
	C28_AUDIT_CREATE_DATE	DATE NULL,
	C29_AUDIT_CREATED_BY	VARCHAR2(255) NULL,
	C30_AUDIT_MODIFY_DATE	DATE NULL,
	C31_AUDIT_MODIFIED_BY	VARCHAR2(255) NULL
)
NOLOGGING';
                        EXECUTE IMMEDIATE create_query;
                    END;  
                    