select	
	PRICE_SET.DESCRIPTION	   C1_DESCRIPTION,
	PRICE_SET.TAX_INCLUSIVE	   C2_TAX_INCLUSIVE,
	PRICE_SET.NAME	   C3_NAME,
	PRICE_SET.AUDIT_CREATE_DATE	   C4_AUDIT_CREATE_DATE,
	PRICE_SET.PRICE_SET_ID	   C5_PRICE_SET_ID,
	PRICE_SET.AUDIT_MODIFY_DATE	   C6_AUDIT_MODIFY_DATE,
	PRICE_SET.CURRENCY	   C7_CURRENCY
from	PS_OWN.PRICE_SET   PRICE_SET
where	(1=1)
And (PRICE_SET.AUDIT_MODIFY_DATE >= TO_DATE(SUBSTR(:v_cdc_load_date, 1, 19), 'YYYY-MM-DD HH24:MI:SS')  - 1)