select	
	STOCK_KEEPING_UNIT.TAX_PRODUCT_CODE	   C1_TAX_PRODUCT_CODE,
	STOCK_KEEPING_UNIT.UPGRADE_TYPE	   C2_UPGRADE_TYPE,
	STOCK_KEEPING_UNIT.SKU_CODE	   C3_SKU_CODE,
	STOCK_KEEPING_UNIT.NAME	   C4_NAME,
	STOCK_KEEPING_UNIT.LOOK_COUNT	   C5_LOOK_COUNT,
	STOCK_KEEPING_UNIT.DESCRIPTION	   C6_DESCRIPTION,
	STOCK_KEEPING_UNIT.PERSONALIZABLE	   C7_PERSONALIZABLE,
	STOCK_KEEPING_UNIT.PRODUCT_LINE	   C8_PRODUCT_LINE,
	STOCK_KEEPING_UNIT.DISPLAY_GROUP	   C9_DISPLAY_GROUP,
	STOCK_KEEPING_UNIT.CATEGORY	   C10_CATEGORY,
	STOCK_KEEPING_UNIT.IMAGE_COUNT	   C11_IMAGE_COUNT
from	PS_OWN.STOCK_KEEPING_UNIT   STOCK_KEEPING_UNIT
where	(1=1)