select	
	PRICE_PROGRAM_PRICE_SET.PRICE_PROGRAM_ID	   C1_PRICE_PROGRAM_ID,
	PRICE_PROGRAM_PRICE_SET.PRICE_SET_ID	   C2_PRICE_SET_ID
from	PS_OWN.PRICE_PROGRAM_PRICE_SET   PRICE_PROGRAM_PRICE_SET, PS_OWN.PRICE_PROGRAM   PRICE_PROGRAM
where	(1=1)
And (PRICE_PROGRAM.AUDIT_MODIFY_DATE >= TO_DATE(SUBSTR(:v_cdc_load_date, 1, 19), 'YYYY-MM-DD HH24:MI:SS')  - 1)
 And (PRICE_PROGRAM_PRICE_SET.PRICE_PROGRAM_ID=PRICE_PROGRAM.PRICE_PROGRAM_ID)