select	
	PRICE_SET_SKU.CHANNEL	   C1_CHANNEL,
	PRICE_SET_SKU.AMOUNT	   C2_AMOUNT,
	PRICE_SET_SKU.PRICE_SET_ID	   C3_PRICE_SET_ID,
	PRICE_SET_SKU.PRODUCT_CODE	   C4_PRODUCT_CODE,
	PRICE_SET_SKU.PRICE_SET_SKU_ID	   C5_PRICE_SET_SKU_ID,
	PRICE_SET_SKU.STOCK_KEEPING_UNIT_ID	   C6_STOCK_KEEPING_UNIT_ID
from	PS_OWN.PRICE_SET_SKU   PRICE_SET_SKU
where	(1=1)