select	
	SU_COUPON_ATTRIBUTE.SU_COUPON_ATTRIBUTE_ID	   C1_SU_COUPON_ATTRIBUTE_ID,
	SU_COUPON_ATTRIBUTE.SU_COUPON_BATCH	   C2_SU_COUPON_BATCH,
	SU_COUPON_ATTRIBUTE.TYPE	   C3_TYPE,
	SU_COUPON_ATTRIBUTE.VALUE	   C4_VALUE
from	PS_OWN.SU_COUPON_ATTRIBUTE   SU_COUPON_ATTRIBUTE
where	(1=1)