select	
	SU_COUPON_BATCH.SU_COUPON_BATCH_ID	   C1_SU_COUPON_BATCH_ID,
	SU_COUPON_BATCH.DESCRIPTION	   C2_DESCRIPTION,
	SU_COUPON_BATCH.BATCH_PREFIX	   C3_BATCH_PREFIX,
	SU_COUPON_BATCH.START_DATE	   C4_START_DATE,
	SU_COUPON_BATCH.END_DATE	   C5_END_DATE,
	SU_COUPON_BATCH.COUPON_COUNT	   C6_COUPON_COUNT,
	SU_COUPON_BATCH.BATCH_TYPE	   C7_BATCH_TYPE,
	SU_COUPON_BATCH.EXPORTED	   C8_EXPORTED,
	SU_COUPON_BATCH.AUDIT_CREATE_DATE	   C9_AUDIT_CREATE_DATE,
	SU_COUPON_BATCH.AUDIT_CREATED_BY	   C10_AUDIT_CREATED_BY,
	SU_COUPON_BATCH.AUDIT_MODIFY_DATE	   C11_AUDIT_MODIFY_DATE,
	SU_COUPON_BATCH.AUDIT_MODIFIED_BY	   C12_AUDIT_MODIFIED_BY,
	SU_COUPON_BATCH.STACKABLE	   C13_STACKABLE
from	PS_OWN.SU_COUPON_BATCH   SU_COUPON_BATCH
where	(1=1)
And (NVL(SU_COUPON_BATCH.AUDIT_MODIFY_DATE, SU_COUPON_BATCH.AUDIT_CREATE_DATE) >= TO_DATE(SUBSTR(:v_cdc_load_date, 1, 19), 'YYYY-MM-DD HH24:MI:SS')  -:v_cdc_overlap)