select	
	SKU_EXTERNAL_REFERENCE.ID	   C1_ID,
	SKU_EXTERNAL_REFERENCE.STOCK_KEEPING_UNIT_ID	   C2_STOCK_KEEPING_UNIT_ID,
	SKU_EXTERNAL_REFERENCE.EXTERNAL_ID	   C3_EXTERNAL_ID,
	SKU_EXTERNAL_REFERENCE.REFERENCE_TYPE	   C4_REFERENCE_TYPE,
	SKU_EXTERNAL_REFERENCE.AUDIT_CREATE_DATE	   C5_AUDIT_CREATE_DATE,
	SKU_EXTERNAL_REFERENCE.AUDIT_MODIFY_DATE	   C6_AUDIT_MODIFY_DATE,
	SKU_EXTERNAL_REFERENCE.EXTERNAL_TYPE	   C7_EXTERNAL_TYPE
from	PS_OWN.SKU_EXTERNAL_REFERENCE   SKU_EXTERNAL_REFERENCE
where	(1=1)