select	
	SU_COUPON_PROMOTION.SU_COUPON_PROMOTION_ID	   C1_SU_COUPON_PROMOTION_ID,
	SU_COUPON_PROMOTION.SU_COUPON_BATCH	   C2_SU_COUPON_BATCH,
	SU_COUPON_PROMOTION.PROMOTION	   C3_PROMOTION
from	PS_OWN.SU_COUPON_PROMOTION   SU_COUPON_PROMOTION
where	(1=1)