select	
	PRICE_PROGRAM.PRICE_PROGRAM_ID	   C1_PRICE_PROGRAM_ID,
	PRICE_PROGRAM.AUDIT_CREATE_DATE	   C2_AUDIT_CREATE_DATE,
	PRICE_PROGRAM.AUDIT_MODIFY_DATE	   C3_AUDIT_MODIFY_DATE,
	PRICE_PROGRAM.DESCRIPTION	   C4_DESCRIPTION,
	PRICE_PROGRAM.NAME	   C5_NAME
from	PS_OWN.PRICE_PROGRAM   PRICE_PROGRAM
where	(1=1)
And (PRICE_PROGRAM.AUDIT_MODIFY_DATE  >= TO_DATE(SUBSTR(:v_cdc_load_date, 1, 19), 'YYYY-MM-DD HH24:MI:SS')  - 1)